### ISSUE TITLE
KRFD-Chicago/Rockford International Airport-ILLINOIS-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#1]

**Comment by Nik-Barbour** [comment]
Redone from scratch -  Note, runways realigned to satellite imagery.

**Comment by Swang007** [comment]
Removed runway hold-short spawn points

**Comment by kilt46** [comment]
Buildings are NOT set into concrete. Need holes to be made and buildings set

**Comment by kilt46** [comment]
Buildings rectified. Jetbridges added

**Comment by kilt46** [comment]
I am working on this airport. Please leave it alone!

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19951331/5ccc552c-a12b-11e6-8dd4-c3f1e529a234.png)

**Comment by Czechoslovaki** [comment]
Sent for OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/82481742-28560580-9aac-11ea-9efa-04212eac7b96.jpg)
