### ISSUE TITLE
EGQS-Lossiemouth Airport-SCOTLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#10]

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22318587/7463230c-e341-11e6-9621-7657da6ffe33.png)

**Comment by MajorTomMueller** [comment]
New apron for P-8

**Comment by MajorTomMueller** [comment]
![EGQS-git](https://user-images.githubusercontent.com/26853210/127690676-b4b7bb48-38f1-4e5e-b2e6-6bfce6f1f8a1.png)
