### ISSUE TITLE
LFOA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#100]

**Comment by kilt46** [comment]
taxiways seem off (see image): http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=LFOA
2 runways on top of each other

**Comment by kilt46** [comment]
Hidden taxiways have been fixed. Gate names standardized. Road lines added for clarity

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21075288/5b08f5ae-bed3-11e6-98dd-bf7bcd369b1b.png)
