### ISSUE TITLE
SEQM-Quito/Mariscal Sucre International Airport-PICHINCHA-ECUADOR

### ISSUE THREAD

**Issue by ProcrastinatorKenny** [InfiniteFlightAirportEditing/Airports#1000]

**Comment by samuelandersson** [comment]
Duplicate; continue here:

https://github.com/InfiniteFlightAirportEditing/Airports/issues/19

**Comment by IFAEpat** [comment]
KORD is O'Hare

**Comment by samuelandersson** [comment]
Here's the issue for Orlando if you need it;

https://github.com/InfiniteFlightAirportEditing/Airports/issues/556

**Comment by KarlLuebs** [comment]
Can I do this one?

**Comment by KarlLuebs** [comment]
Same with this one. Wedding image completely useless. Tried inserting scenery from google earth but no success.

**Comment by dushyants19** [comment]
Up for grabs

**Comment by brunocr98** [comment]
Taking this airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21075544/b06666ec-beda-11e6-8592-bac1e92005a1.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/43671253-123425e8-975c-11e8-904a-0e87f9ebcf90.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/120202137-d92ccf80-c1eb-11eb-9466-ded8535629c1.png)
