### ISSUE TITLE
KCHO

### ISSUE THREAD

**Issue by danielshaw** [InfiniteFlightAirportEditing/Airports#1002]
Redoing Charlottesville-Albemarle Airport

**Comment by dushyants19** [comment]
@danielshaw any progress?

**Comment by danielshaw** [comment]
@dushyants19 I asked to get this airport closed several months ago. There was an alignment issue with Wedbing and WED. No one was able to help me fix it.

**Comment by TristinWoolf** [comment]
If the imagery is not aligning properly with the X-Plane airport file, then that just usually means that the X-Plane file was a bit out of place. No matter what, the WEDBing imagery should be in the proper place, so just adjust everything in the airport over to the proper place.

**Comment by dushyants19** [comment]
So after Tristin's explanation, would you like to continue? :)

**Comment by danielshaw** [comment]
@TristinWoolf I know how to align WED with the layover image. I should've clarified. The main issue came when I was setting the runway length. I input the correct length however the runway on the satellite image was longer.

**Comment by TristinWoolf** [comment]
How much longer than the runway is the imagery? If it's a few feet than it doesn't really matter. You can't let that minute issue stop you from editing the airport. ;)

**Comment by bavAVIA** [comment]
Is this still being worked on? I'm interested.

**Comment by danielshaw** [comment]
I left airport editing several months ago and asked Dush to close this for me. I did my part. :)

**Comment by brunocr98** [comment]
Up for grabs.

**Comment by bavAVIA** [comment]
Mine mwhahahahahaaaa

**Comment by brunocr98** [comment]
Lol 😂

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23822843/b736f504-061a-11e7-9fd0-9b14080b735c.png)
