### ISSUE TITLE
5B7

### ISSUE THREAD

**Issue by hmkane1214** [InfiniteFlightAirportEditing/Airports#1003]
Rensselaer County Airport, Poestenkill, New York. I'll do this one as my first edit.

**Comment by IFAEpat** [comment]
@hmkane1214 needs be invited guys! :)

**Comment by dushyants19** [comment]
@hmkane1214 hows this going

**Comment by hmkane1214** [comment]
Not good. A while in WED stopped running for me. I don't think I have enough storage.

**Comment by dushyants19** [comment]
Up for Grabs

@hmkane1214 you can do it later, if your things start working

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21501131/d0ecc770-cc0a-11e6-9138-4ca0bd213dfe.png)
