### ISSUE TITLE
LHDK

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#1004]
Dunakeszi airport

**Comment by IFAEpat** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17537366/a5229e10-5e61-11e6-8ba0-195ddd6f0589.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17537373/ad2c619a-5e61-11e6-99f8-cc8941515a3d.png)
