### ISSUE TITLE
KALB-Albany International Airport-NEW YORK-USA

### ISSUE THREAD

**Issue by Adam167** [InfiniteFlightAirportEditing/Airports#1005]
I'll do this one

**Comment by Adam167** [comment]
This one is up for grabs

**Comment by lolo31r** [comment]
i will take over

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22091330/5b6ee410-ddbc-11e6-9227-ea6526c03a13.png)

**Comment by ECoops-123** [comment]
I will redo this

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105580598-eecc4d00-5d52-11eb-9c8d-cf7dc53fd59b.png)
