### ISSUE TITLE
KLGB-Long Beach /Daugherty Field/ Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by dushyants19** [InfiniteFlightAirportEditing/Airports#1008]
removin' runways

**Comment by dushyants19** [comment]
Runways removed and spawns corrected to new guidelines

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17651410/17925954-622c-11e6-87c5-4a3a06e624f1.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17651418/1fec361a-622c-11e6-8bbd-6fbfbe7c9a5c.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17651419/27a480e2-622c-11e6-84ae-00cfa24c30a9.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17651422/2fba2430-622c-11e6-802d-b3ab68e901da.png)

**Comment by Czechoslovaki** [comment]
Time to upgrade.

**Comment by Czechoslovaki** [comment]
- Parts of the airport have gone through considerable changes, either needing to be updated or removed
- Pavements are all incorrect or missing
- 8R/26L dimensions have changed

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102611281-404e4000-40f4-11eb-849d-523355597d1a.png)
