### ISSUE TITLE
KSET-St Charles County Smartt Airport-MISSOURI-USA

### ISSUE THREAD

**Issue by owenkreisler** [InfiniteFlightAirportEditing/Airports#1009]
RECYCLED ♻️

**Comment by Tamz00** [comment]
I’ll take this. Will be fun.. probably

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34057512-dceb22f8-e19c-11e7-9928-ff45b3bcb6ed.png)
