### ISSUE TITLE
RKPU

### ISSUE THREAD

**Issue by RiKowalSkipper** [InfiniteFlightAirportEditing/Airports#1011]
I'll do this

**Comment by RiKowalSkipper** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17792762/56c37592-6568-11e6-9f2e-ee1ccfa7a18b.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17792766/5ea73bea-6568-11e6-8135-95d8dce0f34f.png)
