### ISSUE TITLE
MYAX

### ISSUE THREAD

**Issue by TristinWoolf** [InfiniteFlightAirportEditing/Airports#1012]
Spanish Cay Airport

Being redone.

**Comment by TristinWoolf** [comment]
Done. 

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/168501bd4897f525eba3652667fe287c85d66bed)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17720471/c5b4a44e-63e7-11e6-9e4e-34b7e3651cfa.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17720476/cd8cf068-63e7-11e6-8738-aa01c0f1d556.png)
