### ISSUE TITLE
RKJB-Muan International Airport-JEOLLANAM-DO-SOUTH KOREA

### ISSUE THREAD

**Issue by RiKowalSkipper** [InfiniteFlightAirportEditing/Airports#1013]
Will do this

**Comment by kilt46** [comment]
Please modify airport as per attachment
![image](https://cloud.githubusercontent.com/assets/14023167/17912629/5418c9f0-695a-11e6-822e-eae5b2d2f999.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17912636/5ba757e0-695a-11e6-815c-617ab3a83478.png)

**Comment by RiKowalSkipper** [comment]
Redone

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18224931/0bdbc8e0-71ac-11e6-9d3b-a2a64d144f16.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18224932/127b4d06-71ac-11e6-87ae-78a09ce0c1e3.png)
