### ISSUE TITLE
RKPD

### ISSUE THREAD

**Issue by RiKowalSkipper** [InfiniteFlightAirportEditing/Airports#1014]
I'll do this

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17912479/7befb714-6959-11e6-8dde-01003c2b6827.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17912481/83440434-6959-11e6-8cb5-48bf7bbe9f41.png)
