### ISSUE TITLE
EPSC

### ISSUE THREAD

**Issue by KarlLuebs** [InfiniteFlightAirportEditing/Airports#1015]
I'll fully redo this nice airport.

**Comment by IFAEpat** [comment]
You can't be assigned, you're already doing 3 airports.

**Comment by dushyants19** [comment]
@KarlLuebs any progress

**Comment by KarlLuebs** [comment]
Hi Dush, I’m progressing and nearly done. Give me at the very most one week. 

Thanks, Karl

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20859591/8ec24b9e-b928-11e6-95b0-56f358912dbc.png)
