### ISSUE TITLE
CYEG-Edmonton International Airport-ALBERTA-CANADA

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#1016]
Edmonton Int'l Airport. I'll re-do this one.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by kilt46** [comment]
This airport has no ATC info!!!

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18226785/de5db722-71d6-11e6-99b1-2ecdfee3d2e3.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18226787/e78465da-71d6-11e6-9751-880fbc7ea13d.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103105786-a146ae00-45f5-11eb-8122-fbca30107143.png)
