### ISSUE TITLE
SAZS-San Carlos de Bariloche Airport-RIO NEGRO-ARGENTINA

### ISSUE THREAD

**Issue by RiKowalSkipper** [InfiniteFlightAirportEditing/Airports#1019]
RECYCLED ♻️

**Comment by kilt46** [comment]
Please check gates
![image](https://user-images.githubusercontent.com/14023167/27503134-45c0e61a-583f-11e7-8951-24122b9a7213.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27507746-35067f0e-589b-11e7-8f78-989609d1843c.png)
