### ISSUE TITLE
YSCB-Canberra Airport-AUSTRALIAN CAPITAL TERRITORY-AUSTRALIA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#102]

**Comment by Swang007** [comment]
Will add ATIS frequency

**Comment by kilt46** [comment]
Reworking buildings and gates

**Comment by kilt46** [comment]
Airport redrawn

**Comment by Swang007** [comment]
Snap to Vertices

**Comment by Swang007** [comment]
Apron accidentally got deleted last month, should now be fixed

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19409957/e13dc37a-92a5-11e6-86ab-38abd703dbfb.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/71944299-22692300-31a2-11ea-8ed1-48235f54c351.jpg)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/71944795-aa9bf800-31a3-11ea-9121-97e9f4f63e71.jpg)
