### ISSUE TITLE
RKNY-Yangyang International Airport-GANGWON-DOSOUTH KOREA

### ISSUE THREAD

**Issue by RiKowalSkipper** [InfiniteFlightAirportEditing/Airports#1020]

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17911155/d0092d38-6951-11e6-940a-1360597698eb.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17911171/dc45cd18-6951-11e6-850c-6f57a2b244ad.png)

**Comment by kilt46** [comment]
Please redo gates as per attachment

**Comment by RiKowalSkipper** [comment]
Redone

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17989353/52e10162-6af2-11e6-88f1-d2870d45db25.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17989356/5d9d5718-6af2-11e6-84f8-7509b016674d.png)
