### ISSUE TITLE
RKTH

### ISSUE THREAD

**Issue by RiKowalSkipper** [InfiniteFlightAirportEditing/Airports#1022]

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17837106/148ee5a4-676f-11e6-9c87-490da372405c.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17837108/1b809628-676f-11e6-9f70-e5e1589526ff.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17837110/244b0d6a-676f-11e6-85c2-8b89a0cec952.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17837111/2c51574e-676f-11e6-99e2-6bad9626c56c.png)
