### ISSUE TITLE
RKTL

### ISSUE THREAD

**Issue by RiKowalSkipper** [InfiniteFlightAirportEditing/Airports#1023]

**Comment by dushyants19** [comment]
RiKowal has 4 issues assigned to himself since one will be approved after a minor change by RiKowal.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17874857/e792afec-6893-11e6-9101-0fde893d620b.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17874860/ee46684c-6893-11e6-9255-bedf2266d7f7.png)
