### ISSUE TITLE
UMMS-Minsk National Airport-MINSK-BELARUS

### ISSUE THREAD

**Issue by tsarkov90** [InfiniteFlightAirportEditing/Airports#1026]
Main airport in Belarus. Hub for Aeroflot-Russian Airlines and Belavia.
Runway - 3600 m

**Comment by dushyants19** [comment]
Thanks for putting runway length, wish all would do that.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18219291/333d7ec0-712e-11e6-8991-4f636929b5db.png)

**Comment by Czechoslovaki** [comment]
Redoing this airport.

 - New runway + taxiways
 - New Ramps
 - Several apron configurations do not seem to match up with imagery
 - Airport appears to be very unaligned with imagery
 - ATC frequencies missing

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104131578-b4b78000-533c-11eb-85bc-954023048705.png)
