### ISSUE TITLE
LEAL

### ISSUE THREAD

**Issue by sudafly** [InfiniteFlightAirportEditing/Airports#1027]
I'm doing this.

Can somebody add labels?

**Comment by dushyants19** [comment]
Only max 3,

**Comment by sudafly** [comment]
What do you mean @dushyants19

**Comment by Aviationluver** [comment]
@sudafly You can only re-do a maximum of 3 airports at a time.

**Comment by sudafly** [comment]
Other 2 are canceled @Aviationluver

**Comment by sudafly** [comment]
EGVA and TNCC are canceled. Who can assign me?

**Comment by PaulNielsen** [comment]
How is this one going ? @sudafly

**Comment by dushyants19** [comment]
How is this one going ? @sudafly

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21578433/f086d12e-cf44-11e6-9fbb-cdbfef49db6e.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108596017-d185a100-7347-11eb-8b3a-a4a85497c504.png)
