### ISSUE TITLE
LPHR

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#1028]
Doing this one to start off my mini-project Azores.

**Comment by dushyants19** [comment]
Again, max 3.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17836877/3412eda6-6767-11e6-9abb-6ec68835962d.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17836878/3e5070b8-6767-11e6-84f7-5e5f0f4588ee.png)
