### ISSUE TITLE
KPWM-Portland International Jetport Airport-MAINE-USA

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Airports#1029]
Part of my "Project New England"

**Comment by CptNathanHope** [comment]
sent via email; awaiting acceptance

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18417531/d73eab86-77f8-11e6-90ec-1eb1e16ce094.png)
OUTLINES ADDED
![image](https://cloud.githubusercontent.com/assets/14023167/18417535/e5c08530-77f8-11e6-9d5f-04f53189dc33.png)

**Comment by RyanEpps** [comment]
Airport is in pretty rough shape. Several elements missing or unsnapped. Recommend complete rework.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45259439-a0d96900-b392-11e8-985a-3516f8d9710d.png)
