### ISSUE TITLE
ORER-Erbil International Airport-ARBIL-IRAQ

### ISSUE THREAD

**Issue by AxelBeder** [InfiniteFlightAirportEditing/Airports#103]
Please redesign me

**Comment by carmichaelalonso** [comment]
Duplicate, closing

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24126727/833a226e-0d9d-11e7-828a-903f650cfbc4.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24126742/9be11494-0d9d-11e7-82c2-425bbcd570c4.png)
