### ISSUE TITLE
KBHB-Hancock County-Bar Harbor Airport-MAINE-USA

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Airports#1031]
Part of my "Project New England"

**Comment by CptNathanHope** [comment]
sent for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23147948/6fbe8f28-f7a8-11e6-8c50-8ba9b6bb1a05.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38147094-6e32cba0-3416-11e8-8324-dad2b54c3410.png)

**Comment by kilt46** [comment]
Main Gate and Terminal Building added
