### ISSUE TITLE
KRUT-Rutland - Southern Vermont Regional Airport-VERMONT-USA

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Airports#1033]
Part of my "Project New England"

**Comment by CptNathanHope** [comment]
Sent in for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23827276/82ba82ae-0675-11e7-8cf1-580f53e6d11e.png)
