### ISSUE TITLE
KMHT-Manchester Airport-NEW HAMPSHIRE-USA

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Airports#1034]
Part of my "Project New England"

**Comment by CptNathanHope** [comment]
Sent for review. :)

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22318143/e26ce06c-e33d-11e6-8c64-22fbfa5ea7ee.png)

**Comment by CptNathanHope** [comment]
Needs a refresh.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59851720-b62cec00-9343-11e9-9609-6de14c59979e.jpg)
