### ISSUE TITLE
KLEB-Lebanon Municipal Airport-NEW HAMPSHIRE-USA

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Airports#1035]
Part of my "Project New England"

**Comment by CptNathanHope** [comment]
Sent for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24024543/57e0e436-0a82-11e7-8f5b-b612db683710.png)
