### ISSUE TITLE
KBED-Laurence G Hanscom Field Airport-MASSACHUSETTS-USA

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Airports#1038]
Part of my "Project New England"

**Comment by CptNathanHope** [comment]
Please reassign me. I'm currently doing this. Thanks! :)

**Comment by CptNathanHope** [comment]
Sent for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23823006/41612c9c-061e-11e7-825a-25c407bb4bdc.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52540886-5a7aa280-2d54-11e9-827e-4627b4ed2422.png)
