### ISSUE TITLE
KEWB

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Airports#1039]
Part of my "Project New England"

**Comment by moritzbabl** [comment]
added, runway lengths are different from the skyvector numbers but are correct according to @CptNathanHope and also another website

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22450729/3c89b4e6-e72e-11e6-80c6-b0b192256cd4.png)
