### ISSUE TITLE
KPVD-Theodore Francis Green State Airport-RHODE ISLAND-USA

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Airports#1043]
Part of my "Project New England"

**Comment by CptNathanHope** [comment]
Sent for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22046831/e06cac4e-dce8-11e6-9238-40eaa90bb189.png)

**Comment by CptNathanHope** [comment]
Reworking.

**Comment by CptNathanHope** [comment]
Oops.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51781215-48093380-20db-11e9-91c1-a9efe186d375.png)
