### ISSUE TITLE
KBDL

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Airports#1045]
Part of my "Project New England"

**Comment by CptNathanHope** [comment]
Sent for review.

**Comment by kilt46** [comment]
Missing Comms
![image](https://cloud.githubusercontent.com/assets/14023167/22006738/30f9a1e6-dc33-11e6-96c6-e1a8800e3ac0.png)

**Comment by kilt46** [comment]
Missing Terminal B
![image](https://cloud.githubusercontent.com/assets/14023167/22006773/7b4b9ec0-dc33-11e6-9538-4a5be35b39e3.png)

**Comment by CptNathanHope** [comment]
I can add the comms. 

Terminal B is closed IRL so I didn't include the taxilines leading up to the gate and I didn't add spawns there.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22182433/f4c9d56a-e06a-11e6-9c29-1cc9d39738b9.png)
