### ISSUE TITLE
RPVB

### ISSUE THREAD

**Issue by chrislunde** [InfiniteFlightAirportEditing/Airports#1047]
Bacolod-Silay International Airport, Philippines

**Comment by IFAEpat** [comment]
@chrislunde are you on Slack? If not, you need to be invited there and then here so we can assign you :)

**Comment by chrislunde** [comment]
Hey, I am not on Slack.


________________________________
Fra: Patrick U <notifications@github.com>
Sendt: 21. august 2016 06:56
Til: InfiniteFlightAirportEditing/Airports
Kopi: chrislunde; Mention
Emne: Re: [InfiniteFlightAirportEditing/Airports] RPVB (#1047)


@chrislunde<https://github.com/chrislunde> are you on Slack? If not, you need to be invited there and then here so we can assign you :)

-

**Comment by dushyants19** [comment]
Hi @chrislunde, please send an email to airports@liveflightapp.com :)

**Comment by dushyants19** [comment]
@chrislunde invited you to the team, please Accept:)

**Comment by dushyants19** [comment]
@chrislunde any progress?

**Comment by GentlePig500** [comment]
Can this be transfered to me?

**Comment by brunocr98** [comment]
There you go @GentlePig500 :)

**Comment by GentlePig500** [comment]
Thanks

**Comment by GentlePig500** [comment]
Sent For Review :)

**Comment by GentlePig500** [comment]
Resent For Reveiw :}

**Comment by moritzbabl** [comment]
Added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34696986-8a36dcd4-f496-11e7-8d7e-88eaf4305f46.png)
