### ISSUE TITLE
LPPD-Ponta Delgada Airport-AZORES-PORTUGAL

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#1048]
Redoing.
Airport 2/9 from Project Azores.

**Comment by bavAVIA** [comment]
Sent in for next review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19403051/4ff22c7e-922a-11e6-9a17-6c811345ecab.png)

**Comment by MBeringuy** [comment]
Continues in #5891.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123176679-868caf00-d449-11eb-8c37-1d0d43e2886a.png)
