### ISSUE TITLE
LPPI

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#1049]
Redoing,
Airport 3/9 from Project Azores.

**Comment by PaulNielsen** [comment]
@bavAVIA 1,5 month and still nothing. Are you still doing this one? If not I can finish it off.

**Comment by bavAVIA** [comment]
Did you guys recieve my e-mail?

**Comment by dushyants19** [comment]
yes we did

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19222741/ff0c00e0-8e24-11e6-817c-a54b6c05e6bb.png)
