### ISSUE TITLE
SBMA-Maraba/Joao Correa Da Rocha Airport-PARA-BRAZIL

### ISSUE THREAD

**Issue by david-garden** [InfiniteFlightAirportEditing/Airports#1050]
♻️ Recycling is the best thing on Earth ♻️

-_brunocr98_

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29643962-2f0ac37c-8838-11e7-8a7a-630938b35323.png)
