### ISSUE TITLE
LETL-Teruel Airport-ARAGON-SPAIN

### ISSUE THREAD

**Issue by Adrien-Z** [InfiniteFlightAirportEditing/Airports#1051]
RECYCLING IS LOVE. RECYCLING IS LIFE ♻️ ❤️

**Comment by Adrien-Z** [comment]
I just sent it for review :slightly_smiling_face:.

**Comment by dushyants19** [comment]
@Adrien-Z hows this going? 😡

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29594115-5bb1d6f0-8774-11e7-9fc4-455c50b4ffb0.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/110241160-f87dce80-7f14-11eb-8b7a-7d803a9aa94a.png)
