### ISSUE TITLE
VOTV-Trivandrum International Airport-KERALA-INDIA

### ISSUE THREAD

**Issue by bedaboy** [InfiniteFlightAirportEditing/Airports#1052]
Thiruvananthapuram Int'l Airport

**Comment by dushyants19** [comment]
Nice choice! :)

**Comment by dushyants19** [comment]
Any progress? @bedaboy

**Comment by brunocr98** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22403974/221967ac-e5ec-11e6-83ac-202411dee8aa.png)

**Comment by Czechoslovaki** [comment]
- Adding new apron.
- Domestic and international apron need updates (markings in imagery and the apt data look real different).
- Handful of atc frequencies to be added.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108006799-06999880-6fc2-11eb-9fd3-08988bff8437.png)
