### ISSUE TITLE
TNCA-Queen Beatrix International  Airport-ORANJESTAD-ARUBA

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#1053]
Re-doing TNCA

**Comment by Benny87654321** [comment]
Everything is in the wrong place. How do i make it from scratch?

**Comment by dushyants19** [comment]
You still with the team doing this?

**Comment by dushyants19** [comment]
@Benny87654321 when are you going to submit

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by brunocr98** [comment]
Taking this airport

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20780806/a92dc6ac-b743-11e6-8e23-42cbc56e48ca.png)

**Comment by kilt46** [comment]
Airport OUT OF ALIGNMENT!!!

https://drive.google.com/open?id=1GAM0d_W2VnC53Phcc50EZSC4OFE
--

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33743484-9657d5f0-db72-11e7-945f-ee93b40af923.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/58919002-ea2cce00-8702-11e9-9eb8-373330c216b2.jpg)
