### ISSUE TITLE
FALM-Makhado AFB Airport-LIMPOPO-SOUTH AFRICA

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#1054]
Please edit me. Recycled

**Comment by IFAEpat** [comment]
continue in #1053

**Comment by MajorTomMueller** [comment]
![falm-git](https://user-images.githubusercontent.com/26853210/38146069-9e57a2a2-344c-11e8-9576-d336c88abdcb.jpeg)
