### ISSUE TITLE
KLTS-Altus AFB Airport-OKLAHOMA-USA

### ISSUE THREAD

**Issue by J0mpa** [InfiniteFlightAirportEditing/Airports#1055]
Recycled.

**Comment by TristinWoolf** [comment]
Duplicate issue. Please search before creating issues. Continue in #550.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36064657-df473b84-0e53-11e8-84d9-552a08c80e65.png)
