### ISSUE TITLE
SANT-Tucuman Airport-TUCUMAN-ARGENTINA

### ISSUE THREAD

**Issue by dushyants19** [InfiniteFlightAirportEditing/Airports#1059]
RECYCLING IS GOOD 😄 ♻️

**Comment by dushyants19** [comment]
@Theyoshifan200 hows this going

**Comment by Theyoshifan200** [comment]
Good. I'm still working on it. To be honest, school has also been in the
way, which really hindered me to be able to work on it. I work on it on the
weekends.

**Comment by dushyants19** [comment]
@Theyoshifan200 any progress?

**Comment by dushyants19** [comment]
@Theyoshifan200 any progress?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27231469-4f8a7ffc-5278-11e7-85c7-42481ce89dbd.png)

**Comment by kilt46** [comment]
Positions seem slightly off???
![image](https://user-images.githubusercontent.com/14023167/27232234-e45df5b2-527a-11e7-9a34-de17447b1a8c.png)

**Comment by brunocr98** [comment]
Hope these fixes are fine.
