### ISSUE TITLE
LGST

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#1064]
Will redo this one

**Comment by PaulNielsen** [comment]
Sent in for review

**Comment by PaulNielsen** [comment]
@dushyants19 Is this one added? As you told me in the E-mail it was added?

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18224765/0c72cf7a-71a6-11e6-8546-e3b35a85c9f5.png)
