### ISSUE TITLE
EHAM-Amsterdam Airport Schiphol-NORTH HOLLAND-NETHERLANDS

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#107]

**Comment by carmichaelalonso** [comment]
Made some improvements, more parking spaces

**Comment by dushyants19** [comment]
Assign yourself Dylan

**Comment by kilt46** [comment]
This should be fixed

**Comment by kilt46** [comment]
New Taxiway S added

**Comment by dushyants19** [comment]
Misalinged with G Maps :disappointed: Not uniform misalignment either

**Comment by kilt46** [comment]
Redesigned airport

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17537301/171107c4-5e61-11e6-8347-d8fbd67e46af.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17537303/1bf01500-5e61-11e6-96f7-3b6d7a0ed654.png)

**Comment by dushyants19** [comment]
Assigning @janpolet since he wants to make minor fixes

**Comment by moritzbabl** [comment]
Airport has plenty of snapping issues all around the field

**Comment by TristinWoolf** [comment]
After looking this over on WED, I would suggest a major overhaul/redo of all taxiways and taxilines. Not only are lines unsnapped, many taxiway edges are not curved, some overlapping the airport boundary, and some lines running off the edges of taxiways, all possibly suggesting misalignment..

**Comment by moritzbabl** [comment]
Are you interested @TristinWoolf? Otherwise I will give it a try

**Comment by TristinWoolf** [comment]
I was considering, but I suppose I should get my other airport done that has been open for quite some time first. You can take this one, if you’d like. 👍

**Comment by moritzbabl** [comment]
I can’t promise that it will be finished before Christmas but I guess I’ll take it then 😉

**Comment by moritzbabl** [comment]
Finally done, now restricted to 3GB+ RAM devices, please add the TFR @carmichaelalonso

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34921800-6509e4b4-f94c-11e7-8094-1da3aaeddf6f.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52177659-fc652280-2789-11e9-8066-63bb5eefaff6.png)

**Comment by kilt46** [comment]
Gate G9 fixed. Buildings removed
