### ISSUE TITLE
LTAZ-Nevşehir Kapadokya Airport-NEVSEHIR-TURKEY

### ISSUE THREAD

**Issue by turkish1941** [InfiniteFlightAirportEditing/Airports#1070]
On it

**Comment by turkish1941** [comment]
Email is gone

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18224628/1cd79d36-71a2-11e6-9f35-cf6264921683.png)

**Comment by Czechoslovaki** [comment]
- Missing line types (double yellows, critical center lines)
- Main apron lacking lines that need to be added
- Incorrect runway settings
- Ramp start names to not be in full caps
- Buildings to be removed
- Frequency additions
