### ISSUE TITLE
KBIS

### ISSUE THREAD

**Issue by KarlLuebs** [InfiniteFlightAirportEditing/Airports#1073]
Fully redoing this one.

**Comment by dushyants19** [comment]
@KarlLuebs any progress?

**Comment by KarlLuebs** [comment]
KBIS will be ready soon. Again: slowly but surely.

**Comment by KarlLuebs** [comment]
@kilt46 finished it

**Comment by brunocr98** [comment]
When will this airport be approved Karl? Has been 2 months since you said that.

**Comment by KarlLuebs** [comment]
I know Bruno. I don't wanna explain everything now but I don't believe it was my fault. I'm getting fed up with this airport. Every time I send it something else is wrong

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27181431-37a9d4fe-519d-11e7-803c-0e45ab907ab8.png)
