### ISSUE TITLE
EDDB-Berlin Schonefeld Airport-BRANDENBURG-GERMANY

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#1075]
Berlin Schönefeld Airport. I'll re-do this one.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18495594/ecfa87c2-79e4-11e6-8ad5-6a51198d6a49.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18495602/f661d130-79e4-11e6-9b6d-1149f8aad2a6.png)

**Comment by ItsW1ll** [comment]
Planning on a full redo of this airport as it is very outdated now

**Comment by moritzbabl** [comment]
@ItsW1ll are you still working on this? If not, I’d take over to prepare it for the opening of BER in October

**Comment by moritzbabl** [comment]
![image](https://user-images.githubusercontent.com/19365980/96319931-4ac75d00-1011-11eb-9e58-8442c5dcd872.png)
