### ISSUE TITLE
LHKK

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#1076]
Kiskunlacháza Airport

**Comment by IFAEpat** [comment]
Imagery issues, will look for something else to change this to that has good imagery.

**Comment by IFAEpat** [comment]
I hope this one has good imagery

**Comment by IFAEpat** [comment]
Yay, good imagery

**Comment by IFAEpat** [comment]
Done! 5ef940d

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18369131/65c63138-75e9-11e6-8157-5c4a6010836d.png)
