### ISSUE TITLE
LEAS

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#1077]
Asturias Airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18225203/fdde5f1c-71b2-11e6-85b6-1608035f614c.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18225205/0563e4e6-71b3-11e6-9e46-fa31bbbde240.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108625824-884e5380-7412-11eb-8f81-002e90750067.png)
