### ISSUE TITLE
EGHH-Bournemouth Airport-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by IF-Airport-Team** [InfiniteFlightAirportEditing/Airports#108]
Bournemouth Airport

**Comment by IF-Airport-Team** [comment]
I would like to do this one.

**Comment by dushyants19** [comment]
Needs a redo

**Comment by IFAEpat** [comment]
May wok on it after KDBQ :)

**Comment by dushyants19** [comment]
@IFAEpat is doing this

**Comment by IFAEpat** [comment]
I have finished this long ago, still no review from staff... :/

**Comment by IFAEpat** [comment]
This is complete, approved by Cam. Needs closing :)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17196676/fc061c2e-542b-11e6-8eac-fae46cb9a359.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17250860/da5e8f0c-556b-11e6-9792-89eb6add4fa4.png)

**Comment by IFAEpat** [comment]
Needs some snapping

**Comment by IFAEpat** [comment]
Snapped and Gated

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17457535/78af9d54-5bc0-11e6-9486-483d74dcf04f.png)
TERMINAL
![image](https://cloud.githubusercontent.com/assets/14023167/17457539/836f7a66-5bc0-11e6-8eb5-27407d9e2fc7.png)
MILITARY/FBO
![image](https://cloud.githubusercontent.com/assets/14023167/17457543/907f7a44-5bc0-11e6-88a6-c2bd01fb3fb0.png)

**Comment by ItsW1ll** [comment]
Airport layout needs some tweaking and updating

**Comment by ItsW1ll** [comment]
Added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50481528-b0170d80-09a7-11e9-96cc-db1372eff9c7.png)

**Comment by kilt46** [comment]
Duplicate spawn removed
