### ISSUE TITLE
EGNM-Leeds Bradford Airport-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by liamkirky** [InfiniteFlightAirportEditing/Airports#1080]
Redone by @brunocr98

**Comment by liamkirky** [comment]
Hey I would like to do this

**Comment by liamkirky** [comment]
Starting to edit it again.

**Comment by liamkirky** [comment]
Unassign me please i don't have time for an airport like this

**Comment by brunocr98** [comment]
Oh by the way, I'm going to do this airport.

**Comment by brunocr98** [comment]
Finished....

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24383841/2cbbe0b6-1325-11e7-9fd2-ca9a86776f26.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/93654008-17c58580-f9e1-11ea-9ac7-ec7f2c544225.png)
