### ISSUE TITLE
LGAL

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#1085]
Being redone

**Comment by PaulNielsen** [comment]
Annnnd. Sent in for review! :)

**Comment by PaulNielsen** [comment]
@kilt46 Dush has already approved it :)

**Comment by dushyants19** [comment]
Just taking some time to push it :)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18230953/38b4787a-7270-11e6-97c6-06a56e79569b.png)
