### ISSUE TITLE
UHWW

### ISSUE THREAD

**Issue by sentikum** [InfiniteFlightAirportEditing/Airports#1086]
Vladvostok=Knevichi Intl' Airport

two runways
07r-25l -11500 ft
07l-25r - 11400 ft

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18533680/65f7363c-7aaa-11e6-85fe-213fa0711e81.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18533686/6dca20c2-7aaa-11e6-9773-67d0656be8cf.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/43993208-8cd9b95e-9d4f-11e8-8f2d-0df434ca514c.png)
