### ISSUE TITLE
EDDE 

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#1087]
Erfurt airport, being redone by me.

**Comment by PaulNielsen** [comment]
Sent in for approval! :)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18255629/0969bb32-7371-11e6-904c-7764c4a9183f.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18255631/1176a772-7371-11e6-8712-5f4a6430a01f.png)
