### ISSUE TITLE
LQSA

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#1088]
LQSA, Sarajevo. Being redone! :) by me

**Comment by PaulNielsen** [comment]
Sent in for approval!

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18330572/05bb9334-751f-11e6-9460-b73329d5e315.png)

**Comment by MajorTomMueller** [comment]
From the duplicate #5167
![](https://user-images.githubusercontent.com/26853210/86533450-f1ec1280-bec0-11ea-91e6-9eaa5a35f4f8.png)
