### ISSUE TITLE
EGLL-London Heathrow Airport-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by JoeMaynard** [InfiniteFlightAirportEditing/Airports#109]
Just touching up any small bugs or errors.

**Comment by Swang007** [comment]
Not sure which issue we are using so I'll comment on both. Adding EGLL departure frequency 120.52.

**Comment by kilt46** [comment]
Working on Main Terminal Upgrade

**Comment by kilt46** [comment]
Complete

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32758164-95a29b36-c8a8-11e7-858a-c0be5ab44ff1.png)

**Comment by kilt46** [comment]
Please remove ALL Buildings on completion

**Comment by mbmhwue148** [comment]
Alright, will check those aswell.

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48971691-f3fea780-efe2-11e8-98d4-bff98d018d81.png)

**Comment by kilt46** [comment]
Gates 209 / 210 added. Centerlines fixed

**Comment by MajorTomMueller** [comment]
JackH on slack:
Well never mind won’t be able to it then, if somebody could do it. Remote 524 the spawn is incorrect, then Remote 531 doesn’t have a line when parking and Remote 561 doesn’t have the correct colour line.

**Comment by liamkirky** [comment]
Could I be assigned to this please?

**Comment by kztmtn** [comment]
Sent in for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/77239974-6ffd0580-6bbf-11ea-8ef2-bebcf0cd75e9.jpg)
