### ISSUE TITLE
LHPA

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#1092]
Pápa Air Base

**Comment by IFAEpat** [comment]
Done! 1 more to go! 8d7e2b2

**Comment by IFAEpat** [comment]
Done! 8d7e2b2

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18421515/f877796e-7851-11e6-84b2-26cea1c2acb7.png)
