### ISSUE TITLE
LHSN

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#1093]
Szolnok Air Base

**Comment by IFAEpat** [comment]
Starting this one now, it's the last for Hungary!

**Comment by IFAEpat** [comment]
Done! eb1b6d2

Hungary is complete!!!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34082779-33fe5c66-e32a-11e7-83d1-92bf28bdf32b.png)
