### ISSUE TITLE
LYTV

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#1094]
LYTV, Tivat. Being redone! :)

**Comment by PaulNielsen** [comment]
Sent in for approval.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18411645/285b084c-7741-11e6-867d-9d0f527928c3.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18411649/303c4940-7741-11e6-8268-1fcfdf49516a.png)
