### ISSUE TITLE
MMJC

### ISSUE THREAD

**Issue by lalomarlin** [InfiniteFlightAirportEditing/Airports#1096]
Atizapan de Zaragoza

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18808396/ab0adc82-8226-11e6-82e2-9d242a6738cf.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108432228-a85ef680-7209-11eb-8180-81d750de06e4.png)
