### ISSUE TITLE
KSNA-John Wayne Airport-Orange County Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#11]

**Comment by Swang007** [comment]
Will completely redo KSNA. Expect completion before May

**Comment by Swang007** [comment]
Might be a delay... Other priorities with other airports. Feel free to take over if you want :)

**Comment by kilt46** [comment]
Image: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=KSNA

**Comment by kilt46** [comment]
Working it

**Comment by kilt46** [comment]
Done and e-mailed

**Comment by kilt46** [comment]
Completed Image:
http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=KSNA

**Comment by moritzbabl** [comment]
There are some wrongly orientated runway holds and some parking space are messed up, will also reposition the gates according to the new guidelines

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19789275/06572b9c-9c74-11e6-9c06-93540d47a5cc.png)

**Comment by brunocr98** [comment]
Renovation in process:
- No shoulder on taxiways
- Marking improvements 
- Adding more gates
- Etc...

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30772934-e39734f0-a02b-11e7-888b-b9737fe50207.png)

**Comment by Czechoslovaki** [comment]
@jakey20 will be renovating the airport. Suggested by Bruno.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109386991-208d8200-78c4-11eb-9ef3-362eb5f9d0c3.png)
