### ISSUE TITLE
LFHU-Lalpe Dhuez Airport-RHONE-ALPES-FRANCE

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#1104]

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18410340/189b0874-7725-11e6-8eb2-8dd8207b71d0.png)

**Comment by ECoops-123** [comment]
Will be reworked by @RobertineIFC

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111004933-83b0f700-834f-11eb-9038-f8c2437bc738.png)
