### ISSUE TITLE
LFLB-Chambery Aix Les Bains Airport-RHONE-ALPES-FRANCE

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#1105]

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18410398/8f656ede-7727-11e6-921a-ded6caaff357.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18410400/980bdb0e-7727-11e6-8df7-97accea12bc7.png)

**Comment by dushyants19** [comment]
Apron markings need adding and runway  markings need updating.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/35177307-dfe3ee78-fd43-11e7-88f3-12f876ed2d90.png)
