### ISSUE TITLE
NUIE

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#1106]

**Comment by kilt46** [comment]
unknown airport location!!

**Comment by dushyants19** [comment]
@AxelBeder

**Comment by dushyants19** [comment]
@kilt46 : https://en.wikipedia.org/wiki/Niue_International_Airport

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34753004-32ba923a-f57b-11e7-9598-4ebaacca7e34.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107146741-a0e94480-690f-11eb-94b4-9494c94ee5f2.png)
