### ISSUE TITLE
LOAA

### ISSUE THREAD

**Issue by IceBlue02** [InfiniteFlightAirportEditing/Airports#1107]
Redoing

**Comment by IceBlue02** [comment]
Done.
https://github.com/InfiniteFlightAirportEditing/Airports/commit/f09d18eb0eafe4dbb19e89daebff2a2b74d3f942

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18413458/43dadebc-776e-11e6-8410-0b6aa9477426.png)
