### ISSUE TITLE
LOAB

### ISSUE THREAD

**Issue by IceBlue02** [InfiniteFlightAirportEditing/Airports#1108]
Redoing

**Comment by IceBlue02** [comment]
Done.
https://github.com/InfiniteFlightAirportEditing/Airports/commit/f09d18eb0eafe4dbb19e89daebff2a2b74d3f942

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18413443/d573d56e-776d-11e6-8832-ea846676430c.png)
