### ISSUE TITLE
LOAD

### ISSUE THREAD

**Issue by IceBlue02** [InfiniteFlightAirportEditing/Airports#1109]
Redoing.

**Comment by IceBlue02** [comment]
Done.
https://github.com/InfiniteFlightAirportEditing/Airports/commit/f09d18eb0eafe4dbb19e89daebff2a2b74d3f942

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18413506/5e218ad6-776f-11e6-9727-048f4921aa38.png)
