### ISSUE TITLE
LOAG

### ISSUE THREAD

**Issue by IceBlue02** [InfiniteFlightAirportEditing/Airports#1110]
Redoing

**Comment by IceBlue02** [comment]
Done. https://github.com/InfiniteFlightAirportEditing/Airports/commit/2733bac49c6ddd06a6b1013cbf70c06811130b8b

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22182773/292ee59a-e073-11e6-9cff-3f02252b2b30.png)
