### ISSUE TITLE
LOAL

### ISSUE THREAD

**Issue by IceBlue02** [InfiniteFlightAirportEditing/Airports#1111]
Redoing

**Comment by IceBlue02** [comment]
Done. https://github.com/InfiniteFlightAirportEditing/Airports/commit/2733bac49c6ddd06a6b1013cbf70c06811130b8b

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22182797/ac4c1434-e073-11e6-8f28-109b6b715a47.png)
