### ISSUE TITLE
LOAN

### ISSUE THREAD

**Issue by IceBlue02** [InfiniteFlightAirportEditing/Airports#1112]
Redoing

**Comment by IceBlue02** [comment]
Done. https://github.com/InfiniteFlightAirportEditing/Airports/commit/5b53a3fe59ef96a539786db99e1d60db0c74711c

(After the LOWW excursion)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22089212/3d7ec0fe-ddaf-11e6-9c05-9d07b9d92ad4.png)
