### ISSUE TITLE
URRR

### ISSUE THREAD

**Issue by sentikum** [InfiniteFlightAirportEditing/Airports#1113]
Rostov-on-Don Int'l Airport (Russian Federation)

**Comment by dushyants19** [comment]
Done in eb23b6a6765fbe8eadadb18c5211f6913c78c8f5

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18975087/45396090-866d-11e6-9645-afa76de31ab1.png)
