### ISSUE TITLE
KOUN

### ISSUE THREAD

**Issue by CaptainDawud** [InfiniteFlightAirportEditing/Airports#1114]
University of Oklahoma Westheimer Airport

**Comment by IFAEpat** [comment]
Dawud says he doesn't have time to contribute, now a suggestion.

**Comment by dushyants19** [comment]
bad bad :(

**Comment by dushyants19** [comment]
ill get it done by today

**Comment by CaptainDawud** [comment]
I'm sorry guys airport editing isn't my thing, too hard and I don't have
that much time. ;(

**Comment by dushyants19** [comment]
Unacceptable.

**Comment by dushyants19** [comment]
Redone in dcbb80463f4a02d84c89719ccb11395eab2f6d57

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18897902/8ed875b8-84f3-11e6-9014-ec09e176ed69.png)
