### ISSUE TITLE
 RCMQ-Taichung Cingcyuankang-TAIWAN

### ISSUE THREAD

**Issue by MalongMa** [InfiniteFlightAirportEditing/Airports#1115]
Mabye i can do this?

**Comment by dushyants19** [comment]
Are you in our slack?

Please mail to airports@liveflightapp.com

**Comment by dushyants19** [comment]
@MalongMa Any developments?

**Comment by MalongMa** [comment]
no but it will have developments so fast

**Comment by dushyants19** [comment]
Invited to the github team

**Comment by MalongMa** [comment]
Makeing...

**Comment by dushyants19** [comment]
@MalongMa are you doing this?

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by Yifan081** [comment]
Redoing this one, please assign me.

**Comment by Yifan081** [comment]
Sent for review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23824777/514c8e3e-0642-11e7-90d9-d8a6e999d389.png)
