### ISSUE TITLE
LPLA-Lajes Field-AZORES-PORTUGAL

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#1119]
Lajes Field, Project Azores.
Being redone from scratch.

**Comment by bavAVIA** [comment]
Runway length is over 10.000ft.

**Comment by bavAVIA** [comment]
Please add the Priority 2 label to this one. Thanks.

**Comment by bavAVIA** [comment]
Please unassign. I'm aborting this project, it's driving me crazy ever since I started. Up for grabs.
Sorry.

**Comment by bavAVIA** [comment]
Oh well, I guess it's about time...

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27812749-d5238c0a-6036-11e7-98ab-184398453db7.png)
