### ISSUE TITLE
HECA

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#1123]
Cairo International, Egypt. (القاهرة ,مصر)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33636862-aebfc9f8-d9e3-11e7-865b-31c7c674b1f3.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/79932083-0cb2fd00-8423-11ea-8c1e-3722adb00a19.jpg)
