### ISSUE TITLE
EDXW-Sylt Airport-SCHLESWIG-HOLSTEIN-GERMANY

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#1124]
I will be re-doing this one.

Runways are not longer than 10,000 feet.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18570545/84bf6d66-7b70-11e6-96ad-a8b73b64bc34.png)

**Comment by moritzbabl** [comment]
Needs a rework, taxiway materials are incorrect in various areas, terminal got a 3rd gate in the meantime and public roads are included in the design

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45579413-0757fe80-b84d-11e8-91c4-06975d4cc06b.png)

**Comment by kilt46** [comment]
Airport has Buildings and yellow/white 'X's. Philippe requested these NOT to be included in new edits.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45579479-82b9b000-b84d-11e8-9158-e1e0676e6b0a.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45596692-70429200-b985-11e8-985a-9016e74563ac.png)
