### ISSUE TITLE
LIRJ-Marina Di Campo Airport-TOSCANA-ITALY

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#1127]
Being redone

**Comment by PaulNielsen** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18570089/e82bd1c2-7b6c-11e6-8482-a37e634aaabb.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/70662057-43426500-1c44-11ea-8102-7baadb2205a7.jpg)
