### ISSUE TITLE
LIMZ-Cuneo/Levaldigi Airport-PIEMONTE-ITALY

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#1128]
Being redone

**Comment by PaulNielsen** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18570320/7bb6d6c0-7b6e-11e6-9871-ed3323114010.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/69433926-5637d880-0d1b-11ea-9bdf-a580c9d9bf56.jpg)
