### ISSUE TITLE
MMCM

### ISSUE THREAD

**Issue by lalomarlin** [InfiniteFlightAirportEditing/Airports#1129]
Chetumal Intl

**Comment by dushyants19** [comment]
You have 6 airports assigned to you, max is 3

**Comment by dushyants19** [comment]
bc2d6aadd69446e3b347ddcc771c690eee7011e1

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18854127/ddce77b6-840e-11e6-9d66-86bc6ad57615.png)
