### ISSUE TITLE
MPMG

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1130]
Doing this airport. Albrook "Marcos A. Gelabert" Int'l Airport.

**Comment by brunocr98** [comment]
Sent for approval (ignore the message in the MPPA issue, I meant to comment in here but I mistakenly commented in there).

**Comment by dushyants19** [comment]
Done, Great detail

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19205072/be4f9bb4-8ca5-11e6-883c-ec28be88e397.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112719476-2aa49f80-8ec7-11eb-9b08-9304bc70dff9.png)
