### ISSUE TITLE
SVMI-Maiquetia Simon Bolivar International Airport-VARGAS-VENEZUELA

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#1131]
I do not want to re-do this one.

This is a suggestion.

**Comment by Adam167** [comment]
I will redo this when I have finished my other one

**Comment by Adam167** [comment]
Finally got round to this. 2 runways one is 11k feet

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22088293/aa9aff1a-dda8-11e6-9bf5-4a14a452fa62.png)
