### ISSUE TITLE
PGUM-Guam International Airport-GUAM-GUAM

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#1133]
Antonio B. Won Pat Intl

**Comment by IFAEpat** [comment]
Up for grabs

**Comment by brunocr98** [comment]
Abandoning this airport.

**Comment by dushyants19** [comment]
will do

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25042400/64c4d132-20dd-11e7-8917-a721b45df884.png)

**Comment by brunocr98** [comment]
Vladimir wants to fix some things...

**Comment by moritzbabl** [comment]
readded

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/40874620-f70076b0-6636-11e8-83ad-fb559905d9c9.png)

**Comment by kilt46** [comment]
PGUM-TOM MUIR-12/30/18-Gate 19 renamed

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50547833-d935d900-0c07-11e9-9b5f-88f286346027.png)
Buildings removed
