### ISSUE TITLE
KCAK-Akron-Canton Regional Airport-OHIO-USA

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#1134]
RECYCLED ♻️

**Comment by IFAEpat** [comment]
Up for grabs

**Comment by brunocr98** [comment]
Leaving this airport for someone else. The design drove me crazy!

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26725422/1c617cf8-4764-11e7-9b7b-05db01efbcbf.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52188303-c5c5f100-27f7-11e9-87c8-d2c5681e5f52.png)
