### ISSUE TITLE
PAEI-Eielson Air Force Base-ALASKA-USA

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#1135]
♻️

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18652760/937f9e02-7e9a-11e6-8dd7-0c3e86d1925d.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/37003955-6e7d0070-2094-11e8-814b-c88f1874a270.png)
