### ISSUE TITLE
TFFC

### ISSUE THREAD

**Issue by dushyants19** [InfiniteFlightAirportEditing/Airports#1136]
IF airport, horrible condition

**Comment by dushyants19** [comment]
Airport fixed in 1eb906d

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18652840/340b5a50-7e9b-11e6-93de-7791ab1a9e48.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52543196-3bd4d580-2d6d-11e9-883e-a8eb86203511.png)
