### ISSUE TITLE
SBGL-Rio De Janeiro Galeao Airport-RIO DE JANEIRO-BRAZIL

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#1137]
Tom Jobim International Airport

New A380 Airport to the list! FAA approved airport for A380 Operations!

**Comment by dushyants19** [comment]
NO GP1 label, no commercial service

**Comment by Abimael96** [comment]
GIG RioGaleao Airport!! Nice...

**Comment by dushyants19** [comment]
@Abimael96 All airports are getting added.

**Comment by brunocr98** [comment]
Taking this airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21706920/2af1fc7c-d390-11e6-8dfb-38c53d3dcfc8.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/49188539-bfffeb00-f330-11e8-8bdf-b65601f40341.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/60597454-5857c580-9d81-11e9-86a0-b75e48894f95.jpg)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/93001150-9fe3f080-f4f2-11ea-9f9c-aa119c38feb6.png)
