### ISSUE TITLE
EDDV-Hannover Airport-NIEDERSACHSEN-GERMANY

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#1138]
Hannover Airport.

Runway= 10,000+ feet

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19003652/73ff3da0-8717-11e6-9171-9bfa4ec77675.png)

**Comment by Fabse1803** [comment]
Good Evening I got an Message from an Friend that the Tower Position isn't right they have an new Tower at an new Spot the Tower position in IF is Out Dated

**Comment by MBeringuy** [comment]
What is the situation at this airport? Is it being redone?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/83929240-4718f500-a758-11ea-8721-57baaaf4e868.png)
