### ISSUE TITLE
MMCS-Cd. Juarez/Abraham Gonzalez Airport-CHIHUAHUA-MEXICO

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#1139]
I ❤️ RECYCLING

**Comment by IFAEpat** [comment]
Up for grabs

**Comment by brunocr98** [comment]
No longer doing this one.

**Comment by lalomarlin** [comment]
Who is Doing it?

**Comment by brunocr98** [comment]
Yes, that's why I self-assigned to this airport ¯\_(ツ)_/¯

**Comment by brunocr98** [comment]
This airport has been proudly done with a recycled issue.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27085064-cacdcbae-5013-11e7-80ba-f63dffc7573e.png)
