### ISSUE TITLE
EGLM

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#114]

**Comment by kilt46** [comment]
Started

**Comment by kilt46** [comment]
This appears to be a simple one. Hope Im not missing something

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20597910/00496a5a-b20c-11e6-8c18-8981aadfc7da.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45264617-e6cf1500-b404-11e8-8918-7f151c3ffc2d.png)

**Comment by kilt46** [comment]
Duplicate spawn removed
