### ISSUE TITLE
TJRV-Jose Aponte de la Torre Airport-CEIBA-PUERTO RICO

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#1141]
José Aponte de la Torre Airport

**Comment by kilt46** [comment]
Looks like detail missing
![image](https://cloud.githubusercontent.com/assets/14023167/19220874/23fa4538-8dfd-11e6-9fea-8afafcb97932.png)

**Comment by IFAEpat** [comment]
@kilt46 there's no "detail" the pavement has no markings, some aircraft are just randomly parked.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33692116-544b3038-dab1-11e7-8478-a2b109e1f0ad.png)
