### ISSUE TITLE
X63-Humacao Regional Airport-PUERTO RICO

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#1142]
Humacao Airport

**Comment by kilt46** [comment]
Not uploaded
![image](https://cloud.githubusercontent.com/assets/14023167/19025930/27fb64cc-88e5-11e6-8e50-717f71a69a1f.png)

**Comment by IFAEpat** [comment]
![screen shot 2016-10-02 at 10 23 22 pm](https://cloud.githubusercontent.com/assets/18223248/19026048/fde04266-88ee-11e6-90a3-5008d284b7e5.png)
Weird

**Comment by IFAEpat** [comment]
Especially since I uploaded it when I created a folder for it

**Comment by IFAEpat** [comment]
It's good now :)

**Comment by kilt46** [comment]
No folder
![image](https://cloud.githubusercontent.com/assets/14023167/19220898/aaf8bfb0-8dfd-11e6-8475-cff8ad3007d5.png)

**Comment by IFAEpat** [comment]
@kilt46 I did upload this, twice actually...

**Comment by IFAEpat** [comment]
![screen shot 2016-10-09 at 1 01 23 pm](https://cloud.githubusercontent.com/assets/18223248/19222188/91ee3e64-8e20-11e6-869a-39d87368bf99.png)
![screen shot 2016-10-09 at 1 01 31 pm](https://cloud.githubusercontent.com/assets/18223248/19222189/91f0ad02-8e20-11e6-9b07-26c5515e3a40.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19222983/3dd0f862-8e2a-11e6-8eb6-6711718ee8ff.png)
