### ISSUE TITLE
EETN

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#1149]
Will redo this one!

**Comment by PaulNielsen** [comment]
Done

**Comment by kilt46** [comment]
Added outlines. PLEASE provide when editing airport!!!
![image](https://cloud.githubusercontent.com/assets/14023167/18819669/89b47d06-835a-11e6-9775-4c1c096d9c33.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18819671/92894524-835a-11e6-8f8d-e6103c196945.png)

**Comment by PaulNielsen** [comment]
@kilt46 on the map it looked like the lines where actually red, that's why I didn't add them.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/72274953-d851c880-360b-11ea-8608-7d8420fabf3f.jpg)

**Comment by MajorTomMueller** [comment]
![EETN-git](https://user-images.githubusercontent.com/26853210/125097657-e16b0b00-e0c5-11eb-8062-565fd02d1beb.png)
