### ISSUE TITLE
ZKPY-Pyongyang Airport-PYONGYANG-NORTH KOREA

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#1150]
Pyongyang International

**Comment by dushyants19** [comment]
d1fbd33

the great airport has been done :flag-kp:

**Comment by IFAEpat** [comment]
Rip Emoji. But yes, I made 5000 peanuts happy 😂

**Comment by dushyants19** [comment]
It showed up in our slack tho :P

**Comment by IFAEpat** [comment]
why not here though? :P

**Comment by IFAEpat** [comment]
no emoji on git for it, rip.

**Comment by dushyants19** [comment]
Im disappointed. No emoji for North Korea 😭

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19020333/473321e2-886b-11e6-86c4-9deb3d152696.png)
![image](https://cloud.githubusercontent.com/assets/14023167/19020336/4f8454ec-886b-11e6-9965-98c7fe97cf2e.png)

**Comment by RyanEpps** [comment]
Danny is doing, uh, something to this airport.

**Comment by brunocr98** [comment]
Up for grabs.

**Comment by norta890** [comment]
I wanna redo it

**Comment by MajorTomMueller** [comment]
@norta890 you are in our slack? wich name?

**Comment by brunocr1050** [comment]
Closing this for now, no attempt to redo this airport has been successful.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/119228375-5c597180-bad8-11eb-896f-98b93fe78ef7.png)
