### ISSUE TITLE
EGSF-Peterborough Connington-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#1151]
Runways reversed

**Comment by dushyants19** [comment]
b4e0df6a9d4e342a5f8464f62832183ec2754765 <---- Was fixed/done in this

**Comment by dushyants19** [comment]
Done in b4e0df6a9d4e342a5f8464f62832183ec2754765

**Comment by dushyants19** [comment]
This one :|

79b270b9532f434d1708031b39bf318be777a284

Why is the SHA changing? :|

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18898086/e38108ae-84f4-11e6-9971-98c597868f74.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45254660-6b585f80-b341-11e8-8069-1ba2f42aa072.png)
