### ISSUE TITLE
KVLA-Vandalia Municipal Airport-ILLINOIS-USA

### ISSUE THREAD

**Issue by turkish1941** [InfiniteFlightAirportEditing/Airports#1153]
RECYCLED ♻️

**Comment by turkish1941** [comment]
done

**Comment by dushyants19** [comment]
@turkish1941 hows this goin

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34057407-74a903ea-e19c-11e7-9193-b1ca4eb49368.png)
