### ISSUE TITLE
UACC-Nur-Sultan Astana International Airport-AQMOLA-KAZAKHSTAN

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#1154]
Hub of Air Astana for it's european flights, soon to be their full hub (moving from a dual hub system where the asian flights were departing from Almaty and the european from Astana to a single Astana airport hub in the future). Btw, Air Astana is the airline to operate the newest fleet of 767, with the best Business Class I have ever seen on a 767.

**Comment by NickArt1342** [comment]
@kilt46 Please approve that this airport does belong into your priority list: It's runway is 3500 m, so about 11k feet.

**Comment by dushyants19** [comment]
ok thanks for the great tripreport.com

**Comment by NickArt1342** [comment]
@dushyants19 As if you knew.

**Comment by NickArt1342** [comment]
Ups, wrong button.

**Comment by sentikum** [comment]
Ok, I can do it.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19368918/106c15d2-9168-11e6-86fe-44fe2d017149.png)

**Comment by Czechoslovaki** [comment]
Reworking this.

- Several missing aprons
- Many outdated line placements
- Many Incorrect / missing line attributes
- Boundary too close to taxiways (snapped to them)
- Spawns are not snapped to their lines

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105578170-de60a600-5d43-11eb-8c55-d7fd3235d582.png)
