### ISSUE TITLE
EDLP-Paderborn Lippstad Airport-NORDRHEIN-WESTFALEN-GERMANY

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#1155]
Will redo!

**Comment by PaulNielsen** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18936380/714e617e-85ac-11e6-8f76-658578cd1c5a.png)

**Comment by bavariaaviation** [comment]
Redoing this.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/80316459-6412ed80-87d4-11ea-8935-c7f08ba0cc44.jpg)
