### ISSUE TITLE
MUHA-Jose Marti International Airport-CIUDAD DE LA HABANA-CUBA

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#1158]
Havana, Cuba

**Comment by JcFl4** [comment]
I know I have assigned myself to many already, but this is the last one for now... 😉

**Comment by dushyants19** [comment]
Just 8, Julio. ;)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22630418/7b0dc8ac-ebbf-11e6-9aef-2292dcc901f9.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55199639-b7a5a880-5188-11e9-87f0-f0e5de923b03.png)
