### ISSUE TITLE
UBBB

### ISSUE THREAD

**Issue by sentikum** [InfiniteFlightAirportEditing/Airports#1159]
Baku International airport. Two runways over 11000ft. Main airport in Azerbaijan

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19222851/94d799d4-8e27-11e6-8e44-30c4a6fa4e7e.png)
![image](https://cloud.githubusercontent.com/assets/14023167/19222853/9e6db92e-8e27-11e6-8587-6bfb6fe52f57.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/43937634-6f11fc46-9c24-11e8-8a44-5f20724838a7.png)
