### ISSUE TITLE
HEGN-Hurghada Airport-AL BAHR AL AHMAR-EGYPT

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#116]
Please edit me

**Comment by JcFl4** [comment]
Being redone

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24334050/d79eede6-1228-11e7-9887-a77bb9c58240.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68155452-7ba9a180-ff28-11e9-8e2c-e9b85cba362b.jpg)
