### ISSUE TITLE
GVAC-Sal/Amilcar Cabral International Airport-SAL-CAPE VERDE

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#1165]
Will redo

**Comment by PaulNielsen** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19017480/b369f720-8800-11e6-9118-659cb3133563.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/71528808-77628a80-28c0-11ea-83ae-82c3da1cd3dc.jpg)
