### ISSUE TITLE
GCHI 

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#1168]
Being redone

**Comment by PaulNielsen** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19017455/72b52d7c-87ff-11e6-8868-9538ac9df5d7.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107885765-b0ddc700-6ec1-11eb-8825-b4712d826661.png)
