### ISSUE TITLE
GCLA

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#1169]
Being redone

**Comment by PaulNielsen** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19017425/7527a64e-87fe-11e6-95c5-e2a5c8104fd9.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107885604-f0f07a00-6ec0-11eb-9bb0-ec08d9f185d8.png)
