### ISSUE TITLE
MYBC

### ISSUE THREAD

**Issue by TristinWoolf** [InfiniteFlightAirportEditing/Airports#1170]
Chub Cay

**Comment by TristinWoolf** [comment]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/26290b1a158dd7b3ec1a4d73c68a404d38ad7b55)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19020566/43b24d20-8872-11e6-9b8b-7d2bc5f20024.png)
