### ISSUE TITLE
MYBG

### ISSUE THREAD

**Issue by TristinWoolf** [InfiniteFlightAirportEditing/Airports#1171]
Great Harbour Cay Airport

**Comment by TristinWoolf** [comment]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/e0b8c79dc78414c981a6bcb4cfc41845b1ae8b6d)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19020463/0a6d071a-886f-11e6-9998-b7ddbeaca573.png)
