### ISSUE TITLE
MYBS

### ISSUE THREAD

**Issue by TristinWoolf** [InfiniteFlightAirportEditing/Airports#1172]
South Bimini Airport

**Comment by TristinWoolf** [comment]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/bdc2b798af5bcfd594a2d24f81c6d27a5a68742d)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19020391/cba5cf32-886c-11e6-94c3-4edfecd6a65d.png)
