### ISSUE TITLE
LECO

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#1173]
Being redone

**Comment by PaulNielsen** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19095649/87cd674c-8a5c-11e6-8357-d8b32bfd4154.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109083977-84e5f100-76cc-11eb-8f92-9a9f027fe98f.png)
