### ISSUE TITLE
LEXJ

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#1174]
Being redone

**Comment by PaulNielsen** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19095237/49f0a8a0-8a5a-11e6-86e8-30faae5e99d3.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/110395287-7f28cd80-8033-11eb-806a-3288c6a05e64.png)
