### ISSUE TITLE
UWOO

### ISSUE THREAD

**Issue by ErshovlaD** [InfiniteFlightAirportEditing/Airports#1178]
Being redone

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19207422/687e576e-8cb6-11e6-8887-4228fb0d28df.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19207427/76cc6568-8cb6-11e6-8286-054467646aae.png)
