### ISSUE TITLE
EGPE-Inverness Airport-SCOTLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#1179]

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19058708/27ecf5bc-899f-11e6-818c-c9a6e9758c9e.png)

**Comment by ItsW1ll** [comment]
Quick update; Hold G needs to be added along with the taxiway lines and a bigger SAR apron.
