### ISSUE TITLE
SBFN-Fernando De Noronha Airport-PERNAMBUCO-BRAZIL

### ISSUE THREAD

**Issue by ErshovlaD** [InfiniteFlightAirportEditing/Airports#1182]
Being redone

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19256238/ab6e702e-8f2a-11e6-85fb-8208c6da3f54.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/47969532-8c39ea00-e03e-11e8-8420-1ad08db40bf3.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118895241-68bcaf00-b8cb-11eb-81d8-1929c95d49b5.png)
