### ISSUE TITLE
RPLL-Manila-Ninoy Aquino International Airport-MANILA-PHILIPPINES

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#1184]
Ninoy Aquino International Airport (Manila Airport), Philippines

**Comment by dushyants19** [comment]
Do you want to do this? @chriscroft20

**Comment by chrislunde** [comment]
Yeah, not so much work to do. Just adding gates and small things

**Comment by dushyants19** [comment]
@chrislunde any progress?

**Comment by Aviationluver** [comment]
How is this one going? @chrislunde If there is no progress being made, I will gladly take this.

**Comment by brunocr98** [comment]
There you go @Aviationluver :)

**Comment by Aviationluver** [comment]
Thanks ;) @brunocr98

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22533747/728be5e0-e8b5-11e6-8682-45940d785e52.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53295024-9a5f7200-37b7-11e9-90b1-a2ad7a49d775.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53299477-7411f480-3800-11e9-925e-b4b85f54488a.png)

**Comment by kilt46** [comment]
DUPLICATES REMOVED

**Comment by MajorTomMueller** [comment]
@liamkirky in slack:
Can a Supervisor unassign me from RPLL please as imagery quality isn’t the best and I need to wait for imagery to update so I can bring the airport up to expected quality.

**Comment by MajorTomMueller** [comment]
EAD:
![EE59B7A4-12DD-4377-ACA3-04644BA0AEAA](https://user-images.githubusercontent.com/26853210/89206816-16b7d080-d5ba-11ea-9646-d71297a834a0.jpeg)

**Comment by MajorTomMueller** [comment]
![](https://aws1.discourse-cdn.com/infiniteflight/original/4X/a/6/f/a6f37d8f5a7e506d3f4c866b95fa91e96900d4f5.jpeg)

![](https://aws1.discourse-cdn.com/infiniteflight/original/4X/2/d/e/2de6e9b3ceed732373f46678e19b09b5952a4a31.jpeg)

![](https://aws1.discourse-cdn.com/infiniteflight/original/4X/6/3/2/6320f2b509d6d92cf5f5f2b21a03ea7a24d3a7d4.jpeg)

![](https://aws1.discourse-cdn.com/infiniteflight/original/4X/e/a/e/eae74ea2a935db57408a3c1430df7159b457492b.jpeg)

![](https://aws1.discourse-cdn.com/infiniteflight/original/4X/e/b/5/eb51623331ca2ab30a8b6af9e30d776a905c58e1.jpeg)

![](https://aws1.discourse-cdn.com/infiniteflight/original/4X/1/e/3/1e37ed556ee9a9e4e55998e14537219c53ec37c0.jpeg)

**Comment by jakey20** [comment]
Here.com has got sufficient imagery for these updates @MajorTomMueller, I’ll fix it.

**Comment by MajorTomMueller** [comment]
IFC is calling @jakey20 
https://community.infiniteflight.com/t/airport-and-navigation-updates-november-2020/496923/72

**Comment by jakey20** [comment]
Hi, I’m asking to be unassigned from RPLL. If you would like to take over PM me for the apt.dat please.

**Comment by brennanhackard** [comment]
@zacky89315 will take over editing this airport.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123343615-b6a28380-d517-11eb-88ec-8bb99f069c39.png)
