### ISSUE TITLE
SWFN-Manaus/Flores Airport-AMAZONAS-BRAZIL

### ISSUE THREAD

**Issue by ErshovlaD** [InfiniteFlightAirportEditing/Airports#1185]
Being redone

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19371766/8aee6202-917b-11e6-898a-de7b0245a59d.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56686039-de2c0600-6698-11e9-9899-8c77aeb13a82.png)
