### ISSUE TITLE
SBEG-Manaus Eduardo Gomes Airport-AMAZONAS-BRAZIL

### ISSUE THREAD

**Issue by ErshovlaD** [InfiniteFlightAirportEditing/Airports#1186]
Being redone

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19256503/419c1658-8f2d-11e6-9225-dd10b094cbdd.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46443399-03741980-c733-11e8-8578-abff9f9bb6e4.png)
