### ISSUE TITLE
KDRO-Durango-La Plata Airport-COLORADO-USA

### ISSUE THREAD

**Issue by MCTechPlays** [InfiniteFlightAirportEditing/Airports#1187]
♻️

**Comment by dushyants19** [comment]
Please send an email to airports@liveflightapp.com! Thanks

**Comment by ErshovlaD** [comment]
Can I take this port? I'm going to make it

**Comment by PaulNielsen** [comment]
Uhh, MCTechPlays is already doing it @ErshovlaD

**Comment by dushyants19** [comment]
@ErshovlaD interested?

**Comment by dushyants19** [comment]
Any progress? @ErshovlaD

**Comment by ErshovlaD** [comment]
Yet no. Now I'm working on project Georgia. This airport I'm will make later

**Comment by MajorTomMueller** [comment]
@ErshovlaD are you working on it? Any progress?

**Comment by ErshovlaD** [comment]
@MajorTomMueller you can take it for working, I'm very busy for creating airports :(

**Comment by MajorTomMueller** [comment]
the question is if you have done already anything on ot and want to continue or not. The two other issues that you have open are also quite old...

**Comment by ErshovlaD** [comment]
I have full done UTTT, and that's all

**Comment by moritzbabl** [comment]
added
