### ISSUE TITLE
UUWW-Moscow/Vnukovo Airport-MOSKVA-RUSSIA

### ISSUE THREAD

**Issue by tsarkov90** [InfiniteFlightAirportEditing/Airports#1188]
Moscow Vnukovo Int'l airport.
Hub for Rossiya, arline of Aeroflot group
Two runways (over 10000ft)

**Comment by dushyants19** [comment]
Do you want to do this @sentikum

**Comment by sentikum** [comment]
Sure

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19912607/a767d4b6-a069-11e6-9229-b71d35f5b84a.png)

**Comment by Czechoslovaki** [comment]
Reasons for rework:

•Apron 5 is missing
•Hangar spawns are missing too
•Several buildings should be removed
•Update to new standards

@AleksanderIF will be doing this.

**Comment by AleksanderIF** [comment]
@Czechoslovaki Thanks.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103033458-1ba8fc80-4528-11eb-9dc1-6b1eb0dbe0fc.png)
