### ISSUE TITLE
MPPA

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1189]
Doing this airport. Panamá-Pacífico International Airport.

**Comment by brunocr98** [comment]
Sent for approval.

**Comment by brunocr98** [comment]
Sent for approval (now I meant to comment in here).

**Comment by kilt46** [comment]
Missing some gates
![image](https://cloud.githubusercontent.com/assets/14023167/19222933/6fe4df0e-8e29-11e6-915a-618f49b2e05a.png)
![image](https://cloud.githubusercontent.com/assets/14023167/19222941/9f7ed094-8e29-11e6-98f8-2d9a5e358f20.png)

**Comment by brunocr98** [comment]
Changes sent for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19254692/06e29804-8f1c-11e6-9373-adc2b1a7eb62.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112719214-c33a2000-8ec5-11eb-899a-a7b06f205244.png)
