### ISSUE TITLE
KFUL-Fullerton Municipal Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#119]

**Comment by kilt46** [comment]
Airport redone

**Comment by dushyants19** [comment]
Changing runway attribute to Asphalt as per AirNav.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20868454/e5fdc97a-ba21-11e6-81c1-040b82d99fe8.png)

**Comment by Czechoslovaki** [comment]
I'll rework this.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106361845-43d50980-62e5-11eb-817d-e7b5dd6cf880.png)
