### ISSUE TITLE
UWWT

### ISSUE THREAD

**Issue by ErshovlaD** [InfiniteFlightAirportEditing/Airports#1191]
Being redone

**Comment by kilt46** [comment]
SE region does NOT look like a part of the airport!
![image](https://cloud.githubusercontent.com/assets/14023167/19213321/e1a55354-8d2e-11e6-835c-064178737f06.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19213323/f668c4d8-8d2e-11e6-9591-cce4f0b92357.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19254736/a918b63a-8f1c-11e6-8d05-495bdbae48ee.png)
