### ISSUE TITLE
HESH

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#1194]
Sharm El Sheikh International Airport

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19220514/973f204e-8df4-11e6-952c-81eb9ab83918.png)

**Comment by MBeringuy** [comment]
Buildings removed.

![Untitled-1](https://user-images.githubusercontent.com/32115399/59394993-3a85da80-8d58-11e9-98c1-9ed3c3e93f10.jpg)
