### ISSUE TITLE
MPSM

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1195]
Doing this airport from scratch. Río Hato "Scarlett Martínez" Int'l Airport. Using the MPHR file, updated the code to MPSM, Bing image also blurry.

**Comment by brunocr98** [comment]
Sent for review.

**Comment by brunocr98** [comment]
Changes sent for review.

**Comment by dushyants19** [comment]
new folder made

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19334015/a7fc5164-90be-11e6-8e1a-1ab52afa00df.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112719102-021ba600-8ec5-11eb-921e-a36c2579477f.png)
