### ISSUE TITLE
MMPQ-Palenque International Airport-CHIAPAS-MEXICO

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#1196]
Being redone

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19213192/4c23506e-8d2a-11e6-8d4c-9359b4eed097.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22400957/98935c44-e588-11e6-847e-41b481808c8b.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22400963/af6f030a-e588-11e6-90f8-f1bb73f38413.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22400970/c37dc1a6-e588-11e6-88b7-e976ce691ee4.png)

**Comment by moritzbabl** [comment]
new airport has been edited

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23194099/cb375208-f871-11e6-94b2-e1de88bce0ce.png)
