### ISSUE TITLE
FMCH-Prince Said Ibrahim Airport-NJAZIDJA-COMOROS

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#1197]
Being redone

**Comment by PaulNielsen** [comment]
Done

**Comment by kilt46** [comment]
This has NOT been done
![image](https://cloud.githubusercontent.com/assets/14023167/19220633/3eae9ab0-8df7-11e6-86ff-69eb1723bc9b.png)

**Comment by PaulNielsen** [comment]
HMm, let me look into it.

**Comment by PaulNielsen** [comment]
https://github.com/InfiniteFlightAirportEditing/Airports/blob/august2016/Comoros/FMCH/apt.dat

@kilt46 Have a look again, it is there.

**Comment by kilt46** [comment]
Got it sorry, didnt have August selected

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19220788/21126e92-8dfb-11e6-9e0f-bfdb72f7ad34.png)
