### ISSUE TITLE
VOHS - Rajiv Gandhi International Airport-TELANGANA-INDIA

### ISSUE THREAD

**Issue by sumith11** [InfiniteFlightAirportEditing/Airports#1198]
Airport serving Hyderabad. I'm re-doing this one.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19405075/474b4d3a-9239-11e6-9898-03dfd2d72c1a.png)
![image](https://cloud.githubusercontent.com/assets/14023167/19405079/5105dc82-9239-11e6-8538-74c5d3b9f556.png)

**Comment by Czechoslovaki** [comment]
I'm gonna give this airport a massive overhaul. Between the last time this was edited and now, Hyderabad airport has changed a lot, and by a lot I mean there are new aprons (aka massive chunks of the airport) that are currently missing. Also, most of the airport doesn't look accurate with imagery, buildings need to be removed, and the atc frequencies and the runways are somewhat whacked.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104968548-c7206200-59ab-11eb-8fb0-ecb6392c01f8.png)
