### ISSUE TITLE
PHLI-Lihue Airport-HAWAII-USA

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#1199]
Lihue Airport. I will be re-doing this one.

Both runways are not longer than 10k feet.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by dushyants19** [comment]
accepto

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19406014/1aae8728-9244-11e6-8cc8-033a4addd738.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46589636-92ee3500-ca71-11e8-8e40-3cf1521a1ceb.png)
