### ISSUE TITLE
KPSP-Palm Springs International Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#12]

**Comment by IceBlue02** [comment]
Class Bravo with only 8 Spawn Points! One of the most used as well.

Redoing this.

**Comment by IceBlue02** [comment]
Would someone reopen please :-P

**Comment by Swang007** [comment]
Looks like you're a collaborator already. You should be able to open/close yourself?

**Comment by JohnPreston21** [comment]
Is this one actually beging redone?

**Comment by JohnPreston21** [comment]
NVM is i see, sorry.

**Comment by JohnPreston21** [comment]
NVM is see sorry.

**Comment by kilt46** [comment]
Completed by IceBlue

**Comment by dushyants19** [comment]
Blue lights inside buildings. from #721

**Comment by samuelandersson** [comment]
Removed blue lights that were in the vicinity and inside buildings.

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/bae18597aa28c9c79eb75f14e2f65085aa52287f)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19413671/64f6b192-92f9-11e6-944b-295a8cbe956a.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68349815-29f64800-00dd-11ea-97a3-2871c62d17f1.jpg)
