### ISSUE TITLE
KSQL

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#120]
Runway lighting has issues

**Comment by carmichaelalonso** [comment]
had a quick look, awaiting results.

**Comment by dushyants19** [comment]
Removing Hold Short spawns :grinning:

**Comment by dushyants19** [comment]
Removed White Lines & Hold short Spawns. 
Approved by Jonathan.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20908872/8d6e9e7c-bb1d-11e6-8e3c-f8b58baf1b32.png)
