### ISSUE TITLE
EGPT-Perth/Scone Airport-SCOTLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by Vladimir35028B** [InfiniteFlightAirportEditing/Airports#1201]
Russia, Vnukovo international airport (VKO)

**Comment by dushyants19** [comment]
Duplicate. What are you doing btw, @Vladimir35028B ?

Contribute in #1181

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19254435/1bde0a7a-8f19-11e6-8d8b-97a7a575d617.png)

**Comment by dushyants19** [comment]
beautiful airport you forgot to close issue @kilt46
