### ISSUE TITLE
MROC-Juan Santamaria Airport-ALAJUELA-COSTA RICA

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#1202]
San José, Costa Rica

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19951704/d5e49d50-a12d-11e6-99cd-5a56c95c7cb5.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53683431-5a702180-3cc6-11e9-863f-add29ef4e3a4.png)

**Comment by brunocr1050** [comment]
@zhf21 will be updating the layout of the airport.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104135128-a32da280-5353-11eb-859a-d54637b60763.png)
