### ISSUE TITLE
MPDA-Enrique Malek Airport-CHIRIQUI-PANAMA

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1205]
Doing this airport. David "Enrique Malek" Int'l Airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19371612/248c23ec-917a-11e6-826c-de949e095e4d.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59853253-db6f2980-9346-11e9-938c-cf175639fa71.jpg)

**Comment by brunocr1050** [comment]
Pushed some updates to the airport

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112718999-6ee27080-8ec4-11eb-90c9-3a948b8043cf.png)
