### ISSUE TITLE
LLBG-Tel Aviv Ben Gurion Airport-HAMERKAZ-ISRAEL

### ISSUE THREAD

**Issue by ErshovlaD** [InfiniteFlightAirportEditing/Airports#1206]
Being redone
3 runways (10 000 ft>)

**Comment by Urielmazoz** [comment]
Just for curiosity. Did you guys have any progress with this airport?

**Comment by ErshovlaD** [comment]
![image](https://cloud.githubusercontent.com/assets/22447757/21295429/5ec7bfc6-c56e-11e6-948a-3735bdcfb0c8.png)
I'm focusing on Russian airports right now. that's progress

**Comment by Urielmazoz** [comment]
Thanks for answering. It looks good. Hope you return working on it, I can't wait to see it done :)

**Comment by brunocr98** [comment]
I'll take care of this airport once I finish with Larnaca.

**Comment by brunocr98** [comment]
Up for grabs.

**Comment by ReflexRSM** [comment]
I'll take this one.

**Comment by dushyants19** [comment]
Any progress? @sumith11

**Comment by sumith11** [comment]
Making a slow progress on this 😅
Airport will be completed before June 20. Sorry for the delay I've been a bit busy.

**Comment by moritzbabl** [comment]
Added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28097115-5814639a-6673-11e7-9aa8-9b5278c9ff48.png)

**Comment by MajorTomMueller** [comment]
According to @royfr83 this airport needs an update including building removal, frequencies are outdated, some spawns are missing, some aprons are disused, etc.

Official AIP:
http://en.caa.gov.il/index.php?option=com_content&view=article&id=414&Itemid=278

**Comment by royfr83** [comment]
Fixes sent for official review.

**Comment by royfr83** [comment]
**For future reference purpose:**
Once updated imagery is available, the following needs to be added - 
1. Terminal 3 gates D2, D3
2. Terminal 3 gates E2 to E9
3. Apron H in its entirety.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51091325-f5c92980-174e-11e9-9e8b-f30cc29eb9c8.png)

**Comment by ECoops-123** [comment]
@OscarConklin  will be redoing the airport.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104818623-597b0700-57ee-11eb-885d-c0e1c04b1001.png)
