### ISSUE TITLE
RJFR-Kitakyushu Airport-FUKUOKA-JAPAN

### ISSUE THREAD

**Issue by ryangreene15** [InfiniteFlightAirportEditing/Airports#1208]
♻️

**Comment by dushyants19** [comment]
😱

**Comment by dushyants19** [comment]
@ryangreene15 any progress?

**Comment by ryu12332** [comment]
ISSUE: Excess nodes and snapping errors.

**Comment by MajorTomMueller** [comment]
-service road and boarder straightened to reduce vertices
-snapping fixed
-H in Helispots removed
-road marking under piers removed

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/35177513-9e87c11e-fd45-11e7-8128-fa8160f3cf8c.png)

**Comment by MajorTomMueller** [comment]
-Boundary fixed
-Buildings removed
-Hangar floors added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48674193-17bb7c80-eb0f-11e8-8a0f-5aa05cc33d73.png)
