### ISSUE TITLE
URWW

### ISSUE THREAD

**Issue by ErshovlaD** [InfiniteFlightAirportEditing/Airports#1209]
Being redone
Priority 2 (10 000> ft runway)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19614118/525bd324-97b7-11e6-9cbc-9e85b80cfbea.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44754080-0ea9a900-aae6-11e8-852a-f2ce88e07418.png)
