### ISSUE TITLE
MMAS-Aguascalientes-Jesus Teran Int Airport-AGUASCALIENTES-MEXICO

### ISSUE THREAD

**Issue by Epadilla1** [InfiniteFlightAirportEditing/Airports#1210]

**Comment by dushyants19** [comment]
@Epadilla1 please dont close issues.

**Comment by Epadilla1** [comment]
Sorry, I'll working on this project once done with MMLO, would you please ming adding me as assignee please. Thanks!

**Comment by dushyants19** [comment]
@Epadilla1 any progress?

**Comment by Epadilla1** [comment]
Still working on it, sry, I work at a slow pace

**Comment by moritzbabl** [comment]
Is there any progress?

**Comment by lalomarlin** [comment]
@Epadilla1 ?

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26061667/32684f78-394e-11e7-8494-5219d25a14ed.png)
