### ISSUE TITLE
MPBO

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1211]
Doing this airport. Bocas del Toro "Isla Colón" International Airport.

**Comment by brunocr98** [comment]
Sent for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19402242/ad9999a2-9225-11e6-8674-09641e7c699e.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112718896-e95ec080-8ec3-11eb-89b1-cbe3ad3b8820.png)
