### ISSUE TITLE
MPCH

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1212]
Doing this airport. Changuinola "Capitán Manuel Niño" International Airport.

**Comment by brunocr98** [comment]
Sent for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19402139/fc38593c-9224-11e6-95ac-7b2ebca54a4b.png)

**Comment by kilt46** [comment]
![Uploading image.png…]()
