### ISSUE TITLE
MWCR-Owen Roberts International/Grand Cayman Airport-GEORGE TOWN-CAYMAN ISLANDS

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#1213]
Owen Roberts Intl

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19403334/2e392ab8-922c-11e6-83e8-3ae6a35c1d77.png)

**Comment by liamkirky** [comment]
I asked for this to be unlocked as it needs a full rework to be completed and updating to new guidelines. E.g removing buildings.

**Comment by liamkirky** [comment]
Could I be unassigned as I’ll wait for new satellite imagery to come out then redo it as the main apron has been extended etc so I’m waiting for that before redoing it.

**Comment by PatricioAY** [comment]
Can I do it

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90314022-534acc80-ded6-11ea-8e61-1bfceb215f28.png)

**Comment by zhf21** [comment]
The airport needs an update. There are new taxiways, more gates, etc.

I’d like take this. It will be worked on as soon as LLHA is complete - approx. 3 days.

**Comment by zhf21** [comment]
![FA144DE1-49AC-493E-BA43-806A241F41EC](https://user-images.githubusercontent.com/67797012/120025016-0b58ea00-bfbe-11eb-88af-7387336fa596.png)

![750D72A1-CB3B-47E3-8178-8A14C4D43371](https://user-images.githubusercontent.com/67797012/120025064-1c096000-bfbe-11eb-90ca-36e81110bd50.png)
