### ISSUE TITLE
MPEJ

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1215]
Doing this airport. Enrique Adolfo Jimenez Airport.

**Comment by brunocr98** [comment]
Sent for review.

**Comment by brunocr98** [comment]
Changes sent for review

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19540242/9d056dee-9623-11e6-899f-31a5f8d556a0.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112718818-68072e00-8ec3-11eb-918f-3fef4b7594ef.png)
