### ISSUE TITLE
FMCZ-Dzaoudzi–Pamandzi International Airport-MAYOTTE-MADAGASCAR

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#1216]

**Comment by PaulNielsen** [comment]
Sorry if this is the old version of the airport I've done. I found some older charts and did it after them. But not sure if that's up to date today.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19401986/008e78c8-9224-11e6-95d4-b6bf66240532.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/71199621-165e0580-2275-11ea-9a6e-25f330487ed4.jpg)
