### ISSUE TITLE
MPOA

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1217]
Doing this airport. Puerto Obaldia Airport.

**Comment by brunocr98** [comment]
Sent for review.

**Comment by brunocr98** [comment]
Changes sent for review

**Comment by brunocr98** [comment]
Sent for review again

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19612627/55cd8002-97ad-11e6-8b1a-29f7c77f6f6c.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112718722-db5c7000-8ec2-11eb-872b-334f35e629a4.png)
