### ISSUE TITLE
LPAZ

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#1218]
Redoing LPAZ (Santa Maria Airport, Azores, Portugal).
Runway length is exactly 10000ft.

**Comment by bavAVIA** [comment]
Available for review on Slack.

**Comment by bavAVIA** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19626231/9e0591fc-98f2-11e6-8b0e-ecc81b67c197.png)
