### ISSUE TITLE
UMKK-Kaliningrad Khrabrovo Airport-KALININGRAD-RUSSIA

### ISSUE THREAD

**Issue by ErshovlaD** [InfiniteFlightAirportEditing/Airports#1219]
Being redone

**Comment by dushyants19** [comment]
Max 3, you are already at 4.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19837452/a22e63fe-9e87-11e6-9038-696ee2f8976b.png)

**Comment by brunocr1050** [comment]
Being updated by @AleksanderIF for the following reasons:

- Removal buildings
- Extended runway
- New runway exit
- New Apron
- update Terminal apron
- There are no remote stands 24 & 26 in present
- Add Military stands

**Comment by AleksanderIF** [comment]
![image](https://user-images.githubusercontent.com/53284798/104112285-d2b1c000-52fd-11eb-8e0d-df347f1d1581.png)
Now runway is 10990 ft

**Comment by brunocr1050** [comment]
Thank you!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104813680-5cff9580-57d0-11eb-80d8-2d2782aae99f.png)
