### ISSUE TITLE
RJSY-Shonai Airport-YAMAGATA-JAPAN

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#1221]
♻️

**Comment by GiacomoLaw** [comment]
Happy to be doing this!

**Comment by GiacomoLaw** [comment]
Sorry, I don't have time to do this at the moment. 😢

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by Will171** [comment]
![screenshot_7](https://cloud.githubusercontent.com/assets/16463484/20565333/0b0219fc-b189-11e6-97dc-13cbd90b7642.png)

**Comment by dushyants19** [comment]
ok

**Comment by liamkirky** [comment]
I'll be doing this one just a quick one

**Comment by brunocr98** [comment]
Disponible.....

**Comment by MajorTomMueller** [comment]
nice GA airport, well documented

http://www.fairoaksairport.com/pdfdownloads/UKAIP%20EG%20AD2EGTF-PLAN.pdf

http://www.fairoaksairport.com/pdfdownloads/UKAIP%20EG%20AD2EGTF-CHART.pdf

Hi quality Google an Bing images, but a cluttered Apron.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36946264-cb7fb7ba-1f7f-11e8-883e-92e1f42a63e0.png)
