### ISSUE TITLE
MPVR-El Porvenir Airport-GUNA YALA-PANAMA

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#1222]
Doing this airport. El Porvenir Airport.

**Comment by brunocr98** [comment]
Sent for review.

**Comment by brunocr98** [comment]
Changes sent for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19612779/2a44843e-97ae-11e6-829e-584a1d79aec4.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112718584-0d210700-8ec2-11eb-8dd7-405009d80f39.png)
![image](https://user-images.githubusercontent.com/14023167/112718592-14e0ab80-8ec2-11eb-802b-8e3e951ebf99.png)
Looks like a concrete runway!
