### ISSUE TITLE
08D-Stanley Municipal Airport-NORTH DAKOTA-USA

### ISSUE THREAD

**Issue by Adam167** [InfiniteFlightAirportEditing/Airports#1223]
♻️

**Comment by unitedfc** [comment]
I fix it

**Comment by dushyants19** [comment]
Any Progress? @unitedfc

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by MajorTomMueller** [comment]
GA Airfield
http://www.wellesbourneairfield.com/dataandmap.htm

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/35542983-5f534f8c-0528-11e8-94a3-6f2409d1333b.png)
