### ISSUE TITLE
EGPU-Tiree Airport-SCOTLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by JonathanAirbus** [InfiniteFlightAirportEditing/Airports#1226]
Missing hold short lines for runway 26R

**Comment by TristinWoolf** [comment]
Please record issues for any airports in their separate issue. Please do not create new issues. Continue in #54.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22175256/20017530-dfb7-11e6-95d0-fa1749c64451.png)
