### ISSUE TITLE
XUMH

### ISSUE THREAD

**Issue by ErshovlaD** [InfiniteFlightAirportEditing/Airports#1228]
Being redone

**Comment by IceBlue02** [comment]
Just to confirm this is Chernoi air base?

**Comment by ErshovlaD** [comment]
Chernoe Air Base


Chernoe* 
Not Chernoi Понедельник, 17 октября 2016, 22:09 +04:00 от Ewan Massey <notifications@github.com>:

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20029976/75820e9a-a329-11e6-986b-dcce81a529d8.png)
