### ISSUE TITLE
LFMU-Beziers Vias Airport-LANGUEDOC-ROUSSILLON-FRANCE

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#1229]

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19498449/8486aa44-9556-11e6-9414-ffdb26c5bb73.png)
MISSING GATES AS PER NAVIGRAPH

**Comment by PaulNielsen** [comment]
It looks like the apron has been extended, but isn't shown on current images. If someone can do it, go ahead. But I can't figure this out

**Comment by dushyants19** [comment]
'Parking' in spawn names too. 

@PaulNielsen arent you supposed to know this?

**Comment by dushyants19** [comment]
There is imagery btw @PaulNielsen. Check GEarth

**Comment by dushyants19** [comment]
Missing ILS Centerlines, wow....

**Comment by dushyants19** [comment]
You are fired. :P

**Comment by PaulNielsen** [comment]
Dush, I suck when it comes to ortophoto. I can't get it to work.

**Comment by dushyants19** [comment]
@PaulNielsen That doesnt explain ILS Centerlines, and the ramp starts' name...

**Comment by dushyants19** [comment]
Should've been fixed

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20038118/9ae47be4-a3f3-11e6-81cb-3647c57460cf.png)
