### ISSUE TITLE
WSAG (Singapore) 

### ISSUE THREAD

**Issue by Nik-Barbour** [InfiniteFlightAirportEditing/Airports#123]
Assigned to Nik Barbour 
Full rebuild required.

**Comment by Nik-Barbour** [comment]
Underway.

**Comment by Nik-Barbour** [comment]
Redone from scratch.

**Comment by JohnPreston21** [comment]
Responded to an issue with hold short spawns. Removed hold short spawns.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17270294/047fc5f8-5625-11e6-9bec-df39a063608f.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17954396/6758b818-6a40-11e6-9d1c-6cbdf9d52c0a.png)
