### ISSUE TITLE
EDDC

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#1230]
I'll do this one

**Comment by moritzbabl** [comment]
Sent for approval

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19837204/bf530d7c-9e82-11e6-93ac-98d508da93d6.png)

**Comment by kilt46** [comment]
A380 Parking
![image](https://cloud.githubusercontent.com/assets/14023167/19837207/d079813a-9e82-11e6-9893-8e45a3e63332.png)
