### ISSUE TITLE
EDMA-Augsburg Airport-BAYERN-GERMANY

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#1231]
Augsburg Airport. I will be re-doing this one. 

Runway is not longer than 10k feet.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19582330/23d9f7c4-96f9-11e6-8d00-c23215a597b7.png)
