### ISSUE TITLE
MPWN

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1232]
Airport already made, just need to be reviewed. Wannukandí Airport.

**Comment by brunocr98** [comment]
Sent for review.

**Comment by dushyants19** [comment]
Brunocr98 did this

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19614542/d2f93644-97bb-11e6-91d7-321487ecb5ce.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112718482-50c74100-8ec1-11eb-85d0-2ab345b5cce5.png)
