### ISSUE TITLE
VNKT

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#1233]
Tribhuvan International Airport, Nepal.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20465477/9b123260-af23-11e6-91b3-9887d005a406.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54882392-85faad80-4e27-11e9-97d6-ef2b44d56801.png)
