### ISSUE TITLE
OMSJ-Sharjah Airport-SHARJAH-UNITED ARAB EMIRATES

### ISSUE THREAD

**Issue by JonathanAirbus** [InfiniteFlightAirportEditing/Airports#1234]
♻️

**Comment by dushyants19** [comment]
Please search before creating an issue. This is the 3rd time you are doing this. 

Continue here #245 

A simple search  won't hurt, @JonathanAirbus

**Comment by dushyants19** [comment]
Why dont you fix it? You aren't here for just reporting minor issues

**Comment by dushyants19** [comment]
Ahh nice airport

**Comment by dushyants19** [comment]
I might do this if I have time. (DONT ASSIGN ME)

**Comment by bavAVIA** [comment]
I'm redoing this one.

**Comment by bavAVIA** [comment]
Please unassign. Has been discussed.

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by ReflexRSM** [comment]
I'll take this one

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22575030/9ceaabbe-e978-11e6-8ba4-e68a51c1c493.png)
