### ISSUE TITLE
LIPZ-Venezia/Tessera Airport-VENETO-ITALY

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#1235]
Venice Int'l Airport. I will be re-doing this one.

RWY 04R/22L is longer than 10k feet.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19912346/ce4280d8-a067-11e6-8b2e-05c290bd5ff9.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50386631-75b02680-06b0-11e9-9930-9728164658fa.png)
