### ISSUE TITLE
KPHX-Phoenix Sky Harbor International Airport-ARIZONA-USA

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1236]
Redoing this airport. Phoenix Sky Harbor Int'l Airport. The runways 8/26 and 7L/25R are >10,000ft.

**Comment by dushyants19** [comment]
great work

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19952348/9d0594c6-a132-11e6-8365-6e3bbbb4bbe0.png)

**Comment by brunocr98** [comment]
Renovation works in progress.🚧🏗👷🏻‍♂️

**Comment by brunocr98** [comment]
4 days later, it's finished.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/43677662-54adbb72-97cb-11e8-9f28-33b0f7133b2f.png)

**Comment by MBeringuy** [comment]
Terminal 3 added.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/73990830-14392e80-4929-11ea-93b2-d85787c03264.jpg)
