### ISSUE TITLE
UUMB

### ISSUE THREAD

**Issue by ErshovlaD** [InfiniteFlightAirportEditing/Airports#1237]
Being redone. 

All my airprorts which I assigned already done. Check email. 10 days gone after moment, when I send them

**Comment by dushyants19** [comment]
ok whatever

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20029696/8230529e-a321-11e6-9cff-42a224745765.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20029700/b00f675e-a321-11e6-8694-e3e7db162026.png)

**Comment by kilt46** [comment]
Issues fixed and closed
