### ISSUE TITLE
UUMW-Vatulino Airfield Airport-MOSCOW OBLAST-RUSSIA

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#1238]

**Comment by dushyants19** [comment]
ee8e96ce3971928d6e83fbc1be79d3736d46a3b4

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20161889/ffae9792-a6b6-11e6-9034-9ca9ae077b28.png)
