### ISSUE TITLE
ZB3C-Zagiel Airstrip-MOSCOW OBLAST-RUSSIA

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#1239]

**Comment by dushyants19** [comment]
Are you doing this and #1238 @ErshovlaD

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20160339/ce1d48a0-a6ab-11e6-999c-f59ca21ee895.png)
