### ISSUE TITLE
YBTL-Townsville Airport-QUEENSLAND-AUSTRALIA

### ISSUE THREAD

**Issue by jpperks** [InfiniteFlightAirportEditing/Airports#124]
Converted to YBTL

**Comment by jpperks** [comment]
Redone by John P via Email.

**Comment by JohnPreston21** [comment]
Added start ramps & Taxi Lines

**Comment by JohnPreston21** [comment]
moving engine test spawn point back a bit and removing one

**Comment by JohnPreston21** [comment]
Finished

**Comment by B777fan** [comment]
Checking this over, and it to look clean and neat.

**Comment by B777fan** [comment]
Waiting approval.

**Comment by dushyants19** [comment]
@B777fan do you want to continue with your issues?

**Comment by B777fan** [comment]
@dushyants19 sorry for the late response, I will be continuing as my keyboard has been fixed.

**Comment by samuelandersson** [comment]
Still WIP @B777fan?

**Comment by B777fan** [comment]
Yes it is, @samuelandersson.

**Comment by dushyants19** [comment]
DJ, invited you to the team. Check it out. Accept it ASAP

**Comment by dushyants19** [comment]
Still on? Been 2 months

**Comment by B777fan** [comment]
I am on it still, just haven't had enough time to finish it.

**Comment by IFAEpat** [comment]
I will do this, please disregard the amount of issues I have assigned to myself, most of them are for a project

**Comment by TristinWoolf** [comment]
@IFAEpat: DJ said he is still doing it...? Unless you have talked to @B777fan about it in PM?

**Comment by IFAEpat** [comment]
@TristinWoolf Yes, I talked to him and he said he quit editing

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19877521/e6273adc-9fad-11e6-87a7-5bec0fc09fa8.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/49342834-a3f89400-f625-11e8-8a55-9bc403c62368.png)

**Comment by kilt46** [comment]
Duplicate spawns corrected

**Comment by moritzbabl** [comment]
Needs rework to new standards - Event Airport

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/66597312-18209400-eb75-11e9-87f6-a4a704cf5998.jpg)
