### ISSUE TITLE
SBRJ-Rio De Janeiro/Santos Dumont Airport-RIO DE JANEIRO-BRAZIL

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#1240]
Santos Dumont, Rio de Janeiro

**Comment by kilt46** [comment]
NO JETBRIDGES!!!
![image](https://cloud.githubusercontent.com/assets/14023167/20247261/890e58fa-a98d-11e6-9f7f-093c554df118.png)

**Comment by JcFl4** [comment]
I didn't know they were not permitted! Is there any particular reason?

**Comment by JcFl4** [comment]
My previous airports all have them!

**Comment by bavAVIA** [comment]
Guess it's because there is no ground marking for jetbridges. We only draw taxiways on taxiways or buildings. As a jetbridge is an object, we don't add it.

**Comment by JcFl4** [comment]
That's annoying... Good to know nevertheless...

**Comment by JcFl4** [comment]
Fixed.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20250526/4d99df22-a9d5-11e6-886f-ca7f103f0e44.png)

**Comment by MBeringuy** [comment]
Airport redone.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50257940-1659ca00-03c3-11e9-8176-0937a4b0b2c0.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/79644538-f9ccce00-817f-11ea-8726-a48189ae4d4e.jpg)
