### ISSUE TITLE
MPJE

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1241]
I already made this airport, just need to be reviewed. Jaqué Airport.

**Comment by dushyants19** [comment]
done by @brunocr98 typing this cause no one cares to assign him

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19619363/cd5ad336-982a-11e6-9545-1b503fdb31a4.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112718398-ac44ff00-8ec0-11eb-8157-8d85cbd8ef2c.png)
