### ISSUE TITLE
MPLP

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1242]
I already made this airport, just need to be reviewed. Ramón Xatruch Airport.

**Comment by dushyants19** [comment]
Done by @brunocr98

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19619418/4eb7b236-982c-11e6-81d7-6eeb7096fd09.png)

**Comment by brunocr98** [comment]
This issue was recycled into SEST. The previous airport (MPLP) doesn't exist anymore.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/58844391-61078f80-864d-11e9-989d-7771f7cc4e7b.jpg)
