### ISSUE TITLE
YBSU

### ISSUE THREAD

**Issue by benschenk** [InfiniteFlightAirportEditing/Airports#1243]
Hasn't been made, please assign me here

**Comment by benschenk** [comment]
Please close, don't have time rn

**Comment by dushyants19** [comment]
Up for grabs

**Comment by Aviationluver** [comment]
I can re-do this one.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20232661/6762d8f2-a82f-11e6-9b57-973c7297f01b.png)
