### ISSUE TITLE
MPFS

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1245]
Airport already made, just need to be reviewed. Fort Sherman Airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19627134/a27516be-9905-11e6-892f-29e3fb768f88.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112718309-22953180-8ec0-11eb-9c29-b4207ca61cff.png)
