### ISSUE TITLE
MPZL

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1246]
Airport already made, just need to be reviewed. Finca 32 Airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19627157/3134e104-9906-11e6-9523-0c453de5849c.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112721608-be2f9d80-8ed2-11eb-8843-ecd388fe20b5.png)
