### ISSUE TITLE
KJAN-Jackson-Medgar Wiley Evers International Airport-MISSISSIPPI-USA

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#1247]
Redoing KJAN (Jackson - Medgar Wiley Evers International Airport), Mississippi, United States.

**Comment by bavAVIA** [comment]
Sent in for review.

**Comment by kilt46** [comment]
These gates are WRONG: Check the Satellite image!!
![image](https://cloud.githubusercontent.com/assets/14023167/19837604/17c443d8-9e8b-11e6-8e91-a5631b5e3adb.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19873200/b0d285b6-9f8b-11e6-94ed-c146c80d9064.png)
