### ISSUE TITLE
EGQL-Leuchars Airport-SCOTLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by unitedfc** [InfiniteFlightAirportEditing/Airports#1248]

**Comment by dushyants19** [comment]
Why did you close it?

**Comment by dushyants19** [comment]
Its done already btw #451 

:)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21948781/dc1a3938-d9b2-11e6-9e32-fe1254c5ba13.png)
