### ISSUE TITLE
WSSL-Singapore Seletar Airport-RIAU-SINGAPORE

### ISSUE THREAD

**Issue by jpperks** [InfiniteFlightAirportEditing/Airports#125]

**Comment by kohanson** [comment]
completed and close.

**Comment by kilt46** [comment]
not to scale. NEEDS REDRAWN!!!
![image](https://cloud.githubusercontent.com/assets/14023167/19256114/8428ba70-8f29-11e6-966a-68c3c6c0c9bb.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21742217/7e8547a2-d4af-11e6-8955-8003b5edcfb6.png)
