### ISSUE TITLE
MPCE

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1250]
Airport already made, just need to be reviewed. Alonso Valderrama Airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19836487/e5a254c8-9e6f-11e6-9a59-8e4f708ad03a.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112718200-72272d80-8ebf-11eb-9894-b5ce2c1ce5a9.png)
