### ISSUE TITLE
MPSA

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1251]
Airport already made, just need to be reviewed. Rubén Cantú Airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19749299/afd75100-9bad-11e6-8a70-de4c347a5ea0.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112718101-d1d10900-8ebe-11eb-9f34-fae83b79bcc7.png)
