### ISSUE TITLE
LIPE-Bologna Airport-EMILIA-ROMAGNA-ITALY

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#1252]
Bologna airport being redone

**Comment by PaulNielsen** [comment]
Done, sorry Kilt if some gates aren't exactly correct. As the WedBing image was not the best, I hade to draw some gates out of blind eye.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19912237/14c36bfe-a067-11e6-9a72-562dd7c3122c.png)

**Comment by dushyants19** [comment]
15ed0e838ae0187fc4902ac7cd3f5e8789bbb7ef

**Comment by dushyants19** [comment]
Improvements by @johanneskkl 

c025ed885685bc421e5f3aac112a33ab7309e727

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68905366-b9c07580-071f-11ea-94f2-eef8e74a43fb.jpg)
