### ISSUE TITLE
MPNU

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1253]
Airport already made, just need to be reviewed. Augusto Vergara Airport.

**Comment by dushyants19** [comment]
Please send all of Panama airports you have already done!

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19877473/8f68a226-9fad-11e6-96a2-8a9fe37700b6.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112705372-6b22ff80-8e6c-11eb-892d-088652ab8f37.png)
