### ISSUE TITLE
LIRA-Rome Ciampino Airport-LAZIO-ITALY

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#1254]
Rome-Ciampino Int'l Airport. I will be re-doing this one.

Runway is not longer than 10k feet.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by kilt46** [comment]
Not in repo yet

**Comment by dushyants19** [comment]
Yeah not in repo. I'll close it when I add it

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19876261/780e02e8-9fa2-11e6-8922-168972cbf314.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48982115-98e0b980-f0a3-11e8-9400-34eb41c44bd0.png)

Duplicate spawns removed. Buildings removed

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104818478-8bd83480-57ed-11eb-857c-3158300e6188.png)
