### ISSUE TITLE
UKBB-Boryspil Airport-KIEV-UKRAINE

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#1255]
Kiev Int'l Airport. This is a suggestion.

**Comment by sentikum** [comment]
Ok, I can do that.

**Comment by sentikum** [comment]
I can redo this airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20859873/a7143e98-b930-11e6-9542-d0ff450cf8fd.png)
