### ISSUE TITLE
EKSS-Samso Airport-ARHUS-DENMARK

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#1256]
Myrtle Beach Intl

**Comment by IFAEpat** [comment]
up for grabs

**Comment by IFAEpat** [comment]
Gonna retake this :)

**Comment by alchonub** [comment]
Progress?

**Comment by MajorTomMueller** [comment]
recycled

**Comment by MajorTomMueller** [comment]
![ekss-git1](https://user-images.githubusercontent.com/26853210/35442769-b69772e6-02a8-11e8-838e-2e9097c8c8c1.jpeg)
