### ISSUE TITLE
LIBD-Bari Airport-PUGLIA-ITALY

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#1258]
Bari Airport. I will be re-doing this one.

Runway is not longer than 10k feet.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by dushyants19** [comment]
you are doing nice work!

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19837489/bf599a2e-9e88-11e6-850e-d696a9addbc3.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/69554010-df4f4980-0f7f-11ea-84a8-7b842de47e00.jpg)
