### ISSUE TITLE
KSPS-Sheppard AFB/Wichita Falls Municipal Airport-TEXAS-USA

### ISSUE THREAD

**Issue by CrashTest6254** [InfiniteFlightAirportEditing/Airports#1259]

**Comment by brunocr98** [comment]
That airport was made, look the issue #399

**Comment by mbmhwue148** [comment]
I'll do it

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38471736-f46b7192-3b3a-11e8-990b-b7598e81068e.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53294598-3769dd00-37af-11e9-97fc-5f3c3ec35c8a.png)

**Comment by kilt46** [comment]
DUPLICATES SPAWNS REMOVED
