### ISSUE TITLE
KMIB-Minot AFB Airport-NORTH DAKOTA-USA

### ISSUE THREAD

**Issue by CrashTest6254** [InfiniteFlightAirportEditing/Airports#1260]

**Comment by brunocr98** [comment]
Airport also made, look the issue #143

**Comment by patspark** [comment]
ill work on it

**Comment by patspark** [comment]
I'm having a lot of trouble working on this afb as my first airport....I seek to start off with a much simpler and easy airport....pls unassign

**Comment by American232** [comment]
I will  do this one.

**Comment by American232** [comment]
Still working on this!

![kmib 12-6-17](https://user-images.githubusercontent.com/30371438/33682253-e464e5dc-da94-11e7-8c5f-1e1291cc3008.JPG)

**Comment by ChrisLevet232** [comment]
![kmib](https://user-images.githubusercontent.com/30371438/36564862-bcdafbc4-17ec-11e8-9a21-48018100265e.PNG)

Redone from scratch. Submitted for review.

**Comment by moritzbabl** [comment]
added
