### ISSUE TITLE
KSHV-Shreveport-Regional-Airport-LOUISIANA-USA

### ISSUE THREAD

**Issue by CrashTest6254** [InfiniteFlightAirportEditing/Airports#1261]

**Comment by bavAVIA** [comment]
Taking over, please assign.

**Comment by bavAVIA** [comment]
Sent for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22046254/0691f374-dce5-11e6-8bf4-06099442f67a.png)
