### ISSUE TITLE
KRDU-Raleigh-Durham-International-Airport-NORTH CAROLINA-USA

### ISSUE THREAD

**Issue by CrashTest6254** [InfiniteFlightAirportEditing/Airports#1262]

**Comment by dushyants19** [comment]
Are you requesting these airports to be done, @CrashTest6254? Or are you going to redo them?

**Comment by CrashTest6254** [comment]
I'm redoing them

**Comment by dushyants19** [comment]
@CrashTest6254 cool. Can you mail airports@liveflightapp.com so you can know the things you gotta do? :)

**Comment by dushyants19** [comment]
@CrashTest6254 any chance of mailing us? Else ill unassign you :)

**Comment by bavAVIA** [comment]
Doing this one, Priority II by the way.

**Comment by bavAVIA** [comment]
Hold on, abort mission. The X-Plane file is more accurate than I would even be able to do this 😱

**Comment by bavAVIA** [comment]
Sent for review. 😅

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21589189/e988f5a2-d0b4-11e6-85f5-ecdd88b904a9.png)
