### ISSUE TITLE
ENTC-Tromso/Langnes Airport-TROMS-NORWAY

### ISSUE THREAD

**Issue by KarlLuebs** [InfiniteFlightAirportEditing/Airports#1275]
I'll redo this one.

**Comment by dushyants19** [comment]
Any progress? @KarlLuebs

**Comment by KarlLuebs** [comment]
Hi Dush. 

First I am concentrating on getting KBIS finished. After I will finish the work on this one. If someone is very keen on doing ENTC, feel free to give it to them. Otherwise I'm getting there slowly but surly.

Happy new year!

**Comment by dushyants19** [comment]
@KarlLuebs How is this going?

**Comment by KarlLuebs** [comment]
Need more time. If its urgent, I am sorry and you can give it to someone else.

Regards.

**Comment by KarlLuebs** [comment]
@dushyants19 will start progressing on this one now

**Comment by bavAVIA** [comment]
Are you expecting to finish this anytime soon? @KarlLuebs

**Comment by KarlLuebs** [comment]
I’m sorry that I’m slightly slow at editing.

But the airport is coming, no worries.

**Comment by bavAVIA** [comment]
No worries, just wanted to know if this is being worked on.

**Comment by MajorTomMueller** [comment]
Please assign me

**Comment by moritzbabl** [comment]
This airport is currently in review already, Karl should be able to complete the fixes soon

**Comment by MajorTomMueller** [comment]
Ok

**Comment by KarlLuebs** [comment]
The airport is basically done. One more fix to do.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33242503-c1dfe30a-d29b-11e7-9e26-cf221fc3cc4f.png)

**Comment by brunocr98** [comment]
Jens will be re-working this airport.

**Comment by JensSeverin** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/77346779-8ae18e00-6d15-11ea-82df-91b7067c74a3.jpg)
