### ISSUE TITLE
LIRP-Pisa Airport-TOSCANA-ITALY

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#1276]
Pisa Int'l Airport. I will be re-doing this.

Both runways are not longer than 10k feet.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19953685/da229eec-a13e-11e6-892b-b2a93af29203.png)

**Comment by MajorTomMueller** [comment]
reworking to latest standards while processing project Italy.

**Comment by MajorTomMueller** [comment]
https://github.com/InfiniteFlightAirportEditing/Airports/commit/c3aeecfe6f28de08cfa7088aa7d41371807dad11

![LIRP-git](https://user-images.githubusercontent.com/26853210/70931260-f2a97e00-202e-11ea-87bb-cd800de33a75.png)
