### ISSUE TITLE
KDSM-Des Moines International Airport-IOWA-USA

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#1278]
KDSM - Des Moines International Airport, IA, United States, being redone.

**Comment by bavAVIA** [comment]
Please unassign. Lost all files on my laptop including the progress on this one. Can't motivate myself to do this one anymore.

**Comment by dushyants19** [comment]
Motivation you can do it! You can export it

**Comment by bavAVIA** [comment]
I never sent KDSM to anyone and I lost all files on my laptop.
I mean, I would restart it if I only had a bit of it before, but seriously - all the lines and pavement were 90% finished. No sorry.
Unassign.

**Comment by Hamza787Aj** [comment]
I'm redoing this one

**Comment by TristinWoolf** [comment]
@Hamza787Aj you are not currently on our GitHub team. Please send an email to airports@liveflightapp.com and Dush will get you set up.

**Comment by dushyants19** [comment]
invited

**Comment by dushyants19** [comment]
@Hamza787Aj  any progress?

**Comment by Yifan081** [comment]
Will you do this one Simon? Otherwise I could do it

**Comment by bavAVIA** [comment]
I was planning to at some point, but I have plenty airports I want to finish before.
Go ahead :)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24072919/6be9c836-0bbc-11e7-9a4a-2a0762de55f6.png)

**Comment by MBeringuy** [comment]
#4897

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/88455623-74bb1a00-ce3c-11ea-8699-40873d8974fd.png)
