### ISSUE TITLE
KBFI-Boeing Field/King County International Airport-WASHINGTON-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#128]
Typo on parking spot name

**Comment by kilt46** [comment]
Bravo Airport. Could do with Terminal Buildings and ALL Gates

**Comment by dushyants19** [comment]
Was this ever redone? 

@HenrikBerg02 said @Swang007 re-did this.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20859120/5741fa3c-b91b-11e6-9546-97bffad57f3c.png)

**Comment by MajorTomMueller** [comment]
Full redo

**Comment by Czechoslovaki** [comment]
Sent For OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/88733915-7d8e4300-d0fd-11ea-892d-fafa7b0a85d2.png)
