### ISSUE TITLE
GABS

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#1280]
Modibo Keita / Senou Airport - Bamako, Mali being redone.
Priority 2 Airport.

**Comment by bavAVIA** [comment]
> Priority 2 Airport.

**Comment by bavAVIA** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20237673/29d9c6b0-a89f-11e6-9c70-f72e872218da.png)
