### ISSUE TITLE
KBHM-Birmingham-Shuttlesworth International Airport-ALABAMA-USA

### ISSUE THREAD

**Issue by Tbynum94** [InfiniteFlightAirportEditing/Airports#1282]
Requesting to complete Birmingham-Shuttlesworth International Airport.

**Comment by IceBlue02** [comment]
Permission granted ;)

lol

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by bamaflying** [comment]
What does it means up for grabs. Sorry I haven't been able to do much I've had final exams at school but I'm going to be more active.

**Comment by dushyants19** [comment]
@bamaflying what are you talking about? Trae wanted to do it, but he couldn't. If you want to do, please email airports@liveflightapp.com

**Comment by lolo31r** [comment]
redoing this

**Comment by acaplash19** [comment]
Still needs to have Terminals A, B Added, along with A Gates. and B Gates. C gates are no longer in use at the airport at this time in real life. (2018 April). I can take this if needed.

**Comment by ryu12332** [comment]
It's clearly assigned to someone right now. _If_ it becomes a suggestion, then you can comment to take it. Right now it's being edited.

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by Martijn-Decates** [comment]
i want to rework this airport!

**Comment by Martijn-Decates** [comment]
I'm not going to make this airport. because it is too big an airport for me. I have no experience with large passenger airports. and I don't want to claim it for later! so if someone wants to make it now go ahead! if nobody has made it I will make it later if I have more experience!

**Comment by MBeringuy** [comment]
@Martijn-Decates I'll unassign you. If you want to edit it in the future, please contact a supervisor to assign it to you.

**Comment by PatricioAY** [comment]
Can i take it?

**Comment by brunocr98** [comment]
Please join our team in order to be assigned.

**Comment by PatricioAY** [comment]
i already join it

**Comment by brunocr98** [comment]
It seem you haven't accepted the github invitation, that should've been sent to you via email. Anyway, you'd probably choose a smaller airport.

**Comment by brennanhackard** [comment]
Can I be assigned?

**Comment by brennanhackard** [comment]
- Submitted for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68997632-52bdd080-0887-11ea-9405-2f8674038df7.jpg)
