### ISSUE TITLE
KGSP-Greenville Spartanburg International Airport-SOUTH CAROLINA-USA

### ISSUE THREAD

**Issue by crashtest25** [InfiniteFlightAirportEditing/Airports#1283]

**Comment by IceBlue02** [comment]
@crashtest25 why did you close this?

**Comment by dushyants19** [comment]
Please mail airports@liveflightapp.com

**Comment by dushyants19** [comment]
No mail, up for grabs

**Comment by bavAVIA** [comment]
Taking this one over, please assign.
Priority II by the way.

**Comment by bavAVIA** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21075382/521f499a-bed6-11e6-8eea-4c30509c1949.png)
