### ISSUE TITLE
EDLW

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#1284]
Dortmund-Wickede Int'l Airport. I will be re-doing this one.

Runway is not longer than 10k feet.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19953853/ba16f808-a140-11e6-96a4-70d8e246244e.png)
