### ISSUE TITLE
HTZA-Abeid Amani Karume International Airport-ZANZIBAR-TANZANIA

### ISSUE THREAD

**Issue by tsarkov90** [InfiniteFlightAirportEditing/Airports#1285]
Zanzibar Airport

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19889282/15166ec2-a002-11e6-8932-a2c219220777.png)

**Comment by Czechoslovaki** [comment]
I'd like to edit this airport. All 3 of my other airports are in OR.

**Comment by Czechoslovaki** [comment]
Sent for OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/80316898-ef8d7e00-87d6-11ea-9975-9c83a34157c9.jpg)
