### ISSUE TITLE
EFTU 

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#1286]
Turku Airport, Finland getting a cosmetic surgery.

**Comment by dushyants19** [comment]
"cosmetic". ugh, really?

**Comment by bavAVIA** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20040351/1b56fd98-a41b-11e6-97e9-7b569dcdc45a.png)
