### ISSUE TITLE
LIEE-Cagliari-Elmas Airport-SARDEGNA-ITALY

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#1287]
Cagliari Airport. I will be re-doing this. Runway not longer than 10k feet.

**Comment by dushyants19** [comment]
you are doing some great contributions!

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20029547/bd6913a0-a31c-11e6-913f-ac501f45e0d2.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48981169-d0e1ff80-f097-11e8-9c24-79526ac2fd67.png)
Duplicate spawn removed. Buildings removed

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/69922482-5e121e00-147b-11ea-9f49-7620d3bfca34.jpg)
