### ISSUE TITLE
SAEZ-Ministro Pistarini Airport-BUENOS AIRES-ARGENTINA

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1288]
Doing this airport, Ministro Pistarini Airport. Their runways are long than >10,000ft

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20197728/8cde2f60-a766-11e6-8789-5c2d648e0342.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51440741-c440e880-1c8f-11e9-8d28-e8feb1cde4be.png)
