### ISSUE TITLE
SAWC

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#1290]
Comandante Armando Tola International Airport, Argentina

**Comment by dushyants19** [comment]
Since you commited this @JcFl4, can we close it?

**Comment by JcFl4** [comment]
Yes, sorry it was late and I forgot...

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33232140-68e22b1c-d1c6-11e7-87f2-2b0569d1a4b4.png)
