### ISSUE TITLE
HKMO-Mombasa-Moi Airport-COAST-KENYA

### ISSUE THREAD

**Issue by voosman12** [InfiniteFlightAirportEditing/Airports#1291]

**Comment by TristinWoolf** [comment]
Please search before creating issues. This is a duplicate. Continue discussion in #874.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/35766915-b69db3f0-08a6-11e8-90d2-8e5f321bbe0b.png)
