### ISSUE TITLE
SABE-Aeroparque Jorge Newbery Airport-BUENOS AIRES-ARGENTINA

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#1292]
Aeroparque Jorge Newbery, Buenos Aires, Argentina

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20993218/6b5b5be4-bcae-11e6-9f70-283fe014a7a7.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/61829990-7c6a6c00-ae40-11e9-9dc2-60f4007c5ef0.jpg)

**Comment by MBeringuy** [comment]
![sabe](https://user-images.githubusercontent.com/32115399/126220380-484e6002-bc2c-4585-8eb2-c8c7e14608a8.jpg)

**Comment by MBeringuy** [comment]
![sabe](https://user-images.githubusercontent.com/32115399/126221237-e1c7285c-1b09-4c36-bbea-aec29c65251f.jpg)
