### ISSUE TITLE
LEAM-Almeria-ANDALUCIA-SPAIN

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#1294]
Almeria airport being redone

**Comment by dushyants19** [comment]
you should do some suggestions, @PaulNielsen

**Comment by PaulNielsen** [comment]
@dushyants19 I probably should, but many suggestions are either really big airports my brain can't handle. Or airports with no Bing imagery.  Me and orthophoto don't go together really.

**Comment by kilt46** [comment]
Missing Outlines
Outline #1 
![image](https://cloud.githubusercontent.com/assets/14023167/21410520/ffd7932a-c7a6-11e6-8bac-811a68f138a0.png)
![image](https://cloud.githubusercontent.com/assets/14023167/21410539/19a6514c-c7a7-11e6-9b52-16f05b0999e6.png)

**Comment by kilt46** [comment]
Roadway and outlines
![image](https://cloud.githubusercontent.com/assets/14023167/21410560/2d7e30b8-c7a7-11e6-9a45-e59fbba8bf95.png)

**Comment by PaulNielsen** [comment]
Where did you get those pictures? As I hade to go after old Wedbing images, don't have SAS sorry :/

**Comment by dushyants19** [comment]
You should've imported orthophotos then ¯\_(ツ)_/¯

**Comment by PaulNielsen** [comment]
Fixed

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21547247/6f5b1894-cdaa-11e6-88ef-5940d25c1911.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108596167-ec0c4a00-7348-11eb-87e8-9b191d2246c2.png)
