### ISSUE TITLE
ENTO-Sandefjord / Torp Airport-VESTFOLD-NORWAY

### ISSUE THREAD

**Issue by matsedvin** [InfiniteFlightAirportEditing/Airports#1296]
Sandefjord Lufthavn Torp (ENTO) located in Sandefjord, Norway.

**Comment by dushyants19** [comment]
@matsedvin any progress?

**Comment by Hornet199** [comment]
I will do this.

**Comment by Hornet199** [comment]
Sent to review. 
Note: Runway length was change after reconstruction.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28491105-fe309d36-6eaf-11e7-90c6-9e5985bc38f2.png)
