### ISSUE TITLE
VOCI-Cochin International Airport-KERALA-INDIA

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#1297]
Cochin Int'l Airport. This is a suggestion. I do not want to re-do it.

**Comment by dushyants19** [comment]
bad.

**Comment by Aviationluver** [comment]
what's bad? @dushyants19

**Comment by dushyants19** [comment]
bad as in you made it as a suggestion and you didn't do it :(

**Comment by ReflexRSM** [comment]
I'll take this one

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22004425/22af4fc6-dc21-11e6-8661-8f83f788afc8.png)

**Comment by akshay2777** [comment]
Is it not yet completed

**Comment by dushyants19** [comment]
It is completed @akshay2777

**Comment by dushyants19** [comment]
# Airport Name

Cochin International Airport (VOCI)

# Country?

India

# Improvements that need to be made?

Adding new international terminal and parking bay

# Are you working on this airport?

 Yes

# Airport Priority? (A380, 10000ft+ Runway)

10000ft+Runway

**Comment by akshay2777** [comment]
i can't do it.

**Comment by akshay2777** [comment]
Iam doing this one.almost completed

**Comment by brunocr98** [comment]
Unfortunately we are unable to assign you because you are not part of this team. Please send an email to contact@airportediting.com to reapply.

**Comment by akshay2777** [comment]
now iam part of this please assign me

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51220246-0b2e8700-18fa-11e9-8edb-51a3fe6c23be.png)
