### ISSUE TITLE
CYHZ

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#1298]
Halifax Int'l airport. I will be re-doing this one. 

Runway 05/23 is longer than 10k feet.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20198764/04e675a8-a76c-11e6-9036-a1eba793586c.png)
