### ISSUE TITLE
EGBB-Birmingham Airport-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#13]

**Comment by carmichaelalonso** [comment]
Given you this Nik, thought you might want a British airport for a change :)

**Comment by Nik-Barbour** [comment]
Starting EGBB 08 Jan

**Comment by carmichaelalonso** [comment]
Nik's moving on to pastures new now, Jonathan can have this

**Comment by Nik-Barbour** [comment]
Sounds like I'm about to pass away - I've just spotted another I fancied first in Seattle is all. :-) 

Good luck Jonathan, your other UK assignments have looked great BTW.

**Comment by IFAEpat** [comment]
Runway is being extended and I am redoing this

**Comment by IFAEpat** [comment]
Done and done.

**Comment by IFAEpat** [comment]
Google earth has updated, will make extra adjustments :)

**Comment by IFAEpat** [comment]
Actually, seems misaligned a bit...

**Comment by IFAEpat** [comment]
Realigned and added missing features

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17249434/8891447c-5565-11e6-94f5-a1fbab14bebd.png)

**Comment by IFAEpat** [comment]
Needs to be re-cataloged with the proper "mini image"

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17385438/54743a2c-59a8-11e6-9f70-62bf5f35a758.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17385444/5e39db0c-59a8-11e6-9779-488a7074792b.png)

**Comment by kilt46** [comment]
Will is fixing median lines

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32756776-6db990cc-c8a1-11e7-87a0-20341f762222.png)

**Comment by kilt46** [comment]
Redone by Will
![image](https://user-images.githubusercontent.com/14023167/34079812-b1308216-e2fa-11e7-80c4-ef23e9181d23.png)

**Comment by kilt46** [comment]
Redone by ItsWill
![image](https://user-images.githubusercontent.com/14023167/36064742-ebb22bbc-0e54-11e8-83ef-24a03da34828.png)
