### ISSUE TITLE
KSAN-San Diego International Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#130]

**Comment by JohnPreston21** [comment]
Fixing Cargo Ramp Spot 4's spawn point

**Comment by JohnPreston21** [comment]
Fixed Cargo Ramp Spot 4
finished

**Comment by Swang007** [comment]
Investigation for the spawn point that is holding short of runway 27. Pilots are using it to cut ahead of other players.

**Comment by IFAEpat** [comment]
Service roads have no pavement, easy fix.

**Comment by dushyants19** [comment]
Doesnt matter.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19875615/1ddadd42-9f9c-11e6-9b27-5f6a4f917af6.png)

**Comment by brunocr98** [comment]
The airport has been renovated. New spawns, taxiways and markings were added.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25771187/10cb2ce0-3210-11e7-9ca9-a9e95b264f0b.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42914109-1f805744-8abe-11e8-988c-8db2d5d5d7a7.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/73790627-8a9a2d00-477f-11ea-894c-b755268e8aab.jpg)
