### ISSUE TITLE
FOOL

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#1300]
FOOL - Liberville International Airport, Gabon being redone.
Runway is slightly shorter than 10.000ft.

**Comment by bavAVIA** [comment]
Sent in, awaiting approval.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20247061/b7c6daa4-a989-11e6-83fb-caa2fabf0c10.png)
