### ISSUE TITLE
URFF-Simferopol International Airport-CRIMEA-RUSSIA

### ISSUE THREAD

**Issue by ErshovlaD** [InfiniteFlightAirportEditing/Airports#1301]
It is UKFF, but after annexation of Crimea this airport have other ICAO (URFF)

It need rework spawns.
Being redone
Airport priority 2 (10 000ft+)

**Comment by dushyants19** [comment]
Maximum 3 issues per person please

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20330905/75100e9e-ab67-11e6-83c3-216b7f0225d1.png)

**Comment by MajorTomMueller** [comment]
Transferred from #4902

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/82396529-817a5680-9a24-11ea-892d-a5f98df29983.jpg)

**Comment by kilt46** [comment]
Removal of buildings and tidy up
