### ISSUE TITLE
EGTB

### ISSUE THREAD

**Issue by WrenJago** [InfiniteFlightAirportEditing/Airports#1302]

**Comment by dushyants19** [comment]
Issue title as ICAO please, and @WrenJago please give some description

**Comment by Aviationluver** [comment]
I can re-do this one.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20247009/8a265da0-a988-11e6-952a-c7d735bf06fc.png)
