### ISSUE TITLE
UATT-Aktobe Airport-AQTOBE-KAZAKHSTAN

### ISSUE THREAD

**Issue by ErshovlaD** [InfiniteFlightAirportEditing/Airports#1303]
Being redone
Priority 2 (10000ft+)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21456654/64a2928e-c8ef-11e6-8cc4-2b877614d8fc.png)

**Comment by Czechoslovaki** [comment]
Updating this airport (I'm reusing all taxiways possible so it's not from scratch).

- Airport name incorrect
- Grass runways have unnecessary settings
- Main runway width incorrect
- Incorrect line types on main apron
- Buildings to be removed
- Gaps in some of the taxiway exits from the runway

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109078131-827e9980-76c2-11eb-9c9c-c89f6b15c186.png)
