### ISSUE TITLE
ETSI

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#1304]
Ingolstadt Manching Airbase
German Air Force and Airbus Defence and Space Maintenance Base
Former Transoceanic Abort Landing Site for the Space Shuttle 
Also has a small civil airfield included 

Runways not longer than 10000 feet

**Comment by dushyants19** [comment]
assigned you @moritzbabl

**Comment by moritzbabl** [comment]
Sent for approval

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20233043/43aab026-a832-11e6-98f6-4be8f5be6e65.png)
