### ISSUE TITLE
MMMT

### ISSUE THREAD

**Issue by lalomarlin** [InfiniteFlightAirportEditing/Airports#1305]
Minatitlán/Coatzacoalcos International Airport  (MTT)

**Comment by dushyants19** [comment]
what do you intend to do? @lalomarlin

**Comment by lalomarlin** [comment]
I dont get your answer.

**Comment by dushyants19** [comment]
@lalomarlin you want to redo this?

**Comment by lalomarlin** [comment]
Yes

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20818451/487b383e-b7f3-11e6-8901-953234ec981d.png)
