### ISSUE TITLE
KFHB

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#1308]
Fernandina Beach Muni

**Comment by IceBlue02** [comment]
Labels @IFAEpat, come on

**Comment by IFAEpat** [comment]
@IceBlue02 oops, sorry.

Done!

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20234426/bbc639b4-a840-11e6-8ced-8ec548ca35a1.png)
