### ISSUE TITLE
ZSAM

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#1309]
Gaoqi, China.

**Comment by bavAVIA** [comment]
Didn't you already commit this? @JcFl4

**Comment by JcFl4** [comment]
Oh wow, completely forgot to close the issue... Thanks @bavAVIA

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24430450/4c0e5342-13dc-11e7-8d6f-5d2968e5e412.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/43550728-246eb72c-95aa-11e8-8839-c9ee324e7c73.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/43670591-10349c86-9753-11e8-9078-318256d5e3d0.png)
