### ISSUE TITLE
GCLP-Gran Canaria Airport-ISLAS CANARIAS-SPAIN

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#1310]
Gran Canaria, Spain

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22183057/43fdbf2a-e07a-11e6-9527-1afdcb887a3e.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68040991-4b56ce80-fcae-11e9-97ac-7e699671410f.jpg)
