### ISSUE TITLE
ETAR 

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#1312]
Ramstein Air Base, will redo this

**Comment by moritzbabl** [comment]
Sent for approval

**Comment by moritzbabl** [comment]
BTW, i forgot to mention that the airport has a 10k+ ft runway

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20460380/dc4938d8-aea5-11e6-955f-d32398c17b51.png)
