### ISSUE TITLE
DAAJ

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#1314]
Djanet - Tiska Airport, Algeria, being redone. 
Runways slightly too short for Priority II.

**Comment by bavAVIA** [comment]
Sent in for review.
Just before the 24 hours mark 😅 .

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20447463/996d8066-ada4-11e6-8f15-fa312ee82e84.png)
