### ISSUE TITLE
KMDT-Harrisburg International Airport-PENNSYLVANIA-USA

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#1315]
Harrisburg International Airport, Pennsylvania, United States - being redone.
Priority II Airport - Runway length is just one foot over 10000.

**Comment by bavAVIA** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20468253/64f7f412-af5a-11e6-94dc-8692a773a656.png)

**Comment by HiFlyerBwi** [comment]
Submitted for OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/69681063-9edcf200-108b-11ea-8297-414285c6cfc2.jpg)
