### ISSUE TITLE
ENML

### ISSUE THREAD

**Issue by scandinaviangroup** [InfiniteFlightAirportEditing/Airports#1317]
This will be my first airport that I will be editing.

**Comment by PaulNielsen** [comment]
If I am not wrong, you aren't in the Slack team. Send Airports@liveflightapp.com a email

**Comment by dushyants19** [comment]
@scandinaviangroup hows the progress?

**Comment by bavAVIA** [comment]
Quickly redid this one.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25063619/310e5f7a-21af-11e7-9b1b-82114e420aa2.png)
