### ISSUE TITLE
EDQP

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#1318]
I'll redo this small airport quickly

**Comment by IceBlue02** [comment]
Better be real quick

**Comment by moritzbabl** [comment]
Sent for approval

**Comment by IceBlue02** [comment]
Damn that was quick, GJ

**Comment by moritzbabl** [comment]
Doing it was even quicker 😉

**Comment by dushyants19** [comment]
But you missed some key things :(

**Comment by moritzbabl** [comment]
Sent again, just forgot to change the export target 👀

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20446903/7e641378-ada1-11e6-891f-898bcc436cc1.png)
