### ISSUE TITLE
VOML-Mangalore/International Airport-KARNATAKA-INDIA

### ISSUE THREAD

**Issue by sumith11** [InfiniteFlightAirportEditing/Airports#1319]

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20446472/601b0464-ad9f-11e6-9f0e-119255007e46.png)

**Comment by MajorTomMueller** [comment]
1.Wrongly aligned with the imagery 
2.Wrong runway markings
3.Wrong runway lights 
4.Wrong approach lights 
5.Need to remove buildings
6.Need to remove "X"s 
7.Wrong runway width
8.Improve the gates' detailing
9.Increase number of gates
10.Wrong taxi lines need to be fixed 
11.There are unnecessary lights at a few places which need to be removed

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104398372-34e40e00-5514-11eb-85af-d50df170cfa5.png)
