### ISSUE TITLE
WIDT-Sei Bati Airport-TANJUNG BALAI-INDONESIA

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#132]
Going to make the long journeys worth it!

**Comment by carmichaelalonso** [comment]
WIBD done by Nik

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18036592/5e4d3842-6d34-11e6-99d0-1683bc7eacda.png)

**Comment by RyanEpps** [comment]
Changed to WIDT by Tom 12/28/20

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/117544753-7418fc00-afe8-11eb-867c-81d74654c54e.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/117544773-8430db80-afe8-11eb-9548-5b81285b50e7.png)

**Comment by kilt46** [comment]
Significant increase in runway length. Rework approved.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118742985-1326ca80-b817-11eb-9128-5c6692862ce2.png)
