### ISSUE TITLE
YOAS

### ISSUE THREAD

**Issue by Adam167** [InfiniteFlightAirportEditing/Airports#1321]
https://community.infinite-flight.com/t/yoas-australia-runway-orientation/78812

Runways the wrong way round , ramp start could do with a name change. It's an echo so should be a nice easy one to do.

**Comment by dushyants19** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20460299/4aa7585c-aea4-11e6-9572-6d517e9750a9.png)
