### ISSUE TITLE
MMGL-Guadalajara Airport-JALISCO-MEXICO

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1323]
Doing this airport. Don Miguel Hidalgo y Costilla International Airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20505500/21f0a6dc-b013-11e6-99b3-c79db71557f0.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/60034214-7a19c400-9680-11e9-9a96-4a72a09cd3fa.jpg)
