### ISSUE TITLE
MMMY-Monterrey Airport-NUEVO LEON-MEXICO

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1324]
Doing this airport. General Mariano Escobedo International Airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20819516/582edff4-b7fa-11e6-8fd3-fb097a1a39fa.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/60034757-b00b7800-9681-11e9-9855-fece1c0d3cc3.jpg)
