### ISSUE TITLE
KAMA-Rick Husband Amarillo International Airport-TEXAS-USA

### ISSUE THREAD

**Issue by jpperks** [InfiniteFlightAirportEditing/Airports#133]
Please edit me

**Comment by carmichaelalonso** [comment]
I'll fix this

**Comment by Yifan081** [comment]
I'd like to be assigned this one.

**Comment by Yifan081** [comment]
Sent for revision.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22531322/d375482a-e8a5-11e6-8988-04ec85cdc5ec.png)
