### ISSUE TITLE
KLBB

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#1332]
KLBB, Lubbock International Airport, Texas, USA - being redone.
Priority II Airport.

**Comment by bavAVIA** [comment]
Airport sent in to E-mail, awaiting review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21075416/545bf55e-bed7-11e6-9bd3-a59142750241.png)
