### ISSUE TITLE
SCEL-Santiago International Airport-SANTIAGO-CHILE

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1334]
Doing this airport. Arturo Merino Benítez Int'l Airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20776697/d96c3e0a-b727-11e6-846b-edc4439dbf66.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59349713-b3514c00-8cf0-11e9-9945-24e59c54c86c.jpg)
