### ISSUE TITLE
EDKA-Aachen Merzbruck Airport-NORDRHEIN-WESTFALEN-GERMANY

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#1335]
Original IF airport needs redone

**Comment by moritzbabl** [comment]
I will redo this

**Comment by moritzbabl** [comment]
Already sent for approval some days ago

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21467092/48103ad2-c9a7-11e6-8f50-3dd68414adb6.png)
