### ISSUE TITLE
EKVJ-Stauning Airport-RINGKOBING-DENMARK

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#1336]
RECYCLED ♻️

**Comment by DS2001** [comment]
I want to do this one.

**Comment by MajorTomMueller** [comment]
this one is over a year open, may be it could be recycled to EKVJ Stauning Vestjylland DENMARK witch would be my next...

**Comment by MajorTomMueller** [comment]
send to review

**Comment by MajorTomMueller** [comment]
![ekvj-overview](https://user-images.githubusercontent.com/26853210/34354667-3392b58a-ea30-11e7-8b2c-b98da7272f03.jpeg)
