### ISSUE TITLE
EDLM-Marl Loemuhle Airport-NORDRHEIN-WESTFALEN-GERMANY

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#1337]
Original IF airport. Needs redone

**Comment by lolo31r** [comment]
i´ll redo it

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21750964/ca170162-d584-11e6-8714-9bbb5795a390.png)
