### ISSUE TITLE
YWOL-Illawarra Regional Airport-NEW SOUTH WALES-AUSTRALIA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#134]
Added boundary, hole for large hangar.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18036429/8b15e04a-6d2f-11e6-8ca7-4efd962538e7.png)

**Comment by ewanfleming** [comment]
I'll do the ol' redo from the ol' scratch ye coz apparently the ol' airport needs an ol' redo ye

**Comment by ewanfleming** [comment]
By the way, this airport is in the regions.

**Comment by ewanfleming** [comment]
Sent in for review.

**Comment by ryu12332** [comment]
Would have been added 3 weeks ago if you had asked me on slack before.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34450732-6ca0465e-ecd7-11e7-9b85-0886fab55c98.png)
