### ISSUE TITLE
MUSC-Abel Santamaria Airport-VILLA CLARA-CUBA

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1340]
Doing this airport. Abel Santamaría Aiport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20818780/9fbec474-b7f5-11e6-85a3-797b290d02e5.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54872938-38842f00-4d9a-11e9-8792-1f19655a90d7.png)
