### ISSUE TITLE
EGQK-RAF Kinloss-SCOTLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#1341]

**Comment by Ralphy444** [comment]
I will do this.

**Comment by MajorTomMueller** [comment]
Ok, will care about this one.

**Comment by MajorTomMueller** [comment]
![egqk-git](https://user-images.githubusercontent.com/26853210/34730719-84d4d9ce-f560-11e7-9f1c-c7d6921d5049.jpg)
The imagery for this one was a real mess...
