### ISSUE TITLE
MUHG-Holguin Airport-HOLGUIN-CUBA

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1342]
Doing this airport. Frank País Airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20780659/4b24f978-b742-11e6-9b60-f6417c531908.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54873371-e693d700-4da2-11e9-97f4-70b3f91ad8d5.png)
