### ISSUE TITLE
MTPP-Port Au Prince Airport-OUEST-HAITI

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1343]
Doing this airport. Toussaint Louvertoure Airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20776937/31a5fa92-b729-11e6-8eeb-1a0ec4f05412.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/60684384-e0b69300-9e73-11e9-9d2d-3386aec4501e.jpg)
