### ISSUE TITLE
MKJP-Kingston/Norman Manley Airport-SAINT ANDREW-JAMAICA

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1344]
Airport made, needs to be reviewed. Norman Manley Airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20775947/3777f692-b723-11e6-9cab-5c984be1a505.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54064143-5d43a880-41d7-11e9-9338-53d908a406bf.png)
