### ISSUE TITLE
MKJS-Montego Bay Airport-SAINT JAMES-JAMAICA

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1345]
Airport made, needs to be reviewed. Sangter Airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20778376/d68fead2-b732-11e6-8b11-360f0eb1a600.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53705698-f34c8d00-3deb-11e9-8027-985e3ef4692d.png)
