### ISSUE TITLE
EGJA-Alderny Airport-CHANNEL ISLANDS-UNITED KINGDOM 

### ISSUE THREAD

**Issue by Will171** [InfiniteFlightAirportEditing/Airports#1346]
Full Redo

**Comment by Will171** [comment]
Sent for Review

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20859928/f078094c-b931-11e6-8505-854fcca74d4c.png)

**Comment by ItsW1ll** [comment]
#4621
