### ISSUE TITLE
MDPC-Punta Cana Airport-LA ALTAGRACIA-DOMINICAN REPUBLIC

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1347]
Doing this airport. Punta Cana Airport.

**Comment by dushyants19** [comment]
Duplicate, #918

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20816095/4be8d3d0-b7e6-11e6-951e-1236e36219b8.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53288277-2fc51c80-374c-11e9-9f36-da64b5394903.png)

**Comment by MBeringuy** [comment]
Updated airport.
