### ISSUE TITLE
MDSD-Las Americas Airport-SANTO DOMINGO-DOMINICAN REPUBLIC

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1348]
Doing this airport. Las Américas Airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20859945/87c3789a-b932-11e6-9829-b1b81cb43dfe.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54071338-e63afe00-4230-11e9-850c-76a186dcfc4d.png)
