### ISSUE TITLE
TTPP-Piarco Airport-TUNAPUNA-TRINIDAD AND TOBAGO

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1349]
Doing this airport. Piarco Airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20859710/076017fe-b92c-11e6-987d-fafff35bcee4.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55195995-17e21d80-517c-11e9-9b78-f01ea5c82b47.png)
