### ISSUE TITLE
WAHS

### ISSUE THREAD

**Issue by 4riw** [InfiniteFlightAirportEditing/Airports#1350]
Working on Achmad Yani Intl Airport, Indonesia. The Actual ICAO code has changed into WAHS

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20948816/a6d1a760-bbdb-11e6-9110-ed22565e2cb3.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20948825/b43926bc-bbdb-11e6-8d8d-81af0e34ca6c.png)

**Comment by kilt46** [comment]
South Terminal. A few lines missing. Also from charts maybe gates are incorrectly named?
![image](https://user-images.githubusercontent.com/14023167/46258166-778c9400-c48b-11e8-8559-b6a81004641d.png)
![image](https://user-images.githubusercontent.com/14023167/46258170-7f4c3880-c48b-11e8-917c-d45d7cdb29a2.png)
