### ISSUE TITLE
MZBZ-Philip S W Goldson International Airport-BELIZE-BELIZE

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1354]
Doing this airport. Philip Goldson Airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20949145/7f9755bc-bbdd-11e6-8d96-c48789cfe3eb.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54084255-90338c80-42fc-11e9-8f88-8da02fde20d0.png)
