### ISSUE TITLE
MRLB-Daniel Oduber Quiros Airport-GUANACASTE-COSTA RICA

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1355]
Doing this airport. Daniel Oduber Airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20949333/64c01318-bbde-11e6-8a59-76f77fa6f7f9.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53687125-56f48e80-3cf6-11e9-9f22-dc9b57dfe143.png)
