### ISSUE TITLE
MSLP-Monseñor Oscar Romero Airport-LA PAZ-EL SALVADOR

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1356]
Doing this airport. Monseñor Oscar Romero Airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20950018/95ee4cf8-bbe2-11e6-85d7-59940fcdf816.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53695144-77b3f700-3d7d-11e9-95fa-60ac55fc09c3.png)
