### ISSUE TITLE
CYYC-Calgary International Airport-ALBERTA-CANADA

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#1359]
Calgary Int'l Airport. I will re-do this one.

Runways are longer than 10k feet.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21166712/d80432b2-c16c-11e6-9520-3914fdb53ec8.png)

**Comment by ryu12332** [comment]
ISSUE: There are several parking positions missing from the airport, on Apron II, which are numbered from 200 to 211. These are located on the west and east edges of the apron itself, which can be found to the southwest of the main terminal apron, north of runway 29/11 and between the parallel runways, closer to 35L/17R.

In addition, the parking positions "Remote Apron C61" to "C64" do not exist and the markings around that area are incorrect. There is a single apron laneway that is used for aircraft on Gates 51, 53, 55, 57, as well as 70A/B, 71, 72A/B, 73, and 76, not the dual laneway that goes around the nonexistent C61-C64 positions. The aforementioned 70-series gates are located at our international terminal, and receive large aircraft.

Lastly, the large cargo apron on the far northwest end of the airport, near the threshold of runway 11, has been expanded in recent years, doubling the size of the apron. These parking positions should be relabelled from "Cargo Apron 01-05" to "Cargo Apron 900-912", once the apron is expanded to its correct size (which also includes a second entrance point further northwest). Note: stand 900 would be on the southeast end of said apron, while 912 is on the far northwest.

Furthermore, the small terminal on the far northwest end of the main apron (between the parallel runways on the north of the airport) has been expanded recently, with two gates being added, they are gate 5 and 6 for Q400 use.

Nonetheless, these issues aside, I must commend the accuracy of the rest of the airport. Keep up the fantastic work, maybe I will join your team someday :)

Alex Peterson - IFATC

[IMAGES](https://drive.google.com/drive/folders/0BxV1gM4MK9U0NWs0a3FTTEFXdUE)

**Comment by ECoops-123** [comment]
I'll spend some time on this airport for the following reasons:

* Half the airport is asphalt, 3/4 runways have the incorrect surface. (Concrete areas are on the East and terminal side)
* New Terminal markings and service road markings
* Tons of new general markings and miscellaneous bits
* New main De-icing ramp

![image](https://user-images.githubusercontent.com/59462519/115463516-cd7cdf00-a223-11eb-91ab-d906ddedd927.png)

**Comment by ECoops-123** [comment]
![Full](https://user-images.githubusercontent.com/59462519/116763564-c4ef8a00-aa15-11eb-8db2-f58d372aaa3c.png)
