### ISSUE TITLE
EDDL-Düsseldorf Airport-NORTH RHINE-WESTPHALIA-GERMANY

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#136]

**Comment by AxelBeder** [comment]
Adding 2D buildings, more lines and details.

**Comment by samuelandersson** [comment]
Still working on this one?

**Comment by kilt46** [comment]
Axel has been working this one for 3+ months. Would recommend completing or make available to another editor :)

**Comment by AxelBeder** [comment]
It's close to being finished :) 

    Le Samedi 12 décembre 2015 2h00, KIlt McHaggis <notifications@github.com> a écrit :
 

 Axel has been working this one for 3+ months. Would recommend completing or make available to another editor :)—

**Comment by Ksisky** [comment]
I'm removing Axel as an assignee, he hasn't made a commit in 4+ months.

**Comment by kilt46** [comment]
Renamed gates. This airport looks done

**Comment by moritzbabl** [comment]
@CptNathanHope added runway centerlines to one runway

**Comment by bavAVIA** [comment]
In urgent need of a complete re-do, far from current quality standards.

- Countless unnecessary and unsnapped nodes and objects
- Many missing apron spawns west to the passenger terminal
- Many unsnapped and overlapping taxiways
- Very poor detail
- Objects outside of boundary
- Missing airport beacon
- ...

Up for grabs.

**Comment by brunocr98** [comment]
I'll try to redo it then....seems interesting.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32979922-884cce42-cc23-11e7-898e-002ac23ccd70.png)
