### ISSUE TITLE
UNOO

### ISSUE THREAD

**Issue by sentikum** [InfiniteFlightAirportEditing/Airports#1360]
Omsk / Tsentralnyi Int'l airport
Omsk-Center Int'l Airport

runway - 2500 m

Being redone

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21081084/aa13aa16-bf84-11e6-8126-133bbf8429a3.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44309600-e0fa8c80-a38e-11e8-92f8-4a270a5ad694.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44309632-4babc800-a38f-11e8-8d31-6e57e2f55761.png)
