### ISSUE TITLE
KDCA-Ronald Reagan Washington National Airport-VIRGINIA-USA

### ISSUE THREAD

**Issue by Adam167** [InfiniteFlightAirportEditing/Airports#1364]
I'll redo this.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23145738/39b16cbe-f796-11e6-92a2-b0607d6f81c9.png)

**Comment by RyanEpps** [comment]
Allegedly is old and requires some tidying. My project.
