### ISSUE TITLE
WIMM-Kualanamu International Airport-SUMATERA UTARA-INDONESIA

### ISSUE THREAD

**Issue by 4riw** [InfiniteFlightAirportEditing/Airports#1366]
Medan Kualanamu Intl Airport, North Sumatra, Indonesia
with 12,300ft runway

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21081012/c8fad852-bf82-11e6-95a3-3e726851c563.png)

**Comment by kilt46** [comment]
Not quite 10,000 ft
![image](https://cloud.githubusercontent.com/assets/14023167/21081015/d94ff958-bf82-11e6-8e57-ff0133165e7e.png)

**Comment by kilt46** [comment]
Needs Cargo apron

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32134395-20f30918-bbb2-11e7-9d5d-e495be5dbf4e.png)
