### ISSUE TITLE
MGGT-La Aurora Airport-GUATEMALA-GUATEMALA

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1367]
Doing this airport. La Aurora Airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21074807/96a26afc-bec7-11e6-8131-ccdc51de0c8a.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53288446-ae6e8980-374d-11e9-913c-adc21ca94f8d.png)
