### ISSUE TITLE
MHLM-Ramon Villeda Morales International Airport-CORTES-HONDURAS

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1368]
Doing this airport. Ramón Villeda Morales Airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21075633/672d269e-bedc-11e6-96d1-33cf41e414f7.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54077861-fe883880-4283-11e9-81e6-d88a441a3d13.png)
