### ISSUE TITLE
MNMG-Augusto C. Sandino International Airport-MANAGUA-NICARAGUA

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1369]
Doing this airport. Augusto C. Sandino Airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21075525/e4a710ce-bed9-11e6-8bfb-281799fc05ef.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54072718-41c2b700-4244-11e9-8e65-20ec0a031f92.png)
