### ISSUE TITLE
UTAT-Dashoguz-DASHOGUZ-TURKMENISTAN

### ISSUE THREAD

**Issue by ErshovlaD** [InfiniteFlightAirportEditing/Airports#1372]
♻️

**Comment by ErshovlaD** [comment]
Done, check email

**Comment by dushyants19** [comment]
We know you finished it

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21481569/cc1ebafa-cb2e-11e6-9248-623cb17b910a.png)

**Comment by kilt46** [comment]
Airport no longer exists

**Comment by Czechoslovaki** [comment]
Changed to UTAT, @AleksanderIF will do this.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111088025-1b9b1600-84f3-11eb-8777-4f9bcc69b7a6.png)
