### ISSUE TITLE
OIMM-Mashhad Airport-RAZAVI KHORASAN-IRAN

### ISSUE THREAD

**Issue by AsianaIFVA** [InfiniteFlightAirportEditing/Airports#1373]
10K airport for global

**Comment by TristinWoolf** [comment]
@AsianaIFVA Are you doing this?

**Comment by dushyants19** [comment]
@TristinWoolf  I don't think so.

**Comment by Aviationluver** [comment]
I'll take this one as well. @AsianaIFVA In future, please do not create issues unless you are prepared to re-do the airport.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21750156/32483c6e-d572-11e6-9001-842fd9960496.png)

**Comment by ryu12332** [comment]
ISSUE: Runway numbers are wrong. Real is 13R/31L and 13L/31R but in IF is 14R/32L and 14L/32R
[IF SCREENSHOT](https://drive.google.com/file/d/1oSiLVtQ4JKcJvVI9wACwoTonrVw9ofeT/view)
[SAT SCREENSHOT](https://drive.google.com/file/d/1OXhnzc0Doyz8Gt2PDC_l1ECTBXeAsgYe/view)

**Comment by brunocr98** [comment]
Finally the issue has been cleared
