### ISSUE TITLE
UTTT-Tashkent Airport-TASHKENT CITY-UZBEKISTAN

### ISSUE THREAD

**Issue by liamkirky** [InfiniteFlightAirportEditing/Airports#1374]
Please edit me

♻️

**Comment by kilt46** [comment]
THIS IS A DUPLICATE ISSUE!!! PLEASE # **DO NOT** create duplicate issues

**Comment by IFAEpat** [comment]
There's no RJCJ. The 'RJCJ' and RJCC files make up the full RJCC: 

RJCJ
![screen shot 2016-12-22 at 11 23 45 pm](https://cloud.githubusercontent.com/assets/18223248/21447120/c9015c9e-c89d-11e6-90fd-372f1ebce0e1.png)
Plus...
RJCC
![screen shot 2016-12-22 at 11 24 28 pm](https://cloud.githubusercontent.com/assets/18223248/21447123/d8ec6842-c89d-11e6-9863-ad5a57c060c5.png)
...equals...
Actual RJCC
![screen shot 2016-12-22 at 11 22 15 pm](https://cloud.githubusercontent.com/assets/18223248/21447106/99997176-c89d-11e6-8f4f-9cf4a513674e.png)
...which means...
...how in the world???

**Comment by IFAEpat** [comment]
One has the ATC and half the taxiways and the other has no ATC and the other half of the taxiways.

**Comment by ErshovlaD** [comment]
I take this. 
Being redone :)

**Comment by ryu12332** [comment]
Progress?

**Comment by moritzbabl** [comment]
Member inactive, up for grabs

**Comment by ErshovlaD** [comment]
It is a pity that you excluded me from the conversation Slack.

Keep completely finished UTTT, maybe someone will correct small mistakes in it and add the airport to the database.
[apt.txt](https://github.com/InfiniteFlightAirportEditing/Airports/files/1801527/apt.txt)

**Comment by brunocr98** [comment]
“Pity” sounds quite disrespectful, doesn’t it? 

It was announced previously that there was going to be a cleanup to remove inactive users, everyone was asked to provide there username in the #github-names channel to remain in the team. You for some reason didn’t do that and so it was assumed that you wanted to leave. If you wish to rejoin just send and email and the admins will be glad to re-add you.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42415773-7e1b8aae-8220-11e8-986a-94f993db1abc.png)
