### ISSUE TITLE
SPZO-Cusco Airport-CUSCO-PERU

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#1375]
Cuzco, Peru

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22044696/8930f460-dcdb-11e6-828d-8c357165c330.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90571091-b2c70780-e176-11ea-943d-7e9aaf9440ff.png)
