### ISSUE TITLE
SPJC-Lima/Jorge Chavez International Airport-CALLAO-PERU

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#1376]
Lima, Peru

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22492654/8420b9f4-e7f0-11e6-9250-e89e4ea46832.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51793045-20b87200-2180-11e9-90aa-8240b2369477.png)
