### ISSUE TITLE
UHMA-Anadyr Airport-CHUKOT-RUSSIA

### ISSUE THREAD

**Issue by sentikum** [InfiniteFlightAirportEditing/Airports#1378]
Anadyr-Ugolny International Airport.
The eastest airport in Russia

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21167314/5790242e-c171-11e6-859d-8af15590f89e.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/43986803-8bb81f98-9cdc-11e8-86ed-4f2b44958061.png)
