### ISSUE TITLE
EDNP

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#1379]
Pfarrkirchen Airport, Bavaria, Germany.
Tiny GA airport.

**Comment by bavAVIA** [comment]
Aaaaaaand sent for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21080947/604b1e26-bf81-11e6-9e28-144aca2f1035.png)
