### ISSUE TITLE
KSDM-Brown Field Municipal Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#139]

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18033973/6f144578-6cf6-11e6-9c31-a341f49e363a.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18033979/78f45042-6cf6-11e6-8ee5-e044e2348710.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/72483410-94172180-37df-11ea-9adb-6406d2ca172e.jpg)
