### ISSUE TITLE
OIAA

### ISSUE THREAD

**Issue by AsianaIFVA** [InfiniteFlightAirportEditing/Airports#1392]
Info:
Two runways, one is around 10,000ft and the second around 7,000ft, Military/Civil airport 
Location;
Abadan, Islamic Republic Of Iran

**Comment by TristinWoolf** [comment]
If you are not going to do the airport, do NOT create an issue for it. We have enough to do already and do not want random people creating issues.

**Comment by AsianaIFVA** [comment]
I'm not doing it by the way

**Comment by dushyants19** [comment]
I dont expect you to do.

**Comment by AsianaIFVA** [comment]
Maybe after school (that en

**Comment by AsianaIFVA** [comment]
Maybe after school (that en

**Comment by AsianaIFVA** [comment]
Sorry, I meant to say: Maybe after school (which ends 6months from now in Iran,  I'll become a part of the team

**Comment by bavAVIA** [comment]
Awesome. Could you please stop randomly creating issues until then? Thanks.

**Comment by Aviationluver** [comment]
I'm taking this one.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21590555/97b8c014-d0c2-11e6-9b5c-f9b8eaec46ef.png)
