### ISSUE TITLE
CYOW

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#1393]
Ottawa Int'l airport. I will be re-doing this one.

Runway is longer than 10k feet.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21501530/4ec4d9a0-cc0e-11e6-9161-8a7179aeed55.png)
