### ISSUE TITLE
0V7-Kayenta Airport-ARIZONA-USA

### ISSUE THREAD

**Issue by ChrisAviator** [InfiniteFlightAirportEditing/Airports#1394]
♻️

**Comment by alchonub** [comment]
I’ll do this as soon as I’m done with LGTS, I’m in the Gating Stage!

**Comment by alchonub** [comment]
I thank that I can finish this before Finals

**Comment by alchonub** [comment]
Messed up imagery

**Comment by brunocr98** [comment]
The imagery provided looks perfect for me.

**Comment by alchonub** [comment]
I'll take it back in later October

**Comment by brunocr98** [comment]
Oh well, this is available in the meantime.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34700014-3af66c06-f4a6-11e7-90b5-6624cb77524d.png)
