### ISSUE TITLE
WAMM-Sam Ratulangi Airport-SULAWESI UTARA-INDONESIA

### ISSUE THREAD

**Issue by 4riw** [InfiniteFlightAirportEditing/Airports#1395]
Working on Manado Sam Ratulangi, North Celebes, Indonesia

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21482254/fa0c34da-cb36-11e6-948c-edfeb70b7d69.png)

**Comment by ECoops-123** [comment]
@adibyaputra will be updating the airport with new aprons east of the runway and removing taxiway buildings.

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/130266308-f6012da0-a5ec-467a-a45d-6e2271291504.png)
