### ISSUE TITLE
89GE-South Fulton Airport-GEORGIA-USA

### ISSUE THREAD

**Issue by gabrielasher1018** [InfiniteFlightAirportEditing/Airports#1398]
RECYCLED ♻️

**Comment by TristinWoolf** [comment]
@gabrielasher1018 Are you doing this?

**Comment by dushyants19** [comment]
@gabrielasher1018 please respond.

**Comment by gabrielasher1018** [comment]
I am very sorry, i got confused on if this was a site where you could
request fixes. But if you can, tell me how i can fix it using a application
etc, so i can do that.

thnk

**Comment by TristinWoolf** [comment]
@gabrielasher1018 Email airports@liveflightapp.com to get started.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34260469-b2075d48-e62b-11e7-8ec7-0bf7a091774d.png)
