### ISSUE TITLE
VCBI-Bandaranaike International Airport-GAMPAHA-SRI LANKA

### ISSUE THREAD

**Issue by rafiffakhri** [InfiniteFlightAirportEditing/Airports#1400]
♻️ 

Colombo

**Comment by rafiffakhri** [comment]
![eqpzryl](https://cloud.githubusercontent.com/assets/24670843/21349440/f13516a4-c6ec-11e6-97b7-5f82eec01dd1.png)

**Comment by rafiffakhri** [comment]
oh well i did on wrong app LOL

**Comment by dushyants19** [comment]
What the hell

**Comment by dushyants19** [comment]
will do

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31048045-0fc53a72-a5db-11e7-9ad4-e3a8107958d9.png)

**Comment by Balloonchaser** [comment]
Sent in for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55042334-f7408900-4ffe-11e9-8a87-cde02a12ae24.png)
