### ISSUE TITLE
EGBG 

### ISSUE THREAD

**Issue by Theobsidianguy** [InfiniteFlightAirportEditing/Airports#1401]
leiscester airport England

**Comment by TristinWoolf** [comment]
Please create issues for airports only if you are going to work on them. Creating issues on GitHub will not make them get done any faster, unless you do them yourself.

**Comment by dushyants19** [comment]
@Theobsidianguy dont worry. We wont do this and #1402

**Comment by Theobsidianguy** [comment]
i'll do it

**Comment by moritzbabl** [comment]
Should be done quickly - will do it

**Comment by moritzbabl** [comment]
done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24066213/73778422-0b3e-11e7-8dfe-6e72ea9cf527.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56097731-f42e0f80-5ebd-11e9-9a3b-493d2faadb32.png)
