### ISSUE TITLE
YBCS

### ISSUE THREAD

**Issue by Theobsidianguy** [InfiniteFlightAirportEditing/Airports#1402]
Cairns airport Australia

**Comment by dushyants19** [comment]
😒

**Comment by Aviationluver** [comment]
@Theobsidianguy Why don't you re-do it yourself?

**Comment by Theobsidianguy** [comment]
ok sorry I will start it

**Comment by dushyants19** [comment]
Please accept the repo collab invite

**Comment by Theobsidianguy** [comment]
@dushyants19 done that

**Comment by dushyants19** [comment]
Any progress? @captainmckean

**Comment by dushyants19** [comment]
Up for Grabs; Let us know if you want to do the airport.

**Comment by MajorTomMueller** [comment]
will do this

**Comment by MajorTomMueller** [comment]
Send to review

**Comment by moritzbabl** [comment]
added

**Comment by MajorTomMueller** [comment]
![ybcs-overview2](https://user-images.githubusercontent.com/26853210/32218446-2a787e52-be2b-11e7-9157-f549bb1c8293.jpeg)

**Comment by kilt46** [comment]
Duplicate spawns removed

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/49343781-ea092400-f634-11e8-8d1b-259ca37114e7.png)

**Comment by MajorTomMueller** [comment]
![YBCS](https://user-images.githubusercontent.com/26853210/54838228-626d2100-4cc8-11e9-9f4f-f84d5309ac2e.jpg)
boarder fixed
hangar floors adjusted
