### ISSUE TITLE
EKAT-Anholt Airport-ARHUS-DENMARK

### ISSUE THREAD

**Issue by bumbewildered** [InfiniteFlightAirportEditing/Airports#1407]
♻️

**Comment by MajorTomMueller** [comment]
![ekat-git](https://user-images.githubusercontent.com/26853210/34918939-eeffbdba-f95b-11e7-94c0-ade99428b2db.jpeg)

**Comment by MajorTomMueller** [comment]
boundary

**Comment by MajorTomMueller** [comment]
-Boundary fix
-Buildings removed

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46046105-6e936f80-c0e5-11e8-914b-6fe2db69eae8.png)
