### ISSUE TITLE
SBSV-Dpto L. Eduardo Magalhaes International Airport-BAHIA-BRAZIL

### ISSUE THREAD

**Issue by liamkirky** [InfiniteFlightAirportEditing/Airports#1409]
♻️

**Comment by liamkirky** [comment]
Can someone unassign me from this as my computer wont work with it.

**Comment by brunocr98** [comment]
**PLEASE DON'T CLOSE THE ISSUES UNLESS THE AIRPORT HAS BEEN APPROVED**

**Comment by brunocr98** [comment]
Up for grabs.

**Comment by liamkirky** [comment]
I'll take it again.

**Comment by dushyants19** [comment]
@liamkirky hows this going?

**Comment by liamkirky** [comment]
It’s going ok. I’ve been busy with school so haven’t had much time to edit either airport. Luckily school work is going down a bit so I’ll hopefully get time to edit again.

**Comment by liamkirky** [comment]
Hi may I be unassigned from this airport as my laptop has run out of space and I can no longer save it.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36057918-308917a2-0ddb-11e8-9e90-15ca0d9f892c.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52857229-299bc400-30ec-11e9-9a4d-12a4ea5c1335.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/60296025-878eb280-98fb-11e9-814a-436e9a1cdbfd.jpg)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/75615016-9928f980-5b1d-11ea-89e1-78700a3175d6.jpg)
