### ISSUE TITLE
EDLE-Essen Mulheim Airport-NORDRHEIN-WESTFALEN-GERMANY

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#141]

**Comment by JohnPreston21** [comment]
Adding spawn points and Taxi lines for this one

**Comment by JohnPreston21** [comment]
Finished

**Comment by kilt46** [comment]
This one needs cleaned up. taxiways not snapped, etc

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/16714764/17af5a86-4693-11e6-845a-bb259b8754d8.jpeg)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/16714782/6abc5e36-4693-11e6-8cab-e7d2d0a9cd57.jpeg)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/16714790/b5d58da2-4693-11e6-9dae-ef07a6616701.jpeg)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/16714792/cd0e6d2c-4693-11e6-81a1-5c49f6e4c27e.jpeg)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/16714816/67cdf7ec-4694-11e6-9842-e9f7689f179e.jpeg)

**Comment by kilt46** [comment]
AIRPORT REDONE

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18976227/e3950ade-8675-11e6-9083-dc7e2ddf3f11.png)
