### ISSUE TITLE
RPMZ-Zamboanga Airport-ZAMBOANGA DEL SUR-PHILIPPINES

### ISSUE THREAD

**Issue by GentlePig500** [InfiniteFlightAirportEditing/Airports#1412]
Edit taxiways, terminal and more.

**Comment by dushyants19** [comment]
You want us to do this. OK. Why won't you ask nicely? This is like commanding us.

**Comment by GentlePig500** [comment]
I will edit taxiways, terminal and other issues in the airport.

**Comment by dushyants19** [comment]
great! make sure you snap them

**Comment by GentlePig500** [comment]
Okay

**Comment by GentlePig500** [comment]
Sent For approval

**Comment by GentlePig500** [comment]
Sent For Review

**Comment by kilt46** [comment]
![Uploading image.png…]()

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22089630/132c071e-ddb2-11e6-8184-4b9c7ebf9099.png)
