### ISSUE TITLE
RPLC

### ISSUE THREAD

**Issue by superven13** [InfiniteFlightAirportEditing/Airports#1413]
Edit taxiways and all other issues.

**Comment by dushyants19** [comment]
@GentlePig500 you want to do this?

**Comment by GentlePig500** [comment]
dushyants19, Yes I want to.

**Comment by GentlePig500** [comment]
Still Editing

**Comment by GentlePig500** [comment]
Sent For Review

**Comment by superven13** [comment]
Resent For Review :)

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22713483/40e6a636-ed4e-11e6-855d-6742f2993b41.png)
