### ISSUE TITLE
EGHC Lands End Airport UK

### ISSUE THREAD

**Issue by Will171** [InfiniteFlightAirportEditing/Airports#1414]
Updating runways to asphalt and a full redo.

**Comment by Will171** [comment]
Sent for review
![screenshot_22](https://cloud.githubusercontent.com/assets/16463484/21460788/e308b4f6-c943-11e6-9bc6-7c361936aea4.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21467625/9423ca3e-c9ba-11e6-98cc-a870bfc7b389.png)
