### ISSUE TITLE
SACO-Cordoba Airport-CORDOBA-ARGENTINA

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1415]
Doing this airport. Ambrosio Taravella Airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21577662/8ebc32e8-cf28-11e6-9b14-5031bf8742fb.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55442856-f4e9ac00-5575-11e9-9fa7-0b57e31f1557.png)
