### ISSUE TITLE
SAAR-Rosario Airport-SANTA FE-ARGENTINA

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1416]
Doing this airport. Islas Malvinas Airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21589484/e3464ea8-d0b7-11e6-8470-544e0a5580a1.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55445022-f79ccf00-557e-11e9-8e01-95fbb27072ee.png)
