### ISSUE TITLE
SLVR-Viru Viru International Airport-SANTA CRUZ-BOLIVIA

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1417]
Doing this airport. Viru Viru Airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21589755/a60fb22e-d0ba-11e6-8a0a-1829eb801b8d.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56527848-ea3a8b00-6513-11e9-9d0b-c5312262494c.png)
