### ISSUE TITLE
SBCF-Belo Horizonte/Tancredo Neves Airport-MINAS GERAIS-BRAZIL

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#1418]
Doing this airport. Tancredo Neves Airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21577800/cce374b4-cf2d-11e6-8814-5a141358d394.png)
DOES NOT FIT SATELLITE IMAGE
RUNWAY LENGTH is 3000 m

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21589310/20afb9a2-d0b6-11e6-9fbd-217c24484613.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/49408504-2fefe600-f722-11e8-9d72-b14b2dcd37f7.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123346496-1308a180-d51e-11eb-8598-f9e379d69aa2.png)
