### ISSUE TITLE
SBBR-Brasilia/Pres.Juscelino Kubits Airport-DISTRITO FEDERAL-BRAZIL

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#1419]
Doing this airport. Juscelino Kubitschek Airport.

**Comment by brunocr98** [comment]
Airport done.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21751561/c0c5f62c-d58e-11e6-9a7e-511034055a2f.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52520998-39239480-2c36-11e9-842e-3f841ad13e64.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52754726-37085f80-2fc1-11e9-971c-76a86e6f6bca.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118894898-bf75b900-b8ca-11eb-91eb-e7f4eff16f1d.png)
