### ISSUE TITLE
VTBD-Bangkok Don Mueang Intl-BANGKOK-THAILAND

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#142]
John Preston editor

**Comment by JohnPreston21** [comment]
Started work on this one

**Comment by JohnPreston21** [comment]
Added taxi lines,  (jet) start points and Props start points
Finished

**Comment by carmichaelalonso** [comment]
Nice work, in the repo :)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24574313/4374c9c4-1656-11e7-992f-40f31a4d83f1.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48984001-c5083480-f0bb-11e8-8624-04427a7ecb58.png)

**Comment by kilt46** [comment]
Duplicate gates removed. Buildings removed.

**Comment by Czechoslovaki** [comment]
Reworking this.

**Comment by MajorTomMueller** [comment]
Our new reworker....

**Comment by Czechoslovaki** [comment]
- Rename ATC frequencies
- Add Asphalt, adjust paving to be correct
- Remove any unnecessary drawings (ie, golf course, roads along the outer edge)
- Adjust markings to be correct in their respective places
- Add missing gate parking positions

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/99194683-8eaf9e00-2746-11eb-849f-c1a04e0b9253.png)
