### ISSUE TITLE
KOGA-Searle Field Airport-NEBRASKA-USA

### ISSUE THREAD

**Issue by Theobsidianguy** [InfiniteFlightAirportEditing/Airports#1420]
RECYCLED ♻️

**Comment by LeonVeen** [comment]
Could I do this one?

**Comment by brunocr98** [comment]
Up fo grabs for any Aussie.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34233093-06a2a8d6-e5a9-11e7-8a33-309fd40a0d05.png)
