### ISSUE TITLE
SBPA-Porto Alegre/Salgado Filho Airport-RIO GRANDE DO SUL-BRAZIL

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1421]
Doing this airport. Salgado Filho Airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21730500/9b48578e-d415-11e6-8bd1-ebcccfaf57ce.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/74086869-f32a2800-4a65-11ea-9d69-73d00290d7bb.jpg)
