### ISSUE TITLE
SBRF-Recife/Guararapes Airport-PERNAMBUCO-BRAZIL

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1422]
Doing this airport. Guararapes-Gilberto Freyre Airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21590897/264b4a70-d0c5-11e6-96e7-292c277d67b0.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52521418-9cb0c080-2c3c-11e9-8d6f-38a4e8412d7a.png)
