### ISSUE TITLE
SKBQ-Barranquilla Airport-ATLANTICO-COLOMBIA

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1423]
Doing this airport. Ernesto Cortissoz Airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21590707/c26b3fde-d0c3-11e6-8bbf-2016a3515973.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59471738-6e253b00-8e12-11e9-9b64-862189c83335.jpg)
