### ISSUE TITLE
SKBO-El Dorado Airport-CUNDINAMARCA-COLOMBIA

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1424]
Doing this airport. El Dorado Airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21751635/ef25ce60-d58f-11e6-8caf-970d6d12a8cf.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54497835-94981080-48cd-11e9-8141-ae6c7d12f4eb.png)
