### ISSUE TITLE
SKBG-Bucaramanga Airport-SANTANDER-COLOMBIA

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#1425]
Doing this airport. Palonegro Airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21746872/0ab5778c-d51a-11e6-9779-744cb89ff1e0.png)
![Uploading image.png…]()

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21746880/4a2b10fc-d51a-11e6-86b4-4da925731b1c.png)

**Comment by brunocr98** [comment]
Fixed.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21751718/4a8fd18c-d591-11e6-9e61-2bff484b5cd3.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59701977-18afac00-91cd-11e9-8343-7c2509416a83.jpg)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122672295-82823800-d190-11eb-92be-b7ab1063e5c7.png)
