### ISSUE TITLE
SKCL-Cali Airport-VALLE DEL CAUCA-COLOMBIA

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1426]
Doing this airport. Alfonso B. Aragón Airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21751265/325fdcd0-d58a-11e6-9297-df802e22f8e9.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59606844-82a25580-90e8-11e9-9cec-0c630d2edea0.jpg)
