### ISSUE TITLE
SKRG-Jose Maria Cordova Airport-ANTIOQUIA-COLOMBIA

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1428]
Doing this airport. José M. Córdova Airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21751341/43f0e6dc-d58b-11e6-9fe6-cde10ecefd47.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54085247-fa066300-4309-11e9-8ad5-f46900e30236.png)
