### ISSUE TITLE
SKPE-Pereira Airport-RISARALDA-COLOMBIA

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1429]
Doing this airport. Matecaña Airport.

**Comment by brunocr98** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21750895/a2bf4724-d583-11e6-930b-391223e27f3c.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59701524-37617300-91cc-11e9-8cbd-7b3be3223b36.jpg)
