### ISSUE TITLE
KFLL-Fort Lauderdale/Hollywood International Airport-FLORIDA-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#143]

**Comment by Swang007** [comment]
KFLL needs a lot of fixing. Lot of objects missing, and ILS could be off a few degrees @carmichaelalonso . Probably best not to redo the whole thing, just try to fix things up, check with WEDBing, etc.

**Comment by Omari4u** [comment]
great stuff

Date: Fri, 7 Aug 2015 11:51:51 -0700

**Comment by Omari4u** [comment]
there are a few airports in South Florida with a similar ILS?GPS issue as in slightly of a few degress and no alignment

Date: Fri, 7 Aug 2015 11:51:52 -0700

**Comment by Swang007** [comment]
Checked this out with WEDBing. The northern runway is in place, but the southern runway is not. Runways are the most important thing, then you can add taxiways on and build from there. It looks like there used to be another runway that went diagonally across both, but it is closed now. From the satellite imagery it looks like there's a lot of construction going on.

**Comment by kilt46** [comment]
Taking on another big project! I'm not scared

**Comment by kilt46** [comment]
Complete redo: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=KFLL

**Comment by samuelandersson** [comment]
Removed jetbridges and white ones from buildings.

**Comment by dushyants19** [comment]
Quickly fixing the borders of holes and adding 0 to unit numbers

**Comment by dushyants19** [comment]
Done. [Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/0d97bcacca32ce472f6d95b4956a756ab0823db4)

**Comment by dushyants19** [comment]
And changed Field Elevation, from 4.6 to 64.6 [Commit](http://www.airnav.com/airport/kfll)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18607903/009e57e6-7ca0-11e6-9838-e7aea6df225d.png)

**Comment by dushyants19** [comment]
UPDATED PAPIs and runway attributes 


![image](https://cloud.githubusercontent.com/assets/13567007/18608281/b22fec10-7d02-11e6-81ab-7a1bf079e64f.png)

**Comment by ItsW1ll** [comment]
Quick fix required. Blastpad on 10L needs moving back as people keep getting speed violations when rolling for takeoff.

**Comment by bavAVIA** [comment]
Permission granted.

**Comment by brunocr98** [comment]
This airport is **not** GP2.

https://skyvector.com/airport/FLL/Fort-Lauderdale-Hollywood-International-Airport

**Comment by ItsW1ll** [comment]
Will try and do this during august as got so many issues to get through

**Comment by brunocr98** [comment]
Renovating this to deal with all the issues declared and more.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/43980712-d7a31dea-9cb4-11e8-90b4-8be890d1f551.png)
