### ISSUE TITLE
SKSP-Gustavo Rojas Pinilla Airport-SAN ANDRES Y PROVIDENCIA-COLOMBIA

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1430]
Doing this airport. Gustavo R. Pinilla Airport.

**Comment by brunocr98** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21791863/8672ce46-d6ab-11e6-8e76-1eab81e7d758.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59393837-9d28a780-8d53-11e9-8cc5-cd677e5479cf.jpg)
