### ISSUE TITLE
SEGU-Guayaquil/Jose J. De Olmedo Airport-GUAYAS-ECUADOR

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1431]
Doing this airport. José J. de Olmedo Airport.

**Comment by brunocr98** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21791554/280b1c84-d6a9-11e6-805e-b36cf7df87b1.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59853692-c5ae3400-9347-11e9-983c-47b9c2f8eeac.jpg)
