### ISSUE TITLE
SYCJ-Cheddi Jagan International Airport-EAST BERBICE-CORENTYNE-GUYANA

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1432]
Doing this airport. Cheddi Jagan Airport.

**Comment by brunocr98** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21790047/3cbeface-d69f-11e6-9fbd-9c3e7f8b5d6a.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59854232-e2973700-9348-11e9-8c8d-317a48604105.jpg)
