### ISSUE TITLE
SGAS-Luque/Silvio Pettirossi Airport-CENTRAL-PARAGUAY

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1433]
Doing this airport. Silvio Pettirosi Airport.

**Comment by brunocr98** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21787117/0180dd36-d68d-11e6-8e69-a2a7da30f732.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52166404-63270500-26d2-11e9-962b-b2c6399b8a35.png)
