### ISSUE TITLE
SPHI-Chiclayo-J A Gonzales Airport-LAMBAYEQUE-PERU

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1434]
Doing this airport. José A. Quiñones Airport.

**Comment by brunocr98** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21829485/d6cb7a90-d75b-11e6-8dbf-7a9e32e4c3ce.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/60200617-d7e31300-981c-11e9-8a7b-aeb887f171f1.jpg)
