### ISSUE TITLE
SUMU-Montevideo/Carrasco L Berisso Airport-CANELONES-URUGUAY

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1435]
Doing this airport. Cesáreo L. Berisso Airport.

**Comment by brunocr98** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21829663/104f3ed6-d75d-11e6-87b9-6d5201718f9c.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51645734-2cffbd80-1f3b-11e9-9d0a-571980ab277b.png)
