### ISSUE TITLE
SVMC-Maracaibo/International La Chinita Airport-ZULIA-VENEZUELA

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1436]
Doing this airport. La Chinita Airport.

**Comment by brunocr98** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21873656/a6fa06f8-d835-11e6-8623-9ab3ec1225ff.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54888023-65524800-4e67-11e9-8cd1-6c20a63bdf5a.png)
