### ISSUE TITLE
SVVA-Valencia Airport-CARABOBO-VENEZUELA

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1437]
Doing this airport. Arturo Michelena Airport.

**Comment by brunocr98** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21911638/3d10b3ba-d8e7-11e6-99ca-f46aa2ef6d74.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54887522-ffaf8d00-4e61-11e9-90ef-f13b11c5de73.png)
