### ISSUE TITLE
KTUS

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1438]
Doing this airport. Tucson Airport.

**Comment by Theobsidianguy** [comment]
@brunocr98  are you seriously doing all of these? #1415 #1416 #1417 #1418 #1419 #1421 #1422 #1423 #1424 #1425 #1426 #1427 #1428 #1429 #1430 #1431 #1432 #1433 #1434 #1435 #1436 #1437

**Comment by bavAVIA** [comment]
You don't know Bruno. Yes. Yes he will.

**Comment by brunocr98** [comment]
@Theobsidianguy, yes I'll do them all.

**Comment by brunocr98** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21944333/39b51472-d99b-11e6-9367-8111ee8e2134.png)
