### ISSUE TITLE
KRKS

### ISSUE THREAD

**Issue by DarlanFernandes** [InfiniteFlightAirportEditing/Airports#1439]
RECYCLED ♻️

**Comment by brunocr98** [comment]
Up for grabs. (The user originally assigned has been removed due to inactivity)

**Comment by bavAVIA** [comment]
Recycled. Now Rock Springs - Sweetwater County Airport. Doing this soon, don't take over.

**Comment by bavAVIA** [comment]
Taking over.

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26276076/9546e416-3d35-11e7-9683-c439401ad25f.png)
