### ISSUE TITLE
EGKE

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#144]

**Comment by JohnPreston21** [comment]
I would like to edit this one

**Comment by JohnPreston21** [comment]
Adding a few more spawn points and basic taxiways

**Comment by kilt46** [comment]
simple airfield

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20037580/0fb92fc0-a3e8-11e6-9858-e82687c9e66d.png)
