### ISSUE TITLE
HBBA

### ISSUE THREAD

**Issue by DarlanFernandes** [InfiniteFlightAirportEditing/Airports#1440]

**Comment by brunocr98** [comment]
Up for grabs. (The user originally assigned has been removed due to inactivity)

**Comment by bavAVIA** [comment]
Recycled. Now Bujumbra Int'l Airport. Doing this soon, don't take over.

**Comment by bavAVIA** [comment]
Taking over.

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25877376/cd3025ae-34e8-11e7-80cd-cfe2d0fc573d.png)
