### ISSUE TITLE
EPRZ

### ISSUE THREAD

**Issue by DarlanFernandes** [InfiniteFlightAirportEditing/Airports#1441]

**Comment by brunocr98** [comment]
Up for grabs. (The user originally assigned has been removed due to inactivity)

**Comment by bavAVIA** [comment]
Recycled. Now Rzeszow Jasionka Int’l Airport. Doing this soon, don't take over.

**Comment by bavAVIA** [comment]
Taking over.

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26072380/e5303770-3970-11e7-9919-1c88e4539ecc.png)
