### ISSUE TITLE
LKMT

### ISSUE THREAD

**Issue by DarlanFernandes** [InfiniteFlightAirportEditing/Airports#1442]

**Comment by brunocr98** [comment]
@DarlanFernandes como vai este aeroporto? Além disso, como estão indo #1439 e #1441 ?

**Comment by brunocr98** [comment]
Up for grabs. (The user originally assigned has been removed due to inactivity)

**Comment by bavAVIA** [comment]
Recycled. Now Ostrava - Mosnov Int'l

**Comment by bavAVIA** [comment]
Taking over.

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26024915/c0d6bf6e-37a1-11e7-844d-1ddcc003500f.png)
