### ISSUE TITLE
CYHM-John C. Munro Hamilton Airport-ONTARIO-CANADA

### ISSUE THREAD

**Issue by justypic29** [InfiniteFlightAirportEditing/Airports#1444]
I will do it

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25044680/929c2e24-20ed-11e7-8491-981cbc205fb9.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50539689-eab8ab80-0b49-11e9-8fb1-6c9ffd57c9de.png)

**Comment by kilt46** [comment]
Duplicate spawns renamed. Buildings removed
