### ISSUE TITLE
MMSM-Santa Lucia Air Force Base-ESTADO DE MEXICO-MEXICO

### ISSUE THREAD

**Issue by lalomarlin** [InfiniteFlightAirportEditing/Airports#1445]
Santa Lucia Afb

**Comment by dushyants19** [comment]
do you want to do it?

**Comment by lalomarlin** [comment]
Yes, both

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21589048/37a12be4-d0b3-11e6-8c6a-64c8c5e6cc02.png)
