### ISSUE TITLE
MMML-Mexicali Airport-BAJA CALIFORNIA NORTE-MEXICO

### ISSUE THREAD

**Issue by lalomarlin** [InfiniteFlightAirportEditing/Airports#1446]
Mexicali Airport

**Comment by lalomarlin** [comment]
Redoing it

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21568400/e0b60a92-ce79-11e6-89c3-d798829dfed0.png)
