### ISSUE TITLE
EGEW-Westray Airport-SCOTLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by NYAviation** [InfiniteFlightAirportEditing/Airports#1447]
Westray Airport, located in Scotland, flies daily flights to Papa Westray Airport. These flights are the shortest flights in the world.

**Comment by dushyants19** [comment]
Please give some description

**Comment by NYAviation** [comment]
I can not do this one, does anyone want to do it?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/43993000-88c97e10-9d4c-11e8-936f-21bac65fca4b.png)
