### ISSUE TITLE
EGEP-Papa Westray Airport-SCOTLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by NYAviation** [InfiniteFlightAirportEditing/Airports#1448]
Papa Westray Airport, located in Scotland, flies daily flights to Westray Airport. These flights are the shortest scheduled flights in the world.

**Comment by dushyants19** [comment]
Give some description, thanks.

**Comment by NYAviation** [comment]
I can not do this one, up for grabs

**Comment by bavAVIA** [comment]
Why can't you do it? You can open issues, why can't you do them then?

**Comment by NYAviation** [comment]
I can't do any right now because of the holidays and I'll be busy for most of january

**Comment by bavAVIA** [comment]
Awesome, you can do it afterwards then.

**Comment by kilt46** [comment]
Scotland - Land of my birth

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21472732/7aad52bc-caac-11e6-9a94-d4ade9f59d6b.png)
