### ISSUE TITLE
WALL

### ISSUE THREAD

**Issue by 4riw** [InfiniteFlightAirportEditing/Airports#1449]
working on WALL (Balikpapan Sepinggan, East Borneo, Indonesia)

**Comment by dushyants19** [comment]
There are 2 more Indonesian airports too, #600 and #610. Would you like to do them? @4riw

**Comment by 4riw** [comment]
@dushyants19 sure, u can assign me to both #600 & #610. Thanks for the info, i didnt know they're existed =D

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21750278/2ea48e70-d575-11e6-93b3-7cc76e4d2e8b.png)
