### ISSUE TITLE
MMAA-Acapulco Airport-GUERRERO-MEXICO

### ISSUE THREAD

**Issue by lalomarlin** [InfiniteFlightAirportEditing/Airports#1450]
Being Redone

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22006228/f706db92-dc2e-11e6-96cc-cabd001cbf97.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/98453024-7b437800-2133-11eb-8514-292e2391f423.jpg)
