### ISSUE TITLE
DABT

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#1452]
Batna - Mostepha Ben Boulaid Airport, Algeria.
Being redone.

**Comment by bavAVIA** [comment]
Sent for review.

**Comment by dushyants19** [comment]
how do you even find these airports? did you find them while you were lost in the Sahara?

**Comment by bavAVIA** [comment]
I want to get some airports in Africa done, so I just hover over Africa on Google Maps...
Then I find these. Yeah...

**Comment by lalomarlin** [comment]
Haha, nice choice :)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21577393/632bcf6c-cf1e-11e6-8eeb-5f5a723c13d4.png)

**Comment by kilt46** [comment]
Satellite showed white outlines!! I have added!
