### ISSUE TITLE
MMSD-San Jose Del Cabo Airport-BAJA CALIFORNIA SUR-MEXICO

### ISSUE THREAD

**Issue by lalomarlin** [InfiniteFlightAirportEditing/Airports#1454]
Being Redone

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22005790/ae7f4bfa-dc2b-11e6-9104-68eee95998f1.png)

**Comment by MBeringuy** [comment]
I don't usually leave airports as a suggestion, but the apron for GA needs to be updated, as well as some lines of marking; and it is also necessary to remove the buildings and, if possible, update the paving to be similar to the real one.
To sum up, it needs to be redone from scratch; and as i'm already involved with another airport and i'm out of time, does anyone volunteer?

**Comment by jakey200** [comment]
Once an issue opens up for me I will take this

**Comment by jakey200** [comment]
sent to official review

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78675231-20a31e80-78bb-11ea-8387-5ef98fb45efc.jpg)
