### ISSUE TITLE
LERS-Reus Airport-CATALUÑA-SPAIN

### ISSUE THREAD

**Issue by lolo31r** [InfiniteFlightAirportEditing/Airports#1455]
I´ll be redoing it

**Comment by moritzbabl** [comment]
surprisingly finally added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22388410/02ef8434-e4a6-11e6-831c-ac2e0f90c386.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109883289-d1877a00-7c40-11eb-95e8-4adc441192fd.png)
