### ISSUE TITLE
CYQY

### ISSUE THREAD

**Issue by tranquil-skyflyer** [InfiniteFlightAirportEditing/Airports#1457]
I'll do this one (actually).

**Comment by tranquil-skyflyer** [comment]
Submitted for review.

**Comment by tranquil-skyflyer** [comment]
Submitted revamped version for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22393415/a5282fc4-e4cb-11e6-8b5a-5f2e7056c89e.png)
