### ISSUE TITLE
KDPG-Michael AAF (Dougway Proving Grounds)-UTAH-USA

### ISSUE THREAD

**Issue by anonymous123567** [InfiniteFlightAirportEditing/Airports#1458]
Please edit me

♻️

**Comment by IFAEpat** [comment]
@anonymous123567 this has been done #330

**Comment by lolo31r** [comment]
i´ll be doing this

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25063594/446a5dea-21ae-11e7-9d6d-220895ac8e9d.png)
