### ISSUE TITLE
KHWO-North Perry Airport-FLORIDA-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#146]

**Comment by kilt46** [comment]
Started

**Comment by kilt46** [comment]
Airport redone and updated

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21082929/53b73846-bfab-11e6-86c2-5731a9d32165.png)

**Comment by brennanhackard** [comment]
Needs a rework. Up for grabs.
