### ISSUE TITLE
KICR-Winner Regional Airport-SOUTH DAKOTA-USA

### ISSUE THREAD

**Issue by BrandonKreuter** [InfiniteFlightAirportEditing/Airports#1461]
Please edit me

♻️

**Comment by KSJCRampAgent** [comment]
I'll work on this one.

**Comment by moritzbabl** [comment]
member inactive, up for grabs

**Comment by moritzbabl** [comment]
member inactive, up for grabs

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/40568858-dbb32b86-6042-11e8-9a15-b556edc8b01c.png)
