### ISSUE TITLE
EVRA-Riga Airport-RIGA-LATVIA

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#1462]
Riga Int'l airport. I will be re-doing this one.

Runway is longer than 10k feet.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22357838/6ebeb956-e400-11e6-9ad5-25e903045c98.png)

**Comment by MBeringuy** [comment]
Is it to reopen these and the other two issues (#999 and #1149)?

**Comment by brunocr98** [comment]
I guess I got distracted and forgot to reopen. Well I'll only reopen this one and #999. #1149 is going to be finished by this evening.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/72275990-c709bb80-360d-11ea-986c-ec3b918cb3b7.jpg)
