### ISSUE TITLE
KOKS-Garden County Airport-NEBRASKA-USA

### ISSUE THREAD

**Issue by NYAviation** [InfiniteFlightAirportEditing/Airports#1463]
RECYCLED ♻️

**Comment by dushyants19** [comment]
What are you trying to do? Please dont create unnecessary issues.

**Comment by dushyants19** [comment]
Done. Please dont request anything again, kid.

**Comment by BrandonKreuter** [comment]
Please don't call me a kid again.  K? Thanks

**Comment by dushyants19** [comment]
I told NYAviation, not you. Moreover I replied already that it's added yet you request it, a random field in the middle of nowhere. Just for the sake of looking it on a TV show.

**Comment by Theobsidianguy** [comment]
@NYAviation please search before creating issues. and don't create issues that you aren't going to do. 
@dushyants19 I know what you're thinking, I've learnt my lesson

**Comment by BrandonKreuter** [comment]
Oh okay sorry @dushyants19.  Sorry again!  Keep up the good work

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34319447-4a5d55a2-e7a8-11e7-9a68-bb831ad15dfb.png)
