### ISSUE TITLE
FMNN-Nosy-Be Fascene Airport-ANTSIRANANA-MADAGASCAR

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#1464]

**Comment by PaulNielsen** [comment]
Done, sorry if the ramp positions are not 100% correct, I found no ground charts, and the lines on the ground were quite messy, so I hade to go after just looking at some pictures & videos and common sense. :)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21590085/323aae7c-d0be-11e6-9d87-d1f3a46c6d88.png)

**Comment by kilt46** [comment]
Wrong runway size. Also gates included
![image](https://cloud.githubusercontent.com/assets/14023167/21590165/d24c3264-d0be-11e6-8bd6-b92fe955840f.png)

**Comment by dushyants19** [comment]
@PaulNielsen anything?

**Comment by dushyants19** [comment]
Should be fixed

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24731567/978405ce-1a30-11e7-86aa-629f47731c01.png)
