### ISSUE TITLE
HTKJ-Kilimanjaro Airport-KILIMANJARO-TANZANIA

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#1465]
Kilimajaro International Airport, Tanzania being redone.
Priority II Airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21749876/00210ad0-d56e-11e6-8d0c-5ff19c6c398e.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/77239646-e26be680-6bbb-11ea-8e0d-b130157a47b9.jpg)
