### ISSUE TITLE
XWMB-Kaliningrad Airbase-KALININGRAD OBLAST-RUSSIA

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#1467]

**Comment by ErshovlaD** [comment]
Hey, are you here?
![vhkomc2bxpe 1](https://cloud.githubusercontent.com/assets/22447757/22303074/0d854480-e34b-11e6-90de-d42a6bbeff44.jpg)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22393170/ffb2a0e0-e4c7-11e6-85dd-a9a8696e2a20.png)
