### ISSUE TITLE
DNMM-Murtala Muhammed International-LAGOS-NIGERIA

### ISSUE THREAD

**Issue by ebukarthur** [InfiniteFlightAirportEditing/Airports#1468]
sorry for creating the issue but I can not re-do the airport so sorry for the inconvenience but I woild really love to see the airport

**Comment by Adam167** [comment]
Are you going to be re doing this one? If you aren't going to do it please don't make issues
If so are you in the slack team?

**Comment by dushyants19** [comment]
@ebukarthur please response else we dont do this airport.

**Comment by ebukarthur** [comment]
Leave a comment

**Comment by brunocr98** [comment]
Please don't close the issues unless the airport is done!

**Comment by brunocr98** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23826745/bc93b7e6-0668-11e7-8354-fd8711f9db80.png)

**Comment by brennanhackard** [comment]
Airport needs a rework. Reply to this comment if you'd like to be assigned.

Be advised: Imagery is relatively distorted
