### ISSUE TITLE
BIGR-Grímsey Airport-HALSHREPPUR-ICELAND

### ISSUE THREAD

**Issue by liamkirky** [InfiniteFlightAirportEditing/Airports#1469]

**Comment by liamkirky** [comment]
![bigr](https://cloud.githubusercontent.com/assets/19878689/21620345/be616638-d1eb-11e6-8c70-29b40e9337fd.PNG)

**Comment by liamkirky** [comment]
Sent in for a review

**Comment by PaulNielsen** [comment]
There is no need to close the issue, @liamkirky

**Comment by liamkirky** [comment]
Can i be reassigned as a quick project

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24322216/ee4b12a6-112c-11e7-8d3a-360920405733.png)
