### ISSUE TITLE
KEGE-Eagle County Regional Airport-COLORADO-USA

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#147]

**Comment by JohnPreston21** [comment]
Adding taxiways, a couple more spawn points and hold short point points

**Comment by JohnPreston21** [comment]
Finished

**Comment by JohnPreston21** [comment]
completed

**Comment by dushyants19** [comment]
Needs a redo, multiple taxiways

**Comment by HenrikBerg02** [comment]
I'll rework this one.

**Comment by RileyDunshea** [comment]
Henrik I am currently reworking KEGE already

**Comment by HenrikBerg02** [comment]
I just finished reworking it. You assigned it nine days ago and it hasn't been finished yet, I decided to go ahead and do it for you. :)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18654308/9dc21a56-7ea5-11e6-8219-12ebaa066d1e.png)

**Comment by brennanhackard** [comment]
@Aceorbit will be updating this airport for the following reasons:

- new ANG ramp
- buildings need to be removed
- imagery for areas under construction now available

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122673379-d04d6f00-d195-11eb-8f97-2ce2b34b97b0.png)
