### ISSUE TITLE
UAUU-Kostanay Airport-QOSTANAY-KAZAKHSTAN

### ISSUE THREAD

**Issue by tsarkov90** [InfiniteFlightAirportEditing/Airports#1471]

**Comment by dushyants19** [comment]
Please give a description

**Comment by ErshovlaD** [comment]
Assign me. I will make it.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23321690/1ecca0e0-faa6-11e6-83d8-9f30621d7387.png)

**Comment by Czechoslovaki** [comment]
Redoing this.

- Main runway needs to be extended, shoulder needs to be added too.
- Main commercial apron config changed.
- One apron in current apt data not in use anymore, needs to be updated
- Missing double yellow lines and runway holds
- Too many buildings need to be removed
- Extra grass runways need to go

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109419196-e68ab180-7991-11eb-827c-7c503ba08ddb.png)
