### ISSUE TITLE
LJMB-Maribor/Orehova Vas Airport-PODRAVSKA-SLOVENIA

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#1472]
Maribor - Edvard Rusjan Airport, Slovenia.
Redoing.

**Comment by kilt46** [comment]
This airport is an XPLane Original! There are zero spawns
![Uploading image.png…]()

**Comment by bavAVIA** [comment]
I've already sent

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22174184/d4d45d48-df9d-11e6-8814-3a3df6a25140.png)
