### ISSUE TITLE
SASA-Salta Airport-SALTA-ARGENTINA 

### ISSUE THREAD

**Issue by lolo31r** [InfiniteFlightAirportEditing/Airports#1473]
RECYCLED ♻️ (TWICE)

**Comment by lolo31r** [comment]
duplicate sorry

**Comment by dushyants19** [comment]
C'mon Lorenzo...

**Comment by lolo31r** [comment]
Wait....why did you reopen this issue?

**Comment by lolo31r** [comment]
Oh i see

**Comment by brunocr98** [comment]
Edited in the night shift.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27228899-1efba31a-526f-11e7-8d66-aaec76845547.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/58834944-f7768980-862a-11e9-9bb8-0eba407bcb30.jpg)
