### ISSUE TITLE
RPMN-Sanga Airport-TAWI-TAWI-PHILIPPINES

### ISSUE THREAD

**Issue by GentlePig500** [InfiniteFlightAirportEditing/Airports#1475]
I will edit taxiway, taxiway line and other issues

**Comment by GentlePig500** [comment]
Sent For Approval

**Comment by GentlePig500** [comment]
Sent For Review

**Comment by kilt46** [comment]
Shape of main apron looks different
![image](https://cloud.githubusercontent.com/assets/14023167/22091657/a2477536-ddbd-11e6-8475-3554f0ec57c1.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22091670/ae48ff4e-ddbd-11e6-8419-b2e540082bbc.png)

**Comment by kilt46** [comment]
Runway length incorrect
![image](https://cloud.githubusercontent.com/assets/14023167/22091723/f4aa9a06-ddbd-11e6-88a5-a314dbc7b976.png)
![image](https://cloud.githubusercontent.com/assets/14023167/22091729/015d3312-ddbe-11e6-8882-4bb6c3ccfb2b.png)

**Comment by GentlePig500** [comment]
Sent for Review

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22174317/f6073668-dfa0-11e6-8d48-fb8ec888a766.png)
