### ISSUE TITLE
EDAQ

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#1476]
Halle-Oppin, used for the tutorial video, still some additional work to do

**Comment by moritzbabl** [comment]
Done and comitted, be proud of me ^^ If you don't trust me @dushyants19 , you can search any errors in my tutorial video :P

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21789834/87f697c4-d69d-11e6-96f4-7cd5ce64e494.png)

**Comment by dushyants19** [comment]
It's because of the trust, you were given access. :)
