### ISSUE TITLE
3LF-Litchfield Municipal Airport-ILLINOIS-USA

### ISSUE THREAD

**Issue by Cleipelt** [InfiniteFlightAirportEditing/Airports#1477]
♻️

**Comment by dushyants19** [comment]
@Cleipelt how is this going?

**Comment by Cleipelt** [comment]
@dushyants19 I'm actually working on a 3D modeled KTVL for X-Plane 10/11 ATM. As soon as o finish that project, I'll send over the apt.dat for it which is almost done. Need to touch up on some lines and spawn points.

**Comment by dushyants19** [comment]
Any progress? @Cleipelt

**Comment by Cleipelt** [comment]
Yeah I got a new computer and lost a lot of stuff, let me re download the old file I emailed you and work from there. Probably get it done today.

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31548235-ce796a9c-afef-11e7-8f68-183d51d42105.png)
