### ISSUE TITLE
KCRW-Yeager Airport-WEST VIRGINIA-USA

### ISSUE THREAD

**Issue by lolo31r** [InfiniteFlightAirportEditing/Airports#1478]
American states airport KCRW West Virginia

redoing this now

**Comment by lolo31r** [comment]
@bavAVIA is doing this now

**Comment by moritzbabl** [comment]
added, please learn to handle github @bavAVIA, no need to review...

**Comment by kilt46** [comment]
Missing Gate
![image](https://cloud.githubusercontent.com/assets/14023167/22356693/f5bb5d4a-e3f8-11e6-8a13-68cb7a03d7c6.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22387391/ff3b0bc4-e4a0-11e6-81d6-32dbc7ea0fa9.png)
