### ISSUE TITLE
CYMX-Montréal International (Mirabel) Airport-QUEBEC-CANADA

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#1479]

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21751465/8f8de6f6-d58d-11e6-8a6e-c7dc89ba404f.png)

**Comment by Adam167** [comment]
Ill do this one

**Comment by alexpeterson-if** [comment]
I'll take this.

**Comment by alexpeterson-if** [comment]
Sent for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33691559-695937ca-daae-11e7-94c5-fa8fdb5df0f6.png)
