### ISSUE TITLE
KAGS-Augusta Regional At Bush Field Airport-GEORGIA-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#148]
Charlotte

**Comment by JohnPreston21** [comment]
Fixing this one up a bit, including airport boundary

**Comment by JohnPreston21** [comment]
added taxi ways, hanger & ramp spawn points

**Comment by HenrikBerg02** [comment]
Doing this one, not many spawn points.

**Comment by IceBlue02** [comment]
Will fix:
https://community.infinite-flight.com/t/hold-short-line-missing-kags/40561/2

**Comment by samuelandersson** [comment]
How's this going @IceBlue02?

**Comment by IceBlue02** [comment]
Oh, never got anywhere with this, think it need for that just that fix if I remember.

**Comment by kilt46** [comment]
Airport redone

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18976111/ec435718-8674-11e6-8cb8-526beffc2ebe.png)
