### ISSUE TITLE
KANQ-Tri-State Steuben County Airport-INDIANA-USA

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#1480]
♻️

**Comment by AggieAirlines** [comment]
Can't wait to fly at this airport!

**Comment by cptchris** [comment]
I’ll take this ;$

**Comment by AggieAirlines** [comment]
Thank you! There is only one startup location in the whole airport 
		
		

		Thank you,Benjamin M. Self
	




On Thu, Nov 23, 2017 at 5:48 PM -0600, "cptchris" <notifications@github.com> wrote:












I’ll take this ;$

**Comment by CptNathanHope** [comment]
re: [No Gates at Love Field](https://community.infinite-flight.com/t/no-gates-at-love-field-kdal/187263?u=nathan). 

@cptchris are you still doing this? Have you made any progress on this thus far? Please let us know. Thanks! – N

**Comment by brunocr98** [comment]
Part of Project Indiana / Parte del Proyecto Indiana.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36352623-56d94498-1481-11e8-8e55-7d0d442cb51f.png)
