### ISSUE TITLE
LESO

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#1483]
San Sebastian, Spain

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22007038/7a3e1ad8-dc35-11e6-8108-d9bf48eb8948.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/110037349-e5e07b00-7d03-11eb-9def-ec60749bf73c.png)
