### ISSUE TITLE
KGRR-Grand Rapids Airport-MICHIGAN-USA

### ISSUE THREAD

**Issue by ryu12332** [InfiniteFlightAirportEditing/Airports#1485]
Part of Project Michigan

**Comment by ryu12332** [comment]
KGRR is nearly complete.
**Overview**

<img width="976" alt="screen shot 2017-01-13 at 9 43 31 am" src="https://cloud.githubusercontent.com/assets/20650961/21934266/cd2d1ce2-d976-11e6-8c52-b1da41db14d2.png">

**Main Terminal, GA bases**

<img width="983" alt="screen shot 2017-01-13 at 9 44 01 am" src="https://cloud.githubusercontent.com/assets/20650961/21934269/cfb27052-d976-11e6-98f2-4240f3373b94.png">

**Comment by kilt46** [comment]
Gates don't make sense
![image](https://cloud.githubusercontent.com/assets/14023167/22006872/43907c3e-dc34-11e6-8acd-49eefbb168a2.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22006881/51bab7c0-dc34-11e6-9970-9a6bb1bd2028.png)

**Comment by kilt46** [comment]
Hold Shorts NOT ALLOWED
![image](https://cloud.githubusercontent.com/assets/14023167/22006905/74536d18-dc34-11e6-9d6c-4f5e9ae0c92f.png)

**Comment by kilt46** [comment]
Preface Fixed Base Operators with FBO  (e.g.)
![image](https://cloud.githubusercontent.com/assets/14023167/22006929/956cdde0-dc34-11e6-9df9-ae83f8d890b8.png)

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22318375/9a4e967a-e33f-11e6-9f08-9e271f95e317.png)
