### ISSUE TITLE
SKAR-Armenia Airport-QUINDIO-COLOMBIA

### ISSUE THREAD

**Issue by Yifan081** [InfiniteFlightAirportEditing/Airports#1486]
El Eden International Airport, Colombia. I'll edit it

**Comment by Yifan081** [comment]
Submitted for review

**Comment by kilt46** [comment]
Runway length
![image](https://cloud.githubusercontent.com/assets/14023167/22004012/b4cec1f6-dc1d-11e6-919a-b53da890ea5f.png)
![image](https://cloud.githubusercontent.com/assets/14023167/22004019/c32a7c90-dc1d-11e6-9591-9a2ee5e9eb8d.png)

**Comment by kilt46** [comment]
Hold lights missing
![image](https://cloud.githubusercontent.com/assets/14023167/22004031/d852a73c-dc1d-11e6-8325-62a9968dac79.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22007265/117a4344-dc37-11e6-933f-ec547cd86f44.png)
