### ISSUE TITLE
WBGS-Sibu Airport-SARAWAK-MALAYSIA

### ISSUE THREAD

**Issue by Yifan081** [InfiniteFlightAirportEditing/Airports#1487]
Sibu Airport, Malaysia. I'll edit it.

**Comment by Yifan081** [comment]
Submitted for review

**Comment by kilt46** [comment]
ATS: https://skyvector.com/airport/WBGS/Sibu-Airport
![image](https://cloud.githubusercontent.com/assets/14023167/22003143/d80daddc-dc16-11e6-967a-0c227285fa36.png)
![image](https://cloud.githubusercontent.com/assets/14023167/22003159/ee0031fa-dc16-11e6-8ae2-b1ce2ff96e9a.png)

**Comment by kilt46** [comment]
Slots not cut in apron
![image](https://cloud.githubusercontent.com/assets/14023167/22003179/2b8fecae-dc17-11e6-8039-98dab8f0180d.png)

**Comment by kilt46** [comment]
Runway holds missing lighting
![image](https://cloud.githubusercontent.com/assets/14023167/22003199/5712c4be-dc17-11e6-83a1-29c84d69c41a.png)

**Comment by kilt46** [comment]
Good job with main parking. Please update hangars as shown
![image](https://cloud.githubusercontent.com/assets/14023167/22003238/981ef4be-dc17-11e6-8724-e04aad90a164.png)

**Comment by kilt46** [comment]
Good job with the runway length

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22007560/4a4c963e-dc39-11e6-9ec4-7aa5f8218e29.png)
