### ISSUE TITLE
LFLX-Chateauroux Deols Airport-CENTRE-FRANCE

### ISSUE THREAD

**Issue by Adam167** [InfiniteFlightAirportEditing/Airports#1488]
I ❤️ RECYCLING :)

**Comment by Adam167** [comment]
Currently not able to do this as there are no images at all that can be put in the correct place. I will do this as soon as I can see the airport

**Comment by Adam167** [comment]
If anyone wants to take a shot at this they can, But there is no images as yet

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29489638-51ebfd3e-84eb-11e7-89a0-f6ff2935cf29.png)
