### ISSUE TITLE
WBGB-Bintulu Airport-SARAWAK-MALAYSIA

### ISSUE THREAD

**Issue by Yifan081** [InfiniteFlightAirportEditing/Airports#1489]
Bintulu Airport, Malaysia.

**Comment by moritzbabl** [comment]
Are you doing this? Also, are you in the slack channel yet? If not and if you want to work on the airports you created issues for, send a mail to airports@liveflightapp.com to join us

**Comment by Yifan081** [comment]
Submitted for review

**Comment by kilt46** [comment]
Holes should be cut round protrusions
![image](https://cloud.githubusercontent.com/assets/14023167/22002916/53f2b926-dc15-11e6-91ab-da4c531d68b3.png)

**Comment by kilt46** [comment]
Gates numbered incorrectly
![image](https://cloud.githubusercontent.com/assets/14023167/22002967/ac90be8e-dc15-11e6-94e4-ca8a12156fe8.png)

**Comment by kilt46** [comment]
Runway should be 2745 m
![image](https://cloud.githubusercontent.com/assets/14023167/22002973/c139784e-dc15-11e6-93af-6575fb09d868.png)

**Comment by kilt46** [comment]
Only 1 tower (ATC)
![image](https://cloud.githubusercontent.com/assets/14023167/22003009/0a82a282-dc16-11e6-80d9-d69fd0d69e7f.png)
![image](https://cloud.githubusercontent.com/assets/14023167/22003013/11ad2fd2-dc16-11e6-8049-ea4a3ff09807.png)

**Comment by kilt46** [comment]
hole not cut properly. Apron doubles back on itself. Now apron is invisible.
![image](https://cloud.githubusercontent.com/assets/14023167/22088641/3360c4b8-ddab-11e6-8d53-e1240f9378d9.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22088652/41b01a96-ddab-11e6-9058-7767a17cd808.png)

**Comment by kilt46** [comment]
Finished off for you. You will need to learn how to cut holes
![image](https://cloud.githubusercontent.com/assets/14023167/22088738/c3950da0-ddab-11e6-8dc4-a4f5be9a28a3.png)
