### ISSUE TITLE
KCAE-Columbia Metropolitan Airport-SOUTH CAROLINA-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#149]
Charlotte

**Comment by kilt46** [comment]
Started

**Comment by kilt46** [comment]
Complete rewrite of airport

**Comment by Swang007** [comment]
https://community.infinite-flight.com/t/kcae-columbia-metro-needs-parking/14989

**Comment by kilt46** [comment]
spawn on runway

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/11329326/4c3b45fa-9160-11e5-885d-09d25bf1dfca.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17267285/d6dacc06-55ca-11e6-808a-be5ede4b111c.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18227771/4feebd6e-71f5-11e6-8eee-9a8318da3b88.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18227772/586bb654-71f5-11e6-8f33-d1e5ec842e1c.png)

**Comment by bavariaaviation** [comment]
to be redone by @AleksanderIF

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/82478869-eb880f80-9aa7-11ea-8775-f09855103ac2.jpg)
