### ISSUE TITLE
WBGG

### ISSUE THREAD

**Issue by Yifan081** [InfiniteFlightAirportEditing/Airports#1490]
Kuching International Airport, Malaysia.

**Comment by bavAVIA** [comment]
@Yifan081 Are you doing this and #1489 ?

**Comment by Yifan081** [comment]
Yes, I was part of the Slack team before, however, it seems my account was disabled, since I didn't access for quite long.  I'll resend the request.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22354194/e2a4e492-e3e9-11e6-924b-eb39bdcf9d82.png)
