### ISSUE TITLE
XWWO-Bobrovka (Samara)-SAMARA OBLAST-RUSSIA

### ISSUE THREAD

**Issue by ErshovlaD** [InfiniteFlightAirportEditing/Airports#1496]
I make it

**Comment by ErshovlaD** [comment]
Send to email

**Comment by moritzbabl** [comment]
already added some weeks ago

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22618286/3957f85a-ea9e-11e6-9396-c5547ddcadc6.png)
