### ISSUE TITLE
LICC-Catania Fontanarrosa Airport-SICILIA-ITALY

### ISSUE THREAD

**Issue by johanneskkl** [InfiniteFlightAirportEditing/Airports#1497]
Catania airport (ITALY) with this i am starting my project Italy .

**Comment by johanneskkl** [comment]
Catania airport (ITALY) with this i am starting my project Italy .

**Comment by johanneskkl** [comment]
Sent for review

**Comment by johanneskkl** [comment]
sent for review. Moritz is going to review it this evening

**Comment by johanneskkl** [comment]
![screenshot 24](https://cloud.githubusercontent.com/assets/22429067/23178113/825a8f12-f869-11e6-811a-d261084da243.png)
![screenshot 22](https://cloud.githubusercontent.com/assets/22429067/23178121/898e98a0-f869-11e6-80bc-5bc718d28606.png)

**Comment by PaulNielsen** [comment]
You don't have to post pictures of it in the issue here on GitHub :)

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
Wrong gate numbers
![image](https://cloud.githubusercontent.com/assets/14023167/23320706/8007e69e-faa1-11e6-9595-0fee0efae76a.png)

**Comment by kilt46** [comment]
Missing white outlines on west apron. Also suggest full white lines for outlines on main apron

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23754374/4e7b9b24-04a2-11e7-9ab2-6707c5b46913.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/70488185-aa420b80-1ad6-11ea-9bd6-891325f74e5a.jpg)
