### ISSUE TITLE
KBML-Berlin Regional Airport-NEW HAMPSHIRE-USA

### ISSUE THREAD

**Issue by Theyoshifan200** [InfiniteFlightAirportEditing/Airports#1498]
Part of **Project New Hampshire**, KBML is a small airport in Milan, NH. I would like to do this airport.

**Comment by Theyoshifan200** [comment]
<img width="440" alt="screen shot 2017-01-12 at 5 53 45 pm" src="https://cloud.githubusercontent.com/assets/21222414/21911739/1b8efed2-d8f0-11e6-84f0-0e48cff51f02.png">
So, I added the buildings and also added a tower (not visible), but the airport is non-towered and is only UNICOM. Should I keep the tower anyways? what do you think about the progress? I started KBML yesterday :)

**Comment by Theyoshifan200** [comment]
I have submitted Berlin rgnl Airport for review! I hope it passes :)

**Comment by Theyoshifan200** [comment]
I have submitted the airport to the editing team, should I close the issue
or leave it open?

**Comment by lolo31r** [comment]
Please join our slack team. There we will answer all your questions.

**Comment by Theyoshifan200** [comment]
Airport resubmitted from fixes

**Comment by bavAVIA** [comment]
Quickly did this.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27829457-57347a2e-6087-11e7-93bf-c57a2ef757fa.png)
