### ISSUE TITLE
KPGD-Punta Gorda Airport-FLORIDA-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#15]

**Comment by JohnPreston21** [comment]
Added hanger and ramp spawn points

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20649099/eeb79190-b47c-11e6-851b-cd3db70a5bc2.png)

**Comment by dushyants19** [comment]
Missing a taxiway it seems, @ksisky wants to fix it.

**Comment by Ksisky** [comment]
Added taxiway and sent in for review.

**Comment by Ksisky** [comment]
Just going to redo the entire thing. It was designed poorly.

**Comment by ryu12332** [comment]
Progress?

**Comment by moritzbabl** [comment]
member inactive, up for grabs

**Comment by brennanhackard** [comment]
Reopening this to anyone. This airport needs:

- taxiway material fixes
- addition of the new stands
- many more spawns
- various spawn fixes and adjustments
- frequency fixes
- improved taxiway and linear feature geometry
- more accurate boundary

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115096877-c33da680-9eec-11eb-9d71-a45a0f33261b.png)
