### ISSUE TITLE
KLIT-Bill and Hillary Clinton National/Adams Field Airport-ARKANSAS-USA

### ISSUE THREAD

**Issue by Josh391** [InfiniteFlightAirportEditing/Airports#1500]
Clinton National Airports

**Comment by brunocr98** [comment]
Hi,

Are you in our team, if not, please don't create random issues if you're not going to do the airports. We have enough airports with the Suggestion label. If you want to do them, please send an email to airports@liveflightapp.com to get started.

Thanks

**Comment by dushyants19** [comment]
its lit.

**Comment by bavAVIA** [comment]
grabbing this

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22627256/1f52f06c-eb85-11e6-86c5-ac1102697433.png)

**Comment by rich-art-02** [comment]
Rework of spawns, taxiway layout and teh whole node design

**Comment by rich-art-02** [comment]
Sent to OR and approved

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/66950400-a8a41c00-f02e-11e9-9964-8256e5d0b509.jpg)
