### ISSUE TITLE
LIPK-Forli Airport-EMILIA-ROMAGNA-ITALY

### ISSUE THREAD

**Issue by johanneskkl** [InfiniteFlightAirportEditing/Airports#1501]
Forli Airport.
Maybe I've opened this issue too late!😑

**Comment by johanneskkl** [comment]
Sent for review

**Comment by johanneskkl** [comment]
Pls review is done since mire than 48h.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
Missing outlines in main gate apron
![image](https://cloud.githubusercontent.com/assets/14023167/23095915/d7ef0c08-f5d7-11e6-9da9-8171d69bcef6.png)
![image](https://cloud.githubusercontent.com/assets/14023167/23095919/e9f818c2-f5d7-11e6-8364-33b9ca6a5d31.png)

**Comment by johanneskkl** [comment]
Done. Sent for review

**Comment by moritzbabl** [comment]
Didn't receive anything from you today @johanneskkl

**Comment by johanneskkl** [comment]
![Uploading Screenshot_20170219-155954.png…]()

**Comment by moritzbabl** [comment]
I have no idea what the screenshot is but i sent you two mails if the screenshot refers to one of them @johanneskkl

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23107351/7e28bb52-f6c1-11e6-8627-3e0945d4fa4a.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45789205-0b688f80-bc44-11e8-9de1-5ca8224e61df.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68903772-ed4cd100-071a-11ea-8516-79f913b4a092.jpg)
