### ISSUE TITLE
VOAT-Agatti Airport-LAKSHADWEEP-INDIA

### ISSUE THREAD

**Issue by shanawaz97** [InfiniteFlightAirportEditing/Airports#1502]
Please do mentioned airport,  it will be fun to fly here

**Comment by lolo31r** [comment]
Please don´t open issues if you aren´t going to do that airport.

**Comment by Adam167** [comment]
@lolo31r Has agreed to do it as it is so small. But don't make issues unless you are an airport editor, ALL airports will be in global they just may not be of a hight standard.

**Comment by shanawaz97** [comment]
Thank dear I've noted

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22005692/f6a0f4b6-dc2a-11e6-8c6a-b28c9c7d089b.png)
