### ISSUE TITLE
KFNT-Flint Bishop Airport-MICHIGAN-USA

### ISSUE THREAD

**Issue by ryu12332** [InfiniteFlightAirportEditing/Airports#1503]
Part of Project Michigan

**Comment by ryu12332** [comment]
<img width="783" alt="screen shot 2017-03-18 at 8 19 19 pm" src="https://cloud.githubusercontent.com/assets/20650961/24077094/42de33b2-0c18-11e7-9462-b304130ecef6.png">

**Comment by brunocr98** [comment]
U're not Kilt to do that 😂

**Comment by moritzbabl** [comment]
added
