### ISSUE TITLE
GBYD

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#1506]
Banjul Intl, Gambia, i'll do it

**Comment by moritzbabl** [comment]
Done in 2 hours, the whole of Gambia is ready for global with this ^^

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21956543/521f5078-da49-11e6-999b-dddc3ddfdcb1.png)
