### ISSUE TITLE
GVMA-Maio Airport-MAIO-CAPE VERDE

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#1509]
Maio Airport being redone.
Part of Project Cape Verde.

**Comment by bavAVIA** [comment]
Sent for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22046498/b62f74d6-dce6-11e6-8584-628bb6ab9ec3.png)
