### ISSUE TITLE
KMMT-Mc Entire Jngb Airport-SOUTH CAROLINA-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#151]
Charlotte

**Comment by kilt46** [comment]
Image: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=KMMT

**Comment by dushyants19** [comment]
I have started on this :blush:

**Comment by dushyants19** [comment]
Approved by Jonathan

**Comment by kilt46** [comment]
spawn on runway

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/11329180/1253ae60-915e-11e5-8335-fef352134517.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17822305/fcba3e00-661b-11e6-9c8e-a52f0d32f542.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17822308/07705852-661c-11e6-84c4-863ffb3be1ee.png)

**Comment by MajorTomMueller** [comment]
Rework was requested especial related to spawns, Dush wont. Will care if no one else dose and other priorities are done.

**Comment by MajorTomMueller** [comment]
- buildings removed
- Heli Spawns removed
- markings updated
- Spawns updated/completed
![kmmt-git](https://user-images.githubusercontent.com/26853210/52971367-75ce5900-33b7-11e9-8f82-719e2e0686e4.jpg)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53279168-c5709580-36d3-11e9-9974-4dacd68cf29c.png)
