### ISSUE TITLE
GVNP-Praia Nelson Mandela International Airport-PRAIA-CAPE VERDE

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#1510]
Praia - Nelson Mandela International Airport being redone.
Part of Project Cape Verde.

**Comment by bavAVIA** [comment]
Sent for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22049171/5291a5be-dcf7-11e6-8623-9232a50f5aef.png)
