### ISSUE TITLE
GVSN-Preguica Airport-SAO NICOLAU-CAPE VERDE

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#1511]
Sao Nicolao - Preguica Airport being redone.
Part of Project Cape Verde.

**Comment by bavAVIA** [comment]
Sent for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22047117/98ef42da-dcea-11e6-8c21-7b9d12546a7a.png)
