### ISSUE TITLE
GVSV

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#1512]
Sao Pedro - Cesaria Evora International Airport being redone.
Part of Project Cape Verde.

**Comment by moritzbabl** [comment]
@kilt46 there will be a slight runway length issue, however, after checking SAT image, i don't see a reason to change the current state

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22182720/ec7555e0-e071-11e6-9aca-128fbf080c95.png)
