### ISSUE TITLE
GCRR

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1514]
recycling

**Comment by TristinWoolf** [comment]
Duplicate. #733

**Comment by brunocr98** [comment]
Recycling issue

**Comment by brunocr98** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21966502/38d3d188-db3a-11e6-98c3-e9eea87d88a2.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108001045-093fc200-6fb1-11eb-8cd1-8b56b9533778.png)
