### ISSUE TITLE
XWWL-Kinel'-Cherkasy (Tolkay)-SAMARA OBLAST-RUSSIA

### ISSUE THREAD

**Issue by ErshovlaD** [InfiniteFlightAirportEditing/Airports#1516]
Add please this airport in repo. And it already done, I send it in email :)

**Comment by kilt46** [comment]
![Uploading image.png…]()

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22047395/684a04e2-dcec-11e6-966e-7b9cd267dc03.png)
