### ISSUE TITLE
LIPX-Verona Villafranca Airport-VENETO-ITALY

### ISSUE THREAD

**Issue by johanneskkl** [InfiniteFlightAirportEditing/Airports#1517]
Verona airport . part of project italy

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by johanneskkl** [comment]
please unassign me. I am to latz to find the snapping issues in the military part.
I can provide the apt if someone interested

**Comment by brunocr98** [comment]
Up for grabs.

**Comment by dushyants19** [comment]
@johanneskkl please send the apt to the email ID

**Comment by dushyants19** [comment]
If anyone is interested, you can continue the work w/ this file


https://gist.githubusercontent.com/dushyants19/7ab2dd5541f4c8d5a7d4a32661556792/raw/ddeaa019357a3aba63f743697667698e2635a633/LIPX.dat

**Comment by Aviationluver** [comment]
I'm taking this one. I will be re-doing this one from scratch.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by kilt46** [comment]
Different apron config
![image](https://user-images.githubusercontent.com/14023167/27931749-f3f98c52-6260-11e7-9951-59630a8fa552.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27931761-ffa3040c-6260-11e7-96d7-4d3f74f848de.png)
![image](https://user-images.githubusercontent.com/14023167/27931790-14e95e6a-6261-11e7-9db6-41a689b5aebd.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34277305-b7f9f2da-e66a-11e7-992e-f0e9cb6d3a2e.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/70915746-2b2e6500-1ff9-11ea-8082-92a5541508e3.jpg)
