### ISSUE TITLE
ZB0L-Voskresenka (Aeropark)-SAMARA OBLAST-RUSSIA

### ISSUE THREAD

**Issue by ErshovlaD** [InfiniteFlightAirportEditing/Airports#1518]
Add please this airport in repo. And it already done, I send it in email :)

**Comment by ErshovlaD** [comment]
Russia region

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22167521/92c7c456-df2c-11e6-9af8-7b9c50adf12b.png)
