### ISSUE TITLE
SKVV

### ISSUE THREAD

**Issue by Yifan081** [InfiniteFlightAirportEditing/Airports#1519]
La Vanguardia Airport. Villavicencio, Colombia.  I'll redo it.

**Comment by Yifan081** [comment]
Has anyone worked on this one previously?

**Comment by kilt46** [comment]
Missing yellow line
![image](https://cloud.githubusercontent.com/assets/14023167/22091795/7eb87cc2-ddbe-11e6-9dae-94bd1a498549.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22091828/c85e00d6-ddbe-11e6-90c6-aef0859de60c.png)
