### ISSUE TITLE
KHIE- Mt. Washington Regional Airport

### ISSUE THREAD

**Issue by Theyoshifan200** [InfiniteFlightAirportEditing/Airports#1520]
Part of **Project New Hampshire**, I would like to do this airport I visited back in August. 
<img width="710" alt="screen shot 2017-01-14 at 7 36 43 pm" src="https://cloud.githubusercontent.com/assets/21222414/21959313/023fa07e-da91-11e6-858b-826c7bbb5a24.png">

**Comment by Theyoshifan200** [comment]
<img width="843" alt="screen shot 2017-01-14 at 11 08 19 pm" src="https://cloud.githubusercontent.com/assets/21222414/21960165/76f6cba0-daae-11e6-9952-6cc2b3652549.png">
Finally finished the airport, now has been sent in for review :)

**Comment by Theyoshifan200** [comment]
Found that I missed a Centerline into the runway. I have now updated that and is now fully complete.
<img width="686" alt="screen shot 2017-01-15 at 11 56 15 am" src="https://cloud.githubusercontent.com/assets/21222414/21964420/aa37c2d8-db19-11e6-922a-fe01327878af.png">

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22049512/4eeb20a0-dcf9-11e6-8f60-d584abde2750.png)
