### ISSUE TITLE
CYZF-Yellowknife Airport-NORTHWEST TERRITORIES-CANADA

### ISSUE THREAD

**Issue by Talentedrobloxen** [InfiniteFlightAirportEditing/Airports#1521]
Yellowknife canada airport

**Comment by Talentedrobloxen** [comment]
Some one did it already my bad

**Comment by kilt46** [comment]
This airport is not complete!

**Comment by Talentedrobloxen** [comment]
Ok well my remake is 90% complete ill push it out soon and some one can revise it and do a 2and layer scan before it gets put into the files

**Comment by alexpeterson-if** [comment]
Is this still incomplete? I can do it if so.

**Comment by brunocr98** [comment]
It’s all yours :)

**Comment by alexpeterson-if** [comment]
Sent for review.

**Comment by dushyants19** [comment]
Redone in 2ccf77b. :)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32867111-d6c50994-ca30-11e7-93b7-55f81201c083.png)
