### ISSUE TITLE
LFML-Marseille Provence Airport-PROVENCE-ALPES-COTE D'AZUR-FRANCE

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#1522]
Marseille Provence Airport, will redo it

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23003074/0226f8c6-f3b4-11e6-92f3-158f3b96bcb6.png)

**Comment by Czechoslovaki** [comment]
@Jeremy351 will update the airport with new remote stands.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106528742-de347900-64ae-11eb-8190-b858852a4006.png)
