### ISSUE TITLE
LIRQ-Firenze Peretola Airport-TOSCANA-ITALY

### ISSUE THREAD

**Issue by johanneskkl** [InfiniteFlightAirportEditing/Airports#1523]
Florence arport . part of project italy

**Comment by Epadilla1** [comment]
Can someone sign me up for this project, thanks!

**Comment by johanneskkl** [comment]
Yes sure!  Do you want to join me in project Italy?

**Comment by johanneskkl** [comment]
@moritzbabl  may you assign this to @Epadilla1 ?

**Comment by dushyants19** [comment]
@Epadilla1 progress?

**Comment by Epadilla1** [comment]
Working on final details, I am currently on a cruise therefore internet
connectivity is low, I will get back you once I get wifi connectivity on my
laptop.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25876845/6d95f482-34e5-11e7-8213-603d4c3a4869.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/70662469-06c33900-1c45-11ea-976e-ce3d1d106d2b.jpg)
