### ISSUE TITLE
XWWV-Samara (Kryazh)-SAMARA OBLAST-RUSSIA

### ISSUE THREAD

**Issue by ErshovlaD** [InfiniteFlightAirportEditing/Airports#1524]
Add please in repo. Russia location. Already done and send in e-mail.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22166699/02db6090-df28-11e6-8361-8ac707c9b3e1.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22166715/13610140-df28-11e6-9afc-f4cf048ec6db.png)

**Comment by ErshovlaD** [comment]
![image](https://cloud.githubusercontent.com/assets/22447757/22169178/ae7819b2-df8b-11e6-9a64-3bac2b1bbb0c.jpeg)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22169575/bb1ac012-df3a-11e6-9071-d0522150406c.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22169609/f056618c-df3a-11e6-90e0-55a88d03309e.png)
