### ISSUE TITLE
FXME

### ISSUE THREAD

**Issue by Theobsidianguy** [InfiniteFlightAirportEditing/Airports#1525]
doing this one. matekane airport lesotho

**Comment by dushyants19** [comment]
This airport is done - I did it. 

0ac4be6df66b8ff4f80d87e8f18371c93b33162e

The issue was recycled.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27130102-62b6a9fc-50ca-11e7-8e96-71098ef4f5f7.png)
