### ISSUE TITLE
WABB

### ISSUE THREAD

**Issue by 4riw** [InfiniteFlightAirportEditing/Airports#1527]
Working on WABB (Biak, Frans Kaisiepo, Indonesia)
this airport has 11,712 feet of runway, please add it to milestone

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22353854/1d477d46-e3e8-11e6-8e3c-cb2ff92f3403.png)

**Comment by MajorTomMueller** [comment]
https://aimindonesia.dephub.go.id/images/281-WABB%20AD%202.24-1_AMDT%2058%20Dated%2008%20Dec%2016.pdf
https://aimindonesia.dephub.go.id/images/117-WABB%20AMDT%2060.pdf
spawns update and buildings removed.
Airport alligned.
