### ISSUE TITLE
FTTJ

### ISSUE THREAD

**Issue by ebukarthur** [InfiniteFlightAirportEditing/Airports#1530]
♻️ 

-Bruno

**Comment by dushyants19** [comment]
Stop creating duplicates.

**Comment by PaulNielsen** [comment]
@dushyants19 I think @ebukarthur means he is going to edit it.

**Comment by brunocr98** [comment]
This is a duplicate, search before posting 

See issue #1468

**Comment by brunocr98** [comment]
Recycling....

**Comment by IceBlue02** [comment]
I'll do.

**Comment by IceBlue02** [comment]
Done.
https://github.com/InfiniteFlightAirportEditing/Airports/commit/9e52c1b323426556cc0c8e9fc381f6e724de934f?diff=unified

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25303389/ad05b192-2717-11e7-9e77-58ddfe89c0ca.png)
