### ISSUE TITLE
CYQR-Regina International Airport-SASKATCHEWAN-CANADA

### ISSUE THREAD

**Issue by Talentedrobloxen** [InfiniteFlightAirportEditing/Airports#1532]
♻️ 

-Bruno

**Comment by brunocr98** [comment]
Why you closed this issue?

**Comment by brunocr98** [comment]
This is a duplicate btw.

#1050

**Comment by brunocr98** [comment]
Recycled....now Muscat Airport.

**Comment by Talentedrobloxen** [comment]
Some one already did holman feild i checked the files

**Comment by Talentedrobloxen** [comment]
Ill do rochester international airport mn instead no one has done it yet so ill do it

**Comment by brunocr98** [comment]
I'll be editing this one soon.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25045535/73b5d3de-20f2-11e7-881e-7a9847e5ae59.png)

**Comment by kilt46** [comment]
Duplicates removed

**Comment by MajorTomMueller** [comment]
rework required:
![CYQR-rwn](https://user-images.githubusercontent.com/26853210/80117802-22d1d200-8577-11ea-81d0-e0642ce86cd0.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105579319-6d24f100-5d4b-11eb-9389-892927ef344e.png)
