### ISSUE TITLE
KRST-Rochester International Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by Talentedrobloxen** [InfiniteFlightAirportEditing/Airports#1534]
Rochester International Airport ,Minnasota ,united states of america.....(ill do it)

**Comment by dushyants19** [comment]
Send an email to airports@liveflightapp.com please.

**Comment by dushyants19** [comment]
@Talentedrobloxen  any progress?

**Comment by dushyants19** [comment]
@bavAVIA interested? huge american airport with great scenery

**Comment by bavAVIA** [comment]
I literally told you I am planning to do this one in the supervisor channel earlier today.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31104770-8cd0dfb0-a7a4-11e7-952b-78219d0960f1.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/58842853-62818980-8646-11e9-89f2-fa3cbea143ec.jpg)
