### ISSUE TITLE
ZSQD

### ISSUE THREAD

**Issue by Yifan081** [InfiniteFlightAirportEditing/Airports#1535]
Liuting Airport. Qingdao, China. I'll edit it.

**Comment by Yifan081** [comment]
Submitted for revision.

**Comment by moritzbabl** [comment]
Added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22393327/e2fae38e-e4c9-11e6-8c62-02cf8bbb84b5.png)
