### ISSUE TITLE
KBJC-Rocky Mountain Metropolitan Airport-COLORADO-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#154]
Denver

**Comment by JohnPreston21** [comment]
I'll be doing this one, Thanks :)

**Comment by JohnPreston21** [comment]
Added taxi lines, removed old boundary and created a new one. added spawn-ins to accommodate both ends of the field.

**Comment by kilt46** [comment]
This one requires a rewrite. There are Zero Gates. This is an original X-Plane vintage. See kiltmchaggis.com

**Comment by kilt46** [comment]
Image: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=KBJC

**Comment by samuelandersson** [comment]
Here we go. Starting on the one now.

**Comment by samuelandersson** [comment]
Quitting this project. Can't stand creating all the buildings.

**Comment by kilt46** [comment]
spawn on runway

**Comment by kilt46** [comment]
Complete redo of airport INCLUDING buildings

**Comment by kilt46** [comment]
http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=KBJC

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21080544/4bd0cd9c-bf77-11e6-90e2-523ed2739e35.png)

**Comment by MajorTomMueller** [comment]
Ups

**Comment by brennanhackard** [comment]
sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/92983375-98780500-f468-11ea-800e-141a449ef0bd.png)
