### ISSUE TITLE
CYQM

### ISSUE THREAD

**Issue by tranquil-skyflyer** [InfiniteFlightAirportEditing/Airports#1540]
Greater Moncton Roméo LeBlanc International Airport
10k+ ft runway.

**Comment by Aviationluver** [comment]
@tranquil-skyflyer How is this one coming along?

**Comment by tranquil-skyflyer** [comment]
Last couple weeks been busy, will get done soon.

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by Aviationluver** [comment]
I'll grab this one. A nice little relief airport before I do a few bigger airports. Priority II airport.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24833132/7e2b1372-1c85-11e7-8d3e-584bb2baa365.png)
