### ISSUE TITLE
KDAW

### ISSUE THREAD

**Issue by Theyoshifan200** [InfiniteFlightAirportEditing/Airports#1541]
Part of **Project New Hampshire**, I would like to do Skyhaven Airport

**Comment by dushyants19** [comment]
any progress?

**Comment by dushyants19** [comment]
i'll do it.

**Comment by dushyants19** [comment]
done.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27107674-f09efc9a-505e-11e7-99f9-ebc272c692d6.png)
