### ISSUE TITLE
MDPP-Puerto Plata Airport-PUERTOM PLATA-DOMINICAN REPUBLIC

### ISSUE THREAD

**Issue by MiguelIF27** [InfiniteFlightAirportEditing/Airports#1543]
Int'l Gregorio Luperón Airport (Puerto Plata)

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
Incorrectly gated
![image](https://cloud.githubusercontent.com/assets/14023167/22393502/585ee96a-e4cd-11e6-967a-6b7293343b4d.png)

**Comment by kilt46** [comment]
Also missing outlines at gates
![image](https://cloud.githubusercontent.com/assets/14023167/22393554/27092a96-e4ce-11e6-97e0-a4ce53f2e126.png)

**Comment by MiguelIF27** [comment]
I am editing it

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23824847/11157cac-0644-11e7-9205-44660e76fc0e.png)
