### ISSUE TITLE
NZMF

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#1545]
Milford Sound, NZ

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22089515/357b75bc-ddb1-11e6-9fce-ced6a9c23097.png)

**Comment by RyanEpps** [comment]
Added

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/58833686-f2fca180-8627-11e9-860e-49c03b146b65.jpg)
