### ISSUE TITLE
WIII-Jakarta International/Soekarno Hatta Airport-BANTEN-INDONESIA

### ISSUE THREAD

**Issue by 4riw** [InfiniteFlightAirportEditing/Airports#1547]
I will working on WIII/CGK (Soekarno-Hatta Intl, Jakarta, Indonesia).
have 2 runways with 11800ft & 12000ft

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
Should be no white lines around buildings
![image](https://cloud.githubusercontent.com/assets/14023167/23093250/4fc6c19c-f5a3-11e6-94bc-6bc2e3c8434f.png)

**Comment by kilt46** [comment]
Missing white outlines at gates - use white dashed for jetbridge danger zones
![image](https://cloud.githubusercontent.com/assets/14023167/23093251/60bc7ef6-f5a3-11e6-83c6-bfb714e40d5c.png)

**Comment by kilt46** [comment]
Expect below image - ALSO with interconnects between gates
![image](https://cloud.githubusercontent.com/assets/14023167/23093266/e4d4bbf4-f5a3-11e6-850f-b83b8b884cfe.png)

**Comment by moritzbabl** [comment]
fixed

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23330708/67367f9e-fb1a-11e6-8212-20a29b30685e.png)

**Comment by kilt46** [comment]
EC1 and EC2 plus Apron H added
![image](https://user-images.githubusercontent.com/14023167/39095361-ee7b2fe6-4604-11e8-96f4-991275fdf3fd.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/39095368-ff9ac084-4604-11e8-9ce9-e5773ac5c3c5.png)
![image](https://user-images.githubusercontent.com/14023167/39095371-0cdc186a-4605-11e8-9d1d-974c59514d89.png)

**Comment by moritzbabl** [comment]
Airport got a new runway with additional taxiways, imagery is available from Bing

**Comment by RyanEpps** [comment]
Jake's problem now

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/89475744-78a93f00-d74e-11ea-9807-2687ee592d95.png)
