### ISSUE TITLE
UWWQ-Samara (Krasnyy Yar)-SAMARA OBLAST-RUSSIA

### ISSUE THREAD

**Issue by ErshovlaD** [InfiniteFlightAirportEditing/Airports#1548]
Already done and send via email. Check please and add in repo list

**Comment by IceBlue02** [comment]
@Adam167 please read description, he has finished and has been sent in

**Comment by ErshovlaD** [comment]
IceBlue02, what are you doing? First you need to check out my airport, and then to close the issue.

**Comment by dushyants19** [comment]
Not approved yet guys..

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22618311/e8e40df4-ea9e-11e6-8abd-0dc035f5daff.png)
