### ISSUE TITLE
YLZI-Lizard Island Airport-QUEENSLAND-AUSTRALIA

### ISSUE THREAD

**Issue by Talkingribzz** [InfiniteFlightAirportEditing/Airports#1549]
I'm going to redo Lizard Island.

**Comment by moritzbabl** [comment]
there are different runway lengths on the web, the difference results from in- or excluding the displ. threshold in the length, according to the markings i'd suggest to leave the runway length as it is now @kilt46

**Comment by kilt46** [comment]
Runway length too long
![image](https://cloud.githubusercontent.com/assets/14023167/22182575/2d05703a-e06e-11e6-9ca9-467557410b49.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22182578/3c15ba6c-e06e-11e6-97d8-60a53d0fce9e.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22182697/77822556-e071-11e6-86b9-c4acfa4e9a10.png)
