### ISSUE TITLE
KBKF

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#155]
Denver

**Comment by kilt46** [comment]
This one needs gates and is original X-Plane Vintage. Very spartan

**Comment by kilt46** [comment]
Image: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=KBKF

**Comment by kilt46** [comment]
spawn on runway

**Comment by dushyants19** [comment]
I will do this :blush:

**Comment by dushyants19** [comment]
ReDone and Approved by Jonathan.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21077991/867a31b6-bf24-11e6-9025-97b7f73513a8.png)
