### ISSUE TITLE
MMTG-Tuxtla Gutierrez Airport-CHIAPAS-MEXICO

### ISSUE THREAD

**Issue by lalomarlin** [InfiniteFlightAirportEditing/Airports#1550]
Being Redone

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
Runway size incorrect
![image](https://cloud.githubusercontent.com/assets/14023167/22169325/ebac72e0-df38-11e6-922e-b5830b17ea1f.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22169332/f70d5398-df38-11e6-9b91-456ec41166a8.png)

**Comment by moritzbabl** [comment]
added with fixed runway length

**Comment by Tristanpearson** [comment]
Hey guys can I suggest a air port for the army force military base would
you like the map and the satellite imagery I think it would be cool inbox
me if you would like that ok thanks

**Comment by brunocr98** [comment]
@Tristanpearson, if you want to do that airport, please send an email to airports@liveflightapp.com. Follow the setup instructions in order to start. Thanks :)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22182374/a69c6534-e069-11e6-99f2-b9b970a420aa.png)
