### ISSUE TITLE
8B2- Twin Mountain Airport [Private] New Hampshire, USA

### ISSUE THREAD

**Issue by Theyoshifan200** [InfiniteFlightAirportEditing/Airports#1557]
Part of **Project New Hampshire** I would like to do this airport. Actually, I already finished this airport before I created this issue. 
<img width="653" alt="screen shot 2017-01-20 at 9 39 27 pm" src="https://cloud.githubusercontent.com/assets/21222414/22171331/3595a992-df59-11e6-8b46-effaba11e037.png">

**Comment by Theyoshifan200** [comment]
Airport has been submitted :) I did some touchups before submission.
<img width="707" alt="screen shot 2017-01-20 at 9 50 47 pm" src="https://cloud.githubusercontent.com/assets/21222414/22171401/456bbf6c-df5b-11e6-8908-21d00af127d5.png">

**Comment by moritzbabl** [comment]
added

**Comment by Theyoshifan200** [comment]
photo?

**Comment by brunocr98** [comment]
Kilt will add it :)

**Comment by Theyoshifan200** [comment]
oh, ok :)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22182406/731fcb82-e06a-11e6-8dd8-2984200ce055.png)
