### ISSUE TITLE
VVTS-Tan Son Nhat International Airport-HO CHI MINH-VIETNAM

### ISSUE THREAD

**Issue by Yifan081** [InfiniteFlightAirportEditing/Airports#1558]
Tan Son Nhat International Airport. Ho Chi Minh City, Vietnam. Will redo it

**Comment by Yifan081** [comment]
Poor /outdated imagery is really hampering the task. If someone is eager to take it, please go ahead. (Sorry)

**Comment by brunocr98** [comment]
Up for grabs.

**Comment by Aviationluver** [comment]
I'll take this one.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24832250/f3a9d580-1c70-11e7-8c15-e35b2d3bb90a.png)

**Comment by aads552** [comment]
Can I take this airport? It's been a while since this issue reopened. I'm ready to rework this now.

**Comment by IFUA2003** [comment]
Can i take this one too? I’m almost done with this project.

**Comment by brunocr98** [comment]
@IFUA2003 this airport is already assigned to someone new not long ago. Choose another project.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/77239839-c79a7180-6bbd-11ea-9d1c-e7f96556b46f.jpg)

**Comment by brunocr98** [comment]
@IFUA2003 is adding new things to the western apron of this airport.

**Comment by IFUA2003** [comment]
![ts](https://user-images.githubusercontent.com/43931356/78680039-2f1e2400-7915-11ea-8b6b-5cddfd3e27ca.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78690246-931cfa00-78cd-11ea-97a4-8fdae7f1bdeb.jpg)

**Comment by MajorTomMueller** [comment]
-some smart fixes found last editor after last accepted.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103154129-28f9fd00-475b-11eb-9cf3-081778373538.png)
