### ISSUE TITLE
KFCS

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#156]
Denver

**Comment by Swang007** [comment]
Adding new spawn points & parking lines

**Comment by Swang007** [comment]
Note to self: fix layering for taxiway shoulders.

**Comment by Swang007** [comment]
Looks amazing, can't wait for the next scenery push!

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21078066/1659f652-bf27-11e6-9e3b-99a772155977.png)
