### ISSUE TITLE
FHSH-St Helena Airport-SAINT HELENA-SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA

### ISSUE THREAD

**Issue by IceBlue02** [InfiniteFlightAirportEditing/Airports#1560]
New airport, not in repo, to go in St Helena folder. Making.

**Comment by IceBlue02** [comment]
Allez Fini

https://github.com/InfiniteFlightAirportEditing/Airports/commit/039a71ed9061461144cef20c1e5360c3038b2d3e

Note for Kilt- this is a new airport, is certified as of May last year. It may or may not be on navigraph, I'm not sure. If not, charts are here http://www.atns.com/atm.php#subnav (projects on the right sidebar)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22390567/69220e9c-e4b1-11e6-854d-3dfeadf8520e.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106356395-e29d3e00-62c4-11eb-80db-e725900c92f3.png)
