### ISSUE TITLE
26U-McDermitt State Airport-OREGON-USA

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#1563]

**Comment by dushyants19** [comment]
Isn't this in IF already?

**Comment by brunocr98** [comment]
Ehm...maybe not redone?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/37234719-020d75e0-23bf-11e8-9879-2de9a0cf3e38.png)

**Comment by Czechoslovaki** [comment]
sent for OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/80624136-a1b88600-8a21-11ea-8d71-12abad827e90.jpg)
