### ISSUE TITLE
SARI-Cataratas Del Iguazu Airport-MISIONES-ARGENTINA

### ISSUE THREAD

**Issue by Talkingribzz** [InfiniteFlightAirportEditing/Airports#1565]
♻️

**Comment by dushyants19** [comment]
@Talkingribzz any progress?

**Comment by Tom-Bonfield** [comment]
Is it ok if I try this one

**Comment by dushyants19** [comment]
ok

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/35767080-6c234a84-08aa-11e8-8ac9-068126c7b718.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55441694-52c7c500-5571-11e9-86f0-dddca559c54a.png)
