### ISSUE TITLE
RPVA

### ISSUE THREAD

**Issue by GentlePig500** [InfiniteFlightAirportEditing/Airports#1566]
I will fix taxiway add buildings gates and other issues.

**Comment by GentlePig500** [comment]
Sent For Review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22277340/6275024e-e280-11e6-9cf6-fa1cb5a7fad1.png)
