### ISSUE TITLE
FSIA-Seychelles Airport-MAHE-SEYCHELLES

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#1568]
Doing this airport. Seychelles Airport.

**Comment by brunocr98** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22277065/1b561878-e27e-11e6-851f-a19323597d9e.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/74991332-6ba8c580-5424-11ea-92ca-a8be210d906e.jpg)

**Comment by MajorTomMueller** [comment]
Reworks needed.

**Comment by shivaay20** [comment]
Willing to start on this airport

**Comment by brunocr1050** [comment]
This airport was redone just last year and imagery hasn't changed since then. Closing this issue.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123343964-742d7680-d518-11eb-9b75-c3bb5da3fa77.png)
