### ISSUE TITLE
SLLP-El Alto International Airport-LA PAZ-BOLIVIA

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1569]
Doing this airport. El Alto Airport

**Comment by brunocr98** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22358955/cfc492ea-e408-11e6-82b7-95d1d36f9441.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68349557-552c6780-00dc-11ea-88b7-9386573161d8.jpg)
