### ISSUE TITLE
SKSM

### ISSUE THREAD

**Issue by Yifan081** [InfiniteFlightAirportEditing/Airports#1571]
Simon Bolivar International Airport. Santa Marta, Colombia. I'll redo this one.

**Comment by bavAVIA** [comment]
Do not create any more issues! You are allready assigned to 4, but I'll still assign you to this one.
The limit is 4 airports at a time.

**Comment by Yifan081** [comment]
Wow. I think you might have said that in a more gentle way. If I am creating this one, is because I am making progress on the ones I already have.

**Comment by bavAVIA** [comment]
I'd wish to ask his majesty to note the very few rules we have established while executing his highly appreciated voluntary work in the future.

**Comment by Yifan081** [comment]
Irony never contributes.

**Comment by moritzbabl** [comment]
added, you can calm down @bavAVIA ;)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22390798/dae847b6-e4b2-11e6-88df-56ac2986f17e.png)
