### ISSUE TITLE
LEST

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#1572]
Santiago de Compostela International Airport, Galicia, Spain.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22536205/936ed42e-e8c5-11e6-9f1d-4a305a2bebb9.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/110187001-87d39680-7ddc-11eb-8bd2-fe039f9bf04f.png)
