### ISSUE TITLE
NTAA-Tahiti Airport-TAHITI-FRENCH POLYNESIA

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1575]
Doing this airport. Fa'a'ā Airport

**Comment by brunocr98** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22388100/76c85d10-e4a4-11e6-81d1-47c7f3b1751d.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/75613624-aa1e3e80-5b0e-11ea-970e-a5aaf0fbfc13.jpg)
