### ISSUE TITLE
EDXH-Helgoland Dune Airport-SCHLESWIG-HOLSTEIN-GERMANY

### ISSUE THREAD

**Issue by CasaAviation** [InfiniteFlightAirportEditing/Airports#1578]
EDXH Helgoland-Dune, I will do this airport

**Comment by dushyants19** [comment]
Any progress? @CasaAviation

**Comment by CasaAviation** [comment]
I will continue after a break tomorrow.  But thanks for the information

**Comment by moritzbabl** [comment]
Is there any progress?

**Comment by dushyants19** [comment]
Grabs

**Comment by CasaAviation** [comment]
I'm very sorry. But I can't continue on this project anymore. I have a lot
in school and have to develop and design thinhs for companies. Also I m
working on VirtualHub.  Thanks for your email.
Caspar Wamik

**Comment by bavAVIA** [comment]
Perhaps taking over shortly.

**Comment by moritzbabl** [comment]
Are you busy atm? I'm doing Bavarian GA anyway so I could include it in my spam evening today

**Comment by CasaAviation** [comment]
Oh. That would be very helpful.

**Comment by bavAVIA** [comment]
Taking over.

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27033635-e5b20a40-4f3f-11e7-9246-9dc8e4a3adbe.png)
