### ISSUE TITLE
4F2

### ISSUE THREAD

**Issue by DeerCrusher** [InfiniteFlightAirportEditing/Airports#1579]
I will work on 4F2, Panola County-Sharpe Airfield

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22533449/e1aff1c0-e8b3-11e6-8071-f6b7400ae074.png)

**Comment by kilt46** [comment]
Airport relocated to correct coordinates
