### ISSUE TITLE
EGLJ

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#158]
London

**Comment by kohanson** [comment]
hey, I just opened up this airport and I think it is completed.

**Comment by kilt46** [comment]
This one has ZERO lines or Spawn Points
Image:http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=EGLJ

**Comment by samuelandersson** [comment]
Will redo.

**Comment by samuelandersson** [comment]
Now waiting for approval.

**Comment by samuelandersson** [comment]
Done and approved.

**Comment by kilt46** [comment]
spawn on runway

**Comment by samuelandersson** [comment]
Negative. There are no runway spawns on this airport.
![image](https://cloud.githubusercontent.com/assets/15381853/11457007/e5c8d0ca-969c-11e5-9ed9-d271ac8df8ce.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17264635/fbb9caee-55ad-11e6-8a21-8bdfb2694864.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18230999/89e14506-7271-11e6-82bc-cb90fb29dd2a.png)
