### ISSUE TITLE
FQMA-Maputo International Airport-MAPUTO-MOZAMBIQUE

### ISSUE THREAD

**Issue by AsianaIFVA** [InfiniteFlightAirportEditing/Airports#1580]
♻️

**Comment by liamkirky** [comment]
Please only create the issue if you are going to do it.

**Comment by brunocr98** [comment]
@AsianaIFVA, with all due respect, please **STOP** creating issues in our repository. All the airports will be added in Global Flight, edited or not edited, will be in there. Do us all a favor, and don't think in create an issue again.

Thanks

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24731974/49ee0366-1a33-11e7-9ab1-c6a7facb4e17.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68062080-e10e5000-fce6-11e9-9cdf-e5e2eebe59af.jpg)
