### ISSUE TITLE
KGGG

### ISSUE THREAD

**Issue by DeerCrusher** [InfiniteFlightAirportEditing/Airports#1581]
East Texas Regional Airport, I will work on this.

**Comment by DeerCrusher** [comment]
Sent in for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23049583/a4933402-f482-11e6-8a02-9bfba04dc4af.png)
