### ISSUE TITLE
MYSM-Cockburn Town Airport-SAN SALVADOR ISLAND-BAHAMAS

### ISSUE THREAD

**Issue by TristinWoolf** [InfiniteFlightAirportEditing/Airports#1586]

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22450893/9d0da9fc-e72f-11e6-80ff-779fb0c2b650.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42725454-234ca724-8749-11e8-8dbd-a07c358c1dce.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42725648-cf6d8cdc-874c-11e8-80c2-9c5bab99d993.png)
