### ISSUE TITLE
KHOU-William P Hobby Airport-TEXAS-USA

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#1587]

**Comment by brunocr98** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22618058/17b6f91c-ea99-11e6-8e57-7b878fbf4d60.png)

**Comment by brunocr1050** [comment]
This airport will need a redo.

**Comment by zhf21** [comment]
I will be reworking this (per my tag, lol). I'll get PAEN done as soon as possible. I have a bit of a busy schedule this week

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/119576050-a31bc580-bd7d-11eb-87ac-b7281b48308a.png)
