### ISSUE TITLE
KMEM-Memphis International Airport-TENNESSEE-USA

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#1588]
Doing this airport. Memphis Airport. Fedex's SuperHub.

**Comment by brunocr98** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22842302/64cd96c4-ef9a-11e6-8d53-9f283d3f3e91.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/49330257-bbfee380-f551-11e8-9948-f3d20257709d.png)

**Comment by kilt46** [comment]
Duplicate spawn removed. Buildings removed

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/89746124-a9a2b000-da7d-11ea-94ad-417a0f5d1e09.png)
