### ISSUE TITLE
ZBHH-Hohhot/Baita Airport-INNER MONGOLIA-CHINA

### ISSUE THREAD

**Issue by CNwyang** [InfiniteFlightAirportEditing/Airports#1590]
Baita Int'l airport,Hohhot,Inner Mongolia, China

**Comment by brunocr98** [comment]
Are you in our team? If not, please **DON'T** create random issues please.

**Comment by brunocr98** [comment]
Don't close this!

**Comment by CNwyang** [comment]
SORRY for opening it without joining the team, i'll reread the instructions and do it later, :D @brunocr98

**Comment by brunocr98** [comment]
Thanks for understanding 🙂

**Comment by moritzbabl** [comment]
just to make sure i'm not roasted for assigning him, he's now a member ;)

**Comment by CNwyang** [comment]
Sent for review

**Comment by CNwyang** [comment]
Sorry, revision😂

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
Missing runway holds
![image](https://cloud.githubusercontent.com/assets/14023167/23093625/29faeca8-f5ae-11e6-863a-bb8c8d3431f2.png)

**Comment by kilt46** [comment]
Buildings with white lines
![image](https://cloud.githubusercontent.com/assets/14023167/23093627/3debd27c-f5ae-11e6-96a8-560d79d62615.png)

**Comment by kilt46** [comment]
Also several spwan positions marked as 'HEAVY' . Heavy is reserved for types F and E

**Comment by CNwyang** [comment]
Sent for re-re-review😄

**Comment by moritzbabl** [comment]
fixed

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23330923/2950a2f2-fb21-11e6-8629-340a06b5bb4d.png)

**Comment by Czechoslovaki** [comment]
@zacky89315 will update the airport with the new apron section.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102946089-3c6c4600-4485-11eb-87f1-12530f16e21d.png)
