### ISSUE TITLE
URKK-Krasnodar (Pashkovsky)-KRASNODAR KRAY-RUSSIA

### ISSUE THREAD

**Issue by ErshovlaD** [InfiniteFlightAirportEditing/Airports#1591]
Being redone. Priority 2 (10 000> ft)

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22761485/8f15d250-ee20-11e6-89b5-eb69d0bf78c1.png)

**Comment by MajorTomMueller** [comment]
Whatbneeds to be done @AleksanderIF ?

**Comment by AleksanderIF** [comment]
Remove buildings, runway 05R/24L was reconstructed, 05C/24C is now a taxiway, tidy up entire airport

**Comment by AleksanderIF** [comment]
Sorry, 05R/23L and 05C/23C
