### ISSUE TITLE
ZSOF

### ISSUE THREAD

**Issue by Yifan081** [InfiniteFlightAirportEditing/Airports#1592]
Hefei Xinqiao International Airport, China. Will redo it.

**Comment by Yifan081** [comment]
Sent for revision.

**Comment by moritzbabl** [comment]
Added, Runway length was measured by me using google earth, it's correct. The airport replaced the old airport of the city

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22618117/8c9b09fc-ea9a-11e6-843d-e910aa46943e.png)

**Comment by moritzbabl** [comment]
updated by @Yifan081
