### ISSUE TITLE
EGNC-Carlisle Airport-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by ItsW1ll** [InfiniteFlightAirportEditing/Airports#1593]
Full Redo.

**Comment by moritzbabl** [comment]
added

**Comment by Will171** [comment]
whoops, it is close to Scotland if that makes any difference?

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22718001/c737048c-ed63-11e6-921f-240da7b87225.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45928181-04bc6f80-bf05-11e8-845c-338dee21fd09.png)

**Comment by ItsW1ll** [comment]
Will require a full redo as new apron added runway dimensions changed

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/47969681-efc51700-e040-11e8-85f5-d63a19125260.png)
