### ISSUE TITLE
KDLZ

### ISSUE THREAD

**Issue by DeerCrusher** [InfiniteFlightAirportEditing/Airports#1595]
Delaware Municipal Airport- Going to start working on this.

**Comment by DeerCrusher** [comment]
Sent in for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23048384/13b45184-f47b-11e6-98df-2773cc51389c.png)
