### ISSUE TITLE
URKA-Anapa (Vityazevo)-KRASNODAR KRAY-RUSSIA

### ISSUE THREAD

**Issue by ErshovlaD** [InfiniteFlightAirportEditing/Airports#1596]
Beind redone

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22717630/d02d511a-ed61-11e6-9568-7a9c1a3130ef.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44315289-5777a880-a3e8-11e8-946f-4d0a94d86852.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44340087-5a56b580-a449-11e8-8f65-65e31b5b9139.png)
