### ISSUE TITLE
URKG-Gelendzhik-KRASNODAR KRAY-RUSSIA

### ISSUE THREAD

**Issue by ErshovlaD** [InfiniteFlightAirportEditing/Airports#1597]
Being redone
One runway 10170 ft

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23096306/05e41642-f5df-11e6-97f5-2338b59a09a5.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44340818-ae629980-a44b-11e8-9b46-d28c4898aef9.png)
