### ISSUE TITLE
SKNV

### ISSUE THREAD

**Issue by Yifan081** [InfiniteFlightAirportEditing/Airports#1598]
Benito Salas Airport, Neiva, Colombia. Being reworked.

**Comment by Yifan081** [comment]
Sent for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22719063/44bdaec4-ed69-11e6-9f0f-d5569df82c72.png)
