### ISSUE TITLE
ZUUU-Chengdu Airport-SICHUAN-CHINA

### ISSUE THREAD

**Issue by CNwyang** [InfiniteFlightAirportEditing/Airports#1599]
Shuangliu/chengdu int'l,Sichuan, China. Being redone.

**Comment by CNwyang** [comment]
Sent for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
Outlines are not realistic. Please review outlines available in Bing

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24228380/c9f7f44c-0f41-11e7-9129-d59e433c834d.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/99011247-4eb3a580-2511-11eb-814f-3736698bb69e.png)
