### ISSUE TITLE
KOAK-Metropolitan Oakland International Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#16]
Runway direction changed

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21630693/3dc939d4-d1f9-11e6-960b-ffc313156d52.png)

**Comment by RyanEpps** [comment]
Isaac gonna mess some stuff up

**Comment by HiFlyerBwi** [comment]
It will be just fine, thanks for the suggestion.

**Comment by HiFlyerBwi** [comment]
Submitted for OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/69680770-abad1600-108a-11ea-9aa7-1264fb2ebab8.jpg)
