### ISSUE TITLE
LPMI-Mirandela Airport-BRAGANCA-PORTUGAL

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#1604]
Mirandela, Portugal

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22627184/852f9dec-eb83-11e6-8d85-3d262ad9ed5b.png)

**Comment by kilt46** [comment]
Miscellaneous items to right of airport

**Comment by JcFl4** [comment]
Nice catch! It is the original file of the airport that was displaced and I forgot to delete it.

**Comment by JcFl4** [comment]
Fixed.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22630336/d1a40d72-ebbd-11e6-90f7-fe5548a76bc8.png)
