### ISSUE TITLE
OISS-Shiraz International Airport-FARS-IRAN

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#161]
Please redesign me!

**Comment by Swang007** [comment]
Added terminal area with spawn points and simple taxi lines. Please remember to reclone the InfiniteFlightAirportEditing/Airports repository before working on or redoing this one, otherwise my changes will be lost!

**Comment by JohnPreston21** [comment]
Oh wait I was working on this one, guess I should have assigned myself first

**Comment by Swang007** [comment]
Yes, I didn't know you were working on this.

**Comment by kilt46** [comment]
According to the latest graphics I have there are no spawn points atm
Image: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=KATW

**Comment by samuelandersson** [comment]
Currently redoing this. Hope it gets better :)

**Comment by samuelandersson** [comment]
Done. Have redone everything but runways, frequencies, tower views (just moved a few meters to actual tower positions) and lights.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24590583/06eae1a4-17b5-11e7-9f1d-55f426163ffb.png)
