### ISSUE TITLE
RPMG-Dipolog  Airport-ZAMBOANGA DEL NORTE-PHILIPPINES

### ISSUE THREAD

**Issue by superven13** [InfiniteFlightAirportEditing/Airports#1610]
Start from scratch and add building, taxiway, gates and more.

**Comment by superven13** [comment]
Sent For Review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23047226/f93120dc-f473-11e6-8475-35a92d60c335.png)

**Comment by MajorTomMueller** [comment]
missaligned
![grafik](https://user-images.githubusercontent.com/26853210/125190746-345fd200-e22e-11eb-8298-b5b0ec9db4d0.png)
![grafik](https://user-images.githubusercontent.com/26853210/125190754-3d50a380-e22e-11eb-9732-d66954fd766e.png)

**Comment by MajorTomMueller** [comment]
@superven13 still active here? Then have a look.
(@becarboner3000 could you please check if he is still around)

**Comment by MajorTomMueller** [comment]
Up for grabs

**Comment by jaypzs** [comment]
Can i grab? thanks

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/132604250-a5b2806c-0f87-4dbf-8f27-1a4b7fa053f6.png)
