### ISSUE TITLE
AGGH

### ISSUE THREAD

**Issue by tranquil-skyflyer** [InfiniteFlightAirportEditing/Airports#1613]
Honiara Airport, Solomon Islands.
I'll be doing this one.

**Comment by tranquil-skyflyer** [comment]
Submitted for review.

**Comment by tranquil-skyflyer** [comment]
Resubmitted!

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23096349/5445f548-f5e0-11e6-91e6-7a67a3dcbe09.png)
