### ISSUE TITLE
LFBL 

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#1614]
Limoges - Bellegrade Airport
Being redone.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22857224/ac3cc04e-f066-11e6-8d06-7b1ad3e5a2e9.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54086944-4a86bc00-431c-11e9-9a0b-4ff3e0ccddd7.png)
