### ISSUE TITLE
CYWK

### ISSUE THREAD

**Issue by Yifan081** [InfiniteFlightAirportEditing/Airports#1616]
Wabush Airport. Newfoundland and Labrador, Canada. Redoing it.

**Comment by Yifan081** [comment]
Sent for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23103360/07fcb28a-f680-11e6-88c9-2e057466821e.png)
