### ISSUE TITLE
YSRI-Richmond (Nsw) Airport-NEW SOUTH WALES-AUSTRALIA

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#1618]
This airport is a mess
![image](https://cloud.githubusercontent.com/assets/14023167/22675954/27fa7bf2-ecae-11e6-8e96-3ca1e556b431.png)

**Comment by kilt46** [comment]
![img_0438](https://cloud.githubusercontent.com/assets/14023167/22675974/52e20b64-ecae-11e6-9a9e-69a006e8f3d2.PNG)

**Comment by DS2001** [comment]
I want to do this one

**Comment by dushyants19** [comment]
Any progress? @DS2001

**Comment by rnorris03** [comment]
I'll do this

**Comment by brunocr98** [comment]
Please ask an admin to add you to the organization, I can't assign you.

**Comment by rnorris03** [comment]
I think I am a collaborator now. Can I take this airport? Thanks.

**Comment by renorris** [comment]
Sorry for the inactivity, I'll catch up on this airport

**Comment by renorris** [comment]
Hello, could you possibly un-assign this airport to me? I don't have the time necessary to complete this larger airport. I'm already in progress with KFSD, and will stick with smaller airports in the future :)

@brunocr98

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36572364-01fd784e-1801-11e8-9464-78ad4cfb9f77.png)

**Comment by kilt46** [comment]
Redone from scratch

**Comment by MajorTomMueller** [comment]
spawn size doesn't reflesct real world usage

**Comment by MajorTomMueller** [comment]
https://github.com/InfiniteFlightAirportEditing/Airports/commit/59b75546efa9c19c645f64bd16a020cfd27ecce3
![YSRI-git](https://user-images.githubusercontent.com/26853210/70849321-d1049700-1e74-11ea-9601-2ebd7e73ccf6.png)
