### ISSUE TITLE
06FA

### ISSUE THREAD

**Issue by Adam167** [InfiniteFlightAirportEditing/Airports#1620]
In SOFLO region needs a redo, very wrong and has no ramp starts

**Comment by tranquil-skyflyer** [comment]
I'll do this.

**Comment by liamkirky** [comment]
Was it ever redone?

**Comment by moritzbabl** [comment]
No

**Comment by liamkirky** [comment]
Ok ill try and start it when airports master has finished unzipping

**Comment by liamkirky** [comment]
unassign me cant see somethings

**Comment by Spinxzl** [comment]
Liam has told me he isn't doing this anymore, unassign it please :) (he told me to post this as he's unavailable rn)

**Comment by brunocr98** [comment]
Finish your other 3 airports please :)

**Comment by cptchris** [comment]
I'll do this.

**Comment by cptchris** [comment]
Finally after many many many months, sent in for review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30766872-ad1646f0-9fbd-11e7-9ada-9ed22b721a99.png)
