### ISSUE TITLE
ZSYW

### ISSUE THREAD

**Issue by LightsR** [InfiniteFlightAirportEditing/Airports#1624]
Yiwu,Zhejiang, China. Being redone.

**Comment by dushyants19** [comment]
Any progress? @LightsR

**Comment by LightsR** [comment]
I have sent the file to the mailbox，but no one answered me

**Comment by dushyants19** [comment]
USE #peer-review next time on slack

**Comment by LightsR** [comment]
sent for a review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26708194/eaa70f92-470f-11e7-8695-16b70d780561.png)
