### ISSUE TITLE
CYZD-Toronto/Downsview Airport-ONTARIO-CANADA

### ISSUE THREAD

**Issue by tranquil-skyflyer** [InfiniteFlightAirportEditing/Airports#1626]
Toronto/Downsview (Downsview) Airport
Final assembly plant for the Bombardier Q400 and Global Series.
I'm up to doing this. Needs to be completely redone.

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by aircanada143** [comment]
I can do it :)

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30991147-7dfdc018-a469-11e7-8efc-785aa31208c2.png)
