### ISSUE TITLE
EPKT-Katowice-Pyrzowice Airport-SILESIAN-POLAND

### ISSUE THREAD

**Issue by unitedfc** [InfiniteFlightAirportEditing/Airports#1627]
RECYCLED ♻️

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26180292/50b48b4a-3b2e-11e7-86c0-99bc2ab01de2.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34961147-adb63584-fa03-11e7-97bd-05db61747db0.png)

Airport coordinates not lining up with satellite

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34990636-76e77b42-fa8c-11e7-8e31-02a6f017e734.png)
