### ISSUE TITLE
EGTE - Exeter Airport - England

### ISSUE THREAD

**Issue by Will171** [InfiniteFlightAirportEditing/Airports#1628]
I will be updating this airport to the latest google earth imagery

**Comment by Will171** [comment]
Sent for Review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23093429/cc015c72-f5a8-11e6-8d3b-1ab086e231c7.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45929024-bbbee800-bf11-11e8-848a-94605d25daad.png)
