### ISSUE TITLE
LATI

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#1630]
Tirana, Albania

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22857271/ae7b7f84-f067-11e6-99e2-0436d53b5ec4.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124360190-1bcc3800-dbee-11eb-804b-97a6aa325253.png)
