### ISSUE TITLE
SBFZ-Fortaleza Pinto Martins Airport-CEARA-BRAZIL

### ISSUE THREAD

**Issue by kyle12098** [InfiniteFlightAirportEditing/Airports#1634]
♻️

**Comment by lolo31r** [comment]
And again...please search for issues before doing one. I am editing it. We already have many airports with the suggestion label. So if you make an issue you should do it then

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36057860-30fd1d24-0dda-11e8-8526-a38cfb981d44.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51439711-c309be80-1c83-11e9-9766-66b103eae246.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/80316778-1f885180-87d6-11ea-8616-61c267ec467d.jpg)

**Comment by MBeringuy** [comment]
Updated Passenger Terminal

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/93649415-8e5a8700-f9d1-11ea-92fc-b9346d08c57f.png)
