### ISSUE TITLE
KSTK-Sterling Municipal Airport-COLORADO-USA

### ISSUE THREAD

**Issue by kyle12098** [InfiniteFlightAirportEditing/Airports#1635]
RECYCLED (TWICE) ♻️

**Comment by lolo31r** [comment]
Duplicate. Already was edited and approved by me. And for the future please don't make issues unless you are going to do it

**Comment by kilt46** [comment]
Apparently 2 runways here!
![image](https://user-images.githubusercontent.com/14023167/34357133-0109036a-ea0a-11e7-8d2f-ce7bb47f622a.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34362695-7757aa22-ea3b-11e7-8f9d-60c2dfa1a0ce.png)
