### ISSUE TITLE
KBOI-Boise Air Terminal/Gowen Field Airport-IDAHO-USA

### ISSUE THREAD

**Issue by CayJAvGeek** [InfiniteFlightAirportEditing/Airports#1636]
PLEASE EDIT ME

**Comment by Aviationluver** [comment]
I'll take this one. Priority II airport.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by dushyants19** [comment]
dat boiiiiiiiiiiii

**Comment by kilt46** [comment]
Please rename gates as per chart
![image](https://cloud.githubusercontent.com/assets/14023167/25109197/b5c9b776-23a0-11e7-8bc5-5dad8bc775e5.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25256873/aab357f6-25f9-11e7-9ec3-16aa2fae2b6a.png)

**Comment by kilt46** [comment]
Missing taxiway S and Sky West Hangar'
![image](https://user-images.githubusercontent.com/14023167/32991141-7d14bb06-ccfb-11e7-8d22-f4fa1381b4c0.png)

**Comment by ryu12332** [comment]
Progress?

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/37625138-b5fb6fe0-2b98-11e8-8e01-79f60d39156c.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52541595-8ac63f00-2d5c-11e9-8b68-1f6cad2ee84a.png)

**Comment by kilt46** [comment]
REMOVE DUPLICATE   SPAWNS | BUILDINGS REMOVED
-- | --

**Comment by Czechoslovaki** [comment]
Sent For OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/86483682-2a9db780-bd1a-11ea-938f-83a86980bee2.png)
