### ISSUE TITLE
KRNO-Reno/Tahoe International Airport-NEVADA-USA

### ISSUE THREAD

**Issue by 45679** [InfiniteFlightAirportEditing/Airports#1637]
:recycle:

-Bruno

**Comment by bavAVIA** [comment]
duplicate (https://github.com/InfiniteFlightAirportEditing/Airports/issues/55)

**Comment by brunocr98** [comment]
Recycled.

**Comment by Awoodbay** [comment]
I'll do this one

**Comment by brunocr98** [comment]
@Awoodbay have you received the invitation for GitHub, can't assign you because you don't appear on the list,

**Comment by Awoodbay** [comment]
@brunocr98 no I didn't get an email.

**Comment by Awoodbay** [comment]
@brunocr98 I got added

**Comment by brunocr98** [comment]
Still you don't appear in the list 😕

**Comment by Awoodbay** [comment]
Henrik said he added me on slack... @brunocr98

**Comment by Awoodbay** [comment]
Alright, now I should be on the list @brunocr98

**Comment by dushyants19** [comment]
Any progress? @Awoodbay

**Comment by Awoodbay** [comment]
@dushyants19 I'm so sorry, I'm a little past halfway done. My brother was in the hospital for over a month and I had to run the the operations in the house for the past couple of weeks and I barely even had time for myself. I'll have it done by the fourth at the latest. Thanks for understanding.

**Comment by IceBlue02** [comment]
Take the time you need, absolutely no rush or pressure. We just want to make sure you haven't completely given up 👍

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by twocflyer** [comment]
ill take this one!  email was was sent.

**Comment by brunocr98** [comment]
I have put the green label to indicate that the airport is being redone. In the meantime, please accept the invite that should have been sent to your email to join our team as a collaborator, so we can assign you to this issue. Let us know when you accepted the invite, thanks! :)

**Comment by twocflyer** [comment]
I was unable to edit for a while. And a couple weeks ago my computer was destroyed and i lost everything from liquid damage and will not be continuing this airport.  You can unassign me. Thank you.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36341146-553c3d3e-13af-11e8-86a6-89702b788a58.png)
