### ISSUE TITLE
SCDA-Iquique-Diego Aracena Airport-TARAPACA-CHILE

### ISSUE THREAD

**Issue by 45679** [InfiniteFlightAirportEditing/Airports#1638]
Recycle

**Comment by dushyants19** [comment]
Duplicate. Please search before posting.

**Comment by brunocr98** [comment]
@45679 please **STOP** creating issues, all the airports will be renovated at some point.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36057964-f06c1eb6-0ddb-11e8-8cf0-81ea04d00a26.png)
