### ISSUE TITLE
SKEJ-Barrancabermeja/Yariguies Airport-SANTANDER-COLOMBIA

### ISSUE THREAD

**Issue by N644US** [InfiniteFlightAirportEditing/Airports#1639]
♻️

-Bruno

**Comment by N644US** [comment]
Seems @CptNathanHope is already on it!

**Comment by brunocr98** [comment]
Reciclando ando. 😄♻️

**Comment by brunocr98** [comment]
Recycled. Now Pittsburgh Airport. Up for grabs!!!

**Comment by brunocr98** [comment]
I'll work on this one. It's a possible destination of Copa Airlines, therefore could be added to my endless project Hub of the Americas.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/26858469-02ddd664-4af7-11e7-80fd-31b3ba3b36d4.png)
