### ISSUE TITLE
LFOC

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#164]
Paris

**Comment by kilt46** [comment]
Image: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=LFOC
This is currently a bare bones airport. Needs some love!

**Comment by kilt46** [comment]
spawn on runway

**Comment by DS2001** [comment]
I want to do this one

**Comment by kilt46** [comment]
Airport Redesign

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20038087/0515f6ce-a3f3-11e6-883b-09fdb4efc307.png)
