### ISSUE TITLE
6B6-Minute Man Air Field-MASSACHUSETTS-USA

### ISSUE THREAD

**Issue by N644US** [InfiniteFlightAirportEditing/Airports#1640]
Part of "Project New England," 6B6 is a GA field in Stow, Mass. Nathan said it was cool if I did it.

**Comment by dushyants19** [comment]
@N644US yeah but hows the progress?

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24685213/ae79fa46-1971-11e7-8a7c-e4343f1e49cc.png)

**Comment by ECoops-123** [comment]
https://github.com/InfiniteFlightAirportEditing/Airports/commit/8cfb53396fdeb14bcb1e9bde815d7835bc1ecbcc

![Full](https://user-images.githubusercontent.com/59462519/126434948-3cf69b6a-5611-4fb4-8654-84ae65923578.png)
