### ISSUE TITLE
LIRN-Napoli-Capodichino Airport-CAMPANIA-ITALY

### ISSUE THREAD

**Issue by johanneskkl** [InfiniteFlightAirportEditing/Airports#1641]
Naples airport. Part of Project Italy.

**Comment by johanneskkl** [comment]
Sent to review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24071710/92b7b9de-0ba6-11e7-9c46-62b162321539.png)

**Comment by dushyants19** [comment]
He just redid it

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38771924-5e8150b4-3ff1-11e8-9412-f36607f03c56.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68038539-f5335c80-fca8-11e9-8674-ee1e0bff1bdf.jpg)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68039162-4859df00-fcaa-11e9-8e57-243d3263717a.jpg)
