### ISSUE TITLE
RPVM-Mactan-Cebu International Airport-CEBU-PHILIPPINES

### ISSUE THREAD

**Issue by superven13** [InfiniteFlightAirportEditing/Airports#1642]
Start the airport from scratch and add taxiway, terminal and more.

**Comment by superven13** [comment]
Sent For Review ;}

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23189754/1917bdd6-f85a-11e6-9509-57436e7dd4ca.png)

**Comment by MajorTomMueller** [comment]
New terminal with apron

**Comment by OscarConklin** [comment]
Could I please have this after one of my other issues gets closed?

**Comment by MajorTomMueller** [comment]
Yes, remind here when it is the case.

**Comment by OscarConklin** [comment]
One of my other issues has been closed. Can I be assigned to this now?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90312582-3957bc80-decb-11ea-947e-87a3cc8f691e.png)
