### ISSUE TITLE
DAAG-Houari Boumediene Airport-ALGIERS-ALGERIA

### ISSUE THREAD

**Issue by anthonyb123** [InfiniteFlightAirportEditing/Airports#1644]
♻️

**Comment by Tamz00** [comment]
I'll take this

**Comment by MajorTomMueller** [comment]
Any progress?

**Comment by Tamz00** [comment]
@MajorTomMueller No, old file became corrupted and I'm currently in exam season. I should begin editing again from July. You're more than happy to take this though if you'd like.

**Comment by Balloonchaser** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54886488-5d3ddc80-4e56-11e9-85a6-36c68036fcee.png)
