### ISSUE TITLE
LUKK-Chisinau Airport- CHISINAU-MOLDOVA

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#1645]
Chisinau Airport, Moldova

**Comment by moritzbabl** [comment]
done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23093148/97963c80-f5a0-11e6-9481-bfc1755233ec.png)

**Comment by moritzbabl** [comment]
More expansion works? 👀

**Comment by danisrils39** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/61163829-206e2200-a4e7-11e9-83e7-efa74ab4df64.jpg)
