### ISSUE TITLE
KCBF

### ISSUE THREAD

**Issue by SportsAviator8** [InfiniteFlightAirportEditing/Airports#1646]
Council Bluffs Municipal Airport, I will do it.

**Comment by dushyants19** [comment]
@SportsAviator8 any progress?

**Comment by SportsAviator8** [comment]
Yeah I am having trouble with some of the lighting and buildings but all
the taxiways are done.  Been busy with school work hoping to get some more
work on it done soon

**Comment by dushyants19** [comment]
Any progress? @SportsAviator8

**Comment by dushyants19** [comment]
Up for Grabs; Let us know if you want to do the airport.

**Comment by ewanfleming** [comment]
I can take it

**Comment by brunocr98** [comment]
Assigned to @ewanfleming

**Comment by ewanfleming** [comment]
Sent in for review

**Comment by moritzbabl** [comment]
Added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28044838-5b7380e0-659f-11e7-8cdb-a3a729d3980f.png)
