### ISSUE TITLE
WAHQ-Solo Adi Soemarmo Airport-JAWA TENGAH-INDONESIA

### ISSUE THREAD

**Issue by 4riw** [InfiniteFlightAirportEditing/Airports#1647]
WARQ (Solo Adi Sumarmo, Indonesia) being redone.
ICAO code has changed into WAHQ

**Comment by moritzbabl** [comment]
added as WAHQ

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26276129/d2625fa0-3d36-11e7-8e65-ad312f9a555f.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103312721-843e2080-49e3-11eb-8b93-5328bc5e94a6.png)
