### ISSUE TITLE
WIEE-Minangkabau Airport-SUMATERA BARAT-INDONESIA

### ISSUE THREAD

**Issue by 4riw** [InfiniteFlightAirportEditing/Airports#1648]
Working on new airport, WIEE (Padang Pariaman Minangkabau, Indonesia)

**Comment by moritzbabl** [comment]
added

**Comment by 4riw** [comment]
Sorry, i think i made a mistake here. WIEE is new ICAO code for WIPT. so its not a new airport, it should replace the original WIPT

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23327989/2f189cec-fadd-11e6-8524-8ad5177203fd.png)

**Comment by MajorTomMueller** [comment]
Apron extended

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85909815-592f0600-b7e1-11ea-803a-84e370cf44e7.png)
