### ISSUE TITLE
LKPA

### ISSUE THREAD

**Issue by johanneskkl** [InfiniteFlightAirportEditing/Airports#1649]
Policka airport. Czech republic.
LKPA is a little airfield with 2 runways.
(Grassways).

**Comment by moritzbabl** [comment]
I already got the airport for review, second try should pass soon @kilt46

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23189318/0175aabe-f858-11e6-8582-a723c6d4c815.png)
