### ISSUE TITLE
LFOE

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#165]
Paris

**Comment by kohanson** [comment]
I am currently working on this airport.

**Comment by kohanson** [comment]
My bad, I worked on LFOB using this apt.dat and noticed it after submitting.

**Comment by Swang007** [comment]
Oh no! Lol Imagine suddenly seeing KLAX where KSAN should be 😂

**Comment by kohanson** [comment]
lol, my 2 - 3 hours wasted. grr.

**Comment by Swang007** [comment]
Haha what a hoax that would be! I submit KLAX and KSAN and suddenly they're switched!

**Comment by kilt46** [comment]
Image: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=LFOE
Minimal airport

**Comment by samuelandersson** [comment]
Just for anyone willing to do this one, the airport is blurred out on the map as it is an air force base. In case you did not know.

**Comment by kilt46** [comment]
spawn on rnwy

**Comment by kilt46** [comment]
Airport redesigned

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17877883/44fa7cba-68ac-11e6-99af-3233150626ab.png)
