### ISSUE TITLE
EDVE-Braunschweig Wolfsburg Airport-NIEDERSACHSEN-GERMANY

### ISSUE THREAD

**Issue by lolo31r** [InfiniteFlightAirportEditing/Airports#1651]
redoing this

**Comment by Marsiana7** [comment]
Whats the progress of this airport?😊

**Comment by lolo31r** [comment]
I am about to finish it @marsiana7

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
This runway looks longer. What am I missing?
![image](https://user-images.githubusercontent.com/14023167/30032871-c2b9d27e-915d-11e7-8978-5a241c284e09.png)
![image](https://user-images.githubusercontent.com/14023167/30032883-cd2c2072-915d-11e7-957f-57f32e9dcf6c.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30034442-0d20696e-9167-11e7-8886-791613991aa7.png)
