### ISSUE TITLE
CSS3-Montréal/Les Cèdres Airport-QUEBEC-CANADA

### ISSUE THREAD

**Issue by adamalfinge13** [InfiniteFlightAirportEditing/Airports#1652]
Aérodome Les Cèdres Montréal operated by Laurentide Aviation, I will do this one.

**Comment by dushyants19** [comment]
@adamalfinge13 any progress?

**Comment by adamalfinge13** [comment]
A bit, it's going to be hard now with all my school exams!

2017-03-30 5:56 GMT-04:00 Dushyanth <notifications@github.com>:

**Comment by adamalfinge13** [comment]
Sorry, I have to close this issue because I won't be able to finishit!

Sorry for the trouble,

Adam

**Comment by adamalfinge13** [comment]
Someone could do it for me!

**Comment by brunocr98** [comment]
Please don't close an issue unless the airport is done.

**Comment by brunocr98** [comment]
Next time ask for being unassigned.

**Comment by adamalfinge13** [comment]
Ok, sorry.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27498197-8f9c48e0-5823-11e7-83e1-f2a18c25c6fa.png)
