### ISSUE TITLE
URML-Makhachkala (Uytash)-DAGESTAN REPUBLIC-RUSSIA

### ISSUE THREAD

**Issue by ErshovlaD** [InfiniteFlightAirportEditing/Airports#1656]
Being redone

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23330871/f9a29980-fb1f-11e6-961d-86c33008fb10.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44343442-89722480-a453-11e8-905b-1000907ecc64.png)
