### ISSUE TITLE
FZGN

### ISSUE THREAD

**Issue by tranquil-skyflyer** [InfiniteFlightAirportEditing/Airports#1657]
Boende Airport, African Rainforest (Democratic Republic of the Congo)
By request of @moritzbabl.

**Comment by tranquil-skyflyer** [comment]
Submitted for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23194003/467b1a72-f871-11e6-88a4-d202b30f26d9.png)
