### ISSUE TITLE
SAWH-Ushuaia Airport-TIERRA DEL FUEGO-ARGENTINA

### ISSUE THREAD

**Issue by Yifan081** [InfiniteFlightAirportEditing/Airports#1659]
Ushuaia - Malvinas Argentinas International Airport. Argentina. Redoing it.

**Comment by brunocr98** [comment]
This is your third airport. Don't create another issue until you finish one of your current assigned airports.

**Comment by Yifan081** [comment]
Sent

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23331021/c49b4b9e-fb22-11e6-8371-abc4d97ec634.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/61554835-425e2c00-aa34-11e9-9a94-4683d7bceec3.jpg)
