### ISSUE TITLE
LFPT-Pontoise Cormeilles En Vexin Airport-ILE-DE-FRANCE-FRANCE

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#166]
Paris

**Comment by kilt46** [comment]
spawn on runway

**Comment by kilt46** [comment]
Started

**Comment by kilt46** [comment]
Airport redesigned

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20038049/e69f9336-a3f1-11e6-9129-ac06a90990c3.png)

**Comment by brunocr1050** [comment]
Jeremy will be adding more spawns to this airport.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107101708-cece6c00-67dd-11eb-8930-dd065cafbe13.png)
