### ISSUE TITLE
XMWH-Chernyakhovsk-KALININGRAD OBLAST-RUSSIA

### ISSUE THREAD

**Issue by ErshovlaD** [InfiniteFlightAirportEditing/Airports#1661]
It is will be made from scratch
Create please folder with this airport in list of airports

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23827212/d4a88c16-0673-11e7-8460-14baeb1ff50a.png)
