### ISSUE TITLE
KROW-Roswell International Air Center-NEW MEXICO-USA

### ISSUE THREAD

**Issue by koolkid57312** [InfiniteFlightAirportEditing/Airports#1662]
RECYCLED ♻️

**Comment by dushyants19** [comment]
@koolkid57312 are you doing this?

**Comment by bavAVIA** [comment]
Up for grabs

**Comment by koolkid57312** [comment]
yes up for grabs

**Comment by brunocr98** [comment]
Please **DON'T** close the issue. Issues can only be closed when the airport gets reviewed and approved.

**Comment by willhax9** [comment]
What is involved in editing the airports?

**Comment by brunocr98** [comment]
You basically help us to renovate airports for FDS. Are you interested? send an email to airports@livelfightapp.com

**Comment by willhax9** [comment]
I am interested. I fly in and out of KBNA every year. What do you have to know how to do?

**Comment by brunocr98** [comment]
Wait until you get added, once there we'll help you to get you started.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29250095-e0748100-8001-11e7-93e6-5902146c61e0.png)
