### ISSUE TITLE
EDDI

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#1682]
Good old (and sadly closed :( ) Berlin Tempelhof Airport

**Comment by johanneskkl** [comment]
would like to fly there with a dc 3!
good luck!

**Comment by moritzbabl** [comment]
done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23239085/c0e7807a-f92a-11e6-8486-36974105636e.png)
