### ISSUE TITLE
MRLM-Limon International Airport-LIMON-COSTA RICA

### ISSUE THREAD

**Issue by koolkid57312** [InfiniteFlightAirportEditing/Airports#1683]

**Comment by brunocr98** [comment]
@koolkid57312, any progress?

**Comment by koolkid57312** [comment]
Yes I had to redo both airports cause my mom went on my mac and deleted it by accident.

**Comment by dushyants19** [comment]
So bad, Any progress? @koolkid57312 

Gotta be a koolkid and password protect the mac

**Comment by dushyants19** [comment]
Up for Grabs; Let us know if you want to do the airport.

**Comment by brunocr98** [comment]
Will do quickly...don't have homework to do.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27180961-29292904-519b-11e7-804b-da1b3e2827a2.png)
