### ISSUE TITLE
HAGM

### ISSUE THREAD

**Issue by tranquil-skyflyer** [InfiniteFlightAirportEditing/Airports#1686]
Gambella Airport, African Rainforest

**Comment by tranquil-skyflyer** [comment]
Submitted for review.

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by dushyants19** [comment]
i'll do it

**Comment by dushyants19** [comment]
done.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27130312-6b2699c0-50cb-11e7-823a-bdb395017454.png)
