### ISSUE TITLE
KLUK-Cincinnati Municipal Airport Lunken Field Airport-OHIO-USA

### ISSUE THREAD

**Issue by netjets-1951** [InfiniteFlightAirportEditing/Airports#1687]
Being redone
https://github.com/InfiniteFlightAirportEditing/Airports/blob/master/United%20States/K---/KL--/KLUK/apt.dat

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24225799/7fafa120-0f30-11e7-8fcf-0595ffce695b.png)

**Comment by kilt46** [comment]
Here is my data which shows this!
https://drive.google.com/open?id=1Vd652sUjg9VE1Z8nzi28hUhJwmRpK2eL

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/43045871-f1205906-8d85-11e8-8361-2226925a253f.png)

**Comment by orangejuicie** [comment]
I want to know elevation of KLUK.
Now apt.dat elevation is 480ft.
But chart says 483ft.
https://ja.flightaware.com/resources/airport/KLUK/IAP/all/pdf

Which is correct?

**Comment by brunocr98** [comment]
Nick is working on some updates.

**Comment by netjets-1951** [comment]
Sent in to be reviewed

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by RyanEpps** [comment]
Actually done, labels never removed.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48917436-7012b700-ee4c-11e8-9967-a5fc02d7fbf2.png)
