### ISSUE TITLE
KOSU

### ISSUE THREAD

**Issue by netjets-1951** [InfiniteFlightAirportEditing/Airports#1688]
Being redone
https://github.com/InfiniteFlightAirportEditing/Airports/blob/master/United%20States/K---/KO--/KOSU/apt.dat

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23827265/263989bc-0675-11e7-9c1b-fcc8a94d3ad8.png)
