### ISSUE TITLE
KILN

### ISSUE THREAD

**Issue by netjets-1951** [InfiniteFlightAirportEditing/Airports#1689]
Being Redone
https://github.com/InfiniteFlightAirportEditing/Airports/blob/master/United%20States/K---/KI--/KILN/apt.dat

**Comment by brunocr98** [comment]
This is your third issue. Don't create more.

**Comment by netjets-1951** [comment]
+10,000 FT

**Comment by brunocr98** [comment]
Any progress with this airport?

**Comment by netjets-1951** [comment]
Yes, sorry I just haven't had time time to fix the little errors. I'll finish it today.

**Comment by brunocr98** [comment]
Ok, no worries :)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25514448/bfe8675c-2ba2-11e7-9d41-6afd48d7ac16.png)
