### ISSUE TITLE
KTCM-Mcchord Field (Joint Base Lewis-Mcchord) Airport-WASHINGTON-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#169]
Seattle

**Comment by samuelandersson** [comment]
Added boundary.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19010623/0a77c668-8749-11e6-99ce-4e1be4bdbe0c.png)

**Comment by ryu12332** [comment]
Airport has some design issues. Hashing, public roads, incorrect hold markings, etc.

**Comment by moritzbabl** [comment]
updated

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36768857-bad1d8ca-1c06-11e8-9bf1-e1d0473801a4.png)
