### ISSUE TITLE
LICJ-Palermo Punta Raisi Airport-SICILIA-ITALY

### ISSUE THREAD

**Issue by johanneskkl** [InfiniteFlightAirportEditing/Airports#1690]
Palermo airport. Part of project Italy. One runway is longer than 10k feet.

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by johanneskkl** [comment]
@dushyants19 why were I unassigned from all my airports???

**Comment by johanneskkl** [comment]
Well, after the issue with the pavement please unassign me.
Who wants to redo this I have done a lot of white lines and the spawns are already set in with the correct number  (I used charts).
Who wants my version just contact me.
The mainly issue is the pavement isnt aligned with the imagery.
Up for grabs. Really easy if you dont  have imagery problems.
Please unassign me.

**Comment by bavAVIA** [comment]
Send a screenshot of the e-mail and the apt.dat via PM or in #peer-review on Slack, thanks.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26182689/64956524-3b3f-11e7-9d61-67c6a5999c30.png)

**Comment by moritzbabl** [comment]
@johanneskkl is going to rework this to improve the overall quality

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/43870154-c52d15a0-9b3b-11e8-934f-ffad49c8919c.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/70488413-64397780-1ad7-11ea-91e9-32b0c07ac64b.jpg)
