### ISSUE TITLE
MMQT-Queretaro Airport-QUERETARO-MEXICO

### ISSUE THREAD

**Issue by lalomarlin** [InfiniteFlightAirportEditing/Airports#1691]
Unintentional created issue, Sorry

**Comment by brunocr98** [comment]
X what?

**Comment by brunocr98** [comment]
@lalomarlin make sure what are you typing is the airport code.......

**Comment by brunocr98** [comment]
Are you doing this?

**Comment by lalomarlin** [comment]
Changed the name for redoing this airport

**Comment by brunocr98** [comment]
Ok then.

**Comment by lalomarlin** [comment]
Thanks

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23823352/198a5a42-0626-11e7-9816-78f361470be8.png)
