### ISSUE TITLE
EYKA

### ISSUE THREAD

**Issue by ryu12332** [InfiniteFlightAirportEditing/Airports#1693]
Recycled.

**Comment by bavAVIA** [comment]
Duplicate. https://github.com/InfiniteFlightAirportEditing/Airports/issues/577

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23826599/d2af11c8-0664-11e7-84b6-468ee01b1eed.png)
