### ISSUE TITLE
NZMK

### ISSUE THREAD

**Issue by BenW14** [InfiniteFlightAirportEditing/Airports#1694]

**Comment by dushyants19** [comment]
Any progress? @BenW14

**Comment by BenW14** [comment]
@dushyants19 I'm still working on it, I've been quite busy with school, so I'll finish it shortly

**Comment by dushyants19** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33518483-41790402-d75b-11e7-92a0-284ed74ba3ef.png)
