### ISSUE TITLE
KSYR

### ISSUE THREAD

**Issue by carterhumphreys** [InfiniteFlightAirportEditing/Airports#1695]

**Comment by carterhumphreys** [comment]
I am in the process of editing.

**Comment by dushyants19** [comment]
@carterhumphreys any progress?

**Comment by carterhumphreys** [comment]
It's been submitted for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
Not uploaded yet!

**Comment by moritzbabl** [comment]
sure? :P

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24578795/0e278146-16ae-11e7-80b8-ed61dd785e29.png)
