### ISSUE TITLE
NTTB-Motu Mute Airport-BORA BORA-FRENCH POLYNESIA

### ISSUE THREAD

**Issue by RTG113** [InfiniteFlightAirportEditing/Airports#1697]
The airport name is Motu Mute, located on the island of Bora Bora.

**Comment by dushyants19** [comment]
@RTG113 any progress?

**Comment by dushyants19** [comment]
up for grabs

**Comment by dushyants19** [comment]
i'll do it.

**Comment by dushyants19** [comment]
done.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27106993-7f319750-505b-11e7-8a20-6cdf81f5189f.png)

**Comment by kilt46** [comment]
add the new apron area.

**Comment by MajorTomMueller** [comment]
@danisrils39 https://www.sia.aviation-civile.gouv.fr/dvd/eAIP_18_JUN_2020/PAC-P/AIRAC-2020-06-18/html/eAIP/FR-AD-2.NTTB-fr-FR.html#AD-2.eAIP.NTTB

**Comment by Aceorbit** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/95522237-2de7b580-0991-11eb-89b9-3cdd21715465.png)
