### ISSUE TITLE
KORE-Orange Municipal Airport-MASSACHUSETTS-USA

### ISSUE THREAD

**Issue by GoldenSpotter** [InfiniteFlightAirportEditing/Airports#1699]
Part of Project New England.

**Comment by dushyants19** [comment]
Any progress? @GoldenSpotter

**Comment by CptNathanHope** [comment]
I'll do this.

**Comment by CptNathanHope** [comment]
All done.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27668361-4791a1fe-5c46-11e7-8c92-bd0f0c066a68.png)
