### ISSUE TITLE
FAOR-O. R. Tambo International Airport-GAUTENG-SOUTH AFRICA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#17]

**Comment by turkish1941** [comment]
I will make it

**Comment by turkish1941** [comment]
E mail is gone

**Comment by turkish1941** [comment]
2016-08-29 14:20 GMT+02:00 Dushyanth <notifications@github.com>:

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18111527/fbda4e9e-6ee5-11e6-9bb7-440a9ef8868a.png)
CARGO
![image](https://cloud.githubusercontent.com/assets/14023167/18111535/0b7a4be2-6ee6-11e6-9c97-0187a7834be7.png)
INTERNATIONAL TERMINAL
![image](https://cloud.githubusercontent.com/assets/14023167/18111543/21662638-6ee6-11e6-87ca-f3bb092e65a1.png)
DOMESTIC TERMINAL
![image](https://cloud.githubusercontent.com/assets/14023167/18111551/3021b822-6ee6-11e6-9a0e-dff6fe4da1f5.png)

**Comment by MajorTomMueller** [comment]
Editor is busy with real life. Up for grabs.

**Comment by kilt46** [comment]
Does this really need redone?

**Comment by Czechoslovaki** [comment]
I will be redoing this.

- Missing section of a ramp / missing parking positions
- Outdated marking configurations in select areas / missing lines
- Airport will be retraced with less imagery distortion 
- Absent line types that need to be added in
- Boundary too close to taxiways
- Missing atc frequencies

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103439623-19b7fb00-4c04-11eb-962d-6f472e67c146.png)
