### ISSUE TITLE
HETB-Taba Airport-SHAMAL SINA-EGYPT

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#170]
Please edit me

**Comment by dushyants19** [comment]
I checked this *airport* in Google maps, I cant see any scenery and this doesn't have an IATA code too.. The Wikipedia page is also empty

**Comment by kilt46** [comment]
Check my wiki: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=Singapore
https://www.google.com/maps/place/2.045361%20103.306519

**Comment by IceBlue02** [comment]
Taking This

**Comment by IceBlue02** [comment]
WEDbing having issues, so putting on hold. Does exist though

**Comment by kilt46** [comment]
This looks fine. Will close

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24731253/79f1b256-1a2e-11e7-91e7-1a01b39225a8.png)
