### ISSUE TITLE
KRAL-Riverside Municipal Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#1700]
Design issue. Needs fixing.

https://community.infinite-flight.com/t/very-slight-runway-inaccuracy-kral/100189

**Comment by brunocr98** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23754757/c5465de2-04a3-11e7-8354-bc2c5f28e2b3.png)

**Comment by Czechoslovaki** [comment]
- Main taxiway has the wrong surface
- Runways have the wrong surface / wrong settings
- All hangars are drawn as asphalt
- Buildings need to be removed
- Missing markings everywhere / markings not matching with imagery

Open to anyone to take, it really needs some help.
