### ISSUE TITLE
ROAH-Naha Airport-OKINAWA-JAPAN

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#1704]
Doing this airport. Naha Airport.

**Comment by brunocr98** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23826659/82f855fc-0666-11e7-8c90-5f6e4a4cc5be.png)

**Comment by MajorTomMueller** [comment]
Moved from duplicate #5221

**Comment by MBeringuy** [comment]
Runway 18R/36L and its access taxiways were removed at the request of the Administration because it is still under construction in real life.

**Comment by kilt46** [comment]
This is NOT a rework. This is an improvement from a previous iteration done by Oscar Conklin.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/120076894-6eee2080-c06d-11eb-8501-b68425b3f47a.png)
