### ISSUE TITLE
SKPV

### ISSUE THREAD

**Issue by Yifan081** [InfiniteFlightAirportEditing/Airports#1705]
El Embrujo Airport. Providencia Island, Colombia.

**Comment by Yifan081** [comment]
Sent for review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23824924/c76f6eb2-0645-11e7-86a5-3e322d8a34f9.png)
