### ISSUE TITLE
YNWN

### ISSUE THREAD

**Issue by InfiniteAirPhotos** [InfiniteFlightAirportEditing/Airports#1706]
Newman Airport, I'll do it

**Comment by brunocr98** [comment]
Ok...?

**Comment by dushyants19** [comment]
Any progress? @InfiniteAirPhotos

**Comment by dushyants19** [comment]
Up for Grabs; Let us know if you want to do the airport.

**Comment by dushyants19** [comment]
i'll do it.

**Comment by dushyants19** [comment]
Done. :)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27179145-edb32c38-5192-11e7-9b4f-f828845d399f.png)
