### ISSUE TITLE
WITT

### ISSUE THREAD

**Issue by haociek** [InfiniteFlightAirportEditing/Airports#1707]
Sultan Iskandar Muda, Banda Aceh.
will try to make this:)

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23825506/b6780fdc-0650-11e7-8ffa-c88083f5c73b.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48921607-731aa100-ee66-11e8-9e31-a8bcce605629.png)
