### ISSUE TITLE
OEDF-Dammam-King Fahd International Airport-ASH SHARQIYAH-SAUDI ARABIA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#171]
Please edit me

**Comment by kohanson** [comment]
link to #125  
completed and close.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25045342/78bbde6a-20f1-11e7-9022-41ecbf3ec811.png)

**Comment by kilt46** [comment]
Airport edited. Please remove buildings

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56457171-6b3f2a00-633c-11e9-90ee-3c2bcb3a6721.png)
