### ISSUE TITLE
PTPN-Pohnpei International Airport-POHNPEI-MICRONESIA

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#1711]
Pohnpei International Airport, Federated States of Micronesia, Ocenaia

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
Thin grey strip around airport shouldn't be there
![image](https://cloud.githubusercontent.com/assets/14023167/23825624/aad120d6-0652-11e7-9a87-a3efd9b46133.png)

**Comment by kilt46** [comment]
Duplicate terminal names
![image](https://cloud.githubusercontent.com/assets/14023167/23825627/bb3f9a60-0652-11e7-8d95-08b5568506dc.png)

**Comment by kilt46** [comment]
There is no perimeter road in existing satellite?
![image](https://cloud.githubusercontent.com/assets/14023167/23825642/fca10610-0652-11e7-8968-4610ff38030e.png)

**Comment by kilt46** [comment]
Main Apron looks very different!
![image](https://cloud.githubusercontent.com/assets/14023167/23825659/4e34b5a8-0653-11e7-841a-38e6dc8c0e77.png)
![image](https://cloud.githubusercontent.com/assets/14023167/23825663/5df1af3c-0653-11e7-8db8-8867e19ad4a5.png)

**Comment by bavAVIA** [comment]
Committed a fix, removed road around airport and I fixed the duplicate spawn name.
Also, you have outdated imagery. 

![screenshot 356](https://cloud.githubusercontent.com/assets/19326264/23825672/34354c18-068e-11e7-89bb-b4d6a772bde0.png)

**Comment by bavAVIA** [comment]
34e672da1c47d0254963f0109babbe6f39f80375

**Comment by kilt46** [comment]
Wow looks like SAS has better imagery than Google Earth! Thx Simon

**Comment by kilt46** [comment]
Looks a lot cleaner without boundary road - thx
![image](https://cloud.githubusercontent.com/assets/14023167/23825798/40ec2450-0656-11e7-80d7-8ad5b3aaa0f3.png)
