### ISSUE TITLE
CYEU

### ISSUE THREAD

**Issue by Yifan081** [InfiniteFlightAirportEditing/Airports#1712]
Eureka Aerodrome. Nunavut, Canada. Redoing it.

**Comment by Yifan081** [comment]
Sent for review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23824874/96fcabce-0644-11e7-8115-170c0ec78737.png)
