### ISSUE TITLE
KAVP

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#1713]
Scranton - Wilkes-Barre International Airport, Pennsylvania, United States.

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24227816/069c5040-0f3e-11e7-969c-4bb8564cf1c3.png)

**Comment by ECoops-123** [comment]
![Full](https://user-images.githubusercontent.com/59462519/111007086-f210ac00-8385-11eb-849c-cf5cf69d7433.png)
