### ISSUE TITLE
7B2 - Northampton Airport

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Airports#1715]
Part of [Project New England](https://community.infinite-flight.com/t/project-new-england/43169/).

*Disclaimer: I know this is a class echo airport, but I had already started it for a while and decided to finish it to get it out of the way. Thanks for understanding. :)

**Comment by CptNathanHope** [comment]
Sent for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23827484/32d6c1d0-067a-11e7-9b34-929691c6ee6f.png)
