### ISSUE TITLE
EDHK-Kiel Holtenau Airport-SCHLESWIG-HOLSTEIN-GERMANY

### ISSUE THREAD

**Issue by KarlLuebs** [InfiniteFlightAirportEditing/Airports#1716]
Also doing this one please.

**Comment by dushyants19** [comment]
How is this going? @KarlLuebs

**Comment by KarlLuebs** [comment]
Not too good. I’m always a bit slow as you know but of course it will be finished.

**Comment by moritzbabl** [comment]
Member inactive, up for grabs

**Comment by johanneskkl** [comment]
@KarlLuebs will you take this again? Otherwise will I

**Comment by KarlLuebs** [comment]
@johanneskkl 

Yes, please take it.

**Comment by johanneskkl** [comment]
sent in

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38134909-d27b1806-33da-11e8-984b-00e68523af30.png)
