### ISSUE TITLE
SKVP

### ISSUE THREAD

**Issue by Yifan081** [InfiniteFlightAirportEditing/Airports#1717]
Alfonso Lopez Pumarejo Airport. Valledupar, Colombia. Redoing it.

**Comment by Yifan081** [comment]
Sent for review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23824891/0c9eb8ae-0645-11e7-8f2b-99c432848858.png)
