### ISSUE TITLE
MMZO

### ISSUE THREAD

**Issue by johanneskkl** [InfiniteFlightAirportEditing/Airports#1719]
playa d´or intl. airport mexico. part of project mexico.

**Comment by bavAVIA** [comment]
This is your fourth airport. Please wait until one of your other airports is approved.
Not assigning for the time being.

**Comment by johanneskkl** [comment]
sadly dídnt saw your comment. this airport has been already sent for review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23823438/33cc67c2-0628-11e7-8d15-67101deb0bac.png)
