### ISSUE TITLE
RCFN

### ISSUE THREAD

**Issue by Yifan081** [InfiniteFlightAirportEditing/Airports#1721]
Fongnian Airport. Taitung, Taiwan. Redoing it.

**Comment by Yifan081** [comment]
Sent for review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23824696/b43acf9e-0640-11e7-9331-373d207eec25.png)
