### ISSUE TITLE
WADL-Lombok International Airport-TENGGARA BARAT-INDONESIA

### ISSUE THREAD

**Issue by haociek** [InfiniteFlightAirportEditing/Airports#1722]
Lombok International Airport, West Nusa Tenggara, Indonesia
will do this

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23824633/73d63188-063f-11e7-9f24-56c1fb1a0e6d.png)

**Comment by kilt46** [comment]
Request by Adibya Putra to review need for improvements to WADL 5/15/2021

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118399691-f1b1bd00-b623-11eb-9c6f-304c695d7e31.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118399826-9d5b0d00-b624-11eb-8e98-87b34b4d6241.png)

**Comment by kilt46** [comment]
Recommendation: Simple airport layout. Increased runway length and potentially 2 additional taxiways. Will recommend approval. Pending Ryan or Bruno to approve

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/119258553-caad3b00-bb8f-11eb-8129-072c2b521b71.png)
