### ISSUE TITLE
LOWG-Graz Airport-STEIERMARK-AUSTRIA

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#1723]
Finally got internet back at home. Graz-Thalerhof Int'l airport. I Will be doing this one. 

Runways are not longer than 10k feet.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23824149/f88bbfaa-0636-11e7-9340-9ed3af5a47de.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/71770778-a9529d00-2f0f-11ea-8cae-ccd6c5c2f11f.jpg)
