### ISSUE TITLE
KICT-Wichita Dwight D. Eisenhower National Airport-KANSAS-USA

### ISSUE THREAD

**Issue by captainmckean** [InfiniteFlightAirportEditing/Airports#1724]
Recycled by The GitHub Issue Recycler Inc. ♻️

**Comment by captainmckean** [comment]
im redoing YBCS

**Comment by brunocr98** [comment]
Duplicate. See issue #1402

**Comment by brunocr98** [comment]
Starting recycling process.

**Comment by brunocr98** [comment]
Recycling process completed. Now Wichita Dwight D. Eisenhower National Airport. Up for grabs!

**Comment by captainmckean** [comment]
i guess ill snatch that one up before anyone else does

**Comment by brunocr98** [comment]
@captainmckean Please search before creating an issue :) Thanks!

**Comment by brunocr98** [comment]
@captainmckean any news with the progress?

**Comment by dushyants19** [comment]
Grabs

**Comment by PrinceObi15** [comment]
I'll do this one.

**Comment by brunocr98** [comment]
Please accept the email you have been sent to join the repo, otherwise we won't be able to assign you.

**Comment by PrinceObi15** [comment]
I accepted the email.

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33232603-af0bd716-d1ce-11e7-992a-e1f8c174cd2b.png)
