### ISSUE TITLE
EPKK-Krakow-Balice Airport-LESSER POLAND-POLAND

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1728]
Saint John Paul II International Airport Kraków–Balice

**Comment by brunocr98** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23824065/69ae40e2-0635-11e7-8bf4-8467049e27fd.png)

**Comment by MajorTomMueller** [comment]
Detailed Information about Airport:
https://ais.pansa.pl/aip/pliki/EP_AD_2_EPKK_en.pdf
https://ais.pansa.pl/aip/pliki/EP_AD_2_EPKK_1-1-1_en.pdf
https://ais.pansa.pl/aip/pliki/EP_AD_2_EPKK_1-3-1_en.pdf

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/69197890-a80d1280-0b11-11ea-8f4f-becd8a2bd0da.jpg)
