### ISSUE TITLE
GCXO

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#1729]
Tenerife-North airport. I will re-do this one.

Runway is longer than 10k feet.

**Comment by brunocr98** [comment]
Have fun ;)

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24066065/89cfc9ec-0b3d-11e7-969a-bb6e6b6a5a5f.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108275825-851a4580-713c-11eb-9de7-92beebe91ac8.png)
