### ISSUE TITLE
NZNV

### ISSUE THREAD

**Issue by D-Gee** [InfiniteFlightAirportEditing/Airports#1730]
Doing this airport now..

**Comment by dushyants19** [comment]
Any progress? @D-Gee

**Comment by D-Gee** [comment]
I've had a play, but I don't use IF anymore so just reassign and remove me ✌

**Comment by dushyants19** [comment]
Okay, will do so. :)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27130577-8026099a-50cc-11e7-81d8-8e79608832ab.png)
