### ISSUE TITLE
RJFS-Saga Airport-SAGA-JAPAN

### ISSUE THREAD

**Issue by unitedfc** [InfiniteFlightAirportEditing/Airports#1731]
♻️

**Comment by brunocr98** [comment]
How is this airport going? any progress?

**Comment by dushyants19** [comment]
grabs

**Comment by dushyants19** [comment]
Recycled to RJFS

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/35482334-23cd7698-03f9-11e8-9453-b3a2b632e6d5.png)
