### ISSUE TITLE
SCAE

### ISSUE THREAD

**Issue by Yifan081** [InfiniteFlightAirportEditing/Airports#1737]
El Buitre Airfield. Arica, Chile. Redoing it

**Comment by brunocr98** [comment]
El nombre más raro que he visto LOL.

**Comment by Yifan081** [comment]
Sent for review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24071761/3e6f4b60-0ba8-11e7-82d4-127090296bdf.png)
