### ISSUE TITLE
UGMS-Queen Tamar Airport-SAMEGRELO ZEMO SVANETI-GEORGIA

### ISSUE THREAD

**Issue by ErshovlaD** [InfiniteFlightAirportEditing/Airports#1738]
Being done from scratch
Please, create folder in airport repo

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24071986/778b7d20-0bac-11e7-8510-f383cf908d94.png)
