### ISSUE TITLE
MMPR-Puerto Vallarta Airport-JALISCO-MEXICO

### ISSUE THREAD

**Issue by lalomarlin** [InfiniteFlightAirportEditing/Airports#1739]
Being Redone

**Comment by kilt46** [comment]
Airport NOT LOADED to library

**Comment by dushyants19** [comment]
I'll check

**Comment by dushyants19** [comment]
Never actually recvd MMPR, just the wrong issue closed.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25771432/62a87f3a-3216-11e7-835d-e56b0e79b444.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/60033755-8cdfc900-967f-11e9-9bc3-98f9669f871b.jpg)
