### ISSUE TITLE
KPMD

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#174]
SoCal

**Comment by Swang007** [comment]
Needs spawn points.

**Comment by Rotate-FDS** [comment]
Runway 07/25 should be 200 feet wide. I'll get on it ASAP.

**Comment by AxelBeder** [comment]
I have already redone it, I will push it asap. Should have updated it there sorry.

**Comment by AxelBeder** [comment]
Will send the last version when I get back from work.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/11551600/61fe9080-9940-11e5-86af-fae256ec4784.png)

**Comment by kilt46** [comment]
Combining taxiways together and cleaning up

**Comment by kilt46** [comment]
Airport redone

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20859831/eb4c962e-b92f-11e6-80b2-4c47995d446f.png)
