### ISSUE TITLE
UGSS-Sukhumi Babushara Airport-SUKHUMI-GEORGIA

### ISSUE THREAD

**Issue by ErshovlaD** [InfiniteFlightAirportEditing/Airports#1741]
Being done from scratch

**Comment by bavAVIA** [comment]
Don't create any more issues until others of yours are closed.
This is your fourth already.

**Comment by ErshovlaD** [comment]
Sometimes I have 6 issues and what a problem? 
I send some airports already. I'm active editor, so it's not necessary explain me rules. 

Thanks you.

**Comment by bavAVIA** [comment]
It's a rule.
Rules apply to everyone, this includes you. 

Just don't create further issues until other ones are closed.

**Comment by ErshovlaD** [comment]
OK. If you are talking about rules, then show me the place where this rule is documented.
I can be inconsiderate, but I did not find it.

And further. If I did everything I had to do, now should I wait? I'd rather start the next airport, than I'll sit back.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24273287/75aa170e-0fef-11e7-8a38-b93da4ef2449.png)
