### ISSUE TITLE
LIKO-Ozzano Airport-EMILIA-ROMAGNA-ITALY

### ISSUE THREAD

**Issue by johanneskkl** [InfiniteFlightAirportEditing/Airports#1742]
This is an airfield in italy. It wasnt in the list. Will create this airport.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
Missing Runway Holds (3 off)

**Comment by moritzbabl** [comment]
re-added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24578712/94b9b150-16ab-11e7-8e93-72c1fe7b20c7.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68151976-80b72280-ff21-11e9-95a5-7988217bcd69.jpg)
