### ISSUE TITLE
 UGKS-Airport of Senaki-SENAKI-GEORGIA

### ISSUE THREAD

**Issue by ErshovlaD** [InfiniteFlightAirportEditing/Airports#1743]
Being done from scratch 
Create please folder for this airport in repo :)

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24322296/cf0d4c86-112e-11e7-8a3f-fd7a262ae6cd.png)

**Comment by kilt46** [comment]
Airport is disused. Spawn points removed!

**Comment by IceBlue02** [comment]
@kilt46 doesn't this mean it will have runway spawns?
