### ISSUE TITLE
SCAR

### ISSUE THREAD

**Issue by Yifan081** [InfiniteFlightAirportEditing/Airports#1745]
Chacalluta International Airport. Arica, Chile. Redoing it.

**Comment by Yifan081** [comment]
Sent for review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24071612/85af29cc-0ba4-11e7-96ad-72a193d61314.png)
