### ISSUE TITLE
SKMZ

### ISSUE THREAD

**Issue by Yifan081** [InfiniteFlightAirportEditing/Airports#1746]
La Nubia Airport. Manizales, Colombia. Redid it.

**Comment by Yifan081** [comment]
Sent for review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24066283/03af33f0-0b3f-11e7-953e-921fbded1990.png)
