### ISSUE TITLE
KAPF-Naples Municipal Airport-FLORIDA-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#175]
Florida

**Comment by HenrikBerg02** [comment]
I'll redo this airport.

**Comment by kilt46** [comment]
SPAWN ON RNWY

**Comment by Swang007** [comment]
I was going to delete the spawn points on the runway, but the airport looks fairly primitive. 
![kapf screenshot](https://cloud.githubusercontent.com/assets/11000109/11861801/4a824096-a449-11e5-899f-61a6eecc5023.png)

I don't remember if it looked better than this before or not, I just reorganized the airport boundary and renamed the runway on November 15, nothing special.

![kapf history](https://cloud.githubusercontent.com/assets/11000109/11861809/61020afe-a449-11e5-804b-3bd2023bd57f.png)

Whoever committed or didn't commit after November 15, your edits did not show up in the repository. I don't see any spawn points on the runway

**Comment by Swang007** [comment]
Oh, I just realized. Automatic runway spawn points show up when a spawn point does not exist on the airport. I guess someone can go through and try to find gate names? No need to re-download the repository if your local version is newer than November 15, I haven't committed anything :)

**Comment by HenrikBerg02** [comment]
![screen shot 2015-12-16 at 11 07 34 pm](https://cloud.githubusercontent.com/assets/14116830/11861853/eea779fc-a449-11e5-8b58-c3d9e959b615.png)

This is what I have. It seems it was updated when I sent it into to Jonathan. I'll do it now.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21079928/d13b2fb0-bf66-11e6-8056-bd33045db4e5.png)

**Comment by brennanhackard** [comment]
Airport needs a full redo. Open to anyone who wants it.

**Comment by brennanhackard** [comment]
@feitidede will be working on this airport

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112736553-9287d400-8f21-11eb-8165-2bbf421e7b69.png)
