### ISSUE TITLE
YLHI

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#1754]
Lord Howe Airport. I'm taking this one. 
Runway not longer than 10k feet.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24322622/2da358d8-1136-11e7-9203-b8c0f2776a16.png)
