### ISSUE TITLE
YMHB

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#1757]
Hobart Airport. I will be re-doing this one.
Runway not longer than 10k feet.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24273109/8895e308-0fee-11e7-8166-8057aace07fd.png)

**Comment by MBeringuy** [comment]
Buildings removed

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102725632-d4c7c680-42dd-11eb-9317-4db5cbc0a1d7.png)
