### ISSUE TITLE
OAMN-Maimana Airport-FARYAB-AFGHANISTAN

### ISSUE THREAD

**Issue by KyanBasil** [InfiniteFlightAirportEditing/Airports#1758]
I would like this to be added. I will try to make it myself too.

**Comment by brunocr98** [comment]
Wait, are you in our team? If not, please send an email to airports@flightliveapp.com to get started.

**Comment by grizpac** [comment]
I will take this one for my first.

**Comment by johanneskkl** [comment]
*(5 months later)*
any progress?

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by baseballinferno** [comment]
I would like to edit this

**Comment by brunocr98** [comment]
Unfortunately I’m unable to assign you because you don’t appear on the list of collaborators. You must’ve had accepted an invitation mailed to your email address upon acceptance to this team.

**Comment by baseballinferno** [comment]
How do I join the list of collaborators

**Comment by baseballinferno** [comment]
And I did accept upon entrance to the team from my email

**Comment by baseballinferno** [comment]
I am ready

**Comment by baseballinferno** [comment]
I want to choose a different airport, an easier one

**Comment by MajorTomMueller** [comment]
![recycle](https://user-images.githubusercontent.com/26853210/54352311-abcaca00-4651-11e9-9f2f-ae623c504fe3.png)

**Comment by MajorTomMueller** [comment]
![OAMN](https://user-images.githubusercontent.com/26853210/54354045-ee8ea100-4655-11e9-9fc6-8cd3b48c0dbb.jpg)
