### ISSUE TITLE
KBCT-Boca Raton Airport-FLORIDA-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#176]
Florida

**Comment by JohnPreston21** [comment]
Will being this one

**Comment by JohnPreston21** [comment]
My Apologies Cameron, I've started work on this one. Correcting taxiways, adding taxi lines and parking

**Comment by JohnPreston21** [comment]
Re did this one.. Taxi ways were all wrong. Re designed taxi ways, added taxi lines with props, jet and ramp spawn parking. Jonathon added this one to the library.

**Comment by Omari4u** [comment]
John,did you remember to remove spawning on the runway?

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21207469/e09329da-c22d-11e6-9f95-b6aee3dec46c.png)

**Comment by kilt46** [comment]
Airport needs reworked

**Comment by brunocr98** [comment]
Aeropuerto renovado.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23330853/2dfe9982-fb1f-11e6-85e9-e581bf007527.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52540139-d2909a80-2d4b-11e9-8fcd-31c7ca0430ec.png)

**Comment by kilt46** [comment]
REMOVE DUPLICATE   SPAWNS | BUILDINGS REMOVED
-- | --
