### ISSUE TITLE
UGSP-Poti East Airport-SAMEGRELO-ZEMO SVANETI-GEORGIA

### ISSUE THREAD

**Issue by ErshovlaD** [InfiniteFlightAirportEditing/Airports#1761]
Beind done from scratch.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24273504/c04388ee-0ff0-11e7-8ca7-7d7946d4b11d.png)
