### ISSUE TITLE
UGGN-Signakhi Airport-TSNORI-GEORGIA

### ISSUE THREAD

**Issue by ErshovlaD** [InfiniteFlightAirportEditing/Airports#1762]
Being done from scratch. Last 3 my airports already done. May be today Moritz will check it. :)

So, assign me please :)

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24322394/7bc601e6-1131-11e7-95a7-34c3941151a2.png)
