### ISSUE TITLE
ZBOW

### ISSUE THREAD

**Issue by CNwyang** [InfiniteFlightAirportEditing/Airports#1763]
Baotou, NeiMongol, china，will redo it.

**Comment by CNwyang** [comment]
Done from scratch,sent for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24322495/567ef85a-1133-11e7-9430-f110bfa9c9b5.png)
