### ISSUE TITLE
NFFN-Nadi Airport-WESTERN-FIJI

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1764]
Doing this airport. Nadi International Airport.

**Comment by brunocr98** [comment]
Hecho.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24322002/49f77efe-1129-11e7-8ddb-b628cf8a0c4e.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68903360-aa3e2e00-0719-11ea-9b36-de0e3f22480a.jpg)
