### ISSUE TITLE
ZBLA

### ISSUE THREAD

**Issue by CNwyang** [InfiniteFlightAirportEditing/Airports#1769]
Hailaer/Dongshan, Neimongol, China. Being redone.

**Comment by CNwyang** [comment]
Sent for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24322589/3ef8360e-1135-11e7-8db0-82ad5d48ff1f.png)
