### ISSUE TITLE
KFMY

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#177]
Florida

**Comment by kilt46** [comment]
HAS HOLD SHORT AREAS,

**Comment by Swang007** [comment]
Hold-short spawn points removed,
Manual blast pad's replaced with runway blast pad's, manual lines removed, manual displaced threshold lines removed,
Removed weird ATC routes that weren't letting me save the file.

**Comment by TristinWoolf** [comment]
Found parking lots that need to be removed. 
![image](https://cloud.githubusercontent.com/assets/18745517/18020473/13967874-6ba7-11e6-9c87-61d7f33e121d.png)
![image](https://cloud.githubusercontent.com/assets/18745517/18020474/139893ca-6ba7-11e6-9617-ccdacd9f7cf5.png)
![image](https://cloud.githubusercontent.com/assets/18745517/18020475/1399a364-6ba7-11e6-8133-1b596a893476.png)

**Comment by dushyants19** [comment]
Does it matter? Are we now removing parking lots?

**Comment by dushyants19** [comment]
To do for this airport

- [ ] Snap Nodes - F HANGERS and A-S
- [ ] Cut holes for buildings

**Comment by dushyants19** [comment]
8c44982

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18251122/d8391072-734c-11e6-9178-ecf9577c788f.png)
