### ISSUE TITLE
RJNS 

### ISSUE THREAD

**Issue by Yifan081** [InfiniteFlightAirportEditing/Airports#1770]
Shizuoka airport, Japan. Will redo it.

**Comment by Yifan081** [comment]
Sent for review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24579125/d1dbcd76-16b4-11e7-81a3-39c6d12f58fc.png)
