### ISSUE TITLE
ZBMZ

### ISSUE THREAD

**Issue by CNwyang** [InfiniteFlightAirportEditing/Airports#1771]
Manzhouli, Neimongol, China. Being redone.

**Comment by CNwyang** [comment]
Sent for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24228002/58c06ed2-0f3f-11e7-847e-dab1e3fb3fbf.png)
