### ISSUE TITLE
ZYTL-Dalian/Zhoushuizi Airport-LIAONING-CHINA

### ISSUE THREAD

**Issue by CNwyang** [InfiniteFlightAirportEditing/Airports#1773]
Dalian/Zhoushuizi, Liaoning,China. Being redone.

**Comment by dushyants19** [comment]
Any progress? @CNwyang

**Comment by dushyants19** [comment]
Up for Grabs; Let us know if you want to do the airport.

**Comment by CNwyang** [comment]
@dushyants19 sorry for delaying,im doing it now

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
Please use the following spawn points
![image](https://user-images.githubusercontent.com/14023167/27792844-3196c20c-5fc1-11e7-9fa1-4d6647ae93c2.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27792852-3eeba79c-5fc1-11e7-9fd3-d9f5156826cf.png)

**Comment by moritzbabl** [comment]
Added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28247044-923862aa-69ee-11e7-9438-b21b461b4a41.png)
