### ISSUE TITLE
KCRP-Corpus Christi International Airport-TEXAS-USA

### ISSUE THREAD

**Issue by RyanEpps** [InfiniteFlightAirportEditing/Airports#1774]
PLEASE EDIT ME

**Comment by brunocr98** [comment]
This is the 2nd you create an issue for the same airport! And you're assigned to it already! 

#577

**Comment by brunocr98** [comment]
Recycled. Up for grabs!

**Comment by johanneskkl** [comment]
maybe gonna do this

**Comment by dushyants19** [comment]
maybe later, finish all your airports

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28291507-5b2644ee-6b10-11e7-9fa4-2877aaf21d92.png)
