### ISSUE TITLE
D60-Tioga Municipal Airport-NORTH DAKOTA-USA

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Airports#1775]
♻️

**Comment by CptNathanHope** [comment]
Submitted for review.

**Comment by kilt46** [comment]
This is a duplicate airport (See #413)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34535915-29bff540-f089-11e7-95c0-6e4b6afb0906.png)
