### ISSUE TITLE
WIOO-Pontianak Supadio Airport-KALIMANTAN BARAT-INDONESIA

### ISSUE THREAD

**Issue by haociek** [InfiniteFlightAirportEditing/Airports#1776]
Supiado International Airport, Pontianak, Indonesia

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25254754/d8ef03fc-25ec-11e7-9363-8afc1de9ce1c.png)

**Comment by MajorTomMueller** [comment]
This Airport need
• Add new Taxiway to enter runway
• Change little bit parking position
• And anything need to change


And remove buildings...

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103048756-3e9dd580-4555-11eb-9c5c-db4e68d1f3d0.png)
