### ISSUE TITLE
YMLT

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#1777]
Launceston Airport, Tasmania. I will be re-doing this one.

Runway is not longer than 10k feet.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24578603/f47d0ea0-16a8-11e7-8e1b-b6ff44c0d418.png)
