### ISSUE TITLE
LMML-Luqa Airport-MALTA-MALTA

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1778]
Malta International Airport.

**Comment by brunocr98** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24478835/17a9c7aa-14a2-11e7-8057-685ad1fbd985.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/70917282-ccb6b600-1ffb-11ea-8809-5df27d0fe525.jpg)
