### ISSUE TITLE
KFPR-Treasure Coast International-FLORIDA-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#178]
Florida

**Comment by HenrikBerg02** [comment]
Redoing it.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18617317/782b023a-7d92-11e6-9fe0-3dc78a886d81.png)

**Comment by brennanhackard** [comment]
Airport needs a rework. Open to anyone who wants it.
