### ISSUE TITLE
HTDA-Julius Nyerere International Airport-DAR-ES-SALAAM-TANZANIA

### ISSUE THREAD

**Issue by KaranMshah** [InfiniteFlightAirportEditing/Airports#1782]
Redoing this airport

**Comment by dushyants19** [comment]
Any progress? @KaranMshah

**Comment by dushyants19** [comment]
Up for Grabs; Let us know if you want to do the airport.

**Comment by Aviationluver** [comment]
I'll take this one.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by moritzbabl** [comment]
Added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28239009-8e0033d4-6926-11e7-9ce5-cd71df0277b9.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/69554677-e3c83200-0f80-11ea-93ab-d23d08cbe77b.jpg)
