### ISSUE TITLE
EGNJ-Humberside Airport-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by liamkirky** [InfiniteFlightAirportEditing/Airports#1783]
Editing this airport now

**Comment by bavAVIA** [comment]
Previous editor decided to leave the team. Up for grabs.

**Comment by huddys7** [comment]
I can start with some help!

**Comment by huddys7** [comment]
How do I assign myself?

**Comment by benlenahan** [comment]
You cannot. Wait, and an admin will get to you in no time :)

**Comment by huddys7** [comment]
Ok! Thanks

**Comment by brunocr98** [comment]
@huddys7 please send an email to airports@liveflightapp.com to join us :)

**Comment by huddys7** [comment]
Sent it. Now what?

**Comment by CptNathanHope** [comment]
@huddys7 Please wait until an airport editing staff sends an email back. They will provide instructions on how to get set up as well as join the slack group :)

**Comment by huddys7** [comment]
Ok! Thanks.

**Comment by ItsW1ll** [comment]
Has the airport been started?

**Comment by huddys7** [comment]
No. You can start. I had a conflict come up so I cannot get to it right now. Go ahead!

**Comment by ItsW1ll** [comment]
Okay, i will start it!
Its almost done.. please don't unassign me!

**Comment by ItsW1ll** [comment]
another suggestion done! 65 suggestions to go!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34502547-89bb3672-efd9-11e7-9af1-5f897efef6c5.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/99734102-e53f1400-2a87-11eb-8f8d-8041814034bb.png)
