### ISSUE TITLE
KFFO-Wright Patterson Air Force Base-OHIO-USA

### ISSUE THREAD

**Issue by netjets-1951** [InfiniteFlightAirportEditing/Airports#1786]
Being Redone.
https://github.com/InfiniteFlightAirportEditing/Airports/tree/master/United%20States/K---/KF--/KFFO

**Comment by kilt46** [comment]
Missing many spawn points in airfield ops!
![image](https://cloud.githubusercontent.com/assets/14023167/24636126/a01c1008-189d-11e7-862d-82289d99fe5a.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24828249/ae4a5d9a-1c1e-11e7-9846-29872f2ba56f.png)
