### ISSUE TITLE
KLCK-Rickenbacker International Airport-OHIO-USA

### ISSUE THREAD

**Issue by netjets-1951** [InfiniteFlightAirportEditing/Airports#1787]
Being Redone https://github.com/InfiniteFlightAirportEditing/Airports/tree/master/United%20States/K---/KL--/KLCK

**Comment by netjets-1951** [comment]
+10,000 FT

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25514193/acfecc1e-2ba0-11e7-992d-9ea3bc2d5c70.png)

**Comment by dushyants19** [comment]
Cargo Spawns added

**Comment by RyanEpps** [comment]
Spawns adjusted.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45191185-7e671480-b207-11e8-8ddb-80deb4df6bd8.png)
