### ISSUE TITLE
WBKK-Kota Kinabalu Airport-SABAH-MALAYSIA

### ISSUE THREAD

**Issue by Yifan081** [InfiniteFlightAirportEditing/Airports#1788]
Kota Kinabalu International Airport. Sabah, Malaysia. Redoing it. _Runway length 12402 ft_

**Comment by Yifan081** [comment]
Sent for review

**Comment by kilt46** [comment]
Suggested gates.
![image](https://cloud.githubusercontent.com/assets/14023167/24731887/aeee2f3a-1a32-11e7-8909-2e9d18c5eee2.png)

**Comment by Yifan081** [comment]
Terminal 2 layout was drawn based on documentation published by The Malaysian Department of Civil Aviation (Dated 02 MAR 2017). Please go over the following link: http://aip.dca.gov.my/aip/eAIP/2017-03-02/graphics/78264.pdf

**Comment by dushyants19** [comment]
@Yifan081 so you were correct?

**Comment by Yifan081** [comment]
I strongly believe so

**Comment by brunocr98** [comment]
I suggest you to follow the charts above, otherwise the airport won't be accepted.

**Comment by Yifan081** [comment]
@brunocr98  Aren't we aiming for realism here? Don't want to think that further research is indeed penalized.

**Comment by dushyants19** [comment]
@Yifan081 if you believe so, i'll close it

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25043299/7af83334-20e4-11e7-9c95-ffe39cc539ce.png)

**Comment by MBeringuy** [comment]
Removed terminal and other improvements

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/92186521-a56b7780-ee1c-11ea-8e2c-7a3adf093b5b.png)
