### ISSUE TITLE
CYQX

### ISSUE THREAD

**Issue by Yifan081** [InfiniteFlightAirportEditing/Airports#1789]
Gander International Airport. Newfoundland and Labrador, Canada. Will redo it.

**Comment by brunocr98** [comment]
Nice choice! :)

**Comment by Yifan081** [comment]
Sent for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25047312/a08075aa-20fb-11e7-8982-0bdd25b108c1.png)
