### ISSUE TITLE
KFXE-Fort Lauderdale Executive Airport-FLORIDA-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#179]
Florida

**Comment by kilt46** [comment]
Started

**Comment by kilt46** [comment]
Airport redone: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=KFXE

**Comment by samuelandersson** [comment]
Removed white lines from a lot (!) of buildings.

**Comment by PaulNielsen** [comment]
Fixed 2 taxiways connecting to runway 08.

**Comment by dushyants19** [comment]
Did you move spawns according to new type, @PaulNielsen ?

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19500979/7de856e0-9567-11e6-9493-956303120fda.png)

**Comment by RyanEpps** [comment]
Airport needs reworked up to new standards and additional spawns.

**Comment by danisrils39** [comment]
I'm willing to do this one.

**Comment by danisrils39** [comment]
Almost done with it, just need to add the other half of the hangars and spawns, and then it should be good! Sorry for the delay.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53682991-3b22c580-3cc1-11e9-85b0-e7d2c1462c0c.png)
