### ISSUE TITLE
LICR-Reggio Calabria Airport-CALABRIA-ITALY

### ISSUE THREAD

**Issue by johanneskkl** [InfiniteFlightAirportEditing/Airports#1791]
Reggio Calabria airport. Part of project italy

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by johanneskkl** [comment]
Why?

**Comment by johanneskkl** [comment]
sent for review

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25108474/a2058dfa-239b-11e7-99c3-bae3c21c7f86.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/67638096-e3744280-f8bf-11e9-83c3-6729fbab6b39.jpg)
