### ISSUE TITLE
LIPQ-Trieste/Ronchi Dei Legionari Airport-FRIULI-VENEZIA GIULIA-ITALY

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#1792]
Trieste - Friuli Venezia Giulia Int’l Airport, being redone.

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24887626/b5c297c6-1e22-11e7-8a46-3514beff5fca.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68996065-d1107780-0873-11ea-946f-7bdc5e2e307e.jpg)
