### ISSUE TITLE
LEVX

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#1793]
Vigo Airport, Galicia, Spain.
Being redone.

**Comment by bavAVIA** [comment]
@lolo31r is taking over. this was discussed.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27249508-ecf94034-52dc-11e7-9a7c-9d3cc12d54f4.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/110395035-0e81b100-8033-11eb-8af9-ef14b38b1b57.png)
