### ISSUE TITLE
LEPP

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#1794]
Pamplona Regional Airport, Spain. 
Being redone.

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24828183/827aec08-1c1d-11e7-8d31-e68b35b35ab7.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109576721-f43b5680-7ab9-11eb-8556-678f0d8057aa.png)
