### ISSUE TITLE
EGNR-Hawarden Airport-WALES-UNITED KINGDOM 

### ISSUE THREAD

**Issue by Will171** [InfiniteFlightAirportEditing/Airports#1797]
Full Redo
Please assign me

![screenshot_92](https://cloud.githubusercontent.com/assets/16463484/24427824/3cf619b2-1404-11e7-9c2d-3bc35989a80c.png)

**Comment by brunocr98** [comment]
Located in Wales.


https://en.m.wikipedia.org/wiki/Hawarden_Airport

**Comment by Will171** [comment]
thanks for confirming that bruno

**Comment by Will171** [comment]
Sent for review.. I put the wrong ICAO in the email..

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24935142/a4135722-1ee5-11e7-92c1-ff58323386f8.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45930996-dfdbf280-bf2c-11e8-9975-20e73019c881.png)
