### ISSUE TITLE
EGLC-London City Airport-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#18]

**Comment by jpperks** [comment]
Replaced "Broken" (Solid in IF) road center markings.

**Comment by jpperks** [comment]
Fixed Typing Error

**Comment by AxelBeder** [comment]
Fixed the runway threshold issue.

**Comment by Swang007** [comment]
Will add ATIS frequency

**Comment by Swang007** [comment]
Deleted second tower frequency

**Comment by Swang007** [comment]
Changed GS angle in the earth_nav.dat file

**Comment by Swang007** [comment]
Fixed blast pad bug

**Comment by HenrikBerg02** [comment]
Hashed marking need to be removed on this one.

**Comment by HenrikBerg02** [comment]
Have you removed them, @dushyants19?

**Comment by kilt46** [comment]
Renaming and cleaning

**Comment by kilt46** [comment]
Hatched lines removed. Gates relabelled

**Comment by dushyants19** [comment]
Boundary Fixed, was taking too much area from the Docks

**Comment by Will171** [comment]
Will add some missing features such as taxiway signs and hold positions

**Comment by Will171** [comment]
+ Adding new extended parts of taxiway W as can be seen on Google Earth.
+ Redoing parking stand lines as they have been changed as seen on Google Earth.
+ Overall fixes and improvements round the whole airport

**Comment by Will171** [comment]
All improvements completed, and emailed

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17264578/8d51852e-55ad-11e6-8cdc-371cdfa931b7.png)

**Comment by dushyants19** [comment]
Minor improvements by @Will171

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18224695/42e13ada-71a4-11e6-83d4-787fef47a1df.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18224697/4bd12786-71a4-11e6-849e-c5dcdedc8e0c.png)

**Comment by dushyants19** [comment]
@ItsW1ll will be doing some changes.

**Comment by ItsW1ll** [comment]
Basically, new imagery reveals that the runway has been covered with asphalt, there is also a new taxiway and changes to the turn around area. 

Please see google earth/charts for more info

**Comment by ItsW1ll** [comment]
Sent for review

**Comment by brennanhackard** [comment]
- imagery is now available for new gates. 

@liamkirky will be editing this airport.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103045897-ee6e4580-454b-11eb-9a69-df4b5b8eb9a5.png)

**Comment by AleksanderIF** [comment]
![EGLC](https://user-images.githubusercontent.com/53284798/124932419-bc19c680-e00b-11eb-8954-84c26ec69968.png)
