### ISSUE TITLE
KHST

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#180]
Florida

**Comment by Omari4u** [comment]
would like to work on this one

**Comment by Omari4u** [comment]
working on this one...adding taxiways & spawning point and parking

**Comment by kilt46** [comment]
Image: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=KHST

**Comment by kilt46** [comment]
SPAWN ON RNWY

**Comment by NickArt1342** [comment]
is somebody still doing this one? They should remove the ray spawn points asap then

**Comment by Swang007** [comment]
Um, @NickArt1342 is this the KHSt you're talking about? Looks pretty empty to me

![khst screenshot](https://cloud.githubusercontent.com/assets/11000109/11861643/de24244c-a447-11e5-8a57-994f704acdb7.png)

**Comment by Swang007** [comment]
Automatic runway spawn points show up when a spawn point does not exist on the airport. This airport is up for grabs!

**Comment by NickArt1342** [comment]
Yeah exactly, that's why spawn points should be added!

**Comment by samuelandersson** [comment]
Completely redoing with curved taxiways and spawn points.

**Comment by HenrikBerg02** [comment]
This needs a major redo. No spawn points, no snapped taxiways, and poor overall design. @samuelandersson, are you still working on this or did you abandon it?

**Comment by samuelandersson** [comment]
I have abandoned it. Something happened to my hard drive which pretty much removed most of my files and documents from the computer. Then I forgot to remove my assignment here. Sorry.

**Comment by dushyants19** [comment]
I'm on this.

**Comment by samuelandersson** [comment]
How is this going @dushyants19?

**Comment by kilt46** [comment]
Completed this!

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20158264/f33e4600-a69e-11e6-9f51-4107db0197e7.png)
