### ISSUE TITLE
ULAA-Arkhangel'sk Airport (Talagi)-ARKHANGEL'SK-RUSSIA

### ISSUE THREAD

**Issue by ErshovlaD** [InfiniteFlightAirportEditing/Airports#1801]
Being redone

**Comment by dushyants19** [comment]
Cannot assign you, maximum 3 airports per person. Complete your other airports.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24982770/ce95d826-1fa8-11e7-831e-46ccdf6a27ef.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44003123-7f0febd0-9e13-11e8-88af-789d98e17dd8.png)
