### ISSUE TITLE
FMMI-Ivato Airport-ANTANANARIVO-MADAGASCAR

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#1802]
Aeropuerto Internacional Ivato. Madagascar.

**Comment by brunocr98** [comment]
Done

**Comment by kilt46** [comment]
Not loaded to library

**Comment by brunocr98** [comment]
Uhm, I'm quite sure I committed the file.

**Comment by brunocr98** [comment]
I'll commit it again...strange it's not in the database.

**Comment by brunocr98** [comment]
Should be now in the database.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24833001/c9c3a0b8-1c82-11e7-8b23-271a6730afa3.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/69904701-71908c80-1388-11ea-970f-a2b15c77982b.jpg)
