### ISSUE TITLE
VRMG-Gan Island Airport-GAN ISLAND-MALDIVES

### ISSUE THREAD

**Issue by KarlLuebs** [InfiniteFlightAirportEditing/Airports#1803]
Doing this one. International airport in the Maldives.

**Comment by dushyants19** [comment]
Can't assign you. Max 3 issues per person.

**Comment by KarlLuebs** [comment]
oh no, sorry about that. Completely forgot about EDHK.

**Comment by dushyants19** [comment]
Assigned to you @KarlLuebs

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27910434-c5d92026-621a-11e7-854b-623c7256afa2.png)

**Comment by kilt46** [comment]
RUNWAY TOO LONG
![image](https://user-images.githubusercontent.com/14023167/27910572-537e1972-621b-11e7-868a-be4525a2c834.png)

**Comment by KarlLuebs** [comment]
@kilt46 thats a mistake. Your charts must be old. 
![screen shot 2017-07-06 at 16 46 39](https://user-images.githubusercontent.com/20403487/27916920-c6d8c576-626a-11e7-8206-502e3cc1d0f8.png)

**Comment by KarlLuebs** [comment]
Around 500m were added to the runway on the west side of it.

**Comment by KarlLuebs** [comment]
wait, ill take that back. Got the stopways wrong. But the runway length is right isn't it?

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29697188-37485992-8913-11e7-8c1a-b3469d51d0c8.png)
