### ISSUE TITLE
VDPP-Phnom Penh International Airport-PHNOM PENH-CAMBODIA

### ISSUE THREAD

**Issue by Yifan081** [InfiniteFlightAirportEditing/Airports#1804]
Phnom Penh International Airport, Cambodia.  Redoing it.

**Comment by dushyants19** [comment]
Any progress? @Yifan081

**Comment by Yifan081** [comment]
Will send it by the weekend

**Comment by Yifan081** [comment]
Sent for review

**Comment by moritzbabl** [comment]
Added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28253456-cacfd230-6a69-11e7-8fa3-749111e3833f.png)

**Comment by kztmtn** [comment]
@IFClaris Good luck!

**Comment by IFClaris** [comment]
Thanks ! @kztmtn

**Comment by IFClaris** [comment]
Phnom Penh International Airport will be remade from scratch.

**Comment by GBKarp** [comment]
I'll take this.

**Comment by Czechoslovaki** [comment]
The distortion is strong with this one. Happy editing.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105578301-b45bb380-5d44-11eb-8ae4-50327536e6d5.png)
