### ISSUE TITLE
KAZO-Kalamazoo/Battle Creek Airport-MICHIGAN-USA

### ISSUE THREAD

**Issue by ryu12332** [InfiniteFlightAirportEditing/Airports#1805]
Part of Project Michigan

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24935339/0eb6bf14-1ee7-11e7-9b42-b4dfde758287.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52534407-c0d8d400-2d06-11e9-8a8b-8e7251883a27.png)

**Comment by kilt46** [comment]
REMOVE DUPLICATE   SPAWNS BUILDINGS REMOVED
