### ISSUE TITLE
CYYJ-Victoria International Airport-BRITISH COLUMBIA-CANADA

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#1806]
Victoria Int'l Airport. I'll do this one.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25515861/c679cc50-2bac-11e7-80e7-6678be968649.png)

**Comment by DelsterX** [comment]
Updating to add new overnight parking apron and overall cleanup of the airport.

**Comment by DelsterX** [comment]
Submitted for review...
- Main terminal Apron expansion and overnight parking updated
- New gate markings updated and new roadway markings
- Fixed centre lines and updated to correct to IRL situation
- fixed numerous buildings and added more that should be shown
- Added taxi lights and centre lights as per real life
- Added more GA spawns and missing windsocks
- New vehicle security screening added
- redid a few taxiways
- fixed incorrect boundary lines
- fixed unsnapped start-ups and holdlines

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31155046-001f04e8-a871-11e7-8915-ef546a9ead88.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31155198-eca975f0-a871-11e7-9c6f-0ff44269494d.png)

**Comment by DelsterX** [comment]
In progress. 

- Buildings removed
- terminal expansion added

**Comment by DelsterX** [comment]
In for Review...

- Removed buildings
- Updated apron lines around terminal as IRL
- Terminal Expansion Updated
- Concrete apron added as IRL

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52164788-88107d80-26bc-11e9-8a60-53a3acf8831b.png)
