### ISSUE TITLE
WATE

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#1807]
Ende - H. Hasan Aroeboesman Airport, Indonesia.
Small one, quickly redoing.

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24828070/5cfe64e8-1c1b-11e7-8499-6bbad5c4f288.png)
