### ISSUE TITLE
OLBA-Rafic Hariri Beirut International Airport-MOUNT LEBANON-LEBANON

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#181]
OLBA for Cameron

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23096462/654526a0-f5e2-11e6-942d-c1f738e66d6d.png)

**Comment by Czechoslovaki** [comment]
Gap between the shoulder and runway 03/21, presumably that shoulder is probably not the right width either. Airport needs a rework to fine tune (add or modify) all present markings, taxiways and their respective pavements.

Open to anyone to take.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109884610-e6fda380-7c42-11eb-8a35-0f1ba011ff77.png)
