### ISSUE TITLE
KMBS-Mbs International Airport-MICHIGAN-USA

### ISSUE THREAD

**Issue by ryu12332** [InfiniteFlightAirportEditing/Airports#1812]
Part of Project Michigan

**Comment by kilt46** [comment]
Please rename gates as per chart
![image](https://cloud.githubusercontent.com/assets/14023167/25109509/b25d8f2a-23a2-11e7-9ef0-60efe2a72661.png)

**Comment by ryu12332** [comment]
That terminal isn't in my version as the scenery is too old.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25303946/b392262a-2722-11e7-8a97-ed2e643dacbf.png)
