### ISSUE TITLE
LEZL-Seville Airport-ANDALUCIA-SPAIN

### ISSUE THREAD

**Issue by ksmith237** [InfiniteFlightAirportEditing/Airports#1818]
PLEASE EDIT ME!!!! ♻️ 😭

**Comment by brunocr98** [comment]
Please **DON'T** create random issues if you're not in the team. Thanks

**Comment by brunocr98** [comment]
Don't even close them.

**Comment by brunocr98** [comment]
@bavAVIA interested in this one?

**Comment by bavAVIA** [comment]
Maybe at some point in the future

**Comment by rnorris03** [comment]
I'll take this

**Comment by bavAVIA** [comment]
We can't assign you if you are not a part of the team. Did you shoot us an e-mail already?

**Comment by rnorris03** [comment]
I did send you guys an email and have already submitted 2 airports :)

**Comment by brunocr98** [comment]
When you get to Slack, you'll have to PM an admin your GitHub username so they can invite you to our repository.

**Comment by rnorris03** [comment]
I thought you needed to just sent the file to the email

**Comment by brunocr98** [comment]
Yes, but what I meant is that you have to PM an admin in Slack, not to his e-mail address.

**Comment by rnorris03** [comment]
So I PM him so he will "approve" me ?

**Comment by rnorris03** [comment]
Or give him the apt.dat

**Comment by brunocr98** [comment]
You PM the admin, he will send you an invite for github via your e-mail address. You send the apt.dat file to the email you used to request to join us.

**Comment by rnorris03** [comment]
ok sorry didn't understand

**Comment by Jackol2702** [comment]
Hi I'll do this one guys, I'll make it detailed over a few days

**Comment by rnorris03** [comment]
Yes please take it as I am not ready yet

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by alchonub** [comment]
I want this
All airports on review

**Comment by MajorTomMueller** [comment]
![lezl-git](https://user-images.githubusercontent.com/26853210/36794570-fb4c3798-1ca0-11e8-9d88-3d824c2e593c.jpeg)

**Comment by JcFl4** [comment]
I just wanted to say that this airport looks AMAZING. Thank you @MajorTomMueller for putting the time and effort because it really shows. :D

**Comment by MajorTomMueller** [comment]
boundary

**Comment by MajorTomMueller** [comment]
- Boundary Fix
- Buildings removed
- Hangar Floors added
- Markings added

**Comment by kilt46** [comment]
Naming of Gates are strange: Would suggest "Gate 1" or "Remote15" and omit the Apron names

![image](https://user-images.githubusercontent.com/14023167/46635468-2713d700-cb1a-11e8-8192-53c5cd1e7487.png)

**Comment by MajorTomMueller** [comment]
Naming is correct to chart. Distinction between different Aprons seems useful to me especially when the are named in official charts and have different strengths. 
Additionally it is in game for 7 months without complaints from the community. 
Can’t see why they are strange, why a change is needed. 
I will change them if a discussion in slack finds arguments for a mother naming.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46705069-8691e580-cbf3-11e8-9a3b-1a215a5d5016.png)

**Comment by kilt46** [comment]
Was discussed in slack. You can read the comments. Suggest simple Gate 01, Remote 15 etc. I can do for you if you like

**Comment by MajorTomMueller** [comment]
I will do to keep my data up to date. 
Even when I disagree with you that the comments cane tobthis result.

**Comment by MajorTomMueller** [comment]
Spawn names changed to fit Kilts interpretation of the Slack discussion.
