### ISSUE TITLE
DGAA-Kotoka Airport-GREATER ACCRA-GHANA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#1819]
RECYCLED, PLEASE EDIT ME!

**Comment by moritzbabl** [comment]
Congrats, you created a duplicate, boss 😂

**Comment by dushyants19** [comment]
Please search before posting forum mod and owner of this organization

**Comment by moritzbabl** [comment]
@brunocr98 do your job

**Comment by brunocr98** [comment]
Recycled....

**Comment by moritzbabl** [comment]
Wanna do this @carmichaelalonso ?

**Comment by carmichaelalonso** [comment]
lol

**Comment by brunocr98** [comment]
Cameron que te pasa?

**Comment by dushyants19** [comment]
i shall not allow that mortaz

**Comment by moritzbabl** [comment]
But I always wanted to reject an airport done by cam 😔

**Comment by Spinxzl** [comment]
Can I take?

**Comment by brunocr98** [comment]
Up for grabs.

**Comment by JcFl4** [comment]
So... I don't want to say that I will do this, but I'm interested. ;)

**Comment by JcFl4** [comment]
I'll leave it on "unassigned" but if no one has redone it when I finish my exams I will take care of it.

**Comment by Aviationluver** [comment]
I will take this one.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29001810-7d7f1d24-7a59-11e7-81eb-b489cb7205df.png)

**Comment by MajorTomMueller** [comment]
New Terminal and Apron, I will care if no one else does, Yandex has quality imagery.

**Comment by MajorTomMueller** [comment]
![C81543DD-F5CF-4E3D-BC66-88493ADB856D](https://user-images.githubusercontent.com/26853210/101274314-562b3f00-379d-11eb-8628-5075c3ed9340.jpeg)

**Comment by MajorTomMueller** [comment]
https://community.infiniteflight.com/t/accra-airport-update/509678

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103111010-d0691980-460d-11eb-850b-9b0704f457dc.png)
