### ISSUE TITLE
KPBI-Palm Beach International Airport-FLORIDA-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#182]
Florida

**Comment by JohnPreston21** [comment]
I'll be doing this one

**Comment by Swang007** [comment]
Added parking spots

**Comment by Omari4u** [comment]
Cam / Sean don't forget to remove runway spawning

**Comment by AxelBeder** [comment]
I reworked it from scratch :) no more runway spawning.

**Comment by Swang007** [comment]
Both terminal buildings were supposed to be in asphalt, but there is no hole in the surrounding concrete so the layering bug takes effect.

**Comment by kilt46** [comment]
Patched this up for release. Needs redo

**Comment by Swang007** [comment]
Whoever completely redid this one after I added spawn points, great job. I'm still keeping the **Minor Design Issue** label up though, the only flaw is that curved areas like taxi lines and taxiways were drawn with several vertices instead of curved lines. Up to anyone that wants to do it, doesn't require much skill, only time and patience.

**Comment by samuelandersson** [comment]
Removed jetways and white lines from buildings.

**Comment by kilt46** [comment]
Gates renamed. Cleanup of taxiways

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17279527/6d195cc0-573b-11e6-8d4e-3d5b9c35cfe9.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17642959/41b9b9c2-6121-11e6-9a33-0073bc395216.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17642961/4a51b684-6121-11e6-8b90-cd2cbd8522bb.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17642971/94df2268-6121-11e6-8fd6-22c92dc9f3fa.png)

**Comment by moritzbabl** [comment]
Three gates were renamed following a forum request, not sure if you have to regate it @kilt46

**Comment by brunocr98** [comment]
Unnecessary markings removed.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/74392017-97a0c700-4de4-11ea-9306-ba9e895d8e23.jpg)
