### ISSUE TITLE
LIEO-Olbia Costa Smeralda Airport-SARDEGNA-ITALY

### ISSUE THREAD

**Issue by johanneskkl** [InfiniteFlightAirportEditing/Airports#1823]
Olbia airport
Last airport of project Italy.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27504074-9312166e-5849-11e7-8805-8d0a8c47ebe9.png)

**Comment by brunocr98** [comment]
Got mixed up with LIEO, meant to close LIEE.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/70487518-66e69d80-1ad4-11ea-8414-8ad899a542bd.jpg)
