### ISSUE TITLE
KCHS-Charleston AFB/International Airport-SOUTH CAROLINA-USA

### ISSUE THREAD

**Issue by brasil428** [InfiniteFlightAirportEditing/Airports#1824]
Charleston AFB/ International. ill work on this one

**Comment by bavAVIA** [comment]
Please specify an ICAO Airport code when creating issues in the future. Thanks :+1:

**Comment by brunocr98** [comment]
Is there progress being done? I'd like to do it if you're currently unable.

**Comment by brasil428** [comment]
I have some of it done but got busy with work I can upload it maybe if you like?

**Comment by brunocr98** [comment]
Send me what you have on Slack and I'll see what I can do.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28490975-8fbb0178-6eac-11e7-9171-cd94b12a6abf.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/96940558-a1abb700-1495-11eb-8445-21f6c7659d12.png)

**Comment by MajorTomMueller** [comment]
@Czechoslovaki what was done?
