### ISSUE TITLE
TXKF-L.F. Wade International Airport-ST DAVID'S ISLAND-BERMUDA

### ISSUE THREAD

**Issue by netjets-1951** [InfiniteFlightAirportEditing/Airports#1825]
Being redone - airport can support the A380
https://github.com/InfiniteFlightAirportEditing/Airports/tree/master/Bermuda/TXKF

**Comment by bavAVIA** [comment]
Airport does not have regular A380, therefore no A380 priority.

**Comment by netjets-1951** [comment]
That's not what I was saying... I was just saying I could support the A380 even though it's runway is less than 10,000 feet.

**Comment by netjets-1951** [comment]
Sent in for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25771776/a84b1c0a-3220-11e7-9007-03a26e8b16ba.png)

**Comment by RyanEpps** [comment]
Needs new terminal

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/97496444-f1c3c700-1936-11eb-8753-5fec742b4aa4.png)
