### ISSUE TITLE
EGTK-Oxford Kidlington Airport-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by insertusernameh3r3** [InfiniteFlightAirportEditing/Airports#1826]
Grass runways aren't in use and coordinates are off, taxiway margins erroneous

**Comment by ItsW1ll** [comment]
I have looked at this airport my self. The imagery for this airport is terribly out dated.

**Comment by Spinxzl** [comment]
@ItsW1ll I'm using SAS imagery, it shows it how it looks IRL (I live close), is this accurate?

**Comment by ItsW1ll** [comment]
Yes that is fine. Please use the the WEDbing imagery as the base image.

**Comment by ItsW1ll** [comment]
![screenshot_11](https://cloud.githubusercontent.com/assets/16463484/25143141/3ef0e3e2-2461-11e7-8def-c8ad506761ff.png)
As you can see the bing imagery has the bigger apron.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26521017/f1d2ed42-42a3-11e7-9a19-3731bef013d1.png)

**Comment by kilt46** [comment]
Duplicate spawn fixed

**Comment by brunocr98** [comment]
@benjwri will be redoing this airport.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78691725-56520280-78cf-11ea-86af-1e0e47437291.jpg)
