### ISSUE TITLE
KCNY-Canyonlands Field Airport-UTAH-USA

### ISSUE THREAD

**Issue by benlenahan** [InfiniteFlightAirportEditing/Airports#1827]
Canyonlands Field, I will work on this one.

**Comment by brunocr98** [comment]
Are you in our team? Please send an email to airports@liveflightapp.com to get started. 

Thanks.

**Comment by benlenahan** [comment]
Yes, I am. I mistakingly made that issue when I was still waiting for a
response, but now I am officially on the team. Sorry for the long time I
took to reply.

**Comment by moritzbabl** [comment]
Added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28046173-6b910bde-65a7-11e7-8069-e7929cb5c4c3.png)

**Comment by kilt46** [comment]
MAIN GATE ADDED
![image](https://user-images.githubusercontent.com/14023167/41683451-3a8d387e-74a0-11e8-9407-fc9606b8a621.png)
