### ISSUE TITLE
KPIE-St Pete-Clearwater International Airport-FLORIDA-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#183]
Florida

**Comment by carmichaelalonso** [comment]
john did this, forgot

**Comment by JohnPreston21** [comment]
will begin rework on this one

**Comment by JohnPreston21** [comment]
Will try to get to this one soon.

**Comment by JohnPreston21** [comment]
@carmichaelalonso For some reason I can not reopen the .dat file in WED. error say illegal file can not be opened ( or something to that effect.

**Comment by carmichaelalonso** [comment]
Take a screenshot and send it to me :)

**Comment by JohnPreston21** [comment]
will do one sec

**Comment by JohnPreston21** [comment]
Sent in the Chat, Unable to load here.

**Comment by JohnPreston21** [comment]
Had to import from scenery gateway if that's ok before I save it

**Comment by JohnPreston21** [comment]
had to import from scenery gateway, starting on this one

**Comment by JohnPreston21** [comment]
Will begin redesign after KPIA

**Comment by JohnPreston21** [comment]
Forgot to add re add being redone. Just completed this one waiting for approval.

Re designed from scratch except the runways. re designed taxiways and added taxi lines with gates and hanger spawns. Drew everything fromWedbing.

**Comment by JohnPreston21** [comment]
This one has been approved and added to the library. 

Closing this now.

**Comment by JohnPreston21** [comment]
Corrected mis aligned taxi lines, fixed taxiways with snap to verticals and corrected spawn names.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17461581/ac4ca0b6-5c57-11e6-956b-da35f0487de1.png)
TERMINAL
![image](https://cloud.githubusercontent.com/assets/14023167/17461582/b8fec492-5c57-11e6-9cf2-f544013fbb12.png)
COAST GUARD and NORTH
![image](https://cloud.githubusercontent.com/assets/14023167/17461583/ca2c250c-5c57-11e6-8356-1eae07e0f92d.png)
EAST HANGARS
![image](https://cloud.githubusercontent.com/assets/14023167/17461589/d5f03f7c-5c57-11e6-94ff-ba05bceae668.png)

**Comment by brennanhackard** [comment]
Airport desperately needs a rework. Up for grabs.

**Comment by feitidede** [comment]
i will take this one

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116941550-82a49380-ac35-11eb-8db1-1da4d67166ba.png)
