### ISSUE TITLE
EGHF-Lee-On-Solent Airport-ENGLAND-UNITED KINGDOM 

### ISSUE THREAD

**Issue by ItsW1ll** [InfiniteFlightAirportEditing/Airports#1830]
Full redo required

**Comment by ItsW1ll** [comment]
![screenshot_13](https://cloud.githubusercontent.com/assets/16463484/25266356/c54279fc-2668-11e7-8ca4-6a2606e77af0.png)

**Comment by bavAVIA** [comment]
Are you doing it?

**Comment by IceBlue02** [comment]
Will you don't need a picture and really you shouldn't make issues this small unless you are going to do them.

**Comment by ItsW1ll** [comment]
yeah im doing it, forgot to put that sorry!

**Comment by ItsW1ll** [comment]
sent for review

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25876450/ff6714ca-34e2-11e7-935a-dcb8b587c6fd.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45266447-ada49e00-b420-11e8-966e-d0308fa629d2.png)
