### ISSUE TITLE
UTAA-Ashgabat International Airport-ASHGABAT-TURKMENISTAN

### ISSUE THREAD

**Issue by IceBlue02** [InfiniteFlightAirportEditing/Airports#1832]
Ashgabat International Airport; Turkmenistan.

Pri II and World Capital.

Redoing

**Comment by mbmhwue148** [comment]
I'll do it

**Comment by mbmhwue148** [comment]
I'll take it

**Comment by IceBlue02** [comment]
I do have a version with about 60-70% of the airport complete- I'll send it you

**Comment by mbmhwue148** [comment]
Got it, thank you very much, helps quite a lot :)

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/35482264-2b752284-03f8-11e8-9814-2bee72bdb1a4.png)
