### ISSUE TITLE
KCIU-Chippewa County International Airport-MICHIGAN-USA

### ISSUE THREAD

**Issue by rnorris03** [InfiniteFlightAirportEditing/Airports#1833]
I'll do this. Part of Project Michigan.

**Comment by brunocr98** [comment]
Please send an email to airports@liveflightapp.com to get started.

Thanks.

**Comment by rnorris03** [comment]
Hi I did to Dushyanth

**Comment by rnorris03** [comment]
I completed it earlier; how do I upload the repository?

**Comment by IceBlue02** [comment]
Send the file (include the ICAO in the subject) to airports@liveflightapp.com

**Comment by rnorris03** [comment]
Oh ok thanks!

**Comment by ryu12332** [comment]
Part of Project Michigan

**Comment by rnorris03** [comment]
done editing, sent it in.

**Comment by rnorris03** [comment]
Not doing this anymore, thanks

**Comment by brunocr98** [comment]
Up for grabs.

**Comment by rnorris03** [comment]
would be great if someone could do it

**Comment by moritzbabl** [comment]
Well, why don't you do it if you want it to be done? 🤔

**Comment by ryu12332** [comment]
I'll take it.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29435113-59821dd4-836b-11e7-8988-bb44307c8e3b.png)
