### ISSUE TITLE
KANJ-Sault St. Marie Municipal Airport-MICHIGAN-USA

### ISSUE THREAD

**Issue by rnorris03** [InfiniteFlightAirportEditing/Airports#1835]
I'll do this. Part of Project Michigan.

**Comment by rnorris03** [comment]
Done editing, sent it in

**Comment by ryu12332** [comment]
Part of Project Michigan

**Comment by rnorris03** [comment]
Does anyone know how to add vertices to a runway so I can snap the taxiway to it?

**Comment by Spinxzl** [comment]
Pretty sure you just make the taxiway overlap slightly

**Comment by rnorris03** [comment]
Ok thanks. But I am having trouble making the concrete (or whatever) show up after I complete the taxiway

**Comment by rnorris03** [comment]
It shows the border of the taxiway, but no concrete shows up

**Comment by Spinxzl** [comment]
Make sure in view you have pavement transparency Solid

**Comment by rnorris03** [comment]
where do I set that?

**Comment by rnorris03** [comment]
I don't see it in the list of options for the taxiway

**Comment by Spinxzl** [comment]
In view top left of the screen next to edit and file

**Comment by Spinxzl** [comment]
Also make sure it is a closed shape, not any open edges

**Comment by rnorris03** [comment]
Do you mean the Pavement type?

**Comment by rnorris03** [comment]
I know its closed I completed it by clicking the green circle

**Comment by rnorris03** [comment]
Oh... sorry I didn't see that you said "View".. Ill look there

**Comment by rnorris03** [comment]
Yes the transparency is solid

**Comment by rnorris03** [comment]
let me just redraw it

**Comment by rnorris03** [comment]
Still won't work

**Comment by Spinxzl** [comment]
You don't hit the green circle to close it you hit enter
Watch this: https://www.youtube.com/watch?v=DJhvvz_fI48

**Comment by rnorris03** [comment]
ok thanks

**Comment by rnorris03** [comment]
The video shows what I'm doing but it shows up...

Mine won't show up super annoying

**Comment by moritzbabl** [comment]
@rnorris03 please use our Slack Channel for questions, github is not a good chat room and it spams the tracking thread on slack

**Comment by moritzbabl** [comment]
Not to mention that you can load your airports to peer-review there and that github may send emails for every comment to people involved in an issue

**Comment by rnorris03** [comment]
Sent in for #peer-review on Slack

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29201693-3a19f8b2-7e26-11e7-841f-aa5d40dce07a.png)
