### ISSUE TITLE
EGNV-Durham Tees Valley Airport-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by declanmlmoody** [InfiniteFlightAirportEditing/Airports#1839]
I am adding to this airport, here is a list of things that need doing:

- Taxi lines

- Taxiway markings

- Correct surfaces

**Comment by liamkirky** [comment]
is this still being redone?

**Comment by liamkirky** [comment]
Can I take this then?

**Comment by brunocr98** [comment]
Reassigned to @liamkirky

**Comment by liamkirky** [comment]
Hi may I be unassigned from this airport as my laptop doesn't have any free space left so I can't save it anymore.

I am only able to do extremely small airports.

**Comment by ItsW1ll** [comment]
Try using a disk cleaner, cleans out the unwanted stuff and free up some space

**Comment by MajorTomMueller** [comment]
http://www.ead.eurocontrol.int/eadbasic/eais-12BF5DD4DD0AD6134EC30FA6CEBB85C4/3QDXTD5E6YWTY/EN/2017-12-07-AIRAC/html/eAIP/EG-AD-2.EGNV-en-GB.html#AD-2.EGNV

**Comment by ItsW1ll** [comment]
What ever you linked in there doesn't work

**Comment by MajorTomMueller** [comment]
@ItsW1ll the link is nearly two months old...
How about searching for the linked content yourself. It is not as complicated as it looks like, all you need to,find is still in the link. It is readable despite it is a link....

**Comment by ItsW1ll** [comment]
was it like the airport chart of something?

**Comment by MajorTomMueller** [comment]
Yes! You got it.
Another link, same information:
http://www.nats-uk.ead-it.com/public/index.php%3Foption=com_content&task=blogcategory&id=56&Itemid=105.html
And, yes this one will expire as well. All deep links totalisation topics will expire sooner or later. AIP documents are revised...

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36638237-19f2fac2-19b5-11e8-9ba6-708f6e302bb6.png)

**Comment by MBeringuy** [comment]
Renamed
