### ISSUE TITLE
KPMP-Pompano Beach Airpark Airport-FLORIDA-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#184]
Florida

**Comment by kilt46** [comment]
Working on this one

**Comment by kilt46** [comment]
Airport completely redone

**Comment by samuelandersson** [comment]
The apt.dat file of this airport seems to be broken, at least my computer won't open it. Getting an error. Was going to remove white lines from buildings.
![skarmavbild 2015-12-27 kl 11 50 00](https://cloud.githubusercontent.com/assets/15381853/12009947/1b94fc0c-ac90-11e5-8767-debc4a7e9d11.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21074944/b6e50cf8-becb-11e6-812c-eba77787cd68.png)

**Comment by RyanEpps** [comment]
Airport needs reworked up to new standards and additional spawns.

**Comment by chrisindfw** [comment]
I would like to take this one if available.

**Comment by RyanEpps** [comment]
Member inactive, up for grabs

**Comment by chrisindfw** [comment]
I can give this back. I was waiting on some of the construction of a new taxiway to be completed. If anyone wants the latest file let me know.

**Comment by liamkirky** [comment]
Could I take this airport please?

**Comment by liamkirky** [comment]
Actually, as Chris said google maps needs to update its imagery and then he can do it if he wants.

**Comment by HiFlyerBwi** [comment]
Chris gave me permission, I will take up this airport.

**Comment by jackyboy2578** [comment]
I'll take this please

**Comment by jackyboy2578** [comment]
Sent for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/96940340-18948000-1495-11eb-8711-efe050ab5661.png)
