### ISSUE TITLE
LOWK-Klagenfurt Airport-KARNTEN-AUSTRIA

### ISSUE THREAD

**Issue by insertusernameh3r3** [InfiniteFlightAirportEditing/Airports#1840]
RECYCLED. ♻️

**Comment by dushyants19** [comment]
Search before posting

**Comment by Adam167** [comment]
are you on the editing team? there is already an issue for this and the file in the repo is different from the one in IF

**Comment by bavAVIA** [comment]
Recycled. Up for grabs until I get round to it. I will certainly do this one, however if somebody wants to do it before - go ahead.

**Comment by dushyants19** [comment]
LOWKey

**Comment by IceBlue02** [comment]
Dush you're too sLOWW with these Austria airport jokes

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25996650/f221b26e-36dd-11e7-82ac-58e228c47570.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/71787403-0cb6fa80-2ff6-11ea-8690-a0298b09eba9.jpg)
