### ISSUE TITLE
EGXC-Coningsby Airport-ENGLAND-UNITED KINGDOM 

### ISSUE THREAD

**Issue by insertusernameh3r3** [InfiniteFlightAirportEditing/Airports#1842]
Can I take this?

**Comment by bavAVIA** [comment]
Well, you created an issue for it.

**Comment by Spinxzl** [comment]
Can I please be unassigned as my computer is broken so I may not be able to edit for the foreseeable future

**Comment by brunocr98** [comment]
Up for grabs.

**Comment by Spinxzl** [comment]
Computer fixed and checked - I can take this again. Thanks

**Comment by brunocr98** [comment]
Up for grabs

**Comment by brunocr98** [comment]
By the way...again.

**Comment by American232** [comment]
Still working on this one ;)

**Comment by ChrisLevet232** [comment]
- [ ] Finishing ramp starts and markings.

**Comment by ChrisLevet232** [comment]
Sorry all. Haven't been real productive lately but I'm actively working on this one at the moment.

**Comment by ChrisLevet232** [comment]
Up for grabs. I have somethings worked on and will provide the apt.dat for whomever wants to finish this.

**Comment by MajorTomMueller** [comment]
OK, will take over. @ChrisLevet232 if you would be so kind to send the apt to amtm.if@gmail.com
Thanks

**Comment by MajorTomMueller** [comment]
![egxc-git](https://user-images.githubusercontent.com/26853210/46691000-0fb11880-cc04-11e8-807f-e33254b868d0.jpg)
