### ISSUE TITLE
EFLP-Lappeenranta Airport-SOUTHERN FINLAND-FINLAND

### ISSUE THREAD

**Issue by ErshovlaD** [InfiniteFlightAirportEditing/Airports#1843]
Being redone

**Comment by dushyants19** [comment]
Please avoid breaking the 3-issue rule. Might result in dire consequences. 

Пожалуйста, не нарушайте правило из 3 вопросов. Это может привести к тяжелым последствиям. (Google Translate)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25771282/2e8a2fee-3213-11e7-8bcf-61c7b766e2bc.png)
