### ISSUE TITLE
EKAE-Aeroe-DENMARK

### ISSUE THREAD

**Issue by nk1021** [InfiniteFlightAirportEditing/Airports#1845]
The airport has been renovated IRL recently and needs to reflect that change and is missing alot of parking spots

**Comment by brunocr98** [comment]
Are you doing this? Please send an email to airport@liveflightapp.com to get started. Thanks.

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by MajorTomMueller** [comment]
recycled

**Comment by MajorTomMueller** [comment]
![ekae-git](https://user-images.githubusercontent.com/26853210/35339741-a5d3b1aa-0121-11e8-83f8-3158ce32747c.jpeg)
