### ISSUE TITLE
KZZV-Zanesville Municipal Airport-OHIO-USA

### ISSUE THREAD

**Issue by netjets-1951** [InfiniteFlightAirportEditing/Airports#1846]
Part of project Ohio.

**Comment by netjets-1951** [comment]
Sent in for review.

**Comment by dushyants19** [comment]
i like the ICAO; sorry for the late review

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26382704/e2b70526-3ff3-11e7-92bb-a6a2c0f4f04b.png)
