### ISSUE TITLE
I69-Clermont County Airport-OHIO-USA

### ISSUE THREAD

**Issue by netjets-1951** [InfiniteFlightAirportEditing/Airports#1847]
Home to Sporty's pilot shop. Project Ohio.

**Comment by dushyants19** [comment]
@netjets-1951 interested?

**Comment by ryu12332** [comment]
It has been 90 days since your assignment, and other airports have been done by you. If you are still working on this please let one of us know, or you may be unassigned. Thanks!

**Comment by netjets-1951** [comment]
As I have told you multiple times before, I don’t currently have the time to do this, but I am going to complete it as soon as I have some free time. 
(Also it’s only been 2 months since I was assigned)

**Comment by netjets-1951** [comment]
Sent in for review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36816909-f7622bca-1ca4-11e8-8f4e-f3500295abac.png)
