### ISSUE TITLE
KRSW-Southwest Florida International Airport-FLORIDA-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#185]
Florida

**Comment by Omari4u** [comment]
David / Cam..don't forget to remove runway spawning

**Comment by Swang007** [comment]
SoFlo, someone said this airport needs some love. No general aviation and there are only runway spawns!

**Comment by Omari4u** [comment]
yea that is one of those in the list i gave...

Date: Fri, 4 Sep 2015 05:25:32 -0700

**Comment by DavidCutler** [comment]
Spawns were added.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21207979/f064555c-c230-11e6-97ce-68fcc082d34b.png)

**Comment by bavAVIA** [comment]
Airport is lacking entire aprons and buildings, is loaded with unneccessary nodes and overlapping taxiways, snapping issues and has a lot of incorrect attributes for various objects.

**Comment by bavAVIA** [comment]
Entirely redoing.

**Comment by dushyants19** [comment]
Just updated Runway Markings and some snapping issues for the time being.

**Comment by bavAVIA** [comment]
Redone from scratch.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33861902-be3b7e74-dea5-11e7-9423-30361f0d0c99.png)

**Comment by ryu12332** [comment]
ISSUE: showing up as an echo when should be a bravo

**Comment by dushyants19** [comment]
Fixed 19 days ago, check development before reporting. Thanks.

**Comment by dushyants19** [comment]
https://github.com/InfiniteFlightAirportEditing/Airports/commit/8d252a90c40e5f6ba67a8918ecd321be33d3d164#diff-47bee1817253ad4e0328bc669a387123
