### ISSUE TITLE
KBKL-Burke Lakefront Airport-OHIO-USA

### ISSUE THREAD

**Issue by netjets-1951** [InfiniteFlightAirportEditing/Airports#1852]
Part of project Ohio
https://github.com/InfiniteFlightAirportEditing/Airports/tree/master/United%20States/K---/KB--/KBKL

**Comment by netjets-1951** [comment]
Sent in for review

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25771234/661b357c-3211-11e7-9e77-d10aa8a78efd.png)
