### ISSUE TITLE
RPLI

### ISSUE THREAD

**Issue by superven13** [InfiniteFlightAirportEditing/Airports#1855]
I will add taxiway, terminals, taxiway lines, spawns and a lot more.

**Comment by superven13** [comment]
Sent For Review :}

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29343830-31656e50-81f9-11e7-941d-f50d10a6d7dd.png)
