### ISSUE TITLE
OEYN-Yenbo/Prince Abdul Mohsin Bin Airport-AL MADINAH-SAUDI ARABIA

### ISSUE THREAD

**Issue by Boodz-G** [InfiniteFlightAirportEditing/Airports#1856]
Prince Abdul Mohsin bin Abdulaziz Airport. Will do it. 10K

**Comment by moritzbabl** [comment]
Up for grabs

**Comment by Syafsid** [comment]
i'll do this

**Comment by Syafsid** [comment]
Done!

**Comment by moritzbabl** [comment]
Added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28193916-32ff50b2-6806-11e7-934f-b8da5038e928.png)
