### ISSUE TITLE
RJFE-Fukue Airport-NAOASAKI-JAPAN

### ISSUE THREAD

**Issue by adrinerDP** [InfiniteFlightAirportEditing/Airports#1857]
♻️

**Comment by benlenahan** [comment]
Sent in for review.

**Comment by ryu12332** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/37461894-036783b4-281e-11e8-83c4-703cd7a965e9.png)
