### ISSUE TITLE
RJAZ-Kozushima Airport-SHIZUOKA-JAPAN

### ISSUE THREAD

**Issue by adrinerDP** [InfiniteFlightAirportEditing/Airports#1860]
♻️

**Comment by Marsiana7** [comment]
Pls assign me to this one. It does has stunning scenery around 😱🏔

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/37260525-2f7ab75a-2562-11e8-9c1c-0d950dee5ae5.png)
