### ISSUE TITLE
RKSS-Gimpo International Airport-SEOUL-SOUTH KOREA

### ISSUE THREAD

**Issue by adrinerDP** [InfiniteFlightAirportEditing/Airports#1861]
I'll do this.

**Comment by dushyants19** [comment]
https://github.com/InfiniteFlightAirportEditing/Airports/invitations

**Comment by IFK-Poco** [comment]
Please assign me

**Comment by MajorTomMueller** [comment]
Sorry @IFK-Poco , but @adrinerDP is already assigned to this one.

**Comment by adrinerDP** [comment]
It's okay~

**Comment by MajorTomMueller** [comment]
@adinerDP means you want to be unassigned?

**Comment by adrinerDP** [comment]
He will maintain apt design based on my data from now on. Please change asignee

**Comment by moritzbabl** [comment]
member inactive, up for grabs

**Comment by VladK125rus** [comment]
Can i start do this?

**Comment by IFK-Poco** [comment]
If you start, I'll give you the apt file(unperfected).

**Comment by VladK125rus** [comment]
Ok, no problem . I'll try to correct this :D

**Comment by IFK-Poco** [comment]
https://drive.google.com/file/d/1fe8zFg8BFApHzkZ_Cpq4Hk23RSzuhdmI/view?usp=drivesdk

**Comment by VladK125rus** [comment]
Thanks

**Comment by VladK125rus** [comment]
what the format of file? I cant import it into WED

**Comment by VladK125rus** [comment]
![image](https://user-images.githubusercontent.com/32869844/38188765-b10e2afa-36a0-11e8-9922-b94f825a0f49.png)
There is a problem

**Comment by IFK-Poco** [comment]
.dat  ->  .apt 
please modify

**Comment by VladK125rus** [comment]
Are you sure? WED recognizes just *name*.dat , not .apt. 
And can you check "Line 40" - WED still says that here's a problem

**Comment by IFK-Poco** [comment]
Okay i'll give some new file later

**Comment by dushyants19** [comment]
Just 40 lines of the airport data is present in the file.

**Comment by VladK125rus** [comment]
Dont understand you, Dush

**Comment by VladK125rus** [comment]
@IFK-Poco Could you give me file?

**Comment by IFK-Poco** [comment]
[new gimpo.zip](https://github.com/InfiniteFlightAirportEditing/Airports/files/1894959/new.gimpo.zip)
good luck..

**Comment by VladK125rus** [comment]
Actually, it working, thx

**Comment by VladK125rus** [comment]
Also u r right with the luck lol xD
You have too many mistakes in your version of airport
But i think i'll correct them :D

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/39551616-4d35c2ac-4e2b-11e8-94ef-22aa96bf6d01.png)
