### ISSUE TITLE
EGJB-Guernsey Airport-CHANNEL ISLANDS-UNITED KINGDOM

### ISSUE THREAD

**Issue by ItsW1ll** [InfiniteFlightAirportEditing/Airports#1863]
Full Redo - Runway extension and lots of apron improvements. 
Please assign me.

**Comment by ItsW1ll** [comment]
Sent for review

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27230130-d9f78504-5273-11e7-96a1-95d6f19df774.png)

**Comment by ItsW1ll** [comment]
#4621 Moved EGJA, EGJB, EGJJ to the same folder
