### ISSUE TITLE
RKJM-Mokpo Airport-JEOLLANAM-DO-SOUTH KOREA

### ISSUE THREAD

**Issue by adrinerDP** [InfiniteFlightAirportEditing/Airports#1864]
Completed. Pull requested for review.

**Comment by adrinerDP** [comment]
Sent for review

**Comment by dushyants19** [comment]
I'll close it..

**Comment by kilt46** [comment]
Mokpo Airport was an airport in Mokpo, South Korea (IATA: MPK, ICAO: RKJM). In 2006, 16,909 passengers utilized the airport.[3] This airport was closed when the nearby Muan International Airport opened in November 2007.

DELETING FROM DATABASE

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32832601-a7f08400-c9c1-11e7-8ad3-b793e7fd4541.png)
