### ISSUE TITLE
LZZI-Zilina Airport-ZILINA-SLOVAKIA

### ISSUE THREAD

**Issue by Hornet199** [InfiniteFlightAirportEditing/Airports#1868]
Being redone. Low priority regional airport.

**Comment by Hornet199** [comment]
Sent for review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26063743/7c89c540-3954-11e7-9626-b3aeef53e9b1.png)
