### ISSUE TITLE
KSFB-Orlando Sanford International Airport-FLORIDA-USA

### ISSUE THREAD

**Issue by Jackol2702** [InfiniteFlightAirportEditing/Airports#1869]
PLEASE REDRAW ME!!!!!!!!

**Comment by ItsW1ll** [comment]
why did you close it?

**Comment by Jackol2702** [comment]
Sorry i got the icao mixed up and airport I'm now doing another

**Comment by ItsW1ll** [comment]
next time please rename the issue.

**Comment by bavAVIA** [comment]
Recycled. Up for grabs.

**Comment by thisthatone** [comment]
I'll do it

**Comment by thisthatone** [comment]
Sent for review by email

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by aircanada143** [comment]
I got this 🙃

**Comment by ryu12332** [comment]
Progress?

**Comment by aircanada143** [comment]
Oh, yeah sorry for being slow on it, will try to speed up if I can
