### ISSUE TITLE
KSRQ

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#187]
Florida

**Comment by JohnPreston21** [comment]
This one was too big. Sorry guys.

**Comment by kilt46** [comment]
Started

**Comment by kilt46** [comment]
This one has been completely redone

**Comment by kilt46** [comment]
Still working on this one

**Comment by kilt46** [comment]
Now complete

**Comment by kilt46** [comment]
Reworking

**Comment by kilt46** [comment]
Redone airport with 4x single aprons

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21080231/d54d28ac-bf6f-11e6-85aa-bfe703020f35.png)
