### ISSUE TITLE
KCLE-Cleveland-Hopkins International Airport-OHIO-USA

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#1871]
It's about time someone tackles this.
Cleveland - Hopkins International Airport, Ohio, United States.

**Comment by netjets-1951** [comment]
Ah man, I was literally about to make this issue. Good luck!
Also, this needs to be in the +10,000 feet category and tag

**Comment by bavAVIA** [comment]
Nope. Cleveland misses Priortiy II by 44 feet.

**Comment by netjets-1951** [comment]
Oh whoops, I was thinking of before the removal of the third runway.

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26757868/289db670-4891-11e7-8ff7-699808acb7ef.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52184856-82ab5400-27de-11e9-96db-bd2685b8f9c0.png)

**Comment by kilt46** [comment]
REMOVE DUPLICATE SPAWNS BUILDINGS REMOVED
