### ISSUE TITLE
UNKL-Krasnoyarsk Airport-KRASNOYARSK-RUSSIA

### ISSUE THREAD

**Issue by ErshovlaD** [InfiniteFlightAirportEditing/Airports#1872]
Being redone
Priority 2

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26073417/6ed945ae-3974-11e7-9288-a4afb24465a2.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44123326-5caa0b9e-9fed-11e8-96f3-d498262f1dc6.png)
