### ISSUE TITLE
EPWR-Wroclaw Strachowice Airport-LOWER SILESIAN-POLAND

### ISSUE THREAD

**Issue by Spinxzl** [InfiniteFlightAirportEditing/Airports#1878]
RECYCLED ♻️

**Comment by dushyants19** [comment]
Please search before posting. This is the 2nd time you're doing this.

**Comment by brunocr98** [comment]
Recycled. Doing this one.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26130520/cf7a0c22-3a5a-11e7-9ea0-00e1450624a3.png)
