### ISSUE TITLE
ENGM-Oslo Gardermoen Airport-AKERSHUS-NORWAY

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#1879]

**Comment by bavAVIA** [comment]
Tackling this as soon as newer imagery is available. One Terminal concourse and 01L/19R are still under construction on latest Google imagery.

**Comment by Aviationluver** [comment]
I will take this one. Seems like a nice challenge.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28492811-c6a7e714-6ecf-11e7-821d-363923070d0d.png)

**Comment by MajorTomMueller** [comment]
Spawn Size has to be fixed for BBJ and C-130:

![ENGM-mil-C-130](https://user-images.githubusercontent.com/26853210/66718841-eb1feb80-edd7-11e9-92ee-0265c4e53c2b.png)

**Comment by MajorTomMueller** [comment]
@Aviationluver contact viw DM if unlear

**Comment by MajorTomMueller** [comment]
Spawns fixed, Buildings removed.
lacks Hangar space now, and some concrete patches.
Anyway closed for now.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/66757529-c462c300-ee72-11e9-9a75-d51501120aef.jpg)

**Comment by MajorTomMueller** [comment]
https://ais.avinor.no/AIP/Latest/aip/ad/engm/engm_en.html

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112737194-910cda80-8f26-11eb-9606-69b9bc3c4c3d.png)
