### ISSUE TITLE
EBAV

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#188]
Amsterdam

**Comment by kilt46** [comment]
THis was completed and uploaded by Cameron

**Comment by kilt46** [comment]
spawn on runway

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/11328380/e5467b28-914e-11e5-9cfd-fcb22a5c19e3.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20038203/2a1fa350-a3f5-11e6-8aac-7636c60d8a8d.png)
