### ISSUE TITLE
LZTN-Trencin Airport-TRENCIN-SLOVAKIA

### ISSUE THREAD

**Issue by Hornet199** [InfiniteFlightAirportEditing/Airports#1880]
Being redone

**Comment by Hornet199** [comment]
Sent to review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26063106/93934f9c-3952-11e7-8ff1-169a5faf6ad8.png)
