### ISSUE TITLE
LZPP-Piestany Airport-TRNAVA-SLOVAKIA

### ISSUE THREAD

**Issue by Hornet199** [InfiniteFlightAirportEditing/Airports#1881]
Being redone

**Comment by Hornet199** [comment]
Sent to review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26062199/c670d3f6-394f-11e7-8282-16d023d55cc9.png)
