### ISSUE TITLE
UCFM-Bishkek-Manas Airport-CHUY-KYRGYZSTAN

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#1883]

**Comment by MajorTomMueller** [comment]
![ucfm-git](https://user-images.githubusercontent.com/26853210/37557869-4cb37d9a-2a0b-11e8-97b7-719f4168722a.jpeg)

**Comment by MajorTomMueller** [comment]
boundary

**Comment by MajorTomMueller** [comment]
- Boundary Fix
- Buildings removed
- Hangar Floors added
