### ISSUE TITLE
MUCU-Santiago Airport-SANTIAGO DE CUBA-CUBA

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#1885]

**Comment by brunocr98** [comment]
There's an issue for this airport: #1488

**Comment by alchonub** [comment]
I'll do it

**Comment by brunocr98** [comment]
Cannot assign you. Finish one of your 3 assigned airports.

**Comment by alchonub** [comment]
I've finished all 3

**Comment by brunocr98** [comment]
However, they're not approved yet.

**Comment by cptchris** [comment]
I'll do this one, i only have 2 out of 3 airports done.

**Comment by cptchris** [comment]
Sorry about this, i'll wont be able to do it for a couple of days so please unassign me. Thanks :)

**Comment by brunocr98** [comment]
Up for grabs.

**Comment by cptchris** [comment]
Alright, when one of my airports get approved i could do this one again. Priority #1 for project cuba.

**Comment by cptchris** [comment]
Alright, I'll take this one.

**Comment by cptchris** [comment]
Can some one assign me this? I already finished it.

**Comment by bavAVIA** [comment]
You're welcome. That would be a 15€ administration fee.

**Comment by cptchris** [comment]
@bavAVIA I dont use euroes

**Comment by ewanfleming** [comment]
That's clear cause you can't spell it right 🙄

**Comment by cptchris** [comment]
Ewan, for commenting on an issue you dont contribute too that would be 500€

**Comment by dushyants19** [comment]
Who are you to charge 🤔

**Comment by cptchris** [comment]
Dush, For also commenting on an issue you dont contribute to that would be 2 quintillion rupees.

**Comment by ewanfleming** [comment]
I swear that's about 5 pence

**Comment by cptchris** [comment]
In for review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
Recommended gating
![image](https://user-images.githubusercontent.com/14023167/31433019-b79522e8-ae3d-11e7-83dd-79b9e11e8bf6.png)
![image](https://user-images.githubusercontent.com/14023167/31433054-c8843508-ae3d-11e7-85c1-fbd57b318d26.png)

**Comment by cptchris** [comment]
Resent For Review.

**Comment by moritzbabl** [comment]
readded

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31865548-e9094038-b735-11e7-8416-5d186656d55e.png)
