### ISSUE TITLE
ZUGU-Guangyuan Panlong Airport-SICHUAN-CHINA

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#1886]

**Comment by thisthatone** [comment]
I'll do it

**Comment by Aviationluver** [comment]
I will take this. Exams are finished and have some time to kill.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27509296-d6a82ee8-58be-11e7-8731-b59a18c0a108.png)
