### ISSUE TITLE
MMIA-Colima National Airport-COLIMA-MEXICO

### ISSUE THREAD

**Issue by Epadilla1** [InfiniteFlightAirportEditing/Airports#1887]
Missing Taxiways
Missing Lines
Missing Gates

**Comment by Epadilla1** [comment]
Could I be assigned to this, thanks!

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26383054/37edd496-3ff6-11e7-9bb5-12178d16d313.png)
