### ISSUE TITLE
EBBZ

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#189]
Amsterdam

**Comment by kilt46** [comment]
This was completed and uploaded

**Comment by kilt46** [comment]
Spawn on runway

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/11328400/5a5c908c-914f-11e5-8c02-3214ad20c2ab.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20038181/a6634558-a3f4-11e6-95f5-e456bfb0932b.png)
