### ISSUE TITLE
LOXZ-Zeltweg Airport/Fliegerhorst Hinterstoisser-STEIERMARK-AUSTRIA

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#1890]
Fliegerhorst Hinterstoisser, Zeltweg, Steiermark, Austria.

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
This 
![image](https://cloud.githubusercontent.com/assets/14023167/26284570/47793160-3e04-11e7-9855-2555f0dfb46c.png)
