### ISSUE TITLE
LZIB-Bratislava Airport-BRATISLAVA-SLOVAKIA

### ISSUE THREAD

**Issue by Hornet199** [InfiniteFlightAirportEditing/Airports#1891]
Being redone

**Comment by Hornet199** [comment]
Sent to review

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26287595/9108ccec-3e44-11e7-9804-25762ac18225.png)

**Comment by kilt46** [comment]
Parsing error in ../../../Data/Airports/Slovakia\LZIB\apt.dat (line 2094). Parsing error while processing rowcode: 50 Reason: Input string was not in a correct format.

Fixed and buildings removed!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/49192240-d6fa0980-f33f-11e8-9b90-cdabd9a3cda5.png)
