### ISSUE TITLE
EEEI-Amari Military Airport-HARJU-ESTONIA

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#1892]

**Comment by STraveler** [comment]
I'll take this one

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27182609-708b87aa-51a1-11e7-81a5-dadc1b2645b5.png)

**Comment by MajorTomMueller** [comment]
![amara](https://user-images.githubusercontent.com/26853210/46879946-a588b580-ce47-11e8-9b94-c62c44985dda.jpg)
scrolled images over the years, spawns at Apron 2 have to be turned around.
will you do @STraveler ?

**Comment by MajorTomMueller** [comment]
Apron 3+4 added
![EEEI-git](https://user-images.githubusercontent.com/26853210/133922419-42f117ca-5505-4544-a7a6-d01657031793.png)
