### ISSUE TITLE
LICA-Lamezia Terme Airport-CALABRIA-ITALY

### ISSUE THREAD

**Issue by johanneskkl** [InfiniteFlightAirportEditing/Airports#1893]
very last airport of project italy. Runway lenght:9´900 ft.
lamezia terme

**Comment by johanneskkl** [comment]
please unassign, cant find this airport in my PC: no APT avalaible

**Comment by dushyants19** [comment]
Your PC is broken. There is one: https://github.com/InfiniteFlightAirportEditing/Airports/blob/development/Italy/LICA/apt.dat

**Comment by johanneskkl** [comment]
Thanks

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31554267-a61b93a0-b002-11e7-8a4f-bdc3e1e6bcf4.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/67620196-9d917e80-f7da-11e9-8509-df3e29ea19a7.jpg)
