### ISSUE TITLE
7V9-City of Las Animas - Bent County Airport-COLORADO-USA

### ISSUE THREAD

**Issue by thisthatone** [InfiniteFlightAirportEditing/Airports#1894]
♻️

**Comment by thisthatone** [comment]
Sent for review via pull request

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/35543088-c8e0e4f0-0528-11e8-9f64-a25a67cc22ab.png)
