### ISSUE TITLE
LIRZ-Perugia San Francesco d'Assisi-UMBRIA-ITALY

### ISSUE THREAD

**Issue by johanneskkl** [InfiniteFlightAirportEditing/Airports#1896]
Perugia airport. Committed by Alitalia VA

**Comment by johanneskkl** [comment]
Error 404: imagery not found. Other imgarey is outdated. please unassign . Up for crabs

**Comment by brunocr98** [comment]
Crabs don't edit airport.

**Comment by dushyants19** [comment]
You probably left like 1863592 airports in your Project and just tell everyone at the forum that your project is complete. Great.

**Comment by liamkirky** [comment]
I'd like to take this one.

**Comment by liamkirky** [comment]
Because i am doing navigation i will be spending more time on that and won't be editing anymore. This airport is a nice small one.

**Comment by Hornet199** [comment]
I will do it...

**Comment by Hornet199** [comment]
Sent to review

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29390374-876958d6-82b5-11e7-939d-7a123e779125.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/70666021-93bdc080-1c4c-11ea-92c5-0f10c60f6ed2.jpg)
