### ISSUE TITLE
UUOL-Lipetsk Airport-LIPETSK-RUSSIA

### ISSUE THREAD

**Issue by MiguelIF27** [InfiniteFlightAirportEditing/Airports#1898]
Lipetsk Airport

**Comment by kilt46** [comment]
Suggested parking
![image](https://user-images.githubusercontent.com/14023167/29741524-94b82914-8a34-11e7-8efb-4f44b9730028.png)
![image](https://user-images.githubusercontent.com/14023167/29741530-a33c483a-8a34-11e7-9cd5-06a95744a3a7.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30514448-41484a0a-9ada-11e7-9887-9b2dc4a893bb.png)
