### ISSUE TITLE
ENFG-Fagernes Leirin Airport-OPPLAND-NORWAY

### ISSUE THREAD

**Issue by Tom-Bonfield** [InfiniteFlightAirportEditing/Airports#1899]
Ill do it

**Comment by MajorTomMueller** [comment]
could do this one...

**Comment by MajorTomMueller** [comment]
send to review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33242450-e708e164-d29a-11e7-82fd-5e21f8f6fe32.png)

**Comment by MajorTomMueller** [comment]
boundary

**Comment by MajorTomMueller** [comment]
- Boundary fix
- Buildings removed
- Hangar Floor added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46382905-10313880-c673-11e8-9526-a13e389bf7ea.png)
