### ISSUE TITLE
TLPL-Hewanorra International Airport-VIEUX FORT-SAINT LUCIA

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Airports#1901]
Stepping away from Project New England to complete a couple of missing Caribbean airports that, in my opinion, should be redone. :)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26284472/f62ad64e-3e01-11e7-9d19-e36aae892f72.png)
