### ISSUE TITLE
UWLL-Ulyanovsk/Baratayevka Airport-UL'YANOVSK-RUSSIA

### ISSUE THREAD

**Issue by ErshovlaD** [InfiniteFlightAirportEditing/Airports#1904]
Being done from scratch
Priority 2

**Comment by kilt46** [comment]
CHARTS SHOW DIFFERENT LAYOUT FOR GATES
![image](https://user-images.githubusercontent.com/14023167/27183823-ac2ef810-51a5-11e7-95c9-22d1a0455c08.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27183849-bdf5cbbe-51a5-11e7-9074-f7d1762d8d4e.png)

**Comment by henrikbg** [comment]
Gates have been fixed and approved.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30303130-697b71e4-972b-11e7-8f42-b3cc9e2d0e3b.png)
