### ISSUE TITLE
WAHH-Adi Sutjipto Airport-YOGYAKARTA-INDONESIA

### ISSUE THREAD

**Issue by haociek** [InfiniteFlightAirportEditing/Airports#1906]
Adi Sutjipto Airport, Yogyakarta
will do this
previous ICAO was WARJ

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27010662-099af290-4e6f-11e7-850a-f47d7db06f38.png)

**Comment by MajorTomMueller** [comment]
What ever the GitHub name is that wants to redo this one. Comment here.

**Comment by vinoalviano1994** [comment]
I want to redo this Airport
