### ISSUE TITLE
LZSV-Spisska Nova Ves Airport-KOSICE-SLOVAKIA

### ISSUE THREAD

**Issue by Hornet199** [InfiniteFlightAirportEditing/Airports#1907]
Being redone. Small airport with grass runway. Done from scratch. Currently has a minus sign.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26611483/3566678c-4574-11e7-9322-cd0f8ad984a2.png)
