### ISSUE TITLE
EBWE

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#191]
Amsterdam

**Comment by kilt46** [comment]
Started

**Comment by kilt46** [comment]
Redone

**Comment by kilt46** [comment]
spawn on runway

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/11328534/f8faf7d6-9151-11e5-9935-70e0e545c235.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20911293/a7418d3c-bb2c-11e6-8155-6470b2fb8c5c.png)
