### ISSUE TITLE
MMCU-Chihuahua Airport-CHIHUAHUA-MEXICO

### ISSUE THREAD

**Issue by lalomarlin** [InfiniteFlightAirportEditing/Airports#1910]
Being Redone

**Comment by moritzbabl** [comment]
Added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27458910-19869488-5771-11e7-8199-7e48683e4b1a.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27459762-53abbb08-5775-11e7-862c-e81809fb7096.png)
