### ISSUE TITLE
LKPD-Pardubice Airport-PARDUBICE-CZECH REPUBLIC

### ISSUE THREAD

**Issue by Hornet199** [InfiniteFlightAirportEditing/Airports#1912]
Being redone

**Comment by Hornet199** [comment]
Sent to review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26613041/535ffc44-457e-11e7-8710-161f82af1386.png)
