### ISSUE TITLE
KDAY-James M. Cox-Dayton International Airport-OHIO-USA

### ISSUE THREAD

**Issue by netjets-1951** [InfiniteFlightAirportEditing/Airports#1913]
Part of Project Ohio, +10,000 Feet category

https://github.com/InfiniteFlightAirportEditing/Airports/tree/master/United%20States/K---/KD--/KDAY

**Comment by netjets-1951** [comment]
Correction, I didn't mean to make this issue yet. Sorry. Please close or re-use it.

**Comment by brunocr98** [comment]
I'll just let it as a suggestion if someone wants it.

**Comment by netjets-1951** [comment]
Well, I still want to do it, but I want to rework KOSH first.

**Comment by brunocr98** [comment]
KOSH has been reworked already, see issue #51

**Comment by netjets-1951** [comment]
That's the one in the sim currently, right? It is missing a few important things.

**Comment by brunocr98** [comment]
Yes, in the Oshkosh region.

**Comment by PrinceObi15** [comment]
May I do this airport?

**Comment by TristinWoolf** [comment]
@netjets-1951 How far is progress on the other three airports assigned to you? If you aren't close to sending one in for review, I will assign @PrinceObi15.

**Comment by PrinceObi15** [comment]
Actually, never mind. I won't be able to do this one.

**Comment by netjets-1951** [comment]
Please assign me back to this airport. Thanks!

**Comment by netjets-1951** [comment]
Sent in for review

**Comment by henrikbg** [comment]
Approved.

**Comment by kilt46** [comment]
Please check for the following gates
![image](https://user-images.githubusercontent.com/14023167/30765682-8df1ac08-9fb6-11e7-877f-403d23b085cf.png)
![image](https://user-images.githubusercontent.com/14023167/30765699-9fd842f6-9fb6-11e7-83e3-280364f5fa03.png)

**Comment by netjets-1951** [comment]
Which gates are you talking about specifically?

**Comment by netjets-1951** [comment]
It's not being redone...

**Comment by netjets-1951** [comment]
Kilt, I don’t know if you saw my message to you on Slack, but all the gates are correct according to the airport’s website.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31060970-76f2ed00-a6e1-11e7-9c2c-72501b44e033.png)
