### ISSUE TITLE
WIGG-Bengkulu/Fatmawati Soekarno Airport-BENGKULU-INDONESIA

### ISSUE THREAD

**Issue by haociek** [InfiniteFlightAirportEditing/Airports#1914]
Fatmawati Soekarno Airport, Bengkulu, Indonesia
Will do this

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26717663/cfdcda82-4743-11e7-985c-64f72d75e37c.png)

**Comment by MajorTomMueller** [comment]
There is a new concrete expansion in imagery.
Not shown in documents yet:
https://aimindonesia.dephub.go.id/images/138-WIGG%20AD%202-1%20to%20AD%202-13.pdf
https://aimindonesia.dephub.go.id/images/513-WIGG%20AD%202.24-1.pdf

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85909682-a9599880-b7e0-11ea-9f20-f7d79b3ce701.png)
