### ISSUE TITLE
WIJJ-Sultan Thaha Airport-JAMBI-INDONESIA

### ISSUE THREAD

**Issue by haociek** [InfiniteFlightAirportEditing/Airports#1918]
Sultan Thaha Airport, Jambi, Indonesia
previous ICAO was WIPA

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26719561/a7eef8dc-474a-11e7-8e5d-b2016b90490b.png)

**Comment by Czechoslovaki** [comment]
@vinoalviano1994 will update the airport.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103048542-9556df80-4554-11eb-8bdf-43c3f269158a.png)
