### ISSUE TITLE
WAMG

### ISSUE THREAD

**Issue by haociek** [InfiniteFlightAirportEditing/Airports#1919]
Jalaluddin Airport, Gorontalo, Indonesia
will do this........

**Comment by bavAVIA** [comment]
You are already assigned to four issues, the maximum is three.
Please wait until your other airports have been approved and you have a free spot for an airport before creating issues.
Not assigning for the time being.
Thanks.

**Comment by haociek** [comment]
okk

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27182874-5a15e92e-51a2-11e7-999c-4fd9cf8103ca.png)
