### ISSUE TITLE
LKVO-Prague/Vodochody Airport-PRAGUE-CZECH REPUBLIC

### ISSUE THREAD

**Issue by Hornet199** [InfiniteFlightAirportEditing/Airports#1921]
Being redone.

**Comment by Hornet199** [comment]
Sent to review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26727432/7ec66cca-476c-11e7-8b99-b4dcce911ab9.png)
