### ISSUE TITLE
LZLU-Lucenec Airport-BANSKA BYSTRICA-SLOVAKIA

### ISSUE THREAD

**Issue by Hornet199** [InfiniteFlightAirportEditing/Airports#1922]
Being redone.

**Comment by Hornet199** [comment]
Sent to review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26726831/29ea74f0-476a-11e7-8a6e-452ced41b640.png)
