### ISSUE TITLE
LZSK-Svidnik Airport-PRESOV-SLOVAKIA

### ISSUE THREAD

**Issue by Hornet199** [InfiniteFlightAirportEditing/Airports#1923]
Being redone

**Comment by Hornet199** [comment]
Sent to review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26726978/9efa288a-476a-11e7-96cd-5b1b0802ef9e.png)
