### ISSUE TITLE
HTAR-Arusha Airport-ARUSHA-TANZANIA

### ISSUE THREAD

**Issue by ewanfleming** [InfiniteFlightAirportEditing/Airports#1924]
Arusha Airport, I will do it ;-)

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27010866-633d2476-4e74-11e7-9ff9-825cab020cac.png)

**Comment by RyanEpps** [comment]
Gabe

**Comment by Gabe-Z** [comment]
Thank you Ryan.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/81989028-dd06a780-9612-11ea-905c-ddeab473e054.jpg)
