### ISSUE TITLE
EDKV

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#193]
Amsterdam

**Comment by kilt46** [comment]
Too many double yellow lines. No center lines. Needs a little love

**Comment by kilt46** [comment]
Wow this is real messed up
![image](https://cloud.githubusercontent.com/assets/14023167/16900790/2016bf2c-4bf5-11e6-92ac-14de459e0228.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/16900912/b55f5992-4bf8-11e6-8d07-2592f71fb79e.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18615501/2aefa850-7d6e-11e6-8026-29d9f32118de.png)
