### ISSUE TITLE
ZSHC-Hangzhou Xiaoshan International Airport-ZHEJIANG-CHINA

### ISSUE THREAD

**Issue by LightsR** [InfiniteFlightAirportEditing/Airports#1932]
Being redone

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by mbmhwue148** [comment]
I'll take it

**Comment by brunocr98** [comment]
You need to have 3 of your airports in review in order to be assigned to this one.

**Comment by mbmhwue148** [comment]
Alright, will finish those who are due and take it then.

**Comment by mbmhwue148** [comment]
All 3 due airports are completed and sent to different stages of review. Hope, I may take it now.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36817278-299f1e4e-1ca6-11e8-8d54-4240ea008e50.png)

**Comment by kilt46** [comment]
Gate Review

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42136767-1e72e8c0-7d27-11e8-8215-899d2407a310.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50740679-9059c380-11b7-11e9-9dd5-7ac1fc77ff64.png)

**Comment by kilt46** [comment]
Duplicate gate removal
