### ISSUE TITLE
LDZD-Zadar/Zemunik Airport-ZADARSKA-CROATIA

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#1933]
Zadar Int'l Airport. Being Redone.

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27033783-77eabf1a-4f40-11e7-9ec3-86eee12cdd68.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55284109-9c2bd080-5335-11e9-9f6f-b4460b3b3f2c.png)
