### ISSUE TITLE
EKSP-Vojens Skrydstrup Airport-SOUTH JUTLAND-DENMARK

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#1934]
Would start to do this one. It is the Dansk F16 Base.

**Comment by MajorTomMueller** [comment]
Send to review

**Comment by moritzbabl** [comment]
added

**Comment by MajorTomMueller** [comment]
![eksp-skrydstrup-denmark](https://user-images.githubusercontent.com/26853210/27444427-a052b6f4-5776-11e7-8309-53a45c25d947.jpeg)

**Comment by MajorTomMueller** [comment]
Adjusted Shelter Spawns
removed unrealistic Hangar Spawns
renamed some Hangar Spawns for clarification

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/40262529-a7519e38-5acd-11e8-9ae0-03abf330555f.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44948259-1a47e900-ade0-11e8-86f7-ecf99488e838.png)

**Comment by kilt46** [comment]
Boundary Fix
