### ISSUE TITLE
UBBL-Lenkoran International Airport-LENKORAN-AZERBAIJAN

### ISSUE THREAD

**Issue by PrinceObi15** [InfiniteFlightAirportEditing/Airports#1936]
RECYCLED ♻️

**Comment by brunocr98** [comment]
Please search before posting. If you wish to correct this issue, send an email to airports@liveflightapp.com. KORD already has en issue. #19

**Comment by bavAVIA** [comment]
Recycled. Taking over as soon as I have a free spot.

**Comment by bavAVIA** [comment]
Taking over.

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27032548-f5084ca2-4f3a-11e7-9a41-e7982d96d7e5.png)
