### ISSUE TITLE
KTYQ-Indianapolis Executive Airport-INDIANA-USA

### ISSUE THREAD

**Issue by ZaidSal** [InfiniteFlightAirportEditing/Airports#1941]
♻️

**Comment by brunocr98** [comment]
Please send an email to airports@liveflightapp.com to join our team **AND** to do this airport.

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by danielacooper** [comment]
Emailed to contact@airportediting.com

Thanks

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36340973-b89065b6-13ac-11e8-8ad8-eb3fd1980718.png)
