### ISSUE TITLE
LERJ-Logrono Airport-LA RIOJA-SPAIN

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#1942]
Logrono Airport, being redone.

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27255612-057b0806-5367-11e7-80d2-558a1068df68.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109883584-4064d300-7c41-11eb-9ba8-daf52e231166.png)

**Comment by kilt46** [comment]
Should be the commercial airport
![Uploading image.png…]()

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113459360-eb041900-93da-11eb-9905-1eb1c19ee143.png)
