### ISSUE TITLE
EDLA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#195]
Amsterdam

**Comment by IceBlue02** [comment]
@JohnPreston21 is this finished?

**Comment by JohnPreston21** [comment]
You can have this one @IceBlue02. Completely forgot about it.

**Comment by IceBlue02** [comment]
Will do, thanks @JohnPreston21

**Comment by JohnPreston21** [comment]
Sorry about that

**Comment by IceBlue02** [comment]
Finished and sent in

**Comment by henrikbg** [comment]
Accepted.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18036325/f9ff2e7e-6d2c-11e6-8517-be8907e08589.png)
