### ISSUE TITLE
EDLD-Dinslaken/Schwarze Heide Airport-NORDRHEIN-WESTFALEN-GERMANY

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#196]
Amsterdam

**Comment by kilt46** [comment]
This one has been reworked

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/16714709/1d10121a-4691-11e6-8707-222b00372383.jpeg)

**Comment by dushyants19** [comment]
Oo white lines been ages since i have seen that

**Comment by kilt46** [comment]
REDONE
![image](https://cloud.githubusercontent.com/assets/14023167/16898715/1bca61ca-4bab-11e6-9be7-59b62dcd35f9.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18615604/32beebe8-7d70-11e6-8a52-4bce9eadd737.png)
