### ISSUE TITLE
ZUBD-Qamdo Bangda Airport-BAMDA-CHINA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#197]
Please redraw me

**Comment by JohnPreston21** [comment]
Did a complete redesign. awaiting approval or rejection. My First of many full redesigns

**Comment by JohnPreston21** [comment]
Jonathon not long looked at this on and added to the libary

**Comment by Yifan081** [comment]
I can redo this one, please assign me.

**Comment by Yifan081** [comment]
Sent for review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24322408/d957ccb8-1131-11e7-9422-7dca262683f2.png)
