### ISSUE TITLE
EDQZ

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#1973]
Bavarian GA field, will be pushed shortly

**Comment by bavAVIA** [comment]
Please only 3 issues per editor @moritzbabl.
Are you new here?

**Comment by moritzbabl** [comment]
I'm sorry, can you unassign me, please? I can't do them anyway

**Comment by bavAVIA** [comment]
Up for grabs

**Comment by moritzbabl** [comment]
lol - done, as well as all the other airports of the spam

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27002450-5344a098-4da8-11e7-9b35-0d1968918c38.png)
