### ISSUE TITLE
EGCB-Manchester Barton Airport-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by IceBlue02** [InfiniteFlightAirportEditing/Airports#1974]
Manchester Barton- Small GA project

**Comment by MajorTomMueller** [comment]
@IceBlue02 you are not assigned to it yet. Might want to change this or remove the redone label...

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42913739-3404f1fe-8abc-11e8-8689-8554635c9177.png)
