### ISSUE TITLE
WILL-Radin Inten II Airport-LAMPUNG-INDONESIA

### ISSUE THREAD

**Issue by haociek** [InfiniteFlightAirportEditing/Airports#1975]
Raden Inten II, Lampung, Indonesia
will do this

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27227498-4d0fefb4-5269-11e7-8fb9-00ad80773c9f.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/81993478-23accf80-961c-11ea-80ee-ec5042b56381.jpg)
