### ISSUE TITLE
GMTT-Tangier Ibn Batouta Airport-TANGER-TETOUAN-MOROCCO

### ISSUE THREAD

**Issue by ewanfleming** [InfiniteFlightAirportEditing/Airports#1979]
Tangier Ibn Battuta Airport. I will do it. Bigger than my last one so a bit more of a challenge ;-)

**Comment by moritzbabl** [comment]
Added

**Comment by kilt46** [comment]
Gate Configuration
![image](https://user-images.githubusercontent.com/14023167/28147737-2d017dc0-6748-11e7-8a28-cb3d679a55e2.png)

**Comment by moritzbabl** [comment]
Added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28248808-49779dac-6a10-11e7-9fa0-f2d575df93e0.png)
