### ISSUE TITLE
EDLH-Hamm Lippewiesen Airport-NORDRHEIN-WESTFALEN-GERMANY

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#198]
Amsterdam

**Comment by kilt46** [comment]
Started

**Comment by kilt46** [comment]
Completed

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/16714908/b4c4b5b6-4696-11e6-9900-5a82f775b78d.jpeg)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/16901685/16279a0c-4c10-11e6-822e-15c76ca2b3c7.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18615359/9e890a44-7d6a-11e6-9270-e59c802e59dd.png)
