### ISSUE TITLE
EKYT-Aalborg Airport-NORTH JUTLAND-DENMARK

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#1982]
for use with the C130 DK liveley, be edited by me.

**Comment by MajorTomMueller** [comment]
send to peer review in slack

**Comment by MajorTomMueller** [comment]
send to acceptance

**Comment by MajorTomMueller** [comment]
![ekyt-aalborg-denmark-overview](https://user-images.githubusercontent.com/26853210/27878792-b1cf3846-61bf-11e7-954c-680b8f4ce0f7.jpeg)

**Comment by kilt46** [comment]
Runway too long
![image](https://user-images.githubusercontent.com/14023167/27936440-5ddb0c76-6276-11e7-8984-d4428b8e544e.png)

![image](https://user-images.githubusercontent.com/14023167/27936434-5222844a-6276-11e7-9e60-f74874f93476.png)

**Comment by MajorTomMueller** [comment]
The difference in RWY length comes from WED including the threshold in it. The ends of this RWY are thresholds according to satellite imagery.

**Comment by MajorTomMueller** [comment]
I have checked other Airports with displaced threshold. It is a issue of WED that it is showing RWY length including the displaced thresholds. If the decision is to draw the displaced threshold as blast-pad as a work around you have to reopen several airports and change them.
Please deicide, and let me know. I will change the thresholds to blast-pads on moderators request. 
Otherwise this issue could be closed.

**Comment by MajorTomMueller** [comment]
changed displaced Treshold to Blastpads at RWY 08L/26R in WED, despite Sat-Images to fit RWY length with AIP dokuments.
Send apt.dat to airportediting@

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28484375-855d500c-6e37-11e7-8363-9bb45299d644.png)
