### ISSUE TITLE
KHFD-Hartford-Brainard Airport-CONNECTICUT-USA

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Airports#1984]
Part of [Project New England](https://community.infinite-flight.com/t/project-new-england/43169).

**Comment by CptNathanHope** [comment]
Done.

**Comment by kilt46** [comment]
Remove hatching: NOT ALLOWED
![image](https://user-images.githubusercontent.com/14023167/27518765-eba9fa44-59ac-11e7-9d1c-d10610dd231a.png)

**Comment by CptNathanHope** [comment]
Removed hatchings as requested.

<img width="341" alt="screen shot 2017-06-26 at 1 00 32 pm" src="https://user-images.githubusercontent.com/19478765/27552261-a2f12f52-5a74-11e7-8d7f-3d952fb09950.png">
<img width="378" alt="screen shot 2017-06-26 at 1 00 39 pm" src="https://user-images.githubusercontent.com/19478765/27552263-a315bcfa-5a74-11e7-9c0f-91905d83230b.png">
<img width="288" alt="screen shot 2017-06-26 at 1 00 45 pm" src="https://user-images.githubusercontent.com/19478765/27552262-a30e9cf4-5a74-11e7-8dc4-81ccc019370c.png">

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27565332-5505925e-5aa3-11e7-81d4-950a5d838f41.png)
