### ISSUE TITLE
MMDO-Durango International Airport-DURANGO-MEXICO

### ISSUE THREAD

**Issue by lalomarlin** [InfiniteFlightAirportEditing/Airports#1985]
Being Redone

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27508469-2e3f5eb0-58ab-11e7-94b6-27b259f5b0e5.png)

**Comment by kilt46** [comment]
https://drive.google.com/open?id=0B-UR84lbYzkNUHVfcXhCLUE3WW8
