### ISSUE TITLE
MMCV-General Pedro Jose Mendez International Airport-TAMAULIPAS-MEXICO

### ISSUE THREAD

**Issue by lalomarlin** [InfiniteFlightAirportEditing/Airports#1986]
Being Redone

**Comment by brunocr98** [comment]
You have reached the maximum number of assigned airports.

**Comment by lalomarlin** [comment]
I know

**Comment by brunocr98** [comment]
I'll let you pass this time, but don't break the rule again please :)

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27508863-2721a4e0-58b4-11e7-9101-e29692b22205.png)

**Comment by kilt46** [comment]
https://drive.google.com/open?id=0B-UR84lbYzkNalE3WGI4czlFdDg
