### ISSUE TITLE
KGON-Groton–New London Airport-CONNECTICUT-USA

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Airports#1987]
Part of [Project New England](https://community.infinite-flight.com/t/project-new-england/43169).

**Comment by CptNathanHope** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27665476-f8f71c3a-5c32-11e7-89aa-d3933823085e.png)
