### ISSUE TITLE
EDLK-Krefeld Egelsberg Airport-NORDRHEIN-WESTFALEN-GERMANY

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#199]
Amsterdam

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21085828/e320717a-bfdb-11e6-9b2c-1ca7c8c7cdd9.png)

**Comment by kilt46** [comment]
Airport Misaligned!
![image](https://user-images.githubusercontent.com/14023167/48313954-73728c80-e588-11e8-8d7f-ad429c40d0c5.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56101065-fc01aa00-5ee5-11e9-89f8-cc1cb3dbaffa.png)
