### ISSUE TITLE
LFKF-Figari/Sud Corse Airport-CORSE-FRANCE

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#1990]
Redoing Figari - South Corse Airport.

**Comment by bavAVIA** [comment]
Done. As imagery was slightly outdated there are 4 additional gates and some gate positions visible on charts are only rough. All spawns on the chart are there.

**Comment by kilt46** [comment]
Almost!
![image](https://user-images.githubusercontent.com/14023167/27509261-55828ad4-58be-11e7-9670-03c4ed24947a.png)

**Comment by bavAVIA** [comment]
Commited a fix for gate names on the bottom right and spawns F01 & F02. Can't include the helipads due to imagery yet. I also kept in 21-24 since the currently visible gate lines there would be redundant. I'm tackling this again once new imagery is here, I think it is fine for now.

**Comment by bavAVIA** [comment]
> Commited a fix for gate names on the bottom right and spawns F01 & F02. Can't include the helipads due to imagery yet. I also kept in 21-24 since the currently visible gate lines there would be redundant. I'm tackling this again once new imagery is here, I think it is fine for now.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27517683-d75cc7c2-5995-11e7-803d-c40ed208adec.png)

**Comment by kilt46** [comment]
https://drive.google.com/open?id=0B-UR84lbYzkNRWo5akhXUGtMVm8
