### ISSUE TITLE
VAAH-Sardar Vallabhbhai Patel International Airport-GUJARAT-INDIA

### ISSUE THREAD

**Issue by dushyants19** [InfiniteFlightAirportEditing/Airports#1992]
Sardar Vallabhbhai Patel International, Ahmadabad, India. 
:india:

**Comment by bylrret** [comment]
I'll do this one :)

**Comment by bylrret** [comment]
Adding ramp starts and done :)

**Comment by bylrret** [comment]
Done, sent to review.

**Comment by moritzbabl** [comment]
Added

**Comment by kilt46** [comment]
Please use the following gate configuration.
![image](https://user-images.githubusercontent.com/14023167/28250793-cf31cd3e-6a36-11e7-8a62-2aef48bb183c.png)

**Comment by Blently** [comment]
Send for review

**Comment by dushyants19** [comment]
check in master branch for updated file @kilt46

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28494666-80e56140-6efa-11e7-86de-4c5efc2cacb3.png)

**Comment by Czechoslovaki** [comment]
@hari-shreyas will be reworking this airport.

**Comment by hari-shreyas** [comment]
Thanks! What's the design issue tho?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103028483-7b4dda80-451d-11eb-9d02-a8ed7316ed6f.png)
