### ISSUE TITLE
VGHS

### ISSUE THREAD

**Issue by dushyants19** [InfiniteFlightAirportEditing/Airports#1993]
Shahjalal International, Dhaka, Bangladesh.

Old ICAO: VGZR

**Comment by Aviationluver** [comment]
I will take this one.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27886680-c1beea48-61a2-11e7-90d8-a7c054da24c5.png)
