### ISSUE TITLE
LKKB-Kbely Airport-PRAGUE-CZECH REPUBLIC

### ISSUE THREAD

**Issue by Hornet199** [InfiniteFlightAirportEditing/Airports#1996]
Being redone

**Comment by Hornet199** [comment]
Sent for review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27509321-93e3f794-58bf-11e7-946d-fcb86a0a6156.png)
