### ISSUE TITLE
ORBI-Baghdad International Airport-BAGHDAD-IRAQ

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#2]
Please edit me

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20867220/e7ec3018-ba04-11e6-9f18-4066dd386afd.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22618624/b85128d6-eaa6-11e6-9f94-852205bbd801.png)
