### ISSUE TITLE
EDLS

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#200]
Amsterdam

**Comment by kilt46** [comment]
Double yellow lines everywhere
![image](https://cloud.githubusercontent.com/assets/14023167/16789361/94d61f0a-4872-11e6-89a1-4a104b961ceb.jpeg)

**Comment by IFAEpat** [comment]
Up for grabs guys

**Comment by samuelandersson** [comment]
Temporary fix. Removed as per real life config. Leaving issue open as there's still some things to do.

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/c78ede8702d17526260fe012afc0e5f9e3ddbd2b)

**Comment by PaulNielsen** [comment]
@samuelandersson What is left to do?

**Comment by dushyants19** [comment]
- [ ] Holds Missing/incorrect
- [ ] Lights Leaking
- [ ] Objects not snapped
- [ ] Buildings Missing
- [ ] Many Features incorrect


@PaulNielsen

**Comment by PaulNielsen** [comment]
Ok thanks, I might look into this one tonight!

**Comment by dushyants19** [comment]
Redone in 1e7e14e0a4602cc12a6193c5df79a8e08a482096

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18897056/6f10af86-84ec-11e6-85ac-31d9b6f50cb1.png)
