### ISSUE TITLE
LZOC-Ocova Airport-BANSKA BYSTRICA-SLOVAKIA

### ISSUE THREAD

**Issue by Hornet199** [InfiniteFlightAirportEditing/Airports#2003]
Sent to review
- VERY LAST AIRPORT FROM PROJECT SLOVAKIA

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27497570-eb13fb4e-5820-11e7-9799-a9c3bffcd503.png)
