### ISSUE TITLE
CYKL-Schefferville Airport-QUEBEC-CANADA

### ISSUE THREAD

**Issue by DelsterX** [InfiniteFlightAirportEditing/Airports#2007]

**Comment by brunocr98** [comment]
Please join our team to do this airport. Don't create issues deliberately.

**Comment by DelsterX** [comment]
I have requested through the email. No one is responding for two days.

**Comment by DelsterX** [comment]
Can I be unassigned from this issue it was opened in error. I typed the wrong airport code.

**Comment by charlesw181** [comment]
I'll do this one

**Comment by charlesw181** [comment]
Sent for review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30230437-eab183d4-94ab-11e7-9c80-550ab676f012.png)
