### ISSUE TITLE
CYLW-Kelowna Airport-BRITISH COLUMBIA-CANADA

### ISSUE THREAD

**Issue by DelsterX** [InfiniteFlightAirportEditing/Airports#2008]
Kelowna International Airport. I will do this one.

**Comment by moritzbabl** [comment]
added

**Comment by moritzbabl** [comment]
@DelsterX please accept your invite to the github team

**Comment by kilt46** [comment]
CANNOT DISTINGUISH BUILDINGS
![image](https://user-images.githubusercontent.com/14023167/28999064-f85e0e24-79ff-11e7-838f-9f28dd9207de.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28999069-08ee16e4-7a00-11e7-88dd-223099c3455c.png)

**Comment by kilt46** [comment]
Also gating charts
![image](https://user-images.githubusercontent.com/14023167/28999076-271c8574-7a00-11e7-8b2b-7344689b0b50.png)

**Comment by moritzbabl** [comment]
Added, @DelsterX you still did NOT accept your invite to github!

**Comment by DelsterX** [comment]
I have not received one.

Regards,

Del

On Aug 11, 2017, at 2:26 PM, moritzbabl <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #2008<https://github.com/InfiniteFlightAirportEditing/Airports/issues/2008>.

**Comment by moritzbabl** [comment]
Just sent a new one

**Comment by DelsterX** [comment]
Ok I accepted. But what does this do? I am a github IF member already.

Regards,

Del

On Aug 11, 2017, at 2:33 PM, moritzbabl <notifications@github.com<mailto:notifications@github.com>> wrote:


Just sent a new one

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29441220-48b0c392-838f-11e7-8f61-346fc6773549.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50401492-9a5dda00-0754-11e9-805d-c12128165368.png)
Buildings removed. Duplicate spawn removed
