### ISSUE TITLE
EDLV

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#201]
Amsterdam

**Comment by kilt46** [comment]
Image: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=EDLV

**Comment by JcFl4** [comment]
On Its way! Why are you so impatient!

**Comment by carmichaelalonso** [comment]
@JcFl4 he's just linking to graphical representations of airports (done on many other issues too), not rushing you at all :)

**Comment by JcFl4** [comment]
Oh, ok. But what's the purpose, knowing what the airport looks like?

**Comment by carmichaelalonso** [comment]
Basically yep, he's built an impressive collection: http://kiltmchaggis.com/tikiwiki1/tiki-index.php
Quite useful to see where an airport stands before deciding to take it on :)

**Comment by JcFl4** [comment]
I see. :)

**Comment by kilt46** [comment]
spawn on runway,

**Comment by kilt46** [comment]
Hmm it is now Feb 2015 and this one is yet to be completed!

**Comment by JcFl4** [comment]
Oh I forgot! Now i'm doing OMDB... When I finish I will continue with EDLV. Thanks!

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19417449/0c4513e8-9373-11e6-845b-328fff3a95ae.png)
