### ISSUE TITLE
KMMK-Meriden Markham Municipal Airport-CONNECTICUT-USA

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Airports#2011]
Part of [Project New England](https://community.infinite-flight.com/t/project-new-england/43169).

**Comment by CptNathanHope** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27668528-4d9d75a4-5c47-11e7-8662-f1939abc838e.png)
