### ISSUE TITLE
UTSA-Navoi Airport-NAVOI-UZBEKISTAN

### ISSUE THREAD

**Issue by AsianaIFVA** [InfiniteFlightAirportEditing/Airports#2014]
Please edit this airport

**Comment by dushyants19** [comment]
Hi, we don't take requests. Sorry. Please join the team if you want to get this done. This is also the 3rd issue you are creating for Iranian airports, avoid please.

**Comment by alchonub** [comment]
I'll do it

**Comment by alchonub** [comment]
This Airport isn't even on the X-Plane Database
Sorry but please unassing it

**Comment by brunocr98** [comment]
Up for grabs.

**Comment by ewanfleming** [comment]
I'll do this one from scratch.

**Comment by ewanfleming** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29494512-90937e1e-8571-11e7-83ba-abab38018ad2.png)
