### ISSUE TITLE
LRSB-Sibiu International Airport-SIBIU-ROMANIA

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#2016]
Sibiu Airport, Romania. Being redone.

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
Incorrect parking
![image](https://user-images.githubusercontent.com/14023167/27518745-70890c06-59ac-11e7-8162-a6c33e69c9ee.png)

**Comment by bavAVIA** [comment]
Note the date of the chart. June 22nd, 2017.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27711780-d8b479e2-5ce9-11e7-99f5-c7e01835ceea.png)
