### ISSUE TITLE
KIJD-Windham Airport-CONNECTICUT-USA

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Airports#2017]
Part of [Project New England](https://community.infinite-flight.com/t/project-new-england/43169).

**Comment by CptNathanHope** [comment]
All done! :)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27663614-d4f9cbf2-5c28-11e7-83ae-7e9c4f303202.png)
