### ISSUE TITLE
LEGE-Girona Airport-CATALUNA-SPAIN

### ISSUE THREAD

**Issue by Hornet199** [InfiniteFlightAirportEditing/Airports#2024]
Being redone

**Comment by Hornet199** [comment]
Sent to review

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27865736-5a8e8ebc-6159-11e7-92ab-8816416af9c5.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109083694-01c49b00-76cc-11eb-9ed3-fa3a1c8e0d1a.png)
