### ISSUE TITLE
KPQI-Northern Maine Regional Airport at Presque Isle-MAINE-USA

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Airports#2027]
Part of [Project New England](https://community.infinite-flight.com/t/project-new-england/43169).

**Comment by CptNathanHope** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27885138-8c7f8816-619c-11e7-9e73-a9490a6dc126.png)
