### ISSUE TITLE
KMSN-Dane County Regional Airport-Truax Field-WISCONSIN-USA

### ISSUE THREAD

**Issue by TristinWoolf** [InfiniteFlightAirportEditing/Airports#2028]
Madison, Wisconsin
Part of Priority 3 - US State Capitol
Being redone.

**Comment by osujim15** [comment]
May I redo this airport?

**Comment by brunocr98** [comment]
Hello @osujim15 

We appreciate your cooperation, but please send an email to contact@airportediting.com to get started.

**Comment by osujim15** [comment]
I did. Now may I redo this airport?

**Comment by osujim15** [comment]
Thank you.

**Comment by osujim15** [comment]
I was busy over the past few months. Just to confirm, am I still assigned to this airport?

**Comment by brunocr98** [comment]
No one has unassigned you since Feb 26 of this year. You're fine as long as you're still doing it.

**Comment by osujim15** [comment]
Alright, thanks. I’m still working on it.

**Comment by osujim15** [comment]
![screenshot_kmsn_01](https://user-images.githubusercontent.com/20868324/42414226-32c0c300-81f6-11e8-9870-676897378bde.PNG)

The pavement is almost complete.

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by MrMrMan** [comment]
I'll take this airport! Looking forward to editing it.

**Comment by MrMrMan** [comment]
Still editing this airport. Very extensive. Progress may be slow, but it is steady.

**Comment by MrMrMan** [comment]
Forfeiting this airport. Minimal progress has been made, just updated lengths of runways, positions of windsocks, and ATC frequencies. If you want to take this airport, feel free to DM me on Slack to get the apt.dat so you can get a small head start.

**Comment by Balloonchaser** [comment]
I'll take this over :)

Not getting it in by today but definitely for the next update

**Comment by MajorTomMueller** [comment]
Hey @Balloonchaser, the update you reffered to is a while ago now ...
;-)

**Comment by brunocr98** [comment]
@Balloonchaser, any updates on this airport?

**Comment by danisrils39** [comment]
Sent to OR! :D

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/83929482-1f765c80-a759-11ea-85aa-87c4b2f54eca.png)
