### ISSUE TITLE
KRKD-Knox County Regional Airport-MAINE-USA

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Airports#2029]
Part of [Project New England](https://community.infinite-flight.com/t/project-new-england/43169).

**Comment by CptNathanHope** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28045686-34c7cb68-65a4-11e7-8231-63c388757ebc.png)
