### ISSUE TITLE
EHBK-Maastricht Airport-LIMBURG-NETHERLANDS

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#203]
Amsterdam

**Comment by kilt46** [comment]
EHDK is not a valid reference. Should this be EHBK? (Maastricht)

**Comment by kilt46** [comment]
Started EHBK!!

**Comment by kilt46** [comment]
Maastricht redone

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/11328707/0ed89786-9155-11e5-93a6-879bb45dcea9.png)

**Comment by HenrikBerg02** [comment]
I'll rework this.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18608667/1e405546-7cb5-11e6-9697-e325cb6de552.png)

**Comment by MajorTomMueller** [comment]
https://www.lvnl.nl/eaip/2019-08-01-AIRAC/html/eAIP/EH-AD-2.EHBK-en-GB.html
@Czechoslovaki 
• Missing Cargo Apron
• Extra lines to be removed and missing lines to be added
• Incorrect pavement used for large areas 
• Airport name is incorrect
• Rename ATC frequencies
• Extra buildings to be removed

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/96517785-31036100-122f-11eb-9e06-a254b407e3bf.png)
