### ISSUE TITLE
KAUG-Augusta State Airport-MAINE-USA

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Airports#2030]
Part of [Project New England](https://community.infinite-flight.com/t/project-new-england/43169).

**Comment by bavAVIA** [comment]
Added this to the US Capitals milestone.

**Comment by CptNathanHope** [comment]
Accidentally closed KCON instead of this one. Airport has been redone by me. 

Sorry for the trouble. :)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29251340-de1171cc-8018-11e7-8052-df7e7c542e0e.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38142049-7d3f9288-3400-11e8-8ff5-7c20ae237463.png)

**Comment by kilt46** [comment]
Taxiways reworked. Main Terminal Gate added.
