### ISSUE TITLE
RJOA-Hiroshima Airport-HIROSHIMA-JAPAN

### ISSUE THREAD

**Issue by benlenahan** [InfiniteFlightAirportEditing/Airports#2031]
Hiroshima International, will do it.

**Comment by benlenahan** [comment]
Done!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27862562-6ff753d2-614b-11e7-9899-110e5121852c.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111075820-bb3ab300-84b7-11eb-9ef5-19bbed7ad5f5.png)
