### ISSUE TITLE
LKLT-Letnany Airport-PRAGUE-CZECH REPUBLIC

### ISSUE THREAD

**Issue by Hornet199** [InfiniteFlightAirportEditing/Airports#2032]
Sent to review.

**Comment by moritzbabl** [comment]
added

**Comment by johanneskkl** [comment]
@Hornet199 please leave some airports in CZ for me, I wanted to do a project czech republic.

**Comment by bavAVIA** [comment]
@johanneskkl He was simply faster, I'm afraid. Why not help yourself with a couple swiss airports?

**Comment by Hornet199** [comment]
@johanneskkl Nice to hear that! Still many airports leaving. I am currently working on LKHK, and for the future I will still open only one issue. Are you interested in some special airports or do you want to do everything? I don´t have any priorities.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27812610-acadfcde-6035-11e7-86ea-0c3fe4855dca.png)
