### ISSUE TITLE
KIWA-Phoenix-Mesa Gateway Airport-ARIZONA-USA

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#2033]

**Comment by Blently** [comment]
I'll do this one :)

**Comment by Blently** [comment]
Sent for review

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29228326-f78087b8-7e9e-11e7-9bcb-e24f5577b4aa.png)
