### ISSUE TITLE
KOQU-Quonset State Airport-RHODE ISLAND-USA

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Airports#2034]
Part of [Project New England](https://community.infinite-flight.com/t/project-new-england/43169).

**Comment by CptNathanHope** [comment]
Redone via [`b3a868f`](https://github.com/InfiniteFlightAirportEditing/Airports/commit/b3a868fc9197b8d2cbe9abc53c6f99a55a889326).

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32695230-dcc268be-c71a-11e7-88d8-a438a3555c75.png)
