### ISSUE TITLE
LILE-Biella Cerrione Airport-PIEMONTE-ITALY

### ISSUE THREAD

**Issue by PilotaSbiellato** [InfiniteFlightAirportEditing/Airports#2036]
Biella Cerrione Airport (Italy).
Work by Fall Etto

**Comment by dushyants19** [comment]
Please accept your invitation here: https://github.com/InfiniteFlightAirportEditing/Airports/invitations

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30839071-1b2a1b5c-a235-11e7-9af1-6a38b3048d74.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/69196856-76df1300-0b0e-11ea-9797-d23e372a5b0a.jpg)
