### ISSUE TITLE
CYKZ-Toronto/Buttonville Municipal Airport-ONTARIO-CANADA

### ISSUE THREAD

**Issue by aircanada143** [InfiniteFlightAirportEditing/Airports#2037]
Buttonville Municipal Airport, I can do it :)

**Comment by dushyants19** [comment]
Please accept your invitation here: https://github.com/InfiniteFlightAirportEditing/Airports/invitations

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by aircanada143** [comment]
I can do it, again, sorry about last time had some issues

**Comment by aircanada143** [comment]
Was sent for review :)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32699979-03811086-c784-11e7-8b1e-984f2b1f4e80.png)

**Comment by brunocr98** [comment]
Frequencies will be fixed shortly...
