### ISSUE TITLE
SPTN-Tacna/Coronel FAP Carlos Ciriani Santa Rosa International Airport-TACNA-PERU

### ISSUE THREAD

**Issue by captainKorah** [InfiniteFlightAirportEditing/Airports#2038]
PLEASE RECYCLE

**Comment by moritzbabl** [comment]
Ben Gurion? You mean Tel Aviv Airport? That would be LLBG ( Issue #1206 ) and is already in review

**Comment by brunocr98** [comment]
See issue above. This one is invalid.

**Comment by moritzbabl** [comment]
I'll have an use for that one :)

**Comment by bavAVIA** [comment]
Recycled. Doing this very soon, so **don't take over**.

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27777237-86a8caba-5f76-11e7-9de8-185bd00681a4.png)
