### ISSUE TITLE
EHDL-Arnhem-Deelen Airport-GELDERLAND-NETHERLANDS

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#204]
Amsterdam

**Comment by kilt46** [comment]
Started Work

**Comment by kilt46** [comment]
Airport reworked from scratch

**Comment by kilt46** [comment]
Lines need fixed and tidy
![Uploading image.jpeg…]()

**Comment by kilt46** [comment]
REDO

**Comment by kilt46** [comment]
Airport reworked

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18817854/bf6c957a-8330-11e6-8b0c-67e32908a873.png)
