### ISSUE TITLE
RJFK-Kagoshima Airport-KAGOSHIMA-JAPAN 

### ISSUE THREAD

**Issue by benlenahan** [InfiniteFlightAirportEditing/Airports#2043]
RJFK, I'll do this.

**Comment by benlenahan** [comment]
In for review.

**Comment by moritzbabl** [comment]
Added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28144292-46e8edf8-6730-11e7-8a20-47eef46f35ff.png)

**Comment by ryu12332** [comment]
@orangejuicie is going to fix some sort of gating issue.

**Comment by moritzbabl** [comment]
added
