### ISSUE TITLE
MMMV

### ISSUE THREAD

**Issue by alchonub** [InfiniteFlightAirportEditing/Airports#2044]
Monclova, Mexico

**Comment by alchonub** [comment]
t

**Comment by alchonub** [comment]
Imagery is too bad
Gonna get bak to it when improves

**Comment by dushyants19** [comment]
@lalomarlin interested?

**Comment by lalomarlin** [comment]
Sure, once I get rid of the ones that are assigned 🙂

**Comment by lalomarlin** [comment]
Done, could someone assign it to me please?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28490898-e9906ff0-6eaa-11e7-98fc-737ffb906754.png)
