### ISSUE TITLE
ZLIC-Yinchuan/Hedong Airport-NINGXIA-CHINA

### ISSUE THREAD

**Issue by CNwyang** [InfiniteFlightAirportEditing/Airports#2045]
Yinchuan/Hedong Airport,Yinchuan,China.Will do that.

**Comment by moritzbabl** [comment]
Added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28246846-594abc90-69e9-11e7-8fd9-494b2a2f3e74.png)
