### ISSUE TITLE
SPJR-Cajamarca/Mayor General FAP Armando Revoredo Iglesias Airport-CAJAMARCA-PERU

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#2046]
Quickly doing this. Peru's airports are fun.

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27777093-6ca28562-5f75-11e7-8e4b-c989d07de614.png)
