### ISSUE TITLE
LKHK-Hradec Kralove Airport-KRALOVEHRADECKY-CZECH REPUBLIC

### ISSUE THREAD

**Issue by Hornet199** [InfiniteFlightAirportEditing/Airports#2048]
Being redone

**Comment by Hornet199** [comment]
Sent to review

**Comment by johanneskkl** [comment]
@Hornet199 What's your community name?

**Comment by Hornet199** [comment]
@johanneskkl Hornet199

**Comment by moritzbabl** [comment]
Added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28229778-c2b20742-68a9-11e7-90d4-c2377143c857.png)
