### ISSUE TITLE
WBAK

### ISSUE THREAD

**Issue by alchonub** [InfiniteFlightAirportEditing/Airports#2049]
I'll do it

**Comment by alchonub** [comment]
Sent for Approval

**Comment by brunocr98** [comment]
Issues can only be closed when the airport gets approved by a reviewer.

**Comment by alchonub** [comment]
Sorry.
Won't happen again!

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33914313-3972ee16-df63-11e7-814b-d1b9f096aa84.png)
