### ISSUE TITLE
KANP-Lee Airport-MARYLAND-USA

### ISSUE THREAD

**Issue by alchonub** [InfiniteFlightAirportEditing/Airports#2050]
To finish the U.S. Capitals

**Comment by alchonub** [comment]
Sorry, too busy to do this Airport, Too many spawns for my time

**Comment by brunocr98** [comment]
Up for grabs.

**Comment by American232** [comment]
I will take this one.

**Comment by American232** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30766254-60e089d4-9fb9-11e7-9274-75a0c963a213.png)
