### ISSUE TITLE
YPXM

### ISSUE THREAD

**Issue by alchonub** [InfiniteFlightAirportEditing/Airports#2051]
Ho Ho Ho Island

**Comment by brunocr98** [comment]
Merry Christmas.

**Comment by alchonub** [comment]
Done

**Comment by alchonub** [comment]
Done

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30254219-c13e85aa-965a-11e7-8778-d6804a537b2a.png)
