### ISSUE TITLE
NTGA

### ISSUE THREAD

**Issue by david-garden** [InfiniteFlightAirportEditing/Airports#2052]
RECYCLED

**Comment by alchonub** [comment]
Already Done

**Comment by TristinWoolf** [comment]
Already completed in #1364. If you would like to reuse the issue for another airport, you can.

**Comment by david-garden** [comment]
Yep just realized it thanks guys! I'll see what else has to be done :) I also need to find my way back into the slack chat, if that's still active.

**Comment by alchonub** [comment]
Could I recycle it to make NTGA

**Comment by alchonub** [comment]
Done

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27936197-3658b294-6275-11e7-8d81-63c0bb0e0f5e.png)
