### ISSUE TITLE
MUVT

### ISSUE THREAD

**Issue by cptchris** [InfiniteFlightAirportEditing/Airports#2053]
I'll take this airport

**Comment by dushyants19** [comment]
Accept invite link here: https://github.com/InfiniteFlightAirportEditing/Airports/invitations

**Comment by cptchris** [comment]
Added taxi lines, taxi ways, 2D Terminal, alligned the runway, added hold short lines, added runway centerline lights and threshold lights, added tower view to real worl counterpart, added airport becon.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28756757-43604128-753a-11e7-86ca-84cd458767fd.png)
