### ISSUE TITLE
LIPO-Brescia/Montichiari Airport-LOMBARDIA-ITALY

### ISSUE THREAD

**Issue by TZ2112** [InfiniteFlightAirportEditing/Airports#2054]
Recycled

**Comment by bavAVIA** [comment]
Airport has already been done (https://github.com/InfiniteFlightAirportEditing/Airports/issues/1017)
Please search before opening new issues.

**Comment by moritzbabl** [comment]
Done

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28346652-f8ed56a8-6bf7-11e7-9015-4a3489264501.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68997260-2b650480-0883-11ea-8bf5-02710dc89929.jpg)
