### ISSUE TITLE
KSAF-Santa Fe Municipal Airport-NEW MEXICO-USA

### ISSUE THREAD

**Issue by TZ2112** [InfiniteFlightAirportEditing/Airports#2058]
♻️

**Comment by NickArt1342** [comment]
THIS AIRPORT IS CLOSED AND NO LONGER ACTIVE

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36816759-6e603a92-1ca4-11e8-8d7c-f92746350566.png)
