### ISSUE TITLE
EHGR

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#206]
Amsterdam

**Comment by kilt46** [comment]
Airfield reworked

**Comment by kilt46** [comment]
Runway holds backwards
![image](https://cloud.githubusercontent.com/assets/14023167/16888120/9ba2c846-4aa3-11e6-9464-6c2bb22410dc.jpeg)

**Comment by samuelandersson** [comment]
And changed direction of hold shorts.

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/975b6889903c6615b72aec82283e5dbb37e2a9e2)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18610646/25a3063a-7ce7-11e6-968c-7dd9956fd76a.png)
