### ISSUE TITLE
KWMC-Winnemucca Municipal Airport-NEVADA-USA

### ISSUE THREAD

**Issue by TZ2112** [InfiniteFlightAirportEditing/Airports#2060]
Will make it

**Comment by brunocr98** [comment]
We appreciate your cooperation; however, please join our team by sending an email to airports@liveflightapp.com. Also, please search before creating issues.

**Comment by brunocr98** [comment]
Up for grabs. User banned.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/35471969-d6944aa0-032b-11e8-9697-35e96f20082c.png)
