### ISSUE TITLE
WIBB

### ISSUE THREAD

**Issue by haociek** [InfiniteFlightAirportEditing/Airports#2061]
Sultan Syarif Kasim II Airport, Pekanbaru, Indonesia
will do this

**Comment by moritzbabl** [comment]
Added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28095390-c16dcbf8-6667-11e7-97e7-9efa38083829.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106356155-09f30b80-62c3-11eb-9535-4acc9a71048c.png)
