### ISSUE TITLE
HEAX-Alexandria Airport-ISKANDARIYAH-EGYPT

### ISSUE THREAD

**Issue by TZ2112** [InfiniteFlightAirportEditing/Airports#2062]
reuse

**Comment by brunocr98** [comment]
Up for grabs. User banned.

**Comment by ewanfleming** [comment]
I'll take this one.

**Comment by ewanfleming** [comment]
Sent in for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31918436-482b3304-b822-11e7-815d-5fc32efe9c4e.png)
