### ISSUE TITLE
RJCB-Obihiro Airport-HOKKAIDO-JAPAN

### ISSUE THREAD

**Issue by alchonub** [InfiniteFlightAirportEditing/Airports#2065]
I'll do it

**Comment by alchonub** [comment]
Imagery makes me have a headache, Please unassign me and I'll do it in later September

**Comment by alchonub** [comment]
Completing my word

**Comment by alchonub** [comment]
Sent

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
Missing stands
![image](https://user-images.githubusercontent.com/14023167/31584240-970c73b0-b170-11e7-9a7c-8524b481abfe.png)
Also co-ords of apron slight;ly off!
![image](https://user-images.githubusercontent.com/14023167/31584244-a86340a8-b170-11e7-9611-cad70047e6fe.png)

**Comment by alchonub** [comment]
The coordinates are good for me but I haven’t put the GA gates

**Comment by alchonub** [comment]
fixed, again

**Comment by dushyants19** [comment]
Issue fixed

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32992100-214c4382-cd0c-11e7-9d5a-fb59f09c74ea.png)
