### ISSUE TITLE
MUPR

### ISSUE THREAD

**Issue by cptchris** [InfiniteFlightAirportEditing/Airports#2067]
I'll start on pinar del rio airport, MUPR.

**Comment by cptchris** [comment]
All done, added taxi ways, hold short lines, taxi way edge lines, taxi lines, GA gates, added airport beacon, added boundarys.

**Comment by cptchris** [comment]
Sent it in for review :) :) :)

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29434770-0412320e-836a-11e7-9899-59176e9a49f9.png)
