### ISSUE TITLE
KOKC-Will Rogers World Airport-OKLAHOMA-USA

### ISSUE THREAD

**Issue by sumith11** [InfiniteFlightAirportEditing/Airports#2068]
Working on this one.

**Comment by sumith01** [comment]
I'm sorry I can't continue on this anymore. I've been busy with college lately :(

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34260793-a355badc-e62c-11e7-86c1-477a44a7e5fd.png)
