### ISSUE TITLE
CYCD 

### ISSUE THREAD

**Issue by DelsterX** [InfiniteFlightAirportEditing/Airports#2069]
I will work on this one.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28845089-82c291de-76cc-11e7-812e-16cf8a52388b.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50502510-6b31bc00-0a25-11e9-955c-7fda1b4658bd.png)
