### ISSUE TITLE
EHKD

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#207]

**Comment by kilt46** [comment]
I updated this yesterday and submitted to Cameron. Additional terminal buildings added.

**Comment by kilt46** [comment]
This is complete

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20040219/187d38fa-a419-11e6-8462-88ac2a593418.png)
