### ISSUE TITLE
CYYF

### ISSUE THREAD

**Issue by DelsterX** [InfiniteFlightAirportEditing/Airports#2070]
I will work on this airport.

**Comment by bavAVIA** [comment]
You are already assigned to three other issues, which is the max. for any editor. Please wait until your other airports have been approved and you have a free spot before creating more issues.
Labelling this as suggestion for now.

Check latest post on #announcements on Slack for reference.
Happy editing.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28895167-f3a8d1e4-779c-11e7-9b39-29d51731033c.png)

**Comment by kilt46** [comment]
Duplicate spawns fixed, buildings removed
