### ISSUE TITLE
LGRP

### ISSUE THREAD

**Issue by TZ2112** [InfiniteFlightAirportEditing/Airports#2072]
I will make it

**Comment by huddys7** [comment]
Need help?

**Comment by brunocr98** [comment]
Up for grabs. User banned.

**Comment by moritzbabl** [comment]
done

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28395966-da496018-6cbd-11e7-97d7-3d2a5adad09b.png)
