### ISSUE TITLE
ZMUB

### ISSUE THREAD

**Issue by ewanfleming** [InfiniteFlightAirportEditing/Airports#2074]
Will do Chinggis Khan Intl, Mongolia. Apparently has a runway of 10171 feet so would go under the Global Priority 2 category.

**Comment by ewanfleming** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28809610-fe8660ee-7649-11e7-9968-b65e940ff6e7.png)
