### ISSUE TITLE
WAGG-Tjilik Riwut Airport-KALIMANTAN TENGAH-INDONESIA

### ISSUE THREAD

**Issue by haociek** [InfiniteFlightAirportEditing/Airports#2079]
Tjilik Riwut Airport, Palangkaraya, Indonesia
will do this.....

**Comment by moritzbabl** [comment]
Added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28248151-3d1b6d82-6a05-11e7-8277-80018114359f.png)

**Comment by MajorTomMueller** [comment]
new APRON

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90322921-f116b980-df1f-11ea-8a73-8d49d0f03d27.png)
