### ISSUE TITLE
EHLE

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#208]
Amsterdam

**Comment by Misha16** [comment]
I think I will try this one for my first attempt. Is that alright?

**Comment by jpperks** [comment]
That's fine. Once you have selected an airport, change the label to "Being Redone". I'll do it this time for you :)

**Comment by Misha16** [comment]
Will do ((:

**Comment by Misha16** [comment]
Whoops. I didn't mean to do whatever I just did. trying to change it do done

**Comment by dushyants19** [comment]
Are you doing this Misha?

**Comment by kilt46** [comment]
This airport seems to be in order. Names fixed and PAPIs fixed

**Comment by dushyants19** [comment]
Just some changes to the parking spots' names.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20862475/385c2fe2-b971-11e6-8793-04d218aabdb7.png)
