### ISSUE TITLE
LGZA

### ISSUE THREAD

**Issue by TZ2112** [InfiniteFlightAirportEditing/Airports#2080]
Will do it

**Comment by TZ2112** [comment]
finished

**Comment by brunocr98** [comment]
Issues only are closed when the reviewer approves the airport.

**Comment by moritzbabl** [comment]
Up for grabs

**Comment by moritzbabl** [comment]
done

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28481113-37bbcfbc-6e29-11e7-9eac-604a82f7cc47.png)
