### ISSUE TITLE
DBBB-Cardinal Bernardin Gantin Airport-LITTORAL-BENIN

### ISSUE THREAD

**Issue by TZ2112** [InfiniteFlightAirportEditing/Airports#2081]
Mine

**Comment by TZ2112** [comment]
Won't make it anymore

**Comment by bavAVIA** [comment]
Again, do not close issues. Never.
They will always be closed for you when needed.

Also, perhaps think about your airport choice and do a bit of research before making an issue and letting yourself be unassigned 4 hours later. This is not how it works, we have enough suggestions.

**Comment by skotshi** [comment]
I can take it

**Comment by brunocr98** [comment]
Hi @skotshi,

Thank you for your help, but please send an email to contact@airportediting.com to get started.

**Comment by skotshi** [comment]
I already applied for the airport editing team. I'm about to finifh the taxilines now. I just have to set the spawns and I think I'll be ready then

**Comment by skotshi** [comment]
Done! I can't add some gates because the satelite picture is too dark

**Comment by moritzbabl** [comment]
member inactive, up for grabs

**Comment by johanneskkl** [comment]
I will do that

**Comment by johanneskkl** [comment]
sent in. 
I will be in Vienna a few days so I won´t be able to edit

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/41076231-36748550-69d6-11e8-9b3b-0b562c490eaa.png)

**Comment by kilt46** [comment]
Suggested gating chart
![image](https://user-images.githubusercontent.com/14023167/41076269-6c74f928-69d6-11e8-92af-99ddce67c4a3.png)

**Comment by johanneskkl** [comment]
After renaming gates, should I resend it to review?

**Comment by brunocr98** [comment]
It’s obvious when you’re asked to correct something after official review, you must resubmit again.

**Comment by johanneskkl** [comment]
@brunocr98 , @kilt46 provide me the imagery that shows the gates as in charts and I will correct it.
I am unable to find it, and honestly I don´t like blind editing

**Comment by johanneskkl** [comment]
@kilt46 your charts are outdated(2015)
![grafik](https://user-images.githubusercontent.com/22429067/45975998-d7c3a600-c045-11e8-9715-766bb674abfa.png)
while this is what is shown after 2016 (My AP version)
![grafik](https://user-images.githubusercontent.com/22429067/45976018-f1fd8400-c045-11e8-87c7-86bbf6113c8d.png)

**Comment by kilt46** [comment]
Buildings removed
![image](https://user-images.githubusercontent.com/14023167/46244877-37ee7b00-c3ab-11e8-8c9c-b9bba170970d.png)

**Comment by brennanhackard** [comment]
Apron markings need to be updated. The entire layout has changed. 

Opening this up to anyone who wants it.

**Comment by suhasjatla** [comment]
I'd like to take this, please.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114270577-c4de0a80-99d2-11eb-8eb0-03c76138d7ff.png)
