### ISSUE TITLE
OMRK-Ras Al Khaimah Airport-RAS AL KHAYMAH-UNITED ARAB EMIRATES

### ISSUE THREAD

**Issue by TZ2112** [InfiniteFlightAirportEditing/Airports#2082]
Will makeit

**Comment by brunocr98** [comment]
Cannot assign you. You have **5** airports right now. Finish 3 of them to assigned to this one.

**Comment by TZ2112** [comment]
I am finished. Send the data now.

**Comment by alchonub** [comment]
Can do it

**Comment by alchonub** [comment]
Can’t because of Finals

**Comment by brunocr98** [comment]
grabs.

**Comment by dushyants19** [comment]
will do

**Comment by kilt46** [comment]
Gate 11 added
![image](https://user-images.githubusercontent.com/14023167/33805207-946c2f7a-dd7a-11e7-92e8-83dc11166a90.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33805214-b0fe67a2-dd7a-11e7-9223-031e5df89b39.png)
