### ISSUE TITLE
KADW-Joint Base Andrews Airport-MARYLAND-USA

### ISSUE THREAD

**Issue by DelsterX** [InfiniteFlightAirportEditing/Airports#2087]
Recycled
New Airport: Andrews AFB

**Comment by dushyants19** [comment]
Continue on #2087

**Comment by moritzbabl** [comment]
done

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29643659-1ff6a0ec-8836-11e7-9861-36ba6fdf16ae.png)
