### ISSUE TITLE
VEGT-Guwahati Airport-ASSAM-INDIA

### ISSUE THREAD

**Issue by sumith11** [InfiniteFlightAirportEditing/Airports#2088]
Working on this one.

**Comment by ryu12332** [comment]
Progress?

**Comment by moritzbabl** [comment]
member inactive, up for grabs

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42541787-800d962c-8469-11e8-9500-528cf9350b26.png)
