### ISSUE TITLE
KORF-Norfolk International Airport-VIRGINIA-USA

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#2089]
Redoing Norfolk Intl, VA.

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29251383-58624352-8019-11e7-9bf0-b784ece02b88.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53697200-91146d80-3d94-11e9-9cb0-7fe2875b8fb6.png)
