### ISSUE TITLE
LEBB-Bilbao Airport-PAIS VASCO-SPAIN

### ISSUE THREAD

**Issue by Florian18** [InfiniteFlightAirportEditing/Airports#2090]
Hey Github,

this will be my first airport.

**Comment by bavAVIA** [comment]
No it won't.
Unfortunately, this airport has already been done. Please use the search function to look for already done airports before creating new issues in the future. Thank you.

**Comment by Florian18** [comment]
But some Gate stands are too large and false and there aren't all stands for Class A

**Comment by moritzbabl** [comment]
@Florian18 Did you send a mail to airports@liveflightapp.com about ten minutes ago?

**Comment by brunocr98** [comment]
@florian18 please send an email to airports@liveflightapp.com to get started.

**Comment by Florian18** [comment]
Yes that's me

**Comment by Florian18** [comment]
No, I am his older brother!

**Comment by moritzbabl** [comment]
You are a very nice brother considering he wanted to do rhodes but you created an issue now...

**Comment by Florian18** [comment]
He deletes his account, he is a bit unhappy, because no airport is accepted, but he is very young and he will help me!

**Comment by Florian18** [comment]
He hasn't started with it, he sais, so we will make it too.

**Comment by Florian18** [comment]
I doesn't have an overview. He tried to many airports

**Comment by moritzbabl** [comment]
So you use the email of your younger brother who is now officially banned from airport editing? Or is your name the same as the name of your brother with the little difference that the last letter of your surnames are different? ok ^^

**Comment by Florian18** [comment]
He hasn't an own til now and now I tried this.

**Comment by Florian18** [comment]
How will we continue?

**Comment by brunocr98** [comment]
You guys won't. Enough circus shows around here.

**Comment by TristinWoolf** [comment]
I'm sorry but you aren't making any sense. Please take the proper steps to join the team, just like everyone else does, or don't waste our time. Thank you.

**Comment by ewanfleming** [comment]
Not funny or necessary at all. We don't want any funny business around here. We have a reputation to protect.

**Comment by moritzbabl** [comment]
Ok, "Timon's brother", you are "both" banned and blocked from this organization. You can send a pic of you two and your IDs with everything censored but your names and birthdays and I'll add the older one of you to the team. Of course the images will be handled as confidential as possible.

IF Airport Editing Supervisor

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
A few spots missing #4 and #19 for example
![image](https://user-images.githubusercontent.com/14023167/28499542-fd9fb6e4-6f7d-11e7-83ea-197f0fab8894.png)

**Comment by bavAVIA** [comment]
Those spawns were all included. Most probably commited an incorrect version of the airport.
Re-commited the apt.dat, should be fixed now.

**Comment by kilt46** [comment]
Please reload data- I am getting an error with this file
![image](https://user-images.githubusercontent.com/14023167/28551111-5cd0faf0-70ab-11e7-94c6-cc01854e3c83.png)

**Comment by bavAVIA** [comment]
Re-committed another time, but exported in a new scenery pack. I honestly don't know what to do, I could import it to a new scenery package trouble-free.

**Comment by kilt46** [comment]
Reimported with header from a different file   :)
![image](https://user-images.githubusercontent.com/14023167/28597038-61677056-7161-11e7-9a94-6dbde5265b41.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108781960-5af7c780-7530-11eb-85ec-5a16c7c71f00.png)
