### ISSUE TITLE
LEGR-Granada-Jaen Airport-ANDALUCIA-SPAIN

### ISSUE THREAD

**Issue by Florian18** [InfiniteFlightAirportEditing/Airports#2091]

**Comment by bavAVIA** [comment]
This was a nice airport actually. Certainly doing this when I have a free spot.

**Comment by ewanfleming** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29190266-101d5a5a-7ddf-11e7-8263-cd31084d8797.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109387867-4e28fa00-78c9-11eb-9626-b2323999f3b5.png)
