### ISSUE TITLE
RJTH-Hachijojima Airport-TOKYO-JAPAN

### ISSUE THREAD

**Issue by Ksisky** [InfiniteFlightAirportEditing/Airports#2092]
♻️

**Comment by Ksisky** [comment]
Tagging @CptNathanHope for Project New England

**Comment by CptNathanHope** [comment]
♻️

**Comment by benlenahan** [comment]
Sent in for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36704939-4790713e-1b28-11e8-8cd7-dd0832408040.png)
