### ISSUE TITLE
RCBS-Kinmen Airport-FUJIAN-TAIWAN

### ISSUE THREAD

**Issue by Yifan081** [InfiniteFlightAirportEditing/Airports#2094]
Will do this one

**Comment by brunocr98** [comment]
It's not located in Taiwan.

https://en.wikipedia.org/wiki/Kinmen_Airport

**Comment by bavAVIA** [comment]
Of course it is. Kinmen County is an island exclave of the Republic of China (=Taiwan).

**Comment by Yifan081** [comment]
Sent for review

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28730344-643aff24-7395-11e7-8605-ab14f6bf5553.png)
