### ISSUE TITLE
LICB-Comiso Airport-SICILIA-ITALY

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#2095]

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28499564-93455370-6f7e-11e7-97aa-cd77781e488b.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/70487732-1c195580-1ad5-11ea-891f-3eb720f5a6e0.jpg)
