### ISSUE TITLE
EGHE-Scilly Isles/St Mary's Airport-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by ewanfleming** [InfiniteFlightAirportEditing/Airports#2097]
I'll do St Mary's Airport, Isles of Scilly. Tiny project.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28732225-b7a88e5e-739c-11e7-8baa-f13e5f8501df.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/79644889-3b5e7880-8182-11ea-9639-06a2808aa019.jpg)
