### ISSUE TITLE
NZOH-RNZAF Base Ohakea-MANAWATU-WANGANUI-NEW ZEALAND

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#2098]
would like to do this one next

**Comment by MajorTomMueller** [comment]
send to airports@liveflightapp.com

**Comment by MajorTomMueller** [comment]
![nzoh-overview](https://user-images.githubusercontent.com/26853210/28474746-0713da96-6e4a-11e7-87d1-ca0c3e1a936d.jpeg)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28494078-4d57dcba-6ee9-11e7-9fb1-29bb9beaf283.png)

**Comment by MajorTomMueller** [comment]
boundary

**Comment by MajorTomMueller** [comment]
- Boundary Fix
- Buildings removed
- Hangar Floors added
- Markings added to Hangars
-minor adjustments to few spawns

**Comment by MajorTomMueller** [comment]
- Hangar Floors changed

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46589692-4a834700-ca72-11e8-8f10-38846428464e.png)
