### ISSUE TITLE
TNCM-Princess Juliana International Airport-SINT MAARTIN-ANGUILLA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#21]

**Comment by Swang007** [comment]
Will add ATIS frequency

**Comment by Swang007** [comment]
TNCM does not have an ATIS frequency.

**Comment by dushyants19** [comment]
Airport boundary increased it seems, will fix

**Comment by dushyants19** [comment]
Done

**Comment by kilt46** [comment]
Replaced apron with one slab
![image](https://cloud.githubusercontent.com/assets/14023167/15467564/d0a0641e-20a4-11e6-955e-b19cd97e609d.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20641105/99ccd166-b3b6-11e6-9bc2-3212d41c8c8b.png)

**Comment by Balloonchaser** [comment]
Submitted to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52166192-a7fd6c80-26cf-11e9-85fb-b8076c7234cb.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/76170469-ea11a100-6160-11ea-956a-8afa13ea07ac.jpg)
