### ISSUE TITLE
EHWO-Woensdrecht-NOORD-BRABANT-NETHERLANDS

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#210]
Amsterdam

**Comment by JohnPreston21** [comment]
Will begin this one. may be a complete redesign

**Comment by kilt46** [comment]
Started

**Comment by kilt46** [comment]
Airfield done from scratch

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21503627/8da9235a-cc1e-11e6-8c7e-fdd2b628ecb3.png)
