### ISSUE TITLE
WAKK-Mopah Airport-PAPUA-INDONESIA

### ISSUE THREAD

**Issue by haociek** [InfiniteFlightAirportEditing/Airports#2102]
Mopah Airport, Merauke, Indonesia
will do this

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29740907-6c088084-8a27-11e7-85f8-543b046909e4.png)

**Comment by MajorTomMueller** [comment]
https://aimindonesia.dephub.go.id/images/148-WAKK%20AD%202-1%20to%20AD%202-8.pdf

Chart
https://aimindonesia.dephub.go.id/images/552-WAKK%20AD%202.24-1%20ADC.pdf

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/83695656-1d2cca80-a5c0-11ea-92fc-df286350425f.png)
