### ISSUE TITLE
MUVR

### ISSUE THREAD

**Issue by cptchris** [InfiniteFlightAirportEditing/Airports#2103]
I'll take this one.

**Comment by cptchris** [comment]
Has been approved and added to the repository

**Comment by dushyants19** [comment]
Not added to the repository yet ;)

**Comment by cptchris** [comment]
Oh lol, well it has been approved!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28798295-ae88b474-7609-11e7-98ce-2eb3d93f64e3.png)
