### ISSUE TITLE
2N2-Newfound Valley Airport-NEW HAMPSHIRE-USA

### ISSUE THREAD

**Issue by Theyoshifan200** [InfiniteFlightAirportEditing/Airports#2104]
Decided to come back to Airport Editing, I already finished this very simple airport

Would like to do this very simple airport
<img width="247" alt="screen shot 2017-07-17 at 12 33 21 am" src="https://user-images.githubusercontent.com/21222414/28255912-dc21cd7e-6a8a-11e7-9145-24a5efa0b88e.png">
<img width="449" alt="screen shot 2017-07-17 at 12 33 37 am" src="https://user-images.githubusercontent.com/21222414/28255914-dfa65474-6a8a-11e7-827a-db91f8467ee1.png">

**Comment by Theyoshifan200** [comment]
I’ll submit this later today, as I’m at work just so you know :)

**Comment by Theyoshifan200** [comment]
This airport has been submitted for review!

**Comment by CptNathanHope** [comment]
Welcome back @Theyoshifan200! Since this airport is in New England, I've added it the list of airports for _[Project New England](https://community.infinite-flight.com/t/project-new-england/43169)._

Thanks for your contribution! :)

**Comment by Theyoshifan200** [comment]
Thanks! Though I will try to work on airports, it’s very hard because I
have a job and I have chores to do, sorry if I’ve been gone for a very long
time. I didn’t quit the team, I just had lots to do

**Comment by dushyants19** [comment]
Please contact us at airports@liveflightapp,com. You cannot just bluntly join after a period of inactivity and continue doing airports. Do tell us the airports you have been working on in the mail.

Dush

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by Theyoshifan200** [comment]
I fixed it up, but I never had the time to send The updates files in, life
and work got in the way. I hope someone can take this, it’s a relatively
easy private airstrip.

**Comment by dushyants19** [comment]
http://www.airnav.com/airport/2N2

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31045640-e458d2b8-a5ad-11e7-8c83-c843429c9fb4.png)
