### ISSUE TITLE
KMCD

### ISSUE THREAD

**Issue by BrandonKreuter** [InfiniteFlightAirportEditing/Airports#2106]
Ill take Mackinac Island. This is my practice. Wish me luck :)

**Comment by brunocr98** [comment]
Good luck Brandon ;)

**Comment by ryu12332** [comment]
Part of Project Michigan.

**Comment by BrandonKreuter** [comment]
Sent in for Review

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33069455-39e3664a-ce7a-11e7-98bb-0f519798193c.png)
