### ISSUE TITLE
ETHE

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#211]
Amsterdam

**Comment by kilt46** [comment]
Starting work on this

**Comment by kilt46** [comment]
Completely redone. WEDBING had this site hidden. Used Google Maps instead!

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20548127/5d44219a-b0e6-11e6-869b-ff2264db2fb4.png)
