### ISSUE TITLE
LTCE-Erzurum International Airport-ERZURUM-TURKEY

### ISSUE THREAD

**Issue by Alhammadi1963** [InfiniteFlightAirportEditing/Airports#2110]
PLEASE RECYCLE ME ♻️

**Comment by dushyants19** [comment]
Bahrain is already done. Please search before posting #722

**Comment by American232** [comment]
I will take this one.

**Comment by American232** [comment]
Submitted via email.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30997802-e3fddae4-a48f-11e7-98f7-cb55aed457ed.png)
