### ISSUE TITLE
KBFA

### ISSUE THREAD

**Issue by BrandonKreuter** [InfiniteFlightAirportEditing/Airports#2111]
Ill take Boyne Mountain Airport. Just finishing up KMCD :) Joining Project Michigan

**Comment by ryu12332** [comment]
Part of Project Michigan.

**Comment by BrandonKreuter** [comment]
Sent in for Review

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28732766-cf1d7822-739e-11e7-8c2c-4973fae82f59.png)
