### ISSUE TITLE
ETHM

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#212]
Amsterdam

**Comment by AxelBeder** [comment]
Wrong airport. Oops/

**Comment by kilt46** [comment]
Started work

**Comment by kilt46** [comment]
Was created as a default airport. This one has been completely redone

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33801633-6db7070a-dd26-11e7-8bf1-a71368dd88bd.png)
