### ISSUE TITLE
RORE-Iejima Airport-OKINAWA-JAPAN

### ISSUE THREAD

**Issue by 1ofthe3amegos** [InfiniteFlightAirportEditing/Airports#2120]
♻️

**Comment by brunocr98** [comment]
Up for grabs.

**Comment by reedgreat** [comment]
Ill do it :D

**Comment by brunocr98** [comment]
@reedgreat, message an admin your GitHub username, so he can send you an invite to cooperate in the repo, thanks! :)

**Comment by 1ofthe3amegos** [comment]
Thanks for taking this @reedgreat!

**Comment by reedgreat** [comment]
Np @1ofthe3amegos .  It's been a great airport to do as my first project.  It's got a bit of everything :)

**Comment by CptNathanHope** [comment]
♻️

**Comment by reedgreat** [comment]
I was actually most of the way done with it, I just never followed through.  To the person who works on this in the future, if you want the mostly completed version I was doing, just reply to my comment and I'll attach it.

**Comment by benlenahan** [comment]
The airport issue has been recycled. It is no Ocala International but rather Iejima Airport in Japan. If you still have the airport and still wish to continue with it, I can always go to another, not active issue.

**Comment by reedgreat** [comment]
No don’t worry about it, you don’t need to go to the trouble :)

Thanks anyway

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36702653-93db9b00-1b1d-11e8-8b36-b5b9b17cbb43.png)
