### ISSUE TITLE
VOPB

### ISSUE THREAD

**Issue by dushyants19** [InfiniteFlightAirportEditing/Airports#2123]
Port Blair, India.

https://en.wikipedia.org/wiki/Veer_Savarkar_International_Airport

10k

**Comment by American232** [comment]
I will take this one.

**Comment by American232** [comment]
Sent in for review via email.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29737603-550ab0e2-89d6-11e7-82c3-308bb7c61cbb.png)
