### ISSUE TITLE
VGSY-Osmani International Sylhet Airport-SYLHET-BANGLADESH

### ISSUE THREAD

**Issue by Tamz00** [InfiniteFlightAirportEditing/Airports#2126]
Syhlet Osmani International (ZYL), I'll take it (and my first one)

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
Please check gate format as per below
![image](https://user-images.githubusercontent.com/14023167/29494434-e54e3a86-856f-11e7-82ae-5b52e4156abe.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30673088-3438c6d2-9e36-11e7-803e-27225ff5f09a.png)
