### ISSUE TITLE
LFMK-Carcassonne Airport-LANGUEDOC-ROUSSILLON-FRANCE

### ISSUE THREAD

**Issue by DelsterX** [InfiniteFlightAirportEditing/Airports#2127]
I got this one.

♻️ by dush and not brunobbc

**Comment by bavAVIA** [comment]
Airport was already done (check https://github.com/InfiniteFlightAirportEditing/Airports/issues/1016 for reference). Please search for already existing issues before creating new ones in the future, 

Thanks for your work!

**Comment by dushyants19** [comment]
Already done. Check #1016

**Comment by bavAVIA** [comment]
recycled and assigned. always gotta be bavarian efficiency.

**Comment by DelsterX** [comment]
Strange. I did a search for it and it didn't come up.

Regards,

Del

On Jul 25, 2017, at 12:18 PM, Dushyanth <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #2127<https://github.com/InfiniteFlightAirportEditing/Airports/issues/2127>.

**Comment by bavAVIA** [comment]
Done. Edit deviates from current real life layout as satellite imagery was not updated yet in any case.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29489510-5c7afad2-84e8-11e7-838a-8883f0fb5ca7.png)
