### ISSUE TITLE
CYXX-Abbotsford Airport-BRITISH COLUMBIA-CANADA

### ISSUE THREAD

**Issue by DelsterX** [InfiniteFlightAirportEditing/Airports#2128]
I will redo this one.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29476378-6211648c-8429-11e7-9501-dda3bdd97fdf.png)

**Comment by kilt46** [comment]
spawn duplicates fix

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50573235-b6d1c600-0d95-11e9-8583-99cd8d7aadff.png)

**Comment by RyanEpps** [comment]
Taxiways misaligned.

**Comment by DelsterX** [comment]
I will fix this.

**Comment by DelsterX** [comment]
Looked at the file and it appears to be fine. But not in IF looks like the runway moved to the east.

**Comment by DelsterX** [comment]
![image](https://user-images.githubusercontent.com/29551957/83430743-0a14d180-a3eb-11ea-97b7-891028412ca9.png)

**Comment by MajorTomMueller** [comment]
did you @moritzbabl

**Comment by ECoops-123** [comment]
> did you @moritzbabl

It was corrected a while back. This issue hasn't been closed though.

**Comment by brunocr1050** [comment]
If this issue was corrected, I'll close the issue.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104129869-c183a600-5333-11eb-8500-f4ba61b65b1d.png)
