### ISSUE TITLE
ETNG

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#213]
Amsterdam

**Comment by dushyants19** [comment]
I will do it

**Comment by dushyants19** [comment]
Finished, Approved by Jonathan :+1:

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17277420/ec165f0c-5707-11e6-8457-ac0e0fecfa6c.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17277452/c894b906-5708-11e6-8b7b-57d35d777efd.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17651685/d52e7f56-6231-11e6-812b-ace43c8506f2.png)
