### ISSUE TITLE
CYXS-Prince George Airport-BRITISH COLUMBIA-CANADA

### ISSUE THREAD

**Issue by DelsterX** [InfiniteFlightAirportEditing/Airports#2133]
I will work on this one.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29437904-1e894e60-8379-11e7-9f61-e118f66d19b5.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52952349-e2ab0a00-3349-11e9-92f2-ce83b17464ea.png)
