### ISSUE TITLE
TJIG-Isla Grande Airport-PUERTO RICO-PUERTO RICO

### ISSUE THREAD

**Issue by Blently** [InfiniteFlightAirportEditing/Airports#2137]
Small airport west of TJSJ. I'll redo this one as I'm almost finished with KIWA.

**Comment by Blently** [comment]
Sent for review

**Comment by kilt46** [comment]
Maybe some spawns missing
![image](https://user-images.githubusercontent.com/14023167/29227694-7b695594-7e9c-11e7-8e51-b47f3518646f.png)
Probably should show terminal gates
![image](https://user-images.githubusercontent.com/14023167/29227718-9790edcc-7e9c-11e7-9c70-2a817678838c.png)

**Comment by Blently** [comment]
Sent for review

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29490096-a63cfdf0-84f7-11e7-82be-a43bb7f9e2b4.png)
