### ISSUE TITLE
LYBE

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#2138]
Nikola Tesla Int'l airport. I will take this one.

Runway is longer than 10k feet.

**Comment by dushyants19** [comment]
Wow nice name to honor the great person!

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28994593-8a13bee0-7997-11e7-9227-83cf6d2d9dc5.png)
