### ISSUE TITLE
ENCN-Kjevik Airport-VEST-AGDER-NORWAY

### ISSUE THREAD

**Issue by ewanfleming** [InfiniteFlightAirportEditing/Airports#2139]
Will do Kristiansand Airport, Kjevik. Am on holiday ATM so will start this on Monday/Tuesday.

**Comment by ewanfleming** [comment]
Sent in for review.

**Comment by moritzbabl** [comment]
Added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29001593-159d58ce-7a54-11e7-8b25-bfc1b28b8807.png)

**Comment by orangejuicie** [comment]
I take it.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/65000239-3b7f5880-d8c1-11e9-9b21-c377620c1854.jpg)
