### ISSUE TITLE
MUGM-Guantanamo Leeward Point Airport-GUANTANAMO-CUBA

### ISSUE THREAD

**Issue by cptchris** [InfiniteFlightAirportEditing/Airports#2141]
I'll do this one.

**Comment by cptchris** [comment]
Sent in for submission

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28797839-48ac37ee-7608-11e7-9287-b9205b1f0969.png)
