### ISSUE TITLE
ZWWW-Urumqi/Diwopu Airport-XINJIANG UYGUR-CHINA

### ISSUE THREAD

**Issue by CNwyang** [InfiniteFlightAirportEditing/Airports#2142]
being redone

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30351286-411c704e-97e0-11e7-9557-0f825ff7acc9.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50743115-9fea0400-11d9-11e9-9969-d4767340d259.png)
