### ISSUE TITLE
MUSA-San Antonio de los Banos Airport-LA HABANA-CUBA

### ISSUE THREAD

**Issue by cptchris** [InfiniteFlightAirportEditing/Airports#2143]
I'll take this one.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
This is a military base. The spawn points must be incorrect
https://en.wikipedia.org/wiki/San_Antonio_de_los_Ba%C3%B1os_Airfield
Military pads also missing
![image](https://user-images.githubusercontent.com/14023167/29390197-713e248e-82b4-11e7-8ef7-602dcdb422af.png)

**Comment by brunocr98** [comment]
@cptchris you're still working on this airport right? We just want to know how's the progress.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42976642-5bf0eb56-8b88-11e8-8b40-b30d85cc2f16.png)
