### ISSUE TITLE
ETSK-Kaufbeuren Air Base-BAYERN-GERMANY

### ISSUE THREAD

**Issue by cptchris** [InfiniteFlightAirportEditing/Airports#2144]
Recycled

**Comment by cptchris** [comment]
Nevermind, this airport is not in the github database.

**Comment by brunocr98** [comment]
You can actually do the airport, as long as you gather enough information to do it. Just say in the email that the airport is not in the database, and the reviewer will just add it.

**Comment by cptchris** [comment]
Can someone unassign me, And put a suggestion label? I will do this later down the road when im finished with the rest of project cuba but not now.

**Comment by cptchris** [comment]
Someone please unassign me :).

**Comment by moritzbabl** [comment]
done

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33801610-d7516472-dd25-11e7-930f-1b3fb7a770c3.png)
