### ISSUE TITLE
KGSO-Piedmont Triad International Airport-NORTH CAROLINA-USA

### ISSUE THREAD

**Issue by insertusernameh3r3** [InfiniteFlightAirportEditing/Airports#2147]
RECYCLED ♻️

**Comment by brunocr98** [comment]
Up for grabs.

**Comment by henrikbg** [comment]
Duplicate issue.

**Comment by johanneskkl** [comment]
I will take this one

**Comment by johanneskkl** [comment]
sent for review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38524519-7d92aede-3c14-11e8-80e8-afa73114bdcd.png)

**Comment by kilt46** [comment]
Taxiway Missing!!
![image](https://user-images.githubusercontent.com/14023167/38527388-0dc5f0dc-3c20-11e8-9a64-438bfa93e795.png)

**Comment by kilt46** [comment]
Also check out Gates 21-23-25
![image](https://user-images.githubusercontent.com/14023167/38527449-6a103bae-3c20-11e8-9955-b63a8aa56948.png)

**Comment by moritzbabl** [comment]
re-added
