### ISSUE TITLE
LWSK

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#2148]
Skopje Int'l Airport. I will be taking this one.

Runway is not longer than 10k feet.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29006494-f24dc062-7ab6-11e7-906a-c9f47fb8e512.png)
