### ISSUE TITLE
ETSB

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#215]
Amsterdam

**Comment by kilt46** [comment]
This was a bare bones airport. It has now been fully redone

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17277637/4f41047e-570d-11e6-9859-6609a13db6c2.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17643149/811fc9f8-6126-11e6-883f-dbd24382a98e.png)
