### ISSUE TITLE
SLSU

### ISSUE THREAD

**Issue by MoisesIriarte** [InfiniteFlightAirportEditing/Airports#2150]
Juana Azurduy de Padilla Airport in Bolivia, to be edited by me.

**Comment by MoisesIriarte** [comment]
Sent for review via email

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29490876-e489fcda-850f-11e7-9549-da278a774ddf.png)
