### ISSUE TITLE
4B9-Simsbury Airport-CONNECTICUT-USA

### ISSUE THREAD

**Issue by GoldenSpotter** [InfiniteFlightAirportEditing/Airports#2151]
Part of [Project New England](https://community.infinite-flight.com/t/project-new-england/43169).

**Comment by dushyants19** [comment]
Up for Grabs
@CptNathanHope interested?

**Comment by CptNathanHope** [comment]
Redone via [`d924457`](https://github.com/InfiniteFlightAirportEditing/Airports/commit/d9244577f672eb78a7566b9134ff959b9b2c4dfd).

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32578893-99ba44a6-c4a4-11e7-993f-9db6300b27a1.png)
