### ISSUE TITLE
SLOR-Juan Mendoza Airport-ORURO-BOLIVIA

### ISSUE THREAD

**Issue by MoisesIriarte** [InfiniteFlightAirportEditing/Airports#2153]
Juan Mendoza Airport in Oruro Bolivia with a +10k runway and had the old runway closed down. I will make this from scratch.

**Comment by MoisesIriarte** [comment]
I just sent the airport for review via email

**Comment by moritzbabl** [comment]
Added, @MoisesIriarte please check your mails and accept the invite for our github team

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29490713-a80d9614-8509-11e7-993b-6e1beca8161e.png)
