### ISSUE TITLE
SLRQ-Rurrenabaque-RURRENABAQUE-BOLIVIA

### ISSUE THREAD

**Issue by MoisesIriarte** [InfiniteFlightAirportEditing/Airports#2154]
Rurrenabaque airport in Bolivia to be edited by me.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29490732-6b672ba2-850a-11e7-8f9e-d7d5eaa18062.png)
