### ISSUE TITLE
SLUY-Joya Andina Airport-UYUNI-BOLIVIA

### ISSUE THREAD

**Issue by MoisesIriarte** [InfiniteFlightAirportEditing/Airports#2156]
Joya Andina airport in Bolivia with a +10k runway. I'll edit this one.

**Comment by MoisesIriarte** [comment]
Submitted for review via email just now.

**Comment by henrikbg** [comment]
Approved.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29997772-ae1c1ade-8fe1-11e7-87f8-b7c113ac690b.png)
