### ISSUE TITLE
MBSC

### ISSUE THREAD

**Issue by ewanfleming** [InfiniteFlightAirportEditing/Airports#2160]
Very small airport - South Caicos Intl is the one I'm starting. Middle Caicos and North Caicos should be coming soon, cause why not?

**Comment by ewanfleming** [comment]
Sent in for review even tho I haven't even been assigned yet

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29249235-566560a2-7ff1-11e7-9b47-f62b2a9fdd97.png)
