### ISSUE TITLE
MRQP-La Managua Airport-PUNTARENAS-COSTA RICA

### ISSUE THREAD

**Issue by OJFam** [InfiniteFlightAirportEditing/Airports#2163]
♻️

**Comment by dushyants19** [comment]
How's this going? @OJFam

**Comment by dushyants19** [comment]
Suggestion

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36619482-9d27840a-18b4-11e8-845f-d493acb042cb.png)
