### ISSUE TITLE
DNAA-Nnamdi Azikiwe Intl-FEDERAL CAPITAL TERRITORY-NIGERIA

### ISSUE THREAD

**Issue by ebukarthur** [InfiniteFlightAirportEditing/Airports#2164]
It is Nnamdi Azikiwe International Airport, I'll do it

**Comment by JcFl4** [comment]
How's this going? I can upload a rough file in the mean time

**Comment by dushyants19** [comment]
You can have it

**Comment by JcFl4** [comment]
Ok, it's rough though

**Comment by JcFl4** [comment]
Done. It's not that rough anymore cause I made it from scratch

**Comment by kilt46** [comment]
Incorrect terminal layout
![image](https://user-images.githubusercontent.com/14023167/31154159-cbe4832a-a86a-11e7-9422-c9b824b86cf9.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31154172-da35b9e4-a86a-11e7-97ea-a1095013df4e.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31154176-e27ea58e-a86a-11e7-9b25-fab3b3fa292f.png)

**Comment by JcFl4** [comment]
Added terminal

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31585033-b8532938-b17f-11e7-957a-9de2214ae666.png)
