### ISSUE TITLE
LIMF-Torino-Caselle Airport-PIEMONTE-ITALY

### ISSUE THREAD

**Issue by GoldenSpotter** [InfiniteFlightAirportEditing/Airports#2165]
RECYCLED ♻️

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31851334-720e6b00-b629-11e7-863e-ea351454d0c8.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/43675530-773bb00a-97a7-11e8-82c0-e7c733a11a55.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/69487030-0bf54b00-0e32-11ea-857d-af2d6e60df21.jpg)
