### ISSUE TITLE
UEEE

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#2166]
Yakutsk Int'l Airport. I will do this one.

Runway is longer than 10k feet.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29741596-e85d250a-8a35-11e7-8a73-c9d812d64739.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/43808321-1deb4cae-9a72-11e8-9734-c1bba1ced1ab.png)
