### ISSUE TITLE
KGYY

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#217]
Chicago

**Comment by kilt46** [comment]
Is this available to do. It states 'Being Redone' but with no assignee?

**Comment by kilt46** [comment]
Hmm I messed this up. Looks like this is not assigned. I will get done next. No way to unclose as far as I can see!

**Comment by kilt46** [comment]
Please let me know if this is being done by David. He was removed 21 days ago!

**Comment by JohnPreston21** [comment]
I think he's away atm so I think it's safe to grab this one.

**Comment by kilt46** [comment]
OK this one is now done

**Comment by kilt46** [comment]
Consolidated aprons to remove cracks. Lines set to black set with lighting

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20862528/ef2b8e88-b972-11e6-88d7-3954def36756.png)
