### ISSUE TITLE
MMHB-Holbox Airfield-QUINTANA ROO-MEXICO 

### ISSUE THREAD

**Issue by lalomarlin** [InfiniteFlightAirportEditing/Airports#2171]
Being Redone

**Comment by lalomarlin** [comment]
New airfield, it exists IRL but not in the database

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29479105-f8cc9494-8435-11e7-95fc-e41e5f868be3.png)
