### ISSUE TITLE
KILG-New Castle Airport-DELAWARE-USA

### ISSUE THREAD

**Issue by Blently** [InfiniteFlightAirportEditing/Airports#2172]
New Castle Airport, I'll do this one

**Comment by Blently** [comment]
Sent for review

**Comment by henrikbg** [comment]
Approved.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29986142-b71a13e4-8f27-11e7-8812-077914b9d5f0.png)
