### ISSUE TITLE
RJER-Rishiri Airport-HOKKAIDO-JAPAN

### ISSUE THREAD

**Issue by CMO99** [InfiniteFlightAirportEditing/Airports#2173]
♻️

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by LeonVeen** [comment]
I'll 'grab' it
Gonna be my first airport in a high-quality scenery region

**Comment by MajorTomMueller** [comment]
Docking chart: 
http://www.aisro.ro/aip/2018-01-05/DOCS/AIP/AD/AD2/AD_2_14_LRSV/LR_AD_2_LRSV_14-22_en.pdf
Rest of airport HQ imagery

**Comment by LeonVeen** [comment]
Am I not unassigned to this airport?

**Comment by moritzbabl** [comment]
Yes you are

**Comment by benlenahan** [comment]
Sent in for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36761044-ee4bc824-1be2-11e8-9070-530ef5e8753b.png)
