### ISSUE TITLE
MMLM-Los Mochis Airport-SINALOA-MEXICO

### ISSUE THREAD

**Issue by lalomarlin** [InfiniteFlightAirportEditing/Airports#2176]
Being Redone

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36341439-e2b9b5ca-13b3-11e8-83dc-24cae056e937.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36820815-640550e4-1cb5-11e8-9fe1-58c86516674f.png)
