### ISSUE TITLE
LPPS-Porto Santo Airport-VILA BALEIRA-MADEIRA 

### ISSUE THREAD

**Issue by ewanfleming** [InfiniteFlightAirportEditing/Airports#2178]
Porto Santo Airport is para mi

**Comment by ewanfleming** [comment]
Sent in for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29735705-7a5046e8-89c0-11e7-8e59-a92d46ab03fe.png)
