### ISSUE TITLE
KJVL

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#218]
Chicago

**Comment by JohnPreston21** [comment]
adding taxi lines and spawn points

**Comment by JohnPreston21** [comment]
Added taxi lines & parking
finished

**Comment by kilt46** [comment]
This one appears to have no active gates.
Image: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=KJVL

**Comment by JohnPreston21** [comment]
You can have this one if you like @kilt46

**Comment by kilt46** [comment]
Working on this one

**Comment by kilt46** [comment]
Redo of airfield
Image: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=KJVL

**Comment by kilt46** [comment]
Reworking

**Comment by kilt46** [comment]
Line and apron cleanup

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21079988/e7ab6fce-bf68-11e6-85c6-5d08deae17ea.png)
