### ISSUE TITLE
CYXT-Terrace Regional-BRITISH COLUMBIA-CANADA

### ISSUE THREAD

**Issue by DelsterX** [InfiniteFlightAirportEditing/Airports#2180]
I got this one.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30032596-74f0e97a-915c-11e7-8caf-70f482c2ca13.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50567308-15049780-0d09-11e9-8533-b6df9de36a24.png)

**Comment by kilt46** [comment]
removed duplicate spawn
