### ISSUE TITLE
CYKA-Kamloops Airport- BRITISH COLUMBIA-CANADA

### ISSUE THREAD

**Issue by DelsterX** [InfiniteFlightAirportEditing/Airports#2181]
I got this one.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29737539-27170ee8-89d5-11e7-9708-323e5244b26a.png)
Suggested gate layout

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30024339-ef27f7ca-9138-11e7-82f0-d4ddcfc1e38b.png)

**Comment by kilt46** [comment]
Duplicates removed. Buildings removed

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50407443-c56c1c00-079c-11e9-8c51-0dc697ef19ce.png)
