### ISSUE TITLE
RPMR-General Santos International Airport-GENERAL SANTOS-PHILIPPINES

### ISSUE THREAD

**Issue by superven13** [InfiniteFlightAirportEditing/Airports#2182]
I will start from scratch 😁

**Comment by superven13** [comment]
Still editing

**Comment by superven13** [comment]
Sent for Review :}

**Comment by captavgeek** [comment]
i'm requesting to continue the editing of this airport. RWY Length: 10587'.

**Comment by superven13** [comment]
@captavgeek I already sent it for review but they are still on break I think, because they didn't reply yet. THANKS

**Comment by dushyants19** [comment]
We didn't receive anything other than the initial email.

**Comment by captavgeek** [comment]
@superven13 you still on this airport?

**Comment by superven13** [comment]
Yes, @captavjeek I'm still with this

**Comment by captavgeek** [comment]
Gotcha, I'll leave it to you.  Looking forward to RPMR!


On Tue, Jan 2, 2018, at 5:18 PM, Raven Lescano wrote:
> Yes, @captavjeek I'm still with this


> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[1], or mute the thread[2].> 


Links:

  1. https://github.com/InfiniteFlightAirportEditing/Airports/issues/2182#issuecomment-354918423

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34697984-50f8bc30-f49b-11e7-820b-2d352021503f.png)
