### ISSUE TITLE
RPUY-Cauayan Airport-CAUAYAN-PHILIPPINES 

### ISSUE THREAD

**Issue by superven13** [InfiniteFlightAirportEditing/Airports#2183]
I will start from scratch 😀

**Comment by superven13** [comment]
Sent For Review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30255236-b1b0ebe8-9667-11e7-8224-c1b3bee40974.png)
