### ISSUE TITLE
KYNG-Youngstown-Warren Regional Airport-OHIO-USA

### ISSUE THREAD

**Issue by netjets-1951** [InfiniteFlightAirportEditing/Airports#2184]
Part of Project Ohio. Will be redone by me.

**Comment by netjets-1951** [comment]
Also, it does not reach the 10,000ft Milestone. Please add it to the Project Ohio Milestone.

**Comment by netjets-1951** [comment]
Sent in for review. Only two more controlled airports left in Ohio!

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29593463-1979dd90-8770-11e7-8425-99e1b669ac3c.png)
