### ISSUE TITLE
KTLH-Tallahassee International Airport-FLORIDA-USA

### ISSUE THREAD

**Issue by ryanmattwood** [InfiniteFlightAirportEditing/Airports#2186]
Tallahassee International Airport, I'm doing it.

**Comment by ryanmattwood** [comment]
Sent in for review!

**Comment by dushyants19** [comment]
Accept collab invite here: https://github.com/InfiniteFlightAirportEditing/Airports/invitations

**Comment by Yifan081** [comment]
Any updates on this one?

**Comment by ryanmattwood** [comment]
Yes, my apologies. My first attempt at creating an airport went pretty roughly so I let it sit for a while out of frustration. I’ll make the necessary changes as requested by Moritz and have it submitted for review no later than this Saturday.

**Comment by ryu12332** [comment]
Progress?

**Comment by jakevaz423** [comment]
I’ll do this. Will start work later today. :)

**Comment by jakevaz423** [comment]
Just got my PC returned after being in repair for a little while. Starting this from scratch (because I lost all of the data I had already worked on) within the next few days. Can't wait to get back to editing! :)

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by royfr83** [comment]
May I have this one please?

**Comment by royfr83** [comment]
It's been almost 3 months since I took over this airport, so I just want to update that i'm still working on it, with great progress. Coming soon (TM).

**Comment by royfr83** [comment]
Sent in for OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54569714-df875600-49a9-11e9-9523-bc07c4ba8410.png)
