### ISSUE TITLE
MUCF-Jaime González Airport-CIENFUEGOS-CUBA

### ISSUE THREAD

**Issue by cptchris** [InfiniteFlightAirportEditing/Airports#2187]
Part of project cuba.

**Comment by cptchris** [comment]
In for review

**Comment by henrikbg** [comment]
Approved.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30619585-d31ed84e-9d65-11e7-8259-887c9950de85.png)
