### ISSUE TITLE
ENEV-Evenes Airport-NORDLAND-NORWAY

### ISSUE THREAD

**Issue by netjets-1951** [InfiniteFlightAirportEditing/Airports#2188]
This is a suggestion for anyone to take.

**Comment by netjets-1951** [comment]
By the way, this airport was requested by a beta tester.

**Comment by charlesw181** [comment]
I'll take this one if you'd like

**Comment by brunocr98** [comment]
It appears you haven't accepted the invitation to join the repository as a collaborator. Please message an admin your GitHub username so he can send you an email with the invitation, otherwise we won't be able to assign you.

**Comment by charlesw181** [comment]
Alright I finally received and accepted the invitation so can I get assigned to it now?

**Comment by charlesw181** [comment]
Sending for review right now

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30249024-4c6e8bb0-95f8-11e7-91cd-7b7f93a154e4.png)
