### ISSUE TITLE
KHTL-Roscommon County–Blodgett Memorial Airport-MICHIGAN-USA

### ISSUE THREAD

**Issue by brandon1419** [InfiniteFlightAirportEditing/Airports#2189]
Ill take this one. Part of Project Michigan :)

**Comment by brandon1419** [comment]
Sent in for Review :)

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30090976-79e397a4-927c-11e7-8e38-bf590624be22.png)
