### ISSUE TITLE
KMLI

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#219]
Chicago

**Comment by builditbetter** [comment]
I would like to do it

**Comment by Swang007** [comment]
@builditbetter Who are you lol? Haven't seen you before.

**Comment by builditbetter** [comment]
Hey, Its Zachary ;)

**Comment by Swang007** [comment]
Ok, I don't think Zach's active with this anymore. I'll double check but otherwise this airport is open for anyone. Needs to be redone. Make sure you reclone your local repository files, as I added a viewpoint and changed some runway specifics.

**Comment by JohnPreston21** [comment]
What class field is this one?

**Comment by airportmaster** [comment]
Up for grabs. Still figuring out how to download WEDing and I don't have a lot of time for this sized airport. I think it's a Charlie or Bravo

**Comment by JohnPreston21** [comment]
just saw it in wedbing, it's pretty big.

**Comment by Swang007** [comment]
Ok, Zach is still active, but he's having problems with WEDBing and he wants to do a smaller airport.

**Comment by Swang007** [comment]
It looks like it's Bravo as well.

**Comment by JohnPreston21** [comment]
If it isn't too big I'll take it.

**Comment by Swang007** [comment]
I think it would suit you :)

**Comment by JohnPreston21** [comment]
My god this one huge field.

**Comment by kilt46** [comment]
This was completed and uploaded by Cameron

**Comment by kilt46** [comment]
Reworking to make single aprons and clean up lines

**Comment by kilt46** [comment]
Aprons rebuilt

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17277221/2c9d78f8-5703-11e6-99c0-cb052b856018.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17822596/a469b878-661d-11e6-98d7-1fe70a7540f2.png)
TERMINAL
![image](https://cloud.githubusercontent.com/assets/14023167/17822604/adf5281e-661d-11e6-8e43-11da459e6ab5.png)
CARGO
![image](https://cloud.githubusercontent.com/assets/14023167/17822628/b8e83eb4-661d-11e6-9720-ef2f0318e633.png)
GA
![image](https://cloud.githubusercontent.com/assets/14023167/17822641/c4952f06-661d-11e6-8bea-5c13bea24411.png)

**Comment by dushyants19** [comment]
Added small hangar (John Deere)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21121633/2cc27e38-c093-11e6-80b8-1a24d8295bf8.png)
