### ISSUE TITLE
RKPC-Jeju Int'l Airport-JEJU-SOUTH KOREA

### ISSUE THREAD

**Issue by adrinerDP** [InfiniteFlightAirportEditing/Airports#2190]
doing

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31055991-e4988492-a690-11e7-995a-78bf63f65d01.png)

**Comment by kilt46** [comment]
AIRPORT REVIEW
![image](https://user-images.githubusercontent.com/14023167/42411484-1d16a7d8-81c2-11e8-9645-f9245fbe99c6.png)
![image](https://user-images.githubusercontent.com/14023167/42411488-2ebd5e28-81c2-11e8-9390-90f50de09c5f.png)
Stands 22-27 missing - NO Satellite available
