### ISSUE TITLE
KDAB-Daytona Beach International Airport-FLORIDA-USA

### ISSUE THREAD

**Issue by cptchris** [InfiniteFlightAirportEditing/Airports#2191]
I'll do this once one of my 3 airports are approved

**Comment by CptNathanHope** [comment]
Once one of those 3 are approved, please let one of the supervisors know so we can assign you. :)

**Comment by cptchris** [comment]
Will do :)

**Comment by cptchris** [comment]
Can somebody please assign me this one porfavor?

**Comment by cptchris** [comment]
Sent in for review!

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31838991-caea95a8-b5a4-11e7-9e6b-f9613aa29eab.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52541935-3fae2b00-2d60-11e9-9c38-329e3674b885.png)

**Comment by kilt46** [comment]
REMOVE DUPLICATE   SPAWNS | BUILDINGS REMOVED
-- | --
