### ISSUE TITLE
SKGO-Santa Ana Airport-CARTAGO-COLOMBIA

### ISSUE THREAD

**Issue by Yifan081** [InfiniteFlightAirportEditing/Airports#2193]
Santa Ana airport, Cartago, Colombia. Being redone.

**Comment by Yifan081** [comment]
Sent it for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29491506-68dd29b8-8523-11e7-834d-eb90777bd720.png)
