### ISSUE TITLE
KBTL-W. K. Kellogg Airport-MICHIGAN-USA

### ISSUE THREAD

**Issue by ryu12332** [InfiniteFlightAirportEditing/Airports#2194]
Part of Project Michigan

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29643395-7946d63c-8834-11e7-8869-ce530d331837.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112758726-75044a00-8fb5-11eb-8f1c-43fe5881a9d5.png)
