### ISSUE TITLE
RJTQ-Miyakejima Airport-TOKYO-JAPAN

### ISSUE THREAD

**Issue by Yifan081** [InfiniteFlightAirportEditing/Airports#2195]
♻️

**Comment by MajorTomMueller** [comment]
@Yifan081 any progress?

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36945861-b8c5a8ce-1f79-11e8-8d31-2f3d4f6e6019.png)
