### ISSUE TITLE
SKBU

### ISSUE THREAD

**Issue by Yifan081** [InfiniteFlightAirportEditing/Airports#2196]
Gerardo Tobar López Airport, Buenaventura, Colombia. Redone.

**Comment by Yifan081** [comment]
Sent in for review.

**Comment by bavAVIA** [comment]
I swear you either need to fly to all of those in global and screenshot in or pay a 15€ administration fee.

**Comment by moritzbabl** [comment]
added, still waiting for my 15€

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29490455-b9dad656-8502-11e7-9adc-07dc38b1582e.png)
