### ISSUE TITLE
VVNB-Hanoi Noibai International Airport-HANOI-VIETNAM

### ISSUE THREAD

**Issue by lalomarlin** [InfiniteFlightAirportEditing/Airports#2197]
Being Redone 10k+

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
Suggested stands
![image](https://user-images.githubusercontent.com/14023167/31584921-9adbd212-b17d-11e7-926a-ddb1d8895e6d.png)
![image](https://user-images.githubusercontent.com/14023167/31584935-e6929f1a-b17d-11e7-8177-7bdad7e0a891.png)

**Comment by Tamz00** [comment]
Shouldn’t this have ‘Being Redone’ too?

**Comment by ewanfleming** [comment]
You don't want this to stay as it is for long...
![img_1897](https://user-images.githubusercontent.com/28999470/31852397-06c0b04c-b66f-11e7-98d1-18ef8f926ccd.PNG)

**Comment by lalomarlin** [comment]
Will be sent tonight

**Comment by Taixipo2003** [comment]
When it finish?

**Comment by lalomarlin** [comment]
Please be patient, these day have been very occupied for me an don’t have time to fix such a tiny issue until Wednesday night of maybe getting on weekend to send it fixed already, don’t forget that we are also humans and we got duties to do. Thanks for your understanding.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38150162-49597240-3423-11e8-8051-23ee0eeabf46.png)

**Comment by MinhNguyN** [comment]
Ssome gate sizes wrong and some taxiline out of place or in the wrong shape and the airport was upgraded in 2019, so this airport quite outdate. Can I redo this airport?

**Comment by MinhNguyN** [comment]
![image](https://user-images.githubusercontent.com/60785145/80008336-d0020700-84f1-11ea-953f-fe5af99628b4.png)
This is the newest parking chart of VVNB

**Comment by MajorTomMueller** [comment]
Yes, you can.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113458703-c73fd380-93d8-11eb-8078-f0739f7e8783.png)

**Comment by MajorTomMueller** [comment]
Removal of the runway is incorrect.
It is just temporary restricted to icao class C and has displaced threshold:
![4F96BE5D-860D-4EA0-8F2B-3AA5E89841F2](https://user-images.githubusercontent.com/26853210/113596626-e2118280-963a-11eb-8224-f1b01d2d64a9.jpeg)

**Comment by MajorTomMueller** [comment]
@MinhNguyN

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116934962-43714500-ac2b-11eb-8cbe-fd6ec82f9198.png)
