### ISSUE TITLE
KMFD-Mansfield Lahm Regional Airport-OHIO-USA

### ISSUE THREAD

**Issue by netjets-1951** [InfiniteFlightAirportEditing/Airports#2198]
Part of Project Ohio.

**Comment by netjets-1951** [comment]
Sent in for review!

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29593996-8a81c66c-8773-11e7-9646-97c6cc2b0562.png)
