### ISSUE TITLE
SLTJ-Capitan Oriel Lea la Plaza Airport-TARIJA-BOLIVIA

### ISSUE THREAD

**Issue by MoisesIriarte** [InfiniteFlightAirportEditing/Airports#2199]
Doing this one.

**Comment by MoisesIriarte** [comment]
Submitted for review, I kinda had it done already...

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29490484-8a39c5e6-8503-11e7-90a8-51ec68835c8c.png)
