### ISSUE TITLE
KABQ-Albuquerque International Sunport Airport-NEW MEXICO-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#22]
Please redesign me.

Recycled

**Comment by Hamza1108** [comment]
What redesign does this need?

**Comment by dushyants19** [comment]
Get proficient with the skills on editing with your first few ones, then let's grow up to great airports.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22910382/31a33ec0-f21f-11e6-8844-64a7badb2b31.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52528934-695b4980-2caf-11e9-9d58-114177f80c0f.png)
