### ISSUE TITLE
KPWK-Chicago Executive Airport-ILLINOIS-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#220]
Chicago

**Comment by dushyants19** [comment]
I will get this done :)

**Comment by dushyants19** [comment]
Done, was added by Jonathan

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18020002/9ce000bc-6ba4-11e6-982c-b17ce23b89f8.png)

**Comment by moritzbabl** [comment]
![image](https://user-images.githubusercontent.com/19365980/59977121-c0fab180-95cd-11e9-850c-e3a3dddf6545.png)
