### ISSUE TITLE
SLCO-Capitan Anibal Arab Airport-COBIJA-BOLIVIA

### ISSUE THREAD

**Issue by MoisesIriarte** [InfiniteFlightAirportEditing/Airports#2200]
This one too.

**Comment by MoisesIriarte** [comment]
Just sent for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29696566-6ee023f2-890f-11e7-962b-3e1338cf536e.png)
