### ISSUE TITLE
CYWG-Winnipeg/James Armstrong Richardson International Airport-MANITOBA-CANADA

### ISSUE THREAD

**Issue by DelsterX** [InfiniteFlightAirportEditing/Airports#2201]
Surprised this one is not done yet... but I will take it.

**Comment by DelsterX** [comment]
Sent in for Review

**Comment by henrikbg** [comment]
Approved.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30767120-c0621f5c-9fbf-11e7-8e25-399fa1b864b5.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50403394-ccc30380-0763-11e9-8638-c7c43137b2d3.png)

**Comment by kilt46** [comment]
Duplicate spawns removed. Buildings removed. Boundary fixed
