### ISSUE TITLE
ZSNB

### ISSUE THREAD

**Issue by Yifan081** [InfiniteFlightAirportEditing/Airports#2202]
Ningbo Lishe International Airport, China. +10k feet airport.  Redoing it.

**Comment by Yifan081** [comment]
Sent in for review

**Comment by henrikbg** [comment]
Approved.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30521681-34dd28d0-9b89-11e7-9820-65e8e981315a.png)
