### ISSUE TITLE
PAGS

### ISSUE THREAD

**Issue by ewanfleming** [InfiniteFlightAirportEditing/Airports#2203]
I'm starting Gustavus Airport, Alaska, 'Murica.

EDIT: Changed the name of the airport after the wonderful autocorrect decided to change the name

**Comment by ewanfleming** [comment]
Sent in for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29594257-60731b6c-8775-11e7-8b20-bf5d0b2b936f.png)
