### ISSUE TITLE
SLTR-Jorge Henrich Arauz / Trinidad Airport-EL BENI-BOLIVIA

### ISSUE THREAD

**Issue by MoisesIriarte** [InfiniteFlightAirportEditing/Airports#2207]
I'll do this one.

**Comment by MoisesIriarte** [comment]
Sending for review now...

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29696822-e3ef55a4-8910-11e7-8a1c-58b12f1061a3.png)

**Comment by kilt46** [comment]
Please review gate layout at terminal

**Comment by MoisesIriarte** [comment]
On it...

**Comment by MoisesIriarte** [comment]
sent for review with fixes just now

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29995675-a2a111d2-8fb4-11e7-84a5-0301bb7be0f5.png)
