### ISSUE TITLE
07MT-Glasgow Industrial Airport-MONTANA-USA

### ISSUE THREAD

**Issue by ryanmattwood** [InfiniteFlightAirportEditing/Airports#2211]
♻️

**Comment by dushyants19** [comment]
Accept collab invite here: https://github.com/InfiniteFlightAirportEditing/Airports/invitations

**Comment by MajorTomMueller** [comment]
@ryanmattwood any progress?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/37309496-2227fa92-260f-11e8-9d39-c4ba32a6ed0a.png)
