### ISSUE TITLE
EDVP 

### ISSUE THREAD

**Issue by Marsiana7** [InfiniteFlightAirportEditing/Airports#2212]
RECYCLED :recycle:

**Comment by Marsiana7** [comment]
srry did not get along with it.

**Comment by ewanfleming** [comment]
I've got some advice:
A. Make sure you are going to be able to do the airport before making the issue.
B. Don't close the issue. We will either recycle it or make it a suggestion.

**Comment by brunocr98** [comment]
I'll put this as a suggestion if someone wants it.

**Comment by brunocr98** [comment]
Airport closed. 

From Wikipedia:
"The Peine-Eddesse airfield was a German transport land at Peine in the south-east of Lower Saxony."

https://de.m.wikipedia.org/wiki/Flugplatz_Peine-Eddesse
https://airportguide.com/airport/info/ZPG

**Comment by brunocr98** [comment]
Reconverted to EDVP. The code was given to a new airfield.

https://de.m.wikipedia.org/wiki/Flugplatz_Peine-Glindbruchkippe

**Comment by Marsiana7** [comment]
Send in for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30106156-36270700-92c0-11e7-97b5-871311ea4c09.png)
