### ISSUE TITLE
KLAF-Purdue University Airport-INDIANA-USA

### ISSUE THREAD

**Issue by ryu12332** [InfiniteFlightAirportEditing/Airports#2214]

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29899451-338def90-8db1-11e7-8858-bfbea4ffefa1.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52539763-657b0600-2d47-11e9-9e73-9b4ea8c1912b.png)

**Comment by kilt46** [comment]
REMOVE DUPLICATE   SPAWNS | BUILDINGS REMOVED
-- | --
