### ISSUE TITLE
OAQN-Qala-I-Naw-BASGHIS-AFGHANISTAN

### ISSUE THREAD

**Issue by Epadilla1** [InfiniteFlightAirportEditing/Airports#2216]
-missing lines
-misaligned taxiways
-missing parking

**Comment by Epadilla1** [comment]
could I get assigned to this

**Comment by Epadilla1** [comment]
I got WED set up on my new computer now, I've started working on the airport, could I get assigned to this again thx!

**Comment by ryu12332** [comment]
Progress?

**Comment by Epadilla1** [comment]
almost done

**Comment by MajorTomMueller** [comment]
@Epadilla1 still almost done?

**Comment by Epadilla1** [comment]
Yes just working on the squares for GA because I want them to be perfect and not ugly ew. I will only turn in work if I believe it passes by quality test. You know

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by MajorTomMueller** [comment]
![OAQN](https://user-images.githubusercontent.com/26853210/54356973-36fd8d00-465d-11e9-9af2-808b9d699cdb.jpg)
