### ISSUE TITLE
UUDL-Yaroslavl/Tunoshna Airport-YAROSLAV-RUSSIA

### ISSUE THREAD

**Issue by ErshovlaD** [InfiniteFlightAirportEditing/Airports#2217]
Being redone

**Comment by ErshovlaD** [comment]
Done and sent via email.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30340899-ac579220-97b9-11e7-8959-95ac4cc0e214.png)
