### ISSUE TITLE
NZFX-Phoenix Airfield-ROSS ISLAND-ANTARCTICA 

### ISSUE THREAD

**Issue by dushyants19** [InfiniteFlightAirportEditing/Airports#2219]
Recently opened airport. Antarctica

https://en.wikipedia.org/wiki/Phoenix_Airfield

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/35308194-fe306732-006b-11e8-8138-7e7baa66fd9d.png)
