### ISSUE TITLE
KDPA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#222]
Chicago

**Comment by JohnPreston21** [comment]
I would like to take this one

**Comment by JohnPreston21** [comment]
Added new taxi lines, missing airport boundary, New tower view point and ramp starts

**Comment by kilt46** [comment]
Redoing airport

**Comment by kilt46** [comment]
Redesign complete and posted

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21080377/02539842-bf73-11e6-9d24-4bd97ca36343.png)
