### ISSUE TITLE
KCDK-George T Lewis Airport-FLORIDA-USA

### ISSUE THREAD

**Issue by Blently** [InfiniteFlightAirportEditing/Airports#2220]
Small airport, it's off by a few miles and missing it's only taxiway, I'll take care of this.

**Comment by Blently** [comment]
Sent for review

**Comment by henrikbg** [comment]
Approved.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29986972-7ec88d6e-8f2b-11e7-88c6-ba0b0f689a4a.png)
