### ISSUE TITLE
KHTO-East Hampton Airport-NEW YORK-USA

### ISSUE THREAD

**Issue by FlyFi** [InfiniteFlightAirportEditing/Airports#2221]
First edit. I'll do this.

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by dushyants19** [comment]
How is the progress? @FlyFi

**Comment by dushyants19** [comment]
Accept collab invite here: https://github.com/InfiniteFlightAirportEditing/Airports/invitations

**Comment by dushyants19** [comment]
Suggestion

**Comment by ewanfleming** [comment]
I'll take this one.

**Comment by ewanfleming** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32992401-dccb4ede-cd0f-11e7-98c9-81db7296bd76.png)
