### ISSUE TITLE
SLPO-Nicolas Rojas Airport-POTOSI-BOLIVIA

### ISSUE THREAD

**Issue by MoisesIriarte** [InfiniteFlightAirportEditing/Airports#2222]
I'll do this one

**Comment by MoisesIriarte** [comment]
Sending for review already

**Comment by henrikbg** [comment]
Approved.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29989472-c494a870-8f38-11e7-8446-0e9b11c073d6.png)
