### ISSUE TITLE
KOLF-L M Clayton Airport-MONTANA-USA

### ISSUE THREAD

**Issue by insertusernameh3r3** [InfiniteFlightAirportEditing/Airports#2223]
♻️

**Comment by brunocr98** [comment]
Up for grabs

**Comment by brent11292** [comment]
I will do it

**Comment by brunocr98** [comment]
Hi Brent,

Please join out team at contact@airportediting.com to do this airport. By joining our repository as collaborator, we will be able to assign you to future issues.

Thanks

**Comment by brent11292** [comment]
Yep, sent an email and an application on the website

**Comment by brent11292** [comment]
This is up for grabs, got busy and can't devote enough time anymore, message me on Slack for the work that has already been done.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36926277-7a92baee-1e3c-11e8-9ac1-b33ee4c6dc7d.png)
