### ISSUE TITLE
KCGF-Cuyahoga County Airport-OHIO-USA

### ISSUE THREAD

**Issue by netjets-1951** [InfiniteFlightAirportEditing/Airports#2224]
Being redone. Part of Project Ohio.

**Comment by netjets-1951** [comment]
Sent in for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29987463-fb0780cc-8f2d-11e7-8947-c8a4de477013.png)
