### ISSUE TITLE
SLHI-Chimore Airport-CHIMORE-BOLIVIA

### ISSUE THREAD

**Issue by MoisesIriarte** [InfiniteFlightAirportEditing/Airports#2225]
I'll take this one

**Comment by MoisesIriarte** [comment]
Sending for review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29997742-df7cfa54-8fe0-11e7-92bb-6282b4c259c7.png)

**Comment by kilt46** [comment]
Is this too long??

![image](https://user-images.githubusercontent.com/14023167/29997752-38999f16-8fe1-11e7-8769-0f11fc89e7b4.png)

**Comment by MoisesIriarte** [comment]
It's the correct length. The problem is that there was an airport renovation maybe two years ago and nobody has updated the charts for it so the old charts keep saying something like 6,000 feet but in reality that's how long the new runway is now. I used SAS scenery given my Moritz so it's scaled correctly.

**Comment by MoisesIriarte** [comment]
Can someone close this one and unassign me please?
