### ISSUE TITLE
ROYN

### ISSUE THREAD

**Issue by Yifan081** [InfiniteFlightAirportEditing/Airports#2226]
Yonaguni Airport, Okinawa Prefecture, Japan. Being redone.

**Comment by Yifan081** [comment]
Sent in for review

**Comment by henrikbg** [comment]
Approved.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30245134-fb37cb92-9595-11e7-9d6d-629995b51a7a.png)
