### ISSUE TITLE
LEJR-Jerez Airport-ANDALUCIA-SPAIN

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#2227]
Jerez de la Frontera Airport, Andalucía, Spain.

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30241885-a12b063a-9551-11e7-86a3-efbab1332fe0.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109387745-cba03a80-78c8-11eb-97c2-3c544919e208.png)
