### ISSUE TITLE
LFBZ-Biarritz/Pays Basque Airport-AQUITANE-FRANCE

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#2228]
Biarritz Airport in the very southwest of France.

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30002799-c6cc5922-9077-11e7-8248-30da8f9ff42e.png)
