### ISSUE TITLE
KINL-Falls International Airport/Einarson Field-MINNESOTA-USA

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#2229]
Falls International Airport, Minnesota, United States of America.

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29742062-b97d374a-8a3d-11e7-8d3c-9e4fee467d30.png)
