### ISSUE TITLE
KCMI

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#223]
Chicago

**Comment by 787Michael** [comment]
working on it.

**Comment by Swang007** [comment]
Tower position is on the runway (I know a lot of airports are but this one has been pointed out by IFFG)
![image](https://cloud.githubusercontent.com/assets/11000109/7798208/7928c156-02bc-11e5-86c5-b038b16575ca.jpg)
![image](https://cloud.githubusercontent.com/assets/11000109/7798209/793d8334-02bc-11e5-871f-bbd6e067677a.jpg)

**Comment by Swang007** [comment]
@JohnPreston21

**Comment by Swang007** [comment]
Fixed tower position and spawn points.

**Comment by HenrikBerg02** [comment]
Doesn't seem like anybody has worked on it. I'll get this one redo'd when I have time.

**Comment by HenrikBerg02** [comment]
Finished up KCMI.

**Comment by kilt46** [comment]
lines need SNAPPED. Also missing hold lines. Some hold lines are upside down

**Comment by kilt46** [comment]
Main apron consolidated

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17267710/cbbcbb8a-55d5-11e6-85bd-5231d306e7c2.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17269546/d52504da-5610-11e6-94c3-ddbdacad05a3.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18022342/8decb0fa-6bb3-11e6-9163-61b8c4d68ffd.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18022348/97dc773a-6bb3-11e6-8015-261a282da049.png)
