### ISSUE TITLE
EDVN

### ISSUE THREAD

**Issue by Marsiana7** [InfiniteFlightAirportEditing/Airports#2231]
EDVN Northeim Flugplatz    I´ll do it.

**Comment by Marsiana7** [comment]
Send in for review.

**Comment by henrikbg** [comment]
Approved.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30106548-6a5a3f6e-92c1-11e7-98c6-2fbcfe635c26.png)
