### ISSUE TITLE
GCFV-Fuerteventura Airport-ISLAS CANARIAS-SPAIN

### ISSUE THREAD

**Issue by Marsiana7** [InfiniteFlightAirportEditing/Airports#2232]
I do suggest this airport, because every major airport of the canaries (Gran Canaria, Teneriffa, Lanzarote) had been done as far as i know except of this one.

**Comment by brunocr98** [comment]
Seems wondeful, I'll attempt to redo it.

**Comment by Marsiana7** [comment]
Could you make a screenshot and send it to me when u have finished? Its just because it is my fav. holiday destination😊.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29742256-2f6a8e78-8a41-11e7-9fc0-15c0cbafe441.png)

**Comment by kilt46** [comment]
Outlines converted to solid white
![image](https://user-images.githubusercontent.com/14023167/34649614-60c04062-f378-11e7-8970-7db2f8b81754.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107861794-d0b3b300-6e0d-11eb-950a-f1e0c555fb1a.png)
