### ISSUE TITLE
KPUW-Pullman/Moscow Regional Airport-WASHINGTON-USA

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#2233]
Pullman - Moscow Regional, Washington, US.

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29999408-cd78ae80-900c-11e7-90db-25dc0981a24f.png)
