### ISSUE TITLE
WAAA-Sultan Hasanuddin Airport-SULAWESI SELATAN-INDONESIA

### ISSUE THREAD

**Issue by haociek** [InfiniteFlightAirportEditing/Airports#2234]
Sultan Hasanuddin Airport, Makassar, Indonesia
will work on this

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30004860-08ab69e0-909c-11e7-84f5-d38e979f9cd5.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90312343-555a5e80-dec9-11ea-98d2-eadc6153dc86.png)

**Comment by MajorTomMueller** [comment]
This Airport need :
1. Extended the taxiway
2. Add some Parking Gate
3. Change incorect some spawn number that I make before

**Comment by MajorTomMueller** [comment]
Comment here @vinoalviano1994
