### ISSUE TITLE
KGIF-Winter Haven Regional-FLORIDA-USA

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#2236]
Will do this once unassigned.

**Comment by cptchris** [comment]
In for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29986851-dc1c9fa6-8f2a-11e7-94ce-3cfd0097bcc7.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53294464-3cc62800-37ad-11e9-8f1f-a30e3220e64c.png)

**Comment by kilt46** [comment]
DUPLICATE SPAWNS REMOVED

**Comment by brennanhackard** [comment]
Available to anyone who wants it. 

- needs the new taxiways on the north and west sides
- needs the new hangars 
- missing lots of markings
- poor taxiway geometry
- missing several spawns
