### ISSUE TITLE
ENAL-Alesund Vigra Airport-MORE OG ROMSDAL-NORWAY

### ISSUE THREAD

**Issue by ewanfleming** [InfiniteFlightAirportEditing/Airports#2237]
Alesund Airport, Vigra, Norway, I'll take it

**Comment by ewanfleming** [comment]
Sent in for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30038759-c2ceb5f6-918d-11e7-9008-3683999b7f18.png)

**Comment by ewanfleming** [comment]
Turns out Wedomaker was outdated (again), re-emailed in
NOTE TO REVIEWER: You might have to realign the airport, the gate layout wasn't the only problem with the imagery

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30249336-319a161c-9600-11e7-924c-4941c2d709fa.png)
