### ISSUE TITLE
KCGX

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#224]
Chicago

**Comment by JohnPreston21** [comment]
Redoing Spawn points and adding a couple

**Comment by JohnPreston21** [comment]
Finised

**Comment by kilt46** [comment]
Redo airport

**Comment by kilt46** [comment]
Airport remodelled with gates

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17267311/39563f82-55cb-11e6-9e88-ca31f226ceb2.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18227689/da06fe06-71f2-11e6-89b6-f02f97de6aea.png)
