### ISSUE TITLE
HTSO

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#2241]
Requested by a beta tester via Cameron, up for grabs, doing it may get you a digital cookie with the LiveFlight logo on it

**Comment by ewanfleming** [comment]
I'll take it. You know I love the small airports in Tanzania.
P.S. On holiday ATM so will not be able to do too much.

**Comment by ewanfleming** [comment]
Sent in for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30006709-444d1390-90c4-11e7-9975-a92b7ec66448.png)
