### ISSUE TITLE
KPKB-Mid-Ohio Valley Regional Airport-WEST VIRGINIA- USA

### ISSUE THREAD

**Issue by cptchris** [InfiniteFlightAirportEditing/Airports#2242]
Part of project ohio

**Comment by cptchris** [comment]
In for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29986605-c05e9388-8f29-11e7-812d-f62d4bde595b.png)
