### ISSUE TITLE
KECG-Elizabeth City Coast Guard Air Station/Regional Airport-NORTH CAROLINA-USA

### ISSUE THREAD

**Issue by henrikbg** [InfiniteFlightAirportEditing/Airports#2243]
Going to be reworking this airport from scratch.

**Comment by henrikbg** [comment]
Essentially finished with this one. Waiting on something before I'll commit to the repository.

**Comment by henrikbg** [comment]
Redone.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32405708-57fe867c-c138-11e7-9aec-1ccc6e6d8945.png)
