### ISSUE TITLE
MKBS-Ian Fleming International Airport-SAINT MARY-JAMAICA

### ISSUE THREAD

**Issue by charlesw181** [InfiniteFlightAirportEditing/Airports#2246]
I'll take care of this one.

**Comment by charlesw181** [comment]
sent in for review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30038820-8643d976-918e-11e7-9604-5f17ed3220e2.png)
