### ISSUE TITLE
SLET-El Trompillo Airport-SANTA CRUZ-BOLIVIA

### ISSUE THREAD

**Issue by MoisesIriarte** [InfiniteFlightAirportEditing/Airports#2251]
I'll do this one, it's ready to submit.

**Comment by MoisesIriarte** [comment]
Sent for review

**Comment by henrikbg** [comment]
Approved.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29995555-98473f48-8fb1-11e7-97a3-a34e4445d460.png)
