### ISSUE TITLE
KYIP-Willow Run Airport-MICHIGAN-USA

### ISSUE THREAD

**Issue by netjets-1951** [InfiniteFlightAirportEditing/Airports#2253]
Part of Project Michigan. Doing this one as a favor for Ryan, since he did KTOL.

**Comment by netjets-1951** [comment]
Sent in for review!

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36341108-c249750a-13ae-11e8-8be0-ca3b05447e17.png)
