### ISSUE TITLE
SLSA-Jose Chavez Suarez Airport-SANTANA DE YACUMA-BOLIVIA

### ISSUE THREAD

**Issue by MoisesIriarte** [InfiniteFlightAirportEditing/Airports#2254]
I'll take care of this one.

**Comment by MoisesIriarte** [comment]
Sent in for review

**Comment by henrikbg** [comment]
Approved.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29995429-c9930a3a-8fae-11e7-9f29-e392b110a299.png)
