### ISSUE TITLE
SLPS-Puerto Suarez Airport-PUERTO SUAREZ-BOLIVIA

### ISSUE THREAD

**Issue by MoisesIriarte** [InfiniteFlightAirportEditing/Airports#2255]
This one too.

**Comment by MoisesIriarte** [comment]
Just sent in for review.

**Comment by henrikbg** [comment]
Approved.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30139370-1dc63db6-9333-11e7-949c-8d8771f0565e.png)
