### ISSUE TITLE
SLYA-Yacuiba Airport-TARIJA-BOLIVIA 

### ISSUE THREAD

**Issue by MoisesIriarte** [InfiniteFlightAirportEditing/Airports#2257]
I'll do this one too.

**Comment by MoisesIriarte** [comment]
Sending for review...

**Comment by henrikbg** [comment]
Approved.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30139271-7936f524-9332-11e7-8900-5c646f7d216f.png)
