### ISSUE TITLE
LICT-Trapani Birgi Airport-SICILIA-ITALY

### ISSUE THREAD

**Issue by charlesw181** [InfiniteFlightAirportEditing/Airports#2258]
I'll take this one up

**Comment by dushyants19** [comment]
How is this going?

**Comment by charlesw181** [comment]
I've been short for time lately but airport is 85% done so I'll complete it soon.

**Comment by charlesw181** [comment]
Sent for review

**Comment by johanneskkl** [comment]
Any news?

**Comment by brunocr98** [comment]
Johannes will take this when he finishes with his other airport.

**Comment by johanneskkl** [comment]
sent in for review. We need a faster/more efficient peer-review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38906229-f585bece-427a-11e8-8052-00a1b21832b7.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/70490074-386cc080-1adc-11ea-9775-d038bd054d55.jpg)
