### ISSUE TITLE
KFFT-Capital City Airport-KENTUCKY-USA

### ISSUE THREAD

**Issue by lolo31r** [InfiniteFlightAirportEditing/Airports#2259]
Redoing this one. Project US State Capitals project

**Comment by MajorTomMueller** [comment]
@lolo31r any progress?

**Comment by MajorTomMueller** [comment]
In for second review next week according to editor

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38179678-aa5bdb9a-35eb-11e8-95cf-fdd001660570.png)
