### ISSUE TITLE
NZSP-Jack F. Paulus Skiway-SOUTH POLE-ANTARCTICA 

### ISSUE THREAD

**Issue by brandon1419** [InfiniteFlightAirportEditing/Airports#2260]
I will take this one.  Just want to make sure the runway length is correct :)

**Comment by brandon1419** [comment]
![100524082823ztavy4](https://user-images.githubusercontent.com/30906497/29999890-8b0247c2-9026-11e7-83c6-a1f21e30194d.png)
![feb08aerialscot11](https://user-images.githubusercontent.com/30906497/29999891-8d6a6e86-9026-11e7-9e2d-72451ac4596f.jpg)
![south_pole_station_1680](https://user-images.githubusercontent.com/30906497/29999892-900bfc68-9026-11e7-863b-dadfea58a4bf.jpg)

There is no imagery available for this airport... I found the coordinates of each side of the runway so I inserted those in.  May I use the pictures above to make the buildings? Thanks :)

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30255531-19fdbaee-966a-11e7-8bb8-033053b28acb.png)
