### ISSUE TITLE
1KC-Kalakaket Creek Air Station Airport-ALASKA-USA

### ISSUE THREAD

**Issue by netjets-1951** [InfiniteFlightAirportEditing/Airports#2262]
Recommendation. It would make for some pretty cool bush flying.

**Comment by netjets-1951** [comment]
It's IATA is KKK

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31578710-8c369a30-b0ec-11e7-996b-ad254b41e35d.png)
