### ISSUE TITLE
RPVJ-Masbate Airport-MASBATE-PHILIPPINES 

### ISSUE THREAD

**Issue by superven13** [InfiniteFlightAirportEditing/Airports#2265]
I will start from scratch add taxiway, terminal and more other things

**Comment by superven13** [comment]
Sent For Review

**Comment by dushyants19** [comment]
It's been approved, I'll add it to the repo once I get a stable wifi

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/35059021-69e6fcee-fb7f-11e7-8920-5c9854fa800f.png)
