### ISSUE TITLE
OOTH-Thumrait Airbase-DHOFAR-OMAN

### ISSUE THREAD

**Issue by Swang007** [InfiniteFlightAirportEditing/Airports#227]
Please edit me

**Comment by dushyants19** [comment]
Poor markings on Gmaps

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25065132/fdd1c03c-21ce-11e7-95a8-dc6e9cc552e5.png)

**Comment by MajorTomMueller** [comment]
![OOTH-github-db](https://user-images.githubusercontent.com/26853210/107844498-b6f17c00-6dcb-11eb-9e32-87ca94a3f7e2.png)

**Comment by MajorTomMueller** [comment]
![OOTH-git](https://user-images.githubusercontent.com/26853210/108407939-54a9d880-721c-11eb-9d2c-5ec4342b29c3.png)
