### ISSUE TITLE
WAJJ

### ISSUE THREAD

**Issue by haociek** [InfiniteFlightAirportEditing/Airports#2272]
Sentani International Airport, Jayapura, Indonesia
will do this

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34073587-134ad8aa-e262-11e7-98e7-b09078369b87.png)

**Comment by kilt46** [comment]
New request: This airport want to Extend the Runway, Expand the Apron, and add other Linear Features.
Existing Baseline: (Buildings removed)
![image](https://user-images.githubusercontent.com/14023167/115783664-bf91a000-a382-11eb-87b0-080a2d9f2a88.png)
Navigraph Chart
![image](https://user-images.githubusercontent.com/14023167/115783749-d6d08d80-a382-11eb-9d7f-24bd0473884b.png)
Parking stands
![image](https://user-images.githubusercontent.com/14023167/115783781-e4861300-a382-11eb-8011-530afb60b483.png)
