### ISSUE TITLE
SPST-Guillermo del Castillo Airport-SAN MARTIN-PERU

### ISSUE THREAD

**Issue by LeonVeen** [InfiniteFlightAirportEditing/Airports#2274]

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31047883-2b43f7e6-a5d8-11e7-8570-d145bbddcf1e.png)

**Comment by kilt46** [comment]
Suggests 5 spots
![image](https://user-images.githubusercontent.com/14023167/31047928-f900f56c-a5d8-11e7-8f4b-0cffabae809e.png)
![image](https://user-images.githubusercontent.com/14023167/31047932-04edba5e-a5d9-11e7-8e3b-090e79eba126.png)

**Comment by LeonVeen** [comment]
Where did you get that diagram kilt? Just wondering, couldn't find one myself...

**Comment by moritzbabl** [comment]
readded

**Comment by kilt46** [comment]
issue

**Comment by LeonVeen** [comment]
What??

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31918638-5d5c0e50-b823-11e7-9ef4-520c13aa194a.png)

**Comment by LeonVeen** [comment]
What's the issue?
