### ISSUE TITLE
OPKC-Karachi Jinnah International Airport-SIND-PAKISTAN

### ISSUE THREAD

**Issue by Tamz00** [InfiniteFlightAirportEditing/Airports#2275]
Karachi Jinnah Intl., Pakistan

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31861183-470875c0-b6ee-11e7-9739-f25784356d14.png)

**Comment by MBeringuy** [comment]
Excluded buildings and other minor changes.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85929971-51716f00-b87e-11ea-9a7d-75d2e792674d.png)
