### ISSUE TITLE
GATB

### ISSUE THREAD

**Issue by ewanfleming** [InfiniteFlightAirportEditing/Airports#2276]
Timbuktu Airport, the airport far away from everywhere with an endless touchdown zone

**Comment by ewanfleming** [comment]
Sent in for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34643510-ec810462-f2ea-11e7-9c68-0ce6e76f4611.png)
