### ISSUE TITLE
DRRN-Niamey Diori Hamani Airport-NIAMEY-NIGER

### ISSUE THREAD

**Issue by johanneskkl** [InfiniteFlightAirportEditing/Airports#2279]
Niamey airport. I will do this to warm up before getting to other airports

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31588309-82c302f8-b1b5-11e7-98f1-f01c1c0409df.png)

**Comment by brunocr1050** [comment]
@hari-shreyas will be redoing the airport

**Comment by hari-shreyas** [comment]
I'd like to redo this airport from scratch. Thanks.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123527471-838dfa80-d6a5-11eb-801d-af93ee0040c9.png)
