### ISSUE TITLE
MPRA-Raul Arias Espinoza Airport-PANAMA-PANAMA

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#2280]

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30088422-cb24752c-926b-11e7-93a6-042e60a59873.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112704324-31e89080-8e68-11eb-8d75-b6b05c9114e1.png)
