### ISSUE TITLE
MPMF-Miraflores Airport-DARIEN-PANAMA

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#2281]

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30089357-d932e634-9271-11e7-9c86-e95c7ced3d37.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112704205-b4248500-8e67-11eb-8b24-6764575873c7.png)
