### ISSUE TITLE
SKRH

### ISSUE THREAD

**Issue by alchonub** [InfiniteFlightAirportEditing/Airports#2282]
Desierto!

**Comment by alchonub** [comment]
Btw I'll do it

**Comment by alchonub** [comment]
Sent in

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30251710-1d9a8996-962b-11e7-996f-6b12b0a3dcd8.png)
