### ISSUE TITLE
SLAG-Monteagudo Airport-CHUQUISACA-BOLIVIA

### ISSUE THREAD

**Issue by MoisesIriarte** [InfiniteFlightAirportEditing/Airports#2284]
Doing this one

**Comment by MoisesIriarte** [comment]
Sent for review

**Comment by henrikbg** [comment]
Approved.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30231130-08b4f84a-94af-11e7-864e-933bff986b87.png)
