### ISSUE TITLE
SLIX-Ixiamas Airport-LA PAZ-BOLIVIA

### ISSUE THREAD

**Issue by MoisesIriarte** [InfiniteFlightAirportEditing/Airports#2285]
This one too

**Comment by MoisesIriarte** [comment]
Sent for review just now

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30245096-dd364886-9594-11e7-8211-737bbafe42a4.png)
