### ISSUE TITLE
SLAL-Alcantari Airport-SUCRE-BOLIVIA

### ISSUE THREAD

**Issue by MoisesIriarte** [InfiniteFlightAirportEditing/Airports#2286]
This too. Airport not in repository yet though.

**Comment by MoisesIriarte** [comment]
Runway is +10k feet

**Comment by MoisesIriarte** [comment]
Sent for review

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30672855-b0738324-9e34-11e7-9ad4-9205a650cfc4.png)
