### ISSUE TITLE
MPPI-Bahía Piña Airport-DARIEN-PANAMA

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#2287]
http://www.gcmap.com/airport/BFQ

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30233305-4a580a34-94ba-11e7-8075-39c7aefcaf84.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112704013-18931480-8e67-11eb-97cd-0ff0c08bdbc8.png)
