### ISSUE TITLE
MPCO-El Trapiche Airport-VERAGUAS-PANAMA

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#2288]
http://www.gcmap.com/airport/MPCO

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30233409-11fdd3e8-94bb-11e7-9efa-e9b5e516951f.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112703904-9dc9f980-8e66-11eb-828e-b231d6cc3795.png)
