### ISSUE TITLE
YPDN-Darwin Airport-NORTHERN TERRITORY-AUSTRALIA

### ISSUE THREAD

**Issue by alchonub** [InfiniteFlightAirportEditing/Airports#2289]
Kangaroo Wilderness

**Comment by alchonub** [comment]
Messed up the apt.dat expect it in about 4 weeks

**Comment by alchonub** [comment]
I am officially going wild over this airport, It's just having one more chance on the GA ramps

**Comment by alchonub** [comment]
Can’t Do this, Finals

**Comment by brunocr98** [comment]
grabs

**Comment by haociek** [comment]
i'll take this one

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34700257-cc7e12e0-f4a7-11e7-9601-3293a2068d2d.png)
