### ISSUE TITLE
KMUO-Mountain Home AFB Airport-IDAHO-USA

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#229]
Please edit me

**Comment by Swang007** [comment]
Hey you know someone else is already working on this, right? Check the issue tracker...

**Comment by kohanson** [comment]
Hey, I just completed for issue #172 WSAT and submitted. Currently waiting for approval.

**Comment by jpperks** [comment]
Added to the library.

**Comment by JcFl4** [comment]
Just saw the comment. Was going to delete.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25207627/a6696290-2535-11e7-8b3c-230c71081089.png)
