### ISSUE TITLE
WAUU-Manokwari/Rendani Airport-IRIAN JAYA BARAT-INDONESIA

### ISSUE THREAD

**Issue by haociek** [InfiniteFlightAirportEditing/Airports#2290]
Rendani Airport, Manokwari, Indonesia
will do this..........

**Comment by henrikbg** [comment]
Approved.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30231462-9ef78024-94b0-11e7-92ad-e0a348764c37.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/91103779-ed76e700-e631-11ea-916e-2d3e23e2f3d3.png)
