### ISSUE TITLE
EDWR-Borkum Airport-NIEDERSACHSEN-GERMANY

### ISSUE THREAD

**Issue by Marsiana7** [InfiniteFlightAirportEditing/Airports#2297]
I'll do it.

**Comment by Marsiana7** [comment]
Send in.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30241744-3097ee30-954f-11e7-9bc4-0970cf8b29b2.png)
