### ISSUE TITLE
EGVN-RAF Brize Norton-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by charlesw181** [InfiniteFlightAirportEditing/Airports#2300]
I'll take this one

**Comment by MajorTomMueller** [comment]
@charlesw181 any progress?

**Comment by moritzbabl** [comment]
member inactive, up for grabs

**Comment by MajorTomMueller** [comment]
Recycled

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/41814333-95bbc812-770e-11e8-9f7b-601cd59324c4.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42126681-0ef0337a-7c51-11e8-9e34-99ff6771dd6d.png)

**Comment by kilt46** [comment]
Suggest the areas in RED are reviewed and non-aircraft buildings removed.

Respectfully

**Comment by MajorTomMueller** [comment]
Airport is in a clean state according to the rules valid when published.
New rules were discussed, but not published or clearly defined.
IF FDS clearly states that Buildings need to be REMOVED from existing airports I will do this.
If unused Hangers should stay, I will leave them.
At the moment we have nothing precise and specific witch hangars should be drawn.
Actually: No action needed.

**Comment by kilt46** [comment]
Pending clarification from Philippe Rollin

**Comment by MajorTomMueller** [comment]
![EGVN-git](https://user-images.githubusercontent.com/26853210/126032597-ea7218e3-144b-497d-bb12-b8b5810b20bb.png)
