### ISSUE TITLE
FAYP-Ysterplaat Air Force Base-WESTERN CAPE-SOUTH AFRICA

### ISSUE THREAD

**Issue by Herman2511** [InfiniteFlightAirportEditing/Airports#2301]
♻️

**Comment by ryu12332** [comment]
Progress?

**Comment by Herman2511** [comment]
Oh sorry it has not progressed very much but i will try to do it.

ke 28.2.2018 klo 7.03 Ryan <notifications@github.com> kirjoitti:

**Comment by moritzbabl** [comment]
Recycled, will quickly fix this

**Comment by moritzbabl** [comment]
done

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/39557018-35531274-4e4a-11e8-95d1-35afcd02215c.png)
