### ISSUE TITLE
OOSH-Sohar Airport-AL BATNAH-OMAN

### ISSUE THREAD

**Issue by dillion30** [InfiniteFlightAirportEditing/Airports#2302]
♻️

**Comment by brunocr98** [comment]
Sure, will be added if you it yourself. Please join our team at airports@liveflightapp.com. We don't take requests by the way.

**Comment by bavAVIA** [comment]
Yes it will be in global but I will personally make sure this remains a suggestion until it catches dust.

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32701979-e818cf20-c7a4-11e7-9122-ea96e64e2b96.png)
