### ISSUE TITLE
CYQQ-Comox Airport-BRITISH COLUMBIA-CANADA

### ISSUE THREAD

**Issue by ewanfleming** [InfiniteFlightAirportEditing/Airports#2303]
Comox Military Airport. By far my biggest one so far so wish me luck.
10k

P.S. I've tried the title, change it if it is wrong

**Comment by bavAVIA** [comment]
"It is it is" right, but don't consider that a huge achievement for somebody your age.

**Comment by ewanfleming** [comment]
That's why I edited the comment after 10 seconds 🙄

**Comment by ewanfleming** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30772778-5189f24e-a028-11e7-8e39-a725fb8a09ef.png)

**Comment by kilt46** [comment]
Airport incorrectly scaled

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32980961-7799fef0-cc35-11e7-8f94-80b9f6362bf3.png)

**Comment by kilt46** [comment]
Check runway end markers
![image](https://user-images.githubusercontent.com/14023167/32980965-9065f93e-cc35-11e7-9d2c-dd8af33f5027.png)

**Comment by kilt46** [comment]
Fixed
