### ISSUE TITLE
WAYY-Mozes Kilangin Airport-PAPUA-INDONESIA

### ISSUE THREAD

**Issue by haociek** [InfiniteFlightAirportEditing/Airports#2306]
Mozes Kilangin Airport, Timika, Indonesia
will do this.....

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30245034-e8c17b0a-9592-11e7-85d7-55ab298d6c76.png)

**Comment by samChrist07** [comment]
Pls add New terminal

**Comment by MajorTomMueller** [comment]
https://aimindonesia.dephub.go.id/images/160-WAYY%20AD%202-1%20to%20AD%202-9.pdf

https://aimindonesia.dephub.go.id/images/601-WAYY%20AD%202.24-1.pdf

**Comment by MajorTomMueller** [comment]
> 
> 
> Pls add New terminal

your job

**Comment by MajorTomMueller** [comment]
Markings on apron not visible

**Comment by brunocr1050** [comment]
Closing this for now, no attempt to redo this airport has been successful. Will be reopened when someone can really complete it.

**Comment by brunocr1050** [comment]
@adibyaputra will be adding the new terminal.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112908434-24741600-90b5-11eb-8a6e-01317ffa7611.png)
