### ISSUE TITLE
SBSG-Sao Goncalo Do Amarante Airport-RIO GRANDE DO NORTE-BRAZIL

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Airports#2307]
New Natal International Airport

**Comment by FellipeEdu** [comment]
I would like to do it

**Comment by brunocr98** [comment]
You're assigned to it, so you're good to go :)

**Comment by FellipeEdu** [comment]
I finished the airport, how do I send it?

**Comment by brunocr98** [comment]
Send it to airports@liveflightapp.com, and a reviewer will check it. But I'd recommend to upload the file in the Peer-Review channel in our Slack team first, so other editors can see the possible mistakes you might have done.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34185576-bf64f3b0-e4eb-11e7-9112-9fae766ff381.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/61380727-49dcd400-a880-11e9-98bd-334c4333cc8e.jpg)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/75721787-b8f42500-5cb7-11ea-9414-60cfd1e39e01.jpg)
