### ISSUE TITLE
OOMS-Muscat International Airport-MUSCAT-OMAN

### ISSUE THREAD

**Issue by cptchris** [InfiniteFlightAirportEditing/Airports#2310]
Will do this

**Comment by brunocr98** [comment]
@dushyants19 will be happy.

**Comment by cptchris** [comment]
Im sure he will, this is also a suggestion airport btw

**Comment by brunocr98** [comment]
Then why you put "Will do this"?

**Comment by cptchris** [comment]
NO NO NO LOL I mean somone suggested this to me, I am doing this 😂

**Comment by brunocr98** [comment]
Please **clarify** your messages.

**Comment by ewanfleming** [comment]
@brunocr98 we need to swing the ban hammer on @cptchris I think

**Comment by dushyants19** [comment]
This already had an issue but Bruno recycled it

**Comment by bavAVIA** [comment]
@cptchris You do know that the max number for airports you may be assigned to simultaneously is three. This is your *eighth* airport already. Please wait until your other ones have been accepted and you have a free spot.

**Comment by cptchris** [comment]
Wait, i did all that orthorphoto nonsense just to be unassigned. Okay i'll wait 🙄

**Comment by bavAVIA** [comment]
Rules are rules, apply to everyone, and have been pointed out often enough.

**Comment by Aviationluver** [comment]
It's ridiculous that this airport has not been edited yet, I am taking over. 

I don't know how much I will be able to edit before my exams, but afterwards, I will get this done as soon as I can!

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38836143-cc5c4ba0-4192-11e8-95a5-1ca3248b19ff.png)

**Comment by kilt46** [comment]
Kines missing at E4!
![image](https://user-images.githubusercontent.com/14023167/38838564-4addc3e2-419c-11e8-8a67-49ee05a3b8b5.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/39097171-8691cd62-461e-11e8-8d78-353d7060940b.png)

**Comment by MajorTomMueller** [comment]
spawn names changed at certain areas
will update as well as some concrete and removing buildings

**Comment by MajorTomMueller** [comment]
![OOMS-git](https://user-images.githubusercontent.com/26853210/68108842-e505c200-fee0-11e9-8776-05e2344cf986.png)
Aircraft releavant parts are up to date.
Still lacks road markings due to imagery

**Comment by MajorTomMueller** [comment]
Will reopen when imagery changed.
