### ISSUE TITLE
KNLC-Lemoore NAS (Reeves Field) Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by Swang007** [InfiniteFlightAirportEditing/Airports#232]
PLEASE EDIT ME

**Comment by Swang007** [comment]
Issue already exists.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25780433/b9a91bbe-32ed-11e7-983a-cc2039435bbe.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/49330004-e0f15780-f54d-11e8-900b-8c0f4c8f3a8b.png)

**Comment by kilt46** [comment]
Duplicate spawns removed. Buildings removed.
