### ISSUE TITLE
LFQQ-Lille Lesquin-HAUTS-DE-FRANCE-FRANCE

### ISSUE THREAD

**Issue by Tamz00** [InfiniteFlightAirportEditing/Airports#2325]
Lille Lesquin, France

**Comment by brunocr98** [comment]
Please finish 1 of your other 3 airports you have currently assigned.

**Comment by Tamz00** [comment]
I have and sent them in for review (apart from OPKC)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30785745-20dd8390-a131-11e7-8b5f-77a7f1c69bf7.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42725988-d5f7dd0e-8752-11e8-91a7-c84bd0bdb64a.png)
