### ISSUE TITLE
CYQB-Québec/Jean Lesage International Airport-QUEBEC-CANADA

### ISSUE THREAD

**Issue by DelsterX** [InfiniteFlightAirportEditing/Airports#2326]
I will do this one.

**Comment by DelsterX** [comment]
In for review...finally!

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32143057-abae70a0-bc71-11e7-8748-71870821079e.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50425368-3ca3bd80-083a-11e9-9c2e-5a0e0e83c56f.png)

**Comment by kilt46** [comment]
Duplicate spawns removed. Buildings removed
