### ISSUE TITLE
EICK-Cork Airport-CORK-IRELAND

### ISSUE THREAD

**Issue by ewanfleming** [InfiniteFlightAirportEditing/Airports#2328]
I'll do it.

**Comment by ewanfleming** [comment]
Sent in for review.

**Comment by henrikbg** [comment]
Approved.

**Comment by kilt46** [comment]
Some gates in Cargo Area: Gates changed as per Jeppesen
![image](https://user-images.githubusercontent.com/14023167/31045683-a91d982c-a5ae-11e7-96ce-a02a71f1c3f5.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31045687-b50c8ff8-a5ae-11e7-8cf1-c92bd489aa54.png)

**Comment by ECoops-123** [comment]
I have improved and updated this airport.

![Full](https://user-images.githubusercontent.com/59462519/112476403-c4563a80-8d69-11eb-9d5e-13c7be6d16ce.png)
