### ISSUE TITLE
OEJB-Jubail Airport-ASH SHARQIYAH-SAUDI ARABIA

### ISSUE THREAD

**Issue by Swang007** [InfiniteFlightAirportEditing/Airports#233]
Please edit me

**Comment by JohnPreston21** [comment]
@Swang007 do you know what region this on is in?

**Comment by kilt46** [comment]
KPFR is not a valid airport

**Comment by carmichaelalonso** [comment]
Typo in this name - should be KFPR located in Florida.

**Comment by kilt46** [comment]
Will start this one tomorrow

**Comment by kilt46** [comment]
Airport redone. 4 spawn points added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25780904/07aae236-32f6-11e7-8986-842146cbe693.png)
