### ISSUE TITLE
HCMM-Aden Adde Int'l Airport-MOGADISCIO-SOMALIA

### ISSUE THREAD

**Issue by Tamz00** [InfiniteFlightAirportEditing/Airports#2331]
Mogadishu Aden Adde Int'l. Airport, Somalia 
There's literally nothing there, not even a runway shown on WED. Will do this.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30774361-e2913e5a-a046-11e7-9adf-87783525db27.png)
