### ISSUE TITLE
EKAH-Aarhus Airport-ARHUS-DENMARK

### ISSUE THREAD

**Issue by LeonVeen** [InfiniteFlightAirportEditing/Airports#2334]

**Comment by MajorTomMueller** [comment]
![ekah-git7](https://user-images.githubusercontent.com/26853210/35778559-1595a4ac-09c0-11e8-864e-9a9fa4872a28.jpeg)

**Comment by MajorTomMueller** [comment]
boundary

**Comment by MajorTomMueller** [comment]
-Boundary Fix
-Buildings removed
-Hangar Floors added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46118849-30be4600-c1ce-11e8-8ba3-463a0ac543ee.png)
