### ISSUE TITLE
LGTS-Thessaloniki Makedonia Airport-KENTRIKI MAKEDONIA-GREECE

### ISSUE THREAD

**Issue by alchonub** [InfiniteFlightAirportEditing/Airports#2335]
Greek Vacations

**Comment by alchonub** [comment]
If I have more than 3 commits feel free to unassign me

**Comment by brunocr98** [comment]
This is your 4th issue. When one of your other 3 is approved, feel free to ask to be reassigned to this one.

**Comment by alchonub** [comment]
Done and Sent

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31535633-613498ae-afc1-11e7-9975-e807ff7edd48.png)

**Comment by moritzbabl** [comment]
Looks like Yandex finally has usable images of the runway extension to work with 🎉

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85936741-02016200-b8c3-11ea-9da3-a43fe8a1ed6b.png)
