### ISSUE TITLE
EDWY-Norderney Airport-NIEDERSACHSEN-GERMANY

### ISSUE THREAD

**Issue by Marsiana7** [InfiniteFlightAirportEditing/Airports#2338]
I'll do it.

**Comment by Marsiana7** [comment]
Send in.

**Comment by henrikbg** [comment]
Approved.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30724623-b6e3b47e-9f04-11e7-8c38-7732cceb63fa.png)
