### ISSUE TITLE
EKVH-Vesthimmerland Airport-NORTH JUTLAND-DENMARK

### ISSUE THREAD

**Issue by dlewis189** [InfiniteFlightAirportEditing/Airports#2339]
PLEASE EDIT ME.

**Comment by brunocr98** [comment]
Duplicate #818

**Comment by MajorTomMueller** [comment]
recycled

**Comment by MajorTomMueller** [comment]
![ekvh-git](https://user-images.githubusercontent.com/26853210/35435060-972bec9e-0289-11e8-9d49-be0104757d1d.jpeg)

**Comment by MajorTomMueller** [comment]
-boundary fix
-Buildings removed
-Hangar Floors added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46258005-5f1b7a00-c489-11e8-9717-a6e922e7b93f.png)
