### ISSUE TITLE
EGEC-Campbeltown Airport-SCOTLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#234]

**Comment by Swang007** [comment]
Some reports of grass and other stuff on taxiways. @JcFl4 do you want to check this again? I didn't look at the apt.dat

**Comment by JcFl4** [comment]
Already fixed.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21742424/8e91c166-d4b4-11e6-98ea-4b02efa8193f.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45268648-3af9e980-b445-11e8-8745-37ed50676028.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45268664-8b714700-b445-11e8-8cb4-35b50524cf62.png)
