### ISSUE TITLE
YCDR

### ISSUE THREAD

**Issue by AndrewRG10** [InfiniteFlightAirportEditing/Airports#2345]
GA airport in Coloundra near Sunshine coast, Queensland, Australia
currently doing this

**Comment by AndrewRG10** [comment]
Sent in for review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34450656-c9dd9694-ecd4-11e7-820d-13e5133cdf31.png)

**Comment by kilt46** [comment]
Spawns fixed. Buildings removed

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/49340674-03947680-f609-11e8-8081-2e133c5ae346.png)
