### ISSUE TITLE
MUMZ-Sierra Maestra Airport-MANZANILLO-CUBA

### ISSUE THREAD

**Issue by netjets-1951** [InfiniteFlightAirportEditing/Airports#2346]
Being done for Chris, since he did two Ohio Airports. (Part of Project Cuba)

**Comment by cptchris** [comment]
Thanks my freind

**Comment by netjets-1951** [comment]
Sent in for review

**Comment by cptchris** [comment]
It only took you 36 minutes wtf 😱

**Comment by netjets-1951** [comment]
Lol 😏

**Comment by henrikbg** [comment]
Approved.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30775739-674dd564-a05f-11e7-888c-7c62ecdae543.png)
