### ISSUE TITLE
CYQG-Windsor International Airport-ONTARIO-CANADA

### ISSUE THREAD

**Issue by brandon1419** [InfiniteFlightAirportEditing/Airports#2347]
I will take this one :) Thanks!

**Comment by cptchris** [comment]
cpt_chris assigned CYQG-Windsor International Airport-ONTARIO-CANADA to brandon1419

**Comment by cptchris** [comment]
cptchris added the [Being Redone] label

**Comment by cptchris** [comment]
cptchris added the [Low Priority] label

**Comment by brunocr98** [comment]
@cptchris 😒

**Comment by cptchris** [comment]
Yea im a better supervisor than you @brunocr98

**Comment by brandon1419** [comment]
Sent in for Review :)

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31059028-56c6eedc-a6c3-11e7-9cc1-c67c89778277.png)
