### ISSUE TITLE
YSPE-Stanthorpe Airport-NEW SOUTH WALES-AUSTRALIA

### ISSUE THREAD

**Issue by AndrewRG10** [InfiniteFlightAirportEditing/Airports#2348]
I'll get round to finishing boundary and parking spaces

**Comment by AndrewRG10** [comment]
Sent in for review.

**Comment by AndrewRG10** [comment]
May not have this airport fixed before global, it depends on its release date and when I get back, if so will get round to fixing YSPE, however YHOT and YCDR should be fixed and ready.

**Comment by brunocr98** [comment]
That's fine, take the time you need :)

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36936812-9a72a1f6-1ecf-11e8-97b3-81d21d09e189.png)
