### ISSUE TITLE
KCRQ-Mc Clellan-Palomar Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by Epadilla1** [InfiniteFlightAirportEditing/Airports#2349]
- missing terminal parking
- missing FBO parking spaces
- missing lines
- misaligned tarmac 
- misaligned taxiways

**Comment by Epadilla1** [comment]
could I be assigned to this thx

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34699865-60963848-f4a5-11e7-8a94-5c1d305216da.png)
