### ISSUE TITLE
KCLT-Charlotte Douglas International Airport-NORTH CAROLINA-USA

### ISSUE THREAD

**Issue by Swang007** [InfiniteFlightAirportEditing/Airports#235]
Needs more accurate gate parking lines, more gate options at least? Basically needs a do-over if anyone wants to do this one.

**Comment by JohnPreston21** [comment]
Completed by Axel

**Comment by Swang007** [comment]
@kilt46

**Comment by kilt46** [comment]
redoing taxiways

**Comment by kilt46** [comment]
Airport reworked

**Comment by henrikbg** [comment]
Updated ATC frequencies as per airnav.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17267320/772aad16-55cb-11e6-9697-567dd0574894.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17267324/8124eab6-55cb-11e6-9359-7a27beefdea2.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17457934/82f513d4-5bca-11e6-99ef-d889df0e3232.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17457954/b617231a-5bca-11e6-8722-33f7eab7096e.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17457958/c30d3b9a-5bca-11e6-8449-ab4b40bb7c6a.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17457964/e3501850-5bca-11e6-93ba-c61776a5e0fa.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17457971/ee2ba8fc-5bca-11e6-9695-d1054e0215da.png)

**Comment by brunocr98** [comment]
Renovations and updates in progress

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/47617571-7b193800-da96-11e8-86d7-73538202e6a1.png)
