### ISSUE TITLE
KRDR-Grand Forks AFB-NORTH DAKOTA-USA

### ISSUE THREAD

**Issue by ewanfleming** [InfiniteFlightAirportEditing/Airports#2350]
Needs redoing, according to a beta tester. I'll take it. https://community.infinite-flight.com/t/global-flight-beta-testers-tracking-thread/98197/10952

10k

**Comment by ewanfleming** [comment]
'I'll take it.'
@bavAVIA what part of that did you not understand?

**Comment by ewanfleming** [comment]
Not even bothering with an assignment then?

**Comment by ewanfleming** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31045591-c77ea5c4-a5ac-11e7-8229-3b8e86f34c84.png)

**Comment by kilt46** [comment]
KRDR Offset!
![image](https://user-images.githubusercontent.com/14023167/32994405-7e628dcc-cd2c-11e7-9db3-44d149ac8c1f.png)

**Comment by ewanfleming** [comment]
Completely forgot about this. Fixed and sent in.

**Comment by dushyants19** [comment]
:ewan:
