### ISSUE TITLE
YHOT

### ISSUE THREAD

**Issue by AndrewRG10** [InfiniteFlightAirportEditing/Airports#2353]
Highest airport in Australia, in a poor condition, I shall get it done in the next few hours to a day

**Comment by AndrewRG10** [comment]
Sent in for review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31307274-3d899390-ab26-11e7-9829-d37f259f1942.png)
