### ISSUE TITLE
RJAN-Niijima Aiprort-TOKYO-JAPAN

### ISSUE THREAD

**Issue by Yifan081** [InfiniteFlightAirportEditing/Airports#2354]
♻️

**Comment by ryu12332** [comment]
Progress?

**Comment by Yifan081** [comment]
I've given up editing for now. Thanks

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/37181246-d3b4f876-22f1-11e8-83ec-ff46d427dd91.png)
