### ISSUE TITLE
EDVW-Hameln-Bad Pyrmont Airport-NIEDERSACHSEN-GERMANY

### ISSUE THREAD

**Issue by Marsiana7** [InfiniteFlightAirportEditing/Airports#2357]
I‘ll do it.

**Comment by Marsiana7** [comment]
I accidentally put the wrong ICAO code in the title. Now its correct.

**Comment by Marsiana7** [comment]
Send in for review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30997597-9e76308a-a48e-11e7-8ae8-56a2f32055c6.png)
