### ISSUE TITLE
KSTC-St. Cloud Regional Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by Epadilla1** [InfiniteFlightAirportEditing/Airports#2358]
♻️

**Comment by Epadilla1** [comment]
easy fixed, sending in the apt.dat already, could I get assigned to this just in case?

**Comment by Adrien-Z** [comment]
Duplicate of #30.

**Comment by mbmhwue148** [comment]
I'll redo it.

**Comment by ryu12332** [comment]
You have 5 assigned issues including this. Are the other 4 in review? If not would you like to be unassigned from other ones or this one?

**Comment by mbmhwue148** [comment]
2 of them are in review (ZSSS, KSPS), I'm currently redoing one (ZSHC, 70% complete) and I am assigned to one I should not be assigned on anymore (KDFW, reworked an apron + some stands)

**Comment by ryu12332** [comment]
Finish ZSHC, then we can assign you.

**Comment by mbmhwue148** [comment]
Can't I redo 3 max at the same time?

**Comment by ryu12332** [comment]
Yes. 2 in review + ZSHC = 3. A 4th can be assigned _only_ if 3 others are in review.

**Comment by mbmhwue148** [comment]
Allright, will finish ZSHC first.

**Comment by mbmhwue148** [comment]
ZSHC is finished and in review. Now, I'll do this one :)

**Comment by kilt46** [comment]
Please check runway lighting - PAPIs
![image](https://user-images.githubusercontent.com/14023167/42717481-ee3b874e-86c6-11e8-8f69-87a86921ae4a.png)

**Comment by kilt46** [comment]
Suggest this portion of the hangar does not house aircraft (National Guard area)
![image](https://user-images.githubusercontent.com/14023167/42717606-d6c77f90-86c7-11e8-8bca-15dbbdbe8209.png)

**Comment by kilt46** [comment]
Also here!
![image](https://user-images.githubusercontent.com/14023167/42717706-89cd772a-86c8-11e8-89ec-01af9c425c48.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42724450-f78dddb2-8737-11e8-9a20-411105e2aefe.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111979411-0ade3780-8ad3-11eb-80ad-7494a9ab80e5.png)
