### ISSUE TITLE
GQNO-Nouakchott Airport-NOUAKCHOTT-MAURITANIA

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#2359]
Nouakchott (Super quick update) It's not my usual standard of edit, but it is usable anyway.

**Comment by kilt46** [comment]
Nouakchott International Airport (ICAO: GQNN) (Arabic: مطار نواكشوط الدولي‎‎) was an airport located in Nouakchott, It closed in June 2016 upon the opening of Nouakchott–Oumtounsy International Airport, 25 kilometres (16 mi) north of the city.
![image](https://user-images.githubusercontent.com/14023167/30783556-70168104-a10a-11e7-87f4-a95cf68d9ed4.png)
![image](https://user-images.githubusercontent.com/14023167/30783563-8161838c-a10a-11e7-8c5d-e965982fee9c.png)

**Comment by JcFl4** [comment]
There's no imagery for the new one, so I'll leave this open to anyone for the future.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/35252654-17dc585a-ffa7-11e7-8e36-4601abd25a2c.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/69487132-a013e200-0e33-11ea-9140-82b54f7e55a7.jpg)
