### ISSUE TITLE
RJSC-Yamagata Airport-YAMAGATA-JAPAN

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#2366]
♻️

**Comment by MajorTomMueller** [comment]
http://www.ais-asecna.org/pdf/atlas/guineeequ/bata/pdf/bata-00v.pdf

**Comment by benlenahan** [comment]
Sent in for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36705115-2419bed0-1b29-11e8-9b4f-9b2e7830af8a.png)
