### ISSUE TITLE
DNKN-Mallam Aminu Kano Airport-KANO-NIGERIA

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#2367]
Kano, Nigeria

**Comment by ewanfleming** [comment]
I'll take this one.

**Comment by ewanfleming** [comment]
Cheers @carmichaelalonso and @ryu12332

**Comment by dushyants19** [comment]
@carmichaelalonso dont try, we'll take care of this

**Comment by ewanfleming** [comment]
Well, at least he tried. 😜

**Comment by ewanfleming** [comment]
Sent in for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31637135-e8e8201c-b292-11e7-87d0-17a88343ccc6.png)

**Comment by brennanhackard** [comment]
- new terminal and apron need to be added
- several taxiways are snapped to themselves
- SE apron is missing several spawns
- hangars need spawns
- missing a few approach frequencies
- spawn names need to be changed from all caps

Up for grabs.
