### ISSUE TITLE
EDDK-Koln/Bonn Airport-NORDRHEIN-WESTFALEN-GERMANY

### ISSUE THREAD

**Issue by AxelBeder** [InfiniteFlightAirportEditing/Airports#237]
Added lines, taxiways...

**Comment by kilt46** [comment]
Main Terminal Buildings added

**Comment by rednaxela796** [comment]
I'll rework parking lines and other lines and details

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20579873/cb34f22a-b194-11e6-910c-266ed719190e.png)

**Comment by kilt46** [comment]
Gates have changed considerably
![image](https://user-images.githubusercontent.com/14023167/51876659-f48f2380-232e-11e9-941d-bf5b2a0b6345.png)

**Comment by moritzbabl** [comment]
Sounds like a job for my winter break 🤓

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59353439-5dcd6d00-8cf9-11e9-8e47-08af4b342e59.jpg)
