### ISSUE TITLE
KCPS-St Louis Downtown-ILLINOIS-USA

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#2375]
I will take this one... Part of Project Delta :)

**Comment by MajorTomMueller** [comment]
@brandon1419 any progress?

**Comment by brandon1419** [comment]
Sorry for being inactive. I think I was almost done with this one... I’ll take a look tomorrow when I’m back at my desk. :)

**Comment by MajorTomMueller** [comment]
@brandon1419 are you sure you are finish this anytime?

**Comment by brunocr98** [comment]
Looks like the user deleted his account, so this is now available.

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by CaptainCameron** [comment]
I can take this one.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/89112757-792f9600-d42d-11ea-9f58-f31dc8a302fb.png)
