### ISSUE TITLE
KLSN-Los Banos Municipal Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by twocflyer** [InfiniteFlightAirportEditing/Airports#2376]
I will take this one. I got approval from a supervisor to start.  I sent my email to join.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32144047-f636d644-bc80-11e7-8e6b-a459e8a3d9d3.png)
