### ISSUE TITLE
LICD-Lampedusa Airport-SICILIA-ITALY

### ISSUE THREAD

**Issue by Marsiana7** [InfiniteFlightAirportEditing/Airports#2378]
I‘ll try to make this one.

**Comment by Marsiana7** [comment]
Send in for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31155612-0be13a22-a875-11e7-9744-676555b96534.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/70487971-dad57580-1ad5-11ea-9b30-4d29c86ce306.jpg)
