### ISSUE TITLE
LFBH-La Rochelle Airport-CHARENTE-MARITIME-FRANCE

### ISSUE THREAD

**Issue by Tamz00** [InfiniteFlightAirportEditing/Airports#2379]
Low Priority. Will be done within the next few hours.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31058429-f47f1650-a6b8-11e7-922b-1b3dc5a647ef.png)
