### ISSUE TITLE
EGGW-London Luton Airport-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by AxelBeder** [InfiniteFlightAirportEditing/Airports#238]
Adding lines, taxiways...

**Comment by kilt46** [comment]
Great job Axel. I removed an extraneous gate from model and mailed in

**Comment by carmichaelalonso** [comment]
Will wants to do _minor_ fixes, including removing hashed areas.

**Comment by Will171** [comment]
Will also be re-aligning the taxiway lines/taxiways

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17250810/a116019e-556b-11e6-8886-5cc4e68bfb75.png)

**Comment by AxelBeder** [comment]
Please don't do it, I prefer to do it myself.

**Comment by Will171** [comment]
do u want me to send you the file i have been working on?

**Comment by Will171** [comment]
what's going on with this airport? Have the changes on google earth been done?

**Comment by Will171** [comment]
if anyone isn't currently doing this airport i would like to do it.

**Comment by bavAVIA** [comment]
Nobody is working on it I guess...

**Comment by ItsW1ll** [comment]
Sent for review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29644416-78b33b00-883b-11e7-81c4-764e82f18d4a.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50451401-5eb04500-08f9-11e9-86b0-31164c90e238.png)

**Comment by kilt46** [comment]
Duplicates removed, buildings removed

**Comment by ItsW1ll** [comment]
Will be adding the new taxiway Bravo taxiway along with various stand alterations

**Comment by RyanEpps** [comment]
![EGGW](https://user-images.githubusercontent.com/20650961/57655825-d4653680-75a4-11e9-9291-01d75525e808.png)

**Comment by ItsW1ll** [comment]
Changing runway designators and adding tax F
