### ISSUE TITLE
LEVC-Valencia Airport-VALENCIA-SPAIN

### ISSUE THREAD

**Issue by Marsiana7** [InfiniteFlightAirportEditing/Airports#2380]
Suggestion. 10k ft Runway.

**Comment by MajorTomMueller** [comment]
Ok, will take this one.

**Comment by MajorTomMueller** [comment]
send to review

**Comment by moritzbabl** [comment]
added

**Comment by MajorTomMueller** [comment]
![levc-overview](https://user-images.githubusercontent.com/26853210/31942968-6f4bd876-b8c7-11e7-9ed1-e76da583a2d4.jpeg)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32144615-77831246-bc89-11e7-9fa5-e14da34f3ccb.png)

**Comment by MajorTomMueller** [comment]
Hi @kilt46 
Something wrong with the pic before?

**Comment by MajorTomMueller** [comment]
Ah, identified the difference myself.

**Comment by MajorTomMueller** [comment]
boundary

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46576046-dae45d80-c986-11e8-8a8d-d50e7b5e510b.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46576065-71b11a00-c987-11e8-96eb-2303afc695dd.png)

**Comment by MajorTomMueller** [comment]
Spawn names

**Comment by MajorTomMueller** [comment]
spawn names fixed

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48678342-92a08980-eb47-11e8-874c-3d37ad7077ee.png)
