### ISSUE TITLE
KRBQ-Roben-Hood Airport-MICHIGAN-USA

### ISSUE THREAD

**Issue by ryu12332** [InfiniteFlightAirportEditing/Airports#2381]
Part of Project Michigan

**Comment by kilt46** [comment]
Something missing here
![image](https://user-images.githubusercontent.com/14023167/30939480-2ba6351e-a3a3-11e7-9beb-80a021a10bf2.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30942957-75dc1a1c-a3b3-11e7-9d33-fc3f923cc679.png)
