### ISSUE TITLE
EDXD-Bohmte-Bad Essen Airport-NIEDERSACHSEN-GERMANY

### ISSUE THREAD

**Issue by Marsiana7** [InfiniteFlightAirportEditing/Airports#2385]
I‘ll do it.

**Comment by Marsiana7** [comment]
Send in for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31055885-62d7ca40-a68f-11e7-87a6-025b416ba5ad.png)
