### ISSUE TITLE
ROIT-Oitakenou Airport-OITA-JAPAN

### ISSUE THREAD

**Issue by alchonub** [InfiniteFlightAirportEditing/Airports#2391]
♻️

**Comment by brunocr98** [comment]
This code is no longer in use. There’s an issue for the new airport #2359 

https://en.m.wikipedia.org/wiki/Nouakchott_International_Airport

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36936618-5b0d92b6-1ecd-11e8-9d4c-ee4e61d11240.png)
