### ISSUE TITLE
UKLR-Rivne Airport-RIVNE-UKRAINE

### ISSUE THREAD

**Issue by Drake9980** [InfiniteFlightAirportEditing/Airports#2394]

**Comment by MajorTomMueller** [comment]
@Drake9980 any progress?

**Comment by moritzbabl** [comment]
member inactive, up for grabs

**Comment by johanneskkl** [comment]
Will take this. Other open airports awaiting review

**Comment by johanneskkl** [comment]
sent in

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/39097132-dfaf5faa-461d-11e8-84c8-fca6d8ea0967.png)
