### ISSUE TITLE
OEAB-Abha Airport-ASIR-SAUDI ARABIA

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#2395]
Suggestion for anyone to take.

**Comment by johanneskkl** [comment]
will take this. thanks

**Comment by moritzbabl** [comment]
addedd

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32871795-c5cf993e-ca48-11e7-8e9e-70a9066defe7.png)

**Comment by ECoops-123** [comment]
@suhasjatla will redo this to add:

* Markings to empty ramp
* Improve gate area
* Improve runway and runway surface
* Remove excess taxiways

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114934258-4d0f4600-9dff-11eb-92de-866bd5df6cc1.png)
