### ISSUE TITLE
KDEN-Denver International Airport-COLORADO-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#24]

**Comment by kilt46** [comment]
Fixes to snap points adjacent to 34R

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19006911/bccf9222-8727-11e6-9e1e-57f461e8feed.png)

**Comment by brunocr98** [comment]
Airport needs renovations: no shoulders on taxiways, missing gates, some unsnapped lines and other things (doing this with permission).

**Comment by brunocr98** [comment]
Reviewing gates.

https://community.infiniteflight.com/t/kden-limited-heavy-gates/311983

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56471353-03a9dd00-6417-11e9-882d-11530fe45ede.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/60388047-63a9a900-9a82-11e9-9d00-d1689d5919f8.jpg)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/60388578-2fd28180-9a8a-11e9-8313-f2e6acbbc03c.jpg)
