### ISSUE TITLE
TQPF-Clayton J Lloyd International Airport-THE VALLEY-ANGUILLA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#240]

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21122995/75c899e8-c09b-11e6-98d0-41bdf70c0359.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33153482-904429ce-cfa7-11e7-9b40-fee675ca86e1.png)

**Comment by Balloonchaser** [comment]
Sent to OR - @MajorTomMueller you spelled Caribbean wrong my friend ;)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48681801-55012800-eb6a-11e8-88cd-2ddc6d8e63cb.png)
