### ISSUE TITLE
CYYR-Goose Bay Airport-NEWFOUNDLAND AND LABRADOR-CANADA

### ISSUE THREAD

**Issue by Tamz00** [InfiniteFlightAirportEditing/Airports#2403]
After recent events, it feels right to have this for ‘emergencies’. Will do this

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32391167-1617f9f8-c09f-11e7-9639-6fce90b9877f.png)
