### ISSUE TITLE
XNO1-Haren-Dankern Airport-NIEDERSACHSEN-GERMANY

### ISSUE THREAD

**Issue by Marsiana7** [InfiniteFlightAirportEditing/Airports#2404]
I‘ll do it. (This airport is not in the repo yet)

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31303244-c8a29d34-aacf-11e7-9d3d-a9f773a644a9.png)
