### ISSUE TITLE
EDLI

### ISSUE THREAD

**Issue by johanneskkl** [InfiniteFlightAirportEditing/Airports#2406]
*@dushyants19 told me I could open more issues as long all the other are awaiting review.*
Bielefeld airfield, Germany, NRW.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31303208-4d08237e-aacf-11e7-815b-f5a8d1ddc738.png)
