### ISSUE TITLE
CZMT-Masset Airport-BRITISH COLUMBIA-CANADA

### ISSUE THREAD

**Issue by DelsterX** [InfiniteFlightAirportEditing/Airports#2407]
I will take this one.

**Comment by DelsterX** [comment]
Sent in for review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31306997-092dc738-ab21-11e7-96f4-28c3725c5f0c.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50725071-8bb0e480-10bd-11e9-8f92-8671529ae0e2.png)

**Comment by kilt46** [comment]
Duplicate spawn fixed. Buildings removed
