### ISSUE TITLE
KMGY-Dayton-Wright Brothers Airport-OHIO-USA

### ISSUE THREAD

**Issue by netjets-1951** [InfiniteFlightAirportEditing/Airports#2409]
Part of project Ohio.

**Comment by ryu12332** [comment]
It has been 90 days since your assignment, and other airports have been done by you. If you are still working on this please let one of us know, or you may be unassigned. Thanks!

**Comment by netjets-1951** [comment]
As I have told you multiple times before, I don’t currently have the time to do this, but I am going to complete it as soon as I have some free time.

**Comment by netjets-1951** [comment]
Sent in for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38524230-89126124-3c13-11e8-9fcf-1561f05dc840.png)
