### ISSUE TITLE
EBBE-Beauvechain-WALLONIE-BELGIUM

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#241]
This one needs, lines, hold short points, added spawns and spawn corrections

**Comment by justindebord16** [comment]
Im working on it But it's wont let me show I Opened it.

**Comment by JohnPreston21** [comment]
It's already opened.

**Comment by justindebord16** [comment]
How Can I Add the Being Redone Label?

**Comment by JohnPreston21** [comment]
I've already added it and removed suggestion for you :)

**Comment by justindebord16** [comment]
Thanks John. It's finished now.

**Comment by JohnPreston21** [comment]
Have you exported the apt.dat and emailed to Cameron?

**Comment by JohnPreston21** [comment]
Justin completed this one and is now closed

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21334380/9f0a1e5e-c61c-11e6-9903-733a3a999a4f.png)
