### ISSUE TITLE
CYPR-Prince Rupert Airport-BRITISH COLUMBIA-CANADA

### ISSUE THREAD

**Issue by DelsterX** [InfiniteFlightAirportEditing/Airports#2411]
I will do this one.

**Comment by DelsterX** [comment]
Sent for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31863688-9f967868-b716-11e7-9560-8eed31e602d6.png)
