### ISSUE TITLE
YCOM-Cooma Snowy Mountains Airport-NEW SOUTH WALES-AUSTRALIA

### ISSUE THREAD

**Issue by AndrewRG10** [InfiniteFlightAirportEditing/Airports#2414]
Should get this done over weekend

**Comment by AndrewRG10** [comment]
Sent in for review

**Comment by ryu12332** [comment]
Progress?

**Comment by AndrewRG10** [comment]
Well let us say I forgot I told someone I would do this before Global. I honestly have made too much of a mess of it I'll need to delete and start from scratch again. Right now I want to get YSPE done because it's been too long.

**Comment by dushyants19** [comment]
you know you shouldnt be closing issues.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36944985-52817af0-1f6c-11e8-83b0-ee58ee29d909.png)

**Comment by sam2875** [comment]
# Airport Name

Cooma-Snowy Mountains Airport

# Country

Australia

# Improvements

Redone (fixed taxiways, markings, gates)

# Are you working on this airport?

Yes

# Airport Priority

None - Low priority
