### ISSUE TITLE
RJAF-Matsumoto Airport-NAGANO-JAPAN

### ISSUE THREAD

**Issue by LeonVeen** [InfiniteFlightAirportEditing/Airports#2417]
♻️

**Comment by LeonVeen** [comment]
Please let me know I you know a website with all airport charts, I can't find one for SPUR on SkyVector.

**Comment by dushyants19** [comment]
FYI - Skyvector is not reliable and doesn't usually have charts. Use the slash command on slack please

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36936762-f671dbe4-1ece-11e8-999b-cf2dd2ee934e.png)
