### ISSUE TITLE
KEVU-Northwest Missouri Regional Airport-MISSOURI-USA

### ISSUE THREAD

**Issue by SuperPuperSteve** [InfiniteFlightAirportEditing/Airports#2418]
♻️

**Comment by SuperPuperSteve** [comment]
should I set parkings at abadoned aprons?

**Comment by brunocr98** [comment]
I wouldn't if the apron has no use currently. And I suggest you to join our Slack team if you need more help.

**Comment by SuperPuperSteve** [comment]
no, thanks

**Comment by ryu12332** [comment]
Progress?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38173755-f687f016-3588-11e8-81d2-1ad13a57f155.png)
