### ISSUE TITLE
KGEG-Spokane International Airport-WASHINGTON-USA

### ISSUE THREAD

**Issue by mbmhwue148** [InfiniteFlightAirportEditing/Airports#2419]
♻️

**Comment by cptchris** [comment]
Goodluck!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34700118-da8858ce-f4a6-11e7-94e2-2072c7b4c443.png)

**Comment by Czechoslovaki** [comment]
Sent For OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/82482205-d9f53680-9aac-11ea-8488-28fce29ebf2e.jpg)
