### ISSUE TITLE
KEDW

### ISSUE THREAD

**Issue by JohnPreston21** [InfiniteFlightAirportEditing/Airports#242]
Needs taxi-Lines and better ramp parking/spawns. I will begin this one

**Comment by JohnPreston21** [comment]
Completed this one. added taxi-lines with parking spots along with new spawns and corrected current spawn.

**Comment by Swang007** [comment]
https://community.infinite-flight.com/t/typo-on-parking-space-at-kedw/10145

Parking space needs to be renamed. Also, "Parking" should not be in the name of any gate. Infinite Flight automatically adds "Parking:" to the beginning of every spawn point. Snap to Vertices is already enabled, but was never used. A lot of lines are not connected to each other.

**Comment by JohnPreston21** [comment]
Now that we have Wedbing I'll be starting it over.  But will not make the next update.  Thanks @Swang007

**Comment by Swang007** [comment]
Apparently @kilt46 fixed this already? Someone needs to turn on StV

**Comment by JohnPreston21** [comment]
Yup,  he saud he corrected it

**Comment by Swang007** [comment]
You said you were going to start over on it? I don't think he snapped any lines to vertices either

**Comment by kilt46** [comment]
Complete

**Comment by kilt46** [comment]
Modified to yellow/black lines

**Comment by dushyants19** [comment]
https://community.infinite-flight.com/t/edw-rwy-22r/19560

From that picture, I see that hold lines are over the grass also. Needs to be fixed.

**Comment by kilt46** [comment]
Corner piece added to taxiway at 22R. White lines on buildings removed

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32689312-a8d2c742-c6a7-11e7-8423-f15134898f7c.png)
