### ISSUE TITLE
EKST-Sydfyn Tasinge Airport-FYN-DENMARK

### ISSUE THREAD

**Issue by alchonub** [InfiniteFlightAirportEditing/Airports#2421]
A Random Airport I found

**Comment by alchonub** [comment]
Woud be better if recycled, Hard to get Imagery close to the 60 degrees North
@DelsterX @alexpeterson-if  Interested?

**Comment by brunocr98** [comment]
Up for grabs for any proud Canadian.

**Comment by MajorTomMueller** [comment]
recycled

**Comment by MajorTomMueller** [comment]
![ekst-git2](https://user-images.githubusercontent.com/26853210/35446290-8d62d68e-02b4-11e8-9316-751f95ea4066.jpeg)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/35472000-590be092-032c-11e8-8a84-e4ae56394b84.png)
