### ISSUE TITLE
ENOL-Orland Airport-SOR-TRONDELAG-NORWAY

### ISSUE THREAD

**Issue by bensonbaird** [InfiniteFlightAirportEditing/Airports#2424]
♻️

**Comment by ryu12332** [comment]
Progress?

**Comment by moritzbabl** [comment]
Member inactive, up for grabs

**Comment by Will-Burke123** [comment]
I can do it. this would be my first airport and i have watched all the tutorials and i think i am ready to edit an airport

**Comment by MajorTomMueller** [comment]
Recycled

**Comment by MajorTomMueller** [comment]
![enol-git1](https://user-images.githubusercontent.com/26853210/40280853-765fa7a6-5c59-11e8-8c15-dcb5796ba70d.jpg)
