### ISSUE TITLE
LIPA-Aviano Afb-ITALY

### ISSUE THREAD

**Issue by cptchris** [InfiniteFlightAirportEditing/Airports#2425]
Will do this one.

**Comment by ryu12332** [comment]
Progress?

**Comment by MajorTomMueller** [comment]
recycled

**Comment by MajorTomMueller** [comment]
![lipa-git](https://user-images.githubusercontent.com/26853210/39958309-93a392d6-5601-11e8-913d-f47102d5bb26.jpg)
