### ISSUE TITLE
KBJI-Bemidji Regional Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by twocflyer** [InfiniteFlightAirportEditing/Airports#2426]
I'll Take this one.  All ready to send in, just forgot to make an issue.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31856333-c80ca9cc-b683-11e7-9a88-11e864bd27a6.png)

**Comment by brunocr98** [comment]
Being redone.

**Comment by Gabe-Z** [comment]
The airport is now in OR. Thank you to Bruno for assigning me, farewell Bruno!

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/79277657-9fcac080-7e80-11ea-9a50-e237f8f98bda.jpg)
