### ISSUE TITLE
ZHCC-Zhengzhou Xinsheng Airport-HENAN-CHINA

### ISSUE THREAD

**Issue by zren01** [InfiniteFlightAirportEditing/Airports#2428]
Zhengzhou Xinzheng Intl', China

**Comment by zren01** [comment]
has two runways, both above 10,000ft

**Comment by ryu12332** [comment]
Progress?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/39951607-1be9dbc0-5551-11e8-99c1-64da4627ba47.png)

**Comment by kilt46** [comment]
Really nice job Bruno. :)
