### ISSUE TITLE
KNZY-NAS North Island-CALIFORNIA-USA

### ISSUE THREAD

**Issue by justindebord16** [InfiniteFlightAirportEditing/Airports#243]
Redoing KNZY

**Comment by JohnPreston21** [comment]
241 is opened already justin :)

**Comment by justindebord16** [comment]
Oh Ok I see it now. I was having trouble viewing some of these.

**Comment by kilt46** [comment]
This one still looks pretty ugly from the image: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=KNZY

**Comment by kilt46** [comment]
This one was completed:
http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=KNZY

**Comment by IceBlue02** [comment]
https://community.infinite-flight.com/t/call-sign-change-knzy-nas-north-island-socal/20409

Sorting this now.

**Comment by IceBlue02** [comment]
Done and emailed.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21287603/e67c120e-c434-11e6-84fb-08f73813af66.png)

**Comment by brunocr98** [comment]
This airfield will need a redo. Putting this up for grabs for whoever is interested.

**Comment by Oskapew** [comment]
Pick me! ;)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103041447-0fc73580-453c-11eb-9f3d-82c22fed7f9c.png)
