### ISSUE TITLE
1H0-Creve Coeur Airport-MISSOURI-USA

### ISSUE THREAD

**Issue by Marsiana7** [InfiniteFlightAirportEditing/Airports#2430]
♻️

**Comment by ryu12332** [comment]
Progress?

**Comment by moritzbabl** [comment]
member inactive, up for grabs

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/40866026-330aa1ec-65c1-11e8-9dd0-02c85cf7e163.png)
