### ISSUE TITLE
EDHU-Lauenbrück Airfield-NIEDERSACHSEN-GERMANY 

### ISSUE THREAD

**Issue by Marsiana7** [InfiniteFlightAirportEditing/Airports#2431]
I‘ll do it.

**Comment by ryu12332** [comment]
Progress?

**Comment by moritzbabl** [comment]
member inactive, up for grabs

**Comment by johanneskkl** [comment]
Will take this too. All others have been send for review

**Comment by johanneskkl** [comment]
sent in for review

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38134642-937b403c-33d9-11e8-9c2f-12f3b38763a3.png)
