### ISSUE TITLE
RCGI-Lyudao Airport-TAIWAN-TAIWAN

### ISSUE THREAD

**Issue by canoneoswen** [InfiniteFlightAirportEditing/Airports#2432]
Lyudao,Taitung

**Comment by canoneoswen** [comment]
sent for review

**Comment by canoneoswen** [comment]
second review sent.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33534521-6d6e9974-d86d-11e7-910b-0fdf1eeed60e.png)
