### ISSUE TITLE
KMKJ-Mountain Empire Airport-VIRGINIA-USA

### ISSUE THREAD

**Issue by Yifan081** [InfiniteFlightAirportEditing/Airports#2434]
Mountain Empire Airport, Virginia, USA.

**Comment by Yifan081** [comment]
Sent for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32253399-ce9e62d4-be68-11e7-9b9a-a0825eede5a3.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32253785-bf52a6a8-be6a-11e7-8cc2-eb97b31e8d53.png)
