### ISSUE TITLE
SBBE-Belem Airport-PARA-BRAZIL

### ISSUE THREAD

**Issue by lukespotter** [InfiniteFlightAirportEditing/Airports#2439]
I'll make a new SBBE airport to the game.

**Comment by ryu12332** [comment]
Progress

**Comment by lukespotter** [comment]
Hi. I had problems with WED-O-MAKER, it did not work on any of my
computers. Sorry, I'll do it another time, if possible.
#FlySafe

Em 28 de fev de 2018 2:06 AM, "Ryan" <notifications@github.com> escreveu:

**Comment by MajorTomMueller** [comment]
@FellipeEdu are you working on this one?

**Comment by FellipeEdu** [comment]
Will be my next airport to edit, I'm working on the SBPV, but it's taking so long because I'm busy with studies.

**Comment by FellipeEdu** [comment]
Airport redone and already reviewed in peer review. I estimate less than a day to give the final touches and send for OR!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48653013-251a1f00-e9c8-11e8-8ad1-01bf49ab3338.png)
