### ISSUE TITLE
ESSA-Stockholm Arlanda Airport-STOCKHOLM-SWEDEN

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#244]
RWY hold short  needs to be removed.  I'll do this one

**Comment by JohnPreston21** [comment]
Removed Hold Short Spawns 07, 34R, & 16R. Sending to master now

**Comment by Rotate-FDS** [comment]
ATIS frequency

**Comment by samuelandersson** [comment]
Duplicate

**Comment by samuelandersson** [comment]
And added buildings as well as stands.

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/59f15154bef3d1f461aeac4fd5716d5a3cf25b88)

**Comment by kilt46** [comment]
Would suggest the centre lines need a little more detail. I show model v satellite.
![image](https://cloud.githubusercontent.com/assets/14023167/16972901/b72c4b88-4df4-11e6-80d2-4c1a3004d695.png)

**Comment by samuelandersson** [comment]
@kilt46 do you mean the centreline at the actual stand or the one that runs along all of the stands?

**Comment by samuelandersson** [comment]
Fixed.

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/72c97e13fefda5c068158fe8b21a5f98c0d71305)

**Comment by kilt46** [comment]
BASELINE
![image](https://cloud.githubusercontent.com/assets/14023167/17233051/479a0d00-54f2-11e6-984b-c839ef759e1f.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17234331/6b47144a-54fd-11e6-8616-80d19688adc8.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17234887/54bf0098-5502-11e6-9a39-0660455b8550.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17234899/7176ab78-5502-11e6-8706-6e7ecd643f06.png)

**Comment by kilt46** [comment]
Missing ATC data!!!

**Comment by PaulNielsen** [comment]
Will fix the ATC data! :)

**Comment by PaulNielsen** [comment]
Uhh, I just opened it. There is already 5 frequencies in there with the correct names and numbers.

**Comment by kilt46** [comment]
ATC ITEMS missing  ON UPLOADED FILE
![image](https://cloud.githubusercontent.com/assets/14023167/18495396/364befc6-79e3-11e6-8c88-4b3f36990f66.png)

**Comment by PaulNielsen** [comment]
Hmm, maybe I got a bit confused when I used the WED beta, I will look into it again today.

**Comment by PaulNielsen** [comment]
My bad, fixed.

https://github.com/InfiniteFlightAirportEditing/Airports/commit/e89dee080d75554f45c8ccdabc4bdb5747408bc1

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18534492/43ba4bf2-7ab1-11e6-8481-8373f2a36edc.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18534494/4e7735e6-7ab1-11e6-9b19-c3c257379d87.png)

**Comment by brunocr1050** [comment]
Re-opening this airport and putting it up for grabs. Needs a complete overhaul (runways, taxiways, spawns, taxilines, etc etc etc). ERSI imagery seems to be up to date than Google and Bing (but it may be a bit blurry).

**Comment by MajorTomMueller** [comment]
The only source that has the new apron E that I found is Yandex, but that has feasible quality.
Airport data and charts are available with free registration at 
https://aro.lfv.se/

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123345902-b5278a00-d51c-11eb-8619-464b501e9593.png)
