### ISSUE TITLE
YBHI-Broken Hill Airport-NEW SOUTH WALES-AUSTRALIA

### ISSUE THREAD

**Issue by ewanfleming** [InfiniteFlightAirportEditing/Airports#2440]
Will be working on this for @bensonbaird 's project Australia.

**Comment by ewanfleming** [comment]
Sent in for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32145606-7cd3cf5a-bc99-11e7-9277-d8587248a0bb.png)
