### ISSUE TITLE
DTMB

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#2441]
Monastir

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31852307-0565c374-b63b-11e7-95a0-8d264dd9255f.png)

**Comment by MajorTomMueller** [comment]
Spanw size and naming updated, buildings removed.
http://www.oaca.nat.tn/index.php?id=760&L=2

![DTMB-git](https://user-images.githubusercontent.com/26853210/102019411-6037d980-3d6b-11eb-8eff-92e7f8b2e5c3.png)
