### ISSUE TITLE
RCLY-Lanyu Airport-TAIWAN-TAIWAN

### ISSUE THREAD

**Issue by canoneoswen** [InfiniteFlightAirportEditing/Airports#2442]
Lanyu,Taitung

**Comment by canoneoswen** [comment]
sent for review

**Comment by canoneoswen** [comment]
sent for review

**Comment by canoneoswen** [comment]
second review sent.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33532013-ff3d540c-d85a-11e7-9ecc-5722e634ab13.png)
