### ISSUE TITLE
EKTD-Tonder Airport-SOUTH JUTLAND-DENMARK

### ISSUE THREAD

**Issue by GoldenSpotter** [InfiniteFlightAirportEditing/Airports#2443]
Part of [Project New England](https://community.infinite-flight.com/t/project-new-england/43169).

**Comment by MajorTomMueller** [comment]
recycled

**Comment by MajorTomMueller** [comment]
![ektd-git4](https://user-images.githubusercontent.com/26853210/35485965-65fc36c6-0467-11e8-9237-15472a8ee86c.jpeg)

**Comment by MajorTomMueller** [comment]
-boundary fix
-Buildings removed
-Hangar Floors added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46257867-f3381200-c486-11e8-849d-f06309b9e11a.png)
