### ISSUE TITLE
EHGG-Groningen Eelde Airport-DRENTHE-NETHERLANDS

### ISSUE THREAD

**Issue by rohaimkhedr** [InfiniteFlightAirportEditing/Airports#2447]

**Comment by rohaimkhedr** [comment]
Can someone assign me and do the Labels

**Comment by ryu12332** [comment]
Progress?

**Comment by bamaflying** [comment]
No problem! Also just please keep me updated on my application and line tests. 

      Thanks,
              Mason

**Comment by rohaimkhedr** [comment]
I did was a bit inactive now i will rework this airfield

**Comment by rohaimkhedr** [comment]
just found out i lost all of my files so i cannot continue i will close this and someone else can go with this sorry

**Comment by johanneskkl** [comment]
will take this one

**Comment by johanneskkl** [comment]
sent in

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38711665-a5ca8c12-3e8c-11e8-80f5-39f83a16d0b7.png)
