### ISSUE TITLE
KFAR-Hector International Airport-NORTH DAKOTA-USA

### ISSUE THREAD

**Issue by LoganIsLogan13** [InfiniteFlightAirportEditing/Airports#2448]

**Comment by ryu12332** [comment]
Progress?

**Comment by LoganIsLogan13** [comment]
Still Working On It. It’s More Of A When I Bored I’ll Work On It. I Got A
New Computer And I Need To Set Up The Programs On It. I Was Having Problems
With The Satalite Map For The Background Not Being In The Right Spot But
Otherwise I’m Still Working On It.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/43040123-43250a42-8d01-11e8-8b2d-96bdf847bcc0.png)
