### ISSUE TITLE
EBBR-Brussels Airport-VLAANDEREN-BELGIUM

### ISSUE THREAD

**Issue by Swang007** [InfiniteFlightAirportEditing/Airports#245]
Nothing to see here! Move along :)

**Comment by kilt46** [comment]
Reworking Gates: Only 15 gates in existing airport. This is a Bravo. My next big rework   :)

**Comment by kilt46** [comment]
All Main Terminal Gates added: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=EBBR

**Comment by kilt46** [comment]
Integration of Axel Airport and gates/buildings

**Comment by samuelandersson** [comment]
Small fixes, see [commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/26ec9961cc00c271a6566a661c620898ce7fc675) for details.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17641017/72a143d6-60d4-11e6-9b4f-31e6702e1fb0.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17641029/0d52b57c-60d5-11e6-87e6-b867f7b57c5c.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17641032/1c56f894-60d5-11e6-966d-5edf75858faf.png)

**Comment by dushyants19** [comment]
Needs runway number change, I'll fix it

**Comment by liamkirky** [comment]
Someone open this as im adding the taxi lines and snapping them

**Comment by liamkirky** [comment]
First airport sent in for review hopefully taxiline issue is gone

**Comment by dushyants19** [comment]
No need to, there aren't taxilines there IRL

**Comment by ryu12332** [comment]
ISSUE: Runway 20/02 is runway 19/01 since late 2013.

**Comment by dushyants19** [comment]
I fixed this ages ago, guess it got lost in things

https://github.com/InfiniteFlightAirportEditing/Airports/commit/830645f0516c34f1e2a424107ca360822f02366f

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50044524-524f0100-004a-11e9-92e6-e2a6def6ffc9.png)

**Comment by kilt46** [comment]
Reworked 312-328. Duplicates removed. Buildings removed

**Comment by kilt46** [comment]
Reworking whole airport
