### ISSUE TITLE
MRGP-Guapiles Airport-LIMON-COSTA RICA

### ISSUE THREAD

**Issue by alchonub** [InfiniteFlightAirportEditing/Airports#2452]
RECYCLED AGAIN ♻️

**Comment by alchonub** [comment]
New Islamabad Airport*

**Comment by alchonub** [comment]
Since Its not opened irl It would be fitting on the suggestions tab

**Comment by netjets-1951** [comment]
I’ll take this one when KYIP is accepted

**Comment by netjets-1951** [comment]
I'll take this one

**Comment by ryu12332** [comment]
Since you don't have enough time to complete your 2 other assigned airports, we are freeing you up from this much larger airport. Let us know when those 2 are completed, and you can be assigned again provided no one else has taken this airport. Thanks!

**Comment by netjets-1951** [comment]
Just to let you know, I have finished both airports. I'll be sending them in tomorrow. You can reassign me now. I don't see why you feel the need to target me, I never did anything to you.

**Comment by netjets-1951** [comment]
Ryan always has to be right doesn't he

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/37238365-8078f172-23ea-11e8-82f5-9929d81ab31c.png)
