### ISSUE TITLE
OPRN

### ISSUE THREAD

**Issue by luqmanhussain** [InfiniteFlightAirportEditing/Airports#2454]
Wrong frequencies and missing taxiways
Ill do it.

**Comment by alchonub** [comment]
Luqman please stop making Issues on Github without joining the team, You need to be in the team to at least get your Airport accepted

**Comment by alchonub** [comment]
And make commits*

**Comment by Tamz00** [comment]
Luqman wishes to be unassigned from OPRN too so I'll take over

**Comment by Tamz00** [comment]
Sent.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32920848-a0a30792-caf0-11e7-981d-a06c16fdfe03.png)
