### ISSUE TITLE
YMIA-Mildura Airport-VICTORIA-AUSTRALIA

### ISSUE THREAD

**Issue by ewanfleming** [InfiniteFlightAirportEditing/Airports#2455]
Part of Project Australia, will do this.

**Comment by ewanfleming** [comment]
Sent in for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32253628-f3b0b59e-be69-11e7-89f1-9256c1f5b32a.png)
