### ISSUE TITLE
LCPH-Paphos Airport-PAPHOS-CYPRUS

### ISSUE THREAD

**Issue by liamkirky** [InfiniteFlightAirportEditing/Airports#2456]
I'll be doing this one if it's ok? 
Since it hasn't been done yet

**Comment by liamkirky** [comment]
Hi may I be unassigned from this airport as my laptop doesn't have any free space left so I can't save it anymore.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/35602632-e5a7359a-05fe-11e8-9378-40348a8fe236.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51801750-6a986b00-2207-11e9-8b17-4ccba636d470.png)
