### ISSUE TITLE
LEMP-Aeródromo Los Martines Del Puerto-MURCIA-SPAIN

### ISSUE THREAD

**Issue by ewanfleming** [InfiniteFlightAirportEditing/Airports#2457]
https://community.infinite-flight.com/t/broken-airport-come-to-lemp-on-the-casual-server/156530?u=ewanfleming
I'll do this. 2 of my three assigned airport are in for review.

**Comment by ewanfleming** [comment]
Sent in for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32145379-80bd6c56-bc95-11e7-8e85-d95357e68b0b.png)
