### ISSUE TITLE
EGBM-Tatenhill Airport-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by luqmanhussain** [InfiniteFlightAirportEditing/Airports#2459]
Missing taxi ways
I'll do it

**Comment by luqmanhussain** [comment]
I dont have time to dedicate to this airfield so closing issue for now.

**Comment by brunocr98** [comment]
Issues are only closed when the airport is done.

**Comment by henryhunt1158** [comment]
Ill do it

**Comment by moritzbabl** [comment]
member inactive, up for grabs

**Comment by ItsW1ll** [comment]
Might as well reduce the suggestions. Stick me on this Bruno!

**Comment by ItsW1ll** [comment]
All fixed. Sent for review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56098101-859f8080-5ec2-11e9-999e-5f82bcea544a.png)
