### ISSUE TITLE
LFPG-Charles de Gaulle Airport-ILE DE FRANCE-FRANCE

### ISSUE THREAD

**Issue by Swang007** [InfiniteFlightAirportEditing/Airports#246]
Will add ATIS frequency

**Comment by carmichaelalonso** [comment]
More gates needed:
https://community.infinite-flight.com/t/paris-cdg-gates/6214

**Comment by JohnPreston21** [comment]
This one has spawns no?

**Comment by AxelBeder** [comment]
Started reworking this one.

**Comment by dushyants19** [comment]
https://community.infinite-flight.com/t/missing-taxi-lines/49000?u=dush19

Ill fix it

**Comment by dushyants19** [comment]
Done. :)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19412513/e4e1bb52-92dd-11e6-9f61-69058581c36e.png)
![image](https://cloud.githubusercontent.com/assets/14023167/19412523/02d285c4-92de-11e6-8163-0821a86b06e0.png)
![image](https://cloud.githubusercontent.com/assets/14023167/19412526/0fc97a9e-92de-11e6-9b5f-0f8304f47707.png)

**Comment by kztmtn** [comment]
Sent in for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/75723802-c4494f80-5cbb-11ea-9e4c-6e5c8d7df06d.jpg)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/79482661-81330980-7fe7-11ea-856d-0d8e055fd4af.jpg)
