### ISSUE TITLE
CYQL-Lethbridge Airport-ALBERTA-CANADA

### ISSUE THREAD

**Issue by alexpeterson-if** [InfiniteFlightAirportEditing/Airports#2462]
I'd like to do this one as my first project for IFAE. Runway is less than 10,000 feet.

**Comment by alexpeterson-if** [comment]
Sent for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32143575-7a936b8a-bc79-11e7-8ae4-ee3eb965ecbe.png)
