### ISSUE TITLE
CYBW-Calgary Springbank Airport-ALBERTA-CANADA

### ISSUE THREAD

**Issue by alexpeterson-if** [InfiniteFlightAirportEditing/Airports#2463]
I'll do this one. Runway is less than 10k.

**Comment by alexpeterson-if** [comment]
Sent for review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32676360-f2e26dd4-c61f-11e7-88ab-16928b1e1a99.png)
