### ISSUE TITLE
YLRE-Longreach Airport-QUEENSLAND-AUSTRALIA

### ISSUE THREAD

**Issue by ewanfleming** [InfiniteFlightAirportEditing/Airports#2466]
Part of Project Australia.

**Comment by ewanfleming** [comment]
Sent in for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32695053-11bd6892-c717-11e7-9226-bd11c0a2a04a.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32695248-96121cf6-c71b-11e7-873f-a7b11df77ceb.png)
