### ISSUE TITLE
NGFU-Funafuti International Airport-FUNAFUTI-TUVALU

### ISSUE THREAD

**Issue by tranquil-skyflyer** [InfiniteFlightAirportEditing/Airports#2467]
Funafuti Int'l
Capital of Tuvalu. 
Yes, this place actually exists.
I'll do this one.

**Comment by tranquil-skyflyer** [comment]
Submitted for review.

**Comment by tranquil-skyflyer** [comment]
Resubmitted!

**Comment by johanneskkl** [comment]
_*(4 months later)*_
any progress here?

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by danisrils39** [comment]
I was just wondering if this airport was done yet. Always love these tropical airports. Sign me up!

**Comment by brunocr98** [comment]
This was freed up so...it's yours.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/49051605-39230500-f1ae-11e8-85d3-ac50ef404b96.png)
