### ISSUE TITLE
KSZL-Whiteman AFB Airport-MISSOURI-USA

### ISSUE THREAD

**Issue by Daniyal03** [InfiniteFlightAirportEditing/Airports#2468]
reuse.

**Comment by brunocr98** [comment]
Please refer to the issue #2275

**Comment by brunocr98** [comment]
And please **search** before creating an issue. Thanks!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/35187974-43c1314e-fdf3-11e7-9d1f-1ff68cf69542.png)

**Comment by MajorTomMueller** [comment]
![KSZL-git](https://user-images.githubusercontent.com/26853210/102713287-24e36080-42bf-11eb-97db-828e7fc12213.png)
