### ISSUE TITLE
 ZGHA-Changsha Huanghua International Airport-HUNAN-CHINA

### ISSUE THREAD

**Issue by carlrick2007** [InfiniteFlightAirportEditing/Airports#2469]
REUSED.

**Comment by Blently** [comment]
Hey @carlrick2007 this not the place to report any issues or comments about the Training Serve in , this proyect is dedicated to creating and improving airport layouts in Infinite Flight. If there’s any issues that you will like to report please vist the [forum](www.community.infinite-flight.com) and we apologize fro any inconvenience.

Thanks

**Comment by carlrick2007** [comment]
Okay

**Comment by carlrick2007** [comment]
but the taxi ways are not connecting in one part of the airport

**Comment by brunocr98** [comment]
There's no need to create an issue for that, you could easily create a support topic in the IF forum, and someone one (specially the editor of the airport) would proceed to do the changes. If you're not familiar with this site and the functions done in here, I suggest you not to touch anything. Thanks.

**Comment by moritzbabl** [comment]
ZGCS is the code for Changsha Datuopu Airport, ZMUB for Chinggis Khaan International Airport

**Comment by brunocr98** [comment]
Stop changing the title of the issue. There is an issue for ZMUB already

**Comment by CNwyang** [comment]
I would like to take this airport.

**Comment by CNwyang** [comment]
sent for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36819434-2060531c-1caf-11e8-99b4-15ec4da38cbc.png)

**Comment by MajorTomMueller** [comment]
@AnthonyCK Pleas post reference for new runway here. Thanks

**Comment by AnthonyCK** [comment]
[ZGHA-2.pdf](https://github.com/InfiniteFlightAirportEditing/Airports/files/4791576/ZGHA-2.pdf)

**Comment by AnthonyCK** [comment]
Sent for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/86467245-abe55200-bcfa-11ea-9ef3-2d88e02b8226.png)
