### ISSUE TITLE
YGEL-Geraldton Airport-WESTERN AUSTRALIA-AUSTRALIA

### ISSUE THREAD

**Issue by ewanfleming** [InfiniteFlightAirportEditing/Airports#2470]
Part of Project Australia.
Again, all my other airport are in for review.

**Comment by ewanfleming** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32254060-75264952-be6c-11e7-867a-a6d06e292d4d.png)

**Comment by moritzbabl** [comment]
Open for rework (IF Event Airport)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/73310934-063a2e00-4204-11ea-93b2-fa62eaf74df3.jpg)
