### ISSUE TITLE
FKKD-Douala Airport-LITTORAL-CAMEROON

### ISSUE THREAD

**Issue by sebbieee** [InfiniteFlightAirportEditing/Airports#2471]
PLEASE EDIT ME

**Comment by Blently** [comment]
Please refer to issue #87

**Comment by ewanfleming** [comment]
Also, **please do not make issues unless you are an editor yourself.** Please visit this page if you have any airport-related queries. 
https://community.infinite-flight.com/t/airport-inaccuracies-what-should-i-do/152800?u=ewanfleming
P.S. **DO NOT MAKE PULL REQUESTS IF YOU ARE NOT EDITING AN AIRPORT**

**Comment by Tamz00** [comment]
I’ll take this

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36352231-274e2b22-147b-11e8-9462-2369f46fa84c.png)
