### ISSUE TITLE
YRTI-Rottnest Island Airport-WESTERN AUSTRALIA-AUSTRALIA

### ISSUE THREAD

**Issue by ewanfleming** [InfiniteFlightAirportEditing/Airports#2474]
Very small one, part of Project Australia.
Apologies that I already have 5 or 6 assigned but again, they're all in for review.

**Comment by ewanfleming** [comment]
Sent in for review. (even though I'm not assigned yet...)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32253958-d94a2bf2-be6b-11e7-990f-2b519eb69a1c.png)
