### ISSUE TITLE
ENSI-Ski Airport-AKERSHUS-NORWAY

### ISSUE THREAD

**Issue by tranquil-skyflyer** [InfiniteFlightAirportEditing/Airports#2476]
♻️

**Comment by tranquil-skyflyer** [comment]
Finally submitted for review.

**Comment by tranquil-skyflyer** [comment]
Resubmitted

**Comment by MajorTomMueller** [comment]
@tranquil-skyflyer still working on this?

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by tranquil-skyflyer** [comment]
If anyone takes this and wants the files from where I left off just let me know. I'd be happy to send it over cause the x-plane files for these airports are pretty bad.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54886295-95442000-4e54-11e9-9776-e2107d1da660.png)
