### ISSUE TITLE
KSSC-Shaw AFB Airport-SOUTH CAROLINA-USA

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#248]
Working on this one

**Comment by JohnPreston21** [comment]
Re designing this one now.

**Comment by JohnPreston21** [comment]
Re designed this from scratch except the runways, Removed old taxiways and re designed better one with Taxiways and plenty of Parking spots with spawns.

**Comment by kilt46** [comment]
Image: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=KSSC

**Comment by JohnPreston21** [comment]
Noooo this was already approved. Why the change @kilt46

**Comment by JohnPreston21** [comment]
I have already rebuilt this one, it was approved weeks ago.

**Comment by JohnPreston21** [comment]
Fixed taxi line mis aliegnments corrected taxiways with snap to vericals and updated spawn names

**Comment by Swang007** [comment]
Taxi lines need to be connected, not overlapping. Snap to Vertices needs to be enabled. Estimated time needed to fix these issues: About 30-45 minutes

https://community.infinite-flight.com/t/kssc-markings/15460

**Comment by JohnPreston21** [comment]
Going to fix AGAIN the taxi lines.

**Comment by JohnPreston21** [comment]
Finished and emailed awaiting approval.

**Comment by kilt46** [comment]
John I posted this for you after I cleaned it up. This can now be closed

**Comment by JohnPreston21** [comment]
Thanks man. Much appreciated.

**Comment by dushyants19** [comment]
Adding 0 to unit numbers. And correcting the boundary :)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18036029/5da5176e-6d27-11e6-8fb1-f01a1320f401.png)
MAIN HANGARS
![image](https://cloud.githubusercontent.com/assets/14023167/18036031/82449310-6d27-11e6-8aab-22a001656ae5.png)
ALPHA/BRAVO/CHARLIE
![image](https://cloud.githubusercontent.com/assets/14023167/18036036/9237823c-6d27-11e6-81b2-2a41d43e1a5d.png)
DELTA/ECHO/FOXTROT
![image](https://cloud.githubusercontent.com/assets/14023167/18036042/acd08760-6d27-11e6-8e53-76a61a867326.png)
FAST REACTION APRON
![image](https://cloud.githubusercontent.com/assets/14023167/18036050/c057d6bc-6d27-11e6-8d79-c642b35e4030.png)

**Comment by moritzbabl** [comment]
done

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50385496-2829be80-069c-11e9-91f9-e5bee6c02fc1.png)
