### ISSUE TITLE
EKVB-Viborg-DENMARK

### ISSUE THREAD

**Issue by alchonub** [InfiniteFlightAirportEditing/Airports#2480]
200ft off from the 10k category, suggestion

**Comment by brunocr98** [comment]
Do you think we want more suggestions?

**Comment by alchonub** [comment]
lol sorry bruno

**Comment by alchonub** [comment]
Doing this Now

**Comment by alchonub** [comment]
I'm not doing it sorry, wrong thread

**Comment by MajorTomMueller** [comment]
recycled

**Comment by MajorTomMueller** [comment]
miss typed ICAO, EKVG was done long ago...

**Comment by MajorTomMueller** [comment]
![ekvb-git3](https://user-images.githubusercontent.com/26853210/35482814-90f3a8d2-043a-11e8-9291-aeb01abe1fbd.jpeg)
