### ISSUE TITLE
CYFI-Fort MacKay/Firebag Aerodrome-ALBERTA-CANADA

### ISSUE THREAD

**Issue by alexpeterson-if** [InfiniteFlightAirportEditing/Airports#2481]
I'll do this one. Runway is less than 10k. Airport is relatively new so does not appear in XPlane, May also appear as CFG6 (airport code was also changed, CYFI is current and correct).

**Comment by alexpeterson-if** [comment]
Sent for review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32392258-e28ab5d6-c0a2-11e7-858a-97dba5e77ba1.png)
