### ISSUE TITLE
1H2-Effingham County Memorial Airport-ILLINOIS-USA

### ISSUE THREAD

**Issue by carlrick2007** [InfiniteFlightAirportEditing/Airports#2484]
REUSE.

**Comment by brunocr98** [comment]
You've been told already that for this kind of reports, you **have** to submit an topic in the IFC forum. Please **avoid** creating issues in our repository. Thanks!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32925706-f18a0f44-cb08-11e7-9a12-644fd26a2bea.png)
