### ISSUE TITLE
ZJSY-Sanya Phoenix Airport-HAINAN-CHINA

### ISSUE THREAD

**Issue by VladK125rus** [InfiniteFlightAirportEditing/Airports#2485]
Being redone

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33639102-6177c3d8-d9ef-11e7-85ff-55830f2aebeb.png)

**Comment by RyanEpps** [comment]
New terminal, other fixes

**Comment by zhf21** [comment]
Sent to OR about 5 hours ago 😂

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102945916-ba7c1d00-4484-11eb-8880-73ec048bc35d.png)
