### ISSUE TITLE
VVCR-Cam Ranh International Airport-NAM TRUNG-VIETNAM

### ISSUE THREAD

**Issue by VladK125rus** [InfiniteFlightAirportEditing/Airports#2486]
I'll do it

**Comment by Taixipo2003** [comment]
Thanks god

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34451377-0b7eccbc-ece9-11e7-9ede-0d60a7d4d5a2.png)

**Comment by MajorTomMueller** [comment]
New runway

**Comment by OscarConklin** [comment]
I can do this.

**Comment by OscarConklin** [comment]
Sent for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/96939733-7aec8100-1493-11eb-8dd4-ae45eacbf166.png)
