### ISSUE TITLE
EKKA-Karup Air Base Airport-VIBORG-DENMARK

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#2487]
formerly known as Karup Airport
I will do this

**Comment by MajorTomMueller** [comment]
send to review

**Comment by MajorTomMueller** [comment]
![ekka-gh](https://user-images.githubusercontent.com/26853210/33527952-a370bc00-d859-11e7-8e06-b6cfa0ed3196.jpeg)

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33534757-321f73e6-d86f-11e7-92de-70cd8038ed9a.png)

**Comment by MajorTomMueller** [comment]
- boundary fix
- buildings removed
- hangar floors added
- minor additions to spawns
