### ISSUE TITLE
CAL4-Fort MacKay/Albian Aerodrome-ALBERTA-CANADA 

### ISSUE THREAD

**Issue by alexpeterson-if** [InfiniteFlightAirportEditing/Airports#2488]
I'll do this one as well. Runway is less than 10k.

**Comment by alexpeterson-if** [comment]
Sent for review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32583271-5d776f82-c4b8-11e7-9de1-fc9603baee7e.png)
