### ISSUE TITLE
CYNR-Fort MacKay/Horizon Airport-ALBERTA-CANADA 

### ISSUE THREAD

**Issue by alexpeterson-if** [InfiniteFlightAirportEditing/Airports#2489]
I'll do this one also. Runway is less than 10k.

**Comment by alexpeterson-if** [comment]
Sent for review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32583136-9d9b6948-c4b7-11e7-92de-9f71afcf5ecc.png)
