### ISSUE TITLE
SBBV-Atlas Brasil Cantanhede Airport-RORAIMA-BRAZIL

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Airports#2491]
Boa Vista - Roraima Airport

**Comment by dushyants19** [comment]
It's been approved, I'll add it to the repo once I get a stable wifi

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/35058245-ec5827aa-fb7c-11e7-89f5-9a8b64b2a953.png)
