### ISSUE TITLE
4NY8-Harris Hill Gliderport-NEW YORK-USA

### ISSUE THREAD

**Issue by tomthetank46** [InfiniteFlightAirportEditing/Airports#2494]
Harris Hill Soaring, I'll do it to get familiar with this all. My local airport.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33247824-84c6f1a2-d2e6-11e7-9b69-8f9fbe88157e.png)

**Comment by RyanEpps** [comment]
Done with issue closed :ban:

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/75924482-cc34fb00-5e45-11ea-9d93-b18da8b7c3dc.jpg)
