### ISSUE TITLE
PKWA-Bucholz AAF Airport-KWAJALEIN-MARSHALL ISLANDS

### ISSUE THREAD

**Issue by alchonub** [InfiniteFlightAirportEditing/Airports#2495]
Majuro, Just let this issue slip, only this time

**Comment by alchonub** [comment]
Sorry Dup
rECYCLED

**Comment by brunocr98** [comment]
After realizing you just broke the 3-issues rule, I've unassigned you from your 2 most recent issues. If you have your other 3 airports in review, feel free to ask to be reassigned to one of the 2 issues.

**Comment by rocketman1974** [comment]
I'm looking at the airport now, looks like this is in need of a redo?

**Comment by dushyants19** [comment]
Yes KimJongUn1974 this needs a redo

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/35471938-1b1de3f8-032b-11e8-96d4-6fef2c9c3c61.png)
