### ISSUE TITLE
CYRV-Revelstoke Airport-BRITISH COLUMBIA-CANADA 

### ISSUE THREAD

**Issue by alexpeterson-if** [InfiniteFlightAirportEditing/Airports#2496]
Will do this small one. Runway is (much) less than 10k.

**Comment by alexpeterson-if** [comment]
Sent for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32695269-50b084b2-c71c-11e7-97bc-ead44616ff01.png)
