### ISSUE TITLE
CYQF-Red Deer Regional Airport-ALBERTA-CANADA 

### ISSUE THREAD

**Issue by alexpeterson-if** [InfiniteFlightAirportEditing/Airports#2498]
I'll do this one. Runway is less than 10k.

**Comment by alexpeterson-if** [comment]
Sent for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32871437-9357ba6a-ca46-11e7-9fdd-fd55355cfe68.png)
