### ISSUE TITLE
HSSS-Khartoum Airport-KHARTOUM-SUDAN

### ISSUE THREAD

**Issue by alchonub** [InfiniteFlightAirportEditing/Airports#2499]
Khartum, Sudan.

W          i         i         l                     d          o

**Comment by dushyants19** [comment]
Please use proper English. This is not a meme

**Comment by LeonVeen** [comment]
I will do this one

**Comment by brunocr98** [comment]
Please finish/submit 3 or your 4 airports to be assigned to this one.

**Comment by LeonVeen** [comment]
Allright, I will finish KSAV first...

**Comment by mbmhwue148** [comment]
I´ll do it, if that's ok.

**Comment by LeonVeen** [comment]
All right, that's fine

**Comment by kilt46** [comment]
Wrong numbering as per Navigraph/Jeppeson
![image](https://user-images.githubusercontent.com/14023167/34266525-12cbd664-e63f-11e7-992f-0b5c89f63cd8.png)

**Comment by mbmhwue148** [comment]
I´ll fix this

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34343640-b22d9188-e99c-11e7-8d26-b199248b3dfa.png)
