### ISSUE TITLE
KEWR-Newark Liberty International Airport-NEW JERSEY-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#25]

**Comment by kilt46** [comment]
Rework for jetbridges and terminal building details

**Comment by kilt46** [comment]
This has been completed

**Comment by NickArt1342** [comment]
Some spawn points need to be made heavy capable (for example B64, so my T7s nose doesn't stick into the terminal)

**Comment by dushyants19** [comment]
All spawns are heavy capable. It will be eventually gated

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18895513/b79f4c60-84df-11e6-94ac-cc57ef964a5a.png)

**Comment by CptNathanHope** [comment]
Needs a lot of beautifying.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46898657-bd186c00-ce50-11e8-965f-6bbd947c8102.png)

**Comment by Czechoslovaki** [comment]
@jakey20 will make several major updates to the airport.

**Comment by Czechoslovaki** [comment]
@jakey20 is updating the markings, taxiways, the outline for T1 and also relocating the UPS apron.

**Comment by Czechoslovaki** [comment]
Jake has gotten busy in life, so I will take over maintenance.
