### ISSUE TITLE
KSMO-Santa Monica Municipal Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by Misha16** [InfiniteFlightAirportEditing/Airports#250]
Several noncurved taxiways. Not enough parking

**Comment by Swang007** [comment]
https://community.infinite-flight.com/t/santa-monica-airport-runway-border-line/15124

**Comment by cboisselier** [comment]
Could someone check that? I think the problem is that a part of the taxiway is ON the runway...? I can't figure that out #newbie

**Comment by HenrikBerg02** [comment]
I'll check it out.

**Comment by kilt46** [comment]
Center lines removed next to runway.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21075095/2e4cff5a-becf-11e6-8ccb-ed2bb61d56cd.png)

**Comment by danisrils39** [comment]
I see this is open, I guess I can grab and bring it up to standard

**Comment by MajorTomMueller** [comment]
@dhamilton30 are you still working on this? 
Respond with in a week, otherwise I will assign @danisrils39.

**Comment by dhamilton30** [comment]
I was working on it, but due to a change in my work schedule, my
availability has drastically decreased.  Please feel free to reassign.  My
apologies.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/93725872-2c885180-fb78-11ea-80ed-03fd042eeaf8.png)
