### ISSUE TITLE
CYMM-Fort McMurray International Airport-ALBERTA-CANADA

### ISSUE THREAD

**Issue by alexpeterson-if** [InfiniteFlightAirportEditing/Airports#2500]
Will do this one. Runway less than 10k.

**Comment by alexpeterson-if** [comment]
Sent for review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32992484-dbd841de-cd10-11e7-94bc-de6bde642b8c.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50449111-b85d4300-08ea-11e9-83c9-e36b3810bd69.png)

**Comment by kilt46** [comment]
Duplicate spawn removed. Buildings removed
