### ISSUE TITLE
KCEF-Westover Air Reserve Base-MASSACHUSETTS-USA

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Airports#2501]
Part of [Project New England](https://community.infinite-flight.com/t/project-new-england/43169). 

Final _Priority II_ airport for this project.

**Comment by CptNathanHope** [comment]
Redone via [`c6f4350`](https://github.com/InfiniteFlightAirportEditing/Airports/commit/c6f4350eb2d0a08e08e4f4671ec1f94e9c6ae441).

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33176684-88893caa-d025-11e7-9128-a92d05c2d666.png)
