### ISSUE TITLE
CEF4-Airdrie Airpark-ALBERTA-CANADA

### ISSUE THREAD

**Issue by alexpeterson-if** [InfiniteFlightAirportEditing/Airports#2503]
Will do this one. Runway is less than 10k.

**Comment by alexpeterson-if** [comment]
Sent for review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32992649-b13ca486-cd12-11e7-9317-f2f6e9b78f12.png)
