### ISSUE TITLE
LIEA-Alghero Fertilia Airport-SARDEGNA-ITALY

### ISSUE THREAD

**Issue by johanneskkl** [InfiniteFlightAirportEditing/Airports#2504]
Alghero airport, italy.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34450636-d65ed492-ecd3-11e7-86dd-9a23a552289a.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/69883273-299f3600-12b2-11ea-8711-627400e00dbd.jpg)
