### ISSUE TITLE
KSUU-Travis AFB Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by slaci56** [InfiniteFlightAirportEditing/Airports#2506]
♻️

**Comment by ewanfleming** [comment]
Please avoid creating issues if you aren’t part of the team. Thanks!

**Comment by benlenahan** [comment]
I will take this one.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36401066-87b93432-159a-11e8-90d6-a0428f7277db.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124395795-c5352b80-dccb-11eb-9686-f7594aa24ff8.png)

**Comment by kilt46** [comment]
Hole in taxiway removed. Buildings removed
