### ISSUE TITLE
CYQU-Grande Prairie Airport-ALBERTA-CANADA

### ISSUE THREAD

**Issue by alexpeterson-if** [InfiniteFlightAirportEditing/Airports#2509]
Will do this one.

**Comment by alexpeterson-if** [comment]
Sent for review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34074095-95dbcf94-e26d-11e7-9427-8595654a2c98.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50402195-3fc77c80-075a-11e9-98d8-43489d018197.png)

**Comment by kilt46** [comment]
Duplicate spawn removed. Buildings removed
