### ISSUE TITLE
KCLS

### ISSUE THREAD

**Issue by JohnPreston21** [InfiniteFlightAirportEditing/Airports#251]
Seattle

**Comment by adamkassio** [comment]
I'll try this one.

**Comment by JohnPreston21** [comment]
Remember to alwabys add the "being Redone" label and remove the "suggestion" once you self-assign so the other editors will know not to touch what you are doing, 

Thanks.

**Comment by adamkassio** [comment]
ok. sorry about that.

**Comment by JohnPreston21** [comment]
No worries, i updates this one for you.

**Comment by adamkassio** [comment]
Hey guys sorry that this is not done. I have had a lot of work as I am applying for college and just don't have time for this right now. Hope to get back to it soon. Someone else can work on it if they wish.

**Comment by samuelandersson** [comment]
Will do this one. Small and nice :) Here I come

**Comment by samuelandersson** [comment]
Done. Added everything and a little more.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21080918/b5bd3462-bf80-11e6-897b-3622fe0e49b0.png)
