### ISSUE TITLE
KNRS

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#252]
So-Cali

**Comment by kilt46** [comment]
Will work on this next

**Comment by kilt46** [comment]
Is this KNRS? KNRC is not an available airport on IF

**Comment by kilt46** [comment]
I found no KNRC. I have completed KNRS as best I can. It is a partially completed airfield on West Coast. I am considering it closed.

**Comment by HenrikBerg02** [comment]
This one needs to be done ASAP. Pretty bad and has small issues with taxiways.

**Comment by kilt46** [comment]
Redone

**Comment by dushyants19** [comment]
Doing Minor Changes

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20821958/6a37e01c-b80c-11e6-8602-8e0621e42b42.png)
