### ISSUE TITLE
KMTP-Montauk Airport-NEW YORK-USA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#2526]
Ill work on this. (Part of Project NY-GA)

**Comment by ryu12332** [comment]
Progress?

**Comment by Balloonchaser** [comment]
Done. I’ll send it in tomorrow

**Comment by MajorTomMueller** [comment]
@Balloonchaser forgot to send in? or rejected and not proceeded?

**Comment by Balloonchaser** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44122413-6831ea08-9fe9-11e8-903e-790d7e6b965b.png)
