### ISSUE TITLE
EKEB-Esbjerg Airport-SYDDANMARK-DENMARK

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#2528]
Will care about this one next.

**Comment by MajorTomMueller** [comment]
![enfg-spawn](https://user-images.githubusercontent.com/26853210/33238827-ae43ab70-d295-11e7-8c00-8462a85f1631.jpeg)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33244998-4709fd92-d2c7-11e7-8215-5ecd3a7fa422.png)

**Comment by MajorTomMueller** [comment]
Boundary

**Comment by MajorTomMueller** [comment]
-Boundary fixed
-Buildings removed
-Hangar Floors added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46245415-e518c180-c3b2-11e8-917d-ebf4ae0c161d.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46246120-6590ef80-c3be-11e8-8dab-6ce36673defb.png)

**Comment by MajorTomMueller** [comment]
Spawn naming

**Comment by MajorTomMueller** [comment]
spawn name fix
GA spawns added
