### ISSUE TITLE
KDAG

### ISSUE THREAD

**Issue by JohnPreston21** [InfiniteFlightAirportEditing/Airports#253]
SoCal

**Comment by JohnPreston21** [comment]
re doing taxiways, adding taxilines and spawn parking

**Comment by JohnPreston21** [comment]
Waiting for approval

**Comment by Omari4u** [comment]
don't forget to remove spawning on runways..

**Comment by JohnPreston21** [comment]
Already. Done. I never leave room for runway spawn

**Comment by JohnPreston21** [comment]
Also thanks Cameron for readding the boundary on this one and LFOZ. Totally forgot I'm sorry man.

**Comment by Omari4u** [comment]
well done..

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18033457/b21ee0be-6cea-11e6-950d-6c8ec481a256.png)
