### ISSUE TITLE
EIIR

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#2534]
@mbmhwue148 please create an issue before starting an airport next time...I thought I mentioned this in the guide :smirk: :ban:

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33246646-92f6b884-d2dc-11e7-9bc1-ff45c8e6c603.png)
