### ISSUE TITLE
EKSB-Sonderborg Airport-SYDDANMARK-DENMARK

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#2535]
will do this one

**Comment by MajorTomMueller** [comment]
send to review

**Comment by MajorTomMueller** [comment]
![eksb-overview](https://user-images.githubusercontent.com/26853210/34354677-47c5bd4a-ea30-11e7-85a4-2330ce53b460.jpeg)

**Comment by MajorTomMueller** [comment]
-Boundary fix
-Buildings removed
-Hangar Floors added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46258995-4a92ae00-c498-11e8-8712-85a96d9de2b5.png)
