### ISSUE TITLE
CYTA-Pembroke Airport-ONTARIO-CANADA

### ISSUE THREAD

**Issue by rnorris03** [InfiniteFlightAirportEditing/Airports#2537]
I'll do this

**Comment by rnorris03** [comment]
Sent in for review.

**Comment by rnorris03** [comment]
Submitted for review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34074117-0ee86032-e26e-11e7-8ca0-57b75efc307c.png)
