### ISSUE TITLE
KRNM-Ramona Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by renorris** [InfiniteFlightAirportEditing/Airports#2538]
This is an old region airport, I'll redo it

**Comment by johnkellyoxford** [comment]
?

**Comment by dushyants19** [comment]
Wrong account John

**Comment by rnorris03** [comment]
what happened here?

**Comment by rnorris03** [comment]
Sent in for review

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/35485314-72d52356-0423-11e8-99f7-8558d99ea932.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53293124-9883b780-3793-11e9-9a1d-a1df910bdbb3.png)

**Comment by kilt46** [comment]
DUPLICATES REMOVED
