### ISSUE TITLE
RJDO-Oijka Airport-NAGASAKI-JAPAN

### ISSUE THREAD

**Issue by tomthetank46** [InfiniteFlightAirportEditing/Airports#2539]
♻️

**Comment by tomthetank46** [comment]
Unable to finish this airport as it is very big and complex, and I am new.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/37181478-c4ec0fe0-22f2-11e8-8626-4dc72d45dde2.png)
