### ISSUE TITLE
KASE-Aspen-Pitkin Co/Sardy Field Airport-COLORADO-USA

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#254]
Buildings and taxiways aren't lining up: Gras spots all over the place

**Comment by NickArt1342** [comment]
KSAE is messed up badly... jeez

**Comment by kilt46** [comment]
Assuming this is KASE as KSAE does NOT exist!

**Comment by kilt46** [comment]
Airport redone from scratch.

**Comment by NickArt1342** [comment]
Bro, There was a label on it that I was doing it...

**Comment by NickArt1342** [comment]
Kase if course not KSAE, lil typi

**Comment by kilt46** [comment]
Sorry. It was hard to tell that you were doing it as you were not assigned
to it. I saw that you were working on several at once. The text made it
sound like you were giving up. I have been using the method of assigning
myself to one airport at a time to help people know what I am working on.
It is not a large job. My version I went in and deleted everything and just
started from scratch as it was horrible. If you want to send your version
to Cameron or however you do this doesn't matter. It is a team event. Peace
man!

**Comment by carmichaelalonso** [comment]
I'm a little confused here - @NickArt1342  - what airfield were you doing, KSAE, or KASE?

**Comment by kilt46** [comment]
KSAE doesn't exist should have been KASE unless I am mistaken. I checked ICAO listing.

**Comment by kilt46** [comment]
Cameron there was a little communication glitch. Nick had written against several airports but had used BUG on KASE (KSAE) and had not assigned himself to the issue. I took it that he needed help as he wasn't assigned and I redid the airport last night.

**Comment by NickArt1342** [comment]
No worries, since you finished already We'll take yours, but seriously, gow do I assign myself to a prob? I'm constantly having trouble with this forum...

**Comment by carmichaelalonso** [comment]
OK, thanks for clearing it up.
@NickArt1342  - on the right hand bar, under Assignee, there is a Settings  gear - tap on that and select your name. Also, add the "Being Reworked" label. :)

**Comment by kilt46** [comment]
Nick hopefully you are using a PC to make updates on GitHub. I have tried iPad and iPhone. They do not show all of the options. Yes it is frustrating to use this web page. I taught myself through trial and error. On the right hand side under each issue are several boxes where you can flag the status and also assign yourself. I am at work just now as I live in the USA. If you don't see what I talking about drop me a line and I'll send you a screen shot. You are more than welcome to contact me any time if you need any help.

Respectfully.

**Comment by kilt46** [comment]
Reworking airport extension (from satellite as it does not show on WEDBing

**Comment by samuelandersson** [comment]
Cool :)

**Comment by kilt46** [comment]
South runway extension added as per 2015 Google Earth (does not exist in WEDBing)

**Comment by dushyants19** [comment]
Quick altitude change :)

**Comment by dushyants19** [comment]
Gated in ee54eca

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19253043/f966639e-8f0d-11e6-9b6a-0f71ff301cb7.png)

**Comment by kilt46** [comment]
Buildings removed

**Comment by JensSeverin** [comment]
Please remove my assignment for this

**Comment by JensSeverin** [comment]
@kilt46 have fixed this airport

**Comment by MajorTomMueller** [comment]
Complete rework needed, buildings remove, spawn size to be checked (fit Dash class C), and so on

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68167300-c8e73c80-ff43-11e9-9cbe-19e6c67d149e.jpg)
