### ISSUE TITLE
KLEW-Auburn/Lewiston Municipal Airport-MAINE-USA

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Airports#2543]
Part of [Project New England](https://community.infinite-flight.com/t/project-new-england/43169).

**Comment by CptNathanHope** [comment]
Redone via [`6e191db`](https://github.com/InfiniteFlightAirportEditing/Airports/commit/6e191dbec2d0a885b1a192c8a98dd29bb7e94caf).

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34545954-45c57058-f0b6-11e7-9cda-6d92de866bb7.png)
