### ISSUE TITLE
KBST-Belfast Municipal Airport-MAINE-USA

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Airports#2544]
Part of [Project New England](https://community.infinite-flight.com/t/project-new-england/43169).

**Comment by CptNathanHope** [comment]
Redone via [`da04eea`](https://github.com/InfiniteFlightAirportEditing/Airports/commit/da04eea370c41e5a08a06dc5b64724c7da240eca).

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34546063-0bad281a-f0b7-11e7-876d-32b206dd6e8b.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45058764-445b0e80-b05f-11e8-8f06-40d2765482e9.png)
