### ISSUE TITLE
RODN-Kadena AFB Airport-OKINAWA-JAPAN

### ISSUE THREAD

**Issue by brent11292** [InfiniteFlightAirportEditing/Airports#2546]
I will do it

**Comment by brent11292** [comment]
Sorry, I am not able to do it anymore because I have lost some time in my day for editing this

**Comment by MajorTomMueller** [comment]
...next challenge to patience...

**Comment by MajorTomMueller** [comment]
![rodn-git](https://user-images.githubusercontent.com/26853210/36274064-d6b76750-1286-11e8-92d1-674839d9fd01.jpeg)

**Comment by MajorTomMueller** [comment]
boundary

**Comment by MajorTomMueller** [comment]
...moped the floor, taken the trash out, whipped the windows...

- Boundary Fix
- Buildings removed
- Hangar Floors and Markings added
- EOR Spawns removed

![RODN-git-new](https://user-images.githubusercontent.com/26853210/54488612-0d827280-48a4-11e9-94c1-fc905c1d69c9.jpg)
