### ISSUE TITLE
ROMY-Miyako Airport-OKINAWA-JAPAN

### ISSUE THREAD

**Issue by benlenahan** [InfiniteFlightAirportEditing/Airports#2547]
I'll take this one, need something to make me look productive in the time being. Part of project Japan.

**Comment by benlenahan** [comment]
I opened up the apt.dat and the airport was already completed. A pleasant surprise none the less.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33693932-1c9baa00-dabb-11e7-9c82-ef4a5918e60b.png)
