### ISSUE TITLE
GOBD-Blaise Diagne International Airport-DAKAR-SENEGAL

### ISSUE THREAD

**Issue by ewanfleming** [InfiniteFlightAirportEditing/Airports#2549]
Brand new airport opening tomorrow. I’ll work on it.
10k

**Comment by ewanfleming** [comment]
Sent in for review.

**Comment by dushyants19** [comment]
It's been approved, I'll add it to the repo once I get a stable wifi

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/35058596-1249dcd2-fb7e-11e7-8da3-4efacf41dc9e.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124352269-11497880-dbc5-11eb-8de1-06e636db0061.png)
