### ISSUE TITLE
LIRF-Leonardo da Vinci-Fiumicino Airport-LAZIO-ITALY

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#255]
Airport map totally outdated. Redoing the whole airport.

**Comment by kilt46** [comment]
Airport redone by Nick

**Comment by kilt46** [comment]
White lines need to be removed. Hatching needs to be removed. Runway name needs 0 at beginning

**Comment by NickArt1342** [comment]
0 added

**Comment by IceBlue02** [comment]
@NickArt1342 what are you doing with this ATM?

**Comment by NickArt1342** [comment]
I'm working on it @IceBlue02

**Comment by turkish1941** [comment]
is someone working on this?

**Comment by samuelandersson** [comment]
No one is working on it @turkish1941.

**Comment by turkish1941** [comment]
oke thats good to hear, I will make it ☺

**Comment by IceBlue02** [comment]
@samuelandersson don't forget assignee :+1:

**Comment by samuelandersson** [comment]
Not the easiest when I am on vacation with limited internet @IceBlue02 :) thanks though

**Comment by turkish1941** [comment]
email is gone

**Comment by turkish1941** [comment]
Its accepted but not closed and not in the repo....

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17758908/c764c9fa-64b8-11e6-81eb-9ec6cce37bac.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17758932/f8dafd60-64b8-11e6-9d12-387f4fa4ef84.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17758940/06eb7b64-64b9-11e6-8ffc-597519aed99c.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50321563-0e6b5a00-0497-11e9-93f7-a065a6f38448.png)
