### ISSUE TITLE
ZSSS-Shanghai/Hongqiao International Airport-SHANGHAI-CHINA

### ISSUE THREAD

**Issue by mbmhwue148** [InfiniteFlightAirportEditing/Airports#2551]
I´ll do this one

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
Wrong gating :As per Navigraph/Jeppesen
![image](https://user-images.githubusercontent.com/14023167/36818377-66d87bb2-1caa-11e8-8d1b-d3f8bd63b752.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36819272-6b733bf4-1cae-11e8-95c3-94647762bf25.png)

**Comment by mbmhwue148** [comment]
Fixed and sent in.

**Comment by moritzbabl** [comment]
readded

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/37258012-37602fc2-253f-11e8-8892-b641275a2460.png)
