### ISSUE TITLE
CYXJ-Fort St. John Airport-BRITISH COLUMBIA-CANADA

### ISSUE THREAD

**Issue by DelsterX** [InfiniteFlightAirportEditing/Airports#2553]
I will do this one. 
Part of Project Canada

**Comment by DelsterX** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34183399-44af9e0a-e4e0-11e7-885e-e14746f05120.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50539962-a11e8f80-0b4e-11e9-83ea-14aafeaf60c5.png)
