### ISSUE TITLE
GCGM-La Gomera Airport-ISLAS CANARIAS-SPAIN

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#2554]
La Gomera Airport, Canaries, Spain.

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34965299-a5213062-fa18-11e7-9f28-1e913466efc4.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107885508-52641900-6ec0-11eb-99bd-954d1b2bfc53.png)
