### ISSUE TITLE
CYQZ-Quesnel Airport-BRITISH COLUMBIA-CANADA

### ISSUE THREAD

**Issue by DelsterX** [InfiniteFlightAirportEditing/Airports#2555]
I will do this one.
Part of Project Canada.

**Comment by DelsterX** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34185267-10f7b818-e4ea-11e7-96b7-7e6579ff15a8.png)
