### ISSUE TITLE
CYWL-Williams Lake-BRITISH COLUMBIA-CANADA

### ISSUE THREAD

**Issue by DelsterX** [InfiniteFlightAirportEditing/Airports#2558]
I will do this one.
Part of Project Canada

**Comment by DelsterX** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34079837-3a5c7aea-e2fb-11e7-8600-200c0598d1c9.png)
