### ISSUE TITLE
YMAV-Avalon Airport-VICTORIA-AUSTRALIA

### ISSUE THREAD

**Issue by dushyants19** [InfiniteFlightAirportEditing/Airports#256]

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20860105/0c33ebde-b936-11e6-9667-1a51757ecffe.png)

**Comment by MajorTomMueller** [comment]
Hello @joshhicks1,
Any progress with this one? We gave normally 3 months to the average editor for average editors. 
There is another edited that offered to do this one.
If you do not reclaim to finish this till Monday I will unassign you.

**Comment by joshhicks1** [comment]
Hey @MajorTomMueller sorry for the delay I've been super busy lately. It's pretty much finished, I just need to touch up a couple things and send it off to OR

**Comment by ECoops-123** [comment]
Hi there, guessing Sunday has been and gone 50 times, you're no longer working on this airport? If not I'll take over.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113459640-b47ace00-93db-11eb-889d-8190f02f0e36.png)
