### ISSUE TITLE
MRTM-Tamarindo De Santa Cruz Airport-GUANACASTE-COSTA RICA

### ISSUE THREAD

**Issue by mbmhwue148** [InfiniteFlightAirportEditing/Airports#2560]
RECYCLE ♻️

**Comment by ewanfleming** [comment]
Hey. Just to make it easier, let's keep to one issue. The other one is here
https://github.com/InfiniteFlightAirportEditing/Airports/issues/428
Just ask an admin to re-open it for you ;)

**Comment by mbmhwue148** [comment]
Alright, will do :)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36925958-fba47d68-1e3a-11e8-98df-d4942a01d4ef.png)
