### ISSUE TITLE
3AU-Augusta Muncipal Airport-KANSAS-USA

### ISSUE THREAD

**Issue by bobo2345** [InfiniteFlightAirportEditing/Airports#2561]
Augusta Muncipal Airport, Kansas USA, i'll do it.

**Comment by dushyants19** [comment]
We'll get someone who knows lat/long to redo this field.

**Comment by MajorTomMueller** [comment]
[FAA Record 3AU](http://www.gcr1.com/5010web/airport.cfm?Site=3AU)
From 
[wikipedia 3AU](https://en.wikipedia.org/wiki/Augusta_Municipal_Airport)

Airport Latitude: 37-40-17.9000N ESTIMATED
Airport Longitude: 097-04-40.3000W
Airport Elevation: 1328.0 SURVEYED

**Comment by rocketman1974** [comment]
Tom, Bo had no idea about how to input coords, didn’t use the guide. I’ll take it I guess, redo it, and then put in my 3 airports into peer editing at the same time.

**Comment by MajorTomMueller** [comment]
Haven‘t noticed the discussion on slack... ;-) now I got it.

**Comment by dushyants19** [comment]
@mrpidgeon is doing this

**Comment by moritzbabl** [comment]
Member inactive, up for grabs

**Comment by ewanfleming** [comment]
Not sure why this has taken so long, I'll take it.

**Comment by ewanfleming** [comment]
Sent in for review. 🉑

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/40268224-41066c00-5b2f-11e8-9a55-4a89a004798c.png)
