### ISSUE TITLE
CYYE-Northern Rockies Regional (Fort Nelson) Airport- BRITISH COLUMBIA-CANADA

### ISSUE THREAD

**Issue by DelsterX** [InfiniteFlightAirportEditing/Airports#2562]
I will do this one.

**Comment by DelsterX** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34457668-9093d4a8-ed7d-11e7-9831-c0632c9342df.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50573595-eb954b80-0d9c-11e9-9dd2-f12170fc579e.png)

**Comment by kilt46** [comment]
Buildings removed. Duplicate spawn fixed.
