### ISSUE TITLE
HKKI-Kisumu Airport-NYANZA-KENYA

### ISSUE THREAD

**Issue by kizzair** [InfiniteFlightAirportEditing/Airports#2564]
Kenya's third largest airport with 10,826ft of asphalt runway needs a makeover. I'll be redoing the airport.

**Comment by dushyants19** [comment]
Please accept collaboration invite here: https://github.com/InfiniteFlightAirportEditing/Airports/invitations

**Comment by moritzbabl** [comment]
Member inactive, up for grabs

**Comment by johanneskkl** [comment]
I will take even this one

**Comment by johanneskkl** [comment]
sent in even this one

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38708589-a4ae4720-3e7c-11e8-9a03-0e0188345a63.png)
