### ISSUE TITLE
SBCT-Curitiba Alfonso Pena Airport-PARANA-BRAZIL

### ISSUE THREAD

**Issue by mbmhwue148** [InfiniteFlightAirportEditing/Airports#2565]
I´ll do this one

**Comment by brunocr98** [comment]
Just a friendly reminder: you may only have 3 assigned issues at the same time. If the rest of your airports are in review, then you can ask to be assigned to this one again :)

**Comment by mbmhwue148** [comment]
two of them are actually in review :)

**Comment by dushyants19** [comment]
All 3 need to be in review.

**Comment by mbmhwue148** [comment]
so I can´t keep the 3rd one as a longer project, but have to finish it right away?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34546175-d2c67b2c-f0b7-11e7-88a1-c659574351df.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/58821865-6abcd300-860c-11e9-8fe9-f8d2857a833f.jpg)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/63651255-3e0aea00-c729-11e9-8f48-4af9a364ff72.jpg)
