### ISSUE TITLE
KXMR-Cape Canaveral AFS Skid Strip-FLORIDA-USA

### ISSUE THREAD

**Issue by alexpeterson-if** [InfiniteFlightAirportEditing/Airports#2568]
A quick USA one. Runway is exactly 10k feet.

**Comment by alexpeterson-if** [comment]
Sent for review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34357016-cebe06f4-ea08-11e7-8554-8822bfc229f2.png)
