### ISSUE TITLE
KFPK-Fitch H. Beach Airport-MICHIGAN-USA

### ISSUE THREAD

**Issue by ryu12332** [InfiniteFlightAirportEditing/Airports#2569]
Part of Project Michigan.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34319455-d4e7d3d2-e7a8-11e7-9ee9-5d0a7dfdc777.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54879165-d5c77d80-4e03-11e9-9afc-1019965f180f.png)
