### ISSUE TITLE
KLAS-McCarran International Airport-NEVADA-USA

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#257]
reused

**Comment by IceBlue02** [comment]
Is this done? If not see https://community.infinite-flight.com/t/wrongly-named-gates-at-wsss-t2/25698/2

**Comment by NickArt1342** [comment]
The issue has been addressed and fixed.

**Comment by NatIsrael972** [comment]
Bringing to attention new gates at West Cargo Apron and East Cargo Apron

**Comment by NatIsrael972** [comment]
Searched before posting. The other two are CLOSED.

Please undo the DUP unless you have a very valid reason and evidence to say that #257 is open.

**Comment by samuelandersson** [comment]
@NatIsrael972 if you are working on an airport, search for it, if it's closed, just add a note syaing you are redoing or adding sextions and we will open it.

**Comment by NatIsrael972** [comment]
@samuelandersson Thanks for the clarification but then why are there two issues (one by Carmalonso and the other one, this)?

**Comment by samuelandersson** [comment]
@kilt46 takes care of the duplicates.

**Comment by NatIsrael972** [comment]
@samuelandersson What do you mean by "takes care"?

**Comment by carmichaelalonso** [comment]
@NatIsrael972 my one was from a veeeery long time ago, before we worried about duplicates too much :wink:
Kilt nowadays manages old issues and recycles them to avoid these duplicates. Don't worry about it too much, we can just continue here. I'll reopen it for you based on your old issue.

**Comment by IceBlue02** [comment]
@NatIsrael972 current status pls?

**Comment by NickArt1342** [comment]
Wasn't I assigned to this?

**Comment by NatIsrael972** [comment]
I don't know. I opened #601 and it was closed and reused as YSSY.. Derp

**Comment by DavidCutler** [comment]
@NickArt1342 You are assigned to this but @NatIsrael972 is just updating it. No worries :)

**Comment by NatIsrael972** [comment]
@NickArt1342 Since you're doing Terminal 4 and I'm doing the Cargo Terminal, it shouldn't be a problem.. I'll wait for you to finish yours before I continue with mine. Meanwhile, I have changed runway properties, ILS, PAPI, beacon and frequencies..

**Comment by B777fan** [comment]
Thanks Ice. Now I've got a big project on my hands!

**Comment by dushyants19** [comment]
Up for grabs :)

**Comment by Aviationluver** [comment]
I can re-do this one.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19611373/13ea1570-97a7-11e6-956c-496935a12e3e.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19611449/61e9a466-97a7-11e6-9852-2ae789372d14.png)

**Comment by dushyants19** [comment]
Runways numbers changed, @ewanfleming is changing it.

**Comment by ewanfleming** [comment]
Done. Sent in.

**Comment by moritzbabl** [comment]
added

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/61163046-1eee2b00-a4e2-11e9-9fd1-feb9a77b4f8d.jpg)
