### ISSUE TITLE
CYLL-Lloydminster Airport-ALBERTA-CANADA

### ISSUE THREAD

**Issue by alexpeterson-if** [InfiniteFlightAirportEditing/Airports#2571]
Part of Project Canada. Runway less than 10k.

**Comment by alexpeterson-if** [comment]
Sent for review..

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34505509-033b8e64-efeb-11e7-9804-5cfb113e4685.png)
