### ISSUE TITLE
CEN4-High River Airport-ALBERTA-CANADA

### ISSUE THREAD

**Issue by alexpeterson-if** [InfiniteFlightAirportEditing/Airports#2573]
Part of Project Canada. Appears as "EN4" in the sim.

**Comment by alexpeterson-if** [comment]
Sent for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34450688-f3d99b68-ecd5-11e7-91f3-b5e460c43668.png)
