### ISSUE TITLE
RPMY-Laguindingan Airport-MISAMIS ORIENTAL-PHILIPPINES

### ISSUE THREAD

**Issue by captavgeek** [InfiniteFlightAirportEditing/Airports#2574]
I'll do this.  This airport has to be done from scratch.

**Comment by captavgeek** [comment]
submitted apt.dat for review. done with peer review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34697746-1b31dac4-f49a-11e7-8739-e2578572defd.png)
