### ISSUE TITLE
CYPY-Fort Chipewyan Airport-ALBERTA-CANADA

### ISSUE THREAD

**Issue by alexpeterson-if** [InfiniteFlightAirportEditing/Airports#2575]
Part of Project Canada.

**Comment by alexpeterson-if** [comment]
Sent for review.

**Comment by moritzbabl** [comment]
added by Cam

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34450676-507912be-ecd5-11e7-9d5f-d7677867a341.png)
