### ISSUE TITLE
CZVL-Edmonton/Villeneuve Airport-ALBERTA-CANADA

### ISSUE THREAD

**Issue by alexpeterson-if** [InfiniteFlightAirportEditing/Airports#2576]
Part of Project Canada.

**Comment by alexpeterson-if** [comment]
Sent for review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34505378-87541eba-efea-11e7-9ea2-32347df5a7ed.png)

**Comment by kilt46** [comment]
Duplicate spawns fixed. Buildings removed
