### ISSUE TITLE
EKSN-Syndal Airport-NORTH JUTLAND-DENMARK

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#2577]

**Comment by MajorTomMueller** [comment]
![eksn](https://user-images.githubusercontent.com/26853210/34411245-d9cea886-ebd5-11e7-8ff6-ee438299f171.jpeg)

**Comment by MajorTomMueller** [comment]
-Boundary fix
-Buildings removed
-Hangar Floors added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46258944-ad377a00-c497-11e8-8520-0ff05c34dddf.png)
