### ISSUE TITLE
LFOZ

### ISSUE THREAD

**Issue by JohnPreston21** [InfiniteFlightAirportEditing/Airports#258]
Paris

**Comment by JohnPreston21** [comment]
Just completed this one, pending approval

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18034905/46c62636-6d0f-11e6-8fca-f3c829c26396.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20859638/9df0c888-b929-11e6-9b6b-26dfb0e7f4de.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20859639/a7e8e884-b929-11e6-983f-ee3c167a8b07.png)

**Comment by kilt46** [comment]
Runway 05L/23R removed
