### ISSUE TITLE
MBPI-Pine Cay Airport-PROVIDENCIALES AND WEST CAICOS-TURKS AND CAICOS ISLANDS

### ISSUE THREAD

**Issue by Tamz00** [InfiniteFlightAirportEditing/Airports#2581]
Airport is misaligned. I’ll redo it soon.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34546598-857c0b22-f0ba-11e7-8918-6788a72c5be7.png)
