### ISSUE TITLE
EKVD-Kolding Vamdrup Airport-VEJLE-DENMARK

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#2584]

**Comment by MajorTomMueller** [comment]
![ekvd-git](https://user-images.githubusercontent.com/26853210/34461923-998c4f34-ee38-11e7-9a0f-b421a2f1a474.jpeg)

**Comment by MajorTomMueller** [comment]
-boundary fix
-Buildings removed
-Hangar Floors added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46257974-bd942880-c488-11e8-8136-5246fe7fd875.png)
