### ISSUE TITLE
RPMS-Surigao Airport-SURIGAO DEL NORTE-PHILIPPINES

### ISSUE THREAD

**Issue by captavgeek** [InfiniteFlightAirportEditing/Airports#2586]
I'll do this

**Comment by moritzbabl** [comment]
member inactive, up for grabs

**Comment by itsmeraven** [comment]
I'll do this

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/40569300-144d6440-6046-11e8-8cac-6cb979b1fc33.png)
