### ISSUE TITLE
EKMB-Lolland Faister/ Maribo Airport-STORSTROM-DENMARK

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#2587]

**Comment by MajorTomMueller** [comment]
![ekmb-git1](https://user-images.githubusercontent.com/26853210/34469974-696c9caa-ef28-11e7-9bd9-82a9ad6abb3b.jpg)

**Comment by MajorTomMueller** [comment]
-boundary fix
-buildings removed
-hangar floors added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46246428-eeaa2580-c3c2-11e8-82fd-83b836e9fff5.png)
