### ISSUE TITLE
RJCH-Hakodate Airport-HOKKAIDO-JAPAN

### ISSUE THREAD

**Issue by benlenahan** [InfiniteFlightAirportEditing/Airports#2592]
I'll take this as I have already redone it. I know it will be my fourth issue, but I was told this is ok if it's only for submission.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34699695-6f6e0036-f4a4-11e7-879d-6cc40dbccceb.png)
