### ISSUE TITLE
KTUL-Tulsa International Airport-OKLAHOMA-USA

### ISSUE THREAD

**Issue by captavgeek** [InfiniteFlightAirportEditing/Airports#2593]
♻️

**Comment by moritzbabl** [comment]
member inactive, up for grabs

**Comment by Aviationluver** [comment]
Taking this one.

**Comment by moritzbabl** [comment]
@dushyants19 you added the airport 3 days ago, but didn't close the issue. Any reason or accidentally?

**Comment by dushyants19** [comment]
Forgot. Sorry.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/39336533-aac0152e-497d-11e8-8b8b-856a32b5dc22.png)
