### ISSUE TITLE
RPLV-Fort Magsaysay Airport-NUEVA ECIJA-PHILIPPINES

### ISSUE THREAD

**Issue by superven13** [InfiniteFlightAirportEditing/Airports#2596]
I will start from scratch and add every anything needed! :}

**Comment by superven13** [comment]
Sent For Review!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34697819-7c592bc2-f49a-11e7-90be-2aa50ea496fd.png)
