### ISSUE TITLE
KECP-Northwest Florida Beaches International Airport-FLORIDA-USA

### ISSUE THREAD

**Issue by JamesBrowne1** [InfiniteFlightAirportEditing/Airports#2599]
♻️

**Comment by brunocr98** [comment]
Issue solved in #418

**Comment by kilt46** [comment]
Done from scratch

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/35134223-a2fa828c-fc9a-11e7-9827-1df5ecfca7e4.png)
