### ISSUE TITLE
EDLN-Düsseldorf Mönchengladbach Airport-NORDRHEIN-WESTFALEN-GERMANY

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#260]
Mönchengladbach Airport

**Comment by kilt46** [comment]
Started work

**Comment by kilt46** [comment]
Complete. File sent to Cameron

**Comment by JcFl4** [comment]
Kilt46, what work did you do on the airport? I had already done it?

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/16789119/6074db4a-4870-11e6-9609-f0595a1489ac.jpeg)
Hatching needs removed

**Comment by samuelandersson** [comment]
Removed hashed regions.

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/46e7be27056bb362a8f1c04eecd0d7b966f8b5a3)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18615274/0681f640-7d68-11e6-9a26-6c4271d7ebf5.png)

**Comment by CptNathanHope** [comment]
Found a slight design mistake. I'll try to fix it before the end of the week. :)

![img_2384](https://cloud.githubusercontent.com/assets/19478765/21123235/85679098-c0a5-11e6-9e10-21343cb4aadb.JPG)

**Comment by CptNathanHope** [comment]
@dushyants19 I apologize about this. I'll try to get to it at some point this weekend. Thanks for the heads-up! :)

**Comment by CptNathanHope** [comment]
Submitted for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25771658/4774bc0e-321d-11e7-948b-7cd4ae3d90f1.png)
