### ISSUE TITLE
EKHG-Herning Skinderhol Airport-RINGKOBING-DENMARK

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#2600]

**Comment by MajorTomMueller** [comment]
![ekhg-git](https://user-images.githubusercontent.com/26853210/34917069-bdf2da14-f941-11e7-8f47-b227a0e5c702.jpeg)

**Comment by MajorTomMueller** [comment]
-boundary fix
-buildings removed
-hangar floors added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46246343-c0781600-c3c1-11e8-85bf-f5bbb769839e.png)
