### ISSUE TITLE
SBMO-Maceio/Zumbi Dos Palmares Airport-ALAGOAS-BRAZIL

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Airports#2601]

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/35196511-9b8e3b60-fe98-11e7-9823-a2b7bf18f96c.png)

**Comment by MBeringuy** [comment]
Updated airport.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112059020-53284480-8b29-11eb-8e63-84181ec0e7c4.png)
