### ISSUE TITLE
UHBB-Blagoveshchensk/Ignatyevo Airport-AMUR-RUSSIA

### ISSUE THREAD

**Issue by VladK125rus** [InfiniteFlightAirportEditing/Airports#2608]
I'll do it

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/35195572-2732c25c-fe8b-11e7-9675-7599c7a37077.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/43984401-0979b160-9cc6-11e8-8599-1df0d935d6ae.png)
