### ISSUE TITLE
RPUR-Baler Community Airport-AURORA-PHILIPPINES 

### ISSUE THREAD

**Issue by superven13** [InfiniteFlightAirportEditing/Airports#2609]
I will start from scratch!!

**Comment by moritzbabl** [comment]
Member inactive, up for grabs

**Comment by itsmeraven** [comment]
I'll do this

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/40569353-86e9d1b4-6046-11e8-8af6-258c9fbdebd4.png)
