### ISSUE TITLE
KTNT

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#261]
South Florida

**Comment by Omari4u** [comment]
working on taxi ways spawning points and other areas..

**Comment by kilt46** [comment]
Does this mean this is available to take? It states 'Being Redone but no-one assigned. I am confused!

**Comment by JohnPreston21** [comment]
Is anyone doing this one? It says being redone but no one assigned.

**Comment by JohnPreston21** [comment]
Opps

**Comment by kilt46** [comment]
Gates added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21075753/76c6afd2-bedf-11e6-8175-e83377f575dc.png)
