### ISSUE TITLE
RPVK-Kalibo Airport-AKLAN-PHILIPPINES 

### ISSUE THREAD

**Issue by superven13** [InfiniteFlightAirportEditing/Airports#2610]
I will start from scratch!

**Comment by moritzbabl** [comment]
Member inactive, up for grabs

**Comment by itsmeraven** [comment]
I'll do this

**Comment by brunocr98** [comment]
Please rejoin our team at contact@airportediting.com

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/40575354-fa9fb94a-60a8-11e8-8071-a0496941a519.png)
