### ISSUE TITLE
4V8-Deerfield Valley Regional Airport-VERMONT-USA

### ISSUE THREAD

**Issue by grizpac** [InfiniteFlightAirportEditing/Airports#2611]
Part of [Project New England](https://community.infinite-flight.com/t/project-new-england/43169)

**Comment by grizpac** [comment]
Submitted for official review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/35485344-ebe10788-0423-11e8-8ea6-e558142debcf.png)
