### ISSUE TITLE
ENOV-Orsta Volda-Hovden Airport-MORE OG ROMSDAL-NORWAY

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#2615]
Orsta Volda Airport, Norway

**Comment by bavAVIA** [comment]
D to the o to the n to the e.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34921701-763e6918-f94b-11e7-85a3-a79396600360.png)
