### ISSUE TITLE
4IL2-Wayne Ziller Strip-ILLINOIS-USA

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#2616]
Kortrijk Wevelgem Airport, Belgium

**Comment by CaptainGeorgeIF** [comment]
Hello
I want to make the airport. Can I get assigned to this? I'll do a full rework.
Thanks!

**Comment by CaptainGeorgeIF** [comment]
Can anyone assign me, please ?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90574265-17399500-e17e-11ea-92fb-99ab67f9c8e8.png)
