### ISSUE TITLE
KONT-Ontario International Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by Misha16** [InfiniteFlightAirportEditing/Airports#262]
Needs more spawn points and a little tiny up of lines

**Comment by kilt46** [comment]
Will work on next as is top of list

**Comment by kilt46** [comment]
Now complete. Terminals 1, 1A, 2 and 4 redone

**Comment by kilt46** [comment]
Reworking Aprons

**Comment by kilt46** [comment]
Solidified into 3 aprons. tidy of gates

**Comment by kilt46** [comment]
KONT
<img src="/uploads/infinite_flight/original/3X/4/2/4269bba65bdf4b17f6cb67c895cddcd92b7d2664.png" width="690" height="273">
TERMINAL 1
<img src="/uploads/infinite_flight/original/3X/8/8/88aaee645d36029a62e407f2cb96cb6aba130959.jpg" width="455" height="313">
TERMINAL 2
<img src="/uploads/infinite_flight/original/3X/1/8/1846c6cd902b7e871682c7aef63db62d6fad0747.jpg" width="690" height="313">
TERMINAL 4
<img src="/uploads/infinite_flight/original/3X/b/f/bf92817818f89d5481cbdfae6638812993b17e85.jpg" width="669" height="216">

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/71906481-eb1a5800-3148-11ea-9a28-0a6a60155194.jpg)

**Comment by MBeringuy** [comment]
Update: FedEx apron on north side; southern cargo apron; International Terminal; correction of some yellow center lines to access runway 8R/26L; correction of lighting on the runways.
![KONT](https://user-images.githubusercontent.com/32115399/126400256-a768fec1-6edb-40f2-9905-56fb1143e266.jpg)
