### ISSUE TITLE
CYQT-Thunder Bay International Airport-ONTARIO-CANADA

### ISSUE THREAD

**Issue by DelsterX** [InfiniteFlightAirportEditing/Airports#2622]
I will take this one.

**Comment by DelsterX** [comment]
Sent in for review.

**Comment by DelsterX** [comment]
This has been approved Feb 13th but issue has not been closed.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36401133-02886f98-159b-11e8-94f7-ae6b269be232.png)
