### ISSUE TITLE
ZGZJ-Zhanjiang Airport-GUANGDONG-CHINA

### ISSUE THREAD

**Issue by CNwyang** [InfiniteFlightAirportEditing/Airports#2623]
have been doing this.

**Comment by CNwyang** [comment]
uhh…my mistake,the province is GUANGDONG not GUANGZHOU，fixed it

**Comment by CNwyang** [comment]
Sent for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/35196422-6c337a7a-fe97-11e7-85d0-ef3c963206fa.png)
