### ISSUE TITLE
ZBYN-Taiyuan/Wusu Airport-SHANXI-CHINA

### ISSUE THREAD

**Issue by CNwyang** [InfiniteFlightAirportEditing/Airports#2624]
redoing this airport.

**Comment by CNwyang** [comment]
sent for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/35177042-703cf43a-fd42-11e7-8704-2e942b86bfda.png)
