### ISSUE TITLE
VVDN-Da Nang International Airport-NAM TRUNG-VIETNAM

### ISSUE THREAD

**Issue by VladK125rus** [InfiniteFlightAirportEditing/Airports#2625]
I'll do it

**Comment by ryu12332** [comment]
Do not quit airports you are assigned to because there are too many issues. Either complete then correctly the first time or don't start them at all. We are not here to serve you, and this has been an incredible waste of time for everyone involved. You are going to finish this airport prior to doing any other airports. End of story.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
Please gate as per diagram
![image](https://user-images.githubusercontent.com/14023167/36698398-5d7f46e6-1b0f-11e8-8a5c-b5d17f676dd1.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36702328-4415b912-1b1c-11e8-8a64-827b27230894.png)
Done it myself!!

**Comment by GBKarp** [comment]
@IFUA2003 still working on this?

**Comment by IFUA2003** [comment]
@GBKarp sorry, I was in the examination :( I didn’t reply to you sooner. I’m still working on this.

**Comment by brunocr1050** [comment]
@IFUA2003 did you join our new Discord group? If yes, what's your username?

**Comment by IFUA2003** [comment]
No, I haven’t joined yet 😳

**Comment by IFUA2003** [comment]
Hello, I’m still working on this airport, and expect next week I will send it to OR. Since last night you removed me from Discord

**Comment by brunocr1050** [comment]
The person currently assigned to this airport submitted it to OR already. After the activity check was over, this issue like many others were put of for grabs and soon after someone claimed it. I'm sorry for the inconvenience, but I'm taking the tough decision to accept the work that was submitted first to OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114271058-2dc68200-99d5-11eb-9840-ab6f4de4c501.png)
