### ISSUE TITLE
ZSQZ-Quanzhou/Jinjiang Airport-FUJIAN-CHINA

### ISSUE THREAD

**Issue by CNwyang** [InfiniteFlightAirportEditing/Airports#2626]
a small one, doing it.

**Comment by CNwyang** [comment]
sent for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36352325-c1ca7af6-147c-11e8-8d0a-89273e8279a8.png)
