### ISSUE TITLE
KLSV-Nellis AFB Airport-NEVADA-USA

### ISSUE THREAD

**Issue by IFBR0006** [InfiniteFlightAirportEditing/Airports#2627]
Santa Genoveva Airport, i'll do it

**Comment by moritzbabl** [comment]
member inactive, up for grabs

**Comment by MajorTomMueller** [comment]
![recycle](https://user-images.githubusercontent.com/26853210/41292416-cc68e6e8-6e52-11e8-8f8a-d241432b55f7.png)

**Comment by MajorTomMueller** [comment]
No buildings,
No holes for pavement patches
![klsv-git](https://user-images.githubusercontent.com/26853210/42021693-8f1016ca-7abb-11e8-84f2-e04bb249a16d.jpg)

**Comment by MajorTomMueller** [comment]
![KLSV-git](https://user-images.githubusercontent.com/26853210/128640319-c8251fbe-a6fe-4687-be19-1ca1d85e9db0.png)

**Comment by MajorTomMueller** [comment]
new ram,ps added
