### ISSUE TITLE
TKPK-Robert L Bradshaw Airport-BASSETERRE-SAINT KITTS AND NEVIS

### ISSUE THREAD

**Issue by Swang007** [InfiniteFlightAirportEditing/Airports#263]
Runway spawns need to be removed, I'll do it.

**Comment by Swang007** [comment]
Sorry for including you guys. Selection doesn't work well on iPhone.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20644641/1da597f8-b401-11e6-8922-6f583962b346.png)

**Comment by MajorTomMueller** [comment]
Can a sup edit the stands at TKPK? BA has a scheduled 772 service, but it can’t spawn in IF
Stand 2

**Comment by MajorTomMueller** [comment]
Will care at home when no one else did before.

**Comment by kilt46** [comment]
Size D Class added
![image](https://user-images.githubusercontent.com/14023167/84832649-4d7a5d00-aff3-11ea-9950-cd0ad7f67c7c.png)

**Comment by brennanhackard** [comment]
@Aceorbit will be making the following improvements to this airport:

- adding missing markings
- fixing taxiway materials and geometry
- spawn fixes
- removing buildings
- fixing improperly made lines
- frequency fixes

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/117539110-b6354400-afce-11eb-8275-b47890c37867.png)
