### ISSUE TITLE
CAM3-Duncan Airport-BRITISH COLUMBIA-CANADA

### ISSUE THREAD

**Issue by renorris** [InfiniteFlightAirportEditing/Airports#2633]
I'll do this

**Comment by brunocr98** [comment]
Please finish your other 3 airports in order to be assigned to this one.

**Comment by renorris** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36768239-c8320b46-1c03-11e8-862e-a68fe42a9b42.png)
