### ISSUE TITLE
LFPO-Paris Orly Airport-ILE-DE-FRANCE-FRANCE

### ISSUE THREAD

**Issue by AxelBeder** [InfiniteFlightAirportEditing/Airports#264]
Rewroking from scratch.

**Comment by kilt46** [comment]
Requires all gates

**Comment by IceBlue02** [comment]
@kilt46 have you redone this?

**Comment by NickArt1342** [comment]
@AxelBeder How is this one coming along?

**Comment by IFAEpat** [comment]
@AxelBeder anything?

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25771073/8bc5547e-320c-11e7-8c5c-c6e07adfaf78.png)

**Comment by MajorTomMueller** [comment]
Runway moved, several other changes. Work is incomplete in satellite images yet.
https://www.sia.aviation-civile.gouv.fr/dvd/eAIP_18_JUN_2020/FRANCE/AIRAC-2020-06-18/html/eAIP/Cartes/LFPO/AD%202%20LFPO%20ADC%2001.pdf

**Comment by OscarConklin** [comment]
Could I please be assigned to this?

**Comment by MajorTomMueller** [comment]
Have you chacke satelite images @OscarConklin ?
![orly](https://user-images.githubusercontent.com/26853210/88569227-aa712600-d029-11ea-91ba-a55a17856819.png)

**Comment by OscarConklin** [comment]
I know the imagery is bad, but I assumed that by the time I finish done redoing Cebu and Naha there will probably be better imagery from either Bing or Google. If I am wrong I can always do a different airport.

**Comment by Czechoslovaki** [comment]
@OscarConklin Bing and Google are really slow when it comes to updating imagery, so I highly doubt by the time you finish your other two airports imagery will be updated.

**Comment by zhf21** [comment]
I don't think Apple Maps works, but if so, they have it updated. 

<img width="822" alt="Screen Shot 2020-08-12 at 10 48 16 PM" src="https://user-images.githubusercontent.com/67797012/90088829-eaa0fb80-dced-11ea-861b-a7643870ed0c.png">

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/93891501-192cd180-fcb1-11ea-8ddf-1d8a45a8d5b7.png)

**Comment by Czechoslovaki** [comment]
- New asphalt taxiways @ rwy 25 (07/25 also repaved to asphalt)
- PAPI lights to be added / moved for all runways
- Missing / random markings scattered throughout airport
- Missing ramp starts
- Runway shoulders not accurate
- Taxiways appear haphazardly drawn (ie. illegal overlapping, no snapping) / some surfaces missing, incorrect material
- High marking inaccuracy (holds not snapped to edges, overcurves, poor layering)

**Comment by Czechoslovaki** [comment]
![image](https://user-images.githubusercontent.com/51279558/126076559-1d115b2d-88dd-4b2c-aa4e-51783a8ac830.png)
