### ISSUE TITLE
ULMM-Murmansk Airport-MURMANSK-RUSSIA

### ISSUE THREAD

**Issue by VladK125rus** [InfiniteFlightAirportEditing/Airports#2640]
I'll do it

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36352096-67005904-1479-11e8-86e6-39dc8efb76cf.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36352096-67005904-1479-11e8-86e6-39dc8efb76cf.png)
