### ISSUE TITLE
EVGA-Lielvarde Airport-RIGA-LATVIA

### ISSUE THREAD

**Issue by canoneoswen** [InfiniteFlightAirportEditing/Airports#2646]
♻️

**Comment by MajorTomMueller** [comment]
![recycle](https://user-images.githubusercontent.com/26853210/42025490-f55da95c-7ac4-11e8-8cab-b0d44f0ebdc3.png)

**Comment by MajorTomMueller** [comment]
no buildings
no holes for pavement patches
![evga-git](https://user-images.githubusercontent.com/26853210/42030737-1c702af6-7ad4-11e8-8db4-76b4a396ad3a.jpg)

**Comment by kilt46** [comment]
This airport currently shows oft elevation. Should be at 200 ft!

**Comment by MajorTomMueller** [comment]
fixed.
source:https://ais.lgs.lv/aiseaip
https://ais.lgs.lv/eAIPfiles/2018_005_19-JUL-2018/data/2018-07-19-AIRAC/html/index.html
thx for remark
