### ISSUE TITLE
RKSO-Osan Air Base-GYEONGGI-DO-SOUTH KOREA

### ISSUE THREAD

**Issue by canoneoswen** [InfiniteFlightAirportEditing/Airports#2647]
Songshan Airport,I will do it

**Comment by CPTTONG** [comment]
taxiway and ramp should be rework

**Comment by CptNathanHope** [comment]
@CPTTONG: Please send an email requesting to join our GitHub and Slack groups.

contact@airportediting.com. 

Thank you, good day!

**Comment by MajorTomMueller** [comment]
![recycle](https://user-images.githubusercontent.com/26853210/42041823-0cb97a08-7af3-11e8-8373-a72273c3d904.png)

**Comment by MajorTomMueller** [comment]
![rkso-git](https://user-images.githubusercontent.com/26853210/42724732-099444e8-8778-11e8-893e-85d59a30d533.jpg)
-no Buildings
-no pavement patches holes

**Comment by kilt46** [comment]
Looks like a slight offset with Satellite - See red dots
![image](https://user-images.githubusercontent.com/14023167/42733795-93f8ac3e-87fd-11e8-9e14-4aeb903f0310.png)
Also curious that 09R/27L does not show active in Jepessen
![image](https://user-images.githubusercontent.com/14023167/42733799-b28da276-87fd-11e8-863b-4fac50390987.png)

**Comment by MajorTomMueller** [comment]
Cross-checked the runway threshold coordinates with different sources. They correlate pretty well with only one differing 19.1ft as a result if less precession of this source itself.
I will leave it as it is fitting the Bing image as well.
![rkso-runways](https://user-images.githubusercontent.com/26853210/42734716-1e5a5760-8849-11e8-9a1c-4c5545191c24.jpg)
If someone can provide official (USAF or South Korean Gov.) coordinates for the thresholds please reopen and comment.
