### ISSUE TITLE
LFPZ

### ISSUE THREAD

**Issue by AxelBeder** [InfiniteFlightAirportEditing/Airports#265]

**Comment by AxelBeder** [comment]
Finished.

**Comment by henrikbg** [comment]
Runway lengths are incorrect for runway 11:

http://community.infinite-flight.com/t/bug-in-paris-france-airport-lfpz-runway-11/72636?u=henrik

**Comment by henrikbg** [comment]
Disregard the labels, runways are correct.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19294772/4508a324-8ff5-11e6-8d65-c71e0c6dfb55.png)
