### ISSUE TITLE
EKRS-Ringsted Airport-VESTSJAELLAND-DENMARK

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#2652]

**Comment by MajorTomMueller** [comment]
-Boundary fix
-Buildings removed
-Hangar Floors added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46260830-c8fb4a00-c4b0-11e8-9977-e609a8d39024.png)
