### ISSUE TITLE
FBSK-Sir Seretse Khama International Airport-GABORONE-BOTSWANA

### ISSUE THREAD

**Issue by IFBR0006** [InfiniteFlightAirportEditing/Airports#2655]
Recycled

**Comment by moritzbabl** [comment]
member inactive, up for grabs

**Comment by moritzbabl** [comment]
Recycled to Gaborone Airport, capital of Botswana and first Airport in the country

**Comment by moritzbabl** [comment]
done, first airport in edited in Botswana, No.148

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/41076598-05eb8f12-69d8-11e8-9196-20b55084880d.png)

**Comment by MBeringuy** [comment]
Buildings removed, hangars changed to concrete and frequencies updated.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103316389-f7e52b00-49ed-11eb-94b7-4b91f57fdf67.png)
