### ISSUE TITLE
EEHU-Haapsalu Airfield-ESTONIA

### ISSUE THREAD

**Issue by tang0325** [InfiniteFlightAirportEditing/Airports#2656]
I will do it.
It is a small airport.

**Comment by tang0325** [comment]
sent for review

**Comment by MajorTomMueller** [comment]
![eehu-git](https://user-images.githubusercontent.com/26853210/42967540-db7b3404-8ba0-11e8-9f9c-9cf653605526.jpg)

**Comment by kilt46** [comment]
This is a disused airfield. I suggest it is deleted and removed from the database

**Comment by MajorTomMueller** [comment]
The Airfield is used in a regular basis for training of NATO forces. That is why I have added it. I suggest to keep it.
