### ISSUE TITLE
KDXR-Danbury Municipal Airport-CONNECTICUT-USA

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Airports#2662]
Part of [Project New England](https://community.infinite-flight.com/t/project-new-england/43169).

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36062066-77fe9680-0e2a-11e8-8e37-349904a72d46.png)

**Comment by ryu12332** [comment]
ISSUE: Boundary is clipped. Main taxiway is not snapped. Runway markings are incorrect. Might want to give this one a closer look for over curving, extra nodes, and taxiways snapped to themselves.

**Comment by benlenahan** [comment]
Also, entire airport has been snapped to itself. Turn off runway visibility to see this. 
I "undid" a few nodes here:
![image](https://user-images.githubusercontent.com/27709408/36084526-5ae38dd8-0f7b-11e8-8e2b-aea97f5a5a05.png)
Also several lines have arrows that need to be de-clicked.
