### ISSUE TITLE
CYFC-Fredericton International Airport-NEW BRUNSWICK-CANADA

### ISSUE THREAD

**Issue by DelsterX** [InfiniteFlightAirportEditing/Airports#2663]
I will do this one. 

Part of Project Canada

**Comment by DelsterX** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36340842-3065ae64-13aa-11e8-98da-c8ac49856a78.png)
