### ISSUE TITLE
KUMP-Indianapolis Metropolitan Airport-INDIANA-USA

### ISSUE THREAD

**Issue by danielacooper** [InfiniteFlightAirportEditing/Airports#2667]
Would like to redo this airport - add taxiways, hangars, etc

**Comment by danielacooper** [comment]
sent to contact@airportediting.com

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36340935-1fc9d5c4-13ac-11e8-9a23-e1b9aa8a1b6a.png)
