### ISSUE TITLE
SDUN-Itaperuna Airport-RIO DE JANEIRO-BRAZIL

### ISSUE THREAD

**Issue by IFBR0006** [InfiniteFlightAirportEditing/Airports#2668]
Aeroporto de Itaperuna, i'll do it

**Comment by moritzbabl** [comment]
member inactive, up for grabs

**Comment by johanneskkl** [comment]
will take this

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/39557126-e4f2d17e-4e4a-11e8-94bf-a9f1ead186ee.png)

**Comment by MBeringuy** [comment]
Airport redone.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/49685818-5611df00-fab0-11e8-9e81-c49da03e0d4f.png)
