### ISSUE TITLE
KNUQ-Moffett Federal Airfield-CALIFORNIA-USA

### ISSUE THREAD

**Issue by AxelBeder** [InfiniteFlightAirportEditing/Airports#267]
Finished.

**Comment by kilt46** [comment]
Missing Runway HOLDS
![image](https://cloud.githubusercontent.com/assets/14023167/11452515/be1fb28e-95af-11e5-8f64-190b76dd59bc.png)

**Comment by kilt46** [comment]
Marked up version added to library

**Comment by henrikbg** [comment]
There's a lot of gaps between the taxiways and the runways.

**Comment by dushyants19** [comment]
Did some make up 💁  and added in e789143be4f78bb7e1b7c3eb7aba86af6b116ec0

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18897844/05d9d8f6-84f3-11e6-8f30-52ccc68a1ed7.png)
