### ISSUE TITLE
KMIE-Delaware County Regional Airport-INDIANA-USA

### ISSUE THREAD

**Issue by danielacooper** [InfiniteFlightAirportEditing/Airports#2679]
Part of Project Indiana

**Comment by ryu12332** [comment]
4th assigned airport is approved.

**Comment by danielacooper** [comment]
Sent to contact@airportediting.com

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36761600-6fe9fa20-1be5-11e8-9ff7-46f68fc329ee.png)
