### ISSUE TITLE
EGLF

### ISSUE THREAD

**Issue by jpperks** [InfiniteFlightAirportEditing/Airports#268]
I'll take this...

Free time woohoo!!!

**Comment by JohnPreston21** [comment]
This is awesome

**Comment by jpperks** [comment]
Watched the Farnborough air show?

**Comment by carmichaelalonso** [comment]
How's this going Jonathan? (testing Slack integration...)

**Comment by jpperks** [comment]
I started it when I had free time... Haven't had much time since then :)

**Comment by kilt46** [comment]
Need me to help?

On Sun, Sep 20, 2015 at 11:23 AM, Jonathan Perkins <notifications@github.com

**Comment by jpperks** [comment]
Yes I think I do! Thanks :)

Current progress can be found here http://jpapps.co.uk/eglf.html

**Comment by kilt46** [comment]
Will do this for Jonathan

**Comment by kilt46** [comment]
Focusing on Heathrow

**Comment by kilt46** [comment]
still only 2 spawn points.

**Comment by Will171** [comment]
ill claim this one :)

**Comment by Will171** [comment]
look like it needs an update, will re draw the aprons

**Comment by dushyants19** [comment]
Update given

**Comment by dushyants19** [comment]
Forgot to close :///

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18800221/7730d0a4-81a1-11e6-872e-50d4e56c6e47.png)

**Comment by GiacomoLaw** [comment]
Glad to see my home airport is edited! 😊

**Comment by Will171** [comment]
No problem dude

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45397352-4562e180-b605-11e8-9853-32c6fcd33384.png)
