### ISSUE TITLE
UNEE-Kemerovo/Alexey Leonov Airport-KEMEROVO-RUSSIA

### ISSUE THREAD

**Issue by VladK125rus** [InfiniteFlightAirportEditing/Airports#2680]
I'll do this airport.

**Comment by VladK125rus** [comment]
I made , but waiting for official review of my 2 last airports.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36351988-344990d6-1477-11e8-9849-d62f7e2cb99b.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44063738-81b97ae4-9f27-11e8-99bf-686febdffc0a.png)
