### ISSUE TITLE
CYYG-Charlottetown Airport-PRINCE EDWARD ISLAND-CANADA

### ISSUE THREAD

**Issue by DelsterX** [InfiniteFlightAirportEditing/Airports#2681]
I will do this.

Part of Project Canada

**Comment by DelsterX** [comment]
Sent for review...finally! : )

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42604598-3c1eb812-8539-11e8-98af-db5fe6479650.png)
