### ISSUE TITLE
KAID-Anderson Municipal-Darlington Field Airport-INDIANA-USA

### ISSUE THREAD

**Issue by danielacooper** [InfiniteFlightAirportEditing/Airports#2687]
Part of Project Indiana

**Comment by ryu12332** [comment]
5th assigned airport is approved.

**Comment by danielacooper** [comment]
Sent to contact@airportediting.com for review

**Comment by ryu12332** [comment]
Up for grabs.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/41075424-33285ae2-69d2-11e8-8aec-03dc2aad9662.png)
