### ISSUE TITLE
KEYE-Eagle Creek Airpark-INDIANA-USA

### ISSUE THREAD

**Issue by danielacooper** [InfiniteFlightAirportEditing/Airports#2691]
Redo twys, parking, etc. Part of Project Indiana

**Comment by ryu12332** [comment]
6th assigned airport is approved.

**Comment by danielacooper** [comment]
Submitted for review

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36341035-a2976182-13ad-11e8-90b6-167c9f8ad0d6.png)
