### ISSUE TITLE
2R2-Hendricks County-Gordon Graham Field-INDIANA-USA

### ISSUE THREAD

**Issue by danielacooper** [InfiniteFlightAirportEditing/Airports#2693]
Part of Project Indiana

**Comment by danielacooper** [comment]
Submitted for review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36761716-ff1686fa-1be5-11e8-9c7b-28100132efaf.png)
