### ISSUE TITLE
LRCL-Avram Iancu Airport-CLUJ-ROMANIA

### ISSUE THREAD

**Issue by skotshi** [InfiniteFlightAirportEditing/Airports#2695]

**Comment by moritzbabl** [comment]
member inactive, up for grabs

**Comment by johanneskkl** [comment]
will take this

**Comment by johanneskkl** [comment]
imagery outdated. More recent imagery is atrocious, awful, cheap, crummy, dreadful and bottomed out, as it some areas it completely reflects light. This imagery is not satisfactory for a high quality-detailed airport. Will eventually re-take this in a while.

**Comment by MajorTomMueller** [comment]
excellent AIP documents, challenge accepted

**Comment by MajorTomMueller** [comment]
![lrcl-git](https://user-images.githubusercontent.com/26853210/38310360-a2e98442-381c-11e8-9654-ecf45248b5ab.jpg)
