### ISSUE TITLE
CYMW-Maniwaki Airport-QUEBEC-CANADA

### ISSUE THREAD

**Issue by renorris** [InfiniteFlightAirportEditing/Airports#2696]
I'll take this airport

**Comment by renorris** [comment]
Sent for review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36768352-63ad772c-1c04-11e8-8f80-9fb5a9cda5ce.png)
