### ISSUE TITLE
OAFZ-Feyzabad Airport-BADAKHASHAN-AFGHANISTAN

### ISSUE THREAD

**Issue by MrAlaska** [InfiniteFlightAirportEditing/Airports#2697]
Yakima Air Terminal/McAllister Field. I will do it.

**Comment by kennethbgamboa** [comment]
Can I take this one?

**Comment by ryu12332** [comment]
You haven't accepted the collaboration invite, so we can't assign you. Check your email.

**Comment by kennethbgamboa** [comment]
Is this the collaboration invite? If it is something seems to be wrong.


[Image]


[Image]



________________________________

**Comment by dushyants19** [comment]
Nothing's wrong, hit this link and accept the invite. https://github.com/InfiniteFlightAirportEditing/Airports/invitations

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by MajorTomMueller** [comment]
![OAFZ](https://user-images.githubusercontent.com/26853210/54360775-e63e6200-4665-11e9-9c91-6475912f7980.jpg)
