### ISSUE TITLE
RJCR-Rebun Airport-HOKKAIDO-JAPAN

### ISSUE THREAD

**Issue by benlenahan** [InfiniteFlightAirportEditing/Airports#2698]
Part of Project Japan.

**Comment by benlenahan** [comment]
Submitted.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36761210-a867e6f2-1be3-11e8-8fad-30e827ccc2b6.png)
