### ISSUE TITLE
KBNA-Nashville International Airport-TENNESSEE-USA

### ISSUE THREAD

**Issue by CNwyang** [InfiniteFlightAirportEditing/Airports#2699]
♻️

**Comment by moritzbabl** [comment]
member inactive, up for grabs

**Comment by netjets-1951** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45186664-df84ed00-b1f3-11e8-8a99-43bb1ce5105f.png)
