### ISSUE TITLE
TAPA-St Johns/Vc Bird (Antigua) Airport-SAINT GEORGE-ANTIGUA AND BARBUDA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#27]

**Comment by carmichaelalonso** [comment]
Done by JcFl

**Comment by carmichaelalonso** [comment]
Fixes by David Cutler

**Comment by JcFl4** [comment]
The airport is misaligned.

**Comment by Swang007** [comment]
Misaligned as in not lined up with WEDBing? If so, I just committed a fix for that.

**Comment by kilt46** [comment]
New terminal added. Airport aligned

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20641355/c5f34e50-b3bb-11e6-9448-9530b4698b6f.png)

**Comment by MajorTomMueller** [comment]
Hole in the Taxiway
![tapa-hole](https://user-images.githubusercontent.com/26853210/34411424-ca6604d8-ebd6-11e7-8fc5-ab6b8faa0329.jpeg)
unsnaped Lines
TWY missaligned
...

**Comment by MajorTomMueller** [comment]
@ewanfleming want's to do as soon as his other issues that are in review were closed.

**Comment by ryu12332** [comment]
In for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36352492-77ffb7e4-147f-11e8-903c-2dcef9bdb725.png)
