### ISSUE TITLE
PKMJ-Marshall Islands Airport-MAJURO-MARSHALL ISLANDS

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#270]
Please redesign me!

**Comment by kilt46** [comment]
Airport redone

**Comment by kilt46** [comment]
Runway holds fixed

**Comment by Hamza1108** [comment]
Is this still open??I would like to take it if it is available.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25515268/ffbc0bee-2ba8-11e7-94f8-0a6868e9b2b0.png)
