### ISSUE TITLE
OABN-Bamyan Airport-BAMYAN-AFGHANISTAN

### ISSUE THREAD

**Issue by CNwyang** [InfiniteFlightAirportEditing/Airports#2700]
a small one, will do it.

**Comment by moritzbabl** [comment]
member inactive, up for grabs

**Comment by CNwyang** [comment]
Im back and am doing it now.lol

**Comment by brunocr98** [comment]
Please send an email to rejoin the team.

**Comment by CNwyang** [comment]
well I`ve already sent one to dush,who has reactivated my slack account.lol

**Comment by moritzbabl** [comment]
Dush didn’t send a GitHub invite, check your mails now and accept the invitation in the mail I sent you via GitHub

**Comment by CNwyang** [comment]
invitation accepted,thanks!

**Comment by MajorTomMueller** [comment]
@CNwyang still working on it?

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by MajorTomMueller** [comment]
![recycle](https://user-images.githubusercontent.com/26853210/54357031-5c8a9680-465d-11e9-8bf7-95880a70fd5d.png)

**Comment by MajorTomMueller** [comment]
![OABN](https://user-images.githubusercontent.com/26853210/54358643-23ecbc00-4661-11e9-9cd8-f1937a805e02.jpg)
