### ISSUE TITLE
KDAL-Dallas Love Field-TEXAS-USA

### ISSUE THREAD

**Issue by bamaflying** [InfiniteFlightAirportEditing/Airports#2704]
I can redo it. It is not complete.

**Comment by CptNathanHope** [comment]
Email us at contact@airportediting.com to join our team, please. Thank you!

**Comment by schyllberg** [comment]
Yeah, this needs some love. Like.. really fast. Come on now people! You can do it! / MOD ^^

**Comment by ewanfleming** [comment]
Stop abusing your powers :stuck_out_tounge_winking_eye:

**Comment by dushyants19** [comment]
https://imgur.com/a/56VsT

**Comment by acaplash19** [comment]
I will do it.

**Comment by ewanfleming** [comment]
No, you won’t. This is assigned to someone else, you’ll have to go look elsewhere for something to edit. Thanks

**Comment by moritzbabl** [comment]
How is this one going @acaplash19 ?

**Comment by acaplash19** [comment]
@moritzbabl running into a few problems, should be done by the end of this week.

**Comment by ewanfleming** [comment]
Sent in for review.

**Comment by ewanfleming** [comment]
Apologies for stealing it off you, but the airport was long overdue and we weren't getting anywhere.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42724782-0795983e-873e-11e8-8c37-2ee4362de34b.png)

**Comment by kilt46** [comment]
Should ONLY be 2 PAPIs in the model. Please adjust
![image](https://user-images.githubusercontent.com/14023167/42724811-76c22542-873e-11e8-930b-a06345d33320.png)

**Comment by kilt46** [comment]
Also here are the ATC frequencies. List could be more complete
![image](https://user-images.githubusercontent.com/14023167/42724838-1125c2f6-873f-11e8-9a60-1c35a0c11979.png)

**Comment by ewanfleming** [comment]
Fixes done & sent in.
