### ISSUE TITLE
UHMM-Magadan Sokol Airport-MAGA BURYATDAN-RUSSIA

### ISSUE THREAD

**Issue by VladK125rus** [InfiniteFlightAirportEditing/Airports#2707]
I'll did it

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36946465-0a74147c-1f83-11e8-8558-648bb18bf55b.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/43991433-658255cc-9d32-11e8-8b7a-8654a3debc35.png)
