### ISSUE TITLE
LOIH-Hohenems Dornbirn Airport-VORARLBERG-AUSTRIA

### ISSUE THREAD

**Issue by bawariawien** [InfiniteFlightAirportEditing/Airports#2708]

**Comment by ryu12332** [comment]
Do not close airports by yourself. The necessary people will close them when necessary.

**Comment by moritzbabl** [comment]
member inactive, up for grabs

**Comment by johanneskkl** [comment]
will take this as all airports are pending review.

**Comment by johanneskkl** [comment]
sent in

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38136561-d477828e-33e4-11e8-8667-e2f382605022.png)
