### ISSUE TITLE
EDAB-Bautzen Airport-SACHSEN-GERMANY

### ISSUE THREAD

**Issue by bawariawien** [InfiniteFlightAirportEditing/Airports#2709]
I'll do that one

**Comment by moritzbabl** [comment]
member inactive, up for grabs

**Comment by johanneskkl** [comment]
sent in

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38708421-c38317da-3e7b-11e8-96b9-2bb5c27bb5b8.png)
