### ISSUE TITLE
LGKL-Kalamata Airport-PELOPONNISOS-GREECE

### ISSUE THREAD

**Issue by Moonlit21** [InfiniteFlightAirportEditing/Airports#2710]
Would like to work on this airport. No duplicate.

**Comment by Moonlit21** [comment]
Keeping this on hold for now as it's a bit too large for my liking, I will redo a smaller one and get back to this one.

**Comment by Moonlit21** [comment]
Could this be changed to "Suggestion"? I won't be able to get to it

**Comment by Moonlit21** [comment]
Am ready to begin work on this again, could this be assigned to me? Thanks

**Comment by Moonlit21** [comment]
About 80% through this, the huge military ramp makes it difficult. Should be done by the end of November.

**Comment by Moonlit21** [comment]
Sent in for official review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51080445-687bcb80-16a1-11e9-9c38-15c20183d7d3.png)
