### ISSUE TITLE
RJSF-Fukushima Airport-FUKUSHIMA-JAPAN

### ISSUE THREAD

**Issue by ewanfleming** [InfiniteFlightAirportEditing/Airports#2714]
Project Japan, will do.

**Comment by ewanfleming** [comment]
Sent in for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38588336-e475b4f8-3cea-11e8-9e74-fb1cd944f997.png)
