### ISSUE TITLE
RJTJ-Iruma Air Base-SAITAMA-JAPAN

### ISSUE THREAD

**Issue by renorris** [InfiniteFlightAirportEditing/Airports#2716]
I'll take this

**Comment by moritzbabl** [comment]
Member inactive, up for grabs

**Comment by renorris** [comment]
Because I'm not active on the IFC means I can't airport edit?

**Comment by moritzbabl** [comment]
You’ve been unassigned from the issue and removed from Slack and GitHub since you didn’t state your intention to remain in the team on slack, if you are still willing to edit airports I can add you back

**Comment by renorris** [comment]
That would be great thank you sir.

**Comment by moritzbabl** [comment]
I reinvited you to the github repo, please accept the invitation in the mail you got

**Comment by MajorTomMueller** [comment]
@renorris any progress?

**Comment by renorris** [comment]
Sorry for the delay. I will continue working on this airport. Almost done.

**Comment by renorris** [comment]
Sent in for review

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by orangejuicie** [comment]
Recycle

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54495931-eed9a700-48b6-11e9-8afa-8fbca2c970c8.png)

**Comment by orangejuicie** [comment]
Spawn size fix.
