### ISSUE TITLE
MPGA-Garachine Airport-DARIEN-PANAMA

### ISSUE THREAD

**Issue by AndrewRG10** [InfiniteFlightAirportEditing/Airports#2718]
♻️

**Comment by MajorTomMueller** [comment]
Hi @AndrewRG10,
what’s with you 3 months target? ;-))

**Comment by AndrewRG10** [comment]
Remind me to never set deadlines again, I'll have to quit school to full-fill them, I won't abandon this project because I want to see it done. Give me time and I should be back to airport editing after mid year

**Comment by MajorTomMueller** [comment]
... wasn't serious... :-) just want to know. Take your time.

**Comment by MajorTomMueller** [comment]
Hello @AndrewRG10, 
with the 1 year anniversary passed I encouraged myself to ask again:
Any progress?
Regards, Tom

**Comment by RyanEpps** [comment]
Member inactive. Up for grabs

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/62652034-bfdcd400-b930-11e9-8e2c-f630e7380f1f.jpg)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112703706-e7661480-8e65-11eb-8167-5cfeb61ec4e7.png)
