### ISSUE TITLE
YSOL-Solomon Airport-WESTERN AUSTRALIA-AUSTRALIA

### ISSUE THREAD

**Issue by IFATCPanther** [InfiniteFlightAirportEditing/Airports#2719]
Solomon Airport. I'll do it. My first airport!

**Comment by IFATCPanther** [comment]
What do I do if YSOL isn't in the list of airports?

**Comment by moritzbabl** [comment]
Create the airport from scratch then, we will add the airport when it passes review

**Comment by moritzbabl** [comment]
member inactive, up for grabs

**Comment by IFATCPanther** [comment]
I'm still active! I put my GitHub name in slack... why was I removed?

**Comment by dushyants19** [comment]
Mortiz isn't a bot. Sorry, reaccept the invite here: https://github.com/InfiniteFlightAirportEditing/Airports/invitations

**Comment by moritzbabl** [comment]
That actually wasn’t an issue on my side, you didn’t react on the cleanup announcement in GitHub channel, only entries from the start of the cleanup were tracked (so from March 3), your comment in the channel actually dates back to Feb 20

**Comment by MajorTomMueller** [comment]
@IFATCPanther any progress?

**Comment by IFATCPanther** [comment]
@MajorTomMueller uhh no, need some help with it. I’ve been quite busy lately, but I’m going to be free more. 
I’ve asked Andrew (another IFAET) to help me create an apt. File, but he hasn’t replied

**Comment by brunocr98** [comment]
I'll create an apt.dat file in a few minutes to help you out. I'll add basic information of the airport, you'll do the rest. You can ask Kilt McHaggis (kilt46) for charts (PM him in Slack).

**Comment by brunocr98** [comment]
New folder has been added.

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by AussieLuke** [comment]
@RyanEpps I'll take it (:

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53674146-8a311200-3c51-11e9-998f-6747d72932cd.png)
