### ISSUE TITLE
EDDG - Münster Osnabrück International Airport

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#272]
Only 10 gates in whole airport. Definition of terminals is poor. Big project!

**Comment by Swang007** [comment]
@kilt46 Are you working on this one?

**Comment by kilt46** [comment]
No I was reviewing Amsterdam and Socal Bravo/Charlie airports. I posted a link to the view www.kiltmchaggis.com

**Comment by AxelBeder** [comment]
For some reasons the old topic has been closed. The current version isn't the final one.

**Comment by kilt46** [comment]
Image: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=EDDG

**Comment by kilt46** [comment]
This airport has been completed.
![image](https://cloud.githubusercontent.com/assets/14023167/11388117/18aa98aa-92f8-11e5-85ac-05a5c476c2ce.png)

**Comment by kilt46** [comment]
Missing runway hold added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17197334/7ea31560-5431-11e6-9755-df87ee79c5e7.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18602542/a17768c2-7c2f-11e6-835d-8007156f8efc.png)
