### ISSUE TITLE
KHYI-San Marcos Regional Airport-TEXAS-USA

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#2724]
I haven't done a lot of editing over the past few months, but I'm back and I'll start off with a smaller one to ease myself back into it.

I will be doing this one.

Runways are not longer than 10k feet.

**Comment by Aviationluver** [comment]
Sent in for review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/37627240-963a8322-2ba1-11e8-9042-5198038c398d.png)
