### ISSUE TITLE
VYMD-Mandalay Airport-MANDALAY-MYANMAR

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#2728]

**Comment by MajorTomMueller** [comment]
Warning: creepy Google imagery, and no official Apron Chart.
![mandalay](https://user-images.githubusercontent.com/26853210/37331613-a38afcac-26a4-11e8-8eed-998bea54f0fe.jpeg)
official AIP:
https://www.ais.gov.mm/eAIP/2018-03-01-AIRAC/html/index-en-GB.html

**Comment by ItsW1ll** [comment]
OH Jesus that is bad.. is there other imagery sources to use?

**Comment by ItsW1ll** [comment]
It’s all good! Just use bing. Taxiway lines are almost gone. stand markings are clearly visible.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/43026504-926c36d2-8c3b-11e8-93c8-6692cc7a6df4.png)
