### ISSUE TITLE
RJOI-MCAS Iwakuni-EHIME-JAPAN

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#2730]

**Comment by Talentedrobloxen** [comment]
Ill take that

**Comment by brunocr98** [comment]
Make sure to send an email to contact@airportediting.com to join the repository as a collaborator, otherwise we will not be able to assign you.

**Comment by Talentedrobloxen** [comment]
I sent an email

**Comment by brunocr98** [comment]
Make sure to accept the invite sent to you then.

**Comment by MajorTomMueller** [comment]
recycled

**Comment by MajorTomMueller** [comment]
![rjoi-git](https://user-images.githubusercontent.com/26853210/42967598-0d93e97c-8ba1-11e8-922e-270886011ca0.jpg)
