### ISSUE TITLE
EPMO-Warszawa/Modlin Airport-MASOVIAN-POLAND

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#2732]
Warsaw Modlin Airport.

I will re-do this one.

RWY is not longer than 10k feet.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38221740-bb78123e-36a6-11e8-9246-22b9a94efaa6.png)
