### ISSUE TITLE
KPNE-Northeast Philadelphia Airport-PENNSYLVANIA-USA

### ISSUE THREAD

**Issue by gsherbert** [InfiniteFlightAirportEditing/Airports#2735]
Being Redone completely.

**Comment by dushyants19** [comment]
Accept Invitation here: https://github.com/InfiniteFlightAirportEditing/Airports/invitations

**Comment by MajorTomMueller** [comment]
@gsherbert any progress?

**Comment by gsherbert** [comment]
Some, have been focusing on KPNE

**Comment by gsherbert** [comment]
Hey, I have been really busy lately, hope to get this done in the next couple of weeks at a maximum.

**Comment by gsherbert** [comment]
Airport was sent to OR (Couple weeks ago.) Going through peer review again.

**Comment by gsherbert** [comment]
Sent to OR again.
