### ISSUE TITLE
OPIS-Islamabad Airport-PUNJAB-PAKISTAN

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#2737]
Official AIP including Aerodromchart:
http://www.caapakistan.com.pk/Upload/AIS/AIRAC%20AIP%20Supplement%20S-06(18).pdf

**Comment by dushyants19** [comment]
Islamabad has commercial A380 service?

**Comment by brunocr98** [comment]
This airport *isn't* open yet. https://en.wikipedia.org/wiki/New_Islamabad_International_Airport

**Comment by MajorTomMueller** [comment]
![opis-git](https://user-images.githubusercontent.com/26853210/39396746-5e2a162e-4af4-11e8-97a6-7407c3abb0b1.jpg)

**Comment by MajorTomMueller** [comment]
edited for Freq Fix (wrong category for Ground)
Buildings removed

**Comment by MajorTomMueller** [comment]
Adding some shelters and stuff

**Comment by MajorTomMueller** [comment]
![OPIS-git](https://user-images.githubusercontent.com/26853210/115762137-aa247200-a392-11eb-99d3-fbfbcb207bab.png)
