### ISSUE TITLE
ROIG-New Ishigaki Airport-OKINAWA-JAPAN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#2745]
# Airport Name

New-Ishigaki

# Country?

Japan.

# Improvements that need to be made?

Will be redone from scratch.
Move the location of the airport.

# Are you working on this airport?

Yes.

# Airport Priority? (A380, 10000ft+ Runway)

Low.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38585209-a7e54172-3cde-11e8-8560-99040b8fed4c.png)
