### ISSUE TITLE
OAKG-Khojaghar Airport-TAKHAR-AFGHANISTAN

### ISSUE THREAD

**Issue by netjets-1951** [InfiniteFlightAirportEditing/Airports#2747]
# Airport Name

Butler County Regional Airport-Hogan Field

# Country?

United States of America

# Improvements that need to be made?

Needs to be redone.

# Are you working on this airport?

Yes, of course.

# Airport Priority? (A380, 10000ft+ Runway)

Not applicable

Other Notes: Part of Project Ohio

**Comment by MajorTomMueller** [comment]
@netjets-1951 any progress?

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by MajorTomMueller** [comment]
![OAKG](https://user-images.githubusercontent.com/26853210/54475484-1155bc80-47f2-11e9-97c1-be2bbc805eec.jpg)
