### ISSUE TITLE
LIDP-Pavullo Airport-EMILIA-ROMAGNA-ITALY

### ISSUE THREAD

**Issue by johanneskkl** [InfiniteFlightAirportEditing/Airports#2748]
# Name

< Pavullo >

# Country?

< Italy >

# Improvements that need to be made?

< do from scratch >

# Are you working on this airport?

< yes  >

# Airport Priority? (A380, 10000ft+ Runway)

< Nothing that´s GA >

**Comment by johanneskkl** [comment]
sent in

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38136283-121c16f6-33e3-11e8-944a-42c85b8d5fe0.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68075089-1a47ce00-fd82-11e9-96a3-2d4dd4890d7a.jpg)
