### ISSUE TITLE
KCSM-Clinton-Sherman Airport-OKLAHOMA-USA

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#275]

**Comment by kilt46** [comment]
Completed gates in main terminals

**Comment by kilt46** [comment]
TEMP jethubs available on this model

**Comment by Swang007** [comment]
@kilt46 Next time, search for existing issues before creating duplicates. Even if it's not a complete do-over, any improvements should stay in one issue so it's easier to track. Thanks!

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25781674/0d19e2d8-3302-11e7-9438-9753bc25be60.png)
