### ISSUE TITLE
MX69-Valle de Bravo Airfield-MEXICO-MEXICO

### ISSUE THREAD

**Issue by lalomarlin** [InfiniteFlightAirportEditing/Airports#2752]
# Airport Name

Valle de Bravo Airfield

# Country?

Mexico

# Improvements that need to be made?

Done From Scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

None

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
Cannot find much info on this airport
![image](https://user-images.githubusercontent.com/14023167/38281699-8b7a85fa-3771-11e8-802b-62ae6c317610.png)
