### ISSUE TITLE
MMJA-Xalapa National Airport-VERACRUZ-MEXICO

### ISSUE THREAD

**Issue by lalomarlin** [InfiniteFlightAirportEditing/Airports#2753]
# Airport Name

Xalapa

# Country?

Mexico

# Improvements that need to be made?

Redone From Scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

None

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/41074688-dcbbb81e-69ce-11e8-884e-216b96cfe600.png)
