### ISSUE TITLE
RJSA-Aomori Airport-AOMORI-JAPAN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#2754]
# Airport Name

Aomori

# Country?

Japan

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38396895-26085216-3900-11e8-980b-36fda7bb4e03.png)
