### ISSUE TITLE
CFX2-Okotoks Air Ranch Airport-ALBERTA-CANADA

### ISSUE THREAD

**Issue by alexpeterson-if** [InfiniteFlightAirportEditing/Airports#2756]
# Airport Name

Okotoks Air Ranch Airport

# Country?

Canada

# Improvements that need to be made?

Redone from scratch.

# Are you working on this airport?

Yes.

# Airport Priority? (A380, 10000ft+ Runway)

Low.

**Comment by alexpeterson-if** [comment]
Sent for review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38119464-883669ba-3387-11e8-8e79-f6719b4a3849.png)
