### ISSUE TITLE
BGTL-Thule Air Base-PITUFFIK-GREENLAND

### ISSUE THREAD

**Issue by alexpeterson-if** [InfiniteFlightAirportEditing/Airports#2758]
# Airport Name

Thule Air Base

# Country?

Greenland

# Improvements that need to be made?

Redone from scratch.

# Are you working on this airport?

Oui oui

# Airport Priority? (A380, 10000ft+ Runway)

Low

**Comment by alexpeterson-if** [comment]
Sent for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38340635-02305346-383a-11e8-841e-c3dd4c092f41.png)
