### ISSUE TITLE
FAPE-Port Elizabeth International Airport-EASTERN CAPE-SOUTH AFRICA

### ISSUE THREAD

**Issue by ImranMoosa** [InfiniteFlightAirportEditing/Airports#2759]
Port Elizabeth International Airport, I'll work on it

**Comment by moritzbabl** [comment]
How is this going? Redo is quite urgent since the airport doesn’t have any spawns meaning pilots can spawn in runways and on approach in live

**Comment by ImranMoosa** [comment]
ImranMoosa

> On 01 May 2018, at 11:17 AM, moritzbabl <notifications@github.com> wrote:
> 
> How is this going? Redo is quite urgent since the airport doesn’t have any spawns meaning pilots can spawn in runways and on approach in live
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Hey.

I have been quite busy recently with exams for the past 3 weeks.

My tests are finishing this week and I’ll get it done by the 10th of May.

Sorry for all inconvenience caused.

**Comment by moritzbabl** [comment]
No problem, just wanted to make sure it’s actually worked on since it wouldn’t be the first time an airport is started and then forgotten 😉

**Comment by moritzbabl** [comment]
@ImranMoosa are you still working on this?

**Comment by moritzbabl** [comment]
Taking over this due to inactivity

**Comment by moritzbabl** [comment]
Done
