### ISSUE TITLE
CZPC-Pincher Creek Airport-ALBERTA-CANADA

### ISSUE THREAD

**Issue by alexpeterson-if** [InfiniteFlightAirportEditing/Airports#2760]
# Airport Name

Pincher Creek Airport

# Country?

Canada

# Improvements that need to be made?

Redone from scratch.

# Are you working on this airport?

Yessir

# Airport Priority? (A380, 10000ft+ Runway)

Low.

**Comment by alexpeterson-if** [comment]
Sent for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38223513-ef45aaf4-36b0-11e8-915b-c46de00b9919.png)
