### ISSUE TITLE
LIPV-Venezia/Lido Airport-VENETO-ITALY

### ISSUE THREAD

**Issue by johanneskkl** [InfiniteFlightAirportEditing/Airports#2761]
# Airport Name

 venezia san nicolo´

# Country?

italy

# Improvements that need to be made?

do from scratch tough it is in repo

# Are you working on this airport?

yes

# Airport Priority? (A380, 10000ft+ Runway)

None

**Comment by johanneskkl** [comment]
sent in

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38223376-2e02e0fa-36b0-11e8-839c-a94c7d096ff2.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/70913230-5f535700-1ff4-11ea-8e71-08af8e866b25.jpg)
