### ISSUE TITLE
KEZZ-Cameron Memorial Airport-MISSOURI-USA

### ISSUE THREAD

**Issue by Taixipo2003** [InfiniteFlightAirportEditing/Airports#2762]
♻️

**Comment by dushyants19** [comment]
There is already an issue for it #1558, please use this in the future

https://community.infinite-flight.com/t/airport-inaccuracies-what-should-i-do/152800?u=dush19

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38223231-7425131a-36af-11e8-95ba-8bb4a732b432.png)
