### ISSUE TITLE
CYPE-Peace River Airport-ALBERTA-CANADA

### ISSUE THREAD

**Issue by alexpeterson-if** [InfiniteFlightAirportEditing/Airports#2763]
# Airport Name

Peace River Airport

# Country?

Canada

# Improvements that need to be made?

Redone from scratch.

# Are you working on this airport?

Si

# Airport Priority? (A380, 10000ft+ Runway)

Low

**Comment by alexpeterson-if** [comment]
Sent for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38393984-5de6d6fc-38f2-11e8-8964-85acdbf43c7d.png)
