### ISSUE TITLE
CYHY-Hay River/Merlyn Carter Airport-NORTHWEST TERRITORIES-CANADA

### ISSUE THREAD

**Issue by alexpeterson-if** [InfiniteFlightAirportEditing/Airports#2764]
# Airport Name

Hay River/Merlyn Carter Airport

# Country?

Canada

# Improvements that need to be made?

Redone from scratch.

# Are you working on this airport?

Ja

# Airport Priority? (A380, 10000ft+ Runway)

Low.

**Comment by alexpeterson-if** [comment]
Sent for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38395874-b8781880-38fa-11e8-9f2a-57715bc1deb3.png)
