### ISSUE TITLE
LIPM-Modena/Marzaglia Airport-EMILIA-ROMAGNA-ITALY

### ISSUE THREAD

**Issue by johanneskkl** [InfiniteFlightAirportEditing/Airports#2765]
# Airport Name
Modena marzaglia

# Country?
Italy

# Improvements that need to be made?
edit

# Are you working on this airport?
yes

# Airport Priority? (A380, 10000ft+ Runway)

none

**Comment by johanneskkl** [comment]
sent in

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38649020-f3c4aa98-3db9-11e8-9146-a4b3986933d3.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68349400-d2a3a800-00db-11ea-8bd7-952db28abf53.jpg)
