### ISSUE TITLE
LIVD-Dobbiaco Airport-TRENTINO-ALTO ADIGE-ITALY

### ISSUE THREAD

**Issue by johanneskkl** [InfiniteFlightAirportEditing/Airports#2766]
# Airport Name

Dobbiaco

# Country?
Italy

# Improvements that need to be made?
Edit

# Are you working on this airport?
yes

# Airport Priority? (A380, 10000ft+ Runway)
none

**Comment by johanneskkl** [comment]
sent in

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38285167-99698ad6-3784-11e8-8a65-a60d6491d5a3.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/70664046-5fe09c00-1c48-11ea-97ac-03a45afaa36d.jpg)
