### ISSUE TITLE
LIPH-Treviso San Angelo Airport-VENETO-ITALY

### ISSUE THREAD

**Issue by johanneskkl** [InfiniteFlightAirportEditing/Airports#2767]
# Airport Name

Treviso Sant´Angelo

# Country?

Italy

# Improvements that need to be made?

edit

# Are you working on this airport?
yes

# Airport Priority? (A380, 10000ft+ Runway)
none

**Comment by johanneskkl** [comment]
Sent in

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38649209-f4f824ac-3dba-11e8-9a21-127c27315d42.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/70916099-df2ff000-1ff9-11ea-97cd-8bd8f0bc9065.jpg)
