### ISSUE TITLE
OANZ-Nimroz Airport-NIMROZ-AFGHANISTAN

### ISSUE THREAD

**Issue by MrAlaska** [InfiniteFlightAirportEditing/Airports#2769]
# Airport Name

Yakubu Gowon Airport

# Country?

Nigeria

# Improvements that need to be made?

Add Gates

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

9837ft x 147ft runway

**Comment by MrAlaska** [comment]
This is my second attempt to redo an airport. I have someone in order to help me if I get stuck. Hopefully I complete this one with ease, and redo many more airports!

**Comment by brunocr98** [comment]
Please send an email to the IFAET to be re-added.

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by MajorTomMueller** [comment]
![OANZ](https://user-images.githubusercontent.com/26853210/54364116-8ac3a280-466c-11e9-90b0-34b5ef5cab52.jpg)
