### ISSUE TITLE
RJX7-Satsuma Iwojima Airport-KAGOSHIMA-JAPAN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#2770]
# Airport Name

< Satsuma-Iojima>

# Country?

< Japan>

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes>

# Airport Priority? (A380, 10000ft+ Runway)

< No >

**Comment by orangejuicie** [comment]
This tiny airport had sent for review without "peer- review".
I hope you will understand.
Thank you.

**Comment by dushyants19** [comment]
peer-review is not mandatory for every airport, once you get the hang of editing. You don't need peer-review anymore :)

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38586877-2d77b332-3ce5-11e8-88c0-6063aa76b6ca.png)
