### ISSUE TITLE
OACC-Chakhcharan Airport-GHOR-AFGHANISTAN

### ISSUE THREAD

**Issue by rafacortes** [InfiniteFlightAirportEditing/Airports#2771]
# Airport Name

< CASTELSARRASIN Moissac >

# Country?

< France >

# Improvements that need to be made?

< Enter text here >

# Are you working on this airport?

< Yes>

# Airport Priority? (A380, 10000ft+ Runway)

< Enter text here >

**Comment by rafacortes** [comment]
I'm trying to create this airport for xplane11,Estoy intentando de crear este aeropuerto para xplane11

**Comment by brunocr98** [comment]
Hello @rafacortes 

If you're doing this airport, this will be for Infinite Flight, not X-Plane 11. Please join us at contact@airportediting.com. Thank you! Glad to meet another hispanic :)

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by benjwri** [comment]
Hi, I'll take this

**Comment by MajorTomMueller** [comment]
![OACC](https://user-images.githubusercontent.com/26853210/54362917-21db2b00-466a-11e9-95bf-cf83d092fdbf.jpg)
