### ISSUE TITLE
RJCM-Memanbetsu Airport-HOKKAIDO-JAPAN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#2772]
# Airport Name

< Memanbetsu >

# Country?

< Japan >

# Improvements that need to be made?

< redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38532292-bd35b05c-3c39-11e8-9416-8d0af98bf69a.png)
