### ISSUE TITLE
EGEN-North Ronaldsay Airport-SCOTLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by johnkellyoxford** [InfiniteFlightAirportEditing/Airports#2775]
# Airport Name

North Ronaldsay Airport

# Country?

United Kingdom

# Improvements that need to be made?

Complete redo

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

None

**Comment by moritzbabl** [comment]
added, @johnkellyoxford please accept a new invitation to the repo in your mails

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38592875-27013022-3d04-11e8-9e73-d0545aebacf1.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38593276-330e2260-3d06-11e8-8a22-75d12e55b29c.png)
