### ISSUE TITLE
SBTE-Teresina/Senador P. Portela Airport-PIAUI-BRAZIL

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#2776]
Redone without opening an issue, added

**Comment by FellipeEdu** [comment]
I have to make a small correction at the airport, I ask you to reopen the issue, please.

**Comment by brunocr98** [comment]
No need, just send the correction to the email as usual.

**Comment by kilt46** [comment]
Charts show the following. Please check gate layout
![image](https://user-images.githubusercontent.com/14023167/38652146-3b2d4380-3dca-11e8-9bda-405faa8bb53b.png)

**Comment by moritzbabl** [comment]
re-added, looks like current layout is quite accurate, corresponds with google images from January 2018

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38904942-f002f9ec-4272-11e8-94a4-e8de1e86c3d8.png)
