### ISSUE TITLE
PAED-Elmendorf Air Force Base-ALASKA-USA

### ISSUE THREAD

**Issue by Asneed8706** [InfiniteFlightAirportEditing/Airports#2777]
# Elmendorf Air Force Base 

<Elmendorf Air Force Base>

# USA

< United States>

# Airport issues

< being redone >

# Are you working 

< yes >

# Priority A380, 10000ft+ runway)

< 1000ft runway >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54079790-d2cb7980-42a8-11e9-84c7-9ba0cae743e8.png)
