### ISSUE TITLE
EBZR

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#278]
Mimimal airport see image: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=EBZR

Class Charlie

**Comment by kilt46** [comment]
Final Image: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=EBZR

**Comment by kilt46** [comment]
Lines and gates added
![image](https://cloud.githubusercontent.com/assets/14023167/11384110/9efa29a0-92d2-11e5-916d-1ce2a60a242c.png)

**Comment by JcFl4** [comment]
There is no need for so many hangars. I try to make my airports as realistic as possible. Why do you keep changing them?

**Comment by JcFl4** [comment]
There is no need for so many hangars, but thanks.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18033412/34bb0874-6ce9-11e6-930f-49412594a034.png)
