### ISSUE TITLE
LGIO-King Pyrros Airport-IPEIROS-GREECE

### ISSUE THREAD

**Issue by Moonlit21** [InfiniteFlightAirportEditing/Airports#2781]
# Airport Name?

LGIO - Ioannina King Pyrrhus Airport 

# Country?

Greece 

# Improvements that need to be made?

General rework, taxilines & ways added, spawns, etc.

# Are you working on this airport?

Affirmative

# Airport Priority? (A380, 10000ft+ Runway)

No priority

**Comment by Moonlit21** [comment]
Could this be moved to Suggestions for now? All my computer files got deleted and I’ll have to redownload everything. I might do a different airport when I restart in a few days’ time.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46316886-00dcbd00-c597-11e8-87a4-3e17fd26b5e8.png)
