### ISSUE TITLE
EGEY-Colonsay Airport-SCOTLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by johnkellyoxford** [InfiniteFlightAirportEditing/Airports#2782]
# Airport Name

Colonsay airport

# Country?

United Kingdom

# Improvements that need to be made?

Complete redo

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

None

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46839446-99d3bb00-cd83-11e8-8a01-f96666f71a8f.png)
