### ISSUE TITLE
EIMN-Inishmaan Airport-GALWAY-IRELAND

### ISSUE THREAD

**Issue by johnkellyoxford** [InfiniteFlightAirportEditing/Airports#2785]
# Airport Name

Inishmaan airport

# Country?

Republic of Ireland

# Improvements that need to be made?

Complete redo

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

None

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by orangejuicie** [comment]
I'll take this.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55682813-ee548f00-58fd-11e9-9b9f-8664bf7d5a3a.png)
