### ISSUE TITLE
EGDO-Predannack Airport-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by johnkellyoxford** [InfiniteFlightAirportEditing/Airports#2786]
# Airport Name

Predanneck airport

# Country?

Her Majesty's United Kingdom of Great Britain and Northern Ireland

# Improvements that need to be made?

Complete redo

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

None

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46839870-c5f03b80-cd85-11e8-8744-16845bd3ed91.png)
