### ISSUE TITLE
RJAM-Minami Torishima Airport-SHIZUOKA-JAPAN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#2788]
# Airport Name

< Minami Torishima >

# Country?

< Japan >

# Improvements that need to be made?

< redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by orangejuicie** [comment]
sent for review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/38771865-78338f32-3ff0-11e8-9f95-cfec367793a9.png)
