### ISSUE TITLE
SBJV-Lauro Carneiro De Loyola Airport-SANTA CATARINA-BRAZIL

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Airports#2789]
# Airport Name

< Joinville, Lauro Carneiro de Loyola Airport >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/41949028-3387f0ca-7985-11e8-9195-8cbb44f011ab.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/61190820-d2892380-a678-11e9-8be1-1fd4155edb4c.jpg)
