### ISSUE TITLE
KLAL-Lakeland Linder Regional Airport-FLORIDA-USA

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#279]

**Comment by AxelBeder** [comment]
Your picture shows EDDG not EDDK which has already been redone.

**Comment by kilt46** [comment]
No terminal gates

**Comment by kilt46** [comment]
Image: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=KLAL

**Comment by DS2001** [comment]
Maybe I want ti do this one

**Comment by kilt46** [comment]
HAS HOLD SHORT AREA

**Comment by Swang007** [comment]
Hold-short spawn points removed.

**Comment by Swang007** [comment]
Wait, @kilt46 did you add terminal gates and whatever else you wanted to add?

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18572145/280dbc18-7b7e-11e6-8283-06cd89c0e6fe.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18572151/34cee6f2-7b7e-11e6-9242-3068a2a01a07.png)

**Comment by brennanhackard** [comment]
Airport needs a rework. Open to anyone who wants it.

**Comment by joshsmith07** [comment]
I'll do this one.
