### ISSUE TITLE
RJOW-Iwami Airport-SHIMANE-JAPAN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#2791]
# Airport Name

< Iwami >

# Country?

< Japan >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/39495318-72b9589e-4d5f-11e8-9ef3-33e45d9dd78e.png)
