### ISSUE TITLE
CYET-Edson Airport-ALBERTA-CANADA

### ISSUE THREAD

**Issue by alexpeterson-if** [InfiniteFlightAirportEditing/Airports#2793]
# Airport Name

Edson Airport

# Country?

Canada

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yup

# Airport Priority? (A380, 10000ft+ Runway)

Low

**Comment by alexpeterson-if** [comment]
Sent for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/39088917-b20bb14a-4580-11e8-8da7-9b921c12134e.png)
