### ISSUE TITLE
OR87-Blue Skies Farm Airport-OREGON-USA

### ISSUE THREAD

**Issue by KarlLuebs** [InfiniteFlightAirportEditing/Airports#2795]
♻️

**Comment by dushyants19** [comment]
too hard to full up?...

**Comment by KarlLuebs** [comment]
Was just doing that. Sorry Dushyants

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56080502-82739a00-5dc7-11e9-9963-7aa731f37c12.png)
