### ISSUE TITLE
CYEV-Inuvik (Mike Zubko) Airport-NORTHWEST TERRITORIES-CANADA

### ISSUE THREAD

**Issue by alexpeterson-if** [InfiniteFlightAirportEditing/Airports#2797]
# Airport Name

Inuvik (Mike Zubko) Airport

# Country?

Canada

# Improvements that need to be made?

Redone from scratch.

# Are you working on this airport?

Si, señor.

# Airport Priority? (A380, 10000ft+ Runway)

Low.

**Comment by alexpeterson-if** [comment]
Sent for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/39662908-08b3263c-502f-11e8-9287-b47107cbae4d.png)
