### ISSUE TITLE
TFFR-Le Raizet Airport-POINTE-A-PITRE-GUADELOUPE

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#28]

**Comment by Swang007** [comment]
Will add ATIS frequency

**Comment by Swang007** [comment]
TFFR already has an ATIS frequency.

**Comment by dushyants19** [comment]
Duplicate Spawn points
https://slack-files.com/T0B0SBFFY-F0HHELEK0-d17c4606e3

**Comment by kilt46** [comment]
Pending Jonathan to add to GIT

**Comment by dushyants19** [comment]
Approved and into the repo - (Jonathan Perkins)

**Comment by dushyants19** [comment]
Needs a redo

**Comment by IceBlue02** [comment]
Will do

**Comment by kilt46** [comment]
Why does this need a redo?
![image](https://cloud.githubusercontent.com/assets/14023167/14301615/d9f9e2ee-fb5e-11e5-9baf-2ff5c6a74acc.png)

**Comment by IceBlue02** [comment]
Going with Kilt's version- in 4.0

**Comment by dushyants19** [comment]
Adding turnaround points.

**Comment by NickArt1342** [comment]
is it done @dushyants19 ?

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20644566/4771cfc8-b3fe-11e6-90ec-96ff87e868b5.png)

**Comment by RyanEpps** [comment]
<img width="882" alt="Screen Shot 2019-05-13 at 5 15 19 PM" src="https://user-images.githubusercontent.com/20650961/57654757-f493f600-75a2-11e9-93ec-dcc4b6f724a6.png">
