### ISSUE TITLE
PHJR

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#280]
Only 3 gates
Image: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=PHJR

**Comment by DS2001** [comment]
I maybe I want to do this one

**Comment by samuelandersson** [comment]
Redoing.

**Comment by HenrikBerg02** [comment]
@samuelandersson, are you still working on this one? If not, change it back to "Suggestion" so another editor can redo it.

**Comment by dushyants19** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20864006/c6849150-b9a4-11e6-89f5-f84e40b72e86.png)
