### ISSUE TITLE
OASG-Eshkashem Airport-AFGHANISTAN

### ISSUE THREAD

**Issue by Skunkape29** [InfiniteFlightAirportEditing/Airports#2803]
# Airport Name

< KHEG>

# Country?

< United States >

# Improvements that need to be made?

< Entire Airport needs to be done >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by MajorTomMueller** [comment]
on request of @Skunkape29 in Slack assignment changed to @johanneskkl

**Comment by johanneskkl** [comment]
I will have to take an exam in latin in a month and I need time to study. 
Expect delays (mostly) for this airport (A**late**alia style)

**Comment by johanneskkl** [comment]
Untouched since August, feel free to assign

**Comment by MajorTomMueller** [comment]
![OASG](https://user-images.githubusercontent.com/26853210/54433687-c4f47900-472c-11e9-8360-e3b966de1920.jpg)
