### ISSUE TITLE
KSLI

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#281]
Only a few gates
See Image: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=KSLI

**Comment by samuelandersson** [comment]
Im on to this one. Completely redoing it.

**Comment by samuelandersson** [comment]
Done. Added everything needed and more :100:

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21082226/da4d6c54-bf9c-11e6-9f46-4c5dce12bd8b.png)
