### ISSUE TITLE
WAVC-Ilu Airport-PAPUA-INDONESIA

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#2810]
Ilu airport being redone

**Comment by kilt46** [comment]
This doesn't appear anything like the satellite!
![image](https://user-images.githubusercontent.com/14023167/39452806-37daeb96-4c99-11e8-8eeb-00464e173d96.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/39452898-8f4252c0-4c99-11e8-9b6a-ece39c873412.png)
