### ISSUE TITLE
WASG-Anggi-PAPUA-INDONESIA

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#2816]
Anggi airport being redone

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/39412850-f38d9558-4be7-11e8-913d-c42894bcba44.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/39413691-cd3bb3ce-4bf3-11e8-8324-332338cd3644.png)
