### ISSUE TITLE
RJNF-Fukui Airport-FUKUI-JAPAN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#2818]
# Airport Name

< Fukui >

# Country?

< Japan >

# Improvements that need to be made?

< redone from scratch >

# Are you working on this airport?

< yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/39495948-29aeb966-4d62-11e8-97f4-d549354b1be8.png)
