### ISSUE TITLE
2NC0-Mountain Air Airport-NORTH CAROLINA-USA

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#2819]
# Airport Name

< Mountain Air Airport >

# Country?

< United States >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by moritzbabl** [comment]
added

**Comment by orangejuicie** [comment]
Boundary Fix.
