### ISSUE TITLE
LIMC-Milan Malpensa Airport-LOMBARDY-ITALY

### ISSUE THREAD

**Issue by AxelBeder** [InfiniteFlightAirportEditing/Airports#282]
LIMC

**Comment by kilt46** [comment]
Image: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=LFPG

**Comment by kilt46** [comment]
Airport rebuilt

**Comment by samuelandersson** [comment]
Fixing this one after I am done with LIML.

**Comment by samuelandersson** [comment]
Starting work on this one now.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19627696/92458640-9912-11e6-81a9-f5c290aed826.png)
![image](https://cloud.githubusercontent.com/assets/14023167/19627699/9e250030-9912-11e6-9d71-bf153fcec497.png)
