### ISSUE TITLE
OADZ-Darwaz Airport-AFGHANISTAN

### ISSUE THREAD

**Issue by netjets-1951** [InfiniteFlightAirportEditing/Airports#2820]
# Airport Name

Springfield-Beckley Municpal Airport

# Country?

United States of America

# Improvements that need to be made?

Needs redone, also IF shows it having tower and ground frequencies, but it has never had them in real life...

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Project Ohio

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by MajorTomMueller** [comment]
![OADZ](https://user-images.githubusercontent.com/26853210/54447129-ecf1d580-4748-11e9-90a4-db81a47e420d.jpg)
