### ISSUE TITLE
LIRS-Grosseto Air Base-TOSCANA-ITALY

### ISSUE THREAD

**Issue by johanneskkl** [InfiniteFlightAirportEditing/Airports#2828]
# Airport Name

Grosseto 

# Country?

Italy

# Improvements that need to be made?

working

# Are you working on this airport?

yes

# Airport Priority? (A380, 10000ft+ Runway)

no

**Comment by MajorTomMueller** [comment]
Aerodrom Chart: https://grossetoairport.files.wordpress.com/2015/01/adprs2-1.pdf

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/39901385-c3818294-548d-11e8-9cef-61330f6bd672.png)

**Comment by MajorTomMueller** [comment]
Minor adjustments

**Comment by MajorTomMueller** [comment]
https://github.com/InfiniteFlightAirportEditing/Airports/commit/825e95b3b97380a67533df1569cce035ff7e8823

![LIRS-git](https://user-images.githubusercontent.com/26853210/71307203-db79e000-23e2-11ea-8ead-7b46a6cef438.png)
