### ISSUE TITLE
KMIA-Miami International Airport-FLORIDA-USA

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#283]
Very few gates in Main Terminal. Rewrite Opportunity

**Comment by kilt46** [comment]
Image: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=KMIA

**Comment by kilt46** [comment]
Main Terminal redone

**Comment by dushyants19** [comment]
Fixed an issue (added an exit) as per https://community.infinite-flight.com/t/disguised-taxiway-at-kmia/21036

**Comment by kilt46** [comment]
Working on replacing outer perimeter

**Comment by kilt46** [comment]
Now done with 2 piece apron, MAIN and WEST

**Comment by Swang007** [comment]
Miami International Airport.
Gates D39 and D41 are repeated 3 times for each.

https://community.infinite-flight.com/t/list-of-airports-changed-since-last-release-feb-2016/24899/4

**Comment by dushyants19** [comment]
Will fix :D

**Comment by dushyants19** [comment]
Done

**Comment by Swang007** [comment]
https://community.infinite-flight.com/t/airport-parking/41621

**Comment by kilt46** [comment]
This has been redone

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17277112/d00625e2-5700-11e6-8f23-3e77af01e33b.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17277113/db809e5c-5700-11e6-848e-40a9ffa1a591.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17831264/b5bc0482-66a9-11e6-88f3-1f9023b638b7.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17831273/d9401c22-66a9-11e6-8cae-72a9aa92b8b1.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17831276/e53c71ec-66a9-11e6-8bed-072bfe91ce0e.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17831278/fb8cf0e8-66a9-11e6-9475-c8c14e5c3124.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17831303/70123662-66aa-11e6-9c69-13e8827dfeea.png)

**Comment by brunocr98** [comment]
Looks like there are some missing gates. I'll add them when I have time and with some minor improvements.

![screenshot 314 _li](https://cloud.githubusercontent.com/assets/22130457/25956489/7c4e982e-3631-11e7-826c-4169cc7d00ed.jpg)

**Comment by brunocr98** [comment]
New gates were added.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/61162164-b604b400-a4dd-11e9-8932-e6a1af3e27d3.jpg)
