### ISSUE TITLE
LIRE-Pratica Di Mare Airport-LAZIO-ITALY

### ISSUE THREAD

**Issue by johanneskkl** [InfiniteFlightAirportEditing/Airports#2830]
# Airport Name

Pratica di mare

# Country?

Italy-lazio

# Improvements that need to be made?

Do it

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

None

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/40753625-a6e44560-643a-11e8-91ad-effe36b971ac.png)
