### ISSUE TITLE
RJDK-Kamigoto Airport-NAOASAKI-JAPAN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#2831]
# Airport Name

< Kami-Goto >

# Country?

< Japan >

# Improvements that need to be made?

< redo from scratch >

# Are you working on this airport?

< yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/39901074-d5f1edf8-548b-11e8-96e8-9c9f88314bd7.png)
