### ISSUE TITLE
KSAV-Savannah/Hilton Head International Airport-GEORGIA-USA

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#2836]
# Airport Name

Savannah/Hilton Head Int'l Airport

# Country?

The United States of Americas

#Improvements to the airport

Complete re-work from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Runway not longer than 10k feet

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/39967483-6bb4f71c-5681-11e8-9a12-00eeb8ac45fc.png)
