### ISSUE TITLE
LFBE-Bergerac Dordogne Perigord Airport-AQUITAINE-FRANCE

### ISSUE THREAD

**Issue by ItsW1ll** [InfiniteFlightAirportEditing/Airports#2837]
# Airport Name

Bergerac Dordogne Perigord Airport

# Country?

France

# Improvements that need to be made?

Full redo from old x-plane file. 

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

None

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/40145406-4423adee-5927-11e8-8a19-71bbd216e45d.png)
