### ISSUE TITLE
VIDN-Dehradun Airport-UTTARANCHAL-INDIA

### ISSUE THREAD

**Issue by iceman183** [InfiniteFlightAirportEditing/Airports#2838]
# Airport Name

Jolly Grant Airport 

# Country?

India

# Improvements that need to be made?

Complete redone (current one has inaccurate runway length, no parking size, etc)

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

No

**Comment by brunocr98** [comment]
Thank you for your cooperation. But please make sure to send an email to contact@airportediting.com to be officially in our team. Thank you!

**Comment by akshay2777** [comment]
I will do this

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51088395-a3731300-1724-11e9-89e0-2d7f9671b1d9.png)

**Comment by MajorTomMueller** [comment]
![VIDN new apn](https://user-images.githubusercontent.com/26853210/103551658-8f40f700-4ea2-11eb-9203-50c9a326b8c6.png)

Update, **no full rework**

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103715302-e4a20480-4f85-11eb-9444-b95448f9ed2f.png)
