### ISSUE TITLE
RJKN-Tokunoshima Airport-KAGOSHIMA-JAPAN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#2840]
# Airport Name

< Tokunoshima Airport >

# Country?

< Japan >

# Improvements that need to be made?

< redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/39969213-6beec77c-569e-11e8-93e4-e67bf92bb3f4.png)
