### ISSUE TITLE
LBWN-Varna Airport-VARNA-BULGARIA

### ISSUE THREAD

**Issue by skotshi** [InfiniteFlightAirportEditing/Airports#2841]
# Airport Name

Varna

# Country?

Bulgaria

# Improvements that need to be made?

From scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

No

**Comment by skotshi** [comment]
![screenshot 143](https://user-images.githubusercontent.com/35876784/39965729-ee3f7280-569e-11e8-83b5-3a87eee36236.png)

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/39970324-0c2c227e-56af-11e8-97ae-5632a56264f4.png)
