### ISSUE TITLE
MPSB-Sambu Airport-DARIEN-PANAMA

### ISSUE THREAD

**Issue by SportsAviator8** [InfiniteFlightAirportEditing/Airports#2842]
♻️

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by liamkirky** [comment]
Could I take this airport please?

**Comment by liamkirky** [comment]
Actually, I’ll be alright.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/62653047-1f3be380-b933-11e9-827e-c6f7b460c076.jpg)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112703366-b20cf700-8e64-11eb-83a1-ce1c0dd16a1b.png)
