### ISSUE TITLE
PGSN-Francisco C Ada/Saipan International Airport-NORTHERN MARIANA ISLANDS-USA

### ISSUE THREAD

**Issue by VladK125rus** [InfiniteFlightAirportEditing/Airports#2843]
# Airport Name

PGSN Saipan Intl' Airport

# Country?

USA

# Improvements that need to be made?

Full redone from scratch

# Are you working on this airport?

Of course, started

# Airport Priority? (A380, 10000ft+ Runway)

IDK, RW is 8700ft long

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/40575644-324fb200-60ae-11e8-81b8-d2ffdee23dbf.png)
