### ISSUE TITLE
KFLG-Flagstaff Pulliam Airport-ARIZONA-USA

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#2847]
# Airport Name

Flagstaff Pulliam Airport

# Country?

United States of America

# Improvements that need to be made?

Complete re-work from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

RWY not longer than 10k feet.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/40210844-f5ec870e-5a0c-11e8-8f7c-b6d54cebcd9b.png)
