### ISSUE TITLE
KAFN-Jaffrey Airport–Silver Ranch-NEW HAMPSHIRE-USA

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Airports#2849]
Part of [Project New England](https://community.infinite-flight.com/t/project-new-england/43169).

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/40152478-049b769c-594b-11e8-993a-f0ca7a82848d.png)
