### ISSUE TITLE
LHSZ

### ISSUE THREAD

**Issue by Swang007** [InfiniteFlightAirportEditing/Airports#285]

**Comment by kilt46** [comment]
Image: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=PHKO

**Comment by Swang007** [comment]
There was never an issue. This airport represents taxiways just like in real life.

**Comment by IFAEpat** [comment]
Szentes Airport

**Comment by IFAEpat** [comment]
done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17209518/f74f9154-5482-11e6-9fd5-ab3986af2449.png)

**Comment by IFAEpat** [comment]
Gated

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17719596/606809ce-63e1-11e6-9399-a8e01d97148d.png)
