### ISSUE TITLE
RJDB-Iki Airport-NAGASAKI-JAPAN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#2851]
# Airport Name

< Iki Airport >

# Country?

< Japan >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by orangejuicie** [comment]
Redone

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/40207904-726dc9e8-59fc-11e8-88f2-ef1576d5c32a.png)
