### ISSUE TITLE
KLCI-Laconia Municipal Airport-NEW HAMPSHIRE-USA

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Airports#2852]
Part of [Project New England](https://community.infinite-flight.com/t/project-new-england/43169/).

**Comment by CptNathanHope** [comment]
State of New Hampshire (NH) is complete. 3 more to go! 🎉

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/40268843-e24c6122-5b3a-11e8-9ad2-de54cacd8cbc.png)
