### ISSUE TITLE
KFAT-Fresno Yosemite International Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#2853]
# Airport Name

Fresno Yosemite Int'l Airport

# Country?

United States of America

# Improvements that need to be made?

Re-work from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

RWY's not longer than 10k feet

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/40614453-7fc4f158-6248-11e8-8d5b-3aa00e356c3e.png)

**Comment by Czechoslovaki** [comment]
Airport needs some updates.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/99735384-259f9180-2a8a-11eb-89e9-65c103838772.png)
