### ISSUE TITLE
OAEM-Eshkashem-BADAKHSHAN-AFGHANISTAN

### ISSUE THREAD

**Issue by Vulcanodong** [InfiniteFlightAirportEditing/Airports#2854]
# Airport Name

Linyi Shubuling Airport
# Country?

China

# Improvements that need to be made?

From scratch
# Are you working on this airport?

yes
# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by brunocr98** [comment]
Hello @Vulcanodong 

Thank you for your cooperation, but please send an email to contact@airportediting.com to be an official member of the team. Thanks!

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by MajorTomMueller** [comment]
![OAEM](https://user-images.githubusercontent.com/26853210/54434741-3cc3a300-472f-11e9-8248-d16cab6f5da3.jpg)
