### ISSUE TITLE
RJNO-Oki Airport-SHIMANE-JAPAN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#2857]
# Airport Name

< Oki Airport >

# Country?

< Japan >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/40391499-208e1016-5dde-11e8-8eb2-eec68fb58d52.png)
