### ISSUE TITLE
PGUA-Andersen AFB Airport-GUAM-USA

### ISSUE THREAD

**Issue by VladK125rus** [InfiniteFlightAirportEditing/Airports#2858]
# Airport Name

Andersen Air Force Base

# Country?

USA (Mariana Islands)

# Improvements that need to be made?

Full redone from scratch

# Are you working on this airport?

Will be

# Airport Priority? (A380, 10000ft+ Runway)

10000ft+ Runways

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/40874934-c2eaa340-663c-11e8-82b7-466957a7ef74.png)

**Comment by kilt46** [comment]
Rename spawns as per Navigraph aprons
