### ISSUE TITLE
RJEB-Monbetsu Airport-HOKKAIDO-JAPAN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#2859]
# Airport Name

< Monbetsu Airport >

# Country?

< Japan >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/40394342-b0af1398-5de8-11e8-80c2-2f99011c6dd8.png)
