### ISSUE TITLE
LFOJ-Bricy Air Base-CENTRE-FRANCE

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#286]
Basic airport with one ramp
Image: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=LFOJ

**Comment by BVRAU** [comment]
I am going to work on this

**Comment by Ksisky** [comment]
Working on it now.

**Comment by Ksisky** [comment]
Finished

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20992677/4d0c3792-bcab-11e6-9abe-d15b4bb10c4a.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53292543-59e8ff80-3789-11e9-952d-2910316b9ee3.png)

**Comment by kilt46** [comment]
Duplicate spawns removed

**Comment by MajorTomMueller** [comment]
rework needed

**Comment by MajorTomMueller** [comment]
![LFOJ-git](https://user-images.githubusercontent.com/26853210/83255291-a9de1f80-a19f-11ea-8974-ee5c4337daa7.png)

**Comment by MajorTomMueller** [comment]
![LFOJ-git](https://user-images.githubusercontent.com/26853210/83256394-de52db00-a1a1-11ea-89da-4bf48570a65f.png)
