### ISSUE TITLE
OAJL-Jalalabat-NANGAHAR-AFGHANISTAN

### ISSUE THREAD

**Issue by itsmeraven** [InfiniteFlightAirportEditing/Airports#2860]
# Airport Name

< Dumaguete Airport >

# Country?

< Philippines >

# Improvements that need to be made?

< Runway, Taxiways, Spawns and more >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by MajorTomMueller** [comment]
![OAJL](https://user-images.githubusercontent.com/26853210/54290708-bc286980-45ab-11e9-8eaf-ad01cd972247.jpg)
