### ISSUE TITLE
VTSS-Hat Yai International Airport-SONGKHLA-THAILAND

### ISSUE THREAD

**Issue by benlenahan** [InfiniteFlightAirportEditing/Airports#2861]
♻️

**Comment by IFC-PlaneCrazy** [comment]
Redone and sent to OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/75639584-49772a80-5c10-11ea-90fe-47d8d3f18faf.jpg)
