### ISSUE TITLE
OADS-Sardeh Band-GHAZNI-AFGHANISTAN

### ISSUE THREAD

**Issue by itsmeraven** [InfiniteFlightAirportEditing/Airports#2864]
# Airport Name

< Fernando Airport >

# Country?

< Philippines >

# Improvements that need to be made?

< Add Taxiways, Spawns, buildings and more! >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by MajorTomMueller** [comment]
![OADS](https://user-images.githubusercontent.com/26853210/54476337-52eb6500-47fc-11e9-951c-e05cdcd16017.jpg)
