### ISSUE TITLE
RJKA-Amami Airport-KAGOSHIMA-JAPAN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#2865]
# Airport Name

< Amami Airport >

# Country?

< Japan >

# Improvements that need to be made?

< redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/40518951-ad989882-5f82-11e8-84ea-894110dd3938.png)
