### ISSUE TITLE
CYZU-Whitecourt Airport-ALBERTA-CANADA

### ISSUE THREAD

**Issue by alexpeterson-if** [InfiniteFlightAirportEditing/Airports#2866]
# Airport Name

Whitecourt Airport

# Country?

Canada

# Improvements that need to be made?

Redone from scratch.

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/41800756-90db9804-763c-11e8-8d26-8fcac5139732.png)
