### ISSUE TITLE
URRP-Platov Airport-ROSTOV-RUSSIA

### ISSUE THREAD

**Issue by VladK125rus** [InfiniteFlightAirportEditing/Airports#2867]
# Airport Name

Rostov-on-Don Platov

# Country?

Russia

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Starting today-tomorrow

# Airport Priority? (A380, 10000ft+ Runway)

10000ft+ RW

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
Please use tghe following parking numbering (as per Navigraph/Jeppesen)
![image](https://user-images.githubusercontent.com/14023167/40878060-f8beabc4-6650-11e8-93b2-25523459b4e2.png)

**Comment by VladK125rus** [comment]
Sent

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/41881393-ea3a372a-78a8-11e8-9c05-eec277c5bffc.png)

**Comment by kilt46** [comment]
Altitude changed to 282 ft
