### ISSUE TITLE
RJOR-Tottori Airport-TOTTORI-JAPAN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#2868]
# Airport Name

< Tottori Airport >

# Country?

< Japan >

# Improvements that need to be made?

< redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/40589136-d4416a22-61ad-11e8-85f3-e67bddfb2de0.png)
