### ISSUE TITLE
KTYS-McGhee Tyson Airport-TENNESSEE-USA

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#2869]
# Airport Name

Knoxville Airport

# Country?

United States of America 

# Improvements that need to be made?

Complete re-work from scratch

# Are you working on this airport?

yes

# Airport Priority? (A380, 10000ft+ Runway)

RWY not longer than 10k feet

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/40873755-087c8f1a-662c-11e8-8286-9bee996a2753.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/40874143-37fcac8e-6631-11e8-8694-8ccd7cf7eb84.png)

Runway 5L/23R too long - should be 6000 ft!

**Comment by moritzbabl** [comment]
readded

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/41075097-ae41251c-69d0-11e8-9b53-fc57c5f0dd57.png)
