### ISSUE TITLE
PGRO-Benjamin Taisacan Manglona International Airport-NORTHERN MARIANA ISLANDS-USA

### ISSUE THREAD

**Issue by VladK125rus** [InfiniteFlightAirportEditing/Airports#2870]
# Airport Name

Benjamin Taisacan Mangola Intl

# Country?

USA Mariana islands

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

No

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/40874470-4d2a9edc-6635-11e8-8921-809b72936344.png)
