### ISSUE TITLE
RJCO-Sapporo/Okadama Airfield-HOKKAIDO-JAPAN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#2871]
# Airport Name

< Sapporo/Okadama Airfield >

# Country?

< Japan >

# Improvements that need to be made?

< redo from scratch >

# Are you working on this airport?

< YES >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/40689129-7b8e1cd0-6366-11e8-985c-0c6c3696de3d.png)
