### ISSUE TITLE
SBPL-Petrolina Airport-PERNAMBUCO-BRAZIL

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Airports#2872]
# Airport Name

< Petrolina, Senador Nilo Coelho Airport >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< 10000ft+ Runway >

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42067378-8cc80008-7b0b-11e8-9cfd-3ca657d18a3c.png)
