### ISSUE TITLE
RORK-Kitadaito Airport-OKINAWA-JAPAN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#2873]
# Airport Name

< KItadaito Airport >

# Country?

< Japan >

# Improvements that need to be made?

< redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/40755378-ded7cf9c-6443-11e8-8a5e-e396a036c24f.png)
