### ISSUE TITLE
ROMD-Minamidaito Airport-OKINAWA-JAPAN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#2874]
# Airport Name

< Minamidaito Airport >

# Country?

< Japan >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/40691906-31524dea-6374-11e8-8d67-cdf1f081e7fc.png)
