### ISSUE TITLE
RJFY-Kanoya Air Base-KAGOSHIMA-JAPAN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#2877]
# Airport Name

< Kanoya Air Base >

# Country?

< Japan >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/40880672-c1645b18-667a-11e8-9f1b-498013529fce.png)
