### ISSUE TITLE
OAHN-Khwahan Airport-AFGHANISTAN

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#2878]
# Airport Name

Rapid City Regional Airport

# Country?

United States of America

# Improvements that need to be made?

Complete rework from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

No priority

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by HiFlyerBwi** [comment]
Hello could you un-assign me from this airport? I did not know I was assigned to it and I am currently working on a couple of other airports at the moment.

**Comment by MajorTomMueller** [comment]
![OAHN](https://user-images.githubusercontent.com/26853210/54448121-45c26d80-474b-11e9-9111-d325162cb726.jpg)
