### ISSUE TITLE
ZPPP-Kunming/Changshui Airport-YUNNAN-CHINA

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#2879]
# Airport Name
Kunming Changshui International

# Country?
CHINA

# Improvements that need to be made?
NOT YET EDITED

# Are you working on this airport?
NO

# Airport Priority? (A380, 10000ft+ Runway)
10k

**Comment by SpaceGuru01** [comment]
From what I can see, it just needs to be gated. Is that correct?

**Comment by kztmtn** [comment]
Checked imagery, gained materials. I take this one. Assign me.

**Comment by kztmtn** [comment]
Send in for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/62657127-22879d00-b93c-11e9-848c-d1b7aa7b3667.jpg)
