### ISSUE TITLE
LFPM-Melun Villaroche Airport-ILE-DE-FRANCE-FRANCE

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#288]
Has only 3 spawn points. Needs some love
Image: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=LFPM

**Comment by DS2001** [comment]
Maybe I want to do this airport but wedpress don't work by me

**Comment by DS2001** [comment]
I am working on this airport now

**Comment by DS2001** [comment]
This one is ready he is already updates in the game so this one can close

**Comment by kilt46** [comment]
This was completed by DS2001

**Comment by kilt46** [comment]
NEEDS A BIT MORE DETAIL
![image](https://cloud.githubusercontent.com/assets/14023167/16550200/12bdd488-416d-11e6-8cad-3bd78728d849.png)

**Comment by dushyants19** [comment]
@AxelBeder its a french airfield, want to take on?

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21743112/45cf0580-d4c1-11e6-9712-b1ea9666c2dd.png)
