### ISSUE TITLE
SBCY-Marechal Rondon Airport-MATO GROSSO-BRAZIL

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Airports#2880]
# Airport Name

< Cuiabá, Marechal Rondon Airport >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42713447-254df922-86b5-11e8-965a-8772ea4fcc06.png)
