### ISSUE TITLE
SBJF-Juiz de Fora-Francisco de Assis Airport-MINAS GERAIS-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#2881]
# Airport Name

< Juiz de Fora, Francisco de Assis Airport >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by brunocr98** [comment]
Make sure to accept an invitation to join out repository as a collaborator. If you didn’t received this invite via email, contact an administrator. This will be helpful to assign you to issues not created by you.

**Comment by MBeringuy** [comment]
Submitted for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/41803624-63725b46-7650-11e8-9c12-f37a28329fa2.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48101872-1ffde880-e1ee-11e8-953a-ef6f866b4188.png)
