### ISSUE TITLE
RJOC-Izumo Airport-SHIMANE-JAPAN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#2882]
# Airport Name

< Izumo Airport >

# Country?

< Japan >

# Improvements that need to be made?

< redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/41783728-3981c404-7603-11e8-9f50-2a5a4759c50a.png)
