### ISSUE TITLE
SNGA-Guarapari Airport-ESPIRITO SANTO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#2883]
# Airport Name

< Guarapari Airport >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by MBeringuy** [comment]
Submitted for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/41813535-7fd973de-76fd-11e8-90b1-432871b92f17.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/75616491-7c49f180-5b30-11ea-862f-c03c890c2ec3.jpg)
