### ISSUE TITLE
GMAD-Agadir/Al Massira International Airport-SOUSS-MASSA-DRAA-MOROCCO

### ISSUE THREAD

**Issue by lalomarlin** [InfiniteFlightAirportEditing/Airports#2884]
# Airport Name

Agadir-Al Massira

# Country?

Morocco

# Improvements that need to be made?

Redone

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

10000ft+ Runway

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42726298-b87c78f2-8757-11e8-8a71-68aa915d2335.png)
