### ISSUE TITLE
MMTM-Gral. Francisco Javier Mina Airport-TAMAULIPAS-MEXICO

### ISSUE THREAD

**Issue by lalomarlin** [InfiniteFlightAirportEditing/Airports#2885]
# Airport Name

Tampico

# Country?

Mexico

# Improvements that need to be made?

Redone

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)
No

**Comment by lalomarlin** [comment]
Going to finish this one soon as well

**Comment by MajorTomMueller** [comment]
Hey @lalomarlin still around?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103705774-4441e500-4f71-11eb-96b1-14920c4ead95.png)
