### ISSUE TITLE
SBPS-Porto Seguro Airport-BAHIA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#2887]
# Airport Name

< Porto Seguro Airport >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by MBeringuy** [comment]
Submitted for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42008400-f1c90f36-7a4a-11e8-9cd6-879a4f70ba2b.png)

**Comment by MBeringuy** [comment]
Buildings removed and update of markings.
