### ISSUE TITLE
LFPV

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#289]
Only 1 spawn point; Map is rudimentary
Image: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=LFPV

Paris

**Comment by IceBlue02** [comment]
Gonna do this

**Comment by IceBlue02** [comment]
Cannot find any satisfactory satellite background due to privacy blurring. Leaving this.

**Comment by kilt46** [comment]
Airport redone

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20031216/de1eaae0-a341-11e6-98d1-7e1ed2f298dc.png)
