### ISSUE TITLE
RJSI-Hanamaki airport-IWATE-JAPAN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#2891]
# Airport Name

< Hanamaki airport  >

# Country?

< Japan >

# Improvements that need to be made?

< Redo from scratch  >

# Are you working on this airport?

< Yes  >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/41780694-17166260-75fb-11e8-9c69-9b6987b45c60.png)
