### ISSUE TITLE
19N-Camden County Airport-NEW JERSEY-USA

### ISSUE THREAD

**Issue by ChrisLevet232** [InfiniteFlightAirportEditing/Airports#2892]
# Airport Name

< Camden County Airport >

# Country?

< United States of America >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low Priority >

**Comment by ChrisLevet232** [comment]
Airport complete and submitted for review via email.

**Comment by moritzbabl** [comment]
added

**Comment by ChrisLevet232** [comment]
Thanks for the tips! Greatly appreciated ;)

Chris Levet
Cx Field Technician



On Sun, Jun 17, 2018 at 12:44 PM -0400, "moritzbabl" <notifications@github.com<mailto:notifications@github.com>> wrote:


added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42118998-308da33e-7bcd-11e8-98c4-12dbca194717.png)
