### ISSUE TITLE
SBJU-Juazeiro do Norte Airport-CEARA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#2893]
# Airport Name

< Orlando Bezerra de Menezes Airport >

# Country?

< Brazil>

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/41813720-b52a9cb8-7700-11e8-9a97-c8f9a9a6739b.png)

**Comment by brennanhackard** [comment]
@victormw22 will ONLY be editing the recently renovated commercial apron, which has had its layout changed and an additional stand added.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104075306-fa0e6d00-51d7-11eb-9191-2b1918d78043.png)
