### ISSUE TITLE
SBUL-Ten Cel Av Cesar Bombonato Airport-MINAS GERAIS-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#2894]
# Airport Name

< Ten Cel AV Cesar Bombonato Airport >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low Priority >

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/41813381-a486653c-76fa-11e8-9440-8de16b4558e8.png)
