### ISSUE TITLE
SBCA-Cel Adalberto Mendes da Silva Airport-PARANA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#2896]
# Airport Name

< Cascavel, Cel Adalberto Mendes da Silva Airport >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low Priority >

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/41686565-271917e0-74aa-11e8-8131-453b37b5e620.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/41813242-814a83a8-76f7-11e8-8f08-07fb1b3a8e97.png)

**Comment by MajorTomMueller** [comment]
*A new terminal was added and imagery for it is in Google Earth Pro.
*A new GA area with hangars was added to the NW of the airport.
* The main apron is poorly made, separate hangars with a 5m distance are made as a single piece. In addition, some lines are missing, and no hangar has spawns.
