### ISSUE TITLE
FZQA-Lubumbashi Airport-KATANGA-DEMOCRATIC REPUBLIC OF THE CONGO

### ISSUE THREAD

**Issue by mbmhwue148** [InfiniteFlightAirportEditing/Airports#2897]
# Airport Name

FZQA, Lubumbashi Intl 

# Country?

Democratic Republic of the Congo

# Improvements that need to be made?

Complete redraw from scratch

# Are you working on this airport?

Redoing it

# Airport Priority? (A380, 10000ft+ Runway)

10000ft+

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/41874162-ad3dd8ca-788c-11e8-9b58-162f8709ed99.png)
