### ISSUE TITLE
RJBK-Kohnan Airport-OKAYAMA-JAPAN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#2898]
# Airport Name

< Kohnan Aiefield >

# Country?

< Japan >

# Improvements that need to be made?

< redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/41753671-75a86ca4-7594-11e8-91fd-62ddb14b4f13.png)
