### ISSUE TITLE
ROKJ-Kumejima Airport-OKINAWA-JAPAN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#2899]
# Airport Name

< Kumejima Airport >

# Country?

< Japan >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/41752961-3b43fa50-7590-11e8-8655-4a5ba683ff5d.png)
