### ISSUE TITLE
KLAX-Los Angeles International Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#29]

**Comment by Swang007** [comment]
Will correct me if I'm wrong pre-parking lines and add shoulders to taxiways.

**Comment by Swang007** [comment]
Still working on this, it's a really big project. I'm also getting bogged down with homework and studying for finals. When I travel to Germany at the end of May I'll probably finish on the 14 hour plane ride.

**Comment by Swang007** [comment]
You can now keep track of my progress. Here's a checklist of things I still need to do.

https://www.checkli.com/checklists/viewro/60de762aa4b65522ac28c74d92560063

**Comment by Swang007** [comment]
Hehe finish on the plane, yeah right...

**Comment by kilt46** [comment]
Is KLAX being done or is it open?

**Comment by carmichaelalonso** [comment]
Sean is redoing this one.

**Comment by kilt46** [comment]
Was unsure as listing states Swang was unassigned 24 days ago

**Comment by JohnPreston21** [comment]
Yep, Sean is rebuilding this one from scratch.

**Comment by kilt46** [comment]
This one has now been completed and uploaded

**Comment by Swang007** [comment]
Actually still open. Thanks for finishing up the taxiways for me but I'm going to tidy up the details.

**Comment by Swang007** [comment]
@kilt
https://community.infinite-flight.com/t/air-newlealand/14757/5

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/11261946/12ae8e06-8e3f-11e5-8340-801093df4452.png)
small yellow line change

**Comment by dushyants19** [comment]
Looks like we have Hold Short spawn points :disappointed: in here

**Comment by Swang007** [comment]
If someone has a great attention to detail, this should be a quick project for you. It's not a biggie, but all the individual points need to be replaced with curved lines.

![points](https://cloud.githubusercontent.com/assets/11000109/13869832/7c93677a-ec9e-11e5-8a63-9362cd1ea667.png)

**Comment by IceBlue02** [comment]
@kilt46 are you done?

**Comment by kilt46** [comment]
No

**Comment by dushyants19** [comment]
@kilt46 still doing this?

**Comment by IceBlue02** [comment]
What is the status on this?

**Comment by IFAEpat** [comment]
Anything? Anyone?

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17874347/b0a0a80c-6890-11e6-8f9b-74f9a1e184b3.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17874369/d40ee4d4-6890-11e6-99e2-9a228ea7da3b.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17874377/e14757a8-6890-11e6-89a9-2bfd199aff35.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33805003-b1741622-dd76-11e7-8d46-8b76690c50c9.png)

**Comment by moritzbabl** [comment]
done

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/40587468-eeaa3baa-6194-11e8-8c6e-d956e87d0bae.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52540033-b6d8c480-2d4a-11e9-9106-5633caae033e.png)
