### ISSUE TITLE
KGRB-Austin Straubel International Airport-WISCONSIN-USA

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#290]
Only 1 spawn point
Image: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=KGRB

**Comment by ZaidSal** [comment]
I will add parking and make the airport very good

**Comment by dushyants19** [comment]
@ZaidSal can you self assign this?

**Comment by ZaidSal** [comment]
I am rechanging this to redone still some fixes that I need to do

**Comment by ZaidSal** [comment]
i will o P2 of the edit

**Comment by ZaidSal** [comment]
Just Finished

**Comment by JohnPreston21** [comment]
Is this one completed? The taxi lines aren't completed and there is only 1 Term spawn

**Comment by dushyants19** [comment]
Free to take, his computer is down

**Comment by dushyants19** [comment]
(Assigned @freddiefrogs)

**Comment by dushyants19** [comment]
@freddiefrogs still doing this? If not, remove labels and un-assign yourself

**Comment by freddiefrogs** [comment]
It won't let me close the issue. :/

**Comment by freddiefrogs** [comment]
Thanks dushy.

**Comment by dushyants19** [comment]
@freddiefrogs did this get approved?

**Comment by samuelandersson** [comment]
@dushyants19 It was never added to the repo

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21835180/9e1cdf2a-d780-11e6-862b-0ef2cee2a049.png)

**Comment by Czechoslovaki** [comment]
@ShaneAviation will rework the airport.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111978720-3d3b6500-8ad2-11eb-8d44-7e9a389b5a41.png)
