### ISSUE TITLE
SCHL-Hacienda Lipangue Airport-SANTIAGO-CHILE

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#2901]
♻️

**Comment by brunocr98** [comment]
#331 < :facepalm:

**Comment by osujim15** [comment]
May I have this one?

**Comment by osujim15** [comment]
Oh wait. I messed up. I meant I want to do KPVU.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42738353-17cd45fc-8848-11e8-9d3f-8b644e6add45.png)
