### ISSUE TITLE
SNJO-Joao Pessoa Aeroclube Airport-PARAIBA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#2902]
# Airport Name

< Joao Pessoa Aeroclube >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low Priority >

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/41684526-447323b4-74a3-11e8-88ab-035728cc0beb.png)
