### ISSUE TITLE
SCIE-Carriel Sur Airport-BIO BIO-CHILE

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#2903]
# Airport Name

< Concepcion, Carriel Sur Intl Airport >

# Country?

< Chile >

# Improvements that need to be made?

< Redone from Scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low Priority >

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/41946643-20060c96-7979-11e8-808b-62f413d6c4a9.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/41946725-74b931be-7979-11e8-86e4-c0ce6dc93ba1.png)
