### ISSUE TITLE
OAHN-Sheghnan Airfield-AFGHANISTAN

### ISSUE THREAD

**Issue by natedog508** [InfiniteFlightAirportEditing/Airports#2904]
♻️

**Comment by natedog508** [comment]
First edit so wanted to start off small. AKA 1 taxiway

**Comment by brunocr98** [comment]
Please search before creating an issue #463

**Comment by osujim15** [comment]
May I do this one instead of KOMA?

**Comment by osujim15** [comment]
I'll begin working on this in maybe a week when I'm available and have access to my computer.

**Comment by osujim15** [comment]
Correction. The airport is caught up in peer review.

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by MajorTomMueller** [comment]
![OAHN](https://user-images.githubusercontent.com/26853210/54449486-82dc2f00-474e-11e9-9003-44b6bee19749.jpg)
