### ISSUE TITLE
KLOM-Wings Field-PENNSYLVANIA-USA

### ISSUE THREAD

**Issue by gsherbert** [InfiniteFlightAirportEditing/Airports#2905]
# Airport Name

< Wings Field >

# Country?

< USA >

# Improvements that need to be made?

< Complete Redo >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low Priority >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45788414-1de0ca00-bc40-11e8-9f2a-bea206bde940.png)
