### ISSUE TITLE
SBKG-Presidente Joao Suassuna Airport-PARAIBA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#2906]
# Airport Name

< Presidente Joao Suassuna Airport >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low priority >

**Comment by MBeringuy** [comment]
Submitted for review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42660461-e2c4a9b2-85f0-11e8-9121-6c9573ffe7ca.png)
