### ISSUE TITLE
SBSL-Marechal Cunha Machado Airport-MARANHAO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#2907]
# Airport Name

< Marechal Cunha Machado Intl Airport >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low priority >

**Comment by MBeringuy** [comment]
Submitted for review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42662232-77f10198-85f6-11e8-8605-5de84010e10e.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42662340-dafaf8ac-85f6-11e8-9d5e-f74f457b4649.png)
