### ISSUE TITLE
KUES

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#291]
There are 8 Hold Short positions. Do we wish to remove them?
Image: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=KUES

**Comment by kilt46** [comment]
has hold short areas

**Comment by dushyants19** [comment]
Needs a rework?

**Comment by kilt46** [comment]
No just remove hold shorts and add a few more remote spawn points

**Comment by dushyants19** [comment]
@DavidCutler are you still "fixing her"?

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20649560/62b26d12-b488-11e6-845c-16f01ab278fa.png)
