### ISSUE TITLE
SBIL-Jorge Amado Airport-BAHIA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#2910]
# Airport Name

< Jorge Amado Airport >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low priority >

**Comment by MBeringuy** [comment]
Submitted for review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42667795-1d4ea3fe-8613-11e8-911e-e86b51cc6bcd.png)
