### ISSUE TITLE
SBZM-Presidente Itamar Franco Airport-MINAS GERAIS-BRAZIL

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Airports#2913]
# Airport Name

< Goiana, Presidente Itamar Franco >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< yes >

# Airport Priority? (A380, 10000ft+ Runway)

< low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42715354-392609e2-86bc-11e8-88e3-923ecedf61ac.png)
