### ISSUE TITLE
SBPV-Governador Jorge T de O International Airport-RONDONIA-BRAZIL

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Airports#2917]
# Airport Name

< Porto Velho, Gov Jorge Teixeira de Oliveira >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by FellipeEdu** [comment]
Hello, I have no time to edit this airport due to studies, and my colleague Maurício Cabral offered to finish it, so I ask you to unassign this issue to me.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46380869-a1031680-c669-11e8-9874-5b8bf9617807.png)
