### ISSUE TITLE
KGHG-Marshfield Municipal Airport - George Harlow Field-MASSACHUSETTS-USA

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Airports#2919]
Part of [Project New England](https://community.infinite-flight.com/t/project-new-england/43169/).

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42187574-25bcde20-7e16-11e8-96ea-7dfa7330b3e4.png)
