### ISSUE TITLE
UWPS-Saransk Airport-MORDOVIA-RUSSIA

### ISSUE THREAD

**Issue by Wespenstich** [InfiniteFlightAirportEditing/Airports#2920]
♻️

**Comment by brunocr98** [comment]
This is not a place to post your personal wishes.

**Comment by brunocr98** [comment]
Ok, you're contradicting yourself, are you going to work on this?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42410803-d4a2b05c-81b5-11e8-932f-c380fd32f3bf.png)
