### ISSUE TITLE
RJDT-Tsushima Airport-NAGASAKI-JAPAN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#2921]
# Airport Name

< Tsushima Airport >

# Country?

< Japan >

# Improvements that need to be made?

< redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42410551-c2e5248a-81b0-11e8-8a8c-12bf2b9a1e30.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42410556-d0fa8baa-81b0-11e8-845f-67a354af2d62.png)
