### ISSUE TITLE
SBAR-Santa Maria Airport-SERGIPE-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#2922]
# Airport Name

< Aracaju, Santa Maria Airport >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low priority >

**Comment by MBeringuy** [comment]
Submitted for review.

**Comment by kilt46** [comment]
Is this hangar missing?
![image](https://user-images.githubusercontent.com/14023167/42716314-91590f34-86c0-11e8-99d6-81818f3aed4e.png)

**Comment by kilt46** [comment]
Please check unicom
![image](https://user-images.githubusercontent.com/14023167/42716363-bc7d7b82-86c0-11e8-8e46-bfde9619b944.png)

**Comment by kilt46** [comment]
Runway width
![image](https://user-images.githubusercontent.com/14023167/42716381-d9ae181a-86c0-11e8-8359-057971363ed1.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42723904-214b4a68-872e-11e8-8712-b875308e4f22.png)
