### ISSUE TITLE
UHSH-Okha Airport-SAKHALIN-RUSSIA

### ISSUE THREAD

**Issue by VladK125rus** [InfiniteFlightAirportEditing/Airports#2924]
# Airport Name

Okha

# Country?

Russia

# Improvements that need to be made?

Redo from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

No

**Comment by kilt46** [comment]
Missing ATC
![image](https://user-images.githubusercontent.com/14023167/42733856-078b90d4-87ff-11e8-915e-68d265a2a626.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42734039-8f0a4188-8802-11e8-8e33-b60e8d3f6dfc.png)
