### ISSUE TITLE
RJSR-Odate-Noshiro Airport-AKITA-JAPAN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#2927]
# Airport Name

< Odate-Noshiro Airport >

# Country?

< Japan >

# Improvements that need to be made?

< redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42478551-b90486ea-839a-11e8-956e-b32ae4ca7384.png)
