### ISSUE TITLE
SBGO-Goiania/Santa Genoveva Airport-GOIAS-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#2928]
# Airport Name

< Goiania, Santa Genoveva Airport >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low priority >

**Comment by MBeringuy** [comment]
Submitted for review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42605437-8e36843c-853d-11e8-9eb8-08f1d13deb33.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113069565-3d003100-9186-11eb-95b2-55fdbe830a55.png)
