### ISSUE TITLE
EGBE

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#293]
2 spawn points and NO lines!
Image: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=EGBE

**Comment by IceBlue02** [comment]
Taking this for a total redo.

- Sorry Misha, clicked the wrong one :-P

**Comment by IceBlue02** [comment]
Job Done!

Now has lines, buildings, more detailed TWYs and more spawn points

**Comment by Swang007** [comment]
https://community.infinite-flight.com/t/missing-taxiway-egbe-coventry-airport/19632

**Comment by samuelandersson** [comment]
Gonna fix the small issues that are listed in the community thread posted above by Sean.

**Comment by samuelandersson** [comment]
That was a quick fix, some issues were already resolved? Anyway, did what I could.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17249543/09756802-5566-11e6-8c5e-d00b2eebc275.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18297988/bb310fa0-747a-11e6-955b-a029eff9cc48.png)

**Comment by kilt46** [comment]
Airport realigned.
