### ISSUE TITLE
ROKR-Kerama Airport-OKINAWA-JAPAN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#2932]
# Airport Name

< Kerama Airport >

# Country?

< Japan >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42479435-7ca6a7f6-839e-11e8-985f-03077036301f.png)
