### ISSUE TITLE
SBAN-Anapolis AB Airport-GOIAS-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#2934]
# Airport Name

< Anapolis, Base Aerea >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Runway 06L/24R with 10843ft in length >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42725223-c8cb46fa-8745-11e8-8c47-eb6e302fc692.png)
