### ISSUE TITLE
SBMQ-Macapa/Alberto A. Intl Airport-AMAPA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#2935]
# Airport Name

< Macapa, Alberto Alcolumbre Intl Airport >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low priority >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42734727-ae88e63e-880e-11e8-9865-37ae6dcfbf99.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105922325-10059580-6000-11eb-8767-c50354fe9152.png)
