### ISSUE TITLE
KTAN-Taunton Municipal Airport - King Field-MASSACHUSETTS-USA

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Airports#2936]
Part of [Project New England](https://community.infinite-flight.com/t/project-new-england/43169/).

**Comment by CptNathanHope** [comment]
The state of **Massachusetts** is complete. 🎉

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42733581-00f78526-87f9-11e8-9243-e9c07c429e9d.png)
