### ISSUE TITLE
SBSR-Sao Jose do Rio Preto Airport-SAO PAULO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#2937]
# Airport Name

< Sao Jose do Rio Preto Airport >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low priority >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/43493608-6dec4362-94f4-11e8-9e95-35eff26bd2cf.png)
