### ISSUE TITLE
LFBM-Mont de Marsan-NOUVELLE AQUITAINE-FRANCE

### ISSUE THREAD

**Issue by cfvfd104** [InfiniteFlightAirportEditing/Airports#2939]
♻️

**Comment by cfvfd104** [comment]
Thank You @RyanEpps. So, do you guys prefer for us to edit and redo high priority airports or can we start where we are comfortable and work our way up?

**Comment by RyanEpps** [comment]
It is recommended to start with a smaller airport first to "practice" on, before moving on to any larger airports you all would prefer to edit.

**Comment by cfvfd104** [comment]
Cool Beans, I think midland will be perfect for me to practice on. I know it well and its not a heavy traffic airport. Thanks

**Comment by cfvfd104** [comment]
This airport has been submitted to Official Review.

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by MrMrMan** [comment]
I think I'll take this one. Looks fun!

**Comment by cfvfd104** [comment]
I have began working on this again. Due to issues in my personal life, I had to take some time and get my life back in order. I will resume my active status. If this airport still has not been completed, please let me know as I still have all of my previous work saved and can pick up where I left off.

**Comment by MrMrMan** [comment]
Hey there! I have been working on this airport, and have it almost entirely completed except for the rest of the hangars and the spawns. Are you in the Slack? I’d love to have a more in-depth conversation with you about your completion and what would be more efficient. 

I meant in no way to “steal” this from you, but it was up for grabs and looked fun.

**Comment by cfvfd104** [comment]
Oh, no I dont think you stole it. I was just saying if it hadnt been done yet that I would finish it up. I was in the slack but was removed due to inactivity. I am trying to reach an admin so that I can be added back.

**Comment by MrMrMan** [comment]
Alrighty! When you get added back, let’s compare what we both have.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/77239535-a84e1500-6bba-11ea-8f7e-7ab28913debe.jpg)

**Comment by MajorTomMueller** [comment]
@RyanEpps ?

**Comment by MajorTomMueller** [comment]
recycled

**Comment by MajorTomMueller** [comment]
![LFBM-git](https://user-images.githubusercontent.com/26853210/88449152-24d85500-ce34-11ea-9f5a-fbd5a13e6ab7.png)
