### ISSUE TITLE
EGDL

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#294]
London

Some lines messed up. Only 4 Spawn points
Image: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=EGDL

**Comment by JohnPreston21** [comment]
Code may be incorrect.

**Comment by Swang007** [comment]
What code?

**Comment by JohnPreston21** [comment]
There's no EGDL, I just checked.

**Comment by kilt46** [comment]
Yes there is. It is in the UK

**Comment by Hamza787Aj** [comment]
May I add parking ramps, there's a few empty ones.

**Comment by JohnPreston21** [comment]
Are you doing this one @Hamza787Aj ?

**Comment by kilt46** [comment]
Airport realigned and cleaned up

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17249804/3fd26818-5567-11e6-99a3-99ab74f251f6.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18296904/912b8b66-7472-11e6-95ba-1e1a29ef815b.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/47623848-f9e89200-dae3-11e8-8357-5a434a52f3db.png)
