### ISSUE TITLE
SBCB-Cabo Frio Airport-RIO DE JANEIRO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#2940]
# Airport Name

< Cabo Frio Airport >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low priority >

**Comment by MBeringuy** [comment]
@RyanEpps that you added up is in the wrong issue.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/43676333-bf26b4b6-97b4-11e8-9915-aa904ce27919.png)
