### ISSUE TITLE
RJFN-Nyutabaru Air Base-MIYAZAKI-JAPAN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#2942]
# Airport Name

< Nyutabaru Air Base >

# Country?

< Japan >

# Improvements that need to be made?

< redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/43107317-122ff9fe-8ea2-11e8-948d-141ae1f8a51b.png)
