### ISSUE TITLE
MPMI-San Miguel Airport-PANAMA-PANAMA

### ISSUE THREAD

**Issue by MatttheBoss179** [InfiniteFlightAirportEditing/Airports#2943]
♻️

**Comment by moritzbabl** [comment]
Up for grabs

**Comment by Martijn-Decates** [comment]
Are you still working on it?

**Comment by brunocr98** [comment]
This is a suggestion, no one is working on it.

**Comment by Martijn-Decates** [comment]
Ok so  i can start it?

**Comment by brunocr98** [comment]
Please let us know when all the 3 airports are approved.

**Comment by Martijn-Decates** [comment]
i want to make this airport! im already working on it!

**Comment by Martijn-Decates** [comment]
i dont want to make this airport anymore. maybe when there is a new photo on google maps. so if someone want to make this airport. you can go.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/62652934-d8e68480-b932-11e9-9919-7114d9cd8fb9.jpg)
