### ISSUE TITLE
NZNR-Napier Airport-HAWKE’S BAY-NEW ZEALAND

### ISSUE THREAD

**Issue by Lukeh0** [InfiniteFlightAirportEditing/Airports#2944]
# Airport Name
Hawkes Bay Airport (Napier Airport)

# Country?
New Zealand

# Improvements that need to be made?
Needs a Apron and Gates added

# Are you working on this airport?
Yes

# Airport Priority? (A380, 10000ft+ Runway)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/43104627-af68e330-8e97-11e8-817c-27106a87e884.png)

**Comment by brunocr98** [comment]
@Lukeh0 will be redoing the airport.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/77341168-199ddd00-6d0d-11ea-9efa-8146f31ded48.jpg)
