### ISSUE TITLE
OAGZ-Gardez Airport-PAKTIA-AFGHANISTAN

### ISSUE THREAD

**Issue by Georges180305** [InfiniteFlightAirportEditing/Airports#2945]
# Airport Name

< Nador International Airport >

# Country?

< Morocco >

# Improvements that need to be made?

< I will redo the airport from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low Priority >

**Comment by brunocr98** [comment]
Why are you closed this?

**Comment by Georges180305** [comment]
I did not know I could edit it so i deleted it and I wanted to do a new one. But thanks for putting it back.

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by MajorTomMueller** [comment]
![OAGZ](https://user-images.githubusercontent.com/26853210/54476370-ca20f900-47fc-11e9-901a-da303637f96d.jpg)
