### ISSUE TITLE
SBBH-Belo Horizonte/Carlos Drummond de Andrade Airport-MINAS GERAIS-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#2946]
# Airport Name

< Pampulha - Carlos Drummond de Andrade Airport >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low priority >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44280832-737a1f00-a21b-11e8-8791-f8f219163c9e.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48909909-2f0ea880-ee34-11e8-9225-1832c709aa4c.png)

**Comment by MBeringuy** [comment]
Airport updated.
