### ISSUE TITLE
OABT-Bost Airport-HELMAND-AFGHANISTAN

### ISSUE THREAD

**Issue by forest23** [InfiniteFlightAirportEditing/Airports#2947]
# Airport Name

ZUAS-Anshun Huangguoshu Airport

# Country?

China

# Improvements that need to be made?

Not yet edited

# Are you working on this airport?

YES

# Airport Priority? (A380, 10000ft+ Runway)

Low

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by MajorTomMueller** [comment]
![recycle](https://user-images.githubusercontent.com/26853210/54290892-06a9e600-45ac-11e9-8e08-2e83f9297dd1.png)

**Comment by MajorTomMueller** [comment]
![OABT](https://user-images.githubusercontent.com/26853210/54293954-255eab80-45b1-11e9-9558-c8e1a8c0f7c2.jpg)
