### ISSUE TITLE
EHVK-Volkel Air Base-NOORD BRABANT-NETHERLANDS

### ISSUE THREAD

**Issue by cfvfd104** [InfiniteFlightAirportEditing/Airports#2949]
32°24'40.8"N 099°40'54.8"W

**Comment by moritzbabl** [comment]
This is a duplicate, for airport issues head to the original issue -> #262

**Comment by brunocr98** [comment]
KDYS is already a suggestion #2751. I’ll look for something else.

**Comment by MajorTomMueller** [comment]
I step back from editing for the moment.
Up for Graps....

**Comment by MajorTomMueller** [comment]
![ehvk-git](https://user-images.githubusercontent.com/26853210/49030400-80f25e00-f1a7-11e8-964f-1b063ab33460.jpg)
