### ISSUE TITLE
EGHI-Southampton Airport-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#295]
Needs more Gates

**Comment by kilt46** [comment]
Completed and emailed
Image: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=EGHI

**Comment by dushyants19** [comment]
Quoted from https://github.com/InfiniteFlightAirportEditing/Airports/issues/447, 
>>>Could do with a look at as there are some lines missing such as the turning circle line on rwy 20, and the hold short lines are too small. The terminal building needs the white lines removed and some parking arrows need aligning with the parking line. Also the surface of the turning circles needs to be asphalt I think.

**Comment by Will171** [comment]
![image](https://cloud.githubusercontent.com/assets/16463484/13728380/13d830c8-e90e-11e5-870b-c5d114b5814d.png)

**Comment by Will171** [comment]
Sill needs work, ill have a look at it :)

**Comment by Swang007** [comment]
@Will171: Are you basing this off of the current in-game scenery or did you check out Dushyanth's latest commit from 5 days ago?

**Comment by Will171** [comment]
i checked his latest commit, and worked from that.

**Comment by Will171** [comment]
Completed

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17250893/f4de3260-556b-11e6-816f-e572a2f2f04e.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18270137/0f02f722-73f1-11e6-825a-a3216adb63f1.png)

**Comment by MajorTomMueller** [comment]
Spawn size needs to be checked
https://community.infiniteflight.com/t/gate-restriction-inaccuracy-southampton-eghi-uk/385986?u=major-tom

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/77239910-c289f200-6bbe-11ea-8813-b347afbb417f.jpg)
