### ISSUE TITLE
UUBW-Moscow Zhukovsky Airport-MOSCOW-RUSSIA

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#2952]
55°33'10.0"N 038°8'59.0"E

**Comment by 2003iggy** [comment]
Can I take this one please?

**Comment by sentikum** [comment]
Yes you can

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/89230341-b8362680-d5a8-11ea-82bd-700d913968ed.png)
