### ISSUE TITLE
PAPK-Napaskiak Airport-ALASKA-USA

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#2953]
60°42′10″N 161°46′42″W

**Comment by renorris** [comment]
Global Priority 10k Runway?
![airport](https://user-images.githubusercontent.com/25239181/43476391-58d4b974-94ad-11e8-8b65-49d1ac1240eb.PNG)
](url)

**Comment by dushyants19** [comment]
10k+ runway is a water runway

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46251360-38702b80-c416-11e8-972d-81c3992c3461.png)
