### ISSUE TITLE
KSKF-Lackland Air Force Base-TEXAS-USA

### ISSUE THREAD

**Issue by Taixipo2003** [InfiniteFlightAirportEditing/Airports#2956]
♻️

**Comment by brunocr98** [comment]
** PLEASE STOP** creating duplicates. This airport has been **REDONE** already.

**Comment by cfvfd104** [comment]
if this is available, you can assign it to me.

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by MajorTomMueller** [comment]
![KSKF-git](https://user-images.githubusercontent.com/26853210/54879338-f1e51200-4e37-11e9-8935-f22d4588abfd.jpg)
