### ISSUE TITLE
KORS-Orcas Island Airport-WASHINGTON-USA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#2959]
# Airport Name

< Orcas Island Airport >

# Country?

< United States >

# Improvements that need to be made?

< Redid Whole Airport (Basically) >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by Balloonchaser** [comment]
Sent in for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44121487-d97d6100-9fe5-11e8-8c9b-ab87a8795250.png)
