### ISSUE TITLE
KAVX

### ISSUE THREAD

**Issue by xjayrod1999** [InfiniteFlightAirportEditing/Airports#296]
Editing Taxi,runway,parking

**Comment by xjayrod1999** [comment]
Being Redone

**Comment by JcFl4** [comment]
Sorry but what are you doing in KAVX? It is already done. Everything is added.

**Comment by kilt46** [comment]
This appears to be a pretty basic airport. The view I get from Wedbing is very distorted. It does not appear that this airport requires any surgery.

**Comment by Swang007** [comment]
Please search for similar issues before making new ones :)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19626147/3b1597b0-98f0-11e6-976f-d6beb7b4080e.png)
