### ISSUE TITLE
VTBU-Rayong/U-Tapao Rayong Pattaya Airport-RAYONG-THAILAND

### ISSUE THREAD

**Issue by VladK125rus** [InfiniteFlightAirportEditing/Airports#2962]
# Airport Name

U-Tapao–Rayong–Pattaya International Airport

# Country?

Thailand

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Starting

# Airport Priority? (A380, 10000ft+ Runway)

10000ft+ Runway

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45522265-8f73d080-b787-11e8-9d05-7b552883972b.png)
