### ISSUE TITLE
9LL1-Buffalo Park Airfield-ILLINOIS-USA

### ISSUE THREAD

**Issue by renorris** [InfiniteFlightAirportEditing/Airports#2964]
# Airport Name

Buffalo Park Airport

# Country

USA

# Improvements that need to be made?

Redone from scratch

**Comment by renorris** [comment]
sent in for review

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/43493136-0345dbba-94f2-11e8-9e2a-9d681fd16f9e.png)

**Comment by kilt46** [comment]
9LL1 is a grassland and not an airfield - Deleted

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/83947273-9f450b00-a7db-11ea-9842-034e2ef11cc5.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/83952606-83ebf700-a7ff-11ea-887c-a0453b022ed5.png)
