### ISSUE TITLE
TFFB-Basse Terre Baillif Airport-BASSE-TERRE-GUADELOUPE

### ISSUE THREAD

**Issue by Nickm45** [InfiniteFlightAirportEditing/Airports#2966]
# Airport Name

Baillif

# Country?

Guadeloupe

# Improvements that need to be made?

Airport needs to be moved the west, currently in the wrong place, cuts into the hill making takeoff and landing difficult

# Are you working on this airport?

yes

# Airport Priority? (A380, 10000ft+ Runway)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/43982133-4a2f69c2-9cba-11e8-97fa-310046e0453b.png)
