### ISSUE TITLE
MRBT-Barra Del Tortugero Airport-LIMON-COSTA RICA

### ISSUE THREAD

**Issue by Nickm45** [InfiniteFlightAirportEditing/Airports#2967]
# Airport Name

Barra DeTortuguero

# Country?

Costa Rica

# Improvements that need to be made?

New, doesnt exist in IF yet

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

< Enter text here >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44429006-b7db2700-a55b-11e8-9d8c-e0e6d2efca94.png)
