### ISSUE TITLE
EGYM

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#297]
Only 6 spawn points in one place. Blocky grapgics on taxiways
Image:http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=EGYM

**Comment by ErmakDimon** [comment]
taking it over

**Comment by dushyants19** [comment]
Are you still doing this @ErmakDimon ?

**Comment by kilt46** [comment]
Redrawn

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19420465/73b507f2-93b1-11e6-8fb0-d229bda628f6.png)
