### ISSUE TITLE
KOMA-Eppley Airfield Airport-NEBRASKA-USA

### ISSUE THREAD

**Issue by RyanEpps** [InfiniteFlightAirportEditing/Airports#2970]
Part of Project US.

**Comment by MajorTomMueller** [comment]
... airfield airport... sounds weird somehow?

**Comment by RyanEpps** [comment]
I never said that it didn't.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44399786-6f494c80-a50e-11e8-8e9f-9d43be0dab4a.png)
