### ISSUE TITLE
SBRP-Ribeirao Preto/Leite Lopes Airport-SAO PAULO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#2971]
# Airport Name

< Ribeirao Preto, Leite Lopes Airport >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low priority >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44458880-31f7c400-a5cd-11e8-815f-7082730f1360.png)
