### ISSUE TITLE
LKPR Václav Havel Airport Prague update

### ISSUE THREAD

**Issue by lvylvy** [InfiniteFlightAirportEditing/Airports#2972]
# Airport Name

< LKPR Václav Havel Airport Prague >

# Country?

< Czech Republic >

# Improvements that need to be made?

< add ATC frequencies, lights, spawn sizes, heliport etc. >

# Are you working on this airport?

< No >

# Airport Priority? (A380, 10000ft+ Runway)

< A380 (GP1), +10K (GP2), World Capitals (GP3) >

**Comment by brunocr98** [comment]
This airport is already redone #525. Don't create issues to report design problems on airports. Thanks.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/43984307-5610be3e-9cc5-11e8-9b48-8092d511dd50.png)
