### ISSUE TITLE
N51-Solberg–Hunterdon Airport-NEW JERSEY-USA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#2977]
# Airport Name

< Solberg-Hunterdon Airport >

# Country?

< USA >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by Balloonchaser** [comment]
Sent in for OR

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
Should be 3 runways!!!
![image](https://user-images.githubusercontent.com/14023167/44122546-09437682-9fea-11e8-94eb-125b21e17604.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44122734-cb6a74e0-9fea-11e8-9dd1-5fc6badeb98d.png)
