### ISSUE TITLE
RJSH-Hachinohe Airbase-AOMORI-JAPAN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#2978]
Part of Project Japan.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44122896-6b0451c4-9feb-11e8-8f7a-71b6a30fd959.png)

**Comment by kilt46** [comment]
Charts show only one runway!
![image](https://user-images.githubusercontent.com/14023167/44122997-de0ae796-9feb-11e8-8a48-40a000332d39.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44180318-4dd90280-a0c1-11e8-9b32-e0b72483b558.png)
