### ISSUE TITLE
OATQ-Taloqan Airport-TAKHAR-AFGHANISTAN

### ISSUE THREAD

**Issue by liamkirky** [InfiniteFlightAirportEditing/Airports#2979]
# Airport Name

< Dalaman Airport >

# Country?

< Turkey >

# Improvements that need to be made?

< Redone from Scracth (Not been edited)  >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low Priority >

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by MajorTomMueller** [comment]
![OATQ](https://user-images.githubusercontent.com/26853210/54474570-bb2f4c00-47e6-11e9-861a-78912dec1dc3.jpg)
