### ISSUE TITLE
EGYE

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#298]
Only 4 spawn points in one location. Graphics on taxiways are blocky
Image: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=EGYE

**Comment by samuelandersson** [comment]
I'll do this one.

**Comment by samuelandersson** [comment]
For some reason this airport gives me some huge lag. Won't continue because of that.

**Comment by kilt46** [comment]
Started work

**Comment by kilt46** [comment]
Reworked airport

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19628705/8a69df86-9929-11e6-881e-063e108ad5d0.png)
