### ISSUE TITLE
LEMH-Menorca Airport-ISLAS BALEARES-SPAIN

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#2980]
# Improvements that need to be made?
Hey there everyone, when I flew to LEMH (Menorca) I have seen there are two runways instead of one. The runway 19L-1R in real world is a taxiway.

**Comment by vansh21** [comment]
can i be working on this

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by Balloonchaser** [comment]
Ill take this - Submitted to OR

**Comment by orangejuicie** [comment]
Runway number correction.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109576449-5e073080-7ab9-11eb-90c9-d0c9fd31d507.png)
