### ISSUE TITLE
KUNV-University Park Airport-PENNSYLVANIA-USA

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Airports#2984]
# Airport Name

University Park Airport. 

# Country?

USA.

# Improvements that need to be made?

Redone from scratch. 

# Are you working on this airport?

Yes.

# Airport Priority? (A380, 10000ft+ Runway)

Low priority. 
Part of [Project US Commercial Airports](https://community.infinite-flight.com/t/project-us-commercial-airports/234240).

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44299406-a9baab80-a2ba-11e8-9722-e3ebaa444dc5.png)
