### ISSUE TITLE
KJQF-Concord–Padgett Regional Airport-NORTH CAROLINA-USA

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Airports#2986]
# Airport Name

Concord–Padgett Regional Airport (NASCAR Airport).

# Country?

USA.

# Improvements that need to be made?

Redone from scratch. 

# Are you working on this airport?

Yes.

# Airport Priority? (A380, 10000ft+ Runway)

Low priority.
Part of [Project US Commercial Airports](https://community.infinite-flight.com/t/project-us-commercial-airports/234240?u=nathan).

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44308468-28c3e880-a37c-11e8-8d04-781d37e2d732.png)
