### ISSUE TITLE
N87-Trenton-Robbinsville Airport-NEW JERSEY-USA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#2987]
# Airport Name

< Trenton-Robbinsville Airport >

# Country?

< United States of America >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44433192-e3b1d900-a56a-11e8-8b13-2077ed650051.png)
