### ISSUE TITLE
SBPK-Pelotas Airport-RIO GRANDE DO SUL-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#2988]
# Airport Name

< Pelotas Int'l Airport >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low priority >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44459800-805a9200-a5d0-11e8-90bd-c50be1831899.png)
