### ISSUE TITLE
KGFL-Floyd Bennett Memorial Airport-NEW YORK-USA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#2989]
# Airport Name

< Floyd Bennett Memorial Airport >

# Country?

< USA >

# Improvements that need to be made?

< Remade >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45787665-09023780-bc3c-11e8-8e47-46010232f053.png)
