### ISSUE TITLE
EGSX

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#299]
Minimal lines on this one. Not a high priority
Image: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=EGSX

**Comment by Carsontomato** [comment]
I'll work on this one

**Comment by kilt46** [comment]
Airport redrawn

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20037567/c1428e90-a3e7-11e6-9306-75d18bda7371.png)
