### ISSUE TITLE
SVBC-Barcelona Airport-ANZOATEGUI-VENEZUELA

### ISSUE THREAD

**Issue by JonathanPrecise** [InfiniteFlightAirportEditing/Airports#2990]
# Airport Name

General José Antonio Anzoátegui International Airport

# Country?

Venezuela

# Improvements that need to be made?

Will be redone from scratch.

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

None

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by MBeringuy** [comment]
I will edit this airport.
