### ISSUE TITLE
SBNF-Navegantes/Min Victor Konder Airport-SANTA CATARINA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#2991]
# Airport Name

< Navegantes, Ministro Victor Konder Intl Airport >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low priority >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44755141-78c44d00-aaea-11e8-85f1-58700e2b40ea.png)
