### ISSUE TITLE
FSSB-Bird Island Airport-BIRD ISLAND-SEYCHELLES 

### ISSUE THREAD

**Issue by Nickm45** [InfiniteFlightAirportEditing/Airports#2992]
# Airport Name

Bird Island

# Country?

Seychelles

# Improvements that need to be made?

New created form scratch

# Are you working on this airport?

yes

# Airport Priority? (A380, 10000ft+ Runway)

< Enter text here >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44757700-0b1e1e00-aaf6-11e8-8d61-60dd4d537942.png)
