### ISSUE TITLE
HLLT-Tripoli International Airport-TARABULUS-LIBYA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#2994]
# Airport Name

< Tripoli Intl Airport >

# Country?

< Libya >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< 10000ft+ Runway >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44817582-7aa21500-abab-11e8-9830-4c1fee15d670.png)
