### ISSUE TITLE
EGHQ-Newquay Airport-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#3]

**Comment by JohnPreston21** [comment]
I would like to edit this one

**Comment by JohnPreston21** [comment]
Wasn't able to edit this one. too big for now

**Comment by dushyants19** [comment]
Done, edited by. Approved by Jonathan

**Comment by dushyants19** [comment]
Gated by @kilt46

**Comment by dushyants19** [comment]
Invalid

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20455580/cc3058fe-ae24-11e6-8a09-62112d4d1e2e.png)
