### ISSUE TITLE
MMTJ-Tijuana Airport-BAJA CALIFORNIA-MEXICO

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#30]

**Comment by dushyants19** [comment]
https://community.infinite-flight.com/t/missing-taxiline-at-mmtj/54939/25?u=dush19

**Comment by henrikbg** [comment]
https://community.infinite-flight.com/t/mmtj-taxiway-inside-runway/56668?u=henrik

**Comment by dushyants19** [comment]
`cb5257e

**Comment by dushyants19** [comment]
missing new recently opened taxiway ~ @Epadilla1

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33525091-f0893e84-d7ed-11e7-8796-156047f0c238.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/72397493-d167aa80-371e-11ea-9a26-09e8d44e23e4.jpg)
