### ISSUE TITLE
KAUS-Austin Bergstrom International Airport-TEXAS-USA

### ISSUE THREAD

**Issue by Swang007** [InfiniteFlightAirportEditing/Airports#300]
Austin Bergstrom International Airport. I call this one for when it comes out, nobody take it!

**Comment by HenrikBerg02** [comment]
If KAUS ever comes out, it'll probably come with the rest of the cities surrounding it Austin (KIAH, KSAT). If so, I'll take KIAH.

**Comment by Swang007** [comment]
In the world branch KAUS already exists. Looks pretty sweet in WED. I might make some changes and commit just so I can call it my own

**Comment by Swang007** [comment]
Okay it's not actually being redone yet but it will be priority for me once the time comes around

**Comment by kilt46** [comment]
This is NOT an issue

**Comment by NickArt1342** [comment]
@Swang007 Do you still want to this one?

**Comment by Swang007** [comment]
@NickArt1342 It's basically already done. I checked with WEDBing, the airport is aligned, everything else is there. It doesn't need to be redone. I'll commit anyway in case I did make any changes.

**Comment by samuelandersson** [comment]
What are you doing with this one @kilt46?

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18608000/8a58dfc2-7ca2-11e6-91cf-7929c8658e2c.png)

**Comment by kilt46** [comment]
This airport is made up from many apron strips. Would ideally need redone

**Comment by brunocr98** [comment]
I'd like to redo this then.

**Comment by brunocr98** [comment]
Unfortunately I won't have time to redo this airport, things have turned complicated lately. Sorry.

**Comment by brunocr98** [comment]
I'll retake it again, problems solved.

**Comment by brunocr98** [comment]
Renovated

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24636010/c25cfe76-189c-11e7-8bea-33551f2f9023.png)

**Comment by MrMrMan** [comment]
I'll add app/dep frequencies for Paul

**Comment by MrMrMan** [comment]
added freqs, sent in

**Comment by brunocr98** [comment]
The airport needs redo to handle E-size jets. I'm no longer updating/supporting this airport so I'll leave this to whoever wants it.

**Comment by HiFlyerBwi** [comment]
Submitted for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/62655796-25cd5980-b939-11e9-91d2-2ec245d54549.jpg)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78706514-958b4e00-78e5-11ea-9cfe-10b6871d0a2e.jpg)
