### ISSUE TITLE
OAYQ-Yangi Qaleh Airport-TAKHAR-AFGHANISTAN

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#3000]
# Airport Name

< Enter text here >

# Country?

< Enter text here >

# Improvements that need to be made?

< Enter text here >

# Are you working on this airport?

< Enter text here >

# Airport Priority? (A380, 10000ft+ Runway)

< Enter text here >

**Comment by MajorTomMueller** [comment]
![OAYQ](https://user-images.githubusercontent.com/26853210/54474749-e87cf980-47e8-11e9-87f2-5df742431df3.jpg)
