### ISSUE TITLE
OAYW-Yawan Airport-BADAKHSHAN-AFGHANISTAN

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#3001]
# Airport Name

< Enter text here >

# Country?

< Enter text here >

# Improvements that need to be made?

< Enter text here >

# Are you working on this airport?

< Enter text here >

# Airport Priority? (A380, 10000ft+ Runway)

< Enter text here >

**Comment by MajorTomMueller** [comment]
![OAYW](https://user-images.githubusercontent.com/26853210/54475246-7c51c400-47ef-11e9-99e5-276a4a51f729.jpg)
