### ISSUE TITLE
SBLE-Lencois/Horacio de Mattos Airport-BAHIA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3002]
# Airport Name

Lençois, Horacio de Mattos Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44757014-8087ef80-aaf2-11e8-981b-5ea525722ba3.png)
