### ISSUE TITLE
CYCB-Cambridge Bay Airport-NUNAVUT-CANADA

### ISSUE THREAD

**Issue by alexpeterson-if** [InfiniteFlightAirportEditing/Airports#3006]
# Airport Name

Cambridge Bay Airport

# Country?

Canada

# Improvements that need to be made?

Done from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44617715-87caa700-a82d-11e8-8ecd-5595f654d435.png)
