### ISSUE TITLE
LIBP-Pescara Airport-ABRUZZO-ITALY

### ISSUE THREAD

**Issue by johanneskkl** [InfiniteFlightAirportEditing/Airports#3022]
# Airport Name
Pescara 

# Country?

Italy

# Improvements that need to be made?

Redo

# Are you working on this airport?
Yes

# Airport Priority? (A380, 10000ft+ Runway)
no

**Comment by kilt46** [comment]
Suggested spawn positions (Several GAs missing!) Also cargo area has different numbering
![image](https://user-images.githubusercontent.com/14023167/45242702-a5305400-b2b6-11e8-950a-66fd063042e0.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45460720-e5cc0b00-b6c4-11e8-965b-0d9f9dfd65cc.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/67235492-91de3a80-f41d-11e9-8af3-ac272459728a.jpg)
