### ISSUE TITLE
EBLG-Liege Airport-WALLONIE-BELGIUM

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#303]
Bravo Airport: Needs more detail

**Comment by kilt46** [comment]
This one was completed

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20038897/e3066aec-a400-11e6-964a-77141e65be59.png)

**Comment by moritzbabl** [comment]
Runway numbers change back in 2017 - now 04s/22s

http://www.ead.eurocontrol.int/eadbasic/pamslight-B4A53CF611E93955E79C9F5C1487992E/UW2XZDUJH55X2/EN/Charts/AD/NON_AIRAC/EB_AD_2_EBLG_ADC_01_en_2018-04-26.pdf

**Comment by moritzbabl** [comment]
turned out to require a major redo e.g. for incorrect curving

**Comment by MajorTomMueller** [comment]
redone to latest stand of guidelines, sat imagery, and AIP.
![EBLG-git](https://user-images.githubusercontent.com/26853210/54755528-6294f000-4be6-11e9-8a63-f412a9046c6e.jpg)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54878713-731fb300-4dfe-11e9-85e5-add2fc40f9b3.png)
