### ISSUE TITLE
SAWG-Rio Gallegos Airport-SANTA CRUZ-ARGENTINA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3033]
# Airport Name

Rio Gallegos, Piloto Civil N Fernandez Airport

# Country?

Argentina

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

10000ft+ Runway

**Comment by MBeringuy** [comment]
Waiting for PR analysis.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44957314-a3215c00-ae96-11e8-8d4b-0892bcd811fd.png)
