### ISSUE TITLE
KOQN-Brandywine Airport-PENNSYLVANIA-USA

### ISSUE THREAD

**Issue by tomthetank46** [InfiniteFlightAirportEditing/Airports#3037]
# Airport Name

Brandywine Airport

# Country?

United States

# Improvements that need to be made?

Will be redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

None

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45128723-2a93f700-b145-11e8-9a98-fcb5943417de.png)
