### ISSUE TITLE
SWPI-Parintins Airport-AMAZONAS-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3039]
# Airport Name

Parintins Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by MBeringuy** [comment]
Waiting for PR analysis.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44957193-f0043300-ae94-11e8-8d17-a19f52b24c24.png)
