### ISSUE TITLE
KMKE-General Mitchell International Airport-WISCONSIN-USA

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#304]

**Comment by kilt46** [comment]
Complete airport redesign

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17277117/fbe969d0-5700-11e6-8203-8833e9b4c768.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17826851/978f21c0-663a-11e6-9df1-de5dcf4243b9.png)
TERMINAL
![image](https://cloud.githubusercontent.com/assets/14023167/17826856/a4ec0342-663a-11e6-8245-9b1caf790cd1.png)
MILITARY A
![image](https://cloud.githubusercontent.com/assets/14023167/17826862/b16bc800-663a-11e6-84a8-e13a3478a3af.png)
MILITARY B/C
![image](https://cloud.githubusercontent.com/assets/14023167/17826869/bd6f6c9c-663a-11e6-874c-a70406279abf.png)
CARGO
![image](https://cloud.githubusercontent.com/assets/14023167/17826881/c90dd0ac-663a-11e6-8fe9-f01e31f2f0d4.png)

**Comment by kilt46** [comment]
- Removal of buildings
- Correct asphalt taxiway shoulders
- Adding hangar spawns
- Redrawing most curves

**Comment by Czechoslovaki** [comment]
Sent For OR
