### ISSUE TITLE
SBSN-Santarem International Airport-PARA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3041]
# Airport Name

Santarem, Maestro Wilson Fonseca Intl Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by MBeringuy** [comment]
Waiting for PR analysis.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44957794-c00c5e00-ae9b-11e8-9ebb-856d921c9186.png)
