### ISSUE TITLE
SBVT-Eurico De Aguiar Salles Airport-ESPIRITO SANTO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3045]
# Airport Name

Vitoria, Eurico de Aguiar Salles Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/49410720-aa713380-f72b-11e8-973f-f59099234cea.png)
