### ISSUE TITLE
EGTC-Cranfield Airport-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by henrikbg** [InfiniteFlightAirportEditing/Airports#305]
Redoing EGTC.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20037577/f877a3f0-a3e7-11e6-836a-baeb5ae38ec1.png)

**Comment by ItsW1ll** [comment]
Grass runways no longer in use plus some boundary changes needed

**Comment by ItsW1ll** [comment]
Added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46924489-ee2ca400-cfea-11e8-88e1-8be129c8b69f.png)
