### ISSUE TITLE
EYKS-Aleksotas Airport-KAUNAS-LITHUANIA

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#3050]
# Improvements that need to be made?
Boundary Fix

**Comment by MajorTomMueller** [comment]
http://eaip.eans.ee/Initial/html/eAIP/EE-AD-2.EEKE-en-GB.html#EEKE-ADC

**Comment by jackyboy2578** [comment]
Could I be assigned to this please

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/77345546-874d0780-6d13-11ea-9c9e-f5aa643ed677.jpg)
