### ISSUE TITLE
SBFL-Hercilio Luz Airport-SANTA CATARINA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3057]
# Airport Name

Florianopolis, Hercilio Luz Intl Aiport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
Requires new terminal and taxiways added

**Comment by 2000rpm** [comment]
[SBFL PARKING SPOTS 2020 APR 17.pdf](https://github.com/InfiniteFlightAirportEditing/Airports/files/4775748/SBFL.PARKING.SPOTS.2020.APR.17.pdf)

**Comment by MajorTomMueller** [comment]
Sorry, @kilt46 , @FellipeEdu is already assigned to 3 issues. Ryan asked us to enforce the 3 issue threshold, there is no exemptions anymore.

**Comment by MajorTomMueller** [comment]
@FellipeEdu ;-)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/85931719-d79cae00-b89c-11ea-9df4-bdaa52393f22.jpg)
