### ISSUE TITLE
OIFM-Esfahan Airport-ESFAHAN-IRAN

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Airports#306]
Please redesign me

**Comment by PaulNielsen** [comment]
I will try to redo this airport! :)

**Comment by dushyants19** [comment]
@kilt46 this airport doesnt get A380s

**Comment by PaulNielsen** [comment]
Maybe he added it because so we will get a good network all over the world with kind of big airports :)

**Comment by PaulNielsen** [comment]
Awaiting approval! :)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18497306/be447768-79f2-11e6-9b55-03fd421c007f.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18497311/c82cbc68-79f2-11e6-95dd-b26ed338c5c3.png)
