### ISSUE TITLE
08ME-Lindbergh Airstrip-MAINE-USA

### ISSUE THREAD

**Issue by RyanEpps** [InfiniteFlightAirportEditing/Airports#3061]

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44956258-ce9c4a80-ae86-11e8-8176-121d58bd096a.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44956280-2d61c400-ae87-11e8-8274-422f4491963d.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44963676-b7467700-aef1-11e8-958d-7e73f4601dfc.png)
