### ISSUE TITLE
KOLD-Dewitt Field Old Town Municipal Airport-MAINE-USA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3076]
# Airport Name

< Dewitt Field Old Town Municipal >

# Country?

< USA >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by Balloonchaser** [comment]
Sent for OR. Thanks Nathan for the great PR! :)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45788195-aeb6a600-bc3e-11e8-949c-f923c730d101.png)
