### ISSUE TITLE
KAST-Astoria Regional Airport-OREGON-USA

### ISSUE THREAD

**Issue by henrikbg** [InfiniteFlightAirportEditing/Airports#308]
I'll take this one on.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20373994/2cf1c998-ac3b-11e6-8474-189cfd4a14ce.png)

**Comment by Czechoslovaki** [comment]
![image](https://user-images.githubusercontent.com/51279558/96957738-52bf4b00-14b0-11eb-9cac-66c8235e668d.png)
