### ISSUE TITLE
SAVC-Comodoro Rivadavia Airport-CHUBUT-ARGENTINA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3081]
# Airport Name

Comodoro Rivadavia, Gen Henrique Mosconi Airport

# Country?

Argentina

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45126944-7fcb0b00-b13b-11e8-8d98-c6c6cc905b36.png)
