### ISSUE TITLE
 SBJD-Jundiai Airport-SAO PAULO-BRAZIL

### ISSUE THREAD

**Issue by IFBR0006** [InfiniteFlightAirportEditing/Airports#3086]
# Airport Name

< Jundiai Airport>

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low priority >

**Comment by IFBR0006** [comment]
Hey Bruno! I had not seen that you had corrected the name. Sorry!

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by IFBR0006** [comment]
het ryan! I'm still working at this airport.

Em seg, 19 de nov de 2018 22:53, RyanEpps <notifications@github.com>
escreveu:

**Comment by RyanEpps** [comment]
Okay. I'll reactivate you. Be sure to check slack periodically for news on member cleanups in the future!

**Comment by IFBR0006** [comment]
right!

Em seg, 19 de nov de 2018 22:57, RyanEpps <notifications@github.com>
escreveu:

**Comment by RyanEpps** [comment]
Member inactive, up for grabs

**Comment by MBeringuy** [comment]
I'm catching this airport.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55669582-c4886300-583e-11e9-945c-ca0458f40e5a.png)
