### ISSUE TITLE
KIAH-George Bush Intercontinental Airport-TEXAS-USA

### ISSUE THREAD

**Issue by henrikbg** [InfiniteFlightAirportEditing/Airports#309]
I'll do this one if it ever comes out. Don't take it.

**Comment by dushyants19** [comment]
:joy: I want Doha then :joy:

**Comment by HenrikBerg02** [comment]
Make a new issue ;)

**Comment by kilt46** [comment]
This is NOT an issue

**Comment by henrikbg** [comment]
I'm going to actually start working on this now.

**Comment by IFAEpat** [comment]
Are you still working @henrikbg ?

**Comment by henrikbg** [comment]
Yes, I am. :) Here's the progress...

![screen shot 2016-07-20 at 11 06 21 am](https://cloud.githubusercontent.com/assets/14116830/16981269/1f922f88-4e6a-11e6-971c-c6c4378fbb62.png)

**Comment by dushyants19** [comment]
Pat hows this goin

**Comment by IFAEpat** [comment]
@dushyants19 almost done, just been having computer issues lately.

**Comment by brunocr98** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25207827/934e302c-2536-11e7-90ac-d6629f8b2dfb.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/58843355-81811b00-8648-11e9-8b78-e42d83602f75.jpg)
