### ISSUE TITLE
SNJM-Manhuacu Airport-MINAS GERAIS-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3090]
# Airport Name

Manhuacu, Elias Breder Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45061942-4a0b2100-b06c-11e8-973c-54dffa62fcab.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/61917765-24f1fc00-af25-11e9-9ece-3a6e585e4938.jpg)
