### ISSUE TITLE
SBLO-Londrina Airport-PARANA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3091]
# Airport Name

Londrina, Governador Jose Richa Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45243204-89c64880-b2b8-11e8-8b29-f4da1d3a7ee7.png)
