### ISSUE TITLE
KMDW-Chicago Midway International Airport-ILLINOIS-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#31]

**Comment by HenrikBerg02** [comment]
Redoing KMDW

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17277106/a983a304-5700-11e6-8578-ced0bbe1c443.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17831494/ed4a63a2-66af-11e6-8262-6087ae1bcb57.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17831495/f5b36886-66af-11e6-9c41-e9cae673a866.png)

**Comment by jakey200** [comment]
Sent for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/83969463-cbbd5d80-a895-11ea-9fd4-481763ab37d1.png)
