### ISSUE TITLE
EHRD- Rotterdam Airport-ZUID-HOLLAND-NETHERLANDS

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#310]
This airport could do with a refresh if anyone is willing

**Comment by Zimnaan** [comment]
What needs to be done?

**Comment by IceBlue02** [comment]
@Zimnaan have you done this yet? Or can we free it up for someone else?

**Comment by Zimnaan** [comment]
@iceblue02,yeah you can free it up for someone else.

**Comment by IceBlue02** [comment]
And boom, he pounces.

Thanks @Zimnaan.

**Comment by Zimnaan** [comment]
No problem

**Comment by IceBlue02** [comment]
Finished, PRed and will send in now.

**Comment by henrikbg** [comment]
Accepted.

**Comment by dushyants19** [comment]
Jan wants to edit minor things over here

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20245399/389e37fe-a966-11e6-9b43-5bc477cc2620.png)

**Comment by kilt46** [comment]
MAIN APRON GATES ALIGNED
![image](https://user-images.githubusercontent.com/14023167/52179116-d9dc0500-279b-11e9-9474-589ffda0270e.png)
