### ISSUE TITLE
RJOZ-Ozuki Airbase-YAMAGUCHI-JAPAN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#3104]
# Airport Name

< Ozuki Airbase >

# Country?

< JAPAN >

# Improvements that need to be made?

< redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45194839-6c42a180-b21a-11e8-9008-ea8d9ac62804.png)
