### ISSUE TITLE
KTEB-Teterboro Airport-NEW JERSEY-USA

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Airports#311]
Redoing, graphics look blocky and taxiways are not properly aligned with real life.

**Comment by samuelandersson** [comment]
Done and approved.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20251748/6a464db6-a9e1-11e6-97fc-ff7339b2db3b.png)

**Comment by RyanEpps** [comment]
Airport needs reworked up to new standards and additional spawns.

**Comment by ChrisLevet232** [comment]
I would like to take this one. Can someone send me the latest apt.dat ?

**Comment by ChrisLevet232** [comment]
![kteb snip 3](https://user-images.githubusercontent.com/30371438/45710932-1f35c800-bb56-11e8-83e0-b2bcee1cae7d.PNG)
![kteb snip 2](https://user-images.githubusercontent.com/30371438/45710933-1f35c800-bb56-11e8-8d93-148695d42a2d.PNG)
![kteb snip 1](https://user-images.githubusercontent.com/30371438/45710935-1f35c800-bb56-11e8-9fe8-83df055a02b0.PNG)
Removed buildings, holes, updated lighting and markings. Added numerous GA spawns. 
Sent in for review.

**Comment by kilt46** [comment]
Duplicate spawns removed
