### ISSUE TITLE
LGKC-Kithira Airport-PELOPONNISOS-GREECE

### ISSUE THREAD

**Issue by Moonlit21** [InfiniteFlightAirportEditing/Airports#3112]
# Airport Name

< LGKC - Kithira Island National Airport >

# Country?

< Greece >

# Improvements that need to be made?

< Complete rework >

# Are you working on this airport?

< Affirm >

# Airport Priority? (A380, 10000ft+ Runway)

< Low priority >

Small airport, I would like to begin on this during the weekend.

**Comment by Moonlit21** [comment]
Sent in for review

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46265314-dc2b0b80-c4ea-11e8-920d-1e455b304d63.png)

**Comment by orangejuicie** [comment]
Reversing edge lights.
