### ISSUE TITLE
KTPF

### ISSUE THREAD

**Issue by dushyants19** [InfiniteFlightAirportEditing/Airports#312]
Doing a Quick redo, SoFlo

**Comment by kilt46** [comment]
Completed by Dush19

**Comment by dushyants19** [comment]
Gated in 4acf7872708506433703114766ae1851bfa6926d

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19253569/b468f4ce-8f11-11e6-9cd1-b3f4e56c098a.png)
