### ISSUE TITLE
HLLB-Benghazi International Airport-CIRENAICA-LIBYA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3123]
# Airport Name

Benghazi, Benina Intl Airport

# Country?

Libya

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

GP2 (+10k)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45520791-9a773280-b780-11e8-9b73-5de60d20a21b.png)
