### ISSUE TITLE
OARZ-Razer Airport-BADAKHASAN-AFGHANISTAN

### ISSUE THREAD

**Issue by LeonVeen** [InfiniteFlightAirportEditing/Airports#3128]
♻️

**Comment by LeonVeen** [comment]
As of early 2018, ramps and taxiways at HTKJ were extended, and a new taxiway parallel to the runway has been built, together with a new maintenance ramp

**Comment by LeonVeen** [comment]
I would like to do this one.

**Comment by johanneskkl** [comment]
This is still a duplicate. You have to ask a supervisor to reopen that for You, writing what you wrote here(design changes)

**Comment by brunocr98** [comment]
Search, search, search!!!! #1465

**Comment by MajorTomMueller** [comment]
![OARZ](https://user-images.githubusercontent.com/26853210/54476403-313ead80-47fd-11e9-8479-6f392ef9ec9d.jpg)

**Comment by kilt46** [comment]
Looks like wrong airport loaded
![image](https://user-images.githubusercontent.com/14023167/54479667-2419c280-47ed-11e9-91c2-2b5152062e11.png)

**Comment by MajorTomMueller** [comment]
Ups, will correct when I am back to my PC

**Comment by MajorTomMueller** [comment]
correct file uploaded
