### ISSUE TITLE
FAMM-Mafikeng International Airport-NORTH WEST-SOUTH AFRICA

### ISSUE THREAD

**Issue by DS2001** [InfiniteFlightAirportEditing/Airports#313]
REUSED

**Comment by dushyants19** [comment]
@DS2001 check https://github.com/InfiniteFlightAirportEditing/Airports/issues/107 

Reopen it.

**Comment by samuelandersson** [comment]
I'll continue this one when I get home from vacation.

**Comment by samuelandersson** [comment]
Done :) 

A whole redone was needed.

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/ced7f24cdb96979863814c22d142858395a4f6de)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18815701/946aef58-82fd-11e6-8f31-f46ca7dced6a.png)
