### ISSUE TITLE
OARG-Uruzgan Airfield-UROZGAN-AFGHANISTAN

### ISSUE THREAD

**Issue by cade-norris** [InfiniteFlightAirportEditing/Airports#3131]
# Airport Name

Autauga County Airport
 Prattville-Grouby Field

# Country?

United States

# Improvements that need to be made?

Rework

# Are you working on this airport?
Yes

# Airport Priority? (A380, 10000ft+ Runway)

no

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by coxiebay** [comment]
I would like to do this Airport

**Comment by IQ3milionen** [comment]
I edit this airport now.

**Comment by MajorTomMueller** [comment]
![OARG](https://user-images.githubusercontent.com/26853210/54478486-f778a180-4812-11e9-92c6-7bedb97c8269.jpg)
