### ISSUE TITLE
KISM-Kissimmee Gateway Airport-FLORIDA-USA

### ISSUE THREAD

**Issue by tomthetank46** [InfiniteFlightAirportEditing/Airports#3132]
# Airport Name

Kissimmee Gateway Airport

# Country?

USA

# Improvements that need to be made?

Redone frome scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

None

**Comment by MajorTomMueller** [comment]
@tomthetank46 still working on this one? It is the „oldest“ of the open ones

**Comment by tomthetank46** [comment]
That's not a title I want... I have a good portion done (pavement, lines, lights), just need to do spawns. I've been side tracked lately but will prioritize this.

**Comment by tomthetank46** [comment]
Sent to PR! @MajorTomMueller

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/94748683-74ad2e00-0347-11eb-9179-bcbb7ba3be3b.png)
