### ISSUE TITLE
LLSD-Tel Aviv Sde Dov Airport-TEL AVIV-ISRAEL

### ISSUE THREAD

**Issue by royfr83** [InfiniteFlightAirportEditing/Airports#3139]
# Airport Name

Sde Dov Tel Aviv

# Country?

Israel

# Improvements that need to be made?

Will be remade from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

None

**Comment by royfr83** [comment]
Status update:

Airport is more complicated than initially expected, due to unanticipated several military aprons. 

Currently ~70% of the work is done, I aim to finish by the end of November.

**Comment by kilt46** [comment]
Please review chart and validate against submission
![image](https://user-images.githubusercontent.com/14023167/49837594-91403680-fd6c-11e8-8a8d-c8ade20e53f6.png)

**Comment by royfr83** [comment]
The above chart was issued 1 month ago. I used the older layout that match the satellite imagery.
Please see:

https://airportediting.slack.com/archives/C0DUAMF46/p1543844345016000

@kilt46 @brunocr98

**Comment by royfr83** [comment]
Following my conversation with Kilt, appreciate if a manager remove all labels and close the issue again.
Thank you.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50195469-d2a08b00-0304-11e9-8ffe-ec89f72ae2f6.png)
