### ISSUE TITLE
KPAE- Snohomish County (Paine Field) Airport-WASHINGTON-USA

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#314]
This airpot hasn't been redone since 10 months and since it's the boeing field it should be freshend up :D

**Comment by IceBlue02** [comment]
Thought I saw someone was doing this on the forum. If not, I will take.

**Comment by samuelandersson** [comment]
I was kind of into it. But as I said it's a big project and it has a working prototype right now. You can take it, if you don't get enough time. I might help you out :+1:

**Comment by HenrikBerg02** [comment]
I'll take on this one.

**Comment by IceBlue02** [comment]
CaptainDJ sent me some pics and stuff on the forum, I'll add you in to the PM

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20414089/566cdfcc-acf6-11e6-9e18-5d72a36b1d9b.png)

**Comment by kilt46** [comment]
Several of the hold lines were backwards. Now fixed

**Comment by Czechoslovaki** [comment]
It's time to take this out of the trash.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101244101-062f7800-36ca-11eb-8798-e0e44c6d0c4a.png)
