### ISSUE TITLE
SBCH-Chapeco Airport-SANTA CATARINA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3140]
# Airport Name

Chapeco Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
Suggested Gate Configuration
![image](https://user-images.githubusercontent.com/14023167/45458565-d85d5380-b6b9-11e8-8bdf-cbb7da406907.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45577009-95c58380-b83f-11e8-8bff-4fb1e9914d02.png)
