### ISSUE TITLE
LIMG-Albenga Clemente Panero Airport-LIGURIA-ITALY

### ISSUE THREAD

**Issue by johanneskkl** [InfiniteFlightAirportEditing/Airports#3141]
# Airport Name
Albenga

# Country?

liguria, italy

# Improvements that need to be made?

edit

# Are you working on this airport?

yes. I don´t spam issues 

# Airport Priority? (A380, 10000ft+ Runway)
no

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45458691-59b4e600-b6ba-11e8-9492-f4f767b67ea2.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68996536-23549700-087a-11ea-9e32-2de68f6b5a8c.jpg)
