### ISSUE TITLE
KRVS-Richard Lloyd Jones Jr Airport-OKLAHOMA-USA

### ISSUE THREAD

**Issue by RyanEpps** [InfiniteFlightAirportEditing/Airports#3143]
Needs full redo.

**Comment by ChrisLevet232** [comment]
Almost done this one. Finishing up spawn names and some hangar floors.

![krvs](https://user-images.githubusercontent.com/30371438/50604959-be28ca80-0e8e-11e9-9ba2-b2b767455993.PNG)

**Comment by ChrisLevet232** [comment]
Sent in to OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53681450-643a5a80-3caf-11e9-9126-0d90311a66fd.png)
