### ISSUE TITLE
KFFZ-Falcon Field Airport-ARIZONA-USA

### ISSUE THREAD

**Issue by RyanEpps** [InfiniteFlightAirportEditing/Airports#3144]
Needs full redo.

**Comment by tomthetank46** [comment]
I'd like to redo this airport.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46700004-3873e680-cbe1-11e8-91d9-2142396e6b55.png)

**Comment by kilt46** [comment]
Duplicate spawns removed
