### ISSUE TITLE
KDVT-Phoenix Deer Valley Airport-ARIZONA-USA

### ISSUE THREAD

**Issue by RyanEpps** [InfiniteFlightAirportEditing/Airports#3145]
Needs full redo.

**Comment by johanneskkl** [comment]
I will do this

**Comment by johanneskkl** [comment]
Need to finish spawns and taxilines. 
I have been busy with school, if someone wants to take over feel free, but I want to stay in the team

**Comment by tomthetank46** [comment]
I can take this over if still needed

**Comment by tomthetank46** [comment]
Sent for OR a a couple days ago. Never drawing a spawn again.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/75924942-95abb000-5e46-11ea-8d17-48925d7dd1e3.jpg)

**Comment by MajorTomMueller** [comment]
Duplicate spawn names:
https://gist.github.com/carmichaelalonso/652d032d7fe3683cbf8d88365ff5a690

**Comment by MajorTomMueller** [comment]
@tomthetank46 are you going to fix this? They are still there in latest error file. Disregard when you have send to OR already

**Comment by MajorTomMueller** [comment]
Still piped up in latest error file.

**Comment by MajorTomMueller** [comment]
Still in last error list:
https://gist.github.com/carmichaelalonso/bd54fd4eec434da4905cc6633b9a73a3

**Comment by MBeringuy** [comment]
Duplicate spawns fixed.
