### ISSUE TITLE
KDWH-David Wayne Hooks Memorial Airport-TEXAS-USA

### ISSUE THREAD

**Issue by RyanEpps** [InfiniteFlightAirportEditing/Airports#3147]
Needs full redo.

**Comment by Clocktapus** [comment]
I'll do this

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by cfvfd104** [comment]
This still up for grabs? Local airport for me and willing to redo.

**Comment by MajorTomMueller** [comment]
Hello @cfvfd104 I haven’t found you in our slack channel, and I couldn’t find any Airport you edited so far. Have already joint the team as advised in the IFC thread „how to start with airport editing“? The airport you selected has a very cluttered GA Hangar area making it extremely time consuming for beginners. SomIf you have joint slack and was still willing to do lots of nifty little hangar on your first airport, or if I have missed something by searching, let us know and you will be assigned.

**Comment by cfvfd104** [comment]
Hey Tom, I will send you a message on Slack right now. I returned to active status recently.

**Comment by Matt1093** [comment]
I'm a beginner but can I do this one?

**Comment by IFsami** [comment]
I can do this

**Comment by OscarConklin** [comment]
Sent for OR!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/98440215-29f8a180-20bd-11eb-839c-dc1f67d20f12.png)
