### ISSUE TITLE
KFRG-Republic Airport-NEW YORK-USA

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#315]
This one is really messed up. Needs to be done from scratch. High Priority! Lines are wrong type

**Comment by Swang007** [comment]
https://community.infinite-flight.com/t/incorrect-airport-layout-at-kfrg/18692/1

Hopefully this can get pushed in the next update. Nice job @HenrikBerg02

**Comment by IFAEpat** [comment]
Runway needs to be rotated, 01 is facing ≈190˚ instead of ≈10˚ and vice versa

![img_8806](https://cloud.githubusercontent.com/assets/18223248/17653366/609f5490-6262-11e6-93c9-66d7a263a112.PNG)

**Comment by IFAEpat** [comment]
Rotated

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17760954/f75ff20a-64c8-11e6-8a35-041983d41272.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17760967/149ddecc-64c9-11e6-89d1-6795ab8b6547.png)

**Comment by RyanEpps** [comment]
Airport needs reworked up to new standards and additional spawns.

**Comment by andreycronenwett** [comment]
I can rework it if you'd like

**Comment by RyanEpps** [comment]
Hello! Please send an email to contact@airportediting.com to get started. Also note that this airport is pretty large, so we'd recommend you practice on a smaller airport first. Thanks for you interest!

**Comment by andreycronenwett** [comment]
Ok I applied via the website, should I still email?. I done this sort of stuff before with x-plane so I will let you know if it's too much if you are ok with me working on it

**Comment by RyanEpps** [comment]
If you think you can handle it, go for it. Applications take a little bit to show up in our inbox, so you should be good. Good luck.

**Comment by andreycronenwett** [comment]
Finished, sent off an email

**Comment by Balloonchaser** [comment]
I'll take this

**Comment by Balloonchaser** [comment]
Sent in for OR! :)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55684643-287c5b80-5913-11e9-9591-508ecb712c0d.png)
