### ISSUE TITLE
SBUF-Paulo Afonso Airport-BAHIA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3151]
# Airport Name

Paulo Afonso Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45597827-16e35e80-b997-11e8-9684-53925eccb192.png)

**Comment by MBeringuy** [comment]
@kilt46 this needs to be cataloged.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107769895-3f095000-6cfe-11eb-88bd-407f0e1aef61.png)
