### ISSUE TITLE
LGKJ-Kastelorizo Airport-NOTIO AIGAIO-GREECE

### ISSUE THREAD

**Issue by Moonlit21** [InfiniteFlightAirportEditing/Airports#3152]
# Airport Name

Kastellorizo Island Airport

# Country?

Greece

# Improvements that need to be made?

Remade from scratch (the airport does not exist in IF yet)

# Are you working on this airport?

Affirmative

# Airport Priority? (A380, 10000ft+ Runway)

Low Priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46918149-e42b8680-cf93-11e8-9af2-8d77ce5823b1.png)
