### ISSUE TITLE
RKJJ-Gwangju Airport-GWANGJU-SOUTH KOREA

### ISSUE THREAD

**Issue by Session-IFK** [InfiniteFlightAirportEditing/Airports#3156]
# Airport Name

Gwangju Airport 

# Country?

South Korea

# Improvements that need to be made?

redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Nothing

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/47258543-3ec85500-d462-11e8-9f9e-e3df6bbf8c6f.png)
