### ISSUE TITLE
CYPS-Pemberton Airport-BRITISH COLUMBIA-Canada

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3159]
# Airport Name

< Pemberton Airport >

# Country?

< Canada >

# Improvements that need to be made?

< Redone From Scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None (General Aviation) >

**Comment by Balloonchaser** [comment]
Sent in for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45855934-04ab4c80-bd18-11e8-9db9-dc0917a88683.png)
