### ISSUE TITLE
KSWF-Stewart International Airport-NEW YORK-USA

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#316]
Redoing Airport to include Terminal Buildings

**Comment by kilt46** [comment]
Airport redone

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20414770/d96f2558-acf9-11e6-9da4-e383bfa84bcb.png)

**Comment by ECoops-123** [comment]
Airport needs updating, several new taxiways and several removed as well as missing markings everywhere. I'll work on this.

**Comment by ECoops-123** [comment]
![Full](https://user-images.githubusercontent.com/59462519/113275140-5d3f0580-92d6-11eb-93e5-60fe8faedb33.png)
