### ISSUE TITLE
CYSE-Squamish Airport-BRITISH COLUMBIA-Canada

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3162]
# Airport Name

< Squamish Airport >

# Country?

< Canada >

# Improvements that need to be made?

< Airport Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None (General Aviation) >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45856078-9ca93600-bd18-11e8-81ea-e64b6fea51db.png)
