### ISSUE TITLE
PHJH-Kapalua Airport-HAWAII-USA

### ISSUE THREAD

**Issue by ItsW1ll** [InfiniteFlightAirportEditing/Airports#3168]
# Airport Name

Kapalua

# Country?

Hawaii-USA

# Improvements that need to be made?

Full redo

# Are you working on this airport?

yes

# Airport Priority? (A380, 10000ft+ Runway)

none

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45910646-78a92b80-bdd0-11e8-9ff0-9b1b8139563f.png)
