### ISSUE TITLE
KVBG-Vandenberg AFB Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Airports#317]
REUSED

**Comment by samuelandersson** [comment]
After closer inspection this airport is no longer in need of any redo.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25995982/71d718b8-36da-11e7-8ef6-417c09e7c099.png)
