### ISSUE TITLE
PHDH- Dillingham Airfield Airport-HAWAII-USA

### ISSUE THREAD

**Issue by henrikbg** [InfiniteFlightAirportEditing/Airports#318]
Did this one but forgot to make an issue.

**Comment by dushyants19** [comment]
Removing Hold Short spawn points

**Comment by dushyants19** [comment]
Removed and into the repo. Approved by Jonathan

**Comment by dushyants19** [comment]
Misalinged badly and Bing scenery isn't great. High priority

**Comment by IceBlue02** [comment]
I'll take :)

LAST SUGGESTION GONE!!! (For Now)

**Comment by IceBlue02** [comment]
Finished and going in for review.

**Comment by dushyants19** [comment]
@IceBlue02 did this get approved?

**Comment by IceBlue02** [comment]
Sorry about this mess. I committed back in mid june:
https://github.com/InfiniteFlightAirportEditing/Airports/commit/fb150fa91bd109965d1c43af8e80488dd28aaf30

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19413753/ba5fc594-92fc-11e6-866a-f29fedd32075.png)
