### ISSUE TITLE
FVHA-Harare International Airport-HARARE-ZIMBABWE

### ISSUE THREAD

**Issue by henrikbg** [InfiniteFlightAirportEditing/Airports#319]
REUSED

**Comment by HenrikBerg02** [comment]
This one is a duplicate, just don't mind this one.

**Comment by planemadnews** [comment]
Sent in for review

**Comment by planemadnews** [comment]
Sent for Review

**Comment by AxelBeder** [comment]
Added to repro.

**Comment by planemadnews** [comment]
wait, so its been committed?

**Comment by dushyants19** [comment]
Yes again, Caleb

**Comment by kilt46** [comment]
How did this ever get approved????
![image](https://cloud.githubusercontent.com/assets/14023167/20056402/8e06a862-a4ab-11e6-801b-13ec09ebdf88.png)

**Comment by kilt46** [comment]
This is simply junk!!!
![image](https://cloud.githubusercontent.com/assets/14023167/20056429/aa0f87fe-a4ab-11e6-963b-bcf26a1b2178.png)

**Comment by dushyants19** [comment]
@henrikbg do you just blindly approve airports?

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20059119/27352abe-a4ba-11e6-9058-79ab10bef696.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20059122/32c6ecb4-a4ba-11e6-9407-1637675b17ff.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20059134/3e24423c-a4ba-11e6-975b-f8c31b0082e1.png)
