### ISSUE TITLE
KRYY-Cobb County International-McCollum Field Airport-GEORGIA-USA

### ISSUE THREAD

**Issue by ChrisLevet232** [InfiniteFlightAirportEditing/Airports#3190]
# Airport Name

< Cobb County International Airport - McCollum Field >

# Country?

< USA >

# Improvements that need to be made?

< Needs to be redone from scratch; this airport has never been edited >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low Priority >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46440111-0e757c80-c728-11e8-9569-3b6bf4705de1.png)
