### ISSUE TITLE
SBBZ-Armacao dos Buzios Airport-RIO DE JANEIRO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3197]
# Airport Name

Armacao dos Buzios, Umberto Modiano Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45983799-d8e3db80-c023-11e8-8a78-87fe7c69c464.png)
