### ISSUE TITLE
KMTJ-Montrose Regional Airport-COLORADO-USA

### ISSUE THREAD

**Issue by henrikbg** [InfiniteFlightAirportEditing/Airports#322]

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17277375/f6887340-5706-11e6-8731-d95803860331.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17653640/40b6e96c-625e-11e6-9d32-876f40b1211a.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17653644/4859570e-625e-11e6-85b4-09a2f144d6e5.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17653645/4f3206d4-625e-11e6-8802-7e1b8682e1c8.png)

**Comment by Czechoslovaki** [comment]
![image](https://user-images.githubusercontent.com/51279558/97066399-08020980-156a-11eb-91d1-ffeb4fdb17fc.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/97640730-666a3480-1a0f-11eb-886c-930636e4143b.png)
