### ISSUE TITLE
SBCJ-Carajas Airport-PARA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3220]
# Airport Name

Carajas Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46381848-abbfaa80-c66d-11e8-9638-6aa8328f55bb.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46444458-b3e41c80-c737-11e8-9b48-fe253f47a87b.png)
