### ISSUE TITLE
CYPZ-Burns Lake Airport-BRITISH COLUMBIA-CANADA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3221]
# Airport Name

< Burns Lake Airport >

# Country?

< Canada >

# Improvements that need to be made?

< Remade from Scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low Priority >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46258712-e6bab600-c494-11e8-8f78-fcdfbd6a1e8f.png)
