### ISSUE TITLE
CAV3-One Hundred Mile House Airport-BRITISH COLUMBIA-CANADA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3223]
# Airport Name

< One Hundred Mile House Airport >

# Country?

< Canada >

# Improvements that need to be made?

< Remade >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low Priority >

**Comment by Balloonchaser** [comment]
Submitted for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46258777-9ee85e80-c495-11e8-979e-39dc5c635f26.png)
