### ISSUE TITLE
KERR-Errol Airport-NEW HAMPSHIRE-USA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3224]
♻️

**Comment by Balloonchaser** [comment]
Submitted for OR

**Comment by RyanEpps** [comment]
DUPLICATE: See #2411

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/47617504-caab3400-da95-11e8-8a2b-28d5486bb5fd.png)
