### ISSUE TITLE
CYGE-Golden Airport-BRITISH COLUMBIA-CANADA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3225]
# Airport Name

< Golden Airport >

# Country?

< Canada >

# Improvements that need to be made?

< Remade >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low Priority >

**Comment by Balloonchaser** [comment]
Sent in for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46258857-6432f600-c496-11e8-8208-9ae6755b4086.png)
