### ISSUE TITLE
KVCV- Southern California Logistics Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by henrikbg** [InfiniteFlightAirportEditing/Airports#323]
This one is a priority. Only 3 spawn points.

**Comment by ErmakDimon** [comment]
I guess I'd take this one

**Comment by dushyants19** [comment]
@ErmakDimon Please assign yourself and update on this

**Comment by dushyants19** [comment]
About 20 spawns here, means its redone.

**Comment by dushyants19** [comment]
Spawns have white outlines

**Comment by dushyants19** [comment]
outlines removed and gated

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20162096/52a838f8-a6b8-11e6-9d3e-2e2391aab2b5.png)

**Comment by ryu12332** [comment]
ISSUE: Needs buildings.

**Comment by brunocr98** [comment]
I'll add them later this evening.
