### ISSUE TITLE
LILO-Sondrio Caiolo Airport-LOMBARDIA-ITALY

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#3233]
![image](https://user-images.githubusercontent.com/14023167/46233329-c6c1b000-c337-11e8-9126-67e4aa558077.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68996819-1afe5b00-087e-11ea-9e5d-5936770e53f7.jpg)
