### ISSUE TITLE
YPMQ-Port Maquarie Airport-NEW SOUTH WALES-AUSTRALIA

### ISSUE THREAD

**Issue by AshRand** [InfiniteFlightAirportEditing/Airports#3234]
# Airport Name

Port Macquarie Airport

# Country?

Australia

# Improvements that need to be made?

Removal of the 10/28 Runway and rework

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

No Priority

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55764658-2eb52980-5a32-11e9-8db6-a906073e35d3.png)
