### ISSUE TITLE
CAL5-Alexis Creek Airport-BRITISH COLUMBIA-CANADA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3235]
# Airport Name

< Alexis Creek Airport >

# Country?

< Canada >

# Improvements that need to be made?

< Delete (Closed IRL) >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low Priority >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46246502-6d539280-c3c4-11e8-94f6-45ff474ccb01.png)
