### ISSUE TITLE
SBAT-Alta Floresta Airport-MATO GROSSO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3236]
# Airport Name

Alta Floresta Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46264367-ac2b3a80-c4e1-11e8-8f56-5021eb50d265.png)
