### ISSUE TITLE
CBQ2-Fort Langley Airport-BRITISH COLUMBIA-CANADA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3239]
# Airport Name

< Fort Langley Airport >

# Country?

< Canada >

# Improvements that need to be made?

< Remade >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low Priority >

**Comment by Balloonchaser** [comment]
Sent in for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46316286-629c2780-c595-11e8-8b7f-5918b3502a3d.png)
