### ISSUE TITLE
KTTS-Nasa Shuttle Landing Facility Airport-FLORIDA-USA

### ISSUE THREAD

**Issue by ErmakDimon** [InfiniteFlightAirportEditing/Airports#324]
PLEASE REDRAW ME

**Comment by HenrikBerg02** [comment]
Duplicate. I'll add you to the current one.

**Comment by tranquil-skyflyer** [comment]
I'll do this short one!

**Comment by tranquil-skyflyer** [comment]
Submitted for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22356554/c884071a-e3f7-11e6-9390-9bce5efe421e.png)
