### ISSUE TITLE
CAT5-Port McNeill Airport-BRITISH COLUMBIA-CANADA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3244]
# Airport Name

< Port McNeill Airport >

# Country?

< Canada >

# Improvements that need to be made?

< Remade >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low Priority >

**Comment by Balloonchaser** [comment]
Sent in for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46638299-e28e3880-cb25-11e8-8c4c-c080bde7a9e7.png)
