### ISSUE TITLE
WASS-Domine Eduard Osok Airport-IRIAN JAYA BARAT-INDONESIA

### ISSUE THREAD

**Issue by haociek** [InfiniteFlightAirportEditing/Airports#3245]
# Airport Name

Domine Eduard Osok

# Country?

Indonesia

# Improvements that need to be made?

redone

# Are you working on this airport?

yes

# Airport Priority? (A380, 10000ft+ Runway)

none

# Notes = This is to replace WA1A in the game

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46636055-372cb600-cb1c-11e8-9570-f652b498ea4d.png)
