### ISSUE TITLE
VRMH-Hanimaadhoo International Airport-HAA DHAALU-MALDIVES

### ISSUE THREAD

**Issue by gsherbert** [InfiniteFlightAirportEditing/Airports#3247]
# Airport Name

Hanimaadho International Airport

# Country?

Maldives

# Improvements that need to be made?

Redo from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low Priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46698895-debded00-cbdd-11e8-8d25-fbcf6732c4e6.png)
