### ISSUE TITLE
OIZH-Zahedan Airport-SISTAN AND BALUCHESTAN-IRAN

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#325]
PLEASE REDESIGN ME

**Comment by samuelandersson** [comment]
Will do when I have time.

**Comment by dushyants19** [comment]
@DavidCutler are you doing this?

**Comment by IceBlue02** [comment]
On Hold- If anyone wants to pick up especiall @cboisselier or @AxelBeder DM me on slack- not much done tho.

**Comment by IFAEpat** [comment]
Continue #255

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26025341/00728a32-37ab-11e7-93e8-2a2e38ac56cb.png)
