### ISSUE TITLE
SDAG-Angra dos Reis Airport-RIO DE JANEIRO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3251]
# Airport Name

Angra dos Reis Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46445479-b72dd700-c73c-11e8-81d3-09e163abb411.png)
