### ISSUE TITLE
SBCX-Caxias do Sul Airport-PARANA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3252]
# Airport Name

Caxias do Sul, Campo dos Bugres Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46585754-6b2faa80-ca3a-11e8-8014-71a81e9b1feb.png)
