### ISSUE TITLE
SBOI-Oiapoque Airport-AMAPA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3254]
# Airport Name

Oiapoque Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46583693-534b2d00-ca20-11e8-9178-95cc1f0c4c61.png)
