### ISSUE TITLE
SBSJ-Sao Jose dos Campos Airport-SAO PAULO-BRAZIL

### ISSUE THREAD

**Issue by IFBR0006** [InfiniteFlightAirportEditing/Airports#3255]
# Airport Name

< Sao Jose dos Campos Airport >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low priority >

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by MBeringuy** [comment]
@RyanEpps I am in contact with this member, he is active; but he walks a little out of time.

**Comment by RyanEpps** [comment]
Member inactive, up for grabs

**Comment by MBeringuy** [comment]
I'm catching this airport.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56079458-4128bd80-5dba-11e9-9468-4306a74cd9ae.png)
