### ISSUE TITLE
EKFU-Fur-DENMARK

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#3258]
# Airport Name

Fur

# Country?

Denmark

# Improvements that need to be made?

boundary issue, from scratch

# Are you working on this airport?

Yesss

# Airport Priority? (A380, 10000ft+ Runway)
very low

**Comment by MajorTomMueller** [comment]
redone from scratch

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46581888-fc842a00-ca04-11e8-96b7-bf7a2f0237f3.png)
