### ISSUE TITLE
PHKO-Kona International At Keahole Airport-HAWAII-USA

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Airports#326]
Redoing.

**Comment by samuelandersson** [comment]
Done. Redid the whole airport and added shoulder markings and new parking spots. Referred to WEDbing and charts.

**Comment by kilt46** [comment]
This airport needs lines redone. Holds wrong way round and shoulders need attention

**Comment by kilt46** [comment]
LINES FIXED

**Comment by dushyants19** [comment]
>A taxi way is not snapped to another, thus it creates a little void of grass.

from #615

**Comment by dushyants19** [comment]
Not an issue.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20371835/1139a6de-ac2d-11e6-8389-36af10a268b6.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78705362-bce11b80-78e3-11ea-9e3a-e88fca0a39cf.jpg)
