### ISSUE TITLE
SBSI-Sinop Airport-MATO GROSSO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3260]
# Airport Name

Sinop Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46583522-4dece300-ca1e-11e8-870f-d2a0070c8969.png)

**Comment by MBeringuy** [comment]
ICAO updated.

**Comment by victormw22** [comment]
Sent to OR!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/97495244-66960180-1935-11eb-96eb-844392973830.png)
