### ISSUE TITLE
KCFJ-Crawfordsville Regional Airport-INDIANA-USA

### ISSUE THREAD

**Issue by MrMrMan** [InfiniteFlightAirportEditing/Airports#3261]
# Airport Name

Crawfordsville Regional Airport

# Country?

United States

# Improvements that need to be made?

Needs to be completely redone with spawns, hangars, and correct taxiways.

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

 Low Priority

**Comment by MrMrMan** [comment]
Sent in for OR yesterday, forgot to update.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/47685968-be62cc00-dba6-11e8-999a-b63a32a2c521.png)
