### ISSUE TITLE
CAV4-McBride/Charlie Leake Field Airport-BRITISH COLUMBIA-CANADA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3263]
# Airport Name

< McBride/Charlie Leake Field Airport >

# Country?

< Canada >

# Improvements that need to be made?

< Redone From Scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None (Error Project) >

**Comment by Balloonchaser** [comment]
Sent in for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46638927-e40d3000-cb28-11e8-9713-14ee77145d60.png)
