### ISSUE TITLE
CAR2-Crawford Bay Airport-BRITISH COLUMBIA-CANADA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3266]
# Airport Name

< Crawford Bay Airport >

# Country?

< Canada >

# Improvements that need to be made?

< Remade from Scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None [Error Project] >

**Comment by Balloonchaser** [comment]
Sent in for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46704641-81339b80-cbf1-11e8-8843-c5425fe6568e.png)
