### ISSUE TITLE
CBE2-Elko/Lionel P. Demers Memorial Airpark Airport-BRITISH COLUMBIA-CANADA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3267]
# Airport Name

< Elko/Lionel P. Demers Memorial Airpark Airport >

# Country?

< Canada >

# Improvements that need to be made?

< Remade from Scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None [Error Project] >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46918308-5c934700-cf96-11e8-82d2-4eb65aa8df99.png)

Needs realigned
