### ISSUE TITLE
EBCI - Amsterdam

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#327]
CHARLIE 
Main Terminal buildings needed as well as ALL Gates

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/11328423/ff561234-914f-11e5-8e33-16691f282cc2.png)

**Comment by samuelandersson** [comment]
Will redo.

**Comment by samuelandersson** [comment]
Redid airport, everything but the runway and boundary is pretty much updated, except that very small heading change to the runway.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20464611/f9b23482-af0f-11e6-9b68-2d60cdabb6e6.png)
