### ISSUE TITLE
RKNW-Wonju Airport-GANGWON-DO-SOUTH KOREA

### ISSUE THREAD

**Issue by Session-IFK** [InfiniteFlightAirportEditing/Airports#3271]
# Airport Name

Wonju Airport

# Country?

South Korea

# Improvements that need to be made?

redone from scratch

# Are you working on this airport?

yes

# Airport Priority? (A380, 10000ft+ Runway)

No

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48672068-c606f800-eaf6-11e8-9e01-dba27e6f42ce.png)
