### ISSUE TITLE
KGCN-Grand Canyon National Park Airport-ARIZONA-USA

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#3275]
![c69c5182-6af3-4e71-a633-caeaf919e9f9](https://user-images.githubusercontent.com/22130457/46848391-28a9fd00-cdaf-11e8-94ad-66569398966b.jpeg)

**Comment by Balloonchaser** [comment]
Submitted To OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48675399-062da100-eb1e-11e8-9f00-0830ec13646b.png)
