### ISSUE TITLE
RJAW-Iwoto Air Base-TOKYO-JAPAN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#3276]
# Airport Name

< Iwoto Air Base >

# Country?

< Japan >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46905495-31d3c080-ceba-11e8-923c-6247b76a690e.png)

**Comment by orangejuicie** [comment]
Add Departure Frequency.
