### ISSUE TITLE
KCKC-Grand Marais/Cook County Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by danisrils39** [InfiniteFlightAirportEditing/Airports#3297]
# Airport Name

Grand Marais/Cook County Airport

# Country?

United States

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

N/A

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46917736-dd9b1000-cf8f-11e8-89b1-1a077a0b7742.png)
