### ISSUE TITLE
KPAO

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#33]

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17458676/d6cbf7c4-5bdf-11e6-9186-44af51ba9c51.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17458683/16bcab44-5be0-11e6-8e2f-396ca73a131d.png)
