### ISSUE TITLE
MMIO-Plan de Guadalupe International Airport-COAHUILA-MEXICO

### ISSUE THREAD

**Issue by IFK-Flightsim** [InfiniteFlightAirportEditing/Airports#3302]
Recycled

**Comment by orangejuicie** [comment]
Duplicate.

https://github.com/InfiniteFlightAirportEditing/Airports/issues/1773

**Comment by becarboner3000** [comment]
#3357

**Comment by MajorTomMueller** [comment]
![MMIO-git](https://user-images.githubusercontent.com/26853210/131215498-413dc99a-7db7-493a-ad01-5464746e8189.png)
