### ISSUE TITLE
KISP-Long Island McArthur Airport-NEW YORK-USA

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#331]
has hold short areas

**Comment by rednaxela796** [comment]
ill do it

**Comment by kilt46** [comment]
Hold Shorts removed. Gates renamed

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20648396/27dcd578-b46b-11e6-97cb-d19d50b66a6e.png)

**Comment by kilt46** [comment]
Please check against Navigraph Chart for spawns - expected results
![image](https://user-images.githubusercontent.com/14023167/42136569-958aa244-7d23-11e8-8d96-fe2a3c28959c.png)

**Comment by RyanEpps** [comment]
Needs a complete redo. None of this "partial rework" crap.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51791395-d0351a80-2167-11e9-9ff5-3997c038fb2b.png)
