### ISSUE TITLE
KTTN - New York

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#332]
has hold short areas

**Comment by DS2001** [comment]
What you most do here??

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/11415193/61729682-93c5-11e5-89a4-07148ecd4966.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20625633/32a8a3ca-b2da-11e6-8f63-3817e1387695.png)
