### ISSUE TITLE
63MN-Weideman International Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by danisrils39** [InfiniteFlightAirportEditing/Airports#3328]
# Airport Name

Weideman International Airport

# Country?

USA

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

N/A

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/47221690-b6bb5000-d37a-11e8-8b9e-166c50252ca6.png)
