### ISSUE TITLE
OETB-Tabuk/Prince Sultan Bin Abdula Airport-TABUK-SAUDI ARABIA

### ISSUE THREAD

**Issue by M3RKZ** [InfiniteFlightAirportEditing/Airports#3333]
# Airport Name

< Tabuk >

# Country?

< Saudia Arabia >

# Improvements that need to be made?

< Adding taxiways and parking >

# Are you working on this airport?

< yes >

# Airport Priority? (A380, 10000ft+ Runway)

< N/Y >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53690121-0c8d0500-3d2a-11e9-9071-ec19a1d16f2a.png)
