### ISSUE TITLE
VRMD-Dharavandhoo Airport-DHARAVANDHOO-MALDIVES

### ISSUE THREAD

**Issue by gsherbert** [InfiniteFlightAirportEditing/Airports#3334]
# Airport Name

Dharavandhoo Airport

# Country?

Maldives

# Improvements that need to be made?

New airport to repo (Done from scratch)

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

No

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/47121107-f547f200-d236-11e8-8725-24c920ce55dd.png)
