### ISSUE TITLE
EYSA-Siauliai International Airport-SIAULIAI-LITHUANIA

### ISSUE THREAD

**Issue by danisrils39** [InfiniteFlightAirportEditing/Airports#3339]
# Airport Name

Siauliai International Airport

# Country?

Lithuania

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

yes

# Airport Priority? (A380, 10000ft+ Runway)

10K Runway

**Comment by MajorTomMueller** [comment]
Hi @danisrils39, 
Just in case you don’t have it:
https://www.ans.lt/media/filer_public/6d/91/6d91fce2-7e81-4e83-ada0-16fb88ffcb81/ey_ad_2_eysa_en.pdf

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/49972739-34718700-fef8-11e8-8707-59e4c6c1f4dd.png)
