### ISSUE TITLE
SNQD-Sousa Airport-PARAIBA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3350]
# Airport Name

Sousa Regional Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by MBeringuy** [comment]
Should not this issue be closed?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/47953380-d8a3fd80-df4a-11e8-8dca-18255bb4dd9f.png)
