### ISSUE TITLE
EKBR-Braedstrup-DENMARK

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#3351]
# Airport Name

Braedstrup

# Country?

Denmark

# Improvements that need to be made?

scratch

# Are you working on this airport?

yes

# Airport Priority? (A380, 10000ft+ Runway)

low low low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/47256874-32390200-d44c-11e8-8d51-64607951e573.png)
