### ISSUE TITLE
EKEL-Endelave-DENMARK

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#3352]
# Airport Name

Endelave

# Country?

Denmark

# Improvements that need to be made?

scratch

# Are you working on this airport?

yes

# Airport Priority? (A380, 10000ft+ Runway)

low low low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/47256812-46c8ca80-d44b-11e8-8e37-8c83c95c118a.png)
