### ISSUE TITLE
EKFM-Femoe-DENMARK

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#3353]
# Airport Name

Femoe

# Country?

Denmark

# Improvements that need to be made?

scratch

# Are you working on this airport?

yes

# Airport Priority? (A380, 10000ft+ Runway)

low low low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/47256746-70cdbd00-d44a-11e8-9706-6be75d9086f2.png)
