### ISSUE TITLE
EKFR-Freerslev-DENMARK

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#3354]
# Airport Name

Freerslev

# Country?

Denmark

# Improvements that need to be made?

scratch

# Are you working on this airport?

yes

# Airport Priority? (A380, 10000ft+ Runway)

low low low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/47256547-bc329c00-d447-11e8-8fd1-5c5a6663ff8f.png)
