### ISSUE TITLE
EKGO-Goerlev Airport-ZEALAND-DENMARK

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#3355]
# Airport Name

Goerlev

# Country?

Denmark

# Improvements that need to be made?

scratch

# Are you working on this airport?

yes

# Airport Priority? (A380, 10000ft+ Runway)

low low low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/47256503-272fa300-d447-11e8-9b21-9e5e3f5706d2.png)
