### ISSUE TITLE
GMAA-Agadir Inezgane Airport-SOUSS-MASSA-DRAA-MOROCCO

### ISSUE THREAD

**Issue by IFK-Flightsim** [InfiniteFlightAirportEditing/Airports#3356]
♻️

**Comment by becarboner3000** [comment]
This airport is actually completed #3364

**Comment by Czechoslovaki** [comment]
Taking on this bRaVo.

**Comment by Czechoslovaki** [comment]
![image](https://user-images.githubusercontent.com/51279558/128279389-ea2d9ec0-f620-47d9-9058-79754c48c75d.png)
