### ISSUE TITLE
ZGSD-Zhuhai Jinwan Airport-GUANGDONG-CHINA

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#3357]
# Airport Name

< Enter text here >

# Country?

< Enter text here >

# Improvements that need to be made?

< Enter text here >

# Are you working on this airport?

< Enter text here >

# Airport Priority? (A380, 10000ft+ Runway)

< Enter text here >

**Comment by PopuleuxMusicYT** [comment]
I am new if i want to this how do i claim?

**Comment by Berlin-N** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/86644683-5bdce880-bfa3-11ea-9c90-7ddc091be485.png)
