### ISSUE TITLE
RJOB-Okayama Airport-OKAYAMA-JAPAN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#3360]
# Airport Name

< Okayama Airport >

# Country?

< Japan >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/47607150-e7862f80-d9e1-11e8-966b-aa190ecf98ee.png)

**Comment by orangejuicie** [comment]
Spawn name correction.
