### ISSUE TITLE
SOCA-Felix Eboue Airport-CAYENNE-FRENCH GUIANA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3361]
# Airport Name

Cayenne, Felix Eboue Intl Airport

# Country?

French Guiana

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

GP2 (10000ft+ Runway)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/47609980-ba507600-da0f-11e8-807c-28f5c9e34e49.png)
