### ISSUE TITLE
ZSNJ-Nanjing Lukou International Airport-JIANGSU-CHINA

### ISSUE THREAD

**Issue by eltonfly** [InfiniteFlightAirportEditing/Airports#3362]
# Airport Name

Nanjing Lukou International Airport

# Country?

China

# Improvements that need to be made?

Wil be redone from scratch

# Are you working on this airport?

No

# Airport Priority? (A380, 10000ft+ Runway)

The length of both two runways 06/24, 07/25 are more than 10000ft.

**Comment by eltonfly** [comment]
the airport has been sent for approval, anything else will be handled by the reviewer.

**Comment by kilt46** [comment]
Where is Terminal 1?
![image](https://user-images.githubusercontent.com/14023167/50321453-92711200-0496-11e9-8862-b726e7dd32fc.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50321461-9ef56a80-0496-11e9-9ac0-293db47d1e19.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50321480-af0d4a00-0496-11e9-9c24-996a60073d1c.png)

**Comment by eltonfly** [comment]
> Where is Terminal 1?
> ![image](https://user-images.githubusercontent.com/14023167/50321453-92711200-0496-11e9-8862-b726e7dd32fc.png)

The Terminal 1 and the associated aprons are now being renovated. So I didn't edit them. When the reconstruction project is finished, I will edit them again.

**Comment by AnthonyCK** [comment]
Can anyone assign this issue to me? I'm working on it
![image](https://user-images.githubusercontent.com/37546244/77670899-c6a08000-6fc1-11ea-8f0c-49bab17e414d.png)

**Comment by AnthonyCK** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78403854-8baad780-75d3-11ea-8a41-190effcc489f.jpg)
