### ISSUE TITLE
KSHR-Sheridan County Airport-WYOMING-USA

### ISSUE THREAD

**Issue by 2018ljh** [InfiniteFlightAirportEditing/Airports#3363]
# Airport Name

Sheridan County Airport

# Country?

United States of America

# Improvements that need to be made?

Will be redone from scratch.

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low Priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54884963-f82dbb00-4e44-11e9-805d-d5a5aaf6b5ee.png)
