### ISSUE TITLE
ZLXY-Xian Xianyang Airport-SHAANXI-CHINA

### ISSUE THREAD

**Issue by akshay2777** [InfiniteFlightAirportEditing/Airports#3364]
oops ♻️

**Comment by dushyants19** [comment]
Please accept your slack invitation.

**Comment by dushyants19** [comment]
Continue in #1297

**Comment by grxninesix** [comment]
https://community.infiniteflight.com/t/new-airport-navigation-update/306208/27?u=grxninesix

I just found this on IFC.

**Comment by SKYSTAR-F** [comment]
ZLXY everything reworked and updated.

**Comment by kilt46** [comment]
Taxiways E and F need added.

**Comment by kilt46** [comment]
![Uploading image.png…]()
