### ISSUE TITLE
VECC-Netaji Subhash Chandra Bose International Airport-WEST BENGAL-INDIA

### ISSUE THREAD

**Issue by dailyservice** [InfiniteFlightAirportEditing/Airports#3366]
# Airport Name

< Netaji Subhash Chandra Bose International Airport >

# Country?

< India >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< yes >

# Airport Priority? (A380, 10000ft+ Runway)

< GP2 >

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by Racerhell513** [comment]
Hey I want to redo this airport,so can you please assign me ;)

**Comment by brunocr98** [comment]
We are unable to assign you because you're not part of this team. You have to send an email to contact@airportediting.com

**Comment by RyanEpps** [comment]
Accept collab invite: https://github.com/InfiniteFlightAirportEditing/Airports/invitations

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54865169-78fa9300-4d2f-11e9-925b-b0276cc3028b.png)
