### ISSUE TITLE
SBIP-Usiminas Airport-MINAS GERAIS-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3369]
# Airport Name

Ipatinga, Usiminas Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/47953117-df307600-df46-11e8-882f-47e16992eda6.png)
