### ISSUE TITLE
UWLW-Ulyanovsk/Vostochny Airport-ULYANOVSK-RUSSIA

### ISSUE THREAD

**Issue by rednaxela796** [InfiniteFlightAirportEditing/Airports#337]

**Comment by rednaxela796** [comment]
I'll do this one

**Comment by kilt46** [comment]
Is this one not already done?

**Comment by kilt46** [comment]
http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=EDDK

**Comment by kilt46** [comment]
Why are you opening a NEW issue when there is already a thread for this one?

**Comment by kilt46** [comment]
https://github.com/InfiniteFlightAirportEditing/Airports/issues/237

**Comment by rednaxela796** [comment]
I looked at it just now and there are no parking location lines and also some of the hold short lived new are funny. Also some lines missing

**Comment by kilt46** [comment]
http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=EDDK

**Comment by kilt46** [comment]
Is this the same airport you are seeing?

**Comment by kilt46** [comment]
This is EDDK
![image](https://cloud.githubusercontent.com/assets/14023167/11424029/3f65f710-940f-11e5-80be-a5d15a9464e0.png)

**Comment by kilt46** [comment]
Is this the airport you are seeing?

**Comment by kilt46** [comment]
There should be NO airports with HOLD SHORTs. We are removing them all since we have ATC and they cause conflict

**Comment by MiguelIF27** [comment]
I will make

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
Suggested numbers for spawns
![image](https://cloud.githubusercontent.com/assets/14023167/26082551/335e8166-3996-11e7-8f6b-893b78c25673.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26285002/7f231038-3e0c-11e7-98b9-1ea280bb1430.png)
