### ISSUE TITLE
WICA-Kertajati International Airport-JAWA BARAT-INDONESIA

### ISSUE THREAD

**Issue by haociek** [InfiniteFlightAirportEditing/Airports#3374]
# Airport Name

Kertajati International Airport

# Country?

Indonesia

# Improvements that need to be made?

from scratch

# Are you working on this airport?

yes
# Airport Priority? (A380, 10000ft+ Runway)

none

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48102199-99e2a180-e1ef-11e8-918b-bb298603c6e2.png)

**Comment by ECoops-123** [comment]
@adibyaputra will be reworking this airport with the addition of a remote stand area and runway extension.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106954032-cd774380-66f8-11eb-8cda-c950ffda35ae.png)
