### ISSUE TITLE
LTFM-Istanbul Airport-ISTANBUL-TURKEY

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#3375]
♻️

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48304138-06a0b900-e4da-11e8-92d0-fa2322e3a23d.png)

**Comment by MajorTomMueller** [comment]
Snapping issues on maintenance apron (M03) and taxiway junction near 34L

**Comment by MajorTomMueller** [comment]
![IMG_2221](https://user-images.githubusercontent.com/26853210/57966060-4050f180-794d-11e9-89fb-072e5dc79ce4.png)
![IMG_2220](https://user-images.githubusercontent.com/26853210/57966062-45ae3c00-794d-11e9-9059-b59c54c6f813.png)

**Comment by liamkirky** [comment]
Due to it only being minor issues may I take this airport?

**Comment by liamkirky** [comment]
Could I be removed from this temporarily unless someone wants to take this over as with current terrain data and overlayed imagery it makes it practically impossible to edit. It's a shame that I'm letting this airport go but yeah :)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/73789503-aef50a00-477d-11ea-9b8a-a6bba45a48c6.jpg)

**Comment by brunocr1050** [comment]
@OscarConklin will be updating this airport.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103481407-794b0d80-4da0-11eb-9637-83339141e3e1.png)
