### ISSUE TITLE
SCSE-La Florida Airport-COQUIMBO-CHILE

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3377]
# Airport Name

La Serena, La Florida Airport

# Country?

Chile

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/47967458-47ed2080-e023-11e8-8877-266639efb108.png)
