### ISSUE TITLE
SBVG-Major Brigadeiro Trompowsky Airport-MINAS GERAIS-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3378]
# Airport Name

Varginha, Major Brigadeiro Trompowsky Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/47968015-b503b480-e029-11e8-85f4-68476d2dc7bb.png)
