### ISSUE TITLE
EKGR-Greenaa-DENMARK

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#3379]
# Airport Name

Greenaa

# Country?

Denmark

# Improvements that need to be made?

from scratch

# Are you working on this airport?

done

# Airport Priority? (A380, 10000ft+ Runway)

smal privat GA

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/47953431-9cbd6800-df4b-11e8-9566-a0a9da85c4ed.png)
