### ISSUE TITLE
KPOB-Pope Army Airfield-NORTH CAROLINA-USA

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#338]
Charlie Class. Ugly needs some love

**Comment by DS2001** [comment]
Foto?

**Comment by harrymorris** [comment]
I'll take

**Comment by dushyants19** [comment]
I can't assign @harrymorris

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/11761991/1efd26da-a09c-11e5-9049-e589df6d6669.png)

**Comment by cboisselier** [comment]
@harrymorris are you doing it or I can start with it?

**Comment by cboisselier** [comment]
Have any of you guys found an information of where the displaced threshold is exactly? Can't find that on internet...

**Comment by cboisselier** [comment]
Work is in progress. Had to redo it entirely as curved taxiways were misdone...

**Comment by HenrikBerg02** [comment]
@cboisselier, are you still working on this? If not, I'll take it and redo it.

**Comment by HenrikBerg02** [comment]
Reworking.

**Comment by henrikbg** [comment]
I have more important stuff to work on at the moment. I'll un-assign myself just in case other people want to work on this airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22175099/f2a8b740-dfb3-11e6-8da7-5edd8d77eb32.png)
