### ISSUE TITLE
EKHE-Anisse-DENMARK

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#3380]
# Airport Name

Anisse

# Country?

Denmark

# Improvements that need to be made?

from scratch

# Are you working on this airport?

done

# Airport Priority? (A380, 10000ft+ Runway)

small privat GA

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/47953562-6a146f00-df4d-11e8-9876-7219b62cf025.png)
