### ISSUE TITLE
LGTG-Tanagra Air Base-STEREA ELLADA-GREECE

### ISSUE THREAD

**Issue by Alexsar738** [InfiniteFlightAirportEditing/Airports#3384]
# Airport Name

Tanagra (Air Force Base)

# Country?

Greece

# Improvements that need to be made?

Rework

# Are you working on this airport?

I will be doing it 

# Airport Priority? (A380, 10000ft+ Runway)

Low Priority

**Comment by MajorTomMueller** [comment]
Any progress? Still with us @Alexsar738

**Comment by MajorTomMueller** [comment]
![LGTG-git](https://user-images.githubusercontent.com/26853210/112148772-2e3ddb00-8bd6-11eb-9687-84eceb15d3ee.png)
