### ISSUE TITLE
SBQV-Vitoria da Conquista Airport-BAHIA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3386]
# Airport Name

Vitoria da Conquista Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/47969377-0b79ee80-e03c-11e8-812d-49e5a7975ccb.png)
