### ISSUE TITLE
WIKK-Depati Amir Airport-BANGKA BELITUNG-INDONESIA

### ISSUE THREAD

**Issue by haociek** [InfiniteFlightAirportEditing/Airports#3387]
# Airport Name

Depati Amir

# Country?

Indonesia

# Improvements that need to be made?

redone

# Are you working on this airport?

yes

# Airport Priority? (A380, 10000ft+ Runway)

none

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48674953-fca13a80-eb17-11e8-9744-aff20145d2fb.png)

**Comment by brunocr1050** [comment]
@vinoalviano1994 will be redoing the airport.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103161547-055da380-47a9-11eb-917b-2f6af4f226e2.png)
