### ISSUE TITLE
FYWH-Hosea Kutako Int/Windhoek Airport-KHOMAS-NAMIBIA

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Airports#339]
PLEASE REDRAW ME

**Comment by henrikbg** [comment]
Tristin will be fixing the spawn points. :)

**Comment by TristinWoolf** [comment]
As Henrik said, I will be removing some of the spawn points that are labeled with a Left and Right, also will be revising the entire commercial parking area.

**Comment by TristinWoolf** [comment]
Parking area and spawning points fixed. also fixed a couple minor taxiway issues. Submitted it to the email!

**Comment by TristinWoolf** [comment]
Approved. Can somebody un-label and close please? Thanks.

**Comment by bavAVIA** [comment]
Taking over.

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25048081/0e050c72-2100-11e7-8189-5ea97a39446c.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/69557472-6bb03b00-0f85-11ea-961c-3caa31579950.jpg)
