### ISSUE TITLE
SBPR-Carlos Prates Airport-MINAS GERAIS-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3390]
# Airport Name

Belo Horizonte, Carlos Prates Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48307501-06251400-e514-11e8-9bd4-6dea250bb8cf.png)
