### ISSUE TITLE
EDAR-Pirna Pratzschwitz Airport-SACHSEN-GERMANY

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#3391]
# Airport Name

< Enter text here >

# Country?

< Enter text here >

# Improvements that need to be made?

GA airport with duplicate spawn issue, will be completely redone in the Saxony project I’ve started 

# Are you working on this airport?

< Enter text here >

# Airport Priority? (A380, 10000ft+ Runway)

< Enter text here >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48381719-eb34da00-e6a2-11e8-9701-6815ec135299.png)
