### ISSUE TITLE
SWBE-Sao Benedito Airport-CEARA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3392]
# Airport Name

Sao Benedito Airport

# Country?

Brazil

# Improvements that need to be made?

Created from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48304756-86cc1c00-e4e4-11e8-96dd-c08c5e37f396.png)
