### ISSUE TITLE
SBPB-Parnaiba Airport-PIAUI-BRAZIL

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Airports#3394]
# Airport Name

< Parnaiba, Prefeito Dr. João Silva Filho >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low priority >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48654568-90b5b980-e9d3-11e8-811d-045c0fe5f32c.png)
