### ISSUE TITLE
12D-Tower Municipal Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by danisrils39** [InfiniteFlightAirportEditing/Airports#3396]
# Airport Name

Tower Municipal Airport

# Country?

USA

# Improvements that need to be made?

Scratch

# Are you working on this airport?

yes

# Airport Priority? (A380, 10000ft+ Runway)

N/A

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48661443-672e7980-ea37-11e8-9eeb-a9ca8e708f52.png)
