### ISSUE TITLE
SBAA-Conceicao do Araguaia Airport-PARA-BRAZIL

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Airports#3397]
# Airport Name

< Conceicao do Araguaia >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low priority >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48518390-151b0780-e82f-11e8-8413-5ca7beb71b33.png)
