### ISSUE TITLE
SDFX-Casa Nova Aerodrome-BAHIA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3398]
# Airport Name

Casa Nova Aerodrome

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104075488-86b92b00-51d8-11eb-80a6-fe3b72d17db0.png)
