### ISSUE TITLE
SNBM-Cristiano Ferreira Varella Airport-MINAS GERAIS-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3399]
# Airport Name

Muriae, Cristiano Ferreira Varella Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48307536-ec380100-e514-11e8-9786-3c751a385f79.png)
