### ISSUE TITLE
KPDX-Portland International Airport-OREGON-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#34]
Seattle

**Comment by Swang007** [comment]
Will add ATIS frequency

**Comment by Swang007** [comment]
Lines in the grass.

**Comment by kilt46** [comment]
Bravo - Missing Airport Terminal Buildings

**Comment by dushyants19** [comment]
Which region is it?

**Comment by samuelandersson** [comment]
This is not in the denver region, it's actually Seattle.

**Comment by kilt46** [comment]
Main terminal buildings added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17279536/c2ba243e-573b-11e6-849d-325398681b9f.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17280270/cc1a34ea-5751-11e6-9b6c-d8cab3d919d9.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32990418-c3879ff2-ccee-11e7-8e88-d72759f75e3a.png)

**Comment by kztmtn** [comment]
Good Luck!

**Comment by Czechoslovaki** [comment]
Sent For OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85080019-c8777b00-b18d-11ea-9ebc-7b3e00264711.png)
