### ISSUE TITLE
KPCM

### ISSUE THREAD

**Issue by DavidCutler** [InfiniteFlightAirportEditing/Airports#340]
Southern Florida. Requires complete overhaul.  Broken taxiways (grass between a couple taxiways and runway entrance), a few taxi lines that look like instant noodles, and hold short lines, irrespective of which side of a runway they're on.

**Comment by Swang007** [comment]
Why was this closed?

**Comment by samuelandersson** [comment]
Redoing. More info on exactly what has been redone when done.

**Comment by samuelandersson** [comment]
o

**Comment by kilt46** [comment]
https://community.infinite-flight.com/t/whats-wrong-with-kpcm-plant-city-airport/37669

**Comment by kilt46** [comment]
This airport has been redrawn

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17279533/a07e24d8-573b-11e6-80b3-89b046a26dd2.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17642905/c0157250-611e-11e6-9b8c-f842d5bb275c.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17642907/c7e6de9c-611e-11e6-9eaa-5c88da3ea447.png)
