### ISSUE TITLE
KCQM-Cook Municipal Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by danisrils39** [InfiniteFlightAirportEditing/Airports#3400]
# Airport Name

Cook Municipal Airport

# Country?

USA

# Improvements that need to be made?

scratch

# Are you working on this airport?

yes

# Airport Priority? (A380, 10000ft+ Runway)

n/a

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48661502-5c281900-ea38-11e8-9aba-fc6449c100a9.png)
