### ISSUE TITLE
EDMT

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#3401]
# Airport Name

< Enter text here >

# Country?

< Enter text here >

# Improvements that need to be made?

< Enter text here >

# Are you working on this airport?

< Enter text here >

# Airport Priority? (A380, 10000ft+ Runway)

< Enter text here >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48515982-d9307400-e827-11e8-9554-d75c74a65486.png)
