### ISSUE TITLE
EDNL

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#3402]
# Airport Name

< Enter text here >

# Country?

< Enter text here >

# Improvements that need to be made?

< Enter text here >

# Are you working on this airport?

< Enter text here >

# Airport Priority? (A380, 10000ft+ Runway)

< Enter text here >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48515193-c026c380-e825-11e8-9ed0-b75777b1ab84.png)
