### ISSUE TITLE
KNFL-Fallon NAS (Van Voorhis Field) Airport-NEVADA-USA

### ISSUE THREAD

**Issue by DavidCutler** [InfiniteFlightAirportEditing/Airports#341]
PLEASE REDESIGN ME

**Comment by dushyants19** [comment]
@DavidCutler it is an old airport, it was removed and its a park now.... 

https://www.google.co.in/maps/@41.860483,-87.606529,2182m/data=!3m1!1e3?hl=en

It is this now^

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26276044/57cc6aa8-3d34-11e7-8274-712abdf9646e.png)
