### ISSUE TITLE
EDAU

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#3413]
# Airport Name

< Enter text here >

# Country?

< Enter text here >

# Improvements that need to be made?

< Enter text here >

# Are you working on this airport?

< Enter text here >

# Airport Priority? (A380, 10000ft+ Runway)

< Enter text here >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48383295-c80e2880-e6aa-11e8-8bee-60f186ffc5c0.png)
