### ISSUE TITLE
EDAW

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#3414]
# Airport Name

< Enter text here >

# Country?

< Enter text here >

# Improvements that need to be made?

< Enter text here >

# Are you working on this airport?

< Enter text here >

# Airport Priority? (A380, 10000ft+ Runway)

< Enter text here >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48381846-a52c4600-e6a3-11e8-8f79-756d8cf42c64.png)
