### ISSUE TITLE
OIIE-Tehran/Imam Khomeini Airport-TEHRAN-IRAN

### ISSUE THREAD

**Issue by DavidCutler** [InfiniteFlightAirportEditing/Airports#342]
PLEASE REDRAW ME

**Comment by brunocr98** [comment]
I'll take this one!

**Comment by brunocr98** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24321887/bdc97b7e-1125-11e7-9e55-23a22b8eda7f.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59607365-9c906800-90e9-11e9-9949-5dd23992374f.jpg)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/75932802-21c5d380-5e57-11ea-8fde-2addea12510b.jpg)
