### ISSUE TITLE
SBNT-Natal Augusto Severo Airport-RIO GRANDE DO NORTE-BRAZIL

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Airports#3427]
# Airport Name

< Natal Air Base >

# Country?

< Brazil >

# Improvements that need to be made?

<  redone from scratch >

# Are you working on this airport?

< yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low Priority >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52164447-0bc76b80-26b7-11e9-913a-72ec42d12857.png)
