### ISSUE TITLE
SBAC-Aracati Airport-CEARA-BRAZIL

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Airports#3428]
# Airport Name

< Aracati Regional >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low Priority >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/49040791-23e7af80-f189-11e8-882d-47a39b8098ca.png)

**Comment by kilt46** [comment]
OK so is this SBAC or SNAT?

**Comment by brunocr98** [comment]
Looks like it's SBAC, SNAT is the old code. http://ais.decea.gov.br/download/?arquivo=2064a660-acb0-4e22-8e467d38a77ad970&apikey=1587263166
