### ISSUE TITLE
OAFR-Farah Airport-FARAH-AFGHANISTAN

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#3429]
# Airport Name

Farah

# Country?

Afghanistan

# Improvements that need to be made?

From scratch

# Are you working on this airport?

Yup

# Airport Priority? (A380, 10000ft+ Runway)

Beneath the soil

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48662820-14f85300-ea4d-11e8-9758-0b3896c8f99e.png)

**Comment by kilt46** [comment]
Co-ordinates of airport seems to be a few hundred feet off
![image](https://user-images.githubusercontent.com/14023167/48662983-5f7acf00-ea4f-11e8-9943-f7a6d6a2313f.png)

**Comment by MajorTomMueller** [comment]
image is off, that’s common to this region. Editing was based of governmental runway threshold coordinates:
http://acaa.gov.af/wp-content/uploads/AERODROME.pdf
The imagery used in the comparison above was very outdated by the way, I used a newer one...

**Comment by MajorTomMueller** [comment]
checked in IF now, Airport fits perfect in scenery-
