### ISSUE TITLE
VREI-Ifuru Airport-IFURU-MALDIVES

### ISSUE THREAD

**Issue by gsherbert** [InfiniteFlightAirportEditing/Airports#3431]
# Airport Name

Ifuru Airport

# Country?

Maldives

# Improvements that need to be made?

New to Repo

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

No

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48675466-c2876700-eb1e-11e8-97f0-16f264a21f41.png)
