### ISSUE TITLE
SSZW-Ponta Grossa Airport-PARANA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3432]
# Airport Name

Ponta Grossa Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48655882-10975000-e9e3-11e8-80dd-69647bbd6bc2.png)
