### ISSUE TITLE
23N-Bayport Aerodome-NEW YORK-USA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3433]
# Airport Name

< Bayport Aerodome >

# Country?

< USA >

# Improvements that need to be made?

< Redone>

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48661370-634e2780-ea36-11e8-994d-1d85348316de.png)
