### ISSUE TITLE
1N2-Spadaro-Lufker Airport-NEW YORK-USA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3434]
# Airport Name

< Spadaro-Lufker Airport >

# Country?

< USA >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by Balloonchaser** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/49837717-13305f80-fd6d-11e8-97b8-7a233ea66a80.png)
