### ISSUE TITLE
CYBF-Bonnyville Regional Airport-ALBERTA-CANADA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3435]
# Airport Name

< Bonnyville Regional Airport >

# Country?

< Canada >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by Balloonchaser** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48656033-30c80e80-e9e5-11e8-8e88-3eaba18dc56d.png)
