### ISSUE TITLE
49NY-Westmoreland Airport-NEW YORK-USA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3436]
# Airport Name

< Westmoreland Airport >

# Country?

< USA >

# Improvements that need to be made?

< Remade >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48661205-1406f780-ea34-11e8-9ae9-f9d62c98abce.png)
