### ISSUE TITLE
2NK3-Rose Field Airport-NEW YORK-USA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3437]
# Airport Name

< Rose Field Airport >

# Country?

< USA >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48661281-4fee8c80-ea35-11e8-995c-28422fa2a871.png)
