### ISSUE TITLE
SBJE-Comandante Ariston Pessoa Airport-CEARA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3438]
# Airport Name

Comandante Ariston Pessoa Airport

# Country?

Brazil

# Improvements that need to be made?

Created from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48521139-d68a4a80-e838-11e8-9b1a-818436f23640.png)
