### ISSUE TITLE
KSFO-San Francisco International Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#344]
Requires Terminal Buildings

**Comment by kilt46** [comment]
Terminal Buildings added. Gates added

**Comment by dushyants19** [comment]
unassigned @JonathanAirbus

**Comment by kilt46** [comment]
Milestone is already Global Priority 1    :)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20159560/0ed12b00-a6a7-11e6-86b1-7efb7e87cbfa.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20159598/4b33c18e-a6a7-11e6-8ccd-a7458dbb2f2d.png)

**Comment by moritzbabl** [comment]
The airport is missing taxiway shoulders, runway holds are drawn like in real life resulting in the lines being drawn outside the taxiways. Needs a bit more attention

**Comment by moritzbabl** [comment]
done

**Comment by brennanhackard** [comment]
I will be updating this airport to include Harvey Milk Terminal 1.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/117376610-204acd80-ae97-11eb-853a-2654db9f31ea.png)
