### ISSUE TITLE
YANN-Anningie Airport-WESTERN AUSTRALIA-AUSTRALIA

### ISSUE THREAD

**Issue by grxninesix** [InfiniteFlightAirportEditing/Airports#3442]
# Airport Name

< Enter text here >
Annigie

# Country?

Australia

# Improvements that need to be made?

Altitude are wrong and that allows pilots to go off ground
Unable to spawn at airport and stay on ground. Plane start falling down through the ground directly after calibrating.

# Are you working on this airport?

Editing altitude after issue creation

# Airport Priority? (A380, 10000ft+ Runway)

N/A

**Comment by grxninesix** [comment]
Will edit to real altitude according to sky vector

**Comment by grxninesix** [comment]
I didn't find any other number than the actual IF altitude (that are wrong anyways) in a website, i checked many websites and they have set 0, or unknow altitude. it's confusing but i am continuing investigations

**Comment by MajorTomMueller** [comment]
Try 1771ft as a good guess....
;-)

**Comment by grxninesix** [comment]
ok will put this in the file (directly into a push request in GH
