### ISSUE TITLE
KAWG-Washington Municipal Airport-IOWA-USA

### ISSUE THREAD

**Issue by MrMrMan** [InfiniteFlightAirportEditing/Airports#3443]
# Airport Name

Washington Municipal Airport

# Country?

United States

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

None

# Airport Priority? (A380, 10000ft+ Runway)

N/A

**Comment by MrMrMan** [comment]
Sent in for OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48917623-59b92b00-ee4d-11e8-96dc-625ae0dedf10.png)
