### ISSUE TITLE
OASA-Sharana Airport-PAKTIKA-AFGHANISTAN

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#3445]
# Airport Name

Sharana

# Country?

Afghanistan

# Improvements that need to be made?

from scratch

# Are you working on this airport?

yes

# Airport Priority? (A380, 10000ft+ Runway)
low

**Comment by MajorTomMueller** [comment]
done

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48662703-57209500-ea4b-11e8-9a4a-ab2ea25e57dc.png)
