### ISSUE TITLE
SJZA-Cajazeiras Airport-PARAIBA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3448]
# Airport Name

Cajazeiras Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48590660-ff2c4600-e905-11e8-8619-11300b107e58.png)
