### ISSUE TITLE
KCUB

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#345]
Airport seems to be off from satellite image. Even by scooting image to line up with a feature scaling of certain elements is incorrect. (Charlotte). Buildings would be a nice addition.

**Comment by harrymorris** [comment]
Can I take this please?

**Comment by NickArt1342** [comment]
What is the status on this?

**Comment by dushyants19** [comment]
@NickArt1342 he deleted his account, so its open now.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17269673/9b2a9caa-5614-11e6-8ae4-64edeb6750bf.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17269694/1af0dad0-5615-11e6-9495-db8e1c759679.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18019730/18ff5f8c-6ba3-11e6-9fde-0144e3727046.png)
