### ISSUE TITLE
SSRS-Barreirinhas Airport-MARANHAO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3450]
# Airport Name

Barreirinhas Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48651728-db2e3a80-e9c1-11e8-8fe0-c74f4ac9777e.png)
