### ISSUE TITLE
OAZJ-Zaranj-NIMRUZ-AFGHANISTAN

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#3456]
# Airport Name

Zaranj

# Country?

Afghanistan

# Improvements that need to be made?

from scratch

# Are you working on this airport?

finished

# Airport Priority? (A380, 10000ft+ Runway)

uhuh

**Comment by MajorTomMueller** [comment]
done

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48672544-be4a5200-eafc-11e8-8c41-8036f67f92b5.png)
