### ISSUE TITLE
SBUR-Mario de Almeida Franco Airport-MINAS GERAIS-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3459]
# Airport Name

Uberaba, Mario de Almeida Franco Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48676578-3a10c280-eb2e-11e8-8567-367aea29aece.png)
