### ISSUE TITLE
KBOW

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#346]
Hold short spawn points

**Comment by Swang007** [comment]
Runway hold-short spawn points removed.

**Comment by kilt46** [comment]
Adding building detail and spawn points

**Comment by kilt46** [comment]
This one probably needs redone
![image](https://cloud.githubusercontent.com/assets/14023167/12071252/a18f69b6-b067-11e5-811f-fc90cdd18e7d.png)

**Comment by kilt46** [comment]
Airport redesigned

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20610963/77daa59c-b267-11e6-8684-9ac8390f337d.png)
