### ISSUE TITLE
KTWM-Richard B Helgeson Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by danisrils39** [InfiniteFlightAirportEditing/Airports#3460]
# Airport Name

Richard B Helgeson Airport

# Country?

USA

# Improvements that need to be made?

Scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

N/A

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48962155-e5ac7f00-ef41-11e8-9e8a-60abdfd74a1d.png)
