### ISSUE TITLE
SBJA-Regional Sul Airport-SANTA CATARINA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3461]
# Airport Name

Jaguaruna, Regional Sul Airport

# Country?

Brazil

# Improvements that need to be made?

Created from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48683068-fd19ef80-eb70-11e8-80ba-066e170550ae.png)
