### ISSUE TITLE
KFKA-Fillmore County Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by LoganIsLogan13** [InfiniteFlightAirportEditing/Airports#3464]
# Airport Name

Fillmore County Airport

# Country?

United States

# Improvements that need to be made?

Will be redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Neither

**Comment by LoganIsLogan13** [comment]
I don't know if I'm supposed to tell you but I did move the runway to its correct position. So I don't know if the waypoints/navigation around the airport have to be changed or if they were already in the correct spots.

**Comment by moritzbabl** [comment]
If a moved runway has ILS this should be reported in the Navigation repo once the airport got added to the repo by the reviewer

**Comment by LoganIsLogan13** [comment]
Can someone send me a new invitation to the Slack Workspace. My old account got deactivated.

**Comment by brunocr98** [comment]
Send an email to contact@airportediting.com to re-apply. An admin should find your account and reactivate it.

**Comment by LoganIsLogan13** [comment]
Ok. Thank You!

**Comment by moritzbabl** [comment]
@LoganIsLogan13 please accept your invitation to the GitHub team at https://github.com/InfiniteFlightAirportEditing/Airports/invitations

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/49686660-6bd9d100-fabd-11e8-8c34-feadf38a7e0b.png)
