### ISSUE TITLE
KOPF-Opa-Locka Executive Airport-FLORIDA-USA

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#347]
has hold short spawn points

**Comment by Swang007** [comment]
Runway hold-short spawn points removed.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20627733/971118e4-b2e7-11e6-8641-899bb86a0509.png)

**Comment by RyanEpps** [comment]
Airport needs reworked up to new standards and additional spawns.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45653362-585e3180-ba9d-11e8-810e-bc8adbd5e8c3.png)
