### ISSUE TITLE
WN08-Kendall Airstrip-WASHINGTON-USA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3472]
# Airport Name

< Kendall Airstrip >

# Country?

< USA >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/49049804-29072780-f1a6-11e8-8f87-65e242e19a80.png)
