### ISSUE TITLE
HUAR-Arua National Airport-ARUA-UGANDA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3473]
# Airport Name

< Arua National Airport >

# Country?

< Uganda >

# Improvements that need to be made?

< Redone - Elevation Issue >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by Balloonchaser** [comment]
Sent In For Review :)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/49051425-6de28c80-f1ad-11e8-9377-28f87aad6f0b.png)
