### ISSUE TITLE
LFRS-Nantes Atlantique Airport-LOIRE-FRANCE

### ISSUE THREAD

**Issue by royfr83** [InfiniteFlightAirportEditing/Airports#3478]
# Airport Name

Nantes Atlantique

# Country?

France

# Improvements that need to be made?

From scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by royfr83** [comment]
Pending OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51086407-55eaac00-170c-11e9-91d4-b6465d4a8ce8.png)
