### ISSUE TITLE
KFTG 

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#348]
Very basic airport. Needs rework. Also please use correct spelling of Hangar!

**Comment by cboisselier** [comment]
Basic but huge airport! There was a full part of hangars and also a part of ramp missing + all taxi lines. Working on it atm.

**Comment by dushyants19** [comment]
Done it @cboisselier ?

**Comment by Swang007** [comment]
This airport was never committed. Is this still being worked on?

**Comment by freddiefrogs** [comment]
I'll do it.

**Comment by freddiefrogs** [comment]
It seems he did do the airport. It looks complete. Will give it a proper check tomorrow though.

**Comment by IceBlue02** [comment]
@freddiefrogs is it ok?

**Comment by samuelandersson** [comment]
@freddiefrogs How is this going?

**Comment by freddiefrogs** [comment]
@cboisselier did this.

**Comment by samuelandersson** [comment]
Okay, cool.

**Comment by freddiefrogs** [comment]
I'm confused though. If it was never committed, then how come the copy idownloaded looked pretty complete?

**Comment by NickArt1342** [comment]
I guess it was committed eventually.

**Comment by samuelandersson** [comment]
Latest commit was Feb 2.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20648650/4e7f8520-b472-11e6-8eac-b8013dc14e9d.png)
