### ISSUE TITLE
RCSS-Taipei Songshan Airport-TAIWAN-TAIWAN

### ISSUE THREAD

**Issue by aads552** [InfiniteFlightAirportEditing/Airports#3484]
# Airport Name

Taipei SongShan Airport

# Country?

TWIWAN

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

yes

# Airport Priority? (A380, 10000ft+ Runway)

World Capitals

**Comment by aads552** [comment]
sent for approval

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50320324-6a32e480-0491-11e9-911c-e4738b35d09d.png)
