### ISSUE TITLE
OIKQ-Ghesm Island Airport-HORMOZGAN-IRAN

### ISSUE THREAD

**Issue by cboisselier** [InfiniteFlightAirportEditing/Airports#349]
PLEASE REDRAW ME

**Comment by kilt46** [comment]
is this an Airport Edit or an ATC edit?

**Comment by cboisselier** [comment]
ATC

**Comment by dushyants19** [comment]
Continue discussion here -> #130

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26276891/d3d15dfe-3d46-11e7-83aa-5637cd052a91.png)
