### ISSUE TITLE
KLIC-Limon Municipal Airport-COLORADO-USA

### ISSUE THREAD

**Issue by MrMrMan** [InfiniteFlightAirportEditing/Airports#3491]
# Airport Name

Limon Municipal Airport

# Country?

United States

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

None

**Comment by MrMrMan** [comment]
Sent in for OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51075300-3e012280-164f-11e9-978e-50d8fb3927b1.png)
