### ISSUE TITLE
1IS3-Cribbet Airstrip-ILLINOIS-USA

### ISSUE THREAD

**Issue by TrentPierce** [InfiniteFlightAirportEditing/Airports#3492]
![image](https://user-images.githubusercontent.com/14023167/108629700-cc4b5380-7426-11eb-98e9-2e78c204227e.png)

**Comment by TrentPierce** [comment]
I completed the update and sent the apt.dat to contact@airportediting.com

**Comment by MajorTomMueller** [comment]
Hello @TrentPierce are you still around?

**Comment by TrentPierce** [comment]
Yes I am

**Comment by MajorTomMueller** [comment]
@moritzbabl or @RyanEpps could you please check the status of this?

**Comment by RyanEpps** [comment]
No submission in sight. Please reapply on the Infinite Flight Community to stay assigned to this issue.
