### ISSUE TITLE
KHGR-Hagerstown Regional Airport-MARYLAND-USA

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#3494]
# Airport Name

Hagerstown Regional Airport

# Country?

USA

# Improvements that need to be made?

from scratch

# Are you working on this airport?

no

# Airport Priority? (A380, 10000ft+ Runway)

fabric site of Fairchild's A-10

**Comment by MajorTomMueller** [comment]
good image quality in Google Maps and Bing
FAA Data:
https://nfdc.faa.gov/nfdcApps/services/ajv5/airportDisplay.jsp?airportId=KHGR
Aerodrom diagramm:
https://aeronav.faa.gov/d-tpp/1812/05114ad.pdf#nameddest=(HGR)

**Comment by HiFlyerBwi** [comment]
I will work on this airport.

**Comment by MajorTomMueller** [comment]
@HiFlyerBwi you are already assigned to 3 Airports, please wait till one passed the review process.

**Comment by MajorTomMueller** [comment]
![KHGR-git](https://user-images.githubusercontent.com/26853210/56080914-5546dc00-5e07-11e9-9422-a6b12648bd46.jpg)
