### ISSUE TITLE
NZRO-Rotorua Airport-BAY OF PLENTY-NEW ZEALAND

### ISSUE THREAD

**Issue by AussieLuke** [InfiniteFlightAirportEditing/Airports#3495]
# Airport Name

Rotorua Regional Airport

# Country?

New Zealand 

# Improvements that need to be made?

Redone from scratch 

# Are you working on this airport?

Yes, I am

# Airport Priority? (A380, 10000ft+ Runway)

N/A

**Comment by MajorTomMueller** [comment]
Officials:
http://www.aip.net.nz/pdf/NZRO_51.1_51.2.pdf

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55997959-015eba80-5c82-11e9-8b2c-85a0d2e0c708.png)
