### ISSUE TITLE
SBAF-Afonsos Air Base-RIO DE JANEIRO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3496]
# Airport Name

Base Aerea dos Afonsos

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/49329661-11ce8e00-f548-11e8-9459-89b9c09d41fc.png)

**Comment by MBeringuy** [comment]
Spawn renamed.
