### ISSUE TITLE
SAZN-Neuquen Presidente Peron International Airport-NEUQUEN-ARGENTINA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3497]
# Airport Name

Presidente Peron Airport

# Country?

Argentina

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
Suggested current parking 5-Oct-18
![image](https://user-images.githubusercontent.com/14023167/49329729-1f384800-f549-11e8-96a9-ffd2b14533e3.png)

**Comment by MBeringuy** [comment]
Parking corrected.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/49341602-583dee80-f615-11e8-9c7c-eb7d852692bb.png)
