### ISSUE TITLE
SCQP-La Araucania Airport-ARAUCANIA-CHILE

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3498]
# Airport Name

La Araucania Intl Airport

# Country?

Chile

# Improvements that need to be made?

Created from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/49328550-5a7e4b00-f538-11e8-8ff0-aae153aac2ba.png)
