### ISSUE TITLE
KTMK-Tillamook Airport-OREGON-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#35]

**Comment by dushyants19** [comment]
Should this be redone?

**Comment by dushyants19** [comment]
Hold spawns removal
Changing the line attribute of buildings to none

**Comment by dushyants19** [comment]
approved by Jonathan

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20868532/5b7c1f34-ba23-11e6-972d-b438dc59f17f.png)

**Comment by Czechoslovaki** [comment]
![image](https://user-images.githubusercontent.com/51279558/96948646-01f12780-149b-11eb-988a-392aa13b12e5.png)
