### ISSUE TITLE
SSMT-Mostardas Airport-RIO GRANDE DO SUL-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3500]
# Airport Name

Mostardas Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/49341169-42c5c600-f60f-11e8-9ebf-29cca3b1fbd3.png)
