### ISSUE TITLE
SBCR-Corumba International Airport-MATO GROSSO DO SUL-BRAZIL

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Airports#3507]
# Airport Name

< Corumba Intl >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52163947-84c2c500-26af-11e9-885b-e7d7e5f5db94.png)
