### ISSUE TITLE
SNVR-Aeroclube da Bahia Airport-BAHIA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3509]
# Airport Name

Aeroclube da Bahia Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/49676904-72c2fe00-fa41-11e8-90b9-9e26df4cff05.png)
