### ISSUE TITLE
KBUR-Bob Hope Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#351]
SoCal- This one could do with some buildings

**Comment by samuelandersson** [comment]
Doing that, adding buildings, most likely gonna fix the taxi lines so they are snapped to each other.

**Comment by samuelandersson** [comment]
Ready. Added buildings and snapped some taxi lines, due to  frame lag it was hard to continue.

**Comment by samuelandersson** [comment]
This is a messy airport, most lines need snapping.  I have added a temporary fix as per forum request:

https://community.infinite-flight.com/t/kbur-missing-taxiway/51220?u=samuel123abc

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/c04850d41663f4e1a629b4ef559e189350291ac9)

**Comment by kilt46** [comment]
Airport totally reworked

**Comment by IFAEpat** [comment]
Has this been committed? Re-cloned repo to see the fixes, previous version still in file and I don't see a commit in `#tracking` on Slack

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18617535/6c91353e-7d97-11e6-90ed-332002f1dcbb.png)

**Comment by jakey200** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/80317579-0635d400-87db-11ea-8d92-2cb34f98c339.jpg)
