### ISSUE TITLE
SISG-Aeroclube de Sergipe Airport-SERGIPE-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3510]
# Airport Name

Aeroclube de Sergipe Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/49685696-7db37800-faad-11e8-85d5-2a7cd3a5bfb4.png)

**Comment by kilt46** [comment]
SNAU = https://pergamum.anac.gov.br/arquivos/PA2017-0370.pdf
This should be SISG

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103443211-788c6d00-4c22-11eb-882f-3582204a56b4.png)
