### ISSUE TITLE
SBUG-Rubem Berta Intl Airport-RIO GRANDE DO SUL-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3514]
# Airport Name

Rubem Berta Intl Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/49686068-c458a080-fab4-11e8-8c4f-7295b5062608.png)
