### ISSUE TITLE
KORB-Orr Regional Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by danisrils39** [InfiniteFlightAirportEditing/Airports#3516]
# Airport Name

Orr Regional Airport

# Country?

USA

# Improvements that need to be made?

Scratch

# Are you working on this airport?

Yep

# Airport Priority? (A380, 10000ft+ Runway)

N/A

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/49969967-8eba1a00-feef-11e8-9a85-355cf04efacb.png)
