### ISSUE TITLE
VRMT-Kaadedhdhoo Airport-GAAFU DHAALU ATOLL-MALDIVES

### ISSUE THREAD

**Issue by gsherbert** [InfiniteFlightAirportEditing/Airports#3517]
# Airport Name
Kaadedhdhoo Airport

# Country?

Maldives

# Improvements that need to be made?

Redo

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low Priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/49971553-86181280-fef4-11e8-8f5d-ae63ad625726.png)
