### ISSUE TITLE
SNKI-Cachoeiro do Itapemirim Airport-ESPIRITO SANTO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3518]
# Airport Name

Cachoeiro do Itapemirim Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/49833532-60a5d000-fd5f-11e8-8fc7-234ed7ced6d8.png)
