### ISSUE TITLE
KREI

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#352]
So Cal. Could do with some building detail

**Comment by samuelandersson** [comment]
Well let's add buildings then. Doing exactly that.

**Comment by samuelandersson** [comment]
Added buildings, fixed taxi line system.

**Comment by kilt46** [comment]
Buildings added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20652321/b6be4352-b4bc-11e6-94b5-7657f851e429.png)
