### ISSUE TITLE
KBDE-Baudette International Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by danisrils39** [InfiniteFlightAirportEditing/Airports#3520]
# Airport Name

Baudette International Airport

# Country?

USA

# Improvements that need to be made?

Scratch

# Are you working on this airport?

Yep

# Airport Priority? (A380, 10000ft+ Runway)

N/A

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/49970285-67b01800-fef0-11e8-86de-833d9330b579.png)
