### ISSUE TITLE
AYPY-Port Moresby Jacksons Airport-CENTRAL-PAPUA NEW GUINEA

### ISSUE THREAD

**Issue by Infiniteflightaviation** [InfiniteFlightAirportEditing/Airports#3521]
Airport name?

Port Moresby Jackson Intl

Country?

Indonesia

 Improvements that need to be made?

< Needs gates and taxi lines >

# Are you working on this airport?

< yes >

# Airport Priority? (A380, 10000ft+ Runway)

< N/A >

**Comment by RyanEpps** [comment]
Member inactive, up for grabs

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56086893-b41b4e00-5e25-11e9-81e7-36830b57b276.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114534334-80da4800-9c14-11eb-9b8a-03d25332a508.png)
