### ISSUE TITLE
SSOG-Arapongas Airport-PARANA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3522]
# Airport Name

Arapongas Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/49837240-5a1d5580-fd6b-11e8-9a94-c0ac73108e51.png)
