### ISSUE TITLE
KGNB-Granby/Grand County Airport-COLORADO-USA

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#3523]
# Airport Name

< Granby/Grand County Airport >

# Country?

< United States >

# Improvements that need to be made?

< From scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50376980-0caaaf00-05db-11e9-8219-43f28ebeb6af.png)

**Comment by HiFlyerBwi** [comment]
Airport accepted and in newest update

**Comment by dushyants19** [comment]
I just accepted it 👀

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51074776-a993c180-1648-11e9-833d-687826584dcd.png)
