### ISSUE TITLE
13Y-Littlefork Municipal/Hanover Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by danisrils39** [InfiniteFlightAirportEditing/Airports#3524]
# Airport Name
Littlefork Municipal/Hanover Airport
# Country?
US of A
# Improvements that need to be made?
Scratch
# Are you working on this airport?
Yep
# Airport Priority? (A380, 10000ft+ Runway)
N/A

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/49971004-a9da5900-fef2-11e8-9791-41764591b3d2.png)
