### ISSUE TITLE
72Y-Northwest Angle Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by danisrils39** [InfiniteFlightAirportEditing/Airports#3527]
# Airport Name

Northwest Angle 

# Country?

USA

# Improvements that need to be made?

Scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

N/A

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50194769-ed253500-0301-11e9-8404-0613b395b794.png)
