### ISSUE TITLE
KRRT-Warroad International Memorial Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by danisrils39** [InfiniteFlightAirportEditing/Airports#3528]
# Airport Name

Warroad International Memorial Airport

# Country?

USA

# Improvements that need to be made?

Scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

N/A

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50376948-65c61300-05da-11e9-8f58-de1df80e1710.png)
