### ISSUE TITLE
RCMT-Beigan Airport-TAIWAN-TAIWAN

### ISSUE THREAD

**Issue by aads552** [InfiniteFlightAirportEditing/Airports#3529]
# Airport Name

Beigan Airport

# Country?

TAIWAN

# Improvements that need to be made?

from scratch

# Are you working on this airport?

yes

# Airport Priority? (A380, 10000ft+ Runway)

no

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50622257-5e9fde80-0ed1-11e9-9daa-9ffe6571417f.png)
