### ISSUE TITLE
YSBK-Sydney Bankstown Airport-NEW SOUTH WALES-AUSTRALIA

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#353]
Sydney - Could do with more Spawn Points

**Comment by IceBlue02** [comment]
Will do.

**Comment by BVRAU** [comment]
Was this complete? If not I will do this

**Comment by BVRAU** [comment]
DM'd you, hear from you soon!

**Comment by IceBlue02** [comment]
BVR taking this one over.

**Comment by NickArt1342** [comment]
Where did at @BVRAU go? Is he still doing it? I can't assign it to him somehow.

**Comment by BVRAU** [comment]
I'm still doing it, I've just been extremely busy

**Comment by dushyants19** [comment]
@BVRAU Assign yourself please.

**Comment by BVRAU** [comment]
@dushyants19 If I could assign myself I would've already, But I cant't.

**Comment by dushyants19** [comment]
@BVRAU are you on slack? tell your email to @carmichaelalonso

**Comment by Swang007** [comment]
@BVRAU Does this mean you won't be doing this airport anymore?

**Comment by BVRAU** [comment]
Yes, that is correct

**Comment by Swang007** [comment]
@IceBlue02 or @NickArt1342? This one is up for grabs

**Comment by dushyants19** [comment]
I'll do it

**Comment by dushyants19** [comment]
I need parking charts for this, anyone have charts?

**Comment by BVRAU** [comment]
Try CASA, they might have information

**Comment by BVRAU** [comment]
Or Airservices Australia

**Comment by dushyants19** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20651584/bd0b402a-b4ad-11e6-9063-e9d74c1a506e.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102824545-ad86fd00-43a2-11eb-95e9-6ef95955a874.png)
