### ISSUE TITLE
PABA-Barter Island-ALASKA-USA

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#3532]
Redo airport

ERROR: Duplicate ramp start name: South Heavy Apron is   already defined on line 1981

**Comment by MajorTomMueller** [comment]
Hi @kilt46, how do I came to the honour to be assigned?

**Comment by MajorTomMueller** [comment]
https://www.airservicesaustralia.com/aip/current/dap/PEAAD01-140_08NOV2018.pdf

**Comment by MajorTomMueller** [comment]
... not on my List ...
Good quality Imagery. No Docking Chart, no Runway coordinates...
... not interested.

**Comment by SpaceGuru01** [comment]
I'll take this one if that's alright

**Comment by AussieLuke** [comment]
I'll take this, thanks

**Comment by kilt46** [comment]
![Uploading image.png…]()
