### ISSUE TITLE
7Y9-Big Falls Municipal Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by danisrils39** [InfiniteFlightAirportEditing/Airports#3534]
# Airport Name

Big Falls Municipal Airport

# Country?

USA

# Improvements that need to be made?

Scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

N/A

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50194438-89e6d300-0300-11e9-9d97-22ba9404946f.png)
