### ISSUE TITLE
KJKA-Jack Edwards National Airport-ALABAMA-USA

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#3537]
# Airport Name

Jack Edwards National Airport

# Country?

United States of America

# Improvements that need to be made?

Needs to be re-made from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

None

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51439417-73c18f00-1c7f-11e9-8fe5-f1861ee3ee07.png)
