### ISSUE TITLE
RKJK-Gunsan Airport-JEOLLABUK-DO-SOUTH KOREA

### ISSUE THREAD

**Issue by Session-IFK** [InfiniteFlightAirportEditing/Airports#3538]
# Airport Name

Gunsan Airport

# Country?

South Korea

# Improvements that need to be made?

redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

NoNoNo

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51093161-118bfa00-1766-11e9-9b9a-57a2dab576b1.png)
