### ISSUE TITLE
RJAH-Hyakuri AirBase/Ibaraki Airport-IBARAKI-JAPAN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#3539]
# Airport Name

< Hyakuri Airbase/ Ibaraki airport>

# Country?

< Japan >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50191797-04115a80-02f5-11e9-9a7a-2a086eb0caa3.png)
