### ISSUE TITLE
FPST-Sao Tome Airport-SAO TOME-SAO TOME AND PRINCIPE

### ISSUE THREAD

**Issue by gsherbert** [InfiniteFlightAirportEditing/Airports#3540]
# Airport Name

Sao Tome Airport

# Country?

Sao Tome and Principe

# Improvements that need to be made?

Full redo

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

World Capital

**Comment by MajorTomMueller** [comment]
Hi, @gsherbert 
you might want to join a image of this one in 
https://community.infiniteflight.com/t/infinite-flight-global-airport-tracking-thread/
it was requested once and it is always god to do some PR for our work.

**Comment by gsherbert** [comment]
Will do.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50722317-c9e4de80-1092-11e9-90d4-5ac79425ec05.png)
