### ISSUE TITLE
CYTR-CFB Trenton-ONTARIO-CANADA

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#3541]
# Airport Name

CFB Trenton

# Country?

Canada

# Improvements that need to be made?

from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

10k exact

**Comment by MajorTomMueller** [comment]
![cytr-git](https://user-images.githubusercontent.com/26853210/50386760-158ba580-06ed-11e9-81fe-67eaf5b9f103.jpg)

**Comment by kilt46** [comment]
Duplicate spawn renamed

**Comment by MajorTomMueller** [comment]
Ups, wich one @kilt46 ?
