### ISSUE TITLE
KNYL-MCAS Yuma/Yuma International Airport-ARIZONA-USA

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#3544]
♻️

**Comment by HiFlyerBwi** [comment]
Airport was recently closed.

**Comment by kilt46** [comment]
File not yet uploaded

**Comment by moritzbabl** [comment]
airport closed / removed from repo

**Comment by kilt46** [comment]
Recycling Issue

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/86468868-eb616d80-bcfd-11ea-9cab-c2918bcbf38c.png)
