### ISSUE TITLE
VIDX-Hindon AFS-UTTAR PRADESH-INDIA 

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#3545]
# Airport Name

Hindon AFS

# Country?

India 

# Improvements that need to be made?

from scratch, difficult Google imagery, not for beginners.

# Are you working on this airport?

No

# Airport Priority? (A380, 10000ft+ Runway)

none

https://en.wikipedia.org/wiki/Hindon_Air_Force_Station

**Comment by MajorTomMueller** [comment]
![vidx-git](https://user-images.githubusercontent.com/26853210/50471967-2c651d00-09b7-11e9-8e8c-fc8dbc4f867f.jpg)

Airport becomes a Civil-Regional Enclave in Q1 2019, needs to be revised when AIP or Imaging is available.

**Comment by kilt46** [comment]
NOT loaded into the library!
![image](https://user-images.githubusercontent.com/14023167/50531594-1bf59500-0ad2-11e9-97f1-fc60e634b9dd.png)

**Comment by MajorTomMueller** [comment]
Should be in now, thank you @kilt46
