### ISSUE TITLE
KSEZ-Sedona Airport-ARIZONA-USA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3548]
# Airport Name

< Sedona Airport >

# Country?

< USA >

# Improvements that need to be made?

< Remade from scratch  >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None>

**Comment by Balloonchaser** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51085479-92fc7180-16ff-11e9-8f1b-3db9e99111ce.png)
