### ISSUE TITLE
EKRD-Randers Airport-MIDTJYLLAND-DENMARK

### ISSUE THREAD

**Issue by cboisselier** [InfiniteFlightAirportEditing/Airports#355]
All hold short lines are reported to be backwards

**Comment by kilt46** [comment]
This appears to be true
![image](https://cloud.githubusercontent.com/assets/14023167/12069244/7db24e46-afea-11e5-9076-e285efa129a0.png)

**Comment by kilt46** [comment]
All Runway hold lines rotated to the correct orientation

**Comment by turkish1941** [comment]
I would like to make this, how can i say being redone

**Comment by turkish1941** [comment]
finished 2 days ago

**Comment by dushyants19** [comment]
Approved by Henrik. [Commit](https://github.com/InfiniteFlightAirportEditing/Airports/blob/b7a4579bd54b2eeb6f3db84e3c9e03c166f6e198/Denmark/EKRD/apt.dat)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20606867/84419814-b239-11e6-9ce9-437b43190009.png)
