### ISSUE TITLE
FNMO-Welwitschia Mirabilis Intl Airport-NAMIBE-ANGOLA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3550]
# Airport Name

Welwitschia Mirabilis Intl Airport

# Country?

Angola

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50518869-af50ab00-0a7d-11e9-8fd9-6d8c91c07688.png)
