### ISSUE TITLE
VVPQ-Phu Quoc Airport-KIEN GIANG-VIETNAM

### ISSUE THREAD

**Issue by IFUA2003** [InfiniteFlightAirportEditing/Airports#3551]
# Airport Name

Phu Quoc International Airport

# Country?

 Vietnam

# Improvements that need to be made?

 The airport hasn't been added

# Are you working on this airport?

 No 

# Airport Priority? (A380, 10000ft+ Runway)

 None

**Comment by brunocr98** [comment]
If you create an issue we would expect you to do this airport, this is not a place to put your wishlist items. If that's the case, the chances of someone taking this airports for redo are slim. The best thing to do is joining our team and do it yourself.

**Comment by MajorTomMueller** [comment]
Wishes, wishes, ...
Give me a reason beyond its Christmas Time...

https://en.wikipedia.org/wiki/Phu_Quoc_International_Airport
https://vau.aero/navdb/chart/VVPQ.pdf

**Comment by IFUA2003** [comment]
Vietnam's airport is very few in the game, there are airports that haven’t been added, so i just request you to remake some airports if you can, i don’t compel you :( it’s a request

**Comment by MajorTomMueller** [comment]
You couldn't compel any of the volunteers in here...
Argues are insufficient for me to do it. So you have to hope for someone else to deviate from his agenda.

**Comment by sirhc1** [comment]
I’ll take this one.

**Comment by IFUA2003** [comment]
> 
> 
> I’ll take this one.

Thank you so much!

**Comment by sirhc1** [comment]
still waiting for peer review...

**Comment by sirhc1** [comment]
sent to OR, hoping it will pass

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56327200-fbb01b80-613e-11e9-9ef5-93962c3956c8.png)
