### ISSUE TITLE
SBTT-Tabatinga Intl Airport-AMAZONAS-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3553]
# Airport Name

Tabatinga Intl Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50519401-5df5eb00-0a80-11e9-8bcf-3dfd79fb2f85.png)
