### ISSUE TITLE
FNUE-Luena Airport-MOXICO-ANGOLA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3554]
# Airport Name

Luena Airport

# Country?

Angola

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

GP2 (10000ft+ Runway)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50518413-1fa9fd00-0a7b-11e9-9022-79f174102ad9.png)
