### ISSUE TITLE
KGYR-Phoenix Goodyear Airport-ARIZONA-USA

### ISSUE THREAD

**Issue by chrisindfw** [InfiniteFlightAirportEditing/Airports#3556]
# Airport Name

Phoenix Goodyear Airport

# Country?

USA

# Improvements that need to be made?

Redo

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

8500'

**Comment by RyanEpps** [comment]
Member inactive, up for grabs

**Comment by chrisindfw** [comment]
I'm still working on it. Just been busy with moderating. This is Tyler's airport so he has been giving me some advice on some of the items that don't show on imagery.

**Comment by RyanEpps** [comment]
Give us an update in June/July if still not done.

**Comment by chrisindfw** [comment]
Submitted for review.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/58842369-395ff980-8644-11e9-9b29-60dd796edd0f.jpg)
