### ISSUE TITLE
1IS2-Triple Creek Airstrip-ILLINOIS-USA

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#3558]
![image](https://user-images.githubusercontent.com/14023167/108629023-9c4e8100-7423-11eb-8f22-a6cafa7557d0.png)

**Comment by Martijn-Decates** [comment]
how far are you. because I would like to make the airport. if you are not going to make the airport anymore I would like to know!

**Comment by pharrm** [comment]
Hi Martijn,
I’m probably 50% done. I’ll try to wrap it up this weekend.

**Comment by Martijn-Decates** [comment]
Thank you i love this airfield!!

**Comment by MajorTomMueller** [comment]
Hey @Martijn-Decates still around and interested? Looks like the guy gave up...
