### ISSUE TITLE
FNME-Comandante Kwenha Airport-CUANDO CUBANGO-ANGOLA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3559]
# Airport Name

Menonge, Comandante Kwenha Airport

# Country?

Angola

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

GP2

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50539085-cc4db280-0b3f-11e9-96b0-c45b10b037d3.png)
