### ISSUE TITLE
YGDO

### ISSUE THREAD

**Issue by dushyants19** [InfiniteFlightAirportEditing/Airports#356]
Sydney

**Comment by dushyants19** [comment]
Runway 36 has a heading of 18X and runway 18 has a heading of 35X (numbers are messed up)

**Comment by dushyants19** [comment]
Fixed

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20651644/92ff6eae-b4ae-11e6-83b1-acf51f38f6e7.png)
