### ISSUE TITLE
LGPZ-Aktion-Preveza Airport-DYTIKI ELLADA-GREECE

### ISSUE THREAD

**Issue by Moonlit21** [InfiniteFlightAirportEditing/Airports#3560]
# Airport Name

Aktion-Preveza Airport

# Country?

Greece

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

Affirmative

# Airport Priority? (A380, 10000ft+ Runway)

Negative

**Comment by liamkirky** [comment]
Hey, are you editing this airport? If not I'll happily take it as my laptop should be able to handle it.

**Comment by Moonlit21** [comment]
Yep go ahead and take it.

My computer is broken & will be for the next few weeks so won’t be able to edit for a while.

**Comment by benjwri** [comment]
It has been agreed between me and @liamkirky that I'll be taking this. However, I'm not sure if it can be assigned right now as I have 3 assigned to me already, although 2 are in OR and one is in PR.

**Comment by benjwri** [comment]
All 3 of my airports are in OR, please could I be assigned.

**Comment by benjwri** [comment]
One of my previous airports has passed through OR, please could I be assigned.

**Comment by benjwri** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/60142149-f5699b80-978e-11e9-821b-f410a49128c5.jpg)

**Comment by MajorTomMueller** [comment]
New parking layout available

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/71787471-f8273200-2ff6-11ea-9284-a3b2c051454c.jpg)
