### ISSUE TITLE
FNKU-Kuito Airport-BIE-ANGOLA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3563]
# Airport Name

Kuito Airport

# Country?

Angola

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50548406-86611f00-0c11-11e9-96a9-3975340fd4d8.png)
