### ISSUE TITLE
ZKWS-Wonsan Kalma International Airport-GANGWON-DO-NORTH KOREA

### ISSUE THREAD

**Issue by Session-IFK** [InfiniteFlightAirportEditing/Airports#3564]
# Airport Name

Wonsan Kalma International Airport

# Country?

North Korea

# Improvements that need to be made?

New Airport (Not in IF Database!)

# Are you working on this airport?

Yes~

# Airport Priority? (A380, 10000ft+ Runway)

15L/33R = 11,483ft , 15R/33L = 10,252ft  (10000ft+)

**Comment by MajorTomMueller** [comment]
15L/32R is not finished according to my research. Please refrain from adding this as runway, just draw it as twy like it is in recent sat images.

**Comment by Session-IFK** [comment]
Okay @MajorTomMueller , I'll add 15L/33R as TWY.

**Comment by Session-IFK** [comment]
Um.. @MajorTomMueller , I can't find any chart of ZKWS, Do you have a chart of ZKWS??

**Comment by MajorTomMueller** [comment]
Unfortunately I haven’t found one yet. You might want to ask kilt via DM in our slack.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51647315-de095680-1f41-11e9-97bf-4f683f0cc023.png)
