### ISSUE TITLE
SNOG-Ceara Mirim Airport-RIO GRANDE DO NORTE-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3567]
# Airport Name

Ceara Mirim Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50563750-48352f80-0ce5-11e9-9a76-55aacd6c18d0.png)
