### ISSUE TITLE
PHFS-French Frigate Shoals-HAWAII-USA

### ISSUE THREAD

**Issue by danisrils39** [InfiniteFlightAirportEditing/Airports#3568]
# Airport Name

FRENCH FRIGATE SHOALS 

# Country?

USA

# Improvements that need to be made?

The airport is misaligned and full rework

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

N/A

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51085538-83c9f380-1700-11e9-8854-ee16ffa3c451.png)
