### ISSUE TITLE
EBKH

### ISSUE THREAD

**Issue by HenrikBerg02** [InfiniteFlightAirportEditing/Airports#357]
The one and only parking spot at this airport is "Custom Starting Position". I would suggest to remove or rename that and add a couple more parking locations. Remember to look at schematics before making parking spots.

**Comment by kilt46** [comment]
Runway realigned. 3 spawn points

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20466583/ab2e92ac-af3b-11e6-9c00-b084e45cf5ea.png)
