### ISSUE TITLE
RCQC-Penghu Airport-TAIWAN-TAIWAN

### ISSUE THREAD

**Issue by aads552** [InfiniteFlightAirportEditing/Airports#3571]
# Airport Name

Penghu airport

# Country?

Taiwan

# Improvements that need to be made?

from scratch

# Are you working on this airport?

yes

# Airport Priority? (A380, 10000ft+ Runway)

no

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51564593-521a0080-1e55-11e9-9eb3-24abf7db57af.png)
