### ISSUE TITLE
SGES-Guarani International Airport-ALTO PARANA-PARAGUAY

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3572]
# Airport Name

Guarani Intl Airport

# Country?

Paraguay

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

GP2

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51075833-9851b180-1656-11e9-835d-6a75f4797e6f.png)
