### ISSUE TITLE
VRMR-Fuvahmulah Airport-FUVAHMULAH-MALDIVES

### ISSUE THREAD

**Issue by gsherbert** [InfiniteFlightAirportEditing/Airports#3573]
# Airport Name

Fuvahmulah Airport

# Country?

Maldives

# Improvements that need to be made?

Make from scratch- New to the repo

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low Priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51077397-0785d080-166c-11e9-90ab-a5cf3eefc664.png)
