### ISSUE TITLE
RJOH-Miho AirBase/Yonago Airport-TOTTORI-JAPAN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#3577]
# Airport Name

< Miho AirBase/Yonago Airport >

# Country?

< JAPAN >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51076500-c3400380-165e-11e9-8661-bd2b4757c770.png)
