### ISSUE TITLE
EBGB

### ISSUE THREAD

**Issue by HenrikBerg02** [InfiniteFlightAirportEditing/Airports#358]
The only parking spot at this airport is "Custom Starting Point". If someone has time, add some more.

**Comment by NickArt1342** [comment]
Gates added: I do not see any potential in this airport in terms of design though.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20466548/0a2b695c-af3b-11e6-9b41-848420c7b0a7.png)
