### ISSUE TITLE
KMLS-Frank Wiley Field-MONTANA-USA

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#3584]
# Airport Name

Frank Wiley Field

# Country?

USA

# Improvements that need to be made?

From Scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

None

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51439581-390d2600-1c82-11e9-85c3-d1ff8f431c3b.png)
