### ISSUE TITLE
SNVC-Vicosa Airport-MINAS GERAIS-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3587]
# Airport Name

Vicosa Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51067536-cbedf680-15d8-11e9-83a8-b424189e7186.png)
