### ISSUE TITLE
PTRO-Babelthuap Airport-BABELTHUAP-PALAU

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3588]
# Airport Name

Babelthuap Airport

# Country?

Palau

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51078604-5daf3f80-167d-11e9-98aa-f857479226e7.png)
