### ISSUE TITLE
LGKV-Kavala Alexander the Great Airport-MAKEDONIA-GREECE

### ISSUE THREAD

**Issue by Moonlit21** [InfiniteFlightAirportEditing/Airports#3589]
# Airport Name

Kavala Alexander the Great Airport

# Country?

Greece

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

Affirmative

# Airport Priority? (A380, 10000ft+ Runway)

No Priority

**Comment by Moonlit21** [comment]
Was away for a while, beginning work on this again.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/75917777-4ca12f00-5e39-11ea-9cb1-8bfabcc90811.jpg)
