### ISSUE TITLE
VRNT-Thimarafushi Airport-THIMARAFUSHI-MALDIVES

### ISSUE THREAD

**Issue by gsherbert** [InfiniteFlightAirportEditing/Airports#3591]
# Airport Name

Thimarafushi Airport

# Country?

Maldives

# Improvements that need to be made?

Redo from scratch, new to repo

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low Priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51092959-6712d780-1763-11e9-894c-fc57f9044292.png)
