### ISSUE TITLE
KMRB-Eastern West Virginia Regional Airport-VIRGINIA-USA

### ISSUE THREAD

**Issue by guzekman** [InfiniteFlightAirportEditing/Airports#3592]
# Airport Name

Eastern West Virginia Regional Airport
Shepherd Field Air National Guard Base

# Country?

United States 

# Improvements that need to be made?

redoing from autogen

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low Priority

**Comment by MajorTomMueller** [comment]
Recycled, please do not abuse the repository for suggestions. If you want to work with us join the team as described in the IFC

**Comment by MajorTomMueller** [comment]
![kmrb-git](https://user-images.githubusercontent.com/26853210/51044594-c507b980-15c1-11e9-8cf1-1259e0e1e857.jpg)
