### ISSUE TITLE
KTIK-Tinker Air Force Base-OKLAHOMA-USA

### ISSUE THREAD

**Issue by guzekman** [InfiniteFlightAirportEditing/Airports#3593]
♻️

**Comment by MajorTomMueller** [comment]
Recycled, please do not abuse the repository for suggestions. If you want to work with us join the team as described in the IFC

**Comment by MajorTomMueller** [comment]
![ktik](https://user-images.githubusercontent.com/26853210/53679807-fbb0a500-3cd1-11e9-8b20-00c17123eba5.jpg)
