### ISSUE TITLE
FIMR-Plaine Corail Airport-RODRIGUEZ-MAURITIUS

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3594]
# Airport Name

Plaine Corail Airport

# Country?

Mauritius

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51079761-dd93d480-1692-11e9-8752-77cab14f1d9a.png)
