### ISSUE TITLE
KDKB-De Kalb Municipal Airport-Illinois-USA

### ISSUE THREAD

**Issue by guzekman** [InfiniteFlightAirportEditing/Airports#3595]
# Airport Name

Walla Walla Regional Airport 

# Country?

USA 

# Improvements that need to be made?

Add taxiways and airport in general 

# Are you working on this airport?

I am 

# Airport Priority? (A380, 10000ft+ Runway)

Low Priority

**Comment by guzekman** [comment]
working on it

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/88463184-9a651500-ce76-11ea-82f0-3afcc26d20b1.png)
