### ISSUE TITLE
MTCH-Cap Haitien International Airport-NORD-HAITI

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3596]
# Airport Name

Cap Haitien Intl Airport

# Country?

Haiti

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51080012-2ea6c700-1699-11e9-8804-262f363752dc.png)
