### ISSUE TITLE
SCCF-El Loa Airport-ANTOFAGASTA-CHILE

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3597]
# Airport Name

El Loa Airport

# Country?

Chile

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51074238-338c5c00-1642-11e9-8a4d-051f26120736.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59124637-a02c2e00-8936-11e9-824d-7c9d194689e5.jpg)
