### ISSUE TITLE
SBBP-Arthur Siqueira Airport-SAO PAULO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3598]
# Airport Name

Arthur Siqueira Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51067757-9c3fee00-15da-11e9-862b-6b2b25ac6cb7.png)
