### ISSUE TITLE
KTPA-Tampa International Airport-FLORIDA-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#36]

**Comment by HenrikBerg02** [comment]
![ktpa](https://cloud.githubusercontent.com/assets/14116830/11879218/afa49534-a4bf-11e5-8e0e-5abf846efbc0.jpg)

Reported by user. Runway hold short lines for 19L are in the wrong direction.

**Comment by kilt46** [comment]
Airport redone

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21077954/3e5c3f0c-bf22-11e6-8916-c0d4363ff1bd.png)

**Comment by kilt46** [comment]
Airport Review
![image](https://user-images.githubusercontent.com/14023167/43041315-4832d534-8d22-11e8-98f8-33db4552abf7.png)
