### ISSUE TITLE
OAPJ-Panjab Airport-BANYAM-AFGHANISTAN

### ISSUE THREAD

**Issue by Flight50** [InfiniteFlightAirportEditing/Airports#3603]
♻️

**Comment by brunocr98** [comment]
Unless you didn't know, this airport is already done! #2

**Comment by MajorTomMueller** [comment]
![OAPJ](https://user-images.githubusercontent.com/26853210/54478668-2bed5d00-4815-11e9-848d-c7715df90565.jpg)
