### ISSUE TITLE
KMSO-Missoula International Airport-MONTANA-USA

### ISSUE THREAD

**Issue by Flight50** [InfiniteFlightAirportEditing/Airports#3604]

**Comment by brunocr98** [comment]
How many times I have to tell you? IT'S DONE.

**Comment by IFC-PlaneCrazy** [comment]
I'm doing this airport from scratch.

**Comment by IFC-PlaneCrazy** [comment]
I'm redoing this airport from scratch.

**Comment by IFC-PlaneCrazy** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56069668-cc1d9f80-5d49-11e9-87f4-f306a2087836.png)
