### ISSUE TITLE
CEM4-Innisfail Airport-ALBERTA-CANADA

### ISSUE THREAD

**Issue by alexpeterson-if** [InfiniteFlightAirportEditing/Airports#3605]
# Airport Name

Innisfail Airport

# Country?

Canada

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low

**Comment by alexpeterson-if** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51086274-7ade1f80-170a-11e9-8795-2e31a64e11c3.png)
