### ISSUE TITLE
SVMG-Santiago Mariño Caribbean International Airport-NUEVA ESPARTA-VENEZUELA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3606]
# Airport Name

Santiago Marino Intl Airport

# Country?

Venezuela

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51073808-0f2d8100-163c-11e9-8b9e-e2dba46d3f16.png)
