### ISSUE TITLE
1LL4-Norfleet Airstrip-ILLINOIS-USA

### ISSUE THREAD

**Issue by Gusdnd** [InfiniteFlightAirportEditing/Airports#3607]
![image](https://user-images.githubusercontent.com/14023167/108784847-ddcf5100-7535-11eb-8974-b29b601ec921.png)

**Comment by MajorTomMueller** [comment]
http://worldaerodata.com/wad.cgi?id=KS45940&sch=RKTP
Wavy Sat Image, numerous Grass roofed shelters, no AIP Documents.
Very ambitious project for a beginner.

**Comment by MajorTomMueller** [comment]
Any Progress?

**Comment by Session-IFK** [comment]
No, He don't work anymore. unassign him. He entered a high school. however, perhaps he will work this AP at future.
