### ISSUE TITLE
83LL-Lindauer Strip-ILLINOIS-USA

### ISSUE THREAD

**Issue by grxninesix** [InfiniteFlightAirportEditing/Airports#3608]
# Airport Name

LAUSANNE - LA BLECHERETTE

# Country?

SWITZERLAND

# Improvements that need to be made?

NEW TAXIWAYS AND HANGARS
BOUNDARY OF AIRPORT HAVE CHANGED IRL

# Are you working on this airport?

YES

# Airport Priority? (A380, 10000ft+ Runway)

LOW PRIORITY

**Comment by grxninesix** [comment]
Rework are mostly done.
Pending LSGY PR+OR approval before sending LSGL to PR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90334783-a2a40200-df95-11ea-80bc-5f7b0a3dd519.png)
