### ISSUE TITLE
SBIC-Itacoatiara Airport-AMAZONAS-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3609]
# Airport Name

Itacoatiara Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51075444-0d21ed00-1651-11e9-9beb-659f8afd170c.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104074477-dea26280-51d5-11eb-900b-a7119e55e942.png)
