### ISSUE TITLE
SNMA-Monte Alegre Airport-PARA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3610]
# Airport Name

Monte Alegre Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51075383-31c99500-1650-11e9-9052-f8ecc1220e19.png)
