### ISSUE TITLE
SCAT-Desierto de Atacama Airport-ATACAMA-CHILE

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3611]
# Airport Name

Desierto de Atacama Airport

# Country?

Chile

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51085988-613ad900-1706-11e9-8712-bcb82d1e3691.png)
