### ISSUE TITLE
SAVT-Almirante Zar Airport-CHUBUT-ARGENTINA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3612]
# Airport Name

Almirante Zar Airport

# Country?

Argentina

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51476339-e8153480-1d4a-11e9-9780-4771ab932f53.png)
