### ISSUE TITLE
VOKN-Kannur International Airport-KERALA-INDIA

### ISSUE THREAD

**Issue by akshay2777** [InfiniteFlightAirportEditing/Airports#3613]
# Airport Name

Kannur International Airport

# Country?

India

# Improvements that need to be made?

New Airport

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

GP2 (10000ft+ Runway)

**Comment by MajorTomMueller** [comment]
Official AIP with Aerodrom chart:
https://aim-india.aai.aero/sites/default/files/aip_supplements/AIPS_2018_127.pdf

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51796126-b10faa80-21b2-11e9-80f5-41e2e3965d82.png)
