### ISSUE TITLE
VRMO-Kooddoo Airport-MAAMENDHOO-MALDIVES

### ISSUE THREAD

**Issue by gsherbert** [InfiniteFlightAirportEditing/Airports#3614]
# Airport Name

VRMO

# Country?

Maldives

# Improvements that need to be made?

New to repo, made from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low Priority

**Comment by gsherbert** [comment]
Note: At the airport there is a clear sign of a runway expansion taking place. Also, there is enough information to accurately create the expanded runway. The expanded runway will be included in the edit.

**Comment by gsherbert** [comment]
Sent to OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51648777-8ec62480-1f47-11e9-8931-970bc3fb7b17.png)
