### ISSUE TITLE
RJFZ-Tsuiki Air Base-FUKUOKA-JAPAN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#3616]
# Airport Name

< Tsuiki Air Base >

# Country?

< Japan >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51554079-fa21d080-1e39-11e9-8eec-fe499591182a.png)
