### ISSUE TITLE
DXXX-Gnassingbe Eyadema-MARITIME-TOGO

### ISSUE THREAD

**Issue by Aceorbit** [InfiniteFlightAirportEditing/Airports#3618]
# Airport Name

Lomé–Tokoin International Airport

# Country?

Togo

# Improvements that need to be made?

Scratch

# Are you working on this airport?

Yus
# Airport Priority? (A380, 10000ft+ Runway)

GP3, World Cap.

**Comment by danisrils39** [comment]
Sent into OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51952185-2d95c980-23fd-11e9-858f-e2b5ed65110e.png)

**Comment by brennanhackard** [comment]
This airport needs the following:
- Airport name needs to be changed
- An approach frequency needs to be added
- Apron needs to be updated to match current imagery
- North Apron spawn sizes need to be adjusted
- Snapping and curving errors need to be fixed

Be advised: Current imagery is relatively distorted.

If you'd like to be assigned, reply to this message below.
