### ISSUE TITLE
UUOO-Voronezh International Airport-VORONEZH-RUSSIA

### ISSUE THREAD

**Issue by ErshovlaD** [InfiniteFlightAirportEditing/Airports#3619]
# Airport Name

Voronezh International Airport

# Country?

Russia

# Improvements that need to be made?

Being redone from scratch

# Are you working on this airport?

Yes

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51794057-6aa95400-2190-11e9-809f-34a575b019e0.png)
