### ISSUE TITLE
EBSL

### ISSUE THREAD

**Issue by HenrikBerg02** [InfiniteFlightAirportEditing/Airports#362]
This airport has no parking spots.

**Comment by Ksisky** [comment]
On it.

**Comment by Ksisky** [comment]
I added parking spots and a few other basic things, but it needs a complete rewrite, and because it is a military base, most of the airport details have been removed and blurred out.

**Comment by dushyants19** [comment]
@Ksisky did you even do anything? There's nothing in the repo

![image](https://cloud.githubusercontent.com/assets/13567007/13197530/469b488c-d816-11e5-8a48-bc9b511b5399.png)

**Comment by Ksisky** [comment]
@dushyants19 I added taxi lines, but when I submitted it, it was denied.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/14065389/d8fb6aee-f3ec-11e5-8269-7b58aaa7ab89.png)
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20469501/e9eda1c0-af65-11e6-9ab9-5a306f5e8ef0.png)
