### ISSUE TITLE
UIAA-Kadala Airport-CHITA-RUSSIA

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#3620]
# Airport Name

Kadala Airport

# Country?

Russia

# Improvements that need to be made?

Being redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52025474-fe995980-24c9-11e9-9d66-857dd9db7f85.png)
