### ISSUE TITLE
KMFE-McAllen Miller International Airport-TEXAS-USA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3621]
♻️

**Comment by Balloonchaser** [comment]
Sent for OR

**Comment by brunocr98** [comment]
I think you should look for another airport, since this one doesn't have a *valid ICAO code*. Until then I'll put the Invalid label.

**Comment by benjwri** [comment]
I’ll take this

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54872399-336eb200-4d91-11e9-8882-f71f6574bf65.png)
