### ISSUE TITLE
KHRT-Hurlburt Field AFB-FLORIDA-USA

### ISSUE THREAD

**Issue by baseballinferno** [InfiniteFlightAirportEditing/Airports#3622]

**Comment by baseballinferno** [comment]
The editing of KMCX is going along smoothly!

**Comment by baseballinferno** [comment]
I'm almost done with this one

**Comment by baseballinferno** [comment]
The apt.dat will not export

**Comment by baseballinferno** [comment]
Finished, now I'm exporting

**Comment by baseballinferno** [comment]
Before I opened it, The ENTIRE taxiway was on the wrong side

**Comment by baseballinferno** [comment]
So I deleted the whole taxiway and did it on the right and the right side.

**Comment by baseballinferno** [comment]
I'm going to continue to work on this

**Comment by baseballinferno** [comment]
As I am still a collaborator.

**Comment by baseballinferno** [comment]
And I will be sending it to the ORs when finished.

**Comment by RyanEpps** [comment]
Clay, please stop this charade. We have already made a decision, and we intend to stick with it. Repeatedly sending messages on here and the IFC does not show you in a good light. As long as you continue to plead your case and claim that it is someone else's fault, nothing will change. Thank you.

**Comment by baseballinferno** [comment]
KMCX is almost done for the OR

**Comment by brunocr98** [comment]
In case you didn't know, since you're no longer part of this team, any airport you do will be refused.

**Comment by baseballinferno** [comment]
> Clay, please stop this charade. We have already made a decision, and we intend to stick with it. Repeatedly sending messages on here and the IFC does not show you in a good light. As long as you continue to plead your case and claim that it is someone else's fault, nothing will change. Thank you.

I'll claim that it is my fault but that would be a lie.  But it technically would be my fault as Benedict set me up and I fell for his 'joke'.  I have the gullibility so I guess it makes it my fault.  This is the last message that will be posted here by me.  Goodbye!

**Comment by baseballinferno** [comment]
![image](https://user-images.githubusercontent.com/44811488/51945569-1e0e8480-23ed-11e9-90e4-f2ec5109d51b.png)
Is this asphalt?  Final question.

**Comment by MajorTomMueller** [comment]
![KHRT-git](https://user-images.githubusercontent.com/26853210/55279093-c325da80-5314-11e9-8716-237eb3742802.jpg)
