### ISSUE TITLE
VICG-Chandigarh Airport-PUNJAB-INDIA

### ISSUE THREAD

**Issue by Ayush-19** [InfiniteFlightAirportEditing/Airports#3623]
# Airport Name

Chandigarh Airport

India

# Improvements that need to be made?

To be redone completely

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

_**+10K**_ 11/29

**Comment by Ayush-19** [comment]
Poor imagery, Airport under construction in imagery. Will delay till new imagery comes out.

**Comment by KaalicharanDH** [comment]
_**I will do it**_

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104111477-b6833400-52a7-11eb-8e14-e549bce2dd4a.png)
