### ISSUE TITLE
RJNG-Gifu Air Base-GIFU-JAPAN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#3625]
# Airport Name

< Gifu Air Base >

# Country?

< Japan >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51564145-07e44f80-1e54-11e9-96b4-cd498502f817.png)

**Comment by orangejuicie** [comment]
Frequency update.
