### ISSUE TITLE
KSPI-Abraham Lincoln Capital Airport-ILLINOIS-USA

### ISSUE THREAD

**Issue by SPARRIET** [InfiniteFlightAirportEditing/Airports#3626]

**Comment by dushyants19** [comment]
I am not, since you created this issue. I assumed you would, are you re-doing it?

**Comment by SPARRIET** [comment]
Well Ok.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/89102084-6f754680-d3cb-11ea-8e86-a73b87734a5c.png)
