### ISSUE TITLE
KTWF-Joslin Field/Magic Valley Regional Airport-IDAHO-USA

### ISSUE THREAD

**Issue by EthanChloe123** [InfiniteFlightAirportEditing/Airports#3628]
# Airport Name

Joslin Field - Magic Valley Regional Airport

# Country?

United States

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

None

**Comment by jakey200** [comment]
@EthanChloe123 How is the progress on this? If you don't respond I would be willing to take this.

**Comment by EthanChloe123** [comment]
Hello!

I have not edited or touched KTWF in awhile, and currently do not plan to continue. It is all yours!

Thanks,
Ethan Michon

**Comment by jakey20** [comment]
Could I be assigned this please?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103048335-e61a0880-4553-11eb-9c82-b0ed639f6dcf.png)
