### ISSUE TITLE
VQGP-Gelephu Domestic Airport-SARPANG-BHUTAN

### ISSUE THREAD

**Issue by gsherbert** [InfiniteFlightAirportEditing/Airports#3629]
# Airport Name

Gelephu Domestic Airport

# Country?

Bhutan

# Improvements that need to be made?

Will do from scratch. New to Repo.

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low Priority

**Comment by gsherbert** [comment]
Sent to OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51793833-a3472e80-218c-11e9-94aa-e4c5ee753fba.png)
