### ISSUE TITLE
VQBT-Bathpalathang Airport-JAKAR-BHUTAN

### ISSUE THREAD

**Issue by gsherbert** [InfiniteFlightAirportEditing/Airports#3630]
# Airport Name

Bathpalathang Airport

# Country?

Bhutan

# Improvements that need to be made?

Will do from scratch. New to repo.

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low Priority

**Comment by gsherbert** [comment]
Sent to OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51793721-a80ae300-218a-11e9-80af-10df720fe182.png)
