### ISSUE TITLE
UNBB-Mikhaylovka Airport-BARNAUL-RUSSIA

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#3632]
# Airport Name

< Mikhaylovka Airport >

# Country?

< Russia >

# Improvements that need to be made?

< Being redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52544458-8018a380-2d76-11e9-846a-71db67dcc9fb.png)
