### ISSUE TITLE
X26-Sebastian Municipal Airport-FLORIDA-USA

### ISSUE THREAD

**Issue by gsherbert** [InfiniteFlightAirportEditing/Airports#3633]
# Airport Name

Sebastian Municipal Airport

# Country?

USA

# Improvements that need to be made?

Complete redo

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low Priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53683123-e6804a00-3cc2-11e9-8583-10c76dca0871.png)
