### ISSUE TITLE
NWWC-Ile Art Waala Airport-NORD-NEW CALEDONIA

### ISSUE THREAD

**Issue by gsherbert** [InfiniteFlightAirportEditing/Airports#3634]
# Airport Name

Waala Airport

# Country?

New Caledonia (France)

# Improvements that need to be made?

Redo from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low Priority

**Comment by gsherbert** [comment]
Will complete my opened issues in the next week.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56100813-de7f1100-5ee2-11e9-8af6-bdb017c54d33.png)
