### ISSUE TITLE
NWWB-Bourail Poe Airport-SUD-NEW CALEDONIA

### ISSUE THREAD

**Issue by gsherbert** [InfiniteFlightAirportEditing/Airports#3635]
# Airport Name

Poé Airport

# Country?

New Caledonia (France)

# Improvements that need to be made?

Redo from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low Priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56100931-57329d00-5ee4-11e9-957c-df4d38348471.png)
