### ISSUE TITLE
EDAY-Strausberg Airport-BRANDERBURG-GERMANY

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#3639]
![image](https://user-images.githubusercontent.com/14023167/51809507-0efdca00-2267-11e9-8323-08aadd9ef47c.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/81461095-ec53a400-917f-11ea-8e1e-62e16a70f6c3.jpg)
