### ISSUE TITLE
KLGA

### ISSUE THREAD

**Issue by DavidCutler** [InfiniteFlightAirportEditing/Airports#364]
New York. Needs Updating. Starting this one tonight.

**Comment by kilt46** [comment]
was going to start this. Would probably get done within 1-2 weeks. If you think you can handle this monster go for it!

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/12252887/d7dd33f4-b8a0-11e5-9a7b-31461408d7ce.png)

**Comment by kilt46** [comment]
Got the buildings defined if you want them

**Comment by DavidCutler** [comment]
I've already got the buildings outlines thanks though. I should have it done soon. Depends on my time frame. :)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/12469563/6fe5f9d4-bfb2-11e5-8b7d-9368cd07a1ee.png)

Airport redone

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20733930/c20fa886-b65b-11e6-962c-03b1407ddee0.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/76574603-84445280-649b-11ea-9d30-ce98883c732a.jpg)
