### ISSUE TITLE
USCC-Balandino Airport-CHELYABINSK-RUSSIA

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#3641]
# Airport Name

< Balandino Airport >

# Country?

< Russia >

# Improvements that need to be made?

< Being redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52542235-5904a680-2d63-11e9-8db4-9e943d5df029.png)
