### ISSUE TITLE
recycle

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#3642]
♻️

**Comment by RyanEpps** [comment]
Duplicate. Search before creating new issues. #2878

**Comment by MajorTomMueller** [comment]
duplicat #3773, fooled myself

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/89103111-05619f00-d3d5-11ea-8588-47918602d1bb.png)
