### ISSUE TITLE
UDSG-Shirak International Airport-SHIRAK-ARMENIA

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#3643]
# Airport Name

Shirak International Airport

# Country?

Armenia

# Improvements that need to be made?

From scratch

# Are you working on this airport?

< Enter text here >

# Airport Priority? (A380, 10000ft+ Runway)

10000+ ft runway

**Comment by HiFlyerBwi** [comment]
Actually not working on this airport, forgot to type in the blank.

**Comment by AussieLuke** [comment]
I'll take this airport :)

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54888388-bd3e7e00-4e6a-11e9-8f6b-099035fd61d1.png)
