### ISSUE TITLE
SPHY-Andahuaylas Airport-APURIMAC-PERU

### ISSUE THREAD

**Issue by danisrils39** [InfiniteFlightAirportEditing/Airports#3644]
# Airport Name

Andahuaylas Airport

# Country?

Peru

# Improvements that need to be made?

Scratch,also elevation fix.  https://community.infiniteflight.com/t/one-challenging-approach-for-me-so-far/290236?u=aceorbit

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

N/A

**Comment by danisrils39** [comment]
Sent in to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52177182-e7d15c00-2782-11e9-8a86-10ff7d9ce3b0.png)
