### ISSUE TITLE
FA81-Tavernaero Park Airport-FLORIDA-USA

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#3645]
# Airport Name

Tavernaero Park Airport

# Country?

USA

# Improvements that need to be made?

From scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

No

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52914984-2b07f080-3294-11e9-82cd-5bcb8af67b3a.png)
