### ISSUE TITLE
NZKK-Kerikeri Airport-NORTHLAND-NEW ZEALAND

### ISSUE THREAD

**Issue by Lukeh0** [InfiniteFlightAirportEditing/Airports#3647]
# Airport Name

Bay of Islands/ Kerikeri Airport

# Country?

New Zealand

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52545301-008dd300-2d7c-11e9-98a2-ca4740ea0fe7.png)
