### ISSUE TITLE
EFKT-Kittila Airport-LAPLAND-FINLAND

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#3649]
![image](https://user-images.githubusercontent.com/14023167/52176772-0e8c9400-277d-11e9-8dde-452f1183069b.png)

**Comment by kilt46** [comment]
Done from scratch

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/73310390-00901880-4203-11ea-863c-2ebb7eeea7a6.jpg)
