### ISSUE TITLE
EBST-Sint Truiden-VLAANDEREN-BELGIUM

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#365]
Amsterdam

This is an Echo.

**Comment by IFAEpat** [comment]
I will do it 👍

**Comment by kilt46** [comment]
Artifact airport - NO LINES!

**Comment by kilt46** [comment]
this is the WRONG Airport
![image](https://cloud.githubusercontent.com/assets/14023167/15133321/510c763e-1627-11e6-8447-a2b3eb93f5bb.png)
Should be https://www.google.com/maps/@50.7919444,5.2016667,970m/data=!3m1!1e3
