### ISSUE TITLE
SJBX-Severino Lopes Airport-RIO GRANDE DO NORTE-BRAZIL

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Airports#3650]
# Airport Name

< Severino Lopes >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53923473-1b332f00-403e-11e9-851a-153730f867c2.png)
