### ISSUE TITLE
UNAA-Abakan Airport-ABAKAN-RUSSIA

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#3651]
# Airport Name

< Abakan >

# Country?

< Russia >

# Improvements that need to be made?

< Being redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52916036-92c43880-32a0-11e9-981f-9262bdf9714f.png)
