### ISSUE TITLE
LPBJ-Beja Airport-BEJA-PORTUGAL

### ISSUE THREAD

**Issue by Martijn-Decates** [InfiniteFlightAirportEditing/Airports#3652]
# Airport Name

< Beja Airport>

# Country?

< Portugal >

# Improvements that need to be made?

< Full Rework >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< A380, 10000ft+ Runway >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55041710-4afda300-4ffc-11e9-9f1c-b091daef83fa.png)
