### ISSUE TITLE
LFOD-Saumur Airport-ILE-DE-FRANCE-FRANCE

### ISSUE THREAD

**Issue by Martijn-Decates** [InfiniteFlightAirportEditing/Airports#3653]
# Airport Name

< Saumur >

# Country?

< France >

# Improvements that need to be made?

< Full rework >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< N/A >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53139942-c927df00-3550-11e9-8c2d-db673ed899b2.png)
