### ISSUE TITLE
SNWE-Clube Estancia Ouro Verde-PARAIBA-BRAZIL

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Airports#3654]
# Airport Name

< Clube Estancia Ouro Verde >

# Country?

< Brazil >

# Improvements that need to be made?

< Add airport >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53675140-362a2b80-3c59-11e9-8a30-1c11718f824c.png)
