### ISSUE TITLE
CYCW-Chilliwack Airport-BRITISH COLUMBIA-CANADA

### ISSUE THREAD

**Issue by DelsterX** [InfiniteFlightAirportEditing/Airports#3655]
# Airport Name

< Chilliwack Airport >

# Country?

< Canada >

# Improvements that need to be made?

<redone from scratch>

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52916670-13d2fe00-32a8-11e9-996d-1f3eab6ef8ac.png)
