### ISSUE TITLE
EDAZ-Schonhagen Airport-BRANDENBURG-GERMANY

### ISSUE THREAD

**Issue by rich-art-02** [InfiniteFlightAirportEditing/Airports#3656]
# Airport Name

Flugplatz Schönhagen

# Country?

Germany

# Improvements that need to be made?
Adding of more Hangars and Taxiways
Rrework of Runway Layout 

# Are you working on this airport?
Yes
# Airport Priority? (A380, 10000ft+ Runway)

none

**Comment by rich-art-02** [comment]
![edaz](https://user-images.githubusercontent.com/47453439/52506183-02299080-2bee-11e9-8300-d3d04a7bbf33.jpg)
After i have imported the picture from SAS Planet i noticed that the whole airport is rotated wrong.
But i don't know, if my picture is wrong or the airport file (apt.dat)

**Comment by rich-art-02** [comment]
After i have imported the picture from SAS Planet i noticed that the whole airport is rotated wrong.
But i don't know, if my picture is wrong or the airport file (apt.dat)
![capture](https://user-images.githubusercontent.com/47453439/52506324-80863280-2bee-11e9-85c8-e14cf7fc1679.JPG)

**Comment by rich-art-02** [comment]
Sent in for official review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54501140-704e2b00-48f1-11e9-80ec-9b6bfbbdaf03.png)
