### ISSUE TITLE
KMDH-Southern Illinois Airport-ILLINOIS-USA

### ISSUE THREAD

**Issue by Daniboi737** [InfiniteFlightAirportEditing/Airports#3657]
♻️

**Comment by brunocr98** [comment]
#730

**Comment by nono45fr** [comment]
Hi , i'll work on it . Sorry again for MZGJ .

**Comment by nono45fr** [comment]
What's the issue with this airport ? @brunocr98

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/89352779-973e0600-d67a-11ea-821e-098394ced1c8.png)
