### ISSUE TITLE
SBCI-Carolina Airport-MARANHAO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3658]
# Airport Name

Carolina Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52521797-4fcfe880-2c42-11e9-855c-71d533330e6d.png)
