### ISSUE TITLE
NZTG-Tauranga Airport-BAY OF PLENTY-NEW ZEALAND

### ISSUE THREAD

**Issue by Lukeh0** [InfiniteFlightAirportEditing/Airports#3659]
# Airport Name

Tauranga Airport

# Country?

New Zealand

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53057814-77ab2180-3476-11e9-9a8e-46a067bff7e1.png)
