### ISSUE TITLE
YCFS-Coffs Harbour Airport-NEW SOUTH WALES-AUSTRALIA

### ISSUE THREAD

**Issue by joshhicks1** [InfiniteFlightAirportEditing/Airports#3660]
# Airport Name

Coffs Harbour

# Country?

 Australia

# Improvements that need to be made?

The apron needs to be fixed and the airport is north of its actual position in real life

# Are you working on this airport?

 Yes

# Airport Priority? (A380, 10000ft+ Runway)

 Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54873686-f4992600-4da9-11e9-9d56-cc1ac7a4564c.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105432195-c2aeb000-5c1c-11eb-9356-1999b8fe2a23.png)
