### ISSUE TITLE
KMFR-Rogue Valley International Airport-OREGON-USA

### ISSUE THREAD

**Issue by LordAidanYT** [InfiniteFlightAirportEditing/Airports#3661]
# Airport Name

Rogue Valley International Airport

# Country?

United States of America

# Improvements that need to be made?

redone

# Are you working on this airport?

I will be doing it by myself.

# Airport Priority? (A380, 10000ft+ Runway)

None

**Comment by yachtopia** [comment]
I would like to take over this airport for rework.

**Comment by Czechoslovaki** [comment]
Could I work on this? The current editor doesn't look active.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/77347034-f9265080-6d15-11ea-9cd1-7b9994c88b29.jpg)
