### ISSUE TITLE
BKPR-Pristina Airport-PRISTINA-KOSOVO

### ISSUE THREAD

**Issue by Martijn-Decates** [InfiniteFlightAirportEditing/Airports#3662]
# Airport Name

< Pristina Intl Airport >

# Country?

< Kosovo >

# Improvements that need to be made?

< Full Rework >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by MajorTomMueller** [comment]
thanks Bruno, --> BK is the ICAO prefix of Kosovo. https://en.wikipedia.org/wiki/ICAO_airport_code#Prefixes

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
Please change spawn locations as per attached map
![image](https://user-images.githubusercontent.com/14023167/54857961-1cb45680-4cd0-11e9-8882-84da0d316663.png)

**Comment by Martijn-Decates** [comment]
I don’t know what i have to do!? Can you explain me?

**Comment by MajorTomMueller** [comment]
The Map Kilt provided is the docking chart of the airport. It shows the official spawn location sceme and kilt says that the airport in the repro does not fit this. He asked you to comply with the given naming.

**Comment by Martijn-Decates** [comment]
Oke! When i fixed it should i sent it to OR?

**Comment by Martijn-Decates** [comment]
ok i sent it to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/91910922-8f6f8280-ec75-11ea-8118-80ec3d8dd559.png)
