### ISSUE TITLE
VAPO-Pune Airport-MAHARASHTRA-INDIA

### ISSUE THREAD

**Issue by chinmayerram** [InfiniteFlightAirportEditing/Airports#3663]
# Airport Name

Pune International Airport 

# Country?

India

# Improvements that need to be made?

To be done from scratch

# Are you working on this airport?

No, but plan to star work

# Airport Priority? (A380, 10000ft+ Runway)

Low Priority

**Comment by rich-art-02** [comment]
Can someone please assign me, user is inactive

**Comment by Prats16** [comment]
Can I please be assigned to this airport as it is my home airport and the user who is supposed to be working on this airport is inactive!

**Comment by KaalicharanDH** [comment]
I will do it

**Comment by brunocr1050** [comment]
Up for grabs.

**Comment by hari-shreyas** [comment]
I'd like to work on it. Could someone assign me to this airport?
Thanks :)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106356490-8c7cca80-62c5-11eb-83ea-89ce4ddcda21.png)
