### ISSUE TITLE
UIBB-Bratsk Airport-BRATSK-RUSSIA

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#3665]
# Airport Name

< Bratsk Airport >

# Country?

< Russia >

# Improvements that need to be made?

< Being redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53848494-30468a00-3f7a-11e9-9f28-12ff704a61b2.png)
