### ISSUE TITLE
RJNH-Hamamatsu Air Base-SHIZUOKA-JAPAN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#3668]
# Airport Name

< Hamamatsu Air Base >

# Country?

< Japan >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52915163-43790a80-3296-11e9-9257-9cd1e3e20d79.png)
