### ISSUE TITLE
ULWC-Cherepovets Airport-CHEREPOVETS-RUSSIA

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#3669]
# Airport Name

< Cherepovets Airport >

# Country?

< Russia >

# Improvements that need to be made?

< Generated Airport, doing from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53134062-2add4e80-353b-11e9-8bf8-382abaa38acd.png)
