### ISSUE TITLE
KSPA

### ISSUE THREAD

**Issue by dushyants19** [InfiniteFlightAirportEditing/Airports#367]
Charlotte
Pretty good already. 
Removing hold short spawns and adding new

**Comment by NickArt1342** [comment]
@dushyants19 are you still doing this one?

**Comment by dushyants19** [comment]
No but I had some issues with another Taxiway which isn't in Bing Maps, you can have it 
@NickArt1342

**Comment by NickArt1342** [comment]
90% clean redone, added spawn points and taxilines and taxiways. For this airport it'd be useful if gravel or broken asphalt and dirt would be rendered.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20738398/6f1a14c8-b678-11e6-86ef-5401d82d6308.png)
