### ISSUE TITLE
RPUI-Iba Airport-ZAMBALES-PHILIPPINES

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#3670]
# Airport Name

< Iba Airport >

# Country?

< Philippines >

# Improvements that need to be made?

< Add new airport >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52915277-796abe80-3297-11e9-8853-77cfb7dd4f65.png)
