### ISSUE TITLE
VILH-Kushok Bakula Rimpochee Airport-JAMMUR AND KASHMIR-INDIA

### ISSUE THREAD

**Issue by dailyservice** [InfiniteFlightAirportEditing/Airports#3672]
# Airport Name

< LEH Airport >

# Country?

< India >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by Ayush-19** [comment]
Can I be assigned this airport? It can't take **6 months** to do this airport. The currently assigned may be inactive.

**Comment by Ayush-19** [comment]
Airport has poor imagery, little information. May I be unassigned?

**Comment by MajorTomMueller** [comment]
Duplicate
