### ISSUE TITLE
EGYP-RAF Mount Pleasant-EAST FALKLAND-FALKLAND ISLANDS

### ISSUE THREAD

**Issue by Developer-33** [InfiniteFlightAirportEditing/Airports#3675]
♻️

**Comment by moritzbabl** [comment]
#730

**Comment by MajorTomMueller** [comment]
![recycle](https://user-images.githubusercontent.com/26853210/52712697-abc5a480-2f95-11e9-8501-9dc590afb51d.png)

**Comment by MajorTomMueller** [comment]
![egyp-git](https://user-images.githubusercontent.com/26853210/53297789-cd3f4f80-3823-11e9-93bf-f85db2758318.jpg)
