### ISSUE TITLE
CYPW-Powell River Airport-BRITISH COLUMBIA-CANADA

### ISSUE THREAD

**Issue by DelsterX** [InfiniteFlightAirportEditing/Airports#3677]
# Airport Name

< Powell River Airport >

# Country?

< Canada >

# Improvements that need to be made?

< Redone from scratch>

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low Priority >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53056667-b8546c00-3471-11e9-9d49-0af076f5f011.png)
