### ISSUE TITLE
CYBR-Brandon Municipal Airport-MANITOBA-CANADA

### ISSUE THREAD

**Issue by DelsterX** [InfiniteFlightAirportEditing/Airports#3678]
# Airport Name

< Brandon Municipal Airport >

# Country?

< Canada >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low Priority >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53280231-6879dd00-36dd-11e9-88e7-7141d80e8db7.png)
