### ISSUE TITLE
SNHS-Santa Magalhaes Airport-PERNAMBUCO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3679]
# Airport Name

Santa Magalhaes Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52859279-ecd2cb80-30f1-11e9-8f24-3573071a7b36.png)
