### ISSUE TITLE
KUDG

### ISSUE THREAD

**Issue by dushyants19** [InfiniteFlightAirportEditing/Airports#368]
Charlotte 
Its pretty good! :blush: 
I'm removing hold short spawn points and adding some more
removing 2 runways too

**Comment by dushyants19** [comment]
Approved by Jonathan.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20649594/d8d71ace-b488-11e6-9d8c-738404f45130.png)
