### ISSUE TITLE
SNRU-Caruaru Airport-PERNAMBUCO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3680]
# Airport Name

Caruaru Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52859551-9a45df00-30f2-11e9-9cc4-acde23711f7b.png)
