### ISSUE TITLE
URMG-Grozny/Severny Airport-CHECHNYA-RUSSIA

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#3681]
# Airport Name

< Severny Airport >

# Country?

< Russia >

# Improvements that need to be made?

< Generated Airport, doing from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53133100-90c7d700-3537-11e9-941e-15cc0109164e.png)
