### ISSUE TITLE
SNBS-Balsas Airport-MARANHAO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3683]
# Airport Name

Balsas Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52913163-d313be80-3280-11e9-9342-d52ba5a5d3a6.png)
