### ISSUE TITLE
SNKB-Aeroclube de Campina Grande Aerodrome-PARAIBA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3684]
# Airport Name

Aeroclube de Campina Grande Aerodrome

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52913218-97c5bf80-3281-11e9-9f31-0ac3879bc230.png)
