### ISSUE TITLE
SBGW-Guaratingueta Airport-SAO PAULO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3685]
# Airport Name

Guaratingueta Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52913717-7adfbb00-3286-11e9-914a-5c612c0c4721.png)
