### ISSUE TITLE
SBCO-Canoas Air Base-RIO GRANDE DO SUL-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3687]
# Airport Name

Canoas Air Base

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52913649-972f2800-3285-11e9-8c82-8960f750a9b2.png)
