### ISSUE TITLE
SIAQ-Bom Futuro Airport-MATO GROSSO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3689]
# Airport Name

Bom Futuro Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52913319-84672400-3282-11e9-90b2-602ea05f8293.png)
