### ISSUE TITLE
VIBN-Varanasi Airport-UTTAR PRADESH-INDIA

### ISSUE THREAD

**Issue by akshay2777** [InfiniteFlightAirportEditing/Airports#3690]
# Airport Name

 Lal Bahadur Shastri Airport

# Country?

 India

# Improvements that need to be made?

 from scratch

# Are you working on this airport?

 yes

# Airport Priority? (A380, 10000ft+ Runway)

 Low Priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53676209-b73af000-3c64-11e9-8348-7938dfb5e6fe.png)

**Comment by ItsW1ll** [comment]
ICAO Changed to VEBN link to chart below;
 https://aim-india.aai.aero/eaip-v2-02-2019/eAIP/VEBN-ILS(Z)-RWY-27.pdf
