### ISSUE TITLE
CYKF-Kitchner/Waterloo Airport-ONTARIO-CANADA

### ISSUE THREAD

**Issue by DelsterX** [InfiniteFlightAirportEditing/Airports#3691]
# Airport Name

<Kitchner/Waterloo Airport>

# Country?

<Canada>

# Improvements that need to be made?

<redone from scratch>

# Are you working on this airport?

<Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low Priority>

**Comment by DelsterX** [comment]
Sent for Review.
Runway 08/26 is an ILS Runway

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54499880-c2d51a80-48e4-11e9-9de0-a7bbffbcdb94.png)
