### ISSUE TITLE
LRIA-Iasi International Airport-MOLDAU-ROMANIA

### ISSUE THREAD

**Issue by vladcmanea** [InfiniteFlightAirportEditing/Airports#3692]
# Airport Name

Iasi International Airport

# Country?

Romania

# Improvements that need to be made?

Redo from scratch
# Are you working on this airport?

Yes, expected work time: February - May 2019.

# Photos

[Airport in Infinite Flight](https://drive.google.com/open?id=1uQ8208bzxFg6X8WL54XPFwTrRpEejWx8)
[Airport before modernisation](http://www.airports-worldwide.com/img/romania/lasi_international_romania_02.jpg)
[Airport after modernisation](https://transport-central.com/show_image.php?id=187&scalesize=0&nocount=y)

**Comment by MajorTomMueller** [comment]
@vladcmanea have you joint the Slack? Couldn‘t find you there.

**Comment by vladcmanea** [comment]
@MajorTomMueller I have sent a request now, will let you know when I got an account. Thank you.

**Comment by vladcmanea** [comment]
Computer died, need to redo.

**Comment by MajorTomMueller** [comment]
@vladcmanea are you still working on it?

**Comment by bavariaaviation** [comment]
any progress? @vladcmanea

**Comment by bavariaaviation** [comment]
Done.

https://github.com/InfiniteFlightAirportEditing/Airports/commit/a93f1cd66089fae47808b53f9f10e1c9c5acad62

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/79276615-bc65f900-7e7e-11ea-98bc-665207d06cd1.jpg)
