### ISSUE TITLE
UNWW-Novokuznetsk/Spichenkovo Airport-KEMEROVO-RUSSIA

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#3693]
# Airport Name

< Spichenkovo Airport >

# Country?

< Russia >

# Improvements that need to be made?

< Generated airport, doing from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by MajorTomMueller** [comment]
@kztmtn you are already assigned to 3 issues. If all 3 have passed peer review, and where send in to OR you could get assigned to the next one.

**Comment by kztmtn** [comment]
Noted, currently 2 have been sent OR after passed peer review and 1 is under peer review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53688000-2286cf80-3d02-11e9-88a9-906089237a9f.png)
