### ISSUE TITLE
SWEI-Eirunepe Airport-AMAZONAS-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3694]
# Airport Name

Eirunepe Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52969613-96c28a00-3376-11e9-8b34-196e88344841.png)
