### ISSUE TITLE
SBCM-Criciuma Forquilhinha Airport-SANTA CATARINA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3695]
# Airport Name

Criciuma Forquilhinha Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52969888-8ced5680-3377-11e9-9a4d-da2a5418b3b2.png)
