### ISSUE TITLE
SNBA-Barretos Chafei Amsei Airport-SAO PAULO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3697]
# Airport Name

Chafei Amsei Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53136032-10a76e80-3543-11e9-84d3-69543416eb4b.png)

**Comment by MBeringuy** [comment]
ICAO updated from SBBT to SNBA.
