### ISSUE TITLE
VOTR-Tiruchirappalli International Airport-TAMIL NADU-INDIA 

### ISSUE THREAD

**Issue by dailyservice** [InfiniteFlightAirportEditing/Airports#3698]
# Airport Name

< Tiruchirapalli Airport >

# Country?

< India >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low priority >

**Comment by Ayush-19** [comment]
May I please take this?

**Comment by MajorTomMueller** [comment]
Still interested @Ayush-19 ?

**Comment by hari-shreyas** [comment]
As there is no response from him, I would like to take over this and work on this airport @MajorTomMueller.

**Comment by Ayush-19** [comment]
Oops i was gonna take this as a break from VIDP but no worries. Enjoy and all the best! @hari-shreyas

**Comment by hari-shreyas** [comment]
Airport has been sent for OR!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/92666204-35eb0180-f2ce-11ea-9cd2-9979b26f82f4.png)
