### ISSUE TITLE
SWLC-Rio Verde Airport-GOIAS-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3699]
# Airport Name

Rio Verde Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53136539-00908e80-3545-11e9-81c0-9f6ce9fa3e3b.png)
