### ISSUE TITLE
VOAR-Arakonam Airport-TAMIL NADU-INDIA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#37]
Recycled

**Comment by TristinWoolf** [comment]
Just found this as a duplicate, it appears that this issue was created first, but #354 has more activity, so continue there.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23106767/06161244-f6b8-11e6-8c69-a1d0bc1bbaa0.png)

**Comment by dushyants19** [comment]
Needs ATC Freqs, if we can find some...
