### ISSUE TITLE
KRIL

### ISSUE THREAD

**Issue by dushyants19** [InfiniteFlightAirportEditing/Airports#370]
Xplane antique. Denver

**Comment by dushyants19** [comment]
Approved by Jonathan.

**Comment by dushyants19** [comment]
Gated in b58bf3fa561e5a80c4621f9ca85267ee9d9b580f

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19253269/86e566ec-8f0f-11e6-9d8c-1aedba531b34.png)
