### ISSUE TITLE
SNTF-Teixeira de Freitas Airport-BAHIA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3700]
# Airport Name

Teixeira de Freitas Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53136287-0d60b280-3544-11e9-82d9-86e3791013ab.png)
