### ISSUE TITLE
EFMI-Mikkeli Airport-EASTERN FINLAND-FINLAND 

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#3701]
# Airport Name

< Mikkeli Airport >

# Country?

< Finland >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53687765-257fc100-3cfe-11e9-8922-19fbd9ce08f1.png)
