### ISSUE TITLE
SBPF-Lauro Kurtz Airport-RIO GRANDE DO SUL-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3703]
# Airport Name

Passo Fundo, Lauro Kurtz Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53138081-ae526c00-354a-11e9-9e5b-ba1e96f03ad5.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/97080560-e6347100-15c1-11eb-9dd1-86e3a795a8d1.png)
