### ISSUE TITLE
ZUKD-Kangding Airport-SICHUAN-CHINA

### ISSUE THREAD

**Issue by Lukeh0** [InfiniteFlightAirportEditing/Airports#3706]

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53688183-91b1f300-3d05-11e9-8eeb-884c66cade72.png)

**Comment by kilt46** [comment]
Duplicate reused

**Comment by MBeringuy** [comment]
I'll edit this airport.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56541083-43b0b300-6530-11e9-9b78-f7c5837afa0a.png)
