### ISSUE TITLE
NZAP-Taupo Airport-WAIKATO-NEW ZEALAND

### ISSUE THREAD

**Issue by Lukeh0** [InfiniteFlightAirportEditing/Airports#3707]
# Airport Name

Taupo Airport

# Country?

New Zealand

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54490748-9f7b8280-4886-11e9-8a18-9febefb1a57f.png)
