### ISSUE TITLE
KPOU

### ISSUE THREAD

**Issue by dushyants19** [InfiniteFlightAirportEditing/Airports#371]
New York 
No taxilines, as per https://community.infinite-flight.com/t/no-taxi-lines-at-kpou-new-york/23245

**Comment by dushyants19** [comment]
Approved.

**Comment by dushyants19** [comment]
Gated in 79437a837f2bc2f84a2f5428fd91ae934d575556

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19254000/cbe91856-8f14-11e6-8ae9-1a849ce9a7c2.png)
