### ISSUE TITLE
SJCM-Aquiraz/Catuleve Airport-CEARA-BRAZIL

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Airports#3710]
# Airport Name

< Catuleve >

# Country?

< Brazil >

# Improvements that need to be made?

< Create airport >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56607376-069afe00-65ce-11e9-9f34-f653b8ef470c.png)
