### ISSUE TITLE
GMFF-Fes Saiss International Airport-BOULEMANE-MOROCCO

### ISSUE THREAD

**Issue by pilot0674** [InfiniteFlightAirportEditing/Airports#3713]
♻️

**Comment by RyanEpps** [comment]
Heliport. Please recycle.

**Comment by pilot0674** [comment]
I'm going insane. I'm 100% sure this was 0MA5 before

**Comment by dhamilton30** [comment]
I'd like to work on this please.

**Comment by dhamilton30** [comment]
Sent to OR.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56079564-2f481a00-5dbc-11e9-8f48-f75aa452ed72.png)
