### ISSUE TITLE
53IL-Steil RLA-ILLINOIS-USA

### ISSUE THREAD

**Issue by pilot0674** [InfiniteFlightAirportEditing/Airports#3714]
# Airport Name

Korean Village Forward Operating Base

# Country?

Iraq

# Improvements that need to be made?

Add to database

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Runways

**Comment by brunocr98** [comment]
When creating issues, please make sure you're going to do airports. http://www.pilotnav.com/airport/ORRW

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/89136102-95980500-d4f7-11ea-9bc0-4abf1160c8e4.png)
