### ISSUE TITLE
MZPL-Placencia Airport-STANN CREEK-BELIZE

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#3715]
# Airport Name

Placencia Airport

# Country?

Belize

# Improvements that need to be made?

Airport is missing

# Are you working on this airport?

No

# Airport Priority? (A380, 10000ft+ Runway)

None

**Comment by HiFlyerBwi** [comment]
Now working on this airport. Hopefully will finish quickly to move on to the rest of the missing Belizean airports.

**Comment by HiFlyerBwi** [comment]
Sent for OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54573271-a525b500-49b9-11e9-9bef-a577790809cd.png)
