### ISSUE TITLE
MZPG-Punta Gorda Airport-TOLEDO DISTRICT-BELIZE

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#3716]
# Airport Name

Punta Gorda Airport

# Country?

Belize

# Improvements that need to be made?

Airport is missing

# Are you working on this airport?

No

# Airport Priority? (A380, 10000ft+ Runway)

None

**Comment by HiFlyerBwi** [comment]
@brunocr98 I am not actually working on this airport.

**Comment by RyanEpps** [comment]
Then why are you opening an issue for it?

**Comment by HiFlyerBwi** [comment]
Working on this airport.

**Comment by HiFlyerBwi** [comment]
Sent in for OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54573499-8ecc2900-49ba-11e9-8319-92ce44769271.png)
