### ISSUE TITLE
MZPB-Dangriga Airport-STANN CREEK-BELIZE

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#3717]
# Airport Name

Dangriga Airport/Pelican Beach Airstrip

# Country?

Belize

# Improvements that need to be made?

Airport is missing

# Are you working on this airport?

No

# Airport Priority? (A380, 10000ft+ Runway)

None

**Comment by HiFlyerBwi** [comment]
Also working on this airport.

**Comment by HiFlyerBwi** [comment]
Sent in for OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54573688-5842de00-49bb-11e9-8ca0-fe9fba4e0775.png)
