### ISSUE TITLE
MZBE-Sir Barry Bowen Municipal Airport-BELIZE CITY-BELIZE

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#3718]
# Airport Name

Sir Barry Bowen Municipal Airport

# Country?

Belize

# Improvements that need to be made?

Airport is missing

# Are you working on this airport?

No

# Airport Priority? (A380, 10000ft+ Runway)

None

**Comment by HiFlyerBwi** [comment]
Working on this airport now.

**Comment by HiFlyerBwi** [comment]
Working on this.

**Comment by HiFlyerBwi** [comment]
Working on this airport.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54871326-488f1500-4d80-11e9-8607-c274e01151d2.png)
