### ISSUE TITLE
MZBP-Hector Silva Airstrip-CAYO DISTRICT-BELIZE

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#3719]
# Airport Name

Hector Silva Airstrip

# Country?

Belize

# Improvements that need to be made?

Airport is missing

# Are you working on this airport?

No

# Airport Priority? (A380, 10000ft+ Runway)

None

**Comment by HiFlyerBwi** [comment]
Working on this airport now.

**Comment by HiFlyerBwi** [comment]
Working on this airport.

**Comment by HiFlyerBwi** [comment]
Sent in for OR.

**Comment by HiFlyerBwi** [comment]
Already sent in for OR, could I be assigned please?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54871226-d4a03d00-4d7e-11e9-9ff8-595d6d2fb45d.png)
