### ISSUE TITLE
CYFB-Iqaluit Airport-NUNAVUT-CANADA

### ISSUE THREAD

**Issue by henrikbg** [InfiniteFlightAirportEditing/Airports#372]
Redone.

**Comment by kilt46** [comment]
There are ZERO gates here. Please redo

**Comment by NickArt1342** [comment]
@henrikbg Do you still want to do this or can I remove your assignment?

**Comment by henrikbg** [comment]
I'll add some parking spaces.

**Comment by henrikbg** [comment]
Added spawn points in commit: 772ee0e.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20459524/42c6ca06-ae8a-11e6-883d-72c8fc29691a.png)

**Comment by kilt46** [comment]
This part of the airport needs updated
![image](https://user-images.githubusercontent.com/14023167/93020551-5e5f4e00-f5a3-11ea-8d64-79d51a6eea2e.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/95211831-a7757d00-07b2-11eb-89e1-00a4af26765f.png)
