### ISSUE TITLE
MZGJ-Chan Chich Airstrip-ORANGE WALK-BELIZE

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#3720]
# Airport Name

Chan Chich Airstrip

# Country?

Belize

# Improvements that need to be made?

Airport is missing

# Are you working on this airport?

No

# Airport Priority? (A380, 10000ft+ Runway)

None

**Comment by brunocr98** [comment]
@HiFlyerBwi what do you intend to do with all these issues?

**Comment by nono45fr** [comment]
I would like to work on it .

**Comment by nono45fr** [comment]
I'm really sorry . There's no apt data as it's missing and i didn't thought of it . I'll do an airport/airstrip with apt data .

**Comment by HiFlyerBwi** [comment]
Working on this airport now.

**Comment by HiFlyerBwi** [comment]
Working on this.

**Comment by HiFlyerBwi** [comment]
Sent in for OR.

**Comment by HiFlyerBwi** [comment]
Could I also get assigned to this? Already sent in for OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54871134-cd2c6400-4d7d-11e9-9b39-932ca83f3d18.png)
