### ISSUE TITLE
OATW-Taywara Airport-GHOR-AFGHANISTAN

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#3721]
# Airport Name

Orange Walk Airport

# Country?

Belize

# Improvements that need to be made?

Airport is missing

# Are you working on this airport?

No

# Airport Priority? (A380, 10000ft+ Runway)

None

**Comment by IQ3milionen** [comment]
Can I edit this airport?

**Comment by MajorTomMueller** [comment]
![OATW](https://user-images.githubusercontent.com/26853210/54478996-dd41c200-4818-11e9-8fa3-def49def1764.jpg)
