### ISSUE TITLE
SBSO-Sorriso Airport-MATO GROSSO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3722]
# Airport Name

Sorriso Airport

# Country?

Brazil

# Improvements that need to be made?

Done from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53674367-06782500-3c53-11e9-8e18-0414563cad90.png)
