### ISSUE TITLE
KSYN-Stanton Airfield-MINNESOTA-USA

### ISSUE THREAD

**Issue by danisrils39** [InfiniteFlightAirportEditing/Airports#3723]
# Airport Name

Stanton Airfield
# Country?

USA

# Improvements that need to be made?

Scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

N/A

First flight lesson here

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53683218-ce5cfa80-3cc3-11e9-846c-d9ce321a25eb.png)
