### ISSUE TITLE
EFRO-Rovaniemi Airport-LAPLAND-FINLAND

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#3724]
# Airport Name

< Rovaniemi Airport >

# Country?

< Finland >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54084414-2ddb8b80-42fe-11e9-8242-1601c6e69fb3.png)
