### ISSUE TITLE
LFJR-Angers Marce Airport-PAYS DE LA LOIRE-FRANCE

### ISSUE THREAD

**Issue by Martijn-Decates** [InfiniteFlightAirportEditing/Airports#3725]
# Airport Name

< Angers - Lore Airport >

# Country?

< France >

# Improvements that need to be made?

< Full Rework >

# Are you working on this airport?

< yes>

# Airport Priority? (A380, 10000ft+ Runway)

< N/A >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54497347-8f37c780-48c7-11e9-8cde-0cb8ee6949f4.png)
