### ISSUE TITLE
LFFI-Ancenis Airport-PAYS DE LA LOIRE-FRANCE

### ISSUE THREAD

**Issue by Martijn-Decates** [InfiniteFlightAirportEditing/Airports#3726]
# Airport Name

< Ancenis Airport >

# Country?

< France >

# Improvements that need to be made?

< Full Rework >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< N/A >

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54497242-459aad00-48c6-11e9-963f-b2a7f764e3fd.png)
