### ISSUE TITLE
LFOQ-Blois Le Breuil-LOIR ET CHER-FRANCE

### ISSUE THREAD

**Issue by Martijn-Decates** [InfiniteFlightAirportEditing/Airports#3727]
# Airport Name

< Blois Le Breuil >

# Country?

< France >

# Improvements that need to be made?

< Full Rework >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< N/A >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54497454-ceb2e380-48c8-11e9-8c29-5952502a0ff2.png)
