### ISSUE TITLE
VEKO-Khajuraho Airport-MADHYA PRADESH-INDIA

### ISSUE THREAD

**Issue by akshay2777** [InfiniteFlightAirportEditing/Airports#3729]
# Airport Name

 Khajuraho Airport

# Country?

 India

# Improvements that need to be made?

 From scratch

# Are you working on this airport?

 Yes

# Airport Priority? (A380, 10000ft+ Runway)

 Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54870351-5b4f1d00-4d73-11e9-8135-e079b5124153.png)
