### ISSUE TITLE
NZNP-New Plymouth Airport-TARANAKI-NEW ZEALAND

### ISSUE THREAD

**Issue by Lukeh0** [InfiniteFlightAirportEditing/Airports#3730]
# Airport Name

New Plymouth Airport

# Country?

New Zealand

# Improvements that need to be made?

Full Rework 

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54489642-63dbbb00-487c-11e9-8447-d989f31788a0.png)
