### ISSUE TITLE
NZWB-Woodbourne Airport-MARLBOROUGH-NEW ZEALAND

### ISSUE THREAD

**Issue by Lukeh0** [InfiniteFlightAirportEditing/Airports#3731]
# Airport Name

Blenheim, Woodbourne Airport

# Country?

New Zealand

# Improvements that need to be made?

Full Rework 

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54484672-fd817900-4838-11e9-9f98-92216eac2185.png)
