### ISSUE TITLE
OAKB-Kabul International-KABUL-AFGHANISTAN 

### ISSUE THREAD

**Issue by hossss6** [InfiniteFlightAirportEditing/Airports#3732]
# Airport name

YMAV

# Country?

Australia

# Improvements that need to be made?

Added taxi ways and gates also ATIS need to be added

# Are you working on this airport?

I am currently working on the airport

**Comment by hossss6** [comment]
I am working on this Airport

**Comment by MajorTomMueller** [comment]
Duplicate, search before opening issues

**Comment by MajorTomMueller** [comment]
Recycled

**Comment by MajorTomMueller** [comment]
![oakb-git](https://user-images.githubusercontent.com/26853210/53897972-83324700-4037-11e9-890c-f79145def3eb.jpg)
