### ISSUE TITLE
EFOU-Oulu Airport-LAPLAND-FINLAND

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#3733]
# Airport Name

< Oulu Airport >

# Country?

< Finland >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kztmtn** [comment]
Sent to OR.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54574911-297b3680-49c0-11e9-90b7-608d3a6858b6.png)
