### ISSUE TITLE
AU24-Port Fairy Airfield-VICTORIA-AUSTRALIA

### ISSUE THREAD

**Issue by joshhicks1** [InfiniteFlightAirportEditing/Airports#3734]
# Airport Name

Port Fairy Airfield (AU24)

# Country?

Australia

# Improvements that need to be made?

Airport not in game, needs to be added

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low

**Comment by brunocr98** [comment]
Are you sure this is the code for the airfield? I was able to locate it on Google Maps but I can't find any source for it.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54873644-725c3200-4da8-11e9-9a7a-20fc015978c6.png)
