### ISSUE TITLE
CYZR-Sarnia Chris Hadfield Airport-ONTARIO-CANADA

### ISSUE THREAD

**Issue by DelsterX** [InfiniteFlightAirportEditing/Airports#3735]
# Airport Name

<Sarnia Chris Hadfield Airport>

# Country?

< Canada >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low>

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54499427-9ff43780-48df-11e9-8fc9-c256c7542264.png)
