### ISSUE TITLE
LUBL-Bălți International Airport-RISCANI-MOLDOVA

### ISSUE THREAD

**Issue by danisrils39** [InfiniteFlightAirportEditing/Airports#3736]
# Airport Name

Bălți International Airport

# Country?

Moldova

# Improvements that need to be made?

Scratch

# Are you working on this airport?

Ye

# Airport Priority? (A380, 10000ft+ Runway)

N/A

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54085192-0211d300-4309-11e9-8638-71e8941ee5f3.png)
