### ISSUE TITLE
YHID-Horn Island Airport-QUEENSLAND-AUSTRALIA

### ISSUE THREAD

**Issue by hossss6** [InfiniteFlightAirportEditing/Airports#3737]
# Airport Name

Horn Island

# Country?

Australia

# Improvements that need to be made?
Complete Redo

# Are you working on this airport?
Yes

# Airport Priority? (A380, 10000ft+ Runway)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/83944290-fc36c600-a7c7-11ea-928e-f2e5f9ad0900.png)
