### ISSUE TITLE
VILK-Chaudhary Charan Singh/Lucknow Airport-UTTAR PADRESH-INDIA

### ISSUE THREAD

**Issue by Ayush-19** [InfiniteFlightAirportEditing/Airports#3738]
# Airport Name

Chaudhary Charan Singh International Airport

# Country?

India

# Improvements that need to be made?

Complete Rework

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low

**Comment by Ayush-19** [comment]
Sent in fro review!

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59125713-8a6c3800-8939-11e9-83ad-26eba13eb746.jpg)
