### ISSUE TITLE
ZSFZ-Fuzhou/Changle Airport-FUJIAN-CHINA

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Airports#3739]
# Airport Name

< Fuzhou Changle Intl >

# Country?

< China >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< 10000ft+ Runway >

**Comment by FellipeEdu** [comment]
There was a problem with my computer's HD and I will have to restart this airport from scratch... Sorry for the delay.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/72672704-046eae80-3a3d-11ea-8e01-6039e93fc583.jpg)
