### ISSUE TITLE
LUBM-Mărculești Air Force Base-MARCULESTI-MOLDOVA

### ISSUE THREAD

**Issue by danisrils39** [InfiniteFlightAirportEditing/Airports#3740]
# Airport Name

Mărculești Air Force Base

# Country?

Moldova

# Improvements that need to be made?

Scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

N/A

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/60141916-fc43de80-978d-11e9-92cd-f5cec7478375.jpg)
