### ISSUE TITLE
VANP-Dr. Babasaheb Ambedkar International/Nagpur Airport-MAHARASHTRA-INDIA

### ISSUE THREAD

**Issue by akshay2777** [InfiniteFlightAirportEditing/Airports#3741]
# Airport Name

 Dr. Babasaheb Ambedkar International Airport

# Country?

 India

# Improvements that need to be made?

 from scratch

# Are you working on this airport?

 yes

# Airport Priority? (A380, 10000ft+ Runway)

 GP2(10000ft+ Runway)

**Comment by liamkirky** [comment]
I take it the previous editor is inactive, so could an SV please assign me and I'll do it. :) Thanks in advance

**Comment by liamkirky** [comment]
@akshay2777 how's the progress on VANP?

**Comment by KaalicharanDH** [comment]
Please assign me, I would like to do it

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103028249-fd89cf00-451c-11eb-8c47-e9bf420023ad.png)
