### ISSUE TITLE
UHSI-Iturup Airport-SAKHALIN-RUSSIA

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#3742]
# Airport Name

< Iturup Airport >

# Country?

< Russia >

# Improvements that need to be made?

< Not exist in Repo, full work from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kztmtn** [comment]
Sent to OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54859050-eb8b5480-4cd6-11e9-8b05-7492c74ac4f7.png)
