### ISSUE TITLE
OASH-FOB Shank-LOGAR-AFGHANISTAN

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#3744]
# Airport Name

FOB Shank

# Country?

Afghanistan

# Improvements that need to be made?

scratch

# Are you working on this airport?

yes

# Airport Priority? (A380, 10000ft+ Runway)

no

**Comment by MajorTomMueller** [comment]
![oash-git](https://user-images.githubusercontent.com/26853210/53963067-d1ede880-40ec-11e9-9f74-f971baad4da6.jpg)

**Comment by kilt46** [comment]
This has a zero elevation!

**Comment by MajorTomMueller** [comment]
Fixed
