### ISSUE TITLE
KMZH-Moose Lake Carlton County Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by Gabe-Z** [InfiniteFlightAirportEditing/Airports#3745]
# Airport Name

Moose Lake Carlton County Airport

# Country?

USA

# Improvements that need to be made?

From scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

None

**Comment by Gabe-Z** [comment]
The airport is sent in for OR.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54496014-40cefc80-48b8-11e9-8745-68ee6b670c8c.png)
