### ISSUE TITLE
00GA-LT World Airstrip-GEORGIA-USA

### ISSUE THREAD

**Issue by hossss6** [InfiniteFlightAirportEditing/Airports#3746]
![image](https://user-images.githubusercontent.com/14023167/91614704-a8abc280-e947-11ea-84b9-675552ee0981.png)

**Comment by MBeringuy** [comment]
Has this airport already been approved by the OR?

**Comment by hossss6** [comment]
Hi sorry about closing it. I reworked this airport a while ago and was very close to finishing it but then everything on my hard drive was deleted and now im not really bothered to redo the whole airport again. This can go into suggestions for someone else to do. Sorry
