### ISSUE TITLE
IS93-Sue Rock Strip-ILLINOIS-USA

### ISSUE THREAD

**Issue by Martijn-Decates** [InfiniteFlightAirportEditing/Airports#3747]
♻️

**Comment by brunocr98** [comment]
#2943

**Comment by Martijn-Decates** [comment]
please remove this issue it's not my issue

**Comment by brunocr98** [comment]
What do you mean with that? You created a duplicate and I had to recycle it.

**Comment by Martijn-Decates** [comment]
i dont make this issue and i dont want to make this airport so can you delete this issue?

**Comment by MajorTomMueller** [comment]
You have created the issue @Martijn-Decates. It is a base principle in GitHub that Issues, once created, will not deleted.
When you created the issue, you did this with a ICAO that had already a issue opened once.
See here:

**Comment by Martijn-Decates** [comment]
again the wrong one
it is KMKL! now i know it!!

**Comment by brunocr98** [comment]
@Martijn-Decates please understand that this issue you create is a duplicate! The reason is because there was already an issue existing for the same airport. I had to recycle it because unfortunately we can't delete it.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/88455367-60761d80-ce3a-11ea-8960-bd4302a4b959.png)
