### ISSUE TITLE
LEBL-Barcelona-El Prat Airport-CATALONIA-SPAIN

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#375]

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20248031/6b0f8cac-a9a1-11e6-821f-35aa09161eb0.png)

**Comment by kztmtn** [comment]
Redo from scratch.

**Comment by kztmtn** [comment]
![LEBL-Git](https://user-images.githubusercontent.com/46369763/80985932-d33eb080-8e6a-11ea-8cf9-94a6bb744df5.jpg)
