### ISSUE TITLE
SBVH-Vilhena Airport-RONDONIA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3750]
# Airport Name

Vilhena Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54063404-c9bba900-41d1-11e9-8b41-b4d75cca3c09.png)
