### ISSUE TITLE
NZHK-Hokitika Airport-WEST COAST-NEW ZEALAND

### ISSUE THREAD

**Issue by Lukeh0** [InfiniteFlightAirportEditing/Airports#3752]
# Airport Name

Hokitika Airport

# Country?

New Zealand

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54858057-8cc2dc80-4cd0-11e9-9f6a-6c09f4f78e3a.png)
