### ISSUE TITLE
UHMP-Pevek Airport-CHUKOT-RUSSIA

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#3753]
# Airport Name

< Pevek Airport >

# Country?

< Russia >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kztmtn** [comment]
Send to OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54858484-f47a2700-4cd2-11e9-8a7c-6350a2e6a01c.png)
