### ISSUE TITLE
KFOZ-Bigfork Municipal Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by Gabe-Z** [InfiniteFlightAirportEditing/Airports#3754]
# Airport Name

Bigfork Municipal Airport

# Country?

USA

# Improvements that need to be made?

From scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

None

**Comment by Gabe-Z** [comment]
Sent in for OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54879032-803ea100-4e02-11e9-8fda-d76eaf27cf74.png)
