### ISSUE TITLE
TLPC-George F. L. Charles Airport-CASTRIES-SAINT LUCIA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3755]
# Airport Name

< George F. L. Charles Airport >

# Country?

< Saint Lucia >

# Improvements that need to be made?

< Remade from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by Balloonchaser** [comment]
Sent in for OR

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54497544-e8085f80-48c9-11e9-8de0-bae8c7bd8b56.png)
