### ISSUE TITLE
NLWF-Futuna Pointe Vele Airport-SINGAVE-WALLIS AND FUTUNA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3756]
# Airport Name

< Futuna Pointe Vele Airport >

# Country?

< Singave >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by Balloonchaser** [comment]
Sent in for OR

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54652421-d3bc9200-4a84-11e9-8844-367b1071d352.png)
