### ISSUE TITLE
1IS4-Swan Valley Farm-ILLINOIS-USA

### ISSUE THREAD

**Issue by hossss6** [InfiniteFlightAirportEditing/Airports#3757]
![image](https://user-images.githubusercontent.com/14023167/108638644-d59fe480-7455-11eb-87a7-e0baa49b3040.png)

**Comment by PilotGonzalez** [comment]
I would like to work on this airport

**Comment by MajorTomMueller** [comment]
Are you sure @hossss6 ?

**Comment by MajorTomMueller** [comment]
You are not assigned to this @hossss6
