### ISSUE TITLE
LEPA-Palma De Mallorca Airport-ISLAS BALEARES-SPAIN

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#376]
My local one, this is mine. Nobody else shall ever touch this without my permission.

**Comment by kilt46** [comment]
Aprons need a little tidy. More defined buildings would be nice. Also outlines for gates if possible.

**Comment by NickArt1342** [comment]
@carmichaelalonso Get to work!

**Comment by samuelandersson** [comment]
Anything here @carmichaelalonso?

**Comment by carmichaelalonso** [comment]
Lorenzo is doing this now.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20506908/ef43cbc4-b01c-11e6-8f25-1e52d3e069f9.png)

**Comment by ryu12332** [comment]
ISSUE: Entrance to 6R updated since release.
[IF IMAGE](https://drive.google.com/file/d/1Uwq_IarOLa0ud8i_sY2vfui03ZQlSmyT/view)
[SAT IMAGE](https://drive.google.com/file/d/1hHvan1VCHti1MvvblDQ_XhAnSGsaeo2d/view)

**Comment by MajorTomMueller** [comment]
Any progress?

**Comment by ItsW1ll** [comment]
If it’s only a small issue I’ll do it 👍🏽

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by Fabse1803** [comment]
I can make it.

**Comment by Fabse1803** [comment]
Sent in for peer-review

**Comment by Fabse1803** [comment]
Sent in for peer-review again

**Comment by moritzbabl** [comment]
Taking this from @Fabse1803 due to technical reasons, @carmichaelalonso hope you'll like it ❤️

**Comment by moritzbabl** [comment]
Done

**Comment by moritzbabl** [comment]
![image](https://user-images.githubusercontent.com/19365980/68719917-db99eb00-05ad-11ea-904a-1472a1bf4f8c.png)
