### ISSUE TITLE
LLIB-Rosh Pina Airport-HAZAFON-ISRAEL

### ISSUE THREAD

**Issue by royfr83** [InfiniteFlightAirportEditing/Airports#3761]
# Airport Name

Rosh Pina

# Country?

Israel

# Improvements that need to be made?

From scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

No

**Comment by royfr83** [comment]
Sent in for OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54864590-4c427d80-4d27-11e9-94a9-994b5d82bd3a.png)
