### ISSUE TITLE
KBTM-Bert Mooney Airport-MONTANA-USA

### ISSUE THREAD

**Issue by IFC-PlaneCrazy** [InfiniteFlightAirportEditing/Airports#3762]
# Airport Name

Bert Mooney Airport

# Country?

United States

# Improvements that need to be made?

Will be redone from scratch 

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

None

**Comment by IFC-PlaneCrazy** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54884266-d92b2b00-4e3c-11e9-9778-f2ec022ac129.png)
