### ISSUE TITLE
NLWW-Wallis Hihifo Airport-UVEA-WALLIS AND FUTUNA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3763]
# Airport Name

< Wallis Hihifo Airport >

# Country?

< Wallis >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by Balloonchaser** [comment]
Sent in for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54726059-5efa5e00-4b3f-11e9-9774-0c85c6de11b1.png)
