### ISSUE TITLE
DTTB-Sidi Ahmed Air Base Airport-BIZERTE-TUNISIA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3764]
# Airport Name

< Sidi Ahmed Air Base Airport >

# Country?

< Tunisia >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None [Mil. Base] >

**Comment by Balloonchaser** [comment]
Sent in for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55195606-119f7180-517b-11e9-9198-1547bf1a7846.png)
