### ISSUE TITLE
DXSK-Sokode Airport-CENTRE-TOGO

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3765]
# Airport Name

< Sokode Airport >

# Country?

< Togo >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by Balloonchaser** [comment]
Sent in for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54484430-b09ba380-4834-11e9-9a7f-09a1d28e12f4.png)
