### ISSUE TITLE
DXNG-Niamtougou Airport-KARA-TOGO

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3766]
# Airport Name

< Niamtougou Airport >

# Country?

< Togo >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by Balloonchaser** [comment]
Sent in for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54484468-ae861480-4835-11e9-99d5-307e77dfabef.png)
