### ISSUE TITLE
DXMG-Sansanne Mango Airport-SAVANES-TOGO

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3769]
# Airport Name

< Sansanne Mango Airport >

# Country?

< Togo >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None [Not In IF yet] >

**Comment by Balloonchaser** [comment]
Sent in for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54484586-d8d8d180-4837-11e9-87f2-459ed42d991e.png)
