### ISSUE TITLE
LESB-Mallorca Son Bonet Airport-ISLAS BALEARES-SPAIN

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#377]
More local than LEPA. Again, nobody is to touch this without permission.

**Comment by dushyants19** [comment]
i'll do it

**Comment by dushyants19** [comment]
Done, apologies for too many spawns. thats what charts said :P 😁

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25515402/f5b0a4ba-2ba9-11e7-9356-5ac120864baa.png)

**Comment by ryu12332** [comment]
ISSUE: There is missing a turnaround spot on the runway
[IF IMAGE](https://drive.google.com/file/d/1iJvik_AqaztgVNWB0tZ55uxE8j2vA7sa/view)
[SAT IMAGE](https://drive.google.com/file/d/1nNFhRGRtoKIA_CBM4S6zVyZ4SXejRtP2/view)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109882894-2f679200-7c40-11eb-9e2a-02aa321184f7.png)
