### ISSUE TITLE
LUKH-Horesti/National Airport-IALOVENI-MOLDOVA

### ISSUE THREAD

**Issue by danisrils39** [InfiniteFlightAirportEditing/Airports#3770]
# Airport Name
Horesti/National Airport

# Country?

Moldova

# Improvements that need to be made?

From de scratch

# Are you working on this airport?

yeeeees

# Airport Priority? (A380, 10000ft+ Runway)

N/A

**Comment by danisrils39** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55037938-4da4cc00-4fed-11e9-9138-9c9ade3784c9.png)
