### ISSUE TITLE
EFKS-Kuusamo Airport-LAPLAND-FINLAND

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#3772]
# Airport Name

< Kuusamo Airport >

# Country?

< Finland >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kztmtn** [comment]
Sent for OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54650215-6b1ce780-4a7b-11e9-8394-1b1e4ff3fbe8.png)
