### ISSUE TITLE
LEZG-Zaragoza Airport-ARAGON-SPAIN

### ISSUE THREAD

**Issue by airbus3d** [InfiniteFlightAirportEditing/Airports#3773]
♻️

**Comment by brunocr98** [comment]
#2885

**Comment by brunocr98** [comment]
Google Maps is awful for this airport. I suggest using Yandex.

**Comment by liamkirky** [comment]
May I take this airport?

**Comment by MBeringuy** [comment]
@liamkirky I'm assigning this airport to you.

**Comment by liamkirky** [comment]
Thanks!

**Comment by liamkirky** [comment]
I’m unable to do this airport. I need to get a better laptop as the airport won’t load through my laptop

**Comment by brunocr98** [comment]
Up for grabs.

**Comment by kztmtn** [comment]
A little bit difficult to draw lines on military aprons, but Yandex is fine as suggested, I'll take this one.

**Comment by kztmtn** [comment]
Submitted for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/58918274-054a0e80-8700-11e9-8cb2-6e89d4c8179c.jpg)

**Comment by MajorTomMueller** [comment]
new Apron extensions add. Spawn nmaes for mil part adjusted
![LEZG-git](https://user-images.githubusercontent.com/26853210/88568736-f53e6e00-d028-11ea-942d-97e21d070d8c.png)

**Comment by MajorTomMueller** [comment]
What did you "fixed" @bruno?
