### ISSUE TITLE
KMTO-Coles Country Memorial Airport-ILLINOIS-USA

### ISSUE THREAD

**Issue by rednaxela796** [InfiniteFlightAirportEditing/Airports#3774]
# Airport Name

Korla Airport

# Country?

China

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/89714832-1a0add80-d967-11ea-8fc3-0ba6e705367a.png)
