### ISSUE TITLE
MM31-Fausto Vega Santander Airport-VERACRUZ-MEXICO

### ISSUE THREAD

**Issue by airbus3d** [InfiniteFlightAirportEditing/Airports#3775]
# Airport Name

Fausto Vega Santander

# Country?

México

# Improvements that need to be made?

Redone

# Are you working on this airport?
Yes

# Airport Priority? (A380, 10000ft+ Runway)

N/A

**Comment by airbus3d** [comment]
Airport sent for approval

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56427746-9402e900-6282-11e9-817a-255d23980e58.png)
