### ISSUE TITLE
CO97-Comanche Springs Ranch Airport-COLORADO-USA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3777]
# Airport Name

< Comanche Springs Ranch Airport >

# Country?

< USA >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by Balloonchaser** [comment]
Sent in for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54360586-2e905c80-4633-11e9-8107-7e6c8b4b23a0.png)
