### ISSUE TITLE
CO92-Frasier Ranch Airstrip-COLORADO-USA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3780]
# Airport Name

< Trinchera Ranch Airstrip Airport >

# Country?

< USA >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by Balloonchaser** [comment]
Sent in for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54484319-e4c19500-4831-11e9-8efb-bf9545d45304.png)

**Comment by kilt46** [comment]
Needs redone as Frasier Ranch Airstrip (was TRINCHERA RANCH AIRSTRIP)

**Comment by MajorTomMueller** [comment]
Are you doing it or is this a suggestion @kilt46 ?

**Comment by brennanhackard** [comment]
This airport was edited a long time ago and does not require any improvements. Closing this now.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104520971-a332da00-55c1-11eb-8b3b-edabda046187.png)
