### ISSUE TITLE
CO90-USAF Academy Bullseye AUX Airfield-COLORADO-USA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3781]
# Airport Name

< USAF Academy - Bullseye AUX Airfield  >

# Country?

< USA >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by Balloonchaser** [comment]
Sent in for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54484353-e2ac0600-4832-11e9-8e19-6544790f968b.png)
