### ISSUE TITLE
CO82-Land Airport-COLORADO-USA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3784]
# Airport Name

< Land Airport >

# Country?

< USA >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by Balloonchaser** [comment]
Sent in to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54484384-b3e25f80-4833-11e9-8ecc-83476b4206c5.png)
