### ISSUE TITLE
LIBC-Crotone Airport-CALABRIA-ITALY

### ISSUE THREAD

**Issue by royfr83** [InfiniteFlightAirportEditing/Airports#3787]
# Airport Name

Crotone Airport

# Country?

Italy

# Improvements that need to be made?

From scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

No

**Comment by royfr83** [comment]
Sent in for OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56079949-cadb8980-5dc0-11e9-920a-47676502f177.png)
