### ISSUE TITLE
01WY-Keyhole Airport-WYOMING-USA

### ISSUE THREAD

**Issue by 2018ljh** [InfiniteFlightAirportEditing/Airports#3788]
# Airport Name

Keyhole Airport

# Country?

USA

# Improvements that need to be made

Built from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

None

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54572891-b372d180-49b7-11e9-9935-d1bd841d8e72.png)
