### ISSUE TITLE
4IS1-Plain Crazy Strip-ILLINOIS-USA

### ISSUE THREAD

**Issue by airbus3d** [InfiniteFlightAirportEditing/Airports#3789]
# Airport Name

Juan Guillermo Villasana 

# Country?

México

# Improvements that need to be made?

Redone

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

N/A

**Comment by airbus3d** [comment]
Sent for approval...

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/89715947-f9df1c80-d96e-11ea-8d4f-a8cae1c05ed2.png)
