### ISSUE TITLE
EGCC-Manchester Airport-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by IceBlue02** [InfiniteFlightAirportEditing/Airports#379]
Manchester- closest not currently in IF. One will not touch without one's permission :)

**Comment by IceBlue02** [comment]
@freddiefrogs- this is mine to do I'm afraid :)

**Comment by IceBlue02** [comment]
Not having much time at the moment so freeing this up

@freddiefrogs ;)

**Comment by IFAEpat** [comment]
@JonathanAirbus ?

**Comment by Adam167** [comment]
Is this being done?

**Comment by Adam167** [comment]
As I can't see this being done I will start on this as is a global priority

**Comment by liamkirky** [comment]
Hey I want to do it

**Comment by Adam167** [comment]
Already started

**Comment by liamkirky** [comment]
Please let me do it

**Comment by dushyants19** [comment]
@Adam167 its yours!

**Comment by dushyants19** [comment]
@Adam167 hows this going?

**Comment by kilt46** [comment]
RUNWAY 05R/23L wrong length
![image](https://cloud.githubusercontent.com/assets/14023167/21734706/6a43ced8-d42a-11e6-950f-cdebbf1be7bf.png)
![image](https://cloud.githubusercontent.com/assets/14023167/21734723/81babb44-d42a-11e6-9f56-7fef5e01b9db.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21746858/6a12f980-d519-11e6-8c4e-ea63ef0b6fc1.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59852688-c0e88080-9345-11e9-9c9e-d6c73dab87ec.jpg)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/99734506-8037ee00-2a88-11eb-97f5-930cd5b77617.png)
