### ISSUE TITLE
LL28-SD Aero Strip-ILLINOIS-USA

### ISSUE THREAD

**Issue by airbus3d** [InfiniteFlightAirportEditing/Airports#3791]
# Airport Name

Gen Div P Angel Corzo Molina Airport

# Country?

Mexico

# Improvements that need to be made?

Redone

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

N/A

**Comment by brunocr98** [comment]
You have reached the limit of 3 airports. Please finish one of them in order to be assigned to other airports.

**Comment by airbus3d** [comment]
Oh! Sorry. I did not know about the limit.

**Comment by airbus3d** [comment]
Sending...

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/89716693-c4d5c880-d974-11ea-9500-53224df95435.png)
