### ISSUE TITLE
MMLC-Lazaro Cardenas Airport-MICHOACAN-MEXICO

### ISSUE THREAD

**Issue by airbus3d** [InfiniteFlightAirportEditing/Airports#3792]
# Airport Name

Lazaro Cardenas Airport

# Country?

Mexico

# Improvements that need to be made?

Redone

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

N/A

**Comment by liamkirky** [comment]
Are you doing this airport? If not may I take this?

**Comment by MBeringuy** [comment]
@liamkirky I'm assigning this airport to you.

**Comment by liamkirky** [comment]
Thanks!

**Comment by liamkirky** [comment]
Sent in for review!

**Comment by liamkirky** [comment]
Sent in for OR!

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/60033289-adf3ea00-967e-11e9-881e-f3a02ff3e704.jpg)
