### ISSUE TITLE
KHZX-Isedor Iverson Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by Gabe-Z** [InfiniteFlightAirportEditing/Airports#3793]
# Airport Name

< Isedor Iverson Airport >

# Country?

< USA >

# Improvements that need to be made?

< From scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by Gabe-Z** [comment]
Sent to the OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54879235-80d83700-4e04-11e9-8d8a-35b611a00530.png)
