### ISSUE TITLE
NZPM-Palmerston North Airport-MANAWATU-NEW ZEALAND

### ISSUE THREAD

**Issue by Lukeh0** [InfiniteFlightAirportEditing/Airports#3794]
# Airport Name

Palmerston North Airport

# Country?

New Zealand

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54858366-5e460100-4cd2-11e9-829a-5b4769711ab5.png)
Please check gates at airport

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54864669-5fa21880-4d28-11e9-991f-f2032883baf2.png)
