### ISSUE TITLE
NZNS-Nelson Airport-NELSON-NEW ZEALAND

### ISSUE THREAD

**Issue by Lukeh0** [InfiniteFlightAirportEditing/Airports#3796]
# Airport Name

Nelson Airport

# Country?

New Zealand

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55844033-0e07d500-5b01-11e9-9a52-20ba3f3c7e1c.png)
