### ISSUE TITLE
VIJP-Jaipur International Airport-RAJASTHAN-INDIA

### ISSUE THREAD

**Issue by akshay2777** [InfiniteFlightAirportEditing/Airports#3797]
# Airport Name

 Jaipur International Airport

# Country?

 India

# Improvements that need to be made?

 from scratch

# Are you working on this airport?

 yes

# Airport Priority? (A380, 10000ft+ Runway

 GP2(10000ft+Runway)

**Comment by Ayush-19** [comment]
May I take this airport?

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59194980-22983600-8b61-11e9-8f6e-4ba60e3dabc3.jpg)
