### ISSUE TITLE
MZCK-Caye Caulker Airport-COROZAL-BELIZE

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#3798]
# Airport Name

Caye Caulker Airport

# Country?

Belize

# Improvements that need to be made?

Airport is missing from repo

# Are you working on this airport?

yes

# Airport Priority? (A380, 10000ft+ Runway)

none

**Comment by HiFlyerBwi** [comment]
Sent in for OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54870553-1082d480-4d76-11e9-9d52-0f9e324b0491.png)
