### ISSUE TITLE
YSSY-Sydney Kingsford Smith Airport-NEW SOUTH WALES-AUSTRALIA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#38]

**Comment by carmichaelalonso** [comment]
Fixes by David Cutler

**Comment by Swang007** [comment]
Runway hold-short spawns removed by John 16 days before this post.

**Comment by kilt46** [comment]
Is this free to do?

**Comment by samuelandersson** [comment]
Asking the same as Kilt, free to take?

**Comment by HenrikBerg02** [comment]
Doing this one.

**Comment by kilt46** [comment]
rewritten

**Comment by samuelandersson** [comment]
https://community.infinite-flight.com/t/yssy-parking-mistake/52065?u=samuel123abc

**Comment by dushyants19** [comment]
Kilt confirmed in that topic that **This is not an issue**

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19014208/36461692-87ac-11e6-9b96-c137a37b8e83.png)
![image](https://cloud.githubusercontent.com/assets/14023167/19014213/7488ce4a-87ac-11e6-89dd-685174b0c7b0.png)
![image](https://cloud.githubusercontent.com/assets/14023167/19014215/83c4565e-87ac-11e6-8534-1d3300501c00.png)

**Comment by CalumBrayshaw** [comment]
Sydney Airport looks soo good I can't wait to see it in the update

**Comment by moritzbabl** [comment]
Airport has gating issues and some design issues, needs an update

**Comment by dushyants19** [comment]
Approach Freq has a weird name

**Comment by kilt46** [comment]
Please remove ALL Buildings on completion

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44947658-4199b880-add6-11e8-9735-cf12c09c4b2e.png)

**Comment by kilt46** [comment]
Boundary Fix

**Comment by MajorTomMueller** [comment]
Sydney is not the capital of Australia. 
That’s Canberra
https://en.wikipedia.org/wiki/Canberra

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/99978215-478b6380-2d6b-11eb-9315-5421272ec483.png)
