### ISSUE TITLE
LEDA

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#380]
I will do my local airport, Aeroport de Lleida-Alguaire.

**Comment by kilt46** [comment]
This Airport is off from satellite. Also no terminal building - Suggest REDO
![image](https://cloud.githubusercontent.com/assets/14023167/15095612/d5c70b80-1494-11e6-8cca-6e01d1d00f04.png)

**Comment by NickArt1342** [comment]
@vkrgarcia Are you doing it?

**Comment by dushyants19** [comment]
@carmichaelalonso worse, how could you approve this? 😡

**Comment by dushyants19** [comment]
Redone in 3d298ee2d0b72b3506bc3a967ff518decd72805e

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18897173/5c2945f8-84ed-11e6-8c23-5746e3012287.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109084245-09387400-76cd-11eb-84f8-f3ba92d3759d.png)
