### ISSUE TITLE
MZCZ-Corozal Airport-COROZAL-BELIZE

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#3800]
# Airport Name

Corozal Airport

# Country?

Belize

# Improvements that need to be made?

Airport is missing from repo

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

None

**Comment by HiFlyerBwi** [comment]
Working on this.

**Comment by HiFlyerBwi** [comment]
Working on this airport.

**Comment by HiFlyerBwi** [comment]
Sent in for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54870990-b08f2c80-4d7b-11e9-9ef3-cc3ccaec341d.png)
