### ISSUE TITLE
MZTH-Orange Walk Airport-ORANGE WALK-BELIZE

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#3801]
# Airport Name

Orange Walk Airport

# Country?

Belize

# Improvements that need to be made?

Airport is missing from repo

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

None

**Comment by HiFlyerBwi** [comment]
Working on this.

**Comment by HiFlyerBwi** [comment]
Working on this airport.

**Comment by HiFlyerBwi** [comment]
Sent in for OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54870613-eda4f000-4d76-11e9-97b9-332d585a58e1.png)
