### ISSUE TITLE
MZMF-San Ignacio Town Airstrip-CAYO-BELIZE

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#3803]
# Airport Name

San Ignacio Town Airstrip/Maya Flats

# Country?

Belize

# Improvements that need to be made?

Airport is missing from repo

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

None

**Comment by HiFlyerBwi** [comment]
Working on this.

**Comment by HiFlyerBwi** [comment]
Sent in for OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54871703-ae7e9b00-4d86-11e9-998e-831c94819887.png)
