### ISSUE TITLE
MZKT-Silver Creek Airport-STANN CREEK-BELIZE

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#3804]
# Airport Name

Silver Creek Airport

# Country?

Belize

# Improvements that need to be made?

Airport is missing from repo

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

None

**Comment by HiFlyerBwi** [comment]
Working on this.

**Comment by HiFlyerBwi** [comment]
Sent in for OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54872071-6b272b00-4d8c-11e9-9ba5-6925b3756807.png)
