### ISSUE TITLE
MZBB-Blackbird Caye Airstrip-BELIZE-BELIZE

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#3805]
# Airport Name

Blackbird Caye Airstrip

# Country?

Belize

# Improvements that need to be made?

Airport is missing from repo

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

None

**Comment by HiFlyerBwi** [comment]
Working on this.

**Comment by HiFlyerBwi** [comment]
Sent in for OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54871430-a839f000-4d81-11e9-85f2-4a39606854bb.png)
