### ISSUE TITLE
SBMS-Mossoro Airport-RIO GRANDE DO NORTE-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3806]
# Airport Name

Mossoro Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54496104-5c86d280-48b9-11e9-954c-30bde91f01cf.png)

**Comment by MBeringuy** [comment]
Spaws and markings have been corrected on both aprons.
