### ISSUE TITLE
CO67-Big View Airport-COLORADO-USA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3808]
# Airport Name

< Big View Airport >

# Country?

< USA >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by Balloonchaser** [comment]
Sent in for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54498963-0b87d600-48db-11e9-9d09-75df8c3c2639.png)
