### ISSUE TITLE
OKBK-Kuwait Intl Airport-KUWAIT CITY-KUWAIT

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#381]
Recycling is good.

**Comment by dushyants19** [comment]
@vkrgarcia assign yourself please.

**Comment by Swang007** [comment]
@vkrgarcia Are you still working on this? Let us know here or in Slack if you have any questions :)

**Comment by ReflexRSM** [comment]
I'll grab this one!

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19213491/4b7fbb9e-8d33-11e6-9097-6fc7699efa0b.png)
![image](https://cloud.githubusercontent.com/assets/14023167/19213496/72b8ddda-8d33-11e6-9c5b-c80ab3bcf8ea.png)

**Comment by dushyants19** [comment]
Minor improvements by Sumith b580fcf

**Comment by ryu12332** [comment]
ISSUE: The ground frequency is missing 
[FREQUENCIES](https://skyvector.com/airport/OKBK/Kuwait-Airport)

**Comment by brunocr98** [comment]
It looks like the airport has all the frequencies according to SkyVector, nothing to correct here.

**Comment by MajorTomMueller** [comment]
Cargo Apron missing, may be some other issues as well.

![Screenshot_٢٠٢٠٠٥٢٧_١٣١٧٣١](https://user-images.githubusercontent.com/26853210/83540831-61e53280-a4e8-11ea-9dde-804ec5fb54ff.jpg)
![Screenshot_20200527_131333_com google android apps docs](https://user-images.githubusercontent.com/26853210/83540845-6578b980-a4e8-11ea-908d-ae4b2bbe5703.jpg)


![Screenshot_20200527_131333_com google android apps docs(1)](https://user-images.githubusercontent.com/26853210/83540819-5db91500-a4e8-11ea-9291-47b88be84493.jpg)

**Comment by MajorTomMueller** [comment]
Cargo spawns we’ll be added as now in imagery available.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115964078-4d3ad000-a4e8-11eb-83a4-dc3135d7f6d6.png)
