### ISSUE TITLE
SWLP-Faz Rosa Paralelo Airport-MATO GROSSO-BRAZIL

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3810]
# Airport Name

< Faz Rosa Paralelo Airport >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by Balloonchaser** [comment]
Sent in for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54500831-0d5b9480-48ef-11e9-95cc-1a6754762255.png)
