### ISSUE TITLE
EFKE-Kemi-Tornio Airport-LAPLAND-FINLAND

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#3811]
# Airport Name

< Kemi-Tornio Airport >

# Country?

< Finland >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kztmtn** [comment]
Sent for OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54650720-cc45ba80-4a7d-11e9-9f5e-3b19388b11e4.png)
