### ISSUE TITLE
01NM-Champion Ranch Airport-NEW MEXICO-USA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3812]
# Airport Name

< Champion Ranch Airport >

# Country?

< USA >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by Balloonchaser** [comment]
Sent in for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54500785-71ca2400-48ee-11e9-9892-8c4150adae36.png)
