### ISSUE TITLE
CYSY-Sachs Harbour Airport-NORTHWEST TERRITORIES -CANADA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3813]
# Airport Name

< Sachs Harbour Airport >

# Country?

< Canada >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by Balloonchaser** [comment]
Sent in for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54499286-feb8b180-48dd-11e9-9596-a1f6ecaa6cdb.png)
