### ISSUE TITLE
KPKD-Park Rapids Municipal-Konshok Field Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by Gabe-Z** [InfiniteFlightAirportEditing/Airports#3815]
# Airport Name

Park Rapids Municipal-Konshok Field Airport

# Country?

USA

# Improvements that need to be made?

From Scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

None

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55843839-e106f280-5aff-11e9-9c59-6b12153aaf7a.png)
