### ISSUE TITLE
CYUB-Tuktoyaktuk/James Gruben Airport-NORTHWEST TERRITORIES-CANADA 

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3817]
# Airport Name

< Tuktoyaktuk/James Gruben Airport >

# Country?

< Canada >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by Balloonchaser** [comment]
Sent in for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54883980-6a000780-4e39-11e9-883a-1169d5612eb9.png)
