### ISSUE TITLE
CYKD-Aklavik Airport-NORTHWEST TERRITORIES-CANADA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3818]
# Airport Name

< Aklavik Airport >

# Country?

< Canada >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by Balloonchaser** [comment]
Sent in for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54649881-f4cbb580-4a79-11e9-9a46-d48f178bbdf9.png)

**Comment by kilt46** [comment]
Redone by Balloonchaser
