### ISSUE TITLE
EFKI-Kajaani Airport-LAPLAND-FINLAND

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#3819]
# Airport Name

< Kajaani Airport >

# Country?

< Finland >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kztmtn** [comment]
Sent for OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54576479-55011f80-49c6-11e9-8ce4-93d2efdbad41.png)
