### ISSUE TITLE
KFWA-Fort Wayne-INDIANA-USA

### ISSUE THREAD

**Issue by DavidCutler** [InfiniteFlightAirportEditing/Airports#382]
Indiana

**Comment by henrikbg** [comment]
Added cargo area and west ramp. This airport still needs work. Hold shorts not snapped, the list goes on.

**Comment by dushyants19** [comment]
What needs to be done here, @henrikbg?

**Comment by dushyants19** [comment]
Nvm

**Comment by dushyants19** [comment]
Fixes in d992c5cc61231b52bc54ce2b16ec180a2b601fae

**Comment by kilt46** [comment]
nooooooo. missing outlines. bah humbug!

**Comment by dushyants19** [comment]
There were red outlines, should I add them?

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18897599/3ba474d4-84f1-11e6-90a9-93af0365d1ce.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18897606/49b2ffbe-84f1-11e6-94d7-d304807de7b9.png)

**Comment by kilt46** [comment]
Outlines added. Helps define aircraft size   :)

**Comment by dushyants19** [comment]
Aha, Ill do it next time. Sorry :/

**Comment by kilt46** [comment]
Additional eastern taxiway added
![image](https://cloud.githubusercontent.com/assets/14023167/23822820/227b1e90-061a-11e7-925a-1c961ece9129.png)
