### ISSUE TITLE
UHKD-Dzyomgi Airport-KOMSOMOLSKA-NA-AMURE-RUSSIA

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#3820]
# Airport Name

< Dzyomgi Airport >

# Country?

< Russia >

# Improvements that need to be made?

< Generated Airport, from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low, the site of a major Sukhoi plant >

**Comment by kztmtn** [comment]
Sent for OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55682924-65d6ee00-58ff-11e9-8ce1-0cc90c48c699.png)
