### ISSUE TITLE
LIRM-Grazzanise Airport-CAMPANIA-ITALY

### ISSUE THREAD

**Issue by kikefernandezw** [InfiniteFlightAirportEditing/Airports#3821]
♻️

**Comment by MajorTomMueller** [comment]
recycled

**Comment by MajorTomMueller** [comment]
![EEKU-git](https://user-images.githubusercontent.com/26853210/64075523-f8aa6780-cca8-11e9-94e4-8f3f13a73e99.png)

**Comment by MajorTomMueller** [comment]
messed some thing up, could be recycled ...

**Comment by MajorTomMueller** [comment]
Recycled

**Comment by MajorTomMueller** [comment]
https://github.com/InfiniteFlightAirportEditing/Airports/commit/348631ddfc5e70fe9c3609e805ba9098a7c1463e

![LIRM Git](https://user-images.githubusercontent.com/26853210/68028493-f4042e80-fcac-11e9-9cc4-dabaa1215d17.png)
