### ISSUE TITLE
LFOT-Tours Val de Loire Airport-PAYS DE LA LAIRE-FRANCE

### ISSUE THREAD

**Issue by Martijn-Decates** [InfiniteFlightAirportEditing/Airports#3822]
# Airport Name

< Tours Val de Loire Airport >

# Country?

< France >

# Improvements that need to be made?

< Full rework >

# Are you working on this airport?

< yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Army >

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/60142650-192de100-9791-11e9-9368-162d2f879a22.jpg)
