### ISSUE TITLE
CYSB-Sudbury Airport-SUDBURY-ONTARIO-CANADA

### ISSUE THREAD

**Issue by DelsterX** [InfiniteFlightAirportEditing/Airports#3823]
# Airport Name

< Sudbury Airport >

# Country?

< Canada >

# Improvements that need to be made?

<Redone form Scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low Priority; Project Canada>

**Comment by DelsterX** [comment]
Submitted to OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/58919803-d46cd800-8705-11e9-9212-83fa56cb15ae.jpg)
