### ISSUE TITLE
VTSG-Krabi Airport-KRABI-THAILAND

### ISSUE THREAD

**Issue by kikefernandezw** [InfiniteFlightAirportEditing/Airports#3826]
♻️

**Comment by Gabe-Z** [comment]
The airport is now in Offical Review.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/77239744-df252a80-6bbc-11ea-8b4b-a11a8ec9f736.jpg)
