### ISSUE TITLE
CZFN-Tulita Airport-NORTHWEST TERRITORIES-CANADA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3827]
# Airport Name

< Tulita Airport >

# Country?

< Canada >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by Balloonchaser** [comment]
Sent in

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54649597-ef21a000-4a78-11e9-9979-cf2d1f6bba15.png)

**Comment by kilt46** [comment]
Redone by Balloonchaser
