### ISSUE TITLE
CZFM-Fort McPherson Airport-NORTHWEST TERRITORIES-CANADA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3828]
# Airport Name

< Fort McPherson Airport >

# Country?

< Canada >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by Balloonchaser** [comment]
Sent In

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54649370-e5e40380-4a77-11e9-9499-3f28958d4bcd.png)

**Comment by kilt46** [comment]
Redone by Balloonchaser
