### ISSUE TITLE
CYWY-Wrigley Airport-NORTHWEST TERRITORIES-CANADA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3829]
# Airport Name

< Wrigley Airport >

# Country?

< Canada >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by Balloonchaser** [comment]
Sent In

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54727334-38d7bc80-4b45-11e9-9901-94972f4939b8.png)

**Comment by kilt46** [comment]
Done from scratch by Balloonchaser
