### ISSUE TITLE
CYWE-Wekweeti Airport-NORTHWEST TERRITORIES-CANADA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3830]
# Airport Name

< Wekweètì Airport >

# Country?

< Canada >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by Balloonchaser** [comment]
Sent In

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54727077-e34ee000-4b43-11e9-991e-060c2acea795.png)

**Comment by kilt46** [comment]
Done from scratch by Balloonchaser
