### ISSUE TITLE
CYRA-Rae Lakes Airport-NORTHWEST TERRITORIES-CANADA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3831]
# Airport Name

< Rae Lakes Airport >

# Country?

< Canada >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by Balloonchaser** [comment]
Sent In

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54727647-f9aa6b00-4b46-11e9-9557-2be651f070bb.png)

**Comment by kilt46** [comment]
Done from scratch by Balloonchaser
