### ISSUE TITLE
CYPC-Paulatuk Airport-NORTHWEST TERRITORIES-CANADA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3832]
# Airport Name

< Paulatuk Airport >

# Country?

< Canada >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by Balloonchaser** [comment]
Sent In

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54727811-de8c2b00-4b47-11e9-8713-5a46b9410006.png)

**Comment by kilt46** [comment]
Done from scratch by Balloonchaser
