### ISSUE TITLE
SBPP-Ponta Pora Airport-MATO GROSSO DO SUL-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3833]
# Airport Name

Ponta Pora Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54878667-8c742f80-4dfd-11e9-97cd-ec9768c2055e.png)
