### ISSUE TITLE
SBTG-Tres Lagoas Airport-MATO GROSSO DO SUL-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3834]
# Airport Name

Tres Lagoas Airport

# Country?

Brazil

# Improvements that need to be made?

Done from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54878587-bed15d00-4dfc-11e9-9394-05332c3de7f7.png)
