### ISSUE TITLE
CYOA-Ekati Airport-NORTHWEST TERRITORIES-CANADA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3835]
# Airport Name

< Ekati Airport >

# Country?

< Canada >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by Balloonchaser** [comment]
Sent In

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54728002-12b41b80-4b49-11e9-8199-1e530f32aeed.png)

**Comment by kilt46** [comment]
Done from scratch by Balloonchaser
