### ISSUE TITLE
LFRE

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#3836]
# Airport Name

< Enter text here >

# Country?

< Enter text here >

# Improvements that need to be made?

< Enter text here >

# Are you working on this airport?

done by @Martijn-Decates without an issue, please create an issue prior to submitting an airport to avoid rejections in the future

# Airport Priority? (A380, 10000ft+ Runway)

< Enter text here >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54885988-a9861e00-4e50-11e9-8484-7851acb97974.png)
