### ISSUE TITLE
LFRZ

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#3837]
# Airport Name

< Enter text here >

# Country?

< Enter text here >

# Improvements that need to be made?

< Enter text here >

# Are you working on this airport?

done by @Martijn-Decates, again, an issue must be created before submission!

# Airport Priority? (A380, 10000ft+ Runway)

< Enter text here >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54885054-0d571980-4e46-11e9-97e0-0cd6edb7ba86.png)
