### ISSUE TITLE
CYLK-Lutselk'e Airport-NORTHWEST TERRITORIES-CANADA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3838]
# Airport Name

< Lutselk'e Airport >

# Country?

< Canada >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by Balloonchaser** [comment]
Sent In

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54728353-5f98f180-4b4b-11e9-8fce-f9177001cfe4.png)

**Comment by kilt46** [comment]
Done from scratch by Balloonchaser
