### ISSUE TITLE
CYJP-Fort Providence Airport-NORTHWEST TERRITORIES-CANADA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3839]
# Airport Name

< Fort Providence Airport >

# Country?

< Canada >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes>

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by Balloonchaser** [comment]
Sent In

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54728663-43964f80-4b4d-11e9-9695-36b3686f999d.png)

**Comment by kilt46** [comment]
Done from scratch by Balloonchaser
