### ISSUE TITLE
YMTG-Mount Gambier Airport-SOUTH AUSTRALIA-AUSTRALIA

### ISSUE THREAD

**Issue by BVRAU** [InfiniteFlightAirportEditing/Airports#384]
Creating Mount Gambier Airport, SA. Non-Region airport

**Comment by BVRAU** [comment]
Finished and Submitted

**Comment by samuelandersson** [comment]
@BVRAU How's this going?

**Comment by dushyants19** [comment]
How is this going? Been a whopping 7 months.

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26036550/48b2ffac-38a5-11e7-9a42-144c0df4fb1b.png)
