### ISSUE TITLE
0WY0-Freedom Air Ranch Airport-WYOMING-USA

### ISSUE THREAD

**Issue by 2018ljh** [InfiniteFlightAirportEditing/Airports#3840]
# Airport Name

Freedom Air Ranch

# Country?

USA

# Improvements that need to be made?

Needs to be built.

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

None

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/66594801-320ba800-eb70-11e9-963b-569d8818064b.jpg)
