### ISSUE TITLE
KBIL-Billings Logan International Airport-MONTANA-USA

### ISSUE THREAD

**Issue by IFC-PlaneCrazy** [InfiniteFlightAirportEditing/Airports#3843]
# Airport Name

Billings Logan International Airport

# Country?

USA

# Improvements that need to be made?

Will be redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

10000ft+ Runway

**Comment by IFC-PlaneCrazy** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56582572-37167400-659d-11e9-9db6-6ea6cbc53838.png)
