### ISSUE TITLE
CYYB-North Bay/Jack Garland Airport-North Bay-ONTARIO-CANADA

### ISSUE THREAD

**Issue by DelsterX** [InfiniteFlightAirportEditing/Airports#3844]
# Airport Name

< North Bay/Jack Garland Airport >

# Country?

< Canada >

# Improvements that need to be made?

< Redone from Scratch >

# Are you working on this airport?

<Yes>

# Airport Priority? (A380, 10000ft+ Runway)

< Low Priority, Project Canada >

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59350348-3fb03e80-8cf2-11e9-9af2-323b4089d7fc.jpg)
