### ISSUE TITLE
KOGS-Ogdensburg International Airport-NEW YORK-USA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3845]
# Airport Name

< Ogdensburg International Airport >

# Country?

< USA >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< None >

**Comment by Balloonchaser** [comment]
Sent In For OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56617857-8d5bd500-65e6-11e9-8252-eac5707b0d71.png)
