### ISSUE TITLE
FXMM-Moshoeshoe Airport-MASERU-LESOTHO

### ISSUE THREAD

**Issue by rich-art-02** [InfiniteFlightAirportEditing/Airports#3846]
# Airport Name

Moshoeshoe International Airport

# Country?
Lesotho

# Improvements that need to be made?
Complete Rework from scratch

# Are you working on this airport?

yes

# Airport Priority? (A380, 10000ft+ Runway)
10000ft+ Runway 04/22: 10499ft

**Comment by rich-art-02** [comment]
Sent in for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56607995-6fcf4100-65cf-11e9-9499-544b3b2c0fdf.png)
