### ISSUE TITLE
EPPO-Poznan Airport-GREATER POLAND-POLAND

### ISSUE THREAD

**Issue by Martijn-Decates** [InfiniteFlightAirportEditing/Airports#3848]
# Airport Name

< Pozan lawice airport >

# Country?

< Poland >

# Improvements that need to be made?

< full rework>

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< N/A >

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59698770-c3709c00-91c6-11e9-8ac9-8639141222f7.jpg)
