### ISSUE TITLE
81LL-Otterbach Farm-ILLINOIS-USA

### ISSUE THREAD

**Issue by AussieLuke** [InfiniteFlightAirportEditing/Airports#3849]
# Airport Name

Armidale Airport - YARM

# Country?

Australia

# Improvements that need to be made?

From scratch

# Are you working on this airport?

Yeah

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90318344-7638a900-def5-11ea-878a-4559ef8adc03.png)
