### ISSUE TITLE
SBKP-Campinas Viracopos Airport-SAO PAULO-BRAZIL

### ISSUE THREAD

**Issue by DavidCutler** [InfiniteFlightAirportEditing/Airports#385]
Recycling issues is awesome! ♻️ 

-Bruno

**Comment by samuelandersson** [comment]
@DavidCutler update please? :/

**Comment by TristinWoolf** [comment]
What is the story with this? I can't find an airport with this ICAO in the code. @DavidCutler ?

**Comment by bavAVIA** [comment]
@DavidCutler 
Did you mix this up with Funchal, Madeira?
That would be LPMA, IATA FNC. KFNC does not exist and LPMA is already being done.
See #597

**Comment by brunocr98** [comment]
Since KFNC doesn't exist, I have recycled the issue.

**Comment by brunocr98** [comment]
Estou a fazer este aeroporto.

**Comment by brunocr98** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24833062/c9d20620-1c83-11e7-9a31-d77edf41060c.png)

**Comment by RyanEpps** [comment]
@MBeringuy is fixing some things.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45265331-d459d900-b40e-11e8-8b1d-5059834812dc.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/89745527-01d7b300-da7a-11ea-89e2-c7d9b9c43488.png)

**Comment by brennanhackard** [comment]
I will be adding the new Azul Hangar and apron on the SE side of the airport.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103707700-bd8f0700-4f74-11eb-89c4-b7c2516c1771.png)
