### ISSUE TITLE
LL49-Raymond RLA-ILLINOIS-USA

### ISSUE THREAD

**Issue by AussieLuke** [InfiniteFlightAirportEditing/Airports#3850]
# Airport Name

Argyle Airport - YARG

# Country?

Australia

# Improvements that need to be made?

From scratch

# Are you working on this airport?

Yeah

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90318650-88b3e200-def7-11ea-830b-878390ebe21e.png)
