### ISSUE TITLE
KTNP-Twentynine Palms Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#3851]
# Airport Name

Twentynine Palms Airport

# Country?

USA

# Improvements that need to be made?

Needs to be re-done from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

None

**Comment by HiFlyerBwi** [comment]
Submitted to OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55685410-7c8b3e00-591b-11e9-83af-ec067792674b.png)
