### ISSUE TITLE
3LL9-Compton Airstrip-ILLINOIS-USA

### ISSUE THREAD

**Issue by AussieLuke** [InfiniteFlightAirportEditing/Airports#3852]
# Airport Name

Aurukun Airport - YAUR

# Country?

Australia

# Improvements that need to be made?

From scratch

# Are you working on this airport?

Yeah

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by MajorTomMueller** [comment]
you are already assigned to 3 issues. Wait till those three are send to OR before taking a new one.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90335134-1d6e1c80-df98-11ea-9aa4-e2c21bb3848a.png)
