### ISSUE TITLE
SBBG-Bage Airport-RIO GRANDE DO SUL-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3854]
# Airport Name

Bage Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54873774-e6e4a000-4dab-11e9-84e2-fcfc8520bf13.png)
