### ISSUE TITLE
EFJY-Jyvaskyla Airport-WESTERN FINLAND-FINLAND

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#3855]
# Airport Name

< Jyvaskyla Airport >

# Country?

< Finland >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kztmtn** [comment]
Sent for OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55683230-27433280-5903-11e9-9328-65d6bde3047f.png)
