### ISSUE TITLE
3IS7-Foote Strip-ILLINOIS-USA

### ISSUE THREAD

**Issue by ProFlightSim** [InfiniteFlightAirportEditing/Airports#3856]
# Airport Name

< Miri, Borneo (WGBR - MRI) >

# Country?

< Malaysia >

# Improvements that need to be made?

< Whole airport needs to be redone. Looks like the airport is way back in the early 2000s. >

# Are you working on this airport?

< Yes. >

# Airport Priority? (A380, 10000ft+ Runway)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90324250-d4837d00-df31-11ea-9a73-49c8b3479e31.png)
