### ISSUE TITLE
MZSP-John Greif II Airport-COROZAL-BELIZE

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#3857]
# Airport Name

John Grief II Airport

# Country?

Belize

# Improvements that need to be made?

Airport is missing from repo

# Are you working on this airport?

yes

# Airport Priority? (A380, 10000ft+ Runway)

none

**Comment by HiFlyerBwi** [comment]
Submitted for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55276246-b4f99f00-52bf-11e9-8ca5-3f733561f7c7.png)
