### ISSUE TITLE
LSZH-Zurich Airport-ZURICH-SWITZERLAND

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#386]
Work in progress

**Comment by Aviationluver** [comment]
@NickArt1342 Are you still doing this one?

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24590447/d2d63e9c-17b2-11e7-87b0-6b56fceab502.png)

**Comment by dushyants19** [comment]
Just a month left to complete nick 😱

**Comment by NickArt1342** [comment]
Wait what. I still have a month? I thought all I had are -1 day...

**Comment by dushyants19** [comment]
Nick I made a timer to help you coordinate your last hours: http://bit.ly/2t0c7kP

**Comment by NickArt1342** [comment]
There ya go.

FYI: I'm actually refining this airport with the most up to date data atm as construction work on LSZH is happening right now.

**Comment by kilt46** [comment]
Apron missing
![image](https://user-images.githubusercontent.com/14023167/27776870-d95effd4-5f73-11e7-8a4e-846e4c65d052.png)

**Comment by kilt46** [comment]
Full array of gates missing
![image](https://user-images.githubusercontent.com/14023167/27776880-ecd219de-5f73-11e7-83a3-3f30567294f0.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27776887-f97bb8a2-5f73-11e7-8e55-61b0cbf66451.png)

**Comment by NickArt1342** [comment]
The chart you uploaded is not up to date.

**Comment by dushyants19** [comment]
- Unsnapped Nodes
![image](https://user-images.githubusercontent.com/13567007/27781134-40ec04aa-5fea-11e7-92d6-0a538a8eb975.png)

- Shoulder taxiways for both runways are transparent and are overlapping other taxiways

![image](https://user-images.githubusercontent.com/13567007/27781204-9070f454-5fea-11e7-884b-6ed40bf5c9d7.png)

- Missing Airport Boundary
- Missing Airport Beacon
- Many small lines have no taxiway beneath, delete them or draw an apron 

![image](https://user-images.githubusercontent.com/13567007/27781352-1e615a6a-5feb-11e7-9ee4-bbed1774d0aa.png)


- This taxiway is transparent, why? just why? Waste of resources

![image](https://user-images.githubusercontent.com/13567007/27781234-b2023826-5fea-11e7-92ef-5cc8ec674eaa.png)


- White outlined buildings here: 

![image](https://user-images.githubusercontent.com/13567007/27781352-1e615a6a-5feb-11e7-9ee4-bbed1774d0aa.png)

- All PAPIs are incorrectly oriented 


****

I'll post more when I find'em

**Comment by dushyants19** [comment]
- Lines are overcurved 

![image](https://user-images.githubusercontent.com/13567007/27781466-9cee6044-5feb-11e7-9a5f-0cde5fe9137d.png)

- Unsnapped Taxiways

![image](https://user-images.githubusercontent.com/13567007/27781505-b9a55440-5feb-11e7-97c1-33243dbb17db.png)

**Comment by dushyants19** [comment]
- Missing Ramp Operation Type for all spawns
- Missing gate Prefix
- Missing A380 spawn

**Comment by NickArt1342** [comment]
@dushyants19 
* Nope
* Nope
* Nope

**Comment by NickArt1342** [comment]
<img width="416" alt="bildschirmfoto 2017-07-03 um 09 06 33" src="https://user-images.githubusercontent.com/11133893/27781629-137d6678-5fcf-11e7-9d21-0748463a62ef.png">
<img width="238" alt="bildschirmfoto 2017-07-03 um 09 06 11" src="https://user-images.githubusercontent.com/11133893/27781630-13846356-5fcf-11e7-8c8a-ece67dcf2559.png">

**Comment by NickArt1342** [comment]
<img width="527" alt="bildschirmfoto 2017-07-03 um 09 08 03" src="https://user-images.githubusercontent.com/11133893/27781647-25da5934-5fcf-11e7-9adf-bcfbc70d5ad8.png">

**Comment by dushyants19** [comment]
Export as 10.50. File -> Export Target ->10.50

**Comment by NickArt1342** [comment]
Did that Done that. I'll send it again then...

The overlapping issues will be resolved by the new huge taxiway I'm currently trying to get to work. Help with that would be appreciated.

**Comment by NickArt1342** [comment]
* Show me one single unsnapped node.
* boundary including beacon were set to invisible, fixed in next upload
* Taxiway below them was set to invisible as well, fixed in the last version, siad taxiway is however not finished yet as it's not working currently.
* Well the PAPIs are just embarrassing. 
* Where is said overcurved line?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27792521-b8d0be46-5fbf-11e7-80ca-614e70ce4e04.png)

**Comment by kilt46** [comment]
Handing this airport over to another editor. Too many errors!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27792591-1dca5596-5fc0-11e7-9e59-49a930e30dfc.png)

**Comment by dushyants19** [comment]
🔥 💣 💥

**Comment by NickArt1342** [comment]
All errors resolved except of Runway Holds with last push. Only few gates missing now.
even the huge asphalt taxiway is working now.

**Comment by NickArt1342** [comment]
Tell me what you think of the *outter road* taxiway, it took most of the day to make it work.

**Comment by moritzbabl** [comment]
ok, what do we have here...

- Spawns are not snapped to the lines
- still some lines outside of any apron
- Dock E is missing all gate outlines
- this area is a snapping hell: 
![unbenannt](https://user-images.githubusercontent.com/19365980/27808024-44df599e-6045-11e7-9340-b6a78dfc6217.JPG)
- Do we really need asphalt buildings inside of asphalt buildings?
- I'm still missing something called boundary and beacon here, not to mention the tower viewpoint
- I'm almost certain this taxiway is NOT shaped this way:
![twy](https://user-images.githubusercontent.com/19365980/27808091-d20c5358-6045-11e7-984f-725cbc9ee892.JPG)

Just for the record, how long do we want to continue this puzzle game?

**Comment by NickArt1342** [comment]
As you can see I'm working as fast as I can to resolve anything.

* How do you snap a spawn to a line when there is no node? create one specifically for the soawn?
*consider it done
*Consider it done
*I must have missed that part there
*What?
*Done
*It actually is.

**Comment by moritzbabl** [comment]
Finally had time to have a quick look at the latest version and detected the following issues:

- unnecessarily the terminals were built from quite a number of separate taxiways
- hangars in the south are the same material as the taxiway around them and one has some unsnapped nodes, also the terminal (asphalt) is touching quite a large area of asphalt
- G/A parking spots including markings at old RWY 02/20 are missing
- hole between 02/20 and the heli area is missing
- old 02/20 is drawn as asphalt while it is concrete irl
- remote position spawns south of 10/28 are missing
- Dock E gate outlines are missing, several outlines for the main terminal could be more accurate
- spawns are still not snapped (yes, you are supposed to add a new node to snap them to)
- G/A hangars in the east are not added
- runway markings are incorrect for all runways
- Do Zurich's PAPIs really have 2° angles? considering the fuss about noisy airplanes in Switzerland and Germany and the Terrain around it seems wrong

**Comment by dushyants19** [comment]
@moritzbabl all yours

**Comment by moritzbabl** [comment]
believe it or not, done!

**Comment by NickArt1342** [comment]
@moritz So my commit went through! :D

**Comment by NickArt1342** [comment]
Nevermind...

**Comment by dushyants19** [comment]
Wrong Moritz and it didn't go through

**Comment by NickArt1342** [comment]
This area is not under construction.

<img width="286" alt="bildschirmfoto 2017-08-13 um 19 47 50" src="https://user-images.githubusercontent.com/11133893/29252055-d09e9266-8060-11e7-91b3-81da7c740017.png">
<img width="618" alt="bildschirmfoto2017-07-01um13 16 44" src="https://user-images.githubusercontent.com/11133893/29252054-d09a4a76-8060-11e7-8322-12d57744c7f6.png">

The lines aren't yellow with black but only single yellow

https://flic.kr/p/to6NMF

Only at the gates it is with yellow with black:

https://flic.kr/p/t6qRVf

This area isn't concrete, but asphalt:

<img width="760" alt="bildschirmfoto 2017-08-13 um 19 43 20" src="https://user-images.githubusercontent.com/11133893/29252061-000c533a-8061-11e7-8378-94228ad8db8c.png">
<img width="736" alt="bildschirmfoto 2017-08-13 um 19 42 53" src="https://user-images.githubusercontent.com/11133893/29252062-007776e2-8061-11e7-805f-e70ca3b1daa7.png">

The asphalt shoulder is missing on most holes and the concrete isn't actually shaped as it is in real life:

<img width="286" alt="bildschirmfoto 2017-08-13 um 19 47 50" src="https://user-images.githubusercontent.com/11133893/29252065-0ee6d542-8061-11e7-8d76-12d66c86f92d.png">
<img width="438" alt="bildschirmfoto 2017-08-13 um 19 46 51" src="https://user-images.githubusercontent.com/11133893/29252068-0f6b21d0-8061-11e7-8c23-44805be06c29.png">

Asphalt runway shoulder is missing at some parts:

<img width="727" alt="bildschirmfoto 2017-08-13 um 19 45 17" src="https://user-images.githubusercontent.com/11133893/29252067-0f6206a4-8061-11e7-9798-ce93a88b3957.png">
<img width="852" alt="bildschirmfoto 2017-08-13 um 19 45 02" src="https://user-images.githubusercontent.com/11133893/29252066-0f60fef8-8061-11e7-88bc-3d433b4868c9.png">

**Comment by moritzbabl** [comment]
Nick, you had more than enough time to complete this airport. When the time limit was over you commited an airport that looked worse than any missing 10cm asphalt shoulder could make it look. The construction sites are visible on the latest Google Earth image available. I don't own an own satellite, if you do I will happily add the new layout. 
As you used to be a supervisor you should also know that every airport is built with a certain level of simplification. If I hadn't added the GA area in concrete one would not have been able to distinguish apron and buildings in that area since some buildings touch both concrete and asphalt. I furthermore added the black lines since the visibility is increased on concrete this way. If a majority of the airport editors think this is not the standard for IF airports I can change the lines to normal yellows. This is just ridiculous right now...

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29266337-0c83ece2-80aa-11e7-84f0-cb9cef46ab64.png)

**Comment by dushyants19** [comment]
"New Taxiway 1" is invisible (the huge one with roads)

**Comment by brunocr98** [comment]
Asphalt taxiways are now visible.

**Comment by moritzbabl** [comment]
Going to add the new runway turnoffs and spawns

**Comment by moritzbabl** [comment]
fixed done

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68997698-1048c380-0888-11ea-9760-32cb77088cc9.jpg)
