### ISSUE TITLE
MD31-Forest Hill Airport-MARYLAND-USA

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#3861]
# Airport Name

Forest Hill Airport

# Country?

USA

# Improvements that need to be made?

re-done from scratch

# Are you working on this airport?

yes

# Airport Priority? (A380, 10000ft+ Runway)

none

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55446650-1b174800-5586-11e9-95c1-a02772b8be90.png)
