### ISSUE TITLE
SNOZ-Coronel Alexandre Airstrip-MARANHAO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3862]
# Airport Name

Coronel Alexandre Airstrip

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (A380, 10000ft+ Runway)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54884099-ef37ec00-4e3a-11e9-8152-96cbcb9257af.png)
