### ISSUE TITLE
KCOQ-Cloquet/Carlton County Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by danisrils39** [InfiniteFlightAirportEditing/Airports#3865]
# Airport Name

Cloquet/Carlton County Airport

# Country?

USA

# Improvements that need to be made?

Scratch

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by danisrils39** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55843600-b8cac400-5afe-11e9-88df-adad554978e6.png)
