### ISSUE TITLE
 LSGY-Yverdon-Les-Bains Airport-VAUD-SWITZERLAND 

### ISSUE THREAD

**Issue by grxninesix** [InfiniteFlightAirportEditing/Airports#3866]
# Airport Name

YVERDON LES BAINS LSGY

# Country?

SWITZERLAND

# Improvements that need to be made?

REWORK FROM SCRATCH

# Are you working on this airport?

YES (for a long time ago and also my first airport)

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
LOW PRIORITY

# CURRENT STATUS : 
In progress following OR rejection, expect PR submit soon

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55445672-16509500-5582-11e9-8a31-af0c3dfefed8.png)
