### ISSUE TITLE
SNCW-Centro de Lancamento de Alcantara AB-MARANHAO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3867]
# Airport Name

Centro de Lancamento de Alcantara

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55039939-51881c80-4ff4-11e9-9780-18b77e28f3cc.png)
