### ISSUE TITLE
SNBC-Barra do Corda Airstrip-MARANHAO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3868]
# Airport Name

Barra do Corda

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55040114-15a18700-4ff5-11e9-931f-4d8bca1d5ab4.png)
