### ISSUE TITLE
KOWA-Owatonna Degner Regional Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by Gabe-Z** [InfiniteFlightAirportEditing/Airports#3871]
# Airport Name

Owatonna Degner Regional Airport

# Country?

USA

# Improvements that need to be made?

From Scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by Gabe-Z** [comment]
Sent in for OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56101317-39673700-5ee8-11e9-95d0-8acb2fbe0f76.png)
