### ISSUE TITLE
LFRB-Brest Bretagne Airport-BRETAGNE-FRANCE

### ISSUE THREAD

**Issue by Bastien1533** [InfiniteFlightAirportEditing/Airports#3872]
# Airport Name

Brest-Bretagne / LFRB / BES 

# Country?

France

# Improvements that need to be made?

Gate restriction problem 

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

+10000ft (RWY 25L/07R)

**Comment by liamkirky** [comment]
Are you doing this airport, if not may I take it please?

**Comment by Bastien1533** [comment]
As I have loads of work, you can take it :)

**Comment by liamkirky** [comment]
Ok thanks. Please may I be assigned?

**Comment by liamkirky** [comment]
Could I take this airport please?

**Comment by MajorTomMueller** [comment]
@liamkirky interrested?

**Comment by liamkirky** [comment]
I can do, just need to complete my other airports. Unless you or anyone else is interested?

**Comment by MajorTomMueller** [comment]
there is a slot free @liamkirky ...

**Comment by liamkirky** [comment]
Only just seen your message. Sure I'll take it 😃

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107290960-067f2300-6a2d-11eb-9d5a-02470d0ec9f6.png)
