### ISSUE TITLE
EFSI-Seinajoki Airport-WESTERN FINLAND-FINLAND

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#3874]
# Airport Name

< Seinajoki Airport >

# Country?

< Finland >

# Improvements that need to be made?

< Redo from Scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kztmtn** [comment]
Submitted for OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55275588-4106c900-52b6-11e9-9447-18f50dc02e0e.png)
