### ISSUE TITLE
SDCO-Sorocaba Airport-SAO PAULO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3875]
# Airport Name

Sorocaba Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
Please check gates at terminal

![image](https://user-images.githubusercontent.com/14023167/55276389-50d7da80-52c1-11e9-9d35-9c4510dda4aa.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55279906-80500c80-52ec-11e9-873f-5ae53cac05f2.png)
