### ISSUE TITLE
CZBA-Burlington Executive Airport-ONTARIO-CANADA

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#3877]
# Airport Name

Burlington Executive Airport.

# Country?

Canada.

# Improvements that need to be made?

Redo from scratch.

# Are you working on this airport?

No. Leaving this for whom may be interested.

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Maximum Priority (maybe IF Events).

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55203978-723ea680-519b-11e9-9849-a730dd6e69e7.png)

**Comment by Bastien1533** [comment]
Can I be assigned ?

**Comment by dmp457** [comment]
can I be assigned will be my first airport, but I will certainly do my best!

**Comment by RyanEpps** [comment]
Are you in our slack team yet? If so, please shoot a PM my way. 

Thanks!

**Comment by Balloonchaser** [comment]
Sent to OR - :)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78402894-cad82900-75d1-11ea-8841-5adb8a58764d.jpg)
