### ISSUE TITLE
LLHZ-Herzlia Airport-HAMERKAZ-ISRAEL

### ISSUE THREAD

**Issue by royfr83** [InfiniteFlightAirportEditing/Airports#3878]
# Airport Name

Herzlia Airport

# Country?

Israel

# Improvements that need to be made?

From scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by royfr83** [comment]
Submitted for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56591107-c62b8800-65ad-11e9-8859-ef4f70b26875.png)
