### ISSUE TITLE
EFVA-Vaasa Airport-WESTERN FINLAND-FINLAND

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#3879]
# Airport Name

< Vaasa Airport >

# Country?

< Finland >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MBeringuy** [comment]
My friend, I assigned this airport to you; but I ask that in the future you wait for the OR close the issues that you have open for you to create new ones, because the members of the team is allowed a maximum of 3 issues open in GitHub, do you understand me?

**Comment by kztmtn** [comment]
Submitted for OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55594841-c2bb8400-5706-11e9-978c-92bff4fabc2a.png)
