### ISSUE TITLE
EGDM-Boscombe Down Airport-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by dushyants19** [InfiniteFlightAirportEditing/Airports#388]
London
Requires a lot of taxilines and a possible re-do

**Comment by IFAEpat** [comment]
Almost done with this one, only a few roadways left! :)

**Comment by samuelandersson** [comment]
@IFAEpat is this done?

**Comment by IFAEpat** [comment]
@samuelandersson yes

**Comment by IFAEpat** [comment]
This was my second airport, needs closing

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17196695/1b700d86-542c-11e6-89af-e2aa5a054936.png)

**Comment by IFAEpat** [comment]
Gating

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17642697/44ca69ec-6115-11e6-8d64-3a3f3642d356.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17642699/4f32d69e-6115-11e6-92b8-6df9c73c15be.png)

**Comment by moritzbabl** [comment]
@ewanfleming wants to fix several issues with the airport

**Comment by ewanfleming** [comment]
This has turned out to be more time consuming than I thought. As this airport has already been edited (whilst not to a high standard) I'm not going to redo it from scratch. I added some taxi lines and added a missing runway and I've sent it in for review.

**Comment by dushyants19** [comment]
I'll just rejecc

**Comment by dushyants19** [comment]
done

**Comment by ewanfleming** [comment]
Dish seems to be incapable of adding an airport that isn’t completely redone. He’s telling me to redo it all from scratch. If someone could convince him to add my slightly amended version, then that would be great. Otherwise I’ll be unassigned.

**Comment by dushyants19** [comment]
It wasn't on par so I couldn't add. Unassigned you.

**Comment by dushyants19** [comment]
thank you for the 1 suggestion 😡

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/35773803-26a51cd0-0922-11e8-9baf-1cc90695adfb.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/35783171-99fe3116-09c8-11e8-9010-776e5c9de064.png)
