### ISSUE TITLE
SAZM-Mar Del Plata Intl Airport-BUENOS AIRES-ARGENTINA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3881]
# Airport Name

Mar Del Plata Intl Airport

# Country?

Argentina

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55438679-ef856500-5567-11e9-86ab-31006ad1413c.png)
