### ISSUE TITLE
LFLY-Lyon Bron Airport-RHONE-ALPES-FRANCE

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#3883]
![image](https://user-images.githubusercontent.com/14023167/55280350-9d87d980-52f2-11e9-82b4-a817fb6107b6.png)

**Comment by kilt46** [comment]
REDONE FROM SCRATCH

**Comment by Czechoslovaki** [comment]
This airport is undoubtedly very suspicious looking, so I'm reworking this. 

- Everything is totally off imagery
- Missing lines / extra lines to be removed
- Runway pavement characteristics to be corrected

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102952351-96283c80-4494-11eb-928c-1353a296aa1a.png)
