### ISSUE TITLE
SADP-El Palomar Airport-BUENOS AIRES-ARGENTINA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3886]
# Airport Name

El Palomar Intl Airport

# Country?

Argentina

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55440179-7ccab880-556c-11e9-9968-ce3e32e43b71.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/87597453-760b7a80-c6b7-11ea-92ba-80cf7eb84d2c.png)
