### ISSUE TITLE
LIMB-Milan Bresso Airport-LOMBARDIA-ITALY

### ISSUE THREAD

**Issue by Eli2519** [InfiniteFlightAirportEditing/Airports#3887]
# Name of the Airport

< Bresso Airfield >

# Country?

<Italy>

# Improvements that need to be made?

<All airport to rework >

# Are you working on this airport?

<yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Milan >

**Comment by Eli2519** [comment]
LIMB REWORKED


[apt.zip](https://github.com/InfiniteFlightAirportEditing/Airports/files/3027157/apt.zip)

**Comment by Eli2519** [comment]
LIMB
[apt LIMB.zip](https://github.com/InfiniteFlightAirportEditing/Airports/files/3027166/apt.LIMB.zip)

**Comment by brunocr98** [comment]
Submit the apt.dat file on the peer-review channel.

**Comment by Eli2519** [comment]
where is the channel ?

**Comment by brunocr98** [comment]
You're not in our slack chat group?

**Comment by Eli2519** [comment]
NO

**Comment by brunocr98** [comment]
Alright, please don't use caps. Please join our slack chat group.

**Comment by Eli2519** [comment]
how can i join ? whats the url ?

**Comment by brunocr98** [comment]
Send an email to contact@airportediting.com

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/67235917-7d4e7200-f41e-11e9-804d-d346b91d42ad.jpg)

**Comment by brunocr1050** [comment]
Adding the following things:

missing grass taxiway
missing grass GA spawns
missing hangar spawns
missing small concrete apron

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106404783-7708bd00-63f9-11eb-963e-903c263c07df.png)
