### ISSUE TITLE
0W3-Harford County Airport-MARYLAND-USA

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#3888]
# Airport Name

Harford County Airport

# Country?

USA

# Improvements that need to be made?

Done from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

None

**Comment by HiFlyerBwi** [comment]
Submitted for OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56078607-ab883080-5daf-11e9-85a9-30b5349c33f2.png)
