### ISSUE TITLE
KAPG-Phillips Army Airfield-MARYLAND-USA

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#3889]
# Airport Name

Phillips Army Airfield

# Country?

USA

# Improvements that need to be made?

Re-done from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

None

**Comment by HiFlyerBwi** [comment]
Submitted for OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56078713-ec347980-5db0-11e9-9183-0ead683f836f.png)
