### ISSUE TITLE
YMML-Melbourne Airport-VICTORIA-AUSTRALIA

### ISSUE THREAD

**Issue by IceBlue02** [InfiniteFlightAirportEditing/Airports#389]
Tip-off from BVRAU.

Looks like it needs some work/a redo

**Comment by kilt46** [comment]
Not currentlt a 'Suggestion as is Non-Region. Please leave "Suggestion for current IF released airports"

**Comment by dushyants19** [comment]
Up for grabs

**Comment by IFAEpat** [comment]
Still doing EDDF, YBTL and US Dependent Islands but, I'll take this one too. Doesn't seem it'll take much time. I'd like us to get these A380 Airports done ✈️

**Comment by Theobsidianguy** [comment]
@IFAEpat any progress?

**Comment by IFAEpat** [comment]
@Theobsidianguy it's nearly completed, don't worry :)

**Comment by Theobsidianguy** [comment]
cool. ;)

**Comment by IFAEpat** [comment]
Will be done latest Saturday :)

**Comment by IFAEpat** [comment]
Done!

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23325418/b5c58886-faba-11e6-9035-86684e9043a8.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42423650-67c06a38-82c3-11e8-865d-7a24c71a5afd.png)
CHecked against
![image](https://user-images.githubusercontent.com/14023167/42423659-8ef8da40-82c3-11e8-867a-57a1393c281c.png)

**Comment by SpaceGuru01** [comment]
This is going to need a major rework but for now I'm just adding the new Jet Base Facility.

**Comment by SpaceGuru01** [comment]
Never mind what I said above, I'll do a Redo.

**Comment by MBeringuy** [comment]
How is the airport progressing?
