### ISSUE TITLE
VISM-Shimla Airport-HIMACHALPRADESH-INDIA

### ISSUE THREAD

**Issue by akshay2777** [InfiniteFlightAirportEditing/Airports#3891]
# Airport Name

 Shimla Airport

# Country?

 India

# Improvements that need to be made?

From scratch

# Are you working on this airport?

 yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59195477-79523f80-8b62-11e9-88cc-8ac0faf9d959.jpg)
