### ISSUE TITLE
SAZR-Santa Rosa Airport-LA PAMPA-ARGENTINA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3893]
# Airport Name

Santa Rosa Airport

# Country?

Argentina

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55444407-ed2d0600-557b-11e9-8fb3-aeb4cc22c9d3.png)
