### ISSUE TITLE
SCIR-Isla Robinson Crusoe Airport-VALPARAISO-CHILE

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3896]
# Airport Name

Isla Robinson Crusoe Airport

# Country?

Chile

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55669802-4da09980-5841-11e9-9ea9-07c14f82d499.png)
