### ISSUE TITLE
SCFX-Isla San Felix Airport-VALPARAISO-CHILE

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3897]
# Airport Name

Isla San Felix Airport

# Country?

Chile

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55669639-6dcf5900-583f-11e9-89c8-351a38a45666.png)
