### ISSUE TITLE
SECU-Cuenca Airport-AZUAY-ECUADOR

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3898]
# Airport Name

Cuenca-Mariscal Lamar Intl Airport

# Country?

Ecuador

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55669976-c1dc3c80-5843-11e9-8f30-e50c98d6b2d9.png)
