### ISSUE TITLE
KSJC-San Jose International Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#39]

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20736498/92809d80-b66c-11e6-8441-44303ab5a9af.png)

**Comment by TristinWoolf** [comment]
Fixed a minor issue with an extra PAPI light that was reported on the forum.
https://community.infinite-flight.com/t/random-papi-light-next-to-taxiway-at-san-jose-airport-kscj/134560/11

**Comment by brunocr98** [comment]
I'll be fixing this misalignment issue + doing a complete overhaul (Authorization granted).

![image uploaded from ios](https://user-images.githubusercontent.com/22130457/40519206-fbc85618-5f83-11e8-946a-a1cf3f53d04c.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/40865844-31b081f0-65c0-11e8-9aba-17e387f3fd12.png)

**Comment by brunocr98** [comment]
I had to reupload again my reworked version because the one pictured shows the previous and current version present in IF.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/40874298-1a4f1940-6633-11e8-9d84-ad853f982ee1.png)
