### ISSUE TITLE
SETN-Tachina Airport-ESMERALDAS-ECUADOR

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3900]
# Airport Name

Tachina Cel Carlos Concha Torres Airport

# Country?

Ecuador

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55669914-9efd5880-5842-11e9-93b8-bb48ab9ff456.png)
