### ISSUE TITLE
SOOG-Saint Georges Airport-CAYENNE-FRENCH GUIANA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3903]
# Airport Name

Sainte Georges Airport

# Country?

French Guiana

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55669440-fbf61000-583c-11e9-8319-c8bb8404f587.png)
