### ISSUE TITLE
NZLX-Alexandra Areodrome-OTAGO-NEW ZEALAND

### ISSUE THREAD

**Issue by Lukeh0** [InfiniteFlightAirportEditing/Airports#3904]
# Airport Name

Alexandra Areodrome

# Country?

New Zealand

# Improvements that need to be made?

Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56100549-bd68f100-5edf-11e9-8663-31c3cc39bc4d.png)
