### ISSUE TITLE
NZGM-Greymouth Airport-WEST COAST-NEW ZEALAND

### ISSUE THREAD

**Issue by Lukeh0** [InfiniteFlightAirportEditing/Airports#3905]
# Airport Name

Greymouth Airport

# Country?

New Zealand

# Improvements that need to be made?

Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56100736-1043a800-5ee2-11e9-91a5-13f0b8dcc46b.png)
