### ISSUE TITLE
SWPY-Primavera Do Leste Airport-MATO GROSSO-BRAZIL

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Airports#3907]
# Airport Name

< Primavera do Leste >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/62659251-40a3cc00-b941-11e9-91a1-68d91944f278.jpg)
