### ISSUE TITLE
UIIB-Belaya Air Base-IRKUTSK-RUSSIA

### ISSUE THREAD

**Issue by Eli2519** [InfiniteFlightAirportEditing/Airports#3908]
♻️

**Comment by MajorTomMueller** [comment]
This is a duplicate! Always check the issue list before opening a new issue.

**Comment by Eli2519** [comment]
I know but the other issue is closed....

**Comment by MajorTomMueller** [comment]
Yes, but we always have only one issue per Airport. If you want something to be changed at a edited airport you should try to contact the editor that did it last and ask him to change it or if he let you change it. If so, or the editor isn’t active anymore, you have to ask a supervisors to reopen the issue.
And you have to give the reason why it needs to be reworked.

**Comment by kztmtn** [comment]
Submitted for OR.

**Comment by Eli2519** [comment]
OK.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56593010-55866a80-65b1-11e9-8044-6c35734c81f2.png)
