### ISSUE TITLE
OMAA-Abu Dhabi Airport-ABU DHABI-UNITED ARAB EMIRATES

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#391]
Airport Rebuild

**Comment by kilt46** [comment]
Airport redrawn from scratch

**Comment by ryu12332** [comment]
ISSUE: The Tower view is showing OMAD's tower view instead of OMAA's. OMAD airport is located close to OMAA. This bug may be an issue for controllers who want to view the traffic on OMAA

**Comment by Tamz00** [comment]
Has this been fixed? If not I can quickly fix it and add the missing ground frequency too.

**Comment by brunocr98** [comment]
No one is assigned to it so...

**Comment by Tamz00** [comment]
Sent for review.

**Comment by moritzbabl** [comment]
readded

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33149779-92ab9672-cf96-11e7-8621-e868d26ed29a.png)

**Comment by kilt46** [comment]
Airport edited. Please remove buildings

**Comment by moritzbabl** [comment]
Buildings not removed yet, will need a major redo once the new terminal is opened in Q4/19

**Comment by JoshTomaz** [comment]
Could I take care of this? The new terminal isn't opening until 2020, but there are many stands that are currently at the airport missing, aswell as a GA area.

**Comment by brunocr98** [comment]
This airport would require a full redo, and I’d suggest to leave it to experienced editors. I’d also wait for newer imagery to come out.

**Comment by jakey200** [comment]
I would like to work on this, new imagery showing 81.6% of the new gate markings is available. Plus this airport seriously needs some help

**Comment by jakey200** [comment]
Ryan Approved™️

**Comment by MajorTomMueller** [comment]
Hope that you drop neither this nor the ones you are assigned already

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/88347305-0ed17400-cd10-11ea-88b3-4a2790885fe9.png)
