### ISSUE TITLE
SAVV-Viedma Gobernador Castello Airport-RIO NEGRO-ARGENTINA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3910]
# Airport Name

Viedma Gobernador Castello Airport

# Country?

Argentina

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56080960-1e53d480-5dcd-11e9-8a55-cefea5cb30a0.png)
