### ISSUE TITLE
38S-Deer Lodge-City-County Airport-MONTANA-USA

### ISSUE THREAD

**Issue by ProFlightSim** [InfiniteFlightAirportEditing/Airports#3911]
# Airport Name

< 38S Deer Lodge-City-County Airport >

# Country?

< United States of America >

# Improvements that need to be made?

< Entire rework >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by IFC-PlaneCrazy** [comment]
I'll take this

**Comment by IFC-PlaneCrazy** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/71448121-8a395b80-2716-11ea-941a-7cba1ca9871d.jpg)
