### ISSUE TITLE
KCGS-College Park Airport-MARYLAND-USA

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#3913]
# Airport Name

College Park Airport

# Country?

USA

# Improvements that need to be made?

Re-done from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

No

**Comment by HiFlyerBwi** [comment]
Sent in for OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/58836858-48d54780-8630-11e9-9afe-dbfb3158397a.jpg)
