### ISSUE TITLE
KDMW-Carroll County Regional Airport-MARYLAND-USA

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#3914]
# Airport Name

Carroll County Regional Airport

# Country?

USA

# Improvements that need to be made?

Re-done from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

No

**Comment by HiFlyerBwi** [comment]
Sent in for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/58842156-492b0e00-8643-11e9-950b-9001b620cac1.jpg)
