### ISSUE TITLE
SBMN-Manaus Ponta Pelada AB-AMAZONAS-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3916]
# Airport Name

Ponta Pelada Air Base

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56079315-63214080-5db8-11e9-8de9-f01bed8d0a8a.png)
