### ISSUE TITLE
OODQ-Duqm Jaaluni Airport-AL WUSTAN-OMAN

### ISSUE THREAD

**Issue by IFUA2003** [InfiniteFlightAirportEditing/Airports#3917]
♻️

**Comment by brunocr98** [comment]
Stop creating duplicates, I beg you!

**Comment by MBeringuy** [comment]
I'm going to edit this airport.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56087592-dd42db00-5e33-11e9-97aa-12452050a714.png)
