### ISSUE TITLE
MT84-Mower Field-MONTANA-USA

### ISSUE THREAD

**Issue by IFC-PlaneCrazy** [InfiniteFlightAirportEditing/Airports#3918]
# Airport Name

Mower Field

# Country?

USA

# Improvements that need to be made?

Redone from scratch 

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by IFC-PlaneCrazy** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56069445-b0fe6000-5d48-11e9-9340-ff704cfe4624.png)
