### ISSUE TITLE
KHLN-Helena Regional Airport-MONTANA-USA

### ISSUE THREAD

**Issue by IFC-PlaneCrazy** [InfiniteFlightAirportEditing/Airports#3919]
# Airport Name

Helena Regional Airport

# Country?

USA

# Improvements that need to be made?

Redone from scratch 

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

US Capital

**Comment by IFC-PlaneCrazy** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56397625-49de2100-620a-11e9-8e87-07f94e5be6e6.png)
