### ISSUE TITLE
KOWD

### ISSUE THREAD

**Issue by Ksisky** [InfiniteFlightAirportEditing/Airports#392]
Local Airport, should be fun.

**Comment by Ksisky** [comment]
Done, waiting on submit confirmation.

**Comment by Ksisky** [comment]
Submitted to repo.

**Comment by kilt46** [comment]
This is NOT done!

**Comment by dushyants19** [comment]
@Ksisky when was this approved?

**Comment by dushyants19** [comment]
I'll look into this

**Comment by dushyants19** [comment]
Added, nice airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20628075/ae2c6176-b2e9-11e6-9415-5b1b301960f6.png)
