### ISSUE TITLE
NZMC-Mount Cook Airport-CANTERBURY-NEW ZEALAND

### ISSUE THREAD

**Issue by Lukeh0** [InfiniteFlightAirportEditing/Airports#3920]
# Airport Name

Mount Cook Airport

# Country?

New Zealand

# Improvements that need to be made?

Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56100449-56970800-5ede-11e9-8790-51742e6eb917.png)
