### ISSUE TITLE
VEIM-Imphal International Airport-MANIPUR-INDIA

### ISSUE THREAD

**Issue by Ayush-19** [InfiniteFlightAirportEditing/Airports#3922]
# Airport Name

Imphal International Airport

# Country?

INDIA

# Improvements that need to be made?

Complete Redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

N/A

**Comment by Ayush-19** [comment]
Submitted to OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59126119-aa502b80-893a-11e9-8f70-471e044dc0b7.jpg)
