### ISSUE TITLE
ZYMH-Mohe Gulian Airport-HEILONGJIANG-CHINA

### ISSUE THREAD

**Issue by FLRAIN** [InfiniteFlightAirportEditing/Airports#3923]
# Airport Name
MOHE GULIAN AIRPORT

# Country?

CHINA

# Improvements that need to be made?

ADD A NEW AIRPORT

# Are you working on this airport?

YES

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

LOW

**Comment by FLRAIN** [comment]
China's northernmost Airport

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56329230-26eb3880-6148-11e9-8cba-4f7c7b4c86c8.png)
