### ISSUE TITLE
EFHA-Halli Airport-WESTERN FINLAND-FINLAND

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#3924]
# Airport Name

< Halli Airport >

# Country?

< Finland >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kztmtn** [comment]
Submitted for OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56100345-3adf3200-5edd-11e9-9688-6d7ec066db88.png)
