### ISSUE TITLE
KSDY-Sidney Richland Municipal Airport-MONTANA-USA

### ISSUE THREAD

**Issue by IFC-PlaneCrazy** [InfiniteFlightAirportEditing/Airports#3925]
# Airport Name

Sidney-Richland Municipal Airport

# Country?

USA

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by IFC-PlaneCrazy** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56581175-f36e3b00-6599-11e9-9eab-b52a08622d79.png)
