### ISSUE TITLE
GVSF-Sao Filipe Airport-SAO FILIPE-CAPE VERDE

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3926]
# Airport Name

Sao Filipe Airport

# Country?

Cape Verde

# Improvements that need to be made?

Done from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56091045-4267f200-5e6f-11e9-8a7e-6eadc8bab700.png)
