### ISSUE TITLE
CYBG-CFB Bagotville-QUEBEC-CANADA

### ISSUE THREAD

**Issue by dmp457** [InfiniteFlightAirportEditing/Airports#3928]
# Airport Name

Bagotville Airport

# Country?

Canada

# Improvements that need to be made?

refresh

# Are you working on this airport?

I will try

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

GP2 (10k)

**Comment by HiFlyerBwi** [comment]
@dmp457 I believe that you are supposed to fill in some info on this airport...

**Comment by liamkirky** [comment]
Could I be unassigned imagery makes certain things hard to see and other images show parts of airport under construction.

**Comment by MajorTomMueller** [comment]
Insufficient imagery according to Liam.
Up for Graps. ;-)

**Comment by lukewilson16** [comment]
I will work on this or atleast try to. I am currently working on another so once airport I am done, I will start this

**Comment by dmp457** [comment]
@HiFlyerBwi the thing is, I can´t fill anything in.

**Comment by dmp457** [comment]
ok i got it now xD

**Comment by MajorTomMueller** [comment]
![CYBG-git](https://user-images.githubusercontent.com/26853210/95021634-a7199c80-0661-11eb-97ac-192e6c696a15.png)
