### ISSUE TITLE
EFKM-Kemijarvi Airfield-LAPLAND-FINLAND

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#3929]
# Airport Name

< Kemijarvi Airfield >

# Country?

< Finland >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kztmtn** [comment]
Submitted for OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56100272-4bdb7380-5edc-11e9-9680-7a16cf7cb85a.png)
