### ISSUE TITLE
OMDB-Dubai International Airport-DUBAI-UNITED ARAB EMIRATES

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#393]
Dubai is coming!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33149828-c78feeec-cf96-11e7-9f16-8ae8a4092301.png)

**Comment by brunocr98** [comment]
Renovation in progress...

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/74172029-4b039300-4c0e-11ea-86de-5cc48b90dcec.jpg)
