### ISSUE TITLE
SSAF-Aeroclube de Foz do Iguacu Airstrip-PARANA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3930]
# Airport Name

Aeroclube de Foz do Iguacu Airstrip

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56087468-abc91000-5e31-11e9-9943-4b40efdc75ff.png)
