### ISSUE TITLE
SSFE-Estancia Hercules Airport-PARANA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3931]
# Airport Name

Estancia Hercules Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56087514-504b5200-5e32-11e9-8291-e3c7067a3e9a.png)
