### ISSUE TITLE
SDNY-Aeroclube de Nova Iguacu Airport-RIO DE JANEIRO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3932]
# Airport Name

Aeroclube de Nova Iguacu Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56087539-f13a0d00-5e32-11e9-9be4-0a3fc69b72a8.png)
