### ISSUE TITLE
KPIR-Pierre Regional Airport-SOUTH DAKOTA-USA

### ISSUE THREAD

**Issue by gsherbert** [InfiniteFlightAirportEditing/Airports#3937]
# Airport Name

Pierre Regional Airport

# Country?

United States of America

# Improvements that need to be made?

Redo from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

US Capital

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59605993-74ebd080-90e6-11e9-9baa-3496103a18b3.jpg)
