### ISSUE TITLE
EDDF-Frankfurt Airport-HESSE-GERMANY

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#394]
Rhein-Main-Flughafen!

**Comment by JcFl4** [comment]
Won't be able to do this one, sorry. I leave it for someone else.

**Comment by IFAEpat** [comment]
I'll be doing this one, seems interesting :)

**Comment by brunocr98** [comment]
Taking over EDDF!

**Comment by brunocr98** [comment]
Done!

**Comment by IFAEpat** [comment]
Awesome, @brunocr98 !

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23193383/5a9cceb8-f86e-11e6-8dbb-ea58cbfbc9d8.png)

**Comment by moritzbabl** [comment]
Some issues were reported and are going to be fixed by @mbmhwue148

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![Uploading image.png…]()

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/41801826-75c60918-7642-11e8-938d-1fbce4a9fe7e.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/41801835-854793d4-7642-11e8-8d6b-9471ca20612c.png)

**Comment by moritzbabl** [comment]
@mbmhwue148 is going to complete the rework following the new guidelines

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48103618-93572880-e1f5-11e8-90ce-ab88dce09ce4.png)
