### ISSUE TITLE
37IL-Minder Airstrip-ILLINOIS-USA

### ISSUE THREAD

**Issue by airbus3d** [InfiniteFlightAirportEditing/Airports#3941]
# Airport Name

Leon Gonzales Pie De La Cuesta

# Country?

Mexico

# Improvements that need to be made?

Redone

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

N/A

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90335596-98850200-df9b-11ea-86f8-534d08a40c20.png)
