### ISSUE TITLE
NZWF-Wanaka Airport-CANTERBURY-NEW ZEALAND

### ISSUE THREAD

**Issue by Lukeh0** [InfiniteFlightAirportEditing/Airports#3942]
# Airport Name

Wanaka Airport

# Country?

New Zealand

# Improvements that need to be made?

Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/58831330-d9a52680-8622-11e9-990f-8dbbba966c26.jpg)
