### ISSUE TITLE
NZOU-Oamaru Airport-OTAGO-NEW ZEALAND

### ISSUE THREAD

**Issue by Lukeh0** [InfiniteFlightAirportEditing/Airports#3943]
# Airport Name

Oamaru Airport

# Country?

New Zealand

# Improvements that need to be made?

Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/58831580-5f28d680-8623-11e9-8fdc-8526eebfb55a.jpg)
