### ISSUE TITLE
EFKA-Kauhava Airfield-WESTERN FINLAND-FINLAND

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#3946]
# Airport Name

< Kauhava Airfield >

# Country?

< Finland >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kztmtn** [comment]
Submitted for OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56470041-1f0cec00-6407-11e9-80a5-4de159e2bcd3.png)
