### ISSUE TITLE
NWWX-Canala Airport-NORD-NEW CALEDONIA

### ISSUE THREAD

**Issue by gsherbert** [InfiniteFlightAirportEditing/Airports#3947]
# Airport Name

Canala Airport 

# Country?

New Caledonia (France)

# Improvements that need to be made?

Redo from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low Priority

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59353832-3a56f200-8cfa-11e9-9b3f-b919c1c186b3.jpg)
