### ISSUE TITLE
NWWE-Île des Pins Airport-SUD-NEW CALEDONIA

### ISSUE THREAD

**Issue by gsherbert** [InfiniteFlightAirportEditing/Airports#3948]
# Airport Name

Île des Pins Airport

# Country?

New Caledonia (France)

# Improvements that need to be made?

Redo from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low Priority

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59354171-ef89aa00-8cfa-11e9-82b0-26b2fb163f7c.jpg)
