### ISSUE TITLE
LFPB-Paris–Le Bourget Airport-ILE DE FRANCE-FRANCE

### ISSUE THREAD

**Issue by IceBlue02** [InfiniteFlightAirportEditing/Airports#395]
Paris Le Bourget

Gonna Redo as necessary.

**Comment by AxelBeder** [comment]
Better be a nice one :eyes: don't joke with Paris. :smile:

**Comment by IceBlue02** [comment]
Haha No pressure lol ;-)

**Comment by dushyants19** [comment]
Continue here 

https://github.com/InfiniteFlightAirportEditing/Airports/issues/325#issuecomment-187096308

**Comment by dushyants19** [comment]
Redo required, not up to current standards (unsnapped stuff everywhere, overlapping) 

@AxelBeder wanna do this?

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22451525/ecb82356-e734-11e6-9a2d-a00c96df3011.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44949121-b8dc4600-adf0-11e8-9982-fbd2c755022f.png)

**Comment by brunocr1050** [comment]
Last time this airport was redone: nearly 4 years ago. @Jeremy351 will be redoing this airport from scratch.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105561481-72972280-5cdc-11eb-9fec-02c2c2bc6769.png)
