### ISSUE TITLE
SAZV-Villa Gesell Airport-BUENOS AIRES-ARGENTINA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3950]
# Airport Name

Villa Gesell Airport

# Country?

Argentina

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56469680-70ff4300-6402-11e9-83c4-ddce7cc873d2.png)
