### ISSUE TITLE
SAVE-Esquel Airport-CHUBUT-ARGENTINA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3951]
# Airport Name

Esquel Airport

# Country?

Argentina

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56469772-904aa000-6403-11e9-9d18-cf727d2ddb8d.png)
