### ISSUE TITLE
HEBA-Alexandria Borg El Arab Airport-AL ISKANDARIYAH-EGYPT

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3952]
# Airport Name

Alexandria Borg El Arab Intl Airport

# Country?

Egypt

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

10000ft+ Runway

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56515379-6aa1c180-64fd-11e9-83e7-027e9c9116e0.png)
