### ISSUE TITLE
KHRO-Boone County Airport-ARKANSAS-USA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3953]
# Airport Name

< Boone County Airport >

# Country?

< USA >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes. 2 Airports are in OR >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< None [DeerCrusher's Homebase Airport] >

**Comment by Balloonchaser** [comment]
Sent in for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56579720-79888280-6596-11e9-973e-36a3901de739.png)
