### ISSUE TITLE
 KGTF-Great Falls International Airport-MONTANA-USA

### ISSUE THREAD

**Issue by IFC-PlaneCrazy** [InfiniteFlightAirportEditing/Airports#3955]
# Airport Name

Great Falls International Airport

# Country

USA

# Improvements that need to be made?

Will be redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

10000ft+ Runway

**Comment by IFC-PlaneCrazy** [comment]
Please temporarily unassign me from this. I will not be able to edit it until the satellite imagery is updated, which doesn't seem to be happening for a while.

**Comment by IFsami** [comment]
I think the scenery has been updated because I can see a united evo blue crj7, so I will take it. If the scenery is good, can I be assigned this please?

**Comment by IFC-PlaneCrazy** [comment]
I can confirm that the imagery is not updated yet on either bing or google, it's still from 2014. Please look at an updated taxiway map. There are several taxiways around runway 16/34 that do not exist on the imagery.

**Comment by GBKarp** [comment]
I'll take it. ESRI has updated imagery.

**Comment by kilt46** [comment]
![Uploading image.png…]()
