### ISSUE TITLE
OEGS-Gassim/Prince Naif Bin Abdulaziz Airport-AL QUASSIM-SAUDI ARABIA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3956]
# Airport Name

Gassim/Prince Naif Abdulaziz Airport

# Country?

Saudi Arabia

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56462129-75d0e200-6383-11e9-9ee9-c1004b5b7db1.png)
