### ISSUE TITLE
7IL3-Lutz RLA-ILLINOIS-USA

### ISSUE THREAD

**Issue by InfiniteFlyer21** [InfiniteFlightAirportEditing/Airports#3957]
♻️

**Comment by brunocr98** [comment]
Hello, please search before creating an issue. There's already an issue for KPDX. We usually don't recommend new people to start by editing big airports. If you haven't joined us, please do so at contact@airportediting.com. This airport could be redone by an experienced editor in the future.

**Comment by InfiniteFlyer21** [comment]
I will be doing this one correct?

**Comment by brunocr98** [comment]
For the moment I wouldn't recommend you start by editing KPDX or any class B airport.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/88351429-ea7b9480-cd1b-11ea-873e-47755e023711.png)
