### ISSUE TITLE
ROTM-MCAS Futenma-OKINAWA-JAPAN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#3959]
# Airport Name

< MCAS Futenma >

# Country?

< Japan >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56469982-44e5c100-6406-11e9-9ba5-eb5c1607b9c1.png)

**Comment by orangejuicie** [comment]
Spawn attribute fix.
