### ISSUE TITLE
LSGG-Geneve Airport-GENEVE-SWITZERLAND

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#396]
Doing this one in the future when done with region airports.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24590448/d88b195c-17b2-11e7-92a0-5d8f0ed73238.png)

**Comment by kilt46** [comment]
Outlines missing on cargo areas
![image](https://user-images.githubusercontent.com/14023167/27776757-fabd1644-5f72-11e7-9c65-d9058123bc2e.png)

**Comment by kilt46** [comment]
Full array of spawn points missing
![image](https://user-images.githubusercontent.com/14023167/27776783-1b7ee90c-5f73-11e7-8fd9-919e80750028.png)

**Comment by NickArt1342** [comment]
I already noted that some spawn points are missing... Also those outlines are red, we do not have said color. I'll add them in white.

**Comment by dushyants19** [comment]
- Snap Nodes
![image](https://user-images.githubusercontent.com/13567007/27781610-4b401a02-5fec-11e7-9e46-209ff648ce5b.png)

- Cut Hole

![image](https://user-images.githubusercontent.com/13567007/27781615-55730868-5fec-11e7-8e6c-b3df7389ca04.png)

![image](https://user-images.githubusercontent.com/13567007/27781665-8dc47dc8-5fec-11e7-9478-9d6d2875614b.png)

**Comment by dushyants19** [comment]
Cut holes
![image](https://user-images.githubusercontent.com/13567007/27781757-120e8a38-5fed-11e7-9f3a-63209987aa4a.png)

Transparent Taxiway:

![image](https://user-images.githubusercontent.com/13567007/27781801-4ecc3416-5fed-11e7-9cae-c1545fef7421.png)

**Comment by brunocr98** [comment]
Another controversy over.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30353239-63eacdf0-97ea-11e7-99d8-2ff15e09760e.png)

**Comment by kilt46** [comment]
Airport edited. Buildings need removed

**Comment by brunocr1050** [comment]
Being redone by @Jeremy351

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104110749-3907f580-52a0-11eb-8f85-2a380c1290fa.png)
