### ISSUE TITLE
ZMAH-Arvaikheer Airport-OVORKHANGAI-MONGOLIA

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#3961]
# Airport Name

< Arvaikheer Airport >

# Country?

< Mongolia >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kztmtn** [comment]
Submitted for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/63641645-334c4880-c688-11e9-86f0-32ccf4a9e682.jpg)
