### ISSUE TITLE
KSTP-St Paul Downtown Airport Holman Field-MINNESOTA-USA

### ISSUE THREAD

**Issue by Gabe-Z** [InfiniteFlightAirportEditing/Airports#3962]
# Airport Name

St Paul Downtown Airport Holman Field

# Country?

USA

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by Gabe-Z** [comment]
The airport has been sent in for the Official Review.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59351678-56a46000-8cf5-11e9-848e-a56d21bd7ee7.jpg)
