### ISSUE TITLE
MMCH-Chilpancingo Airport-GUERRERO-MEXICO

### ISSUE THREAD

**Issue by Gil-Santiago** [InfiniteFlightAirportEditing/Airports#3963]
# Airport Name

Aerodromo Nicolas Bravo

# Country?

Mexico

# Improvements that need to be made?

Redone

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

N/A

**Comment by FlyingOstrich14** [comment]
@Gil-Santiago what is the status of the rework?

**Comment by FlyingOstrich14** [comment]
@MajorTomMueller, I received authorization from Cameron to take over the issue since the original editor is inactive. Could I please be assigned? T

**Comment by MajorTomMueller** [comment]
You have asked Cam? Can’t believe that.

**Comment by FlyingOstrich14** [comment]
Just sent you the evidence via Slack 😅

**Comment by MajorTomMueller** [comment]
🙄 not the thing I meant ...

**Comment by lalomarlin** [comment]
I can take it :)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105780470-221b0180-5f36-11eb-9da4-845a78fdd119.png)
