### ISSUE TITLE
ENDU-Bardufoss Airport-TROMS-NORWAY

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#3964]
# Airport Name

< Enter text here >

# Country?

< Enter text here >

# Improvements that need to be made?

< Enter text here >

# Are you working on this airport?

< Enter text here >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Enter text here >

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/75923058-14065300-5e43-11ea-86e9-8dc62c32ccc8.jpg)

**Comment by MajorTomMueller** [comment]
Spawn size need to be adjusted

**Comment by MajorTomMueller** [comment]
![ENDU-git](https://user-images.githubusercontent.com/26853210/84935163-d9f64f80-b0c7-11ea-8be6-b884f541c570.png)
