### ISSUE TITLE
LTCJ-Batman Airport-BATMAN-TURKEY

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#3965]
Added by kilt

**Comment by MajorTomMueller** [comment]
unassigned on users request

**Comment by GBKarp** [comment]
Can I be assigned for this one?

**Comment by MJP27** [comment]
Quick Question. Is this airport still being edited. If not, I’ll take it

**Comment by Czechoslovaki** [comment]
Negative @MJP27, he's still editing.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103111083-c0056e80-460e-11eb-93d1-6fabd58bc2b5.png)
![image](https://user-images.githubusercontent.com/14023167/103111085-c8f64000-460e-11eb-87e9-c07ad884556b.png)

**Comment by kilt46** [comment]
Elevation needs fixed  :)

**Comment by brunocr1050** [comment]
Fix pushed.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103111199-f8f21300-460f-11eb-900f-60ecdf0f67ce.png)
