### ISSUE TITLE
SPRU-Trujillo Airport-LA LIBERTAD-PERU

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#3967]
# Airport Name

Trujillo International Airport

# Country?

Peru

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56576290-91a7d400-658d-11e9-9aa0-65324bbbfdf8.png)
