### ISSUE TITLE
VVDL-Lien Khuong Airport-LAM DONG-VIETNAM

### ISSUE THREAD

**Issue by IFUA2003** [InfiniteFlightAirportEditing/Airports#3968]
# Airport Name

< Lien Khuong International Airport >

# Country?

< Vietnam >

# Improvements that need to be made?

< The airport hasn’t been added >

# Are you working on this airport?

< No >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

<  None >

**Comment by sirhc1** [comment]
I'll take this (actually I have finished it just waiting for #peer-review)

**Comment by sirhc1** [comment]
<img width="850" alt="VVDL" src="https://user-images.githubusercontent.com/48324628/56472377-3910f380-6434-11e9-998c-095b1ee89710.png">

**Comment by IFUA2003** [comment]
Thank you!

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59124951-60197b00-8937-11e9-8f38-be6554e07d20.jpg)

**Comment by MajorTomMueller** [comment]
New apron

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/97084430-944d1480-15dc-11eb-94b8-acc85d0175a9.png)
