### ISSUE TITLE
RJTE-Tateyama Air Base-CHIBA-JAPAN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Airports#3969]
# Airport Name

< Tateyama Air Base >

# Country?

< Japan >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56475003-d7f31b00-6447-11e9-935c-3b1ad7cf1bfc.png)
