### ISSUE TITLE
LSGL

### ISSUE THREAD

**Issue by antbelldev** [InfiniteFlightAirportEditing/Airports#397]
Working on regional airports. Lausanne-Blécherette, Switzerland.

**Comment by carmichaelalonso** [comment]
Hey @antbelldev! If you get a chance, could you drop us an email at airports@liveflightapp.com?
Thanks for getting involved with this project! :)

**Comment by antbelldev** [comment]
Approved

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18939881/74670c04-85c9-11e6-9daa-6cb6140914cb.png)
