### ISSUE TITLE
ZMAT-Altai Airport-GOVI ALTAY-MONGOLIA

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#3970]
# Airport Name

< Altai Airport >

# Country?

< Mongolia >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kztmtn** [comment]
Submitted for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/63641606-6e01b100-c687-11e9-8bc1-caecfc3a67cf.jpg)
