### ISSUE TITLE
CZBF-Bathurst Airport-NOUVEAU BRUNSWICK-CANADA

### ISSUE THREAD

**Issue by sirhc1** [InfiniteFlightAirportEditing/Airports#3971]
# Airport Name

< Bathurst Regional Airport >

# Country?

< Canada >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< None >

**Comment by sirhc1** [comment]
Sent in for OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/63462848-3817bf00-c432-11e9-8d8b-343ad9f5c309.jpg)
