### ISSUE TITLE
VVPB-Phu Bai International Airport-HUE-VIETNAM

### ISSUE THREAD

**Issue by sirhc1** [InfiniteFlightAirportEditing/Airports#3972]
# Airport Name

< Phu Bai International Airport >

# Country?

< Vietnam >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< None >

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59125352-7d027e00-8938-11e9-82d6-89263ec7ffd3.jpg)
