### ISSUE TITLE
IL95-Corn Field Strip-ILLINOIS-USA

### ISSUE THREAD

**Issue by royfr83** [InfiniteFlightAirportEditing/Airports#3973]
# Airport Name

Megido Airfield

# Country?

Israel

# Improvements that need to be made?

Scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90335616-c10cfc00-df9b-11ea-9bb3-67a0f876c7af.png)
