### ISSUE TITLE
57IS-Dozier Strip-ILLINOIS-USA

### ISSUE THREAD

**Issue by alphabravo6** [InfiniteFlightAirportEditing/Airports#3974]
# Airport Name

< Roma Airport >

# Country?

< Australia >

# Improvements that need to be made?

< There was an airport upgrade a while ago in real life for this airport, meaning that the aprons and taxiways changed, although it hasn't been updated in IF >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90336179-9f157880-df9f-11ea-9cb5-65e68e4c49e9.png)
