### ISSUE TITLE
CYFS-Fort Simpson Airport-NORTHWEST TERRITORIES-CANADA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3975]
# Airport Name

< Fort Simpson Airport >

# Country?

< Canada >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< None >

**Comment by Balloonchaser** [comment]
Sent in for OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/58919583-fb76da00-8704-11e9-9ce5-aaf62bc633ff.jpg)
