### ISSUE TITLE
51IS-Curry Airfield-ILLINOIS-USA

### ISSUE THREAD

**Issue by FLRAIN** [InfiniteFlightAirportEditing/Airports#3976]
# Airport Name

Yibin Caiba Airport

# Country?

CHINA

# Improvements that need to be made?

Fix Runway，taxiway；Add ramp

# Are you working on this airport?

YES

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

LOW

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90337082-bce5dc00-dfa5-11ea-9a66-8a333d0f3b22.png)
