### ISSUE TITLE
EFVR-Varkaus Airport-EASTERN FINLAND-FINLAND

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#3978]
# Airport Name

< Varkaus Airport >

# Country?

< Finland >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kztmtn** [comment]
Submitted for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59197064-b28cae80-8b66-11e9-90f2-333bd7ab378e.jpg)
