### ISSUE TITLE
RC0-Rock Creek Airport-MONTANA-USA

### ISSUE THREAD

**Issue by IFC-PlaneCrazy** [InfiniteFlightAirportEditing/Airports#3979]
# Airport Name

Rock Creek Airport

# Country?

USA

# Improvements that need to be made?

Will be redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by IFC-PlaneCrazy** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59606501-b0d36580-90e7-11e9-9f13-792f50b1ce73.jpg)

**Comment by TheFlyingGuy1** [comment]
Runway size is incorrect. Actual size is 1250m and in the app it is only about 1000m. Much more ramp starts can be placed.
