### ISSUE TITLE
KACK

### ISSUE THREAD

**Issue by Ksisky** [InfiniteFlightAirportEditing/Airports#398]
Complete redo of KACK

**Comment by Ksisky** [comment]
Submitted on March 19, waiting for review.

**Comment by IceBlue02** [comment]
@henrikbg I assume this has been added?

@kilt46 if so for cataloging.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20609425/f3fe3c4e-b251-11e6-9ef7-e5a7d0306544.png)
