### ISSUE TITLE
PVDZ-Valdez Pioneer Field-ALASKA-USA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#3980]
# Airport Name

< Valdez Pioneer Field >

# Country?

< USA >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< IF Events >

**Comment by Balloonchaser** [comment]
Sent in for OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/58843244-11729500-8648-11e9-8a7f-c6d3be879058.jpg)
