### ISSUE TITLE
LEAB-Albacete-Los Llanos Airport-CASTILLA-LA MANCHA-SPAIN

### ISSUE THREAD

**Issue by PilotGonzalez** [InfiniteFlightAirportEditing/Airports#3981]
♻️

**Comment by PilotGonzalez** [comment]
Airport has be sent to Official Review

**Comment by chrisindfw** [comment]
What is the status of this? I see it was submitted for OR but not in the sim yet.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111030657-20fc4180-83c9-11eb-9b07-bfc0340a077b.png)
