### ISSUE TITLE
MWCL-Edward Bodden/Little Cayman Airport-LITTLE CAYMAN-CAYMAN ISLANDS

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#3983]
# Airport Name

Edward Bodden/Little Cayman Airport.

# Country?

Cayman Islands.

# Improvements that need to be made?

Redo from scratch.

# Are you working on this airport?

Nope, leaving this to whoever wants it.

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

None.

**Comment by daneverest** [comment]
Can I take this one for my first airport please?

**Comment by ILOVE787920** [comment]
Could I use this one also as my first airport please? I see it's still unfinished

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90314610-9313b300-deda-11ea-94b1-b451b9539c49.png)
