### ISSUE TITLE
ZMBH-Bayankhongor Airport-BAYANKHONGOR-MONGOLIA

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#3984]
# Airport Name

< Bayankhongor Airport >

# Country?

< Mongolia >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kztmtn** [comment]
Submitted for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/63641691-1401eb00-c689-11e9-84bb-01a8a0507f2f.jpg)
