### ISSUE TITLE
LEMI-Murcia Corvera International Airport-MURCIA-SPAIN

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#3985]
# Airport Name

Murcia Corvera International Airport 

# Country?

Spain

# Improvements that need to be made?

new addition 

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

not as far as I know now

**Comment by MajorTomMueller** [comment]
![LEMI-git](https://user-images.githubusercontent.com/26853210/56867442-946b5480-69e5-11e9-9ae9-00a41db8e927.jpg)

Apron CL and Spawns are not to latest AIP. They have changed in January, so no Sat images are available so far.
Has to be watched.

**Comment by MajorTomMueller** [comment]
Closed for now. Change in satellite images not expect to soon. No complaints from community regarding small spawn are. Will reopen when needed.

**Comment by brunocr1050** [comment]
There has been changes to the apron markings when comparing the ones in the file and the satellite imagery, as well as the numbering. The new markings were drawn the same way as the old ones (more description in the referenced commit).

**Comment by MajorTomMueller** [comment]
Waited for that satellite image for more then a year....
You could have assigned me again ... 😔

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109576191-f18c3180-7ab8-11eb-897a-3ee784b655b9.png)
