### ISSUE TITLE
C75-Marshall County-ILLINOIS-USA

### ISSUE THREAD

**Issue by SOFcobra** [InfiniteFlightAirportEditing/Airports#3987]
# Airport Name

< Abilene Regional Airport >

# Country?

< United States >

# Improvements that need to be made?

< Will be redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90338735-536bca80-dfb1-11ea-90f0-5ada636fdde5.png)
