### ISSUE TITLE
EHLW-Leeuwarden AB-FRIESLAND-NETHERLANDS

### ISSUE THREAD

**Issue by Fabse1803** [InfiniteFlightAirportEditing/Airports#3989]
♻️

**Comment by MajorTomMueller** [comment]
Duplicate, recycled

**Comment by MajorTomMueller** [comment]
Not to far away from Dortmund...

**Comment by Fabse1803** [comment]
wha have to be done at that Airport ?

**Comment by liamkirky** [comment]
Anyone working on this airport

**Comment by Fabse1803** [comment]
> Anyone working on this airport?i think no

**Comment by MajorTomMueller** [comment]
![EHLWgit](https://user-images.githubusercontent.com/26853210/59161273-04362a00-8ad0-11e9-80aa-bd5d2caeeb03.PNG)
