### ISSUE TITLE
KATL-Hartsfield-Jackson Atlanta International Airport-GEORGIA-USA

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#399]

**Comment by kilt46** [comment]
Airport has been reworked

**Comment by TristinWoolf** [comment]
Jacob S is adjusting a few spawn points at the terminals. Just putting it on here for record. Although, Jacob _does_ need to be invited to the GitHub team.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18611080/b16dc5a8-7cf4-11e6-9174-93152510934e.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18611085/d418b770-7cf4-11e6-819e-8b0fe8603e9f.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34641115-82bced0a-f2c4-11e7-8077-7760a2f51636.png)

**Comment by kilt46** [comment]
Gate Review - Navigraph 15-Jun-18

**Comment by kilt46** [comment]
Gate review complete
![image](https://user-images.githubusercontent.com/14023167/42136674-8e22e582-7d25-11e8-8ec7-fb075d596aab.png)

**Comment by MBeringuy** [comment]
Have the changes at this airport been completed? If so, can you already unassign and remove the labels?

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/62654311-eb15f200-b935-11e9-8647-3b666cf5154b.jpg)
