### ISSUE TITLE
LFFQ-La Ferte Alais Airfield-ILE DE FRANCE-FRANCE

### ISSUE THREAD

**Issue by rich-art-02** [InfiniteFlightAirportEditing/Airports#3990]
# Airport Name

La Ferte Alais Airfield

# Country?

France

# Improvements that need to be made?

Complete Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59690492-e6e01a80-91b7-11e9-84ac-3163f0b6dbd6.jpg)
