### ISSUE TITLE
KFDK-Frederick Municipal Airport-MARYLAND-USA

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#3992]
# Airport Name

Frederick Municipal Airport

# Country?

USA

# Improvements that need to be made?

Scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

IDK, Ballonchaser wanted this or somethin

**Comment by HiFlyerBwi** [comment]
Submitted for OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59605623-93050100-90e5-11e9-844c-b0cb131468cc.jpg)
