### ISSUE TITLE
ZMDN-Donoi Airport-DZAVHAN-MONGOLIA

### ISSUE THREAD

**Issue by daneverest** [InfiniteFlightAirportEditing/Airports#3993]
♻️

**Comment by brunocr98** [comment]
#354

**Comment by kztmtn** [comment]
**ZMDN-Donoi Airport-DZAVHAN-MONGOLIA**
Donoi Airport
Mongolia
Not exists in IF, do from scratch
Doing
Low

Thank you @brunocr98

**Comment by kztmtn** [comment]
Submitted for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/63641727-abffd480-c689-11e9-8fe2-6cd07bcd10c0.jpg)
