### ISSUE TITLE
ESPA-Luleå Kallax Airport-NORRBOTTEN-SWEDEN

### ISSUE THREAD

**Issue by qaxand** [InfiniteFlightAirportEditing/Airports#3994]
# Airport Name

< Luleå Kallax Airport >

# Country?

< Sweden >

# Improvements that need to be made?

< New gates, taxiways, and other minor fixes. >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< 10 990 ft runway(14/32) >

**Comment by liamkirky** [comment]
Can I take this? Please

**Comment by MajorTomMueller** [comment]
Ask @qaxand if he is still working on it. If he didn't respond within a week or agreed let me know and I assign you.

**Comment by qaxand** [comment]
Feel free to continue the work, @liamkirky 
I can send you the file if you want to continue with it.

**Comment by MajorTomMueller** [comment]
Transferee to @liamkirky

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104138063-32908100-5367-11eb-83f8-51fd9b6dbe75.png)
