### ISSUE TITLE
KYKM-Yakima Air Terminal McAllister Field-WASHINGTON-USA

### ISSUE THREAD

**Issue by tomthetank46** [InfiniteFlightAirportEditing/Airports#3995]
# Airport Name

Yakima Air Terminal McAllister Field

# Country?

United States

# Improvements that need to be made?

Rework from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

NA

**Comment by MajorTomMueller** [comment]
Changed priority because this is the home base of the manufacturer of the XCub. And the announce a anniversary event on there homepage I am pretty sure IF LLC wants to replicate.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/58843945-3e747700-864b-11e9-8740-e4888c7fdb0a.jpg)
