### ISSUE TITLE
EDGZ-Weinheim an der Bergstraße Airport-BADEN-WÜRTEMBERG-GERMANY

### ISSUE THREAD

**Issue by SKYSTAR-F** [InfiniteFlightAirportEditing/Airports#3996]
♻️

**Comment by moritzbabl** [comment]
There's already an issue for this airport -> #3364

**Comment by moritzbabl** [comment]
recycled

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/58980468-cae77c80-87a6-11e9-93f0-3e01b50a4bea.jpg)
