### ISSUE TITLE
ZMBN-Bulgan Airport-BULGAN-MONGOLIA

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#3997]
# Airport Name

< Bulgan Airport >

# Country?

< Mongolia >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kztmtn** [comment]
Submitted for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/63641941-41e92e80-c68d-11e9-96c8-9c087bc15b39.jpg)
