### ISSUE TITLE
ZMBS-Bulgan Sum Airport-HOVD-MONGOLIA

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#3998]
# Airport Name

< Bulgan Sum Airport >

# Country?

< Mongolia >

# Improvements that need to be made?

< From scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kztmtn** [comment]
Submitted for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/63641798-a8208200-c68a-11e9-9c35-50418c60db2f.jpg)
