### ISSUE TITLE
5LL5-Gordon Brown Strip-ILLINOIS-USA

### ISSUE THREAD

**Issue by Gil-Santiago** [InfiniteFlightAirportEditing/Airports#3999]
# Airport Name

Aerodromo Ta Lo De Soto

# Country?

Mexico

# Improvements that need to be made?

Redone

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

N/A

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90341683-33470600-dfc7-11ea-8832-fc0cf6e10aef.png)
