### ISSUE TITLE
KCOS

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#4]

**Comment by Swang007** [comment]
There might be an issue concerning alignment, but this could be device-related or app-related

**Comment by Swang007** [comment]
Nope, seems to be the alignment bug. This is what happened:
![11178200_10200441700721511_5627429276737009351_n](https://cloud.githubusercontent.com/assets/11000109/7221846/7206e9ea-e6c2-11e4-84b3-a0473ebd412c.jpg)

**Comment by IceBlue02** [comment]
Needs a tarmac rewrite- Misaligned

**Comment by kilt46** [comment]
17L 35R
![image](https://cloud.githubusercontent.com/assets/14023167/14236052/58df0828-f9d4-11e5-8a0d-af32e4a96958.png)

**Comment by kilt46** [comment]
Realigned
![image](https://cloud.githubusercontent.com/assets/14023167/14236069/a0ae1450-f9d4-11e5-9c72-d83d4bc5091f.png)

**Comment by kilt46** [comment]
17L lined up
![image](https://cloud.githubusercontent.com/assets/14023167/14236085/02c998bc-f9d5-11e5-8342-9ca34474a323.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17269640/98b019f6-5613-11e6-97dd-9a9ba32f09f1.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18022153/2ea573d0-6bb2-11e6-9fcc-28caf4e313f2.png)
