### ISSUE TITLE
EKRK-Roskilde Airport-AMAGER-DENMARK

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#40]

**Comment by carmichaelalonso** [comment]
duplicate, closing....

**Comment by IFAEpat** [comment]
up for grabs guys! :)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23445220/80a20ede-fdff-11e6-9925-37aa2f85fd49.png)
