### ISSUE TITLE
OTHH-Hamad International Airport-AD DAWHAH-QATAR

### ISSUE THREAD

**Issue by dushyants19** [InfiniteFlightAirportEditing/Airports#400]
Doha - Hamad. Its mine :stuck_out_tongue:

**Comment by liamkirky** [comment]
Is this anywhere near being done

**Comment by dushyants19** [comment]
No @liamkirky

**Comment by dushyants19** [comment]
took a while but done

![image](https://cloud.githubusercontent.com/assets/13567007/21478696/d63f8eac-cb73-11e6-8ac3-feb49db08e67.png)


i feel proud, largest ive ever done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21481363/5e9ee0ce-cb2c-11e6-8202-23a19efc8335.png)

**Comment by dushyants19** [comment]
Adding the new gates

**Comment by MajorTomMueller** [comment]
Any progress?

**Comment by brunocr98** [comment]
Since there has been no response after almost 2 months I’ll take the task to finish this.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/43928062-366c0e06-9bf5-11e8-9d9e-7112a5435752.png)
