### ISSUE TITLE
VI40-Karnal Airport-HARYANA-INDIA

### ISSUE THREAD

**Issue by Ayush-19** [InfiniteFlightAirportEditing/Airports#4000]
# Airport Name

Karnal Airport

# Country?

India

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

None

**Comment by Ayush-19** [comment]
Submitted to OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59126723-25fea800-893c-11e9-903e-2f2715dee537.jpg)
