### ISSUE TITLE
ZMBU-Baruun-Urt Airport-SUHBAATAR-MONGOLIA

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#4001]
# Airport Name

< Baruun-Urt Airport >

# Country?

< Mongolia >

# Improvements that need to be made?

< from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kztmtn** [comment]
Submitted for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/63641859-73f99100-c68b-11e9-89e4-c3715aabf508.jpg)
