### ISSUE TITLE
K2C6-Tri-County Airfield-ILLINOIS-USA

### ISSUE THREAD

**Issue by Fab03** [InfiniteFlightAirportEditing/Airports#4003]
# Airport Name

< Enter text here >

# Country?

< Enter text here >

# Improvements that need to be made?

< Enter text here >

# Are you working on this airport?

< Enter text here >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Enter text here >

**Comment by Fab03** [comment]
Eisenach Kindel, I will edit it.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90341997-2b3c9580-dfca-11ea-9098-fad389b1876e.png)
