### ISSUE TITLE
A003-Shaw River Airport-WESTERN AUSTRALIA-AUSTRALIA

### ISSUE THREAD

**Issue by TheBestiGamer** [InfiniteFlightAirportEditing/Airports#4004]
# Airport Name

< Shaw River >

# Country?

< Australia >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< none of the above >

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/61494525-be049e00-a98c-11e9-9a47-2e04c45cf53e.jpg)
