### ISSUE TITLE
ZMDA-Deluun Boldog Airport-KHENTII-MONGOLIA

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#4006]
# Airport Name

< Deluun Boldog Airport >

# Country?

< Mongolia >

# Improvements that need to be made?

< Not exists in IF, do from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kztmtn** [comment]
Submitted for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/63641897-35180b00-c68c-11e9-85fc-de15d8f84376.jpg)
