### ISSUE TITLE
VI71-Pinjore Airport-HARYANA-INDIA

### ISSUE THREAD

**Issue by Ayush-19** [InfiniteFlightAirportEditing/Airports#4007]
# Airport Name

Pinjore Airport

# Country?

India

# Improvements that need to be made?

Full rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

None

**Comment by Ayush-19** [comment]
Submitted for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59194709-4a3ace80-8b60-11e9-8828-f139b5befcfc.jpg)
