### ISSUE TITLE
EGWU-RAF Northolt-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by benjwri** [InfiniteFlightAirportEditing/Airports#4008]
# Airport Name

RAF Northolt

# Country?

United Kingdon

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

None

**Comment by benjwri** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59700407-9c679980-91c9-11e9-8d73-0b6c339bc339.jpg)
