### ISSUE TITLE
ETNH-Hohn Airport-SCHLESWIG-HOLSTEIN-GERMANY

### ISSUE THREAD

**Issue by benjwri** [InfiniteFlightAirportEditing/Airports#4009]
# Airport Name

Hohn

# Country?

Germany

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

None

**Comment by benjwri** [comment]
Sent to OR a while ago

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59353003-63768300-8cf8-11e9-9b02-03c91651ffa7.jpg)
