### ISSUE TITLE
VHHH-Hong Kong International Airport-HONG KONG-CHINA

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#401]
ZRH is nearly finished, so here comes my next task

**Comment by NickArt1342** [comment]
Axel already did this one.

**Comment by kilt46** [comment]
This one has either NOT been done or not uploaded yet!

**Comment by NickArt1342** [comment]
@AxelBeder I think you did this one already? If not do you want it or can we reassign somebody else?

**Comment by nick-if** [comment]
YUP, ITS BEENR EASSIGNED TO ME :) @NickArt1342

**Comment by nick-if** [comment]
@NickArt1342 hey since nobody is doing it i think he's too busy i can do it within the next 3 hours i am chan, hahaha, i can do that now if he's not doing it i think in your timezone your sleeping, I'm just gonna go ahead and do this one now ok by the way i am new to this airport editing

**Comment by RileyDunshea** [comment]
@nick-if maybe wait. We don't know if it has already been done.

**Comment by nick-if** [comment]
i can check in the airports folder

**Comment by nick-if** [comment]
can i do it now i have the whole night @RileyDunshea

**Comment by nick-if** [comment]
by the way i spent over an hour downloading that stupid wedbing yesterday

**Comment by nick-if** [comment]
@RileyDunshea can I ask, when we edit it, we just follow the map and add all the taxi lines and taxiways, and all the features, right? thats all we do?

**Comment by RileyDunshea** [comment]
@nick-if Nick listen. Axel may of already of finished the airport but we don't know yet. He might of finished it but hasn't sent it in yet. Please wait for confirmation. There are many other airports you can do.

**Comment by nick-if** [comment]
alright well i'll take the chance of redoing it and wasting my time @RileyDunshea its fine iff he already did it then i just wasted my time

**Comment by nick-if** [comment]
@RileyDunshea you know what this airport is way too big I'm gonna start practicing WED with a smaller airport

**Comment by dushyants19** [comment]
Closed temporarily

**Comment by JcFl4** [comment]
I just added a nearly done one, but someone could finish it if you want.

**Comment by TristinWoolf** [comment]
Liam is doing this now.

**Comment by dushyants19** [comment]
Up for grabs

**Comment by tacobell1015** [comment]
has the new terminal been added yet?

**Comment by liamkirky** [comment]
I'm not doing it anymore

Sent from my iPad

On 23 Aug 2016, at 19:22, tacobell1015 <notifications@github.com<mailto:notifications@github.com>> wrote:


has the new terminal been added yet?

-

**Comment by dushyants19** [comment]
whats the status on this? 

@tacobell1015 are you willing to do this?

**Comment by tacobell1015** [comment]
Ive been busy and Im trying to find time to do it but yes I am willing to do it.

**Comment by dushyants19** [comment]
ok! I have invited you to our GitHub team, check your email and accept the invite.

**Comment by NickArt1342** [comment]
I think I have a finished version of it. Let me check. Somebody already did this one.

**Comment by dushyants19** [comment]
@tacobell1015 any progress? :)

**Comment by tacobell1015** [comment]
Slowly but surely. Im still trying to find a map with the new terminal 2

**Comment by GiacomoLaw** [comment]
Is this one Kai Tak, or the new one? :/

**Comment by dushyants19** [comment]
New

**Comment by GiacomoLaw** [comment]
Oh, okay. Can you link me to Kai Tak issue?

**Comment by dushyants19** [comment]
#585 @GiacomoLaw

**Comment by GiacomoLaw** [comment]
Thanks!

**Comment by dushyants19** [comment]
Hows the progress? @tacobell1015

**Comment by tacobell1015** [comment]
Honestly I haven't done much. Ive been so busy with school I have been finding it hard to find time to do it. If someone else wants to take over as HKG is a big priority for global someone else should do it. I still haven't been able to find a taxiway layout that includes the new terminal for Hong Kong Airlines. The airport itself without the new terminal is done but It needs the new terminal. Sorry guys

**Comment by dushyants19** [comment]
@tacobell1015 have you tried using SAS.planet? If you can't do it let us know. Kilt46 is into getting these A380s done

**Comment by kilt46** [comment]
Duplicate spawn removed

**Comment by kztmtn** [comment]
Fix runwayholds, ILS critical centerlines.

**Comment by kilt46** [comment]
Change line attributes to regular yellow
Add an entire apron
Adjust taxiway edges
Realign and add missing lines
Draw new holes and realign others
Change main taxiway from concrete to asphalt

**Comment by Czechoslovaki** [comment]
Sent For OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/86645424-01905780-bfa4-11ea-9ad9-b0fde8b27635.png)

**Comment by Czechoslovaki** [comment]
I'll be updating the airport with the addition of taxiway P1 and several new remote stands and maybe some additional details I omitted 8 months ago.

Also, this request came straight from the top so I feel obliged to do this ASAP.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111559924-6f119c00-875f-11eb-8afa-223697142699.png)
