### ISSUE TITLE
OEGN-Jazan/King Abdullah Abdulaziz Airport-JIZAN-SAUDI ARABIA

### ISSUE THREAD

**Issue by M3RKZ** [InfiniteFlightAirportEditing/Airports#4011]
# Airport Name

< King Abdullah bin Abdulaziz Airport - jizan >

# Country?

< Saudia Arabia  >

# Improvements that need to be made?

< Gates and taxiways >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/58917920-9fa95280-86fe-11e9-9019-2dd45fcaa4f3.jpg)
