### ISSUE TITLE
OEAH-Al Ahsa Airport-ASH SHARQIYAH-SAUDI ARABIA

### ISSUE THREAD

**Issue by M3RKZ** [InfiniteFlightAirportEditing/Airports#4012]
# Airport Name

< Al hasa >

# Country?

< Saudia Arabia>

# Improvements that need to be made?

< Gates and taxiways>

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low>

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/58917569-6b816200-86fd-11e9-99a1-200c062c623c.jpg)
