### ISSUE TITLE
OESK-Al Jouf Airport-AL JAWF-SAUDI ARABIA

### ISSUE THREAD

**Issue by M3RKZ** [InfiniteFlightAirportEditing/Airports#4013]
# Airport Name

< Al Jouf Airport >

# Country?

<Saudia Arabia >

# Improvements that need to be made?

< Gates taxiways >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by brunocr98** [comment]
This is your 3rd airport. You may create another one when your 3 airports are completed.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/58917408-d2524b80-86fc-11e9-8f58-28aba07e6b9d.jpg)
