### ISSUE TITLE
EDGX-Walldorf Airport-BADEN-WÜRTEMBERG-GERMANY

### ISSUE THREAD

**Issue by M3RKZ** [InfiniteFlightAirportEditing/Airports#4014]
♻️

**Comment by brunocr98** [comment]
You will no be assigned to this one yet. Read my message on #4012

**Comment by MBeringuy** [comment]
This airport has already been edited. See #3956

**Comment by moritzbabl** [comment]
recycled

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/58982217-544c7e00-87aa-11e9-882f-d1747773ad1d.jpg)
