### ISSUE TITLE
NZHS-Hastings Airport-HAWKE'S BAY-NEW ZEALAND

### ISSUE THREAD

**Issue by Lukeh0** [InfiniteFlightAirportEditing/Airports#4015]
# Airport Name

Hastings Areodrome

# Country?

New Zealand

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/58832735-fabb4680-8625-11e9-9634-049b9005a77b.jpg)
