### ISSUE TITLE
ZBER-Erenhot Saiwusu International Airport-NEIMONGOL-CHINA

### ISSUE THREAD

**Issue by FLRAIN** [InfiniteFlightAirportEditing/Airports#4017]
# Airport Name

Erenhot Saiwusu International Airport

# Country?

CHINA

# Improvements that need to be made?

edit a new airport

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68153967-4b143880-ff25-11e9-8a6a-72f8b02269bd.jpg)
