### ISSUE TITLE
ZMDZ-Dalanzadgad Airport-OMNOGOVI-MONGOLIA

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#4019]
# Airport Name

< Dalanzadgad Airport >

# Country?

< Mongolia >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kztmtn** [comment]
Submitted for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/63642052-0fd8cc00-c68f-11e9-9e23-052977cd0e6a.jpg)
