### ISSUE TITLE
ZMHG-Khatgal Airport-KHOVSGOL-MONGOLIA

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#4021]
# Airport Name

< Khatgal Airport >

# Country?

< Mongolia >

# Improvements that need to be made?

< Not exists in IF, do from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/63642117-ace83480-c690-11e9-81ec-b2c8ccad522e.jpg)
