### ISSUE TITLE
ZMHH-Kharkhorin Airport-OVORKHANGAI-MONGOLIA

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#4022]
# Airport Name

< Kharkhorin Airport >

# Country?

< Mongolia >

# Improvements that need to be made?

< Generated airport, do from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/63642813-9dbab400-c69b-11e9-9920-3a9fd1a2ae16.jpg)
