### ISSUE TITLE
ZMKB-Khanbumbat Airport-OMNOGOVI-MONGOLIA

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#4023]
# Airport Name

< Khanbumbat Airport >

# Country?

< Mongolia >

# Improvements that need to be made?

< Not exists in IF, do from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/63642862-4bc65e00-c69c-11e9-9ad9-f4e547a6b28d.jpg)
