### ISSUE TITLE
IL07-Taylor Strip-ILLINOIS-USA

### ISSUE THREAD

**Issue by Gabe-Z** [InfiniteFlightAirportEditing/Airports#4025]
# Airport Name

ANOKA COUNTY-BLAINE (JANES FIELD)

# Country?

USA

# Improvements that need to be made?

Unedited Airport and redone from scratch.

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by Gabe-Z** [comment]
Sorry, conflicting time with editing a large airport cause issues. This is up for grabs (suggestion).

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/87998003-434cf200-cabc-11ea-8206-1e3b7a1560f7.png)
