### ISSUE TITLE
EGXJ-RAF Cottesmore-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#403]
Requires rework

**Comment by freddiefrogs** [comment]
Unable to complete - computer is no longer working. Can someone remove the labels and assignments and choose suggested. It's not working for me.

**Comment by HenrikBerg02** [comment]
@freddiefrogs, there was an post in #announcements regarding the labels and assignee change.

>Changes to the issue tracker​:

>From now on, if you find an issue or create one for an airport you wish to do, ​comment​ on it that you want to do that airport. One of our airport repo reviewers will assign you to it and add necessary labels.

>Please note: ​always​ check there is an issue before starting an airport and make it clear that you plan on editing that airport. We have had conflicts in the past where two people have done the same airport - we will always select the airport done by whoever had it assigned in the issue tracker.

>Thanks guys!

**Comment by freddiefrogs** [comment]
Thanks. I've been away and not been keeping up.

**Comment by Will171** [comment]
ill see what i can do :)

**Comment by Will171** [comment]
i am unable to assign my self. I will be doing this one

**Comment by Will171** [comment]
Cheers Henrik :)

**Comment by Will171** [comment]
im probaly going to leave this airport for a while as there are other airports with a higher priority. can someone unassign

**Comment by AxelBeder** [comment]
Next time you start an airport. Make sure you can finish it.

**Comment by kilt46** [comment]
Airport redone

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19020284/4a34ecaa-886a-11e6-95e8-edf12b651451.png)
