### ISSUE TITLE
MD48-Albrecht Airstrip-MARYLAND-USA

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#4034]
# Airport Name

Albrecht Airstrip

# Country?

USA

# Improvements that need to be made?

Re-done from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

None

**Comment by HiFlyerBwi** [comment]
Submitted for OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/58841906-5d224000-8642-11e9-83be-a67391f203aa.jpg)
