### ISSUE TITLE
ZMTL-Tosontsengel Airport-DZAVHAN-MONGOLIA

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#4037]
# Airport Name

< Tosontsengel Airport >

# Country?

< Mongolia >

# Improvements that need to be made?

< Not exists in IF, do from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kztmtn** [comment]
Submitted for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/63643107-4ff47a80-c6a0-11e9-85eb-597ddad64af5.jpg)
