### ISSUE TITLE
ZMUG-Deglii Tsagaan Airport-UVS-MONGOLIA

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#4038]
# Airport Name

< Deglii Tsagaan Airport >

# Country?

< Mongolia >

# Improvements that need to be made?

< Generated one, do from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kztmtn** [comment]
Submitted for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/63650837-5bd65000-c725-11e9-8420-033d6a854bb7.jpg)
