### ISSUE TITLE
ZMUH-Undurkhaan Airport-HENTIY-MONGOLIA

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#4042]
# Airport Name

< Undurkhaan Airport >

# Country?

< Mongolia >

# Improvements that need to be made?

< Not exists in IF, do from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kztmtn** [comment]
Submitted for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/63650925-4b72a500-c726-11e9-9f6c-2ace073a4987.jpg)
