### ISSUE TITLE
ZMUL-Ulgii Airport-BAYAN ULGII-MONGOLIA

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#4043]
# Airport Name

< Ulgii Airport >

# Country?

< Mongolia >

# Improvements that need to be made?

< Generated airport, do from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kztmtn** [comment]
Submitted for OR. This is the last one of my Mongolian Project, or found aerodromes in AIS Mongolia.
I'll be calm down for a while....

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/63650977-f71bf500-c726-11e9-9509-b68abd5f46c1.jpg)
