### ISSUE TITLE
SJGW-Estancia Floresta Airstrip-MATO GROSSO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#4044]
# Airport Name

Estancia Floresta Airstrip

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/58822111-16662300-860d-11e9-9efb-1135398479b9.jpg)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107123298-5eb5f980-6862-11eb-8aa7-19f0c0f67399.png)

**Comment by kilt46** [comment]
Relocated as per Brazil Database
