### ISSUE TITLE
L52-Oceana County Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by tomthetank46** [InfiniteFlightAirportEditing/Airports#4052]
# Airport Name

Oceana County 

# Country?

United States

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

None

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/58843825-98c10800-864a-11e9-8957-026e41413f26.jpg)
