### ISSUE TITLE
UNTT-Tomsk/Bogashevo Airport-TOMSK-RUSSIA

### ISSUE THREAD

**Issue by TheBestiGamer** [InfiniteFlightAirportEditing/Airports#4056]
# Airport Name

< Luigi Razza >

# Country?

< Italy >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

<none of the above >

**Comment by MajorTomMueller** [comment]
@TheBestiGamer what is your slack Name?

**Comment by moritzbabl** [comment]
Heliport, invalid

**Comment by kztmtn** [comment]
Submitted for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59699329-ca4bde80-91c7-11e9-85a8-91e13ccadcf0.jpg)
