### ISSUE TITLE
DUPLICATE

### ISSUE THREAD

**Issue by TheBestiGamer** [InfiniteFlightAirportEditing/Airports#4060]
# Airport Name

< Miami Executive >

# Country?

<Florida >

# Improvements that need to be made?

< edited... idk >

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< none >

**Comment by brunocr98** [comment]
Let's continue on #343

**Comment by MajorTomMueller** [comment]
![EK05](https://user-images.githubusercontent.com/26853210/57544631-311fe180-7358-11e9-898e-80dab588f356.jpg)
