### ISSUE TITLE
EGSQ-Clacton Airport-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by TheBestiGamer** [InfiniteFlightAirportEditing/Airports#4061]
# Airport Name

< Clacton >

# Country?

< England >

# Improvements that need to be made?

< Redone >

# Are you working on this airport 
yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< none of the above >

**Comment by jackyboy2578** [comment]
could somebody assign if nobody is doing it.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/61340540-20d52880-a819-11e9-86cf-9e3ff5f5f3d1.jpg)
