### ISSUE TITLE
KGBG-Galesburg Municipal Airport-ILLINOIS-USA

### ISSUE THREAD

**Issue by pilot0674** [InfiniteFlightAirportEditing/Airports#4062]
# Airport Name

Kufra Airport

# Country?

Libya

# Improvements that need to be made?

Delete the inactive runway, add parking areas, re-do taxiways, add western part of the airport

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90446124-74621780-e0a6-11ea-8bb6-ed23aaa6ab35.png)
