### ISSUE TITLE
OOKB-Khasab Airport-KHASAB-OMAN

### ISSUE THREAD

**Issue by Ayush-19** [InfiniteFlightAirportEditing/Airports#4063]
# Airport Name

Khasab Airport

# Country?

Oman

# Improvements that need to be made?

Full rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MajorTomMueller** [comment]
not assigned, user already assigned to 4 airports.

**Comment by Ayush-19** [comment]
May I now take this? I have sent 3 of my airports for OR and 1 does not have proper imagery.

**Comment by MajorTomMueller** [comment]
Wich ones the one with the improper imager? Make a comment on the related issues so that I could at a tag.

**Comment by Ayush-19** [comment]
Sent in for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/58835382-335e1e80-862c-11e9-8d5c-a8838d6858cc.jpg)
