### ISSUE TITLE
OSDI-Damascus International Airport-DAMASCUS-SYRIA

### ISSUE THREAD

**Issue by pilot0674** [InfiniteFlightAirportEditing/Airports#4067]
# Airport Name

Damascus International Airport

# Country?

Syria

# Improvements that need to be made?

Runways need to be redone, taxiways need to be added, spawning points need to be added.

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Country Capital

**Comment by pilot0674** [comment]
I would like to have this airport transfered to someone else. im not experienced egnough to handel large airpports

**Comment by MBeringuy** [comment]
Open to anyone who wants to edit.

![Untitled-1](https://user-images.githubusercontent.com/32115399/59467820-fdc4ec80-8e06-11e9-99a0-1afe80b745af.jpg)

![Untitled-1](https://user-images.githubusercontent.com/32115399/59467884-2816aa00-8e07-11e9-9f38-88f52cee5bf1.jpg)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/63973137-86efd500-ca80-11e9-8ffa-555f3579e5ff.jpg)
