### ISSUE TITLE
EGUL-RAF Lakenheath-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#407]
Requires rework

**Comment by kilt46** [comment]
Airport redone

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20601066/4e6c26ea-b21c-11e6-9adf-2ba3edc6e08b.png)

**Comment by MajorTomMueller** [comment]
Needs some polishing. Will take care about.

**Comment by MajorTomMueller** [comment]
![egul-git](https://user-images.githubusercontent.com/26853210/48315139-c2451400-e5d2-11e8-89e7-31ab97556f5d.jpg)
