### ISSUE TITLE
LTBS-Dalaman Airport-MUGLA-TURKEY

### ISSUE THREAD

**Issue by liamkirky** [InfiniteFlightAirportEditing/Airports#4070]
# Airport Name

< Mugla Dalaman International Airport >

# Country?

< Turkey >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes  >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< None >

**Comment by liamkirky** [comment]
Sent for OR!

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59699787-8c9b8580-91c8-11e9-89b6-0a4b6503d6ac.jpg)
