### ISSUE TITLE
EERU-Ruhnu-ESTONIA

### ISSUE THREAD

**Issue by FLRAIN** [InfiniteFlightAirportEditing/Airports#4088]
# Airport Name

Yanji Chaoyangchuan International Airport

# Country?

CHINA
# Improvements that need to be made？

Production details
# Are you working on this airport?
YES

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

LOW

**Comment by brunocr98** [comment]
You have already 3 issues assigned to you. Finish them and then you can be assigned to this one

**Comment by FLRAIN** [comment]
> You have already 3 issues assigned to you. Finish them and then you can be assigned to this one

I have emailed contact@airportediting.com for all three issues, but no reply has been received.

**Comment by moritzbabl** [comment]
As far as I can see in our inbox we’ve not received any of your airports so far

**Comment by FLRAIN** [comment]
> As far as I can see in our inbox we’ve not received any of your airports so far

I have resend it.

**Comment by moritzbabl** [comment]
You must be doing something wrong, I still don’t see a mail from you

**Comment by FLRAIN** [comment]
> You must be doing something wrong, I still don’t see a mail from you

My e-mail shows "Successful arrival at the other server".

**Comment by moritzbabl** [comment]
That’s all we’ve got atm

![E4FA798D-3B9F-46BA-B4A2-2D086D3FE44B](https://user-images.githubusercontent.com/19365980/57786588-0bb61d80-7734-11e9-8176-055d45ef9336.jpeg)

**Comment by MajorTomMueller** [comment]
recycled

**Comment by MajorTomMueller** [comment]
![EERU-git](https://user-images.githubusercontent.com/26853210/64078471-b134d300-ccca-11e9-826e-68a59ffc0f8f.png)
