### ISSUE TITLE
EGBT London Area

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#409]
Requires rework

**Comment by freddiefrogs** [comment]
Will do.

**Comment by freddiefrogs** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17249783/2a286580-5567-11e6-9006-a21e6bf63885.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18297755/df33a022-7478-11e6-8cbd-15084e5a18ca.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45245897-10345780-b2c4-11e8-9771-d249a18b7fdd.png)
