### ISSUE TITLE
4W0-Bandera State Airport-WASHINGTON-USA

### ISSUE THREAD

**Issue by CaptainGeorgeIF** [InfiniteFlightAirportEditing/Airports#4093]
♻️

**Comment by Ocean1c** [comment]
Can I grab this one?

**Comment by MajorTomMueller** [comment]
Yes

**Comment by Czechoslovaki** [comment]
Editor busy with life, airport open to anyone.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111082486-930e7c80-84d6-11eb-9a2d-481237358fa5.png)
