### ISSUE TITLE
OIKB-Bandar Abbas International-HORMOZGAN-IRAN

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#4094]
# Airport Name

Bandar Abbas International

# Country?

Iran

# Improvements that need to be made?

From scratch has no gates in IF

# Are you working on this airport?

No

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

12k runway

**Comment by MajorTomMueller** [comment]
Good imagery, good documentary 

https://ais.airport.ir/iaip?_20_folderId=28714802&_20_viewEntries=1&_20_viewFolders=1&_20_struts_action=%2Fdocument_library%2Fview&_20_action=browseFolder&p_p_id=20&p_p_lifecycle=0&_20_entryStart=0&_20_entryEnd=100&_20_folderStart=0&_20_folderEnd=20&_20_viewEntriesPage=1

https://ais.airport.ir/iaip?p_p_id=20&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&_20_struts_action=%2Fdocument_library%2Fview_file_entry&_20_redirect=https%3A%2F%2Fais.airport.ir%2Fiaip%3Fp_p_id%3D20%26p_p_lifecycle%3D0%26p_p_state%3Dnormal%26p_p_mode%3Dview%26_20_displayStyle%3D%26_20_entryStart%3D0%26_20_viewFolders%3D1%26_20_folderStart%3D0%26_20_action%3DbrowseFolder%26_20_viewEntries%3D1%26_20_folderEnd%3D20%26_20_entryEnd%3D100%26_20_folderId%3D28714802%26_20_struts_action%3D%252Fdocument_library%252Fview&_20_fileEntryId=28714840

**Comment by kztmtn** [comment]
Checked imagery, OK, please assign me.

**Comment by kztmtn** [comment]
Sent in for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59608609-132e6500-90ec-11e9-9c87-6ad95197a788.jpg)
