### ISSUE TITLE
79IL-Miller Airstrip-ILLINOIS-USA

### ISSUE THREAD

**Issue by CPTWilliamVM** [InfiniteFlightAirportEditing/Airports#4095]
# Airport Name

< Kalmar Öland Airport >

# Country?

< Sweden >

# Improvements that need to be made?

< Airport Rework >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90453751-1558ce80-e0b7-11ea-8164-a8f3833fbfae.png)
