### ISSUE TITLE
EEPU-Pärnu-ESTONIA

### ISSUE THREAD

**Issue by IFUA2003** [InfiniteFlightAirportEditing/Airports#4099]
♻️

**Comment by brunocr98** [comment]
Are you requesting this airport or what?

**Comment by RyanEpps** [comment]
Request denied.

**Comment by moritzbabl** [comment]
INVALID

**Comment by MajorTomMueller** [comment]
recycled

**Comment by MajorTomMueller** [comment]
![EEPU-git](https://user-images.githubusercontent.com/26853210/64485963-93112a80-d216-11e9-8bbb-7dc1c8685565.png)
