### ISSUE TITLE
EGNX-East Midlands Airport-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#41]

**Comment by IceBlue02** [comment]
Parking redone https://github.com/InfiniteFlightAirportEditing/Airports/commit/24501c079867c0bfd9451fe5b95f7a42e65104e6

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17536388/47a62970-5e5a-11e6-922e-bf249b95b3f5.png)
WEST CARGO
![image](https://cloud.githubusercontent.com/assets/14023167/17536397/53fe14a8-5e5a-11e6-92ea-2d0228c94967.png)
TERMINAL
![image](https://cloud.githubusercontent.com/assets/14023167/17536410/68b39684-5e5a-11e6-8069-e70bc8ee8807.png)
EAST CARGO
![image](https://cloud.githubusercontent.com/assets/14023167/17536421/741cf376-5e5a-11e6-8173-007ad614ae3a.png)

**Comment by Will171** [comment]
Minor changes to taxiways and i plan on adding taxiway signs

**Comment by Will171** [comment]
Sent to be reviewed

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20369340/07783c46-ac1e-11e6-89c6-9efcc0b0a0ba.png)

**Comment by Will171** [comment]
I will be making improvements to the airport which are seen in the latest 2016 imagery on google earth.

**Comment by Will171** [comment]
Sent for review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
Duplicate spawns removed

**Comment by RyanEpps** [comment]
Full redo by Liam

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/91495084-97977e80-e87f-11ea-94db-d9bec5b63e4c.png)
