### ISSUE TITLE
EGUW London Area

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#410]
Needs rework

**Comment by IceBlue02** [comment]
Will be my next one :)

**Comment by IceBlue02** [comment]
Finished and in for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20601399/0fadb228-b21e-11e6-9ec8-989c60f6a372.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45397903-a7244b00-b607-11e8-8525-03bd41cb4a57.png)

**Comment by kilt46** [comment]
Boundary Fix
