### ISSUE TITLE
VEBS-Biju Patnaik Airport-ODISHA-INDIA

### ISSUE THREAD

**Issue by Ayush-19** [InfiniteFlightAirportEditing/Airports#4101]
# Airport Name

Biju Patnaik Airport

# Country?

India

# Improvements that need to be made?

Full rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

None

**Comment by Ayush-19** [comment]
Sent for OR

**Comment by MBeringuy** [comment]
The gates are listed incorrectly, according to the letter. Please check all gates, correct errors, and resubmit for review.

![Untitled-1](https://user-images.githubusercontent.com/32115399/59196027-edd9ae00-8b63-11e9-8ec2-a0035fc1872f.jpg)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59693848-f06c8100-91bd-11e9-8e95-6fd378c4c4d6.jpg)
