### ISSUE TITLE
CYVO-Val d'Or Airport-QUEBEC-CANADA

### ISSUE THREAD

**Issue by DelsterX** [InfiniteFlightAirportEditing/Airports#4102]
# Airport Name

< Val d'Or Airport >

# Country?

<Canada>

# Improvements that need to be made?

< Re-done from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< 10000ft=+ Runway, Project Canada >

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/65000640-b432e480-d8c2-11e9-9e97-0a0f7dc6b694.jpg)
