### ISSUE TITLE
TVSA-Kingstown/Argyle Airport-SAINT GEORGE-SAINT VINCENT AND THE GRENADINES

### ISSUE THREAD

**Issue by lukewilson16** [InfiniteFlightAirportEditing/Airports#4103]
TSVA/Argyle International Airport

St. Vincent and the Grenadines

The airport needs to be built completely from scratch

I plan to work on it

This airport is the main airport in the country

**Comment by lukewilson16** [comment]
Airport has been sent for review.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/60271962-a411f700-98c9-11e9-9ff8-cd8d53b52eb0.jpg)

**Comment by MajorTomMueller** [comment]
@lukewilson16 :
> Can you reopen Argyle International Airport and assign me. I have found a good bit of missing shoulders, bent apron scenery and gate settings in need of change among other things.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/66703142-cf3c1d00-ece5-11e9-8420-0bb4bb5c3954.jpg)
