### ISSUE TITLE
MD93-Hexton Farms Airport-MARYLAND-USA

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#4104]
# Airport Name

Hexton Farms Airport

# Country?

USA

# Improvements that need to be made?

Re-done from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

None
Just another "airport" in someone's over-sized backyard

**Comment by MajorTomMueller** [comment]
Assignment postponed till all three assigned ones are in OR.
Sorry, but three assignments only rule is under enforcement.

**Comment by HiFlyerBwi** [comment]
All 3 previous airports in OR, ready to be assigned to this airport

**Comment by HiFlyerBwi** [comment]
Submitted for OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59352241-8f910480-8cf6-11e9-9c37-273a635794d7.jpg)
