### ISSUE TITLE
RKTI-Jungwong Airbase-CHUNGCHEON-SOUTH KOREA

### ISSUE THREAD

**Issue by Sashaz55** [InfiniteFlightAirportEditing/Airports#4106]
♻️

**Comment by brunocr98** [comment]
Maybe you should search the code of the airport, before creating an issue.
#519

**Comment by MajorTomMueller** [comment]
recycled

**Comment by MajorTomMueller** [comment]
![RKTI](https://user-images.githubusercontent.com/26853210/60399313-362c3080-9b52-11e9-8a7b-0f1c86e6c7d7.PNG)
