### ISSUE TITLE
EFIM-Immola Airfield-SOUTHERN FINLAND-FINLAND

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#4108]
# Airport Name

< Immola Airfield >

# Country?

< Finland >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kztmtn** [comment]
Send in for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59205483-65660800-8b79-11e9-9c28-25ae46f397b1.jpg)
