### ISSUE TITLE
PAGK-Gulkana Airport-ALASKA-USA

### ISSUE THREAD

**Issue by Lukeh0** [InfiniteFlightAirportEditing/Airports#4109]
# Airport Name

Milford Sound Airport

# Country?

New Zealand

# Improvements that need to be made?

Allignment and Corrections

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by RyanEpps** [comment]
#1545

**Comment by MajorTomMueller** [comment]
recycled

**Comment by MajorTomMueller** [comment]
![PAGK](https://user-images.githubusercontent.com/26853210/59938597-fb851280-9444-11e9-8ea7-4d6ac42347fa.PNG)
