### ISSUE TITLE
EGLD London Area

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#411]
Needs reworked

**Comment by IceBlue02** [comment]
will do

**Comment by IceBlue02** [comment]
Done and Submitted :wink:

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17264609/cd40b966-55ad-11e6-8fe7-71c39985165c.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18231025/9f1f48cc-7272-11e6-8559-6f438137f735.png)
