### ISSUE TITLE
NZKE-Waiheke Reeve Airport-AUCKLAND-NEW ZEALAND

### ISSUE THREAD

**Issue by Lukeh0** [InfiniteFlightAirportEditing/Airports#4110]
# Airport Name

Waiheke Reeve Airport

# Country

New Zealand

# Improvements that need to be made

Airport doesn't exist in game

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/58833197-e9266e80-8626-11e9-8066-7ea75e1cbabb.jpg)
