### ISSUE TITLE
BIKR-Saudarkrokur Airport-NORDURLAND-ICELAND

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#4112]
# Airport Name

< Saudarkrokur Airport >

# Country?

< Iceland >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kztmtn** [comment]
Submitted for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/58830688-3e5f8180-8621-11e9-8481-0c2d6aa7e6fa.jpg)
