### ISSUE TITLE
KRMN-Stafford Regional Airport-VIRGINIA-USA

### ISSUE THREAD

**Issue by Airbus-737** [InfiniteFlightAirportEditing/Airports#4113]
# Airport Name

Stafford Regional
# Country?

United states

# Improvements that need to be made?

Redo from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
None

**Comment by Airbus-737** [comment]
Sent for PR

**Comment by Airbus-737** [comment]
Sent for OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/60271448-c1929100-98c8-11e9-8bc9-339de2f9037c.jpg)
