### ISSUE TITLE
VOHB-Hubli Airport-KARNATAKA-INDIA

### ISSUE THREAD

**Issue by Ayush-19** [InfiniteFlightAirportEditing/Airports#4114]
# Airport Name

Hubli Airport

# Country?

India

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

None

**Comment by Ayush-19** [comment]
Wrong ICAO code in IF. "VAHB" mentioned in contrary to "VOHB"

**Comment by MajorTomMueller** [comment]
https://aim-india.aai.aero/eaip-v2/25-05-2017/eAIP/EC-AD-2.1VOHB-en-GB.pdf
I have deleted VAHb in the database. 
Make sure to mention in email to OR

**Comment by Ayush-19** [comment]
Sent for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59196544-612fef80-8b65-11e9-8cfe-5c2e2f355836.jpg)
