### ISSUE TITLE
LFRQ-Quimper Airport-PLUGUFFAN-FRANCE

### ISSUE THREAD

**Issue by gsherbert** [InfiniteFlightAirportEditing/Airports#4116]
# Airport Name

Quimper Airport

# Country?

France

# Improvements that need to be made?

Redo from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low Priority

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59692374-2c521700-91bb-11e9-834a-08fda414a406.jpg)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59692995-86071100-91bc-11e9-9be9-2564857ba902.jpg)
