### ISSUE TITLE
SBPO-Pato Branco Airport-PARANA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#4117]
# Airport Name

Pato Branco Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/58820540-3eec1e00-8609-11e9-961f-0d72a7bb6ab0.jpg)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/86539369-88b8cf00-bec1-11ea-8cd6-faac3a368316.png)
