### ISSUE TITLE
ENRS-Rost Airport-NORDLAND-NORWAY

### ISSUE THREAD

**Issue by JensSeverin** [InfiniteFlightAirportEditing/Airports#4118]
# Airport Name

Rost Airport

# Country?

Norway

# Improvements that need to be made?

Rebuild from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by JensSeverin** [comment]
Sent for OR

**Comment by JensSeverin** [comment]
Sent for OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/60140887-90f80d80-9789-11e9-8121-386ba1ae1839.jpg)
