### ISSUE TITLE
EGUB-RAF Benson-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#412]
Needs reworked

**Comment by dushyants19** [comment]
Will do

**Comment by kilt46** [comment]
Airport fully reworked

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20599225/a48c897a-b212-11e6-8cbe-6f7ce0a55741.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/73314475-be6bd480-420c-11ea-9804-92dd61e3e664.jpg)
