### ISSUE TITLE
NZPN-Picton Airport-MARLBOROUGH-NEW ZEALAND

### ISSUE THREAD

**Issue by Lukeh0** [InfiniteFlightAirportEditing/Airports#4120]
# Airport Name

Picton Airport

# Country?

New Zealand

# Improvements that need to be made?

Rework & Re-Location

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59351188-31632200-8cf4-11e9-982e-ec7740cac4b5.jpg)
