### ISSUE TITLE
PABI-Allen AAF-ALASKA-USA

### ISSUE THREAD

**Issue by 45679** [InfiniteFlightAirportEditing/Airports#4122]
♻️

**Comment by brunocr98** [comment]
#55

**Comment by brunocr98** [comment]
I kindly ask you to refrain from doing this kind of topics! We have enough duplicate issues, and requests from the public aren't tolerated either.

**Comment by MajorTomMueller** [comment]
recycled

**Comment by MajorTomMueller** [comment]
![PABI](https://user-images.githubusercontent.com/26853210/59962569-ce814000-94d6-11e9-9329-5402bcbb4634.PNG)
