### ISSUE TITLE
KNQX-Key West Naval Air Station-FLORIDA-USA

### ISSUE THREAD

**Issue by liamkirky** [InfiniteFlightAirportEditing/Airports#4123]
# Airport Name

Key West Naval Air Station

# Country?

United States of America

# Improvements that need to be made?

Full rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by liamkirky** [comment]
Could someone unassign me from this airport, as with this laptop I have, it cannot handle even this airport! It has shocked me as I thought it would be able to,

**Comment by AeroTrapp** [comment]
Can you assign me pls

**Comment by AeroTrapp** [comment]
@MajorTomMueller You assigned the wrong person.

**Comment by MajorTomMueller** [comment]
😁
Better now?

**Comment by AeroTrapp** [comment]
Thanks ;)

**Comment by Jeremy351** [comment]
I had the confirmation that the Airport has been added. Could you close the topic ?
Thanks

**Comment by AleksanderIF** [comment]
https://github.com/InfiniteFlightAirportEditing/Airports/blob/development/United%20States/K---/KN--/KNQX/apt.dat Last update - 30 Sep 2018....

**Comment by Jeremy351** [comment]
Hummm. I had a confirmation mail from Ryan that the airport has been added. That's weird

**Comment by MajorTomMueller** [comment]
Keep calm. Ryan might have send you the notice after adding it in his local fork. He push that not every day. It will be closed when he has pushed it to the upstream.

**Comment by Jeremy351** [comment]
Yes. I fully understand. I just wanted to make sure there wasn't problem.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101842125-fde19d80-3b0c-11eb-8f48-426eeb2f1f74.png)
