### ISSUE TITLE
HRZA-Kamembe Airport-CYANGUGU-RWANDA

### ISSUE THREAD

**Issue by lukewilson16** [InfiniteFlightAirportEditing/Airports#4124]
# Airport Name

Aeroport de Kamembe 

# Country?

Rwanda

# Improvements that need to be made?

Needs to be built from scratch

# Are you working on this airport?

I will work on this airport.

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/75923459-e4a41600-5e43-11ea-853a-777c52fde280.jpg)
