### ISSUE TITLE
KCVS-Cannon AFB-NEW MEXICO-USA

### ISSUE THREAD

**Issue by IQ3milionen** [InfiniteFlightAirportEditing/Airports#4125]
# Airport Name

< Mountain View Airstrip>

# Country?

< United States >

# Improvements that need to be made?

< Runway change, taxiway rework, spawns rework>

# Are you working on this airport?

< Yes>

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low>

**Comment by MajorTomMueller** [comment]
You are assigned already to this:
https://github.com/InfiniteFlightAirportEditing/Airports/issues/3748

**Comment by MajorTomMueller** [comment]
recycled

**Comment by MajorTomMueller** [comment]
![KCVS-git](https://user-images.githubusercontent.com/26853210/60766074-ab888b80-a093-11e9-90db-edae58e2ac85.PNG)
