### ISSUE TITLE
ENSS-Vardo Airport Svartnes-FINNMARK-NORWAY

### ISSUE THREAD

**Issue by JensSeverin** [InfiniteFlightAirportEditing/Airports#4126]
# Airport Name

ENSS

# Country?

Norway

# Improvements that need to be made?

Re-build from scratch

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by JensSeverin** [comment]
Sent for OR

**Comment by JensSeverin** [comment]
Passed OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/62660629-f4f32180-b944-11e9-9e9b-d84f85e17060.jpg)
