### ISSUE TITLE
ENJA-Jan Mayensfield-JAN MAYEN-NORWAY

### ISSUE THREAD

**Issue by JamesBrowne1** [InfiniteFlightAirportEditing/Airports#4130]
♻️

**Comment by brunocr98** [comment]
Let's continue on #90 :)

**Comment by MajorTomMueller** [comment]
reycled

**Comment by MajorTomMueller** [comment]
![ENJA](https://user-images.githubusercontent.com/26853210/60766631-ed1d3480-a09b-11e9-8dd0-a206a206b4ea.PNG)
