### ISSUE TITLE
KTOA-Torrance/Zamperini Field Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#4132]
# Airport Name

KTOA

# Country?

USA

# Improvements that need to be made?

Entire Remake

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by jakey20** [comment]
Sent in for OR

**Comment by NAZ32** [comment]
Can I be assigned to this airport? Or is it already done? If not assign me to it.

**Comment by jakey20** [comment]
Hey, here's the apt.dat from when I was working on it. 
https://pastebin.com/bELAk55R

**Comment by brunocr98** [comment]
Any progress on this one? Otherwise it will be re-assigned to the original editor.

**Comment by jakey200** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/80623026-01159680-8a20-11ea-924c-2b07184cac82.jpg)

**Comment by MajorTomMueller** [comment]
The Airport has numerous overlapping and duplicate spawns:
https://gist.github.com/carmichaelalonso/e5f7a8bd5a61b4f1f82f629f09777bc0
https://gist.github.com/carmichaelalonso/652d032d7fe3683cbf8d88365ff5a690

**Comment by MajorTomMueller** [comment]
numerous overlaping Spawns:
https://gist.github.com/carmichaelalonso/97ec814264dc4488aecdaec06cfc6cc0

**Comment by jakey200** [comment]
No overlapping spawns on my end.

**Comment by MajorTomMueller** [comment]
Again, if it shows up in errors, then there are errors.

**Comment by jakey200** [comment]
No issue exists, unassign please

**Comment by MajorTomMueller** [comment]
Parsing errors listed assumed to be caused by processing old files acourding to @RyanEpps

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122679163-6fcb2b80-d1af-11eb-8213-e7be8b3e5e19.png)
