### ISSUE TITLE
ZYTX-Shenyang Taoxian Airport-LIAONING-CHINA

### ISSUE THREAD

**Issue by FlightGeekYuta** [InfiniteFlightAirportEditing/Airports#4135]
# Airport Name
Shenyang Taoxian International Airport

# Country?

China

# Improvements that need to be made?

Shenyang Taoxian International Airport badly needs to be redone. The current version only has a runway and a taxiway. In reality the airport has a huge (to me) terminal that is nowhere to be seen in Infinite Flight

# Are you working on this airport?

I just started Airport Editing. Im going to try but I won't recommend counting on me. If you are experienced, please work on this. I will try my best I probably can't. (I don't quite know how this forum works yet.

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

I'd say it is a pretty major priority. The city is pretty large and the airport also seems pretty large. I am still not sure of how this works so forgive me if i make any mistakes and don't be harsh :)

**Comment by Airbus-737** [comment]
If you can't do this, I'll do it. I've done 2 airports (both in peer review) and am almost finished with my 3rd airport.

**Comment by FlightGeekYuta** [comment]
I’m going to try @Airbus-737 (if that’s how even the forum works) if I can’t, I’ll give it you

**Comment by FlightGeekYuta** [comment]
My computer broke so can’t work on it

**Comment by kztmtn** [comment]
OK, I take this one, so could you change ICAO code to correct one, **ZYTX**?
I hope my computer would not be broken.

**Comment by kztmtn** [comment]
Sent in for OR.
No rush for review..

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/66599050-cb3ebc80-eb78-11e9-8f1d-3b390f5fd9c6.jpg)
