### ISSUE TITLE
KAJO-Corona Municipal Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by TheFlyingGuy1** [InfiniteFlightAirportEditing/Airports#4136]
# Airport Name

< Corona Municipal >

# Country?

< United States >

# Improvements that need to be made?

< Parking >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< IF Event >

**Comment by TheFlyingGuy1** [comment]
Just finished

**Comment by ECoops-123** [comment]
What is the progress of this airport @TheFlyingGuy1? It is not in the repository or has had any signs of completion on this issue.

**Comment by ECoops-123** [comment]
Editor confirmed unable to complete, I'll be taking over.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106840453-cd7a3380-6665-11eb-8541-4b0ead338966.png)
