### ISSUE TITLE
LFBD-Bordeaux Airport-MERIGNAC-FRANCE

### ISSUE THREAD

**Issue by gsherbert** [InfiniteFlightAirportEditing/Airports#4137]
# Airport Name

Bordeaux Airport

# Country?

France

# Improvements that need to be made?

Redo from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

GP2 (10000+ Runway)

**Comment by gsherbert** [comment]
Accidently hit error- Let me fill in the blanks first.

**Comment by MajorTomMueller** [comment]
Hi @gsherbert, still working on it?

**Comment by MajorTomMueller** [comment]
member inactive, up for grabs.
Well documented one
AIP text:
https://www.sia.aviation-civile.gouv.fr/dvd/eAIP_21_MAY_2020/FRANCE/AIRAC-2020-05-21/pdf/FR-AD-2.LFBD-fr-FR.pdf#AD-2.eAIP.LFBD
https://www.sia.aviation-civile.gouv.fr/dvd/eAIP_21_MAY_2020/FRANCE/AIRAC-2020-05-21/html/eAIP/Cartes/LFBD/AD%202%20LFBD%20MIA_TEXT%2001.pdf
https://www.sia.aviation-civile.gouv.fr/dvd/eAIP_21_MAY_2020/FRANCE/AIRAC-2020-05-21/html/eAIP/Cartes/LFBD/AD%202%20LFBD%20MIA_TEXT%2002.pdf
https://www.sia.aviation-civile.gouv.fr/dvd/eAIP_21_MAY_2020/FRANCE/AIRAC-2020-05-21/html/eAIP/Cartes/LFBD/AD%202%20LFBD%20MIA_TEXT%2003.pdf
https://www.sia.aviation-civile.gouv.fr/dvd/eAIP_21_MAY_2020/FRANCE/AIRAC-2020-05-21/html/eAIP/Cartes/LFBD/AD%202%20LFBD%20OACI%2001.pdf
https://www.sia.aviation-civile.gouv.fr/dvd/eAIP_21_MAY_2020/FRANCE/AIRAC-2020-05-21/html/eAIP/Cartes/LFBD/AD%202%20LFBD%20ADC%2001.pdf
https://www.sia.aviation-civile.gouv.fr/dvd/eAIP_21_MAY_2020/FRANCE/AIRAC-2020-05-21/html/eAIP/Cartes/LFBD/AD%202%20LFBD%20APDC%2001.pdf
https://www.sia.aviation-civile.gouv.fr/dvd/eAIP_21_MAY_2020/FRANCE/AIRAC-2020-05-21/html/eAIP/Cartes/LFBD/AD%202%20LFBD%20GMC%2001.pdf

**Comment by AeroTrapp** [comment]
Is it still a suggestion ?
Can I take it then ?

**Comment by AeroTrapp** [comment]
Hi @MajorTomMueller Can you assign me to LFBD ?

**Comment by MajorTomMueller** [comment]
No, you have already three open issues @AeroTrapp

**Comment by AeroTrapp** [comment]
Hi @MajorTomMueller 
I have 1 vacant issue. Did you take LFBD ?

**Comment by MajorTomMueller** [comment]
Yes, it is part of my project. That’s why I took over.

**Comment by MajorTomMueller** [comment]
@AeroTrapp if you want to take over, check image source. And let me know when you think you can handle the issues resulting from this. If you convince me that you succeed I leve it to you.

**Comment by AeroTrapp** [comment]
I wanted to take it. But you have already started working on it. I let you LFBD then 😉

**Comment by MajorTomMueller** [comment]
I have just pulled up imagery, I wouldn't offer when I have done more.

**Comment by AeroTrapp** [comment]
I'd love to take Bordeaux. If you don't mind 🙏

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/95925204-d2e20400-0d7e-11eb-8686-750b3bd5828c.png)
