### ISSUE TITLE
LCEN-Ercan Airport-LACARNA-CYPRUS

### ISSUE THREAD

**Issue by Martijn-Decates** [InfiniteFlightAirportEditing/Airports#4138]
# Airport Name

< Ercan International Airport >

# Country?

< Cyprus >

# Improvements that need to be made?

< New airprot >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< N/A >

**Comment by alpster1** [comment]
If you discontinued this airport, can I have it in 2 weeks?

**Comment by Balloonchaser** [comment]
Since no progress has been made on this airport. Anyone else want?

**Comment by MajorTomMueller** [comment]
Not in Navigraph 
![8DCE3C97-EAEA-4333-8B04-0F4A986E21EF](https://user-images.githubusercontent.com/26853210/102518687-e0bf4880-4091-11eb-8044-4d4a6ff7577f.png)
And turkeys government wants money for their AIP

**Comment by IFsami** [comment]
I will take it

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109419852-328b2580-7995-11eb-9a35-31375d6c453f.png)
Under construction in most satellite images

**Comment by ECoops-123** [comment]
Sufficient charts and all information found, area in construction is completely fenced off from the active airport and does not disrupt anything, have information for the ILS and runway, and imagery for the active part of the airport is available. I'll do this, and the new area will be added by whoever when it is fully completed.

Had a quick 10 minute test to see if it would work, seems perfect.
![1-1](https://user-images.githubusercontent.com/59462519/111706843-ea944b80-883a-11eb-9f2b-7f870e10babf.png)

**Comment by ECoops-123** [comment]
![Full](https://user-images.githubusercontent.com/59462519/111854307-6adbaf00-8916-11eb-8297-03a63cd46de6.png)
