### ISSUE TITLE
FKYS-Yaounde Nsimalen Airport-LITTORAL-CAMEROON

### ISSUE THREAD

**Issue by Martijn-Decates** [InfiniteFlightAirportEditing/Airports#4139]
# Airport Name

< Yaounde Nsimalen Airport >

# Country?

< Cameroon >

# Improvements that need to be made?

< new airport not in IF >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< N/A >

**Comment by brunocr98** [comment]
Re-assigning this airport to another editor, due to inactivity and apparent no progress.

**Comment by Etienne008g** [comment]
Ok. I will

**Comment by GBKarp** [comment]
I'll take it

**Comment by kilt46** [comment]
![Uploading image.png…]()
