### ISSUE TITLE
UKKK-Kyiv/Zhuliany Airport-KIEV-UKRAINE

### ISSUE THREAD

**Issue by Martijn-Decates** [InfiniteFlightAirportEditing/Airports#4140]
# Airport Name

< Kyiv/Zhuliany Airport >

# Country?

< Ukraine >

# Improvements that need to be made?

< Full rework >

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< N/A >

**Comment by bavariaaviation** [comment]
@Martijn-Decates any progress on this?

**Comment by bavariaaviation** [comment]
Taking over.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/80240673-a43d6900-8638-11ea-93eb-844cfa7b7e66.jpg)
