### ISSUE TITLE
VABP-Raja Bhoj Airport-MADHYA PRADESH-INDIA

### ISSUE THREAD

**Issue by Ayush-19** [InfiniteFlightAirportEditing/Airports#4141]
# Airport Name

Raja Bhoj Airport

# Country?

India

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

None

**Comment by Ayush-19** [comment]
Sent for OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/60272716-0b7c7680-98cb-11e9-9142-e953671bc1b0.jpg)
