### ISSUE TITLE
KMGE-Dobbins ARB-GEORGIA-USA

### ISSUE THREAD

**Issue by JamesBrowne1** [InfiniteFlightAirportEditing/Airports#4143]
♻️

**Comment by JamesBrowne1** [comment]
I'll do it quickly if you look on pictures the airport is only tiny

**Comment by brunocr98** [comment]
Airport closed

**Comment by MajorTomMueller** [comment]
recycled

**Comment by MajorTomMueller** [comment]
![KMGE-git](https://user-images.githubusercontent.com/26853210/61185128-06e2ec80-a645-11e9-849a-6040edd3e10e.PNG)
