### ISSUE TITLE
KCPM-Compton/Woodley Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by hossss6** [InfiniteFlightAirportEditing/Airports#4144]
# Airport Name

 Compton Woodley Airport 

# Country?

 America 

# Improvements that need to be made?

 Whole airport rework 

# Are you working on this airport?

 Improved taxiways and also adding gates into the airport

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MajorTomMueller** [comment]
You are not supposed to just close issues that are not finished. And it is finished when a administrator (or supervisor) added the related apt to the database.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104094693-12be6780-5258-11eb-9fad-bea679cd5906.png)
