### ISSUE TITLE
LTBQ-Cengiz Topel Air Base-KOCAELI-TURKEY

### ISSUE THREAD

**Issue by rich-art-02** [InfiniteFlightAirportEditing/Airports#4147]
# Airport Name

Cengiz Topel Air Base

# Country?

Turkey

# Improvements that need to be made?

Redo from scratch

# Are you working on this airport?
yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by rich-art-02** [comment]
Sent in to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/75923935-d1de1100-5e44-11ea-9e6e-17a1ae10e345.jpg)
