### ISSUE TITLE
KDLN-Dillon Airport-MONTANA-USA

### ISSUE THREAD

**Issue by IFC-PlaneCrazy** [InfiniteFlightAirportEditing/Airports#4152]
# Airport Name

Dillon Airport

# Country?

USA

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by IFC-PlaneCrazy** [comment]
Sent to OR!

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/60104034-0981ae80-9737-11e9-89c0-6502df4883e6.jpg)
