### ISSUE TITLE
FVFA-Victoria Falls Airport-MATABELELAND NORTH-ZIMBABWE

### ISSUE THREAD

**Issue by gsherbert** [InfiniteFlightAirportEditing/Airports#4155]
# Airport Name

Victoria Falls Airport

# Country?

Zimbabwe

# Improvements that need to be made?

Redo from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low Priority

**Comment by liamkirky** [comment]
Presume the member is inactive, will be doing.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85946725-1453be00-b90c-11ea-8c0d-3e59cc44722e.png)
