### ISSUE TITLE
FLHN-Harry Mwanga Nkumbula International Airport-SOUTH PROVINCE-ZAMBIA

### ISSUE THREAD

**Issue by gsherbert** [InfiniteFlightAirportEditing/Airports#4156]
# Airport Name

Harry Mwanga Nkumbula International Airport

# Country?

Zambia

# Improvements that need to be made?

Redo from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low Priority

**PLEASE NOTE:** ICAO code was changed from FLLI to FLHN
--->Airport formerly known as Livingstone Airport w/ ICAO: FLLI)
--->**This airport will replace FLLI, which is unedited currently and in IF**

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/60107088-aeeb5100-973c-11e9-8132-01ae7df9db57.jpg)
