### ISSUE TITLE
NZGB-Great Barrier Island, Claris Airport-AUCKLAND-NEW ZEALAND

### ISSUE THREAD

**Issue by Lukeh0** [InfiniteFlightAirportEditing/Airports#4157]
# Airport Name

Great Barrier Island, Claris Airport

# Country?

New Zealand

# Improvements that need to be made?

Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/60141320-4d060800-978b-11e9-9fd4-8366f0fb4cf4.jpg)
