### ISSUE TITLE
ZGNN-Nanning Wuxu International Airport-GUANGXI-CHINA

### ISSUE THREAD

**Issue by mguo787** [InfiniteFlightAirportEditing/Airports#4159]
# Airport Name

Nanning Wuxu International Airport

# Country?

China

# Improvements that need to be made?

Redone

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

World Capital, 10K+

**Comment by zacky89315** [comment]
I want to take over this issue.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/91494559-a16cb200-e87e-11ea-9540-9d8e59df15b8.png)
