### ISSUE TITLE
EGSC-Cambridge Airport-CAMBRIDGESHIRE-UNITED KINGDOM

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#416]
Needs rework

**Comment by IceBlue02** [comment]
will do.

**Comment by IceBlue02** [comment]
Done & submitted :)

**Comment by dushyants19** [comment]
This airport is missing :neutral_face: I'll look into this.

**Comment by dushyants19** [comment]
Done. https://github.com/InfiniteFlightAirportEditing/Airports/commit/19abe7a8fa82bb5580e64dd81cf1d0621e34ede4

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20598752/3fa9800a-b210-11e6-8fae-8666eafb9488.png)

**Comment by CptNathanHope** [comment]
https://community.infinite-flight.com/t/missing-runway-center-line-markings-at-cambridge-airport-egsc/141861

I'll fix this. :)

**Comment by MajorTomMueller** [comment]
Is this real still open? Just have checked in IF, and the rwy centreline that was misssing is there.
On the other Hand the apt file in the repo wasn‘t touched...

**Comment by CptNathanHope** [comment]
Yeah, that is very strange as I just checked myself. Must've been either a rendering issue or an issue with the ground elevation pre-global version.

Just changed the elevation to its proper height and changed the runway markings to match the real-life counterpart. I will be committing it shortly. 

Thanks for the heads up. - N

**Comment by CptNathanHope** [comment]
Fixed via [`8980183`](https://github.com/InfiniteFlightAirportEditing/Airports/commit/898018379fa36d41215d1c4785a1e217eaa54cfc).

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/35419207-553c6dd2-01fc-11e8-83b3-c0918ae72908.png)

**Comment by MajorTomMueller** [comment]
Spawn size,
Needs to bear the C-130s
https://www.forces.net/services/raf/hercules-fleet-given-new-lease-life
Would you @CptNathanHope ?

**Comment by MajorTomMueller** [comment]
https://github.com/InfiniteFlightAirportEditing/Airports/commit/8a62083313ec46dff3dfb8a4b896afbcfd4a6b86
![EGSC-git](https://user-images.githubusercontent.com/26853210/70849303-b5998c00-1e74-11ea-8fec-be0593d012b9.png)
