### ISSUE TITLE
NZOX-Okiwi Airport-AUCKLAND-NEW ZEALAND

### ISSUE THREAD

**Issue by Lukeh0** [InfiniteFlightAirportEditing/Airports#4161]
# Airport Name

Okiwi Airport

# Country?

New Zealand

# Improvements that need to be made?

Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/60141442-efbe8680-978b-11e9-9e69-470d4cf87034.jpg)
