### ISSUE TITLE
NZDA-Dargaville Airport-NORTHLAND-NEW ZEALAND

### ISSUE THREAD

**Issue by Lukeh0** [InfiniteFlightAirportEditing/Airports#4162]
# Airport Name

Dargaville Airport

# Country?

New Zealand

# Improvements that need to be made?

Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/60141146-8d18bb00-978a-11e9-85a2-9c7cd21039b2.jpg)
