### ISSUE TITLE
ENKJ-Kjeller Airport-AKERSHUS-NORWAY

### ISSUE THREAD

**Issue by Developer-33** [InfiniteFlightAirportEditing/Airports#4163]
# Airport Name

Kjeller

# Country?

Norway

# Improvements that need to be made?

Redone from Scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by Developer-33** [comment]
I can’t edit, i am pretty sure my PC can’t handle the Editing so i am not Editing this!

**Comment by IFAEPaul** [comment]
I will do the rework

**Comment by MajorTomMueller** [comment]
Hint: 
https://ais.avinor.no/en/AIP/View/57/aip/ad/enkj/enkj_en.html

**Comment by Developer-33** [comment]
I can do the work now!!. If you want, I can do it

**Comment by Developer-33** [comment]
I can make it

**Comment by IFAEPaul** [comment]
Okay, do it. I haven't done a lot yet. You have the permission to get assigned

**Comment by Developer-33** [comment]
Ok thanks! Finaly It works to edit an Airport

**Comment by Developer-33** [comment]
ENKJ send to Official Review:
![ENKJ-OR](https://user-images.githubusercontent.com/45124789/71784370-3884b100-2ff3-11ea-9c6e-50c038940f68.jpg)

**Comment by Developer-33** [comment]
I won't close the issue now.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/72672657-20258500-3a3c-11ea-8a58-f7785396b763.jpg)
