### ISSUE TITLE
VEZO-Ziro Airport-ARUNACHAL PRADESH-INDIA

### ISSUE THREAD

**Issue by Ayush-19** [InfiniteFlightAirportEditing/Airports#4164]
# Airport Name

Ziro Aiport

# Country?

India

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

None

**Comment by Ayush-19** [comment]
Sent in for OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/60105624-050ac500-973a-11e9-8c6f-92fe241fe8a1.jpg)
