### ISSUE TITLE
VIHR-Hisar Airport-HARYANA-INDIA

### ISSUE THREAD

**Issue by Ayush-19** [InfiniteFlightAirportEditing/Airports#4165]
# Airport Name

Hisar Airport

# Country?

India

# Improvements that need to be made?

Full rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

None

**Comment by Ayush-19** [comment]
Sent for OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/60105773-574be600-973a-11e9-831f-e8b856e0fc9b.jpg)
