### ISSUE TITLE
VOGO-Dabolim Airport-GOA-INDIA

### ISSUE THREAD

**Issue by Parth3315** [InfiniteFlightAirportEditing/Airports#4169]
# Airport Name
Goa International Airport 

# Country?

India

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

10k feet

**Comment by Parth3315** [comment]
It is Done

**Comment by MajorTomMueller** [comment]
@Parth3315 do not remove your assignment!, This will be done when it passed review by the reviewer!

**Comment by KaalicharanDH** [comment]
I will do it. And please change the title to VOGO-Goa Airport-Goa-India

**Comment by GBKarp** [comment]
Can I be assigned please? Also, it's a Priority 2

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123524301-ed4eda00-d68e-11eb-8832-023a1ab06073.png)
