### ISSUE TITLE
FAEL-East London Airport-EASTERN CAPE-SOUTH AFRICA

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#4172]
# Airport Name?

East London Airport

# Country?

Africa

# Improvements that need to be made?

Full rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by Matt1093** [comment]
Can I please get assigned to this airport? I would like to start it!

**Comment by osujim15** [comment]
May I do this one?

**Comment by MajorTomMueller** [comment]
@osujim15 how are you? Still doing this one?

**Comment by osujim15** [comment]
Nope. I forfeit it.

**Comment by Czechoslovaki** [comment]
Completed in #4628.

**Comment by MajorTomMueller** [comment]
![EYRK](https://user-images.githubusercontent.com/26853210/103652204-aba06a80-4f5a-11eb-95da-62ed2f8f9b35.png)

**Comment by MajorTomMueller** [comment]
https://github.com/InfiniteFlightAirportEditing/Airports/commit/a2fc5807f72281a2b4df6fd6037bbcb471138eef
