### ISSUE TITLE
HSSJ-Juba International Airport-JUBEK-SOUTH SUDAN

### ISSUE THREAD

**Issue by pilot0674** [InfiniteFlightAirportEditing/Airports#4173]
# Airport Name

Juba International Airport

# Country?

South Sudan

# Improvements that need to be made?

Remake Airport -airport was originally auto-generated.

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

High; South Sudan's largest and main airport, airport of the Capitol City, Juba.

**Comment by MajorTomMueller** [comment]
Matches none repository priorities. If your it is a high priority in your opinion I expect it to be ready for a single attempt OR pass in less then 2 weeks.

**Comment by IFsami** [comment]
I can do it

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104531772-8a7fef80-55d4-11eb-8ae7-b830134f3781.png)
