### ISSUE TITLE
ENHK-Hasvik Airport-FINNMARK-NORWAY

### ISSUE THREAD

**Issue by JensSeverin** [InfiniteFlightAirportEditing/Airports#4175]
# Airport Name

Hasvik Airport

# Country?

Norway

# Improvements that need to be made?

Redo from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by JensSeverin** [comment]
Can someone assign me, thanks

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/65000036-78971b00-d8c0-11e9-8e18-3392b6ac1140.jpg)
