### ISSUE TITLE
EGXW-RAF Waddington-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by benjwri** [InfiniteFlightAirportEditing/Airports#4178]
# Airport Name

RAF Waddington

# Country?

United Kingdom

# Improvements that need to be made?

Full rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

None

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/62656732-426a9100-b93b-11e9-8093-7fa2cd778842.jpg)
