### ISSUE TITLE
NZAA-Auckland Airport-AUCKLAND-NEW ZEALAND

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#418]

**Comment by JohnPreston21** [comment]
We have new uncovered regions?

**Comment by kilt46** [comment]
Airport redone from scratch

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17248721/e89e3c16-5561-11e6-8313-90f91873e631.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18412864/f33b9640-775e-11e6-9a92-98f8f692f035.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18412870/193b3904-775f-11e6-958c-0dd6d8585695.png)

**Comment by dushyants19** [comment]
North Runway was removed.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/77369955-854c6e00-6d3e-11ea-9d99-8ce7a40f4801.jpg)

**Comment by kilt46** [comment]
![Uploading image.png…]()

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/94870784-113a0380-040e-11eb-9ddd-7285a7b98c98.png)
