### ISSUE TITLE
00WA-Howell Airstrip-WASHINGTON-USA

### ISSUE THREAD

**Issue by alphabravo6** [InfiniteFlightAirportEditing/Airports#4182]
![image](https://user-images.githubusercontent.com/14023167/92041569-12f4a680-ed3e-11ea-95fa-651d6aa9f946.png)

**Comment by MajorTomMueller** [comment]
@alphabravo6 you have reached the three issue limit. You might be assigned when one. Of your issues have passed OR, or all three of them are in OR.

**Comment by Captsebastian1698** [comment]
i'll do it

**Comment by Captsebastian1698** [comment]
i have spoken to alphabravo6 privately and he has given me permission to take over this airport, as he lost his file for it. he said if you have any issues, message him through slack. :)

**Comment by MajorTomMueller** [comment]
Done @Captsebastian1698

**Comment by alphabravo6** [comment]
Thanks @MajorTomMueller
