### ISSUE TITLE
SNWS-Crateus Airport-CEARA-BRAZIL

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Airports#4184]
# Airport Name

< Crateus >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/62658974-8dd36e00-b940-11e9-8f5d-bda6bed19046.jpg)
