### ISSUE TITLE
SBDO-Dourados Airport-MATO GROSSO DO SUL-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#4185]
# Airport Name

Dourados Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/60684700-abab4000-9e75-11e9-8719-1ed739656dcf.jpg)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/89579727-e3638480-d7f9-11ea-8d66-8c6120508015.png)
