### ISSUE TITLE
LEMD-Adolfo Suárez Madrid–Barajas Airport-COMUNIDAD DE MADRID-SPAIN

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#419]
Próximamente, Madrid!

**Comment by turkish1941** [comment]
How is it going?

**Comment by JcFl4** [comment]
Still working on it. It's looking great!

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19836979/04d269f6-9e7e-11e6-8a38-411faa7813a6.png)

**Comment by kilt46** [comment]
Terminal 1
![image](https://cloud.githubusercontent.com/assets/14023167/19836991/3ecb8bc4-9e7e-11e6-8cfa-245669402819.png)

**Comment by kilt46** [comment]
Terminal 4 and 4S
![image](https://cloud.githubusercontent.com/assets/14023167/19836994/59bbfa22-9e7e-11e6-8f69-2999c8f69c2b.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/58918624-560e3700-8701-11e9-9474-874e9ca69648.jpg)

**Comment by brunocr1050** [comment]
Added new gates at Terminal 4S and updated some ramps south of the airfield.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104819833-df4e8080-57f5-11eb-8058-17aa47f04c01.png)
