### ISSUE TITLE
EPLL-Lodz Airport-LODZ-POLAND

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#4190]
# Airport Name

< Lodz Airport >

# Country?

< POLAND >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kztmtn** [comment]
Sent in for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/61341167-af4aa980-a81b-11e9-9c96-a8f74fef1d08.jpg)
