### ISSUE TITLE
LRFT-Fetești Airbase-Județul Călărași-ROMANIA

### ISSUE THREAD

**Issue by Agustin-VR** [InfiniteFlightAirportEditing/Airports#4192]
♻️

**Comment by brunocr98** [comment]
This airport has been redone and current imagery isn't sufficient for the changes you're requesting.

**Comment by MajorTomMueller** [comment]
Recycled

**Comment by MajorTomMueller** [comment]
![LRFT](https://user-images.githubusercontent.com/26853210/61590817-cc7dd000-abad-11e9-9526-3bad157dc750.PNG)
