### ISSUE TITLE
00FL-River Oak Airpark-FLORIDA-USA

### ISSUE THREAD

**Issue by Agustin-VR** [InfiniteFlightAirportEditing/Airports#4196]
# Airport Name

Lovell Field

# Country?

USA

# Improvements that need to be made?

Missing parking spots, wrong airport markings

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90990652-b4267480-e568-11ea-86a6-7c04c93e8a44.png)
