### ISSUE TITLE
EVJA-Jūrmala Airport-ENGURE PARISH-LATVIA

### ISSUE THREAD

**Issue by trungquan99** [InfiniteFlightAirportEditing/Airports#4199]
Recycle ♻️

**Comment by brunocr98** [comment]
This is not a place for your airport wishlist.

**Comment by MajorTomMueller** [comment]
recycled

**Comment by MajorTomMueller** [comment]
![EVJA git](https://user-images.githubusercontent.com/26853210/61577688-66744880-aada-11e9-8f67-2e3712ef3736.PNG)
