### ISSUE TITLE
LHSS

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#42]

**Comment by IFAEpat** [comment]
Szolnok-Szandaszőlős Airport

**Comment by IFAEpat** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17209451/b7bf5e8e-5482-11e6-8535-9375c49391d7.png)

**Comment by IFAEpat** [comment]
Gated

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17719760/91dfea16-63e2-11e6-9737-31981080ef71.png)
