### ISSUE TITLE
99CL-El Mirage Field-CALIFORNIA-USA

### ISSUE THREAD

**Issue by Ksisky** [InfiniteFlightAirportEditing/Airports#420]

**Comment by dushyants19** [comment]
Region? @Ksisky

**Comment by HenrikBerg02** [comment]
@dushyants19, stop being lazy, search it up. The region is Southern California.

**Comment by dushyants19** [comment]
This airport is a desert where 2 of its runways can be barely seen..

**Comment by dushyants19** [comment]
Done

**Comment by dushyants19** [comment]
Gated in e6e01a929fd9a17870e6ed18746a8f3af04192d0

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32689121-0ab028dc-c6a4-11e7-9089-4594fdf69386.png)

**Comment by kilt46** [comment]
New Runway
![image](https://user-images.githubusercontent.com/14023167/83351063-7f5aa680-a306-11ea-9a8c-58d4c86c54f4.png)

**Comment by kilt46** [comment]
![Uploading image.png…]()

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/99906506-32e09a00-2c9d-11eb-8d26-fa8c8dc9782b.png)
