### ISSUE TITLE
EVLA-Liepāja International Airport-LATVIA

### ISSUE THREAD

**Issue by trungquan99** [InfiniteFlightAirportEditing/Airports#4201]
Recycle ♻️

**Comment by brunocr98** [comment]
I don’t know what you’re trying to do but please stop.

**Comment by MajorTomMueller** [comment]
recycled

**Comment by MajorTomMueller** [comment]
![ELVA](https://user-images.githubusercontent.com/26853210/61594133-7de52b80-abd7-11e9-85c1-6253180e4d0f.PNG)
