### ISSUE TITLE
KROX-Roseau Municipal Airport/Rudy Billberg Field-MINNESOTA-USA

### ISSUE THREAD

**Issue by danisrils39** [InfiniteFlightAirportEditing/Airports#4202]
# Airport Name

Roseau Municipal Airport/Rudy Billberg Field

# Country?

USA

# Improvements that need to be made?

scratch

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

N/A

**Comment by danisrils39** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/61340873-968dc400-a81a-11e9-9158-35658ae82e71.jpg)
