### ISSUE TITLE
EPCE-Cewice Air Base-LEBORK-POLAND

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#4203]
# Airport Name

< Cewice Air Base >

# Country?

< Poland >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MajorTomMueller** [comment]
https://ais.pansa.pl/aip/aip.html
https://ais.pansa.pl/aip/aippliki/EP_AD_2_EPCE_1-1-1_en.pdf

**Comment by kztmtn** [comment]
Sent in for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/62659938-266aed80-b943-11e9-8509-6ae9de3c01b4.jpg)
