### ISSUE TITLE
YBWP-Weipa Airport-NEW SOUTH WALES-AUSTRALIA

### ISSUE THREAD

**Issue by sam2875** [InfiniteFlightAirportEditing/Airports#4204]
# Airport Name

Weipa Airport

# Country?

Australia

# Improvements that need to be made?

Missing Parking Spaces and Taxiway Markings - Complete Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by sam2875** [comment]
Sent for OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/64997775-1afed080-d8b8-11e9-80ed-ef1d5351793e.jpg)
