### ISSUE TITLE
UMMG-Hrodna Airport-HRODNA-BELARUS

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#4206]
# Airport Name

< Hrodna Airport >

# Country?

< Belarus >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kztmtn** [comment]
Submitted for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/62656271-2aded880-b93a-11e9-8ab5-f1360816cd5e.jpg)
