### ISSUE TITLE
NZRC-Ryan's Creek Aerodrome-SOUTHLAND-NEW ZEALAND

### ISSUE THREAD

**Issue by Captsebastian1698** [InfiniteFlightAirportEditing/Airports#4207]
# Airport Name

< NZRC/Ryans Creek >

# Country?

< New Zealand >

# Improvements that need to be made?

< REDO >

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< low >

**Comment by Lukeh0** [comment]
Same deal with NZKM - I can also spit this one tomorrow if all good

**Comment by Captsebastian1698** [comment]
Hi im still in the midle of doing this? i just have been busy im getting back into it now tho.

**Comment by MajorTomMueller** [comment]
![NZRC-git](https://user-images.githubusercontent.com/26853210/131215966-5255f24f-4f9d-438e-9cd4-77da90e713a6.png)
