### ISSUE TITLE
KNHK-Patuxent River Naval Station-MARYLAND-USA

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#4210]
# Airport Name

Patuxent River Naval Station

# Country?

USA

# Improvements that need to be made?

Needs some lovin' cuz the government ain't doing it

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

10,000 foot+ runway

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/66596283-fc1bf300-eb72-11e9-824a-954e1965fa9c.jpg)
