### ISSUE TITLE
KNTU-Naval Air Station Oceana-VIRGINIA-USA

### ISSUE THREAD

**Issue by hossss6** [InfiniteFlightAirportEditing/Airports#4214]
# Airport Name

<Naval Air Station Oceana >

# Country?

< United States >

# Improvements that need to be made?

<Added gates and improved runways>

# Are you working on this airport?

< Whole airport rework>

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MajorTomMueller** [comment]
Hi @hossss6 , community asks for progress...

https://community.infiniteflight.com/t/airport-and-navigation-updates-february-2020/406159/117

**Comment by hossss6** [comment]
Yes sorry just now getting back into airport editing. I will have to start this airport all over again due to all files in my hardd drive being deleted

**Comment by MajorTomMueller** [comment]
Your call @hossss6 
https://community.infiniteflight.com/t/project-fighter-bases/218127/129?u=major-tom

**Comment by Jeremy351** [comment]
Hi @hossss6 
Do you still working on NAS Oceana ?

**Comment by hossss6** [comment]
@Jeremy351 im working on this just have had other priorities. Need to fix pavement then check over the whole airport again for no mistakes

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104865772-83bde900-5902-11eb-999a-17c5438c0ed7.png)
