### ISSUE TITLE
VAID-Devi Ahilya Bai Holkar International/Indore Airport-MADHYA PRADESH-INDIA

### ISSUE THREAD

**Issue by akshay2777** [InfiniteFlightAirportEditing/Airports#4215]
# Airport Name

Devi Ahilya Bai Holkar International Airport

# Country?

India

# Improvements that need to be made?

from scratch

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/66597774-05f32580-eb76-11e9-85e5-99e17e1cd9be.jpg)
