### ISSUE TITLE
VASU-Surat International Airport-GUJARAT-INDIA

### ISSUE THREAD

**Issue by akshay2777** [InfiniteFlightAirportEditing/Airports#4216]
# Airport Name
 
Surat international Airport
# Country?

India

# Improvements that need to be made?

from scratch

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/66598164-cc6eea00-eb76-11e9-8338-3ac5887da483.jpg)
