### ISSUE TITLE
UMOO-Mahiliou Airport-MAHILIOU-BELARUS

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#4217]
# Airport Name

< Mahiliou Airport >

# Country?

< Belarus >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MajorTomMueller** [comment]
You are already assigned to three issues. with this rule under enforcement you have to wait for one of the others to pass OR.
Thanks for you patience.

**Comment by MajorTomMueller** [comment]
With your previous issues closed I assigned you now @kztmtn

**Comment by kztmtn** [comment]
@MajorTomMueller Thank you!
Sent in for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/63463139-f1769480-c432-11e9-9c17-3e2480dd3043.jpg)
