### ISSUE TITLE
KMRN

### ISSUE THREAD

**Issue by freddiefrogs** [InfiniteFlightAirportEditing/Airports#422]
Needs love

**Comment by freddiefrogs** [comment]
Undeveloped

**Comment by dushyants19** [comment]
mention region please :)

**Comment by HenrikBerg02** [comment]
@dushyants19, more laziness. The region is Charlotte.

**Comment by freddiefrogs** [comment]
im doing this. i dont know how to add the label. #noobproblems

**Comment by HenrikBerg02** [comment]
Hmm, it doesn't show you as part of the repo, @freddiefrogs. @carmichaelalonso, could you add him?

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17277342/6198296a-5706-11e6-94b2-ebb919c75776.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17821490/90ef188e-6617-11e6-8739-4611bf43a59e.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17821504/9b7f134e-6617-11e6-9fa6-76a851cb2ff4.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17821508/9f6208fe-6617-11e6-89fc-72d1cd418b73.png)
