### ISSUE TITLE
ZUDC-Daocheng Yading Airport-SICHUAN-CHINA

### ISSUE THREAD

**Issue by lukewilson16** [InfiniteFlightAirportEditing/Airports#4220]
# Airport Name

Daocheng Yading Airport

# Country?

China

# Improvements that need to be made?

Needs to be built from scratch 

# Are you working on this airport?

I will work on this airport

# Airport Priority? (IF Event, 10000 ft+ Runway, World/US Capital, Low)

10000 ft+ Runway

**Comment by CrisYe** [comment]
I finished this airport,anyone can assigned this airport to me?

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/77239444-8f912f80-6bb9-11ea-8485-439bf588a05a.jpg)
