### ISSUE TITLE
NTMD-Nuku Hiva Airport-MARQUESAS ISLANDS-FRENCH POLYNESIA

### ISSUE THREAD

**Issue by danisrils39** [InfiniteFlightAirportEditing/Airports#4221]
# Airport Name

Nuku Hiva Airport

# Country?

French Polynesia

# Improvements that need to be made?

Scratch
# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

N/A

**Comment by danisrils39** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/62659553-10a8f880-b942-11e9-8def-cc5f53445d2e.jpg)
