### ISSUE TITLE
KCHU-Houston County-MINNESOTA-USA

### ISSUE THREAD

**Issue by Gabe-Z** [InfiniteFlightAirportEditing/Airports#4222]
# Airport Name

Houston County

# Country?

USA

# Improvements that need to be made?

Unedited, Redo from Scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by Gabe-Z** [comment]
Sent in for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/62655150-c753ab80-b937-11e9-9871-5e79d04ed0b0.jpg)
