### ISSUE TITLE
SWNM-Normandia Airstrip-RORAIMA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#4224]
# Airport Name

Normandia Airstrip

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/61822711-9dc35c00-ae30-11e9-8ed6-04a2652627eb.jpg)

**Comment by MBeringuy** [comment]
Normandia Airstrip in the state of Roraima was closed and the ICAO SWNM was transferred to Fazenda Modulo Aguapei Airstrip, in the state of Mato Grosso.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/120102555-29832f00-c111-11eb-8890-bccb3aa3d686.png)
