### ISSUE TITLE
BGSS

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#423]
Sisimiut Airport

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17199066/c11fa38c-543f-11e6-83ce-b41d5ac1ff79.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18570683/b63ee762-7b71-11e6-8fa4-342dce627da5.png)
