### ISSUE TITLE
VYNT-Naypyidaw International-NAYPYIDAW UNION TERRITORY-MYANMAR

### ISSUE THREAD

**Issue by pilot0674** [InfiniteFlightAirportEditing/Airports#4238]
# Airport Name

Ela Airport

# Country?

Myanmar

# Improvements that need to be made?

Change name, ICAO code, add taxiways and spawnpoints.

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

No

**Comment by MajorTomMueller** [comment]
You are assigned to three issues. Wait for one to be closed before opening a new one.

**Comment by MajorTomMueller** [comment]
VYEL is not existing anymore, Code changed to VYNT some years ago together with the official name.

**Comment by MBeringuy** [comment]
I will be editing this airport.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/63217567-b288cc00-c11e-11e9-92bb-674bc713c54a.jpg)
