### ISSUE TITLE
LBPD-Plovdiv Airport-PLOVDIV-BULGARIA

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#4239]
# Airport Name

< Plovdiv Airport >

# Country?

< Bulgaria >

# Improvements that need to be made?

< Do from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kztmtn** [comment]
Send in for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/63463749-35b66480-c434-11e9-8d97-40bc5274f918.jpg)
