### ISSUE TITLE
BIAR

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#424]
Akureyri Airport

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17199189/ad3475fe-5440-11e6-8a01-83fb067b08d4.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18536400/afd27010-7ac2-11e6-9a2c-803799c9f143.png)
