### ISSUE TITLE
KRED-Red Lodge Airport-MONTANA-USA

### ISSUE THREAD

**Issue by IFC-PlaneCrazy** [InfiniteFlightAirportEditing/Airports#4240]
# Airport Name

Red Lodge Airport

# Country?

USA

# Improvements that need to be made?

Will be redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by IFC-PlaneCrazy** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/63461997-45cc4500-c430-11e9-8ce2-e23d5b078018.jpg)
