### ISSUE TITLE
KMLU-Monroe Regional Airport-LOUISIANA-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#4245]
# Airport Name

Monroe Regional Airport

# Country?

United States of America

# Improvements that need to be made?

Redone from scratch. 

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low Priority

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68152863-3df64a00-ff23-11e9-8666-170ee661373b.jpg)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104385376-bfb70f80-54f8-11eb-8bd9-913724994299.png)
Updates by brennanhackard
