### ISSUE TITLE
23MN-High Grove-MINNESOTA-USA

### ISSUE THREAD

**Issue by Gabe-Z** [InfiniteFlightAirportEditing/Airports#4246]
# Airport Name

High Grove

# Country?

USA

# Improvements that need to be made?

Unedited airport and redo from scratch.

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by Gabe-Z** [comment]
Sent in for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/63462396-35689a00-c431-11e9-9245-e0db01c36c56.jpg)
