### ISSUE TITLE
NZKM-Karamea Aerodrome-WEST COAST-NEW ZEALAND

### ISSUE THREAD

**Issue by JimmyCoder1** [InfiniteFlightAirportEditing/Airports#4249]
# Airport Name

Karamea Aerodrome

# Country?

New Zealand

# Improvements that need to be made?

To be redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

None

**Comment by Lukeh0** [comment]
Probably best to un-assign this person been opened since August 2019, I can spit this one out tomorrow if all good.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/79668937-95fdd180-818e-11ea-93d3-e9951a4d0346.jpg)
