### ISSUE TITLE
TDPD-Douglas–Charles Airport-DOMINICA-DOMINICA

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#425]

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20641455/aeda4ea6-b3bd-11e6-8b6e-e44672a22e5d.png)

**Comment by ECoops-123** [comment]
@Daniel-Baiks will redo this. The taxiways are very non-aligned and is to meet modern day editing standards.

Cool beans.

**Comment by JcFl4** [comment]
I just hope the lines will remain as parallel as they are now.....
Might help: https://www.youtube.com/watch?v=9VhSNhxkOdA&feature=emb_title

**Comment by ECoops-123** [comment]
They actually aren't _incredibly_ misaligned, incorrect usage of wording. They are more updated and slightly different.

The assigned editor does a good job and I'm sure they won't disappoint in this airport. 🙃

![image](https://user-images.githubusercontent.com/59462519/105903681-1c95e800-6018-11eb-8f26-291793f121f1.png)

**Comment by JcFl4** [comment]
I hope so! Might be a little labour-intensive for some, but the quality of airport layouts should NOT be compromised due to speedy editing! **Quality over quantity**, guys. (I've seen this happen far too often...) Everyone likes to land at a pretty airport after a 12h flight: makes the wait worth it!

Check out this old video @IF-Airport-Team , might help: https://www.youtube.com/watch?v=9VhSNhxkOdA&feature=emb_title 

**The use of custom-made rules helps keep lines parallel.**

Keep up the good work! 
JC

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106065418-e9f3fa00-60c0-11eb-9191-69b9566d078a.png)
