### ISSUE TITLE
NGTA-Bonriki International Airport-BONRIKI-KIRIBATI

### ISSUE THREAD

**Issue by danisrils39** [InfiniteFlightAirportEditing/Airports#4250]
# Airport Name

Bonriki International Airport

# Country?

Kiribati

# Improvements that need to be made?

Scratch

# Are you working on this airport?

Suggestion

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

World Capital

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/63229120-559b1d80-c1d3-11e9-8b0f-39fa49f17e12.jpg)
