### ISSUE TITLE
EEKE-Kuressaare-SAARE-ESTONIA

### ISSUE THREAD

**Issue by Lukeh0** [InfiniteFlightAirportEditing/Airports#4253]
# Airport Name

Ryans Creek Airport

# Country?

New Zealand

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by Lukeh0** [comment]
I will consult with the person who opened the first and see where he/she is up to on the airport rework

**Comment by RyanEpps** [comment]
Please do so with the open issue, rather than opening a duplicate issue.

**Comment by MajorTomMueller** [comment]
recycled

**Comment by MajorTomMueller** [comment]
![EEKE-git](https://user-images.githubusercontent.com/26853210/64075268-808e7280-cca5-11e9-8d1f-18e3375f6a37.png)
