### ISSUE TITLE
UKKT-Sviatoshyn Airfield-KIEV-UKRAINE

### ISSUE THREAD

**Issue by danisrils39** [InfiniteFlightAirportEditing/Airports#4254]
# Airport Name

Kyiv/Antonov-1 National Airport

# Country?

Ukraine

# Improvements that need to be made?

Scratch

# Are you working on this airport?

Suggestion

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

World Capital, Antonov Serial Production Plant

**Comment by MajorTomMueller** [comment]
![UKKT-git](https://user-images.githubusercontent.com/26853210/71312374-e3a54000-2421-11ea-8563-1b72fd117ea6.png)
