### ISSUE TITLE
FALA-Lanseria Airport-GAUTENG-SOUTH AFRICA

### ISSUE THREAD

**Issue by JoshTomaz** [InfiniteFlightAirportEditing/Airports#4255]
# Airport Name

< Lanseria International Airport >

# Country?

< South Africa >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low, 10000ft+ Runway (9996ft) >

**Comment by JoshTomaz** [comment]
Sent in for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/73312930-a6925180-4208-11ea-8156-c6a0e0c01e4b.jpg)
