### ISSUE TITLE
18Y-Milaca Municipal Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by Gabe-Z** [InfiniteFlightAirportEditing/Airports#4265]
# Airport Name

Milaca Municipal Airport

# Country?

USA

# Improvements that need to be made?

Unedited Airport

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by Gabe-Z** [comment]
Sent in for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/64998131-5f3ea080-d8b9-11e9-94ae-629b09a2de6f.jpg)
