### ISSUE TITLE
RCNN-Tainan Airport-TAIWAN-TAIWAN

### ISSUE THREAD

**Issue by aads552** [InfiniteFlightAirportEditing/Airports#4267]
# Airport Name

Tainan Airport

# Country?

Taiwan

# Improvements that need to be made?

from scratch

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

10000ft+ Runway

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68154320-0a68ef00-ff26-11e9-94cc-71e070b079ad.jpg)
