### ISSUE TITLE
DUPLICATE

### ISSUE THREAD

**Issue by lukewilson16** [InfiniteFlightAirportEditing/Airports#4268]
# Airport Name

TVSA Argyle International Airport

# Country?

St. Vincent and the Grenadines

# Improvements that need to be made?

Taxiway shoulders missing, apron has bend near the cargo area and gates are labelled with the wrong size 

# Are you working on this airport?

I will work on this

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Enter text here >

**Comment by brunocr98** [comment]
You already completed this airport! #4103

**Comment by MajorTomMueller** [comment]
![EEJI-Git](https://user-images.githubusercontent.com/26853210/64477379-7202f800-d18a-11e9-8481-836947d2f1d5.png)
