### ISSUE TITLE
KTVL-Lake Tahoe Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#4269]
# Airport Name

Lake Tahoe Airport

# Country?

USA

# Improvements that need to be made?

Full rework

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

IF Event September

**Comment by moritzbabl** [comment]
Being redone by @chrisindfw

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/66951374-962ae200-f030-11e9-9c7a-36952df74f81.jpg)
