### ISSUE TITLE
BIRK-Reykjavík Airport-HOFUDBORGARSVAEDI-ICELAND

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#427]
Reykjavik, Iceland

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17208806/c072a642-547f-11e6-92b5-4d3a662bad31.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18421866/11be1322-7859-11e6-8ec3-6d563e1e94fa.png)

**Comment by MajorTomMueller** [comment]
Runway 06/24 closed
http://eaip.samgongustofa.is/graphics/eAIP/BIRK_1_2-1_AD_CHART_01_MAR_2019.pdf

**Comment by moritzbabl** [comment]
Done

**Comment by moritzbabl** [comment]
![image](https://user-images.githubusercontent.com/19365980/57955922-81b6b200-78f7-11e9-8d44-591ca8628abb.png)
