### ISSUE TITLE
KAZC-Colorado City Municipal Airport-COLORADO-USA

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#4270]
# Airport Name

Colorado City Municipal Airport

# Country?

USA

# Improvements that need to be made?

Full rework

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

IF Event September

**Comment by Gabe-Z** [comment]
I have sent the file to the Offical Review.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/64998855-1dfbc000-d8bc-11e9-821d-2d34923fbaee.jpg)
