### ISSUE TITLE
KPGA-Page Municipal Airport-ARIZONA-USA

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#4271]
# Airport Name

Page Municipal Airport

# Country?

USA

# Improvements that need to be made?

Full rework

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

IF Event September

**Comment by Gabe-Z** [comment]
Sent in for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/66950940-bb6b2080-f02f-11e9-8c0c-24bf4180f38e.jpg)
