### ISSUE TITLE
KTRK-Truckee Tahoe Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#4272]
# Airport Name

Truckee Tahoe Airport

# Country?

USA

# Improvements that need to be made?

Full rework

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

IF Event September

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/66951755-7c3dcf00-f031-11e9-82c8-8226be79f434.jpg)
