### ISSUE TITLE
LYNI-Niš Constantine the Great Airport-SERBIA

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#4276]
# Airport Name

Hawthorne Municipal Airport/Jack Northrop Field

# Country?

USA

# Improvements that need to be made?

Full Redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MajorTomMueller** [comment]
recycled

**Comment by MajorTomMueller** [comment]
![LYNI](https://user-images.githubusercontent.com/26853210/67371455-f0193380-f56b-11e9-95e6-000346758940.png)
