### ISSUE TITLE
KDFW-Dallas/Fort Worth International Airport-TEXAS-USA

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#428]
Next on my list

**Comment by kilt46** [comment]
Airport redrawn from scratch

**Comment by TristinWoolf** [comment]
Jacob S has fixed a couple misaligned spawn points and sent it in to the email. I don't think its necessary to re-open and label, etc.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18809306/7200d178-823d-11e6-8e2f-c7ecb5534450.png)

**Comment by moritzbabl** [comment]
Some spawns and taxiway parts are missing, @mbmhwue148 is fixing this issue

**Comment by kilt46** [comment]
Looks like stands are not up to date
![image](https://user-images.githubusercontent.com/14023167/34343552-896cd0a4-e999-11e7-9088-fc50f1438091.png)

**Comment by kilt46** [comment]
C15 missing
![image](https://user-images.githubusercontent.com/14023167/34343563-fbded844-e999-11e7-9efe-74b8b33bf541.png)

**Comment by kilt46** [comment]
E21 missing
![image](https://user-images.githubusercontent.com/14023167/34343574-4054a5d0-e99a-11e7-96fa-41a19631a6ba.png)

**Comment by kilt46** [comment]
B23 shouldn't be there
![image](https://user-images.githubusercontent.com/14023167/34343584-ac6b0bce-e99a-11e7-88bb-1cccc5f9bd4e.png)

**Comment by kilt46** [comment]
D24 should be D23
![image](https://user-images.githubusercontent.com/14023167/34343596-2122f9a4-e99b-11e7-87c1-263407fa4980.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/39960536-302618a8-55ea-11e8-8a77-10e06d22b769.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52605354-1d85dd00-2e34-11e9-9d3b-ec923f47c43c.png)
