### ISSUE TITLE
SSRG-Registro Airport-SAO PAULO-BRAZIL

### ISSUE THREAD

**Issue by MatheusSanteago** [InfiniteFlightAirportEditing/Airports#4280]
# Airport Name

< Aeroporto Estadual de Registro >

# Country?

< Brazil >

# Improvements that need to be made?

< Full Work >

# Are you working on this airport?

< No >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![Uploading image.png…]()
