### ISSUE TITLE
ZLXN-Xining/Caojiapu Airport-QINGHAI-CHINA

### ISSUE THREAD

**Issue by Ignas04** [InfiniteFlightAirportEditing/Airports#4281]
# Airport Name

< Xining Caojiabao International Airport >

# Country?

< China >

# Improvements that need to be made?

< Creation from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< GP2 (10000ft+ >

**Comment by kztmtn** [comment]
@Ignas04 Please advise us the progress of this.

**Comment by kztmtn** [comment]
Editor inactive. Will assign this to @Berlin-N .

**Comment by Berlin-N** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85349832-1a3d3f80-b4c5-11ea-8454-9f64eab8e87f.png)
