### ISSUE TITLE
CYCN-Cochrane Airport-ONTARIO-CANADA

### ISSUE THREAD

**Issue by Ignas04** [InfiniteFlightAirportEditing/Airports#4282]
# Airport Name

< Cochrane Aerodrome >

# Country?

< Canada >

# Improvements that need to be made?

< Full Redo >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kztmtn** [comment]
Member inactive, up for grabs.

**Comment by mike116119** [comment]
I will work on this airport.

**Comment by mike116119** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90322881-5a49fd00-df1f-11ea-9442-dcea0150cbcb.png)
