### ISSUE TITLE
KOFF-Offutt AFB-NEBRASKA-USA

### ISSUE THREAD

**Issue by Ignas04** [InfiniteFlightAirportEditing/Airports#4283]
♻️

**Comment by kztmtn** [comment]
Member inactive, up for grabs.

**Comment by EdCruz26** [comment]
I'll work on this.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118729684-f5983780-b7fb-11eb-9dc3-235fe2de7115.png)
