### ISSUE TITLE
KNFW-Fort Worth Naval Air Station-TEXAS-USA

### ISSUE THREAD

**Issue by mwe2187** [InfiniteFlightAirportEditing/Airports#4284]
# Airport Name

< Fort Worth Naval Air Station >

# Country?

< USA >

# Improvements that need to be made?

< Full Redo >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MajorTomMueller** [comment]
any progress @mwe2187 ?

**Comment by MajorTomMueller** [comment]
Member inactive, up for graps

**Comment by MajorTomMueller** [comment]
![KNFW-git](https://user-images.githubusercontent.com/26853210/103135211-aca9e000-46ae-11eb-8111-714ddb4ec010.png)
