### ISSUE TITLE
KFCM-Flying Cloud Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by danisrils39** [InfiniteFlightAirportEditing/Airports#4286]
# Airport Name

Flying Cloud Airport

# Country?

USA

# Improvements that need to be made?

Scratch

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

N/A

**Comment by danisrils39** [comment]
Only 6 months later off to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78702034-560d3380-78de-11ea-891c-659632c8c9c5.jpg)
