### ISSUE TITLE
NZSL-Springhill Airport-AUCKLAND-NEW ZEALAND

### ISSUE THREAD

**Issue by Lukeh0** [InfiniteFlightAirportEditing/Airports#4288]
# Airport Name

Springhill Airport

# Country?

New Zealand

# Improvements that need to be made?

Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68155165-eb6b5c80-ff27-11e9-9c03-999fb04fca4d.jpg)
