### ISSUE TITLE
LYKV-Morava Airport-Lađevci-SERBIA

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#4289]
# Airport Name

Allegheny County Airport

# Country?

USA

# Improvements that need to be made?

Full Redo

# Are you working on this airport?

Yes - Current HHR and TOA take priority however.

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MajorTomMueller** [comment]
recycled

**Comment by MajorTomMueller** [comment]
![LYKV-git](https://user-images.githubusercontent.com/26853210/67269036-6bfc7880-f4a5-11e9-8db0-7c3524f4a0e7.png)
