### ISSUE TITLE
KMSY-Louis Armstrong New Orleans International Airport-LOUISIANA-USA

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#429]
Louisiana

**Comment by JohnPreston21** [comment]
I would like to do this one.

**Comment by JohnPreston21** [comment]
Will get started finally.

**Comment by dushyants19** [comment]
Open for grabs!

**Comment by brunocr98** [comment]
Taking this airport as well.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20447157/041fca7e-ada3-11e6-94a1-38de88cdf0fe.png)

**Comment by kilt46** [comment]
Concourse A MISSING - Also Asphalt sections next to airport bulding makes airport look confusing. Would recommend removing

![image](https://user-images.githubusercontent.com/14023167/40569106-8b42ed10-6044-11e8-90fc-c82ab61a448f.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/40575881-cb1dfa60-60b2-11e8-9952-44ecb7210e6e.png)
Nice job!

**Comment by FlightGeekYuta** [comment]
There should be a compatible gate to the 787

**Comment by brunocr98** [comment]
I'm sure he took that into account :)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/65000450-0e7f7580-d8c2-11e9-82ae-b1a09f38dc32.jpg)

**Comment by MajorTomMueller** [comment]
New imagery for new terminal available on Arc.GIS.
Will you edit @HiFlyerBwi ?

**Comment by Czechoslovaki** [comment]
@MajorTomMueller ArcGis is a disaster. If you zoom in on sas some chunks will be outdated. Wouldn't recommend as a suggestion.

**Comment by MajorTomMueller** [comment]
@Czechoslovaki , then use Bing. Usually the same source as Arc.GIS with same publish date, but other better processing.
And it is not about a full rework. If @HiFlyerBwi does this he just needs to add markings to his previous work. In addition you might have notice that I have not add the suggestion label. That's by purpose. Let's take it to Sv channel in slack if you have further questions.

**Comment by Czechoslovaki** [comment]
New terminal to be added, open for grabs.

**Comment by brunocr1050** [comment]
@kilt46, be advised: the charts for this airport no longer show the gate map of the old terminal (Navigraph).

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122846204-f7598d00-d2ca-11eb-8396-202e9d6b54e0.png)
