### ISSUE TITLE
FAVG-Virginia/Durban Airport-KWAZULU-NATAL-SOUTH AFRICA

### ISSUE THREAD

**Issue by JoshTomaz** [InfiniteFlightAirportEditing/Airports#4292]
Airport Name
Virginia Airport

Country?
South Africa

Improvements that need to be made?
Rework

Are you working on this airport?
Yes

Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by brunocr98** [comment]
Any reason why you closed this? Ain't no duplicate issues for FAVG.

**Comment by osujim15** [comment]
May I redo this one?

**Comment by MajorTomMueller** [comment]
Yes

**Comment by osujim15** [comment]
Alright. Thank you.

**Comment by osujim15** [comment]
The airport has been sent in for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/73313411-e73e9a80-4209-11ea-8556-f9a32ae4ffd7.jpg)
