### ISSUE TITLE
ZSYT-Yantai/Penglai Airport-SHANDONG-CHINA

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Airports#4295]
# Airport Name

< Yantai/Penglai Airport >

# Country?

< China >

# Improvements that need to be made?

< Generated airport, do from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< 10000+ (11155ft RWY) >

**Comment by kztmtn** [comment]
Sent in for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/66598631-ce857880-eb77-11e9-92a5-46089862b241.jpg)
