### ISSUE TITLE
BIHN

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#430]
Hornafjordur Airport, Iceland

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17200221/13d7b156-5449-11e6-9c28-899e0315c883.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18536010/c3b6e3b2-7abe-11e6-8a90-7ea870de85d8.png)
