### ISSUE TITLE
RJCT-Tokachi Air Field-HOKKAIDO-JAPAN

### ISSUE THREAD

**Issue by NAZ32** [InfiniteFlightAirportEditing/Airports#4308]
♻️

**Comment by brunocr98** [comment]
This airport is already done.

**Comment by orangejuicie** [comment]
♻️

**Comment by orangejuicie** [comment]
![RJCT](https://user-images.githubusercontent.com/35187449/67164048-3a09ea00-f3b1-11e9-9a63-193456eb5a1d.jpg)
