### ISSUE TITLE
BIIS

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#431]
Isafjordur airport, Iceland

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17200265/5bda94fa-5449-11e6-9be9-799c1a27d176.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18535962/351ed092-7abe-11e6-9288-e3041642cf97.png)
