### ISSUE TITLE
81MN-Ewen Landing Field-MINNESOTA-USA

### ISSUE THREAD

**Issue by jackyboy2578** [InfiniteFlightAirportEditing/Airports#4315]
# Airport Name

< Ewen Landing Field >

# Country?

< USA >

# Improvements that need to be made?

< Realign runway and adding missing hangars >

# Are you working on this airport?

< Yes>

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/67233642-02835800-f41a-11e9-8c64-f352468d99a3.jpg)
