### ISSUE TITLE
L77-Chiriaco Summit Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#4318]
# Airport Name

Chiriaco Summit

# Country?

USA

# Improvements that need to be made?

Redo

# Are you working on this airport?

Finished

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by jakey20** [comment]
Sent to OR

**Comment by PatricioAY** [comment]
Can I do it

**Comment by brunocr98** [comment]
This airport is already assigned to someone.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/67234002-a967f400-f41a-11e9-830d-f151a1028a1a.jpg)
