### ISSUE TITLE
BIEG

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#432]
Eglisstadir airport, Iceland.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17200175/a8df3248-5448-11e6-8c8f-d331f93d6967.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18536129/e8b371fc-7abf-11e6-8407-19b00283b32a.png)
