### ISSUE TITLE
LTFG-Alanaya Gazipasa-ANTALAYA-TURKEY

### ISSUE THREAD

**Issue by JensSeverin** [InfiniteFlightAirportEditing/Airports#4320]
# Airport Name

Alanaya Gazipasa

# Country?

Turkey

# Improvements that need to be made?

Redo from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

No

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68998021-a6cab400-088b-11ea-85dc-8606d3cc6c60.jpg)
