### ISSUE TITLE
KTVF-Thief River Falls Regional Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by Gabe-Z** [InfiniteFlightAirportEditing/Airports#4321]
# Airport Name
Thief River Falls Regional Airport

# Country?

USA

# Improvements that need to be made?

Unedited airport and will be redone by me.

# Are you working on this airport?

I will work on this airport.

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by Gabe-Z** [comment]
The airport is now in review.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/72672780-857a7580-3a3e-11ea-9021-683c942203ad.jpg)
