### ISSUE TITLE
VTCC-Chiang Mai International Airport-Chiang Mai-Thailand

### ISSUE THREAD

**Issue by aads552** [InfiniteFlightAirportEditing/Airports#4322]
# Airport Name

Chiang Mai International Airport

# Country?

Thailand

# Improvements that need to be made?

from scratch

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

10000ft+ Runway

**Comment by MajorTomMueller** [comment]
FYI, ggogle imagery is weavy, use ESRI or Bing instead
https://aip.caat.or.th/2019-09-12-AIRAC/pdf/VT-AD-2.VTCC-en-GB.pdf#AD-2.VTCC
https://aip.caat.or.th/2019-09-12-AIRAC/graphics/29918.pdf
https://aip.caat.or.th/2019-09-12-AIRAC/graphics/7504.pdf
https://aip.caat.or.th/2019-09-12-AIRAC/graphics/7505.pdf
now you have all information you need except mil spawn naming.
Have fun @aads552

**Comment by aads552** [comment]
You are right, planning to use Bing. Thanks.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/67237482-ba683380-f421-11e9-84ae-82c9c26f7e18.jpg)
