### ISSUE TITLE
KSGS-Fleming Field-MINNESOTA-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#4323]
# Airport Name

Fleming Field - South St. Paul Airport

# Country?

United States (Minnesota)

# Improvements that need to be made?

Add taxilines, taxiways, and spawns not in the current airport 

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low Priority

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/72672747-c9b94600-3a3d-11ea-8713-08e210c3dde5.jpg)
