### ISSUE TITLE
PANC-Ted Stevens Anchorage Airport-ALASKA-USA

### ISSUE THREAD

**Issue by henrikbg** [InfiniteFlightAirportEditing/Airports#433]
Ted Stevens Anchorage International Airport.

**Comment by JcFl4** [comment]
I'm planning on doing some Alaskan airports too, so great!

**Comment by samuelandersson** [comment]
@henrikbg Did you finish this eventually?

**Comment by henrikbg** [comment]
It's still in progress. I haven't had the time recently. I'll try to finish it this weekend.

**Comment by samuelandersson** [comment]
Okay cool.

**Comment by NickArt1342** [comment]
Was this completed?

**Comment by dushyants19** [comment]
Not completed, Nick.

**Comment by dushyants19** [comment]
And henrik, please add proper labels. (Suggestion)

**Comment by brunocr98** [comment]
I can do this airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20330016/6d7a843a-ab61-11e6-8924-6c900f832470.png)

**Comment by MajorTomMueller** [comment]
For reference:
http://www.dot.state.ak.us/anc/about/docs/Appendix%20K_Airport%20Layout%20Plan_Final.pdf

**Comment by brunocr1050** [comment]
Bringing this airport to current standards.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105580766-efb1ae80-5d53-11eb-8015-51385310a850.png)
