### ISSUE TITLE
NWWD-Kone Airport-NORD-NEW CALEDONIA

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#4338]
# Airport Name

Kone

# Country?

New Caledonia / France

# Improvements that need to be made?

Rework

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

IF Event

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/67236652-13cf6300-f420-11e9-9776-3755a218dae5.jpg)
