### ISSUE TITLE
YPAM-Palm Island Airport-QUEENSLAND-AUSTRALIA

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#4339]
# Airport Name

Palm Island

# Country?

Australia

# Improvements that need to be made?

Redo

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

IF Event

**Comment by moritzbabl** [comment]
@jackyboy2578 whats the progress on this? You missed the deadline for October

**Comment by jackyboy2578** [comment]
It has been sent for review, sorry for the delay

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/69681944-7f939400-108e-11ea-8955-82a02f5a9c8e.jpg)
