### ISSUE TITLE
TNCM

### ISSUE THREAD

**Issue by freddiefrogs** [InfiniteFlightAirportEditing/Airports#434]
Airport boundary has been increased too much.

**Comment by dushyants19** [comment]
Search before posting, like the forum. 
https://github.com/InfiniteFlightAirportEditing/Airports/issues/21

**Comment by Will171** [comment]
It's in the carabean region how can it be non region?

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20649924/f9f5a3ea-b48f-11e6-8f0a-6b900081c2f0.png)
