### ISSUE TITLE
NWWM-Noumea Magenta Airport-SUD-NEW CALEDONIA

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#4340]
# Airport Name

Nouméa Magenta

# Country?

New Caledonia / France

# Improvements that need to be made?

Rework

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

IF Event

**Comment by kztmtn** [comment]
Sent in for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/67237107-f8188c80-f420-11e9-8bd6-688763172b9e.jpg)
