### ISSUE TITLE
SJDS-Fabrica Fortaleza Airport-CEARA-BRAZIL

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Airports#4349]
# Airport Name

< Fabrica Fortaleza >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by FellipeEdu** [comment]
Sent to OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/66596928-35a12e00-eb74-11e9-9c1a-d11312a33b40.jpg)
