### ISSUE TITLE
BIBD

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#435]
Bildudalur airport, Iceland

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17199242/1223507a-5441-11e6-836b-5ffedb8ef4d6.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17200165/88d19630-5448-11e6-8cfb-c5244cae503f.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18536322/019a47a2-7ac2-11e6-9e34-20bebbb43732.png)
