### ISSUE TITLE
SBML-Marilia Airport-SAO PAULO-BRAZIL

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Airports#4351]
# Airport Name

< Marilia Airport >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by FellipeEdu** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/73315984-6d5ddf80-4210-11ea-9b8a-fb37ccfe7900.jpg)
