### ISSUE TITLE
SCAN-San Rafael Airport-VALPARAISO-CHILE

### ISSUE THREAD

**Issue by vichols1506** [InfiniteFlightAirportEditing/Airports#4354]
# Airport Name

< SCAN>

# Country?

< CHILE >

# Improvements that need to be made?

< TAXIWAYS AND PARKING >

# Are you working on this airport?

< YES>

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< LOW>

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/82395841-c30a0200-9a22-11ea-9863-cb36df029625.jpg)
