### ISSUE TITLE
E41-Reagan County Airport-TEXAS-USA

### ISSUE THREAD

**Issue by TheOtherOnesMika** [InfiniteFlightAirportEditing/Airports#4355]
![image](https://user-images.githubusercontent.com/14023167/97756469-ebfdeb00-1ac8-11eb-80fb-180eb8c163ec.png)

**Comment by MajorTomMueller** [comment]
@TheOtherOnesMika there are no “minor” reworks for airports that have not an issue so far.
ESGE was unedited/autogen until now, either you do a full rework or you leave it. With minor changes to the autogen you will never pass reviews...
