### ISSUE TITLE
SDRS-Resende Airport-RIO DE JANEIRO-BRAZIL 

### ISSUE THREAD

**Issue by MatheusSanteago** [InfiniteFlightAirportEditing/Airports#4356]
# Airport Name
Resende Airport

# Country?

Brazil

# Improvements that need to be made?

Full Work

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by carloszferreira** [comment]
Hello people. The person who opened this issue is unable to edit. As a result, she asked me to continue editing this airport. I come to ask you to assign this issue to me, so that I can finish editing my friend.

**Comment by MBeringuy** [comment]
@carloszferreira this issue has been attributed to you. Have a good edit.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107856885-e8c90980-6df0-11eb-8c33-1af92389ab17.png)
