### ISSUE TITLE
BGKK

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#436]
Kulusuk, Greenland.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17198905/8d5c6022-543e-11e6-831a-a5a16006aa77.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18419069/065ed9ca-7819-11e6-9a00-86c0f3f4bfe0.png)
