### ISSUE TITLE
SIQQ-Jose Bernardo Airport-RIO DE JANEIRO-BRAZIL

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Airports#4363]
# Airport Name

< Jose Bernardo >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/71047476-8441ea00-211a-11ea-8dc8-d23990a2fe11.jpg)
