### ISSUE TITLE
SDAI-Americana Airport-SAO PAULO-BRAZIL 

### ISSUE THREAD

**Issue by victormw22** [InfiniteFlightAirportEditing/Airports#4364]
# Airport Name
 
< Americana >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< low >

**Comment by victormw22** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/77349612-0a715c00-6d1a-11ea-8b57-556444939871.jpg)
