### ISSUE TITLE
LIAP-L'Aquila/Parchi Airport-ABRUZZO-ITALY

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#4365]
# Airport Name

L'Aquila-Parchi "Giuliana Tamburro"

# Country?

Italy.

# Improvements that need to be made?

Redo from scratch.

# Are you working on this airport?

Yes.

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

N/A

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/67148595-7c2f1080-f277-11e9-93c8-85bdd783c570.jpg)
