### ISSUE TITLE
KAVX-Catalina Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#4366]
# Airport Name

Catalina 

# Country?

USA

# Improvements that need to be made?

Redo

# Are you working on this airport?

Finished

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by jakey20** [comment]
Sent to PR

**Comment by jakey20** [comment]
Why was I unassigned

**Comment by brunocr98** [comment]
You're no longer welcomed in IFC, so you're also removed from the editing team.

**Comment by DerpCakeFlies** [comment]
Hi, can I be assigned to redo this airport?

**Comment by jakey20** [comment]
Hey, if you want the file I already did I’ll share it with you.

**Comment by DerpCakeFlies** [comment]
Yes please, thanks

**Comment by jakey20** [comment]
Ok. I’ll get it to you soon. Might be tomorrow.

**Comment by jakey20** [comment]
That's the apt.dat. Just put it into a text file and make the file a .dat file and load it up to WED. Everything should already be done.
https://pastebin.com/ZDN0mLLh

**Comment by DerpCakeFlies** [comment]
Tks

**Comment by jakey200** [comment]
official review time

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78695850-0a09c100-78d5-11ea-8ad1-44d519ad31b2.jpg)
