### ISSUE TITLE
BIVM

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#437]
Vestmannaeyjar airport, Iceland

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17208872/0a8123b2-5480-11e6-9380-a4c8e0c79ee5.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17232097/6b261b26-54eb-11e6-8c7e-08957f677615.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18421695/e40512b2-7855-11e6-9c15-9ec83bb0713e.png)
