### ISSUE TITLE
KUCP-New Castle Municipal Airport-PENNSYLVANIA-USA

### ISSUE THREAD

**Issue by IFC-PlaneCrazy** [InfiniteFlightAirportEditing/Airports#4371]
# Airport Name

New Castle Municipal Airport

# Country?

USA

# Improvements that need to be made?

Will be redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by IFC-PlaneCrazy** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/71787752-61f50b00-2ffa-11ea-9974-cd306e910596.jpg)
