### ISSUE TITLE
YSHK-Shark Bay Airport-WESTERN AUSTRALIA-AUSTRALIA

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#4373]
# Airport Name

Shark Bay

# Country?

Australia

# Improvements that need to be made?

Full rework

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

IF Event

**Comment by HiFlyerBwi** [comment]
Submitted for OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68154826-26b95b80-ff27-11e9-875e-3b0809c5ff42.jpg)
