### ISSUE TITLE
YCAR-Carnarvon-WESTERN AUSTRALIA-AUSTRALIA

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#4374]
# Airport Name

Carnarvon

# Country?

Australia

# Improvements that need to be made?

Full rework

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

IF Event

**Comment by Gabe-Z** [comment]
Sent for OR. :)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/69681762-d6e53480-108d-11ea-8ddf-8f5ebe4ffd9c.jpg)
