### ISSUE TITLE
BIVO

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#438]
Vopnafjordur airport, Iceland.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17208930/5c8110c8-5480-11e6-8e8d-9c870787e557.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18421729/a2008292-7856-11e6-806b-c469d1375641.png)
