### ISSUE TITLE
LIAU-Capua Airport-CAMPANIA-ITALY

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#4384]
# Airport Name

Capua Airport

# Country?

Italy

# Improvements that need to be made?

Redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

N/A

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68034602-c0230c00-fca0-11e9-98fc-ec3344e5034e.jpg)
