### ISSUE TITLE
LIRI-Salerno/Pontecagnano Airport-CAMPANIA-ITALY

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#4385]
# Airport Name

Salerno/Pontecagnano Airport

# Country?

Italy

# Improvements that need to be made?

Redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

N/A

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68035038-961e1980-fca1-11e9-868d-77099277d544.jpg)
