### ISSUE TITLE
LIRO-Benevento Airport-CAMPANIA-ITALY

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#4386]
# Airport Name

Benevento

# Country?

Italy

# Improvements that need to be made?

Redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

N/A

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68035702-e8ac0580-fca2-11e9-9e39-b5b39258d6a5.jpg)
