### ISSUE TITLE
WAHI-Yogyakarta International Airport-YOGAKARTA-INDONESIA

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#4387]
# Airport Name

Yogyakarta International Airport

# Country?

Indonesia

# Improvements that need to be made?

new

# Are you working on this airport?

not emediatly, if someone is interrested feel free to get assigned, othervise I will care later

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

+10k

**Comment by MajorTomMueller** [comment]
Charts available, Images sufficient

**Comment by JoshTomaz** [comment]
Could I take this up?

**Comment by MajorTomMueller** [comment]
https://github.com/InfiniteFlightAirportEditing/Airports/commit/efd4a388c40e16ca9bad2a35c714cae3ea3ff840

![WAHI-git](https://user-images.githubusercontent.com/26853210/68460507-f6600e80-01ff-11ea-8ae5-b76b55a7d111.png)
