### ISSUE TITLE
SWRP-Aripuana Airport-MATO GROSSO-BRAZIL

### ISSUE THREAD

**Issue by victormw22** [InfiniteFlightAirportEditing/Airports#4388]
# Airport Name

< Aripuana Airport >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch  >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by victormw22** [comment]
sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/77350056-b87d0600-6d1a-11ea-9435-e96478fdb833.jpg)
