### ISSUE TITLE
LFSB

### ISSUE THREAD

**Issue by antbelldev** [InfiniteFlightAirportEditing/Airports#439]
EuroAirport Basel-Mulhouse

**Comment by antbelldev** [comment]
Waiting for peer-review.

**Comment by dushyants19** [comment]
@antbelldev any progress?

**Comment by dushyants19** [comment]
up for grabs

**Comment by bavAVIA** [comment]
Taking this before anyone else does :eyes:

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25299921/8c0a4efa-26ca-11e7-9e09-0b948a46ec69.png)
