### ISSUE TITLE
1U7-Bear Lake County Airport-IDAHO-USA

### ISSUE THREAD

**Issue by KimballWhite** [InfiniteFlightAirportEditing/Airports#4392]
# Airport Name

Bear Lake County Airport

# Country?

United States of America

# Improvements that need to be made?

Will be redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

N/A

**Comment by KimballWhite** [comment]
Airport has been submitted for approval.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68997564-aaa80780-0886-11ea-8b03-8d45fec81367.jpg)
