### ISSUE TITLE
VAOZ-Ozar Airport-MAHARASHTRA-INDIA

### ISSUE THREAD

**Issue by N365FE** [InfiniteFlightAirportEditing/Airports#4393]
# Airport Name

<Nashik Airport (VAOZ) >

# Country?

< India >

# Improvements that need to be made?

< Entirely Rework, also the current name VA35 is incorrect, should be VAOZ>

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low>

**Comment by buttattatt** [comment]
I would like to rework this airport

**Comment by Czechoslovaki** [comment]
Good Luck.

**Comment by buttattatt** [comment]
I mapped the airport and created a good template, all that needs to be done is spawns , ATC, beacon lights, airport lights, touch up's to my taxi lines etc, but most of it's done, I'm just [not](url) experienced enough to do some of the other stuff as this is my first airport
[VAOZ Template.zip](https://github.com/InfiniteFlightAirportEditing/Airports/files/5610156/VAOZ.Template.zip)

**Comment by MajorTomMueller** [comment]
This is not the way we are doing this. Go Ahead and finsh yourself, you have to learn those things anyway.

**Comment by buttattatt** [comment]
thank you for the tip

**Comment by hari-shreyas** [comment]
Hello!
Could a sup assign me to this airport? Will edit this airport.

Thanks!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123524243-7a456380-d68e-11eb-8280-edbd9f929b2a.png)
