### ISSUE TITLE
LIDE-Reggio Emilia Airport-EMILIA-ROMAGNA-ITALY

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#4395]
# Airport Name

Reggio Emilia

# Country?

Italy

# Improvements that need to be made?

Redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

N/A

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68074963-58dc8900-fd80-11e9-89c3-497cf06526a8.jpg)
