### ISSUE TITLE
LIDG-Lugo Di Romagna Airport-EMILIA-ROMAGNA-ITALY

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#4396]
# Airport Name

Lugo Di Romagna Airport

# Country?

Italy

# Improvements that need to be made?

Redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

N/A

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68075013-21baa780-fd81-11e9-8cd9-1e8d9469d3c3.jpg)
