### ISSUE TITLE
ENRY-Moss Rygge Airport-ØSTFOLD-NORWAY

### ISSUE THREAD

**Issue by Developer-33** [InfiniteFlightAirportEditing/Airports#4397]
# Airport name?

Rygge Airport

# Country?

 Norway

# Improvements that need to be made?

Need to be made in the game

# Are you working on this airport?

No (I am not availble to use Airport Editor on my PC)

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MajorTomMueller** [comment]
This is a joke, one of the tiniest grass stripes I have seen, not listed in official aerodrome list, and you are not able to do it your self?
This is not a wish list, recycled to something more usefull.

**Comment by MajorTomMueller** [comment]
https://ais.avinor.no/no/AIP/View/65/aip/ad/enry/EN_AD_2_ENRY_en.pdf
https://ais.avinor.no/no/AIP/View/65/aip/ad/enry/EN_AD_2_ENRY_2-1_en.pdf

**Comment by Developer-33** [comment]
ENRY is another Nice Airport ro be redone.
Why a change on the title?

**Comment by MajorTomMueller** [comment]
_This is not a wish List._ 
ENRY is a licenced Airport with AIP documents sceduled service and so on.
ENUL is a piece of Grass the wasn't even mentioned in the Aerodrome index by Avinor.
Either you want to contribute with your own work, or you didn't touch this repository and its issue list.

**Comment by Developer-33** [comment]
Can Rygge be like it is now on?

**Comment by MajorTomMueller** [comment]
https://github.com/InfiniteFlightAirportEditing/Airports/commit/31c2c2627bc7cc8366ceea6d69823c8337adeb6f
![ENRY-Git](https://user-images.githubusercontent.com/26853210/75623477-3c235700-5ba2-11ea-975a-b579265fb39d.png)
