### ISSUE TITLE
LIDR-Ravenna Airport-EMILIA-ROMAGNA-ITALY

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#4398]
# Airport Name

Ravenna Airport

# Country?

Italy

# Improvements that need to be made?

Redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

N/A

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68075190-2c763c00-fd83-11e9-8675-f07d902fab7a.jpg)
