### ISSUE TITLE
LIDU-Carpi/Budrione Airport-EMILIA-ROMAGNA-ITALY

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#4399]
# Airport Name

Carpi/Budrione Airport

# Country?

Italy

# Improvements that need to be made?

Redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

N/A

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68075442-b70c6a80-fd86-11e9-8465-68760f33301e.jpg)
