### ISSUE TITLE
LHKH

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#44]

**Comment by IFAEpat** [comment]
Kiskunfélegyháza Airport

**Comment by IFAEpat** [comment]
done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17209362/4c33fab2-5482-11e6-8384-3fd770f14326.png)

**Comment by IFAEpat** [comment]
Gated

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17684349/7850c8e4-6320-11e6-80b0-551559a56eb8.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17684355/7febae20-6320-11e6-909b-f6074674e573.png)
