### ISSUE TITLE
PLCH-Christmas Island/Cassidy International Airport-CHRISTMAS ISLAND-KIRIBATI

### ISSUE THREAD

**Issue by freddiefrogs** [InfiniteFlightAirportEditing/Airports#440]
Cassidy Intl, Kiribati

**Comment by JcFl4** [comment]
Why did you chose this remote airport? And how did you find it? Hahaha

**Comment by freddiefrogs** [comment]
@JcFl4 I found it by looking at a map of the South Pacific.

**Comment by JcFl4** [comment]
I see... I was just wondering, it's so far into the Pacific!

**Comment by kilt46** [comment]
This airport is NOT in the REPO

**Comment by AxelBeder** [comment]
@freddiefrogs are you still redoing this?

**Comment by freddiefrogs** [comment]
No. It's basically defunct in real life... No terminal, taxiways or airlines. It wasn't accepted due to that, even though it's like that in real life.

**Comment by dushyants19** [comment]
@freddiefrogs what are you going to do now?

**Comment by dushyants19** [comment]
up for grabs

**Comment by dushyants19** [comment]
done

**Comment by dushyants19** [comment]
i have no idea what this airport is. its named international tho

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20504858/46c9b024-b00f-11e6-927b-533764d08f60.png)

**Comment by brennanhackard** [comment]
@dklaffke will be making the following improvements to this airport:

- major taxiway work (fixing illegal geometry, making materials accurate, and removing taxiways not present in imagery or charts)
- spawn fixes (adding hangar and apron spawns, resizing terminal spawns)
- moving the boundary to where it is IRL
- fixing runway dimensions

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111982048-7aa1f180-8ad6-11eb-88c4-bd827aa08c6c.png)
