### ISSUE TITLE
LIDV-Prati Vecchi d'Aguscello Airport-EMILIA-ROMAGNA

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#4400]
# Airport Name

Prati Vecchi d'Aguscello Airport

# Country?

Italy

# Improvements that need to be made?

Redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

N/A

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68151509-9ed05300-ff20-11e9-8078-0a61f4a851b0.jpg)
