### ISSUE TITLE
DUPLICATE

### ISSUE THREAD

**Issue by Sacred-Lotus** [InfiniteFlightAirportEditing/Airports#4405]
# Airport Name

Gold Coast International Airport

# Country?

Australia

# Improvements that need to be made?

Taxiway C (between A and D https://www.crc.id.au/xplane/charts/DAPS-2019-AUG-15/Gold%20Coast%20(YBCG).pdf )

# Are you working on this airport?

No, I have never done this before

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by brunocr98** [comment]
#691

**Comment by moritzbabl** [comment]
FY03 quickly redone

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68349180-003c2180-00db-11ea-833c-9f2402715365.jpg)
