### ISSUE TITLE
LIRG-Aeroporto di Guidonia-LAZIO-ITALY

### ISSUE THREAD

**Issue by NAZ32** [InfiniteFlightAirportEditing/Airports#4407]
♻️

**Comment by brunocr98** [comment]
#4132

**Comment by brunocr98** [comment]
If you want to be assigned to the mentioned issue, please request an invite to join our Github site. You're not a member and therefore I can't assign you.

**Comment by MajorTomMueller** [comment]
recycled

**Comment by MajorTomMueller** [comment]
https://github.com/InfiniteFlightAirportEditing/Airports/commit/759b26d50918b42b80188801cebd34c22dc4a8b4

![LIPI-git](https://user-images.githubusercontent.com/26853210/68542887-71642900-03a8-11ea-8572-398d6410325b.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68905848-4c154900-0721-11ea-8ab6-f29083fb1293.jpg)
