### ISSUE TITLE
KPIL-Port Isabel-Cameron County Airport-TEXAS-USA

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#4412]
# Airport Name

Port Isabel Cameron County Airport

# Country?

USA

# Improvements that need to be made?

A scratch rework

# Are you working on this airport?

Yup

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

None, its pretty boring

**Comment by HiFlyerBwi** [comment]
Submitted this bad boy for OR :slowerthanbruno:

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/69681530-21b27c80-108d-11ea-8c13-584ad5a5396e.jpg)
