### ISSUE TITLE
KCBG-Cambridge Municipal Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#4413]
# Airport Name

Cambridge Municipal Airport

# Country?

USA

# Improvements that need to be made?

Add taxiways, hangars and spawns

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low Priority

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/71047922-1eeef880-211c-11ea-84d4-df562a26a09b.jpg)
