### ISSUE TITLE
 U07-Bullfrog Basin Airport-UTAH-USA

### ISSUE THREAD

**Issue by KimballWhite** [InfiniteFlightAirportEditing/Airports#4414]
# Airport Name

Bullfrog Basin Airport

# Country?

United States of America

# Improvements that need to be made?

Full rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

N/A

**Comment by KimballWhite** [comment]
Airport has been submitted for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/71048708-e7358000-211e-11ea-8734-4d3d96fe465d.jpg)
