### ISSUE TITLE
3T5-Fayette Regional Air Center-TEXAS-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#4415]
# Airport Name

Fayette Regional Air Center

# Country?

United States of America

# Improvements that need to be made?

Redone from scratch.

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/71448241-434c6580-2718-11ea-8e4d-63ebc23430a0.jpg)
