### ISSUE TITLE
MP25-Puerto Armuelles Airport-CHIRIQUI-PANAMA

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#442]
♻️

**Comment by Aviationluver** [comment]
I can re-do this one.

**Comment by Aviationluver** [comment]
Sent this one off to be reviewed.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17236900/70c7253a-5512-11e6-9b29-ff3cf07cc9eb.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17236945/ac979e00-5512-11e6-973e-e397c723083b.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17245527/7b880fea-554c-11e6-8a1b-dd2fa52ddc0a.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18418461/8b892dba-780c-11e6-877f-51c724dc6151.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18418468/b8e9e9ac-780c-11e6-9d61-dd873add79a3.png)

**Comment by brunocr98** [comment]
<img width="315" alt="Cattura" src="https://user-images.githubusercontent.com/22130457/63101977-d0e4a100-bf3f-11e9-9382-9cdfcdff53a6.PNG">

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112721703-6f363800-8ed3-11eb-9f87-86386eed7b7b.png)
