### ISSUE TITLE
EGHJ

### ISSUE THREAD

**Issue by freddiefrogs** [InfiniteFlightAirportEditing/Airports#443]
Bembridge, London

**Comment by freddiefrogs** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17250943/277f2238-556c-11e6-9b71-603988509848.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18259961/43192c62-73af-11e6-86a7-9069d9693ef7.png)
