### ISSUE TITLE
XA08-Los Cuernos Ranch-TEXAS-USA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#4431]
![image](https://user-images.githubusercontent.com/14023167/100452782-6f3a3e80-307f-11eb-8fc6-aa07142cf7b8.png)

**Comment by MajorTomMueller** [comment]
FYI @Daniel-Baiks 
Tunis AIP incl text data for DTTX
http://www.oaca.nat.tn/index.php?id=751&L=2
Aerodrome chart
http://www.oaca.nat.tn/fileadmin/docs/DCCRSIA.Doc/AIP/Aerodromes/DTTX/AD2_DTTX_14.pdf
Runway Coordinates
http://www.oaca.nat.tn/fileadmin/docs/DCCRSIA.Doc/AIP/Aerodromes/DTTX/AD2_DTTX_6.pdf
Docking Chrart
http://www.oaca.nat.tn/fileadmin/docs/DCCRSIA.Doc/AIP/Aerodromes/DTTX/AD2_DTTX_15.pdf
Stand Coordinates:
https://www.oaca.nat.tn/fileadmin/docs/DCCRSIA.Doc/AIP/Aerodromes/DTTX/AD2_DTTX_15a.pdf
