### ISSUE TITLE
CYPQ-Peterborough Municipal Airport-ONTARIO-CANADA

### ISSUE THREAD

**Issue by kylejtam** [InfiniteFlightAirportEditing/Airports#4432]
# Airport Name

Peterborough Municipal Airport

# Country?

Canada

# Improvements that need to be made?

Starting from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kylejtam** [comment]
Sent for Approval

**Comment by kylejtam** [comment]
Sent for official review #2

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/72672502-ca4fdd80-3a39-11ea-8ea1-d639267037ed.jpg)
