### ISSUE TITLE
LILR-Cremona-Migliaro Airport-LOMBARDIA-ITALY

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Airports#4433]

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68997026-8ea16780-0880-11ea-82c1-46e56ce0668d.jpg)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68997056-d7592080-0880-11ea-971a-1caae4e1fd30.jpg)
