### ISSUE TITLE
KMKT-Mankato Regional Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#4435]
# Airport Name

Mankato Regional Airport

# Country?

USA

# Improvements that need to be made?

Scratch Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low Priority

**Comment by MajorTomMueller** [comment]
@Czechoslovaki you have reached your 3 issues limit. Please wait till one of your previous issues passed OR and get closed to get assigned to this one.

**Comment by Czechoslovaki** [comment]
@MajorTomMueller may I be assigned now? I only have two issues currently.

**Comment by MajorTomMueller** [comment]
Done

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/71788005-21e35780-2ffd-11ea-874a-b2e865fd73c6.jpg)
