### ISSUE TITLE
EDCD-Flugplatz Cottbus-Drewitz-BRANDENBURG-GERMANY

### ISSUE THREAD

**Issue by rich-art-02** [InfiniteFlightAirportEditing/Airports#4436]
# Airport Name

Flugplatz Cottbus-Drewitz

# Country?

Germany

# Improvements that need to be made?

Rework from scratch
# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by rich-art-02** [comment]
Sent in to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/75722917-efcb3a80-5cb9-11ea-93c6-4f6d7988cd6c.jpg)
