### ISSUE TITLE
CYOO-Oshawa Executive Airport-ONTARIO-CANADA

### ISSUE THREAD

**Issue by kylejtam** [InfiniteFlightAirportEditing/Airports#4438]
# Airport Name

Oshawa Executive Airport

# Country?

Canada

# Improvements that need to be made?

Starting from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kztmtn** [comment]
@kylejtam How is the progress of this?

**Comment by kylejtam** [comment]
I have been quite busy recently due to schoolwork. If someone else wants this airport, you can reassign it. Otherwise, I'll probably restart my work on it during the summer.

**Comment by kztmtn** [comment]
![CYOO-git](https://user-images.githubusercontent.com/46369763/78918061-c7a9d500-7aca-11ea-80e2-b15571e109a7.jpg)
