### ISSUE TITLE
KBDR-Sikorsky Memorial Airport-CONNECTICUT-USA

### ISSUE THREAD

**Issue by dushyants19** [InfiniteFlightAirportEditing/Airports#444]
New York. Many taxiways. No lines, Needs rework

**Comment by freddiefrogs** [comment]
Done

**Comment by kilt46** [comment]
NO NEW LIBRARY FILE. STILL NEEDS REWORKED
![image](https://cloud.githubusercontent.com/assets/14023167/14771928/261b9976-0a5d-11e6-84b3-427bb472debf.png)

**Comment by freddiefrogs** [comment]
@kilt46 , all the ones that I have assigned myself for, I have done. This is no exception, it just hasn't been reviewed and is in a queue I guess.

**Comment by dushyants19** [comment]
@freddiefrogs whats the status on this?

**Comment by freddiefrogs** [comment]
@dushyants19 , I have sent it off via email - nothing back.

**Comment by freddiefrogs** [comment]
Can be closed, completely done. @kilt46 is handling it. ( @dushyants19 )

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20610858/978e0afc-b265-11e6-874c-ddfd708f2938.png)

**Comment by CptNathanHope** [comment]
Part of [Project New England](https://community.infinite-flight.com/t/project-new-england/43169).

Out with the old, in with the new.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36341229-dcd416e4-13b0-11e8-9cb7-256e74492fc8.png)

**Comment by kilt46** [comment]
Looks like Apron A is showing as transparent!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36355599-472cc284-14ab-11e8-9c29-1d70b4c348c9.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52540393-927ee700-2d4e-11e9-86e0-327e4a9440dc.png)

**Comment by kilt46** [comment]
REMOVE DUPLICATE   SPAWNS | BUILDINGS REMOVED
-- | --
