### ISSUE TITLE
HSPN-Port Sudan Airport-RED SEA STATE-SUDAN

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#4441]
# Airport Name

Port Sudan Airport

# Country?

Sudan

# Improvements that need to be made?

Addition to a ramp

# Are you working on this airport?

All is mine.

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/89713399-196d4980-d95d-11ea-907b-47aceef73a8c.png)
