### ISSUE TITLE
ZYCC-Changchun Longjia Airport-JILIN-CHINA

### ISSUE THREAD

**Issue by CrisYe** [InfiniteFlightAirportEditing/Airports#4442]
# Airport Name

Changchun Longjia International Airport

# Country?
China

# Improvements that need to be made?

Improvement

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

A 10000ft+Runway.

**Comment by brunocr98** [comment]
Since this is a very big airport for a beginner, I wouldn't assign you to it. Please reconsider your choices, we'd recommend newcomers to start with small airports.

**Comment by AnthonyCK** [comment]
Can anyone assign this issue to me? I'm working on it.

**Comment by AnthonyCK** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/77344280-b4001f80-6d11-11ea-90a3-3f7b01c0568d.jpg)
