### ISSUE TITLE
KWRI-McGuire AFB-NEW JERSEY-USA

### ISSUE THREAD

**Issue by dushyants19** [InfiniteFlightAirportEditing/Airports#445]
New York. No Taxilines

**Comment by sudafly** [comment]
ok i add taxilines

**Comment by Swang007** [comment]
@sudafly status update on this airport?

**Comment by sudafly** [comment]
@Swang007 I only have to do small things

**Comment by sudafly** [comment]
Hi guys,

I have a problem:-(

My dad has reset our mac without a backup. So i lost all my work :-1: :-((

I have to download all things again. I also lost this airport, it was so much work.

**Comment by dushyants19** [comment]
Can you continue? @sudafly

**Comment by sudafly** [comment]
I now creating airports of Suriname and Guyana, so i'm busy. Maby if i done with This region.
Sorry if my english is bad, i used GoogleTranslate

**Comment by IFAEpilot8** [comment]
If there still is no taxi lines I might do this airport. If that is okay.

**Comment by samuelandersson** [comment]
@IFAEpilot8 Any progress on this airport?

**Comment by IFAEpilot8** [comment]
I am not doing this airport anymore.

**Comment by DS2001** [comment]
I want to do this airport :)

**Comment by dushyants19** [comment]
You are doing this!

**Comment by TristinWoolf** [comment]
@dushyants19 Got the story on this? It automatically unassigned @DS2001 when I didn't even intend to, but now I can't re assign him. Should this be put back up for grabs?

**Comment by TristinWoolf** [comment]
Up for grabs! :)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26280088/c777978a-3d8c-11e7-8823-d7e404f643bb.png)
