### ISSUE TITLE
LIBN-Galatina Airbase-PUGLIA-ITALY

### ISSUE THREAD

**Issue by sentikum** [InfiniteFlightAirportEditing/Airports#4452]
♻️

**Comment by RyanEpps** [comment]
Nope

**Comment by MajorTomMueller** [comment]
recycled

**Comment by MajorTomMueller** [comment]
https://github.com/InfiniteFlightAirportEditing/Airports/commit/e1f012664547948c6fddc259da7c7c26c7dfd36f

![LIBN-git](https://user-images.githubusercontent.com/26853210/69553715-863fdf80-0f98-11ea-82ae-64b337e82ef5.png)
