### ISSUE TITLE
KMCX-White County Airport-INDIANA-USA

### ISSUE THREAD

**Issue by JoshTomaz** [InfiniteFlightAirportEditing/Airports#4454]
# Airport Name

White County Airport

# Country?

USA

# Improvements that need to be made?

Rework

# Are you working on this airport?

Yes, suggested given by Ryan Epps

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/71448096-2020b680-2716-11ea-822d-42ce59834a6e.jpg)
