### ISSUE TITLE
OIII-Tehran Mehrabad International Airport-TEHRAN-IRAN

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#4457]
# Airport Name

Tehran Mehrabad International Airport

# Country?

Iran

# Improvements that need to be made?

Redone from scratch. 

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

World/US Capital, 10000ft+ Runway

**Comment by brennanhackard** [comment]
Can I be unassigned? Imagery isn't accurate compared to charts.

**Comment by brennanhackard** [comment]
Can I be reassigned? Imagery is now current.

**Comment by brennanhackard** [comment]
?

**Comment by MajorTomMueller** [comment]
Sorry for the delay

**Comment by brennanhackard** [comment]
Sent to OR :D

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/82475756-5c78f880-9aa3-11ea-8e2a-4a7f17e62514.jpg)
