### ISSUE TITLE
KCDH-Harrel Field-ARKANSAS-USA

### ISSUE THREAD

**Issue by JoshTomaz** [InfiniteFlightAirportEditing/Airports#4458]
# Airport Name

< Harrel Field Airport >

# Country?

< USA >

# Improvements that need to be made?

< Full Rework >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by JoshTomaz** [comment]
Sent in for review.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/71047727-822c5b00-211b-11ea-95fd-0a83eb97c4b2.jpg)
