### ISSUE TITLE
LIPU-Padua Airport-VENETO-ITALY

### ISSUE THREAD

**Issue by JoshTomaz** [InfiniteFlightAirportEditing/Airports#4461]
♻️

**Comment by JoshTomaz** [comment]
Abandoned, Imagery is bad, leave as suggestion.

**Comment by MajorTomMueller** [comment]
recycled

**Comment by MajorTomMueller** [comment]
![LIPU-git](https://user-images.githubusercontent.com/26853210/69787350-41909000-11b4-11ea-8fdc-8ceb50e0064f.png)
