### ISSUE TITLE
KMHK-Manhattan Regional-KANSAS-USA

### ISSUE THREAD

**Issue by JoshTomaz** [InfiniteFlightAirportEditing/Airports#4462]
# Airport Name

< Manhattan Regional >

# Country?

< USA >

# Improvements that need to be made?

< Rework >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by brunocr98** [comment]
It looks like you have other 3 airports assigned already. I'll un-assign you to this one, complete one of the 3 you have and then we'll re-assign you to this one.

**Comment by JoshTomaz** [comment]
Could someone unassign me from this? I keep on getting a corrupt file message whenever I try open it...

**Comment by zacky89315** [comment]
I want to take over this airport.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/92327199-956eb600-f01d-11ea-88c0-135abbb24c2b.png)
