### ISSUE TITLE
E16-San Martin Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by IFC-PlaneCrazy** [InfiniteFlightAirportEditing/Airports#4465]
# Airport Name

San Martin Airport

# Country?

USA

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by IFC-PlaneCrazy** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/71448181-6cb8c180-2717-11ea-8998-ac710a5b73d4.jpg)
