### ISSUE TITLE
ENRK-Rakkestad Airport-OSTFOLD-NORWAY

### ISSUE THREAD

**Issue by Daniboi737** [InfiniteFlightAirportEditing/Airports#4466]
# Airport Name

Rakkestad, Åstrop

# Country?

Norway

# Improvements that need to be made?

Redone from Scratch

# Are you working on this airport?

YES

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by Daniboi737** [comment]
Aproved by OR

![0719B4F9-8796-48FB-9DE9-27EA49E50DB6](https://user-images.githubusercontent.com/45124789/82118136-71891b00-9775-11ea-8902-9052d00cc268.jpeg)

![4B033C8A-80A7-4491-850A-75EAFE04757E](https://user-images.githubusercontent.com/45124789/82118146-7c43b000-9775-11ea-86f3-9d7fbfe528b2.jpeg)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85926237-9dfb8100-b863-11ea-963b-66b8326da5b3.png)
