### ISSUE TITLE
EKCH-Copenhagen Airport-HOVEDSTADEN-DENMARK

### ISSUE THREAD

**Issue by ItsW1ll** [InfiniteFlightAirportEditing/Airports#447]
Kastrup Copenhagen

**Comment by kilt46** [comment]
RECYCLED ISSUE FOR COPENHAGEN

**Comment by Anfinn** [comment]
I can do this.

**Comment by NickArt1342** [comment]
@Anfinn How is the status on this?

**Comment by samuelandersson** [comment]
Taking this, as we see no action from Anfinn.

**Comment by samuelandersson** [comment]
Redone.

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/ebe864cc9fc221a3c857332f06c395d3b9fdd50d)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17248336/7b433ca4-555f-11e6-9b64-1fe082808f01.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17248348/949665be-555f-11e6-90d3-f57b15ad3005.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18417969/4f791082-7803-11e6-8e92-7aa89f950fb3.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18417982/8057f740-7803-11e6-93ef-ead4334f59d5.png)

**Comment by dushyants19** [comment]
Very well detailed! Nice work!

**Comment by MajorTomMueller** [comment]
Needs a rework. @ItsW1ll would you, or should I?

**Comment by ItsW1ll** [comment]
I didn't edit this, It's all yours! :)

**Comment by MajorTomMueller** [comment]
![EKCH-git](https://user-images.githubusercontent.com/26853210/75116599-f7f3fc00-5661-11ea-8bdc-876ecdb3d34b.png)
