### ISSUE TITLE
KMWA-Veterans Airport of Southern Illinois-ILLINOIS-USA

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#4475]
♻️

**Comment by brunocr98** [comment]
Hmmm, last time I checked you were removed from this team. Why are you doing airports?

**Comment by jakey20** [comment]
I want to

**Comment by brunocr98** [comment]
No.

You've been removed from out Slack for being banned from IFC (due to the reasons stated in your profile). Don't even try to create issues and even do airports, you'll be refused anyway.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/87881884-fb49a480-c9c1-11ea-9b87-074eebe8a800.png)
