### ISSUE TITLE
INVALID

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#4476]
# Airport Name

San Luis County Airport

# Country?

USA

# Improvements that need to be made?

Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by brunocr98** [comment]
I've told you, any action from you will be refused. Don't keep on with this charade.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/87877246-d0038d00-c9a2-11ea-9b11-6ea57824f819.png)
