### ISSUE TITLE
KPVU-Provo Municipal Airport-UTAH-USA

### ISSUE THREAD

**Issue by KimballWhite** [InfiniteFlightAirportEditing/Airports#4477]
# Airport Name

Provo Municipal Airport

# Country?

United States of America

# Improvements that need to be made?

Complete Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

World/US Capital

**Comment by KimballWhite** [comment]
Wouldn't this be World/US Capital? Allegiant (G4) Serves Provo 10x weekly with A319s and A320s to Phoenix, the Capital of Arizona.

**Comment by RyanEpps** [comment]
No. Only if the airport itself is a capital.

**Comment by KimballWhite** [comment]
Ok. Have a good night!

**Comment by MajorTomMueller** [comment]
Still around @KimballWhite ?

**Comment by KimballWhite** [comment]
Feel free to assign this airport to somebody else, since I am now using X-Plane 11.

**Comment by LesterXavier** [comment]
I'll take this pls.

**Comment by KimballWhite** [comment]
Sure thing. I’ve moved on to X-Plane 11, so feel free. By the way, are you from Utah Valley?

**Comment by LesterXavier** [comment]
> Sure thing. I’ve moved on to X-Plane 11, so feel free. By the way, are you from Utah Valley?
> […](#)
> On Dec 21, 2020, at 19:57, LesterXavier ***@***.***> wrote: ﻿ I'll take this pls. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

No...

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103715079-52016580-4f85-11eb-85ce-7cfd009ae048.png)
