### ISSUE TITLE
INVALID

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#4478]
# Airport Name

San Luis County Airport

# Country?

USA

# Improvements that need to be made?

Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

IF Event

**Comment by brunocr98** [comment]
You’ve been warned.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/87876286-db53ba00-c99c-11ea-9c2b-fc92d88fac32.png)
