### ISSUE TITLE
SNLC-Fazenda Panambi-Minas Gerais-BRAZIL

### ISSUE THREAD

**Issue by JensSeverin** [InfiniteFlightAirportEditing/Airports#4487]
![image](https://user-images.githubusercontent.com/14023167/103182320-23daa200-4870-11eb-82ce-e9a06060cd5a.png)

**Comment by JensSeverin** [comment]
Bad imagery, nothing includes the new military ramp

**Comment by JensSeverin** [comment]
Is it possible to be unassigned at this time due to the reasons above?

**Comment by MajorTomMueller** [comment]
As a exception. Thought you had known to check images beforehand... 😉

**Comment by MajorTomMueller** [comment]
@JensSeverin could you tell me where this new apron should be?
https://ais.avinor.no/AIP/Latest/aip/ad/enna/EN_AD_2_ENNA_2-1_en.pdf

**Comment by MajorTomMueller** [comment]
never mind, found
