### ISSUE TITLE
BGSF

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#449]
Kangerlussuaq, Greenland

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17199024/70ee4de6-543f-11e6-8e15-57a671f26314.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18571428/e4c9597c-7b77-11e6-862e-b5aa6c0fb668.png)
