### ISSUE TITLE
NZYP-Waipukurau Airport-HAWKES BAY-NEW ZEALAND

### ISSUE THREAD

**Issue by Lukeh0** [InfiniteFlightAirportEditing/Airports#4500]
# Airport Name

Waipukurau Airport

# Country?

New Zealand

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/72672622-6a5a3680-3a3b-11ea-9fd2-06075db1edb9.jpg)
