### ISSUE TITLE
ZWTN-Hotan Airport-XINJIANG-CHINA

### ISSUE THREAD

**Issue by Fabse1803** [InfiniteFlightAirportEditing/Airports#4501]
# Airport Name

< Hotan Airport>

# Country?

< Xinjiang >

# Improvements that need to be made?

< Full Rework >

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by AnthonyCK** [comment]
Can any sup assign this issue to me? Already had an agreement with @Fabse1803 on this issue.

**Comment by AnthonyCK** [comment]
Any sup here?

**Comment by MajorTomMueller** [comment]
depends on the question

**Comment by AnthonyCK** [comment]
@Fabse1803 has already handed this airport over to me, so could you please assign it to me? @MajorTomMueller

**Comment by AnthonyCK** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/81992974-19d69c80-961b-11ea-8f45-89ee1b6f859b.jpg)
