### ISSUE TITLE
NTAR-Rurutu Airport-RURUTU-FRENCH POLYNESIA

### ISSUE THREAD

**Issue by KC3DLL** [InfiniteFlightAirportEditing/Airports#4502]
# Airport Name

Rurutu

# Country?

French Polynesia 

# Improvements that need to be made?

Full Rework 

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kztmtn** [comment]
@KC3DLL Are you still working on this?

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/79268453-2ecfdc80-7e71-11ea-975d-522ff074842c.jpg)
