### ISSUE TITLE
20IS-Mitek Airstrip-ILLINOIS-USA

### ISSUE THREAD

**Issue by KimballWhite** [InfiniteFlightAirportEditing/Airports#4504]
![image](https://user-images.githubusercontent.com/14023167/109390196-c4cbf480-78d5-11eb-8799-6153505838da.png)

**Comment by KimballWhite** [comment]
Airport has been submitted for OR.

**Comment by MajorTomMueller** [comment]
Submitted over a year ago, what was the result @KimballWhite ?

**Comment by KimballWhite** [comment]
Hi Major Tom,

I edited KDTA over a year ago, and it was rejected because of a few small errors, but I have moved on to X-Plane 11, so feel free to assign this airport to somebody else.

Thanks, KimballWhite
