### ISSUE TITLE
KBDH-Willmar Municipal Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#4505]
# Airport Name

Willmar Municipal Airport

# Country?

USA

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low (?)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/73315411-cdec1d00-420e-11ea-87ce-57dec9e0fc5f.jpg)
