### ISSUE TITLE
DUPLICATE

### ISSUE THREAD

**Issue by JoshTomaz** [InfiniteFlightAirportEditing/Airports#4506]
# Airport Name

< Oliver Reginald Tambo International Airport (O.R Tambo) >

# Country?

< South Africa >

# Improvements that need to be made?

< Incorrect spawn names. >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< 10000ft, World Capital. >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/87857720-7d689900-c8ee-11ea-8556-5f95e9cc9a7f.png)
