### ISSUE TITLE
KULM-New Ulm Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by JoshTomaz** [InfiniteFlightAirportEditing/Airports#4507]
# Airport Name

< New Ulm Airport >

# Country?

< USA >

# Improvements that need to be made?

< Full Rework >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by JoshTomaz** [comment]
Sent in for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/71787937-4a1e8680-2ffc-11ea-81f3-9095c1f98dae.jpg)
