### ISSUE TITLE
BGGH-Nuuk Airport-GODTHAAB-GREENLAND

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#451]
Nuuk, Greenland

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17198858/2168962e-543e-11e6-813a-decabcf0f989.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18571733/66c7cf24-7b7a-11e6-955e-74340260f9c9.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53706588-af0fbb80-3df0-11e9-8d1c-56fdb2a608bb.png)
