### ISSUE TITLE
FAKM-Kimberley Airport-NORTHERN CAPE-SOUTH AFRICA

### ISSUE THREAD

**Issue by JoshTomaz** [InfiniteFlightAirportEditing/Airports#4511]
# Airport Name

< Kimberley Airport >

# Country?

< South Africa >

# Improvements that need to be made?

< Full Rework >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MajorTomMueller** [comment]
@JoshTomaz still want to do this one? otherwise it will be recycled

**Comment by GBKarp** [comment]
Can I be assigned?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101843662-523a4c80-3b10-11eb-87a5-220b1238771d.png)
