### ISSUE TITLE
LPEV-Evora Airport-ALENTEJO-PORTUGAL

### ISSUE THREAD

**Issue by JoshTomaz** [InfiniteFlightAirportEditing/Airports#4514]
# Airport Name

< Evora Airport >

# Country?

< Portugal >

# Improvements that need to be made?

< Full Rework >

# Are you working on this airport?

< Yes. >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by Sid216** [comment]
Hi, can I do a rework on this airport?

**Comment by MajorTomMueller** [comment]
I don't know if you can, but I can assigne you and you could do.

**Comment by Sid216** [comment]
Thank you!

**Comment by MajorTomMueller** [comment]
![LPEV-git](https://user-images.githubusercontent.com/26853210/131220224-526b8b6c-92ba-43a7-a7cd-4eb759210617.png)
