### ISSUE TITLE
EFIV-Ivalo Airport-NORTHERN FINLAND-FINLAND

### ISSUE THREAD

**Issue by liamkirky** [InfiniteFlightAirportEditing/Airports#4516]
# Airport Name

Ivalo Airport

# Country?

Finland

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by liamkirky** [comment]
Sent in for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/71787516-8ef3ee80-2ff7-11ea-9485-88bb23563f54.jpg)
