### ISSUE TITLE
KSBS-Steamboat Springs-COLORADO-USA

### ISSUE THREAD

**Issue by tomthetank46** [InfiniteFlightAirportEditing/Airports#4519]
# Airport Name

< Steamboat Springs Airport/Bob Adams Field >

# Country?

< US >

# Improvements that need to be made?

< Reword from scratch >

# Are you working on this airport?

< Would like to, yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< None >

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/75926455-5894ed00-5e49-11ea-97aa-949214dd17ca.jpg)
