### ISSUE TITLE
BGJN

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#452]
Ilulissat, Greenland.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17198950/e9d842b2-543e-11e6-85b3-639b4663ffdf.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18571664/b717bec2-7b79-11e6-8a41-7c22e09f3be0.png)
