### ISSUE TITLE
UWGG-Nizhny Novgorod Airport-NIZHEGOROD-RUSSIA

### ISSUE THREAD

**Issue by flyingreaper** [InfiniteFlightAirportEditing/Airports#4521]
♻️

**Comment by AleksanderIF** [comment]
Hello, you were assigned on April 6, what is your progress? @HauBHa9lDbIPo4Ka

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105429037-474a0000-5c16-11eb-8d7f-ec9e39fc7230.png)
