### ISSUE TITLE
MRGF-Golfito Airport-PUNTARENAS-COSTA RICA

### ISSUE THREAD

**Issue by HymenopusC** [InfiniteFlightAirportEditing/Airports#4523]
# Airport Name

Golfito Airport

# Country?

Costa Rica

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

I would like to start working on this airport, yes.

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/77341685-dd1eb100-6d0d-11ea-8eca-65d2129d0e4f.jpg)
