### ISSUE TITLE
A26-Adin Airport-CALIFORNIA-USA 

### ISSUE THREAD

**Issue by flyingreaper** [InfiniteFlightAirportEditing/Airports#4525]
# Airport Name

Adin Airport
# Country?

USA

# Improvements that need to be made?

Does not currently exist in IF

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by flyingreaper** [comment]
Sent for OR

**Comment by RyanEpps** [comment]
Are you in our slack team?

**Comment by flyingreaper** [comment]
I was never added to a slack team

**Comment by RyanEpps** [comment]
What’s your IFC username so I can get you added?

**Comment by flyingreaper** [comment]
nk1021

**Comment by flyingreaper** [comment]
jakey2_0

**Comment by RyanEpps** [comment]
Any relation to a previous member?

**Comment by flyingreaper** [comment]
Possibly

**Comment by flyingreaper** [comment]
I just want to help and rework airports

**Comment by RyanEpps** [comment]
Noted.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/87854633-e47b5300-c8d8-11ea-8d51-2ae5b6b13235.png)
