### ISSUE TITLE
A26

### ISSUE THREAD

**Issue by flyingreaper** [InfiniteFlightAirportEditing/Airports#4526]
# Airport Name

Adin Airport
# Country?

USA

# Improvements that need to be made?

Does not Exist in IF

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/87854253-4a1a1000-c8d6-11ea-8747-f158a0f2e4b9.png)
