### ISSUE TITLE
YDWF-Delamere Range Facility Airpor-NORTHERN TERRITORIES-AUSTRALIA 

### ISSUE THREAD

**Issue by bigoof42069** [InfiniteFlightAirportEditing/Airports#4531]

**Comment by MajorTomMueller** [comment]
![YDWF](https://user-images.githubusercontent.com/26853210/71568687-2ec5ef80-2ac1-11ea-893b-4f8d09409696.png)

**Comment by MBeringuy** [comment]
Please check to see if ICAO is correct and apt.dat has been sent to the correct folder.

**Comment by MajorTomMueller** [comment]
Wilco ASAP

**Comment by MajorTomMueller** [comment]
All checked, issue name corrected, folder and apt are correct, commit comment is wrong and can’t be changed.
