### ISSUE TITLE
FVWN-Hwange National Pk Airport-MATABELELAND-ZIMBABWE

### ISSUE THREAD

**Issue by freddiefrogs** [InfiniteFlightAirportEditing/Airports#454]
REUSED

**Comment by dushyants19** [comment]
Search before postin' 

https://github.com/InfiniteFlightAirportEditing/Airports/issues/290

**Comment by IceBlue02** [comment]
Duplicate?
https://github.com/InfiniteFlightAirportEditing/Airports/issues/379

**Comment by PilotCat** [comment]
ill tackle this

**Comment by dushyants19** [comment]
@PilotCat hows this going?

**Comment by dushyants19** [comment]
i'll do this. This is one of the easiest 10k-s ever


![image](https://cloud.githubusercontent.com/assets/13567007/25444311/51bf6126-2ab3-11e7-82cd-a85a149bbc9d.png)

**Comment by dushyants19** [comment]
Done; Poor imagery, poor layout, no markings, no charts

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25515126/04179f06-2ba8-11e7-83bd-a0f1fb8c09a2.png)
