### ISSUE TITLE
MY94-Country Haven Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by Gabe-Z** [InfiniteFlightAirportEditing/Airports#4541]
# Airport Name

Country Haven Airport

# Country?

USA

# Improvements that need to be made?

Unedited

# Are you working on this airport?

Ja

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by Gabe-Z** [comment]
The airstrip is in review.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/71788092-00cf3680-2ffe-11ea-8fe8-2647c78461ca.jpg)
