### ISSUE TITLE
MN57-Bush Field-MINNESOTA-USA

### ISSUE THREAD

**Issue by Gabe-Z** [InfiniteFlightAirportEditing/Airports#4544]
# Airport Name

Bush Field

# Country?

USA

# Improvements that need to be made?

Unedited and way off from its location. About 200 miles offset.

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MajorTomMueller** [comment]
Three issue threshold, can‘t be assigned

**Comment by astoriaaa** [comment]
Can I do this?

**Comment by astoriaaa** [comment]
Sent for OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/73315534-1a375d00-420f-11ea-8f79-7ce33530f7af.jpg)
