### ISSUE TITLE
SWBI-Santa Colomba Cafes Airport-BAHIA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#4545]
# Airport Name

Santa Colomba Cafes Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/71624290-81d29c00-2bc0-11ea-8b00-3d7c2d140bb1.jpg)

**Comment by kilt46** [comment]
https://pergamum.anac.gov.br/arquivos/PA2020-1643.pdf
Wrong Location
Should be
![image](https://user-images.githubusercontent.com/14023167/103459788-1b062800-4cd7-11eb-810c-08deac8a4ed1.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103463064-39781d80-4cef-11eb-8052-6b5e742f6675.png)
