### ISSUE TITLE
KPVC

### ISSUE THREAD

**Issue by Ksisky** [InfiniteFlightAirportEditing/Airports#455]

**Comment by Ksisky** [comment]
Done, submitted to repo.

**Comment by kilt46** [comment]
Still old version in Repo
![Uploading image.png…]()

**Comment by Ksisky** [comment]
> From: Infinite Flight Airport Editing <airports@liveflightapp.com>
> Date: Sun, Apr 3, 2016 at 2:58 PM
> Subject: Re: KPVC
> To: Kevin Sisk <kevindsisk@gmail.com>
>
>Looks good Kevin. Adding to the repro! :)

**Comment by carmichaelalonso** [comment]
I think I added at as KFVC... my apologies, will look into it later.

**Comment by Ksisky** [comment]
It was commited, (https://github.com/InfiniteFlightAirportEditing/Airports/commit/11d59af63adf4f9546736fc22ef6b0b6b680fa60), but [not to the folder.](https://github.com/InfiniteFlightAirportEditing/Airports/blob/11d59af63adf4f9546736fc22ef6b0b6b680fa60/apt.dat) I think the file was later deleted without it being committed to the repository.

**Comment by dushyants19** [comment]
I'll look into this.

**Comment by dushyants19** [comment]
Done. 

https://github.com/InfiniteFlightAirportEditing/Airports/commit/dd2809c941c90fde5ba020e65a72e83d8e2b4c10

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20649173/363f7612-b47e-11e6-9262-09d6b439b256.png)
