### ISSUE TITLE
WSAP

### ISSUE THREAD

**Issue by Ksisky** [InfiniteFlightAirportEditing/Airports#456]
Taxiways and lines need snapping.

**Comment by HenrikBerg02** [comment]
I'll take this one.

**Comment by HenrikBerg02** [comment]
Fixed.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17270338/04676e3a-5626-11e6-8dfc-6364085ea9dd.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17914549/ba2b1ee2-6968-11e6-97ae-91cd4dbdfd76.png)
