### ISSUE TITLE
LFBL-Limoges Bellegarde Airport-LIMOUSIN-FRANCE

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#4560]
# Airport Name

LFBL - Limoges Bellegarde

# Country?

France

# Improvements that need to be made?

Quick gate movements, mainly GA

# Are you working on this airport?

All mine

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85342534-7e093d80-b4b0-11ea-9d45-ad29d23ad51d.png)
