### ISSUE TITLE
ZBSJ-Shijiazhuang Zhengding International Airport-HEBEI-CHINA

### ISSUE THREAD

**Issue by henrylzy** [InfiniteFlightAirportEditing/Airports#4561]
# Airport Name

Shijiazhuang Zhengding International Airport

# Country?

CHINA

# Improvements that need to be made?

Fully redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

RWY 10K+

**Comment by brunocr98** [comment]
This airport is very big for a beginner. I advise you to start with smaller airports to practice and understand essential editing techniques.

**Comment by henrylzy** [comment]
> This airport is very big for a beginner. I advise you to start with smaller airports to practice and understand essential editing techniques.

Yeah it's a bit of a challenge since I've never edit with WED and it's completely different from other editors that I've used(AFCAD, ADE). Took me some time and struggled for a while to get familiar with the software but everything went pretty smooth after that. Now the airport is 60% done, will be finished in a couple more days.

**Comment by henrylzy** [comment]
![Image_20200109220507](https://user-images.githubusercontent.com/25072307/72074091-39d41780-332c-11ea-80fb-55f7b3ef2ce6.png)
Airport is done. Waiting to be assigned.

**Comment by MBeringuy** [comment]
Upload the apt.dat file from the airport to the # peer-review room on Slack for analysis.

**Comment by henrylzy** [comment]
Already did. Thanks a lot

**Comment by henrylzy** [comment]
sent for OR

**Comment by kztmtn** [comment]
@henrylzy Have you fixed advised points by OR and re-submitted it?

**Comment by AnthonyCK** [comment]
Still no reply :( @kztmtn

**Comment by moritzbabl** [comment]
@AnthonyCK you can take this issue, no action on this since January

**Comment by MajorTomMueller** [comment]
Handover agreed by both editors

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101843319-91b46900-3b0f-11eb-8b33-02e990ad953c.png)
