### ISSUE TITLE
KOAJ-Albert J Ellis Airport-NORTH CAROLINA-USA

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#4562]
# Airport Name

Albert J Ellis Airport

# Country?

USA

# Improvements that need to be made?

Scratch rework

# Are you working on this airport?

Why not

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

None

**Comment by HiFlyerBwi** [comment]
Suspended due to imagery issues with SAS.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/75725309-f27c5e80-5cbe-11ea-9242-ceae118acc5c.jpg)
