### ISSUE TITLE
SBTS-Tirios Airport-PARA-BRAZIL

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#4563]
# Airport Name

Tirios Airport

# Country?

Brazil

# Improvements that need to be made?

Scratch re-work

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

None

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/71787570-5d2f5780-2ff8-11ea-810e-6c6b8a6b6487.jpg)
