### ISSUE TITLE
CYUY-Rouyn Noranda Airport-QUEBEC-CANADA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#4565]
# Airport Name

Rouyn Noranda Airport, CYUY

# Country?

Canada

# Improvements that need to be made?

Completely reworked from default/scratch

# Are you working on this airport?

Yes. (uploaded to Slack for Peer Assessment)

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low Priority, will be used in my own events for transatlantic ferry flights with IFGAC.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/77346100-6d5ff480-6d14-11ea-9508-1348ad5811a6.jpg)
