### ISSUE TITLE
ENMH-Mehamn Airport-FINNMARK-NORWAY

### ISSUE THREAD

**Issue by jakey200** [InfiniteFlightAirportEditing/Airports#4566]
# Airport Name

Mehamn

# Country?

Norway

# Improvements that need to be made?

Full Redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by jakey200** [comment]
Sent for OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/75638848-ad97ef80-5c0c-11ea-9a6b-dfb86aaa62fd.jpg)
