### ISSUE TITLE
LESA-Salamanca Airport-CASTILLA Y LEON-SPAIN

### ISSUE THREAD

**Issue by rebal15** [InfiniteFlightAirportEditing/Airports#4567]
# Airport Name

Salamanca Airport, LESA

# Country?

Spain

# Improvements that need to be made?

redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by rebal15** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/77342196-98dfe080-6d0e-11ea-9656-cbb4fee4ea17.jpg)
