### ISSUE TITLE
CYCK-Chatham Kent Airport-ONTARIO-CANADA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#4568]
# Airport Name

Chatham Kent Municipal Airport

# Country?

Canada

# Improvements that need to be made?

New airport in-game

# Are you working on this airport?

Yes.

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low.

It is nearly completed, I just need to add runway information once I am working on it again.

![20200106_065302](https://user-images.githubusercontent.com/59462519/71840996-5d8e2800-30b6-11ea-9081-6ffac94ef0da.jpg)
![20200106_065325](https://user-images.githubusercontent.com/59462519/71840997-5d8e2800-30b6-11ea-947f-802423cdc98e.jpg)

These images are for some reason upside down.

**Comment by ECoops-123** [comment]
Approved. Don't have photo on me currently except from above.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/77239136-d7ae5300-6bb5-11ea-8bb7-cd401a735b56.jpg)
