### ISSUE TITLE
LEVT-Vitoria Airport-PAIS VASCO-SPAIN

### ISSUE THREAD

**Issue by rebal15** [InfiniteFlightAirportEditing/Airports#4569]
# Airport Name

Vitoria Airport, LEVT

# Country?

Spain

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

10000ft+ Runway

**Comment by bavariaaviation** [comment]
@rebal15 any progress on this?

**Comment by rebal15** [comment]
Yep, sorry, I have been a bit busy lately, but its coming!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109082248-31be6f00-76c9-11eb-94ac-4eb0d57b97c6.png)
