### ISSUE TITLE
KOKB - SoCal

### ISSUE THREAD

**Issue by Ksisky** [InfiniteFlightAirportEditing/Airports#457]
Needs snapping and has incorrect markings.

**Comment by dushyants19** [comment]
Continue [here](https://github.com/InfiniteFlightAirportEditing/Airports/issues/69)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20626085/ec77ac86-b2dc-11e6-9098-8a68cfc4bea4.png)
