### ISSUE TITLE
KIAG-Niagara Falls International Airport-NEW YORK-USA

### ISSUE THREAD

**Issue by osujim15** [InfiniteFlightAirportEditing/Airports#4570]
# Airport Name

Niagara Falls International Airport

# Country?

USA

# Improvements that need to be made?

Complete rework

# Are you working on this airport?

No

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by Sid216** [comment]
Can you please assign me this one?

**Comment by Czechoslovaki** [comment]
@Sid216 how's this airport going?

**Comment by Sid216** [comment]
Looking good, its just that the SAS images of the terminals are a bit blurry so it's hard to map it out but I'm trying my best. Also, I just got back from vacation after my semester ended so I will be done with this in two weeks or so. The military terminals are also hard. I have laid out a basic map and I just have to curve them according to the taxiways!

**Comment by GBKarp** [comment]
Can I please be assigned to this one?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116937347-b7611c80-ac2e-11eb-9076-4cff20070464.png)
