### ISSUE TITLE
KMMV-McMinnville Municipal Airport-OREGON-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#4571]
# Airport Name

McMinnville Municipal Airport

# Country?

USA

# Improvements that need to be made?

Full rework

# Are you working on this airport?

Heck yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/75925392-65b0dc80-5e47-11ea-960a-8aa82f91a6a2.jpg)
