### ISSUE TITLE
C81-Campbell Airport-ILLINOIS-USA

### ISSUE THREAD

**Issue by osujim15** [InfiniteFlightAirportEditing/Airports#4573]
# Airport Name

Campbell Airport

# Country?

USA

# Improvements that need to be made?

Full rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by osujim15** [comment]
Airport sent in for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/75641100-e5576500-5c15-11ea-8e0d-eecc4e73b8fb.jpg)
