### ISSUE TITLE
06C-Schaumburg Regional Airport-ILLINOIS-USA

### ISSUE THREAD

**Issue by osujim15** [InfiniteFlightAirportEditing/Airports#4574]
# Airport Name

Schaumburg Regional Airport

# Country?

USA

# Improvements that need to be made?

Full rework

# Are you working on this airport?

No

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MajorTomMueller** [comment]
The answer to the question about airport priority can never be “yes”. It is either “none” or wich one

**Comment by osujim15** [comment]
My bad. I updated it.

**Comment by osujim15** [comment]
Airport sent in for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/75640908-52b6c600-5c15-11ea-8233-5ae7521a9443.jpg)
