### ISSUE TITLE
KJOT-Joliet Regional Airport-ILLINOIS-USA

### ISSUE THREAD

**Issue by osujim15** [InfiniteFlightAirportEditing/Airports#4575]
# Airport Name

Joliet Regional Airport

# Country?

USA

# Improvements that need to be made?

Full rework

# Are you working on this airport?

No

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MajorTomMueller** [comment]
The answer to the question if you are working on this airport has to be always yes unless you are supervisor. 
You have reached the 3 airport open threshold. Please stop opening further issues as long all three of them are open. (And they will be closed by the review administrator ONLY)

**Comment by osujim15** [comment]
I wasn't aware of that. I'll stop.

**Comment by AnthonyCK** [comment]
I think I can do this. Can anyone assign this issue to me? Thanks!

**Comment by AnthonyCK** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/75724484-42f2bc80-5cbd-11ea-95fc-f87df509f4a2.jpg)
