### ISSUE TITLE
KFLD-Fond du Lac County Airport-WISCONSIN-USA

### ISSUE THREAD

**Issue by osujim15** [InfiniteFlightAirportEditing/Airports#4576]
# Airport Name

Fond du Lac County Airport

# Country?

USA

# Improvements that need to be made?

Full rework

# Are you working on this airport?

No

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kirby2007** [comment]
I would like to work on this one.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/89100527-346c1680-d3bd-11ea-81cf-dabd82a8bef0.png)
