### ISSUE TITLE
KAPY-Zapata County Airport-TEXAS-USA

### ISSUE THREAD

**Issue by henrylzy** [InfiniteFlightAirportEditing/Airports#4577]
# Airport Name

Zapata County Airport

# Country?

USA

# Improvements that need to be made?

redone from scratch

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by MajorTomMueller** [comment]
@henrylzy still around?

**Comment by ECoops-123** [comment]
![Full](https://user-images.githubusercontent.com/59462519/104797016-e1432000-57b2-11eb-9ea5-4ae1173acaef.png)
