### ISSUE TITLE
VTCT-Chiang Rai International Airport-CHIANG RAI-THAILAND

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#4579]
# Airport Name

Chiang Rai International Airport

# Country?

Thailand

# Improvements that need to be made?

Redone from scratch.

# Are you working on this airport?

Of course

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by brennanhackard** [comment]
Can I be unassigned temporarily? The scenery is distorted.

**Comment by vidur678** [comment]
CAN I CLAIM THIS AIRPORT

**Comment by MajorTomMueller** [comment]
Well, you can. But be warned, The previous assigned editor is not a newbie and it is not long that he refuse due to poor imagery. I just checked, and the imagery is still creepy.
You really like this task?

**Comment by vidur678** [comment]
Hi Major Tom I'm a newbie can you like send me how to progress with it I
have downloaded the editor but not knowing what to next. Can you like send
me a video please. Thanks

**Comment by MajorTomMueller** [comment]
No, I can‘t send you a video. I don’t have one. Please read the guide the Moritz has written so lovely. And please follow the advice given in IFCs thread: https://community.infiniteflight.com/t/infinite-flight-airport-editing/321307
Do not abuse GitHub for conservation.

**Comment by Czechoslovaki** [comment]
Author of issue will resume work with this airport.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102725558-33d90b80-42dd-11eb-9d16-e631cc077dd4.png)
