### ISSUE TITLE
KSBM - Oshkosh

### ISSUE THREAD

**Issue by Ksisky** [InfiniteFlightAirportEditing/Airports#458]
Taxiways need snapping.

**Comment by kilt46** [comment]
I don't snap taxiways   :)

**Comment by dushyants19** [comment]
Will do :)

**Comment by dushyants19** [comment]
Done most of them

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20690767/24d97f8e-b592-11e6-9661-30e476cd596d.png)
