### ISSUE TITLE
LERE-Requena Airport-COMUNIDAD VALENCIANA-SPAIN

### ISSUE THREAD

**Issue by CaptainMerka** [InfiniteFlightAirportEditing/Airports#4583]
# Airport Name

< Requena Aerodrome >

# Country?

< Spain >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes. >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111030779-b992c180-83c9-11eb-89fc-7eb2da120ebf.png)
