### ISSUE TITLE
SDPW-Piracicaba Airport-SAO PAULO-BRAZIL

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Airports#4584]
# Airport Name

< Piracicaba >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone form scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by FellipeEdu** [comment]
Sent to OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/75721991-15574480-5cb8-11ea-92de-585b0d215fbb.jpg)
