### ISSUE TITLE
NZKT-Kaitaia Airport-NORTHLAND-NEW ZEALAND

### ISSUE THREAD

**Issue by Lukeh0** [InfiniteFlightAirportEditing/Airports#4586]
# Airport Name

Kaitaia Airport

# Country?

New Zealand

# Improvements that need to be made?

Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/73312605-dd1b9c80-4207-11ea-9534-63f2190b7763.jpg)
