### ISSUE TITLE
YSCN

### ISSUE THREAD

**Issue by dushyants19** [InfiniteFlightAirportEditing/Airports#459]
Sydney - needs a rework

**Comment by kilt46** [comment]
Airport redone!

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18036164/a425ad46-6d29-11e6-879a-f668b0ae7bb0.png)

**Comment by hossss6** [comment]
I'll take this airport, currently doing a full airport rework

**Comment by brunocr1050** [comment]
This airport has been completed (Claudio didn't reopen the issue).

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104969188-68f47e80-59ad-11eb-8d60-0be611a4f866.png)
