### ISSUE TITLE
KROS-Rush City Regional-MINNESOTA-USA

### ISSUE THREAD

**Issue by Gabe-Z** [InfiniteFlightAirportEditing/Airports#4591]
# Airport Name

Rush City Regional

# Country?

USA

# Improvements that need to be made?

Unedited

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by Gabe-Z** [comment]
The airport is now in Offical Review.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78412290-311c7600-75e9-11ea-8859-68c7662a35db.jpg)
