### ISSUE TITLE
LUCH-Cahul International Airport-CAHUL-MOLDOVA

### ISSUE THREAD

**Issue by danisrils39** [InfiniteFlightAirportEditing/Airports#4592]
# Airport Name

Cahul International Airport

# Country?

Moldova

# Improvements that need to be made?

Didn't exist in game yet

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

N/A

**Comment by danisrils39** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/73311742-fd4a5c00-4205-11ea-9aea-7499cdcaae21.jpg)
