### ISSUE TITLE
SIFC-Coroa Do Aviao Airport-PERNAMBUCO-BRAZIL

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Airports#4596]
# Airport Name

< Coroa do Aviao >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by FellipeEdu** [comment]
Sent to OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/75722406-ea212500-5cb8-11ea-8f1f-d2470b56ed26.jpg)
