### ISSUE TITLE
KSLE-Salem Municipal Airport-OREGON-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#4598]
# Airport Name

Salem Municipal Airport.

# Country?

USA

# Improvements that need to be made?

Full rework needed.

# Are you working on this airport?

Yeah.

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

US capital.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/77348562-6e932080-6d18-11ea-97de-267447c23d7a.jpg)
