### ISSUE TITLE
LIPB-Bolzano Airport-TRENTINO-ALTO ADIGE-ITALY

### ISSUE THREAD

**Issue by freddiefrogs** [InfiniteFlightAirportEditing/Airports#460]

**Comment by kilt46** [comment]
THIS AIRPORT IS NOT IN THE LIBRARY

**Comment by freddiefrogs** [comment]
I have done this already. Did I not send it off @carmichaelalonso ?

**Comment by freddiefrogs** [comment]
I will resend it tomorrow. I can't do it now.

**Comment by freddiefrogs** [comment]
I checked my sent mail. I did send it off.

**Comment by kilt46** [comment]
This airport is NOT in the Repo

**Comment by freddiefrogs** [comment]
Can be closed now.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20852888/17bb3e9a-b8ae-11e6-945c-e577398b7997.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/70663394-01ff8480-1c47-11ea-8477-7ac995da3d5b.jpg)
