### ISSUE TITLE
KAGC-Allegheny County Airport-PENNSYLVANIA-USA

### ISSUE THREAD

**Issue by jakey200** [InfiniteFlightAirportEditing/Airports#4600]
# Airport Name

Allegheny County

# Country?

United States of America

# Improvements that need to be made?

Full redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by jakey200** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/86422235-259d2180-bca2-11ea-940e-3975ba1a2029.png)
