### ISSUE TITLE
KMHR-Sacramento Mather Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by jakey200** [InfiniteFlightAirportEditing/Airports#4602]
# Airport Name

KMHR

# Country?

USA

# Improvements that need to be made?

Full Redo

# Are you working on this airport?

Yeeeeeeeeeeeeeeeee

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

10k+, US Capital.

**Comment by MajorTomMueller** [comment]
assignment been descided by a administrator

**Comment by RyanEpps** [comment]
No. Send in your other airports first.

**Comment by jakey200** [comment]
Airport needs imagery update. New hangars/ramp area currently shown under construction.

**Comment by MajorTomMueller** [comment]
In google Maps there is no unfinished construction area. No difference to GEpro. Suggest you take latest images and finish as it is shown.

**Comment by jakey200** [comment]
https://gyazo.com/84a1bfb9fa89c2a81a4ed52c19760930
I was talking about this area.

**Comment by MajorTomMueller** [comment]
Use Bing as source in SAS. Excellent imageru]y of the finished and in use apron

**Comment by MajorTomMueller** [comment]
![5D391EBE-FC1F-44E0-8316-5C9ADFB69A12](https://user-images.githubusercontent.com/26853210/80527691-11ccfa80-8995-11ea-8580-ed423bd088bb.jpeg)

**Comment by jakey200** [comment]
sent to o f f i c i a l r e v i e w

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/81997581-860acd80-9626-11ea-9b24-955412b5e777.jpg)
