### ISSUE TITLE
KMCE-Merced Regional Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#4603]
# Airport Name

Merced Regional Airport

# Country?

USA

# Improvements that need to be made?

Full rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

Part of project California. An overview and a few more spawn locations are required by me. A new hangar area is available on the North East area of the airport, however there is no satellite imagery so will ideally leave for now.

Apologies for bad quality pictures.

They won't load so I've linked it to my post on the IFC.

https://community.infiniteflight.com/t/project-california/398007/15?u=ecoops_123

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/77352522-152df000-6d1e-11ea-9319-4057c9aec856.jpg)
