### ISSUE TITLE
VDSV-Sihanoukville International Airport-PREAH SIHANOUK-CAMBODIA

### ISSUE THREAD

**Issue by tomthetank46** [InfiniteFlightAirportEditing/Airports#4606]
# Airport Name

Sihanoukville International Airport

# Country?

Cambodia

# Improvements that need to be made?

All
# Are you working on this airport?

Y

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

GP1

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/77342709-62569580-6d0f-11ea-8193-56ebf6631433.jpg)
