### ISSUE TITLE
PAMR-Merrill Field Airport-ALASKA-USA

### ISSUE THREAD

**Issue by IFC-PlaneCrazy** [InfiniteFlightAirportEditing/Airports#4609]
# Airport Name

Merrill Field Airport

# Country?

USA

# Improvements that need to be made?

Will be redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by IFC-PlaneCrazy** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/77240111-ef3f0900-6bc0-11ea-8bea-992eb6a0657b.jpg)
