### ISSUE TITLE
CYTS-Timmis/Victor M. Power Airport-ONTARIO-CANADA

### ISSUE THREAD

**Issue by flyme2bluemoon** [InfiniteFlightAirportEditing/Airports#4610]
# Airport Name

TIMMINS/VICTOR M. POWER

# Country?

Canada

# Improvements that need to be made?

Redo from Scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by GBKarp** [comment]
Can I be assigned please?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124351944-f83fc800-dbc2-11eb-8b56-d788ded39b02.png)
