### ISSUE TITLE
FYWB-Walvis Bay International Airport-ERONGO-NAMIBIA

### ISSUE THREAD

**Issue by FlyBoii31** [InfiniteFlightAirportEditing/Airports#4614]
# Airport Name

< Walvis Bay International Airport >

# Country?

< Namibia >

# Improvements that need to be made?

< Full Rework >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/87876377-6f258600-c99d-11ea-967d-369a5a7d893d.png)
