### ISSUE TITLE
EDLF-Grefrath Niershorst Airport-NORDRHEIN-WESTFALEN-GERMANY

### ISSUE THREAD

**Issue by marcelborussia** [InfiniteFlightAirportEditing/Airports#4616]
# Airport Name

< Flugplatz Grefrath-Niershorst >

# Country?

< Germany >

# Improvements that need to be made?

< Airport is missing >

# Are you working on this airport?

< No >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/77239287-c9613680-6bb7-11ea-9477-775251253f6a.jpg)
