### ISSUE TITLE
SBNV-Aerodromo Nacional De Aviacao Airport-GOIAS-BRAZIL

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Airports#4617]
# Airport Name

< Aerodromo Nacional De Aviacao >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by FellipeEdu** [comment]
Sent to OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/84606263-26dcea80-ae6a-11ea-882a-50aa02ef4a76.png)
