### ISSUE TITLE
WIPB-Lubuklinggau Silampari Airport-SOUTH SUMATRA-INDONESIA

### ISSUE THREAD

**Issue by vinoalviano1994** [InfiniteFlightAirportEditing/Airports#4618]
# Airport Name

< Lubuklinggau Silampari Airport >

# Country?

< Indonesia >

# Improvements that need to be made?

< Full Rework & Change ICAO From WIKL to WIPB >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by vinoalviano1994** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/79270523-bb2fce80-7e74-11ea-97e6-04a095f846a5.jpg)
