### ISSUE TITLE
PHMK-Molokai Airport-HAWAII-USA

### ISSUE THREAD

**Issue by IceBlue02** [InfiniteFlightAirportEditing/Airports#462]
(Hawaii)

Needs some love

**Comment by kilt46** [comment]
Looks fine to me. did some minor tweaks.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20630307/cb24341e-b2f5-11e6-978a-55da1e64a5f4.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45264686-3e21b500-b406-11e8-95a1-abe0171c1702.png)
