### ISSUE TITLE
SIZM-Mocelin II Airstrip-PARANA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#4622]
# Airport Name

Mocelin II Airstrip

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/74105546-a9ad0c00-4b3d-11ea-943d-e5f76ea44c18.jpg)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107156834-40292e80-6946-11eb-9b6d-6703191d013d.png)
