### ISSUE TITLE
WAGI-Iskandar Airport-CENTRAL KALIMANTAN-INDONESIA

### ISSUE THREAD

**Issue by vinoalviano1994** [InfiniteFlightAirportEditing/Airports#4624]
# Airport Name

< Iskandar Airport >

# Country?

< Indonesia >

# Improvements that need to be made?

< Full Rework & Change ICAO From WAOI to WAGI >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MajorTomMueller** [comment]
User wanted to be unassigned

**Comment by MajorTomMueller** [comment]
![WAGI](https://user-images.githubusercontent.com/26853210/80276021-0a77c980-86d5-11ea-8614-5ebe72334132.png)
