### ISSUE TITLE
EDAP-Verkehrslandeplatz Neuhausen-BRANDENBURG-GERMANY

### ISSUE THREAD

**Issue by rich-art-02** [InfiniteFlightAirportEditing/Airports#4626]
# Airport Name

Verkehrslandeplatz Neuhausen

# Country?

Germany

# Improvements that need to be made?

Redo from Scratch

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/75639960-e090b200-5c11-11ea-919a-118afa6b81e0.jpg)
