### ISSUE TITLE
FAEL-East London Airport-EASTERN CAPE-SOUTH AFRICA

### ISSUE THREAD

**Issue by osujim15** [InfiniteFlightAirportEditing/Airports#4628]
# Airport Name

East London Airport

# Country?

South Africa

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by osujim15** [comment]
Airport sent in for OR.

**Comment by osujim15** [comment]
It looks like the issue for this airport disappeared. I was assigned to it about a month ago. I had to create this new issue for it because I could find the previous one.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/75639752-1719fd00-5c11-11ea-993b-4178de551b2c.jpg)
