### ISSUE TITLE
SJIZ-Modulo Aguapei Airport-MATO GROSSO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#4633]
# Airport Name

Modulo Aguapei Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/74995570-0b1f8580-5430-11ea-8add-5c21d0c9b19c.jpg)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105615500-cb2af600-5d96-11eb-97fa-c2d6076b40db.png)
