### ISSUE TITLE
ZBDH-Qinhuangdao Beidaihe Airport-HEBEI-CHINA

### ISSUE THREAD

**Issue by AnthonyCK** [InfiniteFlightAirportEditing/Airports#4634]
# Airport Name

Qinhuangdao Beidaihe Airport

# Country?

China

# Improvements that need to be made?

New Airport

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by AnthonyCK** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/75639262-b7baed80-5c0e-11ea-9147-6dbac8198c79.jpg)
