### ISSUE TITLE
SNAE-Arcoverde Airport-PERNAMBUCO-BRAZIL

### ISSUE THREAD

**Issue by carloszferreira** [InfiniteFlightAirportEditing/Airports#4636]
# Airport Name

Arcoverde

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by carloszferreira** [comment]
Airport submitted for approval.

**Comment by MBeringuy** [comment]
Available for anyone who wants to edit.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/93710861-55283100-fb0f-11ea-9604-987bc2b97b67.png)
