### ISSUE TITLE
LFPH

### ISSUE THREAD

**Issue by IceBlue02** [InfiniteFlightAirportEditing/Airports#464]
https://community.infinite-flight.com/t/tarmac-error-lfph/32410

May need a full redo, otherwise a quick fix

**Comment by kilt46** [comment]
Gates modified. gras strip removed. New buildings added.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20859442/024cc3b8-b925-11e6-97e7-bad6ca60e8b4.png)
