### ISSUE TITLE
LTCR-Mardin Airport-MARDIN-TURKEY

### ISSUE THREAD

**Issue by gzhynko** [InfiniteFlightAirportEditing/Airports#4640]
# Airport Name

Mardin

# Country?

Turkey

# Improvements that need to be made?

Redo from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by gzhynko** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/75640305-50ec0300-5c13-11ea-8d02-83878386bb83.jpg)
