### ISSUE TITLE
ZSCG-Changzhou Benniu Airport-JIANGSU-CHINA

### ISSUE THREAD

**Issue by AnthonyCK** [InfiniteFlightAirportEditing/Airports#4641]
# Airport Name

Changzhou Benniu Airport

# Country?

China

# Improvements that need to be made?

Redo from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

10000ft+ Runway

**Comment by AnthonyCK** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/75639427-7c6cee80-5c0f-11ea-9930-f8c836436777.jpg)
