### ISSUE TITLE
SSZD-Zirondi Airport-RONDONIA-BRAZIL

### ISSUE THREAD

**Issue by carloszferreira** [InfiniteFlightAirportEditing/Airports#4642]
# Airport Name

Zirondi

# Country?

Brazil

# Improvements that need to be made?

New Airport

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by carloszferreira** [comment]
Airport submitted for approval.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/77350583-8324e800-6d1b-11ea-8a71-e16f4fe0ef8e.jpg)
