### ISSUE TITLE
UKLN-Сhernivtsi Airport-CHERNIVTSI-UKRAINE

### ISSUE THREAD

**Issue by gzhynko** [InfiniteFlightAirportEditing/Airports#4643]
# Airport Name

Сhernivtsi Intl

# Country?

Ukraine

# Improvements that need to be made?

Redo from Scratch

# Are you working on this airport?

Yep

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by gzhynko** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/75640588-5a299f80-5c14-11ea-9fcf-7ef529bdf369.jpg)
