### ISSUE TITLE
KSBD-San Bernardino International Airport-CALIFORNIA-USA 

### ISSUE THREAD

**Issue by jakey200** [InfiniteFlightAirportEditing/Airports#4644]
# Airport Name

San Bernardino International

# Country?

USA

# Improvements that need to be made?

Redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

10k+

**Comment by jakey200** [comment]
Sent for OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78694415-fa897880-78d2-11ea-88cb-634b5d283168.jpg)
