### ISSUE TITLE
EDDM-Munich Airport-BAVARIA-GERMANY

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#465]
Munich

**Comment by HenrikBerg02** [comment]
Duplicate. Continue in this issue: https://github.com/InfiniteFlightAirportEditing/Airports/issues/180

**Comment by Swang007** [comment]
So did this happen or does it still need to be redone?

**Comment by samuelandersson** [comment]
It doesn't seem like it happened @Swang007. Since it's a suggestion it further proves that argument.

**Comment by Swang007** [comment]
Might do it if I have time in the next few weeks

**Comment by moritzbabl** [comment]
@Swang007 be careful with the eastern apron, the easternmost building where planes are parked has been rebuilt to a third terminal which resulted in aerial pictures showing closed aprons which are now used again, there may also be some parking spots which were only temporarily in use (the pictures on google earth are the latest I found on the Internet by now)

**Comment by kilt46** [comment]
This does not contain full compliment of gates. Also terminal buildings are poor.

**Comment by moritzbabl** [comment]
I would like to redo this one and fix it 👍🏼

**Comment by IceBlue02** [comment]
@moritzbabl have you done this or are still interested?

**Comment by moritzbabl** [comment]
Not done yet, but still very interested 😉

**Comment by moritzbabl** [comment]
Sent for approval

**Comment by dushyants19** [comment]
done, great details and roads which @moritzbabl cant wait to get to drive his A380 on

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19626362/8b962984-98f5-11e6-90d9-6fad9c318c01.png)

**Comment by moritzbabl** [comment]
Randomly removed buildings need to be fixed
