### ISSUE TITLE
SJOG-Ariquemes Airport-RONDONIA-BRAZIL

### ISSUE THREAD

**Issue by carloszferreira** [InfiniteFlightAirportEditing/Airports#4650]
# Airport Name

Ariquemes
# Country?
Brazil
# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?
Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by carloszferreira** [comment]
Airport submitted for approval.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/77351381-72c13d00-6d1c-11ea-8852-4d4c55958b0d.jpg)
