### ISSUE TITLE
KSTS-Charles M. Schulz/Sonoma County Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by jakey200** [InfiniteFlightAirportEditing/Airports#4652]
# Airport Name

Charles M. Schulz/Sonoma County Airport

# Country?

USA

# Improvements that need to be made?

Full redo

# Are you working on this airport?

Yep

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by jakey200** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78409059-24932000-75df-11ea-9669-2f9e1c3fd3f5.jpg)

**Comment by MajorTomMueller** [comment]
The Airport has numerous overlapping and duplicate spawns:
https://gist.github.com/carmichaelalonso/e5f7a8bd5a61b4f1f82f629f09777bc0
https://gist.github.com/carmichaelalonso/652d032d7fe3683cbf8d88365ff5a690

**Comment by kztmtn** [comment]
Fixed by @jakey200

**Comment by MajorTomMueller** [comment]
still numerous overlaping spawns:
https://gist.github.com/carmichaelalonso/97ec814264dc4488aecdaec06cfc6cc0

**Comment by jakey200** [comment]
None here. It's all fine for me.

**Comment by MajorTomMueller** [comment]
If it is all fine it wouldn‘t bring a error in Cam‘s parsing. If you close this again without fixing I will talk to the administrators about the consequences!

**Comment by jakey200** [comment]
Unassign me please, no issue is actually present.

**Comment by MajorTomMueller** [comment]
Parsing errors listed assumed to be caused by processing old files acourding to @RyanEpps

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/86470461-1dc09a00-bd01-11ea-9bd7-b921cff4fa7b.png)
