### ISSUE TITLE
0Q9-Sonoma Skypark-CALIFORNIA-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#4657]
# Airport Name

Sonoma Skypark

# Country?

USA

# Improvements that need to be made?

Full redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by brennanhackard** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/77240043-37116080-6bc0-11ea-8d00-323e6079c82e.jpg)
