### ISSUE TITLE
KPSC-Tri Cities Airport-WASHINGTON-USA

### ISSUE THREAD

**Issue by IFC-PlaneCrazy** [InfiniteFlightAirportEditing/Airports#4658]
# Airport Name

Tri-Cities Airport

# Country?

USA

# Improvements that need to be made?

Full redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by IFC-PlaneCrazy** [comment]
Sent to OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/89474789-38e15800-d74c-11ea-9a80-f854959bd4bb.png)
