### ISSUE TITLE
DTTJ-Djerba Zarzis Airport-MEDENINE-TUNISIA

### ISSUE THREAD

**Issue by liamkirky** [InfiniteFlightAirportEditing/Airports#4659]
# Airport Name

DJERBA ZARZIS

# Country?

Tunisia

Full redo

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

10k

**Comment by liamkirky** [comment]
Sent to OR!

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/77343671-d3e31380-6d10-11ea-8e75-99fe17877db3.jpg)
