### ISSUE TITLE
KMVY

### ISSUE THREAD

**Issue by Ksisky** [InfiniteFlightAirportEditing/Airports#466]

**Comment by dushyants19** [comment]
Done. [Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/f931ff5f634f55a8762dfc956c31751135a85ef6)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17277382/14e5286a-5707-11e6-9874-850453da71a7.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17653424/f220d96e-625a-11e6-8fac-c809e4fd3adb.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17653425/f9ff3fa4-625a-11e6-8c67-3d24f8785c57.png)
