### ISSUE TITLE
VAJJ-Juhu Airport-MAHARASHTRA-INDIA

### ISSUE THREAD

**Issue by akshay2777** [InfiniteFlightAirportEditing/Airports#4661]
# Airport Name

Juhu Airport

# Country?

India

# Improvements that need to be made?

From scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low Priority

**Comment by FlightGeekYuta** [comment]
I could try to do it as my first work

**Comment by hari-shreyas** [comment]
Hello Akshay? Are you still working on this airport?
Or can I take over this airport?

**Comment by MajorTomMueller** [comment]
Better tag him:
@akshay2777 , still active?

**Comment by hari-shreyas** [comment]
Akshay contacted me via PMs in the slack workspace saying I can take over this airport. I would like to be assigned to it.
Thanks, Akshay!

**Comment by kilt46** [comment]
![Uploading image.png…]()

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/99909575-046bba80-2caf-11eb-892c-b77fbbed1922.png)
