### ISSUE TITLE
ZGDY-Zhangjiajie Hehua Airport-HUNAN-CHINA

### ISSUE THREAD

**Issue by AnthonyCK** [InfiniteFlightAirportEditing/Airports#4662]
# Airport Name

Zhangjiajie Hehua Airport

# Country?

China

# Improvements that need to be made?

New Airport

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by AnthonyCK** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/77239367-bf8c0300-6bb8-11ea-84d7-4a389f64bd47.jpg)
