### ISSUE TITLE
FQQL-Quelimane Airport-ZAMBEZIA-MOZAMBIQUE 

### ISSUE THREAD

**Issue by victormw22** [InfiniteFlightAirportEditing/Airports#4663]
# Airport Name

< Quelimane Airport >

# Country?

< Mozambique >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/77656575-d5038300-6f52-11ea-8698-c4c18ed7958a.jpg)
