### ISSUE TITLE
KIPL-Imperial County Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#4664]
# Airport Name

Imperial County Airport

# Country?

USA

# Improvements that need to be made?

Full redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78409446-10035780-75e0-11ea-8bfe-a66aac03c33f.jpg)
