### ISSUE TITLE
ZSCN-Nanchang Changbei International Airport-JIANGXI-CHINA

### ISSUE THREAD

**Issue by AnthonyCK** [InfiniteFlightAirportEditing/Airports#4666]
# Airport Name

Nanchang Changbei International Airport

# Country?

China

# Improvements that need to be made?

Redo from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

10000ft+

**Comment by AnthonyCK** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/77344823-84054c00-6d12-11ea-8149-007b116d3c6e.jpg)
