### ISSUE TITLE
VVCS-Con Dao Airport-BA RIA VUNG TAU-VIETNAM

### ISSUE THREAD

**Issue by IFUA2003** [InfiniteFlightAirportEditing/Airports#4667]
# Airport Name

< Con Dao Airport>

# Country?

< Vietnam >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by IFUA2003** [comment]
![2DB4DEB4-B6FC-4498-A35C-65EF0A23631D](https://user-images.githubusercontent.com/43931356/76407216-9223a600-63bd-11ea-8704-ad811708f04c.jpeg)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78413801-878cb300-75ef-11ea-90b8-9716a3e1a28f.jpg)
