### ISSUE TITLE
VVTX-Bai Thuong Airport-THANH HOA-VIETNAM

### ISSUE THREAD

**Issue by MinhNguyN** [InfiniteFlightAirportEditing/Airports#4668]
# Airport Name

< Bai Thuong Airport >

# Country?

< Viet Nam >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78414068-beaf9400-75f0-11ea-84c9-1330bb6da2e7.jpg)
