### ISSUE TITLE
VVCM-Ca Mau Airport-CA MAU-VIETNAM

### ISSUE THREAD

**Issue by IFUA2003** [InfiniteFlightAirportEditing/Airports#4669]
# Airport Name

< Ca Mau Airport >

# Country?

< Vietnam >

# Improvements that need to be made?

< This airport will have to be done from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by IFUA2003** [comment]
![E5AF55A9-B64F-4024-AF52-01A3A1772C90](https://user-images.githubusercontent.com/43931356/76406695-c185e300-63bc-11ea-8242-1684918b12df.jpeg)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78413556-4b0c8780-75ee-11ea-89f1-623f0b20abc5.jpg)
