### ISSUE TITLE
EGKA

### ISSUE THREAD

**Issue by Zimnaan** [InfiniteFlightAirportEditing/Airports#467]
Shoreham Airport has changed its name to Brighton City Airport.

**Comment by dushyants19** [comment]
Ill do it

**Comment by dushyants19** [comment]
Redo completed, Name not changed.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17251235/68572e8a-556d-11e6-9bd8-c25e16ef877e.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18258980/b552dad6-73a4-11e6-924e-a0e093a98bb8.png)

**Comment by moritzbabl** [comment]
updated by @ItsW1ll
