### ISSUE TITLE
VVRG-Rach Gia Airport-KIEN GIANG-VIETNAM

### ISSUE THREAD

**Issue by MinhNguyN** [InfiniteFlightAirportEditing/Airports#4670]
# Airport Name

< Rach Gia Airport >

# Country?

< Viet Nam >

# Improvements that need to be made?

< This airport will have to be done from scratch, which includes adding runways, taxiways, parking locations, boundaries... >

# Are you working on this airport?

< I will >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MajorTomMueller** [comment]
Please respond in slack.

**Comment by Alohahahahaha** [comment]
I don't have slack ULR

Vào Th 4, 11 thg 3, 2020 vào lúc 15:14 Major Tom <notifications@github.com>
đã viết:

**Comment by MajorTomMueller** [comment]
To be Ort of our Slack workspace is a prerequisite to edit airports.thats in Page 8 of the beginners guide https://airportediting.com/docs/IFAE_Beginners_Guide.pdf

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78413949-2b765e80-75f0-11ea-9d53-5bf334110cd7.jpg)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112737341-ded61280-8f27-11eb-80a1-c23ef48c6baa.png)
