### ISSUE TITLE
KFYG-Washington Regional Airport-MISSOURI-USA

### ISSUE THREAD

**Issue by WannaWinItAllDay** [InfiniteFlightAirportEditing/Airports#4672]
# Airport Name

< Washington Regional Airport >

# Country?

< United States >

# Improvements that need to be made?

< Make from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78413301-2bc12a80-75ed-11ea-91b2-9ee1ce3768d6.jpg)
