### ISSUE TITLE
UUEM-Tver Airport-TVER-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#4673]
# Airport Name

< Migalovo Tver AirBase >

# Country?

< Russia >

# Improvements that need to be made?

< Will be redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MajorTomMueller** [comment]
You are not supposed to close issues!

**Comment by AleksanderIF** [comment]
I'll do it

**Comment by AleksanderIF** [comment]
@MajorTomMueller, so can I redo this airport?

**Comment by MajorTomMueller** [comment]
Yes

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/80240250-eb772a00-8637-11ea-9666-5d43c5087f3e.jpg)
