### ISSUE TITLE
DNPO-Port Harcourt International Airport-OMAGWA-NIGERIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#4674]
# Airport Name

< Port Harcourt International Airport >

# Country?

< Nigeria >

# Improvements that need to be made?

< Will be redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/84556381-ff5e1480-ace7-11ea-9afe-2c8c8d465ee4.png)
