### ISSUE TITLE
EDAE-Verkehrslandeplatz Eisenhüttenstadt-Frankfurt-BRANDENBURG-GERMANY

### ISSUE THREAD

**Issue by rich-art-02** [InfiniteFlightAirportEditing/Airports#4675]
# Airport Name

Verkehrslandeplatz Eisenhüttenstadt - Frankfurt

# Country?

Germany

# Improvements that need to be made?

redo from scratch

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by rich-art-02** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/77239227-f52fec80-6bb6-11ea-8009-6ce2f48e462a.jpg)
