### ISSUE TITLE
VVVD-Van Don International Airport-QUANG NINH-VIETNAM

### ISSUE THREAD

**Issue by MinhNguyN** [InfiniteFlightAirportEditing/Airports#4676]
# Airport Name

Van Don International Airport

# Country?

Viet Nam

# Improvements that need to be made?

This is a new airport that's open in late 2018, I want it added to the game

# Are you working on this airport?

Yes

# Airport Priority? (10000ft+ Runway)

Runway 03/21 11811ft (=3600m)

**Comment by MajorTomMueller** [comment]
https://vnaic.vn/images/stories/vnaic.vn/SanPhamDichVu/AIPVietNam/Related%20Links/2019-03-AMDT/html/eAIP/AD-2.VVVD-en-GB.html#AD-2.VVVD

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/80316250-ff0ac800-87d2-11ea-85db-ced93863daaf.jpg)
