### ISSUE TITLE
URMM-Mineralnyye Vody Airport-NORTH KAUKASIA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#4677]
# Airport Name

< Mineralnyye Vody Airport >

# Country?

< Russia >

# Improvements that need to be made?

< Rework from the scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< GP2 - 12/30 (12795ft) >

**Comment by MajorTomMueller** [comment]
@AleksanderIF This is the third one you are assigned now. This is the limit. Before you open a mother issue you have to Finish one of the three and get it past OR.

**Comment by AleksanderIF** [comment]
Ok

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/80315589-f1534380-87ce-11ea-92ec-830c845ade26.jpg)
