### ISSUE TITLE
SCFM-Capitán Fuentes Martínez Airport-MAGALLANES Y ANTÁRTICA CHILENA-CHILE

### ISSUE THREAD

**Issue by HymenopusC** [InfiniteFlightAirportEditing/Airports#4678]
# Airport Name

Capitan Fuentes Martinez Airport

# Country?

Chile

# Improvements that need to be made?

complete redo

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78406774-ba2bb100-75d9-11ea-882a-09a01941b016.jpg)
