### ISSUE TITLE
CYYZ-Toronto Pearson International Airport-ONTARIO-CANADA

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#468]
Toronto Pearson International Airport, Ontario, Canada.

**Comment by RileyDunshea** [comment]
Completed

**Comment by kilt46** [comment]
Airport completely redone
![image](https://cloud.githubusercontent.com/assets/14023167/17276529/29c59842-56f2-11e6-9237-78cf0dc7a013.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17278042/ee904102-5717-11e6-87d6-5693adcc4ab7.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17278043/f6852b0c-5717-11e6-809d-8c9a962dc293.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17278135/b97f7ca0-571a-11e6-991f-5bd96702daaf.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17278137/c0a7003e-571a-11e6-9f7a-fe5f283ebbff.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17643024/aa1a9d96-6122-11e6-8cdd-238a9e4e22ab.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17643026/b58511fc-6122-11e6-9973-1c8ef89f6e4b.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17643028/beb1282e-6122-11e6-8fe6-b63cf40eb6ba.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17643029/c7dbb248-6122-11e6-9433-1076463e0924.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17643032/d39c5524-6122-11e6-988c-940fe5b70767.png)

**Comment by kilt46** [comment]
Airport was edited. Buildings need removed

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45921933-7359e880-be85-11e8-8730-c7eee812acb1.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/58920987-07fe3100-870b-11e9-8526-14003fa4f795.jpg)
