### ISSUE TITLE
KRDD-Redding Municipal Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#4680]
# Airport Name

Redding Muni

# Country?

🇺🇸

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yeah

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by brennanhackard** [comment]
Sent to OR :D

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78699975-1b55cc00-78db-11ea-93dc-32d7a1c42e64.jpg)
