### ISSUE TITLE
Duplicate

### ISSUE THREAD

**Issue by andreagrr** [InfiniteFlightAirportEditing/Airports#4683]
# Airport Name

Edwards Air Force Base

# Country?

California, USA

# Improvements that need to be made?

Some spawn point 

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

10000ft+ Runway

**Comment by MajorTomMueller** [comment]
https://github.com/InfiniteFlightAirportEditing/Airports/issues/242
