### ISSUE TITLE
KTNX-Tonopah Test Range-NEVADA-USA

### ISSUE THREAD

**Issue by andreagrr** [InfiniteFlightAirportEditing/Airports#4684]
# Airport Name

Tonopah Test Range Airport

# Country?

Nevada, USA

# Improvements that need to be made?

Make apron, taxiways and spawn point

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

10000ft+ Runway

**Comment by MajorTomMueller** [comment]
Good Luck! Not realy a beginners project....

**Comment by andreagrr** [comment]
Thank you!

**Comment by Czechoslovaki** [comment]
@andreagrr how's this going?

**Comment by liamkirky** [comment]
Can I do this please instead of LTCK?

**Comment by MajorTomMueller** [comment]
![KTNX-git](https://user-images.githubusercontent.com/26853210/130255063-e9e3db02-f58b-44cd-b4da-c9c664a37356.png)
