### ISSUE TITLE
36S-Happy Camp Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by tomthetank46** [InfiniteFlightAirportEditing/Airports#4686]
# Airport Name

Happy Camp

# Country?

United States

# Improvements that need to be made?

Full rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/77349135-5243b380-6d19-11ea-81af-799afc21a2f8.jpg)
