### ISSUE TITLE
KCOU-Columbia Regional Airport-MISSOURI-USA

### ISSUE THREAD

**Issue by WannaWinItAllDay** [InfiniteFlightAirportEditing/Airports#4687]
# Airport Name

Columbia Regional Airport

# Country?

United States

# Improvements that need to be made?

Needs a refresh, draw taxi lines. Add more spawns, etc...

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by brennanhackard** [comment]
I'll edit this one.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122673148-caa35980-d194-11eb-86f7-2b92924687b3.png)
