### ISSUE TITLE
EDAV-Verkehrslandeplatz Eberswalde Finow-BRANDENBURG-GERMANY

### ISSUE THREAD

**Issue by rich-art-02** [InfiniteFlightAirportEditing/Airports#4689]
# Airport Name

Verkehrslandeplatz Eberswalde Finow

# Country?

Germany

# Improvements that need to be made?

redo from scratch

# Are you working on this airport?

yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by rich-art-02** [comment]
in OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78678294-21d64a80-78bf-11ea-9cb7-4e14914369bc.jpg)
