### ISSUE TITLE
EHLV-Langeveld Airfield-SÜDHOLLAND-NETHERLANDS

### ISSUE THREAD

**Issue by rich-art-02** [InfiniteFlightAirportEditing/Airports#4690]
# Airport Name

Langeveld Airfield

# Country?

NETHERLANDS

# Improvements that need to be made?

redo from scratch

# Are you working on this airport?

no

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by rich-art-02** [comment]
in OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78680512-f7d25780-78c1-11ea-9b25-1c8c11dfe81b.jpg)
