### ISSUE TITLE
L05-Kern Valley Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by tomthetank46** [InfiniteFlightAirportEditing/Airports#4691]
# Airport Name

Kern Valley

# Country?

USA

# Improvements that need to be made?

Full redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by AsternAviation** [comment]
I'll edit it. Redoing from scratch.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122681669-22ed5200-d1bb-11eb-99a9-558d09e7ca57.png)
