### ISSUE TITLE
ID74-Sulphur Creek Ranch-IDAHO-USA

### ISSUE THREAD

**Issue by tomthetank46** [InfiniteFlightAirportEditing/Airports#4692]
# Airport Name

Sulphur Creek Ranch

# Country?

USA

# Improvements that need to be made?

Full redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/91919643-3bbc6380-ec8c-11ea-82f7-5e48a4fb9eed.png)
