### ISSUE TITLE
49X-Chemehuevi Valley Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by kailas23** [InfiniteFlightAirportEditing/Airports#4695]
# Airport Name

< 49X >

# Country?

< USA>

# Improvements that need to be made?

<Full redo >

# Are you working on this airport?

<Yes>

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MajorTomMueller** [comment]
You failed the basic test:
49X is the LID Code, not an Airport name...

**Comment by jakey200** [comment]
The name is Chemehuevi Valley airport

**Comment by ShaneAviation** [comment]
I can redo this one.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115962972-5b3a2200-a4e3-11eb-8dd4-8ae83eb848e9.png)
