### ISSUE TITLE
ZGKL-Guilin Liangjiang Airport-GUANGXI-CHINA

### ISSUE THREAD

**Issue by AnthonyCK** [InfiniteFlightAirportEditing/Airports#4697]
# Airport Name

Guilin Liangjiang Airport

# Country?

China

# Improvements that need to be made?

Redo from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

10000ft+

**Comment by AnthonyCK** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78404244-59e64080-75d4-11ea-969b-93b5a5321b08.jpg)
