### ISSUE TITLE
EDBF-Verkehrslandeplatz Fehrbellin-BRANDENBURG-GERMANY

### ISSUE THREAD

**Issue by rich-art-02** [InfiniteFlightAirportEditing/Airports#4698]
# Airport Name

Verkehrslandeplatz Fehrbellin

# Country?

Germany

# Improvements that need to be made?

redo from scratch

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by MajorTomMueller** [comment]
Verkehrslandeplatz ... Airport? Really @brunocr98? 🙄
A „Verkehrslandplatz“ is German officialese for a small public, often commercial, aerodrome. It is the medium aviation law aerodrome category between glidingfield and airport.

**Comment by rich-art-02** [comment]
in OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78677809-8f35ab80-78be-11ea-9a7e-e31b053cfee5.jpg)
