### ISSUE TITLE
SPJL-Juliaca Airport-PUNO-PERU

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#47]
Please redraw me

♻️

**Comment by bavAVIA** [comment]
I'm quickly doing this one. Please assign.

**Comment by bavAVIA** [comment]
I'm still not assign. Please assign me.

**Comment by bavAVIA** [comment]
Sent in to e-mail, awaiting review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21467190/d3abaf56-c9aa-11e6-94e9-33ad3e727581.png)
