### ISSUE TITLE
1B6

### ISSUE THREAD

**Issue by RileyDunshea** [InfiniteFlightAirportEditing/Airports#470]
Hopedale, Needs a complete re-do

**Comment by samuelandersson** [comment]
@RileyDunshea Any progress here?

**Comment by RileyDunshea** [comment]
finished. i seem to have lost my ability to assign myself @carmichaelalonso

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20649493/0a7e8b40-b487-11e6-98eb-a825457935b1.png)

**Comment by RileyDunshea** [comment]
Why were the parking spots I added removed?

**Comment by kilt46** [comment]
With the silhouettes of the aircraft in place there was simply not enough room to taxi between. I did not check the satellite overlay as it is not even a 4X ICAO field. There are more than enough spawn points for a field of that size.

**Comment by RileyDunshea** [comment]
Ok just making sure.
