### ISSUE TITLE
FQIN-Inhambane Airport-INHAMBANE-MOZAMBIQUE

### ISSUE THREAD

**Issue by victormw22** [InfiniteFlightAirportEditing/Airports#4700]
# Airport Name

< Inhambane >

# Country?

< Mozambique>

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes>

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by victormw22** [comment]
sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78406432-fe6a8180-75d8-11ea-9ab3-44781a0ec1f3.jpg)
