### ISSUE TITLE
KAFW-Fort Worth Alliance Airport-TEXAS-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#4702]
# Airport Name

Fort Worth Alliance Airport

# Country?

USA / United States of America 

# Improvements that need to be made?

Full work from scratch

# Are you working on this airport?

Previously working. PC has major issues and is not able to complete work.

Edit 22/08/2020: Will continue work on new PC when next working on this alone.

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

2 10,000ft+ runways. Very close to KDFW.

**Comment by rich-art-02** [comment]
@MajorTomMueller can somebody assign me to this airport pls

**Comment by ECoops-123** [comment]
> Edit 22/08/2020: Will continue work on new PC when next working on this alone.

Guess I'm not going to be working on this anymore. Could not re-claim becuase all airports currently are in Review 


Re-rework of the airport (taken yesterday) after I edited it once before but wasn't good enough quality. Moving onto another project.
![ae40cf48bc512e59326f63b915dadfd2b085d4ca](https://user-images.githubusercontent.com/59462519/91336047-37460580-e7c9-11ea-88de-c43d1312c803.png)

**Comment by rich-art-02** [comment]
@MajorTomMueller please deasssign me and assign @ECoops-123 to this issue, thanks

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/97752908-e7cecf00-1ac2-11eb-9c41-4b3206964be3.png)
