### ISSUE TITLE
EFME-Menkijarvi Airport-WESTERN FINLAND-FINLAND

### ISSUE THREAD

**Issue by carloszferreira** [InfiniteFlightAirportEditing/Airports#4703]
♻️

**Comment by carloszferreira** [comment]
Sorry. Airport ICAO is wrong

**Comment by kztmtn** [comment]
![EFME-git](https://user-images.githubusercontent.com/46369763/78320445-6c488600-75a4-11ea-804a-03a664e7d669.jpg)
