### ISSUE TITLE
SNDT-Diamantina Airport-MINAS GERAIS-BRAZIL

### ISSUE THREAD

**Issue by carloszferreira** [InfiniteFlightAirportEditing/Airports#4704]
# Airport Name

Diamantina

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by carloszferreira** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/79266020-545ae700-7e6d-11ea-8c7a-70f88f376fa0.jpg)
