### ISSUE TITLE
S12-Albany Municipal Airport-OREGON-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#4705]
# Airport Name

Albany Municipal

# Country?

USA

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/77656031-0b8cce00-6f52-11ea-8309-f4bc97f512fc.jpg)
