### ISSUE TITLE
LFCR-Rodez-Marcillac Airport-MIDI-PYRENEES-FRANCE

### ISSUE THREAD

**Issue by FlyBoii31** [InfiniteFlightAirportEditing/Airports#4708]
**#** Airport Name

< Rodez-Marcillac Airport >

# Country?

< France >

# Improvements that need to be made?

< Full Rework >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78674495-12083780-78ba-11ea-9986-b2efd0f2fc93.jpg)
