### ISSUE TITLE
KUAO-Aurora State Airport-OREGON-USA

### ISSUE THREAD

**Issue by Oskapew** [InfiniteFlightAirportEditing/Airports#4709]
# Airport Name

KUAO

# Country?

United States of America

# Improvements that need to be made?

Many ramps/taxiways are out of date. Only one spawn available. 

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low Priority

**Comment by Czechoslovaki** [comment]
@Oskapew are you still working on this?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/99004264-65073480-2504-11eb-8499-6585b635928a.png)
