### ISSUE TITLE
EGMD-Lydd Airport-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by ItsW1ll** [InfiniteFlightAirportEditing/Airports#471]
Some small improvements needed.

**Comment by Will171** [comment]
Full redo completed- issue closed

**Comment by kilt46** [comment]
This airport is NOT in the library

**Comment by Will171** [comment]
Not my problem, I emailed it off.

**Comment by dushyants19** [comment]
I'll move the file

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20598211/a2e229b8-b20d-11e6-8974-62b9da778c7a.png)

**Comment by moritzbabl** [comment]
updated

**Comment by kilt46** [comment]
Please check charts
![image](https://user-images.githubusercontent.com/14023167/36820916-0f34fe74-1cb6-11e8-8641-bf1eccf356ed.png)
![image](https://user-images.githubusercontent.com/14023167/36820935-210d946c-1cb6-11e8-8905-920b041a84c5.png)

**Comment by ItsW1ll** [comment]
Hi there kilt. In the latest redraw of the airport I decided not to include gate 8 as a t SAR hangar has been built over the gate. I have checked the notams of the airport and gate 8 remains closed unti further notice.

**Comment by MajorTomMueller** [comment]
... rework as by Kilt supposed ...

**Comment by MajorTomMueller** [comment]
![EGMD](https://user-images.githubusercontent.com/26853210/103135785-c5b49000-46b2-11eb-815a-5acca880a32d.png)

**Comment by MajorTomMueller** [comment]
no full rework, fixes by @ECoops-123

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103152687-06161b80-4750-11eb-81b5-43993821d24a.png)
