### ISSUE TITLE
SAWT-El Turbio Airport-SANTA CRUZ-ARGENTINA

### ISSUE THREAD

**Issue by victormw22** [InfiniteFlightAirportEditing/Airports#4715]
# Airport Name

< El Turbio >

# Country?

< Argentina >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by victormw22** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78404692-51dad080-75d5-11ea-96af-c339e439ce15.jpg)
