### ISSUE TITLE
CL84-Ahlem Farms-CALIFORNIA-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#4716]
# Airport Name

Ahlem Farms

# Country?

USA

# Improvements that need to be made?

From scratch

# Are you working on this airport?

Completed, yes.

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Smallest airport ever, literally. No priority.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78411729-10ebb780-75e7-11ea-847a-5b54e52d207e.jpg)
