### ISSUE TITLE
L70-Agua Dulce Airpark-CALIFORNIA-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#4717]
# Airport Name

Agua Dulce Airpark

# Country?

USA

# Improvements that need to be made?

From scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78412077-73918300-75e8-11ea-962c-0a6cce75f822.jpg)
