### ISSUE TITLE
SNFU-Frutal Airport-MINAS GERAIS-BRAZIL

### ISSUE THREAD

**Issue by victormw22** [InfiniteFlightAirportEditing/Airports#4719]
# Airport Name

< Frutal>

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low>

**Comment by victormw22** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78408653-15f83900-75de-11ea-98b2-666a0aac83b6.jpg)
