### ISSUE TITLE
KSDF-Louisville International-Standiford Field Airport-KENTUCKY-USA

### ISSUE THREAD

**Issue by DavidCutler** [InfiniteFlightAirportEditing/Airports#472]
Kentucky

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20238077/81973c26-a8a8-11e6-8538-c19564682474.png)

**Comment by brunocr98** [comment]
I'll be doing some improvements and updates (approved by an admin).

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28985567-c2398116-7928-11e7-9885-0ab9ed487c5d.png)

**Comment by MajorTomMueller** [comment]
rework requested

**Comment by brennanhackard** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/89475082-e6546b80-d74c-11ea-961b-71df819e1259.png)
