### ISSUE TITLE
0O4-Corning Municipal Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#4720]
# Airport Name

Corning Municipal Airport

# Country?

🇺🇸 

# Improvements that need to be made?

redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by brennanhackard** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78411370-db929a00-75e5-11ea-9d2a-8d88ac78b41a.jpg)
