### ISSUE TITLE
MY56-Robertson Field Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by danisrils39** [InfiniteFlightAirportEditing/Airports#4721]
# Airport Name

Robertson Field Airport

# Country?

US

# Improvements that need to be made?

Scratg

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

N/a

**Comment by danisrils39** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78412469-d5062180-75e9-11ea-8915-7d67e9345444.jpg)
