### ISSUE TITLE
KDEC-Decautur Airport-ILLINOIS-USA

### ISSUE THREAD

**Issue by Erukumon** [InfiniteFlightAirportEditing/Airports#4724]
Urgench International Airport, I'll do it

**Comment by Erukumon** [comment]
I am no longer redoing UTNU. Conditions at where I live is getting worse because of COVID-19. Sorry for any inconvenience.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/87852543-7333a400-c8c8-11ea-8a49-c233b1d084a5.png)
