### ISSUE TITLE
KCCB-Cable Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by HymenopusC** [InfiniteFlightAirportEditing/Airports#4725]
# Airport Name

Cable Airport

# Country?

USA (California)

# Improvements that need to be made?

Complete Redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by Czechoslovaki** [comment]
@HymenopusC how's this going?

**Comment by kilt46** [comment]
![Uploading image.png…]()
