### ISSUE TITLE
KMKY-Marco Island Airport-FLORIDA-USA

### ISSUE THREAD

**Issue by victormw22** [InfiniteFlightAirportEditing/Airports#4726]
# Airport Name

< Marco Island >

# Country?

< US>

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< yes>

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78692286-06277000-78d0-11ea-9c14-c9647e7b0819.jpg)
