### ISSUE TITLE
PAEN-Kenai Airport-ALASKA-USA

### ISSUE THREAD

**Issue by Sashaz55** [InfiniteFlightAirportEditing/Airports#4727]
# Airport Name 

< Kenai Airport>

# Country?

< USA >

# Improvements that need to be made?

< Full Redo  >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by Czechoslovaki** [comment]
@Sashaz55 how's this going?

**Comment by Sashaz55** [comment]
Well, my Laptop broke while in the final stages of editing so I’ve put this on hold. I expect to get my pc finished up on the 4th so I’ll start again then.

**Comment by Sashaz55** [comment]
Unfortunately I can’t edit this airport any more. I’d like to request a switch. Z-Tube would like to take over.

**Comment by MajorTomMueller** [comment]
GitHub name of Z-TUbe?

**Comment by zhf21** [comment]
zhf21

**Comment by zhf21** [comment]
Thanks!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107147374-59fd4e00-6913-11eb-9fd5-94d24261e585.png)
