### ISSUE TITLE
LJBL-Lesce/Bled Airport-GORENJSKA-SLOVENIA

### ISSUE THREAD

**Issue by WannaWinItAllDay** [InfiniteFlightAirportEditing/Airports#4728]
# Airport Name

Lesce-Bled Airport

# Country?

Slovenia

# Improvements that need to be made?

Airport needs to be made

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by liamkirky** [comment]
Editor active? If not could I do it?

**Comment by kilt46** [comment]
![Uploading image.png…]()

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/99990932-0b133400-2d7a-11eb-9201-d43ce0683568.png)
