### ISSUE TITLE
LFTZ-Saint Tropez/La Mole Airport-PROVENCE-ALPES-COTE D'AZUR-FRANCE

### ISSUE THREAD

**Issue by bavariaaviation** [InfiniteFlightAirportEditing/Airports#4730]
# Airport Name

Saint Tropez/La Mole 

# Country?

France

# Improvements that need to be made?

Complete rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by bavariaaviation** [comment]
Sent for review.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78407093-640b3d80-75da-11ea-8178-4a90b893b06f.jpg)
