### ISSUE TITLE
LESU-Andorra/La Seu d'Urgell Airport-CATALONIA-SPAIN

### ISSUE THREAD

**Issue by bavariaaviation** [InfiniteFlightAirportEditing/Airports#4731]
# Airport Name

Andorra/La Seu d'Urgell

# Country?

Spain

# Improvements that need to be made?

Complete rework

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78408096-a0d83400-75dc-11ea-9f8e-245d077ff00f.jpg)
