### ISSUE TITLE
VVCA-Chu Lai Airport-QUANG NAM-VIETNAM

### ISSUE THREAD

**Issue by IFUA2003** [InfiniteFlightAirportEditing/Airports#4732]
# Airport Name

< Chu Lai Airport>

# Country?

< Vietnam >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by IFUA2003** [comment]
![vvvv](https://user-images.githubusercontent.com/43931356/78518735-7d370880-77eb-11ea-876a-1e283a09a3b8.png)

**Comment by brunocr98** [comment]
Airport redone in this [commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/afd3fdc64ce786f04c4c3862b897993809f8e720).

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78682082-eee28580-78c3-11ea-800f-aaec490f1ddd.jpg)
