### ISSUE TITLE
KAUO-Auburn University Regional Airport-ALABAMA-USA

### ISSUE THREAD

**Issue by jasonbburks** [InfiniteFlightAirportEditing/Airports#4733]
# Airport Name

< Auburn Opelika Robert G Pitts Airport >

# Country?

< United States >

# Improvements that need to be made?

< The airport is not finished and the ILS is not correct. >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by Czechoslovaki** [comment]
Now open to anyone.

**Comment by Czechoslovaki** [comment]
I'll just snag this. Don't think it'll take too long.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106384576-2cebf100-6391-11eb-9611-be93b08c4bf5.png)
