### ISSUE TITLE
NY03-Klenawicus Airfield-NEW YORK-USA

### ISSUE THREAD

**Issue by EthanNFlyer22** [InfiniteFlightAirportEditing/Airports#4737]
# Airport Name

Klenawicus Airfield

# Country?

United States

# Improvements that need to be made?

Made from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by EthanNFlyer22** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/79279442-701db780-7e84-11ea-8a04-4dda125c5ca9.jpg)
