### ISSUE TITLE
0O9-Ward Field-CALIFORNIA-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#4738]
# Airport Name

Ward Field 

# Country?

🇺🇸 

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Sí

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by brennanhackard** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78411565-6d020c00-75e6-11ea-8ddd-c456d81627ca.jpg)
