### ISSUE TITLE
KSPB-Scappoose Industrial Airpark-OREGON-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#4739]
# Airport Name

Scappoose Industrial Airpark

# Country?

'Murica

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

da

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/83337980-6e1d8580-a285-11ea-8ec6-fd65bfa4b01a.png)
