### ISSUE TITLE
TNCS-Juancho E. Yrausquin Airport-SABA-CARIBBEAN NETHERLANDS

### ISSUE THREAD

**Issue by ItsW1ll** [InfiniteFlightAirportEditing/Airports#474]
More parking needed and needs lining up with wed imagery and runway heading needs to be changed. Possible redo needed. Good Luck!

**Comment by kilt46** [comment]
This is a NON-REGION airport. Please reserve 'Suggestion' for current airfields

**Comment by dushyants19** [comment]
Not non-region @kilt46 :)

**Comment by dushyants19** [comment]
Ill do it

**Comment by dushyants19** [comment]
Done

**Comment by Will171** [comment]
control tower and beacon have been placed outside of the boundary, will fix

**Comment by Will171** [comment]
Improvements Added.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20644669/d6b7acf8-b402-11e6-97f5-5aa39c9e8944.png)

**Comment by MajorTomMueller** [comment]
@danisrils39 saw that you got a free slot, assigned you now.

**Comment by MajorTomMueller** [comment]
So is this a design issue? Or why is this opened once? Why can’t it be worked on?

**Comment by MajorTomMueller** [comment]
![TNCS-git](https://user-images.githubusercontent.com/26853210/71307424-09acef00-23e6-11ea-90a4-315ea732ee4a.png)

**Comment by MajorTomMueller** [comment]
![TNCS-git](https://user-images.githubusercontent.com/26853210/106031427-2cb8d080-60c7-11eb-9fde-a16219acbd46.png)

**Comment by MajorTomMueller** [comment]
Rwy pavement changed
new FATO added
work road stumb added
Turns Lines added
