### ISSUE TITLE
PAFA-Fairbanks International Airport-ALASKA-USA

### ISSUE THREAD

**Issue by cptlogue** [InfiniteFlightAirportEditing/Airports#4741]
# Airport Name

PAFA

# Country?

United States

# Improvements that need to be made?

Needs to be redone

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

10,000ft+ Runway

**Comment by bavariaaviation** [comment]
Doing this.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/81997886-6b852400-9627-11ea-88d1-cfe3fe18d214.jpg)
