### ISSUE TITLE
NZKO-Kaikohe Airport-NORTHLAND-NEW ZEALAND

### ISSUE THREAD

**Issue by Lukeh0** [InfiniteFlightAirportEditing/Airports#4742]
# Airport Name

Kaikohe Airport

# Country?

New Zealand

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78672136-9f498d00-78b6-11ea-9bfd-66025e359cfd.jpg)
