### ISSUE TITLE
ZSJN-Jinan Yaoqiang Airport-SHANDONG-CHINA

### ISSUE THREAD

**Issue by AnthonyCK** [InfiniteFlightAirportEditing/Airports#4743]
# Airport Name

Jinan Yaoqiang Airport

# Country?

China

# Improvements that need to be made?

Redo from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

10000+

**Comment by AnthonyCK** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78671434-ad4ade00-78b5-11ea-8668-f1b339a22e93.jpg)
