### ISSUE TITLE
VVVH-Vinh Airport-NGHE AN-VIETNAM

### ISSUE THREAD

**Issue by MinhNguyN** [InfiniteFlightAirportEditing/Airports#4745]
# Airport Name

< Vinh International Airport >

# Country?

< Viet Nam >

# Improvements that need to be made?

< Redo whole airport >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MajorTomMueller** [comment]
already assigned to 3 other issues

**Comment by MinhNguyN** [comment]
can you unssigned me from the VVVD then sign me to this airport?

**Comment by brunocr98** [comment]
You've been cleared from the other airports you sent for review, so I'll re-assign you to this one again.

**Comment by MinhNguyN** [comment]
Thanks

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78679809-11bf6a80-78c1-11ea-8f28-d4ae42456365.jpg)
