### ISSUE TITLE
0Q3-Sonoma Valley Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#4747]
# Airport Name

Sonoma Valley Airport

# Country?

merica

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Sí

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by brennanhackard** [comment]
Sent to OR :D

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78694940-c8c4e180-78d3-11ea-9b92-e00b8c88ae78.jpg)
