### ISSUE TITLE
ESOW-Stockholm/Vasteras-STOCKHOLM-SWEDEN

### ISSUE THREAD

**Issue by Daniboi737** [InfiniteFlightAirportEditing/Airports#4748]
# Airport Name

Stockholm Vasteras

# Country?

Sweden

# Improvements that need to be made?

Redone from Scratch

# Are you working on this airport?

Yes, I will do it!

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by Daniboi737** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90313575-45477c80-ded3-11ea-81ea-4ad2cf06ed8d.png)
