### ISSUE TITLE
FHSH - Saint Helena Airport

### ISSUE THREAD

**Issue by cptlogue** [InfiniteFlightAirportEditing/Airports#4749]
# Airport Name

Saint Helena Airport

# Country?

Great Britain

# Improvements that need to be made?

Buildings need removed

# Are you working on this airport?

Yuh

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/87259914-2f7a0e00-c474-11ea-9401-11db4344bddd.png)
