### ISSUE TITLE
DIAP-Felix Houphouet Boigny International-ABIDJAN-IVORY COAST

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#475]
ABIDJAN, IVORY COAST

**Comment by kilt46** [comment]
AIRPORT REDRAWN

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20859331/9c4f25d6-b921-11e6-91ff-f8e5418479f0.png)

**Comment by brennanhackard** [comment]
Airport needs a rework. Up for grabs.

**Comment by AviationDash** [comment]
> Airport needs a rework. Up for grabs.

I am Willing to rework it, Just tell me what is missing and I will get to work ASAP

**Comment by Czechoslovaki** [comment]
@AviationDash without knowing who you are on our discord server, I cannot assign you. We also do not recommend such huge airports for newbies either.

**Comment by AviationDash** [comment]
> @AviationDash without knowing who you are on our discord server, I cannot assign you. We also do not recommend such huge airports for newbies either.

Ok, I dont think I was Invited to the discord Server, But What Airport is aviable and not that huge and see if I can try and rework it

**Comment by ECoops-123** [comment]
@AviationDash Message the [Airport Editing Team](https://community.infiniteflight.com/g/airportediting) on the community and we can we can get you on the Discord to proceed with your airport editing. Until then you are not allowed to have any operation or assignments here.

**Comment by AviationDash** [comment]
> @AviationDash Message the [Airport Editing Team](https://community.infiniteflight.com/g/airportediting) on the community and we can we can get you on the Discord to proceed with your airport editing. Until then you are not allowed to have any operation or assignments here.

Ok, And in the meantime, What Airport do you recommend starting with (When I get permission)

**Comment by AviationDash** [comment]
> @AviationDash Message the [Airport Editing Team](https://community.infiniteflight.com/g/airportediting) on the community and we can we can get you on the Discord to proceed with your airport editing. Until then you are not allowed to have any operation or assignments here.

I have messaged the Airport Editing Team, but still no response

**Comment by AviationDash** [comment]
> @AviationDash Message the [Airport Editing Team](https://community.infiniteflight.com/g/airportediting) on the community and we can we can get you on the Discord to proceed with your airport editing. Until then you are not allowed to have any operation or assignments here.

Hi there Ive joined the Infinite Flight Airport Editing team on Discord. You can find my Username as: AVMEX ID: #7789,
And hope to hear from you soon

**Comment by AviationDash** [comment]
@brunocr1050 Hi, Since Im new here and A bit New to WED What Airport do you recommend working on, Because I don't know if im qualified to work on big airports, so what airport are open, or small airports that need reworks

**Comment by GBKarp** [comment]
I would like to do this one, please.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114270908-83e6f580-99d4-11eb-9a19-f899ed74599f.png)
