### ISSUE TITLE
GMFO-Angads Airport-OUJDA-MOROCCO

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#4750]
# Airport Name

Oujda Angads International Airport

# Country?

Morocco

# Improvements that need to be made?

Work from scratch

# Are you working on this airport?

No, suggestion 

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/99977722-9e446d80-2d6a-11eb-827f-65522045b593.png)
