### ISSUE TITLE
O60-Cloverdale Municipal Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#4751]
# Airport Name

Cloverdale Municipal 

# Country?

California, USA 

# Improvements that need to be made?

Full rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low.

Sending off to OR once assigned, airport completed.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78693178-4509f580-78d1-11ea-95d2-2cb733bdc9fe.jpg)
