### ISSUE TITLE
NZRW-Ruawai Airport-NORTHLAND-NEW ZEALAND

### ISSUE THREAD

**Issue by Lukeh0** [InfiniteFlightAirportEditing/Airports#4752]
# Airport Name

Ruawai Airport

# Country?

New Zealand

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78673183-277c6200-78b8-11ea-8c94-689944dc88d1.jpg)
