### ISSUE TITLE
NZPI-Parakai Airport-AUCKLAND-NEW ZEALAND

### ISSUE THREAD

**Issue by Lukeh0** [InfiniteFlightAirportEditing/Airports#4753]
# Airport Name

Parakai Airport

# Country?

New Zealand

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78672806-84c3e380-78b7-11ea-9442-ea640cd37439.jpg)
