### ISSUE TITLE
L06-Furnace Creek Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by jakey200** [InfiniteFlightAirportEditing/Airports#4754]
# Airport Name

Furnace Creek

# Country?

USA

# Improvements that need to be made?

Redo

# Are you working on this airport?

Si

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by jakey200** [comment]
sent to review of officialness

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78696344-adf36c80-78d5-11ea-8d84-86012fb2a282.jpg)
