### ISSUE TITLE
M45-Alpine County-CALIFORNIA-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#4755]
# Airport Name

Alpine County Municipal 

# Country?

California, USA

# Improvements that need to be made?

Work from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78696807-4c7fcd80-78d6-11ea-9b5f-c776ecc8d80d.jpg)
