### ISSUE TITLE
KVWU-Waskish Municipal Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by danisrils39** [InfiniteFlightAirportEditing/Airports#4756]
# Airport Name

Waskish Municipal Airport

# Country?

USA

# Improvements that need to be made?

Scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

N/A

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78701430-696bcf00-78dd-11ea-967c-1dae4a2ec845.jpg)
