### ISSUE TITLE
VVDH-Dong Hoi Airport-QUANG BINH-VIETNAM

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#4757]
# Airport Name

< Dong Hoi Airport >

# Country?

< Vietnam >

# Improvements that need to be made?

< Work from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by DK1904** [comment]
Sent to OR

**Comment by brunocr1050** [comment]
@kilt46 this airport needs to be gated.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123344192-f5850900-d518-11eb-91b8-ba761d8342cd.png)
