### ISSUE TITLE
ULLV-Levashovo Air Base-SANKT PETERBURG-RUSSIA

### ISSUE THREAD

**Issue by Ryanairy55** [InfiniteFlightAirportEditing/Airports#4758]
# Airport Name

Saint Petersburg Levashovo

# Country?

Russia

# Improvements that need to be made?

I am making this airport from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

No airport priorities

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/82399750-32382400-9a2c-11ea-87b4-ba563422ec67.jpg)
