### ISSUE TITLE
EDWB-Bremerhaven Airport-BREMEN-GERMANY

### ISSUE THREAD

**Issue by bavariaaviation** [InfiniteFlightAirportEditing/Airports#4759]
# Airport Name

Bremerhaven Airport

# Country?

Germany

# Improvements that need to be made?

rework from scratch

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78678816-d7a19900-78bf-11ea-8e51-e86d086137db.jpg)
