### ISSUE TITLE
KUDD

### ISSUE THREAD

**Issue by IceBlue02** [InfiniteFlightAirportEditing/Airports#476]
SoCal.

Only parking runway spawns.

**Comment by dushyants19** [comment]
I'll do it.

**Comment by dushyants19** [comment]
Done. Cheers

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20649670/10194ccc-b48a-11e6-8c31-aeb9ec42dc7b.png)
