### ISSUE TITLE
EFHF-Helsinki-Malmi Airport-SOUTHERN FINLAND-FINLAND

### ISSUE THREAD

**Issue by NoahAllan** [InfiniteFlightAirportEditing/Airports#4760]
# Airport Name

< Helsinki Malmi  >

# Country?

< Finland >

# Improvements that need to be made?

< Adding all taxi lines, all spawn points, lighting >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by dklaffke** [comment]
@NoahAllan are you still working on this?

**Comment by NoahAllan** [comment]
@dklaffke No not anymore I lost all the progress and gave up. sorry for any inconvenience.

**Comment by GBKarp** [comment]
I wanna take this one please

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114270782-d5db4b80-99d3-11eb-97db-6dcb0d816a8c.png)
