### ISSUE TITLE
0Q4-Selma Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#4761]
# Airport Name

Selma Airport

# Country?

🇺🇸 

# Improvements that need to be made?

redone from scratch

# Are you working on this airport?

sí

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by brennanhackard** [comment]
Sent to OR :D

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78695345-5c96ad80-78d4-11ea-8657-9c00d5f1becd.jpg)
