### ISSUE TITLE
KCVO-Corvallis Municipal Airport-OREGON-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#4762]
# Airport Name

Corvallis Municipal Airport

# Country?

Murica

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

Ye

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78704865-f2393980-78e2-11ea-9cc8-50a040266268.jpg)
