### ISSUE TITLE
KHCO-Hallock Municipal Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by Gabe-Z** [InfiniteFlightAirportEditing/Airports#4765]
# Airport Name

Hallock Municipal Airport

# Country?

USA

# Improvements that need to be made?

Unedited

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by Gabe-Z** [comment]
The airport is now in OR. 

The airport was also done redo in less than an hour. Personal record for me. 🎉

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78702645-4d692d00-78df-11ea-85d4-4ae2aa06e1d0.jpg)
