### ISSUE TITLE
KLYV-Quentin Aanenson Field-MINNESOTA-USA

### ISSUE THREAD

**Issue by Gabe-Z** [InfiniteFlightAirportEditing/Airports#4766]
# Airport Name
Quentin Aanenson Field

# Country?

USA

# Improvements that need to be made?

Unedited
# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by Gabe-Z** [comment]
The airport is now in OR.

Also, no one has assigned me or add labels. I'm speedy 😂

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78703265-40007280-78e0-11ea-802e-ac06c994f9fb.jpg)
