### ISSUE TITLE
VVTH-Tuy Hoa Airport-PHU YEN-VIETNAM

### ISSUE THREAD

**Issue by MinhNguyN** [InfiniteFlightAirportEditing/Airports#4767]
# Airport Name

< Tuy Hoa >

# Country?

< Vietnam >

# Improvements that need to be made?

< Redo whole airport >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< 10000ft+ Runway >

**Comment by kztmtn** [comment]
RWY 9520ft

**Comment by MinhNguyN** [comment]
This airport is in PHU YEN not NAM TRUNG

**Comment by kztmtn** [comment]
Then you should mention it when you open the issue.

**Comment by MajorTomMueller** [comment]
https://vnaic.vn/images/stories/vnaic.vn/SanPhamDichVu/DAP-Viet-Nam/DAP%20website%20BDKT/Related%20Links/DAP/pdf/VVTH.pdf

**Comment by MinhNguyN** [comment]
Thanks I tried to find it but couldn't find it

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78689532-d165e980-78cc-11ea-8d87-a91c32a6a283.jpg)
