### ISSUE TITLE
VVCL-Cam Ly Airport-LAM DONG-VIETNAM

### ISSUE THREAD

**Issue by MinhNguyN** [InfiniteFlightAirportEditing/Airports#4768]
# Airport Name

< Cam Ly >

# Country?

< Viet Nam >

# Improvements that need to be made?

< redo from scratch >

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MajorTomMueller** [comment]
Abandoned since ages...
Deleted from repository

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/87255154-f9c22e80-c44d-11ea-8749-9c442733fc78.png)
