### ISSUE TITLE
MRAN-Arenal Airport-ALAJUELA-COSTA RICA

### ISSUE THREAD

**Issue by EthanNFlyer22** [InfiniteFlightAirportEditing/Airports#4769]
# Airport Name

Arenal Airport

# Country?

Costa Rica

# Improvements that need to be made?

Made from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by EthanNFlyer22** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/81460981-37b98280-917f-11ea-8015-ba144fa4d7fb.jpg)
