### ISSUE TITLE
YCFS

### ISSUE THREAD

**Issue by timsaviation** [InfiniteFlightAirportEditing/Airports#4770]
# Airport Name

Coffs Harbour

# Country?

Australia

# Improvements that need to be made?

Add grass taxiway and fix gate 2

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by MajorTomMueller** [comment]
Duplicate #3660

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/87087656-1e719880-c1f9-11ea-8817-f230df40928c.png)
