### ISSUE TITLE
SBCC-Cachimbo Airport-PARA-BRAZIL

### ISSUE THREAD

**Issue by victormw22** [InfiniteFlightAirportEditing/Airports#4771]
# Airport Name

< Cachimbo>

# Country?

< Brazil>

# Improvements that need to be made?

<  Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/79644766-744a1d80-8181-11ea-804b-c643d0b0c0aa.jpg)
