### ISSUE TITLE
VVPC-Phu Cat Airport-BINH DINH-VIETNAM

### ISSUE THREAD

**Issue by MinhNguyN** [InfiniteFlightAirportEditing/Airports#4772]
# Airport Name

< Phu Cat >

# Country?

< Vietnam >

# Improvements that need to be made?

< redo whole airport>

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< low >

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78686769-cfe6f200-78c9-11ea-9f59-f8c936d6e97d.jpg)
