### ISSUE TITLE
EDBK-Verkehrslandeplatz Kyritz-BRANDENBURG-GERMANY

### ISSUE THREAD

**Issue by rich-art-02** [InfiniteFlightAirportEditing/Airports#4773]
# Airport Name

Verkehrslandeplatz Kyritz

# Country?

Germany

# Improvements that need to be made?

redo from scratch

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by rich-art-02** [comment]
sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/79668824-e9235480-818d-11ea-8e73-08cd286d89e2.jpg)
