### ISSUE TITLE
0Q5-Shelter Cove Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#4775]
# Airport Name

Shelter Cove Airport

# Country?

🇺🇸 

# Improvements that need to be made?

redone from scratch

# Are you working on this airport?

sí

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by brennanhackard** [comment]
Sent to OR :D

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78698266-75a15d80-78d8-11ea-9437-a6e85e01e0ce.jpg)
