### ISSUE TITLE
A24-California Pines Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by jakey200** [InfiniteFlightAirportEditing/Airports#4776]
# Airport Name

California Pines

# Country?

USA

# Improvements that need to be made?

Redo

# Are you working on this airport?

by all means

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by jakey200** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78697722-a0d77d00-78d7-11ea-9207-444366842e95.jpg)
