### ISSUE TITLE
KTTD-Portland-Troutdale Airport-OREGON-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#4778]
# Airport Name

Portland-Troutdale

# Country?

The one with 50 states

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

Ye

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/79669924-92217d80-8195-11ea-8b1e-602b06a07582.jpg)
