### ISSUE TITLE
KBFL-Meadows Field-CALIFORNIA-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#4779]
# Airport Name

Meadows Field

# Country?

US

# Improvements that need to be made?

Redo

# Are you working on this airport?

Sí

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

10000ft+ Runway

**Comment by brennanhackard** [comment]
Sent to OR :D

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/81996904-b3567c00-9624-11ea-8120-e466e6c21fc2.jpg)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/81996964-e00a9380-9624-11ea-939e-6d8992fbdf2e.jpg)
