### ISSUE TITLE
YMMB-Melbourne Moorabbin Airport-VICTORIA-AUSTRALIA

### ISSUE THREAD

**Issue by joshhicks1** [InfiniteFlightAirportEditing/Airports#4780]
# Airport Name

YMMB - Melbourne Moorabbin Airport

# Country?

Australia

# Improvements that need to be made?

Whole apron and taxiway rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85921995-d8eebc00-b845-11ea-88ce-495687b529bb.png)
