### ISSUE TITLE
KAAA-Logan County-ILLINOIS-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#4782]
# Airport Name

Logan County Airport 

# Country?

Illinois,  USA

# Improvements that need to be made?

Work from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

Airport is ready to be sent to OR

**Comment by MajorTomMueller** [comment]
Are you sure you want to continue editing this one? 
After you have unassigned yourself without mentioning any reason from two other issues it looks unlikeley to me ...

**Comment by ECoops-123** [comment]
Apologies, I, mentioned in the Slack some time ago that I wasn't able to work on some due to a slow computer with continuous issues against using WED, and also asked if any one could take over KAFW. In summary I cannot make small airports. I use a shared computer when I edit with my father, and during the COVID-19 pandemic he has 13+ hour shifts Monday to Friday, and is continuously remotely accessing a PC giving me no time to work.It would be great if you could put them all up as a suggestion.  For the current foreseeable future I won't be able to edit, but when I return will stick to the smaller General Aviation fields across the USA and Canada unless the system I use is improved.Apologetic regards, Ecoops123 
-------- Original message --------From: Major Tom <notifications@github.com> Date: 08/06/2020  16:37  (GMT+00:00) To: InfiniteFlightAirportEditing/Airports <Airports@noreply.github.com> Cc: ECoops123 <flydubaivirtual@gmail.com>, Assign <assign@noreply.github.com> Subject: Re: [InfiniteFlightAirportEditing/Airports] KAAA-Logan County-ILLINOIS-USA (#4782) 
Are you sure you want to continue editing this one?
After you have unassigned yourself without mentioning any reason from two other issues it looks unlikeley to me ...

—You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/InfiniteFlightAirportEditing/Airports/issues/4782#issuecomment-640706709",
"url": "https://github.com/InfiniteFlightAirportEditing/Airports/issues/4782#issuecomment-640706709",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/96046830-bc4cb300-0e39-11eb-9c39-14c2ee046676.png)
