### ISSUE TITLE
TNCE-F. D. Roosevelt Airport-ORANJESTAD-SINT EUSTATIUS

### ISSUE THREAD

**Issue by FlyBoii31** [InfiniteFlightAirportEditing/Airports#4783]
# Airport Name

< F D Roosevelt Airport >

# Country?

< Sint Eustatius>

# Improvements that need to be made?

< New Parking Spots >

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/79277149-a1e04f80-7e7f-11ea-9f01-8e45f3e9e8e8.jpg)
