### ISSUE TITLE
VVPK-Pleiku Airport-GIA LAI-VIETNAM

### ISSUE THREAD

**Issue by IFUA2003** [InfiniteFlightAirportEditing/Airports#4784]
# Airport Name

< Pleiku Airport >

# Country?

< Vietnam >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/79669053-5d122c80-818f-11ea-9623-1f1ee3751826.jpg)
