### ISSUE TITLE
KMJQ-Jackson Municipal Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by Gabe-Z** [InfiniteFlightAirportEditing/Airports#4785]
# Airport Name

Jackson Municipal Airport

# Country?

USA

Improvements that need to be made?

Unedited

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by Gabe-Z** [comment]
The airport is now in OR.

I'm speedy again, no one has assigned me yet and add labels as well. 😂 but it's night so yea.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78707729-5eb63780-78e7-11ea-8c1a-75290fec75f8.jpg)
