### ISSUE TITLE
EDAC-Leipzig-Altenburg Airport-THURINGIA-GERMANY

### ISSUE THREAD

**Issue by bavariaaviation** [InfiniteFlightAirportEditing/Airports#4787]
# Airport Name

Leipzig/Altenburg Airport

# Country?

Germany

# Improvements that need to be made?

rework from scratch

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78681428-17b64b00-78c3-11ea-9d13-3da16a39234f.jpg)
