### ISSUE TITLE
ZJQH-Qionghai Boao Airport-HAINAN-CHINA

### ISSUE THREAD

**Issue by AnthonyCK** [InfiniteFlightAirportEditing/Airports#4789]
# Airport Name

< Qionghai Boao Airport >

# Country?

< China >

# Improvements that need to be made?

< New airport >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< 10000+ >

**Comment by AnthonyCK** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/79644008-84abc980-817c-11ea-883d-5887052d6bdf.jpg)
