### ISSUE TITLE
O26-Lone Pine/Death Valley Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by jakey200** [InfiniteFlightAirportEditing/Airports#4791]
# Airport Name

Lone Pine/Death Valley Airport

# Country?

USA

# Improvements that need to be made?

Redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by jakey200** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78699446-4c81cc80-78da-11ea-93fa-bf5d5a1940e4.jpg)
