### ISSUE TITLE
L09-Stovepipe Wells Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by jakey200** [InfiniteFlightAirportEditing/Airports#4793]
# Airport Name

Stovepipe Wells Airport

# Country?

USA

# Improvements that need to be made?

redo

# Are you working on this airport?

Done

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78698667-0ed07400-78d9-11ea-8764-e82960ef4aa2.jpg)
