### ISSUE TITLE
FMCI-Mohéli Bandar Es Eslam Airport-MOHELI-COMOROS

### ISSUE THREAD

**Issue by jakey200** [InfiniteFlightAirportEditing/Airports#4795]
# Airport Name

Moheli Airport

# Country?

Comoros

# Improvements that need to be made?

Redo

# Are you working on this airport?

Done

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78690965-79c87d80-78ce-11ea-99d6-ed6d3e83253a.jpg)
