### ISSUE TITLE
KSBU-Blue Earth Municipal Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by Gabe-Z** [InfiniteFlightAirportEditing/Airports#4797]
# Airport Name

Blue Earth Municipal Airport

# Country?

USA

# Improvements that need to be made?

Unedited

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by Gabe-Z** [comment]
Damn it, I should have checked the satellite before making the issue.

**Comment by Gabe-Z** [comment]
There is construction in the imagery satellite, : /.

**Comment by IFsami** [comment]
I'll do it

**Comment by IFsami** [comment]
If no one is doing this, I'll do it

**Comment by MajorTomMueller** [comment]
Good luck, the editor before was a experienced one who said the imagery wasn’t good....

**Comment by IFsami** [comment]
It is barely visible, but thanks to google maps I was able to manage 😉

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/91919443-9e612f80-ec8b-11ea-8c14-c624f762e256.png)
