### ISSUE TITLE
SNAB-Araripina Airport-PERNAMBUCO-BRAZIL

### ISSUE THREAD

**Issue by carloszferreira** [InfiniteFlightAirportEditing/Airports#4799]
# Airport Name

Araripina

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by carloszferreira** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/79266590-2f1aa880-7e6e-11ea-8a58-8bf2272751d5.jpg)
