### ISSUE TITLE
LHZK

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#48]

**Comment by IFAEpat** [comment]
Zalakaros Airport

**Comment by IFAEpat** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17209556/2bb3a0f2-5483-11e6-90d1-b5c1d200ae56.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18534789/4ab23afc-7ab4-11e6-978f-d8e545fb3621.png)
