### ISSUE TITLE
SBTA-Base De Aviacao De Taubate Airport-SAO PAULO-BRAZIL

### ISSUE THREAD

**Issue by carloszferreira** [InfiniteFlightAirportEditing/Airports#4800]
# Airport Name
Base De Aviacao De Taubate Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by carloszferreira** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
The author of the topic is no longer part of the IFAET. This is available to anyone who wants to edit.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/93710773-ab48a480-fb0e-11ea-9561-73a10bf213c2.png)
