### ISSUE TITLE
VVSA-Truong Sa Air Base-KHANH HOA-VIETNAM

### ISSUE THREAD

**Issue by MinhNguyN** [InfiniteFlightAirportEditing/Airports#4801]
# Airport Name

< Truong Sa Air Base >

# Country?

< Viet Nam >

# Improvements that need to be made?

< Build whole new airport >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/80251983-e5d80f00-864c-11ea-958c-488fdab1cc3c.jpg)
