### ISSUE TITLE
ZSNT-Nantong Xingdong Airport-JIANGSU-CHINA

### ISSUE THREAD

**Issue by AnthonyCK** [InfiniteFlightAirportEditing/Airports#4802]
# Airport Name

< Nantong Xingdong Airport >

# Country?

< China >

# Improvements that need to be made?

< New >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< 10000+ >

**Comment by AnthonyCK** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/79269144-5bd0bf00-7e72-11ea-9c92-7f48f0199c43.jpg)
