### ISSUE TITLE
1O2-Lampson Field-CALIFORNIA-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#4804]
# Airport Name

Lampson Field

# Country?

🇺🇸 

# Improvements that need to be made?

redo

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by brennanhackard** [comment]
Sent to OR :D

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/79278768-cab61400-7e82-11ea-8bbf-32b0e870c5c5.jpg)
