### ISSUE TITLE
KPDT-Eastern Oregon Regional At Pendleton-OREGON-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#4805]
# Airport Name

Eastern Oregon Regional At Pendleton

# Country?

US

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

Ye

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/79278460-1916e300-7e82-11ea-8936-906a1ba98424.jpg)
