### ISSUE TITLE
ZSXZ-Xuzhou Guanyin Airport-JIANGSU-CHINA

### ISSUE THREAD

**Issue by Berlin-N** [InfiniteFlightAirportEditing/Airports#4807]
# Airport Name

< Xuzhou Guanyin Airport >

# Country?

< China >

# Improvements that need to be made?

< New >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by Berlin-N** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/83468063-568afc00-a441-11ea-888a-76ab2eec71cb.png)
