### ISSUE TITLE
73CA-Bear Valley Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by jakey200** [InfiniteFlightAirportEditing/Airports#4808]
# Airport Name

Bear Valley Airport

# Country?

USA

# Improvements that need to be made?

Redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by jakey200** [comment]
sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/79669724-ec214380-8193-11ea-8213-b21d612991d9.jpg)
