### ISSUE TITLE
DUPLICATE

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#4809]
# Airport Name

Rurutu Airport

# Country?

French Polynesia

# Improvements that need to be made?

Scratch adding

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

No

**Comment by HiFlyerBwi** [comment]
Submitted for OR

**Comment by kztmtn** [comment]
Duplicate (#4502 )

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/86986124-815f2300-c158-11ea-82f6-5e15f37c3eb7.png)
