### ISSUE TITLE
NTAT-Tubuai-Mataura Airport-FRENCH POLYNESIA

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#4810]
# Airport Name

Tubuai-Mataura Airport

# Country?

French Polynesia

# Improvements that need to be made?

Scratch 

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

None

**Comment by HiFlyerBwi** [comment]
Submitted for OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/79664571-92b51680-818b-11ea-8c3f-1f2564720229.jpg)
