### ISSUE TITLE
NTAV-Raivavae Airport-FRENCH POLYNESIA

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#4811]
# Airport Name

Raivavae Airport

# Country?

French Polynesia

# Improvements that need to be made?

Scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

None

**Comment by HiFlyerBwi** [comment]
Submitted for OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/79268067-87eb4080-7e70-11ea-94c6-ebe3b176bd38.jpg)
