### ISSUE TITLE
NTGB-Fangatau Airport-FRENCH POLYNESIA

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#4812]
# Airport Name

Fangatau Airport

# Country?

French Polynesia

# Improvements that need to be made?

Scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

None

**Comment by HiFlyerBwi** [comment]
Submitted for OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/79267564-c3393f80-7e6f-11ea-91e3-b9d268fcaecc.jpg)
