### ISSUE TITLE
NTGC-Tikehau Airport-FRENCH POLYNESIA

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#4813]
# Airport Name

Tikehau Airport

# Country?

French Polynesia

# Improvements that need to be made?

Scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

None

**Comment by HiFlyerBwi** [comment]
Submitted for OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/79267147-08a93d00-7e6f-11ea-9b13-0c745e87cffa.jpg)
