### ISSUE TITLE
ZSYA-Yangzhou Taizhou Airport-JIANGSU-CHINA

### ISSUE THREAD

**Issue by AnthonyCK** [InfiniteFlightAirportEditing/Airports#4814]
# Airport Name

< Yangzhou Taizhou Airport >

# Country?

< China >

# Improvements that need to be made?

< New >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< 10000+ >

**Comment by AnthonyCK** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/79644132-4d89e800-817d-11ea-803e-4de14b0f9811.jpg)
