### ISSUE TITLE
NZMO-Te Anau Regional Airport-SOUTHLAND-NEW ZEALAND

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#4815]
# Airport Name

< Manapouri-Te_Anau >

# Country?

< New Zealand >

# Improvements that need to be made?

< Scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by Berlin-N** [comment]
Sen to OR

**Comment by Berlin-N** [comment]
Sent to OR

**Comment by Piggywu981** [comment]
Sent to OR

**Comment by MajorTomMueller** [comment]
![NZMO-git](https://user-images.githubusercontent.com/26853210/131258904-55d2f694-4eb2-4c4a-b652-b1934dc80136.png)
