### ISSUE TITLE
LELL-Sabadell Airport-CATALONIA-SPAIN

### ISSUE THREAD

**Issue by bavariaaviation** [InfiniteFlightAirportEditing/Airports#4816]
# Airport Name

Sabadell Airport

# Country?

Spain

# Improvements that need to be made?

rework from scratch

# Are you working on this airport?

sí

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/79666933-3d2d3980-818c-11ea-8237-2214b61cd134.jpg)
