### ISSUE TITLE
KAEL-Albert Lea Municipal Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by Gabe-Z** [InfiniteFlightAirportEditing/Airports#4817]
# Airport Name

Albert Lea Municipal Airport

# Country?

USA

# Improvements that need to be made?

Unedited

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by Gabe-Z** [comment]
The airport is now in OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/79670108-01e43800-8197-11ea-9a78-112a1ffc9d39.jpg)
