### ISSUE TITLE
KRIV-March Air Reserve Base-CALIFORNIA-USA 

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#482]
Redo gates and buildings

**Comment by kilt46** [comment]
Airport redone gates

**Comment by IceBlue02** [comment]
https://community.infinite-flight.com/t/kriv-runway-12-30/44207

Will make changes as necessary.

**Comment by IceBlue02** [comment]
Actually unable at this time sorry

**Comment by dushyants19** [comment]
OP of that topic is wrong.

https://community.infinite-flight.com/t/kriv-runway-12-30/44207/3?u=dush19

**Comment by dushyants19** [comment]
Looks like there is an issue....

**Comment by dushyants19** [comment]
Done. [Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/e2d9c5a33fa41c799cf9007bc7a2957966e81d32)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20060557/628b4a24-a4c1-11e6-83a9-c0d47cb4da6a.png)
