### ISSUE TITLE
SWTU-Fazenda Tucunare Airport-MATO GROSSO-BRAZIL

### ISSUE THREAD

**Issue by victormw22** [InfiniteFlightAirportEditing/Airports#4820]
# Airport Name

< Fazenda Tucunare  >

# Country?

< Brazil>

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes>

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low>

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/79644478-af4b5180-817f-11ea-99ee-32d846260e3d.jpg)
