### ISSUE TITLE
NTGE-Reao Airport-FRENCH POLYNESIA

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#4821]
# Airport Name

Reao Airport

# Country?

United States

# Improvements that need to be made?

Scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

None

**Comment by HiFlyerBwi** [comment]
Submitted for OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/79654761-bd51a000-8188-11ea-9d06-75c34e7a5dcf.jpg)
