### ISSUE TITLE
EDBO-Verkehrslandeplatz Oehna-BRANDENBURG-GERMANY

### ISSUE THREAD

**Issue by rich-art-02** [InfiniteFlightAirportEditing/Airports#4823]
# Airport Name

Verkehrslandeplatz Oehna

# Country?

Germany

# Improvements that need to be made?

redo from scratch
# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by rich-art-02** [comment]
sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/80238492-e95f9c00-8634-11ea-8c4e-483d6f6ad025.jpg)
