### ISSUE TITLE
LFCK-Castres/Mazamet Airport-AQUITAINE-FRANCE

### ISSUE THREAD

**Issue by bavariaaviation** [InfiniteFlightAirportEditing/Airports#4825]
# Airport Name

Castres-Mazamet

# Country?

France

# Improvements that need to be made?

complete rework

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/79275799-3bf2c880-7e7d-11ea-9372-ede012a09feb.jpg)
