### ISSUE TITLE
1O3-Lodi Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#4827]
# Airport Name

Lodi Airport

# Country?

🇺🇸 

# Improvements that need to be made?

redo

# Are you working on this airport?

да

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by brennanhackard** [comment]
Sent to OR :D

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/80622500-44233a00-8a1f-11ea-8eef-748b8e945844.jpg)
