### ISSUE TITLE
SDAM-Estadual De Campos Dos Amarais Airport-SAO PAULO-BRAZIL

### ISSUE THREAD

**Issue by carloszferreira** [InfiniteFlightAirportEditing/Airports#4828]
# Airport Name
Estadual De Campos Dos Amarais

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by victormw22** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/93151861-ac1ea800-f6c2-11ea-9785-6198eb6cd7da.png)
