### ISSUE TITLE
TUPJ-Terrance B Lettsome Intl-Tortola-British Virgin Islands

### ISSUE THREAD

**Issue by FlyBoii31** [InfiniteFlightAirportEditing/Airports#4829]
# Airport Name

<Terrance B Lettsome Intl>

# Country?

< British Virgin Islands >

# Improvements that need to be made?

< Full Rework >

# Are you working on this airport?

< Yes>

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/82395194-5e9a7300-9a21-11ea-822f-1c9a4b321c4b.jpg)
