### ISSUE TITLE
KGWS-Glenwood Springs Municipal Airport-COLORADO-USA

### ISSUE THREAD

**Issue by dushyants19** [InfiniteFlightAirportEditing/Airports#483]
Denver, no spawns, Class E, quick project.

**Comment by kenfre02** [comment]
I'll do this one. :)

**Comment by dushyants19** [comment]
Done :)

**Comment by kilt46** [comment]
BUILDINGS ADDED

**Comment by dushyants19** [comment]
51216ca Gated in

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19253208/15b52e1c-8f0f-11e6-9e10-4c10e8aa6e8d.png)

**Comment by brennanhackard** [comment]
@RobertineIFC will be reworking this airport and adding the hangars on the southwest side.
