### ISSUE TITLE
ZSWH-Weihai Dashuipo Airport-SHANDONG-CHINA

### ISSUE THREAD

**Issue by AnthonyCK** [InfiniteFlightAirportEditing/Airports#4832]
# Airport Name

< Weihai Dashuipo >

# Country?

< China >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by AnthonyCK** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/80241816-a7d1ef80-863a-11ea-8db8-d2123069b8eb.jpg)
