### ISSUE TITLE
KFBL-Faribault Municipal Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by Gabe-Z** [InfiniteFlightAirportEditing/Airports#4835]
# Airport Name

Faribault Municipal Airport

# Country?

USA

# Improvements that need to be made?

Unedited

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/81462377-799af680-9188-11ea-8928-edff559111bb.jpg)
