### ISSUE TITLE
RPUG-Lingayen Airport-PHILIPPINES

### ISSUE THREAD

**Issue by zacky89315** [InfiniteFlightAirportEditing/Airports#4839]
# Airport Name

Lingayen Airpot

# Country?

Philippines

# Improvements that need to be made?

Unedited

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/81460031-1b1a4c00-9179-11ea-8b16-6ba56eedda40.jpg)
