### ISSUE TITLE
KPFC

### ISSUE THREAD

**Issue by dushyants19** [InfiniteFlightAirportEditing/Airports#484]
Echo, Quick redo, new editors can have this

**Comment by freddiefrogs** [comment]
Will do

**Comment by freddiefrogs** [comment]
Alas! I've run into another computer problem. I cannot do this unless it fixes itself all of a sudden.

**Comment by freddiefrogs** [comment]
And the problem is gone! I'm getting work right away.

**Comment by freddiefrogs** [comment]
Do e

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17280292/4298cb22-5752-11e6-8f85-8dc50760251a.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17461626/0f3deb48-5c59-11e6-8b56-72e98377222a.png)

**Comment by Czechoslovaki** [comment]
![image](https://user-images.githubusercontent.com/51279558/96944264-3b239a80-148f-11eb-9ccd-baadb38fa0c2.png)
