### ISSUE TITLE
VVCI-Cat Bi Intl Airport-HAI PHONG-VIETNAM

### ISSUE THREAD

**Issue by IFUA2003** [InfiniteFlightAirportEditing/Airports#4842]
# Airport Name

< Cat Bi International Airport>

# Country?

< Vietnam >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/81460127-abf12780-9179-11ea-8288-12ee88e5bce4.jpg)
