### ISSUE TITLE
KOTH-Southwest Oregon Regional Airport-OREGON-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#4845]
# Airport Name

Southwest Oregon Regional Airport

# Country?

Merica

# Improvements that need to be made?

Full house construction

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/79670028-48856280-8196-11ea-934d-b1ed4f0418eb.jpg)
