### ISSUE TITLE
ENST-Sandnessjøen/Stokka Airport-NORDLAND-NORWAY

### ISSUE THREAD

**Issue by bavariaaviation** [InfiniteFlightAirportEditing/Airports#4846]
# Airport Name

Sandnessjøen/Stokka

# Country?

Norway

# Improvements that need to be made?

complete rework

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

n/a

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/79270042-ca624c80-7e73-11ea-945d-f04eba3e1514.jpg)
