### ISSUE TITLE
ZPLC-Lincang Boshang Airport-YUNNAN-CHINA

### ISSUE THREAD

**Issue by Berlin-N** [InfiniteFlightAirportEditing/Airports#4849]
# Airport Name

< Lincang Boshang >

# Country?

< China >

# Improvements that need to be made?

< New >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by Berlin-N** [comment]
Send to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/80315892-ec8f8f00-87d0-11ea-9ad2-68702f0222ff.jpg)
