### ISSUE TITLE
KSMS-Sumter Airport-SOUTH CAROLINA-USA

### ISSUE THREAD

**Issue by dushyants19** [InfiniteFlightAirportEditing/Airports#485]
Echo, needs spawn points, lines.

**Comment by freddiefrogs** [comment]
Will do

**Comment by freddiefrogs** [comment]
@InfiniteFlightAirportEditing/airport-reviewers done

**Comment by dushyants19** [comment]
Many features not snapped.

**Comment by moritzbabl** [comment]
Will do it, shouldn't take too long

**Comment by moritzbabl** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21912155/cd43611a-d8e9-11e6-821d-b540b14672c7.png)
