### ISSUE TITLE
ZGOW-Jieyang Chaoshan Airport-GUANGDONG-CHINA

### ISSUE THREAD

**Issue by AnthonyCK** [InfiniteFlightAirportEditing/Airports#4851]
# Airport Name

< Jieyang Chaoshan Airport>

# Country?

< China >

# Improvements that need to be made?

< New >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by AnthonyCK** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/80242282-81f91a80-863b-11ea-850a-e28543d00559.jpg)
