### ISSUE TITLE
KOXR-Oxnard Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by jakey200** [InfiniteFlightAirportEditing/Airports#4853]
# Airport Name

Oxnard Airport
# Country?

USA

# Improvements that need to be made?

Redo

# Are you working on this airport?

< Enter text here >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by jakey200** [comment]
sent to o f f i c i a l r e v i e w

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/80252565-dc9b7200-864d-11ea-9518-229e07ce00b8.jpg)
