### ISSUE TITLE
TUPW-Virgin Gorda Airport-Virgin Gorda-British Virgin Islands 

### ISSUE THREAD

**Issue by FlyBoii31** [InfiniteFlightAirportEditing/Airports#4855]
# Airport Name

< Virgin Gorda Airport >

# Country?

< British Virgin Islands >

# Improvements that need to be made?

< Full Rework >

# Are you working on this airport?

< Yes>

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/80241162-80c6ee00-8639-11ea-9e6e-0b447f4ca67b.jpg)
