### ISSUE TITLE
TUPA-Auguste George Airport-ANEGADA-BRITISH VIRGIN ISLANDS

### ISSUE THREAD

**Issue by FlyBoii31** [InfiniteFlightAirportEditing/Airports#4856]
# Airport Name

< Auguste George Airport>

# Country?

< British Virgin Islands >

# Improvements that need to be made?

< Full Rework >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MajorTomMueller** [comment]
You have already three airports assigned. Do not open further issues if you haven’t finished the previous ones.

**Comment by FlyBoii31** [comment]
Can i work on this please?

**Comment by FlyBoii31** [comment]
Can I be assigned to this

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/91106931-a856b300-e639-11ea-8219-563f67a5dfe7.png)
