### ISSUE TITLE
VNVT-Biratnagar Airpor-NEPAL

### ISSUE THREAD

**Issue by zacky89315** [InfiniteFlightAirportEditing/Airports#4857]
# Airport Name

<Biratnagar Airport >

# Country?

<Nepal >

# Improvements that need to be made?

< New >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MajorTomMueller** [comment]
Please fill the form always completely.

**Comment by MajorTomMueller** [comment]
http://e-aip.caanepal.gov.np/_uploads/_pdf/fc4a887aba53c24dfd8830a62e1999b6.pdf
Aerodrome chart at the end of document

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/81991925-bd727d80-9618-11ea-8254-4bed2fc6510b.jpg)
