### ISSUE TITLE
NZWT-Whitianga Airport-WAIKATO-NEW ZEALAND

### ISSUE THREAD

**Issue by Lukeh0** [InfiniteFlightAirportEditing/Airports#4858]
# Airport Name

Whitianga Airport

# Country?

New Zealand

# Improvements that need to be made?

Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/80244033-a6a2c180-863e-11ea-9031-4385eb302d5d.jpg)
