### ISSUE TITLE
UWKS-Cheboksary-RUSSIA

### ISSUE THREAD

**Issue by HauBHa9lDbIPo4Ka** [InfiniteFlightAirportEditing/Airports#4859]
# Airport Name

Cheboksary

# Country?

Russia

# Improvements that need to be made?

Full processing

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104823319-f188e880-580e-11eb-903c-d0d33849bd5a.png)
