### ISSUE TITLE
KGCD-Grant County Regional Airport / Ogilvie Field-OREGON-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#4861]
# Airport Name

Grant County Regional Airport / Ogilvie Field

# Country?

USA

# Improvements that need to be made?

Rework from nothing

# Are you working on this airport?

Ye

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/80253806-53396f00-8650-11ea-8b83-317b58dfe04b.jpg)
