### ISSUE TITLE
EDCY-Verkehrslandeplatz Welzow-BRANDENBURG-GERMANY

### ISSUE THREAD

**Issue by rich-art-02** [InfiniteFlightAirportEditing/Airports#4862]
# Airport Name

Verkehrslandeplatz Welzow

# Country?

Germany

# Improvements that need to be made?

redo from scratch

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by rich-art-02** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/81989665-0d027a80-9614-11ea-87fd-3659a0e30540.jpg)
