### ISSUE TITLE
KEDC-Austin Executive Airport-TEXAS-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#4871]
# Airport Name

Austin Executive Airport

# Country?

America

# Improvements that need to be made?

Full redo

# Are you working on this airport?

Sí

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by brennanhackard** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/80317240-f87f4f00-87d8-11ea-9716-5b92015747ea.jpg)
