### ISSUE TITLE
SSCI-Coxim Airport-MATO GROSSO DO SUL-BRAZIL

### ISSUE THREAD

**Issue by HenriqueChen** [InfiniteFlightAirportEditing/Airports#4873]
# Airport Name

< Coxim >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by HenriqueChen** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/91772076-c2e4db00-eba9-11ea-8f8d-dec3e1d7f0ac.png)
