### ISSUE TITLE
KNSI-San Nicolas Island Naval Outlying Field-CALIFORNIA_USA

### ISSUE THREAD

**Issue by rich-art-02** [InfiniteFlightAirportEditing/Airports#4875]
# Airport Name

San Nicolas Island Naval Outlying Field

# Country?

USA

# Improvements that need to be made?

redo from scratch

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

10000ft+ runway

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/81461876-1491d180-9185-11ea-9821-ede0d12f464d.jpg)
