### ISSUE TITLE
YGLA-Gladstone Airport-QUEENSLAND-AUSTRALIA

### ISSUE THREAD

**Issue by bavariaaviation** [InfiniteFlightAirportEditing/Airports#4876]
# Airport Name

Gladstone

# Country?

Australia

# Improvements that need to be made?

complete rework

# Are you working on this airport?

yeah mate

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/80243267-48291380-863d-11ea-9308-cc8288e6abaa.jpg)
