### ISSUE TITLE
EYUT-Udena Airfield-UDENA COUNTY-LITHUNIA

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#4878]
![EYUT-git](https://user-images.githubusercontent.com/26853210/79890102-8381d300-83ee-11ea-9dc2-b1c69077be51.png)

**Comment by MBeringuy** [comment]
If you have a picture of the airport, I assume you have already finished editing it. Is this the case or should the issue remain open?

**Comment by MajorTomMueller** [comment]
It will be automatically close when Github managed to get the commit from my home to the server. But yesterday Github was so slow that I went to bed before it provided me the push button.
