### ISSUE TITLE
EFSO-Sodankyla Airport-LAPLAND-FINLAND

### ISSUE THREAD

**Issue by NoahAllan** [InfiniteFlightAirportEditing/Airports#4879]
# Airport Name

< Sodankylä Airport >

# Country?

< Finland >

# Improvements that need to be made?

< Airport re-do >

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< low >

**Comment by MajorTomMueller** [comment]
![EFSO](https://user-images.githubusercontent.com/26853210/130352808-3769d627-259a-4804-a433-1f2c05578e30.png)
