### ISSUE TITLE
EHTE

### ISSUE THREAD

**Issue by dushyants19** [InfiniteFlightAirportEditing/Airports#488]
Easy fix, check [this](https://community.infinite-flight.com/t/teuge-airport-ehte-missing-its-main-terminal-and-grass-taxiway/35818?u=dush19)

**Comment by kilt46** [comment]
Airport redone

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20859467/eee462ee-b925-11e6-8aea-4dcebe945d0e.png)
