### ISSUE TITLE
KGWS-Glenwood Springs Municipal Airport-Colorado-USA

### ISSUE THREAD

**Issue by TheFlyingGuy1** [InfiniteFlightAirportEditing/Airports#4880]
# Airport Name

< KGWS-Glenwood Springs Municipal Airport >

# Country?

< United States Of America >

# Improvements that need to be made?

< Taxiway, ramp, parking etc. >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< IF Event >

**Comment by TheFlyingGuy1** [comment]
There have been others over the years for this airport but all are closed.

**Comment by Czechoslovaki** [comment]
You know you can just ask a supervisor to the existing issue for GWS?

**Comment by MBeringuy** [comment]
#483

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/86976809-ead33780-c140-11ea-8aba-d5b4bfa6d768.png)
