### ISSUE TITLE
AK47-Shawn Field Airport-ALASKA-USA

### ISSUE THREAD

**Issue by PopuleuxMusicYT** [InfiniteFlightAirportEditing/Airports#4884]
# Airport Name

Shawn Field Airport

# Country?

America

# Improvements that need to be made?

New Airport, from scratch; https://www.airnav.com/airport/AK47

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low Priority

**Comment by PopuleuxMusicYT** [comment]
Also the existing file in the repo is just a windsock, so i was wondering if it can be considered and listed as a new airport?

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/81461776-7bfb5180-9184-11ea-8c3d-3ba852971150.jpg)
