### ISSUE TITLE
5S6-Cape Blanco State Airport-OREGON-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#4885]
# Airport Name

Cape Blanco State Airport

# Country?

USA

# Improvements that need to be made?

Full Renovation

# Are you working on this airport?

Da

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by Czechoslovaki** [comment]
sent for O R

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/80317757-01255480-87dc-11ea-90ed-bb2c8b046f79.jpg)
