### ISSUE TITLE
NTGP-Puka Puka Airport-FRENCH POLYNESIA

### ISSUE THREAD

**Issue by HiFlyerBwi** [InfiniteFlightAirportEditing/Airports#4887]
# Airport Name

Puka Puka Airport

# Country?

French Polynesia

# Improvements that need to be made?

Scratch

# Are you working on this airport?

Ye

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

No

**Comment by HiFlyerBwi** [comment]
Submitted for OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/80317021-abe74400-87d7-11ea-8f97-5751b31e8c0f.jpg)
