### ISSUE TITLE
ZSTX-Huangshan Tunxi Airport-ANHUI-CHINA

### ISSUE THREAD

**Issue by AnthonyCK** [InfiniteFlightAirportEditing/Airports#4889]
# Airport Name

< Huangshan Tunxi Airport >

# Country?

< China >

# Improvements that need to be made?

< New >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by AnthonyCK** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/81458571-6597ca80-9171-11ea-82d9-25864ea78c0b.jpg)
