### ISSUE TITLE
ZSSH-Huai'an Lianshui Airport-JIANGSU-CHINA

### ISSUE THREAD

**Issue by AnthonyCK** [InfiniteFlightAirportEditing/Airports#4890]
# Airport Name

< Huai'an Lianshui Airport >

# Country?

< China >

# Improvements that need to be made?

< New >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by AnthonyCK** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/81458429-bbb83e00-9170-11ea-84ff-70b40f9ad003.jpg)
