### ISSUE TITLE
UBBG-Ganja Airport-GANJA-AZERBAIJAN

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#4893]
# Airport Name

< Ganja International Airport >

# Country?

< Azerbaijan >

# Improvements that need to be made?

< from scratch>

# Are you working on this airport?

< Yessss >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< GP2 (12/30 - 10827ft) >

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/81460870-700c9100-917e-11ea-892a-d1a38fdf2452.jpg)
