### ISSUE TITLE
UIAR-Chara Airport-KALARSKY DISTRICT-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#4895]
# Airport Name

< Chara Airport >

# Country?

< Russia >

# Improvements that need to be made?

< from scratch >

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85903774-ca17f300-b7cc-11ea-80ec-48cc69f45880.png)
