### ISSUE TITLE
KSBP-San Luis County Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#4896]
# Airport Name

San Luis County Airport

# Country?

AMERICA

# Improvements that need to be made?

redo

# Are you working on this airport?

sí

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by brennanhackard** [comment]
Sent for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/86470137-6cb9ff80-bd00-11ea-90fa-37c82379c57e.png)
