### ISSUE TITLE
KDSM-Des Moines International Airport-IOWA-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#4897]
# Airport Name

Des Moines International Airport

# Country?

USA

# Improvements that need to be made?

Full Rework 

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

US Capital

**Comment by Czechoslovaki** [comment]
Sent for OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/81461518-c085ed80-9182-11ea-9d30-cb744d5573e9.jpg)
