### ISSUE TITLE
DA11-Hammaguir Airbase-ALGERIA

### ISSUE THREAD

**Issue by kraftnursery** [InfiniteFlightAirportEditing/Airports#4898]
# Airport Name

Hamaguir

# Country?

Algeria

# Improvements that need to be made?

Need redo

# Are you working on this airport?

YES

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Airport of my home

**Comment by MajorTomMueller** [comment]
@kraftnursery respond in slack

**Comment by MajorTomMueller** [comment]
spam

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/87606169-eb7b4900-c6bf-11ea-8ebb-0ea29271df7b.png)
