### ISSUE TITLE
EGTR-Elstree Aerodrome-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by Y3nnii** [InfiniteFlightAirportEditing/Airports#4899]
# Airport Name

< Elstree >

# Country?

< England >

# Improvements that need to be made?

< Full Rework >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low
 >

**Comment by MajorTomMueller** [comment]
![Uploading EGTR-git.png…]()
