### ISSUE TITLE
KDLS-Columbia Gorge Regional/The Dalles Municipal Airport-OREGON-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#49]

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20043509/35e12f2e-a454-11e6-9f74-b31b008ce87a.png)

**Comment by brunocr98** [comment]
@Czechoslovaki is redoing the airport

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78412717-c0765900-75ea-11ea-9f21-55e004087eec.jpg)
