### ISSUE TITLE
0F2-Bowie Mun–TEXAS-USA

### ISSUE THREAD

**Issue by 2000rpm** [InfiniteFlightAirportEditing/Airports#4900]
# Airport Name

Bowie Muni

# Country?

USA

# Improvements that need to be made?

New Taxiways, Ramps

# Are you working on this airport?

Have done.

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MajorTomMueller** [comment]
2000rpm report in slack so that I can get a link between your slack name and your github name.


Why the heck can’t users just use a NAME where a name is asked for....
And why can’t they keep it consistent throughout a community?
I will never understand...

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/82483728-407b5400-9aaf-11ea-9134-558e3b293059.jpg)
