### ISSUE TITLE
WIRR-Budiarto-BANTEN-INDONESIA

### ISSUE THREAD

**Issue by vinoalviano1994** [InfiniteFlightAirportEditing/Airports#4901]
# Airport Name

< Budiarto >

# Country?

< Indonesia >

# Improvements that need to be made?

< Full Rework >

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/82396966-b509b080-9a25-11ea-8551-a397286c8475.jpg)
