### ISSUE TITLE
Duplicate

### ISSUE THREAD

**Issue by ErshovlaD** [InfiniteFlightAirportEditing/Airports#4902]
# Airport Name

Simferopol International Airport

# Country?

RUSSIA

# Improvements that need to be made?

Improvments with 01R/19L and adding a new terminal

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

10 000ft+ Runway

**Comment by MajorTomMueller** [comment]
#1301 somehow poor when even the original editor can not remember that he has done this airport before.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/86974568-30d9cc80-c13c-11ea-920c-79f59ef0151c.png)
