### ISSUE TITLE
ENSN-Skien Geiteryggen Airport-VESTFOLD OG TELEMARK-NORWAY

### ISSUE THREAD

**Issue by bavariaaviation** [InfiniteFlightAirportEditing/Airports#4903]
# Airport Name

Skien Geiteryggen

# Country?

Norway

# Improvements that need to be made?

Full rework

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/80316648-590c8d00-87d5-11ea-9d86-28ffffa2d91b.jpg)
