### ISSUE TITLE
KROA-Roanoke-Blacksburg Regional Airport/Woodrum Field-VIRGINIA-USA

### ISSUE THREAD

**Issue by bavariaaviation** [InfiniteFlightAirportEditing/Airports#4907]
# Airport Name

Roanoke-Blacksburg Regional Airport/Woodrum Field

# Country?

US of A

# Improvements that need to be made?

Full rework

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/80624605-49ce4f00-8a22-11ea-9b9a-2e204d18b6b2.jpg)
