### ISSUE TITLE
EPSY-Olsztyn-Mazury Airport-WARMIAN-MASURIAN-POLAND

### ISSUE THREAD

**Issue by PopuleuxMusicYT** [InfiniteFlightAirportEditing/Airports#4908]
# Airport Name

Olsztyn-Mazury Airport

# Country?

Poland

# Improvements that need to be made?

Full redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low Priority

**Comment by MajorTomMueller** [comment]
https://www.ais.pansa.pl/aip/pliki/EP_AD_2_EPSY_en.pdf

https://www.ais.pansa.pl/aip/pliki/EP_AD_2_EPSY_1-1-1_en.pdf

**Comment by IFsami** [comment]
I will take

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107147271-ae53fe00-6912-11eb-9d77-a3d637609d2d.png)
