### ISSUE TITLE
VVYB-Yen Bai Air Base-YEN BAI-VIETNAM

### ISSUE THREAD

**Issue by MinhNguyN** [InfiniteFlightAirportEditing/Airports#4909]
# Airport Name

Yen Bai Air Base

# Country?

Viet Nam

# Improvements that need to be made?

new airport 

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/84600383-70174500-ae3e-11ea-8275-0c348a660432.png)
