### ISSUE TITLE
VVGL-Gia Lam Airport-HA NOI-VIETNAM

### ISSUE THREAD

**Issue by MinhNguyN** [InfiniteFlightAirportEditing/Airports#4910]
# Airport Name

Gia Lam Airport

# Country?

Viet Nam

# Improvements that need to be made?

everythings

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/82394178-b2578d00-9a1e-11ea-8769-f7ee5cbae2f2.jpg)
