### ISSUE TITLE
ZGMX-Meizhou Meixian Airport-GUANGDONG-CHINA

### ISSUE THREAD

**Issue by AnthonyCK** [InfiniteFlightAirportEditing/Airports#4911]
# Airport Name

< Meizhou Meixian Airport >

# Country?

< China >

# Improvements that need to be made?

< New >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by AnthonyCK** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/81458098-24062000-916f-11ea-9928-1e72e637af72.jpg)
