### ISSUE TITLE
KBOK-Brookings Airport-OREGON-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#4912]
# Airport Name

Brookings Airport

# Country?

USA

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

Ye

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by Czechoslovaki** [comment]
Sent for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/83337834-2d713c80-a284-11ea-9a8e-d6c9ca388ede.png)
