### ISSUE TITLE
ZHES-Enshi Xujiaping Airport-HUBEI-CHINA

### ISSUE THREAD

**Issue by Berlin-N** [InfiniteFlightAirportEditing/Airports#4914]
# Airport Name

< Enshi Xujiaping >

# Country?

< China >

# Improvements that need to be made?

< New >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by Berlin-N** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/81458295-143b0b80-9170-11ea-8ef8-58829c1ae2dd.jpg)
