### ISSUE TITLE
DAOO-Ahmed Ben Bella International Airport-ORAN-ALGERIA

### ISSUE THREAD

**Issue by tonyi31** [InfiniteFlightAirportEditing/Airports#4915]
# Airport Name
Oran Ahmed Ben Bella international 
< Enter text here >

# Country?
Algerie
< Enter text here >

# Improvements that need to be made?
Work from scratch
< Enter text here >

# Are you working on this airport?
yes
< Enter text here >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low
< Enter text here >

**Comment by MajorTomMueller** [comment]
Hi @tonyi31 ,
still with us?

**Comment by MajorTomMueller** [comment]
https://www.sia-enna.dz/PDF/AIP/AD/AD2/DAOO/DAOO.pdf

https://www.sia-enna.dz/PDF/AIP/AD/AD2/DAOO/AD.pdf

**Comment by MBeringuy** [comment]
Since @tonyi31 did not respond, I am attributing this airport to myself.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106356675-0e212800-62c7-11eb-9b2a-d66ed44ff0c0.png)
