### ISSUE TITLE
ENRA-Mo i Rana/Rossvoll Airport-NORDLAND-NORWAY

### ISSUE THREAD

**Issue by bavariaaviation** [InfiniteFlightAirportEditing/Airports#4917]
# Airport Name

Mo i Rana/Rossvoll 

# Country?

Norway

# Improvements that need to be made?

complete rework

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/80626356-afbbd600-8a24-11ea-8f30-40026671c978.jpg)
