### ISSUE TITLE
KLBE-Latrobe/Arnold Palmer Regional Airport-PENNSYLVANIA-USA

### ISSUE THREAD

**Issue by bavariaaviation** [InfiniteFlightAirportEditing/Airports#4918]
# Airport Name

Latrobe/Arnold Palmer Regional

# Country?

USA

# Improvements that need to be made?

complete rework

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/81462151-caa9eb00-9186-11ea-9d15-d2b7f88aacdd.jpg)
