### ISSUE TITLE
EFRY-Rayskala-South Finland-FINLAND

### ISSUE THREAD

**Issue by NoahAllan** [InfiniteFlightAirportEditing/Airports#4919]
# Airport Name

< Räyskälä Airfield >

# Country?

< Finland >

# Improvements that need to be made?

< Airport re-do >

# Are you working on this airport?

< Si >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by Jasonparker102** [comment]
hey id like to take this airport

**Comment by MajorTomMueller** [comment]
![EFRY-git](https://user-images.githubusercontent.com/26853210/132038265-4a9a99f9-4b82-45af-8041-e1c1f03f34ab.png)
