### ISSUE TITLE
VVVT-Vung Tau Air Base-BA RIA VUNG TAU-VIETNAM

### ISSUE THREAD

**Issue by IFUA2003** [InfiniteFlightAirportEditing/Airports#4920]
# Airport Name

< Vung Tau Air Base >

# Country?

< Vietnam >

# Improvements that need to be made?

< The airport has not been added >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/97764186-c8906b80-1adb-11eb-840e-81da0e328d1d.png)
