### ISSUE TITLE
E51-Bagdad Airport-ARIZONA-USA

### ISSUE THREAD

**Issue by jakey200** [InfiniteFlightAirportEditing/Airports#4922]
# Airport Name

Bagdad Airport

# Country?

USA

# Improvements that need to be made?

Redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MajorTomMueller** [comment]
Sorry Jake 😂 you are already assigned to three issues...

**Comment by jakey200** [comment]
official review time
