### ISSUE TITLE
RCYU-Hualien Airport-TAIWAN-TAIWAN

### ISSUE THREAD

**Issue by aads552** [InfiniteFlightAirportEditing/Airports#4932]
# Airport Name

< Hualien Airport>

# Country?

< Taiwan >

# Improvements that need to be made?

< redo from scratch >

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/82398808-0f0c7500-9a2a-11ea-9c73-bb20eca6e357.jpg)
