### ISSUE TITLE
KLGD-La Grande / Union County Airport-OREGON-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#4933]
# Airport Name

La Grande / Union County Airport

# Country?

Americaaa

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

Yep

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by Czechoslovaki** [comment]
Sent For OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/81462028-1c9e4100-9186-11ea-8c88-3fe4b61919f6.jpg)
