### ISSUE TITLE
ZBYC-Yuncheng Zhangxiao Airport-SHANXI-CHINA

### ISSUE THREAD

**Issue by Berlin-N** [InfiniteFlightAirportEditing/Airports#4935]
# Airport Name

< Yuncheng Zhangxiao >

# Country?

< China >

# Improvements that need to be made?

< New >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MajorTomMueller** [comment]
Younger assigned to 3 issues already. Please wait till one of them was closed by passing OR.

**Comment by Berlin-N** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/82397461-e20a9300-9a26-11ea-95ce-eabe7f2ef7b4.jpg)
