### ISSUE TITLE
Duplicates

### ISSUE THREAD

**Issue by IFClaris** [InfiniteFlightAirportEditing/Airports#4936]
# Airport Name

< Phnom Penh International Airport >

# Country?

< Cambodia >

# Improvements that need to be made?

< Reworking on the airport due to new improvements such as new parking stands and taxiways >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< LOW >

**Comment by IFClaris** [comment]
This issue is a duplicate therefore I'm requesting for a supervisor to close this issue. Thank you.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/83972287-e5b26c80-a8a4-11ea-8ef4-c695e393bde2.png)
