### ISSUE TITLE
OERK

### ISSUE THREAD

**Issue by rryetivac** [InfiniteFlightAirportEditing/Airports#4938]
# Airport Name

< OERK - Riyadh >

# Country?

< Saudi Arabia >

# Improvements that need to be made?

< Gates >

# Are you working on this airport?

< I'll do it. >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Terminal in development >

**Comment by kztmtn** [comment]
@rryetivac Read the guide again and check how to make issue..

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/83957996-6e43f500-a832-11ea-9121-a4ddb55cca7b.png)
