### ISSUE TITLE
FZNA-Goma International Airport-DEMOCRATIC REPUBLIC OF THE CONGO-AFRICA

### ISSUE THREAD

**Issue by jakey200** [InfiniteFlightAirportEditing/Airports#4939]
# Airport Name

Goma International

# Country?

Democratic Republic of the Congo

# Improvements that need to be made?

Reeedo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

GP1

**Comment by MajorTomMueller** [comment]
>3

**Comment by jakey200** [comment]
Sent to OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/81995106-cd419000-961f-11ea-9604-c88479996796.jpg)
