### ISSUE TITLE
CYLS-Lake Simcoe Regional Airport-ONTARIO-CANADA

### ISSUE THREAD

**Issue by starziepie** [InfiniteFlightAirportEditing/Airports#4940]
# Airport Name

Lake Simcoe Regional Airport

# Country?

Canada

# Improvements that need to be made?

New Airport, Made from scratch.

# Are you working on this airport?

Yes.

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

N/A

**Comment by moritzbabl** [comment]
User banned, free to be edited

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104107415-9e002300-5281-11eb-8d3b-f5c891d8e25c.png)
