### ISSUE TITLE
LJCE-Cerklje Ob Krki Airport-SPODNJEPOSAVSKA-SLOVENIA

### ISSUE THREAD

**Issue by Sierra5SLO** [InfiniteFlightAirportEditing/Airports#4942]
# Airport Name

Airport "Cerklje ob Krki"

# Country?

Slovenia  

# Improvements that need to be made?

Apron rework, runway improvements 

# Are you working on this airport?

Yes.

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by MBeringuy** [comment]
From what I'm seeing, it will be your first edition. Unless you have already edited airports before, I suggest you choose a smaller and simpler airport for better development of your editing skills.

**Comment by Sierra5SLO** [comment]
Yeah, sure...sounds reasonable... I just didn't really know where to start and since this is one of my local airports I chose it (not knowing whether is it a good idea or not). Do you have any suggestions for smaller airport (I would really like to start with work;)? Thanks for the help!

**Comment by MajorTomMueller** [comment]
![LJCE-git](https://user-images.githubusercontent.com/26853210/104717410-2f0f4800-5721-11eb-85b4-5ca270eb4333.png)
