### ISSUE TITLE
KMML-Southwest Minnesota Regional Marshall/Ryan Field-MINNESOTA-USA

### ISSUE THREAD

**Issue by Gabe-Z** [InfiniteFlightAirportEditing/Airports#4944]
# Airport Name

Southwest Minnesota Regional Marshall/Ryan FIeld

# Country?

USA

# Improvements that need to be made?

Unedited

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/81998226-59f04c00-9628-11ea-9fbe-319b790a7218.jpg)
