### ISSUE TITLE
KSLN-Salina Regional Airport-KANSAS-United States

### ISSUE THREAD

**Issue by zacky89315** [InfiniteFlightAirportEditing/Airports#4945]
# Airport Name

< Salina Regional Airport>

# Country?

< United States >

# Improvements that need to be made?

< Unedited >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< LOW >

**Comment by MajorTomMueller** [comment]
Please report your github name in related slack channel

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90447239-7fb64280-e0a8-11ea-89ad-2c135dca2acb.png)
