### ISSUE TITLE
RK37-G 227-Gyeonggi-SOUTH KOREA

### ISSUE THREAD

**Issue by 2000rpm** [InfiniteFlightAirportEditing/Airports#4946]
# Airport Name

G 227

# Country?

SOUTH KOREA

# Improvements that need to be made?

Out of Service (You can't see airport mark on Google Earth Pro, either.)

# Are you working on this airport?

N/A

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by Gabe-Z** [comment]
Out of service? You mean the airport is closed or what?

**Comment by 2000rpm** [comment]
![rk37](https://user-images.githubusercontent.com/39461161/80945839-b634be00-8e27-11ea-901c-ac1bfcb1d0b5.jpg)

**Comment by 2000rpm** [comment]
what do you think?

**Comment by MBeringuy** [comment]
For the time being this airport should not be added or modified, since there is nothing there. Check that the airport location is correct, that the airport is in good working order and then edit.

**Comment by 2000rpm** [comment]
@MBeringuy I think I figured out.
![rk37](https://user-images.githubusercontent.com/39461161/81462459-a6352980-91ed-11ea-9844-81a175dba562.jpg)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/87228915-e9d11e80-c369-11ea-82c6-8fa1a0a56ed4.png)
