### ISSUE TITLE
CYDF-Deer Lake Regional Airport-NEWFOUNDLAND-CANADA

### ISSUE THREAD

**Issue by mike116119** [InfiniteFlightAirportEditing/Airports#4948]
# Airport Name

< CYDF- Deer Lake Regional AIrport >

# Country?

< Canada >

# Improvements that need to be made?

<Start from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by liamkirky** [comment]
Can I do this please? Shouldn't take long.

**Comment by mike116119** [comment]
Go for it Liam.

**Comment by liamkirky** [comment]
Can I be assigned have the file ready for OR. Only on two issues

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103105727-267d9300-45f5-11eb-9b5f-54442e2a73a4.png)
