### ISSUE TITLE
CA97-Christy Airstrip-CALIFORNIA-USA

### ISSUE THREAD

**Issue by rich-art-02** [InfiniteFlightAirportEditing/Airports#4949]
# Airport Name

Christy Airstrip

# Country?

USA

# Improvements that need to be made?

redo from scratch

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/81997306-baca5500-9625-11ea-94aa-a4132eae4683.jpg)
