### ISSUE TITLE
KSAT-San Antonio International Airport-TEXAS-USA

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#495]
San Antonio, TX, USA

**Comment by kilt46** [comment]
AIRPORT REDRAWN

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20469231/f8464224-af63-11e6-8cbb-cbecf9c61b6d.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78705913-98397380-78e4-11ea-84d7-8fc50b3b39b3.jpg)
