### ISSUE TITLE
KBLH-Blythe Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by PopuleuxMusicYT** [InfiniteFlightAirportEditing/Airports#4950]
# Airport Name

Blythe Airport

# Country?

USA

# Improvements that need to be made?

Full redo

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low Priority

**Comment by StickThelanding** [comment]
I am still working on this airport

**Comment by StickThelanding** [comment]
Can I be reassigned to this airport?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124364760-38299e00-dc09-11eb-9bf7-5c902f30658f.png)
