### ISSUE TITLE
KRGK-Red Wing Regional Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by Gabe-Z** [InfiniteFlightAirportEditing/Airports#4951]
# Airport Name

Red Wing Regional Airport

# Country?

USA

# Improvements that need to be made?

Unedited

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by Gabe-Z** [comment]
Note: I am aware that I have 3 issues I am assigned to but due to GP1, I can be assigned one more time until non-GP1 issue is unassigned.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/82480343-09567400-9aaa-11ea-8b68-cce9f632e1bc.jpg)
