### ISSUE TITLE
EDCE-Landeplatz Eggersdorf-BRANDENBURG-GERMANY

### ISSUE THREAD

**Issue by rich-art-02** [InfiniteFlightAirportEditing/Airports#4953]
# Airport Name

Airstrip Eggersdorf

# Country?

Germany

# Improvements that need to be made?

redo from scratch

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/81990300-48517900-9615-11ea-8602-3e82ef0baa1b.jpg)
