### ISSUE TITLE
KLMT-Crater Lake-Klamath Regional Airport-OREGON-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#4954]
# Airport Name

Crater Lake-Klamath Regional Airport

# Country?

USA

# Improvements that need to be made?

Redo from air molecules

# Are you working on this airport?

Yep

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

10K Runway

**Comment by Czechoslovaki** [comment]
Sent for OR

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/81996652-efd5a800-9623-11ea-8119-9612018a3954.jpg)
