### ISSUE TITLE
KHTS-Huntington Tri-State Regional Airport/Milton J Ferguson Field-WEST VIRGINIA-USA

### ISSUE THREAD

**Issue by bavariaaviation** [InfiniteFlightAirportEditing/Airports#4955]
# Airport Name

Huntington Tri-State Regional Airport/Milton J Ferguson Field

# Country?

United States

# Improvements that need to be made?

full rework

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/81462243-823efd00-9187-11ea-889d-c1c3dd0a9140.jpg)
