### ISSUE TITLE
ENMS-Mosjoen/Kjaerstad Airport-NORDLAND-NORWAY

### ISSUE THREAD

**Issue by bavariaaviation** [InfiniteFlightAirportEditing/Airports#4956]
# Airport Name

Mosjoen/Kjaerstad Airport

# Country?

Norway

# Improvements that need to be made?

full rework

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/81461222-9c291180-9180-11ea-852c-13753ccb88c3.jpg)
