### ISSUE TITLE
NZWP-RNZAF Whenuapai Airport-AUCKLAND-NEW ZEALAND

### ISSUE THREAD

**Issue by Lukeh0** [InfiniteFlightAirportEditing/Airports#4957]
# Airport Name

RNZAF Whenuapai Airport

# Country?

New Zealand

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low, Military Base

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/82400786-8b08bc00-9a2e-11ea-9699-452fc56ab4aa.jpg)
