### ISSUE TITLE
LFMH-Saint-Étienne/Bouthéon Airport-RHÔNE-ALPES-FRANCE

### ISSUE THREAD

**Issue by bavariaaviation** [InfiniteFlightAirportEditing/Airports#4960]
# Airport Name

Saint-Étienne/Bouthéon 

# Country?

France

# Improvements that need to be made?

full rework

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/81995390-99b33580-9620-11ea-8182-9f5d7f89fac8.jpg)
