### ISSUE TITLE
LJPZ-Portorož Airport-OBLANO-KRASKA-SLOVENIA

### ISSUE THREAD

**Issue by bavariaaviation** [InfiniteFlightAirportEditing/Airports#4961]
# Airport Name

Portorož

# Country?

Slovenia

# Improvements that need to be made?

full rework

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/81992318-936d8b00-9619-11ea-93c6-ca153282eae5.jpg)
