### ISSUE TITLE
SCVH-La Victoria De Chacabuco Airport-SANTIAGO-CHILE

### ISSUE THREAD

**Issue by vichols1506** [InfiniteFlightAirportEditing/Airports#4962]
# Airport Name

SCVH

# Country?

CHILE

# Improvements that need to be made?

ADD NEW AIRPORT

# Are you working on this airport?

YES

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

LOW

**Comment by MBeringuy** [comment]
Hello. Are you already on the airport editing team Slack?

**Comment by vichols1506** [comment]
Hello, sorry it was my mistake I just sent the request to join
Have a good day

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/82396123-87bc0300-9a23-11ea-99a7-82782b2784de.jpg)
