### ISSUE TITLE
SWIW-Brigadeiro Eduardo Gomes Airport-MATO GROSSO-BRAZIL

### ISSUE THREAD

**Issue by victormw22** [InfiniteFlightAirportEditing/Airports#4963]
# Airport Name

< Brigadeiro Eduardo Gomes >

# Country?

< Brazil >

# Improvements that need to be made?

<Redone from scratch >

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/83308169-da3bb300-a1cb-11ea-8a9c-4b114df7558e.png)
