### ISSUE TITLE
RKNC-Camp Page/K-47 Chunchon Airbase-Gangwon Province-South Korea

### ISSUE THREAD

**Issue by 2000rpm** [InfiniteFlightAirportEditing/Airports#4964]
# Airport Name

Camp Page/K-47 Air Base

# Country?

South Korea

# Improvements that need to be made?

Closed
[Ex-U.S. army base Camp Page begins new South Korea chapter](https://upi.com/6707941)
[Camp Page](https://en.wikipedia.org/wiki/Camp_Page)
![RKNC google map pro yr2004](https://user-images.githubusercontent.com/39461161/81489873-e3fd8500-92b5-11ea-9e96-a1064a4f06ca.jpg)
![RKNC google map pro yr2020](https://user-images.githubusercontent.com/39461161/81489879-eb249300-92b5-11ea-8cdc-6a812d117531.jpg)

# Are you working on this airport?

No

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MajorTomMueller** [comment]
We do not add closed and airfields. Especially not when they are now used in a aircraft operations contradicting Manor

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/87235001-844a5580-c39c-11ea-9eed-ee01efe0f086.png)
