### ISSUE TITLE
EDOI-Sonderlandeplatz Bienenfarm-BRANDENBURG-GERMANY

### ISSUE THREAD

**Issue by rich-art-02** [InfiniteFlightAirportEditing/Airports#4965]
# Airport Name

Airstrip Bienenfarm

# Country?

Germany

# Improvements that need to be made?

redo from scratch

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by MajorTomMueller** [comment]
FYI:
Kennung: EDOI

Kanal: 134.990
(Bienenfarm INFO)

Koordinaten:
N52° 39,70' E12° 44,77'
5.5NM NW Nauen
Höhe: 100ft / 30,5 m MSL

Piste: 12/30, 860m x 40m, Gras
Platzrunde: NE 900ft

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/82474343-49fdbf80-9aa1-11ea-8053-66c37eb62f1f.jpg)
