### ISSUE TITLE
MRTR-Tambor Airport-PUNTARENAS-COSTA RICA

### ISSUE THREAD

**Issue by dcaiadaviation** [InfiniteFlightAirportEditing/Airports#4966]
# Airport Name

Tambor Airport

# Country?

Costa Rica

# Improvements that need to be made?

The airport is default, the entire thing needs to be rebuilt from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by dcaiadaviation** [comment]
Sent to the OR!

**Comment by zhf21** [comment]
I can do this. 🙂

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124195454-1fe24380-da90-11eb-9cdb-d684eeaccafc.png)
