### ISSUE TITLE
MMCL-Culiacán International Airport-SINALOA-MEXICO

### ISSUE THREAD

**Issue by FlyingOstrich14** [InfiniteFlightAirportEditing/Airports#4969]
# Airport Name

< Bachigualato Federal International Airport or Culiacán International Airport >

# Country?

< Mexico >

# Improvements that need to be made?

< Redo the airport from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by FlyingOstrich14** [comment]
Sent to OR :)

**Comment by FlyingOstrich14** [comment]
Sent to PR again

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104094238-21efe600-5255-11eb-83c1-0aab03207c0b.png)
