### ISSUE TITLE
UUYK-Aeroport Vuktyl-KOMI REPUBLIC-RUSSIA

### ISSUE THREAD

**Issue by Ocean1c** [InfiniteFlightAirportEditing/Airports#4970]
# Airport Name

< UUYK>

# Country?

< Russia>

# Improvements that need to be made?

< Scratch >

# Are you working on this airport?

< Yes>

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/84555489-e30ba900-ace2-11ea-9bf1-29fdad09f5b4.png)
