### ISSUE TITLE
MMUN-Cancún International Airport-QUINTANA ROO-MEXICO

### ISSUE THREAD

**Issue by FlyingOstrich14** [InfiniteFlightAirportEditing/Airports#4971]
# Airport Name

< Cancún International Airport >

# Country?

< Mexico >

# Improvements that need to be made?

< New taxiway connecting Terminal 4 with runway 12L >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< 10000ft+ Runway >

**Comment by moritzbabl** [comment]
Already done in #566

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/83957826-acd8b000-a830-11ea-84e2-5d01f3845bd9.png)
