### ISSUE TITLE
EPKP-Pobiednik Wielki Airport-LESSER POLAND-POLAND

### ISSUE THREAD

**Issue by FlyingOstrich14** [InfiniteFlightAirportEditing/Airports#4972]
# Airport Name

< Pobiednik Wielki Airport >

# Country?

< Poland >

# Improvements that need to be made?

< New airport >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MajorTomMueller** [comment]
I really like the polish Aviation, they have even for small airfields a public documentation!

https://www.ais.pansa.pl/vfr/pliki/EP_AD_4_EPKP_en.pdf

https://www.ais.pansa.pl/vfr/pliki/EP_AD_4_EPKP_3-0_en.pdf

And:
https://lotniska.dlapilota.pl/krakow-pobiednik-wielki

**Comment by FlyingOstrich14** [comment]
Thanks for the extra info man!

**Comment by FlyingOstrich14** [comment]
Sent to PR again

**Comment by MajorTomMueller** [comment]
![EPKP-git](https://user-images.githubusercontent.com/26853210/132123969-3002600f-f4f8-4f00-b86d-6a7b6d6f653f.png)
