### ISSUE TITLE
ULDW-Varandey Airport-ARKHANGELSK-RUSSIA

### ISSUE THREAD

**Issue by Ocean1c** [InfiniteFlightAirportEditing/Airports#4973]
# Airport Name

ULDW

# Country?

Russia

# Improvements that need to be made?

Scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/84552419-404d2d80-acd6-11ea-9d2e-da6779bc185c.png)
