### ISSUE TITLE
MRSI-San Isidro de El General Airport-SAN JOSE-COSTA RICA

### ISSUE THREAD

**Issue by dcaiadaviation** [InfiniteFlightAirportEditing/Airports#4974]
# Airport Name

San Isidro de El General Airport (MRSI)

# Country?

Costa Rica

# Improvements that need to be made?

Airport not in game

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by dcaiadaviation** [comment]
Sent to the OR

**Comment by MajorTomMueller** [comment]
![MRSI](https://user-images.githubusercontent.com/26853210/132038218-a05edb35-67c2-4a91-803a-24e14f936b36.png)
