### ISSUE TITLE
RPNS-Sayak Airport-SURIGATO DEL NORTE-PHILIPPINES

### ISSUE THREAD

**Issue by pj12decastro** [InfiniteFlightAirportEditing/Airports#4979]
# Airport Name

< Sayak Airport  >

# Country?

< Philippines >

# Improvements that need to be made?

< Gate >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Enter text here >

**Comment by jaypzs** [comment]
can i open and take this issue? Thanks!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123340384-b7d0b200-d511-11eb-9963-5e62dbf57cf7.png)
