### ISSUE TITLE
CYVR-Vancouver International Airport-VANCOUVER-CANADA

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#498]
Vancouver International Airport, Canada

**Comment by planemadnews** [comment]
Does this need to be redone?

**Comment by TristinWoolf** [comment]
Yes, @planemadnews

**Comment by planemadnews** [comment]
Want to asign it to me @TristinWoolf

**Comment by TristinWoolf** [comment]
Sure thing!

**Comment by planemadnews** [comment]
Please Re-assign - I can no longer do this

**Comment by Aviationluver** [comment]
I would like to re-do this one.

**Comment by Aviationluver** [comment]
Sent this one off for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17756206/1e4aed68-64a4-11e6-97f5-4dd72a83a8fc.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17756248/5d94cfd4-64a4-11e6-83fe-ec0c07d2b8e0.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17756265/726e6adc-64a4-11e6-8d46-2b40eed1d0d2.png)

**Comment by DelsterX** [comment]
This Airport has gone from gate cleanup to be being completely being redone and is making active progress. Current progress is about 78%. Target completion is early December 2018.

**Comment by DelsterX** [comment]
Sent for official  review January 5, 2019. 
Peer review previously completed.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51474920-733ffb80-1d46-11e9-9f6a-4eb01222af8a.png)

**Comment by kilt46** [comment]
RWY 12/30 renamed to RWY 13/31
