### ISSUE TITLE
EDBE-Sonderlandeplatz Brandenburg / Mühlenfeld-BRANDENBURG-GERMANY

### ISSUE THREAD

**Issue by rich-art-02** [InfiniteFlightAirportEditing/Airports#4981]
# Airport Name

Sonderlandeplatz Brandenburg / Mühlenfeld

# Country?

Germany

# Improvements that need to be made?

redo from scratch

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/82474869-0b1c3980-9aa2-11ea-9dd2-cf9438cd7d3b.jpg)
