### ISSUE TITLE
SCVH

### ISSUE THREAD

**Issue by EternalGoose** [InfiniteFlightAirportEditing/Airports#4982]
# Airport Name

< SCVH >

# Country?

< Chile>

# Improvements that need to be made?

< Airport is not on IF >

# Are you working on this airport?

< Not yet >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by bavariaaviation** [comment]
🙄♻️ #4962

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/83953928-404aba80-a80a-11ea-93c1-39f2f232e181.png)
