### ISSUE TITLE
UUBI-Ivanovo Airport-IVANOVO OBLAST-RUSSIA

### ISSUE THREAD

**Issue by Ocean1c** [InfiniteFlightAirportEditing/Airports#4984]
# Airport Name

UUBI

# Country?

Russia

# Improvements that need to be made?

Made from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by Ocean1c** [comment]
Can I get unassigned from this.

**Comment by MajorTomMueller** [comment]
Why?

**Comment by AleksanderIF** [comment]
@Ocean1c, are you still working on it?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111075489-23889500-84b6-11eb-9d7d-e1cb42154a22.png)
