### ISSUE TITLE
EDBQ-Sonderlandeplatz Bronkow-BRANDENBURG-GERMANY

### ISSUE THREAD

**Issue by rich-art-02** [InfiniteFlightAirportEditing/Airports#4985]
# Airport Name

Sonderlandeplatz Bronkow

# Country?

Germany

# Improvements that need to be made?

redo from scratch

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/82475281-a1505f80-9aa2-11ea-8d27-c68fd2e04c6e.jpg)
