### ISSUE TITLE
OBBS-Isa Airbase-BAHRAIN

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#4986]
# Airport Name

Isa Airbase

# Country?

Bahrain

# Improvements that need to be made?

scratch

# Are you working on this airport?

guess what

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

12k

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/82398179-91943500-9a28-11ea-87c1-c2d263df5c5e.jpg)
