### ISSUE TITLE
SCRG-La Independencia Airport-RANCAGUA-CHILE

### ISSUE THREAD

**Issue by vichols1506** [InfiniteFlightAirportEditing/Airports#4987]
# Airport Name

< SCRG>

# Country?

< CHILE >

# Improvements that need to be made?

< Build from scratch >

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/83946157-9bfa5100-a7d4-11ea-9739-f57f74e2f9cd.png)
