### ISSUE TITLE
00MN-Battle Lake Municipal-MINNESOTA-USA

### ISSUE THREAD

**Issue by Gabe-Z** [InfiniteFlightAirportEditing/Airports#4988]
# Airport Name

Battle Lake Municipal

# Country?

USA

# Improvements that need to be made?

Unedited

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/82479806-42daaf80-9aa9-11ea-91e7-a1df99ca345e.jpg)
