### ISSUE TITLE
EGAA-Belfast International Airport-ANTRIM-UNITED KINGDOM

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#499]
Belfast International

**Comment by kilt46** [comment]
Airport done from scratch by JFKPlaneSpotter

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17196714/3bdaa126-542c-11e6-856a-98a4d11109a7.png)

**Comment by IFAEpat** [comment]
Gating

**Comment by IFAEpat** [comment]
Gated

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17456373/39285c36-5b9b-11e6-8c04-4c3a8942d6f1.png)
TERMINAL
![image](https://cloud.githubusercontent.com/assets/14023167/17456376/46aac5ba-5b9b-11e6-8436-d298e9dca6ef.png)
MILITARY
![image](https://cloud.githubusercontent.com/assets/14023167/17456378/5358b498-5b9b-11e6-8f65-5083e2605769.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32753207-a3c5977a-c891-11e7-92e8-f767497bed3e.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46247003-db9b5380-c3ca-11e8-9678-c5042ed60677.png)
