### ISSUE TITLE
L00-Rosamond Skypark-CALIFORNIA-USA

### ISSUE THREAD

**Issue by jakey200** [InfiniteFlightAirportEditing/Airports#4993]
# Airport Name

Rosamond Skypark

# Country?

USA

# Improvements that need to be made?

Redo

# Are you working on this airport?

Done

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by jakey200** [comment]
Sent for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/83357873-c8c1ea80-a334-11ea-9042-a72783ebe4b8.png)
