### ISSUE TITLE
SCSD-San Fernando Airport-San Fernando-Chile

### ISSUE THREAD

**Issue by vichols1506** [InfiniteFlightAirportEditing/Airports#4994]
# Airport Name

< San Fernando >

# Country?

< Chile>

# Improvements that need to be made?

Build from scratch

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low>

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/83946006-e0d1b800-a7d3-11ea-8df7-d1618b35a2d2.png)
