### ISSUE TITLE
SCOV-El Tuqui Airport-Ovalle-CHILE

### ISSUE THREAD

**Issue by vichols1506** [InfiniteFlightAirportEditing/Airports#4995]
# Airport Name

< El Tuqui >

# Country?

< Chile >

# Improvements that need to be made?

< Build from scratch>

# Are you working on this airport?

< yes>

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< LOW>

**Comment by MajorTomMueller** [comment]
you have already reached the limit of 3 open issues. Couldn’t assign you.

**Comment by vichols1506** [comment]
> you have already reached the limit of 3 open issues. Couldn’t assign you.

One of my aiports was accepted, so now can i be assign to this one ?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/83945790-a9164080-a7d2-11ea-8141-30cbf0808cf0.png)
