### ISSUE TITLE
VILH-Kushok Bakula Rimpochee Airport-LADAKH-INDIA

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#4996]
# Airport Name

Kushok Bakula Rimpochee Airport / Leh Airbase

# Country?

India

# Improvements that need to be made?

scratch

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

no

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/82477943-88e24400-9aa6-11ea-8436-1d1e57960062.jpg)

**Comment by MajorTomMueller** [comment]
you are faster then me
