### ISSUE TITLE
EDUF-Sonderlandeplatz Falkenberg-Loennewitz-BRANDENBURG-GERMANY

### ISSUE THREAD

**Issue by rich-art-02** [InfiniteFlightAirportEditing/Airports#4998]
# Airport Name

Sonderlandeplatz Falkenberg-Loennewitz

# Country?

Germany

# Improvements that need to be made?

redo from scratch

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/83929050-97dc1e00-a757-11ea-89ae-1af74b3ff156.png)
