### ISSUE TITLE
1O5-Montague Yreka Rohrer Field-CALIFORNIA-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#4999]
# Airport Name

Montague Yreka Rohrer Field

# Country?

USA

# Improvements that need to be made?

full redo

# Are you working on this airport?

yeah

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by brennanhackard** [comment]
sent to OR :D

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/83199346-9cc12200-a106-11ea-854a-85ecef334dd7.png)
