### ISSUE TITLE
KSEA-Seattle-Tacoma International Airport-WASHINGTON-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#5]
Already has parking spots and lines, but someone may want to improve them a bit

**Comment by carmichaelalonso** [comment]
Need to fix spelling of Hangar - tower viewpoint.

**Comment by Swang007** [comment]
Fixed taxiway location issue, cut hole for grass

**Comment by kilt46** [comment]
Tidy up terminal buildings and gates

**Comment by kilt46** [comment]
Cleaned up Main terminal Buildings and gates

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20024549/5a8f50b2-a2b5-11e6-829f-efb8a1440c37.png)

**Comment by MajorTomMueller** [comment]
Snapping on 4th access to RWY 34R.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/71484944-ae1ba080-27ed-11ea-95cb-71193653a304.jpg)
