### ISSUE TITLE
KHIO-Portland-Hillsboro Airport-OREGON-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#50]
David wanted this one done

**Comment by Swang007** [comment]
KHIO has a missing runway: 31R/13L 
@carmichaelalonso This was yours months ago.

**Comment by Swang007** [comment]
https://community.infinite-flight.com/t/khio-missing-runway-31r-13l/8935

**Comment by dushyants19** [comment]
Who's doing this? Region?

**Comment by carmichaelalonso** [comment]
Nobody, you can @dushyants19 if you want. It's in Seattle.

**Comment by kilt46** [comment]
Working it

**Comment by kilt46** [comment]
Complete

**Comment by kilt46** [comment]
Image: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=KHIO

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21208292/d3c5b51a-c232-11e6-8d44-f62e0fd68eca.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78704480-4a237080-78e2-11ea-9e20-79105f193c5a.jpg)
