### ISSUE TITLE
ESGH-Herrljunga Airport-GOTALAND-SWEDEN

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#500]
Herrljunga Airport, Sweden

**Comment by kilt46** [comment]
Assigned to JFplanespotter: no current name available to select

**Comment by IFAEpat** [comment]
Clouds in imagery, unable to produce

**Comment by IFAEpat** [comment]
Clouds in imagery, unable to produce

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26037008/c10e6a5e-38af-11e7-9f0f-8a366cee65ac.png)
