### ISSUE TITLE
K61-Moritz Memorial Airport-KANSAS-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#5000]
# Airport Name

Moritz Memorial Airport

# Country?

USA

# Improvements that need to be made?

full redo

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by brennanhackard** [comment]
Sent to OR :D

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/84581299-8fae5f00-ada5-11ea-8825-9ba995625ac0.png)
