### ISSUE TITLE
ELNT-Wiltz-Noertrange-DIEKIRCH-LUXEMBURG

### ISSUE THREAD

**Issue by VinceC00** [InfiniteFlightAirportEditing/Airports#5001]
# Airport Name

Wiltz-Noertrange Airport

# Country?

Luxembourg

# Improvements that need to be made?

Done from scratch 

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

None

**Comment by Czechoslovaki** [comment]
![image](https://user-images.githubusercontent.com/51279558/120058276-9c4fb580-bffe-11eb-95ce-fe33ea9dc993.png)
