### ISSUE TITLE
T35-Cameron Muni Airpark-TEXAS-USA

### ISSUE THREAD

**Issue by 2000rpm** [InfiniteFlightAirportEditing/Airports#5004]
# Airport Name

< T35 >

# Country?

< USA >

# Improvements that need to be made?

< Redo >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by 2000rpm** [comment]
sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/83979802-8ec58b00-a8d6-11ea-9290-f84847d26e7b.png)
