### ISSUE TITLE
SCOV-El Tuqui Airport-Ovalle-Chile

### ISSUE THREAD

**Issue by vichols1506** [InfiniteFlightAirportEditing/Airports#5008]
# Airport Name

< El Tuqui >

# Country?

< Chile>

# Improvements that need to be made?

< build from scratch>

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< LOW >

**Comment by MBeringuy** [comment]
Please do not create duplicate issues. If you want to be assigned to an airport with an existing issue, wait for a response from a supervisor.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/83952859-9ebf6b00-a801-11ea-94da-f3119c8310ab.png)
