### ISSUE TITLE
LHBP-Budapest Liszt Ferenc Airport-BUDAPEST-HUNGARY

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#501]
Budapest Ferenc Liszt International Airport

**Comment by IFAEpat** [comment]
Can anyone assign me? :)

**Comment by IFAEpat** [comment]
Can someone else do this please? It's very misaligned, and the satellite WEDbing imagery makes it difficult to draw lines. I may work on something else

**Comment by IFAEpat** [comment]
I will being doing this, I'll assign myself after #658

**Comment by IFAEpat** [comment]
I finally got the chance to start this. 

Estimated Time of completion: August 12

**Comment by IFAEpat** [comment]
Finally done!

7aba374

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34082789-7236c05e-e32a-11e7-981e-0a2092abdff6.png)

**Comment by brunocr98** [comment]
@kztmtn will be redoing this airport.

**Comment by kztmtn** [comment]
Thank you, will use Yandex, it's the latest.

**Comment by kztmtn** [comment]
![LHPB-git](https://user-images.githubusercontent.com/46369763/78234668-728e2200-7512-11ea-9351-9d80f78cf35e.jpg)
