### ISSUE TITLE
SWZW-Alagoinhas Airport-BAHIA-BRAZIL

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#5010]
# Airport Name

Alagoinhas Airport

# Country?

Brazil

# Improvements that need to be made?

Redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by jakey200** [comment]
Sent for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/82956858-5ab5a600-9f77-11ea-9375-19d37429ea92.png)

**Comment by kilt46** [comment]
https://pergamum.anac.gov.br/arquivos/PA2020-1820.pdf

This is in the wrong location. I believe that this airport is no longer active please check.

**Comment by MBeringuy** [comment]
ICAO is wrong. Check the link https://ais.decea.gov.br/?i=aerodromos&codigo=SWZW

**Comment by MBeringuy** [comment]
ICAO updated.
