### ISSUE TITLE
TKPN-Charlestown/Vance W. Amory Airport-NEVIS-SAINT KITTS AND NEVIS

### ISSUE THREAD

**Issue by FlyBoii31** [InfiniteFlightAirportEditing/Airports#5011]
# Airport Name

< Charlestown/Vance W. Amory Airport >

# Country?

< Saint Kitts and Nevis >

# Improvements that need to be made?

< Full Rework >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/86673519-61472c80-bfbd-11ea-828b-1f3ce6a895fb.png)
