### ISSUE TITLE
KAAT-Alturas Municipal Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#5012]
# Airport Name

Alturas Municipal Airport

# Country?

USA

# Improvements that need to be made?

full redo

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by brennanhackard** [comment]
Sent to OR :D

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/87889319-9f4d4300-c9f6-11ea-91bb-4d212b962b3f.png)
