### ISSUE TITLE
SNLH-Lajinha Airport-MINAS GERAIS-BRAZIL

### ISSUE THREAD

**Issue by jakey200** [InfiniteFlightAirportEditing/Airports#5013]
# Airport Name

Lajinha Airport

# Country?

Brazil

# Improvements that need to be made?

Redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by jakey200** [comment]
Sent for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/82956429-62c11600-9f76-11ea-903d-45df7c07d599.png)
