### ISSUE TITLE
ORNI-Al Najaf International Airport-IRAQ

### ISSUE THREAD

**Issue by Hussein18Zreik** [InfiniteFlightAirportEditing/Airports#5014]
# Airport Name

Al Najaf International Airport

# Country?
 Iraq 

# Improvements that need to be made?

Airport is not in Infinite Flight

# Are you working on this airport?
Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MajorTomMueller** [comment]
Still alive @Hussein18Zreik?
Still working on this one?
IFC is calling you:
https://community.infiniteflight.com/t/airport-and-navigation-updates-november-2020/496923/38

**Comment by GBKarp** [comment]
@Hussein18Zreik are you still working on this?
Because if not I wanna do it

**Comment by ECoops-123** [comment]
@Daniel-Baiks will take over this.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111042350-9c2e1980-8402-11eb-817b-3be917437da6.png)
