### ISSUE TITLE
UBBN-Nakhchivan Airport-NAKHCHIVAN-AZERBAIJAN

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#5015]
# Airport Name

< Nakhchivan Airport >

# Country?

< Azerbaijan >

# Improvements that need to be made?

< redo >

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< GP2 (14R/32L) >

**Comment by AleksanderIF** [comment]
Sent to OR :D

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/83969839-d37e0180-a897-11ea-8086-6160eaf0a540.png)

**Comment by Czechoslovaki** [comment]
@AleksanderIF will revisit this airport.

- New military apron
- Construction of the new runway is completed

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113069839-cf083980-9186-11eb-8e98-5f88ba72883c.png)
