### ISSUE TITLE
SNVB-Valenca Airport-BAHIA-BRAZIL

### ISSUE THREAD

**Issue by victormw22** [InfiniteFlightAirportEditing/Airports#5016]
# Airport Name

< Valenca >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/83571628-bf2fb280-a4ed-11ea-910f-b5ec8d23cbba.png)
