### ISSUE TITLE
RPVP-Puerto Princesa International Airport-Palawan-Philippines

### ISSUE THREAD

**Issue by zacky89315** [InfiniteFlightAirportEditing/Airports#5017]
# Airport Name

< Puerto Princesa International Airport >

# Country?

< Philippines >

# Improvements that need to be made?

< unedited >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85911407-b11e3a80-b7ea-11ea-8abc-81b3264c463b.png)
