### ISSUE TITLE
EDAS-Sonderlandeplatz Finsterwalde/Heinrichsruh-BRANDENBURG-GERMANY

### ISSUE THREAD

**Issue by rich-art-02** [InfiniteFlightAirportEditing/Airports#5018]
# Airport Name

Sonderlandeplatz Finsterwalde/Heinrichsruh

# Country?

Germany

# Improvements that need to be made?

redo from scratch

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/83928896-fce34400-a756-11ea-88ff-ba9f00837309.png)
