### ISSUE TITLE
ZPLJ-Lijiang Sanyi Airport-YUNNAN-CHINA

### ISSUE THREAD

**Issue by AnthonyCK** [InfiniteFlightAirportEditing/Airports#5022]
# Airport Name

< Lijiang Sanyi Airport >

# Country?

< China >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by AnthonyCK** [comment]
Sent for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/83467761-7e2d9480-a440-11ea-84ac-d160a3614f31.png)
