### ISSUE TITLE
WAQT-Kalimarau-EAST BORNEO-INDONESIA

### ISSUE THREAD

**Issue by vinoalviano1994** [InfiniteFlightAirportEditing/Airports#5023]
# Airport Name

< Kalimarau >

# Country?

< Indonesia >

# Improvements that need to be made?

< Full Rework >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/83695261-4e58cb00-a5bf-11ea-9e50-3fb9dec4fd4d.png)
