### ISSUE TITLE
KNID-China Lake NAWS-CALIFORNIA-USA

### ISSUE THREAD

**Issue by andreagrr** [InfiniteFlightAirportEditing/Airports#5024]
# Airport Name

Naval Air Weapons Station China Lake

# Country?

United States

# Improvements that need to be made?

Complete Redone

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MajorTomMueller** [comment]
Will keep an eye on this

**Comment by andreagrr** [comment]
ok

**Comment by MajorTomMueller** [comment]
any progress @andreagrr ?

**Comment by andreagrr** [comment]
> any progress @andreagrr ?

Yes, I have only to finish spawns and some lines

**Comment by ShaneAviation** [comment]
I’ll do this one.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122681555-727f4e00-d1ba-11eb-8805-90fef1917c40.png)
