### ISSUE TITLE
28LL-Williamson Airstrip-ILLINOIS-USA

### ISSUE THREAD

**Issue by aads552** [InfiniteFlightAirportEditing/Airports#5025]
![image](https://user-images.githubusercontent.com/14023167/110242945-e5233100-7f1d-11eb-8d73-c66032d90093.png)

**Comment by MajorTomMueller** [comment]
Linked to #5026 
While I have seen nothing from you so far I will not assign you to a advanced project like two linked airports. I highly suggest that you get known for your skills before doing so.
