### ISSUE TITLE
2H0-Shelby County Airport-ILLINOIS-USA

### ISSUE THREAD

**Issue by aads552** [InfiniteFlightAirportEditing/Airports#5026]
![image](https://user-images.githubusercontent.com/14023167/110247972-700f2600-7f34-11eb-91b0-2eebb50bb8dd.png)

**Comment by MajorTomMueller** [comment]
Linked to #5025 
While I have seen nothing from you so far I will not assign you to a advanced project like two linked airports. I highly suggest that you get known for your skills before doing so.
