### ISSUE TITLE
3S8-Grants Pass Airport-OREGON-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#5027]
# Airport Name

Grants Pass Airport 

# Country?

A M E R I C A

# Improvements that need to be made?

Full Redo

# Are you working on this airport?

Yee

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/83196526-adbb6480-a101-11ea-9076-fcbf8501ac74.png)
