### ISSUE TITLE
UUYY-Syktyvkar-KOMI-RUSSIA

### ISSUE THREAD

**Issue by Ryanairy55** [InfiniteFlightAirportEditing/Airports#5028]
# Airport Name

Syktyvkar

# Country?

Russia

# Improvements that need to be made?

From scratch

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

no priorities found

**Comment by MajorTomMueller** [comment]
Your 3rd issue

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90077333-7eab9c80-dcc7-11ea-93ec-c384a0abc0df.png)
