### ISSUE TITLE
KGJT-Grand Junction Airport-COLORADO-USA

### ISSUE THREAD

**Issue by jakey200** [InfiniteFlightAirportEditing/Airports#5029]
# Airport Name

Grand Junction Airport

# Country?

USA

# Improvements that need to be made?

Redo

# Are you working on this airport?

YEs

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

10k+

**Comment by jakey200** [comment]
Sent for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/86470904-f9b18880-bd01-11ea-86bf-26ed9d22326b.png)
