### ISSUE TITLE
HALL-Lalibela Airport-AMHARA-ETHIOPIA

### ISSUE THREAD

**Issue by CaptRiley** [InfiniteFlightAirportEditing/Airports#5030]
# Airport Name

Lalibela Airport

# Country?

Ethiopia

# Improvements that need to be made?

Will be redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low Priority

**Comment by CaptRiley** [comment]
Sent to OR 4/30/21

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116934439-9ac2e580-ac2a-11eb-9add-e63cf051ff83.png)
