### ISSUE TITLE
YPCC-Cocos-Keeling Island Airport-COCOS (KNEELING) ISLAND-AUSTRALIA

### ISSUE THREAD

**Issue by Aceorbit** [InfiniteFlightAirportEditing/Airports#5031]
# Airport Name

Cocos-Keeling Island Airport

# Country?

Australia

# Improvements that need to be made?

Scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by Aceorbit** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/95521431-1dced680-098f-11eb-8198-c7755425bc0f.png)
