### ISSUE TITLE
RPUB-Loakan Airport-BAGUIO CITY-PHILIPPINES

### ISSUE THREAD

**Issue by jaypzs** [InfiniteFlightAirportEditing/Airports#5032]
# Airport Name

< Loakan Airport >

# Country?

< Philippines >

# Improvements that need to be made?

< Add Ramp and Gates >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low>

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/87234368-bc9a6580-c395-11ea-83a2-e16ee74299a6.png)
