### ISSUE TITLE
ZBDS-Ordos Ejin Horo Airport-INNER MONGOLIA-CHINA

### ISSUE THREAD

**Issue by AnthonyCK** [InfiniteFlightAirportEditing/Airports#5036]
# Airport Name

< Ordos Ejin Horo Airport >

# Country?

< China >

# Improvements that need to be made?

< New >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< 10000ft+ >

**Comment by AnthonyCK** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85909502-f25d1d00-b7df-11ea-81db-7ba2ee285056.png)
