### ISSUE TITLE
KSPZ-Silver Springs Airport-NEVADA-USA

### ISSUE THREAD

**Issue by jakey200** [InfiniteFlightAirportEditing/Airports#5038]
# Airport Name

Silver Springs

# Country?

US of A

# Improvements that need to be made?

Redo

# Are you working on this airport?

Si

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/83364249-954b8400-a365-11ea-9b0e-445ec12f69c6.png)
