### ISSUE TITLE
SCTB-Tobalaba Airport-SANTIAGO-CHILE

### ISSUE THREAD

**Issue by vichols1506** [InfiniteFlightAirportEditing/Airports#5040]
# Airport Name

< Eulogio Sanchez  >

# Country?

< Chile >

# Improvements that need to be made?

< Scratch>

# Are you working on this airport?

< Yes>

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low>

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/88467626-6271c800-ce9e-11ea-8588-7efe98f0314b.png)
