### ISSUE TITLE
WALS-APT Pranoto-EAST BORNEO-INDONESIA

### ISSUE THREAD

**Issue by vinoalviano1994** [InfiniteFlightAirportEditing/Airports#5041]
# Airport Name

< APT Pranoto >

# Country?

< Indonesia >

# Improvements that need to be made?

< Full Rework >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/89100613-0935f700-d3be-11ea-9791-cc969c00f75e.png)
