### ISSUE TITLE
SCSF-Victor Lafon Airport-SAN FELIPE-CHILE

### ISSUE THREAD

**Issue by vichols1506** [InfiniteFlightAirportEditing/Airports#5042]
# Airport Name

< Victor Lafon >

# Country?

< CHILE>

# Improvements that need to be made?

< Scratch >

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85182695-0e484800-b24f-11ea-90d8-c6c444949607.png)
