### ISSUE TITLE
LTCM-Sinop Airport-SINOP-TURKEY

### ISSUE THREAD

**Issue by Ocean1c** [InfiniteFlightAirportEditing/Airports#5043]
# Airport Name

LTCM

# Country?

Turkey

# Improvements that need to be made?

Scratch 

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85909200-3d763080-b7de-11ea-8984-1915682ba2e8.png)
