### ISSUE TITLE
SCRD-Rodelillo Airport-VALPARAISO-CHILE

### ISSUE THREAD

**Issue by vichols1506** [InfiniteFlightAirportEditing/Airports#5044]
# Airport Name

< Rodelillo >

# Country?

< Chile >

# Improvements that need to be made?

< Scratch>

# Are you working on this airport?

< Yes  >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85181973-f374d400-b24c-11ea-88cf-f56f2d7591bc.png)
