### ISSUE TITLE
RPSP - New Bohol (Panglao) International Airport, PHILIPPINES

### ISSUE THREAD

**Issue by jaypzs** [InfiniteFlightAirportEditing/Airports#5045]
# Airport Name

< New Bohol (Panglao) International Airport >

# Country?

< PHILIPPINES >

# Improvements that need to be made?

< New Airport >

# Are you working on this airport?

< yes>

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low priority
![New Bohol 1](https://user-images.githubusercontent.com/65849473/83086735-2b5f8000-a0c2-11ea-9481-6521b5999ec2.PNG)
![New Bohol 2](https://user-images.githubusercontent.com/65849473/83086738-2dc1da00-a0c2-11ea-9541-794510e5085b.PNG)

 >

**Comment by MajorTomMueller** [comment]
Just to add some pressure @jaypzs 
https://community.infiniteflight.com/t/airport-and-navigation-updates-june-2020/445573/180
😂

**Comment by jaypzs** [comment]
Hey, im still looking for updated imagery (gates are not yet updated on Google map). :(

**Comment by jaypzs** [comment]
Yes! Googlemap just granted my request for an updated imagery.. will update the airport this weekend.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/93725757-25147880-fb77-11ea-855a-687d025032d2.png)
