### ISSUE TITLE
ZLDH-Dunhuang Mogao Airport-GANSU-CHINA

### ISSUE THREAD

**Issue by Berlin-N** [InfiniteFlightAirportEditing/Airports#5046]
# Airport Name

< Dunhuang Mogao Airport >

# Country?

< China >

# Improvements that need to be made?

< New >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< 10000ft+ >

**Comment by Berlin-N** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/89229935-0860b900-d5a8-11ea-8a9d-48ee7395d401.png)
