### ISSUE TITLE
07Y-Hill City-Quadna Mountain-MINNESOTA-USA

### ISSUE THREAD

**Issue by Gabe-Z** [InfiniteFlightAirportEditing/Airports#5048]
# Airport Name

Hill City-Quadna Mountain

# Country?

USA

# Improvements that need to be made?

Unedited

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/83343053-71336880-a2bb-11ea-9480-d6b27353c7df.png)
