### ISSUE TITLE
EDUS-Sonderlandeplatz Finsterwalde/Schacksdorf-BRANDENBURG-GERMANY

### ISSUE THREAD

**Issue by rich-art-02** [InfiniteFlightAirportEditing/Airports#5049]
# Airport Name

Sonderlandeplatz Finsterwalde/Schacksdorf

# Country?

Germany

# Improvements that need to be made?

redo from scratch

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/84580742-3e9b6c80-ad9f-11ea-9756-fc175d260f86.png)
