### ISSUE TITLE
12S-Monument Municipal Airport-OREGON-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#5050]
# Airport Name

Monument Muncipal Airport

# Country?

Americaaa

# Improvements that need to be made?

Full rework

# Are you working on this airport?

Yeah

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by Czechoslovaki** [comment]
Sent For OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/83338168-2bf54380-a287-11ea-92f2-390f42c9d7bc.png)
