### ISSUE TITLE
URMN-Nalchik Airport-KABARDIN BALKAR-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#5052]
# Airport Name

< Nalchik Airport >

# Country?

< Russia >

# Improvements that need to be made?

< redo >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< LOW >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85903048-09dddb00-b7cb-11ea-9183-c5b8a0c5e332.png)
