### ISSUE TITLE
SPHI-Capitan Fap Jose Abelardo Quinones Gonzalez Airport International-LAMBAYEQUE-PERU

### ISSUE THREAD

**Issue by Gabe-Z** [InfiniteFlightAirportEditing/Airports#5056]
# Airport Name

Capitan Fap Jose Abelardo Quinones Gonzalez Airport International

# Country?

Peru

# Improvements that need to be made?

Needs more spawn, need approach freq. and need rework.

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

GP1

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85902212-1f520580-b7c9-11ea-87d9-01b091e184ad.png)
