### ISSUE TITLE
GMMZ-Ouarzazate Airport-DRAA TAFILALET-MOROCCO

### ISSUE THREAD

**Issue by Gabe-Z** [InfiniteFlightAirportEditing/Airports#5057]
# Airport Name

Ouarzazate Airport

# Country?

Morocco

# Improvements that need to be made?

Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

GP1

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/84580618-20813c80-ad9e-11ea-9e36-41e457cced27.png)
