### ISSUE TITLE
OIBS-Sirri Island Airport-HORMOZGAN-IRAN

### ISSUE THREAD

**Issue by rich-art-02** [InfiniteFlightAirportEditing/Airports#5060]
# Airport Name

Sirri Island Airport

# Country?

Iran

# Improvements that need to be made?

redo from scratch

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

GP1

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85802711-1a2e8100-b70b-11ea-9f2d-e61672e87180.png)
