### ISSUE TITLE
CA92-Paradise Skypark-CALIFORNIA-USA

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#5061]
Airport has been redesignated by FAA
Was originally L24 - Its current name in REPO

**Comment by MajorTomMueller** [comment]
What happened to the beautiful issue opening form ...

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/92995752-c7739280-f4cb-11ea-8495-c34efa72f090.png)
