### ISSUE TITLE
SDIL-Fazenda Pedra Branca Airstrip-RIO DE JANEIRO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5062]
# Airport Name

Fazenda Pedra Branca Airstrip

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/83468857-a10d7800-a443-11ea-9356-757b666aab8e.png)
