### ISSUE TITLE
RPML-Lumbia Airfield-PHILIPPINES

### ISSUE THREAD

**Issue by jaypzs** [InfiniteFlightAirportEditing/Airports#5063]
# Airport Name

< Lumbia Airfield >

# Country?

< Philippines >

# Improvements that need to be made?

< Add apron and gates >

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< low priority >

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/125209625-b7e5e700-e25f-11eb-92fb-3bdb49e615b5.png)
