### ISSUE TITLE
SCPQ-Mocopulli Airport-LOS LAGOS-CHILE 

### ISSUE THREAD

**Issue by victormw22** [InfiniteFlightAirportEditing/Airports#5064]
# Airport Name

< Mocopulli >

# Country?

< Chile >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by victormw22** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85181663-1d79c680-b24c-11ea-8290-a14349808507.png)
