### ISSUE TITLE
SWMU-Fazenda Tres Muchachas Airport-MATO GROSSO DO SUL-BRAZIL

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Airports#5065]
# Airport Name

< Fazenda Tres Muchachas >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone form scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by FellipeEdu** [comment]
Sent to OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/84606027-c3ea5400-ae67-11ea-8fea-ad4378944159.png)
