### ISSUE TITLE
SAEM-Miramar Airport-Buenos Aires-ARGENTINA

### ISSUE THREAD

**Issue by victormw22** [InfiniteFlightAirportEditing/Airports#5066]
# Airport Name

< Miramar >

# Country?

< Argentina >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by victormw22** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85483457-71f1ae80-b58a-11ea-8508-d3338eb9f2e7.png)
