### ISSUE TITLE
RJST-Matsushima Airport-MIYAGI-JAPAN

### ISSUE THREAD

**Issue by zacky89315** [InfiniteFlightAirportEditing/Airports#5067]
# Airport Name

< Matsushima >

# Country?

< Japan >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/87875142-beb38400-c994-11ea-875e-ded0d5df5368.png)
