### ISSUE TITLE
SKAS-Tres De Mayo Airport-PUTUMAYO-COLOMBIA

### ISSUE THREAD

**Issue by jakey200** [InfiniteFlightAirportEditing/Airports#5070]
# Airport Name

Tres De Mayo

# Country?

Columbia

# Improvements that need to be made?

Redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MajorTomMueller** [comment]
@jakey200 
You have 5 open Design issues open after last error check. Please check them out before producing new errors.

**Comment by kztmtn** [comment]
@jakey200  Now you can do this, and I know that you had already sent this for OR...

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/84965976-e5e90e00-b0d5-11ea-8e42-1010269ffd0f.png)
