### ISSUE TITLE
12Y-Le Sueur Municipal-MINNESOTA-USA

### ISSUE THREAD

**Issue by Gabe-Z** [InfiniteFlightAirportEditing/Airports#5071]
# Airport Name

Le Sueur Municipal

# Country?

USA

# Improvements that need to be made?

Unedited

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/84568926-6a3f3800-ad48-11ea-98c0-c795ca576827.png)
