### ISSUE TITLE
EDCF-Sonderlandeplatz Friedersdorf-BRANDENBURG-GERMANY

### ISSUE THREAD

**Issue by rich-art-02** [InfiniteFlightAirportEditing/Airports#5073]
# Airport Name

Sonderlandeplatz Friedersdorf

# Country?

Germany

# Improvements that need to be made?

redo from scratch

# Are you working on this airport?

yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85201671-edbbd480-b2c6-11ea-94db-7d2f7e7edacf.png)
