### ISSUE TITLE
F75-Harrison Fld of Knox City-TEXAS-USA

### ISSUE THREAD

**Issue by 2000rpm** [InfiniteFlightAirportEditing/Airports#5074]
# Airport Name

< Harrison Fld of Knox City >

# Country?

< USA >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/86978611-e6a91900-c144-11ea-8832-78522ea6dfb1.png)
