### ISSUE TITLE
SSEF-Passaredo Airport-SAO PAULO-BRAZIL

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Airports#5075]
# Airport Name

< Fazenda Passaredo >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone form scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MajorTomMueller** [comment]
not assigned due to 3 open issues. 
Rule is enforced despite all 3 in OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/87234266-00d93600-c395-11ea-8410-0aa99dac0e94.png)
