### ISSUE TITLE
3F9-Mineola Wisener Fld-TEXAS-USA

### ISSUE THREAD

**Issue by 2000rpm** [InfiniteFlightAirportEditing/Airports#5076]
# Airport Name

< Mineola Wisener Fld >

# Country?

< USA >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by 2000rpm** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/87355772-8b04d400-c526-11ea-82c6-dab0367ce6e4.png)
