### ISSUE TITLE
RPVD-Sibulan Airport-NEGROS ORIENTAL-PHILIPPINES

### ISSUE THREAD

**Issue by jaypzs** [InfiniteFlightAirportEditing/Airports#5078]
# Airport Name

< Dumaguete AIrport >

# Country?

< Philippines >

# Improvements that need to be made?

< Add Apron and Gates >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by jaypzs** [comment]
RPVD is Dumaguete Airport-NEGROS ORIENTAL, PHILIPPINES..

**Comment by jaypzs** [comment]
Requesting for assignment to this airport. thank you.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90448154-71692600-e0aa-11ea-89b6-1e2d411ee903.png)
