### ISSUE TITLE
KLKV-Lake County Airport-OREGON-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#5079]
# Airport Name

Lake County Airport

# Country?

USA

# Improvements that need to be made?

Clean House 

# Are you working on this airport?

Yea

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/84969389-32384c00-b0de-11ea-9fdf-5cc99682abac.png)
