### ISSUE TITLE
LFRN-Rennes–Saint-Jacques Airport-BRITTANY-FRANCE

### ISSUE THREAD

**Issue by AxelBeder** [InfiniteFlightAirportEditing/Airports#508]
Reworking.

**Comment by AxelBeder** [comment]
Wrong name.

**Comment by AxelBeder** [comment]
Has just been added to repro.

**Comment by kilt46** [comment]
This looks like an original from X-Plane. Please check the vintage. Some lines missing. e.g. white lines on main apron
![image](https://cloud.githubusercontent.com/assets/14023167/16540077/936f25d4-401c-11e6-8bc1-51790aa7d47d.png)

**Comment by moritzbabl** [comment]
Working on this? @AxelBeder

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26285255/a3b40010-3e11-11e7-8cc4-c23ae84b9ded.png)
