### ISSUE TITLE
UNBG-Gorno-Altaysk Airport-ALTAI-RUSSIA

### ISSUE THREAD

**Issue by HauBHa9lDbIPo4Ka** [InfiniteFlightAirportEditing/Airports#5083]
# Airport Name

< Gorno-Altaysk Airport >

# Country?

< Russia >

# Improvements that need to be made?

< Full processing >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by AleksanderIF** [comment]
Hey, @HauBHa9lDbIPo4Ka , you were assigned on June 14. What is your progress?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107147144-12c28d80-6912-11eb-9015-0a1b787d7911.png)
