### ISSUE TITLE
SCVN-Huancara Airport-VICUÑA-CHILE

### ISSUE THREAD

**Issue by vichols1506** [InfiniteFlightAirportEditing/Airports#5085]
# Airport Name

< Huancara>

# Country?

< Chile >

# Improvements that need to be made?

< Scratch>

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low>

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85803556-071cb080-b70d-11ea-9b63-cccd3f1c02a8.png)
