### ISSUE TITLE
EDUG-Sonderlandeplatz Gransee-BRANDENBURG-GERMANY

### ISSUE THREAD

**Issue by rich-art-02** [InfiniteFlightAirportEditing/Airports#5086]
# Airport Name

Sonderlandeplatz Gransee

# Country?

Germany

# Improvements that need to be made?

new

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85797578-86a48280-b701-11ea-87cd-f06cef7f36c0.png)
