### ISSUE TITLE
NFTE-Eua Kaufana Airport-PANGAI-TONGA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#5087]
# Airport Name

Eua Kaufana Airport

# Country?

Tonga

# Improvements that need to be made?

Will be redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

None

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85798868-e1d77480-b703-11ea-80d6-0699a401ef05.png)
