### ISSUE TITLE
SA5Q-Florencio Varela El Pajaro Airport-BUENOS AIRES-ARGENTINA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5088]
# Airport Name

Florencio Varela El Pajaro Airport

# Country?

Argentina

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/84957286-7ddbfd00-b0c0-11ea-9bfa-5f3269eb0caa.png)
