### ISSUE TITLE
VEBD-Bagdogra-Airport-WEST BENGAL-INDIA

### ISSUE THREAD

**Issue by NilInfinite** [InfiniteFlightAirportEditing/Airports#5089]
# Airport Name

Bagdogra Airport

# Country?

India

# Improvements that need to be made?

The airport is missing taxiways and spawn areas

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low to Medium

**Comment by MajorTomMueller** [comment]
Good luck with this one. Not a easy, with wavy unsharp imagery ...

**Comment by NilInfinite** [comment]
Yupppp

**Comment by KaalicharanDH** [comment]
May i get assigned to it please?

**Comment by NilInfinite** [comment]
Sure

**Comment by NilInfinite** [comment]
> May i get assigned to it please?

Yes

**Comment by MajorTomMueller** [comment]
@NilInfinite @KaalicharanDH 
Could the two of you please clarify who will work now on this airport. Please do this via DM function in slack, and let me know the RESULT via DM. I will assign the one the and expect a Edit send to OR within 3 months.

**Comment by MajorTomMueller** [comment]
You have it @KaalicharanDH

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106356564-352b2a00-62c6-11eb-93e1-de76c8bb2a61.png)
