### ISSUE TITLE
EDRK-Koblenz-Winningen Airport-RHINELAND-PALATINATE-GERMANY

### ISSUE THREAD

**Issue by dushyants19** [InfiniteFlightAirportEditing/Airports#509]
Redo needed, Multiple taxiways. Amsterdam Region

Please add the Grass Taxiways too

**Comment by samuelandersson** [comment]
Going for this one.

**Comment by dushyants19** [comment]
Not "non-region"

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20596875/40e037de-b206-11e6-8984-3dfe5ee49eb8.png)

**Comment by kilt46** [comment]
Airport misaligned
![image](https://user-images.githubusercontent.com/14023167/48316892-0cb49980-e5af-11e8-9c5a-4e1ef6a0a083.png)
