### ISSUE TITLE
M53-Humboldt Municipal Airport-Tennessee-USA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#5090]
# Airport Name

< Humboldt Municipal Airport >

# Country?

< USA >

# Improvements that need to be made?

< redo >

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/86465388-1f856000-bcf7-11ea-917b-97ad62bd3edb.png)
