### ISSUE TITLE
ZGSD-Zhuhai Jinwan Airport-GUANGDONG-CHINA

### ISSUE THREAD

**Issue by Berlin-N** [InfiniteFlightAirportEditing/Airports#5091]
# Airport Name

< Zhuhai Jinwan Airport>

# Country?

< China >

# Improvements that need to be made?

< New >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< 10000ft+ Runway >

**Comment by MajorTomMueller** [comment]
Duplicate, the lack of the try to search disturbed me ...
Try again

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/86860284-2959eb00-c08a-11ea-8f80-7a6c687b402c.png)
