### ISSUE TITLE
EDKB

### ISSUE THREAD

**Issue by NilsEsser** [InfiniteFlightAirportEditing/Airports#5092]
# Airport Name

Flugplatz Bonn-Hangelar

# Country?

Germany

# Improvements that need to be made?

Will be redone

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MajorTomMueller** [comment]
This is the 3rd duplicat today!
Guys, read the guide! Search the database before making a new issue.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/86859259-e139c900-c087-11ea-93a8-b54fa769a5cb.png)
