### ISSUE TITLE
Duplicate 

### ISSUE THREAD

**Issue by alpster1** [InfiniteFlightAirportEditing/Airports#5093]
# Airport Name

< Ercan International Airport >

# Country?

< Cyprus/Northern Cyprus >

# Improvements that need to be made?

< will be done from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MajorTomMueller** [comment]
A issue for this exists and is assigned to a editor.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/86851196-2655ff00-c078-11ea-8590-56ce9ab70e40.png)
