### ISSUE TITLE
NFTF-Fua Amotu International Airport-TONGATAPU-TONGA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#5094]
# Airport Name

Fua Amotu International Airport

# Country?

Tonga

# Improvements that need to be made?

Small taxiway addition, and minor airport boundary adjustments

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low Priority)

World Capital (Tongo)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/88729467-98f74f00-d0f9-11ea-8285-0c604096eb2d.png)
