### ISSUE TITLE
EDLT-Munster Telgte Airport-NORDRHEIN WESTFALEN-GERMANY

### ISSUE THREAD

**Issue by NilsEsser** [InfiniteFlightAirportEditing/Airports#5095]
# Airport Name

Verkehrslandeplatz Münster-Telgte

# Country?

Germany

# Improvements that need to be made?

New airport

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MajorTomMueller** [comment]
![EDLT-git](https://user-images.githubusercontent.com/26853210/132045137-d53c3ba6-5ec9-45e6-a250-87e770854f3f.png)
