### ISSUE TITLE
GQNI-Nema Airport-HODH ECH CHARGUI-MAURITANIA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5097]
# Airport Name

Nema Airport

# Country?

Mauritania

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/84844903-13b84f00-b011-11ea-99fc-c83ecfdd0519.png)
