### ISSUE TITLE
2PN7-Brennan Personal Use Airport-PENNSYLVANIA-USA

### ISSUE THREAD

**Issue by jakey200** [InfiniteFlightAirportEditing/Airports#5098]
# Airport Name

Brennan Personal Use airport

# Country?

USA

# Improvements that need to be made?

Redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/86422599-284c4680-bca3-11ea-9191-abc2fc793a2e.png)
