### ISSUE TITLE
GQPP-Nouadhibou Airport-DAKHLET NOUADHIBOU-MAURITANIA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5099]
# Airport Name

Nouadhibou Airport

# Country?

Mauritania

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/84844660-72c99400-b010-11ea-9623-655c2bff23c4.png)
