### ISSUE TITLE
KOSH-Wittman Regional Airport-WISCONSIN-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#51]

**Comment by kilt46** [comment]
Airport rewritten. Be careful of Terminal spawn point. Causes issue with ATC. Close proximity to runway

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20868768/fc9cfabe-ba28-11e6-90ab-28e87cd724d2.png)

**Comment by netjets-1951** [comment]
Please un-assign me. I will continue working on this airport at a later time.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29385905-1fceb2d6-829f-11e7-83b5-5fe45bbb5b19.png)

**Comment by RyanEpps** [comment]
<img width="593" alt="KOSH" src="https://user-images.githubusercontent.com/20650961/60048271-c9202300-9699-11e9-82ce-e810bbc3b946.png">

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78413008-ef40ff00-75eb-11ea-98c1-871b0975e02d.jpg)
