### ISSUE TITLE
VABO-Vadodara Airport-GUJARAT-INDIA

### ISSUE THREAD

**Issue by KaalicharanDH** [InfiniteFlightAirportEditing/Airports#5100]
# Airport Name

VABO

# Country?

India

# Improvements that need to be made?

Gates,taxiways and other improvements needed

# Are you working on this airport?

Yes, i will work on it

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

No

**Comment by MajorTomMueller** [comment]
VABO ≠ Airportname
VABO is the four letter ICAO code for the airport it was not questioned under “Aiportname” in the issue form. 
And please redo it from scratch, adjustments are not enough in this case.

**Comment by KaalicharanDH** [comment]
Sorry
I'll keep this in mind next time

**Comment by MBeringuy** [comment]
Available for editing.

**Comment by AstreaI** [comment]
I will do.

**Comment by AstreaI** [comment]
Airport Name
Vadodara Airport

Country
India

Improvements that need to be made?
Gates, taxiways and other improvements needed.

Are you working on this airport?
Yes

Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
No

**Comment by MajorTomMueller** [comment]
here you go @AstreaI

**Comment by AstreaI** [comment]
Thanks :)

**Comment by MajorTomMueller** [comment]
Up for grabs, user is busy with learning (wich is always in life a good choice)

**Comment by KaalicharanDH** [comment]
I'll do it

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102559960-bae87280-4096-11eb-9e15-61c453e8db6e.png)
