### ISSUE TITLE
EDFQ-Allendorf-Eder-HESSEN-GERMANY

### ISSUE THREAD

**Issue by NilsEsser** [InfiniteFlightAirportEditing/Airports#5101]
# Airport Name

Allendorf-Eder Airport

# Country?

Germany 

# Improvements that need to be made?

New airport

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MajorTomMueller** [comment]
![EDFQ-git](https://user-images.githubusercontent.com/26853210/132123957-1e56b8e7-d9dc-4b19-af59-607fc93afac7.png)
