### ISSUE TITLE
VEPT-Lok Nayak Jaya Prakash Narayan Airport-BIHAR-INDIA

### ISSUE THREAD

**Issue by KaalicharanDH** [InfiniteFlightAirportEditing/Airports#5102]
# Airport Name

Lok Nayak Jaya Prakash Narayan Airport

# Country?

India

# Improvements that need to be made?

Gates and taxiways need to be added

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/89588664-b8812c80-d809-11ea-9d30-8c9e1309cfa2.png)
