### ISSUE TITLE
SCQL-El Boco Airport-QUILLOTA-CHILE

### ISSUE THREAD

**Issue by vichols1506** [InfiniteFlightAirportEditing/Airports#5103]
# Airport Name

< SCQL >

# Country?

< CHILE >

# Improvements that need to be made?

< Scratch>

# Are you working on this airport?

< Yes>

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low>

**Comment by MBeringuy** [comment]
You have already reached the maximum limit of 3 issues assigned to you. Wait until one of these 3 airports is approved in the OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85181251-0a1a2b80-b24b-11ea-8d4e-ac34213cd8e7.png)
