### ISSUE TITLE
SCTL-Panguilemo Airport-MAULE-CHILE

### ISSUE THREAD

**Issue by vichols1506** [InfiniteFlightAirportEditing/Airports#5104]
# Airport Name

< Panguilemo >

# Country?

< Chile >

# Improvements that need to be made?

< Scratch>

# Are you working on this airport?

<Yes>

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

<Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85176373-4c3d7000-b23f-11ea-9b4c-eaca9cb50099.png)
