### ISSUE TITLE
GMMA-Es Smara Airport-GUELMIM-ES SEMARA-WESTERN SAHARA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5105]
# Airport Name

Es-Smara Airport

# Country?

Western Sahara

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/84957804-9dbff080-b0c1-11ea-84c3-0d26a4681a75.png)
