### ISSUE TITLE
OYAA-Aden International Airport-ADEN-YEMEN

### ISSUE THREAD

**Issue by jakey200** [InfiniteFlightAirportEditing/Airports#5106]
# Airport Name

Aden International

# Country?

Yemen

# Improvements that need to be made?

Redo

# Are you working on this airport?

Yes, my project for tonight.

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

GP1

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85946419-be7e1680-b909-11ea-8a1e-0e73d243cb41.png)
