### ISSUE TITLE
DUPLICATE

### ISSUE THREAD

**Issue by Jacklcsm** [InfiniteFlightAirportEditing/Airports#5108]
# Airport Name

Simko Field

# Country?

United States

# Improvements that need to be made?

Being added to IF

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
Continues at #5236.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90318050-35d82b80-def3-11ea-8c2c-6aedaddc0680.png)
