### ISSUE TITLE
KSEE-Gillespie Field-CALIFORNIA-USA

### ISSUE THREAD

**Issue by dushyants19** [InfiniteFlightAirportEditing/Airports#511]
So-Cal. Redo might be needed. Misalingment not uniform.

**Comment by Hamza1108** [comment]
Hey can I take this one

**Comment by dushyants19** [comment]
Cool, Please send an email if you havent already to `airports@liveflightapp.com` :)

**Comment by Hamza1108** [comment]
I have a while ago, I dunno if it has been read yet.

**Comment by dushyants19** [comment]
@Hamza1108 how is this going?

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23825348/8e6445a4-064d-11e7-911a-70c807994c1a.png)
Redone from scratch

**Comment by RyanEpps** [comment]
Airport needs reworked up to new standards and additional spawns.

**Comment by liamkirky** [comment]
Can I take this airport please?

**Comment by jakey200** [comment]
Can I take this?

**Comment by jakey200** [comment]
Sent to o f f i c i a l r e v i e w

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78693728-09bbf680-78d2-11ea-8dd8-7fbf13bd6426.jpg)

**Comment by MajorTomMueller** [comment]
Duplicate spawn names:
https://gist.github.com/carmichaelalonso/652d032d7fe3683cbf8d88365ff5a690

**Comment by jakey200** [comment]
fixed
