### ISSUE TITLE
ZHXF-XIANGYANG LIUJI-HUBEI-CHINA

### ISSUE THREAD

**Issue by FlightGeekYuta** [InfiniteFlightAirportEditing/Airports#5111]
# Airport Name

ZHXF

# Country?

China

# Improvements that need to be made?

Full rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85945624-b4a5e480-b904-11ea-9d89-802b82441a23.png)
