### ISSUE TITLE
NFTL-Lifuka Island-Lifuka-Tonga

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#5112]
# Airport Name

Lifuka Island

# Country?

Tonga

# Improvements that need to be made?

Will be redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/87875253-a5f79e00-c995-11ea-9709-05279e3925f7.png)
