### ISSUE TITLE
UBBQ-Gabala International Airport-AZERBAIJAN

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#5113]
# Airport Name

< Gabala Airport >

# Country?

< Azerbaijan >

# Improvements that need to be made?

< missing airport >

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< GP2 (rwy 16/34) >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/86408412-94678400-bc7c-11ea-8f4b-65a5ee26da2a.png)
