### ISSUE TITLE
EDOJ-Sonderlandeplatz Lüsse-BRANDENBURG-GERMANY

### ISSUE THREAD

**Issue by rich-art-02** [InfiniteFlightAirportEditing/Airports#5114]
# Airport Name

Sonderlandeplatz Lüsse

# Country?

Germany

# Improvements that need to be made?

redo from scratch/new

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/87234106-6298a080-c393-11ea-89f1-5a52d07fe69c.png)
