### ISSUE TITLE
KABY-Southwest Georgia Regional Airport-GEORGIA-USA

### ISSUE THREAD

**Issue by victormw22** [InfiniteFlightAirportEditing/Airports#5115]
# Airport Name

< Southwest Georgia Regional >

# Country?

< USA >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by victormw22** [comment]
sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/88481669-60e9e380-cf22-11ea-981d-257e4383f954.png)
