### ISSUE TITLE
04NV-Kingston Ranch Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#5116]
# Airport Name

Kingston Ranch Airport

# Country?

USA

# Improvements that need to be made?

Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/87889143-c1929100-c9f5-11ea-82a2-b995a6c90bdc.png)
