### ISSUE TITLE
SCCY-Teniente Vidal Airport-COYHAIQUE-CHILE

### ISSUE THREAD

**Issue by vichols1506** [InfiniteFlightAirportEditing/Airports#5117]
# Airport Name

< Teniente Vidal >

# Country?

< chile >

# Improvements that need to be made?

< Scratch >

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85930583-4bca5800-b883-11ea-9157-fd98e66fdede.png)
