### ISSUE TITLE
EDGM-Mosbach-Lohrbach-BADEN-WUERTTEMBERG-GERMANY

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#5118]
# Airport Name

Mosbach-Lohrbach

# Country?

Germany

# Improvements that need to be made?

Redo from Scratch

# Are you working on this airport?

yup

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85201575-2f984b00-b2c6-11ea-8e3c-ddc509522888.png)
