### ISSUE TITLE
EDPT-Gerstetten-BADEN-WUERTTEMBERG-GERMANY

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#5119]
# Airport Name

Gerstetten

# Country?

Germany

# Improvements that need to be made?

New Airport to IF

# Are you working on this airport?

Affirmative

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85201441-f0b5c580-b2c4-11ea-986d-8642ebebab8e.png)
