### ISSUE TITLE
EDMC-Blaubeuren-BADEN-WUERTTEMBERG-GERMANY

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#5120]
# Airport Name

Blaubeuren

# Country?

Germany

# Improvements that need to be made?

New Airport to IF

# Are you working on this airport?

Yeah

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85201295-e9da8300-b2c3-11ea-9df3-436009d378c8.png)
