### ISSUE TITLE
EDGU-Unterschuepf-BADEN-WUERTTEMBERG-GERMANY

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#5121]
# Airport Name

Unterschüpf

# Country?

Germany

# Improvements that need to be made?

None when I'm done with it in 5 minutes

# Are you working on this airport?

obviously

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85201182-ed213f00-b2c2-11ea-9e34-b5682dec09db.png)
