### ISSUE TITLE
FEFF-Bangui M'Poko International Airport-CENTRAL AFRICAN REPUBLIC

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#5122]
# Improvements that need to be made?

Rework from Scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

World Capital GP3

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85482706-1115a680-b589-11ea-9903-70bb25786ba2.png)
