### ISSUE TITLE
HHAS-Asmara-CENTRAL REGION-ERITREA

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#5123]
# Improvements that need to be made?

First Rework from Scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

World Capital GP3

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85349381-f9281f00-b4c3-11ea-822d-517beb74ac0e.png)
