### ISSUE TITLE
EDTH-Heubach-BADEN-WUERTTEMBERG-GERMANY

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#5124]
# Improvements that need to be made?

Redo from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85347215-96338980-b4bd-11ea-9b5a-301bd67f10fc.png)
