### ISSUE TITLE
4X4-Wessington Springs-SOUTH DAKOTA-USA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#5126]
# Airport Name

< Wessington Springs >

# Country?

< USA >

# Improvements that need to be made?

< redo >

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/86407917-90873200-bc7b-11ea-83f3-301f4d3d5bd1.png)
