### ISSUE TITLE
VVCB-Quan Cang Cam Ranh Air Base-KHANH HOA-VIETNAM

### ISSUE THREAD

**Issue by IFUA2003** [InfiniteFlightAirportEditing/Airports#5128]
# Airport Name

< Quan Cang Cam Ranh Air Base >

# Country?

< Vietnam >

# Improvements that need to be made?

< This airport has not been added >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by IFUA2003** [comment]
![384ED872-CF52-457B-95B9-6A2E54C8BD91](https://user-images.githubusercontent.com/43931356/85367773-186e8d00-b554-11ea-9cf9-bdcb760a827e.jpeg)

**Comment by Yosh145** [comment]
Can I take this one?

**Comment by Czechoslovaki** [comment]
@Yosh145 still want this one?

**Comment by IFUA2003** [comment]
I'll take this after I finished one of my requested my airports (about 1 more week)

**Comment by IFUA2003** [comment]
Can I take this? I have finished my lastest requested airport

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102725469-94b41400-42dc-11eb-8751-06eba9b804af.png)
