### ISSUE TITLE
SJKE-Presidente Jose Sarney Airport-MARANHAO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5129]
# Airport Name

Presidente Jose Sarney Airport

# Country?

Brazil

# Improvements that need to be made?

Done from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85482545-c431d000-b588-11ea-90e4-b0fd187acbce.png)

**Comment by kilt46** [comment]
![Uploading image.png…]()
