### ISSUE TITLE
LDSP

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Airports#513]
Working on this one. Needs a total redo.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17232359/2996e5c6-54ed-11e6-8d43-18bbde290dfe.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17245634/f942cb46-554c-11e6-9ffd-565d8d01b9b3.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18418056/d13e423a-7804-11e6-8658-3af030e45430.png)
