### ISSUE TITLE
ZSWZ-Wenzhou Longwan International Airport-ZHEJIANG-CHINA

### ISSUE THREAD

**Issue by AnthonyCK** [InfiniteFlightAirportEditing/Airports#5131]
# Airport Name

< Wenzhou Longwan International Airport >

# Country?

< China >

# Improvements that need to be made?

< Full rework >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< 10000+ >

**Comment by AnthonyCK** [comment]
Sent for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/87233982-4cd6ab80-c392-11ea-90f0-aefd332bf176.png)
