### ISSUE TITLE
ZBNY-Beijing Nanyuan Airport-BEIJING-CHINA

### ISSUE THREAD

**Issue by Berlin-N** [InfiniteFlightAirportEditing/Airports#5132]
# Airport Name

< Beijing Nanyuan Airport >

# Country?

< China >

# Improvements that need to be made?

< New >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by Berlin-N** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/86539281-cc5f0900-bec0-11ea-9620-9b0aa9a5ec17.png)
