### ISSUE TITLE
SAMQ-Aeroparque Mendoza Airport-MENDOZA-ARGENTINA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5133]
# Airport Name

Aeroparque Mendoza Airport

# Country?

Argentina

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85796009-d2096180-b6fe-11ea-9e78-7ebd0b550e07.png)
