### ISSUE TITLE
SA16-La Puntilla Airport-MENDOZA-ARGENTINA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5134]
# Airport Name

La Puntilla Airport

# Country?

Argentina

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85794908-febc7980-b6fc-11ea-9bb1-2bebd0ba403b.png)
