### ISSUE TITLE
Duplicate 

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#5135]
# Airport Name

Bahrain International Airport

# Country?

Bahrain

# Improvements that need to be made?

Will be redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

10000+ and World Capital

**Comment by OscarConklin** [comment]
This can be deleted it is a duplicate.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/86540375-595a9000-beca-11ea-94db-c27a5763f576.png)
