### ISSUE TITLE
SCLL-Vallenar Airport-Vallenar-Chile

### ISSUE THREAD

**Issue by vichols1506** [InfiniteFlightAirportEditing/Airports#5138]
# Airport Name

< Vallenar>

# Country?

< Chile >

# Improvements that need to be made?

< Scratch>

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low>

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/86643230-2388da80-bfa2-11ea-968b-5f408d001296.png)
