### ISSUE TITLE
T00-Chambers Co-TEXAS-USA

### ISSUE THREAD

**Issue by 2000rpm** [InfiniteFlightAirportEditing/Airports#5139]
# Airport Name

< Chambers Co >

# Country?

< USA >

# Improvements that need to be made?

< To be redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/88467449-f2af0d80-ce9c-11ea-8137-84bdfbd9688c.png)
