### ISSUE TITLE
ESGT

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Airports#514]
Trollhättan Vänersborg.

Working on this. Needs some small fixes.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17232723/bb942af4-54ef-11e6-9c3b-416bb32cfeae.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17262998/33251f4c-55a4-11e6-845f-9f8515897e17.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18231424/280722e8-727f-11e6-8b96-a1d4fe3304bf.png)
