### ISSUE TITLE
WICN - Cijulang Nusawiru Airport - CIJULANG - INDONESIA

### ISSUE THREAD

**Issue by IFUA2003** [InfiniteFlightAirportEditing/Airports#5140]
# Airport Name

< Cijulang Nusawiru Airport >

# Country?

< Indonesisa >

# Improvements that need to be made?

< Redo from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MajorTomMueller** [comment]
Dear @IFUA2003 , you might not have notice, but I haven’t assigned you previously to the issue you opened. Can you guess why? Hint: it hadn’t changed yet.

**Comment by IFUA2003** [comment]
I don’t really know

**Comment by MajorTomMueller** [comment]
We have a limit of 3 open issues. You are assigned to 3 already. So I can’t assign enough to any additional ones. Please stop open issues before you have a slot free.

**Comment by MajorTomMueller** [comment]
To help you remember:
![B0D88F38-A52D-4B1F-A8C0-22C04FD374AA](https://user-images.githubusercontent.com/26853210/85927403-1a16b880-b8a6-11ea-832d-9aa300270fdb.jpeg)

**Comment by IFUA2003** [comment]
2 of them has already sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103325065-a9488880-4a0f-11eb-8138-555664634010.png)
