### ISSUE TITLE
Duplicate

### ISSUE THREAD

**Issue by joshhicks1** [InfiniteFlightAirportEditing/Airports#5142]
# Airport Name

Brisbane Airport

# Country?

Australia

# Improvements that need to be made?

New runway

# Are you working on this airport?

Affirm

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

10000+ runway

**Comment by MajorTomMueller** [comment]
#588

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/86537472-e98dda80-beb4-11ea-9736-0bec32b949cd.png)
