### ISSUE TITLE
SCDI-Pichidangui Airport-Pichidangui-CHILE

### ISSUE THREAD

**Issue by vichols1506** [InfiniteFlightAirportEditing/Airports#5145]
# Airport Name

< Pichidangui>

# Country?

< Chile >

# Improvements that need to be made?

< Scratch >

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/86982146-2c1e1400-c14e-11ea-8308-f1ca854440d4.png)
