### ISSUE TITLE
KACT-Waco Regional Airport-TEXAS-USA

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#5146]
# Airport Name

Waco Regional Airport

# Country?

USA

# Improvements that need to be made?

Redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by jakey200** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/88435283-7dbdd400-cdc7-11ea-9a87-4e55b5d29aaf.png)
