### ISSUE TITLE
KMEM-Memphis International Airport-TENNESSEE-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#5148]
# Airport Name

Memphis International Airport

# Country?

USA

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

10k

**Comment by moritzbabl** [comment]
#1588

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/86537021-c57cca00-beb1-11ea-9962-f297add31386.png)
