### ISSUE TITLE
KILM-Wilmington International Airport-NORTH CAROLINA-USA

### ISSUE THREAD

**Issue by FlightGeekYuta** [InfiniteFlightAirportEditing/Airports#5149]
# Airport Name

Wilmington international airport

# Country?

USA

# Improvements that need to be made?

Taxiways and gates are inaccurate

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MajorTomMueller** [comment]
@FlightGeekYuta you couldn’t been assigned course I couldn’t find you in the contributor list. May be you haven’t accepted the github invite you should have got after sending your application email. Please post also in slack channel #github-names Your github username, so that we know who you are in slack.

**Comment by FlightGeekYuta** [comment]
@MajorTomMueller Ive havent been able to join slack because the slack channel has not added me in yet for some reason. Ive gotten the workspace URL but ive havent been registed into slack. Could you please add me back in in slack. Appreciate it!

**Comment by MajorTomMueller** [comment]
please contact Administrators, I am only supervisor. Use the email for airport editing

**Comment by FlightGeekYuta** [comment]
Ive gotten onto slack

**Comment by FlightGeekYuta** [comment]
Im not working on airports anymore. I’m very sorry to report this very late.

I’ll just leave the work I did here if you want to work off from an almost completed airport
https://drive.google.com/file/d/1cu5pUGq40X2aPfOpTS6XehsfVLOh7F8d/view?usp=drivesdk

**Comment by ECoops-123** [comment]
Will take. Started editing from scratch.

![V1](https://user-images.githubusercontent.com/59462519/102307857-43fb8e80-3f5d-11eb-9f91-ebd61e750f43.png)
_Nothing shown is complete_

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102950619-99212e00-4490-11eb-9134-cb5de81f6b22.png)
