### ISSUE TITLE
RJBB-Kansai International Airport-OSAKA-JAPAN

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#515]
Kansai Int'l - World's largest man-made island airport. I'll be doing this

**Comment by IFAEpat** [comment]
Can someone assign this to me please? Thanks

**Comment by IFAEpat** [comment]
Missing a couple of lines

**Comment by IFAEpat** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17244412/4ee6384a-5547-11e6-9ac7-a9636087cde0.png)

**Comment by IFAEpat** [comment]
Gating

**Comment by IFAEpat** [comment]
Gated

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17461389/6cbaa422-5c50-11e6-831f-f84034508c19.png)
MAIN TERMINAL
![image](https://cloud.githubusercontent.com/assets/14023167/17461402/dcdca502-5c50-11e6-9311-1eccb0b97c1e.png)
CARGO
![image](https://cloud.githubusercontent.com/assets/14023167/17461406/ec6d0e62-5c50-11e6-8bd4-9367cdc5293d.png)
MAINTENANCE
![image](https://cloud.githubusercontent.com/assets/14023167/17461409/fbaa0542-5c50-11e6-9297-d466b20c6b89.png)
NORTH
![image](https://cloud.githubusercontent.com/assets/14023167/17461411/080c8a44-5c51-11e6-8c3f-39f765b4d677.png)

**Comment by ryu12332** [comment]
Ben is being a picky little child. He's going to fix some "design issues"

**Comment by moritzbabl** [comment]
Since I just came across it, how's the status of this "issue fixing"? Been over a year already

**Comment by benlenahan** [comment]
Good

**Comment by kztmtn** [comment]
I take this, full redo with adding missing new apron.

**Comment by kztmtn** [comment]
Sent in for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/69682398-07c66900-1090-11ea-8821-784de35095ce.jpg)
