### ISSUE TITLE
EDON-Sonderlandeplatz Neuhardenberg-BRANDENBURG-GERMANY

### ISSUE THREAD

**Issue by rich-art-02** [InfiniteFlightAirportEditing/Airports#5151]
# Airport Name

Sonderlandeplatz Neuhardenberg

# Country?

Germany

# Improvements that need to be made?

redo from scratch

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90312288-d7965300-dec8-11ea-9bfe-b545311eaef4.png)
