### ISSUE TITLE
Duplicate 

### ISSUE THREAD

**Issue by Piggywu981** [InfiniteFlightAirportEditing/Airports#5152]
# Airport Name

Narita International Airport

# Country?

Japan

# Improvements that need to be made?

Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

World Capital

**Comment by MajorTomMueller** [comment]
Already edited #547

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/86492151-ccc99980-bd32-11ea-8dcc-b75d997d924e.png)
