### ISSUE TITLE
Duplicate 

### ISSUE THREAD

**Issue by andreagrr** [InfiniteFlightAirportEditing/Airports#5153]
# Airport Name

Trapani-Birgi "Vincenzo Florio"

# Country?

Italy

# Improvements that need to be made?

Add some spawns

# Are you working on this airport?

Not yet

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MajorTomMueller** [comment]
#2258

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/86491058-28922380-bd2f-11ea-9c5b-64f32afd2a3f.png)

**Comment by andreagrr** [comment]
@kilt46 I have to  improve 00IL?
