### ISSUE TITLE
LLER-Ramon Intl-MECHOZ HADAROM-ISRAEL

### ISSUE THREAD

**Issue by rich-art-02** [InfiniteFlightAirportEditing/Airports#5154]
# Airport Name

Ramon Intl

# Country?

Israel

# Improvements that need to be made?

new

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

10k+

**Comment by MajorTomMueller** [comment]
You are aware that this is not a Sonderlandeplatz? It even isn’t in Germany and it is a bit larger.
😂
Never mind, have fun.

**Comment by rich-art-02** [comment]
please deassign me, sat imagery is only available on apple maps, not google maps, no chance in getting it to work in SAS/ WED now, has to be done at a later point :/

**Comment by MajorTomMueller** [comment]
If it is in Apple it is in Bing, ArcGIS, Yandex, or Here. But your wish.

**Comment by rich-art-02** [comment]
Thanks! didn't know that, now I am able to work on the airport, so just assign me back, sorry for the confusion @MajorTomMueller

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/89709982-fdf64480-d944-11ea-8cd9-be964b408cbe.png)
