### ISSUE TITLE
6V5-Bison-SOUTH DAKOTA-USA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#5155]
# Airport Name

< Bison Municipal Airport >

# Country?

< USA >

# Improvements that need to be made?

< redo >

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< LOW >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/87354626-78899b00-c524-11ea-94a3-98dcdcb81236.png)
