### ISSUE TITLE
KCIR-Cairo Regional-ILLINOIS-USA

### ISSUE THREAD

**Issue by GreenF1r3** [InfiniteFlightAirportEditing/Airports#5156]
# Airport Name

KCIR

# Country?

United States 

# Improvements that need to be made?

Redoing from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by GreenF1r3** [comment]
<img width="548" alt="Screenshot 2020-07-08 at 6 22 54 PM" src="https://user-images.githubusercontent.com/67715546/86986319-40f7a900-c148-11ea-96b4-fc27a93d0055.png">
Peer review if you can. Thanks

**Comment by ShaneAviation** [comment]
I can redo this one.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115962077-2af08480-a4df-11eb-93d0-116e906f928a.png)
