### ISSUE TITLE
LFAK-Dunkerque Les Moëre-HAUTS DE FRANCE-FRANCE

### ISSUE THREAD

**Issue by Marc-Stinger** [InfiniteFlightAirportEditing/Airports#5157]
♻️

**Comment by MajorTomMueller** [comment]
Sweet

**Comment by Marc-Stinger** [comment]
wow, okay, I keep that in mind for the future

**Comment by brunocr1050** [comment]
Airport redone here #6102

**Comment by MajorTomMueller** [comment]
![EYRO](https://user-images.githubusercontent.com/26853210/103652369-f02c0600-4f5a-11eb-8b22-b3e7c82237db.png)

**Comment by MajorTomMueller** [comment]
https://github.com/InfiniteFlightAirportEditing/Airports/commit/a2fc5807f72281a2b4df6fd6037bbcb471138eef
