### ISSUE TITLE
VOTP-Tirupati Airport-ANDHRA PRADESH-INDIA

### ISSUE THREAD

**Issue by hari-shreyas** [InfiniteFlightAirportEditing/Airports#5159]
# Airport Name

Tirupati Airport (VOTP/TIR)

# Country?

India

# Improvements that need to be made?

Ramps and taxiways need to be added

# Are you working on this airport?

Yes. Will start working on it shortly
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by kilt46** [comment]
![Uploading image.png…]()
