### ISSUE TITLE
CYKM-Kincardine Airpor-ONTARIO-CANADA

### ISSUE THREAD

**Issue by mike116119** [InfiniteFlightAirportEditing/Airports#5161]
# Airport Name

<Kincardine Airport >

# Country?

< Canada >

# Improvements that need to be made?

< Full Rework>

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by mike116119** [comment]
NOTE: Was labeled as NS7 in apt File

**Comment by mike116119** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/89707568-e9aa4b80-d934-11ea-963e-cd0db6b9b2d8.png)
