### ISSUE TITLE
KSAD-Safford Regional-ARIZONA-USA

### ISSUE THREAD

**Issue by GreenF1r3** [InfiniteFlightAirportEditing/Airports#5162]
# Airport Name

Safford Regional

# Country?

USA

# Improvements that need to be made?

Rework from scratch

# Are you working on this airport?
Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by GreenF1r3** [comment]
<img width="716" alt="Screenshot 2020-07-15 at 8 56 45 PM" src="https://user-images.githubusercontent.com/67715546/87753595-c407a780-c7b7-11ea-9c2e-9a75fba06085.png">
Airport finished. Peer review if you are available. Thanks.

**Comment by MajorTomMueller** [comment]
The peer review is in slack channel #peer-review

**Comment by StickThelanding** [comment]
Can work on this airport?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/120072686-b15a3200-c05a-11eb-8985-63c060903b16.png)
