### ISSUE TITLE
OEBA-King Saud Bin Abdulaziz Airport-AL BAHAH PROVINCE-SAUDI ARABIA 

### ISSUE THREAD

**Issue by victormw22** [InfiniteFlightAirportEditing/Airports#5163]
# Airport Name

< King Saud Bin Abdulaziz  >

# Country?

< SAUDI ARABIA >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by victormw22** [comment]
sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/88342214-9f09bc00-cd04-11ea-9f85-13d385002e88.png)
