### ISSUE TITLE
LFPL-Lognes-Emerainville-SEINE-ET-MARNE-FRANCE

### ISSUE THREAD

**Issue by Marc-Stinger** [InfiniteFlightAirportEditing/Airports#5164]
# Airport Name

< Aérodrome de Lognes - Emerainville >

# Country?

< France >

# Improvements that need to be made?

< Rework >

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by Jeremy351** [comment]
Hi, Marc is a friend, he doesn't have time anymore to do airports for IFAET.
Can I take his position ?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106954952-21cef300-66fa-11eb-96e6-d5b22d402a08.png)
