### ISSUE TITLE
Duplicate 

### ISSUE THREAD

**Issue by TheFlyingGuy1** [InfiniteFlightAirportEditing/Airports#5169]
# Airport Name

< Rock Creek >

# Country?

< United States of America >

# Improvements that need to be made?

< Add ramp starts, and fix runway size >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MajorTomMueller** [comment]
already edited #3979

**Comment by TheFlyingGuy1** [comment]
I saw the old one. It was closed and old. The runway was about 200m off and needed more parking

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/86679007-c2bdca00-bfc2-11ea-8aab-829b8804d4a4.png)
