### ISSUE TITLE
WSAC-Changi Air Base (East)-SINGAPORE

### ISSUE THREAD

**Issue by cboisselier** [InfiniteFlightAirportEditing/Airports#517]
Airport needs redrawn. Also runway needs renamed

**Comment by kilt46** [comment]
Airport needs redesign . Please also check runway numbering

**Comment by kilt46** [comment]
https://community.infinite-flight.com/t/wsac-01-19-instead-of-02r-20l/25613

**Comment by kilt46** [comment]
Airport redrawn

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17270188/cf2d7fbe-5622-11e6-85f8-7482adb39fbb.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17954579/7443c01c-6a41-11e6-809f-11bb1fd561c4.png)

**Comment by MajorTomMueller** [comment]
Was never decomissioned, and is back to operations for a while now ...

**Comment by MajorTomMueller** [comment]
will get interlinked by taxiway in near future to WSSS #87

**Comment by MajorTomMueller** [comment]
![WSAC-git](https://user-images.githubusercontent.com/26853210/85941625-79f77880-b913-11ea-9226-71e54041f301.png)
