### ISSUE TITLE
SCQT-Las Tacas Airport-Quebrada Las Tacas-CHILE 

### ISSUE THREAD

**Issue by vichols1506** [InfiniteFlightAirportEditing/Airports#5170]
# Airport Name

< Las Tacas >

# Country?

< Chile >

# Improvements that need to be made?

< Scratch >

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MajorTomMueller** [comment]
![SCQT](https://user-images.githubusercontent.com/26853210/133922400-98acfb74-b1c4-40a2-b0be-b68bcc2110ef.png)
