### ISSUE TITLE
KHII-Lake Havasu City-Arizona-USA

### ISSUE THREAD

**Issue by TheFlyingGuy1** [InfiniteFlightAirportEditing/Airports#5171]
# Airport Name

< Lake Havasu City >

# Country?

< United States >

# Improvements that need to be made?

< Complete Redo >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by TheFlyingGuy1** [comment]
Finished the airport. Submitted to peer review

**Comment by brennanhackard** [comment]
@jakey20 will be editing this airport. The previous editor is not in our discord.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107861507-d60ffe00-6e0b-11eb-9a1f-8601534966d9.png)
