### ISSUE TITLE
VASD-Shirdi Airport-Maharashtra-INDIA

### ISSUE THREAD

**Issue by hari-shreyas** [InfiniteFlightAirportEditing/Airports#5172]
# Airport Name

Shirdi Airport (VASD/SAG)

# Country?

India

# Improvements that need to be made?

Ramps and taxiways need to be added

# Are you working on this airport?

Yes. I will commence work on this airport soon.

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MajorTomMueller** [comment]
Welcome to the Team.
Please try to follow the format for the issue Titel. It is always ICAO first.

**Comment by hari-shreyas** [comment]
> Welcome to the Team.
> Please try to follow the format for the issue Titel. It is always ICAO first.

Roger that! Thanks for letting me know. Will keep that in mind.

**Comment by hari-shreyas** [comment]
The airport has been sent for OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/97643800-a5e84f00-1a16-11eb-9661-f7dbb36145ee.png)
