### ISSUE TITLE
KSYR-Syracuse Hancock International Airport- NEW YORK- USA

### ISSUE THREAD

**Issue by Yosh145** [InfiniteFlightAirportEditing/Airports#5173]
# Airport Name

<KSYR-Syracuse Hancock International Airport- NEW YORK- USA>

# Country?

< United States of America>

# Improvements that need to be made?

< Complete Redo >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MajorTomMueller** [comment]
You are not supposed to close any issue. Leave that to administrators or supervisors.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/87227157-9efdd980-c35e-11ea-94f9-a0e5680a7a98.png)
