### ISSUE TITLE
Duplicate

### ISSUE THREAD

**Issue by Yosh145** [InfiniteFlightAirportEditing/Airports#5174]
# Airport Name

<KSYR-Syracuse Hancock International Airport>

# Country?

< United States of America>

# Improvements that need to be made?

< Complete Redo >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MajorTomMueller** [comment]
Duplicate #1695

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/86969468-7940bc80-c133-11ea-911e-2d7240caa382.png)
