### ISSUE TITLE
LFNB-Mende Brenoux-LANGUEDOC-ROUSSILLON-FRANCE

### ISSUE THREAD

**Issue by FlyBoii31** [InfiniteFlightAirportEditing/Airports#5175]
# Airport Name

< Mende Brenoux >

# Country?

< France >

# Improvements that need to be made?

<Full Rework >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/94206589-6d8ba900-fe8b-11ea-986d-1d75903385bc.png)
