### ISSUE TITLE
MWCB-Charles Kirkconnell International Airport-SISTER ISLANDS-CAYMAN ISLANDS

### ISSUE THREAD

**Issue by FlyBoii31** [InfiniteFlightAirportEditing/Airports#5176]
# Airport Name

< Charles Kirkconnell International Airport >

# Country?

< Cayman Islands >

# Improvements that need to be made?

< Full redo >

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90313945-dfa8bf80-ded5-11ea-9071-857a1b8b3650.png)
