### ISSUE TITLE
SCTS-Santa Teresa del Almendral Airport-Melipilla-CHILE

### ISSUE THREAD

**Issue by vichols1506** [InfiniteFlightAirportEditing/Airports#5177]
# Airport Name

< Santa Teresa del Almendral >

# Country?

<chile >

# Improvements that need to be made?

< scratch >

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/87875037-fa018300-c993-11ea-8ec6-0c2774d3168d.png)
