### ISSUE TITLE
LETU-Aeródromo Militar de Ablitas-NAVARA-SPAIN

### ISSUE THREAD

**Issue by ItsW1ll** [InfiniteFlightAirportEditing/Airports#518]

**Comment by freddiefrogs** [comment]
Doesn't really have a boundary in real life.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20819881/f2731c90-b7fc-11e6-8282-18e0648df58d.png)

**Comment by kilt46** [comment]
NEED REMOVED
![image](https://user-images.githubusercontent.com/14023167/83351244-de6ceb00-a307-11ea-80d8-a33a3f353951.png)

**Comment by MajorTomMueller** [comment]
deleted

**Comment by MajorTomMueller** [comment]
Reused

**Comment by MajorTomMueller** [comment]
![LETU-git](https://user-images.githubusercontent.com/26853210/88461951-9e555f00-ce97-11ea-8a1b-a43867fb0f8a.png)
