### ISSUE TITLE
VQPR-Paro Airport-PARO-BHUTAN

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#519]
Paro International

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20820020/c461aa78-b7fd-11e6-84fe-6c446fd482f1.png)

**Comment by liamkirky** [comment]
Could I please be assigned to this? :)

**Comment by liamkirky** [comment]
Sent in for OR!
