### ISSUE TITLE
KLBR-Clarksville/Red River City-J D Trissell Fld-TEXAS-USA

### ISSUE THREAD

**Issue by 2000rpm** [InfiniteFlightAirportEditing/Airports#5192]
# Airport Name

< Clarksville/Red River City-J D Trissell Fld >

# Country?

< USA >

# Improvements that need to be made?

< Redoing from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/88466523-df974000-ce92-11ea-86d5-5042a8906e8c.png)
