### ISSUE TITLE
PAWG-Wrangell Airport-ALASKA-USA

### ISSUE THREAD

**Issue by zhf21** [InfiniteFlightAirportEditing/Airports#5193]
# Airport Name

PAWG

# Country?

United States of America

# Improvements that need to be made?

Full Redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by zhf21** [comment]
Not sure if this is required, but I will leave a progress check below. 

**What's Done**

- Runway
- Runway 10 Stopway
- Runway 28 Stopway
- Runway 28 Back Taxi Ramp
- All Light Fixtures
- All Taxiway Markings
- Tower Viewpoint
- Airport Boundary
- Windsock

 **What's Needs to be Done**

- ATC
- Spawn Spots and Lines
- Beacon

**Comment by zhf21** [comment]
Not sure if this is required, but I will leave a progress check below.

**What's Done**

- Runway
- Runway 10 Stopway
- Runway 28 Stopway
- Runway 28 Back Taxi Ramp
- Runway Border
- All Light Fixtures
- All Taxiway Markings
- Tower Viewpoint
- Airport Boundary
- Windsock

**What's Needs to be Done**

- ATC
- Spawn Spots and Lines
- Beacon

**Comment by brennanhackard** [comment]
@zhf21 updates aren't required. The only time someone will ask to see progress in GitHub is if you take way too long to complete an airport. Nice job though!

**Comment by zhf21** [comment]
Alright, thanks for the notice. I wanted to lean on the safe side just in case, but it seems I am in the clear. Thanks!

**Comment by zhf21** [comment]
Airport just submitted for PR! I would like to thank everyone who has helped me get started and can't wait to keep working!

**Comment by zhf21** [comment]
Submitted to PR for V2.

**Comment by zhf21** [comment]
Submitted to OR. Thanks everyone!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/91356210-ef1ce800-e7b4-11ea-91ff-7f064c45b45e.png)
