### ISSUE TITLE
ZHNY-Nanyang Jiangying Airport-HENAN-CHINA

### ISSUE THREAD

**Issue by jasonsoung** [InfiniteFlightAirportEditing/Airports#5195]
# Airport Name

< Nanyang Jiangying Airport >

# Country?

< China  >

# Improvements that need to be made?

< New >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MajorTomMueller** [comment]
You are the second guy that didn’t know the ICAO code he want’s to edit...
The next one who does that wouldn’t be assigned by me and send back to research...

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/119228267-d806ee80-bad7-11eb-8249-7b06f75b6a79.png)
