### ISSUE TITLE
LYPG-Podgorica Airport-MONTENEGRO 

### ISSUE THREAD

**Issue by AviatorNikola** [InfiniteFlightAirportEditing/Airports#5196]
# Airport Name

Podgorica Airport

# Country?

Montenegro

# Improvements that need to be made?

Redoing everything except for the runway

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

GP3 Airport serving capital of Montenegro

**Comment by MajorTomMueller** [comment]
@AviatorNikola , 

https://community.infiniteflight.com/t/question-regarding-podgorica-airport/481998/8

will you continue in foreseeable future? Or should I unassigned you to let a other editor do it?

**Comment by MajorTomMueller** [comment]
![LYPG-git](https://user-images.githubusercontent.com/26853210/130778819-400492c9-e635-48ff-97de-2bf0909816ae.png)
