### ISSUE TITLE
EDBU-Sonderlandeplatz Pritzwalk Sommersberg Airport-BRANDENBURG-GERMANY

### ISSUE THREAD

**Issue by rich-art-02** [InfiniteFlightAirportEditing/Airports#5197]
# Airport Name

Sonderlandeplatz Pritzwalk-Sommersberg

# Country?

Germany

# Improvements that need to be made?

redo from scratch

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/88245938-8f379c80-cc5e-11ea-96f6-4e79b886a472.png)
