### ISSUE TITLE
LFRG-Deauville Saint Gatien-BASSE-NORMANDIE-FRANCE

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#5198]
# Airport Name

Deauville Normandie Airport

# Country?

France

# Improvements that need to be made?

Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/89122920-f17b7300-d490-11ea-8411-6579c37eca9d.png)
