### ISSUE TITLE
KHPY-Baytown-TEXAS-USA

### ISSUE THREAD

**Issue by 2000rpm** [InfiniteFlightAirportEditing/Airports#5199]
# Airport Name

< Baytown >

# Country?

< USA >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/88465594-f84f2800-ce89-11ea-9b60-0d40fd64202a.png)
