### ISSUE TITLE
KLEX-Blue Grass Airport-KENTUCKY-USA

### ISSUE THREAD

**Issue by henrikbg** [InfiniteFlightAirportEditing/Airports#520]
Blue Grass airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20652394/02851210-b4be-11e6-91d5-a697e51a19fa.png)

**Comment by ECoops-123** [comment]
I'll be reworking this.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108007103-c38bf500-6fc2-11eb-8372-e942f49b23ee.png)
