### ISSUE TITLE
ZSGS-Jinggangshan Airport-JIANGXI-CHINA

### ISSUE THREAD

**Issue by Berlin-N** [InfiniteFlightAirportEditing/Airports#5200]
# Airport Name

< Jinggangshan Airport >

# Country?

< China >

# Improvements that need to be made?

< New >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by Berlin-N** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/88245402-ab3a3e80-cc5c-11ea-89b7-fd4d1ac6bc22.png)
