### ISSUE TITLE
SNAO-Trimonte Airport-RIO DE JANEIRO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5202]
# Airport Name

Trimonte Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/87597784-047ffc00-c6b8-11ea-9ddf-fd30a2bb995c.png)
