### ISSUE TITLE
KRAP-Rapid City-SOUTH DAKOTA-USA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#5203]
# Airport Name

< Rapid City Regional Airport >

# Country?

< USA >

# Improvements that need to be made?

< redo >

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/97505919-cf867500-1947-11eb-813e-ac14bfb80f45.png)
