### ISSUE TITLE
SWKO-Coari Airport-AMAZONAS-BRAZIL

### ISSUE THREAD

**Issue by victormw22** [InfiniteFlightAirportEditing/Airports#5205]
# Airport Name

< Coari >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< low >

**Comment by victormw22** [comment]
sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/88728935-5d0fba00-d0f8-11ea-956c-d1e369b50e52.png)
