### ISSUE TITLE
NFTO-Niuafoʻou Airport-NIUAFOʻOU-TONGA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#5206]
# Airport Name

Niuafoʻou Airport

# Country?

Tonga

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/88436386-d2624e80-cdc9-11ea-9989-f6e7d563c576.png)
