### ISSUE TITLE
LFNE-Salon Eyguières Airport-PROVENCE ALPES COTE D'AZUR-FRANCE

### ISSUE THREAD

**Issue by AeroTrapp** [InfiniteFlightAirportEditing/Airports#5208]
# Airport Name

Salon Eyguières Airport

# Country?

France

# Improvements that need to be made?

I will redo the airport from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MajorTomMueller** [comment]
IF Event, 10000ft+ Runway, World/US Capital, low
wich one equals "French aerodrome"?
well, I have no Label for "French aerodrome", I take a random on?
how about "Low"?
Could you live with that?

**Comment by AeroTrapp** [comment]
My bad. It is my first airport. I didn’t undertand this category.
``Low`` works well !

De : Major Tom
Envoyé le :lundi 20 juillet 2020 18:01
À : InfiniteFlightAirportEditing/Airports
Cc : Jeremy351; Assign
Objet :Re: [InfiniteFlightAirportEditing/Airports] LFNE - Salon Eyguières Airport - PROVENCE ALPES COTE D'AZUR - FRANCE (#5208)

IF Event, 10000ft+ Runway, World/US Capital, low
wich one equals "French aerodrome"?
well, I have no Label for "French aerodrome", I take a random on?
how about "Low"?
Could you live with that?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/91649697-176a4800-ea3c-11ea-8d95-c35d017166f8.png)
