### ISSUE TITLE
RPVF-Catarman Airport-NORTHERN SAMAR-PHILIPPINES

### ISSUE THREAD

**Issue by LesterXavier** [InfiniteFlightAirportEditing/Airports#5209]
# Airport Name

Catarman National Airport

# Country?

Philippines

# Improvements that need to be made?

Will be redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by LesterXavier** [comment]
Sent for Approval

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90322497-9e86ce80-df1a-11ea-9a32-72c7f8d054ac.png)
