### ISSUE TITLE
LPCS-Cascais Airport-LISBON-PORTUGAL

### ISSUE THREAD

**Issue by victormw22** [InfiniteFlightAirportEditing/Airports#5210]
# Airport Name

< Cascais  >

# Country?

< Portugal >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MajorTomMueller** [comment]
You have already three open issues.

**Comment by victormw22** [comment]
@MajorTomMueller  now i have 2 issues open, OEBA has been closed

**Comment by victormw22** [comment]
sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90312213-1e377d80-dec8-11ea-9107-47ba23b98454.png)
