### ISSUE TITLE
ZJYX-Sansha Yongxing Airport-HAINAN-CHINA

### ISSUE THREAD

**Issue by Berlin-N** [InfiniteFlightAirportEditing/Airports#5211]
# Airport Name

< Sansha Yongxing Airport >

# Country?

< China >

# Improvements that need to be made?

< New>

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by Berlin-N** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/89470164-b30bdf80-d740-11ea-92e1-6987a94ee771.png)
