### ISSUE TITLE
LFRK-Caen Carpiquet Airport-NORMANDIE-FRANCE

### ISSUE THREAD

**Issue by AeroTrapp** [InfiniteFlightAirportEditing/Airports#5212]
# Airport Name

Caen Carpiquet Airport

# Country?

France

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/93653791-0e87e900-f9e0-11ea-8b1a-d16d86a4affe.png)
