### ISSUE TITLE
RCKU-Chiayi Airport-TAIWAN-TAIWAN

### ISSUE THREAD

**Issue by aads552** [InfiniteFlightAirportEditing/Airports#5215]
# Airport Name

Chiayi Airport

# Country?

Taiwan

# Improvements that need to be made?

redo from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

10000ft+ Runway

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/93003864-e5f77f00-f507-11ea-8654-eae593cd717a.png)
