### ISSUE TITLE
SBPC-Pocos de Caldas Airport-MINAS GERAIS-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5216]
# Airport Name

Pocos de Caldas

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/88467532-a7e1c580-ce9d-11ea-9309-5eb59b0bee3c.png)
