### ISSUE TITLE
66R-Robert R Wells Jr Airport-TEXAS-USA

### ISSUE THREAD

**Issue by 2000rpm** [InfiniteFlightAirportEditing/Airports#5218]
# Airport Name

< Robert R Wells Jr >

# Country?

< USA >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by 2000rpm** [comment]
There has been update for some part north east side and the map has been disoriented compare to non-updated version.
And I have no clue what to do and how to do.
The update is there has been 2 cargoes constructed.

This is updated version.
![off the position](https://user-images.githubusercontent.com/39461161/88476647-0037c680-cf75-11ea-8bde-7ea5bd0bf572.jpg)

This is before updated.
![before updated](https://user-images.githubusercontent.com/39461161/88476674-56a50500-cf75-11ea-87bb-1dcaf4ab1dbf.jpg)

**Comment by 2000rpm** [comment]
![before updated with edit](https://user-images.githubusercontent.com/39461161/88476718-a7b4f900-cf75-11ea-9da6-91a4fec93f9a.jpg)
![off the position with edit](https://user-images.githubusercontent.com/39461161/88476720-ac79ad00-cf75-11ea-9159-a08f4b017fb7.jpg)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/89708996-73f8ac80-d941-11ea-8dfa-cfbf1e79a373.png)
