### ISSUE TITLE
KMOB-Mobile Regional Airport-ALABAMA-USA

### ISSUE THREAD

**Issue by henrikbg** [InfiniteFlightAirportEditing/Airports#522]
Mobile Regional Airport.

**Comment by henrikbg** [comment]
Redone.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17277317/bc77c8aa-5705-11e6-8637-34db3c0fea91.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17821939/de3bec0a-6619-11e6-9410-f2489d168c2f.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17821960/f82d10da-6619-11e6-9b04-0f8e6bbe7495.png)

**Comment by henrikbg** [comment]
Going to make some minor changes to this one to ensure it's up to today's standard.

**Comment by henrikbg** [comment]
Added improved file to the repository.
