### ISSUE TITLE
ROAH-Naha Airport-OKINAWA-JAPAN

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#5221]
# Airport Name

Naha

# Country?

Japan

# Improvements that need to be made?

Will be redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by OscarConklin** [comment]
Sent for OR!

**Comment by MajorTomMueller** [comment]
Duplicate #1704

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/91773996-76030380-ebad-11ea-90ef-695ac58473aa.png)
