### ISSUE TITLE
KTTA-Raleigh Exec-Sanford Lee Co-NORTH CAROLINA-USA

### ISSUE THREAD

**Issue by FlightGeekYuta** [InfiniteFlightAirportEditing/Airports#5222]
# Airport Name

Raleigh Executive Sanford Lee County
# Country?

USA
# Improvements that need to be made?

Full rework
# Are you working on this airport?

yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

US Capitol of North Carolina

**Comment by MajorTomMueller** [comment]
No priority, only a minor airport for Raleigh, they have a International airport.

**Comment by FlightGeekYuta** [comment]
Im not working on airports anymore. I’m very sorry to report this very late.

I’ll just leave the work I did here if you want to work off from an almost completed airport
https://drive.google.com/file/d/1ShAdnErjqYblipZ-bhOderdN3IYZJSrU/view?usp=drivesdk

**Comment by IFsami** [comment]
I can pick it up

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108598817-94c0a680-7355-11eb-9cd3-25f77cc710ae.png)
