### ISSUE TITLE
USUU-Kurgan Airport-KURGAN-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#5223]
# Airport Name

< Kurgan Airport >

# Country?

< Russia >

# Improvements that need to be made?

< Add >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/89470497-84423900-d741-11ea-87c8-bdabb52ec10f.png)
