### ISSUE TITLE
LFKS-Solenzara Airport-CORSE-FRANCE

### ISSUE THREAD

**Issue by AeroTrapp** [InfiniteFlightAirportEditing/Airports#5224]
# Airport Name

Solenzara

# Country?

France

# Improvements that need to be made?

Redone from scatch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/91771719-1276d700-eba9-11ea-8164-8e271cdf53b2.png)
