### ISSUE TITLE
16OI-Trump Airport-OHIO-USA

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#5226]
# Airport Name

Trump Airport

# Country?

USA!

# Improvements that need to be made?

Redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by jakey20** [comment]
sent to or

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/89580929-c16b0180-d7fb-11ea-8e24-48cd2e3e7da2.png)
