### ISSUE TITLE
UHQO-Zaporozhye-KAMCHATKA-RUSSIA

### ISSUE THREAD

**Issue by lucaviness** [InfiniteFlightAirportEditing/Airports#5227]
♻️

**Comment by Czechoslovaki** [comment]
Edited in #6275.

**Comment by AleksanderIF** [comment]
# **UHQO-Zaporozhye-KAMCHATKA-RUSSIA**
# Airport Name
Zaporozhye / Ozyornaya
# Country?
Russia
# Improvements that need to be made?
from scratch
# Are you working on this airport?
soon
# Airport Priority? (10000ft+ Runway, Low)
low
http://www.caiga.ru/common/AirClassGDE/validaip4/aip/ad/ad2/uhqo/4-ad2-uhqo-031.pdf

**Comment by brunocr1050** [comment]
Recycled issue.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106340945-147cb900-6261-11eb-9d8c-0d41da597154.png)
