### ISSUE TITLE
PHLU-Kalaupapa Airport-HAWAII-USA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5228]
# Airport Name

Kalaupapa Airport

# Country?

USA

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/89123661-93ea2500-d496-11ea-8f38-23ee04305770.png)
