### ISSUE TITLE
KEKO-Elko Regional Airport-NEVADA-USA

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#5229]
# Airport Name

Elko Regional

# Country?

USA

# Improvements that need to be made?

Redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/91649585-3fa57700-ea3b-11ea-8bab-184b10165281.png)
