### ISSUE TITLE
LPPM-Portimao Airport-ALGARVE-PORTUGAL

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#5230]
# Airport Name

Portimão Airport

# Country?

Portugal

# Improvements that need to be made?

Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90311913-9c465500-dec5-11ea-9901-47b12851d29c.png)
