### ISSUE TITLE
KRSL-Russell Muicipal Airport-KANSAS-USA

### ISSUE THREAD

**Issue by zacky89315** [InfiniteFlightAirportEditing/Airports#5231]
# Airport Name

< Russell Muicipal Airport >

# Country?

< USA >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90446661-62cd3f80-e0a7-11ea-8698-e0ca336566d4.png)
