### ISSUE TITLE
SIBZ-Itaporanga Airport-PARAIBA-BRAZIL

### ISSUE THREAD

**Issue by victormw22** [InfiniteFlightAirportEditing/Airports#5232]
# Airport Name

< Itaporanga >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by victormw22** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90447652-5ba73100-e0a9-11ea-9053-4ff9e131656b.png)
