### ISSUE TITLE
ZBBB-Beijing Xijiao Airport-BEIJING-CHINA

### ISSUE THREAD

**Issue by Berlin-N** [InfiniteFlightAirportEditing/Airports#5233]
# Airport Name

< Beijing Xijiao Airport >

# Country?

< China >

# Improvements that need to be made?

< New >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by RyanEpps** [comment]
Nope

**Comment by Berlin-N** [comment]
Sen to OR

**Comment by Berlin-N** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90841241-ce224600-e321-11ea-8be9-5058145322d1.png)
