### ISSUE TITLE
KAEX-Alexandria International Airport-LOUISIANA-USA

### ISSUE THREAD

**Issue by IanD1583** [InfiniteFlightAirportEditing/Airports#5234]
# Airport Name

< Alexandria International Airport >

# Country?

< United States >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by feitidede** [comment]
eh i can do this

**Comment by becarboner3000** [comment]
@feitidede have made the corrections I asked last Sunday?

**Comment by feitidede** [comment]
and this

**Comment by becarboner3000** [comment]
Did you seriously waited after I unassigned you to reply? Give me a break.

**Comment by feitidede** [comment]
gbkarp told me u unassigned me so thats why i commented here

**Comment by becarboner3000** [comment]
Well, unfortunately for you, you're no longer a team member considering the background of all this. This makes you unable to (re)claim any airports you had before being removed. Good day sir.

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/132932783-adc62800-e543-4ef8-a951-7b2c97f9c49d.png)
