### ISSUE TITLE
ZGFS-Foshan Shadi Airport-GUANGDONG-CHINA

### ISSUE THREAD

**Issue by Berlin-N** [InfiniteFlightAirportEditing/Airports#5235]
# Airport Name

< Foshan Shadi Airport >

# Country?

< China >

# Improvements that need to be made?

< New >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by Berlin-N** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/92186277-df884980-ee1b-11ea-8e22-6d7a226a3d29.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/120070764-b1a1ff80-c051-11eb-95c6-9bda2380269c.png)
