### ISSUE TITLE
1ID9-Simko Field-IDAHO-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#5236]
# Airport Name

< Simko Field >

# Country?

< USA >

# Improvements that need to be made?

< Full Redo >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by brennanhackard** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90298777-1ab8dd80-de59-11ea-87ea-ec52d3d48b2a.png)
