### ISSUE TITLE
SBMZ-Porto de Moz Airport-PARA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5237]
# Airport Name

Porto de Moz Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/89587820-fed58c00-d807-11ea-83f9-93803a152918.png)
