### ISSUE TITLE
RPLB-Subic Bay Airport-BATAAN-PHILIPPINES

### ISSUE THREAD

**Issue by LesterXavier** [InfiniteFlightAirportEditing/Airports#5238]
# Airport Name

Subic Bay International Airport

# Country?

Philippines

# Improvements that need to be made?

will be done from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/94371523-c8f0ad80-00bc-11eb-8dfc-39cf37ac1c6c.png)
