### ISSUE TITLE
NZAR-Ardmore Airport-AUCKLAND-NEW ZEALAND

### ISSUE THREAD

**Issue by Lukeh0** [InfiniteFlightAirportEditing/Airports#5239]
# Airport Name

Ardmore Airport

# Country?

New Zealand

# Improvements that need to be made?

Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105781485-4e378200-5f38-11eb-80aa-f74d41ee41a9.png)
