### ISSUE TITLE
KIAD-Washington Dulles International Airport-VIRGINIA-USA

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#524]

**Comment by kilt46** [comment]
AIRPORT REDRAWN FROM SCRATCH

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18608522/4703769c-7cb1-11e6-9e44-742a16f3ca15.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18608530/7e315e5e-7cb1-11e6-83a2-c171e62185b0.png)

**Comment by brunocr98** [comment]
Carrying out a full redo.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56399362-1f449600-6213-11e9-84eb-b10af2fc56f5.png)
