### ISSUE TITLE
PATU-Casco Cove CGS-ALASKA-USA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#5240]
# Airport Name

Todd Field

# Country?

USA

# Improvements that need to be made?

Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MajorTomMueller** [comment]
Sorry for not finding the first issue. 
First come first serve.
Please take another one

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/89947271-cf4cc800-dbe9-11ea-8208-165edda9abfb.png)
