### ISSUE TITLE
LEAH-Aerodromas des los Alcores-SPAIN

### ISSUE THREAD

**Issue by EvO1324** [InfiniteFlightAirportEditing/Airports#5242]
# Airport Name

< Camden Airport >

# Country?

< Australia >

# Improvements that need to be made?

< Add new spawn points and a general fix-u >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MajorTomMueller** [comment]
Original #459

**Comment by MajorTomMueller** [comment]
![LEAH-git](https://user-images.githubusercontent.com/26853210/89725827-7e7b7a80-da03-11ea-9a24-c7105b771e6d.png)
