### ISSUE TITLE
KONP-Newport Municipal Airport-OREGON-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#5244]
# Airport Name

Newport Municipal Airport

# Country?

USA

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

yea

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90840542-de392600-e31f-11ea-90e0-0863efe791a9.png)
