### ISSUE TITLE
KTME-Houston Executive Airport-TEXAS-USA

### ISSUE THREAD

**Issue by 2000rpm** [InfiniteFlightAirportEditing/Airports#5245]
# Airport Name

< Houston Executive >

# Country?

< USA >

# Improvements that need to be made?

< Redo >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/91919255-e6cc1d80-ec8a-11ea-994c-76e10fec8160.png)
