### ISSUE TITLE
KUTS-Huntsville Muni-TEXAS-USA

### ISSUE THREAD

**Issue by 2000rpm** [InfiniteFlightAirportEditing/Airports#5246]
# Airport Name

< Huntsville Muni >

# Country?

< USA >

# Improvements that need to be made?

< Redo >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/91919041-4d9d0700-ec8a-11ea-9e5e-c95eac82dfb4.png)
