### ISSUE TITLE
T41-La Porte Muni-TEXAS-USA

### ISSUE THREAD

**Issue by 2000rpm** [InfiniteFlightAirportEditing/Airports#5247]
# Airport Name

< La Porte Muni >

# Country?

< USA >

# Improvements that need to be made?

< Redo >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/91912473-d1e68e80-ec78-11ea-8fda-a028b25c6c46.png)
