### ISSUE TITLE
ZYYJ-Yanji Chaoyangchuan Airport-JILIN-CHINA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#5248]
# Airport Name

Yanji Chaoyangchuan International Airport

# Country?

China

# Improvements that need to be made?

Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/94348738-41476800-0004-11eb-8390-e48757a00ceb.png)
