### ISSUE TITLE
31E-Eagles Nest-NEW JERSEY-USA

### ISSUE THREAD

**Issue by zhf21** [InfiniteFlightAirportEditing/Airports#5249]
# Airport Name

Eagles Nest

# Country?

United States of America

# Improvements that need to be made?

Full Redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

<Low

**Comment by zhf21** [comment]
Airport just submitted for PR! I would like to thank everyone who has helped me and can't wait to continue working!

**Comment by zhf21** [comment]
Sent to OR!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/95926449-f490ba80-0d81-11eb-8383-ea3af7386f26.png)
