### ISSUE TITLE
LKPR-Václav Havel Airport Prague-PRAGUE-CZECH REPUBLIC

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#525]

**Comment by 5620monte** [comment]
I will take take it

**Comment by turkish1941** [comment]
I will make this

**Comment by turkish1941** [comment]
I have sent the email

**Comment by dushyants19** [comment]
5647b95

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19223519/782f32be-8e37-11e6-9f1f-34879810879e.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/77216139-0dd8cd80-6af7-11ea-834c-bedd9ff117f1.jpg)
