### ISSUE TITLE
KVCB-Nut Tree Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#5250]
# Airport Name

Nut Tree Airport

# Country?

USA

# Improvements that need to be made?

Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/93151513-c73ce800-f6c1-11ea-88de-d2141b279c8d.png)
