### ISSUE TITLE
EDOD-Sonderlandeplatz Reinsdorf-BRANDENBURG-GERMANY

### ISSUE THREAD

**Issue by rich-art-02** [InfiniteFlightAirportEditing/Airports#5253]
# Airport Name

Sonderlandeplatz Reinsdorf

# Country?

Germany

# Improvements that need to be made?

redo from scratch

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/92313540-76771200-ef92-11ea-92ce-1c4c0a81cdb9.png)
