### ISSUE TITLE
PHPA-Port Allen Airport-HAWAII-USA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5254]
# Airport Name

Port Allen Airport

# Country?

USA

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90322457-e527f900-df19-11ea-92b0-588e643385e7.png)
