### ISSUE TITLE
PHBK-Barking Sands Pmrf Airport-HAWAII-USA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5255]
# Airport Name

Barking Sands Pmrf Airport

# Country?

USA

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90322965-9598fb80-df20-11ea-903e-94c838747394.png)
