### ISSUE TITLE
USCM-Magnitogorsk International Airport RUSSIA

### ISSUE THREAD

**Issue by Ryanairy55** [InfiniteFlightAirportEditing/Airports#5256]
# Airport Name

Magnitogorsk International Airport

# Country?

Russia

# Improvements that need to be made?

Reworking it from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

GP2

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/91919827-d4eb7a00-ec8c-11ea-8b9a-5b21f3e38992.png)
