### ISSUE TITLE
KHYS-Hays Regional Airport-KANSAS-USA

### ISSUE THREAD

**Issue by zacky89315** [InfiniteFlightAirportEditing/Airports#5257]
# Airport Name

< Hays Regional Airport >

# Country?

< USA >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/92665989-a47b8f80-f2cd-11ea-813f-8908ad824543.png)
