### ISSUE TITLE
IS59-Rotstein Airstrip-ILLINOIS-USA

### ISSUE THREAD

**Issue by jaypzs** [InfiniteFlightAirportEditing/Airports#5258]
# Airport Name

Godofredo P.Ramos Principal Airport

# Country?

Philipppines

# Improvements that need to be made?

To add more gates

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MajorTomMueller** [comment]
#901

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90575044-1efa3900-e180-11ea-996f-5430f8eaa1aa.png)
