### ISSUE TITLE
KCVG-Cincinnati/Northern Kentucky International Airport-KENTUCKY-USA

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#526]
Cincinnati Northern Kentucky Int'l. Needs spawn points and white lines on roadways. A few unsnapped roadways and taxiways

**Comment by dushyants19** [comment]
@IFAEpat are you doing this?

**Comment by netjets-1951** [comment]
I'll take this one since it is sorta part of Project Ohio.

**Comment by netjets-1951** [comment]
Sent in for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/29249367-8f41a816-7ff3-11e7-83bd-13d9c4e0ffbf.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52528773-bb9a6b80-2cab-11e9-8c05-879e785861da.png)
