### ISSUE TITLE
KNUW-Whidbey Island NAS Airport-WASHINGTON-USA

### ISSUE THREAD

**Issue by kirby2007** [InfiniteFlightAirportEditing/Airports#5261]
# Airport Name

< WHIDBEY ISLAND NAS (AULT FIELD) >

# Country?

< United States >

# Improvements that need to be made?

< Total rework from auto-generated >

# Are you working on this airport?

< Yes, if approved >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![Uploading image.png…]()
