### ISSUE TITLE
RPMH-Camiguin Airport-CAMIGUIN-PHILIPPINES

### ISSUE THREAD

**Issue by LesterXavier** [InfiniteFlightAirportEditing/Airports#5262]
# Airport Name

< Camiguin Airport >

# Country?

< Philippines >

# Improvements that need to be made?

< rework from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by LesterXavier** [comment]
Sent for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/92842474-386e5980-f3a9-11ea-84b5-0113a25c2a87.png)
