### ISSUE TITLE
ENHV-Honningsvag Valan Airport-TROMS OG FINNMARK-NORWAY

### ISSUE THREAD

**Issue by JensSeverin** [InfiniteFlightAirportEditing/Airports#5263]
# Airport Name

Honningsvag Valan Airport

# Country?

Norway

# Improvements that need to be made?

Full Redo
# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/96938883-17615400-1491-11eb-803b-5ea13ea6253d.png)
