### ISSUE TITLE
ENBS-Båtsfjord Airport-TROMS OG FINNMRK-NORWAY

### ISSUE THREAD

**Issue by JensSeverin** [InfiniteFlightAirportEditing/Airports#5264]
# Airport Name

Båtsfjord Airport

# Country?

Norway

# Improvements that need to be made?

Full Redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/91649491-952d5400-ea3a-11ea-8ed3-36a5979fae06.png)
