### ISSUE TITLE
KBAD-Barksdale Air Force Base-LOUISIANA-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#5265]
# Airport Name

< Barksdale Air Force Base >

# Country?

< United States of America >

# Improvements that need to be made?

< full redo >

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< 10K+ >

**Comment by MajorTomMueller** [comment]
👍

**Comment by brennanhackard** [comment]
@MajorTomMueller can you please reopen this?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102300628-e8a8ac80-3f1a-11eb-8098-0f69df0096c7.png)
