### ISSUE TITLE
UMKK-Khrabrovo Airport-Russia

### ISSUE THREAD

**Issue by zhf21** [InfiniteFlightAirportEditing/Airports#5267]
# Airport Name

UMKK

# Country?

Russia

# Improvements that need to be made?

Full Redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by RyanEpps** [comment]
Nope

**Comment by zhf21** [comment]
It needs a full redo. Can you reopen #1219 please?
