### ISSUE TITLE
FDSK-Sikhuphe International Airport-MANZINI-KINGDOM OF ESWATINI

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#5268]
# Airport Name

Sikhuphe International Airport

# Country?

Kingdom of Eswatini

# Improvements that need to be made?

New Airport

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

10k+

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/91649956-ed665500-ea3e-11ea-9e29-c5d3c7e7dee0.png)
