### ISSUE TITLE
VEAT-Agartala Airport-INDIA

### ISSUE THREAD

**Issue by KaalicharanDH** [InfiniteFlightAirportEditing/Airports#5269]
# Airport Name

 Agartala Airport

# Country?

India

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/92983257-d58fc780-f467-11ea-8e65-beb9440f9e2b.png)
