### ISSUE TITLE
UTDL-Khujand Airport-TAJIKISTAN

### ISSUE THREAD

**Issue by Ryanairy55** [InfiniteFlightAirportEditing/Airports#5271]
# Airport Name

Khujand Airport

# Country?

Tajikistan

# Improvements that need to be made?

From scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

GP2

**Comment by AleksanderIF** [comment]
Hi @Ryanairy55, you were assigned on August 22, what is your progress?

**Comment by Ryanairy55** [comment]
> Hi @Ryanairy55, you were assigned on August 22, what is your progress?

Hi, I stopped making airport for IF that much. I made half of this airport (and I can send you apt.dat right after get back at home in 3 days)

**Comment by ECoops-123** [comment]
@tsarkov90 was the imposter.

They'll be taking over UTDL.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108599699-4b258b00-7358-11eb-95bb-b5306bbc6f57.png)
