### ISSUE TITLE
CYVK-Vernon Airport-BRITISH COLUMBIA-CANADA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#5273]
# Airport Name

Vernon Airport 

# Country?

Canada

# Improvements that need to be made?

Full rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/92313430-63b00d80-ef91-11ea-94b8-b5bda6823b6b.png)
