### ISSUE TITLE
RPMO-Ozamis Community Airport-MISAMIS OCCIDENTAL-PHILIPPINES

### ISSUE THREAD

**Issue by LesterXavier** [InfiniteFlightAirportEditing/Airports#5275]
# Airport Name

Ozamis Airport

# Country?

Philippines

# Improvements that need to be made?

redone from scratch

# Are you working on this airport?

Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by LesterXavier** [comment]
Sent for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/93001059-f8ff5480-f4f1-11ea-9504-152eb0d976a8.png)
