### ISSUE TITLE
VIDF-Pitoragarh Airport-Uttarakhand-India

### ISSUE THREAD

**Issue by KaalicharanDH** [InfiniteFlightAirportEditing/Airports#5276]
# Airport Name

Pithoragarh Airport

# Country?

India

# Improvements that need to be made?

Full rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/91909009-099e0800-ec72-11ea-9f52-ac245b287c84.png)
