### ISSUE TITLE
SNGI-Guanambi Airport-BAHIA-BRAZIL

### ISSUE THREAD

**Issue by victormw22** [InfiniteFlightAirportEditing/Airports#5277]
# Airport Name

< Guanambi >

# Country?

< Brazil >

# Improvements that need to be made?

< scratch >

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by victormw22** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/92326991-f2696c80-f01b-11ea-913f-8234f182a202.png)
