### ISSUE TITLE
SSPN-Paranaíba Airport-MATO GROSSO DO SUL-BRAZIL

### ISSUE THREAD

**Issue by Renanbas** [InfiniteFlightAirportEditing/Airports#5278]
# Airport Name 

< Paranaíba >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MBeringuy** [comment]
![SSPN](https://user-images.githubusercontent.com/32115399/132260836-0a567d2b-ef63-44d3-a232-80da4f1a4a73.jpg)
