### ISSUE TITLE
7N1-Corning Painted Post Airport-NEW YORK-USA

### ISSUE THREAD

**Issue by tomthetank46** [InfiniteFlightAirportEditing/Airports#5279]
# Airport Name

Corning-Painted Post

# Country?

USA

# Improvements that need to be made?

Full Redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
You have already reached the limit of 3 airports assigned to you. You will need to wait until one of them is approved by the OR and the corresponding issue is closed.

**Comment by tomthetank46** [comment]
ID74 was accepted, may I be assigned this?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/93648264-f740ff80-f9cf-11ea-95a2-c3f1c708d4cf.png)
