### ISSUE TITLE
EGAC-Belfast City Airport-NORTHERN IRELAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#528]
George Best, Belfast City.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17249307/0530e0a6-5565-11e6-8aed-c585718e0e74.png)

**Comment by IFAEpat** [comment]
Still has white outlines, boundary goes through features, unneeded markings

![screen shot 2016-08-22 at 7 01 29 pm](https://cloud.githubusercontent.com/assets/18223248/17874654/1fdba906-689b-11e6-9989-e6fc30bfe0d1.png)

![screen shot 2016-08-22 at 7 03 41 pm](https://cloud.githubusercontent.com/assets/18223248/17874664/2d40967e-689b-11e6-8632-1f9b65263116.png)

**Comment by IFAEpat** [comment]
also missing huge building 

![screen shot 2016-08-22 at 6 58 42 pm](https://cloud.githubusercontent.com/assets/18223248/17874690/500cd8a2-689b-11e6-8cfe-b70b7415d3ed.png)

![screen shot 2016-08-22 at 7 04 59 pm](https://cloud.githubusercontent.com/assets/18223248/17874700/5cc00286-689b-11e6-933e-45f59e103375.png)

**Comment by JcFl4** [comment]
That building is not part of the airport. The boundary does not affect anything if it is over features, but I will change it as soon as I can. What do you mean by "still" and "unnecessary" white "outlines" it's the road and airport details, the same present in EGBB that make the airport so realistic.

**Comment by IFAEpat** [comment]
@JcFl4 I was told to remove those lines at the gates of EGBB.

**Comment by JcFl4** [comment]
Why do we have to...  looks so good with them! Well then, I will remove them as soon as I can. Thanks.

**Comment by JcFl4** [comment]
All fixed.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18225981/e802d4b2-71c5-11e6-8713-1047678eee26.png)

**Comment by dushyants19** [comment]
"White lines need to be removed around the building and also overlapping taxiways need to be cleaned up, runway markings need sorting as well" ~ @ItsW1ll

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34502750-95777ad8-efda-11e7-9d6d-5d43adf6edeb.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44614912-7bc1f380-a7f3-11e8-9093-e799668ee150.png)

**Comment by kilt46** [comment]
Boundary Fixed
