### ISSUE TITLE
SAD4-Aeroclub Rio Gallegos Airport-SANTA CRUZ-ARGENTINA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5281]
# Airport Name

Aeroclub Rio Gallegos

# Country?

Argentina

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/91229995-591f8980-e6f0-11ea-82c6-3fbf58c62a4d.png)
