### ISSUE TITLE
SAWJ-San Julian Airport-SANTA CRUZ-ARGENTINA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5282]
# Airport Name

San Julian Airport

# Country?

Argentina

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/91227502-3be8bc00-e6ec-11ea-90c4-5e1c2b9cc3ad.png)
