### ISSUE TITLE
SUSO-Nueva Hesperides Airport-SALTO-URUGUAY

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5283]
# Airport Name

Nueva Hesperides International Airport

# Country?

Uruguay

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/91226983-66864500-e6eb-11ea-87f7-29814178d682.png)
