### ISSUE TITLE
VIPT-Pantnagar Airport-UTTARAKHAND-INDIA

### ISSUE THREAD

**Issue by KaalicharanDH** [InfiniteFlightAirportEditing/Airports#5284]
# Airport Name

Pantnagar

# Country?

India

# Improvements that need to be made?

Full rework

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by KaalicharanDH** [comment]
i have not yet been assigned to this airport, can someone please assign me to it?

**Comment by MajorTomMueller** [comment]
Looks like you have not accepted the invite to GitHub you should have received via email.
There is a link in that email to accept the invite.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/92313362-a2919380-ef90-11ea-8cdf-97b7b6275c9b.png)
