### ISSUE TITLE
EDCS-Sonderlandeplatz Saarmund-BRANDENBURG-GERMANY

### ISSUE THREAD

**Issue by rich-art-02** [InfiniteFlightAirportEditing/Airports#5289]
# Airport Name

Sonderlandeplatz Saarmund

# Country?

Germany

# Improvements that need to be made?

redo from scratch

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/92982953-27375280-f466-11ea-90c6-e8b86d95554f.png)
