### ISSUE TITLE
VABB-Chhatrapati Shivaji International Airport-MAHARASHTRA-INDIA

### ISSUE THREAD

**Issue by corporate1401** [InfiniteFlightAirportEditing/Airports#529]
Bombay, India. A380 airport

**Comment by dushyants19** [comment]
Recycled issue for VABB. Mumbai, A380 airport

**Comment by sudafly** [comment]
I do this, @corporate1401

**Comment by sudafly** [comment]
Who can unassigns me? I have don't have time now, because i have now exams.

**Comment by corporate1401** [comment]
have i to do this one??

**Comment by dushyants19** [comment]
@corporate1401 any progress?

**Comment by shanawaz97** [comment]
Any progress Bro

**Comment by PaulNielsen** [comment]
I think you can make it, he opened this issue in May and still nothing. So I would say go ahead.

**Comment by corporate1401** [comment]
I didn't even know I was assigned this one...

**Comment by ReflexRSM** [comment]
I think there's a mistake here @IFAEpat..

**Comment by dushyants19** [comment]
Unassigned, @ReflexRSM want to do it?

**Comment by moritzbabl** [comment]
I will take this airport

**Comment by moritzbabl** [comment]
Sent for approval

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21482550/0ad9e54c-cb3b-11e6-8214-e367afeb7fa2.png)

**Comment by moritzbabl** [comment]
Reworked, @kilt46 feel free to do the gating again

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/94338526-978eb980-ffb8-11ea-8be8-d5f90feb495c.png)
