### ISSUE TITLE
ZSZS-Zhoushan Putuoshan Airport-ZHEJIANG-CHINA

### ISSUE THREAD

**Issue by zacky89315** [InfiniteFlightAirportEditing/Airports#5293]
# Airport Name

< Zhoushan Putuoshan Airport >

# Country?

< China >

# Improvements that need to be made?

< redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/95926088-0756bf80-0d81-11eb-9ff5-5e2be5b7ee91.png)
