### ISSUE TITLE
KPIA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#53]
Chicago

**Comment by JohnPreston21** [comment]
Adding spawn points to this one

**Comment by JohnPreston21** [comment]
adding taxiways and some spawn points

**Comment by JohnPreston21** [comment]
added parking, some spawn points, taxiways and  Tower viewpoint as there was none.
Finished

**Comment by Swang007** [comment]
John, someone said that the tower view is at the end of a runway. Maybe not in the right position. Do you want to look at this?

**Comment by JohnPreston21** [comment]
I dont quite remember where i placed the tower viewpoint

**Comment by Swang007** [comment]
I have some pictures: this is the tower view from KPIA

**Comment by Swang007** [comment]
![image](https://cloud.githubusercontent.com/assets/11000109/7798152/d5922e88-02bb-11e5-8500-e3a3f9a94786.jpg)
![image](https://cloud.githubusercontent.com/assets/11000109/7798153/d592e5d0-02bb-11e5-908a-ea546c032764.jpg)

**Comment by JohnPreston21** [comment]
Where was it before now?

**Comment by Swang007** [comment]
I'm not sure. Someone on IFFG asked what airport has the tower sitting on the runway. This one is close but I found that KCMI is closer. Adding pictures to that issue now

**Comment by Swang007** [comment]
Okay, someone just pointed this out in the forum, I'll take care of it

**Comment by Swang007** [comment]
I can't find where the tower is in real life guys...

**Comment by Rotate-FDS** [comment]
Is there still a problem with the tower view?

**Comment by Rotate-FDS** [comment]
I didn't know the tower was already corrected.

The taxiways are really messed up and the cargo apron (northeast), GA hangars (northwest), and ANG ramp (south) are missing.

**Comment by JohnPreston21** [comment]
I am currently working on this one. Completed the reg design and now working on taxi lines and parking. Expect to be done in a couple days

**Comment by kilt46** [comment]
The tower IRL is in the old terminal building to the east

**Comment by JohnPreston21** [comment]
@rotate-FDS I am assigned to this come. Currently working on a complele rework.

**Comment by JohnPreston21** [comment]
This one is up for grabs. Since my mom had to retore my PC, it wiped everything and started my laptop back to factory. Didn't realize she did a full clean, yikes.

**Comment by kilt46** [comment]
I have this one mostly done. I sent revision to Cameron recently

**Comment by JohnPreston21** [comment]
You was working on this also?

**Comment by kilt46** [comment]
I worked on this as an initial learning module.

**Comment by kilt46** [comment]
Thx John. Realized that I couldn't change status using iPad. Java doesn't
jive.

**Comment by JohnPreston21** [comment]
No worries

**Comment by kilt46** [comment]
Fully reworked and National Guard included

**Comment by kilt46** [comment]
KPIA now complete and emailed in.

**Comment by JohnPreston21** [comment]
Thanks for completing this. The current design was a temp job, Closing this one now.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17269535/a9a6a80e-5610-11e6-92c2-0df69d84d4b3.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17280728/31352260-575a-11e6-836a-952e4d34bfd8.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17348446/c1af56a8-58db-11e6-80db-328b063218e9.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17348620/137c38b0-58dd-11e6-9595-d1be5b0a3573.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17384994/49b7c840-59a5-11e6-9a04-fc7ef8bfc1e1.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33464670-207e304a-d609-11e7-80c7-21d6a9805225.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36351830-c66c7094-1474-11e8-94ed-5a92e8ace315.png)
New gates 12-14

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/96355222-c8887880-10a4-11eb-97ba-5b4252c8bb31.png)

**Comment by kilt46** [comment]
Buildings removed. Gates cleaned up
