### ISSUE TITLE
KSGU-St. George Regional Airport-UTAH-USA

### ISSUE THREAD

**Issue by henrikbg** [InfiniteFlightAirportEditing/Airports#530]
St. George Regional Airport.

**Comment by freddiefrogs** [comment]
Will do.

**Comment by freddiefrogs** [comment]
Thank you @samuelandersson

**Comment by freddiefrogs** [comment]
Unable to continue editing due to recurring computer problems. Can someone else please takeover.

**Comment by PilotCat** [comment]
i could do this

**Comment by bavAVIA** [comment]
I'll take this.

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/26853925-966edf7c-4ad9-11e7-94ec-402d79cf2039.png)
