### ISSUE TITLE
LSZI-Flugplatz Fricktal-Schupfart-SWITZERLAND

### ISSUE THREAD

**Issue by NickRWing** [InfiniteFlightAirportEditing/Airports#5300]
# Airport Name

Flugplatz Fricktal-Schupfart 

# Country?

 Switzerland 

# Improvements that need to be made?

A few taxiway lines are missing and there are some parking spots also missing 

# Are you working on this airport?

Yes, I'm working on it 

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MajorTomMueller** [comment]
Duplicate #852
