### ISSUE TITLE
LRSV-Suceava-SUCEAVA-ROMANIA

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#5305]
# Airport Name

Suceava "Stefan Cel Mare"

# Country?

Romania

# Improvements that need to be made?

Redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by jakey20** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/94870127-670dac00-040c-11eb-90ac-45ef8ea1c81d.png)
