### ISSUE TITLE
LPVZ-Viseu Airport-VISEU-PORTUGAL

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#5307]
# Airport Name

Viseu Airport

# Country?

Portugal

# Improvements that need to be made?

Will be redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by OscarConklin** [comment]
Sent for OR!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/93000961-1e3f9300-f4f1-11ea-8d98-fe52b50b767c.png)
