### ISSUE TITLE
LRAR-Arad International-ARAD-ROMANIA

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#5308]
# Airport Name

Arad International

# Country?

Romania

# Improvements that need to be made?

Redo

# Are you working on this airport?

da

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low low low low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/94869698-7809ed80-040b-11eb-920e-a30530827b02.png)
