### ISSUE TITLE
KBKE-Baker City Municipal-OREGON-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#5309]
# Airport Name

Baker City Municipal

# Country?

USA

# Improvements that need to be made?

Full Redo

# Are you working on this airport?

Of Course

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by Czechoslovaki** [comment]
Sent For OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/93000801-47abef00-f4f0-11ea-8e7a-e85c6398c7a8.png)
