### ISSUE TITLE
SAME-Mendoza Airport-MENDOZA-ARGENTINA

### ISSUE THREAD

**Issue by matsedvin** [InfiniteFlightAirportEditing/Airports#531]
RECYCLED.

**Comment by henrikbg** [comment]
Any progress, @matsedvin? I might work on this if you're not going to. :)

**Comment by matsedvin** [comment]
I got caught up in exams... I also had some problems with WEDbing alignment, but feel free to take it, if you can tell me how you fixed it!😂

**Comment by dushyants19** [comment]
@matsedvin how is this going?

**Comment by matsedvin** [comment]
I **finally** fixed my WEDbing problems, I'm working on it now.

**Comment by dushyants19** [comment]
@matsedvin hows the progress?

**Comment by chrislunde** [comment]
Will gladly take over this

**Comment by brunocr98** [comment]
Any updates of this airport?

**Comment by brunocr98** [comment]
I'll take care of this airport after EDDF.

**Comment by brunocr98** [comment]
This airport has officially exploded my mind.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25304050/dad11b72-2724-11e7-8e61-e538117365b2.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/58834583-217b7c00-862a-11e9-9d8a-54decebcffc5.jpg)
