### ISSUE TITLE
KLFK-Angelina Co Airport-TEXAS-USA

### ISSUE THREAD

**Issue by 2000rpm** [InfiniteFlightAirportEditing/Airports#5313]
# Airport Name

< Angelina Co >

# Country?

< USA >

# Improvements that need to be made?

< To be redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/93454811-19882f80-f8a1-11ea-958d-fd6b1c0b3ca0.png)
