### ISSUE TITLE
KJSO-Cherokee Co-TEXAS-USA

### ISSUE THREAD

**Issue by 2000rpm** [InfiniteFlightAirportEditing/Airports#5314]
# Airport Name

< Cherokee Co >

# Country?

< USA >

# Improvements that need to be made?

< To be redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/93647574-56057980-f9ce-11ea-9600-a2aff1844a9f.png)
