### ISSUE TITLE
VIBW-Bhiwani Airport-HARYANA-INDIA

### ISSUE THREAD

**Issue by KaalicharanDH** [InfiniteFlightAirportEditing/Airports#5317]
# Airport Name

Bhiwani Airport

# Country?

India

# Improvements that need to be made?

Full rework needed

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MBeringuy** [comment]
Available for anyone who wants to edit.

**Comment by suhasjatla** [comment]
I'd like to work on this please

**Comment by Czechoslovaki** [comment]
@suhasjatla enjoy.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101243943-12670580-36c9-11eb-86f1-348f4056755c.png)
