### ISSUE TITLE
VIBR-Bhuntar Airport-Himachcal Pradesh-India

### ISSUE THREAD

**Issue by KaalicharanDH** [InfiniteFlightAirportEditing/Airports#5318]
# Airport Name

Bhuntar Airport

# Country?

India

# Improvements that need to be made?

Full rework needed

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MajorTomMueller** [comment]
We have a limit of three issues a user could be assigned to. Make a comment here when you have less then 3 issues Assigned.

**Comment by KaalicharanDH** [comment]
May I be Assigned to it now?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/95924862-03756e00-0d7e-11eb-84f1-d83d3ca077fa.png)
