### ISSUE TITLE
4S1-Gold Beach Municipal Airport-OREGON-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#5320]
# Airport Name

Gold Beach Municipal

# Country?

USA

# Improvements that need to be made?

Full Redo

# Are you working on this airport?

Duh

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by Czechoslovaki** [comment]
Sent For OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/93455290-c793d980-f8a1-11ea-852f-a72b04b0856a.png)
