### ISSUE TITLE
MMMX-Benito Juarez International Airport-DISTRITO FEDERAL-MEXICO

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#533]
RECYCLED
♻️

**Comment by IceBlue02** [comment]
Blimey...

**Comment by carmichaelalonso** [comment]
**This is not a valid issue**.

One issue per airport please. Thanks!

**Comment by TristinWoolf** [comment]
@lalomarlin is taking over on this now. :)

**Comment by lalomarlin** [comment]
México City almost done, no more than 5 days ;)

**Comment by lalomarlin** [comment]
MMMX is delayed again

**Comment by lalomarlin** [comment]
Sent for Review :)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20819708/d6e1eb24-b7fb-11e6-9241-cad6bd1dab31.png)

**Comment by moritzbabl** [comment]
In rework by @lalomarlin (as visible on slack)

**Comment by moritzbabl** [comment]
added (sadly, only MMMX and not the 50 Swiss airport this issue was created for once upon a time)

**Comment by dushyants19** [comment]
![image](https://user-images.githubusercontent.com/13567007/34079207-d8118688-e34e-11e7-9757-b71955ad88bc.png)
![image](https://user-images.githubusercontent.com/13567007/34079208-dc28c2fe-e34e-11e7-9884-e239895d307f.png)

0825b31

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/67320129-2d39e300-f4e4-11e9-92fd-af8b1c29971d.jpg)
