### ISSUE TITLE
ZLLL-Lanzhou Zhongchuan Int'l Airport-LANZHOU-CHINA

### ISSUE THREAD

**Issue by zacky89315** [InfiniteFlightAirportEditing/Airports#5333]
# Airport Name

< Lanzhou Zhongchuan International Airport >

# Country?

< China >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< 10000ft+ Runway >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/95520529-1ad2e680-098d-11eb-9c07-9b00fe5a8534.png)
