### ISSUE TITLE
SDED-Ipeuna Edra Aeronautica Airport-SAO PAULO-BRAZIL

### ISSUE THREAD

**Issue by victormw22** [InfiniteFlightAirportEditing/Airports#5339]
# Airport Name

< Ipeuna Edra Aeronautica >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/93649123-f9578e00-f9d0-11ea-91b2-039b9c522867.png)
