### ISSUE TITLE
LOWI-Innsbruck Airport-TIROL-AUSTRIA

### ISSUE THREAD

**Issue by IceBlue02** [InfiniteFlightAirportEditing/Airports#534]
Innsbruck, Austria.

Redoing.

**Comment by IceBlue02** [comment]
Just realized I've had this on redone since May without actually doing it...

Starting properly now.

**Comment by IceBlue02** [comment]
Done (finally). Commit https://github.com/InfiniteFlightAirportEditing/Airports/commit/8059bcc4cb88b1a727c1f0c9c274cf3d144c56ba

NAV issue made.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18218661/f094cda2-7129-11e6-9998-45047dd87578.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/58920755-fe27fe00-8709-11e9-8af6-de58c7265214.jpg)
