### ISSUE TITLE
LRTR-Timișoara Traian Vuia International Airpor-TIMIS-ROMANIA

### ISSUE THREAD

**Issue by jack5101** [InfiniteFlightAirportEditing/Airports#5342]
# Airport Name

Timișoara Traian Vuia International Airport

# Country?

Romania

# Improvements that need to be made?

Full redo from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

10000ft+ Runway - 11/29 @ 11483 ft

**Comment by MajorTomMueller** [comment]
https://www.aisro.ro/aip/2020-08-13/DOCS/AIP/AD/AD2/AD_2_16_LRTR/LR_AD_2_LRTR_16-20_en.pdf

https://www.aisro.ro/aip/2020-08-13/DOCS/AIP/AD/AD2/AD_2_16_LRTR/LR_AD_2_LRTR_16-22_en.pdf

**Comment by liamkirky** [comment]
Still doing?

**Comment by MajorTomMueller** [comment]
@jack5101 its up to you to answere the quastion

**Comment by jack5101** [comment]
Terribly sorry guys, not doing it now, have unassigned myself so someone else can get going 🙂

**Comment by urAverageMangoflyer** [comment]
I wouldn't mind doing this if possible?

**Comment by urAverageMangoflyer** [comment]
I would have to pull out of this for now as I want to start with a much smaller airport to learn on rather than trying to do an airport this big already. Hope you understand

**Comment by MajorTomMueller** [comment]
another one gave up

**Comment by ECoops-123** [comment]
![Full](https://user-images.githubusercontent.com/59462519/112242829-7693e200-8c44-11eb-9d57-9c6ac11266df.png)
