### ISSUE TITLE
VOJV-Jindal Vijaynagar Airport-KARNATAKA-INDIA

### ISSUE THREAD

**Issue by hari-shreyas** [InfiniteFlightAirportEditing/Airports#5345]
# Airport Name

Jindal Vijaynagar Airport (VOJV)

# Country?

India

# Improvements that need to be made?

Full re-work

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/93826622-433cb000-fc2d-11ea-8e2f-3dfea39f04cb.png)
