### ISSUE TITLE
YMAY-Albury Airport-NEW SOUTH WALES-AUSTRALIA

### ISSUE THREAD

**Issue by edwardtremethick** [InfiniteFlightAirportEditing/Airports#5347]
# Airport Name

Albury Airport

# Country?

Australia

# Improvements that need to be made?

New gate and taxiways

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/100955858-f141c180-34dc-11eb-943c-d217bb6eea9c.png)
