### ISSUE TITLE
ENLK-Leknes Airport-Nordland-NORWAY

### ISSUE THREAD

**Issue by JensSeverin** [InfiniteFlightAirportEditing/Airports#5348]
# Airport Name

Leknes Airport

# Country?

Norway

# Improvements that need to be made?

Full redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104523332-3a009600-55c4-11eb-8a77-250ff02b4c9b.png)
