### ISSUE TITLE
RPUH-San Jose Airport-Mimaropa-PHILIPPINES

### ISSUE THREAD

**Issue by LesterXavier** [InfiniteFlightAirportEditing/Airports#5349]
# Airport Name

< San Jose >

# Country?

< Philippines >

# Improvements that need to be made?

< Rework from scratch (: >

# Are you working on this airport?

< Yes  >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![Uploading image.png…]()
