### ISSUE TITLE
OEJN-King Abdulaziz International Airport-MAKKAH-SAUDI ARABIA

### ISSUE THREAD

**Issue by IFFG-Nico** [InfiniteFlightAirportEditing/Airports#535]

**Comment by IFAEpat** [comment]
As well as this

**Comment by IFAEpat** [comment]
South Main Terminal unfinished in WEDbing (1.0.2), need a SAS user

**Comment by dushyants19** [comment]
@IFAEpat upload the apt and put it as a suggestion

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21333915/febcb158-c618-11e6-8d14-ab51ca8beff7.png)

**Comment by dushyants19** [comment]
Main taxiways (abc, xyz) were removed. Might not look nice in Infinite Flight. Minor issue.

**Comment by brunocr98** [comment]
I'll fix it.

**Comment by dushyants19** [comment]
Requires lines/gates of newest terminal

https://www.rocketroute.com/airports/asia-as/saudiarabia-sa/plates-jeddahkingabdulazizintl-oejn.html

https://community.infinite-flight.com/t/oejn-missing-section-of-airport/258812?u=dush19

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56086645-ed04f400-5e20-11e9-9602-29e0c245863f.png)

**Comment by MajorTomMueller** [comment]
@MBeringuy, @OscarConklin ask to get assigned to this one to add missing things.

**Comment by OscarConklin** [comment]
Sent for OR!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/93399073-67ba1600-f842-11ea-804a-c80151d80765.png)
