### ISSUE TITLE
LRCK-Constanta International Airport-Constanta-ROMANIA

### ISSUE THREAD

**Issue by jack5101** [InfiniteFlightAirportEditing/Airports#5350]
# Airport Name

Constanța Mihail Kogălniceanu International Airport

# Country?

Romania

# Improvements that need to be made?

Full rework from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

GP2 10000 ft+ runway - 18/36 @ 11483 ft

**Comment by AleksanderIF** [comment]
I'll take it

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124388760-e2590280-dca9-11eb-9e26-52e26759a055.png)
