### ISSUE TITLE
VA53-Gondur Airport Dhule-Maharashtra-India

### ISSUE THREAD

**Issue by KaalicharanDH** [InfiniteFlightAirportEditing/Airports#5351]
# Airport Name

Gondur Airport

# Country?

India

# Improvements that need to be made?

Full rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/94371386-ce012d00-00bb-11eb-90c8-59c59850a132.png)
