### ISSUE TITLE
EIWT-Weston Airport-KILDARE-IRELAND

### ISSUE THREAD

**Issue by benmurtagh2003** [InfiniteFlightAirportEditing/Airports#5357]
# Airport Name

< Weston Airport >

# Country?

< Ireland >

# Improvements that need to be made?

< full rework >

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< low priority >

**Comment by ECoops-123** [comment]
Hi there, how is the progress of this airport? 

No response within the next 7 days and I shall take over.

**Comment by ECoops-123** [comment]
![Full](https://user-images.githubusercontent.com/59462519/113955780-4d627c80-9814-11eb-8f70-bfb2f1aab7ac.png)
