### ISSUE TITLE
LOWW-Wien-Schwechat Airport-NIEDEROSTERREICH-AUSTRIA

### ISSUE THREAD

**Issue by IFFG-Nico** [InfiniteFlightAirportEditing/Airports#536]
Vienna International Airport

Im doing this

**Comment by IFFG-Nico** [comment]
Starting working now :)

**Comment by IceBlue02** [comment]
@IFFG-Nico still working on this?

**Comment by IFFG-Nico** [comment]
No i quit

Am 03.09.2016 13:20 schrieb "Ewan Massey" <notifications@github.com>:

**Comment by dushyants19** [comment]
Ice, wanna do this

**Comment by IceBlue02** [comment]
@dushyants19 damn, yeah I'll take it

**Comment by dushyants19** [comment]
@IceBlue02 are you doing this

**Comment by moritzbabl** [comment]
I would do it, if not

**Comment by IceBlue02** [comment]
Slow and steady wins the race...

This should be done in the next week or so

**Comment by IceBlue02** [comment]
All done (finally) https://github.com/InfiniteFlightAirportEditing/Airports/commit/4314ff8f6e06ec29420373e41c6f42b8dbee7873

@kilt46

**Comment by kilt46** [comment]
![Uploading image.png…]()

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22045522/6beac0d4-dce0-11e6-95fc-129288d035fc.png)

**Comment by IceBlue02** [comment]
Resolved with a few other fixes. Sorry @kilt46

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22088916/279097a6-ddad-11e6-80f6-8dd7ea973bf6.png)

**Comment by bavAVIA** [comment]
Runway Holds missing for taxiways A1 and A2.

**Comment by IceBlue02** [comment]
Fixed with a boundary tweak. Thanks for report @bavAVIA 
https://github.com/InfiniteFlightAirportEditing/Airports/commit/abd33d5ce091c41193ab3b33434fd96de4892bd7

**Comment by kilt46** [comment]
2 holds added at A1 and A2

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50042885-1c9d1e80-0030-11e9-9806-c034b296c2aa.png)
renamed spawns and removed buildings

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/71676681-939e7580-2d5f-11ea-8e03-70c19dc7f9b8.jpg)

**Comment by brunocr1050** [comment]
Will be adding new apron.

<img width="443" alt="Capture" src="https://user-images.githubusercontent.com/76137019/104093955-86aa4100-5253-11eb-8644-9e3c9a0b519b.PNG">

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104123360-71471c80-5310-11eb-97a3-cfa49a3aaac1.png)
