### ISSUE TITLE
NFTP-Niuatoputapu Airport-NIUATOPUTAPU-TONGA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#5360]
# Airport Name

Niuatoputapu

# Country?

Tonga

# Improvements that need to be made?

Will be redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/94204908-c6f1d900-fe87-11ea-8ab8-d48175f3a13a.png)
