### ISSUE TITLE
Duplicate 

### ISSUE THREAD

**Issue by LesterXavier** [InfiniteFlightAirportEditing/Airports#5361]
# Airport Name

< Bacolod-Silay Airport >

# Country?

< Philippines >

# Improvements that need to be made?

< Rework from scratch (: >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by MajorTomMueller** [comment]
#1047
