### ISSUE TITLE
RPUQ-Vigan Airport-Ilocos Region-PHILIPPINES

### ISSUE THREAD

**Issue by LesterXavier** [InfiniteFlightAirportEditing/Airports#5363]
# Airport Name

< Mindoro Airport >

# Country?

< Philippines >

# Improvements that need to be made?

< Full rework (: >

# Are you working on this airport?

< Ye >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/94746583-a8d22000-0342-11eb-87f8-36ff5843413f.png)
