### ISSUE TITLE
HKNW-Wilson Nairobi Airport-KENYA

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#5365]
# Airport Name

Wilson Nairobi

# Country?

Kenia

# Improvements that need to be made?

scratch

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by MajorTomMueller** [comment]
![HKNW-git](https://user-images.githubusercontent.com/26853210/93209534-c94c8880-f74d-11ea-8cc0-f5a513099427.png)

**Comment by KQA03** [comment]
Hi Tom, this is looking really good. Let me know if I can be of assistance. Martin

**Comment by MajorTomMueller** [comment]
thnaks for the offer, but as you can see by the picture it is finished.
