### ISSUE TITLE
SBBU-Bauru Airport-SAO PAULO-BRAZIL

### ISSUE THREAD

**Issue by victormw22** [InfiniteFlightAirportEditing/Airports#5366]
# Airport Name

< Bauru >

# Country?

< Brazil >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/94493603-a9d44780-01b2-11eb-972d-cd0761aa0865.png)
