### ISSUE TITLE
UWKE-Nizhnekamsk Begishevo Airport-TATARSTAN-RUSSIA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#5367]
# Airport Name

Nizhnekamsk Begishevo Airport

# Country?

Russia

# Improvements that need to be made?

Redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101842913-b1975d00-3b0e-11eb-8de6-54e0b3b531a0.png)
