### ISSUE TITLE
LFCC-Cahors Lalbenque-OCCITANIE-FRANCE

### ISSUE THREAD

**Issue by AeroTrapp** [InfiniteFlightAirportEditing/Airports#5368]
# Airport Name

Cahors Lalbenque 

# Country?

France

# Improvements that need to be made?

Redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/96792018-2972c200-13bf-11eb-86be-a9215eb3d505.png)
