### ISSUE TITLE
LIML-Milan–Linate Airport-LOMBARDY-ITALY

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Airports#537]
Working on this one currently.

**Comment by kilt46** [comment]
Airport badly misaligned
![image](https://cloud.githubusercontent.com/assets/14023167/15270404/adfec4da-19e4-11e6-9355-a3564e7adfdf.png)

**Comment by samuelandersson** [comment]
@kilt46 when I created this airport from scratch I aligned it exactly accordingly to WEDbing. 

What more would you like me to do?

**Comment by NickArt1342** [comment]
@samuelandersson open it in wed and download the sat images from wedbing again (it is possible at the beginning when everything is selected in the airport that you move the sat images per accident). Check if it's misalligned with your version and allign it. (select whole airport top right in the menu and use the square tool to move it while still being in same shape.

**Comment by samuelandersson** [comment]
[Commit for realignment](https://github.com/InfiniteFlightAirportEditing/Airports/commit/d053c3916e720af9e3fbe5d7e06f86709b3c4fbf)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20251569/cdcc87ee-a9df-11e6-9ab0-0fb21ba37961.png)
