### ISSUE TITLE
WBKW-Tawau Airport-SABAH-MALAYSIA

### ISSUE THREAD

**Issue by vinoalviano1994** [InfiniteFlightAirportEditing/Airports#5370]
# Airport Name

< Tawau Airport >

# Country?

< Malaysia >

# Improvements that need to be made?

< Full Redo >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103102243-c54bc480-45e0-11eb-9c05-710808d752c1.png)
