### ISSUE TITLE
VERC-Ranchi Airport-Jharkhand-India

### ISSUE THREAD

**Issue by KaalicharanDH** [InfiniteFlightAirportEditing/Airports#5371]
# Airport Name

Ranchi Airport

# Country?

India

# Improvements that need to be made?

Full Rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/94626903-b5427400-0281-11eb-85ac-b29a672a0a3f.png)
