### ISSUE TITLE
OERB-Rabigh Airport-MAKKAH-SAUDI ARABIA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5372]
# Airport Name

Rabigh Airport

# Country?

Saudi Arabia

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/93398625-8bc92780-f841-11ea-83a6-c3676c854e0e.png)
