### ISSUE TITLE
Duplicate 

### ISSUE THREAD

**Issue by VR-206Sqn** [InfiniteFlightAirportEditing/Airports#5373]
# Airport Name

< EGDM - MOD Boscombe Down >

# Country

 < United Kingdom >
# Improvements that need to be made?

< Alteration made to ETPS Ramp 28 - to accommodate C-130J like RL >

# Are you working on this airport?

< Not currently, however happy too (new to the team) >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< TBC >

**Comment by VR-206Sqn** [comment]
![5563A38C-15A5-4A39-A23E-F42F18F9FCD8](https://user-images.githubusercontent.com/65855677/93399742-19266f00-f876-11ea-84c2-3254d5913450.jpeg)

**Comment by MajorTomMueller** [comment]
#388
