### ISSUE TITLE
Duplicate

### ISSUE THREAD

**Issue by VR-206Sqn** [InfiniteFlightAirportEditing/Airports#5374]
# Airport Name

< EGQL - RAF Leuchars >

# Country?

< United Kingdom >

# Improvements that need to be made?

< MIL ALPHA RAMP edited to accommodate C-130J's >

# Are you working on this airport?

< TBC >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< High, to enable GAF-EAF to conduct Exercise Chameleon >

**Comment by VR-206Sqn** [comment]
![10C09EC0-0976-4E7B-BBBC-00C5BD10B281](https://user-images.githubusercontent.com/65855677/93399832-3d824b80-f876-11ea-86ae-10a6f12d17c2.jpeg)
![1E45542D-83F2-499F-94DE-ED0117B0D0DB](https://user-images.githubusercontent.com/65855677/93399838-3fe4a580-f876-11ea-9ab2-2d4bd137367e.jpeg)
![22C6D0E5-78BC-4ADE-A906-E5F3C2BD77AC](https://user-images.githubusercontent.com/65855677/93399840-4115d280-f876-11ea-9c9a-203c55dd8b84.jpeg)

**Comment by MajorTomMueller** [comment]
#1248
