### ISSUE TITLE
NFTV - Vava’u International Airport - VAVA'U - TONGA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#5375]
# Airport Name

Vava’u International Airport

# Country?

Tonga

# Improvements that need to be made?

Will be redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/94493154-7e049200-01b1-11eb-8775-bc3e9458c44b.png)
