### ISSUE TITLE
72F-Throckmorton Airport-TEXAS-USA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5376]
# Airport Name

Throckmorton Municipal Airport

# Country?

USA

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

No

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/93647055-1ab67b00-f9cd-11ea-98e6-16293a264ec2.png)
