### ISSUE TITLE
T51-Dan Jones Intl-TEXAS-USA

### ISSUE THREAD

**Issue by 2000rpm** [InfiniteFlightAirportEditing/Airports#5377]
# Airport Name

< Dan Jones Intl >

# Country?

< USA >

# Improvements that need to be made?

< Redo >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/95213022-f4a61e80-07b3-11eb-8b0a-8c607182863c.png)
