### ISSUE TITLE
54T-R W J Airpark-TEXAS-USA

### ISSUE THREAD

**Issue by 2000rpm** [InfiniteFlightAirportEditing/Airports#5378]
# Airport Name

< R W J Airpark >

# Country?

< USA >

# Improvements that need to be made?

< Redo >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/95633972-774a0a80-0a4e-11eb-92e8-6442c9a6280e.png)
