### ISSUE TITLE
KIWS-West Houston-TEXAS-USA

### ISSUE THREAD

**Issue by 2000rpm** [InfiniteFlightAirportEditing/Airports#5379]
# Airport Name

< West Houston >

# Country?

< USA >

# Improvements that need to be made?

< Redo >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/95212425-4dc18280-07b3-11eb-88d4-f7873d4ad747.png)
