### ISSUE TITLE
DUPLICATE

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#5380]
# Airport Name

Pohnpei International Airport

# Country?

Micronesia

# Improvements that need to be made?

Will be redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MajorTomMueller** [comment]
#1711

**Comment by kilt46** [comment]
![Uploading image.png…]()
