### ISSUE TITLE
RPVV-Busuanga/Francisco B Reyes Airport-PALAWAN-PHILIPPINES

### ISSUE THREAD

**Issue by jaypzs** [InfiniteFlightAirportEditing/Airports#5381]
# Airport Name

< RPVV - Busuanga/Francisco B Reyes Airport >

# Country?

< PHILIPPINES >

# Improvements that need to be made?

< Update Ramp with Gates >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/95211153-d50df680-07b1-11eb-9b52-0a5e30d8602a.png)
