### ISSUE TITLE
INVALID

### ISSUE THREAD

**Issue by Berlin-N** [InfiniteFlightAirportEditing/Airports#5382]
# Airport Name

< Beijing Nanjiao Airbase >

# Country?

< China >

# Improvements that need to be made?

< New >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< 10000ft+ Runway>

**Comment by MajorTomMueller** [comment]
Source for ICAO assignment missing, by name “Beijing Nanjiao” it must be the airbase west of ZBAD.

**Comment by Berlin-N** [comment]
Snet to OR

**Comment by MajorTomMueller** [comment]
There is still no evidence for the ICAO code. Source citation is needed before this could be added.

**Comment by MajorTomMueller** [comment]
@RyanEpps @moritzbabl @MBeringuy
