### ISSUE TITLE
Duplicate 

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#5385]
# Airport Name
George Airport
# Country?
South Africa
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
No, going to start
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by liamkirky** [comment]
Duplicate #4479 

We don’t take requests too. Join the team and edit airports!

**Comment by GBKarp** [comment]
Sorry, will edit it, I am in the team

**Comment by MajorTomMueller** [comment]
As @liamkirky posted, already been worked on by @casp959er73 in #4479
