### ISSUE TITLE
SNOU-Novo Aerodromo De Feijo-ACRE-BRAZIL

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#5386]
# Airport Name
Novo Aerodromo De Feijo
# Country?
Brazil
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by GBKarp** [comment]
Sent to PR!

**Comment by GBKarp** [comment]
Sent to OR!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/95920324-d7a1ba80-0d74-11eb-9018-c8924d0099e8.png)
