### ISSUE TITLE
PAYA-Yakutat-ALASKA-USA

### ISSUE THREAD

**Issue by zhf21** [InfiniteFlightAirportEditing/Airports#5387]
# Airport Name

Yakutat

# Country?

United States of America

# Improvements that need to be made?

Full Redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by zhf21** [comment]
Airport just submitted for PR!

**Comment by zhf21** [comment]
Sent to OR!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/96662211-739e6980-1313-11eb-9993-71feed9e7114.png)
