### ISSUE TITLE
UEBB-Batagay Airport-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#5388]
# Airport Name

< Batagay Airport >

# Country?

< Russia >

# Improvements that need to be made?

< redo >

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< low >

**Comment by kilt46** [comment]
This airport should have at least 1 gate!

![image](https://user-images.githubusercontent.com/14023167/95519523-de9e8680-098a-11eb-8865-946990f8d794.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/95519795-78feca00-098b-11eb-9771-7293a81a806e.png)
