### ISSUE TITLE
LFBO-Toulouse Blagnac Airport-MIDI-PYRENEES-FRANCE

### ISSUE THREAD

**Issue by TristinWoolf** [InfiniteFlightAirportEditing/Airports#539]
Toulouse-Blagnac Airport

**Comment by moritzbabl** [comment]
Just opened it in WED, will probably need a complete rework, I will do it in a few days

**Comment by TristinWoolf** [comment]
@IceBlue02 Why is @bylrret assigned? I thought that @moritzbabl was gonna do it?

**Comment by IceBlue02** [comment]
@TristinWoolf good spot sorry

**Comment by moritzbabl** [comment]
Sent for approval

**Comment by AxelBeder** [comment]
Added to repro.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20031675/3e712e0c-a349-11e6-8236-dcf190f681fa.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54087176-6ee39800-431e-11e9-974d-6a60c9eb3e76.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55288873-be4c3f80-5383-11e9-8ef5-6f21924d5f1c.png)

**Comment by Czechoslovaki** [comment]
@Jeremy351 will redo this airport.

- Surface errors in some places
- Missing markings
- Missing line types
- Missing hangars
- Ramp configurations to be updated
- Remove unnecessary pavement near the pax terminals
- Addition of more detailed taxi lines (stop bars at gates)
