### ISSUE TITLE
ZMCK-New Ulaanbaatar International Airport-ULAANBAATAR-MONGOLIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#5390]
# Airport Name

New Ulaanbaatar International Airport

# Country?

Mongolia

# Improvements that need to be made?

New airport

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

World Capital, 10k+

**Comment by MajorTomMueller** [comment]
https://ais.mn/files/aip/eAIP/2020-06-18-AIRAC/html/eAIP/ZM-AD-2.ZMCK-en-MN.html
nice find

**Comment by OscarConklin** [comment]
Sent for OR

**Comment by kilt46** [comment]
![Uploading image.png…]()
