### ISSUE TITLE
WBKS-Sandakan Airport-Sabah-MALAYSIA

### ISSUE THREAD

**Issue by LordWizrak** [InfiniteFlightAirportEditing/Airports#5391]
# Airport Name

Sandakan Airport

# Country?

Malaysia

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by LordWizrak** [comment]
First airport being worked on.

**Comment by kilt46** [comment]
![Uploading image.png…]()
