### ISSUE TITLE
SCBQ-El Bosque Airport-REGION METROPOLITANA DE SANTIAGO-CHILE

### ISSUE THREAD

**Issue by SpeedbirdCL** [InfiniteFlightAirportEditing/Airports#5392]
# Airport Name

Aerodromo El Bosque

# Country?

Chile

# Improvements that need to be made?

Add parking and taxiways

# Are you working on this airport?

Yes

**Comment by MajorTomMueller** [comment]
![SCBQ-git](https://user-images.githubusercontent.com/26853210/135267111-06b34e05-999b-422d-9a98-24cd8174f367.png)
