### ISSUE TITLE
SCCI - Carlos Ibañez del Campo Airport, Punta Arenas, Chile

### ISSUE THREAD

**Issue by SpeedbirdCL** [InfiniteFlightAirportEditing/Airports#5395]
# Airport Name

Presidente Carlos Ibañez del Campo International Airport

# Country?

Chile

# Improvements that need to be made?

Add and modify ramps

# Are you working on this airport?

Yes

**Comment by kilt46** [comment]
See https://github.com/InfiniteFlightAirportEditing/Airports/issues/624

**Comment by SpeedbirdCL** [comment]
> See #624

But it has missing ramps, and I found an error in a part of runway 30.

**Comment by Czechoslovaki** [comment]
@SpeedbirdCL you can ask to be assigned to the existing issue...no need to create a new one

**Comment by SpeedbirdCL** [comment]
> @SpeedbirdCL you can ask to be assigned to the existing issue...no need to create a new one

Oh ok, ty! Im new here so im still learning
