### ISSUE TITLE
LRSM - Satu Mare Airport - ROMANIA

### ISSUE THREAD

**Issue by igor-m01** [InfiniteFlightAirportEditing/Airports#5399]
# Airport Name

Satu Mare Airport

# Country?

Romania

# Improvements that need to be made?

Redo from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by ECoops-123** [comment]
I'll be taking over this (with permission from Igor)

**Comment by ECoops-123** [comment]
![Full](https://user-images.githubusercontent.com/59462519/111920734-8961b780-8a88-11eb-8062-a3f16786c766.png)
