### ISSUE TITLE
EGKK-Gatwick Airport-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#54]
Nik - Jonathan - fight over this one. Jonathan has my support for this now :)

**Comment by carmichaelalonso** [comment]
@Nik-Barbour you two are sharing

**Comment by carmichaelalonso** [comment]
Marking as high priority for Scott!

**Comment by Nik-Barbour** [comment]
Don't have the screen res for this one unfortunately.

**Comment by carmichaelalonso** [comment]
Mostly redone, could do with some optimisations but I'm happy with it for now.

**Comment by Swang007** [comment]
Will add ATIS frequency

**Comment by Swang007** [comment]
Will add ATIS frequency

**Comment by kilt46** [comment]
Looks slightly off: I can redo at a later stage. Renaming Gates for consistency
![image](https://cloud.githubusercontent.com/assets/14023167/10268398/f725ff06-6a7c-11e5-8f87-fec893e8cfdc.png)

**Comment by kilt46** [comment]
E-mailed temporary renumbering of gates. Will do for not for update.

**Comment by kilt46** [comment]
Working this one (gates and jetbridges)

**Comment by kilt46** [comment]
Redone

**Comment by kilt46** [comment]
Runway realigned
![image](https://cloud.githubusercontent.com/assets/14023167/11261261/5f8d7e8c-8e38-11e5-9859-790c330c3909.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/11261274/814a1314-8e38-11e5-8005-a34997ca62a9.png)
Runway realigned, lines cleaned

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17253387/349714ee-5576-11e6-89a7-5bf4bbd3a416.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17253396/3b48332c-5576-11e6-8dc9-80235e4bd6c7.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18250513/7305928c-7349-11e6-8f16-39a2a2f600d5.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18250520/7eb05b12-7349-11e6-9673-a698d7c4deda.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18250546/9e1bf10a-7349-11e6-98a0-44d565919171.png)

**Comment by Will171** [comment]
The airport needs some fixes to some hold positions and additions to stands.. will be happy to have a look

**Comment by Will171** [comment]
i will be adding some asphalt taxiways as well 
![screenshot_69](https://cloud.githubusercontent.com/assets/16463484/24261784/ffb554c2-0fef-11e7-8679-e245593a85b0.png)

**Comment by ItsW1ll** [comment]
New google earth imagery avaliable.. Will look at doing a redo

**Comment by liamkirky** [comment]
Are you still doing this? If not could I take it please?

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/73790066-a3eea980-477e-11ea-8453-602eddf37cfa.jpg)
