### ISSUE TITLE
EDHI-Hamburg Finkenwerder-GERMANY

### ISSUE THREAD

**Issue by IFFG-Nico** [InfiniteFlightAirportEditing/Airports#540]
Hamburg Finkenwerder

**Comment by PaulNielsen** [comment]
@IFFG-Nico Anything? ... It's September and still nothing.. 😒

**Comment by PaulNielsen** [comment]
@IFFG-Nico If you're not doing it, I would like to do it. :)

**Comment by IFFG-Nico** [comment]
Do it i stopped

Am 10.09.2016 23:58 schrieb "PaulNielsen" <notifications@github.com>:

**Comment by PaulNielsen** [comment]
Ok thanks.

**Comment by PaulNielsen** [comment]
Sent in for approval.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18494618/d8ca5816-79dc-11e6-8432-1ca126d3bae6.png)
