### ISSUE TITLE
HEAL-Al Alamain Airport-MARSA MATRUH-EGYPT

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#5407]
# Airport Name

Al Alamain Airport

# Country?

Egypt

# Improvements that need to be made?

Redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![Uploading image.png…]()

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/99468544-72f2f600-2906-11eb-81a6-ce7c94bd2d2e.png)
