### ISSUE TITLE
RPMC-Cotabato Airport-MAGUINDANAO-PHILIPPINES

### ISSUE THREAD

**Issue by LesterXavier** [InfiniteFlightAirportEditing/Airports#5408]
# Airport Name

< Cotabato Airport >

# Country?

< Philippines >

# Improvements that need to be made?

< rework from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/97239241-1db93e00-17b9-11eb-96d7-18f1b7890c88.png)
