### ISSUE TITLE
RPLH-Cagayan North Int'l Airport-CAGAYAN-PHILIPPINES

### ISSUE THREAD

**Issue by LesterXavier** [InfiniteFlightAirportEditing/Airports#5409]
# Airport Name

< Cagayan North International Airport >

# Country?

< Philippines >

# Improvements that need to be made?

< New Airport >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/97238875-67555900-17b8-11eb-8337-273fb3b741c7.png)
