### ISSUE TITLE
KMGW-Morgantown Municipal Airport-WEST VIRGINIA-USA

### ISSUE THREAD

**Issue by henrikbg** [InfiniteFlightAirportEditing/Airports#541]
For @ItsPerses.

**Comment by dushyants19** [comment]
Hen are you doing this

**Comment by henrikbg** [comment]
No. ItPerses was going to do it. I just created the issue for him.

**Comment by dushyants19** [comment]
He was kicked out. Up for grabs

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26286379/eda1b9ca-3e29-11e7-8952-ed3ecab298b0.png)
