### ISSUE TITLE
VIGG-Kangra Airport-Himachal Pradesh-India

### ISSUE THREAD

**Issue by KaalicharanDH** [InfiniteFlightAirportEditing/Airports#5410]
# Airport Name

Kangra Airport

# Country?

India

# Improvements that need to be made?

Full rework

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/95676844-c1cea280-0b86-11eb-893d-43354bd7dfc5.png)
