### ISSUE TITLE
PAKL-Kulik Lake-ALASKA-USA

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#5413]
# Airport Name

Kulik Lake

# Country?

USA

# Improvements that need to be made?

Moved runway and added basic features

# Are you working on this airport?

Done

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Extremely low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/94624889-161b7d80-027d-11eb-8b72-490fa53c3f24.png)
