### ISSUE TITLE
VAUD-Udaipur Airport-Rajasthan-India

### ISSUE THREAD

**Issue by KaalicharanDH** [InfiniteFlightAirportEditing/Airports#5414]
# Airport Name

Udaipur Airport

# Country?

India

# Improvements that need to be made?

Full rework

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![Uploading image.png…]()

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/99975486-ea41e300-2d67-11eb-9280-99eafff61830.png)
