### ISSUE TITLE
RJOO-Osaka Airport-HYOGO-JAPAN

### ISSUE THREAD

**Issue by moiz20012** [InfiniteFlightAirportEditing/Airports#542]
AbuDhabi

**Comment by samuelandersson** [comment]
Are you doing this @moiz20012?

**Comment by kilt46** [comment]
This is done!

**Comment by IFAEpat** [comment]
So is this up for grabs or not? If it is, I'll take it :)

**Comment by IFAEpat** [comment]
Can someone assign me? thanks :D

**Comment by IFAEpat** [comment]
sent for reviewal

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17244607/5c46bc02-5548-11e6-93d5-86d21d21ca87.png)

**Comment by IFAEpat** [comment]
Gating

**Comment by IFAEpat** [comment]
Gated

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17576591/ecfa9ebc-5f39-11e6-9549-68cba71e18c0.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17576595/fb83d85e-5f39-11e6-9219-8c8032b01f2b.png)

**Comment by orangejuicie** [comment]
Rename duplicate spawn name.
Adjust to new manners.

**Comment by kztmtn** [comment]
Fix holdline.
