### ISSUE TITLE
ZABD-Beijing Badaling Airport-Beijing-China

### ISSUE THREAD

**Issue by IFJD-471** [InfiniteFlightAirportEditing/Airports#5420]
# Airport 
Beijing Badaling Airport
# Country?
China
# Improvements that need to be made?
New
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by MajorTomMueller** [comment]
@IFJD-471 
Source of ICAO code and Airport name needed. No evidence, not even a single hint on this one in my search.

**Comment by IFJD-471** [comment]
Hello!
I’ve just seen you said ‘Source of ICAO code and Airport name needed. No evidence, not even a single hint on this one in my search.’ on GitHub. The reason that you have no evidence to this ICAO because in China, most of the General Aviation Airport have NO ICAO CODES! So we used ZA as General Aviation Airport in China and BD as the name of the airport witch is Badaling Airport.

**Comment by MajorTomMueller** [comment]
No evidence that this airfield exists. No evidence of valid ICAO.

**Comment by brennanhackard** [comment]
![image](https://user-images.githubusercontent.com/52306285/94767513-ca92cd80-0369-11eb-9593-bf231ea5ac0e.jpeg)

This airport does in fact exist, and judging by the fact planes are on the apron, cars are in the parking lot, and airport infrastructure appearing to be in decent shape it is most likely active.

**Comment by MajorTomMueller** [comment]
Where in that image is the name of the airport written? And the ICAO code? I can not see it.
Sorry for the sarcasm, but there are tons of airfields airstrips airports airbases that where used more or less. The basic rule was that it needs a ICAO or at least a LID to make it into our database.
Personally I already have a bunch of airstrips that I would have add without that rule.
Pretty sure that there is a bunch of GA airfields in China, but as long as we have no source of information about them we couldn't add them. Same goes for a bunch of Airbases, for some of the, I know the ICAO, but I have no source that I could citate so I couldn't add them.
If one in China has access to a source of GA airfield ICAO codes that he could link visible to the rest of the world that would be a major step forward.
