### ISSUE TITLE
VCRI-Mattala Rajapaksa Hambantota Airport-Mattala-Sri Lanka

### ISSUE THREAD

**Issue by hari-shreyas** [InfiniteFlightAirportEditing/Airports#5421]
# Airport Name

Mattala Rajapaksa Hambantota Airport-Mattala

# Country?
Sri Lanka
# Improvements that need to be made?

Must be added

# Are you working on this airport?

Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by MajorTomMueller** [comment]
https://www.airport.lk/aasl/AIS/AMDT%20WEB/AIP%20FROM%2030%20JAN%202020/htm/143.htm

**Comment by hari-shreyas** [comment]
Thanks for the aerodrome data :)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/99910053-9674c280-2cb1-11eb-8df4-558c2c44c1c5.png)
