### ISSUE TITLE
C23-Peleliu Airstrip-PELELIU-PALAU

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#5422]
# Airport Name

Peleliu Airstrip

# Country?

Palau

# Improvements that need to be made?

Redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/95924387-1b98bd80-0d7d-11eb-8461-787f43e0a055.png)
