### ISSUE TITLE
KMAF-Midland International Air and Space Port-TEXAS-USA

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#5423]
# Airport Name

Midland International Air and Space Port

# Country?

USA

# Improvements that need to be made?

Redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by jakey20** [comment]
Sent to OR!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102610904-9969a400-40f3-11eb-9a1c-e795d2676e33.png)
