### ISSUE TITLE
RPUZ-Bagabag Airport-NUEVA VIZCAYA-PHILIPPINES

### ISSUE THREAD

**Issue by LesterXavier** [InfiniteFlightAirportEditing/Airports#5426]
# Airport Name

< Bagabag Airport >

# Country?

< Philippines >

# Improvements that need to be made?

< rework from scratch >

# Are you working on this airport?

< Ye >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/97238598-bb137280-17b7-11eb-9b03-7f6b6c3023d6.png)
