### ISSUE TITLE
ESGG

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Airports#543]
Misaligned and some small fixes needed to be fixed. Doing it right now.

**Comment by kilt46** [comment]
This one does not match WEDBing. Also buildings are missing.
![image](https://cloud.githubusercontent.com/assets/14023167/15269683/a79f9ffa-19cc-11e6-9ffe-2da0f3422d64.png)

**Comment by NickArt1342** [comment]
@samuelandersson do want to do it?

**Comment by samuelandersson** [comment]
Quite frankly, I don't see how it can be misaligned. I just imported scenery and added a few things AFAIK.

**Comment by samuelandersson** [comment]
Repositioned/realigned.

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/40485186a114bd886b0d405fae68ffa30ab26c46)

Buildings are yet to go.

**Comment by samuelandersson** [comment]
Adding stands and buildings.

**Comment by samuelandersson** [comment]
See commit for what i have done exactly.

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/4def12d8b2041723f5bb631b0d7671b1df69fa1c)

**Comment by kilt46** [comment]
My fault. close range Satellite made airport seem off
![image](https://cloud.githubusercontent.com/assets/14023167/17005819/01218b42-4ea2-11e6-98bf-167986c2cdf2.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17232659/4489b852-54ef-11e6-9490-1855fc29618e.png)

**Comment by samuelandersson** [comment]
Changed stand properties according to data from an airport employee. 

Also @kilt46 Airest Cargo, TuiFly, Primera Air, Thomas Cookare operating at this airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17540387/4d78b7ca-5e7b-11e6-88c2-08f80926dbe9.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17540390/59b75cd0-5e7b-11e6-9377-e4816356867b.png)

**Comment by samuelandersson** [comment]
Fixed everything more accurately.

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/08f28a25a6ab9128193d4e69897675c32bc72fa7)

**Comment by brennanhackard** [comment]
@JensSeverin will be adding the missing concrete taxiways and fixing inaccurate markings.
