### ISSUE TITLE
R33-Wakonda Beach State-OREGON-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#5431]
# Airport Name

Wakonda Beach State

# Country?

USA

# Improvements that need to be made?

Full Redo

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Lowwww

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/95927178-b2687880-0d83-11eb-9581-d53509a68cd2.png)
