### ISSUE TITLE
EKVG

### ISSUE THREAD

**Issue by Anfinn** [InfiniteFlightAirportEditing/Airports#544]
Needs lots of work, new terminal, longer runway etc. I will be doing this as my first airport edit.

**Comment by Anfinn** [comment]
finished, waiting for approval

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20607013/a7ef9e22-b23a-11e6-85a2-c5da985b173b.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/47964513-e3b96500-e000-11e8-915a-87631fa3e614.png)
