### ISSUE TITLE
OPSD-Skardu-GILGIT BALTISTAN-PAKISTAN

### ISSUE THREAD

**Issue by Fabse1803** [InfiniteFlightAirportEditing/Airports#5441]
Airport Name

skardu

Country?

Pakistan

Improvements that need to be made?

Full Redo

Are you working on this airport?

Yes

Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low , 10000ft+ Runway

**Comment by MajorTomMueller** [comment]
7300ft runway:
https://www.caapakistan.com.pk/eAIP/01-20/eAIP/AD/skardu_data.pdf
https://www.caapakistan.com.pk/eAIP/01-20/eAIP/AD/skardu_chart.pdf

**Comment by Fabse1803** [comment]
I still work at it right now i have to make an break because of exams

**Comment by USMN13** [comment]
I can carry this issue forward and complete the work.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115955970-b35f2d00-a4bf-11eb-8293-8fae7c2a9ebf.png)
