### ISSUE TITLE
KIWD

### ISSUE THREAD

**Issue by TristinWoolf** [InfiniteFlightAirportEditing/Airports#545]
Gogebic-Iron County Airport

**Comment by TristinWoolf** [comment]
Finished a complete redo of this airport, and sent it in. Just awaiting approval! Can someone please put the proper label? Thanks!

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20652248/603ac286-b4bb-11e6-8a7c-da57e8e68d22.png)
