### ISSUE TITLE
HKJK-Nairobi Jkia International Airport-NAIROBI-KENYA

### ISSUE THREAD

**Issue by moiz20012** [InfiniteFlightAirportEditing/Airports#546]
Jomo Kenyatta International Airport

**Comment by moiz20012** [comment]
I want to do this.

**Comment by dushyants19** [comment]
@moiz20012 any progress?

**Comment by moiz20012** [comment]
Yes.I will be submitting it on this coming saturday

**Comment by dushyants19** [comment]
@moiz20012 been 22 days, still no submission

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by IceBlue02** [comment]
Will be doing.

**Comment by IceBlue02** [comment]
Having some imagery issues, so I'll keep this on hold for now.

**Comment by Spinxzl** [comment]
I can take this if that's ok

**Comment by brunocr98** [comment]
@Spinxzl, you have already 3 assigned airports; plus, Ewan has not abandoned the airport.

**Comment by IceBlue02** [comment]
I'm gonna offer this up; current google imagery should do the trick however with my image difficulties on another airport this is gonna be a very long while before I can get this done.

**Comment by Aviationluver** [comment]
I'm taking this one.

**Comment by alchonub** [comment]
Damate

**Comment by alchonub** [comment]
I wanted thi one

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by moritzbabl** [comment]
Added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28236037-0525340a-68e1-11e7-8bc1-0842ec9ae949.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/67620429-24475b00-f7dd-11e9-9033-4db4562b3b08.jpg)
