### ISSUE TITLE
ZSLG-Lianyungang Baitabu Airport-JIANGSU-CIHNA

### ISSUE THREAD

**Issue by IFJD-471** [InfiniteFlightAirportEditing/Airports#5463]
# Airport Name
Lianyungang Baitabu Airport
# Country?
China
# Improvements that need to be made?
NEW
# Are you working on this airport?
YES
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by IFJD-471** [comment]
Hello, MajorTomMueller, I found that when you changed my title, you typed CHINA to CIHNA. I hope you can correct this mistake

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/119242823-cc8ee400-bb26-11eb-84ca-0ef32ec11965.png)
