### ISSUE TITLE
SISY-Piraquara Airport-PARANA-BRAZIL

### ISSUE THREAD

**Issue by victormw22** [InfiniteFlightAirportEditing/Airports#5464]
# Airport Name

< Piraquara >

# Country?

< Brazil >

# Improvements that need to be made?

<  Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/97495350-84636680-1935-11eb-866b-d43e178f79b4.png)
