### ISSUE TITLE
AZ90-Hangar Haciendas Airpark-ARIZONA-USA

### ISSUE THREAD

**Issue by Brody02** [InfiniteFlightAirportEditing/Airports#5466]
# Airport Name

 Hangar Haciendas 

# Country?

 USA 

# Improvements that need to be made?

 The runway is Pavement and not concrete. Parking spots and Hangers need to be added. The airport seems out of place. 

# Are you working on this airport?

 I will Be working on this Airport @Brody02  

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

 Low

**Comment by StickThelanding** [comment]
Can I work on this?

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/132604039-2e920971-c93a-47a2-b500-c46b70fed709.png)
