### ISSUE TITLE
RJAA-Narita International Airport-CHIBA-JAPAN

### ISSUE THREAD

**Issue by moiz20012** [InfiniteFlightAirportEditing/Airports#547]
Jomo Kenyatta International Airport.

**Comment by dushyants19** [comment]
Duplicate, @kilt46

**Comment by IFAEpat** [comment]
Can someone assign me? I accidentally made a duplicate issue. . .

**Comment by UpNorthAviation** [comment]
Narita would be a fun airport to fly to in the new Dreamliner from So-Cal!

**Comment by IFAEpat** [comment]
I'm still working on this one, will be finished soon.

**Comment by IFAEpat** [comment]
Does someone else want to do this? DM me on Slack to get what I've done so far.

**Comment by IFAEpat** [comment]
anyone wanna take this?

**Comment by bylrret** [comment]
I will, why not. haha

**Comment by dushyants19** [comment]
@bylrret hows this going!

**Comment by dushyants19** [comment]
Up for Grabs

cc: @kilt46

**Comment by ErshovlaD** [comment]
Okay, I can make this :)

**Comment by ErshovlaD** [comment]
Send for review..

**Comment by ErshovlaD** [comment]
Why this issue not closed?

**Comment by kilt46** [comment]
I did not see this one on the email list. Did you send it in? Did Dush already reply to you?

**Comment by dushyants19** [comment]
Be patient Vlad, you'll get your roubles.. 

I haven't pushed it so I haven't closed it

**Comment by ErshovlaD** [comment]
Be calm, Dush. I made this airport is completely free.

**Comment by moritzbabl** [comment]
finally added - one A380 airport less

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22357172/0908c22c-e3fc-11e6-88d5-4452bcb428b5.png)

**Comment by orangejuicie** [comment]
Spawn correction.
Adjusted to new manners.

This airport need to fix.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/65000866-ab8ede00-d8c3-11e9-8227-c250c2e32554.jpg)

**Comment by kilt46** [comment]
New taxiway to be added

**Comment by Berlin-N** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90842030-d5e2ea00-e323-11ea-95db-c57549649755.png)
