### ISSUE TITLE
RPVS-Evelio Javier Airport-ANTIQUE-PHILIPPINES

### ISSUE THREAD

**Issue by jaypzs** [InfiniteFlightAirportEditing/Airports#5472]
# Airport Name

Evelio Javier Airport

# Country?

Philippines

# Improvements that need to be made?

To add gates and ramps

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/119228151-44352280-bad7-11eb-9d84-cd37ec0c87d1.png)
