### ISSUE TITLE
KTFP-Mccampbell-Porter-TEXAS-USA

### ISSUE THREAD

**Issue by 2000rpm** [InfiniteFlightAirportEditing/Airports#5474]
# Airport Name

< Mccampbell-Porter >

# Country?

< USA >

# Improvements that need to be made?

< Redone >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/96367349-f86e6500-1112-11eb-822d-7add449ff5e8.png)
