### ISSUE TITLE
SWLB-Aeroporto Regional de Labrea-AMAZONAS-BRAZIL

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#5475]
# Airport Name
Aeroporto Regional de Labrea
# Country?
Brazil
# Improvements that need to be made?
Redone, it was autogenerated on Global
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by GBKarp** [comment]
Sent to OR!

**Comment by GBKarp** [comment]
Got rejected from OR, sent to PR again!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/97495299-757cb400-1935-11eb-8da0-4290ce651f51.png)
