### ISSUE TITLE
OEWJ-Wejh Airport-TABUK-SAUDI ARABIA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5476]
# Airport Name

Wejh Airport

# Country?

Saudi Arabia

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

GP2 (+10k)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/95209480-02f23b80-07b0-11eb-8c60-935e6c65e482.png)
