### ISSUE TITLE
EDKL

### ISSUE THREAD

**Issue by IceBlue02** [InfiniteFlightAirportEditing/Airports#548]
https://community.infinite-flight.com/t/incorrect-runway-numbers-edkl/38875

Will fix and redo; in a bad way.

**Comment by IceBlue02** [comment]
Finished.

**Comment by kilt46** [comment]
File not yet in repository

**Comment by samuelandersson** [comment]
@kilt46 I closed it cause the tracking thread was showing that Henrik made commit to this airport yesterday.
![skarmavbild 2016-05-14 kl 14 05 55](https://cloud.githubusercontent.com/assets/15381853/15268390/136e174c-19dd-11e6-9c82-c157175655c1.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20584694/eb2ee178-b1ba-11e6-90cc-95d24d52f5cc.png)
