### ISSUE TITLE
SMJP, Johan Adolf Pengel Luchthaven, PBM

### ISSUE THREAD

**Issue by sudafly** [InfiniteFlightAirportEditing/Airports#549]
I going to create it. Can somebody assign me?

Thanks!

**Comment by sudafly** [comment]
@dushyants19 It's done! In 5 hours 😅😅!

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20690382/dca58052-b58f-11e6-8e18-b9ea1217eabd.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54883235-c0694800-4e31-11e9-9165-ef3e21db452a.png)
