### ISSUE TITLE
EGSS-London Stansted Airport-ESSEX-UNITED KINGDOM

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#55]

**Comment by taylorcam** [comment]
Yay an airport to myself! Time to get designing!

**Comment by carmichaelalonso** [comment]
Finished by @jpperks, nice job as always :)

**Comment by IF-Airport-Team** [comment]
I would like to do this one.

**Comment by Swang007** [comment]
Will add ATIS frequency

**Comment by kilt46** [comment]
JETBRIDGES REMOVED

**Comment by Will171** [comment]
taxiway lines and start positions need updating.. will redo once finished EGGW

**Comment by dushyants19** [comment]
@45679 please continue here.

**Comment by Will171** [comment]
Sent for review

**Comment by dushyants19** [comment]
42700ac

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24935192/206bd128-1ee6-11e7-9c76-3ae9a711cba7.png)

**Comment by Czechoslovaki** [comment]
New apron + taxiway to be added.
![image](https://user-images.githubusercontent.com/51279558/103447969-712b8a80-4c47-11eb-880f-a03fd1f8131a.png)

**Comment by Czechoslovaki** [comment]
@GBKarp will add the new apron and taxiway.

Note: **Do not attempt to touch anything else outside of the new areas. Any other fixes will result in rejection.**

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104823228-4f690080-580e-11eb-9282-16c29cf4c762.png)
