### ISSUE TITLE
RKSI-Incheon Airport-SEOUL-SOUTH KOREA

### ISSUE THREAD

**Issue by cboisselier** [InfiniteFlightAirportEditing/Airports#550]
To be done

**Comment by J0mpa** [comment]
ill finish it

**Comment by IFAEpat** [comment]
@J0mpa any news? I've tried contacting you on Slack and Discord, are you still doing this???

**Comment by dushyants19** [comment]
up for grabs

**Comment by IFAEpat** [comment]
Taking

**Comment by IFAEpat** [comment]
up for grabs

**Comment by IFAEpat** [comment]
@J0mpa said he'll finish this once he gets back.

**Comment by dushyants19** [comment]
@IFAEpat please add proper labels; thanks

**Comment by sentikum** [comment]
OK

**Comment by sentikum** [comment]
I CAN redo this airport

**Comment by sentikum** [comment]
Sent for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21577881/23e4d48a-cf31-11e6-95ec-becf92e37647.png)

**Comment by JcFl4** [comment]
OMG this airport is amazing! Same as UKBB and many others. Excellent work @sentikum!!

**Comment by dushyants19** [comment]
@adrinerDP is adding terminal 2

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32865096-4bf93c9e-ca27-11e7-9ece-2f1176a6b83c.png)

**Comment by ryu12332** [comment]
Progress?

**Comment by SpaceGuru01** [comment]
What needs doing? I am happy to help.

**Comment by kilt46** [comment]
Needs better satellite imagery

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52915381-006c6680-3299-11e9-85de-2a490ecfd6ee.png)
