### ISSUE TITLE
SDOS-Banaer Airport-SAO PAULO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5501]
# Airport Name

Banaer Airport

# Country?

Brazil

# Improvements that need to be made?

Redone from scratch

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/95518498-c9285d00-0988-11eb-9ff6-6d1922d913a0.png)
