### ISSUE TITLE
KEUG-Mahlon Sweet Field-OREGON-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#5502]
# Airport Name

Mahlon Sweet Field

# Country?

USA

# Improvements that need to be made?

Full Redo From Scratch

# Are you working on this airport?

Idk why I'd say no

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by Czechoslovaki** [comment]
Sent For OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/95926768-adef9000-0d82-11eb-95cb-6c457196a450.png)
