### ISSUE TITLE
UWSG-Saratov/Gagarin-SARATOV-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#5503]
# Airport Name

< Saratov Gagarin Intl Airport >

# Country?

< Russia >

# Improvements that need to be made?

< New airport >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/99976268-dcd92880-2d68-11eb-9579-3a33054e4b8a.png)
