### ISSUE TITLE
ZLYL-Yulin Yuyang Airport-YULIN-CHINA

### ISSUE THREAD

**Issue by zacky89315** [InfiniteFlightAirportEditing/Airports#5505]
# Airport Name

< Yulin Yuyang Airport >

# Country?

< China >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< Yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/96053071-70ebd200-0e44-11eb-9d8f-cedccb4fa0c1.png)
