### ISSUE TITLE
SPHO-C. F. Alfredo Mendivil Duarte Airport-AYACUCHO-PERU

### ISSUE THREAD

**Issue by victormw22** [InfiniteFlightAirportEditing/Airports#5507]
# Airport Name

< C. F. Alfredo Mendivil Duarte Airport >

# Country?

< Peru >

# Improvements that need to be made?

< Redone from scratch >

# Are you working on this airport?

< yes >

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

< low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/97643460-b0561900-1a15-11eb-8053-f53e8ed9d0ce.png)
