### ISSUE TITLE
VELP-Lengpui Airport-Aizawl-Mizoram-India

### ISSUE THREAD

**Issue by KaalicharanDH** [InfiniteFlightAirportEditing/Airports#5509]
# Airport Name

Lengpui Airport

# Country?

India

# Improvements that need to be made?

Full rework

# Are you working on this airport?

yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

low

**Comment by kilt46** [comment]
![Uploading image.png…]()
