### ISSUE TITLE
LFMN-Nice Cote D'Azur Airport-PROVENCE-ALPES-COTE D'AZUR-FRANCE

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#551]

**Comment by samuelandersson** [comment]
Last time I checked Nice Cote d'Azur it looked pretty detailed in the repo. What changes are you making @cboisselier? Just curious.

**Comment by TristinWoolf** [comment]
I guess that this is up for grabs.. :)

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21578458/0b3fcec0-cf46-11e6-9608-199c43fbf242.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34450711-97f1bc6c-ecd6-11e7-9a84-b580c98fb657.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48974026-65098380-f012-11e8-9424-e8e46feb0c31.png)

**Comment by kilt46** [comment]
Duplicate spawn removed.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/64466082-4d554480-d0e6-11e9-921d-034c5dcf64ff.jpg)

**Comment by MajorTomMueller** [comment]
@MBeringuy there a still Duplicate spawns, would you or should I?
