### ISSUE TITLE
06A-Moton Field Municipal-ALABAMA-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#5515]
# Airport Name
Moton Field Municipal
# Country?
USA
# Improvements that need to be made?
full redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/95683466-0b33e780-0bb1-11eb-8c6e-24521ede89cd.png)
