### ISSUE TITLE
PAJN

### ISSUE THREAD

**Issue by tranquil-skyflyer** [InfiniteFlightAirportEditing/Airports#552]
I'll do this one!

**Comment by dushyants19** [comment]
@Jacob-IF how is this and #565 going?

**Comment by Jacob-IF** [comment]
Not very well.

**Comment by dushyants19** [comment]
hows this going? @Jacob-IF

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by bavAVIA** [comment]
Why not...

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23096113/bef9fcf4-f5db-11e6-95a4-6793e80c21db.png)
