### ISSUE TITLE
PAGM-Gambell Airport-ALASKA-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#5526]
# Airport Name
Gambell Airport
# Country?
USA
# Improvements that need to be made?
Full redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/95796518-b082b480-0cb2-11eb-9d6b-3820c7fae5fb.png)
