### ISSUE TITLE
SSCN-Canela Airport-RIO GRANDE DO SUL-BRAZIL

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#5528]
# Airport Name
Canela Airport
# Country?
Brazil
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes (I am done actually, was waiting for SNOU's approval to create the issue)
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/97080485-42e35c00-15c1-11eb-9383-e4b62705a38a.png)
