### ISSUE TITLE
LOWS-Salzburg Airport-SALZBURG-AUSTRIA

### ISSUE THREAD

**Issue by IceBlue02** [InfiniteFlightAirportEditing/Airports#553]
Salzburg, Austria.

Redoing.

**Comment by IceBlue02** [comment]
Done.

`d953caa`

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18216723/3edc31aa-711e-11e6-8026-e30fcc076498.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/71905983-fde05d00-3147-11ea-9222-7954f0e24680.jpg)
