### ISSUE TITLE
KLUG-Lewisburg-TENNESSEE-USA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#5531]
# Airport Name
< Ellington Airport >
# Country?
< USA >
# Improvements that need to be made?
< full redo >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/97506269-8682f080-1948-11eb-8c85-7ce0c40474ca.png)
