### ISSUE TITLE
SNZA-Pouso Alegre Airport-MINAS GERAIS-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5534]
# Airport Name
Pouso Alegre Airport
# Country?
Brazil
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/95919522-5990e400-0d73-11eb-94d7-2d8ca62dde34.png)
