### ISSUE TITLE
VARK-Rajkot Airport-Gujrat-India

### ISSUE THREAD

**Issue by KaalicharanDH** [InfiniteFlightAirportEditing/Airports#5535]
# Airport Name
Rajkot Airport
# Country?
India
# Improvements that need to be made?
Full Rework
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![Uploading image.png…]()

**Comment by kilt46** [comment]
![Uploading image.png…]()

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/99975086-64be3300-2d67-11eb-80af-22ef2df0c17b.png)
