### ISSUE TITLE
KLBX-Texas Gulf Coast Rgnl-TEXAS-USA

### ISSUE THREAD

**Issue by 2000rpm** [InfiniteFlightAirportEditing/Airports#5536]
# Airport Name
< Texas Gulf Coast Rgnl >
# Country?
< USA >
# Improvements that need to be made?
< Redo >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by 2000rpm** [comment]
Would any supervisor close this issue?
It had been passed OR in last December.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104251842-38a16300-5436-11eb-93b7-8a9e8e6ec5b2.png)
