### ISSUE TITLE
LGKS- Kasos Airport-South Aegean-GREECE

### ISSUE THREAD

**Issue by davide-dc** [InfiniteFlightAirportEditing/Airports#5538]
# Airport Name
Kasos
# Country?
Greece
# Improvements that need to be made?
redone from scratch
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/98440465-7e505100-20be-11eb-9f29-261339882a87.png)
