### ISSUE TITLE
OTBD

### ISSUE THREAD

**Issue by dushyants19** [InfiniteFlightAirportEditing/Airports#554]
Old Doha Intl, Im doing this. :smile:

**Comment by dushyants19** [comment]
[OTBD](https://cloud.githubusercontent.com/assets/13567007/17960150/fc83c0e6-6ac1-11e6-911a-6606f55290b4.png)


Tada! 


f03705c

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17989163/e039aa70-6af0-11e6-9cd1-de890f7cdb23.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17989169/eaae8dcc-6af0-11e6-8ad7-1e812c544b45.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17989173/f5022ca2-6af0-11e6-91a2-b543aa852e3a.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17989178/fbf89a32-6af0-11e6-8f6e-7ed74cab6204.png)
