### ISSUE TITLE
LGKP-Karpathos Airport-South Aegean-GREECE

### ISSUE THREAD

**Issue by davide-dc** [InfiniteFlightAirportEditing/Airports#5540]
# Airport Name
Karpathos
# Country?
Greece
# Improvements that need to be made?
re do from scratch
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by MajorTomMueller** [comment]
lack of ICAO ...

**Comment by MajorTomMueller** [comment]
Kilt supports lazyness ...

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102559253-013cd200-4095-11eb-9acd-df887e3d0e5f.png)
