### ISSUE TITLE
KARM-Wharton Rgnl-TEXAS-USA

### ISSUE THREAD

**Issue by 2000rpm** [InfiniteFlightAirportEditing/Airports#5547]
# Airport Name
< Wharton Rgnl >
# Country?
< USA >
# Improvements that need to be made?
< Redo >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/97506634-6acc1a00-1949-11eb-892e-3b27534f72ee.png)
