### ISSUE TITLE
EGOV-RAF Valley-WALES-UK

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#5548]
# Airport Name
RAF Valley
# Country?
UK
# Improvements that need to be made?
scratch
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/96791525-422ea800-13be-11eb-8aff-ff02db85e130.png)
