### ISSUE TITLE
LGAX-Alexandria-North Aegean-GREECE

### ISSUE THREAD

**Issue by davide-dc** [InfiniteFlightAirportEditing/Airports#5549]
# Airport Name
Alexandria
# Country?
Greece
# Improvements that need to be made?
Full redo
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102721737-57428d00-42c2-11eb-9cd4-d00f28223224.png)
