### ISSUE TITLE
EPWA-Warsaw Chopin Airport-MAZOVIA-POLAND

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#555]
I'm going to do a complete Re-Do of this one. It was requested by a member of the forums. #

**Comment by RileyDunshea** [comment]
I wasn't able to assign myself. Can you not do it on IOS?

**Comment by IceBlue02** [comment]
User Suggestion List (So I get notifications)

**Comment by RileyDunshea** [comment]
Sorry cant do this one anymore

**Comment by kilt46** [comment]
This is NOT ACCEPTABLE starting a job and closing it NOT DONE

**Comment by RileyDunshea** [comment]
Kilt i can't download the files. i will take me three hours to get the pics from WEDbing. Im sorry i didn't know

**Comment by RileyDunshea** [comment]
Okay i will do it. I'm sorry i have an extremely slow download speed so it is going to take me ages to get the photo's from WEDbing. I will start tomorrow.

**Comment by PaulNielsen** [comment]
How many files does it say it has to download, Riley?

**Comment by RileyDunshea** [comment]
21,000. I have slow internet so I don't know when to download them.

**Comment by samuelandersson** [comment]
You need to zoom in closer to the airport @RileyDunshea just so it fits in screen.

**Comment by PaulNielsen** [comment]
Uhhh. Yeah, and also if you have to have it a bit zoomed out, make your browser window smaller. Did you set it on 19? Also 21,000 should only take one hour. Just put in on and do something else at the same... Gosh.

**Comment by RileyDunshea** [comment]
Yes it is one 19. I'm zoomed out as close as I can to get the whole airport in. I live in Aus so my internet is really slow. 21,000 would take me 3 hours. I'll try the window trick.

**Comment by dushyants19** [comment]
@RileyDunshea hows the progress?

**Comment by RileyDunshea** [comment]
Pretty good. Have to redo a area because of outdated scenery. Then it will just be some parking and road ways.

**Comment by brunocr98** [comment]
Any progress Riley?

**Comment by RileyDunshea** [comment]
Kilt said he would do it because my WED wouldn't show the overlay images needed.

**Comment by brunocr98** [comment]
Done

**Comment by kilt46** [comment]
Bruno should there be outlines here, possibly roads?
![image](https://cloud.githubusercontent.com/assets/14023167/24828150/85901ebe-1c1c-11e7-8e67-37a6ee0f448b.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24830629/9d891074-1c4f-11e7-9f72-054ea45bae07.png)

**Comment by brunocr98** [comment]
I just took off from this airport and it will need a redo. Living this to anyone who's interested.

**Comment by MajorTomMueller** [comment]
From: https://ais.pansa.pl/aip/
Thos Files:
https://ais.pansa.pl/aip/pliki/EP_AD_2_EPWA_en.pdf
https://ais.pansa.pl/aip/pliki/EP_AD_2_EPWA_1-1-1_en.pdf
https://ais.pansa.pl/aip/pliki/EP_AD_2_EPWA_1-2-1_en.pdf
https://ais.pansa.pl/aip/pliki/EP_AD_2_EPWA_1-3-1_en.pdf
https://ais.pansa.pl/aip/pliki/EP_AD_2_EPWA_1-3-2_en.pdf
https://ais.pansa.pl/aip/pliki/EP_AD_2_EPWA_1-3-3_en.pdf
https://ais.pansa.pl/aip/pliki/EP_AD_2_EPWA_1-3-4_en.pdf
https://ais.pansa.pl/aip/pliki/EP_AD_2_EPWA_1-3-5_en.pdf
https://ais.pansa.pl/aip/pliki/EP_AD_2_EPWA_1-3-6_en.pdf
representing all Information needed.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/69434307-20472400-0d1c-11ea-8857-a9e70a4976a3.jpg)
