### ISSUE TITLE
KDHN-Dothan Regional Airport-ALABAMA-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#5553]
# Airport Name
Dothan Regional
# Country?
USA
# Improvements that need to be made?
Full redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/98423070-203a5400-2053-11eb-9429-666981bfea5d.png)
