### ISSUE TITLE
KMCO-Orlando International Airport-FLORIDA-USA

### ISSUE THREAD

**Issue by SudarshanMahesh** [InfiniteFlightAirportEditing/Airports#556]
I do this. Can somebody assign me? And labels?

Thanks!

**Comment by IceBlue02** [comment]
User Suggestion List (So I get notifications)

**Comment by sudafly** [comment]
Send!

**Comment by sudafly** [comment]
Waiting for approvement Label?

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17277049/5d5251f2-56ff-11e6-867e-5b69f108fa7b.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17277051/61d99794-56ff-11e6-914e-25be4dcd2f1b.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17831640/dce95a6e-66b3-11e6-9df4-b52deb2b24a5.png)
TERMINALS
![image](https://cloud.githubusercontent.com/assets/14023167/17831643/e698c45a-66b3-11e6-8fdc-b79fec812ec3.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17831646/f6281bb4-66b3-11e6-9414-39241bce7f77.png)

**Comment by dushyants19** [comment]
Terminals have no holes

**Comment by brunocr98** [comment]
I fixed a few weeks ago..

**Comment by RyanEpps** [comment]
Next modernization project
