### ISSUE TITLE
KMVN-Mount Vernon-ILLINOIS-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#5560]
# Airport Name
Mount Vernon

# Country?
Illionois, USA

# Improvements that need to be made?
Full rework

# Are you working on this airport?
Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

https://drive.google.com/file/d/1tfyKpWf_ob-F5TFQBvOP6GWBZLYJ3Z21/view?usp=drivesdk

(Had issue uploading image)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/98422626-cd13d180-2051-11eb-8cd1-96964c64ede1.png)
