### ISSUE TITLE
L41-Marble Canyon Airport-ARIZONA-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#5563]
# Airport Name
Marble Canyon Airport
# Country?
USA
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/97080721-2c3e0480-15c3-11eb-8f01-87115a100afa.png)
