### ISSUE TITLE
SDEP-Presidente Epitacio Airport-SAO PAULO-BRAZIL

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#5565]
# Airport Name
Presidente Epitacio Airport
# Country?
Brazil
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by GBKarp** [comment]
Sent to OR!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/97642300-d0380d80-1a12-11eb-827e-8af6e8686c21.png)
