### ISSUE TITLE
SNIN-Nova Era Airstrip-Rio Grande do Sul-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5566]
Incorrect Airport - Changes in Brazilian Airspace.
Should now be located at 
-1.800277948 , -53.48389053

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/97080403-91442b00-15c0-11eb-8338-a4416804dc24.png)

**Comment by MajorTomMueller** [comment]
What exactly is the design issue with this one?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103421609-e6715f80-4b62-11eb-9861-38378fe2b061.png)
