### ISSUE TITLE
SDZH-Fazenda Santa Helena-SAO PAULO-BRAZIL

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#5567]
# Airport Name
Fazenda Santa Helena
# Country?
Brazil
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by GBKarp** [comment]
Sent to OR!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/97641620-518ea080-1a11-11eb-8072-0ddd04887272.png)
