### ISSUE TITLE
77S-Hobby Field-OREGON-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#5568]
# Airport Name
Hobby Field
# Country?
USA
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/97106585-b0aa8900-1690-11eb-8fd3-ebfc045aa2b8.png)
