### ISSUE TITLE
OENN-Neom Bay Airport-NEOM-SAUDI ARABIA

### ISSUE THREAD

**Issue by M3RKZ** [InfiniteFlightAirportEditing/Airports#5569]
# Airport Name
< Neom >
# Country?
< Saudia Arabia>
# Improvements that need to be made?
< New Airport need adding >
# Are you working on this airport?
< yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by Czechoslovaki** [comment]
If you're not going to be immediately working on this then please do not create the issue.

Are you in our slack? Can't seem to find you.

**Comment by MajorTomMueller** [comment]
3months till a result, subject of recycling after that

**Comment by M3RKZ** [comment]
> If you're not going to be immediately working on this then please do not create the issue.

I'm now working on this airport

**Comment by MajorTomMueller** [comment]
Any progress @M3RKZ ?
Comunity is calling:
https://community.infiniteflight.com/t/project-saudi-arabia/543522/5

**Comment by M3RKZ** [comment]
I'm still working on it

‫في ١٢‏/٠٣‏/٢٠٢١ الساعة ٢:٤٩ م، كتب/كتبت ‏Major Tom ***@***.***>:‬

﻿

Any progress @M3RKZ<https://github.com/M3RKZ> ?
Comunity is calling:
https://community.infiniteflight.com/t/project-saudi-arabia/543522/5

**Comment by SuhasIF** [comment]
I'd like to take this.

**Comment by M3RKZ** [comment]
Actually , I finished designing this airport and I uploaded the file in discord  for review, but it was rejected more than once, and i am corrected the required but it is still rejected , what should i do ?

**Comment by brunocr1050** [comment]
Once you rejoin, please send the airport for review. It has been noted to me that your latest edition of this airport was OKed in peer-review. If you did other stuff to it after the latest peer-review, please sent it to PR again.

**Comment by M3RKZ** [comment]
Ok I will upload again

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116479612-91f69c00-a845-11eb-9e67-97feefee2200.png)
