### ISSUE TITLE
EKBI

### ISSUE THREAD

**Issue by Anfinn** [InfiniteFlightAirportEditing/Airports#557]
Looks to be only minor issues, I'll take on this airport.

**Comment by Anfinn** [comment]
DONE!
Complete redo. Sent in for approval

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20606427/6ef9aaa8-b236-11e6-85ce-f9e7521bc7d0.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52184271-c8641e80-27d6-11e9-8014-14b2bbed3143.png)
DUPLICATE REMOVED. 
REMOVE DUPLICATE   SPAWNS | BUILDINGS REMOVED
