### ISSUE TITLE
VVBH-Bien Hoa Air Base-DONG NAI-VIETNAM

### ISSUE THREAD

**Issue by IFUA2003** [InfiniteFlightAirportEditing/Airports#5570]
# Airport Name
< Bien Hoa Air Base >
# Country?
< Vietnam >
# Improvements that need to be made?
< Redo from scratch >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< No >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/99011635-2c6e5780-2512-11eb-8670-8e206e48da94.png)
