### ISSUE TITLE
KPRC-Prescott Regional / Ernest A Love Field-ARIZONA-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#5573]
# Airport Name
Prescott Regional / Ernest A Love Field
# Country?
USA
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102300002-a894fa00-3f19-11eb-805e-6f4ad6c42826.png)
