### ISSUE TITLE
KSKA-Fairchild AFB-WASHINGTON-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#5574]
# Airport Name
Fairchild AFB
# Country?
USA
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
10k

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/97501816-f5a81700-193f-11eb-93a4-9998b4207a0d.png)
