### ISSUE TITLE
SSBL-Blumenau Airport-SANTA CATARINA-BRAZIL

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#5576]
# Airport Name
Blumenau Airport
# Country?
Brazil
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/99012598-63456d00-2514-11eb-8231-63f934f23521.png)
