### ISSUE TITLE
LFHJ-Lyon Corbas-LYON-FRANCE

### ISSUE THREAD

**Issue by Navy315** [InfiniteFlightAirportEditing/Airports#5581]
# Airport Name
< Lyon Corbas >
# Country?
< France>
# Improvements that need to be made?
< Redo from scratch >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by MajorTomMueller** [comment]
![LFHJ-git](https://user-images.githubusercontent.com/26853210/131700257-93bc88c8-ed62-43c5-836a-76957f99d290.png)
