### ISSUE TITLE
VAAH-Sardar Vallabhbhai Patel International Airport-GUJARAT-INDIA

### ISSUE THREAD

**Issue by hari-shreyas** [InfiniteFlightAirportEditing/Airports#5582]
# Airport Name
Sardar Vallabhbhai Patel International Airport
# Country?
India
# Improvements that need to be made?
New Apron (apron 3) should be added
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by Czechoslovaki** [comment]
#1992
