### ISSUE TITLE
UEBT-Ust-Kuyga-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#5591]
# Airport Name
< Ust-Kuyga >
# Country?
< Russia >
# Improvements that need to be made?
< redo >
# Are you working on this airport?
< yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/99012939-0e562680-2515-11eb-95f9-1000b9ff31f9.png)
