### ISSUE TITLE
RPMQ-Mati Airport-DAVAO ORIENTAL-PHILIPPINES

### ISSUE THREAD

**Issue by LesterXavier** [InfiniteFlightAirportEditing/Airports#5592]
# Airport Name
< Mati Airport >
# Country?
< Philippines >
# Improvements that need to be made?
< Rework from scratch >
# Are you working on this airport?
< Ye >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/99735256-e6714080-2a89-11eb-8f6d-295934569e62.png)
