### ISSUE TITLE
RPMI-Iligan Airport-LANAO DEL NORTE-PHILIPPINES

### ISSUE THREAD

**Issue by LesterXavier** [InfiniteFlightAirportEditing/Airports#5593]
# Airport Name
< Iligan Airport >
# Country?
< Philippines >
# Improvements that need to be made?
< Rework from scratch >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/99734911-44e9ef00-2a89-11eb-9783-5703077d4709.png)
