### ISSUE TITLE
RPMB-Rajah Buayan Air Station-SOUTH COTABATO-PHILIPPINES

### ISSUE THREAD

**Issue by LesterXavier** [InfiniteFlightAirportEditing/Airports#5594]
# Airport Name
< Rajah Buayan Air Station >
# Country?
< Philippines >
# Improvements that need to be made?
< rework from scratch >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/99908077-ffeed400-2ca5-11eb-9bd6-6a168e613f0e.png)
