### ISSUE TITLE
FCBB-Maya Maya Airport-BRAZZAVILLE-REPUBLIC OF THE CONGO

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#5595]
# Airport Name
Maya Maya Airport
# Country?
Republic Of The Congo
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
World Capital

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/99907531-d3858880-2ca2-11eb-979f-81e9b9db812f.png)

**Comment by brennanhackard** [comment]
@GBKarp will be making fixes to this airport.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104968330-1dd96c00-59ab-11eb-901e-064c39b3a505.png)
