### ISSUE TITLE
KJLN-Joplin Regional Airport-MISSOURI-USA

### ISSUE THREAD

**Issue by Jeremy351** [InfiniteFlightAirportEditing/Airports#5597]
# Airport Name
Joblin Regional Airport
# Country?
USA
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102718807-d4183b80-42af-11eb-867e-7243296aab70.png)
