### ISSUE TITLE
KMYR-Myrtle Beach International Airport-SOUTH CAROLINA-USA

### ISSUE THREAD

**Issue by victormw22** [InfiniteFlightAirportEditing/Airports#5598]
# Airport Name
< Myrtle Beach >
# Country?
< USA >
# Improvements that need to be made?
< Redone >
# Are you working on this airport?
< yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103048153-4197c680-4553-11eb-8b77-10b39ecc740c.png)
