### ISSUE TITLE
SURB-Rio Branco Airport-CERRO LARGO-URUGUAY

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5599]
# Airport Name
Rio Branco Airport
# Country?
Uruguay
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/97763882-f628e500-1ada-11eb-9941-ca30b5b0037e.png)
