### ISSUE TITLE
EDDH

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#560]
Airport in Hamburg, Germany. I'll make this one for when global flight comes.

**Comment by kilt46** [comment]
Not sure if this is aligned
![image](https://cloud.githubusercontent.com/assets/14023167/15270264/d47c281a-19de-11e6-8bdc-e0ba41e9982c.png)

**Comment by Aviationluver** [comment]
I've realigned the airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20547238/5da7d4c0-b0e0-11e6-8f86-019adc2f5b37.png)
