### ISSUE TITLE
SURV-Rivera Airport-RIVERA-URUGUAY

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5600]
# Airport Name
Rivera International Airport
# Country?
Uruguay
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/97763704-6c791780-1ada-11eb-8a1a-0dca05b948d3.png)
