### ISSUE TITLE
SUMO-Cerro Largo Airport-CERRO LARGO-URUGUAY

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5602]
# Airport Name
Cerro Largo International Airport
# Country?
Uruguay
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/97763538-e5c43a80-1ad9-11eb-9877-78ba57299c7b.png)
