### ISSUE TITLE
SUAG-Artigas Airport-ARTIGAS-URUGUAY

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5604]
# Airport Name
Artigas International Airport
# Country?
Uruguay
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/97763348-528b0500-1ad9-11eb-8053-a4ccb01b622e.png)
