### ISSUE TITLE
SUCA-Laguna De Los Patos International Airport-COLONIA-URUGUAY

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#5605]
# Airport Name
Laguna De Los Patos International Airport
# Country?
Uruguay
# Improvements that need to be made?
Added in IF
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![Uploading image.png…]()

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/99010911-8bcb6800-2510-11eb-98d8-1ccda7bf2913.png)
