### ISSUE TITLE
UT75-Mineral Canyon-UTAH-USA

### ISSUE THREAD

**Issue by tomthetank46** [InfiniteFlightAirportEditing/Airports#5606]
# Airport Name
Mineral Canyon
# Country?
United States
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
None

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/99972103-bcf33600-2d63-11eb-9174-25f4bdf0a14e.png)
