### ISSUE TITLE
KGYB-Giddings Lee Co-TEXAS-USA

### ISSUE THREAD

**Issue by 2000rpm** [InfiniteFlightAirportEditing/Airports#5609]
# Airport Name
< Giddings Lee Co >
# Country?
< USA >
# Improvements that need to be made?
< Redo >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/99322682-17593780-2836-11eb-9584-b76846df454b.png)
