### ISSUE TITLE
FNLU-Luanda Airport-LUANDA-ANGOLA

### ISSUE THREAD

**Issue by freddiefrogs** [InfiniteFlightAirportEditing/Airports#561]
The new KSGU. Needs renaming and possible redo depending on condition. Will do myself.

**Comment by freddiefrogs** [comment]
Unable to continue editing due to recurring computer problems. Can someone else please takeover?

**Comment by freddiefrogs** [comment]
I am no longer able to edit any airports.

**Comment by bavAVIA** [comment]
There's already another ZURK on the tracker. Recycled this to FNLU - Luanda Int'l in Angola.
Up for grabs!

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27210766-5fd8ded4-521a-11e7-83db-8cd649a5bb9a.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/81995961-3a562500-9622-11ea-9dab-ae5d0000b581.jpg)
