### ISSUE TITLE
2S6-Sportsman Airpark-OREGON-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#5610]
# Airport Name
Sportsman Airpark
# Country?
USA
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Lower than ever

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/98050844-31d3ef80-1df8-11eb-9b0f-e899cd996cb5.png)
