### ISSUE TITLE
LFLW-Aurillac-Auvergne Rhône Alpes-FRANCE

### ISSUE THREAD

**Issue by Jeremy351** [InfiniteFlightAirportEditing/Airports#5612]
# Airport Name
Aurillac Airport
# Country?
France
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102690684-bf16ac00-41cc-11eb-84ba-57d88dbc130a.png)
