### ISSUE TITLE
7S3-Stark's Twin Oaks Airpark-OREGON-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#5617]
# Airport Name
Stark's Twin Oaks Airpark
# Country?
USA
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/98050522-7ad77400-1df7-11eb-8caf-e86b3623ef7a.png)
