### ISSUE TITLE
UUDD-Moscow Domodedovo Airport-MOSKVA-RUSSIA

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#562]
Narita International - Global Priority 1 A380 - Non-region - Being Redone

**Comment by IFAEpat** [comment]
thanks @samuelandersson 👍

**Comment by kilt46** [comment]
Airport redrawn from scratch

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17267376/a31635de-55cc-11e6-96e8-52b0751b9642.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17267378/acd35f70-55cc-11e6-9126-9e63b93eb019.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18027243/8b1f1806-6c24-11e6-9766-ddb65df7b6ec.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18027246/95f5bd2a-6c24-11e6-8c88-180778b0e7bd.png)

**Comment by brunocr1050** [comment]
@AleksanderIF will be working on the following.

- Missing concrete at all near runway 14R/32L
- Missing spawns, octagons and other lines on DA1 and DA2 Aprons
- Stands near H3 not in use
- Some lines are not on the taxiways
- Removing the surface for the new terminal section
- 14L/32R is partially decommissioned
- New runway (will be added as taxiway)
- Elevation and name updates

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111075353-aa893d80-84b5-11eb-9cb0-f151d8dec87a.png)
