### ISSUE TITLE
SWFH-Fly Club Airport-BAHIA-BRAZIL

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Airports#5620]
# Airport Name
< Fly Club >
# Country?
< Brazil >
# Improvements that need to be made?
< Redone from scratch >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103317212-7773f980-49f0-11eb-8b16-4bebdf3014e3.png)
