### ISSUE TITLE
VYYY-Yangon International Airport-YANGON-MYANMAR

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#5625]
# Airport Name
Yangon International
# Country?
Myanmar
# Improvements that need to be made?
Full Redo, apparently this has never been touched before
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
10k

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/98422718-182de480-2052-11eb-9647-5655f468b485.png)
