### ISSUE TITLE
LGSV-Stefanovikion-North Aegean- GREECE

### ISSUE THREAD

**Issue by davide-dc** [InfiniteFlightAirportEditing/Airports#5629]
# Airport Name
Stefanovikion AB
# Country?
Greece
# Improvements that need to be made?
Full redo
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102558974-57f5dc00-4094-11eb-95f1-4597897b51e1.png)
