### ISSUE TITLE
ESGP

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Airports#563]
Small airport near me, will be reworking.

**Comment by samuelandersson** [comment]
Done and approved.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17232700/88861636-54ef-11e6-9634-b9d703311881.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17262919/d9749eaa-55a3-11e6-8351-0caaacc3353c.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18255763/8e1cf460-7372-11e6-82e9-a717b7cfbc43.png)
