### ISSUE TITLE
U692-Mexican Mountain-UTAH-UNITED STATES

### ISSUE THREAD

**Issue by tomthetank46** [InfiniteFlightAirportEditing/Airports#5632]
# Airport Name
Mexican Mountain
# Country?
USA
# Improvements that need to be made?
Airport needs to be created
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
None

**Comment by kilt46** [comment]
![Uploading image.png…]()

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/99971424-c0d28880-2d62-11eb-8df2-33a506a2b963.png)
