### ISSUE TITLE
LSME-Emmen-EMMEN-SWITZERLAND

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#5634]
# Airport Name
Emmen
# Country?
Switzerland
# Improvements that need to be made?
Everything needs to be improved, XPlane scenery.
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by feitidede** [comment]
[
![LSME](https://user-images.githubusercontent.com/69402901/98306409-92069500-1fa2-11eb-9054-1378f7a24838.png)
](url)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103326383-ad77a480-4a15-11eb-9e00-c50a56358b5f.png)
