### ISSUE TITLE
TNCB-Flamingo Airport-BONAIRE-VENEZUELA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5638]
# Airport Name
Flamingo International Airport
# Country?
Bonaire
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
GP2 (+10k)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/99189353-6f087d80-2726-11eb-9c17-e3a1cfe49b92.png)
