### ISSUE TITLE
KPSM-Portsmouth International At Pease Airport-NEW HAMPSHIRE-USA

### ISSUE THREAD

**Issue by Blently** [InfiniteFlightAirportEditing/Airports#564]
It looks like it needs some work done, precise taxiways, taxi lines, etc... I will do it

**Comment by bylrret** [comment]
Waiting for approval

**Comment by dushyants19** [comment]
Approved by Henrik. [Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/3e187fa2a47e1a3cfd5197edd07a17dfc190f62d)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20648993/86ba25b4-b47a-11e6-8f8b-1d76bc0e1232.png)

**Comment by bavAVIA** [comment]
@Blently is overhauling.

**Comment by CptNathanHope** [comment]
Part of [Project New England](https://community.infinite-flight.com/t/project-new-england/43169).

Could use an overhaul as it is a bit sloppy and does not meet current editing standards. Will do as soon as possible if no one else takes it. 
– N

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36057823-77cc8b50-0dd9-11e8-964a-76d161ac7683.png)
