### ISSUE TITLE
Duplicate

### ISSUE THREAD

**Issue by Camber1513** [InfiniteFlightAirportEditing/Airports#5641]
# Airport Name
Bangor International Airport (KBGR)
# Country?
United States
# Improvements that need to be made?
Adding starting spots for the LifeLight of Maine Hangar and Airplane Storage
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by MajorTomMueller** [comment]
#1030
