### ISSUE TITLE
FNCA-Cabinda Airport-CABINDA-ANGOLA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5643]
# Airport Name
Cabinda Airport
# Country?
Angola
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/98440778-4a762b00-20c0-11eb-9e65-22355c89d631.png)
