### ISSUE TITLE
KGWR-Gwinner-NORTH DAKOTA-UNITED STATES

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#5644]
# Airport Name
 Gwinner 
# Country?
 USA 
# Improvements that need to be made?
 Full edit 
# Are you working on this airport?
 yes 
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
 low 

![Full](https://user-images.githubusercontent.com/59462519/98432902-5f4fc000-20ba-11eb-96be-34d860fd35b7.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/99970520-8f0cf200-2d61-11eb-8602-ef14c803d922.png)
