### ISSUE TITLE
PAKT

### ISSUE THREAD

**Issue by tranquil-skyflyer** [InfiniteFlightAirportEditing/Airports#565]
I'll do this one!

**Comment by dushyants19** [comment]
Ill do it

**Comment by dushyants19** [comment]
no time

**Comment by dushyants19** [comment]
piece of cake. done in 2 hours (inc. procrastination)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22714390/e0cdf9d0-ed51-11e6-9257-c7bf2836e526.png)
