### ISSUE TITLE
KADS-Addison Airport-TEXAS-UNITED STATES

### ISSUE THREAD

**Issue by SaharshShu** [InfiniteFlightAirportEditing/Airports#5653]
# Airport Name
Addison Airport
# Country?
United States
# Improvements that need to be made?
Full
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by Czechoslovaki** [comment]
@SaharshShu has been unassigned due to computer maintenance.

**Comment by davide-dc** [comment]
I would like to do it.

**Comment by davide-dc** [comment]
I'm not working on this airport anymore unfortunately, if someone takes over he can pm me for the apt.dat

**Comment by ECoops-123** [comment]
I'll be taking over this edit :)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106362042-44ba6b00-62e6-11eb-9f24-327fe34bcefd.png)
