### ISSUE TITLE
SOOM-Saint Laurent Du Maroni Airport-SAINT LAURENT DU MARONI-FRENCH GUIANA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5654]
# Airport Name
Saint Laurent Du Maroni Airport
# Country?
French Guiana
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/98468573-b0d27a80-21a0-11eb-8684-a9ef13951ec8.png)
