### ISSUE TITLE
FMCV-Ouani Airport-NZWANI-COMOROS

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#5655]
# Airport Name
Ouani Airport
# Country?
Comoros
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101994617-5342b980-3c89-11eb-85c6-5d40654d6982.png)
