### ISSUE TITLE
7M3-Bearce Airport-ARKANSAS-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#5658]
# Airport Name
Bearce Airport
# Country?
the north american one with 50 states
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/98606367-c92fbb80-22ac-11eb-9feb-8b23b2cd3d48.png)
