### ISSUE TITLE
OYTZ-Taiz Airport-TA'IZZ-YEMEN

### ISSUE THREAD

**Issue by zacky89315** [InfiniteFlightAirportEditing/Airports#5661]
# Airport Name
< Taiz Airport >
# Country?
< Yemen >
# Improvements that need to be made?
< redo from scratch>
# Are you working on this airport?
< yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< GP1 >

**Comment by MajorTomMueller** [comment]
GP1 is set by administrative staff

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102148054-61333e80-3e31-11eb-8467-7368794b442f.png)
