### ISSUE TITLE
ORAA-Al Asad Airbase-AL ANBAR-IRAQ

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#5662]
# Airport Name
Al Asad Airbase
# Country?
Iraq
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
GP1, 10k+

**Comment by MajorTomMueller** [comment]
GP1 is set by administrative staff only

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/100491348-67fb4b00-30e8-11eb-9008-9ec59362a76e.png)

**Comment by MajorTomMueller** [comment]
![ORAA-git](https://user-images.githubusercontent.com/26853210/100539736-6472db80-3230-11eb-8fe4-518c46137c49.png)
