### ISSUE TITLE
LFMS-Ales Cevennes / Deaux Airport-LANGUEDOC-ROUSSILLON-FRANCE 

### ISSUE THREAD

**Issue by FlyBoii31** [InfiniteFlightAirportEditing/Airports#5663]
# Airport Name
< Deaux >
# Country?
< France >
# Improvements that need to be made?
< Full Rework >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by MajorTomMueller** [comment]
![LFMS-git](https://user-images.githubusercontent.com/26853210/130357359-85b31308-ebf1-4cb3-9a30-2d687391824d.png)
