### ISSUE TITLE
FABL-Bram Fischer International Airport-ORANGE FREE STATE-SOUTH AFRICA

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#5664]
# Airport Name
Bram Fischer International
# Country?
South Africa
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
One of SA's 3 capitals

**Comment by MajorTomMueller** [comment]
You are already assigned to 3 issues @GBKarp

**Comment by GBKarp** [comment]
SSBL was just accepted @MajorTomMueller

**Comment by MajorTomMueller** [comment]
Might want to wait till it is in GitHub next time.

**Comment by GBKarp** [comment]
Sorry, will do next time.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/100485119-8cddc700-30c4-11eb-8924-fb8e3bff92ce.png)
