### ISSUE TITLE
VGEG-Shah Amanat International Airport-BANGLADESH

### ISSUE THREAD

**Issue by SamiB12** [InfiniteFlightAirportEditing/Airports#5665]
# Airport Name
< VGEG chittagong shah amanat intl >
# Country?
< Bangladesh >
# Improvements that need to be made?
< Adding terminal and taxiway >
# Are you working on this airport?
< yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< 9646x148 ft >

**Comment by SamiB12** [comment]
currently working on this airport

**Comment by KaalicharanDH** [comment]
Is he doing it? I can do it

**Comment by KaalicharanDH** [comment]
I can do it. I think he is not doing it

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108625410-6a7fef00-7410-11eb-89f8-e07a50fc365e.png)
