### ISSUE TITLE
USNN-Nizhnevartovsk-KHANTY–MANSI-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#5666]
# Airport Name
< Nizhnevartovsk Airport >
# Country?
< Russia >
# Improvements that need to be made?
< redo >
# Are you working on this airport?
< yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< GP2 >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101842434-a0018580-3b0d-11eb-955d-ae2ca8f64158.png)
