### ISSUE TITLE
SVJC-Josefa Camejo Airport-FALCON-VENEZUELA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5667]
# Airport Name
Josefa Camejo International Airport
# Country?
Venezuela
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/99189749-56996280-2728-11eb-882b-e9da9a5129c5.png)
