### ISSUE TITLE
KCPF-Wendell H Ford-KENTUCKY-UNITED STATES

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#5668]
# Airport Name
Wendell H Ford

# Country?
Kentucky, USA
# Improvements that need to be made?
Full

# Are you working on this airport?
Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

![Full(3)](https://user-images.githubusercontent.com/59462519/98978216-8b7f9c80-2511-11eb-8b64-a64f61ff4f01.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101841772-3c2a8d00-3b0c-11eb-9412-aeaba0a1b9bd.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101841787-477db880-3b0c-11eb-94fe-ef0176a61fd8.png)
