### ISSUE TITLE
1S8-Arlington Muni-OREGON-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#5669]
# Airport Name
Arlington Muni
# Country?
Biden's country
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/99003198-4c4a4f00-2503-11eb-8d3a-98053893b2c9.png)
