### ISSUE TITLE
EBZW (Zwartberg)

### ISSUE THREAD

**Issue by freddiefrogs** [InfiniteFlightAirportEditing/Airports#567]
Needs redo, random giant square and badly drawn runways and taxiways.

**Comment by freddiefrogs** [comment]
Why was this assigned to me? @samuelandersson

**Comment by freddiefrogs** [comment]
I never stated I will do it. I already have two airports to do.

**Comment by samuelandersson** [comment]
Sorry, thought you would do it.

**Comment by freddiefrogs** [comment]
I could but there would be a delay. It's better off being left for someone else to do.

**Comment by Anfinn** [comment]
I can do it :)

**Comment by samuelandersson** [comment]
Go ahead @Anfinn

**Comment by Anfinn** [comment]
This has been sent in for approval

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20469591/ab977224-af66-11e6-95ba-7b2f75a83867.png)
