### ISSUE TITLE
SUTB-Tacuarembo Airport-TACUAREMBO-URUGUAY

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#5671]
# Airport Name
Tacuarembo Airport
# Country?
Uruguay
# Improvements that need to be made?
Added
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/99978736-ed3ed280-2d6b-11eb-884c-3cc7c17508b4.png)
