### ISSUE TITLE
KFKR-Frankfort Municipal Airport-INDIANA-USA

### ISSUE THREAD

**Issue by huddys7** [InfiniteFlightAirportEditing/Airports#5672]
# Airport Name
< Frankfort Municipal >
# Country?
< United States of America >
# Improvements that need to be made?
< From Skratch >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by kilt46** [comment]
![Uploading image.png…]()

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/99969279-d8f4d880-2d5f-11eb-9cd7-9f00d7268fd1.png)
