### ISSUE TITLE
GMMN-Casablanca/Mohammed V Airport-GRAND CASABLANCA-MOROCCO

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#568]

**Comment by NickArt1342** [comment]
Hmm? I swear this one should be finished, I did it right after Marrakesh. Looks like I never uploaded it. Let me search my hard drive for it.

**Comment by Ba02der** [comment]
Can you also design te Elaaiun Airport?

**Comment by moritzbabl** [comment]
@Ba02der Don't touch the issue list/ our repo if you are not a member! We don't take requests, especially if they are posted on GitHub! You can join us and do it or wait and see if anyone does the airport (which i doubt)

**Comment by Ba02der** [comment]
Ok sorry

**Comment by moritzbabl** [comment]
@NickArt1342 did you find the airport? Otherwise I will do it

**Comment by Aviationluver** [comment]
I will take this one. Priority II airport.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by NickArt1342** [comment]
Didn't I do this one already?

**Comment by Aviationluver** [comment]
@NickArt1342 Only you can know that for certain. Check your list of airports on WED.

**Comment by NickArt1342** [comment]
I'm rather certain. I did it right after Marrakesh, meh, I'll have to search it then, I just checked the uplaoded version and it isn't it. Once I found it we can choose the better one and implement that one. Sounds fair? For the mean time we'll just use yours.

**Comment by Aviationluver** [comment]
Sounds fair. I still have a few things to polish off anyway.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24828471/7501d2fc-1c23-11e7-8fa1-fcadf7f5872b.png)
