### ISSUE TITLE
OEGT-Gurayat Airport-SAUDI ARABIA

### ISSUE THREAD

**Issue by M3RKZ** [InfiniteFlightAirportEditing/Airports#5684]
# Airport Name
< Gurayat Airport >
# Country?
< Saudia Arabia >
# Improvements that need to be made?
< All Rework >
# Are you working on this airport?
< yes>
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by kilt46** [comment]
MBeringuy removed their assignment yesterday
