### ISSUE TITLE
KVGT-North Las Vegas Airport-NEVADA-USA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#5686]
# Airport Name
KVGT - North Las Vegas Airport
# Country?
United States
# Improvements that need to be made?
Full Rework
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103173254-51e3c600-481f-11eb-9bb9-2ccfe33b9e5c.png)

**Comment by brunocr1050** [comment]
@Daniel-Baiks will be fixing the spawn names and duplicates.
