### ISSUE TITLE
KDIK-Dickinson Theodore Roosevelt Regional-NORTH DAKOTA-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#5688]
# Airport Name
Dickinson Theodore Roosevelt Regional
# Country?
🇺🇸 
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
是
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/99468027-37a3f780-2905-11eb-8d4f-48ab2acf6d85.png)
