### ISSUE TITLE
MDST-Cibao Airport-SANTIAGO-DOMINICAN REPUBLIC

### ISSUE THREAD

**Issue by Rob1594** [InfiniteFlightAirportEditing/Airports#570]
Needs grass to be made transparent and make the building into a taxiway. Also, add spawn points.

**Comment by Rob1594** [comment]
I'd be open to do it

**Comment by samuelandersson** [comment]
Then do it haha 👍

**Comment by dushyants19** [comment]
@Rob1594 how is this going?

**Comment by dushyants19** [comment]
Assigned to @brunocr98

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20582775/d258b5d6-b1a9-11e6-9c35-7141494f44d1.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/60594527-8cc88300-9d7b-11e9-82f2-6d42627c3fbb.jpg)
