### ISSUE TITLE
NTTH-Huahine Fare Airport-FRENCH POLYNESIA

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#5708]
# Airport Name
Huahine Fare Airport
# Country?
French Polynesia
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/100484877-bd713100-30c3-11eb-907e-6b847ac897fe.png)
