### ISSUE TITLE
KTRI-Tri-Cities Regional Airport-TENNESSEE-UNITED STATES

### ISSUE THREAD

**Issue by FlyBoii31** [InfiniteFlightAirportEditing/Airports#5709]
# Airport Name
< Tri-Cities Regional Airport >
# Country?
< United States >
# Improvements that need to be made?
< Full Rework >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115156103-5fc88b80-a048-11eb-970a-100fe3e5f59f.png)
