### ISSUE TITLE
VMMC

### ISSUE THREAD

**Issue by Arzanex** [InfiniteFlightAirportEditing/Airports#571]
Macau International Airport / MFM / VMMC

**Comment by samuelandersson** [comment]
Are you doing this @Arzanex?

**Comment by Arzanex** [comment]
^ Yes

**Comment by Arzanex** [comment]
Email sent

**Comment by dushyants19** [comment]
How is this and #591 going, @Arzanex? Been 6 months

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by dushyants19** [comment]
it is added already

https://github.com/InfiniteFlightAirportEditing/Airports/commit/149024ce7bcd81536ddac0dc565f66ce7e131600

**Comment by dushyants19** [comment]
i made some improvements

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20583020/fd31a14e-b1ab-11e6-8311-97e4c0423e81.png)
