### ISSUE TITLE
CYHU-Montréal-St-Hubert Airport-QUEBEC-CANADA

### ISSUE THREAD

**Issue by FlyBoii31** [InfiniteFlightAirportEditing/Airports#5710]
# Airport Name
< Montréal-St-Hubert Airport >
# Country?
< Canada >
# Improvements that need to be made?
< Full Rework >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by ECoops-123** [comment]
![Full](https://user-images.githubusercontent.com/59462519/129130099-96914d03-1364-4e10-ab54-2c8e1aeaf8d3.png)
