### ISSUE TITLE
RPVU-Romblon Airport-PHILIPPINES 

### ISSUE THREAD

**Issue by FlyingEagle0112** [InfiniteFlightAirportEditing/Airports#5714]
# Airport Name
< Romblon Airport >
# Country?
< Philippines >
# Improvements that need to be made?
< Parking Bay >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by FlyingEagle0112** [comment]
How can I Join to slack ?

**Comment by MajorTomMueller** [comment]
@FlyingEagle0112 
https://community.infiniteflight.com/t/infinite-flight-airport-editing/321307
It is all described in there

**Comment by FlyingEagle0112** [comment]
I just finished editing an airport. Where I can send it because the airport@liveflightapp.com email doesn't work.

**Comment by GBKarp** [comment]
contact@airportediting.com

**Comment by GBKarp** [comment]
But you first have to send to #peer-review on Slack

**Comment by FlyingEagle0112** [comment]
I don't have slack invitation yet : (

**Comment by MajorTomMueller** [comment]
Then get one. The IFC Direct message address is in the IFC post I linked you above.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104130722-eed25300-5337-11eb-8cb2-024862e86ce1.png)
