### ISSUE TITLE
UKDE-Zaporizhzhia International Airport-UKRAINE

### ISSUE THREAD

**Issue by liamkirky** [InfiniteFlightAirportEditing/Airports#5715]
# Airport Name
Zaporizhzhia
# Country?
Ukraine
# Improvements that need to be made?
Total Rework
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by liamkirky** [comment]
Can I be unassigned as I’m waiting for more updated imagery. Due to some construction

**Comment by RyanEpps** [comment]
Resolved with Liam in slack :)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103111158-85e89c80-460f-11eb-8133-7d099aacd9c5.png)
