### ISSUE TITLE
VOTK-Tuticorin Airport-TAMIL NADU-INDIA

### ISSUE THREAD

**Issue by hari-shreyas** [InfiniteFlightAirportEditing/Airports#5716]
# Airport Name
Tuticorin Airport
# Country?
India
# Improvements that need to be made?
Must be added/worked on
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/100955833-dff8b500-34dc-11eb-8bdc-83fbafd31ae8.png)
