### ISSUE TITLE
RPUM-Mamburao Airport-MIMAROPA-PHILIPPINES

### ISSUE THREAD

**Issue by LesterXavier** [InfiniteFlightAirportEditing/Airports#5717]
# Airport Name
< Mamburao Airport >
# Country?
< Philippines >
# Improvements that need to be made?
< Done from scratch >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101243836-805efd00-36c8-11eb-844c-0b9edf30dd0e.png)
