### ISSUE TITLE
RP13-Nonoc Airport-CARAGA-PHILIPPINES

### ISSUE THREAD

**Issue by LesterXavier** [InfiniteFlightAirportEditing/Airports#5718]
# Airport Name
< Nonoc Airport >
# Country?
< Philippines >
# Improvements that need to be made?
< Rework from scratch >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101243737-d5e6da00-36c7-11eb-9643-cdf0bf478c4e.png)
