### ISSUE TITLE
LDSB

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Airports#572]
BOL AIRPORT - Working on this.

**Comment by samuelandersson** [comment]
Just for documentation:

A whole redone is done. Added taxiways and buildings as well as corrected runway.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17232337/0324852e-54ed-11e6-9700-c7814e6df6ae.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18418909/e23066d0-7814-11e6-9ddd-1c4ed826aea2.png)
