### ISSUE TITLE
PHHI-Wheeler AFF-HAWAII-UNITED STATES

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#5725]
# Airport Name
Wheeler AFF
# Country?
United States
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/100955781-c35c7d00-34dc-11eb-84c3-c438ad5ef44f.png)
