### ISSUE TITLE
KETB-West Bend Municipal-WISCONSIN-USA

### ISSUE THREAD

**Issue by huddys7** [InfiniteFlightAirportEditing/Airports#5726]
# Airport Name
< West Bend Municipal Airport >
# Country?
< United States of America >
# Improvements that need to be made?
< Redone >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by huddys7** [comment]
Finishing this up right now

**Comment by brunocarbone3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/135530624-30eebe41-a752-4dd6-888d-43ebace12e23.png)
