### ISSUE TITLE
RPLA-Pinamalayan Airport-PHILIPPINES

### ISSUE THREAD

**Issue by FlyingEagle0112** [InfiniteFlightAirportEditing/Airports#5728]
# Airport Name
< Pinamalayan Airport >
# Country?
< Philippines >
# Improvements that need to be made?
< From Scratch >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by MajorTomMueller** [comment]
Please make sure you have read and understand the advice given in the IFC thread.
https://community.infiniteflight.com/t/infinite-flight-airport-editing/321307
Join the Slack workspace before continuing here.
If you hadn't got a invite yet try to restart to get one.

**Comment by Czechoslovaki** [comment]
@zacky89315 will take over.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103481334-e90cc880-4d9f-11eb-9849-6436915bf470.png)
