### ISSUE TITLE
RPMJ-Jolo Airport-ARMM-PHILIPPINES

### ISSUE THREAD

**Issue by LesterXavier** [InfiniteFlightAirportEditing/Airports#5729]
# Airport Name
< Jolo Airport >
# Country?
< Philippines >
# Improvements that need to be made?
< Full Rework >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101269537-67d8fc00-3735-11eb-9db2-20c528cbb372.png)
