### ISSUE TITLE
VIDP-Indira Gandhi International Airport-DELHI-INDIA

### ISSUE THREAD

**Issue by ItsW1ll** [InfiniteFlightAirportEditing/Airports#573]

**Comment by samuelandersson** [comment]
Kudos for good description :)

**Comment by Will171** [comment]
Cheers, I'm on my iPad so can't add labels and assign me

**Comment by henrikbg** [comment]
Duplicate. Continue discussion here:

https://github.com/InfiniteFlightAirportEditing/Airports/issues/18

**Comment by ReflexRSM** [comment]
I'll grab this one!

**Comment by Will171** [comment]
Any progress with this one?

**Comment by ReflexRSM** [comment]
@Will171 - Almost completed, spawns and a few taxilines need to be done.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20948169/4a99e2d0-bbd8-11e6-8e25-8c87c59fdcd1.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59129301-d8396e00-8942-11e9-98d2-091af6b0a430.jpg)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59131835-e343cc80-8949-11e9-955d-217dc6eeb9c6.jpg)
