### ISSUE TITLE
ZGBH-Beihai Fucheng Airport-GUANGXI-CHINA

### ISSUE THREAD

**Issue by zacky89315** [InfiniteFlightAirportEditing/Airports#5735]
# Airport Name
< Beihai Fucheng Airport >
# Country?
< CHINA >
# Improvements that need to be made?
< Redone from scratch >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< 10000ft+ >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102945744-45a8e300-4484-11eb-966e-a116e93ac3f3.png)
