### ISSUE TITLE
KABI-Abilene Regional Airport-TEXAS-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#5736]
# Airport Name
< Abilene Regional >
# Country?
< USA >
# Improvements that need to be made?
< Full rework >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

Current progress:

![3a0454ed7fdbe80928ba43cbab75fad67710633f](https://user-images.githubusercontent.com/59462519/100125127-53168180-2e74-11eb-8cf1-a7cc1af82f4b.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102561438-5a5b3480-409a-11eb-9b69-bb1dd4dd8cb8.png)
