### ISSUE TITLE
KAAF-Apalachicola Regional Airport-FLORIDA-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#5737]
# Airport Name
< Apalachicola Regional Airport >
# Country?
< USA >
# Improvements that need to be made?
< Full edit >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

Very slightly outdated imagery with taxiway lights
![06f3fddea3f6ebf96bc7607c1b898805b767fb44](https://user-images.githubusercontent.com/59462519/99924859-d11f3f00-2d33-11eb-8e46-561bab2bc608.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101243639-332e5b80-36c7-11eb-9e93-ae069c3650ae.png)
