### ISSUE TITLE
USDA-Sabetta-YAMALO–NENETS-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#5738]
# Airport Name
< Sabetta >
# Country?
< Russia >
# Improvements that need to be made?
< redo >
# Are you working on this airport?
< yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/100956832-fb64bf80-34de-11eb-906f-1b8189467d23.png)
