### ISSUE TITLE
IN-0024-Baramati Airport-MAHARASHTRA-INDIA

### ISSUE THREAD

**Issue by hari-shreyas** [InfiniteFlightAirportEditing/Airports#5739]
# Airport Name
Baramati Airport
# Country?
India
# Improvements that need to be made?
Needs to be added
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102829918-c517b300-43ad-11eb-854a-0e440e53dc10.png)
