### ISSUE TITLE
EDDP

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Airports#574]
Leipzig Halle.

Needs a redo, the taxiway is not showing and there are a few missing ones.

Also all of the DHL and cargo spots are not there on the map so I'll add them as well.

**Comment by samuelandersson** [comment]
My computer really cant handle this big of an airport :/ It crashes the whole time.

**Comment by moritzbabl** [comment]
I would like to redo this one

**Comment by moritzbabl** [comment]
Sent for approval just now

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33535077-16878d7e-d871-11e7-9023-fd72ff24a41a.png)

**Comment by kilt46** [comment]
DUPLICATE GATE FIXED

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52171187-0cdfb380-271e-11e9-8a4d-c3ba31c61f00.png)
