### ISSUE TITLE
FCOO-Owando Airport-REPUBLIC OF THE CONGO

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#5740]
# Airport Name
Owando Airport
# Country?
Republic of the Congo
# Improvements that need to be made?
Redone
# Are you working on this airport?
It's done, just need assignment to send to PR
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101269383-fc425f00-3733-11eb-819f-63d4f410f022.png)
