### ISSUE TITLE
KTPL-Draughon-Miller Central Texas Regional Airport-TEXAS-USA

### ISSUE THREAD

**Issue by suhasjatla** [InfiniteFlightAirportEditing/Airports#5748]
# Airport Name
Draughon-Miller Central Texas Regional Airport
# Country?
USA
# Improvements that need to be made?
Redo from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111076389-24bbc100-84ba-11eb-9487-d8ba162134d4.png)
