### ISSUE TITLE
VOVZ-Visakhapatnam Airport-ANDHRA PRADESH-INDIA

### ISSUE THREAD

**Issue by KaalicharanDH** [InfiniteFlightAirportEditing/Airports#5749]
# Airport Name
Visakhapatnam Airport
# Country?
India
# Improvements that need to be made?
Full Rework
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101269171-5db4fe80-3731-11eb-84e2-2a457d26ee5f.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101269201-d320cf00-3731-11eb-9503-81856ddb057e.png)

**Comment by kilt46** [comment]
@KaalicharanDH  Please check against Navigraph chart

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101269230-61955080-3732-11eb-99cd-d4b78e9f00d0.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101269241-8689c380-3732-11eb-8d84-23d85911d793.png)

**Comment by MajorTomMueller** [comment]
Agree to the Code change, but the chart is outdated:
![1CC735F1-2AE5-452D-8C49-EA4187BAACBC](https://user-images.githubusercontent.com/26853210/101273723-380f1000-3798-11eb-99c4-a86456766c79.jpeg)

**Comment by MBeringuy** [comment]
The necessary changes have been made. The Passenger Terminal was left unchanged because, compared to satellite images from Google, the chart is out of date.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101415567-cd4ff880-38ad-11eb-9be9-91822dc0158b.png)
