### ISSUE TITLE
KSMF-Sacramento International Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by Rob1594** [InfiniteFlightAirportEditing/Airports#575]
New addition. I can do it.

**Comment by dushyants19** [comment]
@Rob1594 how is this going?

**Comment by dushyants19** [comment]
I understand you'd like to do it in a year, but since Bruno offered us to finish it quickly. I've assigned him. You aren't doing this anymore @rob1594

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20161531/aae6487e-a6b4-11e6-831d-0b1e0c0c209d.png)

**Comment by brunocr98** [comment]
I usually don't so this, but if someone is interested in redoing this airport, you're more than welcome to do so.

https://community.infiniteflight.com/t/no-available-start-locations-for-a330-at-ksmf/358610

**Comment by NAZ32** [comment]
Ill add the a330 capable gates

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/72672823-59132900-3a3f-11ea-8d09-4f2299666720.jpg)
