### ISSUE TITLE
KDYT

### ISSUE THREAD

**Issue by TristinWoolf** [InfiniteFlightAirportEditing/Airports#576]
Duluth Sky Harbor Airport
Small airport, will do a quick redo of this. Shouldn't take me long! :)

**Comment by TristinWoolf** [comment]
Just finished this! Did a complete redo and sent it in for approval. Can someone label appropriately please? Thanks!

**Comment by TristinWoolf** [comment]
Approved. Someone with labeling abilities please remove the labels? I will close

**Comment by kilt46** [comment]
Still needs uploaded

**Comment by kilt46** [comment]
This is a Sea based Airport. Unlikely to be in IF

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20651879/b924522a-b4b3-11e6-86d2-4798cbbc2c7f.png)
