### ISSUE TITLE
MDBH-Maria Montez International Airport-BARAHONA-DOMINICAN REPUBLIC

### ISSUE THREAD

**Issue by RafaelPadilla29** [InfiniteFlightAirportEditing/Airports#5763]
# Airport Name
Maria Montez International Airport
# Country?
Dominican Republic
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by Czechoslovaki** [comment]
![image](https://user-images.githubusercontent.com/51279558/118213854-944f1d80-b423-11eb-8960-7fae775e9226.png)
