### ISSUE TITLE
VIKG-Kishangarh Airport-RAJASTHAN-INDIA

### ISSUE THREAD

**Issue by OmkarRathi** [InfiniteFlightAirportEditing/Airports#5764]
# Airport Name
Kishangarh Airport
# Country?
India
# Improvements that need to be made?
Needs to be added
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by hari-shreyas** [comment]
Omkar said he will not be able to do the airports so I would like to do this now. Could someone assign me to this airport?
Thanks!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103027612-cff05600-451b-11eb-8ef0-a92e85bc7686.png)
