### ISSUE TITLE
UTDD-Dushanbe International Airport-TAJIKISTAN

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#5766]
# Airport Name
Dushanbe International Airport
# Country?
Tajikistan
# Improvements that need to be made?
Scratch
# Are you working on this airport?
No
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Capital

**Comment by MajorTomMueller** [comment]
not the best source, but anyway:
https://vatrus.info/userupload/files/vatsim862634/UTDD.pdf

**Comment by AleksanderIF** [comment]
http://www.caica.ru/aiptjk/validaip/?lang=en better?

**Comment by MajorTomMueller** [comment]
Yes, just found the way to it. Thanks.
Text page:
http://www.caica.ru/aiptjk/validaip/aiptjk/ad/ad2/utdd/ad2-utdd-txt.pdf
Aerodrome chart:
http://www.caica.ru/aiptjk/validaip/aiptjk/ad/ad2/utdd/ad2-utdd-031-031-1.pdf
Docking chart;
http://www.caica.ru/aiptjk/validaip/aiptjk/ad/ad2/utdd/ad2-utdd-039-039-1.pdf

**Comment by AleksanderIF** [comment]
I want to take it.

**Comment by Czechoslovaki** [comment]
@AleksanderIF it's all yours.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103136919-1f549480-468a-11eb-89b5-4832d25383cf.png)
