### ISSUE TITLE
VNPL-Phaplu Airport-EAST-NEPAL

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#5767]
# Airport Name
Phaplu Airport
# Country?
Nepal
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101706569-01165400-3a4f-11eb-8072-3996c21f4cee.png)
