### ISSUE TITLE
KONO-Ontario Municipal Airport-OREGON-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#5768]
# Airport Name
Ontario Municipal
# Country?
:us:
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Oh Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/100522897-c9b3c780-3171-11eb-992f-072edd1d93a4.png)
