### ISSUE TITLE
KTVC-Cherry Capital Airport-MICHIGAN-USA

### ISSUE THREAD

**Issue by UpNorthAviation** [InfiniteFlightAirportEditing/Airports#577]
A small regional airport in northern Michigan, my hometown airport, I know it like the back of my hand :)

**Comment by dushyants19** [comment]
How's this going?

**Comment by dushyants19** [comment]
Are you in our slack?

**Comment by IFAEpat** [comment]
@dushyants19 he was kicked for being inactive, this is open to anyone! Seems good for newbies! :)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24935703/45c61ce6-1ee9-11e7-922a-08959fba3f76.png)

**Comment by moritzbabl** [comment]
Airport is not aligned with scenery
![cefb9ac2-e5e9-4fc5-92f7-26d92c3a4a9d](https://user-images.githubusercontent.com/19365980/36951201-20c80afc-2001-11e8-892c-74fdaf578326.png)
