### ISSUE TITLE
EGGP- Liverpool Airport-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by chriscroft20** [InfiniteFlightAirportEditing/Airports#578]
its called Liverpool Aiport,  close to Manchester, medium sized.

**Comment by IceBlue02** [comment]
@chriscroft20 I assume you are redoing this :)

**Comment by chriscroft20** [comment]
@IceBlue02 yeah, I wasn't sure how to add the labels

**Comment by chriscroft20** [comment]
sent for approval

**Comment by kilt46** [comment]
Missing main apron!
![image](https://cloud.githubusercontent.com/assets/14023167/15310438/740b6486-1bb5-11e6-978a-b1da9f2a2289.png)

**Comment by chriscroft20** [comment]
It's definitely there, I think maybe it got put to invisible when being reviewed or something. If you scroll down and just put the 'main apron' to visible again

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17250753/5e7afa9c-556b-11e6-9c00-6acba7c232e3.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18292612/c4eb3114-7453-11e6-9e65-d6deabf64a9d.png)

**Comment by dushyants19** [comment]
"there are a number of line fixes and the whole airport needs to be re positioned" ~~ @ItsW1ll

**Comment by ItsW1ll** [comment]
thanks bruno

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31441911-3dc4f3a4-ae5a-11e7-8680-7db6eaa41a6a.png)

**Comment by ItsW1ll** [comment]
I Think that's the old picture?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31444798-a9e50b3e-ae62-11e7-8672-f751b02e9689.png)

**Comment by ItsW1ll** [comment]
perfect!

**Comment by kilt46** [comment]
This area is currently dis-used
![image](https://user-images.githubusercontent.com/14023167/31446977-7ccf4908-ae66-11e7-9874-c650e0c5f40f.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31447009-8ee28416-ae66-11e7-93d6-6d12e498c63a.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45985693-08e3ac80-c02d-11e8-9c28-587bb064a0a4.png)
