### ISSUE TITLE
S49-Miller Memorial Airpark-OREGON-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#5780]
# Airport Name
Miller Memorial Airpark
# Country?
:us:
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/100522792-219dfe80-3171-11eb-9270-03146d1697cd.png)
