### ISSUE TITLE
OMBY-Sir Bani Yas Airport-ABU DHABI-UNITED ARAB EMIRATES

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5786]
# Airport Name
Sir Bani Yas Airport
# Country?
United Arab Emirates
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/100523148-d0433e80-3173-11eb-8c0e-c24dcfa05741.png)
