### ISSUE TITLE
OMDL-Delma Airport-ABU DHABI-UNITED ARAB EMIRATES

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5788]
# Airport Name
Delma Airport
# Country?
United Arab Emirates
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/100544546-28358000-321c-11eb-8d6a-a8267df31e59.png)
