### ISSUE TITLE
KDLH-Duluth International Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by TristinWoolf** [InfiniteFlightAirportEditing/Airports#579]
Duluth International Airport

Will completely redo this airport from head to toe. This is officially my biggest project as an Airport Editor so far! Will get started on this right away! As usual, if someone with labeling capabilities could label and assign properly, it would be appreciated! Wish I could do it myself so I don't have to keep asking everyone else but oh well! Thanks!

**Comment by TristinWoolf** [comment]
Sent in for approval!

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20411341/bb4a124e-ace6-11e6-9114-2f21acf38ee8.png)

**Comment by ryu12332** [comment]
ISSUE: Many lines/taxiways not snapped or overcurved.

**Comment by TristinWoolf** [comment]
I’ll take a look at this.

**Comment by LoganIsLogan14** [comment]
What's the progress on this? I can help if needed.

**Comment by LoganIsLogan14** [comment]
Ok cool. I'll start working on it tonight. What needed to be done in the first place? I see that it needs to be realigned. Anything else?

**Comment by LoganIsLogan14** [comment]
I can do a full rework if needed.

**Comment by brunocr98** [comment]
You can do a rework for this airport if you want. Don't be surprised to find some outdated parts on it when putting it against the imagery.

**Comment by LoganIsLogan14** [comment]
Ok

**Comment by danisrils39** [comment]
Any progress here Logan? If not I can take it off your hands. :)

**Comment by danisrils39** [comment]
How is it going with KDLH?

**Comment by danisrils39** [comment]
Sent to OR.

**Comment by LoganIsLogan14** [comment]
Sorry I have been gone. I’ve been trying to get my life back on track. I’m back now and I would like to say thank you to danisrils39 for taking over.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/58843011-1551e780-8647-11e9-89c3-917b5525d2ad.jpg)
