### ISSUE TITLE
S03-Ashland Municipal Sumner Parker Field-OREGON-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#5796]
# Airport Name
Ashland Muni. Sumner Parker Field
# Country?
:us:
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/100544713-28824b00-321d-11eb-99fe-8c3986a6272d.png)
