### ISSUE TITLE
ETMN-Nordholz Airbase-Niedersachsen-GERMANY

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#5797]
# Airport Name
Nordholz Airbase
# Country?
Germany
# Improvements that need to be made?
First Edit for IF
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
N/A

**Comment by azuma-server** [comment]
Airport Name
< Nordholz Airbase >

Country?
< Germany >

Improvements that need to be made?
< Redo the whole base >

Are you working on this airport?
< Yes >

Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by MajorTomMueller** [comment]
https://www.milais.org/publications.php?c2V0bGFuZz1lbiZmcm1pZD0w

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124355204-99377e80-dbd5-11eb-9dfa-5d628c697371.png)
