### ISSUE TITLE
YCBP-Coober Pedy Airport-SOUTH AUSTRALIA-AUSTRALIA

### ISSUE THREAD

**Issue by IFC-Jennifer23** [InfiniteFlightAirportEditing/Airports#5799]
#Airport Name
Coober Pedy Airport
#Country?
:au:
#Improvements that need to be made?
Full Redo
#Are you working on this airport?
Yes
#Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by Czechoslovaki** [comment]
![image](https://user-images.githubusercontent.com/51279558/134030581-1303edb9-aaae-4633-8eb0-49b47fc75b67.png)
