### ISSUE TITLE
OMAQ-Qarnayn Airport-UNITED ARAB EMIRATES

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5800]
# Airport Name
Qarnayn Airport
# Country?
United Arab Emirates
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/100544558-469b7b80-321c-11eb-87ab-a6a6566a0e3f.png)
