### ISSUE TITLE
HLLM-Mitiga International Airport-LYBIA

### ISSUE THREAD

**Issue by Boeing757** [InfiniteFlightAirportEditing/Airports#5809]
# Airport Name
Mitiga International Airport
# Country?
Libya
# Improvements that need to be made?
Adding gates and taxiways 
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway)

**Comment by MajorTomMueller** [comment]
https://caa.gov.ly/ais/wp-content/uploads/2017/AIP/AD/HLLM.pdf

**Comment by Boeing757** [comment]
Thanks

**Comment by MinhNguyN** [comment]
I will take this:)

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/133866748-d5be8bfc-3df6-4301-b66e-65d0ee8b334b.png)
