### ISSUE TITLE
ZGSZ-Shenzhen/Boan Airport-GUANGDONG-CHINA

### ISSUE THREAD

**Issue by nick-if** [InfiniteFlightAirportEditing/Airports#581]

**Comment by nick-if** [comment]
I submitted it for review

**Comment by IFAEpat** [comment]
Taking this one too

**Comment by IFAEpat** [comment]
Basically half the airport's missing in this one in WEDbing

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21468628/dfb70c64-c9e1-11e6-9b1c-42573511683f.png)

**Comment by kilt46** [comment]
Redone from scratch

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50736696-283eb980-1186-11e9-8ee2-086bc67610ee.png)

**Comment by kilt46** [comment]
Duplicate spawns fixed. Buildings Removed
