### ISSUE TITLE
DGSI-Kumasi Airport-ASHANTI-GHANA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5813]
# Airport Name
Kumasi Airport
# Country?
Ghana
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101267441-62bc8280-371e-11eb-99b2-82d09842036a.png)
