### ISSUE TITLE
SGME-Mariscal Estigarribia Airport-BOQUERON-PARAGUAY

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5815]
# Airport Name
Mariscal Estigarribia International Airport
# Country?
Paraguay
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101262925-8e803e00-3707-11eb-911a-6d4d2dc90952.png)
