### ISSUE TITLE
SGPJ-Pedro Juan Caballero Airport-AMAMBAY-PARAGUAY

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5816]
# Airport Name
Pedro Juan Caballero Airport
# Country?
Paraguay
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101262823-ef5b4680-3706-11eb-9d52-258246db0435.png)
