### ISSUE TITLE
VNTR-Tumlingtar Airport-EAST-NEPAL

### ISSUE THREAD

**Issue by Captainflight** [InfiniteFlightAirportEditing/Airports#5817]
# Airport Name
< Tumlingtar >
# Country
< Nepal>
# Improvements that need to be made?
< redone from scratch >
# Are you working on this airport?
<Yes>
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, low)
< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103101905-5621a080-45df-11eb-9fad-29db18817fa5.png)
