### ISSUE TITLE
KMKN-Comanche County-City Airport-TEXAS-USA

### ISSUE THREAD

**Issue by suhasjatla** [InfiniteFlightAirportEditing/Airports#5839]
# Airport Name
Comanche County-City Airport
# Country?
USA
# Improvements that need to be made?
Full redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102951541-b6ef9280-4492-11eb-87b2-82c795224d62.png)
