### ISSUE TITLE
LGKR 

### ISSUE THREAD

**Issue by chriscroft20** [InfiniteFlightAirportEditing/Airports#584]
Small airport on the greek island of Corfu

**Comment by chriscroft20** [comment]
sent for approval

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17276757/2e450a50-56f8-11e6-905e-5a32b2ac6ebe.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17832721/2ce1b6a4-66cf-11e6-81c9-f138214bb331.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17832723/34f05f58-66cf-11e6-902c-d8aa5d628855.png)
