### ISSUE TITLE
GVMT-Mosteiros Airport-CAPE VERDE

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5840]
# Airport Name
Mosteiros Airport
# Country?
Cape Verde
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101243334-34f71f80-36c5-11eb-877f-c9d543a0c791.png)
