### ISSUE TITLE
5S9-Valley View-OREGON-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#5841]
# Airport Name
Valley View
# Country?
:us:
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Why wouldn't I be
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101106854-a5ebe980-3596-11eb-9a53-5c233c237fe5.png)
