### ISSUE TITLE
KAAS-Taylor County Airport-KENTUCKY-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#5844]
# Airport Name
< Taylor County Airport >
# Country?
< USA >
# Improvements that need to be made?
< Manual edit >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

![Full(9)](https://user-images.githubusercontent.com/59462519/101078996-ca4bc400-359e-11eb-8b50-40bceb744b4e.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102951237-f669af00-4491-11eb-961e-2b6f9103eb9c.png)
