### ISSUE TITLE
FSAS-Assumption Island Airport-SEYCHELLES

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5849]
# Airport Name
Assumption Island Airport
# Country?
Seychelles
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101221813-1144c280-364e-11eb-9334-fd5b40d3641b.png)
