### ISSUE TITLE
VHXX-Kai Tak Airport-HONG KONG-CHINA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#585]
Being done by Axel.

**Comment by JcFl4** [comment]
How are you doing this? It has to be accurate, and right now Kai Tak is pretty much non-existent. Curious to know!

**Comment by Giacomo11** [comment]
Favourite airport, can't wait for it to be made!

**Comment by liamkirky** [comment]
@axelbeder what's this progress like

**Comment by IFAEpat** [comment]
@AxelBeder anything? I would like a go at this.

**Comment by bavAVIA** [comment]
Shouldn't we delete this?

**Comment by lalomarlin** [comment]
Why?

**Comment by brunocr98** [comment]
@lalomarlin this airport is no where in its original location. Plus it's very difficult to find imagery and charts as of the date of the airport's closure.

**Comment by moritzbabl** [comment]
Is there any progress @AxelBeder ? I'm currently searching for charts and images for the airport

**Comment by GiacomoLaw** [comment]
Such a pity, this would have been an awesome airport! 😭

**Comment by moritzbabl** [comment]
done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25109005/6977a3fc-239f-11e7-965b-525cbe15ea0a.png)

**Comment by kilt46** [comment]
Boundary Cleanup
