### ISSUE TITLE
VCCB-Batticaloa Airport-BATTICALOA-SRI LANKA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5852]
# Airport Name
Batticaloa Airport
# Country?
Sri Lanka
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101216768-b27b4b00-3645-11eb-871f-857cfedf5d9e.png)
