### ISSUE TITLE
LEBA-Cordoba Airport-ANDALUCIA-SPAIN

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5855]
# Airport Name
Cordoba Airport
# Country?
Spain
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101222596-b2804880-364f-11eb-8e6c-edea5f70972e.png)
