### ISSUE TITLE
YTGT-The Granites Airport-NORTHERN TERRITORY-AUSTRALIA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5856]
# Airport Name
The Granites Airport
# Country?
Australia
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101243503-6ae8d380-36c6-11eb-9ba2-55658969276c.png)
