### ISSUE TITLE
RPVU

### ISSUE THREAD

**Issue by FlyingEagle0112** [InfiniteFlightAirportEditing/Airports#5857]
# Airport Name
< Romblon Airport >
# Country?
< Philippines >
# Improvements that need to be made?
< From scratch >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by MajorTomMueller** [comment]
Duplicate #5714
