### ISSUE TITLE
RPLU-Lubang Airport-MIMAROPA-PHILIPPINES

### ISSUE THREAD

**Issue by LesterXavier** [InfiniteFlightAirportEditing/Airports#5859]
# Airport Name
< Lubang Airport >
# Country?
< Philippines >
# Improvements that need to be made?
< Rework from scratch >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103111265-d44a6b00-4610-11eb-9f17-f6c3d23941df.png)
