### ISSUE TITLE
VRMM-Ibrahim Nasir International Airport-MALE-MALDIVES

### ISSUE THREAD

**Issue by sumith11** [InfiniteFlightAirportEditing/Airports#586]
Malé International Airport

**Comment by ReflexRSM** [comment]
Sent for approval

**Comment by dushyants19** [comment]
Approved by henrik. [Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/1020bc0e2a118649ef073c21c3263d04866ec3ec)

**Comment by dushyants19** [comment]
Many issues

**Comment by MajorTomMueller** [comment]
Latest Google maps imagery allows for a full rework. It is time to do so.

**Comment by MajorTomMueller** [comment]
![VRMM-git](https://user-images.githubusercontent.com/26853210/107750425-e9d83900-6d13-11eb-82ec-01ed8aa9088c.png)
