### ISSUE TITLE
GVBR-Esperadinha Airport-CAPE VERDE

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5870]
# Airport Name
Esperadinha Airport
# Country?
Cape Verde
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101267502-073ec480-371f-11eb-9bd5-dbab106b952f.png)
