### ISSUE TITLE
FAUS-Ulusaba Airport-MPUMALANGA-SOUTH AFRICA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#5871]
# Airport Name
Ulusaba Airport
# Country?
South Africa
# Improvements that need to be made?
New Airport
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103111346-b9c4c180-4611-11eb-80bf-622c924d5e2d.png)
