### ISSUE TITLE
SSRW-Fazenda J. Campos-SAO PAULO-BRAZIL

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#5874]
# Airport Name
Fazenda J. Campos
# Country?
Brazil
# Improvements that need to be made?
Redone
# Are you working on this airport?
Done
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![Uploading image.png…]()

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102946768-37a89180-4487-11eb-87c7-6442ce938c7e.png)
