### ISSUE TITLE
KRYN-Ryan Field Airport-ARIZONA-USA

### ISSUE THREAD

**Issue by LesterXavier** [InfiniteFlightAirportEditing/Airports#5879]
# Airport Name
< Ryan Field >
# Country?
< USA >
# Improvements that need to be made?
< Full rework >
# Are you working on this airport?
< ye >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102949597-4e061b80-448e-11eb-9955-44f8694f48f6.png)
