### ISSUE TITLE
YBBN-Brisbane Airport-QUEENSLAND-AUSTRALIA

### ISSUE THREAD

**Issue by nick-if** [InfiniteFlightAirportEditing/Airports#588]
♻️

**Comment by dushyants19** [comment]
Duplicate, #401

**Comment by Ksisky** [comment]
Other things have taken up a lot of my time, and I don't know if I'll be able to finish by global release. I have about half done, and I'm willing to send a half-complete apt.dat to anyone who wants to take this up from me. I'm unassigning myself so people can find this as needing completion. I will continue to work slowly until it is taken up, just tag me in this thread so I can send you the file. Thank for understanding!

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21489207/5cc007e8-cbad-11e6-82c2-a6d64c76805b.png)

**Comment by ryu12332** [comment]
ISSUE: There are two gate 76As. I believe one is ment to say Gate 76B but I’m not sure.

**Comment by MBeringuy** [comment]
Improvements made and Terminal excluded.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90572534-e2c3da00-e179-11ea-9607-7fff23c9068e.png)

**Comment by henrus1** [comment]
I've started to play around with adding the new runway. This was with limited success due to the lack of high quality images that show the new runway.

The Xplane DAT for YBBN has been updated, can this be used?
https://gateway.x-plane.com/airports/YBBN/show

**Comment by MajorTomMueller** [comment]
If you are interested in contributing join the team via IFC.

**Comment by becarboner3000** [comment]
@GBKarp will be allowed to add the new runway and a ramp (no rework).

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124353338-7e600c80-dbcb-11eb-9108-3987eef0f98a.png)
