### ISSUE TITLE
KTZR-Bolton Field Airport-OHIO-USA

### ISSUE THREAD

**Issue by LesterXavier** [InfiniteFlightAirportEditing/Airports#5880]
# Airport Name
< Bolton Field >
# Country?
< USA >
# Improvements that need to be made?
< Full rework >
# Are you working on this airport?
< Ya >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103326690-2b887b00-4a17-11eb-9ece-9cf1c6b29fa5.png)
