### ISSUE TITLE
KGNC-Gaines County Airport-TEXAS-USA

### ISSUE THREAD

**Issue by suhasjatla** [InfiniteFlightAirportEditing/Airports#5881]
# Airport Name
Gaines County Airport
# Country?
USA
# Improvements that need to be made?
Full redo
# Are you working on this airport?
Yup
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104110576-8edb9e00-529e-11eb-90a8-1441f64cb8ba.png)
