### ISSUE TITLE
FMNW-Antsohihy Airport-MAHAJANGA-MADAGASCAR

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5883]
# Airport Name
Antsohihy Airport
# Country?
Madagascar
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101415997-84e50a80-38ae-11eb-8e53-a33808a62014.png)
