### ISSUE TITLE
VTBS-Bangkok/Suvarnabhumi Airport-SAMUT PRAKAN-THAILAND

### ISSUE THREAD

**Issue by nick-if** [InfiniteFlightAirportEditing/Airports#589]
hi

**Comment by cboisselier** [comment]
I'm on that one @dushyants19

**Comment by dushyants19** [comment]
@cboisselier hows this going

**Comment by IFAEpat** [comment]
@cboisselier ?

**Comment by dushyants19** [comment]
Unassigned @cboisselier

**Comment by Aviationluver** [comment]
I can re-do this one.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20459567/fd8a58ca-ae8b-11e6-92af-fed42b5dcfea.png)

**Comment by moritzbabl** [comment]
@aads552 will do some minor fixes

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/69682179-51fb1a80-108f-11ea-8644-2de6842623d7.jpg)
