### ISSUE TITLE
SUVO-Vichadero Airport-RIVERA-URUGUAY

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#5892]
# Airport Name
Vichadero
# Country?
Uruguay
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102944070-57d45280-447f-11eb-9ae5-62607de4c4d9.png)
