### ISSUE TITLE
SUPU-Tydeo Larre Borges International Airport-PAYSANDU-URUGUAY

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#5893]
# Airport Name
Tydeo Larre Borges International Airport
# Country?
Uruguay
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102943831-c7960d80-447e-11eb-8de7-365d085c4581.png)
