### ISSUE TITLE
KNGU-Chambers Field-Virginia-USA

### ISSUE THREAD

**Issue by Jeremy351** [InfiniteFlightAirportEditing/Airports#5894]
# Airport Name
Naval Air Station Norfolk - Chambers Field
# Country?
United States 
# Improvements that need to be made?
Full redone
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by MajorTomMueller** [comment]
Make sure to name the airport in WED "Chambers" to have correct Tower and Ground ATC naming in IF.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102950959-5e6bc580-4491-11eb-935e-6c24a6d39aa3.png)
