### ISSUE TITLE
DAON-Zenata / Messali El Hadj-TLEMCEN-ALGIER 

### ISSUE THREAD

**Issue by falous** [InfiniteFlightAirportEditing/Airports#5897]
Pays?
Algérie
Des améliorations à apporter?
Travailler à partir de zéro
Travaillez-vous sur cet aéroport?
oui

**Comment by Czechoslovaki** [comment]
Hi there,

I've never seen you around. May I ask about your unexpected presence here? You are required to join the Slack team for communication with other members.

**Comment by falous** [comment]
Yes

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Claudio <notifications@github.com>
Envoyé : Wednesday, December 9, 2020 11:20:58 PM
À : InfiniteFlightAirportEditing/Airports <Airports@noreply.github.com>
Cc : falous <tonytoca@live.fr>; Author <author@noreply.github.com>
Objet : Re: [InfiniteFlightAirportEditing/Airports] DAON (#5897)


Hi there,

I've never seen you around. May I ask about your unexpected presence here? You are required to join the Slack team for communication with other members.

**Comment by falous** [comment]
how to join slack

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Claudio <notifications@github.com>
Envoyé : Wednesday, December 9, 2020 11:20:58 PM
À : InfiniteFlightAirportEditing/Airports <Airports@noreply.github.com>
Cc : falous <tonytoca@live.fr>; Author <author@noreply.github.com>
Objet : Re: [InfiniteFlightAirportEditing/Airports] DAON (#5897)


Hi there,

I've never seen you around. May I ask about your unexpected presence here? You are required to join the Slack team for communication with other members.

**Comment by Czechoslovaki** [comment]
https://airportediting.com/
Check here to join the team.

**Comment by falous** [comment]
> Salut,
> 
> Je ne t'ai jamais vu. Puis-je vous poser des questions sur votre présence inattendue ici? Vous devez rejoindre l'équipe Slack pour communiquer avec les autres membres.

OUI mes commment

**Comment by falous** [comment]
how to join slack

**Comment by MBeringuy** [comment]
@falous please do not close issues. To do this, contact a supervisor.

**Comment by MBeringuy** [comment]
Open to any member of the editing team who wants to edit.

**Comment by falous** [comment]
this good

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103321411-2586a000-49ff-11eb-8dfe-ab5c178bb39e.png)
