### ISSUE TITLE
KEVY-Summit Airport-DELAWARE-UNITED STATES

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#5899]
# Airport Name
Summit Airport
# Country?
USA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by MajorTomMueller** [comment]
DGAA ready 😁?

**Comment by OscarConklin** [comment]
Yes

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102950164-a853ac00-448f-11eb-8513-4aed42f84560.png)
