### ISSUE TITLE
ZGGG-Guangzhou Baiyun Airport-GUANGDONG-CHINA

### ISSUE THREAD

**Issue by nick-if** [InfiniteFlightAirportEditing/Airports#590]

**Comment by dushyants19** [comment]
Nick, this is not the place to ask for help.

**Comment by Ksisky** [comment]
I'll take it.

**Comment by IFAEpat** [comment]
Imagery is messed up, Kevin said he can't do this

**Comment by IFAEpat** [comment]
Decided to take these abandoned A380 Airports. We need to get these done!

**Comment by IFAEpat** [comment]
Imagery issues, can a windows user please do this? 🙏🏼

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21566036/962bc918-ce64-11e6-93ed-74060b5c4e0c.png)

**Comment by AnthonyCK** [comment]
Sent for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/83468447-63f4b600-a442-11ea-9552-a9998c19359f.png)
