### ISSUE TITLE
URWA-Astrakhan-ASTRAKHAN-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#5900]
# Airport Name
< Astrakhan Boris M. Kustodiev Intl Airport >
# Country?
< 🇷🇺  >
# Improvements that need to be made?
< redo >
# Are you working on this airport?
< yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< GP2 >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103032316-5e1d0a00-4525-11eb-8275-7b7f99e3cc53.png)
