### ISSUE TITLE
SUAA-Angel S. Adami Airport-MONTEVIDEO-URUGUAY

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#5902]
# Airport Name
Angel S. Adami Airport
# Country?
Uruguay
# Improvements that need to be made?
Full Rework
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103101281-7865ef00-45dc-11eb-8baa-070688a662a9.png)
