### ISSUE TITLE
KLMO-Vance Brand-COLORADO-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#5903]
# Airport Name
Vance Brand
# Country?
:us:
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101984678-7f8a1600-3c48-11eb-8a80-c7119fd13365.png)
