### ISSUE TITLE
SAAK-Isla Martin Garcia Airport-COLONIA-ARGENTINA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5906]
# Airport Name
Isla Martin Garcia Airport
# Country?
Argentina
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101984860-a268fa00-3c49-11eb-923b-e485afa471b1.png)
