### ISSUE TITLE
KPAH-Barkley Regional Airport-KENTUCKY-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#5907]
# Airport Name
Barkley Regional Airport
# Country?
:us:
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![Uploading image.png…]()

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101984551-bdd30580-3c47-11eb-8121-0103e34f8e33.png)
