### ISSUE TITLE
VOSM-Salem Airport-TAMIL NADU-INDIA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#5908]
# Airport Name
Salem Airport
# Country?
🇮🇳 
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101984761-13f47880-3c49-11eb-89fa-b6cbf128e643.png)
