### ISSUE TITLE
VHSK

### ISSUE THREAD

**Issue by nick-if** [InfiniteFlightAirportEditing/Airports#591]

**Comment by nick-if** [comment]
![screen shot 2016-05-16 at 7 10 14 pm](https://cloud.githubusercontent.com/assets/19368407/15288039/00241a10-1b9a-11e6-829b-d6ae35a7f317.png)
Help when I do this, the airport appears ON TOP of the map view, so how do I know where to add, the airport is covering it

Someone just teach me how to use WED

**Comment by nick-if** [comment]
this WED is rubbish those idiot computer designers had to make it so complicated. wow the things look so digital not modern like apple desktops these idiot designers

**Comment by Arzanex** [comment]
Ill take this one

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21749788/0fac1168-d56c-11e6-9cd5-b8267d2fb9db.png)
