### ISSUE TITLE
KIFP-Laughlin/Bullhead City International Airport-ARIZONA-USA

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#5910]
# Airport Name
Laughlin/Bullhead City International Airport
# Country?
USA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102949351-b7395f00-448d-11eb-8bce-fc75c1cae3a2.png)
