### ISSUE TITLE
VABV-Bhavnagar-GUJARAT-INDIA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#5912]
# Airport Name
Bhavnagar
# Country?
🇮🇳 
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
It's a quick clap
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101999823-6912a780-3ca6-11eb-89ec-9411edae6d35.png)
