### ISSUE TITLE
VAJL-Jalgaon Airport-MAHARASHTRA-INDIA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#5914]
# Airport Name
Jalgaon
# Country?
🇮🇳 
# Improvements that need to be made?
New
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/101999964-b6434900-3ca7-11eb-95d8-b9368681b3ca.png)
