### ISSUE TITLE
KBDU-Boulder Municipal-COLORADO-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#5915]
# Airport Name
Boulder Municipal
# Country?
:us:
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Niedrig

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102147198-fb928280-3e2f-11eb-8b5f-ad41940564dc.png)
