### ISSUE TITLE
LGIR

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#592]
Iraklion Airport, I will do that

**Comment by moritzbabl** [comment]
I've finished it, will send it for approval soon (just posted it in peer-review)

**Comment by moritzbabl** [comment]
It's finished, I just sent the e-mail

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17276594/50c028bc-56f3-11e6-8c3e-b059f70e2878.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17276732/637d2aa0-56f7-11e6-91df-1b515fda2646.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17833450/457757dc-66e3-11e6-82b3-acb357033c67.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17833452/4d5db608-66e3-11e6-9b68-70384e3f8923.png)

**Comment by moritzbabl** [comment]
Improved this one
