### ISSUE TITLE
VOPC-Puducherry Airport-Puducherry-India

### ISSUE THREAD

**Issue by KaalicharanDH** [InfiniteFlightAirportEditing/Airports#5926]
# Airport Name
Puducherry Airport
# Country?
India
# Improvements that need to be made?
Full rework
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102827564-656ad900-43a8-11eb-9820-b8000bb5cdaa.png)
