### ISSUE TITLE
VERP-Swami Vivekananda Airport-Chhattisgarh-India

### ISSUE THREAD

**Issue by KaalicharanDH** [InfiniteFlightAirportEditing/Airports#5927]
# Airport Name
Swami Vivekananda Airport
# Country?
India
# Improvements that need to be made?
Full _Rework_
# Are you working on this airport?
_Yes_
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102827206-c514b480-43a7-11eb-8885-e16be39c8cf2.png)
