### ISSUE TITLE
KTXK-Texarkana Regional-Webb Field-ARKANSAS-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#5928]
# Airport Name
Texarkana Regional-Webb Field
# Country?
🇺🇸 
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102299229-37087c00-3f18-11eb-8c1c-e654c7c77c73.png)
