### ISSUE TITLE
KSMX-Santa Maria Airport/Capt G Allan Hancock-CALIFORNIA-USA

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#5929]
# Airport Name
Santa Maria Airport/Capt G Allan Hancock
# Country?
USA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102948432-a12a9f00-448b-11eb-9555-baf1c50e166a.png)
