### ISSUE TITLE
KDTW-Detroit Metropolitan Airport-MICHIGAN-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#593]
Requested by Josh.

**Comment by planemadnews** [comment]
I will take this on....

**Comment by planemadnews** [comment]
sent for evaluation

**Comment by planemadnews** [comment]
sent in for approval

**Comment by planemadnews** [comment]
Can someone finish KDTW for me please.... I have done most of the hard work, just a few things to do. I will send the person to do it the file I have been using

**Comment by dushyants19** [comment]
Anyone willing to continue can get the apt.dat by @planemadnews from himself.

**Comment by dushyants19** [comment]
Latest version as sent to me for review.

https://gist.github.com/dushyants19/04714d4fcf909cfcb3d04d2d75b6122e

**Comment by dushyants19** [comment]
-  Most objects are not aligned with WEDbing scenery.
 - Taxiway shoulder missing for nearly all taxiways
- Many objects (taxiway/lines) are missing
 - L.C Smith Terminal's west arm not drawn
- ILS Critical Centerlines missing before most hold shorts
- Stopway lengths of most runways are incorrect 
- Multiple Taxiway Y's

Work which is mostly needed.

**Comment by ryu12332** [comment]
I will start to put some work in.

**Comment by dushyants19** [comment]
Hi @ryu12332, are you in our slack team yet? This airport might be huge for a beginner. If you arent, please email airports@liveflightapp.com

**Comment by IFAEpat** [comment]
Up for grabs, I guess...

**Comment by ryu12332** [comment]
I submitted V1 of the airport. The only work left should be taxiway shoulders and roadways.

**Comment by dushyants19** [comment]
done by @ryu12332

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21751097/c5a5fa50-d586-11e6-96bf-6249f9221080.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59394087-cac22080-8d54-11e9-9333-2f98e24a437c.jpg)

**Comment by RyanEpps** [comment]
<img width="831" alt="Screen Shot 2021-08-08 at 6 57 13 PM" src="https://user-images.githubusercontent.com/20650961/128648127-8f442dfe-6ab2-4425-9720-1ce3fe38c769.png">
