### ISSUE TITLE
KSCK-Stockton Metropolitan-CALIFORNIA-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#5930]
# Airport Name
Stockton Metropolitan
# Country?
USA
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
10K+

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102717451-f443fc80-42a7-11eb-9e40-7ca19d711c57.png)
