### ISSUE TITLE
KCXY-Capital City-PENNSYLVANIA-USA

### ISSUE THREAD

**Issue by davide-dc** [InfiniteFlightAirportEditing/Airports#5931]
# Airport Name
Capital City
# Country?
US
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102945517-881df000-4483-11eb-97f1-25750c6f92f1.png)
