### ISSUE TITLE
OEDR-King Abdulaziz Air Base-ASH SHARQIYAH-SAUDI ARABIA

### ISSUE THREAD

**Issue by davide-dc** [InfiniteFlightAirportEditing/Airports#5932]
# Airport Name
King Abdulaziz AB
# Country?
Saudi Arabia
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
10.000ft runways

**Comment by MajorTomMueller** [comment]
Wow, have fun with this one @davide-dc.
Are there any information for spawn names available?

**Comment by MajorTomMueller** [comment]
On users request taken over,

**Comment by MajorTomMueller** [comment]
![OEDR-git](https://user-images.githubusercontent.com/26853210/135136145-4cce0626-aa9f-4681-8b23-0349533ed6a7.png)
