### ISSUE TITLE
PADL-Dillingham-ALASKSA-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#5933]
# Airport Name
Dillingham
# Country?
:us:
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102561064-5b3f9680-4099-11eb-923f-f67d0b2a912f.png)
