### ISSUE TITLE
YPLC-Port Lincoln Airport-SOUTH AUSTRALIA-AUSTRALIA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5936]
# Airport Name
Port Lincoln Airport
# Country?
Australia
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102553867-30e5dd00-4089-11eb-8f11-af20f7247da1.png)
