### ISSUE TITLE
LFPN-Toussus Le Noble-ÎLE-DE-FRANCE-FRANCE

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#5937]
# Airport Name
Toussus Le Noble
# Country?
🇫🇷 
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102690231-96d97e00-41c9-11eb-8b5f-6ee01394a009.png)
