### ISSUE TITLE
YKSC-Kingscote/Kangaroo Island Airport-SOUTH AUSTRALIA-AUSTRALIA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5938]
# Airport Name
Kingscote/Kangaroo Island Airport
# Country?
Australia
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102553445-78b83480-4088-11eb-8cfc-eff0e6715b3f.png)
