### ISSUE TITLE
AYHK-Hoskins Airport-WEST NEW BRITAIN-PAPUA NEW GUINEA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5939]
# Airport Name
Hoskins Airport
# Country?
Papua New Guinea
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102555483-7e177e00-408c-11eb-87f9-025e93a66a17.png)
