### ISSUE TITLE
LXGB-Gibraltar Airport-GIBRALTAR-UNITED KINGDOM

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#594]
I'll do this one.

**Comment by Aviationluver** [comment]
Airport has been addd to the repo.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20649434/c51198b4-b485-11e6-8bdc-22baf4624e60.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53694868-2ce4b000-3d7a-11e9-972c-d8777bf4485b.png)
