### ISSUE TITLE
AYTK-Tokua Airport-EAST NEW BRITAIN-PAPUA NEW GUINEA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5940]
# Airport Name
Tokua Airport
# Country?
Papua New Guinea
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102555117-be2a3100-408b-11eb-9eb2-0414317f0942.png)
