### ISSUE TITLE
VORY-Rajahmundry Airport-Andhra Pradesh-India

### ISSUE THREAD

**Issue by KaalicharanDH** [InfiniteFlightAirportEditing/Airports#5942]
# Airport Name
Rajahmundry Airport
# Country?
India
# Improvements that need to be made?
Full Rework
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102826787-fa6cd280-43a6-11eb-82e7-a934fdb98eb8.png)
