### ISSUE TITLE
SPGL

### ISSUE THREAD

**Issue by TristinWoolf** [InfiniteFlightAirportEditing/Airports#595]
Chagual Airport
Small airport in Peru with an AMAZING approach that will not take long at all to do. I will take this one myself and get it done quickly! If someone can please add proper labels, that would be great! Thanks!

**Comment by TristinWoolf** [comment]
Already finished and sent it in! It was super easy to do and quick. Just waiting for approval now. Proper labeling would be appreciated until it is approved.

**Comment by TristinWoolf** [comment]
Approved by @henrikbg and added to the repo.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20651075/89bf5814-b4a3-11e6-8513-9c2ff587d065.png)
