### ISSUE TITLE
LFOX-Etampes Mondesir-ÎLE-DE-FRANCE-FRANCE

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#5955]
# Airport Name
Etampes Mondseir
# Country?
🇫🇷 
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Definitely
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Faible

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102690137-ed928800-41c8-11eb-8110-84fa41bf0600.png)
