### ISSUE TITLE
LFFY-Etrepagny-HAUTE-NORMANDIE-FRANCE

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#5957]
# Airport Name
Etrepagny
# Country?
🇫🇷 🥖 
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102690019-3bf35700-41c8-11eb-91b2-05b494fb61d5.png)
