### ISSUE TITLE
LFPP-Le Plessis-Belleville-PICARDIE-FRANCE

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#5958]
# Airport Name
Le Plessis Belleville
# Country?
🇫🇷 
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102689936-950ebb00-41c7-11eb-800f-b5044ed6db35.png)
