### ISSUE TITLE
LFSL-Brive Souillac Airport-NOUVELLE AQUITAINE-FRANCE

### ISSUE THREAD

**Issue by Jeremy351** [InfiniteFlightAirportEditing/Airports#5959]
# Airport Name
Brive Souillac
# Country?
France
# Improvements that need to be made?
Full redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by Jeremy351** [comment]
It is a new airport with an old ICAO code.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102819457-1b2e2b80-4399-11eb-91bf-c8aef0af945c.png)
