### ISSUE TITLE
NZCH-Christchurch Airport-CANTERBURY-NEW ZEALAND

### ISSUE THREAD

**Issue by lachieee** [InfiniteFlightAirportEditing/Airports#596]
Christchurch International Airport - New Zealand.

**Comment by lachieee** [comment]
Christchurch International Aiport - New Zealand.

**Comment by lachieee** [comment]
Currently editing.

**Comment by NickArt1342** [comment]
@lachieee Please accept the invitation on your profile to the infinite flight repository so we can assign you to the issue.

**Comment by lachieee** [comment]
@NickArt1342 Done?

**Comment by NickArt1342** [comment]
Yep, there you go ;)

**Comment by lachieee** [comment]
Sent to email for submission - new taxi lines, added taxiway edge lights, additional ramp starts, [runways have been moved]

**Comment by IFAEpat** [comment]
Can someone else do this? Major misalignments

**Comment by IFAEpat** [comment]
Are you still doing it, @lachieee ?

**Comment by TristinWoolf** [comment]
@IFAEpat He is doing it, I believe, as a complete redo. I would assume that all the issues you see will be fixed when his version is submitted, just as if he was redoing a bad X-Plane file. :)

**Comment by lachieee** [comment]
5/09/16 Still finishing this airport. Will be busy for the next two and a half months however and will continue after.

**Comment by IFAEpat** [comment]
Now has scheduled A3i80 flights!

@lachieee how's this going?

**Comment by IFAEpat** [comment]
It seems lachlan isn't on slack, guess he quit, up for grabs :)

**Comment by IFAEpat** [comment]
It seems Lachlan isn't on slack anymore, guessing he quit, up for grabs :)

**Comment by lachieee** [comment]
Not on Slack, as my account has been removed - likely due to inactivity? As mentioned before, 

> 5/09/16 Still finishing this airport. Will be busy for the next two and a half months however and will continue after.

Currently, It is the 3/11/16. Being in New Zealand I have High School Exams upcoming right through from now until the 27th of November. I would prefer to have this time to study, and will continue to work on this airport after. I have completed all major parts of the airport, I last stopped at the point of checking that things were snapped and aligned.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21121916/bc6123fe-c094-11e6-93e8-f37062c5af1c.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/77370140-f7bd4e00-6d3e-11ea-80bd-3f0463edaa6f.jpg)
