### ISSUE TITLE
LFTW-Nimes Garons-OCCITANIE-FRANCE

### ISSUE THREAD

**Issue by Jeremy351** [InfiniteFlightAirportEditing/Airports#5960]
# Airport Name
Nîmes Garons
# Country?
France
# Improvements that need to be made?
Full redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102819687-90016580-4399-11eb-956f-52bc5b82072a.png)
