### ISSUE TITLE
KGUC-Gunnison-Crested Butte Regional-COLORADO-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#5961]
# Airport Name
Gunnison-Crested Butte Regional
# Country?
🇺🇸 
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102716171-b80c9e00-429f-11eb-978c-d59eb45aa728.png)
