### ISSUE TITLE
WITK-Takengon Rembele Airport-ACEH-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#5963]
# Airport Name
< Takengon Rembele Airport >
# Country?
< Indonesia >
# Improvements that need to be made?
< Create New Airport >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low Priority >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103173829-2f53ac00-4823-11eb-8560-f2b9af56fc67.png)
