### ISSUE TITLE
LFMD-Cannes Mandelieu-PROVENCE ALPES COTE D'AZUR-FRANCE

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#5964]
# Airport Name
Cannes Mandelieu
# Country?
🇫🇷 where they have all the 🥐 🥖 
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102826321-0efc9b00-43a6-11eb-87bd-b16f826e40aa.png)
