### ISSUE TITLE
WIBL-Pelalawan Airport / Sultan Syarif Haroen (RAPP Airbase)-RIAU-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#5965]
# Airport Name
< Sultan Syarif Haroen Airport >
# Country?
< Indonesia >
# Improvements that need to be made?
< Create New Airport >
# Are you working on this airport?
  < Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low Priority >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103161495-283b8800-47a8-11eb-84e3-df43e54f95cd.png)
