### ISSUE TITLE
KMMH-Mammoth Yosemite Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#5966]
# Airport Name
Mammoth Yosemite Airport
# Country?
USA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by jakey20** [comment]
sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102948204-003be400-448b-11eb-99c7-2e9f56a4ef85.png)
