### ISSUE TITLE
WIDO-Ranai-Natuna Airport-NATUNA-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#5967]
# Airport Name
< Raden Sadjad Airport >
# Country?
< Indonesia >
# Improvements that need to be made?
< Create New Airport >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low Priority >

**Comment by MajorTomMueller** [comment]
previously WION

**Comment by MajorTomMueller** [comment]
https://aimindonesia.dephub.go.id/images/1779-24.%20WIDO%20AMDT%2055%20121016.pdf

https://aimindonesia.dephub.go.id/images/1780-24.%20WIDO%20AD%202.24-1%20AMDT%2055_121016.pdf

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103308050-2572aa00-49d7-11eb-9c52-caa4182a822e.png)
