### ISSUE TITLE
9G0-Buffalo Airfield-NEW YORK-USA

### ISSUE THREAD

**Issue by MJP27** [InfiniteFlightAirportEditing/Airports#5969]
# Airport Name
Buffalo Airfield
# Country?
 USA
# Improvements that need to be made?
Add Airport
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by MJP27** [comment]
Thanks!

**Comment by feitidede** [comment]
gimme

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/117542949-5182e500-afe0-11eb-8906-2f901f266682.png)
