### ISSUE TITLE
LPMA-Madeira Airport-MADEIRA-PORTUGAL

### ISSUE THREAD

**Issue by ReflexRSM** [InfiniteFlightAirportEditing/Airports#597]
Madeira Airport

**Comment by NickArt1342** [comment]
are you doing this @dushyants19 ?

**Comment by ReflexRSM** [comment]
@NickArt1342  No, I'm doing this.
Could you assign me?

**Comment by JcFl4** [comment]
So no one is doing this one?

**Comment by NickArt1342** [comment]
I thought @ReflexRSM was, but @dushyants19 Dush unassigned him so I don't know.

**Comment by JcFl4** [comment]
I'll eventually do it, like many other airports I have on the waiting list.

**Comment by bavAVIA** [comment]
What's the progress? I'd be happy to take over if this isn't nearing completion in near future.

**Comment by JcFl4** [comment]
½ way done.

**Comment by kilt46** [comment]
Runway too long. Also a few spawn points missing?
![image](https://cloud.githubusercontent.com/assets/14023167/21829355/10c70da0-d75b-11e6-945a-76835a159087.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21829365/1f299b38-d75b-11e6-8e1a-8f3c15b892c4.png)

**Comment by JcFl4** [comment]
Runway is longer because it has displaced thresholds that are not subtracted from the total length. Also, the missing spawns are there to prevent people spawning on top of others, as the spawns are really close and there is no need to have every spawn.

**Comment by JcFl4** [comment]
But thanks for warning me! 🙂

**Comment by JcFl4** [comment]
Added missing gates.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22491690/deb11644-e7ea-11e6-8499-796bca513ee6.png)

**Comment by dushyants19** [comment]
need to rename :P
