### ISSUE TITLE
LETJ-Trebujena Airport-ANDALUCIA-SPAIN

### ISSUE THREAD

**Issue by pilotignacio** [InfiniteFlightAirportEditing/Airports#5970]
# Airport Name
Trebujena Airfield
# Country?
Spain
# Improvements that need to be made?
New airport
# Are you working on this airport?
Yes, today I am starting
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114269461-d45a5500-99cc-11eb-81b1-210a80cdcebe.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114271238-0623e980-99d6-11eb-9c57-b1932b80bd6f.png)
