### ISSUE TITLE
KPCZ-Waupaca Municipal-WISCONSIN-USA

### ISSUE THREAD

**Issue by zhf21** [InfiniteFlightAirportEditing/Airports#5971]
# Airport Name
Waupaca Municipal
# Country?
USA
# Improvements that need to be made?
Full redo
# Are you working on this airport?
I wouldn't be creating an issue if I wasn't
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by zhf21** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103173677-18608a00-4822-11eb-8fe0-ec8aaf775570.png)
