### ISSUE TITLE
XCUR-Currock Hill-GATESHEAD-UNITED KINGDOM

### ISSUE THREAD

**Issue by jasong92** [InfiniteFlightAirportEditing/Airports#5972]
# Airport Name
< Currock Hill>
# Country?
< United Kingdom >
# Improvements that need to be made?
< Addition to IF Airports >
# Are you working on this airport?
< Yes>
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low>

**Comment by Czechoslovaki** [comment]
What is the ICAO? EGX5?

**Comment by jasong92** [comment]
EGX5 is Yearb airfield I’ll be working on XCUR Currock airfield

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pharoah-21** [comment]
i will do this one

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116325311-7cbb3800-a787-11eb-8ada-3a19c173a7ef.png)
