### ISSUE TITLE
YBPN-Prosperine/Whitsunday Coast Airport-Queensland-AUSTRALIA

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Airports#5974]
# Airport Name
Proserpine Whitsunday Coast
# Country?
Australia
# Improvements that need to be made?
Redo from scratch
# Are you working on this airport?
No. Airport submitted but no issue was created.
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by brunocr1050** [comment]
Done by @hossss6

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102824168-ec688300-43a1-11eb-9a41-a8050c729de9.png)
Airport outside of boundary

**Comment by brunocr1050** [comment]
I checked the file again, the picture of the airport doesn't seem to correspond with any of the runways/taxiways of the file. Nonetheless, I have corrected some nodes of the boundary, because they cannot be curved afaik.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102930149-817e8100-4461-11eb-8e8d-5dcff9f111db.png)

**Comment by hossss6** [comment]
Just noticed the runway being concrete instead of asphalt when i spawned in the app to check the airport out. I have sent the new file to OR to be added in the next push

**Comment by ECoops-123** [comment]
@hossss6 is that the only fix you've made? That can be changed right now into the repo. :)

**Comment by hossss6** [comment]
Yes that is all i changed, all the rest is ok
