### ISSUE TITLE
YMEN

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Airports#5975]
Airport Name
Essendon
Country?
Australia
Improvements that need to be made?
Redo from scratch
Are you working on this airport?
No. Airport submitted but no issue was created.
Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by brunocr1050** [comment]
Redone by @hossss6

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102737677-b083de00-430d-11eb-8692-cbaea8e3c8b5.png)
