### ISSUE TITLE
O46-Weed Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Airports#5976]
♻️

**Comment by brunocr1050** [comment]
Redone by @hari-shreyas

**Comment by jakey20** [comment]
You can recycle this as O46, Weed Airport, California.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103041167-389afb00-453b-11eb-92b3-b9acc60f07e4.png)
