### ISSUE TITLE
URWI-Elista-KALMYKIA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#5977]
# Airport Name
< Elista Intl >
# Country?
< :ru: >
# Improvements that need to be made?
< redo >
# Are you working on this airport?
< yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< GP2 >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103108222-710a0a00-460b-11eb-8d6c-a45e2727d0f4.png)
