### ISSUE TITLE
UWOR-Orsk-ORENBURG-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#5978]
# Airport Name
< Orsk Intl >
# Country?
< :RU: >
# Improvements that need to be made?
< redo >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103108171-f214d180-460a-11eb-840b-baad8755ff65.png)
