### ISSUE TITLE
K15-Glaize-Osage Beach Airport-MISSOURI-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#5979]
# Airport Name
Grand Glaize-Osage Beach Airport
# Country?
USA
# Improvements that need to be made?
Manual Edit
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

![Full](https://user-images.githubusercontent.com/59462519/102737294-ee4d2a80-433e-11eb-8556-779a932c7ede.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102937746-767f1d00-4470-11eb-8656-66d5a4d7298e.png)
