### ISSUE TITLE
VOBL-Kempegowda Int/ Bengaluru Airport-KARNATAKA-INDIA

### ISSUE THREAD

**Issue by sumith11** [InfiniteFlightAirportEditing/Airports#598]
VOBL can accommodate an A380 -  Gate 25-26 is equipped to serve the Airbus A380.

**Comment by dushyants19** [comment]
No commercial service, So no A380 label.

**Comment by IceBlue02** [comment]
But you do get a user suggestion one though :wink:

**Comment by ReflexRSM** [comment]
No one planning do? If so I'll grab this one!

**Comment by ReflexRSM** [comment]
Sent for approval.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18330956/4118279c-7521-11e6-9c6c-5de8813f2af7.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18330963/4a4b028a-7521-11e6-9fc4-3aca2c3f5602.png)

**Comment by Ayush-19** [comment]
Sent for OR.

**Comment by MajorTomMueller** [comment]
New runway, huge construction site for new terminal apron

**Comment by hari-shreyas** [comment]
Who is re-working this?

**Comment by MajorTomMueller** [comment]
No one at the moment. it is a suggestion.
But, to be honest, this is beyond you capacity. With the current stage of available imagerie and data it is for high experienced editors wich are known for their advanced skills.
I wouldn't assign this to you.

**Comment by hari-shreyas** [comment]
No, I was not looking to assign myself to the airport. I was just asking.
Even if I wanted to, I couldn't do it as it needs tonnes of new things to be added like a new runway and I am pretty sure I couldn't do it as a beginner.

**Comment by Czechoslovaki** [comment]
Could I do this one?

**Comment by MajorTomMueller** [comment]
Hard one, assigned you.

**Comment by hari-shreyas** [comment]
Make it good @Czechoslovaki! It's a beautiful airport.

**Comment by Czechoslovaki** [comment]
Sent For OR

**Comment by hari-shreyas** [comment]
> Sent For OR

Yayy! Thanks for working on it :D. Did you add the new RWY?

**Comment by MajorTomMueller** [comment]
Otherwise it would be useless to send to OR...

**Comment by hari-shreyas** [comment]
> Otherwise it would be useless to send to OR...

You got a point.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/89475384-91fdbb80-d74d-11ea-8d1c-55ae8f2eaa33.png)
