### ISSUE TITLE
K19-Albany Municipal Airport-MISSOURI-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#5981]
# Airport Name
Albany Municipal Airport
# Country?
USA
# Improvements that need to be made?
Manual Edit
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

![Full](https://user-images.githubusercontent.com/59462519/102737490-7c291580-433f-11eb-8eec-76aee4ef7d21.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102932341-bab8f000-4465-11eb-8e0e-442f53454c74.png)
