### ISSUE TITLE
429-Ste Croix Sur Verdon-FRANCE

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#5982]
# Airport Name
Ste Croix Sur Verdon
# Country?
🇫🇷 
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![Uploading image.png…]()

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102823568-bb3b8300-43a0-11eb-97bb-e2efddf7b868.png)
