### ISSUE TITLE
LFAQ-Albert Bray-PICARDIE-FRANCE

### ISSUE THREAD

**Issue by Jeremy351** [InfiniteFlightAirportEditing/Airports#5983]
# Airport Name
Albert Bray Airport
# Country?
France
# Improvements that need to be made?
Full redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102952167-25812000-4494-11eb-8746-4f82085138a4.png)
