### ISSUE TITLE
SUPE-El Jaguel International Airport-URUGUAY

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#5984]
# Airport Name
El Jaguel International Airport
# Country?
Uruguay
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yep
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102943612-2d35ca00-447e-11eb-8159-8dd9e5aa2cd9.png)
