### ISSUE TITLE
SDIH-Fazenda Irohy-SAO PAULO-BRAZIL

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#5985]
# Airport Name
Fazenda Irohy
# Country?
Brazil
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yep
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102946494-7722ae00-4486-11eb-9c64-33b3c443ca45.png)
