### ISSUE TITLE
LIDK - Casarsa Della Delizia AB - Friuli Venezia Giulia - Italy

### ISSUE THREAD

**Issue by davide-dc** [InfiniteFlightAirportEditing/Airports#5986]
# Airport Name
Casarsa Della Delizia
# Country?
Italy
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by MajorTomMueller** [comment]
We do not add heliports.

**Comment by MajorTomMueller** [comment]
![EYSE](https://user-images.githubusercontent.com/26853210/103652479-19e52d00-4f5b-11eb-8f27-981a1d032bf3.png)

**Comment by MajorTomMueller** [comment]
https://github.com/InfiniteFlightAirportEditing/Airports/commit/a2fc5807f72281a2b4df6fd6037bbcb471138eef
