### ISSUE TITLE
SUDU-Santa Bernardina Airport-SANTA BERNARDINA-URUGUAY

### ISSUE THREAD

**Issue by davide-dc** [InfiniteFlightAirportEditing/Airports#5987]
# Airport Name
Santa Bernardina Intl
# Country?
Uruguay
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102943407-90732c80-447d-11eb-846b-ded9215831e1.png)
