### ISSUE TITLE
LFBU-Angouleme Brie Champniers-AQUITAINE-FRANCE

### ISSUE THREAD

**Issue by Jeremy351** [InfiniteFlightAirportEditing/Airports#5988]
# Airport Name
Angoulême - Brie - Champniers Airport
# Country?
France
# Improvements that need to be made?
Full redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103172827-eba97400-481b-11eb-8a62-7238bc55c1ff.png)
