### ISSUE TITLE
YABA-Albany Airport-WESTERN AUSTRALIA-AUSTRALIA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5989]
# Airport Name
Albany Airport
# Country?
Australia
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102823924-7106d180-43a1-11eb-873e-9993b47a6972.png)
