### ISSUE TITLE
EDDN

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#599]
Nuremberg Albrecht Duerer Airport, I will redo it, there are missing parking spots, markings, the terminal is missing and public streets have to be removed

**Comment by moritzbabl** [comment]
Finished it, mail was just sent

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20462806/d3ebe6ae-aeeb-11e6-81c4-ee65717085ba.png)
