### ISSUE TITLE
LAKO-Korçë Northwest Airport-KORCE-ALBANIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#5990]
# Airport Name
Korçë Northwest Airport
# Country?
Albania
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102945141-8a337f00-4482-11eb-9565-d610753492ca.png)
