### ISSUE TITLE
LAKU-Kukës International Airport-KUKES-ALBANIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#5991]
# Airport Name
Kukës International Airport
# Country?
Albania
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102944945-f497ef80-4481-11eb-84ea-a3a11616087b.png)
