### ISSUE TITLE
FNBG-Benguela Airport-BENGUELA-ANGOLA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5992]
# Airport Name
Benguela Airport
# Country?
Angola
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102825971-7403c100-43a5-11eb-9c9c-b36b31563ada.png)
