### ISSUE TITLE
21W

### ISSUE THREAD

**Issue by RobertineIFC** [InfiniteFlightAirportEditing/Airports#5994]
# Airport Name
 Ranger Creek Airport 
# Country?
 United States 
# Improvements that need to be made?
 Rework Runway, Add Size Restrictions 
# Are you working on this airport?
 Yes 
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
 Low

**Comment by Czechoslovaki** [comment]
#135

**Comment by MajorTomMueller** [comment]
![EYRD](https://user-images.githubusercontent.com/26853210/103654382-b7416080-4f5d-11eb-9f86-fb383aad587c.png)

**Comment by Czechoslovaki** [comment]
@RobertineIFC no (unless you got a response from your application), Major Tom is only recycling the issue for another airport that needed to be edited.

**Comment by RobertineIFC** [comment]
Okay thanks :D
