### ISSUE TITLE
AYVN-Vanimo Airport-SANDAUN-PAPUA NEW GUINEA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#5995]
# Airport Name
Vanimo Airport
# Country?
Papua New Guinea
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103108087-06a49a00-460a-11eb-9a1b-ceaf5413dbaf.png)
