### ISSUE TITLE
LFHU

### ISSUE THREAD

**Issue by RobertineIFC** [InfiniteFlightAirportEditing/Airports#5996]
# Airport Name
Alpes D'huez
# Country?
France
# Improvements that need to be made?
Add size restrictions, rework gates and runway
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by Czechoslovaki** [comment]
#1104

**Comment by MajorTomMueller** [comment]
![EYPN](https://user-images.githubusercontent.com/26853210/103656354-667f3700-4f60-11eb-9b4a-674e00a1db9f.png)

**Comment by MajorTomMueller** [comment]
https://github.com/InfiniteFlightAirportEditing/Airports/commit/a0b4ab9e0b10eefa426774815e5196f627ae6950
