### ISSUE TITLE
K06-Greater Beardstown Airport-ILLINOIS-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#5997]
# Airport Name
Greater Beardstown AirporT
# Country
USA
# Improvements that need to be made?
Manual Edit
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102938311-b266b200-4471-11eb-9333-e33e8cb586f9.png)
