### ISSUE TITLE
K07-Rolla Downton Airport-MISSOURI-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#5998]
# Airport Name
Rolla Downtown Airport
# Country?
USA
# Improvements that need to be made?
Manual edit
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

![Full](https://user-images.githubusercontent.com/59462519/102840934-d9829c80-43fb-11eb-9ff7-99f8a6723573.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102932025-25b5f700-4465-11eb-9f7f-7ad0a067df85.png)
