### ISSUE TITLE
K09-Piseco Airport-NEW YORK-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#5999]
# Airport Name
Piseco Airport
# Country?
USA
# Improvements that need to be made?
Manual edit
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102931396-ef2bac80-4463-11eb-8a21-7da5e5db1028.png)
