### ISSUE TITLE
TFFJ-St Barthelemy Airport-SAINT BARTHELEMY

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#6]
More parking spots and road

**Comment by Swang007** [comment]
https://community.infinite-flight.com/t/caribbean-airport-name-issue/9926

Some kind of name issue.

**Comment by kilt46** [comment]
Reworked airport and emailed in

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20641540/e610aad0-b3bf-11e6-8f2c-23daac9b46d8.png)

**Comment by brunocr1050** [comment]
To be redone by @davide-dc (last time redone: 2016).

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105433152-b88db100-5c1e-11eb-90f0-ab016de3e8b5.png)
