### ISSUE TITLE
WAOO-Syamsudin Noor Airport-KALIMANTAN SELATAN-INDONESIA

### ISSUE THREAD

**Issue by CaptainTrapBeats** [InfiniteFlightAirportEditing/Airports#600]

**Comment by NickArt1342** [comment]
Is this a suggestion or an airport you want to do? @CaptainTrapBeats

**Comment by CaptainTrapBeats** [comment]
I want to do, and also WADD too

On Thursday, 19 May 2016, NickArt1342 <notifications@github.com> wrote:

> Is this a suggestion or an airport you want to do? @CaptainTrapBeats
> <https://github.com/CaptainTrapBeats>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/InfiniteFlightAirportEditing/Airports/issues/600#issuecomment-220105669>
>


-- 
Sent from Gmail Mobile

**Comment by CaptainTrapBeats** [comment]
HOW TO ACCEPT repository invite?

**Comment by dushyants19** [comment]
Any progress on this, @CaptainTrapBeats?

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by kilt46** [comment]
Gates Renamed
![image](https://cloud.githubusercontent.com/assets/14023167/21750217/d89ddf8c-d573-11e6-8d47-4844e69eb75f.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21750220/f1c3498e-d573-11e6-93a5-7bca3b7d6f63.png)

**Comment by MajorTomMueller** [comment]
Apron expansion

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90312436-11b42480-deca-11ea-8288-cd9570d3cdd8.png)
