### ISSUE TITLE
KSJS-Big Sandy Regional Airport-KENTUCKY-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6001]
# Airport Name
Big Sandy Regional Airport
# Country?
USA
# Improvements that need to be made?
Manual Edit
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

Previous ICAO: K22

![Full](https://user-images.githubusercontent.com/59462519/102842862-e0aba980-43ff-11eb-92fa-d442bcce76f5.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103046621-840ad480-454e-11eb-86ee-c8132d43b747.png)
