### ISSUE TITLE
K26-Carrollton Memorial Airport-MISSOURI-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6003]
# Airport Name
Carrollton Memorial Airport
# Country?
USA
# Improvements that need to be made?
Manual edit
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

![Full](https://user-images.githubusercontent.com/59462519/102843594-61b77080-4401-11eb-941a-e1d365743a2a.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103046126-b61b3700-454c-11eb-948a-298ffacf1953.png)
