### ISSUE TITLE
VA1B-Chandrapur Airport-MAHARASHTRA-INDIA

### ISSUE THREAD

**Issue by Captainflight** [InfiniteFlightAirportEditing/Airports#6004]
# Airport Name
< Chandrapur Airport >
# Country?
< India >
# Improvements that need to be made?
< Rework From scratch >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103027370-522c4a80-451b-11eb-9942-db39969e709b.png)
