### ISSUE TITLE
42U-Morgan County Airport-UTAH-USA

### ISSUE THREAD

**Issue by LesterXavier** [InfiniteFlightAirportEditing/Airports#6005]
# Airport Name
< Morgan County Airport >
# Country?
< US >
# Improvements that need to be made?
< rework from scratch >
# Are you working on this airport?
< Ye >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103714886-c2f44d80-4f84-11eb-9c32-3eae97afd6a0.png)
