### ISSUE TITLE
KABR-Aberdeen Regional Airport-SOUTH DAKOTA-UNITED STATES

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#6006]
# Airport Name
Aberdeen Regional Airport
# Country?
US of A
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yep
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103103081-d8609380-45e4-11eb-8dc6-484bc6aa8b2d.png)
