### ISSUE TITLE
YLST-Leinster Airport-WESTERN AUSTRALIA-AUSTRALIA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#6007]
# Airport Name
Leinster Airport
# Country?
Australia
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
How can this be closed?
![image](https://user-images.githubusercontent.com/14023167/102929206-c99ca400-445f-11eb-9cd3-bfa6e7b31150.png)

**Comment by MBeringuy** [comment]
Sorry, @kilt46. I informed the wrong ICAO in the issue title. Fixed now.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102930932-04540b80-4463-11eb-9fab-41d986eaeff7.png)
