### ISSUE TITLE
VOMY-Mysore Airport-KARANATAKA-INDIA

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#6008]
# Airport Name
Mysore Airport
# Country?
India
# Improvements that need to be made?
Add
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![Uploading image.png…]()
