### ISSUE TITLE
VA1J-Dhana Airport-MADHYA PRADESH-INDIA

### ISSUE THREAD

**Issue by KaalicharanDH** [InfiniteFlightAirportEditing/Airports#6009]
# Airport Name
Dhana Airport
# Country?
India
# Improvements that need to be made?
Full Rework
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by brunocr1050** [comment]
This was approved last week but I forgot to close the issue. My apologies for this.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103325568-ec0b6000-4a11-11eb-810b-529bf00b6e08.png)
