### ISSUE TITLE
YPPH-Perth Intl-AUSTRALIA

### ISSUE THREAD

**Issue by NatIsrael972** [InfiniteFlightAirportEditing/Airports#601]

**Comment by dushyants19** [comment]
Search before posting.  #257

**Comment by dushyants19** [comment]
Done, [Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/21e1d31d0bd3914b9a65089cc4ba5cbd0a4b1c97#diff-e093ec86736a825e1e3ae635b870f379)

**Comment by henrikbg** [comment]
Fixes by Sumith.

**Comment by kilt46** [comment]
REQUIRES TERMINAL REDONE AS PER NAVIGRAPH

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/16363373/9b4fbb3a-3b8d-11e6-8812-0e6a4605e0b9.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/16363376/b6ccf616-3b8d-11e6-9267-9dec9e6242bb.png)

**Comment by dushyants19** [comment]
@ReflexRSM  you are fixing it.

**Comment by BeniPrianto** [comment]
good

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18253951/92c7c4ae-735e-11e6-8e94-cd7fd64b3296.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18253976/c0298f54-735e-11e6-9dec-afb6bd15197d.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18253981/ccacb210-735e-11e6-8e50-9db1b0995afc.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18253994/e55d443c-735e-11e6-8560-cfb5bc094f7c.png)
