### ISSUE TITLE
VLLB-Luang Phabang International Airport-LUANG PRABANG-LAOS

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#6010]
# Airport Name
Luang Phabang International Airport
# Country?
Laos
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103136577-347bf400-4687-11eb-808f-861286cbed5d.png)
