### ISSUE TITLE
VAKD-Khandwa Airport-MADHYA PRADESH-INDIA

### ISSUE THREAD

**Issue by Captainflight** [InfiniteFlightAirportEditing/Airports#6012]
# Airport Name
< Khandwa Airport >
# Country?
< India >
# Improvements that need to be made?
< New >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103101528-ab5cb280-45dd-11eb-9686-c0d6bd35cfd8.png)
