### ISSUE TITLE
KDVN-Davenport Municipal-IOWA-USA

### ISSUE THREAD

**Issue by davide-dc** [InfiniteFlightAirportEditing/Airports#6013]
# Airport Name
Davenport Muni
# Country?
USA
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by brunocr1050** [comment]
@davide-dc, make sure to have been invited to the team's Github repository, otherwise none of the supervisors or myself can assign you to issues not created by you.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103135676-73a64700-467f-11eb-9af8-b93dbc7e8707.png)
