### ISSUE TITLE
2S2-Beaver Marsh-OREGON-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6014]
# Airport Name
Beaver Marsh
# Country?
:us:
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102949091-0df26900-448d-11eb-95e1-6f845eb406ad.png)
