### ISSUE TITLE
5S2-Crescent Lake State-OREGON-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6015]
# Airport Name
Crescent Lake State
# Country?
'M u r i c a
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102948858-77be4300-448c-11eb-808b-96320b5613c6.png)
