### ISSUE TITLE
9MN1-Troll Farm-MINNESOTA-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6016]
# Airport Name
Troll Farm 
# Country?
:us:
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102949919-0f249580-448f-11eb-8eff-e80a2f51c7a2.png)
