### ISSUE TITLE
INVALID

### ISSUE THREAD

**Issue by zacky89315** [InfiniteFlightAirportEditing/Airports#6017]

**Comment by MajorTomMueller** [comment]
![EYPI](https://user-images.githubusercontent.com/26853210/103657585-fa053780-4f61-11eb-81a3-7a1d61a63510.png)

**Comment by MajorTomMueller** [comment]
https://github.com/InfiniteFlightAirportEditing/Airports/commit/a0b4ab9e0b10eefa426774815e5196f627ae6950
