### ISSUE TITLE
KPSO-Stevens Field Airport-COLORADO-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6018]
# Airport Name
Stevens Field Airport
# Country?
USA
# Improvements that need to be made?
Manual Edit
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

![Full](https://user-images.githubusercontent.com/59462519/102960092-1c667200-44d9-11eb-83f2-a739ade2fbb0.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103102924-0e514800-45e4-11eb-8366-16f6cf04aff8.png)
