### ISSUE TITLE
KZER-Schuylkill County/Joe Zerbey Airport-PENNSYLVANIA-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6019]
# Airport Name
Schuylkill County/Joe Zerbey Airport
# Country?
USA
# Improvements that need to be made?
Manual Edit
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

Work in progress

![Full](https://user-images.githubusercontent.com/59462519/102960648-4a988180-44da-11eb-935d-e926ac16f327.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103135555-a7cd3800-467e-11eb-8fcd-6a9d69f7ea49.png)
