### ISSUE TITLE
KSTL-St. Louis Lambert International Airport-MISSOURI-USA

### ISSUE THREAD

**Issue by david-garden** [InfiniteFlightAirportEditing/Airports#602]
I will be doing this one :)

**Comment by NickArt1342** [comment]
@david-garden Please accept the repository invite in your email or the github main page so we cann assign you to the issue

**Comment by david-garden** [comment]
Will do, Nick.

**Comment by david-garden** [comment]
Sent in for approval.

**Comment by dushyants19** [comment]
22420a2

**Comment by kilt46** [comment]
Missing a few gates

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19332032/1dad1b7a-90ae-11e6-9b64-7e78c431bcbc.png)
![image](https://cloud.githubusercontent.com/assets/14023167/19332045/2a1af9b8-90ae-11e6-9030-24e1df940598.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55763528-ee06e180-5a2c-11e9-8f89-edc7d525e522.png)
