### ISSUE TITLE
VAKP-Kolhapur Airport-MAHARASHTRA-INDIA

### ISSUE THREAD

**Issue by KaalicharanDH** [InfiniteFlightAirportEditing/Airports#6020]
# Airport Name
Kolhapur Airport
# Country?
India
# Improvements that need to be made?
Full Rework
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103101417-21ace500-45dd-11eb-8add-e210ab9dac50.png)
