### ISSUE TITLE
UUBP-Bryansk-BRYANSK-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6021]
# Airport Name
< Bryansk Intl >
# Country?
< :RU: >
# Improvements that need to be made?
< redo >
# Are you working on this airport?
< yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103326016-13632c80-4a14-11eb-8d0b-520128979d3a.png)
