### ISSUE TITLE
ZPJH-Xishuangbanna Gasa International Airport-YUNNAN-CHINA

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#6022]
# Airport Name
Xishuangbanna Gasa International Airport
# Country?
China
# Improvements that need to be made?
Redone
# Are you working on this airport?
Actually I'm done
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103102423-85391180-45e1-11eb-9c85-50fb843c2eac.png)
