### ISSUE TITLE
WMKN-Kuala Terengganu Sultan Mahmud Airport-MALAYSIA

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#6023]
# Airport Name
Kuala Terengganu Sultan Mahmud Airport
# Country?
Malaysia
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yep
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
10000ft+

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103102114-258e3680-45e0-11eb-822c-6efb29a36f85.png)
