### ISSUE TITLE
VNRB-Rajbiraj Airport-PROVINCE 2-NEPAL

### ISSUE THREAD

**Issue by Captainflight** [InfiniteFlightAirportEditing/Airports#6024]
# Airport Name
< Rajbiraj Airport >
# Country?
< Nepal >
# Improvements that need to be made?
< Rework from scratch >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103101741-a9472380-45de-11eb-9956-c22ffb9ca7dc.png)
