### ISSUE TITLE
KGED-Delaware Coastal Airport-DELAWARE-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#6026]
# Airport Name
Delaware Coastal Airport
# Country?
🇺🇸 
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103102781-38563a80-45e3-11eb-8060-f3d265cc50a9.png)
