### ISSUE TITLE
5S0-Oakridge State-OREGON-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6027]
# Airport Name
Oakridge State
# Country?
:us:
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103040281-91b55f80-4538-11eb-989c-f4d714b31370.png)
