### ISSUE TITLE
KMAN-Nampa Municipal-IDAHO-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6028]
# Airport Name
Nampa Muni
# Country?
:us:
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103135436-f1695300-467d-11eb-81bf-4762cb021d83.png)
