### ISSUE TITLE
PASD-Sand Point Airport-ALASKA-USA

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6029]
# Airport Name
Sand Point Airport
# Country?
USA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103045712-3b9de780-454b-11eb-8f7b-14a3cee04a08.png)
