### ISSUE TITLE
LEMG-Malaga/Costa Del Sol Airport-ANDALUCIA-SPAIN

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#603]
Malaga airport

**Comment by kilt46** [comment]
Please clean up main apron and provide more defined buildings
![image](https://cloud.githubusercontent.com/assets/14023167/15694411/432e7182-2763-11e6-897f-2f849cca89f8.png)

**Comment by kilt46** [comment]
Expected Building formation and stands
![image](https://cloud.githubusercontent.com/assets/14023167/16362951/68788658-3b81-11e6-8759-f536e2a7622a.png)

**Comment by kilt46** [comment]
Existing layout does not reflect true life
![image](https://cloud.githubusercontent.com/assets/14023167/16362957/831c313a-3b81-11e6-8971-dce4724175d3.png)

**Comment by kilt46** [comment]
Gates are not square to terminal like in airport. They need to reflect the satellite image and follow the contours of the apron lines!

**Comment by Aviationluver** [comment]
I'll redo LEMG from scratch. There are a lot of things that are incorrect about the layout.

**Comment by Aviationluver** [comment]
Sent this one off to be reviewed.

**Comment by dushyants19** [comment]
bc53e72

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19098497/2c361296-8a73-11e6-8d8d-e451e9cd0f8a.png)
![image](https://cloud.githubusercontent.com/assets/14023167/19098504/35a914c2-8a73-11e6-88b8-446479b5b51a.png)

**Comment by Czechoslovaki** [comment]
Airport requires rework, up for grabs.

**Comment by OscarConklin** [comment]
I can do this.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/97123171-6957e300-16f8-11eb-9db6-b92376470b75.png)

**Comment by MajorTomMueller** [comment]
@OscarConklin looks like the mil apron lacks lines and stands. Yandex has images for it, please add as well.

**Comment by OscarConklin** [comment]
Sent for OR!

**Comment by kilt46** [comment]
![Uploading image.png…]()
