### ISSUE TITLE
PASC-Deadhorse Airport-ALASKA-USA

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6030]
# Airport Name
Deadhorse Airport
# Country?
USA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103045565-a26ed100-454a-11eb-9a48-6a8fd2d908f6.png)
