### ISSUE TITLE
KTCS-Truth Or Consequences Municipal Airport-NEW MEXICO-USA

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#6031]
# Airport Name
Truth Or Consequences Municipal Airport
# Country?
US of A
# Improvements that need to be made?
Redone
# Are you working on this airport?
Ye
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103173554-6cb73a00-4821-11eb-9195-2aa0dba03247.png)
