### ISSUE TITLE
UUMO-Ostafyevo-MOSCOW-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6032]
# Airport Name
< Moscow Ostafyevo Airport >
# Country?
< :ru: >
# Improvements that need to be made?
< redo >
# Are you working on this airport?
< yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103481241-3fc5d280-4d9f-11eb-92b6-a4fee8cb2e94.png)
