### ISSUE TITLE
LFCU-Thalamy Airport-LIMOUSIN-FRANCE

### ISSUE THREAD

**Issue by Captainflight** [InfiniteFlightAirportEditing/Airports#6033]
# Airport Name
< Thalamy Airport >
# Country?
< France >
# Improvements that need to be made?
< Runway removal >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103959696-04683280-5116-11eb-85bc-8ad5a21686a5.png)
