### ISSUE TITLE
WICM-Wiriadinata Airport-WEST JAVA-INDONESIA

### ISSUE THREAD

**Issue by vinoalviano1994** [InfiniteFlightAirportEditing/Airports#6034]
# Airport Name
< Wiriadinata Airport >
# Country?
< Indonesia >
# Improvements that need to be made?
< Full Rework >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103111461-d9a8b500-4612-11eb-8d5e-edac82548ec8.png)
