### ISSUE TITLE
2B1-Cape Cod Airport-MASSACHUSETTS-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#6035]
# Airport Name
Cape Cod Airport
# Country?
🇺🇸 
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103102629-83238280-45e2-11eb-91b9-d857179d0f1f.png)
