### ISSUE TITLE
KAFJ-Washington County Airport-PENNSYLVANIA-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6036]
# Airport Name
Washington County Airport
# Country?
USA
# Improvements that need to be made?
Manual Edit
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103173365-172e5d80-4820-11eb-8b4f-7e7a196e29cb.png)
