### ISSUE TITLE
KCLW-Clearwater Air Park-FLORIDA-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#6037]
# Airport Name
Clearwater Air Park
# Country?
🇺🇸 
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103249468-fc014200-4934-11eb-8797-7644950bb3c0.png)
