### ISSUE TITLE
SCRF-Laguna San Rafael Airport-AYSEN-CHILE

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6038]
# Airport Name
Laguna San Rafael
# Country?
Chile
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![Uploading image.png…]()
