### ISSUE TITLE
SING-Fazenda Sao Joao-SAO PAULO-BRAZIL

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#6039]
# Airport Name
Fazenda Sao Joao
# Country?
Brazil
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yup
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Lower than ever

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103135763-38f0de80-4680-11eb-9cde-cedb8c6a6d99.png)
