### ISSUE TITLE
EGPH-Edinburgh Airport-SCOTLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by chriscroft20** [InfiniteFlightAirportEditing/Airports#604]
Redoing Edinburgh Airport

**Comment by chriscroft20** [comment]
sent for review

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18939050/0a864738-85c3-11e6-8d6f-cd1f9e8b368d.png)

**Comment by ItsW1ll** [comment]
Requires a quick redo involving adding some more gates, and removal of RWY 12-30

**Comment by ItsW1ll** [comment]
Completed in  b30db9f

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/60270944-cd318800-98c7-11e9-8826-2b1b0dbdf83e.jpg)
