### ISSUE TITLE
HKKE-Keekorok Airstrip-Nakuru-KENYA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6040]
# Airport Name
Keekorok Airstrip
# Country?
Kenya
# Improvements that need to be made?
New Airport
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103111624-98b1a000-4614-11eb-8c91-37de8dd6d6e0.png)

**Comment by brunocr1050** [comment]
Fixed

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103135127-cb42b380-467b-11eb-88c0-a4e5a0446e57.png)
