### ISSUE TITLE
UUJK-Krutitsy-RYAZAN-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6041]
# Airport Name
< Krutitsy Airport >
# Country?
< :ru: >
# Improvements that need to be made?
< redo >
# Are you working on this airport?
< yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< low >
N54.27439 E040.81616

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103172729-147d3980-481b-11eb-9c6c-b48698260f25.png)
