### ISSUE TITLE
HKMS-Mara Serena Airstrip-NAROK-KENYA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6042]
# Airport Name
Mara Serena Airstrip
# Country?
Kenya
# Improvements that need to be made?
New Airport
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103111536-c0543880-4613-11eb-9e91-a18de15e27cf.png)
