### ISSUE TITLE
WICD-Cakrabhuwana Airport-WEST JAVA-INDONESIA

### ISSUE THREAD

**Issue by vinoalviano1994** [InfiniteFlightAirportEditing/Airports#6043]
# Airport Name
< Cakrabhuwana Airport >
# Country?
< Indonesia >
# Improvements that need to be made?
< Full Rework >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103161384-d0505180-47a6-11eb-8608-0c2972246fcb.png)
