### ISSUE TITLE
13OR-Aubrey Mountain Airstrip-OREGON-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6045]
# Airport Name
Aubrey Mountain Airstrip
# Country?
:us:
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
e
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Lower

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103135316-0a253900-467d-11eb-8860-ec93abd84080.png)
