### ISSUE TITLE
KFCH-Fresno Chandler Executive-CALIFORNIA-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6046]
# Airport Name
Fresno Chandler Executive
# Country?
:us:
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103152629-77090380-474f-11eb-803c-fab7e3eb44ef.png)
