### ISSUE TITLE
SSSS-Sao Francisco Do Sul Airport-SANTA CATARINA-BRAZIL

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#6047]
# Airport Name
Sao Francisco Do Sul Airport
# Country?
Brazil
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103173029-a128f700-481d-11eb-80b0-aa1a541fd7c4.png)
