### ISSUE TITLE
BITE-Thingeyri Airport-ICELAND

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#6048]
# Airport Name
Thingeyri Airport
# Country?
Iceland
# Improvements that need to be made?
Rework
# Are you working on this airport?
Yep
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103172183-49878d00-4817-11eb-83b3-8b542717d39f.png)
