### ISSUE TITLE
VV06 - Nam Can Air Base - CA MAU - VIETNAM

### ISSUE THREAD

**Issue by IFUA2003** [InfiniteFlightAirportEditing/Airports#6049]
# Airport Name
< Nam Can Air Base >
# Country?
< Vietnam >
# Improvements that need to be made?
< This airport has not been added>
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103481158-a3033500-4d9e-11eb-9971-3392dc0a2118.png)
