### ISSUE TITLE
KOFP

### ISSUE THREAD

**Issue by danielshaw** [InfiniteFlightAirportEditing/Airports#605]
I will edit Hanover County Municipal Airport in Richmond Virginia.

**Comment by kilt46** [comment]
Missing a ton of buildings
![Uploading image.png…]()

**Comment by danielshaw** [comment]
I didn't realize I was supposed to make buildings concrete until I was on
my second airport when someone told me. I will definitely fix this airport.
My sincerest apologies.

**Comment by dushyants19** [comment]
Approved by Henrik. [Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/707c42599766bde7ed5009161d7e9c0664098d8b)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20413243/6c677e54-acf1-11e6-919a-0157d929b617.png)
