### ISSUE TITLE
HKOK-Olkiombo Airstrip-NAROK-KENYA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6050]
# Airport Name
Olkiombo Airstrip
# Country?
Kenya
# Improvements that need to be made?
New Airport
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103161335-ddb90c00-47a5-11eb-90e4-47b7ac8dd53f.png)
