### ISSUE TITLE
HKTB-Kichwa Tembo Airstrip-NAROK-KENYA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6051]
# Airport Name
Kichwa Tembo Airstrip
# Country?
Kenya
# Improvements that need to be made?
New Airport
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103161295-28865400-47a5-11eb-9e4e-638ad6061279.png)
