### ISSUE TITLE
GE99-Heaven's Landing-Georgia-USA

### ISSUE THREAD

**Issue by zhf21** [InfiniteFlightAirportEditing/Airports#6052]
# Airport Name
Heaven's Landing
# Country?
US of A
# Improvements that need to be made?
Full redo - auto-gen airport
# Are you working on this airport?
i'd like to
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103411971-a5645580-4b38-11eb-9f9e-e73b2423d0ac.png)
