### ISSUE TITLE
SANU-San Juan Airport-SAN JUAN-ARGENTINA

### ISSUE THREAD

**Issue by victormw22** [InfiniteFlightAirportEditing/Airports#6054]
# Airport Name
< San Juan Airport >
# Country?
< Argentina >
# Improvements that need to be made?
< Redone >
# Are you working on this airport?
< yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103356894-85b92880-4a77-11eb-89bd-10474aeea785.png)
