### ISSUE TITLE
ENAS-Ny Alesund Airport-NORWAY

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#6055]
# Airport Name
Ny Alesund Airport
# Country?
Norway
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yep
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103171426-c31c7c80-4811-11eb-8cf4-d5deb11e3e60.png)
