### ISSUE TITLE
KLDJ-Linden Airport-NEW JERSEY-USA

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#6056]
# Airport Name
Linden Airport
# Country?
US of A
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yep
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103249334-4635f380-4934-11eb-8279-e5b401f7e82a.png)
