### ISSUE TITLE
UWTK-Karaishevo Airport-TATARSTAN-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6057]
# Airport Name
< Karaishevo Airport >
# Country?
< :ru: >
# Improvements that need to be made?
< redo >
# Are you working on this airport?
< yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103247957-4d5a0300-492e-11eb-967e-04bd693ec1ff.png)
