### ISSUE TITLE
WAEK-Kuabang Airport-NORTH MALUKU-INDONESIA

### ISSUE THREAD

**Issue by vinoalviano1994** [InfiniteFlightAirportEditing/Airports#6058]
# Airport Name
< kuabang >
# Country?
< Indonesia >
# Improvements that need to be made?
< Full Rework >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103307431-9b761180-49d5-11eb-8a63-f67dc70a3506.png)
