### ISSUE TITLE
HKMT-Mtito Andei Airport-NAROK-KENYA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6059]
# Airport Name
Mara North Conservancy Airstrip
# Country?
Kenya
# Improvements that need to be made?
New Airport
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
This is NOT HKMT
![image](https://user-images.githubusercontent.com/14023167/103323588-2c1a1500-4a09-11eb-9480-a8bc26a59770.png)

**Comment by brunocr1050** [comment]
@Daniel-Baiks, the airstrip you submitted is not HKMT. The one you submitted (Mara North Conservancy Airstrip) doesn't have ICAO code according to Kilt, and the coordinates don't match. Please redo this airport and resubmit.

**Comment by brunocr1050** [comment]
https://en.wikipedia.org/wiki/Mtito_Andei_Airport

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103356448-8bfad500-4a76-11eb-9f83-4188fc1c3a9a.png)
