### ISSUE TITLE
EGGD- Bristol Airport-ENGLAND-UNITED KINGDOM 

### ISSUE THREAD

**Issue by chriscroft20** [InfiniteFlightAirportEditing/Airports#606]
Redoing Bristol Airport

**Comment by chriscroft20** [comment]
sent for review

**Comment by kilt46** [comment]
Seems to be missing stands 34-36
![image](https://cloud.githubusercontent.com/assets/14023167/15455174/26569e5c-2012-11e6-9f54-a4464d9dca9a.png)

**Comment by TristinWoolf** [comment]
Will look into this quickly.

**Comment by TristinWoolf** [comment]
@kilt46 It looks like that chart is different than what the WEDBing imagery shows. The concrete area does not extend past 31, 32, and 33.

**Comment by samuelandersson** [comment]
I could not find any imaginary where does parking stands are visible.

**Comment by dushyants19** [comment]
what shall we do now? 💭

**Comment by PaulNielsen** [comment]
@dushyants19 I will look into this one later today, as there looks to be no Bing scenery of it, I will just add 3 parkings there and try to make it as accuarate as possible! :)

**Comment by PaulNielsen** [comment]
Or wait... The whole apron has been extended, and new taxi lines etc. Can't do that without image.

**Comment by Adam167** [comment]
Ok, it seems the google images have been updated on SAS to include these stands
Jan has sent the SAS files so I can do this.

**Comment by liamkirky** [comment]
You doing this?

**Comment by brunocr98** [comment]
Duh 🙄, why you think he self-assigned the airport?

**Comment by Will171** [comment]
I'm happy to do it if you haven't got enough time on your hands 👍

**Comment by Adam167** [comment]
Just to clear this one up, yes I am doing it, it's not too far off being finished.

**Comment by brunocr98** [comment]
This airport is not Priority 2. The Runway is less than 10,000ft.

https://skyvector.com/airport/EGGD/Bristol-Airport

**Comment by dushyants19** [comment]
Adam hows this going

**Comment by Will171** [comment]
🙄

**Comment by brunocr98** [comment]
😂

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25299580/1e41b678-26c6-11e7-8426-e9ce1f10db7c.png)

**Comment by kilt46** [comment]
EGGD edited. Please remove buildings

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45257130-ccdef500-b366-11e8-9a6f-a7a508056cf7.png)

**Comment by ItsW1ll** [comment]
Will be adding stands 37,38,39 and updating the airport
