### ISSUE TITLE
HKOM-Angama Airport-NAROK-KENYA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6060]
# Airport Name
Angama Mara Airstrip
# Country?
Kenya
# Improvements that need to be made?
New Airport
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103323497-ab5b1900-4a08-11eb-88f8-b27ae701246e.png)
