### ISSUE TITLE
WADE-Letkol Wisnu Airport-BALI-INDONESIA

### ISSUE THREAD

**Issue by vinoalviano1994** [InfiniteFlightAirportEditing/Airports#6061]
# Airport Name
< Letkol Wisnu Airport >
# Country?
< Indonesia >
# Improvements that need to be made?
< Full Rework >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103283127-52a26680-499d-11eb-94ec-cc33d8d3761c.png)
