### ISSUE TITLE
KAFK-Nebraska City Municipal Airport-NEBRASKA-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6062]
# Airport Name
Nebraska City Municipal Airport
# Country?
USA
# Improvements that need to be made?
Manual edit
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

![Full](https://user-images.githubusercontent.com/59462519/103163811-f6074600-47fa-11eb-94fb-20943612beb2.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103249169-8fd20e80-4933-11eb-826c-55fd9c5c6f19.png)
