### ISSUE TITLE
5B2-Saratoga County Airport-NEW YORK-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6063]
# Airport Name
Saratoga County Airport
# Country?
USA
# Improvements that need to be made?
Manual edit
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103248964-9f048c80-4932-11eb-8513-cb233c521129.png)
