### ISSUE TITLE
WIOK-Ketapang Rahadi Oesman-KALIMANTAN-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6065]
# Airport Name
< Rahadi Oesman >
# Country?
< Indonesia >
# Improvements that need to be made?
< Create New Airport >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low Priority >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103324342-c760b980-4a0c-11eb-9df8-ba1a8c2bfb2b.png)
