### ISSUE TITLE
4FD3-The Wright Place Airport-FLORIDA-UNITED STATES

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6066]
# Airport Name
The Wright Place Airport
# Country?
'Murica
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yea
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103249596-a711fb80-4935-11eb-9b27-2cb0708087c4.png)
