### ISSUE TITLE
FQVL-Vilanculo Airport-INHAMBANE-MOZAMBIQUE

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#6067]
# Airport Name
Vilanculo Airport
# Country?
Mozambique
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103246932-bb043000-492a-11eb-994a-7b3633cd8f4e.png)
