### ISSUE TITLE
SDZG-Pedro Teixeira Castelo Airport-CEARA-BRAZIL

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#6068]
# Airport Name
Pedro Teixeira Castelo Airport
# Country?
Brazil
# Improvements that need to be made?
Added
# Are you working on this airport?
Yep
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103316756-1bf53c00-49ef-11eb-9cbd-46a3588d0630.png)
