### ISSUE TITLE
FNDU-Kamakenzo Airport-LUNDA NORTE-ANGOLA

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#6069]
# Airport Name
Kamakenzo Airport
# Country?
Angola
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103322491-ae9fd600-4a03-11eb-8627-417ce343c6f2.png)
