### ISSUE TITLE
OIHS-Hamadan-Shahrokhi Air Force Base-HAMADAN-IRAN

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#607]
Please redesign me!

**Comment by JcFl4** [comment]
Nevermind this, already another issue available.

**Comment by Ksisky** [comment]
On it.

**Comment by turkish1941** [comment]
it is a duplicate, I have already finished it. And the ICAO is ZBAA not ZBBA

**Comment by IFAEpat** [comment]
Already done by @turkish1941

**Comment by IFAEpat** [comment]
#755

**Comment by MajorTomMueller** [comment]
![oihs-git](https://user-images.githubusercontent.com/26853210/36393453-ef81f940-15af-11e8-89d9-4cf50d242b5c.jpeg)

**Comment by MajorTomMueller** [comment]
adjusted roofed spawns to fir IF fighters completely under roof

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/40267957-de0d7020-5b2a-11e8-8f04-0594fc520902.png)

**Comment by MajorTomMueller** [comment]
Boundary Fix
Buildings removed
Hanagar Flors added
![OIHS](https://user-images.githubusercontent.com/26853210/54828614-dc93aa80-4cb4-11e9-89f8-d86d5877cc7d.jpg)
