### ISSUE TITLE
6Y3-North Fox Island Airport-MICHIGAN-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#6070]
# Airport Name
North Fox Island Airport
# Country?
USA
# Improvements that need to be made?
added to IF
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![Uploading image.png…]()
