### ISSUE TITLE
FBKE-Kasane Airport-NORTH-WEST-BOTSWANA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#6071]
# Airport Name
Kasane Airport
# Country?
Botswana
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103316169-4645fa00-49ed-11eb-87d1-7e74e2aeff99.png)
