### ISSUE TITLE
KMCN-Middle Georgia Regional Airport-GEORGIA-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#6072]
# Airport Name
Middle Georgia Regional Airport
# Country?
USA
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104095264-8ada5c80-525b-11eb-8c31-4828943e87a7.png)
