### ISSUE TITLE
EGOE-RAF Ternhill-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6073]
# Airport Name
RAF Ternhill
# Country?
UK
# Improvements that need to be made?
missing runway and some other fixes
# Are you working on this airport?
yeeeeeeeeeeeeees
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by MajorTomMueller** [comment]
[EGOE-Ternhill-Combined.pdf](https://github.com/InfiniteFlightAirportEditing/Airports/files/5746903/EGOE-Ternhill-Combined.pdf)
[EGOE-Ternhill-Aerodrome.pdf](https://github.com/InfiniteFlightAirportEditing/Airports/files/5746904/EGOE-Ternhill-Aerodrome.pdf)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103411717-0d19a100-4b37-11eb-81c0-bf18e9e4f6e3.png)
