### ISSUE TITLE
UUCB-Beloomut-MOSCOW-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6074]
# Airport Name
< Beloomut >
# Country?
< 🇷🇺  >
# Improvements that need to be made?
< redo >
# Are you working on this airport?
< yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< very low >
54.9519444°, 039.2966667°

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103247669-53031900-492d-11eb-84a4-150e04eeb5b8.png)
