### ISSUE TITLE
UUCW-Vikhrevo-MOSCOW-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6075]
# Airport Name
< Vikhrevo >
# Country?
< 🇷🇺  >
# Improvements that need to be made?
< Redo >
# Are you working on this airport?
< Yes>
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103325900-91730380-4a13-11eb-90a8-7a65192f4a8e.png)
