### ISSUE TITLE
ZPDQ-Diqing Shangri-La Airport-YUNNAN-CHINA

### ISSUE THREAD

**Issue by TsurugiHina** [InfiniteFlightAirportEditing/Airports#6076]
# Airport Name
< Diqing Shangri-La >
# Country?
< CN >
# Improvements that need to be made?
< New >
# Are you working on this airport?
< Yep >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123510933-de8f0580-d643-11eb-8470-7ceead041ff5.png)
