### ISSUE TITLE
AYMO-Momote Airport-MANUS-PAPUA NEW GUINEA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#6079]
# Airport Name
Momote Airport
# Country?
Papua New Guinea
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103247440-87c2a080-492c-11eb-9544-d03592202990.png)
