### ISSUE TITLE
KALS-San Luis Valley Regional Airport-COLORADO-USA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6081]
# Airport Name
Alamosa / San Luis Valley Regional Airport
# Country?
USA USA USA USA USA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yeee
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104250920-42c26200-5434-11eb-9caa-ea87fbf7d8b5.png)
