### ISSUE TITLE
KFHU-Sierra Vista Municipal Airport-ARIZONA-USA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6082]
♻️

**Comment by brunocr1050** [comment]
@Daniel-Baiks, T05 was redone already... #5694

**Comment by OscarConklin** [comment]
May I do this one?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105580173-63ea5300-5d50-11eb-9c35-60b43fadc50c.png)
