### ISSUE TITLE
KFAY-Fayetteville Regional Airport-NORTH CAROLINA-USA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6083]
# Airport Name
Fayetteville Regional Airport
# Country?
USA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104812946-6df9d800-57cb-11eb-8734-91500fd054da.png)
