### ISSUE TITLE
UUDG-Bolshoye Gryzlovo-MOSCOW-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6084]
# Airport Name
< Bolshoye Gryzlovo >
# Country?
< 🇷🇺  >
# Improvements that need to be made?
< redo >
# Are you working on this airport?
< yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104091966-92433b00-5246-11eb-831f-a05ca3747c3a.png)
