### ISSUE TITLE
OISY-Yasouj Airport-IRAN

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#6085]
# Airport Name
Yasouj Airport
# Country?
Iran
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yup
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103318091-ebaf9c80-49f2-11eb-9c42-565b5b1f462a.png)
