### ISSUE TITLE
WIHJ-Bogor Atang Sandjaya-JAWA-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6086]
# Airport Name
< Atang Sandjaya Airbase >
# Country?
< Indonesia >
# Improvements that need to be made?
< Create New Airport >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low Priority >

**Comment by adibyaputra** [comment]
@brunocr1050 Hi, I have an error in naming this Airport ICAO, can someone replace it with "WIHJ"?

Thank you.

**Comment by kilt46** [comment]
This airport is NOT in the REPO
![image](https://user-images.githubusercontent.com/14023167/104106027-21b51200-5278-11eb-9c41-f850b87125bd.png)

**Comment by kilt46** [comment]
![Uploading image.png…]()
