### ISSUE TITLE
FBFT-Francistown Airport-NORTH-EAST-BOTSWANA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#6087]
# Airport Name
Francistown International Airport
# Country?
Botswana
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103315946-abe5b680-49ec-11eb-83fd-75beabed2300.png)
