### ISSUE TITLE
SDOU-Ourinhos Airport-SAO PAULO-BRAZIL

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#6088]
# Airport Name
Ourinhos Airport
# Country?
Brazil
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yup
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103322268-20c3eb00-4a03-11eb-9216-01a33b69f9a5.png)
