### ISSUE TITLE
TGPZ-Lauriston Airport-GRENADA

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#6089]
# Airport Name
Lauriston Airport
# Country?
Grenada
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103328818-e0269a80-4a1f-11eb-95c2-2eab82cb067a.png)
