### ISSUE TITLE
KBOS-General Edward Lawrence Logan International Airport-MASSACHUSETTS-USA

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#609]
Logan Intl. 
Boston, USA
Missing terminals, and some fixes needed, anyone interested?

**Comment by CptNathanHope** [comment]
Sent it for review! :)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21499665/7febe70a-cbfd-11e6-96d2-1c43df40ba78.png)

**Comment by CptNathanHope** [comment]
Received updated imagery for this airport so I'm going to do a few changes to it.

**Comment by CptNathanHope** [comment]
Changes made in `[9ca866f](https://github.com/InfiniteFlightAirportEditing/Airports/commit/9ca866f6bcbe9bde40f9fc4cf6df72dc3ca3f23d)`.

**Comment by CptNathanHope** [comment]
Going to revisit this one. Doing from scratch with more details.

**Comment by kilt46** [comment]
PLEASE REMOVE BUILDINGS - INCLUDE CONCRETE HANGAR PADS
Let me know if you would like me to take care of this

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/41946048-fb7969d4-7975-11e8-82ea-4f29e53522cd.png)

**Comment by kilt46** [comment]
Buildings Removed by Nathan
![image](https://user-images.githubusercontent.com/14023167/42127727-66c2cd62-7c63-11e8-8f54-43235068d3e9.png)
