### ISSUE TITLE
HTDO-Dodoma Airport-DODOMA-TANZANIA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#6090]
# Airport Name
Dodoma Airport
# Country?
Tanzania
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103328411-70fc7680-4a1e-11eb-8314-3bb93b0f9f72.png)
