### ISSUE TITLE
SJCA-Comandante Vittorio Bonomi-SAO PAULO-BRAZIL

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#6092]
# Airport Name
Comandante Vittorio Bonomi
# Country?
Brazil
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103321515-9e85f780-49ff-11eb-9f5b-fd0a6c4cc1ba.png)
THIS has not been uploaded. Looks nothing like reality!

**Comment by brunocr1050** [comment]
Commit coming soon...

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103322070-43093900-4a02-11eb-9654-a7d63d175730.png)
