### ISSUE TITLE
6NA5-Chase Airstrip-NORTH DAKOTA-USA

### ISSUE THREAD

**Issue by Captainflight** [InfiniteFlightAirportEditing/Airports#6093]
# Airport Name
< Chase Airstrip >
# Country?
< United States  >
# Improvements that need to be made?
< Rework from scratch  >
# Are you working on this airport?
< Yes>
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by kilt46** [comment]
![Uploading image.png…]()
