### ISSUE TITLE
4B6-Ticonderoga Municipal Airport-NEW YORK-USA

### ISSUE THREAD

**Issue by Pingu29** [InfiniteFlightAirportEditing/Airports#6094]
# Airport Name
Ticonderoga Municipal Airport
# Country?
United States
# Improvements that need to be made?
Manual edit
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by ShaneAviation** [comment]
I can finish it up.

**Comment by brunocarbone3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/134684703-5804a7dc-717d-4552-8a5a-40f159e35a84.png)
