### ISSUE TITLE
UUDN-Novinki-MOSCOW-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6095]
# Airport Name
< Novinki >
# Country?
< 🇷🇺  >
# Improvements that need to be made?
< redo >
# Are you working on this airport?
< yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104092197-ef8bbc00-5247-11eb-8808-a6e4e102a4bd.png)
