### ISSUE TITLE
PAEW-Newtok Airport-ALASKA-USA

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6096]
# Airport Name
Newtok Airport
# Country?
USA
# Improvements that need to be made?
redo
# Are you working on this airport?
yeees
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103411861-f58ee800-4b37-11eb-9366-dc37d2e6b923.png)
