### ISSUE TITLE
WIMP-Toba Sibisa-SUMATRA-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6098]
# Airport Name
< Sibisa >
# Country?
< Indonesia >
# Improvements that need to be made?
< Create New Airport >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low Priority >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104105905-3ba22500-5277-11eb-9c92-3e76fa091f8b.png)
