### ISSUE TITLE
VERB-Fursatganj Airport-UTTAR PRADESH-INDIA

### ISSUE THREAD

**Issue by hari-shreyas** [InfiniteFlightAirportEditing/Airports#6099]
# Airport Name
Fursatganj Airport
# Country?
India
# Improvements that need to be made?
addition to IF
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107583099-154a0f00-6bc0-11eb-9734-71ccdfc852e4.png)
