### ISSUE TITLE
LFOB-Beauvais Tille Airport-PICARDIE-FRANCE

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#61]

**Comment by carmichaelalonso** [comment]
Assigned to Axel Beder

**Comment by carmichaelalonso** [comment]
@AxelBeder use this one

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21080770/e940d46e-bf7c-11e6-9a83-4e101ced108a.png)

**Comment by MBeringuy** [comment]
![lfob](https://user-images.githubusercontent.com/32115399/100389398-0665ae80-300c-11eb-9c3b-cf94f0ee0ddd.png)
