### ISSUE TITLE
WADD-I Gusti Ngurah Rai Airport-BALI-INDONESIA

### ISSUE THREAD

**Issue by CaptainTrapBeats** [InfiniteFlightAirportEditing/Airports#610]
Completed!

**Comment by dushyants19** [comment]
Still not approved? Probably something wrong on your part.

**Comment by IFAEpat** [comment]
@CaptainTrapBeats please work on this, many overlapped taxiways, unsnapped lines, needs many more spawn points too.

**Comment by dushyants19** [comment]
@CaptainTrapBeats any progress on this and #600?

**Comment by CaptainTrapBeats** [comment]
No

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by lalomarlin** [comment]
I'm on

**Comment by lalomarlin** [comment]
@TristinWoolf

**Comment by lalomarlin** [comment]
It was already done, ca you unassign @dushyants19 :)

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22572827/97565552-e96b-11e6-9b74-a21064455280.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/81994006-4db2c180-961d-11ea-9823-a464fcb49988.jpg)
