### ISSUE TITLE
YBRK-Rockhampton Airport-QUEENSLAND-AUSTRALIA

### ISSUE THREAD

**Issue by victormw22** [InfiniteFlightAirportEditing/Airports#6100]
# Airport Name
< Rockhampton Airport >
# Country?
< Australia >
# Improvements that need to be made?
< Redone >
# Are you working on this airport?
< yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104110343-74a0c080-529c-11eb-8d0d-4c3db3b18241.png)
