### ISSUE TITLE
TA31-Tularosa Airfield-TEXAS-USA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6101]
# Airport Name
Tularosa Airfield
# Country?
USA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Ye
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103480853-7d752c00-4d9c-11eb-9c29-d8a30d035625.png)
