### ISSUE TITLE
LFAK-Dunkerque Les Moëres-France-HAUTS-DE-FRANCE

### ISSUE THREAD

**Issue by Jeremy351** [InfiniteFlightAirportEditing/Airports#6102]
# Airport Name
Dunkerque Les Moëres
# Country?
France
# Improvements that need to be made?
Full redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103412232-b5306980-4b39-11eb-9e96-56af92a3c122.png)
