### ISSUE TITLE
MTCA-Les Cayes Airport-HAITI

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#6103]
# Airport Name
Les Cayes Airport
# Country?
Haiti
# Improvements that need to be made?
Redone
# Are you working on this airport?
Ya
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103412591-7d2a2600-4b3b-11eb-847f-d5cc63dcf20e.png)
