### ISSUE TITLE
DRRT-Tahoua Airport-NIGER

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#6104]
# Airport Name
Tahoua Airport
# Country?
Niger
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yup
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103415810-62f74480-4b49-11eb-8946-bc91f80ea59f.png)
