### ISSUE TITLE
DRZA-Agadez Mano Dayak Airport-NIGER

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#6105]
# Airport Name
Agadez Mano Dayak Airport
# Country?
Niger
# Improvements that need to be made?
Redone
# Are you working on this airport?
Ye
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103415666-d3519600-4b48-11eb-9abd-d0f087e4d658.png)
