### ISSUE TITLE
SAWD-Puerto Deseado Airport-SANTA CRUZ-ARGENTINA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#6106]
# Airport Name
Puerto Deseado Airport
# Country?
Argentina
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103412746-3ee13680-4b3c-11eb-9a14-21f28717fcc5.png)
