### ISSUE TITLE
DRRM-Maradi-MARADI-NIGER

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6107]
# Airport Name
Maradi
# Country?
niger
# Improvements that need to be made?
redo
# Are you working on this airport?
yes i am
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103438800-b2e31380-4bfc-11eb-9296-35942fea9c9e.png)
