### ISSUE TITLE
KAFO-Afton Municipal Airport-WYOMING-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6108]
# Airport Name
Afton Municipal Airport
# Country?
USA
# Improvements that need to be made?
Manual edit
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

![Full](https://user-images.githubusercontent.com/59462519/103397430-469ade00-4b30-11eb-9441-37fd612f0b94.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103439709-df9b2900-4c04-11eb-8ac7-0ac882ca29d6.png)
