### ISSUE TITLE
DRZR-Zinder-ZINDER-NIGER

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6109]
# Airport Name
Zinder
# Country?
niger
# Improvements that need to be made?
redo
# Are you working on this airport?
ye
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103438741-00ab4c00-4bfc-11eb-9c89-035e1e97afde.png)
