### ISSUE TITLE
TFFF-Martinique Aime Cesaire Airport-FORT-DE-FRANCE-MARTINIQUE

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#611]
RECYCLED ♻️

**Comment by IFAEpat** [comment]
Parking error, Minor design issue and Suggestion labels are needed

**Comment by IceBlue02** [comment]
^^^ Super helpful, thanks @IFAEpat

**Comment by patspark** [comment]
ill do this

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26275727/574dda32-3d2d-11e7-8aa2-63da3cd33e9f.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34649820-115263e4-f37c-11e7-9886-a1c8746e4e77.png)
TFFF is both offset and not correctly aligned/scaled. May need a redo

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34700582-7dd8ae1e-f4a9-11e7-9231-5214a2184c6c.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34701045-9e3323e0-f4ab-11e7-856e-f887fccc80b7.png)
