### ISSUE TITLE
TAPH-Barbuda Codrington Airport-BARBUDA-ANTIGUA AND BARBUDA

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#6111]
# Airport Name
Barbuda Codrington Airport
# Country?
Antigua And Barbuda
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yup
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103439545-6b13ba80-4c03-11eb-8281-de2f77de7e69.png)
