### ISSUE TITLE
LGPL-Astypalaia Airport-GREECE

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#6112]
# Airport Name
Astypalaia Airport
# Country?
Greece
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103439435-8500cd80-4c02-11eb-99ef-074c54dd9d49.png)
