### ISSUE TITLE
LGKZ-Kozani Filippos Airport-GREECE

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#6113]
# Airport Name
Kozani Filippos Airport
# Country?
Greece
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103439328-8da4d400-4c01-11eb-8551-f0011a1beb65.png)
