### ISSUE TITLE
LGSO-Syros-CYCLADES-GREECE

### ISSUE THREAD

**Issue by davide-dc** [InfiniteFlightAirportEditing/Airports#6114]
# Airport Name
Syros
# Country?
Greece
# Improvements that need to be made?
Full redo
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103438938-289baf00-4bfe-11eb-8b41-2509bb22b249.png)
