### ISSUE TITLE
DRZL-Arlit Airport-AGADEZ-NIGER

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6117]
# Airport Name
Arlit Airport
# Country?
niger
# Improvements that need to be made?
done from scratch
# Are you working on this airport?
y e s
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103438700-60edbe00-4bfb-11eb-8ed6-3abb9755b687.png)
