### ISSUE TITLE
DRRG-Gaya Airstrip-DOSSO-NIGER

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6118]
# Airport Name
Gaya Airstrip
# Country?
niger
# Improvements that need to be made?
done from scratch
# Are you working on this airport?
**YES**
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103479457-549c6900-4d93-11eb-9a76-7c163c4dbd58.png)
