### ISSUE TITLE
LG53-Lamia-CENTRAL GREECE-GREECE

### ISSUE THREAD

**Issue by davide-dc** [InfiniteFlightAirportEditing/Airports#6119]
# Airport Name
Lamia
# Country?
Greece
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103438848-516f7480-4bfd-11eb-8c9c-476325099b50.png)
