### ISSUE TITLE
EGNH- Blackpool Airport-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by chriscroft20** [InfiniteFlightAirportEditing/Airports#612]
Redoing Blackpool Airport

**Comment by chriscroft20** [comment]
Sent for review

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20370213/1f4fab10-ac23-11e6-8b6d-ff051debf632.png)

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26704241/58cbae3c-46f3-11e7-8704-558214ec28ff.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26720588/7b4f4ddc-474e-11e7-953c-a074ec79a589.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46907192-8d12ac80-ced4-11e8-8fc5-a1272f9ff04d.png)

**Comment by ItsW1ll** [comment]
Latest imagery shows airline gates have been removed

**Comment by ItsW1ll** [comment]
Added in 45b569c
