### ISSUE TITLE
DRZI-Iferouane Airstrip-AGADEZ-NIGER

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6120]
# Airport Name
Iferouane Airstrip
# Country?
niger
# Improvements that need to be made?
done from scratch 
# Are you working on this airport?
### **YES**
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103479365-dcce3e80-4d92-11eb-8fae-2dbfebaaa489.png)
