### ISSUE TITLE
SBYS-Campo Fontenelle-SAO PAULO-BRAZIL

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#6121]
# Airport Name
Campo Fontenelle
# Country?
Brazil
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103479869-3dab4600-4d96-11eb-8abb-3afede3fad2d.png)
