### ISSUE TITLE
DRRC-Dogondoutchi Airstrip-DOSSE-NIGER

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6122]
# Airport Name
Dogondoutchi Airstrip
# Country?
niger
# Improvements that need to be made?
done from scratch
# Are you working on this airport?
guess what: yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103479275-3d10b080-4d92-11eb-9296-ad9bb5b23eb1.png)
