### ISSUE TITLE
LGSP-Sparti-PELOPONNESE-GREECE

### ISSUE THREAD

**Issue by davide-dc** [InfiniteFlightAirportEditing/Airports#6123]
# Airport Name
Sparti
# Country?
Greece
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
loow

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103479723-3cc5e480-4d95-11eb-8b05-23aa2ecfb425.png)
