### ISSUE TITLE
LGKM-Kavala Amigdhaleon-MACEDONIA-GREECE

### ISSUE THREAD

**Issue by davide-dc** [InfiniteFlightAirportEditing/Airports#6124]
# Airport Name
Kavala Amigdhaleon
# Country?
Greece
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103479641-c45f2380-4d94-11eb-97b5-812a59fe2a80.png)
