### ISSUE TITLE
KAFP-Anson County Airport-NORTH CAROLINA-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6125]
# Airport Name
Anson County Airport
# Country?
USA
# Improvements that need to be made?
Manual edit
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

![Full](https://user-images.githubusercontent.com/59462519/103433553-a655bf80-4bea-11eb-99b3-71b8f37edf5a.png)

**Comment by kilt46** [comment]
![Uploading image.png…]()
