### ISSUE TITLE
SNAU-Fazenda Americana Airstrip-MARANHAO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#6126]
# Airport Name
Fazenda Americana Airstrip
# Country?
Brazil
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103445436-b21ca280-4c39-11eb-8f6e-9977e2c4c355.png)
