### ISSUE TITLE
KEDU-University-CALIFORNIA-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6129]
# Airport Name
University
# Country?
:us:
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Even Lower

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103462888-126d1c00-4cee-11eb-94d5-ca451d5d9c62.png)
