### ISSUE TITLE
TJSJ-Luis Munoz Marin Airport-SAN JUAN-PUERTO RICO

### ISSUE THREAD

**Issue by Blently** [InfiniteFlightAirportEditing/Airports#613]
Needs the newest extension to the taxiway and the runway (2013), taxi lights and there's a spawn point near a hold short line, I don't know why. Lol
I will do it

**Comment by bylrret** [comment]
Adding spawn points and done.

**Comment by dushyants19** [comment]
Cool @bylrret, make sure you post your .dat file in #peer-review in Slack so that we can check on your first airport!

**Comment by bylrret** [comment]
Sent to #peer-review @dushyants19

**Comment by bylrret** [comment]
Waiting for approval

**Comment by IFAEpat** [comment]
Many holds not snapped, gate lines have taxi centerline lights, gonna fix this one up

**Comment by IFAEpat** [comment]
Tweaked and Gated

**Comment by IFAEpat** [comment]
oops, sorry about that

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19213682/f6f0f840-8d37-11e6-95bb-8004e5400e52.png)

**Comment by brunocr98** [comment]
@bylrret will be adding some missing ATC frequencies and doing fixes to the displaced thresholds and taxiways.

**Comment by bylrret** [comment]
Sent to review

**Comment by bylrret** [comment]
New imagery shows that terminal C has been renamed as part of B and terminal D ( which probably will be call C) is closed and is been used as GA parking, I will add this and will probably be done for tomorrow.

**Comment by Blently** [comment]
Send for review

**Comment by kilt46** [comment]
SUGGESTED GATE CONFIGURATION
![image](https://user-images.githubusercontent.com/14023167/28754340-c39d5f2e-7508-11e7-9546-5222f1530cb6.png)

**Comment by Blently** [comment]
Sent for review

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56609935-fb4ad100-65d3-11e9-8395-b36034b9445c.png)
