### ISSUE TITLE
KCZT-Dimmit County-TEXAS-USA

### ISSUE THREAD

**Issue by 2000rpm** [InfiniteFlightAirportEditing/Airports#6130]
# Airport Name
Dimmit County
# Country?
USA
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103480783-ec05ba00-4d9b-11eb-8d99-0cc52a7ed8be.png)
