### ISSUE TITLE
KAGO-Magnolia Municipal Airport-ARKANSAS-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6131]
# Airport Name
Magnolia Municipal Airport
# Country?
USA
# Improvements that need to be made?
Manual edit
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

![Full](https://user-images.githubusercontent.com/59462519/103453469-36baff80-4cd2-11eb-863b-8f01a722d720.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103480421-ddb69e80-4d99-11eb-8417-5bcb75319902.png)
