### ISSUE TITLE
LFIS-Saint Inglevert Les Deux Caps-NORDS-FRANCE

### ISSUE THREAD

**Issue by Jeremy351** [InfiniteFlightAirportEditing/Airports#6133]
# Airport Name
Saint Inglevert Les Deux Caps
# Country?
France
# Improvements that need to be made?
Full redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103478774-8e1ea580-4d8e-11eb-966b-c462275da492.png)
