### ISSUE TITLE
ZPMS-Dehong Mangshi Airport-YUNNAN-CHINA

### ISSUE THREAD

**Issue by zacky89315** [InfiniteFlightAirportEditing/Airports#6134]
# Airport Name
< Dehong Mangshi Airport >
# Country?
< China >
# Improvements that need to be made?
< Redone from scratch >
# Are you working on this airport?
< YES >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104526135-50f4b780-55c7-11eb-8b95-641cfa63ec97.png)
