### ISSUE TITLE
KCIC-Chico Municipal-CALIFORNIA-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6135]
# Airport Name
Chico Municipal
# Country?
USA
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Lower Than Ever

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103711788-c9cb9200-4f7d-11eb-9323-67e897d127a0.png)
