### ISSUE TITLE
LG56-Olimboi-NORTH AEGEAN ISLANDS-GREECE

### ISSUE THREAD

**Issue by davide-dc** [InfiniteFlightAirportEditing/Airports#6136]
# Airport Name
Olimboi
# Country?
Greece
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103479548-0c317b00-4d94-11eb-8dea-987eedc75df2.png)
