### ISSUE TITLE
LG03-Maleme-CRETE-GREECE

### ISSUE THREAD

**Issue by davide-dc** [InfiniteFlightAirportEditing/Airports#6137]
# Airport Name
Maleme
# Country?
Greece
# Improvements that need to be made?
Full redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103592918-f1592680-4eb9-11eb-9aa6-716d98487428.png)
