### ISSUE TITLE
DRRP-La Tapoa Airstrip-TILLABERI-NIGER

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6138]
# Airport Name
La Tapoa Airstrip
# Country?
niger
# Improvements that need to be made?
done from scratch
# Are you working on this airport?
**y e s**
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![Uploading image.png…]()
