### ISSUE TITLE
DRRD-Dosso Airfield-DOSSE-NIGER

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6139]
# Airport Name
Dosso Airfield
# Country?
niger
# Improvements that need to be made?
done from scratch
# Are you working on this airport?
¥€$
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103592566-f79ad300-4eb8-11eb-8883-b7f4c2f361ed.png)
