### ISSUE TITLE
UUBM-Myachkovo-MOSCOW-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6140]
# Airport Name
Myachkovo
# Country?
:ru:
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104092696-49da4c00-524b-11eb-84f8-3bdffeb42ef5.png)
