### ISSUE TITLE
GMAG-Guelmim Airport-GUELMIM OUED NOUN-MOROCCO

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6141]
# Airport Name
Guelmim Airport
# Country?
Morocco
# Improvements that need to be made?
New
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103478977-e0ac9180-4d8f-11eb-8316-26cab0c823ce.png)
