### ISSUE TITLE
GMAT-Tan Tan Plage Blanche International Airport-ES SEMARA-MOROCCO

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6142]
# Airport Name
Tan Tan Plage Blanche International Airport
# Country?
Morocco
# Improvements that need to be made?
Redo
# Are you working on this airport?
Si
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103478865-33397e00-4d8f-11eb-9e97-6158298403d6.png)
