### ISSUE TITLE
KAGZ-Wagner Municipal Airport-SOUTH DAKOTA-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6143]
# Airport Name
Wagner Municipal Airport
# Country?
USA
# Improvements that need to be made?
Manual edit
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

![Full](https://user-images.githubusercontent.com/59462519/103474471-1d7e8580-4d9c-11eb-8620-c0f81bf73ccc.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103480308-333e7b80-4d99-11eb-8759-b5d6edc2e895.png)
