### ISSUE TITLE
DRZF-Diffa Airport-NIGER

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#6144]
# Airport Name
Diffa Airport
# Country?
Niger
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103591136-e4860400-4eb4-11eb-9f5d-1bfe468a6bfe.png)
