### ISSUE TITLE
DUPLICATE 

### ISSUE THREAD

**Issue by IFUA2003** [InfiniteFlightAirportEditing/Airports#6147]
# Airport Name
< Dong Hoi Airport>
# Country?
< Vietnam >
# Improvements that need to be made?
< This airport hadn't been added >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< No >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104250126-8d42df00-5432-11eb-9cbf-90d9a890744e.png)
