### ISSUE TITLE
SDCZ-Bom Jardim Airport-RIO DE JANEIRO-BRAZIL

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Airports#6148]
# Airport Name
< Fazenda Bom Jardim >
# Country?
< Brazil >
# Improvements that need to be made?
< Redone from scratch >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103708138-9e44a980-4f75-11eb-86fb-ecacc29b78e8.png)
