### ISSUE TITLE
LAKV-Kuçovë Airbase-BERAT-ALBANIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6149]
# Airport Name
Kuçovë Airbase
# Country?
Albania
# Improvements that need to be made?
New
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104111198-dbc27300-52a4-11eb-93e5-2a378afd29b9.png)
