### ISSUE TITLE
FAUP-Upington Airport-NORTHERN CAPE-SOUTH AFRICA

### ISSUE THREAD

**Issue by Zimnaan** [InfiniteFlightAirportEditing/Airports#615]
REUSED

**Comment by dushyants19** [comment]
You should have checked #326, I told you to search.

**Comment by TristinWoolf** [comment]
I will do this one.

**Comment by TristinWoolf** [comment]
Finished and sent in.

**Comment by kilt46** [comment]
Taxiway to terminal missing
![image](https://cloud.githubusercontent.com/assets/14023167/16362928/c26fa9da-3b80-11e6-9dd1-3aaaeef31a5f.png)

**Comment by TristinWoolf** [comment]
This is an easy fix of making the taxiway visible again in WED. I will fix this when I get home in a few hours.

**Comment by TristinWoolf** [comment]
Should be fixed now. Just awaiting a thumbs up from another person, just to confirm that its still not only showing up on my WED.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20292012/ef878bf6-aaaf-11e6-9959-0c97529b4646.png)
