### ISSUE TITLE
PHNG-Kaneohe Bay Marine Corps Air Station (Marion E Carl Field)-HAWAII-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#6150]
# Airport Name
Kaneohe Bay Marine Corps Air Station (Marion E Carl Field)
# Country?
USA
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106405674-a8cf5300-63fc-11eb-99a4-59b2c4ed7ab9.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106449485-a2b39380-6449-11eb-8200-4bf5926dbda9.png)
