### ISSUE TITLE
GMAZ-Zagora Airport-SOUSS MASSA DRAA-MOROCCO

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6151]
# Airport Name
Zagora Airport
# Country?
Morocco
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103955877-ee09a900-510c-11eb-87f6-d7f073167845.png)
