### ISSUE TITLE
GMFB-Bouarfa Airport-ORIENTAL-MOROCCO

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6152]
# Airport Name
Bouarfa Airport
# Country?
Morocco
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
10k+

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103955397-cb2ac500-510b-11eb-9225-d2a801495057.png)
