### ISSUE TITLE
GMFI-Ifrane Airport-FES MEKNES-MOROCCO

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6153]
# Airport Name
Ifrane Airport
# Country?
Morocco
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103955137-4c358c80-510b-11eb-86dc-4ec3fd78b93b.png)
