### ISSUE TITLE
DRZD-Dirkou-AGADEZ-NIGER

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6154]
# Airport Name
Dirkou
# Country?
niger
# Improvements that need to be made?
redo
# Are you working on this airport?
ye
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103590911-61fd4480-4eb4-11eb-8310-1f39fd48e68a.png)
