### ISSUE TITLE
DRZN-N'Guigmi Airstrip-DIFFA-NIGER

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6155]
# Airport Name
N'Guigmi Airstrip
# Country?
niger
# Improvements that need to be made?
done from scratch
# Are you working on this airport?
ye
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103584853-bea63280-4ea7-11eb-8625-d1668465018c.png)
