### ISSUE TITLE
TN41-100 Aker Wood Airport-TENNESSEE-UNITED STATES

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#6156]
# Airport Name
100 Aker Wood Airport
# Country?
United States
# Improvements that need to be made?
New Airport
# Are you working on this airport?
YESSIR
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Highest of Priority (jk - its a grass strip)

**Comment by Balloonchaser** [comment]
Submitted to OR

**Comment by kilt46** [comment]
Altitude incorrect
![image](https://user-images.githubusercontent.com/14023167/104110663-77e97b80-529f-11eb-8f3d-c710ec309f24.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104131136-2a6e1c80-533a-11eb-9a00-d0e7f2dea441.png)
