### ISSUE TITLE
HRYG-Gisenyi Airport-WESTERN PROVINCE-RWANDA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#6157]
# Airport Name
Gisenyi Airport
# Country?
Rwanda
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104111092-0e1fa080-52a4-11eb-99c6-4c44980be116.png)
