### ISSUE TITLE
CLC2-Chapeskie Field-ONTARIO-CANADA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6158]
# Airport Name
< Chapeskie Field Airport >
# Country?
< Canada >
# Improvements that need to be made?
< Redo >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104107321-df440300-5280-11eb-9bed-fc11df88da68.png)
