### ISSUE TITLE
GMFK-Errachidia/Moulay Ali Cherif International Airport-DRAA TAFILALET-MOROCCA

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6159]
# Airport Name
Errachidia/Moulay Ali Cherif International Airport
Morocco
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
10k+

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103954885-bf8ace80-510a-11eb-8705-434beffee1d4.png)
