### ISSUE TITLE
LTBA-Atatürk Airport-ISTANBUL-TURKEY

### ISSUE THREAD

**Issue by turkish1941** [InfiniteFlightAirportEditing/Airports#616]
I would like to make the Atatürk International Airport in Turkey.

**Comment by turkish1941** [comment]
e-mail has been sent

**Comment by turkish1941** [comment]
Accepted around 2 weeks ago.

**Comment by Oguz8011** [comment]
Kabul edilip eklendi mi?

**Comment by turkish1941** [comment]
![screenshot_2016-06-25-23-09-55](https://cloud.githubusercontent.com/assets/13819750/16359175/a970d270-3b2a-11e6-97c2-3c5ed3867237.png)
evet eklendi

**Comment by Oguz8011** [comment]
Esenboğa ve Antalya da sıkıntı var diye gördüm sanki. İnşallah yoktur Allah senden razı olsun uğraşmasan kimsenin yapacağı yoktu :)

**Comment by samuelandersson** [comment]
Can we please keep all conversation to english so that everyone can understand the history of the issue and what people did to the airport when they worked on it? Thanks!

**Comment by turkish1941** [comment]
@Oguz8011  sağol abi
translation: thank you

**Comment by turkish1941** [comment]
already accepted and in the repo for a month, can someone close it ?

**Comment by IFAEpat** [comment]
Thanks for informing, @turkish1941

**Comment by kilt46** [comment]
This part isn't quite right
![image](https://cloud.githubusercontent.com/assets/14023167/16543372/23af95dc-4097-11e6-8589-6944fe115ab4.png)

**Comment by kilt46** [comment]
More specifically here:
![image](https://cloud.githubusercontent.com/assets/14023167/16543374/38fb8932-4097-11e6-8eec-9f86c393eaf7.png)

**Comment by kilt46** [comment]
Satellite image
![image](https://cloud.githubusercontent.com/assets/14023167/16543376/4bfc0bba-4097-11e6-9793-9fdb7f382fa0.png)

**Comment by kilt46** [comment]
Latest charts to help
![image](https://cloud.githubusercontent.com/assets/14023167/16543377/61478076-4097-11e6-8c03-0259d94cf099.png)

**Comment by kilt46** [comment]
This has now been completed

**Comment by dushyants19** [comment]
Minor changes done by Ilyas

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18455642/d2377eba-7910-11e6-8cdc-f83a04d0dd45.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18455647/dd0713b4-7910-11e6-98ed-c18274252773.png)

**Comment by kilt46** [comment]
Airport needs updated for Accuracy and changes

**Comment by kilt46** [comment]
H2, H3, H4 and H5 missing
![image](https://user-images.githubusercontent.com/14023167/39398441-b28c21c4-4ad3-11e8-8bdd-efa57b4c17aa.png)

**Comment by kilt46** [comment]
Gates Missing
![image](https://user-images.githubusercontent.com/14023167/39398448-cc3efcc2-4ad3-11e8-8abc-a445e6d995ef.png)

**Comment by kilt46** [comment]
Main Terminal not accurate
![image](https://user-images.githubusercontent.com/14023167/39398465-eb7f32e6-4ad3-11e8-8ba5-27b7f71a9712.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/39398471-0129f09a-4ad4-11e8-8fbc-1317d1e1fb5b.png)

**Comment by kilt46** [comment]
Missing
![image](https://user-images.githubusercontent.com/14023167/39398478-1adc1400-4ad4-11e8-8155-616836c156f6.png)

**Comment by MajorTomMueller** [comment]
Removal of disfunct runway to prevent IFATC from using it.

**Comment by MajorTomMueller** [comment]
![LTBA-git](https://user-images.githubusercontent.com/26853210/108518060-0fd77d80-72c0-11eb-8955-fe980285b335.png)
