### ISSUE TITLE
GMFZ-Taza Airport-FES MEKNES-MOROCCO

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6160]
# Airport Name
Taza Airport
# Country?
Morocco
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103954591-2bb90280-510a-11eb-8178-34ba20258e76.png)
