### ISSUE TITLE
GMMD-Beni Mellal International Airport-BENI MELLAL KHENIFRA-MOROCCO

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6161]
# Airport Name
Beni Mellal International Airport
# Country?
Morocco
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103953926-bc8ede80-5108-11eb-875c-7b8ab72308cb.png)
