### ISSUE TITLE
GMMI-Essaouira/Mogador International Airport-MARRAKESH SAFI-MOROCCA

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6162]
# Airport Name
Essaouira/Mogador International Airport
Morocco
# Improvements that need to be made?
REdo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103827682-293da680-503f-11eb-90ff-3755aab92204.png)
