### ISSUE TITLE
GMFM-Meknes Airport-FES MEKNES-MOROCCO

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6163]
# Airport Name
Meknes Airport
# Country?
Morocco
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103594604-c02f2500-4ebe-11eb-91fb-d9f163acf79e.png)
