### ISSUE TITLE
MMPC-Pachuca Airport-HIDALGO-MEXICO

### ISSUE THREAD

**Issue by lalomarlin** [InfiniteFlightAirportEditing/Airports#6164]
# Airport Name
< Pachuca >
# Country?
< Mexico >
# Improvements that need to be made?
< Redone >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103705470-b108af80-4f70-11eb-9390-66fe6356ec96.png)
