### ISSUE TITLE
KAHC-Amedee Army Airfield-CALIFORNIA-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6165]
# Airport Name
Amedee Army Airfield
# Country?
USA
# Improvements that need to be made?
Manual edit
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Runway is 10,000ft (in charts, not including blastpads, runway is actually 9,969ft)

![Full](https://user-images.githubusercontent.com/59462519/103502281-a0f5b080-4e48-11eb-8da1-78434c3b2262.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103710062-b4546900-4f79-11eb-870c-e4baf4b29403.png)
