### ISSUE TITLE
GMTN-Tetouan Saniat R’mel-TANGER TETOUAN AL HOCEIMA-MOROCCO

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6166]
# Airport Name
Tetouan Saniat R’mel
# Country?
Morocco
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103594252-beb12d00-4ebd-11eb-8157-852fe330ce5a.png)
