### ISSUE TITLE
GMTA-Al Hoecima/Cherif El Idrissi International Airport-TANGER TETOUAN AL HOCEIMA-MOROCCO

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6167]
# Airport Name
Al Hoecima/Cherif El Idrissi International Airport
# Country?
Morocco
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103594071-3c286d80-4ebd-11eb-80f4-dfb7c19f4a38.png)
