### ISSUE TITLE
KAHH-Amery Municipal Airport-WISCONSIN-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6168]
# Airport Name
Amery Municipal Airport
# Country?
USA
# Improvements that need to be made?
Manual edit
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104095134-d2141d80-525a-11eb-91bb-ac62626689c4.png)
