### ISSUE TITLE
18AA-18 Meadows Aerodrome-ALASKA-USA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Airports#6169]
# Airport Name
18 Meadows Aerodrome
# Country?
USA
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Grass Strip

**Comment by Balloonchaser** [comment]
Submitted for OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103709183-9f76d600-4f77-11eb-8732-5369d005dd3f.png)

**Comment by kilt46** [comment]
Incorrect altitude - Changed to 89 ft as per FAA

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103709423-1f04a500-4f78-11eb-8950-565b36fcfe3f.png)
