### ISSUE TITLE
SBSP-Congonhas Airport-SAO PAULO-BRAZIL

### ISSUE THREAD

**Issue by sumith11** [InfiniteFlightAirportEditing/Airports#617]
São Paulo–Congonhas Airport
Doing this :)

**Comment by dushyants19** [comment]
Many issues with this

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19333793/19020efa-90bd-11e6-9739-5e098d5aa901.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/43108706-cc84ecc8-8ea8-11e8-8a6f-3baabf370bdd.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/58820972-655e8900-860a-11e9-8805-d37e2d4ce438.jpg)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118895677-395a7200-b8cc-11eb-98cf-6f503d6bba2d.png)
