### ISSUE TITLE
SSKT-Aeroclube de Santa Catarina Airport-SANTA CATARINA-BRAZIL

### ISSUE THREAD

**Issue by victormw22** [InfiniteFlightAirportEditing/Airports#6173]
# Airport Name
< Aeroclube de Santa Catarina >
# Country?
< Brazil >
# Improvements that need to be made?
< Redone >
# Are you working on this airport?
< yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104075056-558c2b00-51d7-11eb-80fd-9367cac06abd.png)
