### ISSUE TITLE
DA10-Illizi Airport-ILLIZI-ALGERIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6174]
# Airport Name
Illizi Airport
# Country?
Algeria
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103593811-75141280-4ebc-11eb-9dd4-420c8f0469b9.png)
