### ISSUE TITLE
DA12-El Abiodh Sidi Cheikh Airport-AL-BAYADH-ALGERIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6175]
# Airport Name
El Abiodh Sidi Cheikh Airport
# Country?
Algeria
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103593647-ffa84200-4ebb-11eb-87aa-9a8c3acb4a27.png)
