### ISSUE TITLE
VGBR-Barisal Airport-BABUGANJ UPAZILA-BANGLADESH

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6176]
# Airport Name
Barisal Airport
# Country?
Bangladesh
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by brennanhackard** [comment]
@jakey20 you're already assigned to three issues.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104106138-0dbde000-5279-11eb-8a2e-c8d9f4769a39.png)
