### ISSUE TITLE
SNCJ-Piquiatuba Airport-PARA-BRAZIL

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Airports#6177]
# Airport Name
Piquiatuba
# Country?
Brazil
# Improvements that need to be made?
Redone from scratch.
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![Uploading image.png…]()
