### ISSUE TITLE
DRRE-Téra Airstrip-TILLABERI-NIGER

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6178]
# Airport Name
Téra Airstrip
# Country?
niger
# Improvements that need to be made?
done from scratch
# Are you working on this airport?
yeas 
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103584305-aeda1e80-4ea6-11eb-8aad-bb190df2c2cd.png)
