### ISSUE TITLE
KHWD-Hayward Executive-CALIFORNIA-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6179]
# Airport Name
Hayward Executive
# Country?
U S A 
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
L  o  w™

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104094580-5a90bf00-5257-11eb-97b2-9147eb3cc318.png)
