### ISSUE TITLE
RCKH-Kaohsiung Airport-TAIWAIN-TAIWAN

### ISSUE THREAD

**Issue by Arzanex** [InfiniteFlightAirportEditing/Airports#618]
Please assign canoneoswen to this airport. 
Thanks!

**Comment by dushyants19** [comment]
What? Please elaborate, @Arzanex .

**Comment by canoneoswen** [comment]
I've done this one.

**Comment by PaulNielsen** [comment]
Okay. Have you sent it in for review at airports@liveflightapp.com

@canoneoswen ?

**Comment by dushyants19** [comment]
What's happening here, @canoneoswen? Are you in our slack? Why haven't you told us about this? Unless you answer these questions. I don't see an approval for this.

**Comment by canoneoswen** [comment]
@PaulNielsen I'll send it soon,probably tomorrow.
@dushyants19 I had ever been in the airport editing team,but maybe it's cause I didn't submit any airports then,I had been removed from that chat.This issue was Arzanex help me to creat since I hadn't joined the github.I'm sorry about that.

**Comment by PaulNielsen** [comment]
Why send it in later? If it's already done?

**Comment by canoneoswen** [comment]
@PaulNielsen it's nearly midnight here and my PC is not home,it's in my workplace.Sorry.

**Comment by dushyants19** [comment]
Assigned to @canoneoswen (Eos Wen)

**Comment by dushyants19** [comment]
@canoneoswen are you doing this?

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by canoneoswen** [comment]
Done.Sending file now

**Comment by canoneoswen** [comment]
sent for review.

**Comment by canoneoswen** [comment]
second review sent.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33534345-6e3cea3c-d86c-11e7-9032-3184903c48af.png)
