### ISSUE TITLE
SDNI-Nascimento I-SAO PAULO-BRAZIL

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#6180]
# Airport Name
Nascimento I
# Country?
Brazil
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yup
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103706402-5708e980-4f72-11eb-9cc4-203bf078a3e0.png)
