### ISSUE TITLE
CYZV-Sept-Îles Airport-QUEBEC-CANADA

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6181]
# Airport Name
Sept-Îles Airport
# Country?
america's hat, maple country of canada
# Improvements that need to be made?
everythingg
# Are you working on this airport?
yes i am ma'am
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104107151-e74f7300-527f-11eb-866f-26d1af701ea5.png)
