### ISSUE TITLE
MMPP-Punta Pescadero Airstrip-BAJA CALIFORNIA SUR-MEXICO

### ISSUE THREAD

**Issue by lalomarlin** [InfiniteFlightAirportEditing/Airports#6182]
# Airport Name
< Punta Pescadero >
# Country?
< Mexico >
# Improvements that need to be made?
< Needs to be done >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low Priority >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103705064-042e3280-4f70-11eb-917e-6475101aeee3.png)
