### ISSUE TITLE
VGCB-Cox’s Bazar Airport-CHITTAGONG-BANGLADESH

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6183]
# Airport Name
Cox’s Bazar Airport
# Country?
Bangladesh
# Improvements that need to be made?
Redo 
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104096241-e9eea000-5260-11eb-8a2d-11127333f027.png)
