### ISSUE TITLE
SAOU-San Luis Airport-SAN LUIS-ARGENTINA

### ISSUE THREAD

**Issue by victormw22** [InfiniteFlightAirportEditing/Airports#6184]
# Airport Name
   San Luis
# Country?
   Argentina
# Improvements that need to be made?
   Redone 
# Are you working on this airport?
   yes 
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
   low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104110817-03afd780-52a1-11eb-8a7d-2512633b2210.png)
