### ISSUE TITLE
YPPF-Parafield Airport-SOUTH AUSTRALIA-AUSTRALIA

### ISSUE THREAD

**Issue by LesterXavier** [InfiniteFlightAirportEditing/Airports#6185]
# Airport Name
Parafield Airport
# Country?
Australia 🇦🇺 
# Improvements that need to be made?
Built from scratch
# Are you working on this airport?
Yasss
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108602257-a8c0d400-7366-11eb-988f-65ac287cf843.png)
