### ISSUE TITLE
YDPO-Devonport Airport-TASMANIA-AUSTRALIA

### ISSUE THREAD

**Issue by LesterXavier** [InfiniteFlightAirportEditing/Airports#6186]
# Airport Name
Devonport Airport
# Country?
Australia 🐨 🇦🇺 
# Improvements that need to be made?
Built from scratch
# Are you working on this airport?
Ya
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104521381-687d7180-55c2-11eb-8e33-aaca57c2d3de.png)
