### ISSUE TITLE
DA13-Tinfouchy Airport-TINDUF-ALGERIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6187]
# Airport Name
Tinfouchy Airport
# Country?
Algeria
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
10k+

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103967485-b9571b00-5127-11eb-8a55-58d5c589368d.png)
