### ISSUE TITLE
UUMC-Chernogolovka-MOSCOW-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6189]
# Airport Name
Chernogolovka Aerodrome
# Country?
RU
# Improvements that need to be made?
New
# Are you working on this airport?
да
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by MajorTomMueller** [comment]
Hi Alex, I couldn't find the Code in Russian AIP GEN2.4.
Could you link a document?

**Comment by AleksanderIF** [comment]
http://www.caiga.ru/common/AirClassGDE/validaip4/aip/ad/ad4/4-ad-4.1.pdf | ru code: УУМЦ
![2eb5f810399c5a5d67df39f42ce8f81a](https://user-images.githubusercontent.com/53284798/103690240-753c0d00-4fa5-11eb-8eef-19b4e2f471e0.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104092872-6460f500-524c-11eb-91f3-1283b1bdbb00.png)
