### ISSUE TITLE
EFHK-Helsinki Vantaa Airport-SOUTHERN FINLAND-FINLAND

### ISSUE THREAD

**Issue by sumith11** [InfiniteFlightAirportEditing/Airports#619]
Re-doing HEL

**Comment by ReflexRSM** [comment]
Sent for approval.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18808351/536c4e30-8225-11e6-9a98-bd8414ef48bc.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18808353/660f1edc-8225-11e6-945c-8c8d061502b2.png)

**Comment by ryu12332** [comment]
ISSUE: Extension part of gates 53-54-55 is missing. 
[IF IMAGE](https://drive.google.com/open?id=1uEJHicky8w8Z3QXitLQvHN-4XHCFRmoZ)
[MAP](http://hel-airport-maps.herokuapp.com/?lang=en&navref=paragraph)

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42119578-23ec8f5e-7bd3-11e8-88a3-d108e61e804b.png)

**Comment by MajorTomMueller** [comment]
adding of new Terminal area

**Comment by OscarConklin** [comment]
Sent for OR!

**Comment by kilt46** [comment]
![Uploading image.png…]()

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/98468921-3e629a00-21a2-11eb-99ef-49303d7e31f1.png)
