### ISSUE TITLE
VNDP-Dolpa Airport-NEPAL

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#6191]
# Airport Name
Dolpa Airport
# Country?
Nepal
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104107016-13b6bf80-527f-11eb-993a-4b0c42867b2b.png)
