### ISSUE TITLE
VGSD-Saidpur Airport-RANGPUR-BANGLADESH

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6192]
# Airport Name
Saidpur Airport
# Country?
bang la desh
# Improvements that need to be made?
everything
# Are you working on this airport?
hmm yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104096110-1d7cfa80-5260-11eb-93f7-83a478bab4c6.png)
