### ISSUE TITLE
DA16-Tindouf East Airport-TINDUF-ALGERIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6193]
# Airport Name
Tindouf East Airport
# Country?
Algeria
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
10k+

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104109953-8b451880-5298-11eb-928f-33878c7f7405.png)
