### ISSUE TITLE
CPR7-Wingham/Richard W LeVan Airport-ONTARIO-CANADA

### ISSUE THREAD

**Issue by mike116119** [InfiniteFlightAirportEditing/Airports#6194]
# Airport Name
< CPR7- WINGHAM RICHARD W LEVAN>
# Country?
< Canada >
# Improvements that need to be made?
< Autogen airport >
# Are you working on this airport?
< yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< None >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105431739-d9083c00-5c1b-11eb-87f3-df4a78d024fb.png)
