### ISSUE TITLE
WARW-Bawean Airport-GRESIK-INDONESIA

### ISSUE THREAD

**Issue by vinoalviano1994** [InfiniteFlightAirportEditing/Airports#6195]
# Airport Name
< Bawean Airport >
# Country?
< Indonesia >
# Improvements that need to be made?
< add new airport >
# Are you working on this airport?
< yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104103896-591cc200-526a-11eb-8f53-189c8303b296.png)
