### ISSUE TITLE
WAQA-Nunukan Airport-NUNUKAN-INDONESIA

### ISSUE THREAD

**Issue by vinoalviano1994** [InfiniteFlightAirportEditing/Airports#6196]
# Airport Name
< Nunukan Airport >
# Country?
< Indonesia >
# Improvements that need to be made?
< change from deafult (full redo) >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by MajorTomMueller** [comment]
![WAQA-git](https://user-images.githubusercontent.com/26853210/131700324-97434d71-47a9-49bf-ba00-36ec3cd85500.png)
