### ISSUE TITLE
WAFO-Morowali Airport-MOROWALI-INDONESIA

### ISSUE THREAD

**Issue by vinoalviano1994** [InfiniteFlightAirportEditing/Airports#6197]
# Airport Name
< Morowali Airport>
# Country?
< Indonesia >
# Improvements that need to be made?
< add new Airport >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103967951-a98c0680-5128-11eb-9353-035908c7e3b0.png)
