### ISSUE TITLE
LFEK-Issoudun Le Fay-Indre-FRANCE

### ISSUE THREAD

**Issue by Jeremy351** [InfiniteFlightAirportEditing/Airports#6198]
# Airport Name
Issoudun Le Fay
# Country?
France
# Improvements that need to be made?
Full redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103959465-5f4d5a00-5115-11eb-9823-43f1bffa9a9a.png)
