### ISSUE TITLE
SSGY-Guaira Airport-PARANA-BRAZIL

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#6199]
# Airport Name
Guaira Airport
# Country?
Brazil
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104074807-afd8bc00-51d6-11eb-8b6b-30fb1bbd71dd.png)
