### ISSUE TITLE
86IL-Sharp Airport-ILLINOIS-USA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6200]
# Airport Name
Sharp Airport
# Country?
USA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104094900-65e4ea00-5259-11eb-83de-b95ba1e69002.png)
