### ISSUE TITLE
LFBP-Pau Pyrénées-Pyrénées Atlantiques-FRANCE

### ISSUE THREAD

**Issue by Jeremy351** [InfiniteFlightAirportEditing/Airports#6201]
# Airport Name
Pau Pyrénées
# Country?
France
# Improvements that need to be made?
Full redo
# Are you working on this airport?
Yep
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104094802-c3c50200-5258-11eb-9014-90e12c243ab8.png)
