### ISSUE TITLE
KKIC-Mesa Del Rey Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6202]
# Airport Name
Mesa Del Rey Airport
# Country?
canada's pants
# Improvements that need to be made?
everything
# Are you working on this airport?
yeah :3
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low :(

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104094434-88c1cf00-5256-11eb-93ec-25f68210f902.png)
