### ISSUE TITLE
KACP-Allen Parish Airport-LOUISIANA-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6203]
# Airport Name
Allen Parish Airport
# Country?
USA
# Improvements that need to be made?
Manual edit
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

![Full](https://user-images.githubusercontent.com/59462519/103876320-68b1d480-50cb-11eb-897b-d1022e9b7530.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104094311-d38f1700-5255-11eb-8b7b-23f555b92051.png)
