### ISSUE TITLE
EYMA-Tirkšliai Mažeikiai Airport-Telšiai County-LITHUNIA

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#6205]
![EYMA](https://user-images.githubusercontent.com/26853210/103891505-df59cc80-50e1-11eb-901e-dd97275cf9b0.png)

**Comment by MajorTomMueller** [comment]
https://github.com/InfiniteFlightAirportEditing/Airports/commit/b8dd6717616f86584e7d61d2188f38dffee4d6d4

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103958927-faddcb00-5113-11eb-98f7-f15638a94061.png)
