### ISSUE TITLE
EYMO-Molėtai Airport-UTENA COUNTY-LITHUNIA

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#6208]
![EYMO](https://user-images.githubusercontent.com/26853210/103891695-38296500-50e2-11eb-8f57-a7390311807c.png)

**Comment by MajorTomMueller** [comment]
https://github.com/InfiniteFlightAirportEditing/Airports/commit/b8dd6717616f86584e7d61d2188f38dffee4d6d4

**Comment by kilt46** [comment]
Field elevation should be around 634 ft!
![image](https://user-images.githubusercontent.com/14023167/103956248-c5ce7a00-510d-11eb-9bc9-fbf2c8242bf0.png)
