### ISSUE TITLE
UUMD-Selnikovo-MOSCOW-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6210]
# Airport Name
Selnikovo
# Country?
RF
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low
http://www.caiga.ru/common/AirClassGDE/validaip4/aip/ad/ad2/uumd/4-ad2-uumd-txt.pdf

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104093297-552f7680-524f-11eb-85d5-85b72869b126.png)
