### ISSUE TITLE
MMIT-Ixtepec AFB Airport-OAXACA-MEXICO

### ISSUE THREAD

**Issue by lalomarlin** [InfiniteFlightAirportEditing/Airports#6211]
# Airport Name
< Ixtepec Afb >
# Country?
< Mexico >
# Improvements that need to be made?
< Redone >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low Priority >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104094113-83fc1b80-5254-11eb-900e-660e424f229f.png)
