### ISSUE TITLE
UUWH-Aerograd Mozhaysky-MOSCOW-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6212]
# Airport Name
Aerograd Mozhaysky
# Country?
RU
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low
http://www.caiga.ru/common/AirClassGDE/validaip4/aip/ad/ad4/4-ad-4.1.pdf - ru: УУВХ  (UUWH)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104091684-750d6d00-5244-11eb-9c6f-6899bb87e5c1.png)
