### ISSUE TITLE
XUMG-Yegoryevsk-MOSCOW-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6213]
# Airport Name
Yegoryevsk
# Country?
RU
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low
http://www.caiga.ru/common/AirClassGDE/validaip4/aip/ad/ad4/4-ad-4.1.pdf - ru: ЬУМГ (XUMG)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104093417-0209f380-5250-11eb-8395-73697a8464ca.png)
