### ISSUE TITLE
LGKN-Kotrioni-CENTRAL GREECE-GREECE

### ISSUE THREAD

**Issue by davide-dc** [InfiniteFlightAirportEditing/Airports#6215]
# Airport Name
Kotrioni
# Country?
Greece
# Improvements that need to be made?
new
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104090916-91f37180-523f-11eb-9539-e6f3d9bc0ccd.png)
