### ISSUE TITLE
KADU-Audubon County Airport-IOWA-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6218]
![Full](https://user-images.githubusercontent.com/59462519/103998228-bf82e100-5193-11eb-92b1-0f94a30df5f1.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104075921-0a274c00-51da-11eb-82b8-257c119e4ec2.png)
