### ISSUE TITLE
MGQZ-Quetzaltenango Airport-GUATEMALA

### ISSUE THREAD

**Issue by zhf21** [InfiniteFlightAirportEditing/Airports#6224]
# Airport Name
Quetzaltenango Airport
# Country?
Guatemala
# Improvements that need to be made?
Full redo (autogen airport)
# Are you working on this airport?
idk, am I?
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
zero, ne, none, cero

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104122725-65f1f200-530c-11eb-9785-afd5cf6ff147.png)
