### ISSUE TITLE
XS12-Liberty Hill Air Ranch-TEXAS-USA

### ISSUE THREAD

**Issue by suhasjatla** [InfiniteFlightAirportEditing/Airports#6225]
# Airport Name
Liberty Hill Air Ranch
# Country?
USA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Indeed
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104093668-8a3cc880-5251-11eb-8cfb-8ca710fd8f0d.png)
