### ISSUE TITLE
SWBQ-Geraldo Alvino Covre Airstrip-ESPIRITO SANTO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#6226]
# Airport Name
Geraldo Alvino Covre Airstrip
# Country?
Brazil
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104074269-460be280-51d5-11eb-9859-092710c4d992.png)
