### ISSUE TITLE
SNMX-Sao Mateus Airport-ESPIRITO SANTO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#6227]
# Airport Name
Sao Mateus Airport
# Country?
Brazil
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104073990-b108e980-51d4-11eb-99e2-18cc1cf5a515.png)
