### ISSUE TITLE
SWZH-Fazenda XV de Outubro-ESPIRITO SANTO-BRAZIL

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#6228]
# Airport Name
Fazenda XV de Outubro
# Country?
Brazil
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Extremely low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104093534-af7d0700-5250-11eb-8247-219e6c2a4442.png)
