### ISSUE TITLE
LFQU-Sarre-Union-ALSACE-FRANCE

### ISSUE THREAD

**Issue by Jeremy351** [InfiniteFlightAirportEditing/Airports#6229]
# Airport Name
Sarre-Union
# Country?
France
# Improvements that need to be made?
Full redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104137976-7df65f80-5366-11eb-899a-10d5b59c1530.png)
