### ISSUE TITLE
CYTZ-Toronto/City Centre Airport-ONTARIO-CANADA

### ISSUE THREAD

**Issue by tranquil-skyflyer** [InfiniteFlightAirportEditing/Airports#623]
I'll do this one!

**Comment by dushyants19** [comment]
@Jacob-IF how is this going?

**Comment by Jacob-IF** [comment]
It's going great!

**Comment by dushyants19** [comment]
@Jacob-IF Whatever, I would like to see this airport and the others submitted soon. #552 #565 

Else put it up for grabs

**Comment by dushyants19** [comment]
@Jacob-IF any progress

**Comment by moritzbabl** [comment]
If there's still no progress I will do it

**Comment by dushyants19** [comment]
Assigned to @moritzbabl

**Comment by moritzbabl** [comment]
Sent for approval

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21578398/1385dcd4-cf44-11e6-95ad-8b1cb4c04ff2.png)

**Comment by danisrils39** [comment]
Sent to OR

**Comment by brunocr98** [comment]
Will be reopen when imagery is updated. For now I just removed the runway (and buildings) to comply with IRL layout of the airport (maybe?).
