### ISSUE TITLE
UUMI-Stupino-MOSCOW-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6230]
# Airport Name
Stupino
# Country?
RU
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low
http://www.caiga.ru/common/AirClassGDE/validaip4/aip/ad/ad4/4-ad-4.1.pdf - ru: УУМИ

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104091395-c9175200-5242-11eb-8a45-d8e2240a3b48.png)
