### ISSUE TITLE
XUMK-Korobcheyevo-MOSCOW-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6231]
# Airport Name
Korobcheyevo
# Country?
RU
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low
http://www.caiga.ru/common/AirClassGDE/validaip4/aip/ad/ad2/xumk/4-ad2-xumk-txt.pdf

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104130557-ff35fe00-5336-11eb-824c-6793b26c19aa.png)
