### ISSUE TITLE
LG55-Triodhon-PELOPONNESIA-GREECE

### ISSUE THREAD

**Issue by davide-dc** [InfiniteFlightAirportEditing/Airports#6232]
# Airport Name
Triodhon
# Country?
Greece
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104125750-6bf0ce80-531e-11eb-8a53-c5404297613d.png)
