### ISSUE TITLE
XUMS-Drakino-MOSCOW-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6233]
# Airport Name
Drakino
# Country?
RU
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low
http://www.caiga.ru/common/AirClassGDE/validaip4/aip/ad/ad4/4-ad-4.1.pdf - ru: ЬУМС

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104130321-aade4e80-5335-11eb-87e1-b1d90f9e2ecd.png)
