### ISSUE TITLE
VNSI-Simara Airport-Province 2-Nepal

### ISSUE THREAD

**Issue by Captainflight** [InfiniteFlightAirportEditing/Airports#6234]
# Airport Name
< Simara Airport >
# Country?
< Nepal >
# Improvements that need to be made?
< Redo from scratch >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
<Low >

**Comment by Captainflight** [comment]
I thought I put Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104254999-aac97600-543d-11eb-82cc-e54954fdbd34.png)
