### ISSUE TITLE
XUOA-Alferyevo-MOSCOW-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6235]
# Airport Name
Alferyevo
# Country?
RU
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low
http://www.caiga.ru/DocAni/manual_of_4_letter_indexes/Indexes_of_Airports.pdf ru: ЬУОА

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104137886-c06b6c80-5365-11eb-9ce2-e25c4aed9527.png)
