### ISSUE TITLE
VTSB-Surat Thani Int'l Airport-SOUTHERN THAILAND-THAILAND

### ISSUE THREAD

**Issue by LesterXavier** [InfiniteFlightAirportEditing/Airports#6236]
# Airport Name
Surat Thani Int'l
# Country?
Thailand 🇹🇭 
# Improvements that need to be made?
Rework from scratch
# Are you working on this airport?
Yaaas
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111558231-64a1d300-875c-11eb-9f53-3625a05524f7.png)
