### ISSUE TITLE
TX11-Ross Planes Airport-TEXAS-USA

### ISSUE THREAD

**Issue by suhasjatla** [InfiniteFlightAirportEditing/Airports#6237]
# Airport Name
Ross Planes Airport
# Country?
USA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Quite so
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104110496-e7f70200-529d-11eb-8058-8632b47af1a0.png)
