### ISSUE TITLE
FEFA-Alindao Airport-CENTRAL AFRICAN REPUBLIC

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6238]
# Airport Name
Alindao Airport
# Country?
CAR
# Improvements that need to be made?
Redo/New Airport
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104125487-a2c5e500-531c-11eb-8e5d-8ee23d3efbbd.png)
