### ISSUE TITLE
INVALID

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6239]
♻️

**Comment by brunocr1050** [comment]
#6241

**Comment by MajorTomMueller** [comment]
So the older issue gets closed? Is this the approved way to deal with duplicates now?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107773804-cc02d800-6d03-11eb-8cc1-721292073580.png)
