### ISSUE TITLE
Duplicate

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6241]
# Airport Name
< Bau-Bau Betoambahari >
# Country?
< Indonesia >
# Improvements that need to be made?
< Create New Airport >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low Priority >

**Comment by MajorTomMueller** [comment]
#2343

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104249494-2c66d700-5431-11eb-9bd6-8dcfe2be9d8e.png)
