### ISSUE TITLE
LFBI-Poitiers Biard-NOUVELLE AQUITAINE-FRANCE

### ISSUE THREAD

**Issue by Jeremy351** [InfiniteFlightAirportEditing/Airports#6242]
# Airport Name
Poitiers Biard
# Country?
France
# Improvements that need to be made?
Full redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104110430-17593f00-529d-11eb-83f5-85d3aca94971.png)
