### ISSUE TITLE
SNEB-Nagib Demachki Airport-PARA-BRAZIL

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Airports#6244]
# Airport Name
Paragominas-Nagib Demachki 
# Country?
Brazil
# Improvements that need to be made?
Redone form scratch
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/110226583-56c79480-7eb6-11eb-9803-6b0cc5746d57.png)
