### ISSUE TITLE
YWBR-Warburton Airport-WESTERN AUSTRALIA-AUSTRALIA

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6245]
# Airport Name
Warburton Airport
# Country?
Australia
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104110283-de6c9a80-529b-11eb-9dc6-4f0c8d89c682.png)
