### ISSUE TITLE
YPTJ-Patjarr Airport-WESTERN AUSTRALIA-AUSTRALIA

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6246]
# Airport Name
Patjarr Airport
# Country?
Australia
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104110238-4e2e5580-529b-11eb-808e-9bfd56eeade2.png)
