### ISSUE TITLE
KCOM-Coleman Municipal Airport-TEXAS-USA

### ISSUE THREAD

**Issue by suhasjatla** [InfiniteFlightAirportEditing/Airports#6247]
# Airport Name
Coleman Municipal Airport
# Country?
USA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Quite so
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104520633-0c661d80-55c1-11eb-9139-6b85b27212dc.png)
