### ISSUE TITLE
UMKB-Borskoye-KALININGRAD-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6248]
# Airport Name
Borskoye
# Country?
RF
# Improvements that need to be made?
from scratch
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low
http://www.caiga.ru/common/AirClassGDE/validaip4/aip/ad/ad4/4-ad-4.1.pdf - ru: УМКБ

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104137764-e5abab00-5364-11eb-82fb-f07c18924e1e.png)
