### ISSUE TITLE
SNJK-Jequie Airport-BAHIA-BRAZIL

### ISSUE THREAD

**Issue by HenriqueChen** [InfiniteFlightAirportEditing/Airports#6249]
# Airport Name
< Jequie Airport "Vicente Grilo" >
# Country?
< Brazil >
# Improvements that need to be made?
< Redone from scratch >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low >

**Comment by HenriqueChen** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/120076639-3568e580-c06c-11eb-9067-cf165d97e4d3.png)
