### ISSUE TITLE
PTSA-Kosrae Airport-KOSRAE-MICRONESIA

### ISSUE THREAD

**Issue by corporate1401** [InfiniteFlightAirportEditing/Airports#625]
RECYCLED. ♻️

**Comment by corporate1401** [comment]
can someone assign me to it please

**Comment by corporate1401** [comment]
I have nearly completed this, only a few taxi ways to add and the spawn points but my computer messed up and cannot edit anymore, to much lag to do it :( i can send the file to someone to complete if anyone wants to take over. @dushyants19

**Comment by dushyants19** [comment]
Try getting WEDBing scenery for smaller areas. The number should be around ~3300. 

Try hiding big taxiways with the eye icon :)

**Comment by corporate1401** [comment]
okay

**Comment by dushyants19** [comment]
@corporate1401 any progress?

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by brunocr98** [comment]
Vacations over, going back to my laptop.

**Comment by bavAVIA** [comment]
@brunocr98 you are not working on this anymore?

**Comment by brunocr98** [comment]
No, I'm not. You can take it if you want.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25515635/8c42105c-2bab-11e7-871d-676669be57ee.png)
