### ISSUE TITLE
YAAL-Yarralin Airport-NORTHERN TERRITORY-AUSTRALIA

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6251]
# Airport Name
Yarralin Airport
# Country?
Kangaroo land
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
I would suggest width is more like 60 ft and not 267 ft. Please review.
![image](https://user-images.githubusercontent.com/14023167/104125645-ae65db80-531d-11eb-895f-1733108d50c0.png)

**Comment by jakey20** [comment]
Hi. I made the runway to match the larger white outlines in the image below.
![image](https://user-images.githubusercontent.com/59377475/104134025-027fb880-533c-11eb-9fbd-6870ef6bd650.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104815454-4bbb8680-57da-11eb-8bb3-9196e44e1db8.png)
