### ISSUE TITLE
LGKA-Aristotelis-MACEDONIA-GREECE

### ISSUE THREAD

**Issue by davide-dc** [InfiniteFlightAirportEditing/Airports#6252]
# Airport Name
Aristotelis
# Country?
Greece
# Improvements that need to be made?
full redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104254575-bd8f7b00-543c-11eb-9bea-739dfe0579f3.png)
