### ISSUE TITLE
KDVO - Gnoss Field Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6253]
# Airport Name
Gnoss Field
# Country?
USA
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104387578-0d357b80-54fd-11eb-8cd5-fd31bfc07b01.png)
