### ISSUE TITLE
LFSD-Dijon Longvic-BOURGOGNE-FRANCE

### ISSUE THREAD

**Issue by Jeremy351** [InfiniteFlightAirportEditing/Airports#6254]
# Airport Name
Dijon Longvic
# Country?
France
# Improvements that need to be made?
Full redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104254094-b025c100-543b-11eb-9d2f-0cd66203a38d.png)
