### ISSUE TITLE
VDKT-Kratié Airport-KRATIE-CAMBODIA

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6255]
# Airport Name
Kratié Airport
# Country?
cambodia
# Improvements that need to be made?
done from scratch
# Are you working on this airport?
:) ye
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![Uploading image.png…]()
