### ISSUE TITLE
VDKK-Kaoh Kong Airstrip-KAOH KONG-CAMBODIA

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6256]
# Airport Name
Kaoh Kong Airstrip
# Country?
cambodia
# Improvements that need to be made?
done from scratch
# Are you working on this airport?
ye
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104137561-5a7de580-5363-11eb-97bc-27527198575a.png)
