### ISSUE TITLE
SIWV-Ten. Brig. Ar Waldir de Vasconcelos-RIO DE JANEIRO-BRAZIL

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6257]
# Airport Name
Ten. Brig. Ar Waldir de Vasconcelos
# Country?
brasil :O
# Improvements that need to be made?
redo
# are u working on this airport bb?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106356812-f7c79c00-62c7-11eb-9ca5-21ebc0f0f343.png)
