### ISSUE TITLE
FEFC-Carnot Airport-MAMBÉRÉ-KADEI-CENTRAL AFRICAN REPUBLIC

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6258]
# Airport Name
Carnot Airport
# Country?
CAR
# Improvements that need to be made?
Redo/New Airport
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104253756-e1ea5800-543a-11eb-9add-9d17498efebd.png)
