### ISSUE TITLE
KGFK-Grand Forks International-NORTH DAKOTA-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#6259]
# Airport Name
Grand Forks International
# Country?
United States of America
# Improvements that need to be made?
redo from scratch
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105580042-9e072500-5d4f-11eb-8e3c-3a52acdc68b1.png)
