### ISSUE TITLE
EGPG-Cumbernauld Airport-SCOTLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by corporate1401** [InfiniteFlightAirportEditing/Airports#626]

**Comment by corporate1401** [comment]
sorry i got the ICAO wrong thats why i didnt know someone had done it already

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19097003/c7e911be-8a66-11e6-9d17-201692d4d610.png)
