### ISSUE TITLE
VVDB-Dien Bien Phu Airport-DIEN BIEN-VIETNAM

### ISSUE THREAD

**Issue by IFUA2003** [InfiniteFlightAirportEditing/Airports#6260]
# Airport Name
< Dien Bien Phu Airport >
# Country?
< Vietnam >
# Improvements that need to be made?
< Redo from scratch >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< No >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104253471-1f9ab100-543a-11eb-903d-de8864c8b1eb.png)
