### ISSUE TITLE
KCAG-Craig-Moffat Airport-COLORADO-USA

### ISSUE THREAD

**Issue by liamkirky** [InfiniteFlightAirportEditing/Airports#6261]
# Airport Name
Craig-Moffat Airport
# Country?
🇺🇸 
# Improvements that need to be made?
Rework
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104250534-6802a080-5433-11eb-9677-a258552b65ec.png)
