### ISSUE TITLE
KCAO-Clayton Municipal Airpark-NEW MEXICO-USA

### ISSUE THREAD

**Issue by liamkirky** [InfiniteFlightAirportEditing/Airports#6263]
# Airport Name
Clayton Municipal Airpark
# Country?
🇺🇸 
# Improvements that need to be made?
Rework
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104387266-5a651d80-54fc-11eb-937c-8e0b07549474.png)
