### ISSUE TITLE
ENRM-Rørvik Airport-TRØNDELAG-NORWAY 

### ISSUE THREAD

**Issue by JensSeverin** [InfiniteFlightAirportEditing/Airports#6264]
# Airport Name
Røros Airport
# Country?
Norway
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104528820-ded3a100-55cd-11eb-8486-e516cfd89413.png)
