### ISSUE TITLE
WALC-Bontang LNG Badak-KALIMANTAN-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6267]
# Airport Name
< LNG Badak >
# Country?
< Indonesia >
# Improvements that need to be made?
< Create New Airport >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low Priority >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104384955-fc363b80-54f7-11eb-9225-44909b24e727.png)
