### ISSUE TITLE
WAQM-Malinau Robert Atty Bessing-KALIMANTAN-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6268]
# Airport Name
< Robert Atty Bessing >
# Country?
< Indonesia >
# Improvements that need to be made?
< Create New Airport >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low Priority >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104384343-e8d6a080-54f6-11eb-8311-d45ad8f05aaa.png)
