### ISSUE TITLE
WAWH-Selayar Haji Aeroppala-SULAWESI-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6269]
# Airport Name
< Haji Aeroppala >
# Country?
< Indonesia >
# Improvements that need to be made?
< Create New Airport >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low Priority >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104383601-b7110a00-54f5-11eb-88d5-e7e2c543fb78.png)
