### ISSUE TITLE
EGPK - Prestwick International 

### ISSUE THREAD

**Issue by corporate1401** [InfiniteFlightAirportEditing/Airports#627]

**Comment by IceBlue02** [comment]
@corporate1401 are you doing this?

**Comment by corporate1401** [comment]
yeah

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19222662/a7730514-8e23-11e6-862c-91427dbddb65.png)

**Comment by MajorTomMueller** [comment]
![EGPK-git](https://user-images.githubusercontent.com/26853210/97613202-4d15b800-1a10-11eb-82d9-70d3debb496e.png)
