### ISSUE TITLE
KPQN-Pipestone Municipal-MINNESOTA-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#6270]
# Airport Name
Pipestone Municipal
# Country?
United States of America
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
very low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104386562-102f6c80-54fb-11eb-82c4-1d28fbfc1c0c.png)
