### ISSUE TITLE
LGTP-Tripolis-PELOPONNESIA-GREECE

### ISSUE THREAD

**Issue by davide-dc** [InfiniteFlightAirportEditing/Airports#6272]
# Airport Name
Tripolis
# Country?
Greece
# Improvements that need to be made?
full
# Are you working on this airport?
yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104525037-f65a5c00-55c4-11eb-86a4-08ea0a4aeea3.png)
