### ISSUE TITLE
NCAI-Aitutaki Airport-COOK ISLANDS

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#6274]
# Airport Name
Aitutaki Airport
# Country?
Cook Islands
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104529248-e6e01080-55ce-11eb-9c96-612dea417e0d.png)
