### ISSUE TITLE
KCCR-Buchanan Field Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6275]
# 机场名字
Buchanan Field
# 国家？
美国
# 要改善什么？
整个机场要改变
# 你是不是现在改变这个机场？
当然
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
低

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104812808-6b4ab300-57ca-11eb-9eb4-3495bb89b2fa.png)
