### ISSUE TITLE
WAMN-Melonguane-SULAWESI-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6276]
# Airport Name
< Melonguane Airport >
# Country?
< Indonesia >
# Improvements that need to be made?
< Create New Airport >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low Priority >

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104813285-d9dd4000-57cd-11eb-8a02-484c0761e3a4.png)
