### ISSUE TITLE
WIHP-Pondok Cabe-BANTEN-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6278]
# Airport Name
< Pondok Cabe >
# Country?
< Indonesia >
# Improvements that need to be made?
< Create New Airport >
# Are you working on this airport?
< Yes >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
< Low Priority >

**Comment by ECoops-123** [comment]
Currently autogen in game as 'WIIP'. Remove in OR approval.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104952208-a9da9c00-5989-11eb-9134-43eac46efded.png)
