### ISSUE TITLE
SPHZ-Comandante FAP Germán Arias Graziani Airport-ANCASH-PERU

### ISSUE THREAD

**Issue by YubaniCM** [InfiniteFlightAirportEditing/Airports#6280]
SPHZ-  Comandante FAP Germán Arias Graziani Airport
Huaraz
# Improvements that need to be made?
the runway (for take off and landing), taxiways, hangars and aircraft parking areas (Apron areas).
# Are you working on this airport?
< no  >
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
<2773 m / 9097 pies (msnm)

>

**Comment by brunocr1050** [comment]
Just to clarify: the priority is not based on the airfield's altitude. The priorities are:

- It's scheduled to serve at an IF-organized event (GP1)
- The runway has a +10k feet long runway (GP2)
- Serves the capital city of a country (GP3)
- Serves the capital city of a US state (GP4)

If your airport doesn't fit in any of these, then it's low priority.

**Comment by Czechoslovaki** [comment]
@YubaniCM please do not close issues if the airport isn't edited!

**Comment by zhf21** [comment]
I can edit this.

**Comment by zhf21** [comment]
**SPHZ Charts:**

![SPHZ](https://user-images.githubusercontent.com/67797012/120498179-08c70d80-c38d-11eb-8684-5ebec3d63191.jpg)

*The field elevation in this chart is out-dated. The correct elevation is 9,097 feet.*

*The chart was found here: https://onedrive.live.com/?authkey=%21AJUOYipU9x6QHQM&id=51B651AF9944E16D%21172&cid=51B651AF9944E16D*

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124187915-22d73700-da84-11eb-831a-0521794b47dc.png)
