### ISSUE TITLE
KCDW-Essex County Airport-NEW JERSEY-USA

### ISSUE THREAD

**Issue by suhasjatla** [InfiniteFlightAirportEditing/Airports#6281]
# Airport Name
Essex County
# Country?
USA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yup
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105937982-418c5a00-601c-11eb-9763-3e22e2397cde.png)
