### ISSUE TITLE
O69-Petaluma Municipal-CALIFORNIA-USA

### ISSUE THREAD

**Issue by suhasjatla** [InfiniteFlightAirportEditing/Airports#6282]
# Airport Name
Petaluma Municipal
# Country?
USA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yup
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113365572-402d2580-931c-11eb-9a29-c77a171bc24d.png)
