### ISSUE TITLE
VOBM-Belgaum Airport-KARNATAKA-INDIA

### ISSUE THREAD

**Issue by Captainflight** [InfiniteFlightAirportEditing/Airports#6283]
# Airport Name

Belgaum Airport

# Country?

India
# Improvements that need to be made?

ICAO change from VABM to VOBM and rework from scratch 

# Are you working on this airport?

Yes

# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)

Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105925987-b3f23f80-6006-11eb-929e-b2a62e736606.png)
