### ISSUE TITLE
KMCB-McComb-Pike County Airport-MISSISSIPPI-USA

### ISSUE THREAD

**Issue by hossss6** [InfiniteFlightAirportEditing/Airports#6285]
♻️

**Comment by AleksanderIF** [comment]
Duplicate #790

**Comment by GBKarp** [comment]
#790 duplicate

**Comment by hossss6** [comment]
I'm aware there is another one just thought ill make a new one because as the other one was a bit old but if I need to continue on #790 then I shall move over there

**Comment by GBKarp** [comment]
You need to continue in the other one, as it's not allowed to create more than one issue per airport, but first, you need to ask in Discord if you can do it, and give the reasons.

**Comment by MBeringuy** [comment]
As stated above, continue on #790.

**Comment by OscarConklin** [comment]
May I do this one?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104812711-b1534700-57c9-11eb-8a4a-91336dd404aa.png)
