### ISSUE TITLE
USHH-Khanty-Mansiysk Airport-RUSSIA

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#6286]
# Airport Name
Khanty-Mansiysk Airport
# Country?
Russia
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104813554-7bb15c80-57cf-11eb-8298-bb2e119046ff.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104816341-23cf2180-57e0-11eb-92e7-0add9ea6fd20.png)
