### ISSUE TITLE
FEFE-Mobaye Mbanga Airport-BASSE-KOTTO-CENTRAL AFRICAN REPUBLIC

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6287]
# Airport Name
Mobaye Mbanga Airport
# Country?
CAR
# Improvements that need to be made?
Redo/New Airport
# Are you working on this airport?
Yes
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104813372-6be54880-57ce-11eb-83d7-2fe229681ff1.png)
