### ISSUE TITLE
WAOK-Kotabaru-KALIMANTAN-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6291]
# Airport Name
Gusti Syamsir Alam
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low Priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105122036-11ccd780-5a9b-11eb-9f45-0b4b70a28a3d.png)
