### ISSUE TITLE
KCHA-Lovell Field-TENNESSEE-USA

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#6292]
# Airport Name
Lovell Field
# Country?
United States of America
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104951284-d8577780-5987-11eb-8413-2357c9bda5ed.png)

**Comment by ECoops-123** [comment]
GBKarp is updating his airport to include fixes and a new paved area.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113452681-1af6f080-93ca-11eb-8278-18d3f6ef831c.png)
