### ISSUE TITLE
1L8-General Dick Stout Field-UTAH-USA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6294]
# Airport Name
General Dick Stout Field
# Country?
USA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
smol

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104936512-4002c800-5972-11eb-8563-7084dc3d8121.png)
