### ISSUE TITLE
KRNT-Renton Municipal Airport-WASHINGTON-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#63]
Redone by @JcFl4. Marking as complete.

**Comment by JcFl4** [comment]
Is there any way to add runway markings without taxi lines?

**Comment by jpperks** [comment]
Hello,

You should leave the runways as they are. You can add a taxi line (yellow) that goes onto the runway from a taxiway.

Hope this helps
Jonathan

**Comment by JcFl4** [comment]
Thanks

**Comment by HenrikBerg02** [comment]
Doing this one.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18608276/8b35a512-7caa-11e6-8c8d-89fa8184be3c.png)

**Comment by dushyants19** [comment]
FILE NOT IN REPO - KIAD IS present instead

**Comment by dushyants19** [comment]
KIAD was gated in KRNT's folder in SHA eea1d36c9ecd36ba4c27983d9ecb18ae68003d77 23 days ago. I reverted eea1d36c9ecd36ba4c27983d9ecb18ae68003d77 in 816f9979ee9b2a31ada27b1dc9ad7002ec42637a to restore KRNT. I copied KIAD (which was present in KRNT) and added it to KIAD's folder. I tried to re-commit KIAD but i think its the same copy.  (Didnt show in changes)

**Comment by kilt46** [comment]
FIXED

**Comment by MajorTomMueller** [comment]
https://nfdc.faa.gov/nfdcApps/services/ajv5/airportDisplay.jsp?airportId=KRNT

**Comment by MajorTomMueller** [comment]
Host airport of Boeing 757 production site.
Needs some love, pavement is incomplete, markings are wrong/incomplete.

**Comment by MajorTomMueller** [comment]
https://www.rentonwa.gov/common/pages/DisplayFile.aspx?itemId=10906230

**Comment by OscarConklin** [comment]
I'll do this once one of my issues is cleared up.

**Comment by Czechoslovaki** [comment]
@OscarConklin will redo this.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102721620-84427000-42c1-11eb-9418-0484c1a5cddc.png)
