### ISSUE TITLE
KRTS-Stead Field-NEVADA-USA

### ISSUE THREAD

**Issue by henrikbg** [InfiniteFlightAirportEditing/Airports#630]
Reno/Stead Airport.

**Comment by henrikbg** [comment]
The airport itself is finished. Waiting on an anonymous individual to send me ground charts.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19501242/843710de-9569-11e6-946b-11221502845e.png)
