### ISSUE TITLE
WAPF-Langgur Karel Sadsuitubun-MALUKU-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6308]
# Airport Name
Karel Sadsuitubun
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low Priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105121539-f8775b80-5a99-11eb-87a4-0e0de70556da.png)
