### ISSUE TITLE
1JY2-Mahogany Mtn Airport-OREGON-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6311]
# Airport Name
Mahogany Mtn Airport
# Country?
USA
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104935257-9c64e800-5970-11eb-9639-582cf636e605.png)
