### ISSUE TITLE
EBBY-Baisy-Thy-WALLONE-BELGIUM

### ISSUE THREAD

**Issue by IFFR-Baba** [InfiniteFlightAirportEditing/Airports#6313]
# Airport Name
Baisy-Thy
# Country?
Belgium
# Improvements that need to be made?
Full redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by ECoops-123** [comment]
Have fun! 😛

**Comment by MajorTomMueller** [comment]
Listed under "ULM Aerodromes" ....
https://ops.skeyes.be/html/belgocontrol_static/eaip/eAIP_Main/html/eAIP/EB-AD-2.EBBY-en-GB.html

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105431388-233ced80-5c1b-11eb-9143-bbc55cd04901.png)
