### ISSUE TITLE
SNXQ-Xique-Xique Airport-BAHIA-BRAZIL

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#6314]
# Airport Name
Xique-Xique Airport
# Country?
Brazil
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105120634-3d9a8e00-5a98-11eb-9c5e-ef9aaa52b4af.png)
