### ISSUE TITLE
BIRL-Mývatn Airport-Northeast-ICELAND

### ISSUE THREAD

**Issue by RobertineIFC** [InfiniteFlightAirportEditing/Airports#6315]
# Airport Name
Myvatn Airport
# Country?
Iceland
# Improvements that need to be made?
Fix Runway width and length, remove one of 2 runways, add starts, add taxiways, add hangars.
# Are you working on this airport?
YES
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
Runway width = 66ft
![image](https://user-images.githubusercontent.com/14023167/105429547-406fbd00-5c17-11eb-910a-18120bf76f16.png)

**Comment by RobertineIFC** [comment]
fixed runway width and tower viewpoint height

**Comment by brunocr1050** [comment]
Have you submitted the changes?

**Comment by RobertineIFC** [comment]
Yes, I replied to the email sent by OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105936060-a6de4c00-6018-11eb-9ff5-90be7700f182.png)
