### ISSUE TITLE
WIDM-Tarempa-KEPULAUAN RIAU-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6316]
# Airport Name
Pal Matak
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low Priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105255120-9d507200-5b48-11eb-90ec-bb95c3360572.png)
