### ISSUE TITLE
WIDL-Jemaja-KEPULAUAN RIAU-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6317]
# Airport Name
Letung
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low Priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105254497-5d3cbf80-5b47-11eb-9fdb-d1bdcfa214b6.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105254635-a4c34b80-5b47-11eb-819c-e2992adff5f1.png)
