### ISSUE TITLE
WIJB-Muara Bungo-JAMBI-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6318]
# Airport Name
Muara Bungo
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low Priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105253706-9ecc6b00-5b45-11eb-97c3-4ebb702cf685.png)
