### ISSUE TITLE
UHPA-Pakhachi-KAMCHATKA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6319]
# Airport Name
Pakhachi
# Country?
RU
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low
http://www.caiga.ru/common/AirClassGDE/validaip4/aip/ad/ad2/uhpa/4-ad2-uhpa-031.pdf

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105428688-8592ef80-5c15-11eb-9274-8e61e9e3309a.png)
