### ISSUE TITLE
KVLD-Valdosta Regional-GEORGIA-USA

### ISSUE THREAD

**Issue by henrikbg** [InfiniteFlightAirportEditing/Airports#632]
Valdosta Regional.

**Comment by henrikbg** [comment]
Redone.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20292567/2cc91562-aab4-11e6-8392-4cf764575c8d.png)

**Comment by henrikbg** [comment]
Going to fix some minor stuff.

**Comment by henrikbg** [comment]
Added new file to the repository.
