### ISSUE TITLE
UHPG-Tigil-KAMCHATKA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6320]
# Airport Name
Tigil
# Country?
RU
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low
http://www.caiga.ru/common/AirClassGDE/validaip4/aip/ad/ad2/uhpg/4-ad2-uhpg-031.pdf

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105428332-cb02ed00-5c14-11eb-94d5-5e138a899834.png)
