### ISSUE TITLE
YGTH-Griffith Airport-New South Wales-Australia

### ISSUE THREAD

**Issue by hossss6** [InfiniteFlightAirportEditing/Airports#6321]
# Airport Name
Griffith Airport
# Country?
Australia
# Improvements that need to be made?
Whole airport rework
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105256549-8f502080-5b4b-11eb-8214-4eeccc59e4f9.png)
