### ISSUE TITLE
FEFG-Bangassou Airport-MBOMOU-CENTRAL AFRICAN REPUBLIC

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6322]
# Airport Name
Bangassou Airport
# Country?
CAR
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105253000-392baf00-5b44-11eb-8944-b1d4ccec0f2f.png)
