### ISSUE TITLE
FEFI-Birao Airport-VAKAGA-CENTRAL AFRICAN REPUBLIC

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6323]
# Airport Name
Birao Airport
# Country?
CAR
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105250067-bf44f700-5b3e-11eb-8f6e-d1a2dc2fa748.png)
