### ISSUE TITLE
FEFK-Kembé Airport-BASSE-KOTTO-CENTRAL AFRICAN REPUBLIC

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6324]
# Airport Name
Kembé Airport
# Country?
CAR
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105249681-21512c80-5b3e-11eb-9597-68f674d82555.png)
