### ISSUE TITLE
YPJT-Jandakot Airport-WESTERN AUSTRALIA-AUSTRALIA

### ISSUE THREAD

**Issue by hossss6** [InfiniteFlightAirportEditing/Airports#6325]
# Airport Name
Jandakot
# Country?
Australia
# Improvements that need to be made?
Whole airport rework
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126415307-8bbc433f-2b33-4aaf-8a1c-e127c6aaafb3.png)
