### ISSUE TITLE
FTTD-Moundou Airport-LOGONE OCCIDENTAL-CHAD

### ISSUE THREAD

**Issue by victormw22** [InfiniteFlightAirportEditing/Airports#6326]
# Airport Name
Moundou
# Country?
Chad
# Improvements that need to be made?
Redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106360309-62370700-62dd-11eb-8df9-566f1c497732.png)
