### ISSUE TITLE
UHPH-Khalaktyrka-KAMCHATKA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6327]
# Airport Name
Khalaktyrka
# Country?
RU
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low
http://www.caiga.ru/common/AirClassGDE/validaip4/aip/ad/ad4/4-ad-4.1.pdf - ru: УХПХ ( UHPH )

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105427768-7c088800-5c13-11eb-9282-857f46ac45e5.png)
