### ISSUE TITLE
EBSH-Saint-Hubert-WALLONE-BELGIUM

### ISSUE THREAD

**Issue by BaptisteDesmet** [InfiniteFlightAirportEditing/Airports#6328]
# Airport Name
Saint Hubert
# Country?
Belgium
# Improvements that need to be made?
Full redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by IFFR-Baba** [comment]
I go start the editing Friday because I'm not at my mom home, sorry for the delay

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122671103-bb1f1300-d18a-11eb-9a43-a39d930e60ae.png)
