### ISSUE TITLE
WATW-Lewoleba-NUSA TENGGARA-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6331]
# Airport Name
Wonopito
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low Priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105425139-6775c100-5c0e-11eb-901c-14720cc4ba31.png)
