### ISSUE TITLE
UHPK-Ust-Kamchatsk-KAMCHATKA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6332]
# Airport Name
Ust-Kamchatsk
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low
http://www.caiga.ru/common/AirClassGDE/validaip4/aip/ad/ad2/uhpk/4-ad2-uhpk-031.pdf

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105939075-10ad2480-601e-11eb-81cf-828c03d6d12b.png)
