### ISSUE TITLE
7MN3-Caldbeck Field-MINNESOTA-UNITED STATES

### ISSUE THREAD

**Issue by Aceorbit** [InfiniteFlightAirportEditing/Airports#6334]
# Airport Name
CALDBECK FLD
# Country?
United States
# Improvements that need to be made?
Scratch
# Are you working on this airport?
ye
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105415409-486f3300-5bfe-11eb-9be6-5d3cf741ebd1.png)
