### ISSUE TITLE
HBBE-Gitega Airport-GITEGA-BURUNDI

### ISSUE THREAD

**Issue by RobertineIFC** [InfiniteFlightAirportEditing/Airports#6336]
# Airport Name
Gitega Airport
# Country?
Burundi
# Improvements that need to be made?
Remake
# Are you working on this airport?
YES
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106362313-b515bc00-62e7-11eb-93de-817d51019348.png)
