### ISSUE TITLE
FEFN-N'Délé Airport-BAMINGUI-BANGORAN-CENTRAL AFRICAN REPUBLIC

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6338]
# Airport Name
N'Délé Airport
# Country?
CAR
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105413169-57081b00-5bfb-11eb-8a27-efa218c8ecfb.png)
