### ISSUE TITLE
FEFO-Bouar Airport-NANA-MAMBERE-CENTRAL AFRICAN REPUBLIC

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6339]
# Airport Name
Bouar Airport
# Country?
CAR
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105411953-b36a3b00-5bf9-11eb-8122-a36a4a560599.png)
