### ISSUE TITLE
PAOH-Hoonah-ALASKA-UNITED STATES

### ISSUE THREAD

**Issue by RobertineIFC** [InfiniteFlightAirportEditing/Airports#6340]
# Airport Name
Hoonah
# Country?
USA
# Improvements that need to be made?
Remake
# Are you working on this airport?
YES
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by brennanhackard** [comment]
Hey @RobertineIFC ! 

You're already assigned to 3 issues, which means I can't assign you to this one, even though it's really tiny. I don't make the rules. OR for BIRL shouldn't take that long.

**Comment by RobertineIFC** [comment]
no problem, thanks :)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108599361-57a8e400-7356-11eb-98cd-839b3f23cf25.png)
