### ISSUE TITLE
26IS-Ficklin-Airtech-ILLINOIS-USA

### ISSUE THREAD

**Issue by RobertineIFC** [InfiniteFlightAirportEditing/Airports#6341]
![image](https://user-images.githubusercontent.com/14023167/109422105-c3ff9500-799f-11eb-884d-a4a012b01fb9.png)

**Comment by Czechoslovaki** [comment]
Finding any aeronautical information for this airport will practically be impossible. Good luck if you really wish to do this airport. Additionally, this is the FIFTH issue you've created, please wait until a few of your airports pass OR.
