### ISSUE TITLE
WIBG-Pasir Pengaraian-RIAU-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6342]
# Airport Name
Tuanku Tambusai
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low Priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105560302-0109a500-5cd9-11eb-867f-ac8639c445b6.png)
