### ISSUE TITLE
WIME-Padang Sidempuan-SUMATRA-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6343]
# Airport Name
Aek Godang
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low Priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105552961-57231c00-5cca-11eb-83c0-33b4e6035311.png)
