### ISSUE TITLE
WIOS-Sintang-KALIMANTAN-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6344]
# Airport Name
Tebelian
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low Priority

**Comment by kilt46** [comment]
Elevation should be 97ft
![image](https://user-images.githubusercontent.com/14023167/105551570-6f923700-5cc8-11eb-983b-987469bdfcf8.png)

**Comment by kilt46** [comment]
Fixed elevation .was a quick fix

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105559629-4b8a2200-5cd7-11eb-9373-2e829f0464c3.png)

**Comment by adibyaputra** [comment]
Thank you

Pada tanggal Sab, 23 Jan 2021 06.29, Kilt McHaggis <notifications@github.com>
menulis:
