### ISSUE TITLE
UHPL-Palana-KAMCHATKA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6345]
# Airport Name
Palana
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low
http://www.caiga.ru/common/AirClassGDE/validaip4/aip/ad/ad2/uhpl/4-ad2-uhpl-031.pdf

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105938744-73ea8700-601d-11eb-80fe-611e92680c1a.png)
