### ISSUE TITLE
UHPM-Milkovo-KAMCHATKA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6346]
# Airport Name
Milkovo
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low
http://www.caiga.ru/common/AirClassGDE/validaip4/aip/ad/ad2/uhpm/4-ad2-uhpm-031.pdf

**Comment by kilt46** [comment]
![Uploading image.png…]()
