### ISSUE TITLE
KESN-Easton Newnam Field Airport-MARYLAND-USA

### ISSUE THREAD

**Issue by PilotPeanutButter** [InfiniteFlightAirportEditing/Airports#6347]
# Airport Name
Easton Newnam Field Airport
# Country?
United States
# Improvements that need to be made?
Scratch 
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by LawinS** [comment]
Will take this one. Finally, I will be in charge of this airport now. Yaay! 🎉

**Comment by brunocarbone3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/134563717-f297f5a8-5e75-44cd-907a-3c4b2c901e6f.png)
