### ISSUE TITLE
2MN6-Van Norman's-MINNESOTA-UNITED STATES

### ISSUE THREAD

**Issue by Aceorbit** [InfiniteFlightAirportEditing/Airports#6348]
# Airport Name
Van Norman's
# Country?
US
# Improvements that need to be made?
scar
# Are you working on this airport?
ye
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105579788-474d1b80-5d4e-11eb-9b7a-5a53d5790357.png)
