### ISSUE TITLE
FEFP-Paoua Airport-OUHAM-PENDÉ-CENTRAL AFRICAN REPUBLIC

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6350]
# Airport Name
Paoua Airport
# Country?
CAR
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105550786-6fde0280-5cc7-11eb-806d-15f778f27355.png)
