### ISSUE TITLE
FEFQ-Kaga Bandoro Airport-NANA-GRÉBIZI-CENTRAL AFRICAN REPUBLIC

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6351]
# Airport Name
Kaga Bandoro Airport
# Country?
CAR
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105550372-e6c6cb80-5cc6-11eb-94a4-b92acedda0fa.png)
