### ISSUE TITLE
FEFR-Bria Airport-HAUTE-KOTTO-CENTRAL AFRICAN REPUBLIC

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6352]
# Airport Name
Bria Airport
# Country?
CAR
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105549314-6c964700-5cc6-11eb-8099-8a573ccea9c8.png)
