### ISSUE TITLE
EGKC-Bognor Regis "Lec" Airfield-ENGLAND-UK

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6353]
# Airport Name
Lec Airfield - Bognor Regis
# Country?
UK
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105580864-99913b00-5d54-11eb-8974-e77b3e16a44b.png)
