### ISSUE TITLE
FEFS-Bossangoa Airport-OUHAM-CENTRAL AFRICAN REPUBLIC

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6357]
# Airport Name
Bossangoa Airport
# Country?
CAR
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105578060-20d5b300-5d43-11eb-8a7c-347a11bbcd33.png)
