### ISSUE TITLE
FEFT-Berbérati Airport-MAMBÉRÉ-KADÉI-CENTRAL AFRICAN REPUBLIC

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6358]
# Airport Name
Berberati Airport
# Country?
CAR
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105577974-95f4b880-5d42-11eb-8a74-e28c4643e31d.png)
