### ISSUE TITLE
KVKS-Vicksburg Municipal-MISSISSIPPI-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#6359]
# Airport Name
Vicksburg Municipal
# Country?
USA
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105577851-a9ebea80-5d41-11eb-83de-b1b9a5a92c2c.png)
