### ISSUE TITLE
EIDW

### ISSUE THREAD

**Issue by chriscroft20** [InfiniteFlightAirportEditing/Airports#636]
Redoing Dublin Airport

**Comment by IFAEpat** [comment]
@chriscroft20, how's the progress going with this? :/

**Comment by Xpheros** [comment]
is this airport finished?

**Comment by dushyants19** [comment]
No

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by DublinSpotter** [comment]
Please somebody do this

**Comment by PaulNielsen** [comment]
Why not do it yourself @DublinSpotter ?

**Comment by Adam167** [comment]
I'll do this one after EGCC and SVMI

**Comment by brunocr98** [comment]
This airport is not Priority 2. None of the runways is >10,000ft.

https://skyvector.com/airport/EIDW/Dublin-Airport

**Comment by Will171** [comment]
Is this airport free??

**Comment by dushyants19** [comment]
I dont think so, you need to pay heavy fees to land there

**Comment by brunocr98** [comment]
LOL 😂

**Comment by moritzbabl** [comment]
done

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/26855750-6f203fca-4ae2-11e7-804b-4f6d6e5b7222.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52183462-b5991c00-27cd-11e9-81df-d3958ea3248a.png)
DUPLICATE SPAWN FIXED

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/65001257-20aee300-d8c5-11e9-9de5-56c2467aa5e2.jpg)
