### ISSUE TITLE
2MN8-Med-City Aviation-MINNESOTA-UNITED STATES

### ISSUE THREAD

**Issue by Aceorbit** [InfiniteFlightAirportEditing/Airports#6360]
# Airport Name
Med-City Aviatione
# Country?
us
# Improvements that need to be made?
s
# Are you working on this airport?
y
# Airport Priority? (10000ft+ Runway, Low)
l

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105579718-c7bf4c80-5d4d-11eb-8854-29a6a10d6be4.png)
