### ISSUE TITLE
MN32-Nietz Airstrip-MINNESOTA-USA

### ISSUE THREAD

**Issue by Aceorbit** [InfiniteFlightAirportEditing/Airports#6361]
# Airport Name
Nietz Airstrip
# Country?
us
# Improvements that need to be made?
scratcg
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105579559-03a5e200-5d4d-11eb-99ec-0f1ae5d371c3.png)
