### ISSUE TITLE
OMAD-Al Bateen Executive Airport-ABU DHABI-UNITED ARAB EMIRATES

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#6362]
# Airport Name
Al Bateen Executive Airport
# Country?
United Arab Emirates
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
10000ft+

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106066629-c5991d00-60c2-11eb-878c-858f34f894ae.png)
