### ISSUE TITLE
WAWP-Pomala-SULAWESI-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6365]
# Airport Name
Sangia Nibandera
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low Priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105633302-7088ad00-5e1d-11eb-9bd2-a82fc6f59069.png)
