### ISSUE TITLE
WALG-Tanjung Selor-KALIMANTAN-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6367]
# Airport Name
Tanjung Harapan
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low Priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105632959-97de7a80-5e1b-11eb-95a5-37873467b3d8.png)
