### ISSUE TITLE
AYOO-Komo Manda Airstrip-HELA-PAPUA NEW GUINEA

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#6369]
![AYOO-git](https://user-images.githubusercontent.com/26853210/105580562-f7d61200-5d84-11eb-9fb5-efd4f0c1987f.png)

**Comment by kilt46** [comment]
Elevation is incorrect

![image](https://user-images.githubusercontent.com/14023167/105638488-78a21600-5e38-11eb-91c6-1b5e2e1720b3.png)

**Comment by MajorTomMueller** [comment]
Solved
