### ISSUE TITLE
DAAS-Ain Arnat Airport-SÉTIF-ALGERIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6370]
# Airport Name
Ain Arnat Airport
# Country?
Algeria
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105925511-e485a980-6005-11eb-837e-f6c371290e08.png)
