### ISSUE TITLE
DABB-Rabah Bitat Airport-ANNABA-ALGERIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6371]
# Airport Name
Rabah Bitat Airport
# Country?
Algeria
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105925149-472a7580-6005-11eb-88f0-bb67d97a8d69.png)
