### ISSUE TITLE
DAOI-Chlef International Airport-CHLEF-ALGERIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6372]
# Airport Name
Chlef International Airport
# Country?
Algeria
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105924813-b358a980-6004-11eb-88f6-914fa32a7fe1.png)
