### ISSUE TITLE
FEFU-Sibut Airport-KÉMO-CENTRAL AFRICAN REPUBLIC

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6373]
# Airport Name
Sibut Airport
# Country?
CAR
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105631505-67471280-5e14-11eb-93a5-cd6d2bbebbfa.png)
