### ISSUE TITLE
KPOC-Brackett Field Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6376]
# Airport Name
Brackett Field
# Country?
USA
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Is that a joke
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105936865-0f79f880-601a-11eb-8eb6-500397eadea0.png)
