### ISSUE TITLE
FEFZ-Zemio Airport-HAUT-MBOMOU-CENTRAL AFRICAN REPUBLIC

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6377]
# Airport Name
Zemio Airport
# Country?
CAR
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105631040-f868ba00-5e11-11eb-94a3-8da1e3137f86.png)
