### ISSUE TITLE
FEGC-Bocaranga Airport-OUHAM-PENDÉ-CENTRAL AFRICAN REPUBLIC

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6378]
# Airport Name
Bocaranga Airport
# Country?
CAR
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105630938-5fd23a00-5e11-11eb-9365-b3526ae54a5c.png)
