### ISSUE TITLE
FEGE-Obo M'Boki Airport-HAUT-MBOMOU-CENTRAL AFRICAN REPUBLIC

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6379]
# Airport Name
Obo M'Boki Airport
# Country?
CAR
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105630815-c440c980-5e10-11eb-967a-a79281e4017c.png)
