### ISSUE TITLE
KCEZ-Cortez Municipal Airport-COLORADO-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#6380]
# Airport Name
Cortez Municipal
# Country?
USA
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106966997-fe14a880-670b-11eb-96d9-112c79717463.png)
