### ISSUE TITLE
WITC-Meulaboh-ACEH-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6382]
# Airport Name
Cut Nyak Dhien
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low Priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105632723-60230300-5e1a-11eb-9394-0d57cc34d71d.png)
