### ISSUE TITLE
WIMU-Kutacane-ACEH-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6383]
# Airport Name
Alas Leuser
# Country?
Indonesia
# Improvements that need to be made?
Create New Airporr
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low Priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106342107-44c65680-6265-11eb-9865-476c7210fd18.png)
