### ISSUE TITLE
ZSYN-Yancheng Nanyang-JIANGSU-CHINA

### ISSUE THREAD

**Issue by zacky89315** [InfiniteFlightAirportEditing/Airports#6386]
# Airport Name
Yancheng Nanyang
# Country?
China
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106360750-f1ddb500-62df-11eb-9684-8c90585c7a57.png)
