### ISSUE TITLE
MX97-San Miguel de Allende Airstrip-GUANAJUATO-MEXICO

### ISSUE THREAD

**Issue by lalomarlin** [InfiniteFlightAirportEditing/Airports#6387]
# Airport Name
San Miguel de Allende Airstrip
# Country?
Mexico
# Improvements that need to be made?
Needs to be added
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low Priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105780147-78d40b80-5f35-11eb-8c84-352a49b1b3e8.png)
