### ISSUE TITLE
MXCA-Xcalak Airstrip-QUINTANA ROO-MEXICO

### ISSUE THREAD

**Issue by lalomarlin** [InfiniteFlightAirportEditing/Airports#6388]
# Airport Name
Xcalak Airstrip
# Country?
Mexico
# Improvements that need to be made?
Needs to be added
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low Priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105778590-483ea280-5f32-11eb-9e40-5664752bb5d0.png)
