### ISSUE TITLE
MM41-Pie de la Cuesta AFB-GUERRERO-MEXICO

### ISSUE THREAD

**Issue by lalomarlin** [InfiniteFlightAirportEditing/Airports#6389]
# Airport Name
Pie de la Cuesta AFB
# Country?
Mexico
# Improvements that need to be made?
Needs to be redone
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low Priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105652586-394ae800-5e7f-11eb-81dd-592ce4bf667b.png)
