### ISSUE TITLE
UHPN-Manily-KAMCHATKA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6390]
# Airport Name
Manily
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low
http://www.caiga.ru/common/AirClassGDE/validaip4/aip/ad/ad2/uhpn/4-ad2-uhpn-031.pdf

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106071605-44df1e80-60cc-11eb-8c39-8f9b38abc63a.png)
