### ISSUE TITLE
UHPS-Sobolevo-KAMCHATKA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6391]
# Airport Name
Sobolevo
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low
http://www.caiga.ru/common/AirClassGDE/validaip4/aip/ad/ad2/uhps/4-ad2-uhps-031.pdf

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106071215-8e7b3980-60cb-11eb-8bc1-ee4077981e36.png)
