### ISSUE TITLE
HTMA-Mafia Airport-Pwani-Tanzania

### ISSUE THREAD

**Issue by Captainflight** [InfiniteFlightAirportEditing/Airports#6392]
# Airport Name
Mafia Airport
# Country?
Tanzania 
# Improvements that need to be made?
Needs to be added 
# Are you working on this airport?
Yes 
# Airport Priority? (IF Event, 10000ft+ Runway, World/US Capital, Low)
 Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106072354-a2c03600-60cd-11eb-8857-515001ede079.png)
