### ISSUE TITLE
OENG-Nejran Airport-SAUDI ARABIA

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#6393]
# Airport Name
Nejran Airport
# Country?
Saudi Arabia
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
10000ft+

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105781114-8d190800-5f37-11eb-976c-b834332e4987.png)
