### ISSUE TITLE
FEGF-Batangafo Airport-OUHAM-CENTRAL AFRICAN REPUBLIC

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6394]
# Airport Name
Batangafo Airport
# Country?
CAR
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105770635-18d56900-5f25-11eb-970f-7cf47c91852f.png)
