### ISSUE TITLE
FEGG-Gamboula Airport-MAMBÉRÉ-KADÉI-CENTRAL AFRICAN REPUBLIC

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6395]
# Airport Name
Gamboula Airport
# Country?
CAR
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105770276-951b7c80-5f24-11eb-9d04-29d0c5976fbc.png)
