### ISSUE TITLE
FEGL-Gordil Airport-VAKAGA-CENTRAL AFRICAN REPUBLIC

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6396]
# Airport Name
Gordil Airport
# Country?
CAR
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105768151-94cdb200-5f21-11eb-9c0f-9247a2ffca1e.png)
