### ISSUE TITLE
40AR-Lost Bridge Village Airport-ARKANSAS-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6397]
![Full](https://user-images.githubusercontent.com/59462519/105649830-90fe4900-5ea9-11eb-9248-38b26226088b.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105936524-764ae200-6019-11eb-891a-46bedfdb8c45.png)
