### ISSUE TITLE
OEPA-Al Qaisumah Airport-ASH SHARQIYAH-SAUDI ARABIA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6398]
# Airport Name
Al Qaisumah / Hafr al Batin Airport
# Country?
KSA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
2

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105780769-d1f06f00-5f36-11eb-9592-c298af03be10.png)
