### ISSUE TITLE
FEGM-Bakouma Airport-MBOMOU-Central African Republic

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6399]
# Airport Name
Bakouma Airport
# Country?
CAR
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105767242-70250a80-5f20-11eb-91a8-08d5c03db6bc.png)
