### ISSUE TITLE
KSHN

### ISSUE THREAD

**Issue by Nik-Barbour** [InfiniteFlightAirportEditing/Airports#64]
Assigned to Nik Barbour.

**Comment by rednaxela796** [comment]
I'll  it

**Comment by rednaxela796** [comment]
I will rework this one (add taxiways and parking areas)

**Comment by dushyants19** [comment]
Will do

**Comment by dushyants19** [comment]
Done :)

**Comment by dushyants19** [comment]
Gated by dush19 in d2b4d8a8a18a4e16b046c3f72d1623bb0b494adc

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19254141/55e24f72-8f16-11e6-85bf-167214550758.png)
