### ISSUE TITLE
FEGO-Ouanda Djallé Airport-VAKAGA-CENTRAL AFRICAN REPUBLIC

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6400]
# Airport Name
Ouanda Djallé Airport
# Country?
CAR
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105766917-f5f48600-5f1f-11eb-833d-6f447696a867.png)
