### ISSUE TITLE
VEMN-Dibrugarh Airport-Assam-India

### ISSUE THREAD

**Issue by KaalicharanDH** [InfiniteFlightAirportEditing/Airports#6401]
# Airport Name
Dibrugarh Airport
# Country?
India
# Improvements that need to be made?
Full Rework
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105927081-de44fc80-6008-11eb-8dcc-d1f39c8e3829.png)
