### ISSUE TITLE
WIEB-Sipora/Rokot-SUMATRA-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6402]
# Airport Name
Rokot
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low Priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105766430-5cc56f80-5f1f-11eb-979a-cd2a3243234a.png)
