### ISSUE TITLE
WIJI-Kerinci-JAMBI-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6403]
# Airport Name
Depati Parbo
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low Priority

**Comment by MajorTomMueller** [comment]
Corrected ICAO to WIJI after checking Indonesia AIP:
https://aimindonesia.dephub.go.id/images/27-GEN%202.4%20LOCATION%20INDICATORS%20AIRAC%20AIP%20AMDT%2098%2031%20DEC%2020.pdf

![WIJI](https://user-images.githubusercontent.com/26853210/105710145-9d68bd00-5f0e-11eb-92f8-ae4ad16c50f7.png)

**Comment by MajorTomMueller** [comment]
make sure to send with correct ICAO to OR @adibyaputra

**Comment by adibyaputra** [comment]
Thank you to corrected ICAO

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105765776-83cf7180-5f1e-11eb-946d-a891238677b3.png)
