### ISSUE TITLE
FEGU-Bouca Airport-OUHAM-CENTRAL AFRICAN REPUBLIC

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6406]
# Airport Name
Bouca Airport
# Country?
CAR
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105769515-8b454980-5f23-11eb-9e25-41ce2a3d84c6.png)
