### ISSUE TITLE
FEGZ-Bozoum Airport-OUHAM-PENDÉ-CENTRAL AFRICAN REPUBLIC

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6407]
# Airport Name
Bozoum Airport
# Country?
CAR
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105769189-11ad5b80-5f23-11eb-88f2-4f664b9f8b77.png)
