### ISSUE TITLE
WIPO-Way Kanan-LAMPUNG-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6408]
# Airport Name
Gatot Subroto
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low Priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105924459-eb132180-6003-11eb-8e47-9d0c5034b38e.png)
