### ISSUE TITLE
WAHU-Karimunjawa-JAWA-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6409]
# Airport Name
Dewandaru
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low Priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105923750-6d024b00-6002-11eb-8689-f8c64a0dbe00.png)
