### ISSUE TITLE
WAHL-Cilacap-JAWA-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6410]
# Airport Name
Tunggul Wulung
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low Priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105924122-44c71c00-6003-11eb-9d2b-874d7acb5531.png)
