### ISSUE TITLE
VNRC-Ramechhap Airport-RAMECHHAP-NEPAL

### ISSUE THREAD

**Issue by USA-ATC** [InfiniteFlightAirportEditing/Airports#6411]
# Airport Name
Manthali Airport
# Country?
RAMECHHAP NEPAL
# Improvements that need to be made?
Redo from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by zhf21** [comment]
I can do this.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124383437-06a8e500-dc92-11eb-99ad-758759bc3eea.png)
Elevation is incorrect. Please check

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124389058-23054b80-dcab-11eb-8cdb-4e578ae25c4d.png)
