### ISSUE TITLE
FEGR-Rafai Airport-MBOMOU-CENTRAL AFRICAN REPUBLIC

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6412]
# Airport Name
Rafai Airport
# Country?
CAR
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105768462-0c034600-5f22-11eb-9c11-4e49be613b22.png)
