### ISSUE TITLE
68Y-Wells Municipal-MINNESOTA-UNITED STATES

### ISSUE THREAD

**Issue by Aceorbit** [InfiniteFlightAirportEditing/Airports#6417]
# Airport Name
Wells Municipal
# Country?
US
# Improvements that need to be made?
Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105918394-776c1700-5ff9-11eb-9db5-d4c16c44cfe1.png)
