### ISSUE TITLE
ENNA-Banak Airport-NORWAY

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#6419]
# Airport Name
Banak Airport
# Country?
Norway
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106070797-bddd7680-60ca-11eb-913d-47b1b54416a1.png)
