### ISSUE TITLE
28MN-River Ridge Ranch-MINNESOTA-UNITED STATES

### ISSUE THREAD

**Issue by Aceorbit** [InfiniteFlightAirportEditing/Airports#6420]
# Airport Name
River Ridge Ranch
# Country?
United states
# Improvements that need to be made?
New airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by Aceorbit** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105917974-ce252100-5ff8-11eb-92a4-b4316a97cfe8.png)
