### ISSUE TITLE
KTOB-Dodge Center-MINNESOTA-UNITED STATES

### ISSUE THREAD

**Issue by Aceorbit** [InfiniteFlightAirportEditing/Airports#6421]
# Airport Name
Dodge Center
# Country?
United States
# Improvements that need to be made?
Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by Aceorbit** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105917566-1a239600-5ff8-11eb-9896-268e9ea34922.png)
