### ISSUE TITLE
DAUO-Guemar Airport-EL OUED-ALGERIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6422]
# Airport Name
Guemar Airport
# Country?
Algeria
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106070341-e618a580-60c9-11eb-8da8-662c159d98a5.png)
