### ISSUE TITLE
SNBD-Sobradinho Airport-BAHIA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#6423]
# Airport Name
Sobradinho Airport
# Country?
Brazil
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105923001-514a7500-6001-11eb-8721-dde6d09528f7.png)
