### ISSUE TITLE
21TE-MacGuire Ranch Airport-TEXAS-USA

### ISSUE THREAD

**Issue by SaharshShu** [InfiniteFlightAirportEditing/Airports#6424]
# Airport Name
Macguire Ranch
# Country?
United States of America
# Improvements that need to be made?
Full
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106341436-eb5d2800-6262-11eb-916c-f224e39fde9a.png)
