### ISSUE TITLE
ZYQQ-Qiqihar Sanjiazi-HEILONGJIANG-CHINA

### ISSUE THREAD

**Issue by zacky89315** [InfiniteFlightAirportEditing/Airports#6426]
# Airport Name
Qiqihar Sanjiazi
# Country?
China
# Improvements that need to be made?
redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107161195-b9ce1600-6960-11eb-9ab1-f2d2c20354ef.png)
