### ISSUE TITLE
VISR-Srinagar Airport-Jammu and Kashmir-India

### ISSUE THREAD

**Issue by KaalicharanDH** [InfiniteFlightAirportEditing/Airports#6429]
# Airport Name
Srinagar Airport
# Country?
India
# Improvements that need to be made?
From scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
10kft+ runway

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106384736-fd89b400-6391-11eb-8109-5c720239000e.png)
