### ISSUE TITLE
LOAS-Spitzerberg Airport-LOWER AUSTRIA-AUSTRIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6430]
# Airport Name
Spitzerberg Airport
# Country?
Austria
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106069521-473f7980-60c8-11eb-8b7a-e9fc2b80f462.png)
