### ISSUE TITLE
LOAU-Stockerau Airport-LOWER AUSTRIA-AUSTRIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6431]
# Airport Name
Stockerau Airport
# Country?
Austria
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106069252-cb453180-60c7-11eb-9f39-1fcf8d6a6a0d.png)
