### ISSUE TITLE
LOGI-Trieben Airport-STYRIA-AUSTRIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6433]
# Airport Name
Trieben Airport
# Country?
Austria
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106068915-05fa9a00-60c7-11eb-8e49-418b1b2ab719.png)
