### ISSUE TITLE
OETR-Turaif Domestic Airport-TURAIF-SAUDI ARABIA

### ISSUE THREAD

**Issue by suhasjatla** [InfiniteFlightAirportEditing/Airports#6434]
# Airport Name
Turaif Domestic Airport
# Country?
Saudi Arabia
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/110187200-19430880-7ddd-11eb-849c-9697d0573de3.png)
