### ISSUE TITLE
UHPT-Tilichiki-KAMCHATKA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6435]
# Airport Name
Tilichiki
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low
http://www.caiga.ru/common/AirClassGDE/validaip4/aip/ad/ad2/uhpt/4-ad2-uhpt-031.pdf

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106340511-ac79a300-625f-11eb-8406-eee5eba558ab.png)
