### ISSUE TITLE
UHPU-Ust-Khayryuzovo-KAMCHATKA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6436]
# Airport Name
Ust-Khayryuzovo
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low
http://www.caiga.ru/common/AirClassGDE/validaip4/aip/ad/ad2/uhpu/4-ad2-uhpu-031.pdf

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106340229-b18a2280-625e-11eb-829b-c4e5bd2c4148.png)
