### ISSUE TITLE
UHPX-Nikolskoye-KAMCHATKA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6437]
# Airport Name
Nikolskoye
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low
http://www.caiga.ru/common/AirClassGDE/validaip4/aip/ad/ad2/uhpx/4-ad2-uhpx-031.pdf

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106340013-ff525b00-625d-11eb-8351-85245811f12e.png)
