### ISSUE TITLE
T50-Menard County-TEXAS-USA

### ISSUE THREAD

**Issue by SaharshShu** [InfiniteFlightAirportEditing/Airports#6438]
# Airport Name
Menard County
# Country?
United States of America
# Improvements that need to be made?
Full
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106341295-58bc8900-6262-11eb-97cc-9f0d9cfa7849.png)
