### ISSUE TITLE
LOGK-Kapfenberg Airport-STYRIA-AUSTRIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6439]
# Airport Name
Kapfenberg Airport
# Country?
Austria
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106216246-51c94400-6198-11eb-9081-074c6a165bd9.png)
