### ISSUE TITLE
NCRG

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#644]
Rarotonga International - 1 runway, 1 ramp, 1 gate

[Non-Region and Suggestion]

**Comment by henrikbg** [comment]
@IFAEpat, we no longer use the non-region label. :)

**Comment by IFAEpat** [comment]
ah, thanks @henrikbg

**Comment by TristinWoolf** [comment]
I can do this one quick.

**Comment by TristinWoolf** [comment]
Just finished and sent it in!

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19418034/3eb952e0-9381-11e6-8e18-d5eb6774dba0.png)
