### ISSUE TITLE
LOGL-Lanzen/Turnau Airport-STYRIA-AUSTRIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6440]
# Airport Name
Lanzen/Turnau Airport
# Country?
Austria
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106215965-b46e1000-6197-11eb-98f7-5c7f31f86253.png)
