### ISSUE TITLE
KOLG-Solon Springs Municipal Airport-WISCONSIN-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#6445]
# Airport Name
Solon Springs Municipal Airport
# Country?
USA
# Improvements that need to be made?
Full (Redo)
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106841799-627e2c00-6668-11eb-864a-aeaadef412cd.png)
