### ISSUE TITLE
ENVD-Vadso Airport-NORWAY

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#6447]
# Airport Name
Vadso Airport
# Country?
Norway
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106339788-4429c200-625d-11eb-94fb-93db328f8c1d.png)
