### ISSUE TITLE
ENKB-Kristiansund Airport Kvernberget-Møre og Romsdal-NORWAY

### ISSUE THREAD

**Issue by JensSeverin** [InfiniteFlightAirportEditing/Airports#6448]
# Airport Name
Kristiansand Airport Kvernberget
# Country?
Norway
# Improvements that need to be made?
Full redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111874220-2aa21e00-8962-11eb-84f4-3103c7c4549a.png)
