### ISSUE TITLE
EGHR-Goodwood Aerodrome-ENGLAND-UK

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6449]
# Airport Name
Goodwood Aerodrome
# Country?
UK
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106361168-1a66ae80-62e2-11eb-8869-865777cb73f2.png)
