### ISSUE TITLE
LOGP-Pinkafeld Airport-STYRIA-AUSTRIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6451]
# Airport Name
Pinkafeld Airport
# Country?
Austria
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106215490-b7b4cc00-6196-11eb-80c7-ad2b5bc4d03d.png)
