### ISSUE TITLE
LOGT-Leoben/Timmersdorf Airport-STYRIA-AUSTRIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6452]
# Airport Name
Leoben/Timmersdorf Airport
# Country?
Austria
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106207996-453cef80-6188-11eb-8ba0-d89194185eac.png)
