### ISSUE TITLE
LOIR-Reutte/Hofen Airport-TYROL-AUSTRIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6455]
# Airport Name
Reutte/Hofen Airport
# Country?
Austria
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106335129-ce6c2900-6251-11eb-8527-3c207e4d97f4.png)
