### ISSUE TITLE
LOKF-Feldkirchen/Ossiacher Airport-CARINTHIA-AUSTRIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6456]
# Airport Name
Feldkirchen/Ossiacher Airport
# Country?
Austria
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106334884-3a01c680-6251-11eb-928d-e7df947f62ab.png)
