### ISSUE TITLE
LOKG-Ferlach-Glainach Airport-CARINTHIA-AUSTRIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6457]
# Airport Name
Ferlach-Glainach Airport
# Country?
Austria
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106334313-fd819b00-624f-11eb-98e4-cc395946e536.png)
