### ISSUE TITLE
KBLU-Blue Canyon Nyack Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by yoshiflyer** [InfiniteFlightAirportEditing/Airports#6458]
# Airport Name
Blue Canyon Nyack
# Country?
United States
# Improvements that need to be made?
Redone from Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low Priority

**Comment by StickThelanding** [comment]
can I redo this airport?

**Comment by brunocr1050** [comment]
Make sure to rejoin the server. You should've received a link for it.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115111360-9ff31580-9f45-11eb-847d-ad79fe02d181.png)
