### ISSUE TITLE
LOAR-Altlictenwarth Airport-LOWER AUSTRIA-AUSTRIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6459]
# Airport Name
Altlictenwarth Airport
# Country?
Austria
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106333956-53a20e80-624f-11eb-867f-39b07eede4ad.png)
