### ISSUE TITLE
LOGF-Furstenfeld Airport-STYRIA-AUSTRIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6460]
# Airport Name
Furstenfeld Airport
# Country?
Austria
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106333506-6cf68b00-624e-11eb-8030-4c5bfb559265.png)
