### ISSUE TITLE
LOGO-Niederoblarn Airport-STYRIA-AUSTRIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6461]
# Airport Name
Niederoblarn Airport
# Country?
Austria
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106331902-5a2e8700-624b-11eb-821a-b83901367e4a.png)
