### ISSUE TITLE
 KSIY-Siskiyou County Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by LawinS** [InfiniteFlightAirportEditing/Airports#6462]
# Airport Name
Siskiyou County Airport

# Country?
USA

# Improvements that need to be made?
Full redo 

# Are you working on this airport?
Yes

# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111087534-1d170f00-84f0-11eb-9e0f-1dfdc08745cd.png)
