### ISSUE TITLE
ESNX-Arvidsjaur Airport-SWEDEN

### ISSUE THREAD

**Issue by JensSeverin** [InfiniteFlightAirportEditing/Airports#6463]
# Airport Name
Arvidsjaur Airport
# Country?
Sweden
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106958069-7a07f400-66fe-11eb-9909-e423d650690c.png)
