### ISSUE TITLE
EDAX-Mueritz Airpark-MECKLENBURG-GERMANY

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6464]
# Airport Name
Mueritz Airpark
# Country?
germany
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by mervinjane** [comment]
i'll like to take this airport.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115121777-1e69aa80-9f7a-11eb-89b1-38fd20a48023.png)
