### ISSUE TITLE
ZYMD-Mudanjiang Hailang-HEILONGJIANG-CHINA

### ISSUE THREAD

**Issue by zacky89315** [InfiniteFlightAirportEditing/Airports#6465]
# Airport Name
Mudanjiang Hailang
# Country?
China
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115963620-b8cf6e00-a4e5-11eb-98bd-b7a72827dccd.png)
