### ISSUE TITLE
FZWA-Mbuji Mayi Airport-KASAI ORIENTAL-DEMOCRATIC REPUBLIC OF CONGO

### ISSUE THREAD

**Issue by dklaffke** [InfiniteFlightAirportEditing/Airports#6466]
# Airport Name
Mbuji Mayi Airport
# Country?
DR Congo
# Improvements that need to be made?
Redone completely
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107298893-e440d180-6a3b-11eb-93e4-c9d381cccfa3.png)
