### ISSUE TITLE
XHPL-Klyuchi-KAMCHATKA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6467]
# Airport Name
Klyuchi AB
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low
http://www.caiga.ru/DocAni/manual_of_4_letter_indexes/Indexes_of_Airports.pdf - ru: ЬХПЛ

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106361035-61a06f80-62e1-11eb-9db1-4c912c196733.png)
