### ISSUE TITLE
LOAV-Voslau Airport-LOWER AUSTRIA-AUSTRIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6468]
# Airport Name
Voslau Airport
# Country?
Austria
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106393126-e7dcb480-63ba-11eb-99a4-128e3bcac26a.png)
