### ISSUE TITLE
LOGG-Punitz-Gussing Airport-STYRIA-AUSTRIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6469]
# Airport Name
Punitz-Gussing Airport
# Country?
Austria
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106393043-4ce3da80-63ba-11eb-966f-830aefc8bfec.png)
