### ISSUE TITLE
EGNT- Newcastle Airport-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by chriscroft20** [InfiniteFlightAirportEditing/Airports#647]
Newcastle airport redo

**Comment by chriscroft20** [comment]
sent for review

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20333716/17b4e4fa-ab7a-11e6-8218-f67197ea4334.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44949276-f0002680-adf3-11e8-9a8a-656a01c1cde6.png)

**Comment by ItsW1ll** [comment]
Will be completing an airport redo

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/61822919-22ae7580-ae31-11e9-8f0c-c74510f290a5.jpg)
