### ISSUE TITLE
LOKH-Friesach/Hirt Airport-CARINTHIA-AUSTRIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6470]
# Airport Name
Friesach/Hirt Austria
# Country?
Austria
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106392941-b7e0e180-63b9-11eb-8c5e-959614b9609e.png)
