### ISSUE TITLE
UTFF-Fergana-FERGANA-UZBEKISTAN

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6471]
# Airport Name
Fergana Intl
# Country?
Uzbekistan
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low
http://ais.uzairways.com/aip/pdf/ad/utff/utff11.pdf

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107439762-31827900-6af8-11eb-8c0b-304db2133cac.png)
