### ISSUE TITLE
KHEF-Manassas Regional Airport-WASHINGTON-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6473]
# Airport Name
Manassas Regional Airport 
# Country?
USA
# Improvements that need to be made?
Manual edtit
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107120202-d596c680-6851-11eb-9cfe-91a5fab24815.png)
