### ISSUE TITLE
GCLB-El Berriel Airport-CANARIAS-SPAIN

### ISSUE THREAD

**Issue by lucaviness** [InfiniteFlightAirportEditing/Airports#6475]
♻️

**Comment by AleksanderIF** [comment]
Duplicate - #5015

**Comment by MajorTomMueller** [comment]
Thanks for mentioning @AleksanderIF

**Comment by brunocr1050** [comment]
Reuse, reduce, recycle.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107885403-bc2ff300-6ebf-11eb-812c-44b178b5d3b5.png)
