### ISSUE TITLE
3DW-Downtown Airport-MISSOURI-USA

### ISSUE THREAD

**Issue by lucaviness** [InfiniteFlightAirportEditing/Airports#6476]
# Airport Name
Downtown Airport
# Country?
United States
# Improvements that need to be made?
Will redo from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by ShaneAviation** [comment]
I can redo this one.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115962788-90924000-a4e2-11eb-88b2-a13d96ac60cf.png)
