### ISSUE TITLE
71TE-Moursund Ranch-TEXAS-USA

### ISSUE THREAD

**Issue by SaharshShu** [InfiniteFlightAirportEditing/Airports#6477]
# Airport Name
Moursund Ranch
# Country?
United States
# Improvements that need to be made?
Full
# Are you working on this airport?
Yep
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106682252-b533e700-6587-11eb-8a61-61fa95f46a80.png)
