### ISSUE TITLE
CYCE-Centralia/James T. Field Memorial Aerodrome-ONTARIO-CANADA

### ISSUE THREAD

**Issue by mike116119** [InfiniteFlightAirportEditing/Airports#6478]
# Airport Name
Centralia/James T. Field Memorial Aerodrome
# Country?
Canada
# Improvements that need to be made?
Full rework- Autogen airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/119260052-a739be80-bb96-11eb-9d25-fe9d46c9bc7d.png)
