### ISSUE TITLE
PPIT-Nunapitchuk Airstrip-ALASKA-USA

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6479]
# Airport Name
Nunapitchuk Airstrip
# Country?
uhhh usa ig
# Improvements that need to be made?
redo >:)
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![Uploading image.png…]()
