### ISSUE TITLE
RJCW-Wakkanai Airport-HOKKAIDO-JAPAN

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#648]
Wakkanai

[Being Redone]

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17244477/b22680a4-5547-11e6-9415-88dda95824fc.png)

**Comment by IFAEpat** [comment]
Gated

**Comment by kilt46** [comment]
Missing lines
![image](https://cloud.githubusercontent.com/assets/14023167/17720316/7f04db14-63e6-11e6-85f5-e705e11563c5.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17827705/116528da-6647-11e6-9a76-66e633f9f584.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17827706/18380d58-6647-11e6-8a1e-28dd29535b04.png)
