### ISSUE TITLE
OYHD-Hodeidah International-TAHAMA-YEMEN

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#6480]
# Airport Name
Hodeidah International
# Country?
Yemen
# Improvements that need to be made?
full redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
GP1

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106958756-65782b80-66ff-11eb-963a-b605af460021.png)
