### ISSUE TITLE
KEVB-New Smyrna Beach Muni-FLORIDA-USA

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6481]
# Airport Name
New Smyrna Beach Muni
# Country?
usa usa usa 
# Improvements that need to be made?
redo
# Are you working on this airport?
hmm yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106841436-bb999000-6667-11eb-8d10-7145ef4db4b4.png)
