### ISSUE TITLE
VNRT-Rumjatar Airport-Province 1-Nepal

### ISSUE THREAD

**Issue by Captainflight** [InfiniteFlightAirportEditing/Airports#6482]
# Airport Name
Rumjatar Airport
# Country?
Nepal
# Improvements that need to be made?
rework from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106959308-1aaae380-6700-11eb-8402-f2bb733c6f90.png)
