### ISSUE TITLE
KJYR-York Municipal Airport-NEBRASKA-USA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6483]
# Airport Name
York Muni
# Country?
NE, USA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106405455-dff13480-63fb-11eb-8ddf-f7727b04d4de.png)
