### ISSUE TITLE
4B0-Albany South Airport-NEW YORK-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6484]
![Full](https://user-images.githubusercontent.com/59462519/106374884-f6a57600-637e-11eb-9196-0dbaf8e16f0f.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106384281-99fe8700-638f-11eb-951f-318b8826d6f1.png)
