### ISSUE TITLE
EPAR-Arłamów Airport-SUBCARPATHIAN-POLAND

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6485]
# Airport Name
Arłamów Airport
# Country?
Poland
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106391870-063fb180-63b5-11eb-89d4-37cedc55e032.png)
