### ISSUE TITLE
EP69-Lipki Wielkie Airport-LUBUSZ-POLAND

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6486]
# Airport Name
Lipki Wielkie AIrport
# Country?
Poland
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106391265-15713000-63b2-11eb-8df0-da1251a4c8ac.png)
