### ISSUE TITLE
KPRB-Paso Robles Municipal-CALIFORNIA-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6487]
# Airport Name
Paso Robles Municipal
# Country?
USA
# Improvements that need to be made?
Hella more hangars to add
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106840759-68730d80-6666-11eb-8e4e-489ebca380df.png)
