### ISSUE TITLE
EPBA-Bielsko Biala Airport-SILESIAN-POLAND

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6488]
# Airport Name
Bielsko Biala Airport
# Country?
Poland
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106405223-1d08f700-63fb-11eb-8bcf-dd444954f6cd.png)
