### ISSUE TITLE
EPBC-Lotnisko Warszawa Babice-MASOVIA-POLAND

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6489]
# Airport Name
Lotnisko Warszawa-Babice
# Country?
Poland
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106405057-7cb2d280-63fa-11eb-84d4-b5bd0395426e.png)
