### ISSUE TITLE
KORL-Orlando Executive-FLORIDA-USA

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6490]
# Airport Name
Orlando Executive
# Country?
usa
# Improvements that need to be made?
redo
# Are you working on this airport?
y
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109230511-9e4d7280-778a-11eb-87cf-69073c40e2c6.png)

**Comment by brennanhackard** [comment]
@feitidede , the previous editor of this airport, will be making taxiway fixes.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/110242074-e6525f00-7f19-11eb-8550-72381e7e931e.png)
