### ISSUE TITLE
EPBK-Białystok-Krywlany Airport-PODLASKIE-POLAND

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6491]
# Airport Name
Białystok-Krywlany Airport
# Country?
Poland
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
What is the source for the asphalt runway?

![image](https://user-images.githubusercontent.com/14023167/106527292-a3314600-64ac-11eb-864e-b21505544e1e.png)

**Comment by brunocr1050** [comment]
@jakey20 used Yandex since it has the latest imagery.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106529575-5e0f1300-64b0-11eb-9e7d-06b952cf39b8.png)
