### ISSUE TITLE
EPBY-Bydgoszcz Ignacy Jan Paderewski Airport-KUYAVIAN POMERANIAN-POLAND

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6492]
# Airport Name
Bydgoszcz Ignacy Jan Paderewski Airport
# Country?
Poland
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106526811-d9ba9100-64ab-11eb-8eaa-81be80e37a68.png)
