### ISSUE TITLE
EPDA-Darlowo Airport-WEST POMERANIAN-POLAND

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6493]
# Airport Name
Darlowo Airport
# Country?
Poland
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106525849-3e74ec00-64aa-11eb-82bf-d734c480ee78.png)
