### ISSUE TITLE
LOKL-Lienz-Nikolsdorf Airport-CARINTHIA-AUSTRIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6494]
# Airport Name
Lienz-Nikolsdorf Airport
# Country?
Austria
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106523718-23ed4380-64a7-11eb-9461-14210a5f5f4e.png)
