### ISSUE TITLE
LOKM-Mayerhofen Bei Friesach Airport-CARINTHIA-AUSTRIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6495]
# Airport Name
Mayerhofen Bei Friesach Airport
# Country?
Austria
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106523120-4763be80-64a6-11eb-8ac6-ef25142b00fa.png)
