### ISSUE TITLE
LOKN-Notsch Im Gaital Airport-CARINTHIA-AUSTRIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6496]
# Airport Name
Notsch Im Gaital Airport
# Country?
Austria
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106522131-d66fd700-64a4-11eb-9dc3-d4008cdd2173.png)
