### ISSUE TITLE
SAAP-General Urquiza Airport-ENTRE RIOS-ARGENTINA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#6497]
# Airport Name
General Urquiza Airport
# Country?
Argentina
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106961357-1207dc80-6703-11eb-87a9-f975bf445d99.png)
