### ISSUE TITLE
EPBO-Lądowisko/Borsk Airfield-POMERANIAN-POLAND

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6498]
# Airport Name
Lądowisko/Borsk Airfield
# Country?
Poland
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106677050-a0eaec80-657d-11eb-8747-676fe860c8b2.png)
