### ISSUE TITLE
EPCD-Depułtycze Królewskie Airport-LUBLIN-POLAND

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6499]
# Airport Name
Depułtycze Królewskie Airport
# Country?
Poland
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106676495-a562d580-657c-11eb-9fc1-d82b538eccb9.png)
