### ISSUE TITLE
LTAC

### ISSUE THREAD

**Issue by turkish1941** [InfiniteFlightAirportEditing/Airports#650]
I will make the airport.

**Comment by turkish1941** [comment]
e-mail has been sent

**Comment by dushyants19** [comment]
If it hasnt been approved till now, something is wrong with the airport :)

**Comment by Oguz8011** [comment]
@turkish1941 kabul edilmedi sanırım tekrar düzenleyebilir misin?

**Comment by kilt46** [comment]
http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=LTAC

**Comment by dushyants19** [comment]
Improvements made by @turkish1941 in 620768e841a82b1bf1bd8a64e7612bc8b47a639e

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18939502/67919e02-85c6-11e6-9a9f-d6157969fe02.png)
