### ISSUE TITLE
EPEL-Elbląg Airport-WARMIAN MASURIAN-POLAND

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6500]
# Airport Name
Elbląg Airport
# Country?
Poland
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106676077-dc84b700-657b-11eb-9413-556072732ab7.png)
