### ISSUE TITLE
LOKR-St. Donat-Mairist Airport-CARINTHIA-AUSTRIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6501]
# Airport Name
St. Donat-Mairist Airport
# Country?
Austria
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106680948-1c9c6780-6585-11eb-80b9-4d0f0b59ecf2.png)
