### ISSUE TITLE
LOKW-Wolfsberg Airport-CARINTHIA-AUSTRIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6502]
# Airport Name
Wolfsberg Airport
# Country?
Austria
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106680672-97b14e00-6584-11eb-8d74-cc4fa7dbd260.png)
