### ISSUE TITLE
LOLC-Scharnstein Airport-UPPER AUSTRIA-AUSTRIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6503]
# Airport Name
Scharnstein Airport
# Country?
Austria
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106680224-d4c91080-6583-11eb-90d9-373200beae29.png)
