### ISSUE TITLE
DAAV-Jijel Ferhat Abbas Airport-JIJEL-ALGERIA

### ISSUE THREAD

**Issue by tonyi31** [InfiniteFlightAirportEditing/Airports#6505]
# Airport Name 
 JIJEL/Ferhat ABBAS
# Country?
Algérie 
# Improvements that need to be made?
 New
# Are you working on this airport?
 yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by MBeringuy** [comment]
@tonyi31 Are you on the IFAET server on Discord? In case you are, I need you to tell me your name so I can send you a PM via Discord.

**Comment by tonyi31** [comment]
Nom Mido

**Comment by tonyi31** [comment]
hello you can redo this airport thank you

**Comment by MBeringuy** [comment]
Available for those who want to redo.

**Comment by Czechoslovaki** [comment]
I'll do it.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106840086-12ea3100-6665-11eb-830d-caeca49fd79b.png)
