### ISSUE TITLE
YBNA-Ballina Airport-NEW SOUTH WALES-AUSTRALIA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#6507]
# Airport Name
Ballina Airport
# Country?
Australia
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106962347-9ad34800-6704-11eb-9ca1-d5484ebaf9d8.png)
