### ISSUE TITLE
HSWW-Wau Airport-WAU-SOUTH SUDAN

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6509]
# Airport Name
Wau Airport
# Country?
South Sudan
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107440315-09dfe080-6af9-11eb-9751-e2993a24cd00.png)
