### ISSUE TITLE
MBPV-Providenciales International Airport-WEST CAICOS-TURKS AND CAICOS ISLANDS

### ISSUE THREAD

**Issue by henrikbg** [InfiniteFlightAirportEditing/Airports#651]
Providenciales International Airport.

**Comment by henrikbg** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19582575/555f806e-96fb-11e6-8e76-be9dc1030662.png)

**Comment by henrikbg** [comment]
Fixed some minor stuff.

**Comment by Czechoslovaki** [comment]
@GBKarp will redo the airport.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104124315-cdf90600-5315-11eb-8619-212cfcb55168.png)
