### ISSUE TITLE
HSSM-Malakal Airport-UPPER NILE-SOUTH SUDAN

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6510]
# Airport Name
Malakal Airport
# Country?
South Sudan
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106971404-7aab8500-6714-11eb-8820-fac77ed8069e.png)
