### ISSUE TITLE
LOLE-Eferding Airport-UPPER AUSTRIA-AUSTRIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6511]
# Airport Name
Eferding Airport
# Country?
Austria
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106680021-68e6a800-6583-11eb-9ddc-e27eff0ad446.png)
