### ISSUE TITLE
KTKV-Tomahawk Regional-WISCONSIN-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#6514]
# Airport Name
Tomahawk Regional
# Country?
USA
# Improvements that need to be made?
Full (Redo)
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106967399-b93d4180-670c-11eb-8743-e3e60b063aa1.png)
