### ISSUE TITLE
M54-Lebanon Muni-TENNESSEE-USA

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6515]
# name
Lebanon Muni
# contri
usa
# is it an ugly autogen that makes u want to puke?
yes :(
# will u unmercifully exterminate this autogen
yes >:)
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106967992-aa0ac380-670d-11eb-89ea-bc2767be19b2.png)
