### ISSUE TITLE
EPGI-Lisie Kąty/Grudziądz Airport-KUYAVIAN POMERANIAN-POLAND

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6516]
# Airport Name
Lisie Kąty/Grudziądz Airport
# Country?
Poland
# Improvements that need to be made?
Redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106675761-523c5300-657b-11eb-96f9-802e860df922.png)
