### ISSUE TITLE
KFCI

### ISSUE THREAD

**Issue by danielshaw** [InfiniteFlightAirportEditing/Airports#652]
I will redo this airport.

**Comment by henrikbg** [comment]
Added proper labels. :)

**Comment by danielshaw** [comment]
Sent for peer review. Will be sent in for final review in a few hours.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20415368/5ea5c986-acfd-11e6-9faf-03f429373415.png)
