### ISSUE TITLE
EPGO-Góraszka Airport-MASOVIAN-POLAND

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6520]
# Airport Name
Góraszka
# Country?
Poland
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106821021-06a0ac80-6642-11eb-8872-5e977bb66703.png)
