### ISSUE TITLE
KALM-Alamogordo White Sands Regional Airport-NEW MEXICO-USA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6521]
# Airport Name
Alamogordo-White Sands Regional Airport
# Country?
USA
# Improvements that need to be made?
Manual edit
# Are you working on this airport?
Yes - ECoops
# Airport Priority? (10000ft+ Runway, Low)
Low Priority

**Comment by ECoops-123** [comment]
Duplicate #3374

I cannot approve you at this time as I do not have current access to Discord.

**Comment by adibyaputra** [comment]
@ECoops-123 But this airport has grown until now, that's why I want to rework this airport.

**Comment by ECoops-123** [comment]
> @ECoops-123 But this airport has grown until now, that's why I want to rework this airport.

Request to update the airport in #Discusions and it will be discussed internally. Do not create duplicate topics for airports, they can always be re-opened for future work.

**Comment by adibyaputra** [comment]
@ECoops-123 Thank you for you suggest, I just know the procedure to Reworking Airport because this is my first time doing it now

**Comment by adibyaputra** [comment]
@ECoops-123 I don't want to rework this airport, but why are you assigned this airport? I don't want to rework an airport that isn't in my area.

**Comment by AleksanderIF** [comment]
@adibyaputra Since you created a duplicate issue supervisor can recycle it for another airport. And you will not redo this airport.

**Comment by ECoops-123** [comment]
> @ECoops-123 I don't want to rework this airport, but why are you assigned this airport? I don't want to rework an airport that isn't in my area.

Don't worry about this issue now. It's being recycled (since this is a duplicate and is no use). It's an airport that I'm working on. If you are working on WICA, you'll continue in the other topic.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106841133-226a7980-6667-11eb-814c-38fd49bb79db.png)
