### ISSUE TITLE
EPGE-Giże Airport-WARMIAN MASURIAN-POLAND

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6522]
# Airport Name
Giże Airport
# Country?
Poland
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106675509-d3471a80-657a-11eb-9b60-897e696475a5.png)
