### ISSUE TITLE
LOLH-Hofkirchen Airport-UPPER AUSTRIA-AUSTRIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6523]
# Airport Name
Hofkirchen Airport
# Country?
Austria
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106818432-e53dc180-663d-11eb-84e0-96582488fc70.png)
