### ISSUE TITLE
LOLM-Micheldorf Airport-UPPER AUSTRIA-AUSTRIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6524]
# Airport Name
Micheldorf Airport
# Country?
Austria
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106817886-1d90d000-663d-11eb-93fa-f5bd8df5861c.png)
