### ISSUE TITLE
LOLO-Linz/Ost Airport-UPPER AUSTRIA-AUSTRIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6525]
# Airport Name
Linz/Ost Airport
# Country?
Austria
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106817577-a824ff80-663c-11eb-8e2b-13f9df023918.png)
