### ISSUE TITLE
EPGY-Grądy Airport-LESSER POLAND-POLAND

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6526]
# Airport Name
Grądy Airport
# Country?
Poland
# Improvements that need to be made?
REdo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106820452-f76d2f00-6640-11eb-833c-a837566f9852.png)
