### ISSUE TITLE
EPIN-Inowrocław Airport-KUYAVIAN POMERANIAN-POLAND

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6527]
# Airport Name
Inowrocław Airport
# Country?
Poland
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106820015-45cdfe00-6640-11eb-9284-fc5d6000b6a4.png)
