### ISSUE TITLE
93MN-Hoppe Sky Ranch-MINNESOTA-USA

### ISSUE THREAD

**Issue by Aceorbit** [InfiniteFlightAirportEditing/Airports#6528]
# Airport Name
Hoppe Sky Ranch
# Country?
US
# Improvements that need to be made?
brand new to repo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106827806-b714ad80-664e-11eb-9292-122219a7773a.png)
