### ISSUE TITLE
MN74-B & D Flyers-MINNESOTA-USA

### ISSUE THREAD

**Issue by Aceorbit** [InfiniteFlightAirportEditing/Airports#6529]
# Airport Name
B & D Flyers
# Country?
US
# Improvements that need to be made?
Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106827293-3190fd80-664e-11eb-86da-ccf936572b52.png)
