### ISSUE TITLE
KECU-Edwards County-TEXAS-USA

### ISSUE THREAD

**Issue by Saharsh1234** [InfiniteFlightAirportEditing/Airports#6530]
# Airport Name
Edwards County
# Country?
USA
# Improvements that need to be made?
Full redo
# Are you working on this airport?
Yessir
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108923423-66192900-75fe-11eb-9e79-6db1aa3321c8.png)
