### ISSUE TITLE
HUPA-Pakuba National Airport-GULU-UGANDA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#6531]
# Airport Name
Pakuba National Airport
# Country?
Uganda
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106964636-066ae480-6708-11eb-9c19-c38e7bba56e7.png)
