### ISSUE TITLE
HUMA-Mbarara Airport-MBARARA-UGANDA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#6532]
# Airport Name
Mbarara Airport
# Country?
Uganda
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106964966-96109300-6708-11eb-9e86-6cad8433360b.png)
