### ISSUE TITLE
KPKF-Park Falls Municipal-WISCONSIN-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#6533]
# Airport Name
Park Falls Municipal
# Country?
USA
# Improvements that need to be made?
Full (Redo)
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107101440-f53fd780-67dc-11eb-9129-686dbe899841.png)
