### ISSUE TITLE
03MN-Nauerth Land Ranch-MINNESOTA-USA

### ISSUE THREAD

**Issue by Aceorbit** [InfiniteFlightAirportEditing/Airports#6535]
# Airport Name
Nauerth Land Ranch
# Country?
USA
# Improvements that need to be made?
Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106822016-e83bb080-6643-11eb-852b-02335f0cbc33.png)
