### ISSUE TITLE
EPJG-Jelenia Góra Airport-LOWER SILESIAN-POLAND

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6536]
# Airport Name
Jelenia Góra Airport
# Country?
Poland
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106819421-634e9800-663f-11eb-93b3-c092c0ad591a.png)
