### ISSUE TITLE
EPKA-Masłów/Kielc Airport-ŚWIETOKRZYSKIE-POLAND

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6537]
# Airport Name
Masłów/Kielc Airport
# Country?
Poland
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106819071-e4f1f600-663e-11eb-801a-7d8d4f2a1d2a.png)
