### ISSUE TITLE
DABC-Mohamed Boudiaf Intl Airport-CONSTATINE-ALGERIA

### ISSUE THREAD

**Issue by tonyi31** [InfiniteFlightAirportEditing/Airports#6538]
# Airport Name
Constantine Mohamed BOUDIAF
# Country?
Algérie 
# Improvements that need to be made?
New 
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by ECoops-123** [comment]
Do not claim or create issues until you are in the Discord! We have rules and procedures here that you must follow! 

And do not change the title back. That is an incorrect title.

**Comment by tonyi31** [comment]
OK sorry

**Comment by tonyi31** [comment]
if possible you do this airport

**Comment by ECoops-123** [comment]
It will be available for anyone until you are in the Discord and request to claim it (and we feel the airport is an appropriate size)

**Comment by OscarConklin** [comment]
May I do this one?

**Comment by mervinjane** [comment]
I'll like to take this airport.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116631677-1b2bd280-a91b-11eb-8a57-8fa171cf038c.png)
