### ISSUE TITLE
DAAE-Abane Ramdane Airport-BÉJAÏA-ALGERIA

### ISSUE THREAD

**Issue by tonyi31** [InfiniteFlightAirportEditing/Airports#6539]
# Airport Name
Bejaia - Abane Ramdane BJA (Soummam – Abane Ramdane Airport)
# Country? 
Algérie 
# Improvements that need to be made?
New
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by ECoops-123** [comment]
Editor currently unavailable to claim airport.

**Comment by ECoops-123** [comment]
@Daniel-Baiks will work on this.

**Comment by kilt46** [comment]
![Uploading image.png…]()
