### ISSUE TITLE
RJDC-Yamaguchi Ube-YAMAGUCHI-JAPAN

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#654]
Yamaguchi-Ube Airport

(Has been done, forgot to make issue, sorry)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17244510/e0003006-5547-11e6-96c4-1eb0ce5be4cf.png)

**Comment by IFAEpat** [comment]
Gated

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17720399/3825d8a0-63e7-11e6-87c4-7833f420f1ba.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17720404/43b9ff7a-63e7-11e6-9944-73b48d43b9f2.png)
Gates not as per Navigraph

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17827668/8ff7d2f2-6646-11e6-9244-d03c188e50fa.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17827670/97ea49d6-6646-11e6-962c-fccc05d983e2.png)
