### ISSUE TITLE
DAUH-Hassi Messaou /Krim Belkacem Airport-OUARGLA-ALGERIA

### ISSUE THREAD

**Issue by tonyi31** [InfiniteFlightAirportEditing/Airports#6540]
# Airport Name
Hassi Messaoud, Krim Belkacem
# Country?
Algérie 
# Improvements that need to be made?
New
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by ECoops-123** [comment]
Editor currently unavailable to claim airport.

**Comment by MajorTomMueller** [comment]
@tonyi31 
To make kit more clear:
If you not been able to join the team as described in IFC:
https://community.infiniteflight.com/t/infinite-flight-airport-editing/321307
the next issue you open in here will be considered as spam and appropriate steps will be taken. 
this is not a wish list

**Comment by MajorTomMueller** [comment]
Here you go @IFsami 
regards, Aladin

**Comment by IFsami** [comment]
Hi, am still working on this and have it in PR right now

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116630632-254cd180-a919-11eb-90c2-4b71ad5b0f82.png)
