### ISSUE TITLE
DNSO-Saddiq Abubakar III Airport-SOKOTO-NIGERIA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#6541]
# Airport Name
Saddiq Abubakar III International Airport
# Country?
Nigeria
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106838617-41b2d800-6662-11eb-8065-952cbbdf72fd.png)
