### ISSUE TITLE
FZOA-Kindu Airport-MANIEMA-DEMOCRATIC REPUBLIC OF CONGO

### ISSUE THREAD

**Issue by dklaffke** [InfiniteFlightAirportEditing/Airports#6542]
# Airport Name
Kindu Airport
# Country?
DR Congo
# Improvements that need to be made?
Complete redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107296273-a7bea700-6a36-11eb-9d5a-f691b1168985.png)
