### ISSUE TITLE
LFMV-Avignon Caumont-VAUCLUSE-FRANCE

### ISSUE THREAD

**Issue by Jeremy351** [InfiniteFlightAirportEditing/Airports#6543]
# Airport Name
Avignon Caumont
# Country?
France
# Improvements that need to be made?
Full redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107290104-9623d200-6a2b-11eb-9447-05513446c6ae.png)
