### ISSUE TITLE
DAAP-Takhamalt Airport-ILLIZI-ALGERIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6544]
♻️

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106838861-af5f0400-6662-11eb-86df-0e27e6cfc9bf.png)

**Comment by OscarConklin** [comment]
Could this issue be recycled to DAAP?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107120283-5f469400-6852-11eb-83e7-3c0e6fee1879.png)
Please check Altitude

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107121134-71c2cc80-6856-11eb-9135-6b08c7fa5da2.png)
