### ISSUE TITLE
LOLT-Seitenstetten Airport-LOWER AUSTRIA-AUSTRIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6545]
# Airport Name
Seitenstetten Airport
# Country?
Austria
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106817154-14ebca00-663c-11eb-8291-87555f54e5a2.png)
