### ISSUE TITLE
LOSM-Mauterndorf Airport-SALZBURG-AUSTRIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6546]
# Airport Name
Mauterndorf Airport
# Country?
Austria
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106816812-8bd49300-663b-11eb-869d-bba0e85782c5.png)
