### ISSUE TITLE
KSNS-Salinas Municipal Airport-CALIFONIA-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6547]
# Airport Name
Salinas Municipal
# Country?
USA
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Lowe

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107147622-a4cb9580-6914-11eb-9c9e-c46dfa9d040b.png)
