### ISSUE TITLE
DAOR-Bechar/Boudghene Ben Ali Lotfi Airport-BECHAR-ALGERIA

### ISSUE THREAD

**Issue by falous** [InfiniteFlightAirportEditing/Airports#6548]
# Airport Name
Béchar - Boudghene Ben Ali Lotfi
# Country?
Algérie 
# Improvements that need to be made?
New
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by brunocr1050** [comment]
Hey there, you don't seem to be in the team. Please make sure to join us before we can assign you.

**Comment by falous** [comment]
I join or I tried slack it doesn't work

**Comment by brunocr1050** [comment]
We moved from Slack to Discord. You have to join through the IF forums.

**Comment by falous** [comment]
We moved from Slack to Discord. You have to join through the IF forums.

**Comment by MBeringuy** [comment]
Access the link below and request to join IFAET. A link to Discord will be sent to you via email.
https://community.infiniteflight.com/t/infinite-flight-airport-editing/321307

**Comment by kilt46** [comment]
![Uploading image.png…]()
