### ISSUE TITLE
LFLC-Clermont Ferrand Auvergne-PUY DE DOME-FRANCE

### ISSUE THREAD

**Issue by Jeremy351** [InfiniteFlightAirportEditing/Airports#6549]
# Airport Name
Clermont Ferrand Auvergne
# Country?
France
# Improvements that need to be made?
Full redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108596538-50300d80-734b-11eb-9b3f-0540d4227e3f.png)
