### ISSUE TITLE
RJFF-Fukuoka Airport-FUKUOKA-JAPAN

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#655]
Needs rename FUKUOKA-Fukuoka

(Also done, forgot to make issue, sorry again)

**Comment by kilt46** [comment]
This one needs more work. Terminal is missing, Overlapping aprons, not snapped.Gate lines incomplete. Looks like an XPlane copy

**Comment by IFAEpat** [comment]
Reflection way too strong on Concrete Slabs, can someone with a working Google Earth software do this? Thanks :)

**Comment by kilt46** [comment]
In my opinion this is not a very good likeness of the airport.

**Comment by IFAEpat** [comment]
what needs to be done @kilt46 ?

**Comment by IFAEpat** [comment]
Committed

**Comment by kilt46** [comment]
Gates need renamed.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17244534/f7b823fc-5547-11e6-8dc4-4f327f3d69e7.png)

**Comment by IFAEpat** [comment]
Gated

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17574960/f22b413e-5f2a-11e6-9ea5-7f336c98c7dd.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17574963/f865df28-5f2a-11e6-945a-5b224ba41cc3.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17574967/00c4023a-5f2b-11e6-86b9-439816550a0c.png)

**Comment by RyanEpps** [comment]
Fixes to be done
