### ISSUE TITLE
2MN4-Cornfield Canyon-MINNESOTA-USA

### ISSUE THREAD

**Issue by Aceorbit** [InfiniteFlightAirportEditing/Airports#6550]
# Airport Name
Cornfield Canyon
# Country?
US
# Improvements that need to be made?
scratch
# Are you working on this airport?
ye
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106966330-bb060580-670a-11eb-851b-95106cdb6821.png)
