### ISSUE TITLE
MY00-Siegs Farm-MINNESOTA-USA

### ISSUE THREAD

**Issue by Aceorbit** [InfiniteFlightAirportEditing/Airports#6551]
# Airport Name
Sieg's Farm Airport
# Country?
US
# Improvements that need to be made?
Scratch
# Are you working on this airport?
YEs
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106965888-f522d780-6709-11eb-8d4b-2143a5d622b1.png)
