### ISSUE TITLE
VEJR-Maa Danteshwari Airport-CHHATTISGARH-INDIA

### ISSUE THREAD

**Issue by Captainflight** [InfiniteFlightAirportEditing/Airports#6553]
# Airport Name
Jagdalpur 
# country 
India
# Improvements that need to be made
needs to be added 
# Are you working on this airport?
Yes 
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by brunocr1050** [comment]
The code for this airport is VEJR and not VEGR.

**Comment by kilt46** [comment]
![Uploading image.png…]()
