### ISSUE TITLE
KSFY-Tri-Township-ILLINOIS-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#6554]
# Airport Name
Tri-Township
# Country?
USA
# Improvements that need to be made?
Full (Redo)
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107161395-17169700-6962-11eb-90eb-78d2141cd511.png)
