### ISSUE TITLE
WIGE-Enggano-BENGKULU-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6555]
# Airport Name?
Enggano
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low Priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107289293-67f1c280-6a2a-11eb-911f-04eb40939853.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107290477-3b3eaa80-6a2c-11eb-8652-97bae5019da4.png)
