### ISSUE TITLE
WIGM-Muko Muko-BENGKULU-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6556]
# Airport Name
Muko-Muko
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low Priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106970926-7fbc0480-6713-11eb-9c1b-8bd2fbbf593f.png)
