### ISSUE TITLE
PFKA-Kasigluk Airport-ALASKA-USA

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6559]
# Airport Name
Kasigluk Airport
# Country?
usa
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/106969436-6f565a80-6710-11eb-9ee9-df563853f504.png)
