### ISSUE TITLE
RJOY

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#656]
Yao

[Being Redone]

**Comment by dushyants19** [comment]
@henrikbg why did you assign yourself :neutral_face:

**Comment by henrikbg** [comment]
My bad, Dush.

**Comment by IFAEpat** [comment]
Done.

**Comment by IFAEpat** [comment]
Gated

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17720232/ec3da41e-63e5-11e6-9485-4585a42355cf.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17720233/f48b6ec6-63e5-11e6-8a10-1de7e38fb571.png)
