### ISSUE TITLE
KPPQ-Pittsfield Penstone Municipal Airport-ILLINOIS-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#6563]
# Airport Name
Pittsfield Penstone Municipal Airport
# Country?
USA
# Improvements that need to be made?
Full (Redo)
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107293858-fae22b00-6a31-11eb-97fc-f4822f46767c.png)
