### ISSUE TITLE
VONL-Nadirgul Airfield-TELANGANA-INDIA

### ISSUE THREAD

**Issue by hari-shreyas** [InfiniteFlightAirportEditing/Airports#6564]
# Airport Name
Nadirgul Airfield
# Country?
India
# Improvements that need to be made?
Must be added
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
Is this VONL?

https://www.pilotnav.com/airport/VONL

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107772888-7417a180-6d02-11eb-8f01-9f269a9bb5d3.png)
