### ISSUE TITLE
X50-Massey Ranch Airpark-FLORIDA-USA

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6565]
# Airport Name
Massey Ranch Airpark
# Country?
us
# Improvements that need to be made?
redo.
# Are you working on this airport?
YES I AM
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107861710-263b9000-6e0d-11eb-81ba-6f04c954c815.png)
