### ISSUE TITLE
NTTP-Maupiti Airport-FRENCH POLYNESIA

### ISSUE THREAD

**Issue by RobertineIFC** [InfiniteFlightAirportEditing/Airports#6566]
# Airport Name
Maupiti
# Country?
French Polynesia
# Improvements that need to be made?
Being Redone
# Are you working on this airport?
YES
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by MinhNguyN** [comment]
Hi:)), Can I redo this airport?

**Comment by MinhNguyN** [comment]
I would assume that is a yes

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/119224852-10053600-bac6-11eb-83d3-4ccb6752acde.png)
