### ISSUE TITLE
40MN-Turner Field-MINNESOTA-USA

### ISSUE THREAD

**Issue by Aceorbit** [InfiniteFlightAirportEditing/Airports#6567]
# Airport Name
Turner Field
# Country?
US
# Improvements that need to be made?
Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107119813-9a939380-684f-11eb-8945-27439a785c56.png)
