### ISSUE TITLE
3MN4-Rolling Hills-MINNESOTA-USA

### ISSUE THREAD

**Issue by Aceorbit** [InfiniteFlightAirportEditing/Airports#6568]
# Airport Name
Rolling Hills Airport
# Country?
USA
# Improvements that need to be made?
New to repo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107119717-075a5e00-684f-11eb-940f-0fc97ae4d973.png)
