### ISSUE TITLE
KHKA-Blytheville Municipal Airport-ARKANSAS-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#6569]
# Airport Name
Blytheville Muni
# Country?
USA
# Improvements that need to be made?
Full (Redo)
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107292701-e0a74d80-6a2f-11eb-97fc-f05ea2a6c561.png)
