### ISSUE TITLE
RJGG-Chubu Centrair Intl-AICHI-JAPAN

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#657]
Chubu International

[Being Redone]

**Comment by IFAEpat** [comment]
Concrete reflects sunlight too much, unable to draw most of the airport. Can someone with a working Google Earth software do this? Thanks :)

**Comment by IFAEpat** [comment]
Still unable to redo this airport because the concrete is reflecting the sun on WEDbing, closing for now :)

**Comment by kilt46** [comment]
This has not been done yet!

**Comment by brunocr98** [comment]
Taking this airport.

**Comment by brunocr98** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22006007/64a769ca-dc2d-11e6-8838-c9f8aab7ec1b.png)

**Comment by orangejuicie** [comment]
Frequency updete.

**Comment by orangejuicie** [comment]
Frequency update ver.2
