### ISSUE TITLE
KALX-Thomas C Russell Field Airport-ALABAMA-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6570]
<Mangoes>

![V1](https://user-images.githubusercontent.com/59462519/107106125-f0e9dd80-6821-11eb-9ebc-ac0a7fa5583b.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107119966-68cefc80-6850-11eb-8f50-a2ebf0457ec9.png)
