### ISSUE TITLE
1MN0-Wetherbee Farm-MINNESOTA-USA

### ISSUE THREAD

**Issue by Gabe-Z** [InfiniteFlightAirportEditing/Airports#6572]
# Airport Name
Wetherbee Farm
# Country?
USA
# Improvements that need to be made?
Unedited
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107147829-c11c0200-6915-11eb-91d2-1b8df0205d1c.png)
