### ISSUE TITLE
ZBDT-Datong/Yungang Airport-SHANXI-CHINA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#6573]
# Airport Name
Datong/Yungang Airport
# Country?
China
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107146940-de9a9d00-6910-11eb-8879-b71a3ea12e78.png)
