### ISSUE TITLE
SVBM-Jacinto Lara International Airport-LARA-VENEZUELA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6574]
# Airport Name
Jacinto Lara International Airport
# Country?
Venezuela
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107161097-fbaa8c80-695f-11eb-9b42-b7a591923de4.png)
