### ISSUE TITLE
LFJL-Metz Nancy Lorraine-MOSELLE-FRANCE

### ISSUE THREAD

**Issue by Jeremy351** [InfiniteFlightAirportEditing/Airports#6575]
# Airport Name
Metz Nancy Lorraine
# Country?
France
# Improvements that need to be made?
Full redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by Czechoslovaki** [comment]
@Jeremy351 how's this airport going?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/120078256-33a32000-c074-11eb-840a-7dd99c8a1df4.png)
