### ISSUE TITLE
1MN5-Molnau Airpark-MINNESOTA-USA

### ISSUE THREAD

**Issue by Gabe-Z** [InfiniteFlightAirportEditing/Airports#6576]
# Airport Name
Molnau Airpark
# Country?
USA
# Improvements that need to be made?
Unedited
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107161301-6f00ce00-6961-11eb-9740-f64e6a892b8b.png)
