### ISSUE TITLE
KVIQ-Neillsville Muni-Wisconsin-USA

### ISSUE THREAD

**Issue by Saharsh1234** [InfiniteFlightAirportEditing/Airports#6577]
# Airport Name
Neillsville Muni
# Country?
USA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108597666-c5054680-734f-11eb-862a-f09dc2a75aaf.png)
