### ISSUE TITLE
RJCC-New Chitose Airport-HOKKAIDO-JAPAN

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#658]
New Chitose

[Being Redone]

**Comment by IFAEpat** [comment]
up for grabs

**Comment by MajorTomMueller** [comment]
This airport is linked to RJCJ Chitose Air Base. Taxiways allow to use RWY of both airports.
This should be taken into consideration when doing this airport.

**Comment by benlenahan** [comment]
I'll take this one over.

**Comment by alchonub** [comment]
Could I take this 2/3 airports in review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/35482386-fbffa5b8-03f9-11e8-8d3c-3c677dd85728.png)

**Comment by MajorTomMueller** [comment]
Shelter spawns misaligned 
![3ddd866e-22fc-4ca5-9790-59f7043c3994](https://user-images.githubusercontent.com/26853210/37675537-ca9e9dae-2c75-11e8-9a8e-c64a9af2e340.png)

**Comment by MajorTomMueller** [comment]
While this edit I cooperated RJCJ RJCJ is missing in IF. That leads to missing procedures for the two western runways. Will split the airports to solve this.

**Comment by MajorTomMueller** [comment]
RJCJ #5143 connects via taxiway

**Comment by MajorTomMueller** [comment]
![RJCC-git](https://user-images.githubusercontent.com/26853210/85946654-56ddc080-b935-11ea-830c-61bdf3b56d7c.png)

**Comment by MajorTomMueller** [comment]
https://github.com/InfiniteFlightAirportEditing/Airports/commit/2b894df3b9b2ba3cab59db6f7cd9d476efd38e32

**Comment by ECoops-123** [comment]
Adding new taxiway, extending terminal, and adding hole.

![20210125_012944](https://user-images.githubusercontent.com/59462519/105677035-44376400-5ee3-11eb-968b-d58229138fd3.jpg)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105771578-61415680-5f26-11eb-8888-efbac6c09232.png)

**Comment by kilt46** [comment]
Concern with visually transparent aprons

**Comment by ECoops-123** [comment]
https://github.com/InfiniteFlightAirportEditing/Airports/commit/7b0b689b3cb2a39371c10b89c773bdb4032cd9d5 

Fixed in update.

----

![Full](https://user-images.githubusercontent.com/59462519/105846790-960be700-5fd4-11eb-85f6-7b94391575a1.png)
