### ISSUE TITLE
UTSB-Bukhara International Airport-BUKHARA-UZBEKISTAN

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6581]
# Airport Name
Bukhara International Airport
# Country?
Uzbekistan
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107586386-6f999e80-6bc5-11eb-88d2-28b405604361.png)
