### ISSUE TITLE
UTNU-Urgench International Airport-XORAZM-UZBEKISTAN

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6582]
# Airport Name
Urgench International Airport
# Country?
Uzbekistan
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107435951-7c00f700-6af2-11eb-9cfa-41a3b3337c8d.png)
