### ISSUE TITLE
UTFN-Namangan Intl-NAMANGAN-UZBEKISTAN

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6583]
# Airport Name
Namangan Intl
# Country?
Uzbekistan
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
10/28 - 10748ft

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107435563-eebda280-6af1-11eb-998e-b17d5b028677.png)
