### ISSUE TITLE
FGBT-Bata Airport-LITORAL-EQUATORIAL GUINEA

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#6585]
# Airport Name
Bata Airport
# Country?
Equatorial Guinea
# Improvements that need to be made?
Full Rework
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
03/21 10,860ft

**Comment by dklaffke** [comment]
Sadly the imagery of ESRI, Google and Bing are all too bad to edit this airport sufficiently

**Comment by MinhNguyN** [comment]
I think the satellite image of the airport is not too bad for me and also the google image has just been updated in March 2021, I will make this airport. Also, does anyone have parking/docking chart of this airport?

**Comment by brunocarbone3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/135530715-845d9ddd-9ebd-4fdf-a586-c1cf2dac8839.png)
