### ISSUE TITLE
UTDK-Kulob Intl-KHALTON-TAJIKISTAN

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6586]
# Airport Name
Kulob (Kulyab) Intl
# Country?
Tajikistan
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108006554-62afed00-6fc1-11eb-8c9f-948e7f807149.png)
