### ISSUE TITLE
UTDT-Bokhtar Intl-KHATLON-TAJIKISTAN

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6587]
# Airport Name
Bokhtar Intl
# Country?
Tajikistan
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109231666-9e4e7200-778c-11eb-9728-23fe60c02172.png)
