### ISSUE TITLE
VEJT-Jorhat Airport-ASSAM-INDIA

### ISSUE THREAD

**Issue by KaalicharanDH** [InfiniteFlightAirportEditing/Airports#6588]
# Airport Name
Jorhat Airport
# Country?
India
# Improvements that need to be made?
Full rework
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107582672-732a2700-6bbf-11eb-908b-c7a746a4faea.png)
