### ISSUE TITLE
DAUI-In Salah Airport-TAMANRASSET-ALGERIA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#6589]
# Airport Name
In Salah Airport
# Country?
Algeria
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107288840-bfdbf980-6a29-11eb-953a-e9c93ac5e39c.png)
