### ISSUE TITLE
RJFU-Nagasaki Airport-NAGASAKI-JAPAN

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#659]
Nagasaki International

[Being Redone]

**Comment by IFAEpat** [comment]
Sent for reviewal :)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17244564/285d435c-5548-11e6-856c-d6710f6dc703.png)

**Comment by IFAEpat** [comment]
gating

**Comment by IFAEpat** [comment]
gated e7d044a

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17651176/e63f20ee-6226-11e6-9807-8d71d4c49025.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17651179/eed0d14e-6226-11e6-8320-bb92dfe006f8.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111075620-da851080-84b6-11eb-8831-42cbb26f4e9c.png)
