### ISSUE TITLE
F70-French Valley Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6590]
# Airport Name
French Valley Airport
# Country?
U S A
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107587819-14b57680-6bc8-11eb-91c0-c38e340c568b.png)
