### ISSUE TITLE
FNGI-Ondjiva Airport-CUNENE-ANGOLA

### ISSUE THREAD

**Issue by dklaffke** [InfiniteFlightAirportEditing/Airports#6592]
# Airport Name
Ondjiva (Ngiva) Airport 
# Country?
Angola
# Improvements that need to be made?
Complete Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
10,640ft 13/31

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108602127-f852d000-7365-11eb-9028-9e35ccd6420c.png)
