### ISSUE TITLE
ORMM-Basra International Airport-AL BASRA-IRAQ

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6594]
# Airport Name
Basra International Airport
# Country?
Iraq
# Improvements that need to be made?
Redo
# Are you working on this airport?
Ye
# Airport Priority? (10000ft+ Runway, Low)
10k

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108599929-9e4c0d80-7359-11eb-8f17-71c91e5304e7.png)
