### ISSUE TITLE
SNED-Socrates Rezende Airport-BAHIA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#6596]
# Airport Name
Socrates Rezende Airport
# Country?
Brazil
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107288347-ec434600-6a28-11eb-98b0-d8812f51d1e5.png)
