### ISSUE TITLE
CYDC-Drayton Valley Industrial Airport-BRITISH COLUMBIA-CANADA

### ISSUE THREAD

**Issue by JulietTango-IF** [InfiniteFlightAirportEditing/Airports#6597]
# Airport Name
Drayton Valley Industrial Airport
# Country?
Canada
# Improvements that need to be made?
Full rework
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by ECoops-123** [comment]
Old ICAO > CER3. Remove on OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115114597-d20c7380-9f55-11eb-9331-9d1708362e08.png)
