### ISSUE TITLE
OEDM-Dawadmi Domestic Airport-RIYADH-SAUDI ARABIA

### ISSUE THREAD

**Issue by Captainflight** [InfiniteFlightAirportEditing/Airports#6598]
# Airport Name
Dawadmi Domestic Airport
# Country?
Saudia Arabia  
# Improvements that need to be made?
Rework from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by Captainflight** [comment]
Change the ICAO to OEDW

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107584056-6f979f80-6bc1-11eb-9475-2ac0afe54bef.png)
