### ISSUE TITLE
KAND-Anderson Regional Airport-SOUTH CAROLINA-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6600]
# Airport Name
Anderson Regional Airport
# Country?
USA
# Improvements that need to be made?
Manual edit
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107590349-88a64d80-6bcd-11eb-9a32-2da23ee0d346.png)
