### ISSUE TITLE
KANW-Ainsworth Regional Airport-NEBRASKA-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6601]
# Airport Name
Ainsworth Regional Airport
# Country?
USA
# Improvements that need to be made?
Manual edit
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107590041-d79fb300-6bcc-11eb-8866-475ef78703e0.png)
