### ISSUE TITLE
OERF-Rafha Domestic Airport-Al-ḤUDŪD Al-SHIMĀLIYYAH-SAUDI ARABIA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6603]
# Airport Name
Rafha Domestic Airport
# Country?
KSA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107584962-f7ca7480-6bc2-11eb-8a81-468eb6b41f0a.png)
