### ISSUE TITLE
SILC-Bom Futuro Airport-MATO GROSSO-BRAZIL

### ISSUE THREAD

**Issue by victormw22** [InfiniteFlightAirportEditing/Airports#6604]
# Airport Name
Bom futuro
# Country?
Brazil
# Improvements that need to be made?
Redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107793325-c618f100-6d1b-11eb-84fb-2c5a5954d359.png)
