### ISSUE TITLE
KANY-Anthony Municipal Airport-KANSAS-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6605]
![Full](https://user-images.githubusercontent.com/59462519/107500499-21b57400-6b8e-11eb-9657-c5da1f278eb9.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107589745-47616e00-6bcc-11eb-84a0-7cb240a1bb2c.png)
