### ISSUE TITLE
KAOC-Arco Butte County Airport-IDAHO-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6606]
![Full](https://user-images.githubusercontent.com/59462519/107506331-da32e600-6b95-11eb-87a3-64d4357d5515.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107589470-b5596580-6bcb-11eb-9c4c-3d602762d2cf.png)
