### ISSUE TITLE
KAOH-Lima Allen County Airport-OHIO-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6607]
![Full](https://user-images.githubusercontent.com/59462519/107516648-a01d1080-6ba4-11eb-9e3f-2fd88e3333d9.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107588618-b4273900-6bc9-11eb-8190-ccd03a31a7e8.png)
