### ISSUE TITLE
SIWD-Pequena Holanda I Airstrip-MARANHAO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#6609]
# Airport Name
Pequena Holanda I Airstrip
# Country?
Brazil
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107586863-66f59800-6bc6-11eb-85e4-189ee8152537.png)
