### ISSUE TITLE
SNAI-Fazenda Nossa Senhora Das Gracas Airport-MATO GROSSO DO SUL-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#6610]
# Airport Name
Fazenda Nossa Senhora Das Gracas Airport
# Country?
Brazil
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107587024-aae89d00-6bc6-11eb-96cb-40a6010dbe23.png)
