### ISSUE TITLE
20V-Mc Elroy Airfield-COLORADO-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#6611]
# Airport Name
Mc Elroy Airfield
# Country?
USA
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107588278-ff8d1780-6bc8-11eb-9c3a-5982c56481a2.png)
