### ISSUE TITLE
KCEK-Crete Municipal Airport-NEBRASKA-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6613]
# Airport Name
Crete Municipal
# Country?
USA
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107861401-318dbc00-6e0b-11eb-9fa5-79243c63350c.png)
