### ISSUE TITLE
2N6-Redwing Airport-NEW JERSEY-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6614]
![Full](https://user-images.githubusercontent.com/59462519/107594965-413eb200-6c0b-11eb-9581-4689cfc02b87.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107788966-9e735a00-6d16-11eb-87da-4254d8110ec6.png)
