### ISSUE TITLE
FZIC-Kisangani Bangoka Airport-ORIENTALE-DEMOCRATIC REPUBLIC OF CONGO

### ISSUE THREAD

**Issue by dklaffke** [InfiniteFlightAirportEditing/Airports#6615]
# Airport Name
Kisangani Bangoka Airport
# Country?
DR Congo 
# Improvements that need to be made?
Complete Rework
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
11,483ft 13/31

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108599803-f7677180-7358-11eb-9162-2f60a9f7b25b.png)
