### ISSUE TITLE
LSMF-Mollis Airport-GLARUS-SWITZERLAND

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6616]
![Full](https://user-images.githubusercontent.com/59462519/107627314-006c8a80-6c57-11eb-8ead-4129af9d3d78.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107771887-133b9980-6d01-11eb-93e5-d51f7a046395.png)

**Comment by MajorTomMueller** [comment]
3rd Spetember 2020:
https://www.mollisairport.ch/post/aus-lsmf-wird-lszm

**Comment by MajorTomMueller** [comment]
https://github.com/InfiniteFlightAirportEditing/Airports/commit/c4d484b34890dfe299ff9708d4cf2ebf23971b0e
