### ISSUE TITLE
VOHY-Begumpet Airport-Telangana-India

### ISSUE THREAD

**Issue by Captainflight** [InfiniteFlightAirportEditing/Airports#6617]
# Airport Name
Begumpet airport
# Country?
India
# Improvements that need to be made?
rework from scratch
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/110720300-f1381880-81d3-11eb-80c4-de4795851332.png)
