### ISSUE TITLE
MY12-Dykstra Acreage-MINNESOTA-USA

### ISSUE THREAD

**Issue by Aceorbit** [InfiniteFlightAirportEditing/Airports#6618]
# Airport Name
Dykstra Acreage Airport
# Country?
USA
# Improvements that need to be made?
Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107781678-c7432180-6d0d-11eb-9eb9-397518204e6e.png)
