### ISSUE TITLE
SNGN-Garanhuns Airport-PERNAMBUCO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#6619]
# Airport Name
Garanhuns Airport
# Country?
Brazil
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107788124-a8488d80-6d15-11eb-89bf-f62c1b0c0c3c.png)
