### ISSUE TITLE
SNMU-Mucuri Airport-BAHIA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#6620]
# Airport Name
Mucuri Airport
# Country?
Brazil
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107767665-f0a68200-6cfa-11eb-9e7e-7d28185a1d6a.png)
