### ISSUE TITLE
KDVP-Slayton Municipal-MINNESOTA-USA

### ISSUE THREAD

**Issue by Aceorbit** [InfiniteFlightAirportEditing/Airports#6621]
# Airport Name
Slayton Municipal Airport
# Country?
USA
# Improvements that need to be made?
Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107858044-a1924700-6df7-11eb-8769-93d55a6c20a6.png)
