### ISSUE TITLE
SILS-Big Master Airport-MATO GROSSO-BRAZIL

### ISSUE THREAD

**Issue by victormw22** [InfiniteFlightAirportEditing/Airports#6622]
# Airport Name
Big Master 
# Country?
Brazil
# Improvements that need to be made?
redone
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113069282-9d42a300-9185-11eb-979e-f2cc67204463.png)
