### ISSUE TITLE
KAQO-Llano Municipal Airport-TEXAS-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6625]
![KAQO](https://user-images.githubusercontent.com/59462519/107771355-8dd0dd00-6d32-11eb-8e83-58837327bea1.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107782668-f1e1aa00-6d0e-11eb-9519-32dc05a39001.png)
