### ISSUE TITLE
FZUA-Kananga Airport-KASAI ORIENTAL-DEMOCRATIC REPUBLIC OF CONGO

### ISSUE THREAD

**Issue by dklaffke** [InfiniteFlightAirportEditing/Airports#6628]
# Airport Name
Kananga Airport
# Country?
DR Congo
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109081782-6b42aa80-76c8-11eb-82ae-fb86f1e92704.png)
