### ISSUE TITLE
UKDD-Dnipropetrovsk International Airport-DNIPROPETROVSK-UKRAINE

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6629]
# Airport Name
Dnipropetrovsk International Airport
# Country?
Ukraine
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108006295-b2da7f80-6fc0-11eb-83f7-0785bb540ba2.png)
