### ISSUE TITLE
EGPN-Dundee Airport-SCOTLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by nmasterson** [InfiniteFlightAirportEditing/Airports#663]
Assigned to me

**Comment by nmasterson** [comment]
- Update to ILS critical area
- Added 3rd ramp to apron A
- Removed taxiway adjacent to TWY D and extended taxi line
- Removed heavy jets from ramp start up

**Comment by henrikbg** [comment]
@nmasterson, I've invited you to the airport editors team. Could you accept? (Invitation should be located in your email.)

**Comment by dushyants19** [comment]
@nmasterson How is the progress on this? Been 6 months!

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32754742-b80ddbb0-c897-11e7-841a-bb44b6171959.png)
