### ISSUE TITLE
KTKC-Tracy Municipal-MINNESOTA-USA

### ISSUE THREAD

**Issue by Aceorbit** [InfiniteFlightAirportEditing/Airports#6630]
# Airport Name
Tracy Municipal
# Country?
USA
# Improvements that need to be made?
Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107857768-398f3100-6df6-11eb-9684-314f47a9e83e.png)
