### ISSUE TITLE
KAQR-Atoka Municipal Airport-OKLAHOMA-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6631]
![Full](https://user-images.githubusercontent.com/59462519/107838846-cbb81a80-6d9f-11eb-96e7-30884439529f.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107861245-3736d200-6e0a-11eb-9d57-2c7825962bcc.png)
