### ISSUE TITLE
MMCO-Comitan Air Force Base-CHIAPAS-MEXICO

### ISSUE THREAD

**Issue by lalomarlin** [InfiniteFlightAirportEditing/Airports#6632]
# Airport Name
Air Force Base
# Country?
Mexico
# Improvements that need to be made?
Needs to be Redone
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108000295-2a071800-6faf-11eb-8c09-3e2c057885d4.png)
