### ISSUE TITLE
MMTA-Tlaxcala Naval Air Station-TLAXCALA-MEXICO

### ISSUE THREAD

**Issue by lalomarlin** [InfiniteFlightAirportEditing/Airports#6633]
# Airport Name
Tlaxcala Naval Air Station
# Country?
Mexico
# Improvements that need to be made?
Needs to be Redone
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/107999956-6f771580-6fae-11eb-9b54-ce14081776cc.png)
