### ISSUE TITLE
OYGD-Al Ghaidah International-AL MAHARA-YEMEN

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#6634]
![OYGD-git](https://user-images.githubusercontent.com/26853210/107876762-d2d64a00-6ebf-11eb-9863-3ece317202c3.png)

**Comment by kilt46** [comment]
![Uploading image.png…]()

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108006054-fed8f480-6fbf-11eb-90cf-57c9260b91c4.png)
