### ISSUE TITLE
KWHP-Whiteman Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6635]
# Airport Name
Whiteman Airport
# Country?
USA
# Improvements that need to be made?
Full Redo not from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108626200-98ffc900-7414-11eb-9c20-04cd67bbda05.png)
