### ISSUE TITLE
UIUU-Ulan-Ude-BURYATIA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6636]
# Airport Name
Ulan-Ude
# Country?
Russia
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Runway - 11,152ft

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108782294-f25d1a80-7530-11eb-810c-2c4961092d70.png)
