### ISSUE TITLE
VEKU-Silchar Airport-ASSAM-INDIA

### ISSUE THREAD

**Issue by hari-shreyas** [InfiniteFlightAirportEditing/Airports#6637]
# Airport Name
Silchar Airport
# Country?
India 
# Improvements that need to be made?
Must be added
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111042477-38f0b700-8403-11eb-99d2-3d424afbe941.png)
