### ISSUE TITLE
LFNY-Saint Etienne en Devoluy-HAUTES ALPES-FRANCE

### ISSUE THREAD

**Issue by Jeremy351** [InfiniteFlightAirportEditing/Airports#6638]
# Airport Name
Saint Etienne en Devoluy
# Country?
France
# Improvements that need to be made?
New airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108597236-9e461080-734d-11eb-9e11-7e63a746c78c.png)
