### ISSUE TITLE
PACM-Scammon Bay-ALASKA-USA

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6639]
# Airport Name
Scammon Bay
# Country?
its the one with the eagles
# Improvements that need to be made?
i redid the airport because it was ugly
# Are you working on this airport?
yea
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108431822-0a6b2c00-7209-11eb-9ac1-7515e15fbff6.png)
