### ISSUE TITLE
EINN

### ISSUE THREAD

**Issue by chriscroft20** [InfiniteFlightAirportEditing/Airports#664]
redo of Shannon airport in Ireland

**Comment by chriscroft20** [comment]
sent for review

**Comment by dushyants19** [comment]
@chriscroft20 any developments?

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by moritzbabl** [comment]
I will edit this one

**Comment by moritzbabl** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21835322/c62e374c-d781-11e6-9e16-ebd6817a2ad7.png)
