### ISSUE TITLE
KARW-Beaufort Executive Airport-SOUTH CAROLINA-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6649]
![Full](https://user-images.githubusercontent.com/59462519/108157089-de9d5880-70d9-11eb-9f16-00613270d110.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108429414-911e0a00-7205-11eb-8c0d-ffdb206dfa59.png)
