### ISSUE TITLE
SDTS-Fazenda Planalto Airstrip-MATO GROSSO DO SUL-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#6650]
# Airport Name
Fazenda Planalto Airstrip
# Country?
Brazil
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108274719-e50fec80-713a-11eb-8206-ec6b0efa290f.png)
