### ISSUE TITLE
SSAY-Sitio Pouso Do Aviador Airport-MATO GROSSO DO SUL-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#6651]
# Airport Name
Sitio Pouso Do Aviador Airport
# Country?
Brazil
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108274361-661ab400-713a-11eb-8558-0e47de2d2107.png)
