### ISSUE TITLE
SIEF-Sao Jose Airstrip-MATO GROSSO DO SUL-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#6652]
# Airport Name
Fazenda Sao Jose Airstrip
# Country?
Brazil
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108272883-75006700-7138-11eb-9b46-eef9d8328fd2.png)
