### ISSUE TITLE
SNAR-Almenara Airport-MINAS GERAIS-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#6653]
# Airport Name
Almenara Airport
# Country?
Brazil
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108272364-be9c8200-7137-11eb-927f-0b4db7b4a449.png)
