### ISSUE TITLE
OSLK-Bassel Al-Assad Intl-LATTAKIA-SYRIA

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6654]
# Airport Name
Bassel Al-Assad Intl
# Country?
syria
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115125825-57ad1500-9f90-11eb-99db-463adfc195d7.png)
