### ISSUE TITLE
SWTO-Paraiso do Tocantins Airport-TOCANTINS-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#6655]
# Airport Name
Paraiso do Tocantins Airport
# Country?
Brazil
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108270850-9a3fa600-7135-11eb-9fb4-45acc6f80165.png)
