### ISSUE TITLE
F31-Lake Texoma State Park Airport-OKLAHOMA-USA

### ISSUE THREAD

**Issue by bbrockairbus** [InfiniteFlightAirportEditing/Airports#6657]
# Airport Name
Lake Texoma State Park Airport
# Country?
United States
# Improvements that need to be made?
Tie Downs/Parking Spots need to be added along with a realistic taxiway
# Are you working on this airport?
Yes!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111077006-d3f99780-84bc-11eb-9f1c-30cd93cfd954.png)
