### ISSUE TITLE
KASJ-Tri County Airport-NORTH CAROLINA-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6658]
![Full](https://user-images.githubusercontent.com/59462519/108294354-a48d8e80-718d-11eb-84e2-01902d53bf96.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108427867-68951080-7203-11eb-97c8-cd51ff0edbbc.png)
