### ISSUE TITLE
EGPD-Aberdeen Dyce Airport-SCOTLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by nmasterson** [InfiniteFlightAirportEditing/Airports#666]
assigned to me

**Comment by dushyants19** [comment]
@nmasterson How is the progress on this? Been 6 months!

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21746659/34a919e8-d512-11e6-9ad9-fab497ce8b88.png)

**Comment by ryu12332** [comment]
ISSUE: 124mtr runway extension at North end of runway (16 threshold) is missing and the associated taxiway. The runway extension was opened in 2011.
[IF IMAGE](https://drive.google.com/open?id=0B-auEAW0MM7ELVFMaU9xbXFoZG8)
[CHART IMAGE](https://drive.google.com/open?id=0B-auEAW0MM7EeFVhYVJnVFl0LW8)

**Comment by Tamz00** [comment]
This is a quick fix that I'll do by the end of today

**Comment by dushyants19** [comment]
![image](https://user-images.githubusercontent.com/13567007/34149929-ce5d5430-e4cc-11e7-9737-6af3f9394672.png)

**Comment by Tamz00** [comment]
Just assign me :roll_eyes:

**Comment by dushyants19** [comment]
turns out it was true

**Comment by Tamz00** [comment]
What happened there was that you didn’t add the ‘Being Redone’ label so I still have time.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34260254-da663cc4-e62a-11e7-9da2-6539ada3f843.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44620909-7bad0c80-a862-11e8-8f99-44ba9822833e.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/82476360-4b7cb700-9aa4-11ea-9df2-32af8df1dd8f.jpg)
