### ISSUE TITLE
63Y-Tyler Municipal-MINNESOTA-USA

### ISSUE THREAD

**Issue by Aceorbit** [InfiniteFlightAirportEditing/Airports#6660]
# Airport Name
Tyler Municipal Airprot
# Country?
USA
# Improvements that need to be made?
Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108595460-a00bd600-7345-11eb-8242-e0d2d22fd352.png)
