### ISSUE TITLE
KASY-Ashley Municipal Airport-NORTH DAKOTA-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6664]
![V1](https://user-images.githubusercontent.com/59462519/108455968-29001000-7267-11eb-9ad0-f1cacbb9edb4.png)

**Comment by kilt46** [comment]
![Uploading image.png…]()

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108598712-d13fd280-7354-11eb-8c41-045391d7de4c.png)
