### ISSUE TITLE
HCMH-Egal International Airport-MAROODI JEEX-SOMALILAND

### ISSUE THREAD

**Issue by dklaffke** [InfiniteFlightAirportEditing/Airports#6665]
# Airport Name
Hargeisa Egal Int'l Airport 
# Country?
Somaliland
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
12,139ft 06/24

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109238050-69e0b300-7798-11eb-9b34-ea70393bfd7e.png)
