### ISSUE TITLE
ENRO-Røros Airport-TRØNDELAG-NORWAY

### ISSUE THREAD

**Issue by JensSeverin** [InfiniteFlightAirportEditing/Airports#6666]
# Airport Name
Røros Airport
# Country?
Norway
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/125147596-f52c6680-e0f1-11eb-96cc-af185312193e.png)
