### ISSUE TITLE
HCMF-Bender Qassim International Airport-PUNTLAND-SOMALIA

### ISSUE THREAD

**Issue by dklaffke** [InfiniteFlightAirportEditing/Airports#6667]
# Airport Name
Bosaso Bender Qassim International Airport
# Country?
Somalia
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109389207-250c6780-78d1-11eb-9fd4-f4de791d4771.png)
