### ISSUE TITLE
Y58-Sleepy Eye Municipal-MINNESOTA-USA

### ISSUE THREAD

**Issue by Aceorbit** [InfiniteFlightAirportEditing/Airports#6668]
# Airport Name
Sleepy Eye Municipal
# Country?
USA
# Improvements that need to be made?
Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108595017-1529dc00-7343-11eb-9b58-666d9aac8780.png)
