### ISSUE TITLE
MY46-Hay Shakers-MINNESOTA-USA

### ISSUE THREAD

**Issue by Aceorbit** [InfiniteFlightAirportEditing/Airports#6669]
# Airport Name
Hay Shakers Airport
# Country?
USA
# Improvements that need to be made?
Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108594685-0b06de00-7341-11eb-95fa-b186f6bc4918.png)
