### ISSUE TITLE
LTAI-Antalya Airport-ANTALYA-TURKEY

### ISSUE THREAD

**Issue by turkish1941** [InfiniteFlightAirportEditing/Airports#667]
I will make this airport.

**Comment by Oguz8011** [comment]
Completed or still editing?

**Comment by turkish1941** [comment]
Completed but I am on vacation. Will send it in on sunday.

**Comment by Oguz8011** [comment]
Thank you bro. 

Eyvallah kardeş. Diğerlerini de yetiştirebilir misin? Yapabilirim dersen İzmir Ankara Antalya ve Sabiha Gökçen de iyi olurdu.

**Comment by turkish1941** [comment]
Tabi abi, Atatürk ve esenboğa yaptım. Eve gelince Izmir ve Sabiha G. once yaparım.

**Comment by NickArt1342** [comment]
Have you sent it in yet?

**Comment by henrikbg** [comment]
Approved.

**Comment by dushyants19** [comment]
Minor changes by Ilyas done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18332110/8c45e5b2-7529-11e6-8181-c9a82af98dc1.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18332113/93e87e7e-7529-11e6-83b4-d615390dd5dd.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18332116/9b834010-7529-11e6-8895-80a36d4ff128.png)

**Comment by MBeringuy** [comment]
Is it to reopen this issue or has this airport already been approved in the OR?

**Comment by liamkirky** [comment]
Sent for OR!

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/78673679-dde04700-78b8-11ea-8295-daacc2c8f8c8.jpg)
