### ISSUE TITLE
MN08-Eagles Nest Aerodrome-MINNESOTA-USA

### ISSUE THREAD

**Issue by Aceorbit** [InfiniteFlightAirportEditing/Airports#6670]
# Airport Name
Eagles Nest Aerodrome
# Country?
USA
# Improvements that need to be made?
New airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108594601-8e73ff80-7340-11eb-895d-97d419ef7b5b.png)
