### ISSUE TITLE
PAKW-Klawock Airport-ALASKA-USA

### ISSUE THREAD

**Issue by LesterXavier** [InfiniteFlightAirportEditing/Airports#6671]
# Airport Name
Klawock Airport
# Country?
U S A 🇺🇸 
# Improvements that need to be made?
Full rework
# Are you working on this airport?
Yep
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108626884-20027080-7418-11eb-8138-cc6108ea0b03.png)
