### ISSUE TITLE
UOOO-Norilsk-KRASNOYARSK-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6672]
# Airport Name
Norilsk Alykel
# Country?
Russia
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108920047-9f02cf00-75f9-11eb-899f-b5aebe3fbce0.png)
