### ISSUE TITLE
KAOO-Altoona-Blair County Airport-PENNSYLVANIA-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6673]
![Full](https://user-images.githubusercontent.com/59462519/108583718-8366a280-7333-11eb-8db2-526a447b2777.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108597753-55dc2200-7350-11eb-814c-c98327151a7c.png)
