### ISSUE TITLE
UACP-Petropavlovsk Airport-NORTH KAZAKHSTAN-KAZAKHSTAN

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6676]
# Airport Name
Petropavlovsk
# Country?
Kazakhstan
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes ma'am
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108625157-e842fb00-740e-11eb-8558-19f56ca8b303.png)
