### ISSUE TITLE
UACK-Kokshetau Airport-AQMOLA-KAZAKHSTAN

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6678]
# Airport Name
Kokshetau
# Country?
Kazakhstan
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108625014-17a53800-740e-11eb-8abe-2352f4689113.png)
