### ISSUE TITLE
LEIB-Ibiza Airport-ISLAS BALEARES-SPAIN

### ISSUE THREAD

**Issue by chriscroft20** [InfiniteFlightAirportEditing/Airports#668]
Redo of Ibiza Airport

**Comment by dushyants19** [comment]
Any progress on LEIB? @chriscroft20

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by lolo31r** [comment]
Being redone

**Comment by dushyants19** [comment]
assigned

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21500374/02fd2de2-cc04-11e6-9fad-d2cd2aae6276.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/49259852-a201bb80-f400-11e8-9133-b5f71c2683cd.png)

**Comment by kilt46** [comment]
Duplicate spawns removed

**Comment by Czechoslovaki** [comment]
Sent For OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/93001307-b474b880-f4f3-11ea-99de-a52c8fe0cc14.png)
