### ISSUE TITLE
UARR-Uralsk Airport-WEST KAZAKHSTAN-KAZAKHSTAN

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6681]
# Airport Name
Uralsk
# Country?
Kazakhstan
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108778812-917f1380-752b-11eb-8499-b53d7587be4a.png)
