### ISSUE TITLE
UATG-Atyrau Airport-ATYRAU-KAZAKHSTAN

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6683]
# Airport Name
Atyrau
# Country?
Kazakhstan
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108779141-0f431f00-752c-11eb-9b08-6d24a76a69d9.png)
