### ISSUE TITLE
UASZ-Zaysan Airport-EAST KAZAKHSTAN-KAZAKHSTAN

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6689]
# Airport Name
Zaysan
# Country?
Kazakstan
# Improvements that need to be made?
New
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Lower

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108778550-233a5100-752b-11eb-942a-03ade06f14a8.png)
