### ISSUE TITLE
EDJA- Memmingen Airport-BAYERN-GERMANY

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#669]
I will do this one

**Comment by moritzbabl** [comment]
Sent for approval some hours ago

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19417641/a60c486c-9377-11e6-9642-61a548186e75.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21984558/1574878c-dbbc-11e6-97ab-7daf07f43f83.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21984566/1fc7df40-dbbc-11e6-81a3-4251dc168ed5.png)

**Comment by moritzbabl** [comment]
WED measures Runways including displaced thresholds in the runway while the chart excludes them (the 200 at the bottom left may state the length of the dt. This explains the difference to the sat image, i will not change the runway in this case.
