### ISSUE TITLE
UASU-Urzhar Airport-EAST KAZAKHSTAN-KAZAKHSTAN

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6690]
# Airport Name
Urzhar
# Country?
Kazakhstan
# Improvements that need to be made?
New
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Even Lower

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108777831-0b160200-752a-11eb-89ba-926b37e79885.png)
