### ISSUE TITLE
UA33-Arkalyk North Airport-KOSTANAY-KAZAKHSTAN

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6691]
# Airport Name
Arkalyk North
# Country?
Kazakhstan
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Lower Than Ever

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108778116-85df1d00-752a-11eb-945b-44756cca241c.png)
