### ISSUE TITLE
UASP-Pavlodar Airport-PAVLODAR-KAZAKHSTAN

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6692]
# Airport Name
Pavlodar
# Country?
Kazakhstan
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Lower than zero

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108919530-c7d69480-75f8-11eb-8099-5f6fde6d3217.png)
