### ISSUE TITLE
KPHK-Palm Beach County Glades Airport-FLORIDA-USA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6693]
# Airport Name
Palm Beach Co. Glades Airport
# Country?
USA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109387650-3bfa8c00-78c8-11eb-8132-388138f436f4.png)
