### ISSUE TITLE
4S9-Mulino State Airport-OREGON-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#6694]
# Airport Name
Mulino State Airport
# Country?
USA
# Improvements that need to be made?
Full (Redo)
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109387531-86c7d400-78c7-11eb-9a8d-834f92a003e8.png)
