### ISSUE TITLE
UUBG-Sasovo-RYAZAN-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6695]
# Airport Name
Sasovo
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109080400-16059980-76c6-11eb-81ae-83938405cf82.png)
