### ISSUE TITLE
SAMI-San Martin-Chapelco Airport-NEUQUEN-ARGENTINA

### ISSUE THREAD

**Issue by IFsami** [InfiniteFlightAirportEditing/Airports#6697]
# Airport Name
San Martin-Chapelco Airport
# Country?
Argentina
# Improvements that need to be made?
Full rework
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109389101-86800680-78d0-11eb-8dd3-ffb0a5c12988.png)
