### ISSUE TITLE
KCUL-Carmi Muni-ILLINOIS-USA

### ISSUE THREAD

**Issue by Saharsh1234** [InfiniteFlightAirportEditing/Airports#6698]
# Airport Name
Carmi Muni
# Country?
USA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109387141-2c2d7880-78c5-11eb-932b-1fcbb1a12fa0.png)
