### ISSUE TITLE
HKML-Malindi Airport-KILIFI-KENYA

### ISSUE THREAD

**Issue by dklaffke** [InfiniteFlightAirportEditing/Airports#6699]
# Airport Name
Malindi Airport
# Country?
Kenya
# Improvements that need to be made?
Full rework
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109386431-2719fa80-78c0-11eb-9ced-929facb05b0a.png)
