### ISSUE TITLE
KNFG

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#67]

**Comment by carmichaelalonso** [comment]
Redone by @JcFl4.

**Comment by kilt46** [comment]
Reworking buildings

**Comment by kilt46** [comment]
Airport fully offset. overlapping taxiways. Full rewrite.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20041896/d40612f6-a435-11e6-8732-7c683816b703.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/49334093-36e7ee80-f592-11e8-9891-cdfc2d81ad16.png)

**Comment by kilt46** [comment]
Buildings removed. Duplicate spawn removed
