### ISSUE TITLE
EDMO - OBERPFAFFENHOFEN

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#670]
I'll do that

**Comment by moritzbabl** [comment]
Just sent for approval

**Comment by moritzbabl** [comment]
The Airport has been approved

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18608147/e393cc60-7ca6-11e6-9268-309642286552.png)
