### ISSUE TITLE
HKUK-Ukunda Airport-KWALE-KENYA

### ISSUE THREAD

**Issue by dklaffke** [InfiniteFlightAirportEditing/Airports#6700]
# Airport Name
Ukunda Airport
# Country?
Kenya
# Improvements that need to be made?
Full rework
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109386336-a3f8a480-78bf-11eb-8eb3-4719dfa32a6a.png)
