### ISSUE TITLE
OYSQ-Socotra International-HADRAMAWT-YEMEN

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#6702]
![OYSQ-git](https://user-images.githubusercontent.com/26853210/109024306-8526c200-76b5-11eb-9ff3-5696d80485ce.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109079100-0dac5f00-76c4-11eb-8b97-294d1b151b4d.png)
