### ISSUE TITLE
UA34-Chardara Airport-SOUTH KAZAKHSTAN-KAZAKHSTAN

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6703]
# Airport Name
Chardara
# Country?
Kazakhstan
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109077576-01270700-76c2-11eb-851d-64efe33c6bfd.png)
