### ISSUE TITLE
OI03-Garmac SW Airport-SEMNAN-IRAN

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6704]
![Full](https://user-images.githubusercontent.com/59462519/109072025-6132a300-76ec-11eb-955c-2e77367bef7f.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109078551-26684500-76c3-11eb-89f2-8fb591104462.png)
