### ISSUE TITLE
UATE-Aktau Airport-MANGYSTAU-KAZAKHSTAN

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6705]
# Airport Name
Aktau
# Country?
Kazakhstan
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
10k

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109231275-df925200-778b-11eb-9f60-e59e02257767.png)
