### ISSUE TITLE
KAUN-Auburn Municipal Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6706]
# Airport Name
Auburn Municipal Airport 
# Country?
USA
# Improvements that need to be made?
Manual edit
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109419468-3ae26100-7993-11eb-868a-4a52b8c4d145.png)
