### ISSUE TITLE
FGAB-Annobón-SAN ANTONIO DE PALÉ-EQUATORIAL GUINEA

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6707]
# Airport Name
Annobón
# Country?
equatorial guinea
# Improvements that need to be made?
scratch
# Are you working on this airport?
yea
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by feitidede** [comment]
# Airport Name
Annobón Airport

# Country?
equatorial guinea

# Improvements that need to be made?
scratch

# Are you working on this airport?
yea

# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109391078-f1363f80-78da-11eb-9fb1-a0831fd463c8.png)
