### ISSUE TITLE
KPMZ-Plymouth Municipal Airport-NORTH CAROLINA-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#6708]
# Airport Name
Plymouth Municipal Airport
# Country?
USA
# Improvements that need to be made?
Full (Redo)
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109386613-63018f80-78c1-11eb-92c8-966791a715bc.png)
