### ISSUE TITLE
OIZS-Saravan Airport-SISTAN VA BALUCHESTAN-IRAN

### ISSUE THREAD

**Issue by dklaffke** [InfiniteFlightAirportEditing/Airports#6709]
# Airport Name
Saravan Airport
# Country?
Iran
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by ECoops-123** [comment]
I can't assign you as you currently are assigned to 3 issues. This will be your next one if no one does take it.

**Comment by dklaffke** [comment]
I just sent one to OR so i should be able to work on this soon

**Comment by MajorTomMueller** [comment]
Should be is not be. 
send to OR is not accepted and in the repository. 
there is a Ling lasting experience for not closing a issue before OR has finally accepted the send data.

**Comment by ECoops-123** [comment]
> I just sent one to OR so i should be able to work on this soon

@MajorTomMueller I believe they mean they have sent another assigned airport to OR not realizing they already had 3 issues.

**Comment by dklaffke** [comment]
Now you can assign me 😀

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109386023-7ad71480-78bd-11eb-89ef-3ef6d4f9a052.png)
