### ISSUE TITLE
LFEC-Ouessant-BRETAGNE-FRANCE

### ISSUE THREAD

**Issue by Jeremy351** [InfiniteFlightAirportEditing/Airports#6710]
# Airport Name
Ouessant
# Country?
France
# Improvements that need to be made?
Full redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109386235-f9808180-78be-11eb-8141-bfdec5638bd2.png)
