### ISSUE TITLE
UAKD-Zhezkazgan Airport-KARAGANDY-KAZAKHSTAN

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6714]
# Airport Name
Zhezkazgan
# Country?
Kazakhstan
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109238409-1cb11100-7799-11eb-9908-360b0be38a38.png)
