### ISSUE TITLE
UAOO-Kyzylorda Airport-KYZYLORDA-KAZAKHSTAN

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6715]
# Airport Name
Kyzylorda
# Country?
Kazakhstan
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109365022-c8b83200-7855-11eb-8697-b8e109849512.png)
