### ISSUE TITLE
05U-Eureka Airport-NEVADA-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#6716]
# Airport Name
Eureka Airport
# Country?
USA
# Improvements that need to be made?
Full(Redo)
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109386523-c7701f00-78c0-11eb-8f21-0b1e1c2d2fbb.png)
