### ISSUE TITLE
LFSS-Saint Sulpice-ILLE ET VILAINE-FRANCE 

### ISSUE THREAD

**Issue by Jeremy351** [InfiniteFlightAirportEditing/Airports#6717]
# Airport Name
Saint Sulpice Des Landes
# Country?
France
# Improvements that need to be made?
Full redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by MajorTomMueller** [comment]
![LFSS-git](https://user-images.githubusercontent.com/26853210/132132200-bbdc2ad0-20a5-4158-9f24-e4ced021ef09.png)
