### ISSUE TITLE
ZWSH-Kashgar Airport-XINJIANG-CHINA

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6718]
# Airport Name
Kashgar Airport
# Country?
chinaa
# Improvements that need to be made?
redo i think
# Are you working on this airport?
i kinda am actually
# Airport Priority? (10000ft+ Runway, Low)
10000ft+ Runway

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109386128-49ab1400-78be-11eb-9f24-3fe444733f87.png)
