### ISSUE TITLE
KPJY-Pinckneyville-Du Quoin Airport-ILLINOIS-USA

### ISSUE THREAD

**Issue by Saharsh1234** [InfiniteFlightAirportEditing/Airports#6719]
# Airport Name
Pinckneyville-Du Quoin Airport
# Country?
USA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Ye
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/110248427-abaaef80-7f36-11eb-9aae-9a588e24d89b.png)
