### ISSUE TITLE
EDDT-Berlin Tegel Airport-BERLIN-GERMANY

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#672]
Berlin Tegel

**Comment by thomasbevan97** [comment]
what happened?

**Comment by kilt46** [comment]
Reworking issue!

**Comment by kilt46** [comment]
Done from scratch

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20249269/963f31ba-a9bb-11e6-9d02-df596503551a.png)

**Comment by ryu12332** [comment]
ISSUE: I landed on 26R and a taxiway is missing. (the one to enter 26L)
[IF IMAGE](https://drive.google.com/open?id=0B2T-CJjgFqjIMUFpQlJNZmptdGc)
[SAT IMAGE](https://drive.google.com/open?id=0B2T-CJjgFqjIc1JpaUFiSnhkZjg)

**Comment by brunocr98** [comment]
I see why, someone set the taxiway to be transparent. I'll be committing the changes shortly.

**Comment by ryu12332** [comment]
ISSUE: Taxiway pavement between the threshold of 26R & 26L missing. Markings are present
[IF IMAGE](https://drive.google.com/open?id=19fmYO_uA5kTmVphYxIcWKHIaX5cIf6Xh)

**Comment by brunocr98** [comment]
This problem has been fixed already!

**Comment by kilt46** [comment]
Airport review. Missing asphalt taxiways

**Comment by moritzbabl** [comment]
If I’m not wrong it’s also missing some pavement parts for roads, only the markings are there

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/42736739-bfd3a9ac-8830-11e8-8bad-944be5286134.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/76917702-f7d2cf00-68a2-11ea-920e-69c5c398cfe8.jpg)
