### ISSUE TITLE
0CD5-Pinon Canyon Airport-COLORADO-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#6720]
# Airport Name
Pinon Canyon Airport
# Country?
USA
# Improvements that need to be made?
added to IF
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109365879-bccd6f80-7857-11eb-9048-f13c6f1a3667.png)
