### ISSUE TITLE
USPP-Perm/Bolshoe Savino Airport-PERM-RUSSIA

### ISSUE THREAD

**Issue by tsarkov90** [InfiniteFlightAirportEditing/Airports#6721]
# Airport Name
Perm / Bolshoe Savino
# Country?
Russia
# Improvements that need to be made?
Redo from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Bravo

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/128280658-e6d03975-8ec3-4e65-be1f-cb93b047d44a.png)
