### ISSUE TITLE
UASB-Ekibastuz Airport-KAZAKHSTAN

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6722]
# Airport Name
Ekibastuz
# Country?
Kazakhstan
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109364820-429beb80-7855-11eb-99c5-56d52aff3781.png)
