### ISSUE TITLE
0CD7-Fox Hole Airport-COLORADO-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#6723]
# Airport Name
Fox Hole
# Country?
USA
# Improvements that need to be made?
added to IF
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109366514-387bec00-7859-11eb-85bb-778a06b0e96c.png)
