### ISSUE TITLE
OIZJ-Jask Airport-HORMOZGAN-IRAN

### ISSUE THREAD

**Issue by dklaffke** [InfiniteFlightAirportEditing/Airports#6727]
# Airport Name
Jask Airport
# Country?
Iran
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/110226506-9f328280-7eb5-11eb-97e1-e5699f183308.png)
