### ISSUE TITLE
OIZI-Iran Shahr Airport-SISTAN VA BALUCHESTAN-IRAN

### ISSUE THREAD

**Issue by dklaffke** [InfiniteFlightAirportEditing/Airports#6728]
# Airport Name
Iran Shahr Airport
# Country?
Iran
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109726489-725e3280-7b78-11eb-9b50-7470f1635fde.png)
