### ISSUE TITLE
OIZB-Zabol Airport-SISTAN VA BALUCHESTAN-IRAN

### ISSUE THREAD

**Issue by dklaffke** [InfiniteFlightAirportEditing/Airports#6729]
# Airport Name
Zabol Airport
# Country?
Iran
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109726149-cd435a00-7b77-11eb-9b5c-d29923b8b1c5.png)
