### ISSUE TITLE
HAJM-Jimma/Aba Jifar Airport-OROMIA-ETHIOPIA

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#673]
PLEASE REUSE ME.

**Comment by brunocr98** [comment]
The airport has 2 ICAO codes, and it has been done already in #439.

https://en.wikipedia.org/wiki/EuroAirport_Basel_Mulhouse_Freiburg

**Comment by dushyants19** [comment]
Invalid. EuroAirport Basel Mulhouse already has an issue #439

**Comment by bavAVIA** [comment]
Recycled. Taking over soon.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27262809-0b92c57c-5424-11e7-9e8a-a70cf218e691.png)

**Comment by bavAVIA** [comment]
![screenshot 743](https://user-images.githubusercontent.com/19326264/27262818-e32bcd1e-545e-11e7-842d-894dc08107c2.png)

Skyvector is outdated.

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27716626-4da3d3fe-5d05-11e7-9fe2-1c514df91587.png)
