### ISSUE TITLE
ENSO-Stord Sørstokken Airport-VESTLAND-NORWAY

### ISSUE THREAD

**Issue by Daniboi737** [InfiniteFlightAirportEditing/Airports#6730]
# Airport Name
Stord Sørstokken
# Country?
Norway
# Improvements that need to be made?
Redone from Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by Daniboi737** [comment]
Sent to OR!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/110188180-7f7d5a80-7de0-11eb-968d-b7b11dcfe394.png)
