### ISSUE TITLE
ZBHD-Handan Airport-HEBEI-CHINA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6731]
# Airport Name
Handan Airport
# Country?
China
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109885155-ace0d180-7c43-11eb-87b9-cf094bc6e7d4.png)
