### ISSUE TITLE
PAHL-Huslia Airport-ALASKA-USA

### ISSUE THREAD

**Issue by zhf21** [InfiniteFlightAirportEditing/Airports#6732]
# Airport Name
PAHL
# Country?
U.S. of A
# Improvements that need to be made?
The current airport is 💩, so redo
# Are you working on this airport?
If I get approved, yes
# Airport Priority? (10000ft+ Runway, Low)
Absolutely not

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109893209-dbb17480-7c50-11eb-8ad5-ff90ad4602cc.png)
