### ISSUE TITLE
ZUNZ-Nyingchi Mainlin-TIBET AUTONOMOUS REGION-CHINA

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6734]
# Airport name

Nyingchi Mainlin

# Country

china

# Improvements

redo

# Are you working on this airport

i will be once i get home

# Priority

low

**Comment by StickThelanding** [comment]
can I take this Airport

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/128636235-76f564fc-65af-4dd9-ad93-946cdeb789a3.png)
