### ISSUE TITLE
UAAH-Balkhash Airport-KARAGANDY-KAZAKHSTAN

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6736]
# Airport Name
Balkhash
# Country?
Kazakhstan
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
( ͡° ͜ʖ ͡°)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109887747-ea475e00-7c47-11eb-86ff-039cca454aad.png)
