### ISSUE TITLE
0CO2-Crested Butte Airpark-COLORADO-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#6738]
# Airport Name
Crested Butte Airpark
# Country?
USA
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109893653-a8231a00-7c51-11eb-9a2f-4861ab972a32.png)
