### ISSUE TITLE
KHPT-Hampton Municipal Airport-IOWA-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#6740]
# Airport Name
Hampton Municipal Airport
# Country?
USA
# Improvements that need to be made?
Full (Redo)
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109728546-067dc900-7b7c-11eb-9d79-b65c6b5a6188.png)
