### ISSUE TITLE
ENUL-Os Vaksinen Ulve Airport-VESTLAND-NORWAY

### ISSUE THREAD

**Issue by Daniboi737** [InfiniteFlightAirportEditing/Airports#6743]
# Airport Name
Os Vaksinen Ulve
# Country?
Norway
# Improvements that need to be made?
Adding it to the sim
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111003397-adb4ea00-834c-11eb-8cb6-a3583507bf99.png)
