### ISSUE TITLE
VIAH-Aligarh Airport-UTTAR PRADESH-India

### ISSUE THREAD

**Issue by KaalicharanDH** [InfiniteFlightAirportEditing/Airports#6752]
# Airport Name
Aligarh Airport
# Country?
India
# Improvements that need to be made?
Needs to be added
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109888579-51194700-7c49-11eb-8e4b-6adc7e9cec69.png)
