### ISSUE TITLE
KLZU-Gwinnett County Airport Briscoe Field-Georgia-USA

### ISSUE THREAD

**Issue by Captainflight** [InfiniteFlightAirportEditing/Airports#6753]
# Airport Name
Gwinnett County Airport Briscoe Field
# Country?
USA
# Improvements that need to be made?
Rework from scratch 
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by ECoops-123** [comment]
Editor is giving up the airport to have a life.... traitor!!

**Comment by MajorTomMueller** [comment]
Hope that's your acount Fajita / @IFsami

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124367252-281aba00-dc1b-11eb-97da-a6fb2949509e.png)
