### ISSUE TITLE
KHAE-Hannibal Regional Airport-MISSOURI-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#6755]
# Airport Name
Hannibal Regional Airport
# Country?
USA
# Improvements that need to be made?
Full (Redo)
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/110207955-dff5b180-7e4b-11eb-8ebd-542ee015f4cf.png)
