### ISSUE TITLE
OIBJ-Jam Airport-BUSHEHR-IRAN

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6758]
mmmmh, jaaaamm

![Full](https://user-images.githubusercontent.com/59462519/109629401-af580400-7b3b-11eb-9313-e5792a5fc331.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109725200-6b362500-7b76-11eb-9b70-75a626da88e6.png)
