### ISSUE TITLE
OITZ-Zanjan Airport-ZANJAN-IRAN

### ISSUE THREAD

**Issue by dklaffke** [InfiniteFlightAirportEditing/Airports#6759]
# Airport Name
Zanjan Airport
# Country?
Iran
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Sí
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113456119-fef74d00-93d1-11eb-97fa-49d2b5d5c924.png)
