### ISSUE TITLE
OITT-Tabriz International Airport-EAST AZERBAIJAN-IRAN

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#6760]
# Airport Name
Tabriz International Airport
# Country?
Iran
# Improvements that need to be made?
Autogen so Full Redo
# Are you working on this airport?
Very much so indeeeed
# Airport Priority? (10000ft+ Runway, Low)
12L/30R | 11,995ft, 12R/30L | 11,537ft

**Comment by KaalicharanDH** [comment]
May i do it?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/119908333-f1fd6280-bf17-11eb-9b3c-663a4d1f4e8a.png)
