### ISSUE TITLE
OIBL-Bandar Lengeh Airport-HORMOZGAN-IRAN

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6761]
![Full](https://user-images.githubusercontent.com/59462519/109654025-9eb68680-7b59-11eb-88a0-9f8a16601472.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109724903-ee0ab000-7b75-11eb-9c4b-e793ca8a978c.png)
