### ISSUE TITLE
PABL-Buckland Airport-ALASKA-USA 

### ISSUE THREAD

**Issue by zhf21** [InfiniteFlightAirportEditing/Airports#6762]
# Airport Name
PABL
# Country?
‘merica
# Improvements that need to be made?
💩 -> less 💩
# Are you working on this airport?
You tell me
# Airport Priority? (10000ft+ Runway, Low)
Negative 0

**Comment by ECoops-123** [comment]
> # Are you working on this airport?
> You tell me

You are now! 😋

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/110038708-b9c5f980-7d05-11eb-9f50-56d791f71fd6.png)
