### ISSUE TITLE
OYSY-Seiyun Hadhramaut Airport-HADHRAMAUT-YEMEN

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6763]
# Airport Name
Seiyun Hadhramaut Airport
# Country?
Yemen
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
smol

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109891085-0ea63900-7c4e-11eb-98e9-f359b180acfb.png)
