### ISSUE TITLE
KJYO-Leesburg Executive Airport-VIRGINIA-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#6764]
# Airport Name
Leesburg Executive Airport
# Country?
USA
# Improvements that need to be made?
Full (Redo)
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/110242294-0b939d00-7f1b-11eb-8b05-9367c7c70e45.png)
