### ISSUE TITLE
X13-Carrabelle Thompson Airport-FLORIDA-USA

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6768]
# Airport Name
Carrabelle Thompson Airport
# Country?
USA
# Improvements that need to be made?
redo
# Are you working on this airport?
yea
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/110040593-aff1c580-7d08-11eb-9161-f3fa11b7e19a.png)
