### ISSUE TITLE
UASK-Ust-Kamenogorsk Airport-EAST KAZAHKSTAN-KAZAKHSTAN

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6770]
# Airport Name
Use-kamenogorsk
# Country?
Kazakhstan
# Improvements that need to be made?
Glorify The Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![Uploading image.png…]()
