### ISSUE TITLE
PFNO-Robert (Bob) Curtis Memorial Airport-ALASKA-USA

### ISSUE THREAD

**Issue by zhf21** [InfiniteFlightAirportEditing/Airports#6771]
# Airport Name
PFNO
# Country?
Estados Unidos
# Improvements that need to be made?
Hmm. Not sure. I can make it work, though
# Are you working on this airport?
If you allow me to
# Airport Priority? (10000ft+ Runway, Low)
0️⃣

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/110039103-5c7e7800-7d06-11eb-8523-ef10ff5d77ce.png)
