### ISSUE TITLE
ENFL-Florø Airport-VESTLAND-NORWAY

### ISSUE THREAD

**Issue by Daniboi737** [InfiniteFlightAirportEditing/Airports#6773]
# Airport Name
Florø Airport
# Country?
Norway
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113455876-5b0da180-93d1-11eb-9598-77fa9f6f7e61.png)
