### ISSUE TITLE
PASH-Shishmaref Airport-ALASKA-USA

### ISSUE THREAD

**Issue by zhf21** [InfiniteFlightAirportEditing/Airports#6774]
# Airport Name
PASH
# Country?
U.S.A.
# Improvements that need to be made?
Redo (autogen)
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/110208079-b0937480-7e4c-11eb-8664-156528333d59.png)
