### ISSUE TITLE
KBIJ-Early County Airport-GEORGIA-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#6775]
# Airport Name
Early County Airport
# Country?
USA
# Improvements that need to be made?
Full (Redo)
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111087387-5733e100-84ef-11eb-9195-51e01d58684a.png)
