### ISSUE TITLE
SSKJ-Pau Dos Ferros Airport-RIO GRANDE DO NORTE-BRAZIL

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Airports#6778]
# Airport Name
Pau dos Ferros
# Country?
Brazil
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113359147-ca6d8d80-930c-11eb-9a9e-4bf14504f8b3.png)
