### ISSUE TITLE
LGAV-Athens Eleftherios Venizelos Airport-ATTIKI-GREECE

### ISSUE THREAD

**Issue by chriscroft20** [InfiniteFlightAirportEditing/Airports#678]
Athens Eleftherios Venizelos Airport redo

**Comment by PaulNielsen** [comment]
I talked to @chriscroft20 some time ago, he told me he isn't doing Athens LGAV anymore, so this one is up for grabs!

**Comment by brunocr98** [comment]
I'm adopting this airport 😇

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20043702/b95b5fee-a456-11e6-8ee2-e7d8d9033907.png)
![image](https://cloud.githubusercontent.com/assets/14023167/20043708/cb3c0efc-a456-11e6-823c-128f43cf6dca.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56665318-6bf2fb80-666f-11e9-8f41-07435f6439fb.png)
