### ISSUE TITLE
KAVC-Mecklenburg Brunswick Regional-VIRGINIA-USA

### ISSUE THREAD

**Issue by Saharsh1234** [InfiniteFlightAirportEditing/Airports#6780]
# Airport Name
Mecklenburg Brunswick Regional
# Country?
USA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yep
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111087269-b5ac8f80-84ee-11eb-8abb-eb6329058d3a.png)
