### ISSUE TITLE
2RR-River Ranch Resort-FLORIDA-USA

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6787]
# Airport Name
River Ranch Resort
# Country?
usa
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/110242186-827c6600-7f1a-11eb-84e4-dca82fdc7efd.png)
