### ISSUE TITLE
KPYN-Piedmont Municipal Airport-MISSOURI-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#6788]
# Airport Name
Piedmont Municipal Airport
# Country?
USA
# Improvements that need to be made?
Full (Redo)
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/110396163-20645380-8035-11eb-9493-29725254dc8d.png)
