### ISSUE TITLE
FVBU-Bulawayo Joshua Nkomo Airport-MATABELELAND-ZIMBABWE

### ISSUE THREAD

**Issue by planemadnews** [InfiniteFlightAirportEditing/Airports#679]
I am editing Bulawayo now

**Comment by planemadnews** [comment]
Sent for Review

**Comment by kilt46** [comment]
This requires a few more spawn points. 
![image](https://cloud.githubusercontent.com/assets/14023167/16356640/23f42bd6-3aa5-11e6-9d73-91ba19546f41.png)
Also consider making from one large apron and cutting holes in it. Many joins which can lead to gaps
![image](https://cloud.githubusercontent.com/assets/14023167/16356641/3783a88e-3aa5-11e6-8786-e34dab69e261.png)

**Comment by kilt46** [comment]
Buildings added and Hangar spawn points

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19414028/869f9004-9306-11e6-96da-e5be2ef8ac48.png)
