### ISSUE TITLE
PAPB-St. George Airport-ALASKA-USA

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6792]
# Airport Name
St. George Airport
# Country?
USA
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/110397326-47bc2000-8037-11eb-967f-776429676f07.png)
