### ISSUE TITLE
SNKN-Currais Novos Airport-RIO GRANDE DO NORTE-BRAZIL

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Airports#6799]
# Airport Name
Currais Novos
# Country?
Brazil
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113358842-24ba1e80-930c-11eb-9ccf-25cf506aafc5.png)
