### ISSUE TITLE
KAUW-Wausau Downtown Airport-WISCONSIN-USA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6800]
![Full](https://user-images.githubusercontent.com/59462519/110257363-7f728b80-7f95-11eb-88ff-36d4ed1322d8.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/110396746-29a1f000-8036-11eb-952a-377ca812f5d2.png)
