### ISSUE TITLE
LFLK-Arbent Airport-RHONE-ALPS-FRANCE

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#6801]
# Airport Name
Arbent Airport
# Country?
France
# Improvements that need to be made?
Full (Redo)
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by ShaneAviation** [comment]
Whoops, this would be my fourth. Sorry!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111028801-b2b28180-83be-11eb-85fe-3c4925210139.png)
