### ISSUE TITLE
KEZI-Kewanee Municipal Airport-ILLINOIS-USA

### ISSUE THREAD

**Issue by LawinS** [InfiniteFlightAirportEditing/Airports#6802]
# Airport Name
Kewanee Municipal Airport

# Country?
USA

# Improvements that need to be made?
Full redo

# Are you working on this airport?
Yes

# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113068994-0a096d80-9185-11eb-9ec5-1e52d907989f.png)
