### ISSUE TITLE
VRBK-Kulhudhuffushi Airport-HAA DHAALU-MALDIVES

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6803]
# Airport Name
Kulhudhuffushi
# Country?
maldives
# Improvements that need to be made?
scratch
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![Uploading image.png…]()
