### ISSUE TITLE
UTAV-Turkmenabat-LEBAP-TURKMENISTAN

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6805]
# Airport Name
Turkmenobat
# Country?
Turkmenistan
# Improvements that need to be made?
from scratch
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
13/31 - 12'467ft

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111557966-c4e44500-875b-11eb-9baf-b2378b21a7f5.png)
