### ISSUE TITLE
KEOE-Newberry County Airport-SOUTH CAROLINA-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#6806]
# Airport Name
Newberry County Airport
# Country?
USA
# Improvements that need to be made?
Old ICAO = 27J, will be updated to KEOE. Doing a full redo on it.
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111087130-d1636600-84ed-11eb-925e-d68a1602bb0d.png)
