### ISSUE TITLE
UADD-Taraz Airport-JAMBYL-KAZAKHSTAN

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6808]
# Airport Name
Taraz
# Country?
Kazakhstan
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
10k

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111029814-56526080-83c4-11eb-91f5-20121fd406c5.png)
