### ISSUE TITLE
KFIN-Flagler Executive Airport-FLORIDA-USA

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6809]
# Airport Name
Flagler Executive Airport
# Country?
usa
# Improvements that need to be made?
redo
# Are you working on this airport?
yea
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111082742-d0bfd500-84d7-11eb-8032-7003d75e7a72.png)
