### ISSUE TITLE
LEVF-Villaframil Airport-GALICIA-SPAIN

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6812]
# Airport Name
Villaframil Airport
# Country?
Spain
# Improvements that need to be made?
Redo
# Are you working on this airport?
Sí
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/110555338-080e3a80-8102-11eb-8da5-cac24d6173db.png)
