### ISSUE TITLE
LEVB-El Carrascal Airport-CASTILLA Y LEÓN-SPAIN

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6813]
# Airport Name
El Carrascal Airport
# Country?
Spain
# Improvements that need to be made?
Redo
# Are you working on this airport?
Sí
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/110556192-a18a1c00-8103-11eb-9d4e-7085687f053b.png)
