### ISSUE TITLE
KCFT-Greenlee County Airport-ARIZONA-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#6815]
# Airport Name
Greenlee County Airport
# Country?
USA
# Improvements that need to be made?
Full (Redo)
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111083345-1df17600-84db-11eb-83de-c490ad50b9e6.png)
