### ISSUE TITLE
LETP-Santo Tomé del Puerto-CASTILLA Y LEÓN-SPAIN

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6816]
# Airport Name
Santo Tomé del Puerto
# Country?
Spain
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/110719101-dbc1ef00-81d1-11eb-8d39-ef73b5c799f2.png)
