### ISSUE TITLE
LETI-El Tietar Airport-CASTILLA LA MANCHA-SPAIN

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6817]
# Airport Name
El Tietar Airport
# Country?
Spain
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/110717967-b6cc7c80-81cf-11eb-9840-c838e2a405da.png)
