### ISSUE TITLE
PAKH-Akhiok Aiport-ALASKA-USA

### ISSUE THREAD

**Issue by zhf21** [InfiniteFlightAirportEditing/Airports#6823]
# Airport Name
PAKH
# Country?
America
# Improvements that need to be made?
Redo (autogen)
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111083217-6197b000-84da-11eb-8196-babef1ebd54b.png)
