### ISSUE TITLE
UMBB-Brest Airport-BREST-BELARUS

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6824]
# Airport Name
Brest Airport
# Country?
Belarus
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111028971-c3172c00-83bf-11eb-90b4-966dda744fc3.png)
