### ISSUE TITLE
UMBK-Borisovo Air Base-BREST-BELARUS

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6825]
# Airport Name
Borisovo Air Base
# Country?
Belarus
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111029257-6583df00-83c1-11eb-89b2-bdde34cbc94b.png)
