### ISSUE TITLE
UMDD-Lida Air Base-GRODNO-BELARUS

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#6826]
# Airport Name
Lida Air Base
# Country?
Belarus
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111870808-d04e9080-8954-11eb-8256-81848968442e.png)
