### ISSUE TITLE
KCRG-Jacksonville Executive Airport at Craig-FLORIDA-USA

### ISSUE THREAD

**Issue by LesterXavier** [InfiniteFlightAirportEditing/Airports#6827]
# Airport Name
Jacksonville Executive Airport at Craig
# Country?
USA 🇺🇸 
# Improvements that need to be made?
rework from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113452370-72e12780-93c9-11eb-8f44-4d2c4b4ef79b.png)
