### ISSUE TITLE
OE46-Al Lidem-KHAMASEEN-SAUDI ARABIA

### ISSUE THREAD

**Issue by suhasjatla** [InfiniteFlightAirportEditing/Airports#6829]
# Airport Name
Al Lidem
# Country?
Saudi Arabia
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111029609-379f9a00-83c3-11eb-82b8-15d381d794f1.png)
