### ISSUE TITLE
LE85-Tablada Airport-ANDALUCÍA-SPAIN

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6830]
# Airport Name
Tablada Airport
# Country?
Spain
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/110716373-a961c300-81cc-11eb-8415-546f1f00fc82.png)
