### ISSUE TITLE
LE96-Albalat 2 Airport-COMUNIDAD VALENCIANA-SPAIN

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6831]
# Airport Name
Albalat 2
# Country?
Spain
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/110716050-001acd00-81cc-11eb-9af5-029bc852a9d1.png)
