### ISSUE TITLE
LE98-Alcocer Airport-COMUNIDAD VALENCIANA-SPAIN

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6832]
# Airport Name
Alcocer Airport
# Country?
Spain
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/110715604-30ae3700-81cb-11eb-892b-b445d37c70de.png)
