### ISSUE TITLE
UAKK-Karaganda Airport-KARAGANDY-KAZAKHSTAN

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6833]
# Airport Name
Karaganda
# Country?
Kazakhstan
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
10k

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111029911-f4462b00-83c4-11eb-9067-6f4b4760fb7c.png)
