### ISSUE TITLE
LE99-Balica Airport-COMUNIDAD VALENCIANA-SPAIN

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6834]
# Airport Name
Balica Airport
# Country?
Spain
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111030905-68370200-83ca-11eb-9595-6c82f534bae8.png)
