### ISSUE TITLE
LEAP-Empuriabrava Airport-CATALUÑA-SPAIN

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6835]
# Airport Name
Empuriabrava Airport
# Country?
Spain
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111031008-00cd8200-83cb-11eb-8bd5-8eb6cf153c46.png)
