### ISSUE TITLE
OEKJ-Al-Kharj-AL-KHARJ-SAUDI ARABIA

### ISSUE THREAD

**Issue by suhasjatla** [InfiniteFlightAirportEditing/Airports#6836]
# Airport Name
Al-Kharj 
# Country?
Saudi Arabia
# Improvements that need to be made?
Redo, Airport Name change (Previously OE47, renamed to OEKJ)
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112060404-29701d00-8b2b-11eb-898c-f513771f7fb5.png)
