### ISSUE TITLE
LEAX-La Axarquía Leoni Benabu Airport-CATALUÑA-SPAIN

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6837]
# Airport Name
La Axarquía Leoni Benabu Airport
# Country?
Spain
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111031193-dc25da00-83cb-11eb-9c60-e2d5e102b141.png)
