### ISSUE TITLE
FZAA-Kinshasa-N'Djili Airport-KINSHASA-DR CONGO

### ISSUE THREAD

**Issue by planemadnews** [InfiniteFlightAirportEditing/Airports#684]
Reused

**Comment by TristinWoolf** [comment]
I can do this one!

**Comment by TristinWoolf** [comment]
Sent in for approval.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19418097/8dcfe122-9382-11e6-985c-31ff53bc54fb.png)
