### ISSUE TITLE
OE48-Quz South-AL QOUZ-SAUDI ARABIA

### ISSUE THREAD

**Issue by suhasjatla** [InfiniteFlightAirportEditing/Airports#6840]
# Airport Name
Quz South
# Country?
Saudi Arabia
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111029718-beed0d80-83c3-11eb-88c1-91d9ecd3b12d.png)
