### ISSUE TITLE
OOJA-Ja'Aluni-AL WUSTA-OMAN

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#6845]
![OOJA-git](https://user-images.githubusercontent.com/26853210/110798772-65c19480-8272-11eb-8410-e851fc8f78fd.png)

**Comment by MajorTomMueller** [comment]
https://github.com/InfiniteFlightAirportEditing/Airports/commit/cc7c4c235f841e2104d597c5da02e18196a34720

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/110875520-6589bf00-829b-11eb-822d-930d4246d09e.png)

**Comment by MajorTomMueller** [comment]
fixed
