### ISSUE TITLE
HAAB-Bole Airport-ADDIS ABABA-ETHIOPIA

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#685]
To be redone - I am happy to redo it

**Comment by JcFl4** [comment]
Too late again... lol

**Comment by JcFl4** [comment]
I might in the future, only if no one else offers, as I have enough to do already!

**Comment by dushyants19** [comment]
@JcFl4 welcome to take this anytime

**Comment by JcFl4** [comment]
Perfect, I will as soon as I finish some of the other airports I have waiting

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20044212/763e5878-a45c-11e6-8834-a73ef4a95891.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68997873-193a9480-088a-11ea-9b24-f6a3f3d4d1f1.jpg)
