### ISSUE TITLE
VEMR-Dimapur Airport-Nagaland-India

### ISSUE THREAD

**Issue by KaalicharanDH** [InfiniteFlightAirportEditing/Airports#6850]
# Airport Name
Dimapur Airport
# Country?
India
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111042774-a18c6380-8404-11eb-9afc-d786b472a35d.png)
