### ISSUE TITLE
LEBE-Beas de Segura Airport-ANDALUCIA-SPAIN

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6851]
# Airport Name
Beas de Segura Airport
# Country?
Spain
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111031283-55bdc800-83cc-11eb-8861-9d889f4226e3.png)
