### ISSUE TITLE
KFPY-Perry-Foley Airport-FLORIDA-USA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6853]
# Airport Name
Perry-Foley Airport
# Country?
USA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111980175-efbff780-8ad3-11eb-90c3-2d8560836542.png)
