### ISSUE TITLE
KSPH-Springhill Airport-LOUISIANA-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#6854]
# Airport Name
Springhill Airport
# Country?
USA
# Improvements that need to be made?
Full (Redo)
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111561540-9ddd4180-8762-11eb-840e-522e5bbd4c28.png)
