### ISSUE TITLE
LESL-San Luis Mallorca Son Bonet Airport-ISLAS BALEARES-SPAIN

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#6857]
# Airport Name
San Luis Mallorca Son Bonet Airport
# Country?
Spain
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111031420-22c80400-83cd-11eb-9cfb-ed588b98be62.png)
