### ISSUE TITLE
UAII-Shymkent Airport-SOUTH KAZAKHSTAN-KAZAKHSTAN

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6859]
# Airport Name
Shymkent
# Country?
Kazakhstan
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
10k

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111556909-a3825980-8759-11eb-842d-afb138ddf77b.png)
