### ISSUE TITLE
RJBE

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#686]
Kobe - Kobe, Japan

**Comment by dushyants19** [comment]
Up for Grabs!

**Comment by Padi3-14** [comment]
I will take it if it's available, what needs to be done?

**Comment by Padi3-14** [comment]
Can I have it?

**Comment by TristinWoolf** [comment]
I don't see why not! I'll assign you now @Padi3-14 :)

**Comment by Padi3-14** [comment]
So, what has to be done?

**Comment by TristinWoolf** [comment]
Probably a redo @Padi3-14

**Comment by Padi3-14** [comment]
Finished the redo, and it is submitted. Waiting for approval.

**Comment by Padi3-14** [comment]
Continuing redo

**Comment by dushyants19** [comment]
85bbb99

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17244436/6f50e7b0-5547-11e6-9771-21ea436f85b1.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17249084/de94a744-5563-11e6-83b6-cf1aee24f02a.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18369942/a47db504-75ee-11e6-9092-063c21ec2bea.png)
