### ISSUE TITLE
VRMU-Dhaalu Airport-DHAALU-MALDIVES

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6860]
# Airport Name
Dhaalu Airport
# Country?
the maldives
# Improvements that need to be made?
scratch
# Are you working on this airport?
hm yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111082105-838e3400-84d4-11eb-9b66-8e374b7ae955.png)
