### ISSUE TITLE
2O8-Hinton Municipal Airport-OKLAHOMA-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#6861]
# Airport Name
Hinton Municipal Airport
# Country?
USA
# Improvements that need to be made?
Full (Redo)
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111562019-70dd5e80-8763-11eb-98fe-b20573689144.png)
