### ISSUE TITLE
VRQM-Maavaarulaa Airport-GAAFU DHAALU-MALDIVES

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#6866]
# Airport Name
Maavaarulaa Airport
# Country?
maldiv
# Improvements that need to be made?
hm scrach
# Are you working on this airport?
yyeyeyyey airport is done yay sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111081999-0b277300-84d4-11eb-812e-745698df4789.png)
