### ISSUE TITLE
57FA-Lake X Airport-FLORIDA-USA

### ISSUE THREAD

**Issue by zhf21** [InfiniteFlightAirportEditing/Airports#6869]
# Airport Name
Lake X Airport
# Country?
U.S.A.
# Improvements that need to be made?
Redo (autgen).
# Are you working on this airport?
Yes.
# Airport Priority? (10000ft+ Runway, Low)
10,000ft (water)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111082616-3e1f3600-84d7-11eb-9349-9c6b7b814063.png)
