### ISSUE TITLE
EDDW

### ISSUE THREAD

**Issue by superkev99** [InfiniteFlightAirportEditing/Airports#687]
Bremen, Germany

**Comment by dushyants19** [comment]
Do you want to redo EDDW, @superkev99? :)

**Comment by superkev99** [comment]
yes, @dushyants19 :)

**Comment by dushyants19** [comment]
Cool @superkev99, can you just check your email and accept an invite from Github? :)

**Comment by dushyants19** [comment]
Thank you!

**Comment by superkev99** [comment]
no problem :)

**Comment by samuelandersson** [comment]
How is this going @superkev99?

**Comment by Aviationluver** [comment]
@superkev99 Are you still working on this one?

**Comment by superkev99** [comment]
No sorry, I have no time anymoreVon meinem Huawei-Mobiltelefon gesendet-------- Originalnachricht --------Betreff: Re: [InfiniteFlightAirportEditing/Airports] EDDW (#687)Von: Aviationluver An: InfiniteFlightAirportEditing/Airports Cc: superkev99 ,Mention @superkev99 Are you still working on this one?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/InfiniteFlightAirportEditing/Airports","title":"InfiniteFlightAirportEditing/Airports","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/InfiniteFlightAirportEditing/Airports"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Aviationluver in #687: @superkev99 Are you still working on this one?"}],"action":{"name":"View Issue","url":"https://github.com/InfiniteFlightAirportEditing/Airports/issues/687#issuecomment-247352923"}}}

**Comment by Aviationluver** [comment]
I would like to re-do this one.

**Comment by PaulNielsen** [comment]
@Aviationluver Go ahead! :)

**Comment by Aviationluver** [comment]
I'll try my best ;) @PaulNielsen

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18808370/decbd7a2-8225-11e6-886b-1b122dff6225.png)
