### ISSUE TITLE
VIZD-Faizabad Airport-UTTAR PADRESH-INDIA

### ISSUE THREAD

**Issue by mervinjane** [InfiniteFlightAirportEditing/Airports#6873]
# Airport Name
Faizabad Airport Maryada Purshottam Shriram Airport
# Country?
India
# Improvements that need to be made?
It is to be added
# Are you working on this airport?
I'll work on it
# Airport Priority? (10000ft+ Runway, Low)
335 ft, low

**Comment by mervinjane** [comment]
@brunocr1050 can you remove the Uttar Pradesh from the name. It does not use it in real life.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116630218-7f00cc00-a918-11eb-9080-b3eb76cd94a4.png)
