### ISSUE TITLE
BIKF-Keflavik Airport-SUDURNES-ICELAND

### ISSUE THREAD

**Issue by planemadnews** [InfiniteFlightAirportEditing/Airports#688]
Happy to redo this too, although may be some time, as I have a few to do now

**Comment by JcFl4** [comment]
Damn, I'm too late... hahaha

**Comment by samuelandersson** [comment]
Any update here @planemadnews?

**Comment by planemadnews** [comment]
I have just finished KDTW and sent off for evaluation - moving on to this now

**Comment by planemadnews** [comment]
Sent in for review

**Comment by dushyants19** [comment]
@planemadnews any progress, Caleb?

**Comment by dushyants19** [comment]
Up for grabs

**Comment by dushyants19** [comment]
@JcFl4 you might like this 😄

**Comment by JcFl4** [comment]
Actually, i do it will no problem! 😉

**Comment by JcFl4** [comment]
@dushyants19, can you asssign me for this and and HAAB? I can't from mobile, thanks!

**Comment by PaulNielsen** [comment]
Done, Julio! :)

**Comment by JcFl4** [comment]
Perfect, thanks @PaulNiesen!

**Comment by JcFl4** [comment]
@PaulNielsen

**Comment by dushyants19** [comment]
Done for both!

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20027013/468e2ec8-a2d6-11e6-8bf6-be5d3d8bf086.png)

**Comment by moritzbabl** [comment]
Airport needs update for apron extension including remote positions 40-44
![b3dc6fa3-7f55-47eb-9e66-e7702d240aa3](https://user-images.githubusercontent.com/19365980/37247479-afe3c9a6-24bb-11e8-86d1-d42cb83ea4a0.jpeg)

**Comment by ItsW1ll** [comment]
Claimed. should be done by end of April :)

**Comment by ItsW1ll** [comment]
@moritzbabl I can't add stands 70L,70, 72L,72,72R as imagery doesn't show it.

**Comment by moritzbabl** [comment]
It's actually worse than I initially thought, still has jet bridges drawn

**Comment by ItsW1ll** [comment]
I know it’s bad!

**Comment by MajorTomMueller** [comment]
@ItsW1ll status?

**Comment by ItsW1ll** [comment]
Taking more time as imagery is poor. Will complete after holiday 👍🏿

**Comment by ItsW1ll** [comment]
Moritz has taken over this one :)

**Comment by moritzbabl** [comment]
done, thanks for the help @ItsW1ll

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56470705-d6f1c780-640e-11e9-8742-1ce607f66703.png)
