### ISSUE TITLE
60MN-Fuhr Flying Svc-MINNESOTA-USA

### ISSUE THREAD

**Issue by Aceorbit** [InfiniteFlightAirportEditing/Airports#6885]
# Airport Name
Fuhr Flying Svc Airport
# Country?
USA
# Improvements that need to be made?
Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111077241-d5778f80-84bd-11eb-939b-5baf6b543b4f.png)
