### ISSUE TITLE
EGSH

### ISSUE THREAD

**Issue by Misha16** [InfiniteFlightAirportEditing/Airports#689]
Lil tidy up. Lines being added etc etc

**Comment by dushyants19** [comment]
@henrikbg clear all labels. :rage:

**Comment by Will171** [comment]
Can someone assign me, im planning on adding ils centre lines and merging most of the taxiways in to one big one.

**Comment by NickArt1342** [comment]
@Will171 This has just been redone 3 days ago. Did you check the april2016 branch if it didn't already have those things you stated you would add?

**Comment by Will171** [comment]
Yeah I did

**Comment by Will171** [comment]
Yeah I did, I'm using the April 2016 copy

**Comment by NickArt1342** [comment]
@dushyants19 Leave the assignee assigned dush, so when sb has a question about the airport they can easily find who was last assigned.

**Comment by Will171** [comment]
Sent for approval

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17249243/b57b6d38-5564-11e6-89e3-0710120efdde.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18369337/c4cc9770-75ea-11e6-92d2-ab6a2ff2bcc3.png)

**Comment by kilt46** [comment]
William Goodchild
Improvements:

Changed runway surface to asphalt
Closed north taxiways and changed the boundary.
Added north apron parking
Added markings to engine test bay
Tweaked taxiways and markings for stands.
Tweaked runway markings
