### ISSUE TITLE
UTAM-Mary-MARY-TURKMENISTAN

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6890]
# Airport Name
Mary Airport
# Country?
Turkmenistan
# Improvements that need to be made?
from scratch
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
18R/36L - 12'467ft

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111087887-3caf3700-84f2-11eb-9a39-f1a6260fa4ac.png)
