### ISSUE TITLE
WIPY-Pagar Alam-SUMATRA-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6891]
# Airport Name
Atungbungsu Airport
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low Priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111241556-64be9900-85cb-11eb-8176-4cb5a2361982.png)
