### ISSUE TITLE
WITA-Tapak Tuan-ACEH-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6892]
# Airport Name
Teuku Cut Ali
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low Priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111241153-8e2af500-85ca-11eb-99c6-5a59d260efd7.png)
