### ISSUE TITLE
WITL-Lhoksukon-ACEH-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6893]
# Airport Name
Lhoksukon Point A
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low Priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111240895-1957bb00-85ca-11eb-992c-e5fb22913f4b.png)
