### ISSUE TITLE
UTAK-Turkmenbashi-BALKAN-TURKMENISTAN

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6895]
# Airport Name
Turkmenbashi
# Country?
Turkmenistan
# Improvements that need to be made?
from scratch
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
16R/34L - 11'483ft

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112061966-3c83ec80-8b2d-11eb-87e5-3095b0ef7756.png)
