### ISSUE TITLE
UBBY-Zagatala-ZAGATALA-AZERBAIJAN

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6896]
# Airport Name
Zagatala
# Country?
Azerbaijan
# Improvements that need to be made?
from scratch
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111870392-777df880-8952-11eb-8491-efe7ee54426d.png)
