### ISSUE TITLE
OPFA-Faisalabad Airport-PUNJAB-PAKISTAN

### ISSUE THREAD

**Issue by USMN13** [InfiniteFlightAirportEditing/Airports#6897]
# Airport Name
Faisalabad Int'l Airport
# Country?
Pakistan
# Improvements that need to be made?
New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114245599-63785600-9956-11eb-892e-c2d9f18e26b3.png)
