### ISSUE TITLE
OMAR-Arzanah Airport-ABU DHABI-UNITED ARAB EMIRATES

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#6898]
# Airport Name
Arzanah Airport
# Country?
United Arab Emirates
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112737271-3627b300-8f27-11eb-836d-25a6e004c9e8.png)
