### ISSUE TITLE
KTYL-Taylor Airport-ARIZONA-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#6899]
# Airport Name
Taylor Airport
# Country?
USA
# Improvements that need to be made?
Full (Redo)
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111980602-87254a80-8ad4-11eb-9099-bca0ae84b93b.png)
