### ISSUE TITLE
HDAM

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#69]
Please edit me

♻️

**Comment by carmichaelalonso** [comment]
Done by @JcFl4.

**Comment by dushyants19** [comment]
>Needs snapping and has incorrect markings.

**Comment by kilt46** [comment]
apron and buildings redone

**Comment by moritzbabl** [comment]
Image is not the best, let's see what we can do

**Comment by moritzbabl** [comment]
done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24529508/ae48936a-1571-11e7-8922-17b1aeafa537.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/55283092-a55e7280-5320-11e9-81f8-854910bc7caf.png)
