### ISSUE TITLE
EDKB

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#690]
No lines in airport. Could do with a tidy up. Existing IF build

**Comment by TristinWoolf** [comment]
Will fix this quickly.

**Comment by TristinWoolf** [comment]
Fixed.

**Comment by kilt46** [comment]
Buildings Missing
![Uploading image.png…]()

**Comment by kilt46** [comment]
Gates incorrect
![image](https://cloud.githubusercontent.com/assets/14023167/16286653/7de92c6c-38a3-11e6-8b48-c14860d175f2.png)

**Comment by dushyants19** [comment]
@IFAEpat you have to search before posting and @TristinWoolf dont touch another guy's airport (which has been assigned to him, in this case @lachieee)

**Comment by dushyants19** [comment]
Continue in/at #596

**Comment by kilt46** [comment]
Baseline
![image](https://cloud.githubusercontent.com/assets/14023167/16897161/d9bc4dac-4b6e-11e6-8794-89f8c9d398f0.png)

**Comment by kilt46** [comment]
Revamped
![image](https://cloud.githubusercontent.com/assets/14023167/16897295/7d7b7762-4b72-11e6-8b7e-5a9f50e8f7e7.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18816923/115c9654-8319-11e6-8d98-b1b3abee5ad3.png)
