### ISSUE TITLE
OYAB-Abbse-YEMEN

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#6900]
![OYAB-git](https://user-images.githubusercontent.com/26853210/111122546-1c20c480-8566-11eb-9372-dddbd8ca494f.png)

**Comment by MajorTomMueller** [comment]
https://github.com/InfiniteFlightAirportEditing/Airports/commit/c3b2f0de91c25da39735b11dbd6a84585229abb2

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111233331-d04c3a80-85ba-11eb-965c-4ab0d71228a0.png)
