### ISSUE TITLE
OYBI-Al-Bayda-YEMEN

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#6901]
![OYBI-git](https://user-images.githubusercontent.com/26853210/111122655-3bb7ed00-8566-11eb-9f10-d100ce36d5b3.png)

**Comment by MajorTomMueller** [comment]
https://github.com/InfiniteFlightAirportEditing/Airports/commit/c3b2f0de91c25da39735b11dbd6a84585229abb2

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111233113-5fa51e00-85ba-11eb-9169-c295e9e7faa9.png)
