### ISSUE TITLE
YBCG-Gold Coast Airport-QUEENSLAND-AUSTRALIA

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#691]
Gold Coast, AU

**Comment by TristinWoolf** [comment]
Will do this one.

**Comment by TristinWoolf** [comment]
Appears to just be minor issues/missing things. I will fix them!

**Comment by TristinWoolf** [comment]
I can see why this issue was created. Needs a complete redo. Starting now.

**Comment by TristinWoolf** [comment]
Finished and sent in.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19580499/391b405a-96ec-11e6-8268-df1b06241de6.png)

**Comment by moritzbabl** [comment]
Layout is outdated, especially at the northern end of the terminal. Also, the airport should be capable of handling 330s/787s which isn't supported in IF yet

**Comment by MajorTomMueller** [comment]
https://github.com/InfiniteFlightAirportEditing/Airports/commit/d9a82e1336c813cb2c0bb65e9758a655cf758e19

![YBLG-git](https://user-images.githubusercontent.com/26853210/71352925-7acbde00-256f-11ea-9806-d62df3179abd.png)
