### ISSUE TITLE
NSFA

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#692]
Faleolo Int'l - un-needed terrain and parking lot, inaccurate border, easy fix

**Comment by IceBlue02** [comment]
@IFAEpat why did you add this to the user suggestion list?

**Comment by IFAEpat** [comment]
@FlyFi said he'll pass this on to me

**Comment by IFAEpat** [comment]
Done 67ac768

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19017393/47a207ce-87fd-11e6-8f98-654af31e6729.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/71309762-a40f3180-23ea-11ea-850b-045296984031.jpg)
