### ISSUE TITLE
ULPB-Petrozavodsk-KARELIA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6921]
# Airport Name
Petrozavodsk
# Country?
Russia 
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111984377-4bd94a80-8ad9-11eb-8222-bb94bf0433e5.png)
