### ISSUE TITLE
LECJ-Castejón de Monegros-ARAGON-SPAIN

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Airports#6922]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/8f4642c8ab045a471d4a8bdecf7e19d376b72b83)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111240301-f2e55000-85c8-11eb-81cd-0afbe9ca7202.png)
