### ISSUE TITLE
WATR-Rote-NUSA TENGGARA-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6923]
# Airport Name
David C. Saunlade
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111555150-c9a5fa80-8755-11eb-8d9d-fbc7a5e76673.png)
