### ISSUE TITLE
LECN-Castellón de la Plana-COMUNIDAD VALENCIANA-SPAIN

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Airports#6926]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/4d420ad9e17df3faaa3aa06d40d1a662a40396c9)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111397284-e9beb680-868e-11eb-804b-dcfc20020afe.png)
