### ISSUE TITLE
LECT-El Castaño Airport-CASTILLA-LA MANCHA-SPAIN

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Airports#6927]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/d3400e766a32d5005220aefb4a83720fbbb59fb0)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111397034-55545400-868e-11eb-94df-6945113e2dc7.png)
