### ISSUE TITLE
LEEM-El Manantío Airport-EXTREMADURA-SPAIN

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Airports#6928]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/71cf181fe3a598dcf316464538e895d6ca777c88)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111396688-9e57d880-868d-11eb-8159-117b74439039.png)
