### ISSUE TITLE
VOND-Shri Guru Gobind Singh Ji Airport-MAHARASTHRA-INDIA

### ISSUE THREAD

**Issue by mervinjane** [InfiniteFlightAirportEditing/Airports#6929]
# Airport Name
Shri Guru Gobind Singh Ji Airport
# Country?
India
# Improvements that need to be made?
New
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by ECoops-123** [comment]
Hey Mervin, not sure if you're aware, but you may only have 3 assigned issues/airports at a time. Until you have an airport approved I cannot assign you.  :)

**Comment by mervinjane** [comment]
Oh okay no problem @ECoops-123

**Comment by StickThelanding** [comment]
can I take this airport

**Comment by mervinjane** [comment]
I'll take this please.

**Comment by hari-shreyas** [comment]
I'll take this. Please assign this airport to me.

Thanks!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118896830-c1da1200-b8ce-11eb-9587-6e8590fa0ec2.png)
