### ISSUE TITLE
WAFU-Ampana-SULAWESI-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6932]
# Airport Name
Tanjung Api
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low Priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111867623-45b16580-8943-11eb-9b33-1e60cb06c790.png)
