### ISSUE TITLE
PAMH-Minchumina Airport-ALASKA-USA

### ISSUE THREAD

**Issue by zhf21** [InfiniteFlightAirportEditing/Airports#6934]
# Airport Name
Minchumina Airport
# Country?
U.S.A.
# Improvements that need to be made?
Redo (autogen).
# Are you working on this airport?
Yes.
# Airport Priority? (10000ft+ Runway, Low)
Low.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111981078-2f3b1380-8ad5-11eb-8eff-af3e234886a4.png)
