### ISSUE TITLE
1Q2-Spaulding-CALIFORNIA-USA

### ISSUE THREAD

**Issue by LawinS** [InfiniteFlightAirportEditing/Airports#6936]
# Airport Name
Spaulding
# Country?
USA
# Improvements that need to be made?
Full rework
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113068640-4ab4b700-9184-11eb-9b96-924053a4c8f0.png)
