### ISSUE TITLE
LEEV-Eduardo Castellanos-Villacastín Airport-CASTILLA Y LEON-SPAIN

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Airports#6937]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/0038ff96d1262ac472ead2995813b72ca9be2f99)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111396272-b8dd8200-868c-11eb-8fce-aeda36cb01e8.png)
