### ISSUE TITLE
LEFM-Fuentemilanos Airport-CASTILLA Y LEON-SPAIN

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Airports#6938]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/b7784a7e480d51da092aab6d02d803903d7f1c7a)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111395624-51730280-868b-11eb-8732-e90fe048da3c.png)
