### ISSUE TITLE
LEGC-Altarejos-Guadalcanal Airport-ANDALUCIA-SPAIN

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Airports#6939]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/7de76608cad86f24ab835acb4a9ffcccdbe02474)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111395030-ec6add00-8689-11eb-8821-6454fd99825c.png)
