### ISSUE TITLE
LEGU-Guadalupe Airport-EXTREMADURA-SPAIN

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Airports#6940]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/b6f41882a9e27f26e214e59925a83cec58cc903c)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111394786-664e9680-8689-11eb-87a3-50cc6e69ce9f.png)
