### ISSUE TITLE
LEGY-Soria-Garray Airport-CASTILLA Y LEON-SPAIN

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Airports#6941]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/262157ce4ea949d9fb984f1230ab863069928646)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111390616-048a2e80-8681-11eb-8c9d-365f70d5f7ef.png)
