### ISSUE TITLE
UAAL-Usharal-USHARAL-KAZAKHSTAN

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#6942]
# Airport Name
Usharal
# Country?
Kazakhstan
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111923048-3c231d00-8a6b-11eb-9b8d-79824e167b3a.png)
