### ISSUE TITLE
LEHI-Hinojosa Del Duque-ANDALUCIA-SPAIN

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Airports#6943]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/ee4b99bc5e3fd250eb223c3f218ee4cca65c63bb)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111390287-7f067e80-8680-11eb-9375-8e5c0f098af1.png)
