### ISSUE TITLE
LEIG-Igualada-Ódena Airport-CATALUNA-SPAIN

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Airports#6945]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/d6468d3cc40c1ad40dcdb2b088ce62ac67de5047)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111389706-6c3f7a00-867f-11eb-93f1-c1be41d16bea.png)
