### ISSUE TITLE
LEIZ-La Perdiz Airport-CASTILLA-LA MANCHA-SPAIN

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Airports#6946]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/905bfaf6f5faa7a1cee239edac23a4d1a8d325d7)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111389367-dd326200-867e-11eb-983d-667f3f242552.png)
