### ISSUE TITLE
LEJU-La Juliana Airport-ANDALUCIA-SPAIN

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Airports#6949]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/f8cb1380fe2a5879a1c9cd42a8025b0f0c54d85e)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111395396-c4c84480-868a-11eb-90bb-829d669f0c6f.png)
