### ISSUE TITLE
KRIC-Richmond International Airport-VIRGINIA-USA

### ISSUE THREAD

**Issue by danielshaw** [InfiniteFlightAirportEditing/Airports#695]
Redo of Richmond International Airport.

**Comment by dushyants19** [comment]
Any progress, @danielshaw?

**Comment by dushyants19** [comment]
@danielshaw any progress?

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21499021/b9bc59c0-cbf7-11e6-895d-446884fe3b61.png)

**Comment by Czechoslovaki** [comment]
Redoing this airport because half of it looks like a disaster.

**Comment by kilt46** [comment]
![Uploading image.png…]()

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/99906126-e2683d00-2c9a-11eb-9c36-41b99cb08689.png)
