### ISSUE TITLE
LRBM-Maramureș Airport-MARAMURES-ROMANIA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6950]
![Full](https://user-images.githubusercontent.com/59462519/111395526-f6560580-86b4-11eb-8211-1fc67a73c556.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111397543-90a35280-868f-11eb-9540-adcfcec9002f.png)
