### ISSUE TITLE
LELA-La Calderera-CASTILLA-LA MANCHA-SPAIN

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Airports#6951]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/d61a5a89d6cdc57a32372e759eabebc6789cc28f)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111552069-97919a00-874f-11eb-8d21-030f249f5578.png)
