### ISSUE TITLE
LELG-Los Garranchos-MURCIA-SPAIN

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Airports#6952]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/210fcf721759302b0a94faa618bb482f641aaccc)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111551814-0d493600-874f-11eb-8bca-5d584491998a.png)
