### ISSUE TITLE
LELH-Alhama de Murcia-MURCIA-SPAIN

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Airports#6953]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/2efd26f3f48a1e9bda9beb54846515e19badb57d)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111551467-492fcb80-874e-11eb-8d42-e4817d4748c9.png)
