### ISSUE TITLE
LELI-Linares-ANDALUCIA-SPAIN

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Airports#6954]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/0392284a94a2df056f354605e439aa1dc5f5e26c)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111551123-8182da00-874d-11eb-8993-27cc44bf615f.png)
