### ISSUE TITLE
LELM-Almansa Airport-CASTILLA-LA MANCHA-SPAIN

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Airports#6955]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/6fa30de3f606c12b6708ad949ff822228c0c98f3)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111550779-d7a34d80-874c-11eb-8baf-58d8bea89501.png)
