### ISSUE TITLE
KABE

### ISSUE THREAD

**Issue by TristinWoolf** [InfiniteFlightAirportEditing/Airports#696]
Lehigh Valley International Airport

Next on my list! :)

**Comment by AR-AR-AR** [comment]
Excellente!

**Comment by TristinWoolf** [comment]
Finished and sent in.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19501514/de4845f0-956b-11e6-9d2a-3a2622588346.png)
