### ISSUE TITLE
LELT-Lillo Airport-CASTILLA-LA MANCHA-SPAIN

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Airports#6960]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/25af2a24761d405abff0c94db744fe6e57652892)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111550522-4c29bc80-874c-11eb-9034-4b8b2ab1e354.png)
