### ISSUE TITLE
LEMR-La Morgal-ASTURIAS-SPAIN

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Airports#6963]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/e1aa5724a1da969a638fa2459037113d3f144a3b)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111549829-de30c580-874a-11eb-88cc-01256a7d50a5.png)
