### ISSUE TITLE
LEMS-Manresa-CATALUNA-SPAIN

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Airports#6964]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/6a9771b6aefbcb972aea506760b8ed8ce831cf93)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111549256-db81a080-8749-11eb-8aa0-1623de4eafdc.png)
