### ISSUE TITLE
LEMT-Casarrubios del Monte-CASTILLA-LA MANCHA-SPAIN

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Airports#6966]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/f9be66f427522cabf556f700549810b21b5a8b1b)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111549575-682c5e80-874a-11eb-8a48-eea54079fb97.png)
