### ISSUE TITLE
LEMX-La Mancha-CASTILLA-LA MANCHA-SPAIN

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Airports#6969]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/b4a63b7d5285880de27690246155d6dbfc5ffc44)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111560634-ded45680-8760-11eb-83c1-a1b6c1fc6d5d.png)
