### ISSUE TITLE
PASI-Sitka Rocky Gutierrez-ALASKA-USA

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#697]
Sitka, AK

**Comment by JcFl4** [comment]
Alaska is over for now.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19421987/b117d95a-93d2-11e6-807b-4fc9e8c523b8.png)

**Comment by brennanhackard** [comment]
@zhf21 will be redoing this airport.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108922757-2d2c8480-75fd-11eb-905e-52cf8d3abec5.png)
