### ISSUE TITLE
LENA-Benabarre-ARAGON-SPAIN

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Airports#6970]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/21aaa360d981e75a334ef240936e90eff61ce712)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111561143-fcee8680-8761-11eb-9f97-2a397452c731.png)
