### ISSUE TITLE
LEOC-Ocaña-CASTILLA-LA MANCHA-SPAIN

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Airports#6971]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/1df580ec8e08be9d9ced393808a354ff8f59ea7b)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111869275-937e9b80-894c-11eb-9f8b-b403c30022d2.png)
