### ISSUE TITLE
LEOT-Ontur-CASTILLA-LA MANCHA-SPAIN

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Airports#6972]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/33384bda555779f050522fa5c081dd4ad7824d4e)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111868923-d5a6dd80-894a-11eb-966c-5d0028db11c7.png)
