### ISSUE TITLE
LEPI-Casas de los Pinos-CASTILLA-LA MANCHA-SPAIN

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Airports#6973]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/7c4edff745346348ec21820686b2cbcaedb9cafd)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111868761-c3786f80-8949-11eb-84a5-6428f8b51288.png)
