### ISSUE TITLE
LEPR-Palma del Río-ANDALUCIA-SPAIN

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Airports#6974]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/5b832053f44dfaaef31bb19782a36c34e1dda8a0)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111868557-a55e3f80-8948-11eb-8a5d-36fa19f5def8.png)
