### ISSUE TITLE
LERM-Robledillo de Mohernando-CASTILLA-LA MANCHA-SPAIN

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Airports#6975]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/e72e8658c09c10bff8ee59b0197b26e6c9971eca)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111868445-dee27b00-8947-11eb-9892-3093c5f7e6b7.png)
