### ISSUE TITLE
OINE-Kalaleh Airport-GOLESTAN-IRAN

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#6982]
![Full](https://user-images.githubusercontent.com/59462519/111646516-a16fd780-87f9-11eb-8b9f-55ba3c44ba7a.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111701417-d0da1080-8808-11eb-86ef-00ee2e8fbd77.png)
