### ISSUE TITLE
OMAS-Das Island Airport-UNITED ARAB EMIRATES

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#6983]
# Airport Name
Das Island Airport
# Country?
United Arab Emirates
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111870101-b743e080-8950-11eb-9fa1-72f79a9c8935.png)
