### ISSUE TITLE
UUOB-Belgorod Intl-BELGOROD-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#6984]
# Airport Name
Belgorod Intl / Vladimir G. Shukhov Airport
# Country?
Russia
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111985711-f867fc00-8ada-11eb-8c12-a1945257f8ad.png)
