### ISSUE TITLE
WATM-Alor-NUSA TENGGARA-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6985]
# Airport Name
Alor
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111867444-f9b1f100-8941-11eb-83f0-583fa77393ad.png)
