### ISSUE TITLE
WADS-Sumbawa Besar-NUSA TENGGARA-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6986]
# Airport Name
Sumbawa Besar
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111867243-c0c54c80-8940-11eb-973f-3e47bc721de9.png)
