### ISSUE TITLE
WAVD-Dekai-PAPUA-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6987]
# Airport Name
Nop Goliat
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111866945-e05b7580-893e-11eb-8909-b09a7187d1a1.png)
