### ISSUE TITLE
ESNV-Vilhelmina Airport-VASTERBOTTEN-SWEDEN

### ISSUE THREAD

**Issue by hari-shreyas** [InfiniteFlightAirportEditing/Airports#6988]
# Airport Name
Vilhelmina Airport
# Country?
Sweden
# Improvements that need to be made?
Needs to be added
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115121190-ee6cd800-9f76-11eb-90b2-cdec08526bb0.png)
