### ISSUE TITLE
WAPG-Buru-MALUKU-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#6995]
# Airport Name
Namlea
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111917515-5ef30880-8a4e-11eb-8c51-6ec7a5a5fa5c.png)
