### ISSUE TITLE
AYTG-Tagula Airport-MILNE BAY-PAPUA NEW GUINEA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#6999]
# Airport Name
Tagula Airport
# Country?
PNG
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112062718-4bb76a00-8b2e-11eb-84c3-b1b669beda40.png)
