### ISSUE TITLE
OPCH-Chitral Airport-KHYBER PAKHTUNKHWA-Pakistan

### ISSUE THREAD

**Issue by USMN13** [InfiniteFlightAirportEditing/Airports#7000]
# Airport Name
Chitral
# Country?
Pakistan
# Improvements that need to be made?
Redo from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113455631-c0ad5e00-93d0-11eb-86ff-d18fc9e930fa.png)
