### ISSUE TITLE
LECX-Castell de Castells-COMUNIDAD VALENCIANA-SPAIN

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Airports#7001]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/d41d45006a56eb0e10258082b27997260bdf5f59)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111917034-dbd0b300-8a4b-11eb-9985-eff8576b98fa.png)
