### ISSUE TITLE
LEDC-La Cuesta-CASTILLA-LA MANCHA-SPAIN

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Airports#7002]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/1e45dd6d3a96ea35f233c13a89efa7a658e656d1)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111916768-8a73f400-8a4a-11eb-8794-2ac7571461b7.png)
