### ISSUE TITLE
LENE-La Caminera-CASTILLA-LA MANCHA-SPAIN

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Airports#7003]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/3619d98f67b3f234eb87475fb78089cce883e47e)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111904158-59c49800-8a13-11eb-8590-8a8bd2365e07.png)
