### ISSUE TITLE
LEPZ-Pozuelos de Calatrava-CASTILLA-LA MANCHA-SPAIN

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Airports#7004]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/f79427e90adf6f5a63d18f5968844a086236e57f)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111904039-c9865300-8a12-11eb-87e2-1f7636478c3c.png)
