### ISSUE TITLE
UAON-Yubileyniy Airport-KYZYLORDA OBLAST-KAZAKHSTAN

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#7005]
# Airport Name
Yubileyniy
# Country?
Kazakhstan
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
10k (It's a thicc runway)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111922904-95d71780-8a6a-11eb-8e46-ea9e296fe02a.png)
