### ISSUE TITLE
WAFL-Toli Toli-SULAWESI-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#7007]
# Airport Name
Sultan Bantilan
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111991462-5ba95c80-8ae2-11eb-8fcf-055d176d934a.png)
