### ISSUE TITLE
WAWD-Wakatobi-SULAWESI-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#7009]
# Airport Name
Matahora
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112002708-2efb4200-8aee-11eb-9f13-d7b0b8d8b10f.png)
