### ISSUE TITLE
ZSPD-Shanghai Pudong Airport-SHANGHAI-CHINA

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#701]
Shanghai International, China

**Comment by dushyants19** [comment]
Any progress?

**Comment by JcFl4** [comment]
I won't be able to upload ZSPD anytime soon as I have exams coming up... I have uploaded a temporary version though - It's not great, but better than nothing.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25048667/29ded1e6-2103-11e7-9edc-d714f5ec4031.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/37377373-873ee25e-26f7-11e8-81d9-b0e012c90c1d.png)
Buildings added. Gates renamed

**Comment by brunocr1050** [comment]
@OscarConklin will be working on this airport for the following reasons: 

1. Add the new Satellite terminal and its surrounding taxiways
2. Add the missing maintenance apron south of the newest runway
3. Add the renovated southern part of Terminal 1
4. Remove the remaining buildings
5. Add the many missing/inaccurate white markings
6. Replace the inaccurate runway shoulders with taxiways
7. Other issues (many adjacent, unsnapped, taxiways of the same material, none of the spawns are snapped, some inaccurate taxiway materials, and remove unnecessary items such as wig-wags.)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111559351-594fa700-875e-11eb-9327-04211d743ce8.png)
