### ISSUE TITLE
UUOK-Kursk Vostochny-KURSK-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7011]
# Airport Name
Kursk Vostochny
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111985371-87284900-8ada-11eb-99aa-d3f81a2365c5.png)
