### ISSUE TITLE
XLLJ-Gromovo AB-LENINGRAD-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7013]
# Airport Name
Gromovo AB
# Country?
Russia
# Improvements that need to be made?
from scratch
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112067334-e7000d80-8b35-11eb-8af6-25af99d710e2.png)
