### ISSUE TITLE
OEJL-King Abdulaziz Naval Base-AL JUBAIL-SAUDI ARABIA

### ISSUE THREAD

**Issue by suhasjatla** [InfiniteFlightAirportEditing/Airports#7014]
# Airport Name
King Abdulaziz Naval Base (Formerly OE50, will be renamed to OEJL)
# Country?
Saudi Arabia
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by MajorTomMueller** [comment]
ICAO code is OEJL
[OE-AD-2.OEJL-en-SA.pdf](https://github.com/InfiniteFlightAirportEditing/Airports/files/6180207/OE-AD-2.OEJL-en-SA.pdf)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112390358-29575500-8cc4-11eb-8dca-e6f998ecec5f.png)
