### ISSUE TITLE
AYMS-Misima Airport-MILNE BAY-PAPUA NEW GUINEA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#7015]
# Airport Name
Misima Airport
# Country?
PNG
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112063087-dbf5af00-8b2e-11eb-9822-47b21a2d1c72.png)
![image](https://user-images.githubusercontent.com/14023167/112063116-e57f1700-8b2e-11eb-95e5-055698cf3bb7.png)
Is this ALL Gravel or is there a grass shoulder?
