### ISSUE TITLE
OEPJ-Pump Station 10-AL MENDASSAH-SAUDI ARABIA

### ISSUE THREAD

**Issue by Aceorbit** [InfiniteFlightAirportEditing/Airports#7016]
# Airport Name
Pump Station 10
# Country?
Saudi Arabia
# Improvements that need to be made?
Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
N/A

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112061143-10b43700-8b2c-11eb-97a1-f5c8a07fd58a.png)
