### ISSUE TITLE
UASA-Ayaguz Airport-EAST KAZAKHSTAN-KAZAKHSTAN

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#7017]
# Airport Name
Ayaguz
# Country?
Kazakhstan
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112737067-b2b99200-8f25-11eb-98af-ace24b93962c.png)
