### ISSUE TITLE
LRTM-Târgu Mureș Airport-MURES-ROMANIA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#7018]
![Full](https://user-images.githubusercontent.com/59462519/111922544-591f1680-8a92-11eb-8f53-9e84e8eece2d.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111983854-9908ec80-8ad8-11eb-9693-f56ef39405ec.png)
