### ISSUE TITLE
WI1B-Batujajar-JAWA-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#7019]
# Airport Name
Batujajar
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112066232-fb430b00-8b33-11eb-8cb9-ea8814863467.png)
