### ISSUE TITLE
KCMH

### ISSUE THREAD

**Issue by DavidCutler** [InfiniteFlightAirportEditing/Airports#702]
Port Columbus Ohio :)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17267606/24234ecc-55d3-11e6-9e2f-f091e57efd09.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18024257/36cc2a7c-6bcb-11e6-8035-4da2451cab34.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18024261/41bf3140-6bcb-11e6-86fe-4d3725baf5fa.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24780337/19da34dc-1afc-11e7-857b-8546f412ce0d.png)

**Comment by dushyants19** [comment]
Completely redone by @netjets-1951

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25514343/f1255204-2ba1-11e7-8b66-909ade9c6f0d.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/77439408-c50a6880-6dc5-11ea-8a40-4dee2c9649c7.jpg)
