### ISSUE TITLE
WAGB-Muara Teweh-KALIMANTAN-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#7021]
# Airport Name
Haji Muhammad Sidik
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112064203-989c4000-8b30-11eb-918a-74b4ae9dafde.png)
