### ISSUE TITLE
UMIO-Orsha Aerodrome-VITEBSK-BELARUS

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#7022]
# Airport Name
Orsha Aerodrome
# Country?
Belarus
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112736982-df20de80-8f24-11eb-8e87-f8d5bc43db7a.png)
