### ISSUE TITLE
UMLI-Minsk Machulishchy Air Base-MINSK-BELARUS

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#7023]
# Airport Name
Minsk Machulishchy Air Base
# Country?
Belarus
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114284079-0abac300-9a13-11eb-9ab4-50fc9dba806e.png)
