### ISSUE TITLE
UMMA-Baranavichi Air Base-BREST-BELARUS

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#7024]
# Airport Name
Baranavichi Air Base
# Country?
Belarus
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/119224740-85243b80-bac5-11eb-9303-77855bab24e7.png)
