### ISSUE TITLE
XLDH-Nagurskaya-ARKHANGELSK-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7025]
# Airport Name
Nagurskaya
# Country?
Russia
# Improvements that need to be made?
from scratch
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low
_N80.80258° E047.66907°_

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112067881-d0a68180-8b36-11eb-9960-2a997ef073ef.png)
