### ISSUE TITLE
URMS-Magas-INGUSHETIA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7027]
# Airport Name
Magas
# Country?
Russia
# Improvements that need to be made?
from scratch
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112066956-44e02580-8b35-11eb-84ef-08ed75bfe775.png)
