### ISSUE TITLE
MYAB

### ISSUE THREAD

**Issue by TristinWoolf** [InfiniteFlightAirportEditing/Airports#703]
Clarence A Bain Airport

Being redone.

**Comment by TristinWoolf** [comment]
Done.

**Comment by TristinWoolf** [comment]
Added UNICOM frequency.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19223744/f07bc610-8e3c-11e6-94f0-71a882f00775.png)
