### ISSUE TITLE
K52-Monroe City-MISSOURI-USA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7032]
# Airport Name
Cpt Ben Smith Airfield
# Country?
USA
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112736901-5144f380-8f24-11eb-8db1-2d84937846e0.png)
