### ISSUE TITLE
KBVU-Boulder City-NEVADA-USA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7033]
# Airport Name
Boulder City Municipal
# Country?
USA
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113507690-ad55dc00-9511-11eb-9d84-022bc94d0a8c.png)
