### ISSUE TITLE
XRKD-Enem-ADYGEA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7034]
# Airport Name
Enem
# Country?
Russia
# Improvements that need to be made?
from scratch
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112730609-87707c00-8f00-11eb-8a1b-76bae9de455b.png)
