### ISSUE TITLE
WASK-Kaimana-PAPUA-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#7035]
# Airport Name
Utarom
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112551331-d72f3600-8d8e-11eb-83c9-5b1a0e403e5e.png)
