### ISSUE TITLE
AYDO-Doini Airport-MILNE BAY-PAPUA NEW GUINEA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#7037]
# Airport Name
Doini Airport
# Country?
PNG
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112734689-53ec1c80-8f15-11eb-9d8e-872c40db966d.png)
