### ISSUE TITLE
H05-Wilburton Municipal Airport-OKLAHOMA-USA

### ISSUE THREAD

**Issue by zhf21** [InfiniteFlightAirportEditing/Airports#7038]
# Airport Name
Wilburton Municipal Airport
# Country?
U.S.A.
# Improvements that need to be made?
Redo (autogen).
# Are you working on this airport?
Yes.
# Airport Priority? (10000ft+ Runway, Low)
Low.

**Comment by zhf21** [comment]
Completed.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112734919-b2fe6100-8f16-11eb-910e-6d843b7e76d3.png)
