### ISSUE TITLE
SA43-Aeroparque Rosario-SANTA FE-ARGENTINA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#7039]
# Airport Name
Aeroparque Rosario
# Country?
Argentina
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112068193-69d59800-8b37-11eb-84f6-34266ca95557.png)
