### ISSUE TITLE
OE52-Al Artawiyah South Airport-AL ARTAWIYAH-SAUDI ARABIA

### ISSUE THREAD

**Issue by suhasjatla** [InfiniteFlightAirportEditing/Airports#7040]
# Airport Name
Al Artawiyah South Airport
# Country?
Saudi Arabia
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112389912-7ab31480-8cc3-11eb-933e-e8494d47f75f.png)
