### ISSUE TITLE
SJBF-Fazenda Santa Barbara Airstrip-MINAS GERAIS-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#7041]
# Airport Name
Fazenda Santa Barbara Airstrip
# Country?
Brazil
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![Uploading image.png…]()
