### ISSUE TITLE
SDWV-Chacara Maringa Airstrip-PARA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#7042]
# Airport Name
Chacara Maringa Airstrip
# Country?
Brazil
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112220289-1412f580-8bf4-11eb-83eb-31bf1ef31b20.png)
