### ISSUE TITLE
OPQT-Quetta Samungli-BALOCHISTAN-PAKISTAN

### ISSUE THREAD

**Issue by USMN13** [InfiniteFlightAirportEditing/Airports#7043]
# Airport Name
Quetta Samungli
# Country?
Pakistan
# Improvements that need to be made?
Redo from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114245205-9ec65500-9955-11eb-8eda-cb0164802ae6.png)
