### ISSUE TITLE
UAAT-Taldykorgan Airport-ALMATY-KAZAKHSTAN

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#7046]
# Airport Name
Taldykorgan
# Country?
Kazakhstan
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112752018-77a37700-8f96-11eb-854a-95566fcce376.png)
