### ISSUE TITLE
SEII-General Villamil Airport-GALAPAGOS-ECUADOR

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#7048]
# Airport Name
General Villamil Airport
# Country?
Ecuador
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112566011-3485b000-8dac-11eb-916c-2a44b14ac136.png)
