### ISSUE TITLE
WAES-Emalamo-MALUKU-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#7050]
# Airport Name
Emalamo
# Country?
Indonesia
# Improvements that need to be made?
Create New Airporr
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112548720-a9e08900-8d8a-11eb-88d7-341cd3c92489.png)
