### ISSUE TITLE
WAEG-Galela-MALUKU-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#7051]
# Airport Name
Gamar Malamo
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112548217-db0c8980-8d89-11eb-94a9-1aa286f9d896.png)
