### ISSUE TITLE
4A5-Searcy County Airport-ARKANSAS-USA

### ISSUE THREAD

**Issue by zhf21** [InfiniteFlightAirportEditing/Airports#7052]
# Airport Name
Searcy County Airport
# Country?
U.S.A.
# Improvements that need to be made?
Redo (autogen).
# Are you working on this airport?
Yes.
# Airport Priority? (10000ft+ Runway, Low)
Low.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112702374-45dcc400-8e61-11eb-9171-3a82b745e271.png)
