### ISSUE TITLE
OE53-King Abdul Aziz Military Academy Airport-RIYADH-SAUDI ARABIA

### ISSUE THREAD

**Issue by suhasjatla** [InfiniteFlightAirportEditing/Airports#7053]
# Airport Name
King Abdul Aziz Military Academy Airport
# Country?
Saudi Arabia
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![Uploading image.png…]()
