### ISSUE TITLE
ID42-Poplar Point Airport-IDAHO-USA

### ISSUE THREAD

**Issue by LesterXavier** [InfiniteFlightAirportEditing/Airports#7059]
# Airport Name
Poplar Point Airport
# Country?
USA 🇺🇸 
# Improvements that need to be made?
New airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112734800-045a2080-8f16-11eb-920c-df9b37516ce0.png)
