### ISSUE TITLE
OE54-Hafar Al Atk Airport-RIYADH-SAUDI ARABIA

### ISSUE THREAD

**Issue by suhasjatla** [InfiniteFlightAirportEditing/Airports#7060]
# Airport Name
Hafar Al Atk
# Country?
Saudi Arabia
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112378839-68ca7500-8cb5-11eb-93c6-1b13f798ea87.png)
