### ISSUE TITLE
OEAD-Aradah Airport-ARADAH-SAUDI ARABIA

### ISSUE THREAD

**Issue by suhasjatla** [InfiniteFlightAirportEditing/Airports#7061]
# Airport Name
Aradah (Formerly OE55)
# Country?
Saudi Arabia
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112727346-25a81600-8ef0-11eb-8fcc-50f473ac080e.png)
