### ISSUE TITLE
OEST-Shabitah Airport-SHUBAYTAH-SAUDI ARABIA

### ISSUE THREAD

**Issue by suhasjatla** [InfiniteFlightAirportEditing/Airports#7062]
# Airport Name
Shabitah (Formerly OE56)
# Country?
Saudi Arabia
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![Uploading image.png…]()
