### ISSUE TITLE
HESG-Suhag Airport-AL WADI AL JADID-EGYPT

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#7063]
# Airport Name
Suhag International Airport
# Country?
Egypt
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112564430-3dc14d80-8da9-11eb-905e-ee3495121c86.png)
