### ISSUE TITLE
HEAT-Assiut Airport-ASSIUT-EGYPT

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#7065]
# Airport Name
Assiut Airport
# Country?
Egypt
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112751873-d74d5280-8f95-11eb-85a8-0d76ac9e240d.png)
