### ISSUE TITLE
EILT-Letterkenny Airport-LETTERKENNY-IRELAND

### ISSUE THREAD

**Issue by zhf21** [InfiniteFlightAirportEditing/Airports#7068]
# Airport Name
Letterkenny Airport
# Country?
Ireland.
# Improvements that need to be made?
Full redo (auto-gen).
# Are you working on this airport?
Yes.
# Airport Priority? (10000ft+ Runway, Low)
Low.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112726041-4caf1980-8ee9-11eb-9112-2e36e7503347.png)
