### ISSUE TITLE
SPGP-Gueppi Airport-LORETO-PERU

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#7070]
# Airport Name
Gueppi Airport
# Country?
Peru
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112553427-7d306f80-8d92-11eb-874c-213a497d56a6.png)
