### ISSUE TITLE
WMKI-Ipoh-PERAK-MALAYSIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#7071]
# Airport Name
Sultan Azlan Shah
# Country?
Malaysia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112727518-d31b2980-8ef0-11eb-9fa7-66dd242a564d.png)
