### ISSUE TITLE
WAHG-Wonosari-JAWA-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#7072]
# Airport Name
Gading
# Country?
Indonesia
# Improvements that need to be made?
Create New Airporr
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112726539-f8596900-8eeb-11eb-8cb6-e6459709357d.png)
