### ISSUE TITLE
LFHS-Bourg Ceyzeriat Airport-JASSERON-FRANCE

### ISSUE THREAD

**Issue by IFsami** [InfiniteFlightAirportEditing/Airports#7074]
# Airport Name
Bourg Ceyzeriat Airport
# Country?
France
# Improvements that need to be made?
Full rework
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112726914-ca752400-8eed-11eb-9c21-7e1d36eaa1e6.png)
