### ISSUE TITLE
LTBH-Canakkale Airport-CANAKKALE-TURKEY

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#7078]
# Airport Name
Canakkale Airport
# Country?
Turkey
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112552073-32adf380-8d90-11eb-9bd8-2d8ba8fdcc7c.png)
