### ISSUE TITLE
LLMZ-Bar Yehuda-MASADA-ISRAEL

### ISSUE THREAD

**Issue by zhf21** [InfiniteFlightAirportEditing/Airports#7079]
# Airport Name
Bar Yehuda
# Country?
Israel.
# Improvements that need to be made?
Redo (auto-gen).
# Are you working on this airport?
Yes.
# Airport Priority? (10000ft+ Runway, Low)
Low.

**Comment by zhf21** [comment]
Minor mistake, Bruno. It should be added to Israel, not Italy,

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112726734-fb088e00-8eec-11eb-9144-76bde77abb50.png)
