### ISSUE TITLE
MYAP

### ISSUE THREAD

**Issue by TristinWoolf** [InfiniteFlightAirportEditing/Airports#708]
Spring Point Airport

Being redone.

**Comment by TristinWoolf** [comment]
Done.

**Comment by TristinWoolf** [comment]
Added airport beacon.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19021463/8a9703d8-8887-11e6-8e75-0309e895be3a.png)
