### ISSUE TITLE
OPMT-Multan Airport-PUNJAB-PAKISTAN

### ISSUE THREAD

**Issue by USMN13** [InfiniteFlightAirportEditing/Airports#7080]
# Airport Name
Multan Intl
# Country?
Pakistan
# Improvements that need to be made?
Redo from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
10000ft+ Runway, Low

**Comment by brennanhackard** [comment]
@USMN13 you're already assigned to three other issues. I'll assign you to this one once one of those airports passes OR.

**Comment by USMN13** [comment]
I would like to do this airport if possible :)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114786000-12e06e80-9d43-11eb-8218-858a413ceb01.png)
