### ISSUE TITLE
MUNG-Nueva Gerona Airport-ISLA DE LA JUVENTUD-CUBA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#7085]
# Airport Name
Nueva Gerona Airport
# Country?
Cuba
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112751655-af112400-8f94-11eb-99ba-c8d79dbf6b2e.png)
