### ISSUE TITLE
MUBA-Baracoa Airport-GUANTANAMO-CUBA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#7087]
# Airport Name
Baracoa Airport
# Country?
Cuba
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112751522-2a260a80-8f94-11eb-99f2-6699faea6ad7.png)
