### ISSUE TITLE
SDVZ-Kareli Airport-RIO GRANDE DO NORTE-BRAZIL

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Airports#7089]
# Airport Name
Kareli
# Country?
Brazil
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114115917-5baea800-98a9-11eb-8dec-833b96c9e38a.png)
