### ISSUE TITLE
MYAS

### ISSUE THREAD

**Issue by TristinWoolf** [InfiniteFlightAirportEditing/Airports#709]
Sandy Point Airstrip

Being redone.

**Comment by TristinWoolf** [comment]
Done.

**Comment by TristinWoolf** [comment]
Added airport beacon.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19224909/e7c5b874-8e54-11e6-950b-3072826fb6f3.png)
