### ISSUE TITLE
KCHD-Chandler Municipal Airport-ARIZONA-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7091]
# Airport Name
Chandler Municipal Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113362996-54b9ef80-9315-11eb-8a22-9c6abc1fe90a.png)
