### ISSUE TITLE
KGGP-Logansport/Cass County Airport-INDIANA-USA 

### ISSUE THREAD

**Issue by RhysV29** [InfiniteFlightAirportEditing/Airports#7092]
# Airport Name
Logansport/Cass County Airport
# Country?
USA
# Improvements that need to be made?
Complete Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115111491-4212fd80-9f46-11eb-840c-ab94abf4dcc8.png)
