### ISSUE TITLE
WAKT-Tanah Merah-PAPUA-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#7093]
# Airport Name
Tanah Merah
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112907849-2093c400-90b4-11eb-85af-bfaad23b989f.png)
