### ISSUE TITLE
WIHC-Cibubur-JAWA-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#7094]
# Airport Name
Wiladatika
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112907476-8a5f9e00-90b3-11eb-939a-1d4b3f49ee44.png)
