### ISSUE TITLE
KVDF-Tampa Executive-FLORIDA-USA

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#7095]
# Airport Name
Tampa Executive
# Country?
us
# Improvements that need to be made?
red0
# Are you working on this airport?
y3z
# Airport Priority? (10000ft+ Runway, Low)
I0w

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113067819-b433c600-9182-11eb-87fd-c541dbf02ac4.png)
