### ISSUE TITLE
AYGN-Gurney Airport-MILNE BAY-PAPUA NEW GUINEA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#7101]
# Airport Name
Gurney Airport
# Country?
PNG
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113211043-8f028e80-923a-11eb-92cd-92ffb018b490.png)
