### ISSUE TITLE
OEBQ-Abqaiq Airport-BUQAYQ-SAUDI ARABIA

### ISSUE THREAD

**Issue by SuhasIF** [InfiniteFlightAirportEditing/Airports#7102]
# Airport Name
Abqaiq
# Country?
Saudi Arabia
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114280452-e5bc5500-99fe-11eb-9109-e6a149be6928.png)
