### ISSUE TITLE
AYSL-Sehulea Airport-MILNE BAY-PAPUA NEW GUINEA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#7104]
# Airport Name
Sehulea Airport
# Country?
PNG
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113065068-daa33280-917d-11eb-8f42-9f39cea09367.png)
