### ISSUE TITLE
UMKE-Medovoye-KALININGRAD-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7105]
# Airport Name
Medovoye
# Country?
Russia
# Improvements that need to be made?
From scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
very low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113060517-5e592100-9176-11eb-971a-34d7359f0c36.png)
