### ISSUE TITLE
UMKS-Strelnya-KALININGRAD-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7106]
# Airport Name
Strelnya
# Country?
Russia
# Improvements that need to be made?
From scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Super low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113059862-8f852180-9175-11eb-9d0c-85a69a33888a.png)
