### ISSUE TITLE
KCIN-Arthur N Neu Airport-IOWA-USA

### ISSUE THREAD

**Issue by zhf21** [InfiniteFlightAirportEditing/Airports#7107]
# Airport Name
Arthur N Neu Airport.
# Country?
U.S.A.
# Improvements that need to be made?
Redo (auto-gen).
# Are you working on this airport?
Yes.
# Airport Priority? (10000ft+ Runway, Low)
Low.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114268944-9576d000-99c9-11eb-9a2f-322acc432f53.png)
