### ISSUE TITLE
MYAW-Walkers Cay Airport-ABACO ISLANDS-BAHAMAS

### ISSUE THREAD

**Issue by TristinWoolf** [InfiniteFlightAirportEditing/Airports#711]
Walkers Cay Airport

Very poor imagery, but will try my best to redo, as it is very small.

**Comment by TristinWoolf** [comment]
Imagery (as poor as it is on WEDBing) will not upload into WED. Google Earth appears to good imagery for the airport that is not blurry, so anyone that has Google Earth set up and knows how to import it into WED is welcome to do this airport. It is a very small airport with just a small runway and very small ramp, enough room for one GA spawn point. Would be a very quick and easy airport to do with proper imagery. It is now open for the taking!

**Comment by TristinWoolf** [comment]
Re-assigning myself to this one, as I have found a way around to get it done.

**Comment by TristinWoolf** [comment]
Redone. 

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/8cd33f459d89842bd8e8b86d8abd7d9ec2528060)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17348046/6adff776-58d9-11e6-905f-855b5cf63890.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17348197/618b93dc-58da-11e6-91d3-733126c8aa2f.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17387059/cb4ad432-59b5-11e6-8767-77790b311a0c.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33587468-e71f2d9e-d933-11e7-8951-81d678cc7d74.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/49046862-336ff400-f19b-11e8-8250-d084438c5533.png)
