### ISSUE TITLE
SSTQ-Silvestre Airport-AMAPA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#7112]
# Airport Name
Silvestre Airport
# Country?
Brazil
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113054097-a411eb80-916e-11eb-80ed-d85cbf9de3b0.png)
