### ISSUE TITLE
SNEG-Fazenda Netolandia-MATO GROSSO-BRAZIL

### ISSUE THREAD

**Issue by AviationDash** [InfiniteFlightAirportEditing/Airports#7113]
# Airport Name
Fazenda Netolandia
# Country?
Brazil
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by AviationDash** [comment]
@brunocr1050 Sorry, Made a mistake, Can you reassign me to this airport, clicked by mistake and I am not assigned anymore

Sorry for the incovinience

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113358471-77dfa180-930b-11eb-8e84-376ee29995bf.png)
