### ISSUE TITLE
LFLH-Chalon Champforgeuil Airport-CHAMPFORGEUIL-FRANCE

### ISSUE THREAD

**Issue by IFsami** [InfiniteFlightAirportEditing/Airports#7114]
# Airport Name
Chalon Champforgeuil Airport
# Country?
France
# Improvements that need to be made?
Full rework 
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113455308-e9812380-93cf-11eb-9d8c-962e7b9df947.png)
