### ISSUE TITLE
KBYI-Burley Municipal Airport-IDAHO-USA

### ISSUE THREAD

**Issue by RhysV29** [InfiniteFlightAirportEditing/Airports#7116]
# Airport Name
Burley Municipal Airport
# Country?
USA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115111635-d8dfba00-9f46-11eb-9c41-fa6791edca1d.png)
