### ISSUE TITLE
UAAR-Boralday Airport-AIMA ATA-KAZAKHSTAN

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#7117]
# Airport Name
Boralday
# Country?
Kazakhstan
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113210537-f9ff9580-9239-11eb-9e9b-be6f79949de6.png)
