### ISSUE TITLE
KCHN-Wauchula Municipal Airport-Florida-USA

### ISSUE THREAD

**Issue by LawinS** [InfiniteFlightAirportEditing/Airports#7119]
# Airport Name
Wauchula Municipal airport
# Country?
USA
# Improvements that need to be made?
Full redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115096783-3266cb00-9eec-11eb-9357-316f3fe12629.png)
