### ISSUE TITLE
KELP-El Paso International Airport-TEXAS-USA

### ISSUE THREAD

**Issue by samtheairportguy** [InfiniteFlightAirportEditing/Airports#712]
RECYCLED AGAIN.

**Comment by TristinWoolf** [comment]
Duplicate issue. Remember to always search the tracker to see if an issue already exists for it.
For further discussion go to #468  :)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28994274-b02271ec-798f-11e7-9f3d-abd54d5e1886.png)
