### ISSUE TITLE
WAHP-Purbalingga-JAWA-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#7120]
# Airport Name
Jendral Besar Sudirman
# Country?
Indonesia
# Improvements that need to be made
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113061397-93b23e80-9177-11eb-86b5-ea3ef8c48c19.png)
