### ISSUE TITLE
AYAF-Afore Airport-ORO-PAPUA NEW GUINEA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#7121]
# Airport Name
Afore Airport
# Country?
PNG
# Improvements that need to be made?
New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113454527-0fa5c400-93ce-11eb-9686-89bf8cb14979.png)
