### ISSUE TITLE
KOGD-Ogden-Hinckley Airport-UTAH-USA

### ISSUE THREAD

**Issue by LesterXavier** [InfiniteFlightAirportEditing/Airports#7122]
# Airport Name
Ogden-Hinckley Airport
# Country?
U.S.A. 🇺🇸 
# Improvements that need to be made?
Rework [from scratch]
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122845989-7f8b6280-d2ca-11eb-8071-29aea98a8364.png)
