### ISSUE TITLE
SARP-Posadas Airport-MISIONES-ARGENTINA

### ISSUE THREAD

**Issue by victormw22** [InfiniteFlightAirportEditing/Airports#7123]
# Airport Name
Posadas
# Country?
Argentina
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113451151-01a07500-93c7-11eb-93d1-7b67d10c71b4.png)
