### ISSUE TITLE
H96-Benton Municipal Airport-ILLINOIS-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7124]
# Airport Name
Benton Municipal Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113362726-a4e48200-9314-11eb-8af4-429a623b02a7.png)
