### ISSUE TITLE
7V7-Red Cloud Municipal Airport-NEBRASKA-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7125]
# Airport Name
Red Cloud Municipal Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113360372-4e287980-930f-11eb-87c4-6279fbfa3e61.png)
