### ISSUE TITLE
XRKH-Khanskaya-ADYGEA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7127]
# Airport Name
Maykop Khanskaya Air Base
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113506635-a1ffb200-950b-11eb-8583-ee1014c86af7.png)
