### ISSUE TITLE
XRKM-Oktyabrskiy-ADYGEA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7128]
# Airport Name
Maykop Oktyabrskiy
# Country?
Russia
# Improvements that need to be made?
from scratch
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113450650-f0a33400-93c5-11eb-9604-58da76fe24b0.png)
