### ISSUE TITLE
MYCA

### ISSUE THREAD

**Issue by TristinWoolf** [InfiniteFlightAirportEditing/Airports#713]
Arthurs Town Airport

Being redone.

**Comment by TristinWoolf** [comment]
Done.

**Comment by TristinWoolf** [comment]
Added airport beacon and UNICOM frequency.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19223828/d524efca-8e3e-11e6-8e58-921441146c24.png)
