### ISSUE TITLE
KFWB-Branson West Municipal Airport-MISSOURI-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7130]
# Airport Name
Branson West Municipal Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113359733-081ee600-930e-11eb-9651-e9a9be560a06.png)
