### ISSUE TITLE
SWFX-Sao Felix do Araguaia Airport-MATO GROSSO-BRAZIL

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#7131]
# Airport Name
Sao Felix do Araguaia Airport
# Country?
Brazil
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113437666-a8c3e300-93ac-11eb-8f17-63d61dcd871d.png)
