### ISSUE TITLE
SJHG-Confresa Airport-MATO GROSSO-BRAZIL

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#7132]
# Airport Name
Confresa Airport
# Country?
Brazil
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113437290-ff7ced00-93ab-11eb-8fcb-56d28ab5de66.png)
