### ISSUE TITLE
MM11-Rancho El Durangueño-DURANGO-MEXICO

### ISSUE THREAD

**Issue by AviationDash** [InfiniteFlightAirportEditing/Airports#7133]
# Airport Name
Rancho El Durangueño
# Country?
Mexico
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by zhf21** [comment]
I can do this.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124388903-82169080-dcaa-11eb-9aca-bf65de2a5cab.png)
