### ISSUE TITLE
KBYL-Williamsburg-Whitley County Airport-KENTUCKY-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7134]
# Airport Name
Williamsburg-Whitley County Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
- Old ICAO = W38, New ICAO = KBYL.
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113451926-9e174700-93c8-11eb-8226-de8ee2a310e3.png)
