### ISSUE TITLE
SWCA-Carauari Airport-AMAZONAS-BRAZIL

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#7135]
# Airport Name
Carauari Airport
# Country?
Brazil
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113436795-f8a1aa80-93aa-11eb-8c6f-613a66f8abd7.png)
