### ISSUE TITLE
RPMF-Bislig Community Airport-CARAGA-PHILIPPINES

### ISSUE THREAD

**Issue by LesterXavier** [InfiniteFlightAirportEditing/Airports#7136]
# Airport Name
Bislig Community Airport
# Country?
Philippines 🇵🇭 
# Improvements that need to be made?
Rework [from scratch]
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113450205-0bc17400-93c5-11eb-98e0-b1929e2a8ff1.png)
