### ISSUE TITLE
ORSU-Sulaymaniyah Int'l-SULAYMANIYAH-IRAQ

### ISSUE THREAD

**Issue by dklaffke** [InfiniteFlightAirportEditing/Airports#7138]
# Airport Name
Sulaymaniyah Int'l
# Country?
Iraq
# Improvements that need to be made?
Full redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
11,483ft 13/31

**Comment by TurkishCptArda737** [comment]
The source from FR24 shows me that the Airport elv. is 2,492

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/119224438-11356380-bac4-11eb-8c38-9e2041c9ed0c.png)
