### ISSUE TITLE
AYCS-China Strait Airport-MILNE BAY-PAPUA NEW GUINEA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#7139]
# Airport Name
China Strait Airport
# Country?
PNG
# Improvements that need to be made?
New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113492272-ef443b00-949b-11eb-9f95-617cfd38578a.png)
