### ISSUE TITLE
MYCB

### ISSUE THREAD

**Issue by TristinWoolf** [InfiniteFlightAirportEditing/Airports#714]
New Bight Airport

Being redone.

**Comment by TristinWoolf** [comment]
Done.

**Comment by TristinWoolf** [comment]
Added airport beacon.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19419326/ec728a0a-939a-11e6-9b74-64a8c905cd5a.png)
