### ISSUE TITLE
AYAG-Agaun Airport-MILNE BAY-PAPUA NEW GUINEA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#7140]
# Airport Name
Agaun
# Country?
PNG
# Improvements that need to be made?
New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113492136-32ea7500-949b-11eb-84e2-93e89ab26c43.png)
