### ISSUE TITLE
SWMW-Maues Airport-AMAZONAS-BRAZIL

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#7141]
# Airport Name
Maues Airport
# Country?
Brazil
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113435919-5d5c0580-93a9-11eb-858b-dbe51b0af835.png)
