### ISSUE TITLE
SBJH-Sao Paulo Catarina Executive Airport-SAO PAULO-BRAZIL

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#7142]
# Airport Name
Sao Paulo Catarina Executive Airport
# Country?
Brazil
# Improvements that need to be made?
New
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![Uploading image.png…]()
