### ISSUE TITLE
SBCD-Cacador Airport-SANTA CATARINA-BRAZIL

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#7144]
# Airport Name
Cacador Airport
# Country?
Brazil
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113491231-cd938580-9494-11eb-997b-1db69479a5f8.png)
