### ISSUE TITLE
SSFB-Francisco Beltrao Airport-PARANA-BRAZIL

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Airports#7145]
# Airport Name
Francisco Beltrao
# Country?
Brazil
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/133866780-582fcdfd-6f8f-4b98-aa7c-a242a9322139.png)
