### ISSUE TITLE
KKNB-Kanab Municipal Airport-UTAH-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7146]
# Airport Name?
Kanab Municipal Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113507609-2f91d080-9511-11eb-80de-61158cd6883c.png)
