### ISSUE TITLE
SDXE-Chacara Serradinho-SAO PAULO-BRAZIL

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#7147]
# Airport Name
Chacara Serradinho
# Country?
Brazil
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113490717-98396880-9491-11eb-8e70-38c226b55c83.png)
