### ISSUE TITLE
SDTB-Atibaia Airport-SAO PAULO-BRAZIL

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#7148]
# Airport Name
Atibaia Airport
# Country?
Brazil
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113490618-e9952800-9490-11eb-8350-c8fbcb9dacde.png)
