### ISSUE TITLE
MMCC-Ciudad Acuna Airport-COAHUILA-MEXICO

### ISSUE THREAD

**Issue by AviationDash** [InfiniteFlightAirportEditing/Airports#7149]
# Airport Name
Ciudad Acuna Airport
# Country?
Mexico
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by mervinjane** [comment]
i'll like to take

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116782404-80ccab80-aa4e-11eb-9f83-6583d4482622.png)
