### ISSUE TITLE
MYCH

### ISSUE THREAD

**Issue by TristinWoolf** [InfiniteFlightAirportEditing/Airports#715]
Hawks News Airport

Being redone.

**Comment by TristinWoolf** [comment]
Done. Had to build this one from scratch.

**Comment by TristinWoolf** [comment]
Forgot to add airport boundary. Adding it now.

**Comment by TristinWoolf** [comment]
Added airport beacon and UNICOM frequency.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19616261/e003bdec-97d3-11e6-90c5-677bfeadacee.png)
