### ISSUE TITLE
SSEZ-Espumoso Airport-RIO GRANDE DO SUL-BRAZIL

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#7158]
# Airport Name
Espumoso Airport
# Country?
Brazil
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113491043-7d67f380-9493-11eb-9e7e-1e9b74abf3fc.png)
