### ISSUE TITLE
LTAS-Zonguldak Çaycuma-ZONGULDAK-TURKEY

### ISSUE THREAD

**Issue by dklaffke** [InfiniteFlightAirportEditing/Airports#7159]
# Airport Name
Zonguldak Çaycuma 
# Country?
Turkey
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114228993-daa0f080-993c-11eb-99bc-67e18bcc122c.png)
