### ISSUE TITLE
LTFJ

### ISSUE THREAD

**Issue by turkish1941** [InfiniteFlightAirportEditing/Airports#716]
I will make this one

**Comment by turkish1941** [comment]
sent

**Comment by dushyants19** [comment]
Done. [Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/5b05481082d49e3570e32bfdbdc9ef8a718b2d94)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19583703/ae28c31e-9704-11e6-90ad-9a7aabad8b87.png)
