### ISSUE TITLE
S28-International Peace Garden-NORTH DAKOTA-USA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7160]
# Airport Name
Intl Peace Garden
# Country?
USA
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113507494-729f7400-9510-11eb-9c63-b1527cebfb47.png)
