### ISSUE TITLE
KCJR-Culpeper-VIRGINIA-USA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7161]
# Airport Name
Culpeper Rgnl
# Country?
USA
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114271383-aa0d9500-99d6-11eb-90ff-1d7af742f99a.png)
