### ISSUE TITLE
VLVT-Wattay International Airport-VIENTIANE-LAOS

### ISSUE THREAD

**Issue by MinhNguyN** [InfiniteFlightAirportEditing/Airports#7163]
# Airport Name
Wattay International Airport
# Country?
Laos
# Improvements that need to be made?
+Addition of new Taxiway
+Improved taxiway and linear feature geometry
+Addition of the new stands
+Taxiway material fixes
+...a lots
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by MinhNguyN** [comment]
Can anybody assign me back to this airport?, I'm still making it.

**Comment by brunocr1050** [comment]
Make sure to rejoin the server.

**Comment by MinhNguyN** [comment]
oh, I forgot about the server

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115120999-1871ca80-9f76-11eb-932d-5d92c9a80aa7.png)
