### ISSUE TITLE
VLPS-Pakse International Airport-CHAMPASAK-LAOS

### ISSUE THREAD

**Issue by MinhNguyN** [InfiniteFlightAirportEditing/Airports#7164]
# Airport Name
Pakse International Airport
# Country?
Laos
# Improvements that need to be made?
redo from nothing
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by MinhNguyN** [comment]
Can anybody assign me back to this airport?, I'm still making it.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115793580-f9b66e00-a391-11eb-9799-476ed6ab3fde.png)
