### ISSUE TITLE
SWTG-Fazenda Santa Marina-SAO PAULO-BRAZIL

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#7165]
# Airport Name
Fazenda Santa Marina
# Country?
Brazil
# Improvements that need to be made?
Redone (Currently has wrong ICAO in IF: SDAJ)
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113507158-69150c80-950e-11eb-9923-f5032c294353.png)
