### ISSUE TITLE
SDWI-Fazenda Lagoa do Cavalo-PERNAMBUCO-BRAZIL

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#7166]
# Airport Name
Fazenda Lagoa do Cavalo
# Country?
Brazil
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113507265-02442300-950f-11eb-8b30-689da96024e6.png)
