### ISSUE TITLE
SDDX-Fazenda Paiquere-SAO PAULO-BRAZIL

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#7167]
# Airport Name
Fazenda Paiquere
# Country?
Brazil
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113507064-ee4bf180-950d-11eb-82fa-2da5988661b7.png)
