### ISSUE TITLE
RPVT

### ISSUE THREAD

**Issue by ReflexRSM** [InfiniteFlightAirportEditing/Airports#717]
Requested by someone on a group chat. It's a small airport, should be done within minutes.

> Tagbilaran Airport is an airport serving the general area of Tagbilaran, the capital city of the province of Bohol in the Philippines.

**Comment by ReflexRSM** [comment]
Completed, sent for approval.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19614963/9c875cae-97bf-11e6-8a6a-bde6b30d2d15.png)
