### ISSUE TITLE
SSJA-Joaçaba Santa Terezinha Municipal Airport-SANTA CATARINA-BRAZIL

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#7174]
# Airport Name
Joaçaba Santa Terezinha Municipal Airport
# Country?
Brazil
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114116885-22773780-98ab-11eb-9c73-e353aa51c018.png)
