### ISSUE TITLE
SIBY-Monteiro Airport-PARAIBA-BRAZIL

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#7175]
# Airport Name
Monteiro Airport
# Country?
Brazil
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114116596-9533e300-98aa-11eb-8021-5f3c36eb95a4.png)
