### ISSUE TITLE
KCPR-Casper/Natrona County International Airport-WYOMING-USA

### ISSUE THREAD

**Issue by Daniboi737** [InfiniteFlightAirportEditing/Airports#7176]
# Airport Name
Casper–Natrona County International Airport
# Country?
USA
# Improvements that need to be made?
Redone from Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
10000ft+ Runway

**Comment by Daniboi737** [comment]
Is it alright if I do this? I just didn’t see the Message in the announcements channel and got removed, back again now.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122845666-d3e21280-d2c9-11eb-8797-7ace85b94819.png)
