### ISSUE TITLE
SPCL-David Armando Abensur Rengifo Airport-UCAYALI-PERU

### ISSUE THREAD

**Issue by victormw22** [InfiniteFlightAirportEditing/Airports#7177]
# Airport Name
David Armando Abensur Rengifo 
# Country?
Peru
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114269570-8eea5780-99cd-11eb-985d-0f1fa78366f2.png)
