### ISSUE TITLE
AYPQ-Pumani Airport-MILNE BAY-PAPUA NEW GUINEA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#7179]
# Airport Name
Pumani
# Country?
PNG
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114242808-1fcf1d80-9951-11eb-839a-a7011900761d.png)
