### ISSUE TITLE
MHTG-Toncontin Airport-FRANCISCO MORAZAN-HONDURAS

### ISSUE THREAD

**Issue by sumith11** [InfiniteFlightAirportEditing/Airports#718]
Toncontín International Airport. Will be doing this alongside HEL

You might have heard about this airport!
https://www.youtube.com/watch?v=v_z5HtME9n8

**Comment by AxelBeder** [comment]
Added to repro.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19594989/60149222-974d-11e6-9c1f-e3a73d9cdfb5.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54076337-41d8ac00-4270-11e9-91b7-33a61c0c2e22.png)
