### ISSUE TITLE
EBOS-Ostend–Bruges International Airport-VLAANDEREN-BELGIUM

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#7180]
# Airport Name
Ostend–Bruges International Airport
# Country?
Belgium
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
10000ft+

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114229955-256f3800-993e-11eb-8322-67402079218a.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114244679-87d33300-9954-11eb-8ad9-cea4a8bd306d.png)
