### ISSUE TITLE
HESC-St Catherine Airport-JANUB SINA-EGYPT

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#7183]
# Airport Name
St Catherine Airport
# Country?
Egypt
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114119315-0629c980-98b0-11eb-8fdf-26edcd11252f.png)
