### ISSUE TITLE
HETR-El Tor Airport-JANUB SINA-EGYPT

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#7184]
# Airport Name
El Tor Airport
# Country?
Egypt
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114117280-f90adb80-98ab-11eb-94b0-e4139f80d7ae.png)
