### ISSUE TITLE
LTFH-Samsun Çarşamba-SAMSUN-TURKEY

### ISSUE THREAD

**Issue by dklaffke** [InfiniteFlightAirportEditing/Airports#7185]
# Airport Name
Samsun Çarşamba
# Country?
Turkey
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115118301-26205380-9f68-11eb-8785-d5846c90e8dd.png)
