### ISSUE TITLE
MYCI

### ISSUE THREAD

**Issue by TristinWoolf** [InfiniteFlightAirportEditing/Airports#719]
Colonel Hill Airport

Being redone.

**Comment by TristinWoolf** [comment]
Done.

**Comment by TristinWoolf** [comment]
Added airport beacon and UNiCOM frequency.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19419305/7def2bf6-939a-11e6-96de-35913873dd1a.png)
