### ISSUE TITLE
KFAM-Farmington Regional Airport-MISSOURI-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7191]
# Airport Name
Farmington Regional Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114268822-d0c4cf00-99c8-11eb-9c12-d85c50fd79dd.png)
