### ISSUE TITLE
KHEG-Herlong Recreational Airport-FLORIDA-USA

### ISSUE THREAD

**Issue by RhysV29** [InfiniteFlightAirportEditing/Airports#7192]
# Airport Name
Herlong Recreational Airport
# Country?
USA
# Improvements that need to be made?
Full redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/120074611-452ffc00-c063-11eb-884c-f620f4cd111c.png)
