### ISSUE TITLE
KCGI-Cape Girardeau Regional Airport-MISSOURI-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7195]
# Airport Name
Cape Girardeau Regional Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114268682-ef769600-99c7-11eb-8fce-145555b2bab8.png)
