### ISSUE TITLE
ZSGZ-Ganzhou Huangjin-JIANGXI-CHINA

### ISSUE THREAD

**Issue by dklaffke** [InfiniteFlightAirportEditing/Airports#7197]
# Airport Name
Ganzhou Huangjin
# Country?
China
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115963497-2af38300-a4e5-11eb-957b-a29dbfdc03e0.png)
