### ISSUE TITLE
OPPS-Peshawar Bacha Khan Airport-KHYBER PAKHTUNKHWA-PAKISTAN

### ISSUE THREAD

**Issue by USMN13** [InfiniteFlightAirportEditing/Airports#7198]
# Airport Name
Peshawar Bacha Khan Intl
# Country?
Pakistan
# Improvements that need to be made?
Redo from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114785410-45d63280-9d42-11eb-9a14-8e67da56cd80.png)
