### ISSUE TITLE
OPKD-Hyderabad Airport-SINDH-PAKISTAN

### ISSUE THREAD

**Issue by USMN13** [InfiniteFlightAirportEditing/Airports#7199]
# Airport Name
Hyderabad
# Country?
Pakistan
# Improvements that need to be made?
Redo from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115120889-7356f200-9f75-11eb-8ddb-5f0977499701.png)
