### ISSUE TITLE
MYCP

### ISSUE THREAD

**Issue by TristinWoolf** [InfiniteFlightAirportEditing/Airports#720]
Pitts Town Airport

Being done from scratch.

**Comment by TristinWoolf** [comment]
Finished. Had to do this one from scratch with a Google orthophoto.

**Comment by TristinWoolf** [comment]
Added airport beacon.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19616191/d3c09344-97d2-11e6-85f8-90e5c1b2681b.png)
