### ISSUE TITLE
LTCW-Hakkari-Yüksekova Airport-HAKKARI-TURKEY

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#7201]
# Airport Name
Hakkari-Yüksekova Airport
# Country?
Turkey
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
RWY 11/29 10,499ft

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114228505-243d0b80-993c-11eb-830d-7dccb3074fa3.png)
