### ISSUE TITLE
KTVB-Cabool Memorial Airport-MISSOURI-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7202]
# Airport Name
Cabool Memorial Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114268573-58114300-99c7-11eb-9adb-5e2c681fd105.png)
