### ISSUE TITLE
SSIE-Teruel Ipanema Estancia Airport-MATO GROSSO DO SUL-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#7204]
# Airport Name
Teruel Ipanema Estancia Airport
# Country?
Brazil
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114110871-26508d00-989e-11eb-825e-f3e8dec9c1b8.png)
