### ISSUE TITLE
ZWTL-Turpan Jiaohe Airport-XINJIANG-CHINA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#7205]
# Airport Name
Turpan Jiaohe Airport
# Country?
CN
# Improvements that need to be made?
Redo/New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114287561-62662800-9a2d-11eb-92bd-a47ed78a8e71.png)
