### ISSUE TITLE
KPUC-Carbon County Regional Airport-UTAH-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7207]
# Airport Name
Carbon County Regional Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114268411-8b070700-99c6-11eb-93cb-b82207af718b.png)
