### ISSUE TITLE
UAAA-Almaty Airport-ALMATY-KAZAKHSTAN

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#721]
RECYCLED.

**Comment by dushyants19** [comment]
Search before posting #12

**Comment by dushyants19** [comment]
V bad, Pat.

**Comment by ErshovlaD** [comment]
Anyone make this airport? 
Can I take it for work?

**Comment by brunocr98** [comment]
@ErshovlaD do you still want it?

**Comment by brunocr98** [comment]
You're doing this airport right @ErshovlaD?

**Comment by ErshovlaD** [comment]
@brunocr98 you ask me just for interested or you wanna take it for doing?

**Comment by ErshovlaD** [comment]
@brunocr98 you ask me just for interested or you wanna take it for doing?

**Comment by brunocr98** [comment]
No, since you ask for do this airport and no one assigned you before. I'm not interested in Almaty.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26284889/cc76c44e-3e0a-11e7-88e9-766bc2046f27.png)

**Comment by Czechoslovaki** [comment]
Redoing this.

- Two taxiways missing between both runways
- Runway widths incorrect
- Terminal building to be removed
- Missing lines / missing line types / incorrect line types used
- ATC frequencies to be adjusted
- Some elements not drawn on any taxiway surface / some drawn poorly

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113492367-7b566280-949c-11eb-95d9-7076123549fc.png)
