### ISSUE TITLE
KLRY-Lawrence Smith Memorial Airport-MISSOURI-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7210]
# Airport Name
Lawrence Smith Memorial Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114287670-3bf4bc80-9a2e-11eb-996d-ca0409a5416b.png)
