### ISSUE TITLE
ZBAL-Alxa Left Banner Bayanhot Airport-INNER MONGOLIA-CHINA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#7215]
# Airport Name
Alxa Left Banner - Bayanhot
# Country?
CN
# Improvements that need to be made?
New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114784940-8c775d00-9d41-11eb-9c05-38e91985953a.png)
