### ISSUE TITLE
ZBAR-Alxa Right Banner Badanjilin Airport-INNER MONGOLIA-CHINA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#7216]
# Airport Name
Alxa Right Banner - Badanjilin
# Country?
CN
# Improvements that need to be made?
New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114784326-b11f0500-9d40-11eb-8830-c0b3ada66e6f.png)
