### ISSUE TITLE
ZBEN-Ejin Banner Taolai Airport-INNER MONGOLIA-CHINA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#7217]
# Airport Name
Ejin Banner - Taolai
# Country?
CN
# Improvements that need to be made?
New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115083350-d2146100-9ecc-11eb-97e9-d92f5e069cde.png)
