### ISSUE TITLE
KJES-Jesup-Wayne County Airport-GEORGIA-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7218]
# Airport Name
Jesup-Wayne County Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114303066-b0147c00-9a91-11eb-9351-de05dee0c1f4.png)
