### ISSUE TITLE
OBBI-Bahrain International Airport-MUHARRAQ-BAHRAIN

### ISSUE THREAD

**Issue by sumith11** [InfiniteFlightAirportEditing/Airports#722]
> BAH is the international airport of Bahrain, located in Muharraq. It serves as the hub for the national carrier Gulf Air.

**Comment by ReflexRSM** [comment]
Sent for approval.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18815516/eb4862dc-82f9-11e6-8bff-3f4419c70580.png)
REMOVED A380 DESIGNATIONS

**Comment by MajorTomMueller** [comment]
http://www.bahrainaims.com/eAIP/Publications/AIRAC%2006-20%2022420/2020-06-18-AIRAC/html/eAIP/OB-AD-2.OBBI-en-BH.html#AD-2.OBBI
The 7 Docking charts:
http://www.bahrainaims.com/eAIP/Publications/AIRAC%2006-20%2022420/2020-06-18-AIRAC/html/eAIP/OB-AD-2.OBBI-en-BH.html#OBBI-AD-2.24

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/88482337-34d06180-cf26-11ea-85f2-1262b850a748.png)
