### ISSUE TITLE
WAPN-Namniwel-MALUKU-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#7223]
# Airport Name
Namniwel
# Country?
Indonesia
# Improvements that need to be made?
Create New
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low Priority

**Comment by kilt46** [comment]
This is not correct- The airfield looks rotated
![image](https://user-images.githubusercontent.com/14023167/115991861-17e9bd00-a590-11eb-9ae5-565cab1b4cbe.png)
![image](https://user-images.githubusercontent.com/14023167/115991868-22a45200-a590-11eb-8b9d-d530bd6b9152.png)
![image](https://user-images.githubusercontent.com/14023167/115991878-318b0480-a590-11eb-8522-463956533cc1.png)

**Comment by kilt46** [comment]
This is actually WAPN!!!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116629675-57f5ca80-a917-11eb-9149-ee5339250f29.png)
