### ISSUE TITLE
KBBP-Marlboro County Jetport-SOUTH CAROLINA-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7224]
# Airport Name
Marlboro County Jetport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115111198-bfd60980-9f44-11eb-8069-21330a38f3c3.png)
