### ISSUE TITLE
KSOP-Moore County Airport-North Carolina-USA

### ISSUE THREAD

**Issue by LawinS** [InfiniteFlightAirportEditing/Airports#7225]
# Airport Name
Moore County airport

# Country?
United States Of America

# Improvements that need to be made?
Full rework

# Are you working on this airport?
Yes

# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115962584-c551c780-a4e1-11eb-90c8-b4771e9ef20f.png)
