### ISSUE TITLE
ZUTR-Tongren Fenghuang Airport-GUIZHOU-CHINA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#7234]
# Airport Name
Tongren Fenghuang
# Country?
CN
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by Daniel-Baiks** [comment]
Already assigned to 3 issues, 2 have been accepted

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114949554-e26a0480-9e16-11eb-8076-cd8151abe30f.png)
