### ISSUE TITLE
OEHW-Hawtah Airport-AL SAHIBAH-SAUDI ARABIA

### ISSUE THREAD

**Issue by SuhasIF** [InfiniteFlightAirportEditing/Airports#7235]
# Airport Name
Hawtah
# Country?
Saudi Arabia
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115116212-1734a380-9f5e-11eb-93c5-248a029dfdb3.png)
