### ISSUE TITLE
OEJF-King Faisal Naval Base-JEDDAH-SAUDI ARABIA

### ISSUE THREAD

**Issue by SuhasIF** [InfiniteFlightAirportEditing/Airports#7236]
# Airport Name
King Faisal Naval Base
# Country?
Saudi Arabia
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116478863-5f986f00-a844-11eb-8b8e-8fd7d5c0eff2.png)
