### ISSUE TITLE
OPSK-Sukkur Airport-SINDH-PAKISTAN

### ISSUE THREAD

**Issue by USMN13** [InfiniteFlightAirportEditing/Airports#7237]
# Airport Name
Sukkur
# Country?
Pakistan
# Improvements that need to be made?
Redo from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115941108-a9124400-a469-11eb-9734-dcd9fee7f61d.png)
