### ISSUE TITLE
ZLDL-Delingha Airport-QINGHAI-CHINA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#7238]
# Airport Name
Delingha
# Country?
CN
# Improvements that need to be made?
Redo/New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114949315-62dc3580-9e16-11eb-8174-07ce334b485e.png)
