### ISSUE TITLE
TNCC-Hato Curacao International Airport-WILLEMSTAD-CURACAO

### ISSUE THREAD

**Issue by SudarshanMahesh** [InfiniteFlightAirportEditing/Airports#724]
Who can assign me?

**Comment by dushyants19** [comment]
You are doing this.

**Comment by sudafly** [comment]
It's very hard to do, because there are clouds. What should i do?

**Comment by dushyants19** [comment]
So you dont want to do this?

**Comment by sudafly** [comment]
Did you know a way to bypass the clouds? If not, unassign me.

**Comment by dushyants19** [comment]
Yes, you can. You have to import scenery from Google maps.

**Comment by sudafly** [comment]
Yes i do that there are clouds

**Comment by sudafly** [comment]
Not doing this because there are clouds on the whole Airport

**Comment by brunocr98** [comment]
Doing this airport, please assign me.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20860031/6e6ad3a0-b934-11e6-8e87-eb9240135491.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54882919-1687bc80-4e2d-11e9-84f3-0710cee7cf0b.png)
