### ISSUE TITLE
CYVV-Wiarton Airport-ONTARIO-CANADA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#7240]
# Airport Name
Wiarton Airport
# Country?
Canada
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114948998-c0bc4d80-9e15-11eb-9a23-d71a29ccac62.png)
