### ISSUE TITLE
SAWL-Tolhuin Lago Fagnano Airport-TIERRA DEL FUEGO-ARGENTINA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#7241]
# Airport Name
Tolhuin Lago Fagnano Airport
# Country?
Argentina
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114938922-54395280-9e05-11eb-8555-948a543e97fb.png)
