### ISSUE TITLE
RCSP-Taiping Airport-SPRATLY ISLANDS-TAIWAN

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#7242]
# Airport Name
Taiping Airport
# Country?
Taiwan
# Improvements that need to be made?
Done from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115096118-80c69a80-9ee9-11eb-8a17-ede3118fd288.png)
