### ISSUE TITLE
OPRK-Rahim Yar Khan Airport-PUNJAB-PAKISTAN

### ISSUE THREAD

**Issue by USMN13** [InfiniteFlightAirportEditing/Airports#7243]
# Airport Name
Rahim Yar Khan
# Country?
Pakistan
# Improvements that need to be made?
Redo from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115941008-2a1d0b80-a469-11eb-8b48-ef45e4353a40.png)
