### ISSUE TITLE
NV42-Heritage Airport-NEVADA-USA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#7244]
# Airport Name
Heritage
# Country?
USA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115097008-60004400-9eed-11eb-93b4-750536797c99.png)
