### ISSUE TITLE
ZBTL-Tongliao Airport-INNER MONGOLIA-CHINA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#7245]
# Airport Name
Tongliao
# Country?
CHina
# Improvements that need to be made?
Redo/New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/117539419-2beddf80-afd0-11eb-8e7e-8197d5039dc2.png)
