### ISSUE TITLE
CAV6-Av-Ranch Airpark-MANITOBA-CANADA

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Airports#7246]
![V1](https://user-images.githubusercontent.com/59462519/114943625-2c1a1580-9e3e-11eb-8397-98b39448da2b.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/114948672-1ba17500-9e15-11eb-8889-3e035e476b5c.png)
