### ISSUE TITLE
KEFK-Northeast Kingdom International Airport-VERMONT-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7247]
# Airport Name
Northeast Kingdom International Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115960297-27a4cb00-a4d6-11eb-8cf1-b491e49bb95c.png)
