### ISSUE TITLE
8FL2-Kiever Airfield-FLORIDA-USA

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#7248]
# Airport Name
Kiever
# Country?
us
# Improvements that need to be made?
redoo doo
# Are you working on this airport?
ye
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115096431-b3bd5e00-9eea-11eb-8529-654809830aff.png)
