### ISSUE TITLE
SILQ-Clube de Ultraleves Aeroleve Airport-PARANA-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#7249]
# Airport Name
Clube de Ultraleves Aeroleve Airport
# Country?
Brazil
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115119775-c0d06080-9f6f-11eb-836f-0a5ef771e2b1.png)
