### ISSUE TITLE
EBNM-Namur-Suarlee Airport-WALLONIE-BELGIUM

### ISSUE THREAD

**Issue by SudarshanMahesh** [InfiniteFlightAirportEditing/Airports#725]
Current active airport. Needs some buildings

**Comment by dushyants19** [comment]
Check #724

**Comment by NickArt1342** [comment]
Are you doing this @kilt46 ? I  think you accidently assigned yourself.

**Comment by kilt46** [comment]
REDONE: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=EBNM

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18817361/f26a262a-8323-11e6-9636-39256509dea8.png)

**Comment by kilt46** [comment]
New Runway added
![image](https://user-images.githubusercontent.com/14023167/83335402-30fbc800-a272-11ea-86db-32f8a050aceb.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/96792368-dd744d00-13bf-11eb-9acf-1deef960d0e2.png)
