### ISSUE TITLE
TFFM-Marie Galante Airport-POINTE-A-PITRE-GUADELOUPE

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#7250]
# Airport Name
Marie Galante Airport
# Country?
Guadeloupe
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![Uploading image.png…]()
