### ISSUE TITLE
FA83-Orlando North Airpark-FLORIDA-USA

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#7251]
# Airport Name
Orlando north airpark
# Country?
usa
# Improvements that need to be made?
scratch
# Are you working on this airport?
YYEYEYYYYYASY
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115096282-0ea28580-9eea-11eb-8414-e6f002f149ff.png)
