### ISSUE TITLE
06FD-Grass Roots Airpark-FLORIDA-USA

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#7254]
# Airport Name
grass roots airpark
# Country?
u
# Improvements that need to be made?
scratch
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115143549-ab117880-a00d-11eb-94e2-184e73a6a84f.png)
