### ISSUE TITLE
0L9-Echo Bay-NEVADA-USA

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#7257]
# Airport Name
ECHO BAY
# Country?
USA
# Improvements that need to be made?
REDO
# Are you working on this airport?
YES
# Airport Priority? (10000ft+ Runway, Low)
LOW

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115155800-1b88bb80-a047-11eb-921f-04a1f0b1d24c.png)
