### ISSUE TITLE
1L3-Searchlight-NEVADA-USA

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#7258]
# Airport Name
Searchlight
# Country?
Us
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115959604-94b66180-a4d2-11eb-84ff-06608fa3dabe.png)
