### ISSUE TITLE
CEW5-Milk River Airport-ALBERTA-CANADA 

### ISSUE THREAD

**Issue by JulietTango-IF** [InfiniteFlightAirportEditing/Airports#7259]
# Airport Name
CEW5 
# Country?
Canada 
# Improvements that need to be made?
Full rework 
# Are you working on this airport?
Yes 
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115940077-e543a580-a465-11eb-9241-06581360f24e.png)
