### ISSUE TITLE
OMDW-Dubai/Al Maktoum International Airport-DUBAI-UNITED ARAB EMIRATES

### ISSUE THREAD

**Issue by SudarshanMahesh** [InfiniteFlightAirportEditing/Airports#726]
I do this, and there are no clouds ;)

**Comment by Swang007** [comment]
@sudafly, still working on this?

**Comment by sudafly** [comment]
@Swang007 Sure, i only need to place the Gates. http://smahesh6.wix.com/sudafly#!Faster-than-i-think/c0lp5/57640ff60cf2c6c57267c9b1

**Comment by sudafly** [comment]
This is delayed 5weeks. Sorry

**Comment by sudafly** [comment]
I'm back! I'm now doing some final mini bugs.

**Comment by sudafly** [comment]
There is a export problem with the aircraft shadows. I restarted WED and my laptop, but that doesn’t work. 

But i send it for approvenal

**Comment by dushyants19** [comment]
@sudafly any progress?

**Comment by ReflexRSM** [comment]
I'll be taking over OMDW as @sudafly is giving up on this one

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21751192/cd2841b4-d588-11e6-95db-a96e14ca4eb7.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/74934859-e2fb3c80-53c5-11ea-829c-5d5d5d26948f.jpg)
