### ISSUE TITLE
OPZB-Zhob Airport-BALOCHISTAN-PAKISTAN

### ISSUE THREAD

**Issue by USMN13** [InfiniteFlightAirportEditing/Airports#7261]
# Airport Name
Zhob
# Country?
Pakistan
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115940627-e1188780-a467-11eb-8ab6-435534d89ed7.png)
