### ISSUE TITLE
88NV-Black Rock City-NEVADA-USA

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#7262]
# Airport Name
black rock city
# Country?
USA
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low
# Fun Fact:
this airport is built along with a temporary city called Black Rock city in a dry lake bed for a few months, where the burning man event takes place, thousands of ppl build their own city where they party for a few months and then bring everything down

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115959458-eb6f6b80-a4d1-11eb-944c-76cbcbe7aed7.png)
