### ISSUE TITLE
UECT-Talakan Airport-YAKUTIA-RUSSIA

### ISSUE THREAD

**Issue by dklaffke** [InfiniteFlightAirportEditing/Airports#7267]
# Airport Name
Talakan Airport
# Country?
RU
# Improvements that need to be made?
full redo / add
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
10,171ft 01/19

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116628049-f41dd280-a913-11eb-97d8-a70b702c7c11.png)
