### ISSUE TITLE
KGPT-Gulfport-Biloxi International Airport-MISSISSIPPI-USA

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#7268]
# Airport Name
Gulfport-Biloxi International Airport
# Country?
USA
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116783013-01d97200-aa52-11eb-9353-5e23c19eacce.png)
