### ISSUE TITLE
FNCV-Cuito Cuanaval Airport-CUANDO CUBANGO-ANGOLA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#7273]
# Airport Name
Cuito Cuanaval Airport
# Country?
Angola
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115963306-5fb30a80-a4e4-11eb-99ed-2b392fc32b11.png)
