### ISSUE TITLE
KLUX-Laurens County Airport-SOUTH CAROLINA-USA

### ISSUE THREAD

**Issue by LawinS** [InfiniteFlightAirportEditing/Airports#7274]
# Airport Name
Laurens County Airport
# Country?
USA
# Improvements that need to be made?
Full redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116813109-cacd9400-ab17-11eb-9ab1-08b10b619dc7.png)
