### ISSUE TITLE
LFDK-Soulac Sur Mer-NOUVELLE AQUITAINE-FRANCE

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7275]
# Airport Name
Soulac Sur Mer
# Country?
France
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115958845-d80ed100-a4ce-11eb-8b33-b4678eb1663e.png)
