### ISSUE TITLE
LFEP-Pouilly Maconge-BOURGOGNE-FRANCE

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7276]
# Airport Name
Pouilly Maconge
# Country?
France
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115958756-528b2100-a4ce-11eb-9b6a-7d274f798bf6.png)
