### ISSUE TITLE
OPBW-Bahawalpur Airport-PUNJAB-PAKISTAN

### ISSUE THREAD

**Issue by USMN13** [InfiniteFlightAirportEditing/Airports#7277]
# Airport Name
Bahawalpur
# Country?
Pakistan
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115940460-461fad80-a467-11eb-9951-4cc1128f14d8.png)
