### ISSUE TITLE
LFEY-Ile D'yeu-PAYS DE LA LOIRE-FRANCE

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7278]
# Airport Name
Ile D'yeu
# Country?
France
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115957404-cece3600-a4c7-11eb-9c7e-3887f229aefa.png)
