### ISSUE TITLE
VLXK-Xieng Khouang-XIANGKHOUANG-LAOS

### ISSUE THREAD

**Issue by MinhNguyN** [InfiniteFlightAirportEditing/Airports#7279]
# Airport Name
Xieng Khouang
# Country?
Laos
# Improvements that need to be made?
Everything
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115792957-d0491280-a390-11eb-8cb0-2f35f34b3f92.png)
