### ISSUE TITLE
KJVY-Clark Regional Airport-INDIANA-USA

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#728]
Clark Rgnl

**Comment by kilt46** [comment]
Too many spawn points

**Comment by IFAEpat** [comment]
Gated

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17720146/4a5f44f4-63e5-11e6-906e-a6ebb8060a1a.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17720152/54413522-63e5-11e6-8cf9-aff232606565.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17720163/60075314-63e5-11e6-996e-7487c35edcdd.png)
