### ISSUE TITLE
VLLN-Louang Namtha-LUANG NAMTHA-LAOS

### ISSUE THREAD

**Issue by MinhNguyN** [InfiniteFlightAirportEditing/Airports#7280]
# Airport Name
Louangnamtha
# Country?
Laos
# Improvements that need to be made?
Everything
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115792633-3ed9a080-a390-11eb-83d6-29573daee167.png)
