### ISSUE TITLE
C24-Mineral County Memorial-COLORADO-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#7281]
# Airport Name
Mineral County Memorial
# Country?
USA
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115959239-de9e4800-a4d0-11eb-96da-d90ea882608b.png)
