### ISSUE TITLE
YPIR-Port Pirie Airport-SOUTH AUSTRALIA-AUSTRALIA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#7282]
# Airport Name
Port Pirie Airport
# Country?
Australia
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115957305-17392400-a4c7-11eb-8f5f-fdd63efe25d3.png)
