### ISSUE TITLE
KLUA-Luray Caverns Airport-VIRGINIA-USA

### ISSUE THREAD

**Issue by ToasterStroodie** [InfiniteFlightAirportEditing/Airports#7283]
# Airport Name
Luray Caverns Airport
# Country?
USA
# Improvements that need to be made?
Redo from scratch. Old ICAO = W45. New ICAO = KLUA. 
# Are you working on this airport?
Yes. 
# Airport Priority? (10000ft+ Runway, Low)
Low.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116324967-b8a1cd80-a786-11eb-91f7-71ce4e7fe8f2.png)
