### ISSUE TITLE
VLAP-Attapeu International Airport-ATTAPEU-LAOS

### ISSUE THREAD

**Issue by MinhNguyN** [InfiniteFlightAirportEditing/Airports#7284]
# Airport Name
Attapeu International Airport
# Country?
Laos
# Improvements that need to be made?
Everythings
# Are you working on this airport?
Yep
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115956552-025a9180-a4c3-11eb-8c23-15aba8f56de1.png)
