### ISSUE TITLE
KTGI-Tangier Island Airport-Virginia-USA

### ISSUE THREAD

**Issue by LawinS** [InfiniteFlightAirportEditing/Airports#7286]
# Airport Name
Tangier Island airport
# Country?
USA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116782928-8d063800-aa51-11eb-8383-c3d067cecd56.png)
