### ISSUE TITLE
KFNL-Northern Colorado Regional-COLORADO-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#7287]
# Airport Name
Northern Colorado Regional
# Country?
USA
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116751657-f6426880-a9c9-11eb-903a-1c28a4e862a8.png)
