### ISSUE TITLE
KPDC-Prairie du Chien Municipal Airport-WISCONSIN-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7289]
# Airport Name
Prairie du Chien Municipal Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115959049-e6112180-a4cf-11eb-901a-66104f4450ba.png)
