### ISSUE TITLE
CYEA-Empress Airport-ALBERTA-CANADA

### ISSUE THREAD

**Issue by JulietTango-IF** [InfiniteFlightAirportEditing/Airports#7290]
# Airport Name
Empress Airport 
# Country?
Canada 
# Improvements that need to be made?
Full rework 
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116625539-69d36f80-a90f-11eb-9beb-46c7004ec3e3.png)
