### ISSUE TITLE
KLKP-Lake Placid Airport-NEW YORK-USA

### ISSUE THREAD

**Issue by IFsami** [InfiniteFlightAirportEditing/Airports#7291]
# Airport Name
Lake Placid Airport
# Country?
USA
# Improvements that need to be made?
Full rework from generic airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/117542268-8c374e00-afdd-11eb-844a-7664a760402c.png)
