### ISSUE TITLE
ZYJZ-Jinzhou Bay Airport-LIAONING-CHINA

### ISSUE THREAD

**Issue by dklaffke** [InfiniteFlightAirportEditing/Airports#7292]
# Airport Name
Jinzhou Bay Airport
# Country?
CN
# Improvements that need to be made?
Yes
# Are you working on this airport?
Adding airport
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116782296-c76dd600-aa4d-11eb-8ff0-6cd97b897bca.png)
