### ISSUE TITLE
KBDJ-Boulder Junction Payzer Airport-WISCONSIN-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7293]
# Airport Name
Boulder Junction Payzer Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116322691-28fa2000-a782-11eb-881f-03b3a8639d8e.png)
