### ISSUE TITLE
OPDG-Dera Ghazi Khan Airport-PUNJAB-PAKISTAN

### ISSUE THREAD

**Issue by USMN13** [InfiniteFlightAirportEditing/Airports#7294]
# Airport Name
Dera Ghazi Khan
# Country?
Pakistan
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116629108-26c8ca80-a916-11eb-9b48-51f989fa3efa.png)
