### ISSUE TITLE
OPMJ-Moenjodaro Airport-SINDH-PAKISTAN

### ISSUE THREAD

**Issue by USMN13** [InfiniteFlightAirportEditing/Airports#7295]
# Airport Name
Moenjodaro
# Country?
Pakistan
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116628469-d4d37500-a914-11eb-9201-774ec8825b11.png)
