### ISSUE TITLE
OPNH-Nawabshah Airport-SINDH-PAKISTAN

### ISSUE THREAD

**Issue by USMN13** [InfiniteFlightAirportEditing/Airports#7296]
# Airport Name
Nawabshah
# Country?
Pakistan
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116780602-56292580-aa43-11eb-8095-6fb5f27e6720.png)
