### ISSUE TITLE
UWUA-Sibay-BASHKORTOSTAN-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7297]
# Airport Name
Sibay
# Country?
Russia
# Improvements that need to be made?
from scratch
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116627746-52968100-a913-11eb-9bae-f3a2b564bab9.png)
