### ISSUE TITLE
WABI-Nabire-PAPUA-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#7298]
# Airport Name
Nabire
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low Priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116629405-c71eef00-a916-11eb-9a3d-f5df131b880f.png)
