### ISSUE TITLE
4P3-Flandreau-SOUTH DAKOTA-USA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7299]
# Airport Name
Flandreau Muni
# Country?
US
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low ↓

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116311595-07dd0380-a771-11eb-9b6f-53badd219cd9.png)
