### ISSUE TITLE
WMKK-Kuala Lumpur International Airport-SELANGOR-MALAYSIA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#73]
This is mine. Nobody steal it.

**Comment by carmichaelalonso** [comment]
Finished.

**Comment by Swang007** [comment]
Lol I'm sorry @carmichaelalonso , but I'm sure you saw the guy on IFFG saying that the runways were in place but taxiways and terminals were not? Do you want to fix that or leave this issue up for grabs?

**Comment by carmichaelalonso** [comment]
To be honest I see this as a very minor thing, we can't expect 100% accuracy, especially with our current tools... I don't have time to tinker with this, but it's there for whoever wants it :)

**Comment by Swang007** [comment]
Awesome. I might look into it after I finish KLAX

**Comment by Swang007** [comment]
![wmkk](https://cloud.githubusercontent.com/assets/11000109/7785121/5936c148-0147-11e5-81b7-594bdc4dbc29.jpg)

**Comment by kohanson** [comment]
Guys sorry, I have to give up on this as i have been trying to figure out the overlay for the pass few hours and the creator of the map has too many objects on the list and are not group together.

**Comment by Swang007** [comment]
Alright I'll look at it I guess unless someone else is up for it. I'll probably delete everything and restart from scratch... lol that's me ;)

**Comment by kilt46** [comment]
Gate tidy up

**Comment by kilt46** [comment]
Compared to WEDbing this airport is off

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/11289820/0044af36-8ef6-11e5-8331-9a5d7add5a78.png)

**Comment by kilt46** [comment]
Red terminal centered on airport and satellite. Looks like a scaling issue.

**Comment by JcFl4** [comment]
Finished! Lacks roads, but I will add them after Christmas.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17876319/ed927912-689e-11e6-86f1-94f40f647d50.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17876325/09ea0878-689f-11e6-9b38-49828a2b1069.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17876351/37b0965a-689f-11e6-889d-9eb12154784a.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17876378/4b42b2ca-689f-11e6-883e-3638516d2860.png)

**Comment by kilt46** [comment]
RW15 - RW33 is not lined up with satellite, southern section of airport is scaled incorrectly. Suggest a REDO
Gates K24/K22/K20 show the disparity the best!
![image](https://user-images.githubusercontent.com/14023167/27955359-15d9654e-62da-11e7-9f14-63bb6bde80fc.png)

**Comment by haociek** [comment]
I'll try to do this......  *fingerscrossed*

**Comment by kilt46** [comment]
Please remove ALL Buildings on completion

**Comment by Khairuddinxd** [comment]
Is it new updated airport

**Comment by brunocr98** [comment]
As you can see, this airport is still being fixed. Please be patient until it's fixed, thanks.

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by kztmtn** [comment]
I'll redo this.

**Comment by kztmtn** [comment]
![WMKK-git](https://user-images.githubusercontent.com/46369763/83732997-dbffed80-a687-11ea-92e3-e982adfdc7c2.jpg)
