### ISSUE TITLE
ENBR-Bergen Flesland Airport-HORDALAND-NORWAY

### ISSUE THREAD

**Issue by henrikbg** [InfiniteFlightAirportEditing/Airports#730]
Bergen Airport, Flesland.

**Comment by henrikbg** [comment]
Redone.

**Comment by henrikbg** [comment]
Changing taxi line attributes and adding north taxiway.

**Comment by dushyants19** [comment]
@henrikbg hows this going

**Comment by henrikbg** [comment]
Very well, thanks for asking. Pretty sure I've already committed this.

**Comment by PaulNielsen** [comment]
Why is it still open than? :thinking:

**Comment by henrikbg** [comment]
Maybe I forgot to close it? ¯\_(ツ)_/¯

**Comment by PaulNielsen** [comment]
Bad Henrik 😡

**Comment by henrikbg** [comment]
Chill. Now work on airports.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19987342/afcc3342-a1e8-11e6-872e-35e0ba39c5b2.png)

**Comment by MajorTomMueller** [comment]
New terminal showed in sat imagery.

**Comment by MajorTomMueller** [comment]
-Buildings removed
-PAPI's added
-Markings and Lighting updated
-GA Area and spawns added
-New Terminal and spawns added
-Flesland Air Station added

![enbr-git](https://user-images.githubusercontent.com/26853210/52810433-d47f9400-3092-11e9-857c-b6e8358f4a8f.jpg)
