### ISSUE TITLE
HHMS-Massawa Airport-DEBUB-ERITREA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#7300]
# Airport Name
Massawa Airport
# Country?
Eritrea
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Priority 2 (10000ft+ Rwy)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115991755-85491e00-a58f-11eb-971c-61f737a58140.png)
