### ISSUE TITLE
SMTB-Tafelberg Airport-SURINAME

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Airports#7301]
# Airport Name
Tafelberg Airport
# Country?
Surinam
# Improvements that need to be made?
scratch 
# Are you working on this airport?
no
# Airport Priority? (10000ft+ Runway, Low)
low

coordinates: 3.7875, -56.15
AIP not available, ICAO listed here:

http://www.cadsur.sr/1%20AIP%20SURINAME%206th%20EDITION.pdf

Attention: coordinates in several sources are significant wrong!
![9FA6E814-C83E-4058-A686-1A32EA453394](https://user-images.githubusercontent.com/26853210/115964802-6bbfbc00-a526-11eb-8850-07c3a3a1e96b.jpeg)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124355411-9426ff00-dbd6-11eb-850a-0f624819cd58.png)
