### ISSUE TITLE
UWUO-Pervushino-BASHKORTOSTAN-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7302]
# Airport Name
Pervushino
# Country?
Russia
# Improvements that need to be made?
from scratch
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116626589-21b54c80-a911-11eb-82fb-98671bb6f513.png)
