### ISSUE TITLE
HABD-Bahir Dar Airport-AMHARA-ETHIOPIA 

### ISSUE THREAD

**Issue by Noxu21** [InfiniteFlightAirportEditing/Airports#7304]
# Airport Name
Bahir Dar
# Ethiopia
Enter text here
# Start from scratch
Enter text here
# Yes
Enter text here
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by MajorTomMueller** [comment]
![HABD-git](https://user-images.githubusercontent.com/26853210/132132227-93fd6b34-bd2f-42eb-b297-0415f8a8fcd8.png)
