### ISSUE TITLE
VLOS-Oudomsay Airport-OUDUMXAI-LAOS

### ISSUE THREAD

**Issue by MinhNguyN** [InfiniteFlightAirportEditing/Airports#7306]
# Airport Name
Oudomsay Airport
# Country?
Laos
# Improvements that need to be made?
Everythings
# Are you working on this airport?
Yep
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116478400-9d48c800-a843-11eb-9f9d-68b9d84dff39.png)
