### ISSUE TITLE
VLSN-Nathong Airport-HOUAPHAN-LAOS

### ISSUE THREAD

**Issue by MinhNguyN** [InfiniteFlightAirportEditing/Airports#7307]
# Airport Name
Nathong Airport
# Country?
Laos
# Improvements that need to be made?
Everything
# Are you working on this airport?
Yup
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116478040-1dbaf900-a843-11eb-891a-68d222f7c29f.png)
