### ISSUE TITLE
KHOE-Homerville Airport-GEORGIA-USA

### ISSUE THREAD

**Issue by SuhasIF** [InfiniteFlightAirportEditing/Airports#7308]
# Airport Name
Homerville
# Country?
USA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/119581101-871d2180-bd87-11eb-8c3b-8fa731be7ccb.png)
