### ISSUE TITLE
KHYR-Sawyer County Airport-WISCONSIN-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7309]
# Airport Name
Sawyer County Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116321830-75dcf700-a780-11eb-9597-4de70b132ef1.png)
