### ISSUE TITLE
ENSB-Svalbard/Longyear Airport-SVALBARD-NORWAY

### ISSUE THREAD

**Issue by henrikbg** [InfiniteFlightAirportEditing/Airports#731]
Svalbard Airport.

**Comment by henrikbg** [comment]
Redone.

**Comment by henrikbg** [comment]
Changed line attributes and moved some buildings.

**Comment by JcFl4** [comment]
Redoing it, as out of date and taxiways and lines are not parallel.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18611163/fd9ea1d4-7cf6-11e6-9292-bfa46fabb8b0.png)
