### ISSUE TITLE
VNLD-Lamidada Airport-Province 1-Nepal

### ISSUE THREAD

**Issue by Captainflight** [InfiniteFlightAirportEditing/Airports#7310]
# Airport Name
Lamidada Airport
# Country?
Nepal
# Improvements that need to be made?
Rework from Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116782105-ea4bba80-aa4c-11eb-8011-76c8e6e439ea.png)
