### ISSUE TITLE
OERR-Arar Airport-Al ḤUDUD AS SAMAIYYA-SAUDI ARABIA

### ISSUE THREAD

**Issue by M3RKZ** [InfiniteFlightAirportEditing/Airports#7311]
# Airport Name
Arar Airport
# Country?
Saudia Arabia 
# Improvements that need to be made?
Rework from Scratch
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116385537-7efcb100-a7de-11eb-9c75-964808757c7a.png)
