### ISSUE TITLE
KIDP-Independence Muni-Kansas-USA

### ISSUE THREAD

**Issue by StickThelanding** [InfiniteFlightAirportEditing/Airports#7312]
# Airport Name
Independence Muni
# Country?
USA
# Improvements that need to be made?
Auto Gen so full rework
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by StickThelanding** [comment]
I am going to stop work on this airport until there is better images in spots. 
<img width="254" alt="Screen Shot 2021-05-08 at 10 29 15 PM" src="https://user-images.githubusercontent.com/80503388/117561593-faffc000-b04c-11eb-80a9-bca9da144a78.png">

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124367175-8c894980-dc1a-11eb-9af0-fb83a0858f0b.png)
