### ISSUE TITLE
KSBO-East Georgia Regional Airport-GEORGIA-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7314]
# Airport Name
East Georgia Regional Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116782726-70b5cb80-aa50-11eb-8401-47b5e979f932.png)
