### ISSUE TITLE
VLSB-Sayaboury Airport-SAINYABULI-LAOS

### ISSUE THREAD

**Issue by MinhNguyN** [InfiniteFlightAirportEditing/Airports#7315]
# Airport Name
Sayaboury Airport
# Country?
Laos
# Improvements that need to be made?
Everythings
# Are you working on this airport?
Yep
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116781798-f8004080-aa4a-11eb-94cf-18e91c9b4fa6.png)
