### ISSUE TITLE
VLFL-Boun Neua Airport-PHONGSALY-LAOS

### ISSUE THREAD

**Issue by MinhNguyN** [InfiniteFlightAirportEditing/Airports#7316]
# Airport Name
Boun Neua Airport
# Country?
Laos
# Improvements that need to be made?
Everything
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by MinhNguyN** [comment]
This is the last Laos airport, yayyy

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116781725-6d1f4600-aa4a-11eb-85f3-b22712736bd1.png)
