### ISSUE TITLE
KIAB-McConnell AFB-KANSAS-USA

### ISSUE THREAD

**Issue by CaptRiley** [InfiniteFlightAirportEditing/Airports#7318]
♻️

**Comment by brennanhackard** [comment]
Duplicate #5039

**Comment by Czechoslovaki** [comment]
Mine now.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118726066-689eaf80-b7f6-11eb-95c9-6cd3d845fdcc.png)
