### ISSUE TITLE
KCBM-Columbus AFB-MISSISSIPPI-USA

### ISSUE THREAD

**Issue by CaptRiley** [InfiniteFlightAirportEditing/Airports#7319]
♻️

**Comment by brennanhackard** [comment]
Duplicate #5034

**Comment by Czechoslovaki** [comment]
Mine.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118725502-a5b67200-b7f5-11eb-8536-01009da08503.png)
