### ISSUE TITLE
ENBO-Bodo Airport-NORDLAND-NORWAY

### ISSUE THREAD

**Issue by henrikbg** [InfiniteFlightAirportEditing/Airports#732]
Bodo Airport.

**Comment by dushyants19** [comment]
@henrikbg still doing this?

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by MajorTomMueller** [comment]
I will take this if no one else would like to do so...

**Comment by moritzbabl** [comment]
Added

**Comment by MajorTomMueller** [comment]
![enbo-overview](https://user-images.githubusercontent.com/26853210/28023142-4c5581ba-658d-11e7-976b-f4dbd2dd94a2.jpeg)

**Comment by MajorTomMueller** [comment]
Adjusted Shelter Spawns
removed unrealistic Hangar Spawns

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/40268472-59ff76f8-5b33-11e8-8ebb-587458d424aa.png)

**Comment by MajorTomMueller** [comment]
Spawn sizes need to be corrected

**Comment by MajorTomMueller** [comment]
fixes tweaked, adepted to current rules
