### ISSUE TITLE
KOTM-Ottumwa Regional Airport-IOWA-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7321]
# Airport Name
Ottumwa Regional Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116782616-e2414a00-aa4f-11eb-817f-72725a05b081.png)
