### ISSUE TITLE
VAPR-Porbandar Airport-GUJARAT-INDIA

### ISSUE THREAD

**Issue by mervinjane** [InfiniteFlightAirportEditing/Airports#7322]
# Airport Name
Porbandar Airport
# Country?
India
# Improvements that need to be made?
It is auto generated and i'll like to edit it completely
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118896566-25b00b00-b8ce-11eb-9995-93278d22b168.png)
