### ISSUE TITLE
USDD-Salekhard Airport-YAMALO-NENETS-RUSSIA

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#7325]
# Airport Name
Salekhard Airport
# Country?
RU
# Improvements that need to be made?
Rework/added
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by AleksanderIF** [comment]
Oh, my precious. I'll take it

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/120074867-73faa200-c064-11eb-9d61-996d9707dc5a.png)
