### ISSUE TITLE
KJAC

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#733]
— Jackson Hole

- Inaccurate Border, Beacon and Tower
- Missing spawns
- Unneeded terrain and parking lot

**Comment by Padi3-14** [comment]
Is this one taken?

**Comment by IFAEpat** [comment]
No @Padi3-14, would you like to do it?

**Comment by Padi3-14** [comment]
Sure!

**Comment by Padi3-14** [comment]
WED isn't letting me make points on a taxi line, so I can't snap other taxi lines to it

**Comment by Padi3-14** [comment]
I'm pressing alt+click, but nothing's happening

**Comment by Padi3-14** [comment]
I fixed the border , beacon, and the tower, added the missing parking spots, and deleted the unneeded parking lots.
I also added in buildings, hangers, and adjusted/ added some missing taxiways, and taxi lines.

**Comment by samuelandersson** [comment]
@Padi3-14 I don't see this committed. Has anyone answered the email you sent yet?

**Comment by Padi3-14** [comment]
Nope. I submitted it via email and I haven't received a response yet.

Sent from my iPhone

On Jun 26, 2016, at 15:02, samuelandersson <notifications@github.com<mailto:notifications@github.com>> wrote:


@Padi3-14<https://github.com/Padi3-14> I don't see this committed. Has anyone answered the email you sent yet?

-

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20238355/b516c232-a8ae-11e6-8f1f-44cd588dae62.png)
