### ISSUE TITLE
05D-New Town-NORTH DAKOTA-USA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7332]
# Airport Name
New Town Muni
# Country?
US
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116782488-04869800-aa4f-11eb-9efb-13e6d2dfb11f.png)
