### ISSUE TITLE
UWUS-Sterlitamak-BASHKORTOSTAN-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7333]
# Airport Name
Sterlitamak
# Country?
Russia
# Improvements that need to be made?
from scratch
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116780996-a1dcce80-aa45-11eb-8e7a-3cb8e9b2cbf1.png)
