### ISSUE TITLE
XWOK-Kumertau-BASHKORTOSTAN-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7334]
# Airport Name
Kumertau
# Country?
Russia
# Improvements that need to be made?
from scratch
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116780798-55dd5a00-aa44-11eb-8a59-dcc255e5fc4c.png)
