### ISSUE TITLE
OPKW-Kadanwari Airport-SINDH-PAKISTAN

### ISSUE THREAD

**Issue by USMN13** [InfiniteFlightAirportEditing/Airports#7335]
# Airport Name
Kadanwari
# Country?
Pakistan
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116780426-5a087800-aa42-11eb-9393-052bee773567.png)
