### ISSUE TITLE
CO39-Flying G Air Ranch-COLORADO-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#7337]
# Airport Name
Flying G Air Ranch
# Country?
USA
# Improvements that need to be made?
Added
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116751124-2e957700-a9c9-11eb-9a59-3839587bb4d8.png)
