### ISSUE TITLE
KLAA-Southeast Colorado Regional Airport-COLORADO-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7338]
# Airport Name
Southeast Colorado Regional Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116750749-8bdcf880-a9c8-11eb-9397-4df15b21bb23.png)
