### ISSUE TITLE
WA93-Eliza Island-WASHINGTON-USA

### ISSUE THREAD

**Issue by RobertineIFC** [InfiniteFlightAirportEditing/Airports#7339]
# Airport Name
Eliza Island
# Country?
USA
# Improvements that need to be made?
Everything
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124367089-f6edba00-dc19-11eb-9e4e-135f5471e731.png)
