### ISSUE TITLE
NZQN-Queenstown Airport-OTAGO-NEW ZEALAND

### ISSUE THREAD

**Issue by lachieee** [InfiniteFlightAirportEditing/Airports#734]
Queenstown Airport - NZ

**Comment by dushyants19** [comment]
Do you want to do this? @lachieee

**Comment by lachieee** [comment]
Yep @dushyants19

**Comment by lachieee** [comment]
5/09/16 Still finishing this airport. Will be busy for the next two and a half months however and will continue after.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20778001/7671adc2-b730-11e6-8621-073a86770284.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111558951-b008b100-875d-11eb-80cd-5ac426086a6b.png)
