### ISSUE TITLE
OPPG-Panjgur Airport-BALOCHISTAN-PAKISTAN

### ISSUE THREAD

**Issue by USMN13** [InfiniteFlightAirportEditing/Airports#7340]
# Airport Name
Panjgur 
# Country?
Pakistan
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116780078-d188d800-aa3f-11eb-807e-69399a59c2b3.png)
