### ISSUE TITLE
UWKJ-Yoshkar-Ola-MARI EL-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7341]
# Airport Name
Yoshkar-Ola
# Country?
Russia
# Improvements that need to be made?
from scratch
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116931816-191d8880-ac27-11eb-8d56-74968ad8e00c.png)
