### ISSUE TITLE
XWKD-Danilovo-MARI EL-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7342]
# Airport Name
Yoshkar-Ola / Danilovo
# Country?
Russia
# Improvements that need to be made?
from scratch
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116931310-77963700-ac26-11eb-8dfa-6d5bd933197a.png)
