### ISSUE TITLE
MO74-Cedar Creek Airport-MISSOURI-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7343]
# Airport Name
Cedar Creek Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116813001-35ca9b00-ab17-11eb-9017-712f0fb2d96b.png)
