### ISSUE TITLE
W78-William M Tuck Airport-VIRGINIA-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7344]
# Airport Name
William M Tuck Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116812873-aae9a080-ab16-11eb-9011-9413246f1ff0.png)
