### ISSUE TITLE
OPSS-Saidu Sharif Airport-KHYBER PAKHTUNKHWA-PAKISTAN

### ISSUE THREAD

**Issue by USMN13** [InfiniteFlightAirportEditing/Airports#7345]
# Airport Name
Saidu Sharif
# Country?
Pakistan
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116933056-a7463e80-ac28-11eb-8ca9-d3198342e3e2.png)
