### ISSUE TITLE
USRO-Noyabrsk Airport-YAMALO-NENETS-RUSSIA 

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#7347]
# Airport Name
Noyabrsk Airport
# Country?
mother russia
# Improvements that need to be made?
redo/add
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by AleksanderIF** [comment]
the octagons are mine!!!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/120074732-def7a900-c063-11eb-9cfb-7d953ff5cc43.png)
