### ISSUE TITLE
GMMB-Benslimane Airport-CHAOUIA-GUARDIGHA-MOROCCO

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#7349]
# Airport Name
Benslimane Airport
# Country?
Morocco
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116932434-e031e380-ac27-11eb-9271-f48ccb248814.png)
