### ISSUE TITLE
KXWA-Williston Basin International Airport-NORTH DAKOTA-USA

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#7351]
# Airport Name
Williston Basin International Airport
# Country?
USA
# Improvements that need to be made?
New
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116812773-1bdc8880-ab16-11eb-92f3-cbbfc228c2c4.png)
