### ISSUE TITLE
ZBES-Arxan Yi'ershi Airport-INNER MONGOLIAN-CHINA

### ISSUE THREAD

**Issue by TsurugiHina** [InfiniteFlightAirportEditing/Airports#7352]
# Airport Name
Aershan Yiershi Airport
# Country?
China
# Improvements that need to be made?
New
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by Czechoslovaki** [comment]
Please identify yourself.

**Comment by TsurugiHina** [comment]
Wait, I'm not part of IFAET?

**Comment by brunocr1050** [comment]
@TsurugiHina have you applied through the Infinite Flight Community?

**Comment by TsurugiHina** [comment]
Yes

**Comment by Daniel-Baiks** [comment]
I can take this

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123510850-6294bd80-d643-11eb-9304-6c6272515be5.png)
