### ISSUE TITLE
CO33-Ria Airport-COLORADO-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#7353]
# Airport Name
Ria
# Country?
USA
# Improvements that need to be made?
added
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116812656-6f9aa200-ab15-11eb-819c-0466716faee6.png)
