### ISSUE TITLE
KMOT-Minot International Airport-NORTH DAKOTA-USA

### ISSUE THREAD

**Issue by CaptRiley** [InfiniteFlightAirportEditing/Airports#7354]
# Airport Name
Minot International Airport
# Country?
USA
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by GBKarp** [comment]
@CaptRiley are you still working on this?

**Comment by CaptRiley** [comment]
Yes

**Comment by brunocarbone3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/134600037-172a2600-450e-4451-9bb3-322449777ca5.png)
