### ISSUE TITLE
CO29-Juniper Hills Airstrip-COLORADO-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#7355]
# Airport Name
Juniper Hills Airstrip
# Country?
USA
# Improvements that need to be made?
added
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116812563-f8650e00-ab14-11eb-8317-7bcf2c9a257e.png)
