### ISSUE TITLE
CO25-Metrogro Farm-COLORADO-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#7359]
# Airport Name
Metrogro Farm
# Country?
USA
# Improvements that need to be made?
added to IF
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116812451-69f08c80-ab14-11eb-9fa3-5377d71574c2.png)
