### ISSUE TITLE
GA14-Pinebloom Plantation Airport-GEORGIA-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7361]
# Airport Name
Pinebloom Plantation Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116936881-08244580-ac2e-11eb-82b6-8e41f5e745a3.png)
