### ISSUE TITLE
SWNK-Novo Campo Airport-AMAZONAS-BRAZIL

### ISSUE THREAD

**Issue by HenriqueChen** [InfiniteFlightAirportEditing/Airports#7362]
# Airport Name
Novo Campo Airport
# Country?
Brazil
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by HenriqueChen** [comment]
Sent to OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/120076340-a5766c00-c06a-11eb-8496-3fea13a2a4e2.png)
