### ISSUE TITLE
GA83-Windy Hill Airport-GEORGIA-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7363]
# Airport Name
Windy Hill Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116936481-89c7a380-ac2d-11eb-9f06-baabc4bd2b29.png)
