### ISSUE TITLE
KHBC-Mohall-NORTH DAKOTA-USA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7364]
# Airport Name
Mohall Muni
# Country?
US
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
super low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116935486-0a85a000-ac2c-11eb-9ecd-84aa76b3a04a.png)
