### ISSUE TITLE
KLRD-Laredo International Airport-TEXAS-USA

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#7365]
# Airport Name
Laredo International Airport
# Country?
USA
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118724454-40ae4c80-b7f4-11eb-8944-15fff119cdb6.png)
