### ISSUE TITLE
FB62-Piajio-NORTH-WEST-BOTSWANA

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#7367]
# Airport Name
Piajio
# Country?
south africa's hat
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116930249-220d5a80-ac25-11eb-8a9d-92daea108b37.png)
