### ISSUE TITLE
ENSG-Sogndal-NORWAY

### ISSUE THREAD

**Issue by henrikbg** [InfiniteFlightAirportEditing/Airports#737]
Sogndal Airport.

**Comment by henrikbg** [comment]
WEDBing imagery isn't the best for this airport. I'll attempt orthophotos but it'll take time.

**Comment by dushyants19** [comment]
@henrikbg hows this going? and #731

**Comment by henrikbg** [comment]
Someone else can feel free to take this. Not too good with orthophotos and have other priorities at the moment.

**Comment by moritzbabl** [comment]
Not a big deal with SAS, will do it

**Comment by moritzbabl** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21944773/8987c75e-d99d-11e6-9e8d-58457d16ad16.png)
