### ISSUE TITLE
KGGI-Grinnell Regional Airport-IOWA-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7370]
# Airport Name
Grinnell Regional Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/117081710-0ded5a00-ad06-11eb-9ea6-fec459f6acbd.png)
