### ISSUE TITLE
VA1C-Birlagram Airport-MADHYA PRADESH-INDIA

### ISSUE THREAD

**Issue by mervinjane** [InfiniteFlightAirportEditing/Airports#7371]
# Airport Name
Birlagram Airport - VA1C
# Country?
India
# Improvements that need to be made?
It is autogen, complete rework.
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by KaalicharanDH** [comment]
I will do it

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118896042-f3ea7480-b8cc-11eb-955e-08eb51d12c59.png)
