### ISSUE TITLE
UNBA-Kosh-Agach-ALTAI REPUBLIC-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7372]
# Airport Name
Kosh-Agach
# Country?
Russia
# Improvements that need to be made?
from scratch
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/117075928-39b71280-acfb-11eb-9f6f-9aa20aec9384.png)
