### ISSUE TITLE
UNBI-Biysk Airport-ALTAI KRAI-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7373]
# Airport Name
Biysk
# Country?
Russia
# Improvements that need to be made?
from scratch
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/117074395-de842080-acf8-11eb-8127-49f1a5177d89.png)
