### ISSUE TITLE
UNBU-Ust-Koksa Airport-ALTAI REPUBLIC-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7374]
# Airport Name
Ust-Koksa
# Country?
Russia
# Improvements that need to be made?
from scratch
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/117073501-9f090480-acf7-11eb-9cf3-2b2e7bf3705e.png)
