### ISSUE TITLE
MMSL-Cabo San Lucas Airport-BAJA CALIFORNIA SUR-MEXICO

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#7375]
# Airport Name
Cabo San Lucas Airport
# Country?
Mexico
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116929614-4a488980-ac24-11eb-9774-c85c765d3b4f.png)
