### ISSUE TITLE
KMOX-Morris Municipal Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7376]
# Airport Name
Morris Municipal Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/117077533-e8f4e900-acfd-11eb-813f-3f68d315aa6b.png)
