### ISSUE TITLE
MMPL-Punta Colorada Airport-BAJA CALIFORNIA SUR-MEXICO

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#7377]
# Airport Name
Punta Colorada Airport
# Country?
Mexico
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/117540252-ed5a2400-afd3-11eb-8b06-3f696d92d9e8.png)
