### ISSUE TITLE
KMNF-Mountain View Airport-MISSOURI-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7378]
# Airport Name
Mountain View Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/117376302-78cd9b00-ae96-11eb-844d-fd45323b3d32.png)
