### ISSUE TITLE
KLEM-Lemmon Municipal Airport-SOUTH DAKOTA-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7379]
# Airport Name
Lemmon Municipal Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/117077042-04abbf80-acfd-11eb-958e-8173f38c8ffd.png)
