### ISSUE TITLE
LFLI-Annemasse-France

### ISSUE THREAD

**Issue by 35000feet** [InfiniteFlightAirportEditing/Airports#738]
LFLI
Annemasse
France

**Comment by dushyants19** [comment]
Done. [Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/c20f194de57c6b5e4b6e80e246518e209b17f9d4)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19501840/4ba60388-956e-11e6-8d7b-3aaeaf862ece.png)
