### ISSUE TITLE
CD23-Aero Bear Field-COLORADO-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#7380]
# Airport Name
Aero Bear Field
# Country?
USA
# Improvements that need to be made?
Added to IF
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/117543368-27322700-afe2-11eb-8277-4a5c2dc9fc08.png)
