### ISSUE TITLE
KJWG-Watonga Regional Airport-OKLAHOMA-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7381]
# Airport Name
Watonga Regional Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/117076442-0032d700-acfc-11eb-8592-b508c828a1e9.png)
