### ISSUE TITLE
FNLB-Lobito Airport-BENGUELA-ANGOLA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#7385]
# Airport Name
Lobito Airport
# Country?
Angola
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/117066637-99f38780-acee-11eb-8c09-1812c9bfa6c0.png)
