### ISSUE TITLE
KJFZ-Tazewell County Airport-VIRGINIA-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7387]
# Airport Name
Tazewell County Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/117376030-eb8a4680-ae95-11eb-99c8-f6c8a80636f0.png)
