### ISSUE TITLE
43Y-Northome Municipal Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by Aceorbit** [InfiniteFlightAirportEditing/Airports#7388]
# Airport Name
Northome Municipal Airport
# Country?
USA
# Improvements that need to be made?
Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/117540973-4d9e9500-afd7-11eb-8f58-7bebc1381e2a.png)
