### ISSUE TITLE
KJQD-Ohio County Airport-KENTUCKY-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7389]
# Airport Name
Ohio County Airport
# Country?
USA
# Improvements that need to be made?
* From Scratch. 
* Old ICAO = 7K4. New ICAO = KJQD.
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/117375751-47a09b00-ae95-11eb-872f-e050b7814fc0.png)
