### ISSUE TITLE
MYCX

### ISSUE THREAD

**Issue by TristinWoolf** [InfiniteFlightAirportEditing/Airports#739]
Cutlass Bay Airport.

Redone by myself.

**Comment by TristinWoolf** [comment]
Adjusted UNICOM frequency.

**Comment by kilt46** [comment]
Rough landing strip

**Comment by kilt46** [comment]
Spawn point and building added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19616099/aceb10e8-97d0-11e6-904b-489670b67451.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/92383361-cc9f9e80-f0d3-11ea-8ae2-7401dd3796f8.png)
