### ISSUE TITLE
HBBK-Gihohi Airport-RUTANA-BURUNDI

### ISSUE THREAD

**Issue by RobertineIFC** [InfiniteFlightAirportEditing/Airports#7391]
# Airport Name
Gihogi
# Country?
Burundi
# Improvements that need to be made?
Everything
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/120067572-10f81380-c042-11eb-9cb3-ad2af7bb9234.png)
