### ISSUE TITLE
KJCT-Kimble County Airport-Texas-USA

### ISSUE THREAD

**Issue by LawinS** [InfiniteFlightAirportEditing/Airports#7395]
# Airport Name
Kimble County Airport
# Country?
USA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Absolutely yes.
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118723702-596a3280-b7f3-11eb-90ff-556b48310053.png)
