### ISSUE TITLE
OERK-Riyadh King Khaled International Airport-AR RIYAD-SAUDI ARABIA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#74]
Please rework me!

**Comment by kilt46** [comment]
Duplicate entry. Should have been PHKO

**Comment by IFAEpat** [comment]
Up for grabs

**Comment by brunocr98** [comment]
I'll make this airport to shut up the Saudi IF fans. LOL.

**Comment by brunocr98** [comment]
Done....finally.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23824369/0a5f95e0-063b-11e7-8c1a-936d5b2339ce.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/43676658-eefc62c0-97ba-11e8-941b-ca0f804bef27.png)

**Comment by kilt46** [comment]
Adding roadways. Adding definition to gates

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/43688794-60e5af40-98b5-11e8-83bf-9727f86142e8.png)
