### ISSUE TITLE
ZYJM-Jiamusi Airport-HEILONGJIANG-CHINA

### ISSUE THREAD

**Issue by korgast** [InfiniteFlightAirportEditing/Airports#7403]
# Airport Name
Jiamusi Airport
# Country?
China
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123510712-9fac8000-d642-11eb-886a-1cd425b8f8e7.png)
