### ISSUE TITLE
DIBK-Bouake Airport-Vallee du Bandama-IVORY COAST

### ISSUE THREAD

**Issue by Yuzhe716** [InfiniteFlightAirportEditing/Airports#7404]
♻️

**Comment by GBKarp** [comment]
#2142

**Comment by StickThelanding** [comment]
Can I redo this airport.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124353878-cd5b7100-dbce-11eb-8283-19ce1333c530.png)
