### ISSUE TITLE
ZWBL-Bole Alashankou Airport-XINJIANG-CHINA

### ISSUE THREAD

**Issue by Yuzhe716** [InfiniteFlightAirportEditing/Airports#7406]
# Airport Name
Bole Alashankou Airport
# Country?
China
# Improvements that need to be made?
Redo/New airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/120071028-e82c4a00-c052-11eb-9486-f44d73aa261f.png)
