### ISSUE TITLE
UATZ-Tengiz Airport-ATYRAU-KAZAKSTAN

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#7407]
# Airport Name
Tengiz
# Country?
Kazakhstan
# Improvements that need to be made?
New
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/117540390-cb14d600-afd4-11eb-8aad-7b503972c9de.png)
