### ISSUE TITLE
XNBN-Lesnoy-ALTAI KRAI-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7413]
# Airport Name
Lesnoy
# Country?
Ru
# Improvements that need to be made?
from scratch
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118401284-b6ff5300-b62a-11eb-965e-746fe68a190c.png)
