### ISSUE TITLE
XNBP-Panfilovo-ALTAI KRAI-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7414]
# Airport Name
Panfilovo
# Country?
RU
# Improvements that need to be made?
from scratch
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
↓

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118399589-7a7c2900-b623-11eb-875a-99dc576fb582.png)
