### ISSUE TITLE
06D-Rolla Muni-NORTH DAKOTA-USA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7415]
# Airport Name
Rolla Muni
# Country?
USA
# Improvements that need to be made?
from scratch
# Are you working on this airport?
да :) 
# Airport Priority? (10000ft+ Runway, Low)
↓ low ↓

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118720586-64bb5f00-b7ef-11eb-814e-a65c4835ff49.png)
