### ISSUE TITLE
KJTC-Springerville Municipal Airport-ARIZONA-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7416]
# Airport Name
Springerville Municipal Airport
# Country?
USA
# Improvements that need to be made?
From Scratch. Old ICAO = D68, New ICAO = KJTC.
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/117543086-f6052700-afe0-11eb-9e14-7db7637b9966.png)
