### ISSUE TITLE
LTBJ-Adnan Menderes Airport-IZMIR-TURKEY

### ISSUE THREAD

**Issue by turkish1941** [InfiniteFlightAirportEditing/Airports#742]
Will make this one

**Comment by turkish1941** [comment]
just sent the e-mail

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19988855/acad12fa-a1f0-11e6-963e-d2b39d94427f.png)

**Comment by Adam167** [comment]
Gates are Halfway down the stands and Gate boarders could do with being checked.

**Comment by skotshi** [comment]
I can take it.

**Comment by RyanEpps** [comment]
Member inactive, up for grabs.

**Comment by liamkirky** [comment]
Can I take this airport please?

**Comment by liamkirky** [comment]
Can someone unassign me please as my laptop cannot even load it up as it is that bad. :(

**Comment by MBeringuy** [comment]
Open for anything you want to redo.

![Untitled-1](https://user-images.githubusercontent.com/32115399/59208130-dd82fc80-8b7e-11e9-85cb-717761ffe875.jpg)

![Untitled-1](https://user-images.githubusercontent.com/32115399/59208324-3d79a300-8b7f-11e9-9efb-7bc057c13b44.jpg)

**Comment by MBeringuy** [comment]
I'm taking this airport.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/60730912-92a99a00-9f1c-11e9-8484-eb58f480a914.jpg)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/87476885-c538a900-c5ec-11ea-9953-8a7414b0e97a.png)
