### ISSUE TITLE
HADR-Dire Dawa Airport-DIRE DAWA-ETHIOPIA

### ISSUE THREAD

**Issue by rianoshea** [InfiniteFlightAirportEditing/Airports#7429]
# Airport Name
Dire Dawa Intl
# Country?
Ethiopia
# Improvements that need to be made?
Adding apron and parking spots 
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by Czechoslovaki** [comment]
#8384
