### ISSUE TITLE
ETIC

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#743]
Grafenwöhr Army Airfield - Bavaria-Germany
I'll do this quickly

**Comment by moritzbabl** [comment]
Sent for approval

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17277424/f8ce615e-5707-11e6-8636-4931241776cf.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17653304/05b8a3a0-6259-11e6-9526-8c58ff19f629.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17653307/0e4931f6-6259-11e6-8e22-7e17d9b7ec4e.png)
