### ISSUE TITLE
ZUDX-Dazhou Heshi Airport-SICHUAN-CHINA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#7430]
# Airport Name
Dazhou Heshi Airport
# Country?
CN
# Improvements that need to be made?
Redo/New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118404300-0435f180-b638-11eb-8364-96e94bd3f721.png)
