### ISSUE TITLE
HADC-Desse Kombolcha Airport-DESSIE-ETHIOPIA

### ISSUE THREAD

**Issue by rianoshea** [InfiniteFlightAirportEditing/Airports#7431]
# Airport Name
Desse Combolcha Airport
# Country?
Ethiopia
# Improvements that need to be made?
New airport
# Are you working on this airport?
Yes.
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by Czechoslovaki** [comment]
#8376
