### ISSUE TITLE
KCPK-Chesapeake Regional Airport-VIRGINIA-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7432]
# Airport Name
Chesapeake Regional Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118724958-ebbf0600-b7f4-11eb-971a-41873ceaa8ca.png)
