### ISSUE TITLE
KGXY-Greeley-Weld County Airport-COLORADO-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#7433]
# Airport Name
Greeley-Weld County
# Country?
USA
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
10k

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/120246425-d2c34580-c235-11eb-9eb3-3fcd44a74c26.png)
