### ISSUE TITLE
RPVW-Borongan Airport-EASTERN SAMAR-PHILIPPINES

### ISSUE THREAD

**Issue by jaypzs** [InfiniteFlightAirportEditing/Airports#7435]
# Airport Name
Borongan Airport
# Country?
Philippines
# Improvements that need to be made?
Add ramp and gates
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123340020-34af5c00-d511-11eb-90c6-543fa2b4209f.png)
