### ISSUE TITLE
RP10-Layang Layang airport, Swallow Reef-SPRATLY ISLANDS-PHILIPPINES

### ISSUE THREAD

**Issue by jaypzs** [InfiniteFlightAirportEditing/Airports#7436]
# Airport Name
Swallow Reef
# Country?
Philippines
# Improvements that need to be made?
To add Ramp and Gates
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123181908-e425f900-d453-11eb-9b5f-979f35b5ac63.png)
