### ISSUE TITLE
ZYHE-Heihe Aihui Airport-HEILONGJIANG-CHINA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#7438]
# Airport Name
Heihe Aihui Airport
# Country?
CN
# Improvements that need to be made?
Redo/New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118404205-807c0500-b637-11eb-9c97-76a5182f158a.png)
