### ISSUE TITLE
2O7-Independence Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by StickThelanding** [InfiniteFlightAirportEditing/Airports#7439]
# Airport Name
Independence Airport
# Country?
USA
# Improvements that need to be made?
Auto Gen
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by StickThelanding** [comment]
I can have it done by the end of the day

**Comment by Czechoslovaki** [comment]
You're at your 3 issue limit. Wait until one of your other airports are approved in OR.

**Comment by StickThelanding** [comment]
ok sounds good

**Comment by StickThelanding** [comment]
Can I work on this airport now that I got one of my 3 done?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/119067577-0ab1c980-b9a8-11eb-9f02-33de14ecbe04.png)
