### ISSUE TITLE
LGSK-Skiathos Airport-THESSALIA-GREECE

### ISSUE THREAD

**Issue by B777fan** [InfiniteFlightAirportEditing/Airports#744]
Currently re-doing.

**Comment by NickArt1342** [comment]
@B777fan I can't assign you until you have accepted the invite to this github repository. To get invited ask to be in the slack chat.

**Comment by ReflexRSM** [comment]
Looks like I'm a bit late..

**Comment by B777fan** [comment]
Sorry all for this.

**Comment by B777fan** [comment]
Yeah, I'm sorry for all of this.

**Comment by dushyants19** [comment]
Please accept the invite Nick mentioned ASAP, @b777fan! :)

**Comment by dushyants19** [comment]
I'll correct boundary

**Comment by dushyants19** [comment]
Needs a lot of fixes. 

- Appr freq values incorrect
- Lines not snapped
- Incorrect taxiline attribute (Use Solid Yellow)
- Incorrect surface attribute (Use Asphalt for everything)
- Incorrect Runway attribute (Use Ashpalt) 
- `Parking XX` spawn names
- No holes for buildings
- Ramp Start on Main Apron
- Runway length incorrect
- Turnaround points wrong
- Runway holds incorrectly placed (other way around) 

DJ is assigned

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17276918/da27799a-56fb-11e6-8997-f5c9320fa7a4.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17832651/a56b3e4e-66cd-11e6-9abd-476eab23e185.png)

**Comment by MajorTomMueller** [comment]
Apron extension missing.
Bringing to latest standard.

**Comment by MajorTomMueller** [comment]
![LGSK-git](https://user-images.githubusercontent.com/26853210/103791541-79fed080-503a-11eb-9dba-6e39753fb1fc.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104091154-2ca08000-5241-11eb-8fe6-0bd93f6c930b.png)
