### ISSUE TITLE
KCYS-Cheyenne Regional Airport-WYOMING-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7442]
# Airport Name
Cheyenne Regional Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118721598-b31d2d80-b7f0-11eb-84cc-5614ab53e65f.png)
