### ISSUE TITLE
ZSSR-Shangrao Sanqingshan Airport-JIANGXI-CHINA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#7447]
# Airport Name
Shangrao - Sanqingshan
# Country?
CN
# Improvements that need to be made?
Redo/New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118404059-fdf34580-b636-11eb-9adc-3d8057ae07f2.png)
