### ISSUE TITLE
KSEG-Penn Valley Airport-PENNSYLVANIA-USA

### ISSUE THREAD

**Issue by LawinS** [InfiniteFlightAirportEditing/Airports#7449]
# Airport Name
Penn Valley Airport
# Country?
USA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118721051-fa56ee80-b7ef-11eb-843e-2813bb07269c.png)

**Comment by LawinS** [comment]
Will change/add the following:

New Tie-Downs 
New marking

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124366185-72983880-dc13-11eb-98db-1a8f89fded3f.png)
