### ISSUE TITLE
EDMS 

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#745]
Straubing 
Small airport, I'll do this one quickly

**Comment by moritzbabl** [comment]
Sent for approval

**Comment by AxelBeder** [comment]
Added to repro.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19622067/aad9e9aa-9866-11e6-8b5b-a98e90561608.png)
