### ISSUE TITLE
KPIM-Harris County Airport-GEORGIA-USA 

### ISSUE THREAD

**Issue by LawinS** [InfiniteFlightAirportEditing/Airports#7450]
# Airport Name
Harris County Airport
# Country?
USA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yep
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/119067246-3ed8ba80-b9a7-11eb-9229-437c8d4c175f.png)
