### ISSUE TITLE
VTUD-Udon Thani Airport-UDON THANI-THAILAND

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#7454]
# Airport Name
Udon Thani
# Country?
Thailand
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
10k, bravo

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118893789-a7049f00-b8c8-11eb-8628-6589a101dbae.png)
