### ISSUE TITLE
KEND-Vance Air Force Base-OKLAHOMA-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7455]
# Airport Name
Vance Air Force Base
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118720082-caf3b200-b7ee-11eb-89ea-4e5dd104d53e.png)
