### ISSUE TITLE
VTUK-Khon Kaen International Airport-KHON KAEN-THAILAND

### ISSUE THREAD

**Issue by LesterXavier** [InfiniteFlightAirportEditing/Airports#7458]
# Airport Name
Khon Kaen International Airport
# Country?
Thailand 🇹🇭 
# Improvements that need to be made?
Rework from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
10000ft+ Runway

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/132961451-9ab48aed-2f39-4b7f-b045-0d389308981e.png)
