### ISSUE TITLE
KHSV

### ISSUE THREAD

**Issue by Tbynum94** [InfiniteFlightAirportEditing/Airports#746]
Huntsville International Airport, closed to my home town would like to work it.

**Comment by bavAVIA** [comment]
@Tbynum94 What's the progress on this one? :)

**Comment by Tbynum94** [comment]
Idk every time I send it in dush finds something new to complain about

**Comment by bavAVIA** [comment]
Yeah that's normal. Just wanted to know if you are still working on it, I would have taken it over if not.

**Comment by Tbynum94** [comment]
But I'm finishing up the last things right. Shouldn't take long

**Comment by Tbynum94** [comment]
Hey man, I just got a new work assignment and I can't work in the ones I have anymore. You can go ahead and take it

**Comment by bavAVIA** [comment]
I will do this one right after I got an airport ready and a free spot in order not to exceed the three issues limit. 
Expect me to do this one guys.

**Comment by bavAVIA** [comment]
Sent for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21588837/4aade176-d0b0-11e6-97d9-f16f9521991d.png)
