### ISSUE TITLE
ZYBS-Changbaishan Airport-JILIN-CHINA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#7464]
# Airport Name
Changbaishan
# Country?
CN
# Improvements that need to be made?
Redo/New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118403884-22025700-b636-11eb-8294-dc30c4337f03.png)
