### ISSUE TITLE
DTKA-Tabarka-Aïn Draham-JENDOUBA GOVERNORATE-TUNISIA

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#7475]
# Airport Name
Tabarka-Aïn Draham
# Country?
tunisia
# Improvements that need to be made?
redo
# Are you working on this airport?
hmm y
# Airport Priority? (10000ft+ Runway, Low)
low but it is bravo :flushed:

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118732256-976d5380-b7ff-11eb-9e2e-57a0f75d48c5.png)
