### ISSUE TITLE
UMMK-Ozerki Aerodrome-VITEBSK-BELARUS

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#7477]
# Airport Name
Ozerki Aerodrome
# Country?
Belarus 🇧🇾 
# Improvements that need to be made?
New
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118743311-c1cb0b00-b817-11eb-8549-d82148486b6b.png)
