### ISSUE TITLE
UMMO-Osovtsy Air Base-BREST-BELARUS

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#7478]
# Airport Name
Osovtsy Air Base
# Country?
Belarus 🇧🇾 
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/120074961-f5eacb00-c064-11eb-9550-bdc4bebf335d.png)
