### ISSUE TITLE
WAMP-Morowali-SULAWESI-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#7479]
# Airport Name
Morowali / IMIP Private Airport
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118741970-1faa2380-b815-11eb-9026-88a7ca1538e3.png)
