### ISSUE TITLE
LTFD-Balikesir/Koca Seyit Airport-BALIKESIR PROVINCE-TURKEY

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Airports#7480]
# Airport Name
Balikesir/Koca Seyit
# Country?
TURKEY
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118741646-5cc1e600-b814-11eb-8ba3-6cff2b17b4a2.png)
