### ISSUE TITLE
DNIL-Ilorin Airport-KWARA-NIGERIA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#7481]
# Airport Name
Ilorin
# Country?
Nigeria
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
10k / Bravoe

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118741353-aeb63c00-b813-11eb-815b-45daad069403.png)
