### ISSUE TITLE
DTTF-Gafsa Airport-GAFSA-TUNISIA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#7482]
# Airport Name
Gafsa
# Country?
Tunisia 
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118404834-406a5180-b63a-11eb-9557-ae0b927b41c8.png)
