### ISSUE TITLE
20U-Beach Airport-NORTH DAKOTA-USA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7483]
# Airport Name
Beach
# Country?
USA
# Improvements that need to be made?
from scratch
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118568609-cd4a0380-b73d-11eb-912b-fe92f9e161eb.png)
