### ISSUE TITLE
DTTX-Sfax Thyne Airport-SFAX-TUNISIA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#7484]
# Airport Name
Sfax Thyne
# Country?
Tunisia
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118404634-54fa1a00-b639-11eb-93cf-d8d246d0bda8.png)
