### ISSUE TITLE
LTCD-Erzincan Airport-ERZINCAN-TURKEY

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#7486]
# Airport Name
Erzincan
# Country?
Turkey
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118399303-2c1a5a80-b622-11eb-98c2-8d2b3d23d0ed.png)
