### ISSUE TITLE
ZWSC-Shache Yeerqiang Airport-XINJIANG-CHINA

### ISSUE THREAD

**Issue by Yuzhe716** [InfiniteFlightAirportEditing/Airports#7489]
# Airport Name
Shache Yeerqiang Airport
# Country?
China
# Improvements that need to be made?
Redo/New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123510419-06309e80-d641-11eb-8ea0-3e7a2ec78480.png)
