### ISSUE TITLE
XRFI-Saki-CRIMEA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7491]
# Airport Name
Saki AB
# Country?
Russia
# Improvements that need to be made?
from scratch
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
04R/22L - 10500 ft

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/119480281-1f2ef280-bd17-11eb-9348-37d4f82c193d.png)
