### ISSUE TITLE
ZGCD-Changde Taohuayuan-HUNAN-CHINA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#7492]
# Airport Name
Changde Taohuayuan
# Country?
China 
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118403746-70632600-b635-11eb-9ac5-9bf919f21fa8.png)
