### ISSUE TITLE
HEAR-El Arish Int'l-NORTH SINAI GOVERNORATE-EGYPT

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#7496]
# Airport Name
El Arish Int'l
# Country?
Egypt
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by ShaneAviation** [comment]
I can get this one done. :)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124388002-51345c80-dca6-11eb-8e64-2e684e80b85f.png)
