### ISSUE TITLE
KGRI-Central Nebraska Regional Airport-NEBRASKA-USA

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#7497]
# Airport Name
Central Nebraska Regional Airport
# Country?
USA
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/119066638-d0472d00-b9a5-11eb-9498-f569d8d4dc30.png)
