### ISSUE TITLE
SBGR-Sao Paulo/Guarulhos International Airport-SAO PAULO-BRAZIL

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#75]
Needs a ground frequency

**Comment by carmichaelalonso** [comment]
Finished.

**Comment by turkish1941** [comment]
can I get assigned to this, I will make it.

**Comment by turkish1941** [comment]
E-mail has been sent.

**Comment by turkish1941** [comment]
updated the airport with the google earth imagery from now, added terminal, windsock, apron 6, tower, beacon and PAPI
email is gone

**Comment by turkish1941** [comment]
and moved both runways

**Comment by samuelandersson** [comment]
@turkish1941 when moving runways please make an issue in the navigation repository. I already made one for you.

https://github.com/InfiniteFlightAirportEditing/Navigation/issues

**Comment by turkish1941** [comment]
@samuelandersson  I am sorry wasnt sure where to put it. I will do it next time.

**Comment by samuelandersson** [comment]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/bfc56c048674f866adbfa8d29c5adb7279ac0519)

**Comment by kilt46** [comment]
Needs outlines reworked

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19905794/371eb7ba-a046-11e6-983b-afa11fefbe5a.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/48911003-22d81a80-ee37-11e8-8f4f-e4f443586dba.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/66758255-4dc6c500-ee74-11e9-8407-63625a4c9bdb.jpg)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/66771215-fb939d00-ee8f-11e9-8b6e-e290432019fd.jpg)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/113459796-3ec33200-93dc-11eb-9588-15a15f7aa6bb.png)
