### ISSUE TITLE
EGJJ - Jersey Airport UK 

### ISSUE THREAD

**Issue by Will171** [InfiniteFlightAirportEditing/Airports#750]
I am currently adding

+Taxiway lines
+Apron/Parking lines
+More buildings
+More Parking spots
+Taxiway Signs
+Tweaking taxiways

**Comment by Will171** [comment]
waiting for approval

**Comment by Will171** [comment]
Approved- Issue Closed

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17250505/3c246542-556a-11e6-8c76-373b9ee4ab00.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18294728/0565f456-7461-11e6-920f-c8557edfa543.png)

**Comment by ItsW1ll** [comment]
#4621 Moved EGJA, EGJB, EGJJ to the same folder
