### ISSUE TITLE
URFB-Belbek-SEVASTOPOL-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7503]
# Airport Name
Sevastopol Belbek
# Country?
Russia
# Improvements that need to be made?
From scratch 
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
11319ft runway

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/119258374-efed7980-bb8e-11eb-98c1-1ee15b0783d0.png)
