### ISSUE TITLE
LELN

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#751]
León, Spain

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19622026/705c70a0-9865-11e6-93ba-de2ce1846041.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/109387966-e921d400-78c9-11eb-9814-bb461e0ea6c3.png)
