### ISSUE TITLE
DGAH-Ho Airport-VOLTA-GHANA

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#7515]
# Airport Name
Ho Airport
# Country?
Ghana
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118731876-ef578a80-b7fe-11eb-9df2-3a1e21bb3fd2.png)
