### ISSUE TITLE
KPQL-Trent Lott International Airport-MISSISSIPPI-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7517]
# Airport Name
Trent Lott International Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/119060478-dc2bf280-b997-11eb-8a3d-85f3507e33ad.png)
