### ISSUE TITLE
WATG-Ruteng-NUSA TENGGARA-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#7518]
# Airport Name
Frans Sales Lega
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118892778-0497ec00-b8c7-11eb-9e4b-17edf72ec733.png)
