### ISSUE TITLE
LCLK-Larnaka Airport-LACARNA-CYPRUS

### ISSUE THREAD

**Issue by elvintiagi** [InfiniteFlightAirportEditing/Airports#752]
Being Redone

**Comment by dushyants19** [comment]
How is this airport going, @elvintiagi?

**Comment by elvintiagi** [comment]
Hi,
Sorry but I am unable to create airports because of me begging very busy. You can dismiss me from the team.

Thanks
//Elvin Tyagi

**Comment by dushyants19** [comment]
Up for grabs

**Comment by brunocr98** [comment]
Taking this airport.

**Comment by brunocr98** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22130540/3b30223e-de72-11e6-8156-ce6254d89986.png)

**Comment by liamkirky** [comment]
Sent for OR.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/73313518-3d134280-420a-11ea-8e82-4a165c5247dc.jpg)
