### ISSUE TITLE
KHXD-Hilton Head Airport-SOUTH CAROLINA-USA

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#7523]
# Airport Name
Hilton Head Airport
# Country?
USA
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/119059551-28763300-b996-11eb-8f7a-4e64ac808111.png)
