### ISSUE TITLE
KHRL-Valley International Airport-TEXAS-USA

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#7524]
# Airport Name
Valley International Airport
# Country?
USA
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122688046-85584980-d1df-11eb-80b6-006f087fc26a.png)
