### ISSUE TITLE
D00-Norman County Ada/Twin Valley Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7526]
# Airport Name
Norman County Ada/Twin Valley Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/119059221-7d657980-b995-11eb-954e-0f74d695b112.png)
