### ISSUE TITLE
KBNL-Barnwell Regional Airport-SOUTH CAROLINA-USA

### ISSUE THREAD

**Issue by elvintiagi** [InfiniteFlightAirportEditing/Airports#753]
Needs redone. Double runways 16 and 17 stacked on top

**Comment by TristinWoolf** [comment]
For any further conversation for this airport, see #752.

**Comment by dushyants19** [comment]
Whats up with this, @kilt46?

**Comment by samuelandersson** [comment]
!["Schematic"](https://cloud.githubusercontent.com/assets/15381853/16363972/b02fcb1e-3bdb-11e6-943c-e43eecbef340.png)

**Comment by samuelandersson** [comment]
![New "schematic"](https://cloud.githubusercontent.com/assets/15381853/16364137/7ca60128-3be0-11e6-80df-fc702d2a6c76.png)

Redid everything without runways

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/c339bba2eca029a0dd7fa51bacd76b86f7b806d8)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19621396/af55e69c-9856-11e6-8ffd-4856e740d42c.png)
