### ISSUE TITLE
ENKR-Kirkenes-Hoybuktmoen Airport-FINNMARK-NORWAY

### ISSUE THREAD

**Issue by henrikbg** [InfiniteFlightAirportEditing/Airports#754]
Kirkenes.

**Comment by henrikbg** [comment]
Redone.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19618855/b626bc0c-981b-11e6-9438-4dff4e62f7c0.png)

**Comment by MajorTomMueller** [comment]
Apron has been significan modifyed, and spawn size insufficient
https://ais.avinor.no/en/AIP/View/65/aip/ad/enkr/EN_AD_2_ENKR_2-1_en.pdf

**Comment by MajorTomMueller** [comment]
![ENKR](https://user-images.githubusercontent.com/26853210/66739440-2f56ce80-ee60-11e9-83c5-2755c69da9f0.png)
