### ISSUE TITLE
DTTZ-Nefta Airport-Tozeur-TUNISIA

### ISSUE THREAD

**Issue by BAKUOV** [InfiniteFlightAirportEditing/Airports#7540]
♻️

**Comment by AleksanderIF** [comment]
#5261

**Comment by StickThelanding** [comment]
Can I take this airport?

**Comment by Czechoslovaki** [comment]
@StickThelanding use Bing for this one.

**Comment by StickThelanding** [comment]
Sounds good @Czechoslovaki

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/120075172-d1432300-c065-11eb-961d-e9f03fd282cf.png)
