### ISSUE TITLE
D02-Osage Municipal Airport-IOWA-USA

### ISSUE THREAD

**Issue by LordWizrak** [InfiniteFlightAirportEditing/Airports#7541]
# Airport Name
Osage Municipal Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/119259896-f59a8d80-bb95-11eb-9ae9-0b765bf9ccc8.png)
