### ISSUE TITLE
D31-Leeds Municipal Airport-NORTH DAKOTA-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7543]
# Airport Name
Leeds Municipal Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/119259764-61302b00-bb95-11eb-8bf0-68ea3ebde0e1.png)
