### ISSUE TITLE
D54-West Fargo Municipal Airport-NORTH DAKOTA-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7544]
# Airport Name
West Fargo Municipal Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/119259668-e535e300-bb94-11eb-88ef-324960a05db5.png)
