### ISSUE TITLE
VA1D-Myorpur Airport-Uttar Pradesh-India

### ISSUE THREAD

**Issue by KaalicharanDH** [InfiniteFlightAirportEditing/Airports#7545]
# Airport Name
Myorpur Airport
# Country?
India
# Improvements that need to be made?
from scratch
# Are you working on this airport?
yo
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/119899351-9f687a00-bf08-11eb-95c9-c83a323835b1.png)
