### ISSUE TITLE
VA1E-Nandini Airstrip-Chhattisgarh-India

### ISSUE THREAD

**Issue by KaalicharanDH** [InfiniteFlightAirportEditing/Airports#7546]
# Airport Name
Nandini Airstrip
# Country?
India
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
yo
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/119898264-39c7be00-bf07-11eb-98d2-ac7f246907c2.png)
