### ISSUE TITLE
ZBAA-Beijing-Capital Airport-BEIJING-CHINA

### ISSUE THREAD

**Issue by turkish1941** [InfiniteFlightAirportEditing/Airports#755]
I will make this one

**Comment by turkish1941** [comment]
I cant follow this anymore, I am a bit confused. When I started the airport I firts looked for the ICAO  but couldnt find it. Thats why I started it. The airport ICAO is ZBAA. When I finished it yesterday I was just scrolling around to search for another airport. Thats when I found out about the 'second' airport whit a wrong ICAO. My question is who is really assigned ☺

**Comment by kilt46** [comment]
I have assigned you. You do such an excellent job. I have not seen Kisky
for a while either.
[image: Inline image 1]

**Comment by Ksisky** [comment]
@kilt46 I'm always working on something on something :+1:

**Comment by samuelandersson** [comment]
Are you working on this one at the momet @Ksisky?

**Comment by Ksisky** [comment]
@samuelandersson No, there was a mixup in the Issues. Turkish is working on it.

**Comment by turkish1941** [comment]
I forgot to say, I have sent the email a few hours ago

**Comment by dushyants19** [comment]
We need to find the error on the runway numbers, stay tuned :)

**Comment by dushyants19** [comment]
a2bd808

**Comment by NickArt1342** [comment]
Question: The altitude in the apt.dat is 35 (m), but it should be given in feet I thought?

**Comment by NickArt1342** [comment]
Most of frequencies are missing. Somebody could add them, but not so necessary. Check here for all the intel you need http://www.uvairlines.com/admin/resources/charts/ZBAA.pdf or http://www.vatprc.net/index.php/en/en-firs/en-zbpe/66-en-zbaa

**Comment by dushyants19** [comment]
@nickart1342 go to view -> hit feet so that it's displayed in feet

**Comment by NickArt1342** [comment]
@dushyants19 I don't care what I see in my WED, but the important thing is the number in the apt.dat. Is it automatically transformed and saved as feet?

**Comment by dushyants19** [comment]
If user enters in metres, saved as metres. Converted to ft as per your request

**Comment by turkish1941** [comment]
I'll look into it and gate it as well this weekend.

**Comment by NickArt1342** [comment]
@dushyants19 I just checked the apt.dat and how it is saved. It will always be saved in feet in the apt.dat no matter if you enter it in meters.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18799486/70c3c3f6-819d-11e6-95d7-c1947ee2f775.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18799544/bcbaeb22-819d-11e6-81a1-51efea14c3f4.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18799549/c7f486e2-819d-11e6-9c63-e075fbfdcb1f.png)

**Comment by kilt46** [comment]
Duplicate spawns fixed

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/50736214-43a6c600-1180-11e9-8ab5-3e460f1f0fc1.png)
