### ISSUE TITLE
PAFE-Kake Airport-ALASKA-USA

### ISSUE THREAD

**Issue by LawinS** [InfiniteFlightAirportEditing/Airports#7559]
# Airport Name
Kake Airport
# Country?
USA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yep
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/119259156-88d1c400-bb92-11eb-9b95-b073a58d34c2.png)
