### ISSUE TITLE
FA02-Counter Terrorism Advanced Training Center Airport-FLORIDA-USA

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#7561]
# Airport Name
Counter Terrorism Advanced Training Center Airport
# Country?
USA
# Improvements that need to be made?
New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![Uploading image.png…]()
