### ISSUE TITLE
ESMS- Malmo Airport-SKANE-SWEDEN

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Airports#757]
Malmo Sturup. Tweaking this quite a bit.

**Comment by samuelandersson** [comment]
Done 

+ New taxiways
+ New gates
+ Buildings
+ Moved tower viewpoint

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/a1c027450cbac2d973211944b1c1d9e91d3e1b67)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17232775/1a2cb798-54f0-11e6-8c6a-2bdf8f937150.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17263065/93b7588e-55a4-11e6-95c0-2a6565f402af.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18231282/66f6f28e-727b-11e6-96cb-4926d5a8712a.png)

**Comment by MajorTomMueller** [comment]
Can’t see what changed, but if you like...

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90841768-2279f580-e323-11ea-8f4f-b86563bd0baf.png)
