### ISSUE TITLE
EDHE-Uetersen Heist-HAMBURG-GERMANY

### ISSUE THREAD

**Issue by Nico-NJ24** [InfiniteFlightAirportEditing/Airports#7575]
# Airport Name
Uetersen Heist
# Country?
Germany
# Improvements that need to be made?
Rework from scratch 
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by brunocr1050** [comment]
https://github.com/InfiniteFlightAirportEditing/Airports/commit/b598ff6419366253f58cd5f71c603a2da095b482

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/120076210-094c6500-c06a-11eb-8c2f-9e88f4c110d2.png)
