### ISSUE TITLE
KRPB-Belleville Municipal Airport-KANSAS-USA

### ISSUE THREAD

**Issue by RhysV29** [InfiniteFlightAirportEditing/Airports#7576]
# Airport Name
Belleville Municipal Airport
# Country?
USA
# Improvements that need to be made?
From scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/119578990-24298b80-bd83-11eb-98a5-6d9a9a1cf8d5.png)
