### ISSUE TITLE
LPPT-Lisboa Airport-LISBOA-PORTUGAL

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#758]
Lisbon Portela Airport

**Comment by TristinWoolf** [comment]
@Aviationluver Do you want to do this one?

**Comment by JcFl4** [comment]
Good! I have some Portuguese airports planned.

**Comment by Aviationluver** [comment]
Sent this one off to be reviewed.

**Comment by dushyants19** [comment]
93c4e12

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19417317/8f551782-936f-11e6-8c3c-66d8a3e5f339.png)
![image](https://cloud.githubusercontent.com/assets/14023167/19417335/c1fb3eb4-936f-11e6-9a5d-66f310753ab1.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/67153300-02ba1100-f2bd-11e9-867a-15cdf9f9644e.jpg)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68997817-68cc9080-0889-11ea-9556-79bde5eba014.jpg)
