### ISSUE TITLE
CYPT-Pelee Island Airport-ONTARIO-CANADA

### ISSUE THREAD

**Issue by mike116119** [InfiniteFlightAirportEditing/Airports#7580]
# Airport Name
Pelee Island
# Country?
Canada
# Improvements that need to be made?
Full rework
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/120069878-c4b2d080-c04d-11eb-8571-100a9969dc44.png)
