### ISSUE TITLE
ZWKN-Burqin Kanasi Airport-XINJIANG-CHINA

### ISSUE THREAD

**Issue by korgast** [InfiniteFlightAirportEditing/Airports#7581]
# Airport Name
Burqin Kanasi Airport
# Country?
China
# Improvements that need to be made?
From scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123510342-81458500-d640-11eb-9249-a61dd2356bbe.png)
