### ISSUE TITLE
KUOX-University-Oxford Airport-MISSISSIPPI-USA

### ISSUE THREAD

**Issue by LawinS** [InfiniteFlightAirportEditing/Airports#7582]
# Airport Name
University Oxford Airport
# Country?
USA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yep
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122691212-e427be00-d1f3-11eb-880e-d8c7f440a846.png)
