### ISSUE TITLE
E11-Andrews County Airport-TEXAS-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7584]
# Airport Name
Andrews County Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/119574730-88485180-bd7b-11eb-9826-3a65d2fb3a0e.png)
