### ISSUE TITLE
VOBG-HAL Airport-KARNATAKA-INDIA

### ISSUE THREAD

**Issue by hari-shreyas** [InfiniteFlightAirportEditing/Airports#7587]
# Airport Name
HAL Airport
# Country?
India
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
10k+ RWY

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124386244-2561a880-dc9f-11eb-879e-55c015889f7c.png)
