### ISSUE TITLE
LLHA-Haifa Airport-HAIFA-ISRAEL

### ISSUE THREAD

**Issue by zhf21** [InfiniteFlightAirportEditing/Airports#7588]
# Airport Name
Haifa Airport
# Country?
Israel
# Improvements that need to be made?
Redo (auto-gen)
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by zhf21** [comment]
**AIP:** https://www.gov.il/BlobFolder/guide/aip-israel/en/aip-eng_AD-2-2.pdf

**Comment by zhf21** [comment]
**Airport Overview:**

- https://www.gov.il/BlobFolder/guide/aip-israel/en/aip-eng_AD-2-2-09.pdf

**Parking Charts:**
- https://www.gov.il/BlobFolder/guide/aip-israel/en/aip-eng_AD-2-2-11.pdf
- https://www.gov.il/BlobFolder/guide/aip-israel/en/aip-eng_AD-2-2-11A.pdf
- https://www.gov.il/BlobFolder/guide/aip-israel/en/aip-eng_AD-2-2-11B.pdf

---

Sorry for the spam in messages. I just want everything referenced to avoid any discrepancies.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123567188-2d918380-d787-11eb-9319-864104df14ea.png)
