### ISSUE TITLE
KHKS-Hawkins Field Airport-MISSISSIPPI-USA

### ISSUE THREAD

**Issue by RhysV29** [InfiniteFlightAirportEditing/Airports#7589]
# Airport Name
Hawkins Field Airport
# Country?
USA
# Improvements that need to be made?
From scratch (auto-gen)
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122691051-c148da00-d1f2-11eb-82bf-8e442fb6dd96.png)
