### ISSUE TITLE
ESSL

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Airports#759]
Redoing

**Comment by samuelandersson** [comment]
Done, a whole redo was needed.

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/c0f4aba159b8b29b2cd53a4dcb1b612c2154d52a)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17264529/349970cc-55ad-11e6-99fe-1de0f7cf590a.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18231137/d699f678-7275-11e6-8cd0-6c3c44ca42db.png)
