### ISSUE TITLE
UEMM-Magan-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7590]
# Airport Name
Magan
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/119899950-71d00080-bf09-11eb-9bf6-78df2e53201c.png)
