### ISSUE TITLE
E91-Chinle Municipal Airport-ARIZONA-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7591]
# Airport Name
Chinle Municipal Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/120071682-0a739700-c056-11eb-872c-c76adcadfecc.png)
