### ISSUE TITLE
F10-Henryetta Municipal Airport-OKLAHOMA-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7592]
# Airport Name
Henryetta Municipal Airport
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/120072961-e61ab900-c05b-11eb-87cb-826e2c96bdf2.png)
