### ISSUE TITLE
NFNR-Rotuma Airport-ROTUMA-FIJI

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#7593]
# Airport Name
Rotuma Airport
# Country?
Fiji
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/119573998-a792af00-bd7a-11eb-944e-be53febcc54f.png)
