### ISSUE TITLE
ZUZH-Panzhihua Bao'anying Airport-SICHUAN-CHINA

### ISSUE THREAD

**Issue by SuhasIF** [InfiniteFlightAirportEditing/Airports#7594]
# Airport Name
Panzhihua Bao'anying Airport
# Country?
China
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/127031889-4e1ef144-90c0-4b2a-a1db-9579a0c54e37.png)
