### ISSUE TITLE
SDXF-Alto Paraiso Airport-GOIAS-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#7595]
# Airport Name
Alto Paraiso Airport
# Country?
Brazil
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
Not uploaded

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/119906723-5ae2db80-bf14-11eb-8aa1-c22d7a05c64b.png)
