### ISSUE TITLE
ZBUC-Ulanqab Jining Airport-INNER MONGOLIA-CHINA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#7596]
# Airport Name
Ulanqab Jining Airport
# Country?
CN
# Improvements that need to be made?
New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
09/27 - 10,499ft

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/120070555-bfa35080-c050-11eb-9987-258b2ea77f6b.png)
