### ISSUE TITLE
SCDW-Almirante Schoeders-MAGALLANES-CHILE

### ISSUE THREAD

**Issue by SpeedbirdCL** [InfiniteFlightAirportEditing/Airports#7598]
# Airport Name
Almirante Schoeders
# Country?
Chile
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/124850366-1c562d00-df66-11eb-9216-46a2e74e1f44.png)
