### ISSUE TITLE
PHNL-Honolulu International Airport-HAWAII-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#76]

**Comment by Swang007** [comment]
Adding a few other spawn points to avoid ATC pushback confusion

**Comment by kilt46** [comment]
Reworking Main Terminal to include ALL Gates

**Comment by kilt46** [comment]
Main Terminal now has complete set of gates
Main Image: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=PHNL
Main Terminal Image: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=PHNLT

**Comment by kilt46** [comment]
reworking

**Comment by kilt46** [comment]
This has been redone

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20640687/a2e11552-b3aa-11e6-82bc-4296a3e7bc88.png)

**Comment by Balloonchaser** [comment]
Time for a Hawaii Revamp! I'll take this :smile:

**Comment by brunocr1050** [comment]
Granting permission to @jakey20 to redo HNL (just please add a boundary or else :reject:.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103480919-11df8e80-4d9d-11eb-8664-4af3f4d597b6.png)

**Comment by MajorTomMueller** [comment]
The whole airport is offset in its latest version in GitHub Airports!
![PHNL](https://user-images.githubusercontent.com/26853210/103898445-da4e4a80-50ec-11eb-82a2-95b44c6ab59f.png)
It neither alligne with satelite nor with FAA data.
It is moved 10ft west and 3ft north compared to FAA data, and even mor compared with satelite.
