### ISSUE TITLE
ESGL 

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Airports#760]
Lidköping Hovby airport.

**Comment by samuelandersson** [comment]
+ New taxiways
+ New taxi lines
+ Tower viewpoint added
+ Buildings added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17232690/6e3ca59c-54ef-11e6-86b4-9395351b3cfc.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17262888/aec29a90-55a3-11e6-9349-c9cb748d0180.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18258925/de54cd1e-73a3-11e6-947b-ab569dafb4ad.png)
