### ISSUE TITLE
SDEM-Estancia Machado Airport-SAO PAULO-BRAZIL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Airports#7604]
# Airport Name
Estancia Machado Airport
# Country?
Brazil
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/119896898-4ba86180-bf05-11eb-882e-d634494d7a40.png)
