### ISSUE TITLE
HBBO-Kirundo Airport-KIRUNDO-BURUNDI

### ISSUE THREAD

**Issue by RobertineIFC** [InfiniteFlightAirportEditing/Airports#7605]
# Airport Name
Kirundo
# Country?
Burundi
# Improvements that need to be made?
Everything
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124199614-efeb6e00-da98-11eb-8a2e-4e40d212300e.png)
