### ISSUE TITLE
UEST-Tiksi-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7606]
# Airport Name
Tiksi
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
no octagons -> low priority

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124038917-9109f400-d9c7-11eb-82a5-7f8089006aee.png)
