### ISSUE TITLE
KPTV-Porterville Municipal Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by RhysV29** [InfiniteFlightAirportEditing/Airports#7609]
# Airport Name
Porterville Municipal Airport
# Country?
USA
# Improvements that need to be made?
From scratch (auto-gen)
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122681400-c76e9480-d1b9-11eb-8807-4b9fc04c0d38.png)
