### ISSUE TITLE
ESOE

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Airports#761]
Örebro airport. Needs a redo, still bad x-plane scenery.

**Comment by samuelandersson** [comment]
Redone 

+ New taxiways
+ Added parking slots
+ Added buildings
+ Corrected PAPIs

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17232988/ea8a223a-54f1-11e6-9350-87d98d973111.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18419026/e1faf1e6-7817-11e6-8b17-41d6649d6995.png)
