### ISSUE TITLE
SCER-Quintero-VALPARAISO-CHILE

### ISSUE THREAD

**Issue by SpeedbirdCL** [InfiniteFlightAirportEditing/Airports#7610]
# Airport Name
Quintero
# Country?
Chile
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/132603918-ddf81902-0dbc-4573-aaad-549920e3a967.png)
