### ISSUE TITLE
CYVL-Colville Lake/Tommy Kochon Airport-NORTHWEST TERRITORIES-CANADA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7611]
# Airport Name
Colville Lake/Tommy Kochon Airport
# Country?
Canada
# Improvements that need to be made?
From Scratch. Old ICAO = CEB3. New ICAO = CYVL.
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/120069767-32123180-c04d-11eb-8e32-cc3194267889.png)
