### ISSUE TITLE
VIJO-Jodhpur Airport-RAJASTHAN-INDIA

### ISSUE THREAD

**Issue by KaalicharanDH** [InfiniteFlightAirportEditing/Airports#7612]
# Airport Name
Jodhpur Airport
# Country?
India
# Improvements that need to be made?
From scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123524119-bd530700-d68d-11eb-9643-d13fd588f71c.png)
