### ISSUE TITLE
ZSHZ-Heze Mudan Airport-SHANDONG-CHINA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#7613]
# Airport Name
Heze - Mudan
# Country?
CN
# Improvements that need to be made?
New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123510236-f3699a00-d63f-11eb-80ba-b43ff84734f8.png)
