### ISSUE TITLE
KNRA-Coupeville NOLF-WASHINGTON-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#7617]
# Airport Name
Coupeville NOLF
# Country?
USA
# Improvements that need to be made?
Some stuff
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
How bout I don't

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/120071334-6a693e00-c054-11eb-812c-fad112cea879.png)
