### ISSUE TITLE
CEB4-Rockyford/Early Bird Air Airport-ALBERTA-CANADA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7618]
# Airport Name
Rockyford/Early Bird Air Airport
# Country?
Canada
# Improvements that need to be made?
New Airport - From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122615773-bce3bc00-d04e-11eb-9cea-7bdf05cb9dba.png)
