### ISSUE TITLE
CEB8-Essex/Billing Airstrip-ONTARIO-CANADA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7620]
# Airport Name
Essex/Billing Airstrip
# Country?
Canada
# Improvements that need to be made?
New Airport - From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122641599-07574e00-d0cc-11eb-863a-b25d45023f17.png)
