### ISSUE TITLE
CFG3-Consort-ALBERTA-CANADA

### ISSUE THREAD

**Issue by JulietTango-IF** [InfiniteFlightAirportEditing/Airports#7621]
# Airport Name
Consort Airport 
# Country?
Canada
# Improvements that need to be made?
Full rework 
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122486009-d37e0a80-cf9d-11eb-9501-7966ff857afb.png)
