### ISSUE TITLE
UMNB-Babruisk Air Base-MOGILEV-BELARUS

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#7623]
# Airport Name
Babruisk Air Base
# Country?
Belarus 🇧🇾
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124106376-c5160100-da29-11eb-9667-d0329dabb27e.png)
