### ISSUE TITLE
UMNL-Luninets Air Base-BREST-BELARUS

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#7624]
# Airport Name
Luninets Air Base
# Country?
Belarus 🇧🇾
# Improvements that need to be made?
New
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124105739-2689a000-da29-11eb-96fd-feeb44a0b7db.png)
