### ISSUE TITLE
ELUS-Useldange Airport-DIEKIRCH-LUXUMBOURG

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#7625]
![image](https://user-images.githubusercontent.com/51279558/120058935-f9e60100-c002-11eb-936e-944f023fd87a.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/120070319-828a8e80-c04f-11eb-88a5-c1765c4d4281.png)
