### ISSUE TITLE
UNNE-Yeltsovka Airport-NOVOSIBIRSK-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7626]
# Airport Name
Novosibirsk Yeltsovka
# Country?
Mutter Russland
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
10873 ft runway. Bravo

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124038495-d4b02e00-d9c6-11eb-9c07-b1f04e86185f.png)
