### ISSUE TITLE
RJNY-Shizuhama Airport-SHIZUOKA-JAPAN

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#7627]
# Airport Name
Shizuhama (静浜基地)
# Country?
Japan
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/120101795-75cc7000-c10d-11eb-82c8-8e61fcfd43b7.png)
