### ISSUE TITLE
LPPR-Porto Airport-PORTO-PORTUGAL

### ISSUE THREAD

**Issue by JcFl4** [InfiniteFlightAirportEditing/Airports#763]
Porto, Portugal.

**Comment by Aviationluver** [comment]
How is this one coming?

**Comment by JcFl4** [comment]
Haven't started yet, but will soon! :)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22393022/85e6c446-e4c5-11e6-8bee-40f0574962f9.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/68041958-822de400-fcb0-11e9-97a0-8039380298bf.jpg)
