### ISSUE TITLE
ZSYC-Yichun Mingyueshan Airport-JIANGXI-CHINA

### ISSUE THREAD

**Issue by korgast** [InfiniteFlightAirportEditing/Airports#7631]
# Airport Name
Yichun Mingyueshan Airport
# Country?
China
# Improvements that need to be made?
Redo from scratch 
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123510045-e7c9a380-d63e-11eb-86dc-b83946859d9f.png)
