### ISSUE TITLE
RJ04-Shikabe Airport-HOKKAIDO-JAPAN

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#7632]
![image](https://user-images.githubusercontent.com/51279558/120094586-0e46fe00-c0d6-11eb-8bd0-2f853331bd8a.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/120101675-d4451e80-c10c-11eb-9dda-a607075703a4.png)
