### ISSUE TITLE
ZWNL-Xinyuan Nalati Airport-XINJIANG-CHINA

### ISSUE THREAD

**Issue by Yuzhe716** [InfiniteFlightAirportEditing/Airports#7633]
# Airport Name
Xinyuan Nalati Airport
# Country?
China
# Improvements that need to be made?
Redo/New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123509961-4b070600-d63e-11eb-97b0-47c821aa99b3.png)
