### ISSUE TITLE
KMVL-Morrisville-Stone State Airport-VERMONT-USA

### ISSUE THREAD

**Issue by LawinS** [InfiniteFlightAirportEditing/Airports#7634]
# Airport Name
Morrisville-Stone State Airport
# Country?
United States of America
# Improvements that need to be made?
Redo :)
# Are you working on this airport?
Yessir
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122844693-d6436d00-d2c7-11eb-8644-b5d4d859f2fc.png)
