### ISSUE TITLE
KLSF-Lawson AAF-GEORGIA-USA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#7635]
# Airport Name
Lawson AAF
# Country?
USA
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
10K runway / Bravo

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122686420-7c16af00-d1d6-11eb-82ec-9d36aac8665e.png)
