### ISSUE TITLE
SWNB-Luis Eduardo Magalhaes Airport-BAHIA-BRAZIL

### ISSUE THREAD

**Issue by HenriqueChen** [InfiniteFlightAirportEditing/Airports#7636]
# Airport Name
Luis Eduardo Magalhaes Airport
# Country?
Brazil
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by HenriqueChen** [comment]
Sent to OR.

**Comment by brunocarbone3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/135531429-2ad37e51-94d9-4c92-9aeb-bc6db7199961.png)
