### ISSUE TITLE
ZWKC-Kuqa Qiuci Airport-XINJIANG-CHINA

### ISSUE THREAD

**Issue by Yuzhe716** [InfiniteFlightAirportEditing/Airports#7639]
# Airport Name
Kuqa Qiuci Airport
# Country?
China
# Improvements that need to be made?
Redo/New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123509867-9bca2f00-d63d-11eb-89d6-356a34ca0640.png)
