### ISSUE TITLE
LIMJ-Genova Cristoforo Colombo Airport-LIGURIA-ITALY

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Airports#764]

**Comment by samuelandersson** [comment]
Done

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/18ee16f7387c8b6f229dcaf3e24db9dce90c7cd2)

**Comment by kilt46** [comment]
Centrelines is unacceptable
![image](https://cloud.githubusercontent.com/assets/14023167/16358988/baf92858-3ae9-11e6-8b87-b196fa232305.png)

**Comment by samuelandersson** [comment]
@kilt46 

That is how it is on the maps.

**Comment by samuelandersson** [comment]
[Main apron retouched](https://cloud.githubusercontent.com/assets/15381853/16359231/c89e6584-3b2c-11e6-95e6-f2c70f5198ac.png)

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/7a2fdaa49488b46440a88a344472614d17fdecc3)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19582920/327e2192-96fe-11e6-96e7-e6b9af13f6c7.png)
