### ISSUE TITLE
CEC3-Fox Lake Airport-ALBERTA-CANADA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7645]
# Airport Name
Fox Lake
# Country?
Canada
# Improvements that need to be made?
New airport, but has a folder in GitHub.
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122616684-75f6c600-d050-11eb-9b85-96f74f6422a9.png)
