### ISSUE TITLE
CED3-Oyen Municipal Airport-ALBERTA-CANADA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7648]
# Airport Name
Oyen Municipal Airport
# Country?
Canada
# Improvements that need to be made?
Has a new folder and an autogen folder. Old ICAO = ED3, New ICAO = CED3.
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/120393838-39109c80-c2f8-11eb-985c-f26cda51a29d.png)
