### ISSUE TITLE
4B7-Schroon Lake Airport-NEW YORK-USA

### ISSUE THREAD

**Issue by zhf21** [InfiniteFlightAirportEditing/Airports#7649]
# Airport Name
Schroon Lake Airport
# Country?
U.S.A.
# Improvements that need to be made?
Redo (auto-gen)
# Are you working on this airport?
Yes.
# Airport Priority? (10000ft+ Runway, Low)
Low.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122743428-98edc980-d24c-11eb-8bf7-ed43cf514292.png)
