### ISSUE TITLE
ZWKM-Karamay Airport-XINJIANG-CHINA

### ISSUE THREAD

**Issue by Yuzhe716** [InfiniteFlightAirportEditing/Airports#7651]
# Airport Name
Karamay Airport
# Country?
China
# Improvements that need to be made?
Redo/New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123509661-5fe29a00-d63c-11eb-9e3d-686cdcdeb484.png)
