### ISSUE TITLE
CED4-Fox Creek Airport-ALBERTA-CANADA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7656]
# Airport Name
Fox Creek Airport
# Country?
Canada
# Improvements that need to be made?
Has a new folder and an autogen folder, Old ICAO = ED4, New ICAO = CED4.
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122617683-56609d00-d052-11eb-952c-1beebd3dbe74.png)
