### ISSUE TITLE
CED6-De Winton/Highwood Airport-ALBERTA-CANADA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7658]
# Airport Name
De Winton/Highwood Airport
# Country?
Canada
# Improvements that need to be made?
Has a new folder and an autogen folder, Old ICAO = ED6, New ICAO = CED6.
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122619474-20bdb300-d056-11eb-9ca5-47b32cf51a44.png)
