### ISSUE TITLE
EDNV

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#766]
I'll do this

**Comment by moritzbabl** [comment]
Sent for approval

**Comment by dushyants19** [comment]
Are you sending to the correct email? `airports@liveflightapp.com`

**Comment by dushyants19** [comment]
1db3d01

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19417563/de984c96-9375-11e6-9b0a-30fab93947e4.png)
