### ISSUE TITLE
FLSW-Solwezi Airport-NORTHWESTERN-ZAMBIA

### ISSUE THREAD

**Issue by James-Beckett** [InfiniteFlightAirportEditing/Airports#7660]
# Airport Name
Solwezi Airport
# Country?
Zambia
# Improvements that need to be made?
Needs to be added to Infinite Flight
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by MajorTomMueller** [comment]
![FLSW-git](https://user-images.githubusercontent.com/26853210/132132210-5e07efa2-019d-4587-939e-1f1213599a34.png)
