### ISSUE TITLE
KSBX-Shelby Airport-MONTANA-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#7661]
# Airport Name
Shelby Airport
# Country?
USA
# Improvements that need to be made?
full redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122690861-85614500-d1f1-11eb-9fb9-c20933879526.png)
