### ISSUE TITLE
KLBF-North Platte Regional / Lee Bird Field-NEBRASKA-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#7670]
# Airport Name
North Platte Regional / Lee Bird Field
# Country?
USA
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122690631-5ac2bc80-d1f0-11eb-9d32-7b523c7580a2.png)
