### ISSUE TITLE
CLM2-Leamington-ONTARIO-CANADA

### ISSUE THREAD

**Issue by mike116119** [InfiniteFlightAirportEditing/Airports#7672]
# Airport Name
Leamington
# Country?
Canada
# Improvements that need to be made?
Autogen
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by brunocarbone3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/134564287-17a78d04-86d8-4468-a43b-f6a92e4223eb.png)
