### ISSUE TITLE
EDJG

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#768]
I'll do this

**Comment by moritzbabl** [comment]
Sent for approval

**Comment by dushyants19** [comment]
2dba024

**Comment by kilt46** [comment]
Why is this closed? There is nothing in the file!!!
![image](https://cloud.githubusercontent.com/assets/14023167/16581923/91802302-4271-11e6-9713-e8b4bdcc2e86.png)

**Comment by moritzbabl** [comment]
I have no idea why there is nothing, I just reopened the version I sent to you and I have the airport...
I'll send it again in a moment

**Comment by dushyants19** [comment]
Should be fixed now, sorry :) 

284beec

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19225021/e6e2d448-8e57-11e6-836b-a8f8f03a82fd.png)
