### ISSUE TITLE
7B6-Skylark Airpark-CONNECTICUT-USA

### ISSUE THREAD

**Issue by RhysV29** [InfiniteFlightAirportEditing/Airports#7690]
# Airport Name
Skylark Airpark
# Country?
USA
# Improvements that need to be made?
Gate/hangar additions (partial rework)
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by RhysV29** [comment]
oops wait I already have 3 assigned to me, this can be made available for the time being, but I'll come back to it.

**Comment by RhysV29** [comment]
I can take this now, most recent was accepted

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122690332-8775d480-d1ee-11eb-872b-f2ffc4a1f6fd.png)
