### ISSUE TITLE
RPLS-Sangley Airport-PHILIPPINES

### ISSUE THREAD

**Issue by jaypzs** [InfiniteFlightAirportEditing/Airports#7691]
# Airport Name
RPLS
# Country?
Philippines
# Improvements that need to be made?
Add ramps and gates
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
no

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/130266417-1f3b4360-84de-40c2-9ed3-9fc24133fb69.png)
