### ISSUE TITLE
ZUAS-Anshun Huangguoshu Airport-GUIZHOU-CHINA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#7692]
# Airport Name
Anshun Huangguoshu Airport
# Country?
CN
# Improvements that need to be made?
New
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123509579-e77bd900-d63b-11eb-91f7-5b9e4d618f95.png)
