### ISSUE TITLE
KBAM-Battle Mountain Airport-NEVADA-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#7697]
# Airport Name
Battle Mountain Airport
# Country?
USA
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122690034-8f347980-d1ec-11eb-88be-6970caf72f33.png)
