### ISSUE TITLE
ZSWA-Wuhu Xuanzhou Airport-ANHUI-CHINA

### ISSUE THREAD

**Issue by korgast** [InfiniteFlightAirportEditing/Airports#7698]
# Airport Name
Wuhu Xuanzhou Airport
# Country?
China
# Improvements that need to be made?
From scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by korgast** [comment]
Sent to OR

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126183469-700c42e5-30c7-4ada-8ce4-6568617bc908.png)
