### ISSUE TITLE
PHOG-Kahului Airport-HAWAII-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#77]

**Comment by carmichaelalonso** [comment]
Ryan's doing this.

**Comment by Swang007** [comment]
Minor change to a spawn point typo.

**Comment by Swang007** [comment]
Added ATIS frequency and removed annoying spawn point in front of runway 02

**Comment by Swang007** [comment]
Taxiways are not aligned.

https://community.infinite-flight.com/t/hawaiian-taxiways/9855

**Comment by dushyants19** [comment]
#317 @samuelandersson Are your changes in IF?

**Comment by dushyants19** [comment]
Doing some line fixes :)

**Comment by dushyants19** [comment]
Removed White lines and some Minor changes.

Approved by Jonathan.

**Comment by dushyants19** [comment]
Its moved from satellite imagery, misaligned with G maps

**Comment by dushyants19** [comment]
Alinged now with a redo

**Comment by TristinWoolf** [comment]
All hold short lines are wrong. Easy fix.

**Comment by TristinWoolf** [comment]
Being fixed by @samuelandersson. Not gonna bother assigning you.

**Comment by samuelandersson** [comment]
Changed hold short line attribute.

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/15e4be747695197ae62d1150c42bdf0f0a8ba65c)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18976713/b387e420-8679-11e6-9ee0-3a5f07713699.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/89126550-00235380-d4ac-11ea-975d-06be2da2af72.png)
