### ISSUE TITLE
ETSF-Fürstenfeldbruck Air Base-BAYERN-GERMANY

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#770]
I'll do this one

**Comment by moritzbabl** [comment]
Sent for approval

**Comment by dushyants19** [comment]
14c8721

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17277646/86977de0-570d-11e6-8b79-d3c1910ab224.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17643103/1f3bfa50-6125-11e6-9385-c4f1b12220c8.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17643104/26a62194-6125-11e6-8c1c-93a5fef46c66.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17643107/2f798a5e-6125-11e6-87bf-082a58271448.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21966346/0b005c48-db37-11e6-85f3-bb59c5c7eb40.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21966351/2732c0e0-db37-11e6-844a-512c23c1894f.png)

![Uploading image.png…]()

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21966359/40646866-db37-11e6-9321-1e9f5c2085a9.png)

**Comment by moritzbabl** [comment]
Fixed now, displaced thresholds had to be changed to blastpads
