### ISSUE TITLE
ZYDD-Dandong Langtou Airport-LIAONING-CHINA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#7707]
# Airport Name
Dandong - Langtou
# Country?
CN
# Improvements that need to be made?
New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
1/19 - ~10500ft

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123509414-00d05580-d63b-11eb-9fa6-6c576c5b2fea.png)
