### ISSUE TITLE
CED8-Thunder Bay/Eldorado Airport-ONTARIO-CANADA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7716]
# Airport Name
Thunder Bay/Eldorado Airport
# Country?
Canada
# Improvements that need to be made?
New airport.
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122641674-687f2180-d0cc-11eb-8c86-abb678ca5425.png)
