### ISSUE TITLE
CEE6-Twin Island Airpark-ALBERTA-CANADA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7720]
# Airport Name
Twin Island Airpark
# Country?
Canada
# Improvements that need to be made?
New airport; has a folder, no autogen.
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122490282-4770e080-cfa7-11eb-8c1e-1637aa97ba44.png)
