### ISSUE TITLE
CEF2-Belwood Airport-ONTARIO-CANADA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7722]
# Airport Name
Belwood Airport
# Country?
Canada
# Improvements that need to be made?
New airport; has a folder, no autogen.
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122641783-f4914900-d0cc-11eb-9b20-bb03d8af0741.png)
