### ISSUE TITLE
EDME-Eggenfelden Airport-BAYERN-GERMANY

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#773]
I'll do this

**Comment by moritzbabl** [comment]
Sent for approval

**Comment by dushyants19** [comment]
No email received with this Name

**Comment by moritzbabl** [comment]
Just sent it again

**Comment by dushyants19** [comment]
e7a18f1

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19224994/630187e6-8e57-11e6-97cd-e68fdc6919d1.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21984627/6a7f3b96-dbbc-11e6-9859-a5e62d2630b5.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21984635/735e7506-dbbc-11e6-9095-3e5666db3d33.png)

**Comment by moritzbabl** [comment]
fixed
