### ISSUE TITLE
OJAI-Queen Alia Airport-AMMAN-JORDAN

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#774]
Queen Alia International

**Comment by Aviationluver** [comment]
I can re-do this one.

**Comment by Aviationluver** [comment]
Sent this one off to be reviewed.

**Comment by Aviationluver** [comment]
Sent this one off to be reviewed again (I sent the apt.dat a few days ago actually)

**Comment by dushyants19** [comment]
f3a01af

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17078125/af2fa6ba-50af-11e6-8617-9778b4098af6.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17078126/c6c9ffd2-50af-11e6-9009-671d6b35057b.png)

**Comment by kilt46** [comment]
Lines for gates are not like the satellite image!

**Comment by Aviationluver** [comment]
I have sent this one in for review again. Some gates have been re-done according to Google Earth Imagery.

**Comment by kilt46** [comment]
MISSING
![image](https://cloud.githubusercontent.com/assets/14023167/17244970/ef140494-5549-11e6-9c0a-67b5e794c508.png)

**Comment by Aviationluver** [comment]
Sent off for review again. I have added the missing gates.

**Comment by kilt46** [comment]
Hmm this airport still seems confused. I have added white lines from Google. Things just don't line up
![image](https://cloud.githubusercontent.com/assets/14023167/17793460/0e367b80-656d-11e6-9527-24d449d7c1bf.png)

**Comment by Aviationluver** [comment]
Can someone please unassign me from this airport? I can't seem to get it right. I would like to give someone else the opportunity to try this one.

**Comment by ZaidSal** [comment]
Assign Me this One as i well-know OJAI and i can Re-done it

**Comment by dushyants19** [comment]
I have invited you, please check your email and accept it.

**Comment by ZaidSal** [comment]
Done

**Comment by ZaidSal** [comment]
Send off review, if it wasnt good, then unassign me

**Comment by dushyants19** [comment]
Doing this using SAS

**Comment by dushyants19** [comment]
should be fixed

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20043867/0a5c2bce-a459-11e6-9531-71a6d5ffbfc8.png)

**Comment by brunocr1050** [comment]
@davide-dc will be reworking this airport (pending assignation to this issue once he accepts the invite).

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/104820527-d14f2e80-57fa-11eb-8117-a98a852d6a4e.png)
