### ISSUE TITLE
CEF3-Bow Island Airport-ALBERTA-CANADA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7745]
# Airport Name
Bow Island Airport
# Country?
Canada
# Improvements that need to be made?
Has a new folder and an autogen folder. Old ICAO = EF3, New ICAO = CEF3.
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122489861-34a9dc00-cfa6-11eb-8244-89877693191c.png)
