### ISSUE TITLE
RJOK

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#775]
Kochi Airport

**Comment by dushyants19** [comment]
@Ksisky hows this going

**Comment by Ksisky** [comment]
I was having scenery problems with this one, Wedbing wasn't loading any detail at all.

**Comment by dushyants19** [comment]
ok ill put it for grabs

**Comment by bavAVIA** [comment]
Taking over.

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27518916-e0837020-59af-11e7-883c-fa8123c59574.png)

**Comment by kilt46** [comment]
https://drive.google.com/open?id=0B-UR84lbYzkNV3ROYTdvcF9DUEE
