### ISSUE TITLE
KSTJ-Rosecrans Memorial Airport-MISSOURI-USA

### ISSUE THREAD

**Issue by LawinS** [InfiniteFlightAirportEditing/Airports#7752]
# Airport Name
Rosecrans Memorial Airport
# Country?
USA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yessir
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122673026-36d18d80-d194-11eb-8d1f-013af245261e.png)
