### ISSUE TITLE
WIBS-Bengkalis-SUMATRA-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#7755]
# Airport Name
Sungai Pakning
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122843565-5e744300-d2c5-11eb-9b76-fc2fd4de8c8f.png)
