### ISSUE TITLE
GMME-Rabat–Sale Airport-RABAT–SALE–KENITRA-MOROCCO

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7759]
# Airport Name
Rabat–Salé Airport
# Country?
Morocco
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
Runway 11'483 ft, Bravo

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124199990-dc8cd280-da99-11eb-98af-0b64043108b9.png)
