### ISSUE TITLE
SJHW-Professor Mauricio Joppert Airport-MINAS GERAIS-BRAZIL

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#7762]
# Airport Name
Professor Mauricio Joppert Airport
# Country?
Brazil
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
LOw

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123346267-81009900-d51d-11eb-9a7e-8f392afbe527.png)
