### ISSUE TITLE
VIJU-Jammu Airport-Jammu & Kashmir-India

### ISSUE THREAD

**Issue by KaalicharanDH** [InfiniteFlightAirportEditing/Airports#7769]
# Airport Name
Jammu Airport
# Country?
India
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Yes

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123511035-958b8100-d644-11eb-8c8d-f310485bc725.png)
