### ISSUE TITLE
TJAB-Antonio/Nery/Juarbe Pol Airport-ARECIBO-PUERTO RICO

### ISSUE THREAD

**Issue by bylrret** [InfiniteFlightAirportEditing/Airports#777]
I'm doing this one. It needs spawn points, lights, and a part of the taxiway. It's a small airport, I will finish this one quickly.

**Comment by bylrret** [comment]
I have moved the whole airport.

**Comment by IFAEpat** [comment]
I still see this as an x-plane file, I'll redo it

**Comment by IFAEpat** [comment]
No ramp starts either!

**Comment by IFAEpat** [comment]
I am so dumb, I looked at the wrong airport

**Comment by IFAEpat** [comment]
need to fix it actually

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19213633/2c96168a-8d36-11e6-9de6-b7f04fe5dd02.png)
