### ISSUE TITLE
KPAO-Palo Alto Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by Pingu29** [InfiniteFlightAirportEditing/Airports#7770]
# Airport Name
Palo Alto Airport
# Country?
United States
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by AleksanderIF** [comment]
#33

**Comment by ECoops-123** [comment]
#33 duplicate

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122834153-aee2a500-d2b3-11eb-9e27-084427e91bcf.png)
