### ISSUE TITLE
CEG4-Drumheller Municipal Airport-ALBERTA-CANADA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7777]
# Airport Name
Drumheller Municipal Airport
# Country?
Canada
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122488727-acc2d280-cfa3-11eb-8e35-d3485d54ca16.png)
