### ISSUE TITLE
CEG5-Chipewyan Lake Airport-ALBERTA-CANADA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7778]
# Airport Name
Chipewyan Lake Airport
# Country?
Canada
# Improvements that need to be made?
New airport; has a folder, no autogen.
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122488515-38882f00-cfa3-11eb-83f4-6b2b85edc2ad.png)
