### ISSUE TITLE
KPHL-Philadelphia International Airport-PENNSYLVANIA-USA

### ISSUE THREAD

**Issue by david-garden** [InfiniteFlightAirportEditing/Airports#778]
I can do this one, as I am almost done with KSTL!

**Comment by david-garden** [comment]
Thank you, Ice!

**Comment by david-garden** [comment]
Won't be doing this one either. One airport only for me :)

**Comment by TristinWoolf** [comment]
Up for grabs!

**Comment by Aviationluver** [comment]
I can do this one.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19254586/b60b8ac2-8f1a-11e6-9210-8509f21b327e.png)
![image](https://cloud.githubusercontent.com/assets/14023167/19254590/c9f2f890-8f1a-11e6-9194-e1fd47ff9d75.png)

**Comment by Czechoslovaki** [comment]
I'd like to be assigned to this for the following reasons:

- Add new taxiways
- Adjust taxiway paving (many incorrect pavings)
- Add hangars, parking spots
- Add missing lines (many)
- Realign taxiways and lines (currently very inaccurate to imagery)

Bing has all of this stuff covered.

**Comment by Czechoslovaki** [comment]
Sent For OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90841534-8354fe00-e322-11ea-9408-740fce91c5c3.png)
