### ISSUE TITLE
LTBU-Corlu Ataturk Airport-TEKIRDAG-TURKEY

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7787]
# Airport Name
Çorlu Atatürk
# Country?
Turkey
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
Bravo Airport!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124202495-12cd5080-daa0-11eb-9425-4a743546b653.png)
