### ISSUE TITLE
LTAY-Cardak Airport-DENIZLI-TURKEY

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7788]
# Airport Name
Çardak
# Country?
Turkey
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
Bravo Airport

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124201702-48713a00-da9e-11eb-9598-aaf7731c586c.png)
