### ISSUE TITLE
VTSP-Phuket International Airport-PHUKET-THAILAND

### ISSUE THREAD

**Issue by B777fan** [InfiniteFlightAirportEditing/Airports#779]
Adding spawn points and fixing little things up.

**Comment by B777fan** [comment]
Thanks Ice! :)

**Comment by dushyants19** [comment]
Up for grabs

**Comment by Aviationluver** [comment]
I can re-do this one.

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20819118/0cd5dbf4-b7f8-11e6-8862-4b5ddd67486a.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/97123771-4b3fb200-16fb-11eb-8987-9beb9fe1fc09.png)
