### ISSUE TITLE
CEG8-North Seal River Airport-MANITOBA-CANADA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7790]
# Airport Name
North Seal River Airport
# Country?
Canada
# Improvements that need to be made?
New airport; has a folder, no autogen.
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122643762-450da400-d0d7-11eb-9879-6dbfda9f6f45.png)
