### ISSUE TITLE
UMNI-Kukoviatsino Aerodrome-VITEBSK-BELARUS

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#7791]
# Airport Name
Kukoviatsino Aerodrome
# Country?
Belarus 🇧🇾
# Improvements that need to be made?
New
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124104889-53898300-da28-11eb-852c-41a60d4f80a4.png)
