### ISSUE TITLE
UMNM-Novo-Pashkovo Airfield-MOGILEV-BELARUS

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#7792]
# Airport Name
Novo-Pashkovo Airfield
# Country?
Belarus 🇧🇾
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124039920-7afd3300-d9c9-11eb-8cd1-69b8aae7e64d.png)
