### ISSUE TITLE
UMNS-Bobruisk Aeroclub-MOGILEV-BELARUS

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#7793]
# Airport Name
Bobruisk Aeroclub
# Country?
Belarus 🇧🇾
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124039352-653b3e00-d9c8-11eb-84df-5516de6acde1.png)
