### ISSUE TITLE
NH69-Windsock Village-NEW HAMPSHIRE-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#7795]
# Airport Name
Windsock Village
# Country?
USA
# Improvements that need to be made?
add to IF
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122689857-5d6ee300-d1eb-11eb-99d8-6d036a88bd6c.png)
