### ISSUE TITLE
TJPS-Mercedita-PONCE-PUERTO RICO

### ISSUE THREAD

**Issue by bylrret** [InfiniteFlightAirportEditing/Airports#780]
Small airport, I will do it

**Comment by bylrret** [comment]
Sent to #peer-review.

**Comment by bylrret** [comment]
Waiting for approval

**Comment by dushyants19** [comment]
18aedb0

**Comment by IFAEpat** [comment]
Some errors with this one, I'll fix them

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19207749/204c80ee-8cb9-11e6-948f-2d490ef88e7c.png)
