### ISSUE TITLE
SCON-Quellon-CHILOE-CHILE

### ISSUE THREAD

**Issue by SpeedbirdCL** [InfiniteFlightAirportEditing/Airports#7806]
# Airport Name
Quellon
# Country?
Chile
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/131269280-65d2398b-be32-4532-80b8-d8746efc20c1.png)
