### ISSUE TITLE
SCQY-Villa Portales-ARAUCANIA-CHILE

### ISSUE THREAD

**Issue by SpeedbirdCL** [InfiniteFlightAirportEditing/Airports#7808]
# Airport Name
Villa Portales
# Country?
Chile
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
You've exceeded the limit of airports you can have assigned simultaneously.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124200260-7d7b8d80-da9a-11eb-94d4-73a16938bb74.png)
