### ISSUE TITLE
LFEB-Dinan Trelivan Airport-BRETAGNE-FRANCE

### ISSUE THREAD

**Issue by RobertineIFC** [InfiniteFlightAirportEditing/Airports#7809]
# Airport Name
Lessay Airport
# Country?
France
# Improvements that need to be made?
Rework
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
Complete the other 3 airports you have assigned.

**Comment by RobertineIFC** [comment]
ok

**Comment by brunocarbone3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/135541951-89495480-db76-4532-9579-ea29e7b2d12a.png)
