### ISSUE TITLE
MYEL

### ISSUE THREAD

**Issue by TristinWoolf** [InfiniteFlightAirportEditing/Airports#781]
Lee Stocking Airport

Being redone.

**Comment by TristinWoolf** [comment]
Finished. This particular file had no airport info, aka "[-]" in the file name. This should be removed.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19418971/8ed194e6-9394-11e6-89af-c4f02281d283.png)
