### ISSUE TITLE
LLBS-Be'er Sheva Airfield-BEERSHEBA-ISRAEL

### ISSUE THREAD

**Issue by zhf21** [InfiniteFlightAirportEditing/Airports#7813]
# Airport Name
Be'er Sheva Airfield
# Country?
Israel
# Improvements that need to be made?
Redo (auto-gen)
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123562273-4728d000-d773-11eb-8746-8a1520dc09fd.png)
