### ISSUE TITLE
CEH2-Cu Nim Airport-ALBERTA-CANADA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7818]
# Airport Name
Cu Nim Airport
# Country?
Canada
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122487998-28238480-cfa2-11eb-8b36-9eb7f7751305.png)
