### ISSUE TITLE
CEH3-Ponoka Industrial Airport-ALBERTA-CANADA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7819]
# Airport Name
Ponoka Industrial Airport
# Country?
Canada
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122487761-9ae03000-cfa1-11eb-9a34-652a6ca6aeeb.png)
