### ISSUE TITLE
CEH5-Red Earth Creek Airport-ALBERTA-CANADA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7820]
# Airport Name
Red Earth Creek Airport
# Country?
Canada
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122487565-30c78b00-cfa1-11eb-9c42-433372d0709c.png)
