### ISSUE TITLE
KGRK-Robert Gray AAF-TEXAS-USA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7822]
# Airport Name
Robert Gray AAF
# Country?
US
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
Bravo Airport

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122687906-981e4e80-d1de-11eb-8545-104b9d777064.png)
