### ISSUE TITLE
NTKH-Fakahina Airport-THE TUAMOTU AND GAMBIER ISLANDS-FRENCH POLYNESIA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#7834]
![image](https://user-images.githubusercontent.com/51279558/121408883-b732fb80-c915-11eb-92be-8c6212596f3d.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122682619-259e7600-d1c0-11eb-8d0f-be4e39f9230c.png)
