### ISSUE TITLE
CEJ6-Elk Point Airport-ALBERTA-CANADA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7837]
# Airport Name
Elk Point Airport
# Country?
Canada
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122486738-489e0f80-cf9f-11eb-8a41-940d7f3da1f4.png)
