### ISSUE TITLE
CEJ4-Claresholm Industrial Airport-ALBERTA-CANADA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7844]
# Airport Name
Claresholm Industrial Airport
# Country?
Canada
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122132393-63864d80-ce00-11eb-8cb6-315266cb26c4.png)
