### ISSUE TITLE
EBAM-Amougies Airport-HAINAUT-BELGIUM

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#7845]
# Airport Name
Amougies Airport
# Country?
Belgium 🇧🇪
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122670990-3a601700-d18a-11eb-9890-add684330d44.png)
