### ISSUE TITLE
EBAR-Arlon-Sterpenich Aerodrome-LUXEMBOURG-BELGIUM

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#7846]
# Airport Name
Arlon-Sterpenich Aerodrome
# Country?
Belgium 🇧🇪
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122670886-d6d5e980-d189-11eb-9201-e7321ef31b10.png)
