### ISSUE TITLE
EBBN-Büllingen Airfield-LIÈGE-BELGIUM

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#7847]
# Airport Name
Büllingen Airfield
# Country?
Belgium 🇧🇪
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122670793-616a1900-d189-11eb-91a9-e4c187c4af49.png)
