### ISSUE TITLE
ZYYK-Yingkou Lanqi Airport-LIAONING-CHINA

### ISSUE THREAD

**Issue by HKK008** [InfiniteFlightAirportEditing/Airports#7853]
# Airport Name
Yingkou Lanqi Airport
# Country?
China
# Improvements that need to be made?
New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by brunocarbone3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/135528469-8770b6d5-1339-4ca3-aee1-610806173afc.png)
