### ISSUE TITLE
KWWD-Cape May County Airport-NEW JERSEY-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#7854]
# Airport Name
Cape May County
# Country?
USA
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122682062-fcc8b180-d1bc-11eb-8076-3266144a5443.png)
