### ISSUE TITLE
WAGF-Kuala Pembuang-KALIMANTAN-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#7855]
# Airport Name
Kuala Pembuang
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124352651-45259d80-dbc7-11eb-8469-3a5cc1edfa44.png)
