### ISSUE TITLE
ZWCM-Qiemo Yudu Airport-XINJIANG-CHINA

### ISSUE THREAD

**Issue by Yuzhe716** [InfiniteFlightAirportEditing/Airports#7856]
# Airport Name
Qiemo Yudu Airport
# Country?
China
# Improvements that need to be made?
Fully redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123492923-870b7e00-d5e0-11eb-9ea3-0fd62e8e71a5.png)
