### ISSUE TITLE
EBBX-Jehonville Air Base-LUXEMBOURG-BELGIUM

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#7857]
# Airport Name
Jehonville Air Base
# Country?
Belgium 🇧🇪
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122670699-ed2f7580-d188-11eb-9898-16c176763296.png)
