### ISSUE TITLE
EBCV-Chièvres Airport-HAINAUT-BELGIUM

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#7858]
# Airport Name
Chièvres Airport
# Country?
Belgium 🇧🇪
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122658418-98611000-d132-11eb-910e-088536c91c99.png)
