### ISSUE TITLE
EBGG-Geraardsbergen Overboelare-OOST-VLAANDEREN-BELGIUM

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#7859]
# Airport Name
Geraardsbergen Overboelare
# Country?
Belgium 🇧🇪
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122656296-c50b2c80-d11e-11eb-96cd-f1376b5e86a7.png)
