### ISSUE TITLE
EBHN-Hoevenen Airport-ANTWERPEN-BELGIUM

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#7861]
# Airport Name
Hoevenen Airport
# Country?
Belgium 🇧🇪
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122656131-8fb20f00-d11d-11eb-8938-e5badb6c8c02.png)
