### ISSUE TITLE
EBIS-ATH/Isières Airport-HAINAUT-BELGIUM

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#7862]
# Airport Name
ATH/Isières Airport
# Country?
Belgium 🇧🇪
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122656052-fb47ac80-d11c-11eb-9e04-c20acfa2b582.png)
