### ISSUE TITLE
EBKT-Kortrijk/Wevelgem International Airport-WEST-VLAANDEREN-BELGIUM

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#7863]
# Airport Name
Kortrijk/Wevelgem International Airport
# Country?
Belgium 🇧🇪
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122654644-79528600-d112-11eb-9fdb-7e62223139ee.png)
