### ISSUE TITLE
ZBXH-Xilinhot Airport-INNER MONGOLIA-CHINA

### ISSUE THREAD

**Issue by zacky89315** [InfiniteFlightAirportEditing/Airports#7864]
# Airport Name
Xilinhot Airport
# Country?
China
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123491669-e23b7180-d5dc-11eb-92b8-2a5184d138c7.png)
