### ISSUE TITLE
ZYBA-Baicheng Chang'an Airport-JILIN-CHINA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#7865]
# Airport Name
Baicheng Chang'an
# Country?
CN
# Improvements that need to be made?
New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123491460-5aedfe00-d5dc-11eb-873b-a988296a348b.png)
