### ISSUE TITLE
CEK2-Braeburn Airport-YUKON-CANADA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7866]
# Airport Name
Braeburn Airport
# Country?
Canada
# Improvements that need to be made?
New airport; has a folder, no autogen.
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122640075-066dee80-d0c3-11eb-81f6-09d6ec072909.png)
