### ISSUE TITLE
CEL3-East Linton Airport-ONTARIO-CANADA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7868]
# Airport Name
East Linton Airport
# Country?
Canada
# Improvements that need to be made?
New airport; has a folder, no autogen.
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122641530-85672500-d0cb-11eb-9dce-c7562873ca5e.png)
