### ISSUE TITLE
EBDT-Schaffen Airport-VLAAMS BRABANT-BELGIUM

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#7869]
# Airport Name
Schaffen Airport
# Country?
Belgium 🇧🇪
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122654535-c5e99180-d111-11eb-9583-5bddffd2c8ec.png)
