### ISSUE TITLE
SKCG-Cartagena Airport-BOLIVAR-COLOMBIA

### ISSUE THREAD

**Issue by B777fan** [InfiniteFlightAirportEditing/Airports#787]
Doing this, needs a redo.

**Comment by TristinWoolf** [comment]
@B777fan Take note that this is your third, and final issue assigned to you until you finish one. :)

**Comment by B777fan** [comment]
@TristinWoolf thanks, I should be finished one soon.

**Comment by B777fan** [comment]
Waiting approval.

**Comment by IFAEpat** [comment]
Was done a while ago...

**Comment by kilt46** [comment]
This has NOT been done!!
![image](https://cloud.githubusercontent.com/assets/14023167/19626309/151116a8-98f4-11e6-8eb7-5c52cb87bfac.png)

**Comment by dushyants19** [comment]
It wasnt, @IFAEpat. Please dont't close issues which arent yours without my consent. thanks

**Comment by dushyants19** [comment]
@B777fan any progress on this? I'll give it to someone else if you can't do it

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by dushyants19** [comment]
Used @B777fan's latest copy, made some changes added it.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20021718/3645c2d2-a2a5-11e6-83b7-274dfd4b7549.png)

**Comment by brunocr98** [comment]
Alfonso wants to make some improvements and minor updates (discussed in DM).

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30775825-28780f9c-a061-11e7-87d4-c55d95c52223.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/59702342-ddfa4380-91cd-11e9-94ac-c5c2cae7090e.jpg)
