### ISSUE TITLE
EBMG-Matagne-La-Petite Airport-NAMUR-BELGIUM

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#7870]
# Airport Name
Matagne-La-Petite Airport
# Country?
Belgium 🇧🇪
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122653847-25916e00-d10d-11eb-8162-9307a98735c3.png)
