### ISSUE TITLE
EBML-Maillen Airport-NAMUR-BELGIUM

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#7871]
# Airport Name
Maillen Airport
# Country?
Belgium 🇧🇪
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122653785-a734cc00-d10c-11eb-97e2-25e7eb6be19e.png)
