### ISSUE TITLE
RPUV-Virac Airport-CATANDUANES-PHILIPPINES

### ISSUE THREAD

**Issue by jaypzs** [InfiniteFlightAirportEditing/Airports#7872]
# Airport Name
Virac Airport
# Country?
Philippines
# Improvements that need to be made?
Provide Gates and Ramps
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123181608-3d415d00-d453-11eb-9c6d-698f196c352c.png)
