### ISSUE TITLE
KSVN-Hunter Army Airfield-GEORGIA-USA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7873]
# Airport Name
Hunter Army Airfield
# Country?
USA
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Bravo; 10/28 = 11,375

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122686181-90a67780-d1d5-11eb-9d63-0bc847e0749f.png)
