### ISSUE TITLE
WAYL-Ilaga-PAPUA-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#7874]
# Airport Name
Ilaga
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124352491-fa575600-dbc5-11eb-92be-faf5b1298263.png)
