### ISSUE TITLE
ZYDQ-Daqing Sartu Airport-HEILONGJIANG-CHINA

### ISSUE THREAD

**Issue by zacky89315** [InfiniteFlightAirportEditing/Airports#7878]
# Airport Name
Daqing Sartu Airport
# Country?
China
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123491182-bc619d00-d5db-11eb-9c87-410b31acf53c.png)
