### ISSUE TITLE
KJAX-Jacksonville International Airport-FLORIDA-USA

### ISSUE THREAD

**Issue by TristinWoolf** [InfiniteFlightAirportEditing/Airports#788]
Jacksonville International Airport.

Will be redoing this one.

**Comment by kilt46** [comment]
Gate types should be selected
![image](https://cloud.githubusercontent.com/assets/14023167/22403899/d94dc028-e5ea-11e6-9d96-6e7df568ceb3.png)

**Comment by kilt46** [comment]
Please review metadata
GATEs at terminal should be 'AIRLINE'
Select CARGO where the location fulfils Cargo duty
For GA type locations use General Aviation

Some of the spawn points have been set to default size C. I suspect this was saved as a 10.0 rather than a 10.50 file

**Comment by TristinWoolf** [comment]
Just checked though and everything seems to be proper. I will push the file again since it appears that some of the metadata selections on my end are not the same as what Kilt has.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22407061/d28b586a-e624-11e6-8df2-25e1f2f40baf.png)
