### ISSUE TITLE
EPGR-Gryźliny Airport-WARMIAN-MASURIAN-POLAND

### ISSUE THREAD

**Issue by StickThelanding** [InfiniteFlightAirportEditing/Airports#7887]
# Airport Name
Gryźliny Airport
# Country?
Poland
# Improvements that need to be made?
New airport 
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
Should this be EPLN?
![image](https://user-images.githubusercontent.com/14023167/124386075-19291b80-dc9e-11eb-8396-d9b8803036d9.png)

**Comment by AleksanderIF** [comment]
No, It's EPGR
https://www.ead.eurocontrol.int/eadbasic/pamslight-37643F1DD4867743518E86422B898946/Y6E3XAL7IZ3BK/EN/AIP/GEN/EP_GEN_2_4-0_en_2021-06-17.pdf
![4d0dda37c53a9615b3f0a80da92a2218](https://user-images.githubusercontent.com/53284798/124386181-dbe67d00-dce1-11eb-8893-4e4cbe81e7cf.png)

**Comment by becarboner3000** [comment]
Sorted, thanks Alexander.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124386518-82119300-dca0-11eb-84fb-e391e71351de.png)
