### ISSUE TITLE
LPMU-Mogadouro Airport-BRAGANCA-PORTUGAL

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7888]
# Airport Name
Mogadouro Airport
# Country?
Portugal
# Improvements that need to be made?
New airport; has a folder, no autogen.
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123176456-13833880-d449-11eb-964f-4bbc01da67da.png)
