### ISSUE TITLE
LPCH-Chaves Airport-VILA REAL-PORTUGAL

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7889]
# Airport Name
Chaves Airport
# Country?
Portugal
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123175164-e9c91200-d446-11eb-9ff5-6e8f45befad6.png)
