### ISSUE TITLE
KCWA-Central Wisconsin Airport-WISCONSIN-USA

### ISSUE THREAD

**Issue by TristinWoolf** [InfiniteFlightAirportEditing/Airports#789]
Central Wisconsin Airport

Will be redoing this also. This will be my third airport assignment.

**Comment by TristinWoolf** [comment]
Decided to take a little break from Project Bahamas and finished this up.

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/2d67e89d0c53e07b36168a8790903de44c6ebaae)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17266914/368334ce-55c4-11e6-8701-21382483ef51.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18230783/92e6e0c6-726b-11e6-895a-bed08aa33eb5.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18230788/9c09841a-726b-11e6-8b02-98d059c35e0a.png)
