### ISSUE TITLE
LTAN-Konya Airport-KONYA-TURKEY

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7890]
# Airport Name
Konya
# Country?
Turkey
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
Bravo Airport, both runways are 10984 ft

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124200661-8325a300-da9b-11eb-9519-c4fc911fb01c.png)
