### ISSUE TITLE
USMU-Novy Urengoy-YAMALO–NENETS-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7891]
# Airport Name
Novy Urengoy
# Country?
Russia
# Improvements that need to be made?
from scratch
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
Bravo Airport with octagons! ( ͡° ͜ʖ ͡°)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124035119-b85dc280-d9c1-11eb-9a5a-cf63fafeca46.png)
