### ISSUE TITLE
MRDC-Duacari 2 Airport-LIMON-COSTA RICA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7892]
# Airport Name
Duacari 2 Airport
# Country?
Costa Rica
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124193037-ce37ba00-da8b-11eb-9975-f8d99cbf9216.png)
