### ISSUE TITLE
MNBL-Bluefields Airport-ATLANTICO SUR-NICARAGUA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7893]
# Airport Name
Bluefields Airport
# Country?
Nicaragua
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124355835-d5b8a980-dbd8-11eb-868f-fd6286824037.png)
