### ISSUE TITLE
ZUTF-Chengdu Tianfu Airport-SICHUAN-CHINA

### ISSUE THREAD

**Issue by korgast** [InfiniteFlightAirportEditing/Airports#7896]
# Airport Name
Chengdu Tianfu Airport
# Country?
China
# Improvements that need to be made?
New airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
10000ft+

**Comment by korgast** [comment]
Sent to OR

**Comment by korgast** [comment]
Sent to OR

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/130363307-695cf125-60aa-457b-8c83-4affc49a03ce.png)
