### ISSUE TITLE
OMAG-Kizad Airport-ABU DHABI-UNITED ARAB EMIRATES

### ISSUE THREAD

**Issue by LawinS** [InfiniteFlightAirportEditing/Airports#7897]
# Airport Name
Kizad Airport
# Country?
United Arab Emirates
# Improvements that need to be made?
New airport
# Are you working on this airport?
Yup!
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124360409-3a7efe80-dbef-11eb-9f80-cf138da1734d.png)
