### ISSUE TITLE
1I8-Converse Airport-INDIANA-USA

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#7898]
# Airport Name
Converse Airport
# Country?
USA
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low :trollface:

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122674196-a26a2980-d199-11eb-9122-4a6609f26ff0.png)
