### ISSUE TITLE
KCVN-Clovis Regional-NEW MEXICO-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#7899]
# Airport Name
Clovis Regional
# Country?
USA
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124367004-6a42fc00-dc19-11eb-96d1-43de7a6d7c40.png)
