### ISSUE TITLE
EBMO-Moorsele Airport-WEST-VLAANDEREN-BELGIUM

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#7900]
# Airport Name
Moorsele Airport
# Country?
Belgium 🇧🇪
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122645828-f7e2ff80-d0e1-11eb-94a3-3e43fe8d4879.png)
