### ISSUE TITLE
EBNE-Neerpelt Airport-LIMBURG-BELGIUM

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#7901]
# Airport Name
Neerpelt Airport
# Country?
Belgium 🇧🇪
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122645744-7db27b00-d0e1-11eb-9d82-5b2cb3920857.png)
