### ISSUE TITLE
EBOR-Orchimont Airport-NAMUR-BELGIUM

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#7902]
# Airport Name
Orchimont Airport
# Country?
Belgium 🇧🇪
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122645068-f8799700-d0dd-11eb-84b1-3bc77dc14f28.png)
