### ISSUE TITLE
MHTE-Tela Airport-ATLANTIDA-HONDURAS

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7903]
# Airport Name
Tela Airport
# Country?
Honduras
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124359636-6f895200-dbeb-11eb-93d1-ef04eddd9d23.png)
