### ISSUE TITLE
MSET-El Tamarindo Airport-LA UNION-EL SALVADOR

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7904]
# Airport Name
El Tamarindo Airport
# Country?
El Salvador
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124359198-8af35d80-dbe9-11eb-8e59-82235620ed26.png)
