### ISSUE TITLE
MZSJ-Sarteneja Airstrip-COROZAL-BELIZE

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7905]
# Airport Name
Sarteneja Airstrip
# Country?
Belize
# Improvements that need to be made?
New Airport.
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122672522-7fd41280-d191-11eb-8cf9-bddeb2cf85dc.png)
