### ISSUE TITLE
EBSG-Saint-Ghislain Airport-HAINAUT-BELGIUM

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#7906]
# Airport Name
Saint-Ghislain Airport
# Country?
Belgium 🇧🇪
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122644728-5e651f00-d0dc-11eb-87a7-775eb55af574.png)
