### ISSUE TITLE
EBSU-Saint-Hubert Air Base-LUXEMBOURG-BELGIUM

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#7907]
# Airport Name
Saint-Hubert Air Base
# Country?
Belgium 🇧🇪
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122644616-ba7b7380-d0db-11eb-8d2a-82fc43097c69.png)
