### ISSUE TITLE
EBSM-Verrebroek Airport-EAST-VLAANDEREN-BELGIUM

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#7908]
# Airport Name
Verrebroek Airport
# Country?
Belgium 🇧🇪
# Improvements that need to be made?
New
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122644365-6fad2c00-d0da-11eb-9546-2ec13955a5e6.png)
