### ISSUE TITLE
MMTN-Tamuin Airport-SAN LUIS POTOSI-MEXICO

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7909]
# Airport Name
Tamuin Airport
# Country?
Mexico
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122644138-5eafeb00-d0d9-11eb-9933-af9b85d2199b.png)
