### ISSUE TITLE
KITR-Kit Carson County Airport-COLORADO-USA

### ISSUE THREAD

**Issue by LawinS** [InfiniteFlightAirportEditing/Airports#7918]
# Airport Name
Kit Carson County Airport
# Country?
United States of America
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yep
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122673301-67fe8d80-d195-11eb-974e-07c4c2005ab7.png)
