### ISSUE TITLE
ZSJD-Jingdezhen Luojia Airport-JIANGXI-CHINA

### ISSUE THREAD

**Issue by HKK008** [InfiniteFlightAirportEditing/Airports#7919]
# Airport Name
Jingdezhen Luojia
# Country?
China
# Improvements that need to be made?
New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by brunocarbone3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/135528698-af2d1860-d85e-44e9-99da-2085a98144b6.png)
