### ISSUE TITLE
EBTN-Goetsenhoven Airport-VLAAMS BRABANT-BELGIUM

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#7920]
# Airport Name
Goetsenhoven Airport
# Country?
Belgium 🇧🇪
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122670588-76927800-d188-11eb-95c4-b917666a6755.png)
