### ISSUE TITLE
EBTX-Theux Airport-LIÈGE-BELGIUM

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#7921]
# Airport Name
Theux Airport
# Country?
Belgium 🇧🇪
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122658490-99467180-d133-11eb-9d00-3bcfbe3fd5b6.png)
