### ISSUE TITLE
EBTY-Maubray Airport-HAINAUT-BELGIUM

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#7922]
# Airport Name
Maubray Airport
# Country?
Belgium 🇧🇪
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122658456-24733780-d133-11eb-867b-d5d16442e468.png)
