### ISSUE TITLE
MDSP-Cueva Las Maravillas Airport-SAN PEDRO DE MACORIS-DOMINICAN REPUBLIC

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7923]
# Airport Name
Cueva Las Maravillas Airport
# Country?
Dominican Republic
# Improvements that need to be made?
New Airport.
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124361961-c432ca00-dbf7-11eb-8e75-05b3e859e888.png)
