### ISSUE TITLE
WPOC-Oecussi-TIMOR-EAST TIMOR

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#7927]
# Airport Name
Oecussi
# Country?
Timor Leste
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124362350-e62d4c00-dbf9-11eb-89ee-70b10eda0758.png)
