### ISSUE TITLE
WPDB-Suai-TIMOR-EAST TIMOR

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#7928]
# Airport Name
Suai
# Country?
Timor Leste
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124362213-3952cf00-dbf9-11eb-977a-5e258e4b95e3.png)
