### ISSUE TITLE
KFES-Festus Memorial Airport-MISSOURI-USA

### ISSUE THREAD

**Issue by liamkirky** [InfiniteFlightAirportEditing/Airports#7929]
# Airport Name
Festus Memorial Airport
# Country?
USA
# Improvements that need to be made?
Done from scratch
# Are you working on this airport?
I could be. Depends on my mood later tonight 
# Airport Priority? (10000ft+ Runway, Low)
Not a Bravo

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122672912-967b6900-d193-11eb-97f7-97df4a5da4ac.png)
