### ISSUE TITLE
LGSM

### ISSUE THREAD

**Issue by TristinWoolf** [InfiniteFlightAirportEditing/Airports#793]
Samos Airport

This airport has already been redone by @PaulNielsen and is awaiting approval.

**Comment by dushyants19** [comment]
204f8f8

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17276926/005e3eb4-56fc-11e6-93b2-e79deba87cf7.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17831844/1524ac48-66ba-11e6-9993-94edd4e23496.png)
