### ISSUE TITLE
SKGP-Guapi/Juan Casiano Airport-CAUCA-COLOMBIA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7930]
# Airport Name
Guapi/Juan Casiano Airport
# Country?
Colombia
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/122672216-038cff80-d190-11eb-94c9-06d185f25f67.png)
