### ISSUE TITLE
L18-Fallbrook Community Airpark-CALIFORNIA-USA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#7931]
# Airport Name
Fallbrook Community Airpark
# Country?
USA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124364657-868a6d00-dc08-11eb-9589-f8dbb1005b64.png)
