### ISSUE TITLE
EBUL-Ursel Airport-EAST-VLAANDEREN-BELGIUM

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#7937]
# Airport Name
Ursel Airport
# Country?
Belgium 🇧🇪
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124361665-cbf16f00-dbf5-11eb-9028-372550aa682d.png)
