### ISSUE TITLE
EBZU-Zuienkerke Airfield-WEST-VLAANDEREN-BELGIUM

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#7939]
# Airport Name
Zuienkerke Airfield
# Country?
Belgium 🇧🇪
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124360499-cf81f780-dbef-11eb-84c0-d819deff5124.png)
