### ISSUE TITLE
KJST-John Murtha Johnstown-Cambria County Airport-PENNSYLVANIA-USA

### ISSUE THREAD

**Issue by LawinS** [InfiniteFlightAirportEditing/Airports#7940]
# Airport Name
John Murtha Johnstown-Cambria County Airport
# Country?
USA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124366119-f7368700-dc12-11eb-85be-a55ca6f1ae21.png)
