### ISSUE TITLE
HKBM-Bamburi Airport-COAST-KENYA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7945]
# Airport Name
Bamburi Airport
# Country?
Kenya
# Improvements that need to be made?
New Airport.
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124381801-0278c980-dc8a-11eb-9501-96c5b39db57c.png)
