### ISSUE TITLE
FAWK-Waterkloof AFB Airport-GAUTENG-SOUTH AFRICA

### ISSUE THREAD

**Issue by Yuzhe716** [InfiniteFlightAirportEditing/Airports#7947]
♻️

**Comment by Daniel-Baiks** [comment]
https://github.com/InfiniteFlightAirportEditing/Airports/issues/7205

**Comment by RhysV29** [comment]
Could someone assign me to this? I'd love to work on it.

**Comment by brunocarbone3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/135530455-7ec7459b-6958-4c4f-b462-35469ec60639.png)
