### ISSUE TITLE
LGHI

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#795]
Being redone!

**Comment by PaulNielsen** [comment]
Done, awaiting approval.

**Comment by dushyants19** [comment]
79efec8`

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17276586/1ee8df50-56f3-11e6-881c-638fdb1898db.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17833495/5e435ee0-66e4-11e6-941a-57832c304780.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17833545/0b529974-66e6-11e6-8aa7-89e9804aab59.png)
