### ISSUE TITLE
WPEC-Baucau-BAUCAU-EAST TIMOR

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#7951]
# Airport Name
Baucau
# Country?
Timor Leste
# Improvements that need to be made?
Create New
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124362115-b0d42e80-dbf8-11eb-8fac-30dad0f24321.png)
