### ISSUE TITLE
PFMP-Rampart Airport-ALASKA-USA

### ISSUE THREAD

**Issue by zhf21** [InfiniteFlightAirportEditing/Airports#7952]
# Airport Name
Rampart Airport
# Country?
U.S.A.
# Improvements that need to be made?
Redo (auto-gen).
# Are you working on this airport?
Yes.
# Airport Priority? (10000ft+ Runway, Low)
Low.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124367384-4cc36180-dc1c-11eb-996c-573264fa406e.png)
