### ISSUE TITLE
CNZ8-Grimsby Regional-ONTARIO-CANADA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#7953]
# Airport Name
Grimsby Regional
# Country?
Canada
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123527355-51c86400-d6a4-11eb-9e93-6ba13aba8cd4.png)
