### ISSUE TITLE
KJHW-Chautauqua County/Jamestown-NEW YORK-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#7955]
# Airport Name
Chautauqua County / Jamestown
# Country?
USA
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124363806-175e4a00-dc03-11eb-807e-cf37d5c1d73f.png)
