### ISSUE TITLE
CEL8-Eleonore Airport-QUEBEC-CANADA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7956]
# Airport Name
Eleonore Airport
# Country?
Canada
# Improvements that need to be made?
New airport; has a folder, no autogen.
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123527280-cd75e100-d6a3-11eb-9bd8-5744b70bca81.png)
