### ISSUE TITLE
CEM3-Whati Airport-NORTHWEST TERRITORIES-CANADA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7957]
# Airport Name
Whati Airport
# Country?
Canada
# Improvements that need to be made?
New airport; has a folder, no autogen.
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123526787-c220b680-d69f-11eb-92a5-4df7b452ea25.png)
