### ISSUE TITLE
RPVY-Catbalogan Airport-SAMAR-PHILIPPINES

### ISSUE THREAD

**Issue by jaypzs** [InfiniteFlightAirportEditing/Airports#7959]
# Airport Name
Catbalogan AIrport
# Country?
Philippines
# Improvements that need to be made?
From scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124026797-bdb60f80-d9b7-11eb-890b-7b2f8e347b12.png)
