### ISSUE TITLE
MYGF

### ISSUE THREAD

**Issue by TristinWoolf** [InfiniteFlightAirportEditing/Airports#796]
Grand Bahama International Airport

Being redone.

**Comment by TristinWoolf** [comment]
Done.

**Comment by kilt46** [comment]
MISSING SOME LINES
![image](https://cloud.githubusercontent.com/assets/14023167/16637095/1df50ccc-43a2-11e6-9bf9-ac9f83c7f6f6.png)

**Comment by TristinWoolf** [comment]
Fixing this.

**Comment by TristinWoolf** [comment]
This has been fixed to the best of my ability.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18620481/317b54e2-7dd9-11e6-9e99-69663171783c.png)
