### ISSUE TITLE
RPPN-Rancudo Airfield-THITU ISLAND-PHILIPPINES

### ISSUE THREAD

**Issue by jaypzs** [InfiniteFlightAirportEditing/Airports#7960]
# Airport Name
RPPN
# Country?
Philippines
# Improvements that need to be made?
From scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123943880-2bcfe780-d962-11eb-8a91-ed73fd710ab0.png)
