### ISSUE TITLE
CEN5-Cold Lake Regional Airport-ALBERTA-CANADA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7963]
# Airport Name
Cold Lake Regional Airport
# Country?
Canada
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123525771-d0b79f80-d698-11eb-980b-6bbd02a4f77d.png)
