### ISSUE TITLE
SKPQ-Captain Germán Olano Moreno Air Base-PALENQUERO-COLOMBIA

### ISSUE THREAD

**Issue by zhf21** [InfiniteFlightAirportEditing/Airports#7964]
# Airport Name
Captain Germán Olano Moreno Air Base
# Country?
Colombia
# Improvements that need to be made?
Redo (auto-gen)
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
10,000ft, Bravo

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124385885-54771a80-dc9d-11eb-9541-3e0c176abef1.png)
