### ISSUE TITLE
USKK-Kirov/Pobedilovo Airport-KIROV-RUSSIA

### ISSUE THREAD

**Issue by Daniboi737** [InfiniteFlightAirportEditing/Airports#7965]
# Airport Name
Pobedilovo
# Country?
Russia
# Improvements that need to be made?
Redone from scratch (currently it’s only auto-gen)
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by Daniboi737** [comment]
@AleksanderIF can be assigned

**Comment by becarboner3000** [comment]
Will be assigned once he's cleared from one of his issues.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124034768-41c0c500-d9c1-11eb-9813-e15daac57f8a.png)
