### ISSUE TITLE
KPBG-Plattsburgh International Airport-NEW YORK-USA

### ISSUE THREAD

**Issue by hossss6** [InfiniteFlightAirportEditing/Airports#7968]
# Airport Name
Plattsburgh International
# Country?
United States
# Improvements that need to be made?
Whole airport rework (the main thing would be adding spawns)
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124363622-f9dcb080-dc01-11eb-837e-f6a9b5de0161.png)
