### ISSUE TITLE
LGKY

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#797]
Being redone.

**Comment by dushyants19** [comment]
6faf5db

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17276777/9bdef5c6-56f8-11e6-8f92-d928be0e8797.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17832677/2c5b0b5a-66ce-11e6-8d36-dc07e288ad68.png)
