### ISSUE TITLE
KPGV-Pitt-Greenville-NORTH CAROLINA-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#7970]
# Airport Name
Pitt-Greenville
# Country?
USA
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124363534-630ff400-dc01-11eb-8b17-6843982c97d9.png)
