### ISSUE TITLE
CEP4-Ross International Airport-ALBERTA-CANADA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7971]
# Airport Name
Ross International Airport
# Country?
Canada
# Improvements that need to be made?
New airport; has a folder, no autogen.
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123525428-30f91200-d696-11eb-8a67-5eb915f96195.png)
