### ISSUE TITLE
EDFY-Elz Airport-HESSEN-GERMANY

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#7972]
# Airport Name
Flugplatz Elz
# Country?
Germain
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
This airport measures just under 2000 ft runway. 
![image](https://user-images.githubusercontent.com/14023167/124354430-95a1f880-dbd1-11eb-9009-3f828d18cf9b.png)

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/125209653-ea8fdf80-e25f-11eb-890a-2bf22f9517c3.png)
