### ISSUE TITLE
PADK-Adak Airport-ALASKA-USA

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#7973]
# Airport Name
Adak Airport
# Country?
USA
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124367311-b131f100-dc1b-11eb-9c11-8b19e67d3e7f.png)
