### ISSUE TITLE
CEQ4-Whetstone International Airport-ALBERTA-CANADA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7977]
# Airport Name
Whetstone International Airport
# Country?
Canada
# Improvements that need to be made?
New airport; has a folder, no autogen.
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124324129-15838080-db48-11eb-85fb-e56bc6411539.png)
