### ISSUE TITLE
CYSJ-Saint John Airport-NEW BRUNSWICK-CANADA

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#7978]
# Airport Name
Saint John Airport
# Country?
Canada
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124351809-22dd5100-dbc2-11eb-96dd-b6680918dc7a.png)
