### ISSUE TITLE
UHHH-Khabarovsk/Novy Airport-KHABAROVSK-RUSSIA

### ISSUE THREAD

**Issue by tsarkov90** [InfiniteFlightAirportEditing/Airports#798]
Redone. I wait the answer

**Comment by IFAEpat** [comment]
You have finished it @sentikum? We don't even know who you are...

**Comment by sentikum** [comment]
Really or is it sarcasm?

**Comment by sentikum** [comment]
So, before it I added russians scenario for x-plane desktop

**Comment by IFAEpat** [comment]
@sentikum you're not even "on" the team. Have you emailed airports@liveflightapp.com?

**Comment by sentikum** [comment]
Oh sorry.
Is it necessary to join your team?

**Comment by IFAEpat** [comment]
If you want to do the airport, yes @sentikum

**Comment by sentikum** [comment]
I sent message for email. 
I hope now you know me.😉

**Comment by dushyants19** [comment]
Check your email, accept the invite

**Comment by sentikum** [comment]
Done.
There are two runways 
13000 ft and 11000 ft.

**Comment by IFAEpat** [comment]
@sentikum did you accept Dush's invite to Slack?

**Comment by Swang007** [comment]
Was this airport committed? I can't find it in the pull request it was in yesterday, and the updated airport is not in the repo either

**Comment by sentikum** [comment]
How can I replace files in repo? I have updated apt.dat

**Comment by dushyants19** [comment]
Check your email, @sentikum. I've given feedback about the airport. Please improve it and send an email or a pull request. :)

**Comment by sentikum** [comment]
No.

**Comment by dushyants19** [comment]
89da88a

**Comment by kilt46** [comment]
Please number gates as per schematic
![image](https://cloud.githubusercontent.com/assets/14023167/16672944/4251770e-446f-11e6-8008-78d4214d8876.png)

**Comment by sentikum** [comment]
I fixed all gates

**Comment by dushyants19** [comment]
Fixes (spawns, name, roads) 

60d2f2e

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17267339/f4aced80-55cb-11e6-9993-b0aa9e22f892.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32467694-3b0d9672-c311-11e7-9b2c-f53fb244290c.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/43868436-3f89524a-9b33-11e8-8f84-dc67f26d727e.png)

**Comment by tsarkov90** [comment]
I've redone it

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/103033764-ddf8a380-4528-11eb-9150-5229868e2438.png)
