### ISSUE TITLE
UOOD-Dudinka Airport-KRASNOYARSK-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7981]
# Airport Name
Dudinka
# Country?
🇷🇺
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124034048-5a7cab00-d9c0-11eb-85bf-aec5146ebf35.png)
