### ISSUE TITLE
CYGR-Iles de La Madeleine Airport-QUEBEC-CANADA

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#7983]
# Airport Name
Iles de La Madeleine Airport
# Country?
Canada
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124351463-0d672780-dbc0-11eb-8863-63b040a3a937.png)
