### ISSUE TITLE
USHQ-Beloyarskiy Airport-KHANTY–MANSI-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7984]
# Airport Name
Beloyarskiy 
# Country?
🇷🇺 
# Improvements that need to be made?
redo from scratch
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124033007-fc9b9380-d9be-11eb-86f8-73170eaeae46.png)
