### ISSUE TITLE
USRK-Kogalym Airport-KHANTY–MANSI-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7985]
# Airport Name
Kogalym
# Country?
🇷🇺 
# Improvements that need to be made?
redo from scratch
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124030384-c01a6880-d9bb-11eb-9aac-171309d65caf.png)
