### ISSUE TITLE
YPLM-Learmonth Airport-WESTERN AUSTRALIA-AUSTRALIA

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Airports#7986]
# Airport Name
Learmonth Airport
# Country?
Australia
# Improvements that need to be made?
From Scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Bravo, 10,000.4 ft

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124203335-195cc780-daa2-11eb-8d55-8175831d81f7.png)
