### ISSUE TITLE
LBBA-Bahovica Airfield-LOVECH-BULGARIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#7987]
# Airport Name
Bahovica Airfield
# Country?
Bulgaria 🇧🇬
# Improvements that need to be made?
New
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124202914-1f05dd80-daa1-11eb-9d77-222a66b4e10a.png)
