### ISSUE TITLE
LBBB-Belchin Airfield-SOFIYA-BULGARIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#7988]
# Airport Name
Belchin Airfield
# Country?
Bulgaria 🇧🇬
# Improvements that need to be made?
New
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124202758-b585cf00-daa0-11eb-8979-125c1943b75a.png)
