### ISSUE TITLE
LBBL-Blagoevo Airfield-RUSE-BULGARIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#7989]
# Airport Name
Blagoevo Airfield
# Country?
Bulgaria 🇧🇬
# Improvements that need to be made?
New
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124384200-baf83a80-dc95-11eb-9895-e410c1e7c8ea.png)
