### ISSUE TITLE
RPVO-Ormoc Airport-LEYTE-PHILIPPINES

### ISSUE THREAD

**Issue by jaypzs** [InfiniteFlightAirportEditing/Airports#7991]
# Airport Name
Ormoc Airport
# Country?
Philippines
# Improvements that need to be made?
To add ramp and gates
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/125468441-6036a1ec-f619-4c4e-876c-3349194e9336.png)
