### ISSUE TITLE
VEGK-Gorakhpur Airport-Uttar Pradesh-INDIA

### ISSUE THREAD

**Issue by hari-shreyas** [InfiniteFlightAirportEditing/Airports#7993]
# Airport Name
Gorakhpur Airport
# Country?
India
# Improvements that need to be made?
Needs to be added with aprons, taxiways, etc
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by brunocarbone3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/134831507-46b3a9be-801a-4131-b134-78a17be55b2e.png)
