### ISSUE TITLE
UNKY-Kyzyl Airport-TUVA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7995]
# Airport Name
Kyzyl
# Country?
Russia
# Improvements that need to be made?
redo from scratch
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124027532-9ca1ee80-d9b8-11eb-9bd0-dc8c12c9d42b.png)
