### ISSUE TITLE
ULAM-Naryan-Mar-NENETS-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7996]
# Airport Name
Naryan-Mar
# Country?
Russia
# Improvements that need to be made?
redo from scratch
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124384838-bbde9b80-dc98-11eb-9f59-fc5d451031ff.png)
