### ISSUE TITLE
IN-0093-Vedanta Lanjigarh Airstrip-ODISHA-INDIA

### ISSUE THREAD

**Issue by Captainflight** [InfiniteFlightAirportEditing/Airports#7997]
# Airport Name
Vedanta Lanjigarh Airstrip
# Country?
India 
# Improvements that need to be made?
Needs to be added
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/125177231-b0f79f80-e19f-11eb-9513-984fd626567f.png)
