### ISSUE TITLE
UIIR-Irkutsk-2/Vostochny Airport-IRKUTSK-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#7998]
# Airport Name
Irkutsk-2 Vostochny
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124384631-df551680-dc97-11eb-85e9-94786ee28c7e.png)
