### ISSUE TITLE
3Y2-George L Scott Municipal Airport-IOWA-USA

### ISSUE THREAD

**Issue by huddys7** [InfiniteFlightAirportEditing/Airports#7999]
# Airport Name
George L Scott Municipal Airport
# Country?
United States of America
# Improvements that need to be made?
New Edit/Complete Rework
# Are you working on this airport?
Yes
# Priority
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124362602-833cb480-dbfb-11eb-92f2-464e0ff23046.png)
