### ISSUE TITLE
L35-Big Bear City Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#8]

**Comment by carmichaelalonso** [comment]
Removed assignment - no time...

**Comment by JcFl4** [comment]
What's wrong with it? Will take a look...

**Comment by carmichaelalonso** [comment]
@JcFl4 Suggested for improvement by Matt a long time ago, missing some T-Parking points, could do with more ramp starts

**Comment by Adam167** [comment]
Im happy to improve big bear

**Comment by Adam167** [comment]
Sent for review

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19876162/43967c12-9fa1-11e6-8a72-415c5eb4b5d4.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/72110212-611fea00-3316-11ea-9a58-971496c2228f.jpg)
