### ISSUE TITLE
KUCC

### ISSUE THREAD

**Issue by B777fan** [InfiniteFlightAirportEditing/Airports#800]
Fixing up Yucca Airstrip

**Comment by B777fan** [comment]
Don't really want to do this anymore

**Comment by dushyants19** [comment]
Why, DJ?

**Comment by dushyants19** [comment]
NV11 is the FAA iden... KUCC is the ICAO

**Comment by dushyants19** [comment]
... 
there is nothing here

**Comment by dushyants19** [comment]
Done in 0508c61ee73fa274901af496854fdb417a381980

**Comment by dushyants19** [comment]
Done with 0508c61ee73fa274901af496854fdb417a381980

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18799840/8ef02b1a-819f-11e6-9d4f-8ca8c882d104.png)
