### ISSUE TITLE
RPEN-El Nido-PALAWAN-PHILIPPINES

### ISSUE THREAD

**Issue by jaypzs** [InfiniteFlightAirportEditing/Airports#8000]
# Airport Name
RPEN
# Country?
PHILIPPINES
# Improvements that need to be made?
Add Ramps and Gates
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/125468260-ae715bb7-7c3f-44c4-a8da-574c9250fc82.png)
