### ISSUE TITLE
LBBO-Bohot-Lm Airport-LOVECH-BULGARIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#8001]
# Airport Name
Bohot-Lm Airport
# Country?
Bulgaria 🇧🇬
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124384050-46bd9700-dc95-11eb-902e-e5370b9effaf.png)
