### ISSUE TITLE
LBBQ-Byala Airport-RUSE-BULGARIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#8002]
# Airport Name
Byala Airport
# Country?
Bulgaria 🇧🇬
# Improvements that need to be made?
New
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124383893-75873d80-dc94-11eb-8927-0126d98ce1a6.png)
