### ISSUE TITLE
UUOT-Tambov Airport-TAMBOV-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8005]
# Airport Name
Tambov Donskoye
# Country?
Russia
# Improvements that need to be made?
redo from scratch
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124384516-360e2080-dc97-11eb-87e1-28f7b94d28fc.png)
