### ISSUE TITLE
UNKM-Krasnoyarsk Cheremshanka Airport-KRASNOYARSK-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8006]
# Airport Name
Krasnoyarsk Cheremshanka
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/125337357-84b15f80-e314-11eb-8acb-d7f858bd36a7.png)
