### ISSUE TITLE
LBBR-Breznik Airport-SOFIYA-BULGARIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#8007]
# Airport Name
Breznik Airport
# Country?
Bulgaria 🇧🇬
# Improvements that need to be made?
New
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124383799-06a9e480-dc94-11eb-8c47-d3a9f8d3b450.png)
