### ISSUE TITLE
LBBZ-Bazan Airport-RUSE-BULGARIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#8008]
# Airport Name
Bazan Airport
# Country?
Bulgaria 🇧🇬 
# Improvements that need to be made?
New
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124383714-94390480-dc93-11eb-9074-41a6395195c1.png)
