### ISSUE TITLE
LBDA-Daskal Atanasovo Airport-KHASKOVO-BULGARIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#8009]
# Airport Name
Daskal Atanasovo Airport
# Country?
Bulgaria 🇧🇬
# Improvements that need to be made?
New
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124383622-12e17200-dc93-11eb-8fd9-27626e055b09.png)
