### ISSUE TITLE
LROP-Henri Coanda Airport-BUCHAREST-ROMANIA

### ISSUE THREAD

**Issue by TheGamingGuy** [InfiniteFlightAirportEditing/Airports#801]
I'll be editing this airport

**Comment by dushyants19** [comment]
Any progress? @TheGamingGuy

**Comment by dushyants19** [comment]
@TheGamingGuy please respond.

**Comment by dushyants19** [comment]
Up for grabs

**Comment by Yifan081** [comment]
I can take care of this one.

**Comment by Yifan081** [comment]
Sent for review

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23321038/22a9b1c4-faa3-11e6-91a7-ae0262a7f3e4.png)

**Comment by MajorTomMueller** [comment]
https://community.infiniteflight.com/t/lrop-wrong-gate-restriction/302835

**Comment by brunocr98** [comment]
Fixed, pushing the changes in a few minutes.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54879450-1a084d00-4e07-11e9-907f-85e2e7130057.png)
