### ISSUE TITLE
KJMS-Jamestown Regional Airport-NORTH DAKOTA-USA

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#8010]
# Airport Name
Jamestown Regional Airport
# Country?
USA
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/125177246-d97f9980-e19f-11eb-9e4a-562dea8a1a8f.png)
