### ISSUE TITLE
YBMA-Mount Isa Airport-QUEENSLAND-AUSTRALIA

### ISSUE THREAD

**Issue by hossss6** [InfiniteFlightAirportEditing/Airports#8013]
# Airport Name
Mount Isa 
# Country?
Australia
# Improvements that need to be made?
Whole airport rework
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/124385654-4d9bd800-dc9c-11eb-8399-535108bbc440.png)
