### ISSUE TITLE
USHN-Nyagan Airport-KHANTY MANSI-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8014]
# Airport Name
Nyagan
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126004082-f525edc3-967a-4a67-8419-1fee4640a947.png)
