### ISSUE TITLE
LBDB-Dolna Banya Airport-SOFIYA-BULGARIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#8015]
# Airport Name
Dolna Banya Airport
# Country?
Bulgaria 🇧🇬
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/124850490-50315280-df66-11eb-97a2-7043d130fb0b.png)
