### ISSUE TITLE
LBDR-Draganovtsi Airport-LOVECH-BULGARIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#8016]
# Airport Name
Draganovtsi Airport
# Country?
Bulgaria 🇧🇬
# Improvements that need to be made?
New
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/124850729-cafa6d80-df66-11eb-8be5-0462ccb53d09.png)
