### ISSUE TITLE
LBDM-Dve Mogli Airport-RUSE-BULGARIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#8017]
# Airport Name
Dve Mogli Airport
# Country?
Bulgaria 🇧🇬
# Improvements that need to be made?
New
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/124850840-fe3cfc80-df66-11eb-86a3-a80e1dba5da3.png)
