### ISSUE TITLE
LTCU-Bingol Airport-BINGÖL-TURKEY

### ISSUE THREAD

**Issue by LawinS** [InfiniteFlightAirportEditing/Airports#8018]
# Airport Name
Bingol Airport
# Country?
Republic of Turkey 🇹🇷 
# Improvements that need to be made?
New airport addition
# Are you working on this airport?
Absolutely yes!
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/124851010-507e1d80-df67-11eb-9abd-9d4e8eaaf0c6.png)
