### ISSUE TITLE
OJAM-Amman Airport-AMMAN-JORDAN

### ISSUE THREAD

**Issue by LawinS** [InfiniteFlightAirportEditing/Airports#8022]
♻️

**Comment by liamkirky** [comment]
#7542?

**Comment by becarboner3000** [comment]
Bravo with a +10k feet runway... up for grabs.

**Comment by AviatorMan** [comment]
I can take this

**Comment by IFsami** [comment]
I'll take it

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/132603857-1eb2349b-03a7-47d9-89eb-f1b4c0a9054d.png)
