### ISSUE TITLE
LBGD-Gradishte Airport-VARNA-BULGARIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#8023]
# Airport Name
Gradishte Airport
# Country?
Bulgaria 🇧🇬
# Improvements that need to be made?
New
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/124851123-891df700-df67-11eb-9d55-bc96ba8acf61.png)
