### ISSUE TITLE
LBGI-Gorski Izvor Airport-KHASKOVO-BULGARIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#8024]
# Airport Name
Gorski Izvor Airport
# Country?
Bulgaria 🇧🇬
# Improvements that need to be made?
New
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/124851208-b5397800-df67-11eb-8013-6bfca64c6630.png)
