### ISSUE TITLE
LBGR-Grivitsa Airport-LOVECH-BULGARIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#8026]
# Airport Name
Grivitsa Airport
# Country?
Bulgaria 🇧🇬
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/125147666-5f450b80-e0f2-11eb-8a67-26c2f401a8d2.png)
