### ISSUE TITLE
LBHT-Ihtiman Airport-SOFIYA-BULGARIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#8027]
# Airport Name
Ihtiman Airport
# Country?
Bulgaria 🇧🇬
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/125147709-974c4e80-e0f2-11eb-8ce4-03b1e292a3ae.png)
