### ISSUE TITLE
LBIA-Bezmer Air Base-BURGAS-BULGARIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#8028]
# Airport Name
Bezmer Air Base
# Country?
Bulgaria 🇧🇬
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/125147630-22791480-e0f2-11eb-90a7-4e1d37f3dc48.png)
