### ISSUE TITLE
WAVV-Wamena-PAPUA-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#8032]
# Airport Name
Wamena
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/124919547-fe1b1c00-dfbb-11eb-8491-3c4a0b14b6aa.png)
