### ISSUE TITLE
NTTE-Tetiꞌaroa Airstrip-TETIAROA-FRENCH POLYNESIA

### ISSUE THREAD

**Issue by RobertineIFC** [InfiniteFlightAirportEditing/Airports#8033]
# Airport Name
Tetiaroa
# Country?
French Polynesia
# Improvements that need to be made?
Remake
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by Czechoslovaki** [comment]
@RobertineIFC how's this going?

**Comment by Czechoslovaki** [comment]
![image](https://user-images.githubusercontent.com/51279558/126857967-bfd15c0f-72a6-4cfa-9157-52d727ac940b.png)
