### ISSUE TITLE
CHB3-Hope Bay-NUNAVUT-CANADA

### ISSUE THREAD

**Issue by hossss6** [InfiniteFlightAirportEditing/Airports#8035]
# Airport Name
Hope Bay Airport
# Country?
Canada
# Improvements that need to be made?
Added Airport into IF
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
<img width="171" alt="CHB3" src="https://user-images.githubusercontent.com/76137019/125083062-8b7a7100-e08d-11eb-8bfb-0903575e74b6.PNG">
