### ISSUE TITLE
CHF2-Hope Field-ONTARIO-CANADA

### ISSUE THREAD

**Issue by hossss6** [InfiniteFlightAirportEditing/Airports#8036]
# Airport Name
Ottawa/Manotick (Hope Field) Airport
# Country?
Canada
# Improvements that need to be made?
Added Runway, Pavement, Spawn and Hangar
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
<img width="557" alt="CHF2" src="https://user-images.githubusercontent.com/76137019/125082884-5a9a3c00-e08d-11eb-8ab2-89fe38673c57.PNG">
