### ISSUE TITLE
CHG2-Harbour Grace-NEWFOUNDLAND-CANADA

### ISSUE THREAD

**Issue by hossss6** [InfiniteFlightAirportEditing/Airports#8037]
# Airport Name
Harbour Grace
# Country?
Canada
# Improvements that need to be made?
Adding airport in game
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/125084744-7c94be00-e08f-11eb-9f82-967eff31bcd1.png)
