### ISSUE TITLE
CHL2-Hillaton/Kings (Pvt)-NOVA SCOTIA-CANADA

### ISSUE THREAD

**Issue by hossss6** [InfiniteFlightAirportEditing/Airports#8038]
# Airport Name
Hillaton/kings (Pvt)
# Country?
Canada
# Improvements that need to be made?
New Airport in IF
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/125177175-434b7380-e19f-11eb-850f-0fb5c4233046.png)
