### ISSUE TITLE
CHM2-Spiritwood/H & M Fast Farms-SASKATCHEWAN-CANADA

### ISSUE THREAD

**Issue by hossss6** [InfiniteFlightAirportEditing/Airports#8039]
# Airport Name

# Country?
Spiritwood/H & M Fast Farms
# Improvements that need to be made?
Added Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/125177145-0f704e00-e19f-11eb-8923-ea63e9a5dbf1.png)
