### ISSUE TITLE
RJOM-Matsuyama-EHIME-JAPAN

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#804]
Matsuyama Airport - Japan

Last Japanese airport I will edit

**Comment by IFAEpat** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17244582/403d5ab6-5548-11e6-9583-28fdd86d9c7f.png)

**Comment by IFAEpat** [comment]
Gated

**Comment by kilt46** [comment]
missing some lines
![image](https://cloud.githubusercontent.com/assets/14023167/17720088/c344a194-63e4-11e6-9f51-ee167f1d4830.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17827732/9d496870-6647-11e6-8896-0a91ec160fc6.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17827734/a54f0868-6647-11e6-909b-4e9b30160465.png)
