### ISSUE TITLE
CHS3-Hillspring (Beck Farm)-ALBERTA-CANADA

### ISSUE THREAD

**Issue by hossss6** [InfiniteFlightAirportEditing/Airports#8040]
# Airport Name
Hillspring (Beck Farm)
# Country?
Canada
# Improvements that need to be made?
New Added Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/125144386-5862cc80-e0e3-11eb-9813-27fe54ca20c1.png)
