### ISSUE TITLE
CHF5-Murillo/Hane Field-ONTARIO-CANADA

### ISSUE THREAD

**Issue by hossss6** [InfiniteFlightAirportEditing/Airports#8042]
# Airport Name
Murillo/Hane Field 
# Country?
Canada
# Improvements that need to be made?
Newly added airport in IF
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/125147524-8d761b80-e0f1-11eb-8cb7-081fa81f507d.png)
