### ISSUE TITLE
WAEM-Buli-MALUKU-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#8043]
# Airport Name
Buli
# Country?
Indonesia
# Improvements that need to be made?
Create New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/125177210-7beb4d00-e19f-11eb-9f06-df8d825b5295.png)
