### ISSUE TITLE
ZGHY-Hengyang Nanyue Airport-HUNAN-CHINA

### ISSUE THREAD

**Issue by Captainflight** [InfiniteFlightAirportEditing/Airports#8044]
# Airport Name
Hengyang Nanyue Airport
# Country?
China
# Improvements that need to be made?
Rework
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/128268663-6d5ffbb0-f3e7-420c-8596-11dea7c7170a.png)
