### ISSUE TITLE
NTTM-Moorea Temae Airport-FRENCH POLYNESIA

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#8045]
# Airport Name
Moorea Temae Airport
# Country?
French Polynesia
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
High - Currently 3D In-Game but autogen on 2D.

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/125209543-034bc580-e25f-11eb-8690-774db5c1a805.png)
