### ISSUE TITLE
CJA3-Morden Regional-MANITOBA-CANADA

### ISSUE THREAD

**Issue by hossss6** [InfiniteFlightAirportEditing/Airports#8046]
# Airport Name
Morden Regional
# Country?
Canada
# Improvements that need to be made?
Airport rework
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/125209430-435e7880-e25e-11eb-8c07-2d41e60081a8.png)
