### ISSUE TITLE
CJA5-Nestor Falls-ONTARIO-CANADA

### ISSUE THREAD

**Issue by hossss6** [InfiniteFlightAirportEditing/Airports#8047]
# Airport Name
Nestor Falls
# Country?
Canada
# Improvements that need to be made?
Reworked airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/125209501-c8e22880-e25e-11eb-8823-29e561db503d.png)
