### ISSUE TITLE
NTTR-Raiatea Airport-FRENCH POLYNESIA

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#8048]
# Airport Name
Raiatea Airport
# Country?
French Polynesia
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
High - Currently 3D In-Game but autogen on 2D.

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/125315257-8c650a00-e2fc-11eb-8ecb-80482e09e03e.png)
