### ISSUE TITLE
CJB2-Friendship Field-MANITOBA-CANADA

### ISSUE THREAD

**Issue by hossss6** [InfiniteFlightAirportEditing/Airports#8051]
# Airport Name
Friendship Field
# Country?
Canada
# Improvements that need to be made?
Rework
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/125217344-01e1c380-e286-11eb-904a-d413f9e039e8.png)
