### ISSUE TITLE
CJB5-Moosomin/Marshall McLeod Field-SASKATCHEWAN-CANADA

### ISSUE THREAD

**Issue by hossss6** [InfiniteFlightAirportEditing/Airports#8053]
# Airport Name
Moosomin/Marshall McLeod Field
# Country?
Canada
# Improvements that need to be made?
Rework
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/125314598-f5984d80-e2fb-11eb-8633-a77fa22d85a4.png)
