### ISSUE TITLE
CJC3-Davidson Municipal-SASKATCHEWAN-CANADA

### ISSUE THREAD

**Issue by hossss6** [InfiniteFlightAirportEditing/Airports#8057]
# Airport Name
Davidson Municipal
# Country?
Canada
# Improvements that need to be made?
Rework
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by hossss6** [comment]
Sent in OR

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/125315595-e8c82980-e2fc-11eb-8ff9-2805b95d76e1.png)
