### ISSUE TITLE
CJC4-Central Butte-SASKATCHEWAN-CANADA

### ISSUE THREAD

**Issue by hossss6** [InfiniteFlightAirportEditing/Airports#8058]
# Airport Name
Central Butte
# Country?
Canada
# Improvements that need to be made?
Rework
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by hossss6** [comment]
Sent in OR

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/125315755-0b5a4280-e2fd-11eb-8d7d-4ad4e2edb43e.png)
