### ISSUE TITLE
CJD2-Cudworth Muni-SASKATCHEWAN-CANADA

### ISSUE THREAD

**Issue by hossss6** [InfiniteFlightAirportEditing/Airports#8060]
# Airport Name
Cudworth Muni
# Country?
Canada
# Improvements that need to be made?
Rework
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by hossss6** [comment]
Sent to OR

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/125316028-54aa9200-e2fd-11eb-8358-567200962d67.png)
