### ISSUE TITLE
CJD3-Birch Hills-SASKATCHEWAN-CANADA

### ISSUE THREAD

**Issue by hossss6** [InfiniteFlightAirportEditing/Airports#8061]
# Airport Name
Birch Hills
# Country?
Canada
# Improvements that need to be made?
Rework
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by hossss6** [comment]
Sent to OR

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/125316304-9dfae180-e2fd-11eb-8c6d-9ba4e7ca1df3.png)
