### ISSUE TITLE
CJE2-Dore Lake-SASKATCHEWAN-CANADA

### ISSUE THREAD

**Issue by hossss6** [InfiniteFlightAirportEditing/Airports#8063]
# Airport Name
Dore Lake
# Country?
Canada
# Improvements that need to be made?
Rework
# Are you working on this airport?
Yes and sent to OR
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/125466592-570b5d8a-b16c-47f2-90fa-1a4f81b67588.png)
