### ISSUE TITLE
CJC8-Laurie River-MANITOBA-CANADA

### ISSUE THREAD

**Issue by hossss6** [InfiniteFlightAirportEditing/Airports#8068]
# Airport Name
Laurie River
# Country?
Canada
# Improvements that need to be made?
Added into IF
# Are you working on this airport?
Yes and sent to OR
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/125467526-2dbc89e5-28cc-4914-877f-242bce455815.png)
