### ISSUE TITLE
ESGJ

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#807]
Will redo this one

**Comment by PaulNielsen** [comment]
Done, awaiting approval.

**Comment by dushyants19** [comment]
1ee6f50

**Comment by kilt46** [comment]
Gates named as per Navigraph
![image](https://cloud.githubusercontent.com/assets/14023167/16650680/12549fd2-4405-11e6-9d25-f8aae097b27b.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17232670/5b71e79c-54ef-11e6-9cdc-342f023081b8.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18421584/48c14c0a-7853-11e6-9b33-35b10ad615b3.png)
