### ISSUE TITLE
CJE6-Paradise Hill-SASKATCHEWAN-CANADA

### ISSUE THREAD

**Issue by hossss6** [InfiniteFlightAirportEditing/Airports#8070]
# Airport Name
Paradise Hill 
# Country?
Canada
# Improvements that need to be made?
Rework
# Are you working on this airport?
Yes and sent to OR
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/125467968-f90c7605-154f-498a-9070-9d66acc5a7bf.png)
