### ISSUE TITLE
RPSG-Sicogon-ILOILO-PHILIPPINES

### ISSUE THREAD

**Issue by jaypzs** [InfiniteFlightAirportEditing/Airports#8072]
# Airport Name
RPSG
# Country?
PHILIPPINES
# Improvements that need to be made?
To add ramps and gates
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/127660503-3066e62c-a9dd-4cc1-8bce-8573b98df539.png)
