### ISSUE TITLE
EGSZ-Papa Stour Airport-SCOTLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by BruhNoobXD** [InfiniteFlightAirportEditing/Airports#8073]
# Airport Name
Papa Stour Airport
# Country?
United Kingdom
# Improvements that need to be made?
needs to be added to IF
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by BruhNoobXD** [comment]
sent to OR

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126852165-e3bbb865-bb71-4957-a632-096db67d4579.png)
