### ISSUE TITLE
CJF4-Buffalo (Jaques Farms)-ALBERTA-CANADA

### ISSUE THREAD

**Issue by hossss6** [InfiniteFlightAirportEditing/Airports#8075]
# Airport Name
Buffalo (Jaques Farms)
# Country?
Canada
# Improvements that need to be made?
Added into IF
# Are you working on this airport?
Yes and sent to OR
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/125678961-cef718d3-f3de-4707-86be-d6cd6d7abc9f.png)
