### ISSUE TITLE
RPLE-Balesin-QUEZON-PHILIPPINES

### ISSUE THREAD

**Issue by jaypzs** [InfiniteFlightAirportEditing/Airports#8077]
# Airport Name
RPLE
# Country?
PHILIPPINES
# Improvements that need to be made?
To add ramps and gates
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/129122234-b77f0c39-cde3-4672-aae2-b700273ef7ff.png)
