### ISSUE TITLE
HRYR-Kigali Airport-KIGALI-RWANDA

### ISSUE THREAD

**Issue by Skunkape29** [InfiniteFlightAirportEditing/Airports#808]
RECYCLED.

**Comment by dushyants19** [comment]
How is this airport going, @Skunkape29?

**Comment by dushyants19** [comment]
@Skunkape29 please respond.

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by JcFl4** [comment]
I'm in!!

**Comment by JcFl4** [comment]
Didn't I assign myself already? I thought I did..

**Comment by JcFl4** [comment]
Actually, I can't do this anymore, so it's open to anybody that can again.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25042235/fb5fb1cc-20db-11e7-9561-8735b3082404.png)

**Comment by brunocr1050** [comment]
Will add new apron, starting tomorrow.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/105638758-2a8e1200-5e3a-11eb-8f4f-2bbe0065fc22.png)
