### ISSUE TITLE
CJG2-Eatonia (Elvie Smith) Municipal-SASKATCHEWAN-CANADA

### ISSUE THREAD

**Issue by hossss6** [InfiniteFlightAirportEditing/Airports#8080]
# Airport Name
Eatonia (Elvie Smith) Municipal 
# Country?
Canada
# Improvements that need to be made?
Rework
# Are you working on this airport?
Yes and sent to OR
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/125822741-41a82df5-fc46-4dac-bd87-0a886434c3df.png)
