### ISSUE TITLE
5I6-Galveston Airport-INDIANA-USA

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#8082]
# Airport Name
Galveston Airport
# Country?
USA
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low 🛑

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126003644-59ed0b07-5b8b-4184-92e1-bc6b25d96319.png)
