### ISSUE TITLE
USTJ-Tobolsk Airport-TYUMEN-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8083]
# Airport Name
Tobolsk Novaya

After opening it will be Tobolsk / Semyon U. Remezov Airport
# Country?
Russia
# Improvements that need to be made?
new airport
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

58.0583333°, 068.3486111°

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126004196-97e80629-d095-49c0-a805-8b0647593fad.png)
