### ISSUE TITLE
ZWHM-Hami Airport-XINJIANG-CHINA

### ISSUE THREAD

**Issue by Yuzhe716** [InfiniteFlightAirportEditing/Airports#8085]
# Airport Name
Hami Airport
# Country?
China
# Improvements that need to be made?
Redo/New Airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by brunocarbone3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/135528568-ebd216ca-2e22-4e0f-a826-d3731f46eed2.png)
