### ISSUE TITLE
UWGB-Bolshoye Boldino-NIZHNY NOVGOROD-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8086]
# Airport Name
Bolshoye Boldino
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low, no octagons(
55.0238889°, 045.3222222°

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126022584-11a1a55c-b3b8-44c4-958e-5daade07c5d2.png)
