### ISSUE TITLE
UWGI-Babino Airfield-NIZHNY NOVGOROD-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8087]
# Airport Name
Babino
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low, no octagons(
N56.21871° E043.59051°

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126022600-01308b11-b181-4c94-be53-30e72257dec8.png)
