### ISSUE TITLE
UWGO-Okhlopkovo-NIZHNY NOVGOROD-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8089]
# Airport Name
Okhlopkovo
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126047501-ba4354e0-53c4-4d7d-be91-085e07e79e3b.png)
