### ISSUE TITLE
NZPP

### ISSUE THREAD

**Issue by lachieee** [InfiniteFlightAirportEditing/Airports#809]
I'll do this.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17248694/b5021cce-5561-11e6-8db2-79389f0cd5e3.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18414461/ae0a5838-778e-11e6-8fcd-8bcf03b40bd5.png)
