### ISSUE TITLE
UWKB-Bugulma Airport-TATARSTAN-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8090]
# Airport Name
Bugulma
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126092225-2b73cb8c-1752-46a7-81d7-4a73af6d6fb5.png)
