### ISSUE TITLE
KLCH-Lake Charles Regional Airport-LOUISIANA-USA

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#8095]
# Airport Name
Lake Charles Regional Airport
# Country?
US
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/129122286-df7c103e-4d17-43f6-a230-ead5471a3f4a.png)
