### ISSUE TITLE
UWKP-Menzelinsk Airport-TATARSTAN-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8096]
# Airport Name
Menzelinsk
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126053839-261e044f-8341-4e13-bf57-39b9e104e3aa.png)
