### ISSUE TITLE
UWKR-Sarmanovo Airport-TATARSTAN-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8097]
# Airport Name
Sarmanovo 
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes, sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126092847-d1bd43cb-94f0-4087-9656-9a9a134b9d96.png)
