### ISSUE TITLE
CJJ3-Wildwood/Loche Mist Farms-ALBERTA-CANADA

### ISSUE THREAD

**Issue by hossss6** [InfiniteFlightAirportEditing/Airports#8099]
# Airport Name
Wildwood/Loche Mist Farms
# Country?
Canada
# Improvements that need to be made?
Added into IF
# Are you working on this airport?
Yes and sent to OR
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126095145-d0cd3d73-9fdd-48fa-b750-7468cf7066c1.png)
