### ISSUE TITLE
KMCI

### ISSUE THREAD

**Issue by david-garden** [InfiniteFlightAirportEditing/Airports#810]
I will do this one! (This is my 3rd and final one for right now :)

**Comment by imaboss31** [comment]
If anyone else wants this one for now they can have it :)

**Comment by david-garden** [comment]
If anyone wants to do this one they can. I am done with my break, but I will only be doing one airport at a time.

**Comment by TristinWoolf** [comment]
Up for grabs!

**Comment by lolo31r** [comment]
Redoing this. Please assign me

**Comment by lolo31r** [comment]
10k feet Runway. Priority label???

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22530808/24d743e2-e8a3-11e6-9883-a8106b2550e7.png)
