### ISSUE TITLE
CJK5-Gull Lake-SASKATCHEWAN-CANADA

### ISSUE THREAD

**Issue by hossss6** [InfiniteFlightAirportEditing/Airports#8106]
# Airport Name
Gull Lake
# Country?
Canada
# Improvements that need to be made?
Rework
# Are you working on this airport?
Yes and sent to OR
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126095182-ffa5a08b-70d3-4fd0-bfa8-74caddbdb317.png)
