### ISSUE TITLE
UWKF-Baltasi Airfield-TATARSTAN-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8108]
# Airport Name
Baltasi
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes, sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126092093-c3f01d64-6f16-43af-9cec-4d7ddc0b12cd.png)
