### ISSUE TITLE
UWKX-Spasskoye Airfield-TATARSTAN-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8109]
# Airport Name
Spasskoye
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes, sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126091803-8563062e-b75d-407f-aa2e-8d8d8c3e31c5.png)
