### ISSUE TITLE
LGIK

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#811]
Being redone

**Comment by PaulNielsen** [comment]
Done, awaiting approval

**Comment by dushyants19** [comment]
0013d7e

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17276590/366d49d6-56f3-11e6-869f-731dc5aced4d.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17833502/9970983e-66e4-11e6-97b4-d297dbaddacc.png)
