### ISSUE TITLE
UWKQ-Kuralovo Aerodrome-TATARSTAN-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8110]
# Airport Name
Kuralovo
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes, sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126091736-3083777b-d12c-4efb-a513-853f647fcb1c.png)
