### ISSUE TITLE
UWLN-Novoselki-ULYANOVSK-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8111]
# Airport Name
Novoselki
# Country?
Russia
# Improvements that need to be made?
from scratch
# Are you working on this airport?
yes, sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126091687-4acced44-bafd-49d7-bb35-28b60d54265d.png)
