### ISSUE TITLE
UWLS-Soldatskaya Tashla Aerodrome-ULYANOVSK-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8112]
# Airport Name
Soldatskaya Tashla
# Country?
Russia
# Improvements that need to be made?
from scratch
# Are you working on this airport?
yes, sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126091624-a0eeb207-1a39-4792-8a7a-e3ed52ad12fd.png)
