### ISSUE TITLE
UWOD-Adamovka Airfield-ORENBURG-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8113]
# Airport Name
Adamovka
# Country?
Russia
# Improvements that need to be made?
from scratch
# Are you working on this airport?
yes, sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126091419-7bf97045-a5df-472e-b28c-99f7ec1b3045.png)
