### ISSUE TITLE
UWOS-Svetlyy Airfield-ORENBURG-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8114]
# Airport Name
Svetlyy
# Country?
Russia
# Improvements that need to be made?
from scratch
# Are you working on this airport?
yes, sent to OR :)
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126091343-db7be57f-aeb2-4828-9ba7-60f63a917744.png)
