### ISSUE TITLE
UWOH-Kvarkeno Airfield-ORENBURG-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8115]
# Airport Name
Kvarkeno
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes, sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126091238-8a76f9fc-8944-4dee-ae34-9a882a246e98.png)
