### ISSUE TITLE
UWOY-Kushkul Sakmara Aerodrome-ORENBURG-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8116]
# Airport Name
Kushkul Sakmara
# Country?
Russia
# Improvements that need to be made?
redo from scratch
# Are you working on this airport?
yes, sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126091119-9c59bcd8-0545-4075-a263-9b375983542f.png)
