### ISSUE TITLE
UWSW-Balashov Repnoye Airfield-SARATOV-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8117]
# Airport Name
Balashov Repnoye
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes, sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126091285-776d8d88-eea9-4c3d-87c3-4099776fdf90.png)
