### ISSUE TITLE
UWKG-Kazan Borisoglebskoye-TATARSTAN-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8118]
# Airport Name
Kazan Borisoglebskoye
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
Runway 10500ft

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126183621-79e99761-fe62-416b-aa1a-144ed3f77bcf.png)
