### ISSUE TITLE
LSGP-La Cote Airport-VAUD-SWITZERLAND

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#812]

**Comment by dushyants19** [comment]
@NickArt1342 do you want to do this?

**Comment by TristinWoolf** [comment]
All of these are up for grabs as Nick already has about 15 airports assigned to him.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22356800/96f5b660-e3f9-11e6-8927-f0acfcd5fabc.png)

**Comment by kilt46** [comment]
Transparent runway and apron. Gates all wrong size

**Comment by NickArt1342** [comment]
@kilt Yeah the transparency I forgot, buttge gates were and still ARE all set to A on my version

**Comment by dushyants19** [comment]
Export target as 10.50 and wrong kilt btw

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22397459/6768c1d2-e537-11e6-9ef4-d88202b09519.png)
