### ISSUE TITLE
UWSX-Shumeyka Airfield-SARATOV-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8120]
# Airport Name
Shumeyka
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126183230-2b5412e4-66c2-4997-ae50-4a88b00bc519.png)
