### ISSUE TITLE
UWTP-Almetyevsk Poyma Airfield-TATARSTAN-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8121]
# Airport Name
Almetyevsk Poyma
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
Yes, sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126182810-231abc7f-d7e5-47d3-8811-78937b38f029.png)
