### ISSUE TITLE
UWTZ-Kazanbash Aerodrome-TATARSTAN-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8122]
# Airport Name
Kazanbash
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
Yes, sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126183068-6ffaad23-36ed-434a-8c23-915879ddb22d.png)
