### ISSUE TITLE
UWTW-Kazan Vishnevka Airfield-TATARSTAN-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8123]
# Airport Name
Kazan Vishnevka
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126415495-3a0f48df-fad6-417c-bcb4-7d255bd88c47.png)
