### ISSUE TITLE
UWSK-Krasny Kut Aerodrome-SARATOV-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8124]
# Airport Name
Krasny Kut
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126415403-c8accf83-ecfd-4ed3-8826-da86989c6fe3.png)
