### ISSUE TITLE
XWWN-Belyy Klyuch Aerodrome-ULYANOVSK-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8125]
# Airport Name
Belyy Klyuch
# Country?
Russia
# Improvements that need to be made?
redo from scratch
# Are you working on this airport?
Yes, sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126415170-dd8851bb-8e57-48d7-aca5-d093fcec86b8.png)
