### ISSUE TITLE
XWKR-Kazan Kurkachi Airfield-TATARSTAN-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8126]
# Airport Name
Kazan Kurkachi
# Country?
Russia
# Improvements that need to be made?
redo from scratch
# Are you working on this airport?
Yes, sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126415048-d283557d-6f30-473c-89df-8ce7e932c1de.png)
