### ISSUE TITLE
XWOB-Buzuluk Airfield-ORENBURG-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8127]
# Airport Name
Buzuluk
# Country?
Russia
# Improvements that need to be made?
redo from scratch
# Are you working on this airport?
yes, sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126414981-5bba1af6-8aa4-4ebb-ac89-345a8afe1f83.png)
