### ISSUE TITLE
XWPO-Penza Sosnovka-PENZA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8129]
# Airport Name
Penza Sosnovka
# Country?
Russia
# Improvements that need to be made?
redo from scratch
# Are you working on this airport?
yes, sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126414819-7bc39618-3788-451b-a7c7-053d3d8735c1.png)
