### ISSUE TITLE
XWSD-Saratov Dubki-SARATOV-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8130]
# Airport Name
Saratov Dubki
# Country?
Russia
# Improvements that need to be made?
redo from scratch
# Are you working on this airport?
yes, sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126414733-ce14ac56-f9dc-4d3d-a77a-6b7e1e92b768.png)
