### ISSUE TITLE
ZCG7-Aznakayevo Airfield-TATARSTAN-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8131]
# Airport Name
Aznakayevo
# Country?
Russia
# Improvements that need to be made?
redo from scratch
# Are you working on this airport?
yes, sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low
N54.87713° E053.07980°

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126414641-0b5003f7-69e9-4faf-81bc-9a46402e4d27.png)
