### ISSUE TITLE
ZCJ3-Tolyatti Podstepki-SAMARA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8132]
# Airport Name
Tolyatti Podstepki
# Country?
Russia
# Improvements that need to be made?
redo from scratch
# Are you working on this airport?
yes, sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126414557-5fa361ab-63ab-4771-9690-0fe34e3a0a61.png)
