### ISSUE TITLE
KGCC-Northeast Wyoming Regional Airport-WYOMING-USA

### ISSUE THREAD

**Issue by Captainflight** [InfiniteFlightAirportEditing/Airports#8133]
# Airport Name
Northeast Wyoming Regional Airport
# Country?
USA
# Improvements that need to be made?
Rework from scratch 
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by brunocarbone3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/135530966-cbdbbead-d861-4cac-98ee-c9935a827b7d.png)
