### ISSUE TITLE
GQNA-Aioun El Atrouss Airport-HODH EL GHARBI-MAURITANIA

### ISSUE THREAD

**Issue by AsternAviation** [InfiniteFlightAirportEditing/Airports#8134]
# Airport Name
Aioun El Atrouss Airport
# Country?
Mauritania 
# Improvements that need to be made?
done from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126851540-a04a40aa-110b-41a3-846f-1a57da947070.png)
