### ISSUE TITLE
XWSW-Balashov Airport-SARATOV-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8135]
# Airport Name
Balashov Air Base
# Country?
Russia
# Improvements that need to be made?
redo from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126568578-86abdf3a-101c-43ea-96f8-66473e1afd7f.png)
