### ISSUE TITLE
ZF7T-Preobrazhenka Airfield-SAMARA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8136]
# Airport Name
Preobrazhenka
# Country?
Russia
# Improvements that need to be made?
redo from scratch
# Are you working on this airport?
yes, sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126568726-e85bceb6-e1a4-4c49-8a90-dc49e0dcb4b5.png)
