### ISSUE TITLE
ZF8C-Kstovo-Vostochny Airfield-NIZHNY NOVGOROD-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8137]
# Airport Name
Kstovo-Vostochny
# Country?
Russia
# Improvements that need to be made?
redo from scratch
# Are you working on this airport?
yes, sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126568638-8810ea4c-a30c-4907-a5b8-df0dc0b971e3.png)
