### ISSUE TITLE
ZF8J-Shelanger Airfield-MARI EL-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8138]
# Airport Name
Shelanger
# Country?
Russia
# Improvements that need to be made?
redo from scratch
# Are you working on this airport?
yes, sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126568494-94818fa8-2929-4792-93f0-a7d7e6f0ce78.png)
