### ISSUE TITLE
LSGS-Sion Airport-VALAIS-SWITZERLAND

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#814]

**Comment by IceBlue02** [comment]
I'll do it

**Comment by dushyants19** [comment]
Will do

**Comment by NickArt1342** [comment]
Dush... Please leave the swiss airports alone until I have reorganized all my files.

**Comment by NickArt1342** [comment]
Simon. This airport is not a suggestion.

**Comment by bavAVIA** [comment]
I swear it's already done I only need to commit it, don't take thanks.
Might take another month though.

**Comment by NickArt1342** [comment]
Look I'm working as fast as I can to correct the issues. You must not be such a *anniying and toxic person* about it.

**Comment by bavAVIA** [comment]
Done. #100

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27997597-42aec03a-64c1-11e7-85dd-7029e31bf335.png)
