### ISSUE TITLE
UEBG-Khayyr Airport-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8146]
# Airport Name
Khayyr
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low
Maxar Imagery

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126851610-f9842f6f-f05d-455c-a99e-53828c3a4d58.png)
