### ISSUE TITLE
UEBD-Deputatsky Airport-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8147]
# Airport Name
Deputatsky
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126851579-710c04c3-29bd-40d0-b8b7-a8b20a9ab3c2.png)
