### ISSUE TITLE
UEBN-Nizhneyansk Airport-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8149]
# Airport Name
Nizhneyansk
# Country?
🇷🇺 
# Improvements that need to be made?
redo
# Are you working on this airport?
yes, sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126851657-cde113a9-8ab5-4fba-ae8f-bc8217c4f8c7.png)
