### ISSUE TITLE
LSGT-Gruyeres Airport-FRIBOURG-SWITZERLAND

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#815]

**Comment by brunocr98** [comment]
Up for grabs......again.

**Comment by dushyants19** [comment]
I'll do this

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34264063-3b0bd712-e637-11e7-8562-24e5b74c0562.png)
