### ISSUE TITLE
UEBS-Sakkyryr Airport-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8159]
# Airport Name
Sakkyryr
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes, sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126851695-e49d0018-ca97-414e-83e1-12f20fc96cda.png)
