### ISSUE TITLE
SLCB-Cochabamba Jorge Wilsterman Airport-COCHABAMBA-BOLIVIA

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#816]

**Comment by dushyants19** [comment]
Will do

**Comment by MajorTomMueller** [comment]
will take care about this one

**Comment by MajorTomMueller** [comment]
sent via email for review

**Comment by moritzbabl** [comment]
added

**Comment by MajorTomMueller** [comment]
![slcb-overview](https://user-images.githubusercontent.com/26853210/28742995-c3b70e12-743e-11e7-86e8-1ad3349b04db.jpeg)

**Comment by MajorTomMueller** [comment]
boundary

**Comment by MajorTomMueller** [comment]
- Boundary Fix
- Buildings removed
- Hangar Floors added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46445715-e4c75000-c73d-11e8-8415-30a4804aa690.png)
