### ISSUE TITLE
UEWB-Arylakh Airfield-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8161]
# Airport Name
Arylakh
# Country?
🇷🇺 
# Improvements that need to be made?
redo
# Are you working on this airport?
yes, sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126852025-bb42e8c7-6932-414c-9078-548fec2b05e5.png)
