### ISSUE TITLE
UEWK-Kustur Airfield-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8162]
# Airport Name
Kustur
# Country?
🇷🇺 
# Improvements that need to be made?
redo
# Are you working on this airport?
yes, sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126852057-8337eb63-e048-4084-a069-a45a61bf7fb9.png)
