### ISSUE TITLE
UEWS-Sartan Airfield-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8163]
# Airport Name
Sartan
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes, sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126852105-db0a7115-2dbd-4c2a-8a0b-0ee2e4a57b13.png)
