### ISSUE TITLE
UEEA-Aldan Airport-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8164]
# Airport Name
Aldan
# Country?
Russische Föderation
# Improvements that need to be made?
redo
# Are you working on this airport?
yes, sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126851735-5b06b53d-29cd-484c-8db1-34b147d73e22.png)
