### ISSUE TITLE
UEEJ-Kobyay Airfield-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8166]
# Airport Name
Kobyay
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
Sì, inviato a OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126851779-5c932335-a842-474d-ae1a-bce820b9f59e.png)
