### ISSUE TITLE
UEEP-Pokrovsk Airport-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8167]
# Airport Name
Pokrovsk
# Country?
Россия 🇷🇺 
# Improvements that need to be made?
redo
# Are you working on this airport?
yes. Sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126851816-4277331f-d6d6-4953-816e-11557c7a4df1.png)
