### ISSUE TITLE
UEEX-Belkachi Airfield-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8168]
# Airport Name
Belkachi
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes. Sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126851999-ac50bf3e-a16f-4890-901c-8c668ee519fb.png)
