### ISSUE TITLE
UEEQ-Sanyyakhtakh-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8169]
# Airport Name
Sanyyakhtakh
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes, sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/126851850-df485726-7755-47ea-8bfa-ecb4649826c1.png)
