### ISSUE TITLE
UEVV-Zhigansk Airport-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8176]
# Airport Name
Zhigansk
# Country?
Fédération de Russie
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/127365619-60e45956-528e-449e-b629-8b9bed63b2b8.png)
