### ISSUE TITLE
UELD-Chulman-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8179]
# Airport Name
Chulman
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low :)

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/127365725-b9b7746d-6092-40ec-baca-e72c3a4f52d6.png)
