### ISSUE TITLE
VOCP-Kadapa Airport-ANDHRA PRADESH-INDIA

### ISSUE THREAD

**Issue by Captainflight** [InfiniteFlightAirportEditing/Airports#8180]
# Airport Name
Kadapa Airport
# Country?
India
# Improvements that need to be made?
Rework from scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by brunocarbone3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/134564021-4e8c77cb-17d7-4785-873b-1b676b0341e3.png)
