### ISSUE TITLE
N59-Rosachi Air Park-NEVADA-USA

### ISSUE THREAD

**Issue by BruhNoobXD** [InfiniteFlightAirportEditing/Airports#8182]
# Airport Name
Rosachi Airpark
# Country?
United States of America
# Improvements that need to be made?
has to be redone
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by brunocarbone3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/134789428-5d8de75e-69a0-4bd5-b116-a7b35a071d32.png)
