### ISSUE TITLE
UEMG-Kebergene Airfield-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8184]
# Airport Name
Kebergene 
# Country?
Russia
# Improvements that need to be made?
redo from scratch
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/127535978-c318af45-1eca-4d45-9e64-24be7aceb762.png)
