### ISSUE TITLE
ULMK-Apatity Airport-MURMANSK-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8185]
# Airport Name
Apatity / Khibiny
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/127660759-41f0112b-47ff-4912-ad95-a496b6a34a5c.png)
