### ISSUE TITLE
UUOD-Voronezh Pridacha Airport-VORONEZH-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8186]
# Airport Name
Voronezh Pridacha
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/127660647-b7531ddb-4c25-4181-946b-f4a8a2d8a8c9.png)
