### ISSUE TITLE
UEMD-Chagda Airfield-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8190]
# Airport Name
Chagda
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes, sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/127725855-a109c125-ab22-4248-87ac-f150d06a27a9.png)
