### ISSUE TITLE
LIBR-Brindisi Airport-PUGLIA-ITALY

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#820]

**Comment by TZ2112** [comment]
Will make it!

**Comment by kilt46** [comment]
Airport not loaded to database
![image](https://user-images.githubusercontent.com/14023167/30233079-ea83174e-94b8-11e7-8be1-a9173094aa25.png)

**Comment by brunocr98** [comment]
Should be fine now...hopefully.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30234832-f84b44d8-94c6-11e7-9407-4f22dea6555c.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/69882588-6e759d80-12af-11ea-9233-7ba8e1da7152.jpg)
