### ISSUE TITLE
UEMJ-Oymyakon Airport-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8206]
# Airport Name
Oymyakon
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes, sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/127753900-4de6da6f-8a5b-4e87-ab84-3d131f19fbdf.png)
