### ISSUE TITLE
UEMN-Syagannakh Airfield-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8216]
# Airport Name
Syagannakh
# Country?
Russia
# Improvements that need to be made?
Redo
# Are you working on this airport?
yes, sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/127790641-f54872f9-6bed-44ff-81d5-f59200eb5cb2.png)
