### ISSUE TITLE
UEMO-Olyekminsk Airport-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8217]
# Airport Name
Olyekminsk
# Country?
Russia
# Improvements that need to be made?
redo from scratch
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/128280553-dfe8dd4b-deb8-4ca2-b74b-acc487a991fb.png)
