### ISSUE TITLE
GMMW-El Aroui Airport-ORIENTAL-MOROCCO

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#8218]
# Airport Name
El Aroui Airport
# Country?
Morocco
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/127790656-57ee2874-4d96-441c-ab23-888fac7a4f10.png)
