### ISSUE TITLE
GMMY-Kenitra Air Base-RABAT-SALE-KENITRA-MOROCCO

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Airports#8220]
# Airport Name
Kenitra Air Base
# Country?
Morocco
# Improvements that need to be made?
Full Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/128268489-c9b9f0bb-7c34-47b5-80ec-8fc5ef2d6d97.png)
