### ISSUE TITLE
FKKU-Bafoussam Airport-WEST-CAMEROON

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#8221]
# Airport Name
Bafoussam
# Country?
CM
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/128268828-ef5932cf-0a99-43ba-82f2-caf68ee1eef1.png)
