### ISSUE TITLE
LTCN-Kahramanmaraş Airport-KAHRAMANMARAS-TURKEY

### ISSUE THREAD

**Issue by LawinS** [InfiniteFlightAirportEditing/Airports#8222]
# Airport Name
Kahramanmaraş Airport
# Country?
🇹🇷 
# Improvements that need to be made?
Reeeeeedooooo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/128636264-d128a007-2149-4687-9f07-a0a78137644c.png)
