### ISSUE TITLE
UEMR-Aryktakh Airfield-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8224]
# Airport Name
Aryktakh
# Country?
Russia
# Improvements that need to be made?
Redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/128280605-43c165a2-fabb-490c-8117-7390ee6bf24c.png)
