### ISSUE TITLE
UEMT-Ust-Nera Airport-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8229]
# Airport Name
Ust-Nera
# Country?
Russia
# Improvements that need to be made?
Redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/128552795-ce13cabb-3520-4df2-a6ba-2bd019676208.png)
