### ISSUE TITLE
UEMU-Ust-Maya Airport-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8230]
# Airport Name
Ust-Maya
# Country?
Russia
# Improvements that need to be made?
Redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/128552699-2aca65a3-ca00-4ae1-b3d5-0f9830739f11.png)
