### ISSUE TITLE
RPUF-Basa Air Base-PAMPANGA-PHILIPPINES

### ISSUE THREAD

**Issue by jaypzs** [InfiniteFlightAirportEditing/Airports#8233]
# Airport Name
Basa Air Base
# Country?
Philippines
# Improvements that need to be made?
To add ramps and gates
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by brunocarbone3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/135531548-9f1de815-df0a-439b-9cce-89d4d993d25c.png)
