### ISSUE TITLE
UEMH-Teply Klyuch-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8236]
# Airport Name
Teply Klyuch
# Country?
Russia
# Improvements that need to be made?
Redo
# Are you working on this airport?
yes, sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/128553062-cad3e3e5-efb5-40db-aa0c-3628e4740cd4.png)
