### ISSUE TITLE
UENW-Vilyuysk Airport-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8237]
# Airport Name
Vilyuysk
# Country?
Russia
# Improvements that need to be made?
Redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/128636532-dceabb90-1c20-497b-b35d-e349eb1296aa.png)
