### ISSUE TITLE
UENI-Verkhnevilyuysk Airport-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8238]
# Airport Name
Verkhnevilyuysk
# Country?
Russia
# Improvements that need to be made?
Redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/128636464-cebb8378-f68e-46cd-8f3d-a3637b7c65dd.png)
