### ISSUE TITLE
UEND-Kyuletsky-2 Airfield-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8239]
# Airport Name
Kyuletsky-2
# Country?
Russia
# Improvements that need to be made?
Redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/128636400-96b1d07e-4129-41e9-b8a6-f3e3c58b548f.png)
