### ISSUE TITLE
KVQQ-Cecil Airport-FLORIDA-USA

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#824]

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32469715-8840128c-c319-11e7-8590-6371cee0efdd.png)

**Comment by kilt46** [comment]
https://drive.google.com/open?id=11s3XQoXXkTJnXN2V3bL4Q2McGLHkCxBH
