### ISSUE TITLE
MGMM-Mundo Maya International Airport-PETEN-GUATEMALA

### ISSUE THREAD

**Issue by zhf21** [InfiniteFlightAirportEditing/Airports#8247]
# Airport Name
Mundo Maya International Airport
# Country?
Guatemala
# Improvements that need to be made?
Addition.
# Are you working on this airport?
Beginning on 08/14/21, yes.
# Airport Priority? (10000ft+ Runway, Low)
Low (9,843ft)

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/133866948-6171cefd-27de-4548-91f2-0afc218da761.png)
