### ISSUE TITLE
UENK-Kysyl-Syr Airfield-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8249]
# Airport Name
Kysyl-Syr
# Country?
Russia
# Improvements that need to be made?
Redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/128657203-3c0be1f5-27c3-44b0-8031-e38bfe4526ee.png)
