### ISSUE TITLE
CYOD-Cold Lake/Group Captain R.W. McNair Airport-ALBERTA-CANADA

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#825]

**Comment by MajorTomMueller** [comment]
Please assign me.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30772832-7c1d9bc2-a029-11e7-9de9-5cfb34675086.png)

**Comment by MajorTomMueller** [comment]
boundary

**Comment by MajorTomMueller** [comment]
- Boundary Fix
- Buildings removed
- Hangar Floors added
- PAPI side correction
