### ISSUE TITLE
UENO-Chapaevo Airfield-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8251]
# Airport Name
Chapaevo
# Country?
Russia
# Improvements that need to be made?
Redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/128657263-2b82b3d1-0c9d-4565-b651-9ea34c42e965.png)
