### ISSUE TITLE
LTBZ-Zafer Airport-KUTAHYA-TURKEY

### ISSUE THREAD

**Issue by LawinS** [InfiniteFlightAirportEditing/Airports#8252]
# Airport Name
Zafer Airport
# Country?
Turkey 🇹🇷 
# Improvements that need to be made?
New airport creation 
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/129122174-3c1668d0-3fbb-4fd6-bfbb-7a80c0a76769.png)
