### ISSUE TITLE
ZUWS-Chongqing Wushan Airport-CHONGQING-CHINA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#8254]
# Airport Name
Chongqing Wushan
# Country?
CN
# Improvements that need to be made?
New
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
<img width="538" alt="Cattura" src="https://user-images.githubusercontent.com/76137019/130335222-29759df1-6891-43c2-9ab0-e68b68281873.PNG">
