### ISSUE TITLE
UENT-Kyuletsky-1 Airfield-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8256]
# Airport Name
Kyuletsky-1
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/129122400-2d3ff2f3-453a-4072-af36-f954cdd6a524.png)
