### ISSUE TITLE
LTCV-Sirnak Airport-SIRNAK-TURKEY

### ISSUE THREAD

**Issue by LawinS** [InfiniteFlightAirportEditing/Airports#8258]
# Airport Name
Sirnak Airport
# Country?
Turkey 🇹🇷 
# Improvements that need to be made?
New airport
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/131269254-b6363eee-f38d-4234-976a-f3cb3d23a4a3.png)
