### ISSUE TITLE
KPIT-Pittsburgh International Airport-PENNSYLVANIA-USA

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#826]

**Comment by American232** [comment]
I will take KPIT.

**Comment by American232** [comment]
![kpit github](https://user-images.githubusercontent.com/30371438/30500086-d998a59e-9a2a-11e7-9953-81e130c479eb.JPG)

I'm still working on Pittsburgh. Almost Done!

**Comment by ewanfleming** [comment]
Where's Pittsburgh?

**Comment by American232** [comment]
Cleaning up markings and removed buildings and fuel storage tanks since Val thinks they are silly.

![kpit 12-6-17](https://user-images.githubusercontent.com/30371438/33682071-595197f6-da94-11e7-9556-5d8ed2fc24ef.JPG)

**Comment by ChrisLevet232** [comment]
- [ ] Have to finish taxi way markings and shoulders.

**Comment by ChrisLevet232** [comment]
Redone from scratch. Sent in for review.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36816474-7c0f58f4-1ca3-11e8-89d1-a86906c02fca.png)

**Comment by kilt46** [comment]
Cargo spawns renamed: https://community.infinite-flight.com/t/if-library-maps-navigation-aircraft-etc/166128/40

**Comment by brunocr98** [comment]
@ChrisLevet232 is doing some improvements.

**Comment by ChrisLevet232** [comment]
![kpit](https://user-images.githubusercontent.com/30371438/46619390-fe76e780-caef-11e8-960f-ace2d373b2a2.PNG)

Removed buildings, updated ATC names, added gates and some minor improvements.

**Comment by ChrisLevet232** [comment]
Sent in to OR.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46700362-3e1dfc00-cbe2-11e8-8333-5a7e293badf3.png)
