### ISSUE TITLE
KCLL-Easterwood Field Airport-TEXAS-USA

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#8261]
# Airport Name
Easterwood Field Airport
# Country?
USA
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/132603813-0fe91c64-d737-40fe-986c-8b71f483b8f5.png)
