### ISSUE TITLE
UENY-Kyrgyday Airfield-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8263]
# Airport Name
Kyrgyday
# Country?
Russia
# Improvements that need to be made?
Redo
# Are you working on this airport?
yes, sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/129131462-14cf7d13-d065-497c-9151-a88eed3f752e.png)
