### ISSUE TITLE
UEOB-Bes-Kyuyel Airfield-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8265]
# Airport Name
Bes-Kyuyel
# Country?
Russia
# Improvements that need to be made?
Redo
# Are you working on this airport?
yes, sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/129431472-1cd9611a-e2e2-426b-9d85-708a9a8729ba.png)
