### ISSUE TITLE
UEOT-Tokko Airfield-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8266]
# Airport Name
Tokko
# Country?
Russia
# Improvements that need to be made?
Redo
# Are you working on this airport?
yes, sent to OR
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/129431461-a39f1175-2d83-4a0b-8c80-f870cde02b2b.png)
