### ISSUE TITLE
LFOK-Chalons Vatry Airport-CHAMPAGNE-ARDENNE-FRANCE

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#827]

**Comment by MajorTomMueller** [comment]
Will take care about this one.

**Comment by MajorTomMueller** [comment]
send to review/acceptance

**Comment by MajorTomMueller** [comment]
![lfok-overview](https://user-images.githubusercontent.com/26853210/28474700-dace5bfa-6e49-11e7-8b67-bfec39ec5084.jpeg)

**Comment by kilt46** [comment]
Missing Military pads
![image](https://user-images.githubusercontent.com/14023167/28499084-25469fd8-6f73-11e7-8111-491ca155c003.png)

**Comment by MajorTomMueller** [comment]
![lfok-aip](https://user-images.githubusercontent.com/26853210/28499769-d3bc787c-6fbd-11e7-87ea-62fac1570900.jpeg)

The Airport is not used for military purpose any more. They are mostly outside the official Airport boundary, and the small part in the south that is inside is not accessible with aircraft’s.
They are only shown in the chart for orientation in VFR aproch.
I would not draw them in this specific case, cause they are not usable.

**Comment by MajorTomMueller** [comment]
Issue should be closed from my perspective!

**Comment by MajorTomMueller** [comment]
NE mil apron occupyed by racetrack:
![lfok-ne](https://user-images.githubusercontent.com/26853210/28499865-b9a18552-6fbf-11e7-975f-f7961fb19c90.jpeg)

NW mil apron, the same and outside the fence:
![lfok-nw](https://user-images.githubusercontent.com/26853210/28499866-b9e21838-6fbf-11e7-99c1-e1360852cdd5.jpeg)

SE mil apron has no TWY to rest of the Airport anymore, and is cut by fence:
![lfok-se](https://user-images.githubusercontent.com/26853210/28499867-b9fbd1b0-6fbf-11e7-88e4-fb9debbaa7f5.jpeg)

**Comment by MajorTomMueller** [comment]
After searching about the topic in the www, I can not see any advantage in adding this useless pieces of pavement.
If someone else can give a good reason to do so, feel free to comment.
Until then, please close the issue, @kilt46 or @brunocr98 or at leased just unassign me.

**Comment by brunocr98** [comment]
Which is the most recent chart? Yours or Kilt's?

**Comment by MajorTomMueller** [comment]
I am not aware of the source of Kilt ones. 
My one is from the official SIA (Government) Homepage:
https://www.sia.aviation-civile.gouv.fr/
https://www.sia.aviation-civile.gouv.fr/dvd/eAIP_25_MAY_2017/FRANCE/AIRAC-2017-05-25/pdf/FR-AD-2.LFOK-fr-FR.pdf
Therefore it should be the most recent.
In addition it is correspondent with the Satellite Images, and the information provided via French and English wikipedia as well as other commercial (Airport) and private internet pages.

At least Kilts chart shows nothing different: the disused mil Aprons are red, and not connected to any other part of the airport.

**Comment by kilt46** [comment]
Ok worth checking. Will close this one. Thank you for all your help.

**Comment by MajorTomMueller** [comment]
your welcome
... I am the last one to miss usable mil-Aprons...
;-)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28553289-778ea9d4-70b8-11e7-9469-7e0535d9a9d6.png)

**Comment by MajorTomMueller** [comment]
boundary

**Comment by MajorTomMueller** [comment]
- boundary fix
- Buildings removed

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46383318-512a4c80-c675-11e8-9e44-bbd4c746314d.png)
