### ISSUE TITLE
UERL-Lensk Airport-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8270]
# Airport Name
Lensk
# Country?
Russia
# Improvements that need to be made?
redo from scratch
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/129631748-96003db8-2eda-485e-ba30-bba9abd27684.png)
