### ISSUE TITLE
UERO-Olenek Airport-SAKHA-RUSSIA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Airports#8271]
# Airport Name
Olenek
# Country?
Russia
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/130266522-b1c6aae3-f3a4-49c6-94e0-40733a46cb81.png)
