### ISSUE TITLE
ZSJJ-Jiujiang Lushan Airport-JIANGXI-CHINA

### ISSUE THREAD

**Issue by korgast** [InfiniteFlightAirportEditing/Airports#8272]
# Airport Name
Jiujiang Lushan
# Country?
China
# Improvements that need to be made?
New
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by brunocarbone3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/135529097-d59adc9b-bc38-4a06-bf4d-293a75eefb0e.png)
