### ISSUE TITLE
LBKJ-Kainardzha Airport-RUSE-BULGARIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#8279]
# Airport Name
Kainardzha Airport
# Country?
Bulgaria 🇧🇬
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/133866848-91efecdd-4a19-46f3-9e9c-2a436360b4d6.png)
