### ISSUE TITLE
LSPD

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#828]

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24682645/63ed70c2-1960-11e7-9ead-8d635f12580e.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/49258899-b3e15f80-f3fc-11e8-81ed-fcee8ab52440.png)

**Comment by kilt46** [comment]
Duplicate spawns removed
