### ISSUE TITLE
LBKL-Kalvacha Airport-KHASKOVO-BULGARIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#8280]
# Airport Name
Kalvacha Airport
# Country?
Bulgaria 🇧🇬
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/133866816-bbf12b81-dccf-49a3-9078-87987718eea9.png)
