### ISSUE TITLE
LBLS-Lesnovo Airport-SOFIYA-BULGARIA

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Airports#8281]
# Airport Name
Lesnovo Airport
# Country?
Bulgaria 🇧🇬
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by brunocarbone3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/135540024-13d5b608-0d7a-470d-a00d-e085fdf9d410.png)
