### ISSUE TITLE
SCFT-Futaleufu Airport-LOS LAGOS-CHILE

### ISSUE THREAD

**Issue by SpeedbirdCL** [InfiniteFlightAirportEditing/Airports#8288]
# Airport Name
Futaleufu 
# Country?
Chile
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/132603977-935bf36f-b82f-4f02-a09e-aba43ab2f107.png)
