### ISSUE TITLE
ZHJZ-Jingzhou Shashi Airport-HUBEI-CHINA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#8291]
# Airport Name
Jingzhou Shashi
# Country?
China
# Improvements that need to be made?
New
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/130546861-b21a06f8-5559-488a-9a81-2cadc4f01c34.png)
