### ISSUE TITLE
ZSDY-Dongying Shengli Airport-SHANDONG-CHINA

### ISSUE THREAD

**Issue by Daniel-Baiks** [InfiniteFlightAirportEditing/Airports#8300]
# Airport Name
Dongying Shengli
# Country?
China
# Improvements that need to be made?
New
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/133906404-f4909ae5-422a-43fa-89de-ff374f153c4a.png)
