### ISSUE TITLE
WAPA-Amahai-MALUKU-INDONESIA

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#8303]
# Airport Name
Amahai
# Country?
Indonesia
# Improvements that need to be made?
Create New
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low Priority

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/131336633-1a4a148a-e757-43a6-8f5b-a36962ccd4f2.png)
