### ISSUE TITLE
RPUA-Pamalican Airstrip-PALAWAN-PHILIPPINES

### ISSUE THREAD

**Issue by jaypzs** [InfiniteFlightAirportEditing/Airports#8322]
# Airport Name
Pamalican Airstrip
# Country?
Philippines
# Improvements that need to be made?
To add ramp and gates
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by brunocarbone3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/134564157-2e1e5200-6a29-43d0-b575-900339d29084.png)
