### ISSUE TITLE
LSPL

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#833]

**Comment by NickArt1342** [comment]
Back off Simon. Back off. 

You have broken the agreement more than enough now.

**Comment by dushyants19** [comment]
Agreement expired 1 week ago

**Comment by NickArt1342** [comment]
Deadline was only for LSZH, LSGG and LSZB.

**Comment by bavAVIA** [comment]
Done. Last one, I surrender.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28240593-7ef4194a-694a-11e7-89a3-2ae50909d4a5.png)
