### ISSUE TITLE
KSXU-Santa Rosa Route 66 Airport-NEW MEXICO-USA

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#834]
RECYCLED ♻️

**Comment by TZ2112** [comment]
Will make it

**Comment by moritzbabl** [comment]
@TZ2112 please accept the invite in your mails so we can assign you, also you are already assigned to 4 airports with the limit being 3, please wait til the other ones are accepted

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34319493-6019229e-e7a9-11e7-8641-4a55237be132.png)
