### ISSUE TITLE
KXLL-Allentown Queen City Municipal Airport-PENNSYLVANIA-USA

### ISSUE THREAD

**Issue by IFsami** [InfiniteFlightAirportEditing/Airports#8340]
# Airport Name
Allentown Queen City Muni
# Country?
USA
# Improvements that need to be made?
Full rework
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by brunocarbone3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/135530336-f8cab590-1df8-4068-bee5-d791b054c73c.png)
