### ISSUE TITLE
SCVM-Viña del Mar-VALPARAISO-CHILE

### ISSUE THREAD

**Issue by SpeedbirdCL** [InfiniteFlightAirportEditing/Airports#8347]
# Airport Name
Viña del Mar
# Country?
Chile
# Improvements that need to be made?
Redo
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by brunocarbone3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/134563860-22b67da9-e9a5-4887-b10d-22d7b3521fa2.png)
