### ISSUE TITLE
KRHI-Rhinelander-Oneida County Airport-WISCONSIN-USA

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Airports#8348]
# Airport Name
Rhinelander-Oneida County Airport
# Country?
USA
# Improvements that need to be made?
Redone
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/133866934-76e8d9d1-c1dd-4302-83fb-f80eaab7b3e0.png)
