### ISSUE TITLE
KEIK-Erie Municipal-COLORADO-USA

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Airports#8349]
# Airport Name
Erie Municipal
# Country?
USA
# Improvements that need to be made?
full redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by Czechoslovaki** [comment]
![image](https://user-images.githubusercontent.com/51279558/135383435-cf7be7a4-dfe1-4244-a212-f5022ad73160.png)
