### ISSUE TITLE
LSPO

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#836]

**Comment by dushyants19** [comment]
done.

**Comment by NickArt1342** [comment]
Dush you f%&48]| a“#Ç[]|. We had a deal. STOP WASTING MY TIME AND DOING AIRPORTS THAT ARE 90% done on my side. WE HAD A DEAL.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27262380-2fa0ce04-541b-11e7-8c88-1171ea198a5a.png)
