### ISSUE TITLE
KGTB-Wheeler Sack AAF-NEW YORK-USA

### ISSUE THREAD

**Issue by hossss6** [InfiniteFlightAirportEditing/Airports#8360]
# Airport Name

WHEELER-SACK AAF
# Country?
United States
# Improvements that need to be made?
Airport Rework
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/133866913-8537885a-1c4b-4a20-9b23-fda5b9a282ad.png)
