### ISSUE TITLE
SCBI-Pampa Guanaco-MAGALLANES-CHILE

### ISSUE THREAD

**Issue by SpeedbirdCL** [InfiniteFlightAirportEditing/Airports#8361]
# Airport Name
Pampa Guanaco
# Country?
Chile
# Improvements that need to be made?
Add airport to the flight sim
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/133866716-2b30b65c-8b23-43a8-b4c5-6b16eca98dc7.png)
