### ISSUE TITLE
SWXQ-Lins Airport-SAO PAULO-BRAZIL

### ISSUE THREAD

**Issue by zhf21** [InfiniteFlightAirportEditing/Airports#8367]
# Airport Name
Lins Airport
# Country?
Brazil
# Improvements that need to be made?
Redo (auto-gen)
# Are you working on this airport?
Yes.
# Airport Priority? (10000ft+ Runway, Low)
Low.

https://pergamum.anac.gov.br/arquivos/PA2014-2413.pdf

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/133866887-a7ec85ea-a2e0-4915-853d-559551895a48.png)
