### ISSUE TITLE
CSC9-Coniston Airport-ONTARIO-CANADA

### ISSUE THREAD

**Issue by LordWizrak** [InfiniteFlightAirportEditing/Airports#8369]
# Airport Name
Coniston Airport
# Country?
Canada
# Improvements that need to be made?
Has a folder, new airport.
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/133906431-f97d53e6-5fdc-4fa6-9c0b-cd3e896af495.png)
