### ISSUE TITLE
KBFK-Buffalo Muni-OKLAHOMA-USA

### ISSUE THREAD

**Issue by JulietTango-IF** [InfiniteFlightAirportEditing/Airports#8370]
# Airport Name
Buffalo Municipal Airport
# Country?
United States of America 
# Improvements that need to be made?
Full rework 
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by brunocarbone3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/134563491-1b95a335-eb1f-4db9-bcbb-b639015311fc.png)
