### ISSUE TITLE
CTG3-Du Rocher-Perce Airport-QUEBEC-CANADA

### ISSUE THREAD

**Issue by ToasterStroodie** [InfiniteFlightAirportEditing/Airports#8371]
# Airport Name
Du Rocher-Perce Airport
# Country?
Canada
# Improvements that need to be made?
From scratch
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by becarboner3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/133930617-4c157ef6-121d-445a-85e0-623f5e7c0263.png)
