### ISSUE TITLE
T74-Taylor Municipal Airport-TEXAS-USA

### ISSUE THREAD

**Issue by SuhasIF** [InfiniteFlightAirportEditing/Airports#8372]
# Airport Name
Taylor Municipal Airport
# Country?
USA
# Improvements that need to be made?
Redo
# Are you working on this airport?
Indeed
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by brunocarbone3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/135546088-3a64e93d-9de5-42ab-9864-f3d61f4d2067.png)
