### ISSUE TITLE
ENBM-Voss Airport, Bømoen-VESTLAND-NORWAY 

### ISSUE THREAD

**Issue by Daniboi737** [InfiniteFlightAirportEditing/Airports#8382]
# Airport Name
Voss Airport, Bømoen
# Country?
Norway
# Improvements that need to be made?
Redone from scratch
# Are you working on this airport?
YES
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by ECoops-123** [comment]
You have until October first to get this in. Check #announcements on the Discord in case you are not aware.

**Comment by Daniboi737** [comment]
Sent to OR

**Comment by brunocarbone3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/135531217-b66251b9-33cd-4f5e-af13-1c61dce06f21.png)
