### ISSUE TITLE
PAIL-Iliamna Airport-ALASKA-USA

### ISSUE THREAD

**Issue by zhf21** [InfiniteFlightAirportEditing/Airports#8383]
# Airport Name
Iliamna Airport
# Country?
United States of America.
# Improvements that need to be made?
Redo (auto-gen).
# Are you working on this airport?
Yes.
# Airport Priority? (10000ft+ Runway, Low)
Low.

**Parking Chart:** https://dot.alaska.gov/stwdav/documents/tiedown_maps/iliamna_tiedown_VIC_MAP.pdf 
*Note: The runway numbers in that chart are out-of-date.*

**Comment by brunocarbone3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/134576186-a5d9f8f3-7749-474b-aac1-f99567cfbfa4.png)
