### ISSUE TITLE
LTFK-Gokceada Airport-CANAKKALE-TURKEY

### ISSUE THREAD

**Issue by LawinS** [InfiniteFlightAirportEditing/Airports#8392]
# Airport Name
Gokceada Airport
# Country?
Turkey 🇹🇷
# Improvements that need to be made?
Adding new airport 
# Are you working on this airport?
Yep
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by brunocarbone3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/134831433-0b0c5a79-23a0-4e94-b26b-ee113633f16a.png)
