### ISSUE TITLE
NV31-Barker Creek Ranch-NEVADA-USA

### ISSUE THREAD

**Issue by BruhNoobXD** [InfiniteFlightAirportEditing/Airports#8393]
# Airport Name
Barker Creek Ranch
# Country?
United States of America
# Improvements that need to be made?
redone from scratch 
# Are you working on this airport?
ye
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by brunocarbone3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/134831469-c56bc8c7-6fc4-411a-acb3-4cb6c166793f.png)
