### ISSUE TITLE
MN00-Webb Lake Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by Aceorbit** [InfiniteFlightAirportEditing/Airports#8396]
# Airport Name
Webb Lake Airport
# Country?
USA
# Improvements that need to be made?
Scratch
# Are you working on this airport?
Ye
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by brunocarbone3000** [comment]
The code seems to be MN00 https://www.aopa.org/destinations/airports/MN00/details

**Comment by brunocarbone3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/134789439-52baba14-12a0-4459-852b-adeb23016056.png)
