### ISSUE TITLE
NV27-Circle L Ranch-NEVADA-USA

### ISSUE THREAD

**Issue by BruhNoobXD** [InfiniteFlightAirportEditing/Airports#8400]
# Airport Name
Circle L Ranch
# Country?
Nevada
# Improvements that need to be made?
redone from scratch
# Are you working on this airport?
ye
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by brunocarbone3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/135531347-b7122f7f-2ab9-4ba8-9fad-b345653b4081.png)
