### ISSUE TITLE
OEBT-Batha Airport-EASTERN PROVINCE-SAUDI ARABIA

### ISSUE THREAD

**Issue by LawinS** [InfiniteFlightAirportEditing/Airports#8402]
# Airport Name
Batha Airport
# Country?
Saudi Arabia🇸🇦 
# Improvements that need to be made?
New airport creation
# Are you working on this airport?
Yep
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by brunocarbone3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/135531062-2a846f1e-0e59-49cd-8b8e-21597512d4db.png)
