### ISSUE TITLE
A28-Fort Bidwell Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Airports#8403]
# Airport Name
Fort Bidwell Airport
# Country?
murica
# Improvements that need to be made?
redo
# Are you working on this airport?
yes
# Airport Priority? (10000ft+ Runway, Low)
low

**Comment by brunocarbone3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/135530825-af791a19-4364-4111-ad30-9aec49218d0c.png)
