### ISSUE TITLE
VTSM-Koh Samui-THAILAND

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Airports#8405]
# Airport Name
Koh Samui
# Country?
Thailand
# Improvements that need to be made?
Create New
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by brunocarbone3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/135529009-00b402f5-bc99-4162-94ad-8d6d1e590b66.png)
