### ISSUE TITLE
YMLS-Miles Airport-QUEENSLAND-AUSTRALIA

### ISSUE THREAD

**Issue by hossss6** [InfiniteFlightAirportEditing/Airports#8406]
# Airport Name
Miles Airport
# Country?
Australia
# Improvements that need to be made?
Airport Rework
# Are you working on this airport?
Yes 
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by brunocarbone3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/135530202-90471c21-82aa-413f-bfb8-d2a64ce0153f.png)
