### ISSUE TITLE
VAMA-Mudra Airport-GUJARAT-INDIA

### ISSUE THREAD

**Issue by LawinS** [InfiniteFlightAirportEditing/Airports#8409]
# Airport Name
Mudra airport
# Country?
India 🇮🇳 
# Improvements that need to be made?
New airport creation
# Are you working on this airport?
Yes
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by brunocarbone3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/135528818-00f259dc-e993-4234-8492-6184955cb19f.png)
