### ISSUE TITLE
R47-Ruhe's Airport-OHIO-USA

### ISSUE THREAD

**Issue by zhf21** [InfiniteFlightAirportEditing/Airports#8410]
# Airport Name
Ruhe's Airport
# Country?
U.S.A.
# Improvements that need to be made?
Redo.
# Are you working on this airport?
Yes.
# Airport Priority? (10000ft+ Runway, Low)
Low.

**Comment by brunocarbone3000** [comment]
![image](https://user-images.githubusercontent.com/76137019/135528907-a0b4b768-379a-40f1-ac0f-e25f13880879.png)
