### ISSUE TITLE
FLKK-Lusaka Airport-LUSAKA-ZAMBIA

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#842]

**Comment by MajorTomMueller** [comment]
And this one for me please

**Comment by MajorTomMueller** [comment]
Could someone change FLLS in the repo to FLKK? FLLS is the former ICAO of FLKK and FLKK is not in the repo...

**Comment by moritzbabl** [comment]
Add that in the email for review and we’ll change it when we commit the airport

**Comment by MajorTomMueller** [comment]
ok

**Comment by MajorTomMueller** [comment]
send to review

**Comment by henrikbg** [comment]
Approved.

**Comment by MajorTomMueller** [comment]
![flls-lusaka-overview](https://user-images.githubusercontent.com/26853210/30744933-853240b2-9fa4-11e7-83c1-8d591101fc1c.jpeg)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/30763205-c4336484-9faa-11e7-8ec4-c57e99f26ddc.png)

**Comment by MajorTomMueller** [comment]
boundary

**Comment by MajorTomMueller** [comment]
- Boundary Fix
- Buildings removed
- Hangar Floors added
