### ISSUE TITLE
KIGM-Kingman Airport-ARIZONA-USA

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#844]

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28938531-f3be6b32-7853-11e7-9054-8df739b23553.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53704722-db253f80-3de4-11e9-8ea3-aee44c451211.png)
