### ISSUE TITLE
OEMA-Madinah/Prince M Bin Abdulaziz Airport-AL MADINAH-SAUDI ARABIA

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#845]

**Comment by dushyants19** [comment]
I'll do this

**Comment by MajorTomMueller** [comment]
Any progress? ;-)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54872324-4af96b00-4d90-11e9-91f3-f568db469cef.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/54872338-7714ec00-4d90-11e9-9a4d-94bffa1af172.png)

**Comment by kilt46** [comment]
Please ensure ALL of the called out spawns in these maps are in the airport

**Comment by MBeringuy** [comment]
I'm solving the spa issue at this airport.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/56461719-1079f280-637d-11e9-98a4-c52ecac92c6b.png)
