### ISSUE TITLE
LJLJ-Ljubljana/Brnik Airport-GORENJSKA-SLOVENIA

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#846]
RECYCLED ♻️

**Comment by NickArt1342** [comment]
Airport closed.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/26275671/bd920680-3d2b-11e7-9bab-0b48aa044a65.png)
