### ISSUE TITLE
SBFI-Foz Do Iguacu / Cataratas Airport-PARANA-BRAZIL

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#847]

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/35780126-c378b5c4-099c-11e8-9800-ae71707c83f4.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52854647-b2166680-30e4-11e9-873a-9c79b02afbef.png)
