### ISSUE TITLE
PTKK-Chuuk International Airport-WENO ISLAND-MICRONESIA

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#848]

**Comment by dushyants19** [comment]
Airport Closed: http://www.gcmap.com/airport/LSZD.OLD

**Comment by arjundayal007** [comment]
I’ll take it. Part of the “Project China” so many people want.

**Comment by brunocr98** [comment]
I see you don't appear in the collaborators list. You must accept an invite to join our repository as a collaborator. PM an admin.

**Comment by dushyants19** [comment]
Invited. Accept collaboration here https://github.com/InfiniteFlightAirportEditing/Airports/invitations

**Comment by rocketman1974** [comment]
Haha that was my wrong account. I really want it, not the fake me!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34750306-122b5388-f56c-11e7-91e0-f58a8f451b0b.png)
