### ISSUE TITLE
LSZG

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#851]

**Comment by TristinWoolf** [comment]
@NickArt1342 That is enough!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27411797-ced9900e-56b5-11e7-9eb7-501b761fe52e.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27458608-86fe31c6-576f-11e7-9e0a-af721484fa7a.png)
