### ISSUE TITLE
LSZL-Locarno Airport-TICINO-SWITZERLAND

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#855]

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27262520-b107eaac-541d-11e7-81a1-466e695f7fa1.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27262543-2964cc40-541e-11e7-8893-52b8682e6bd1.png)

**Comment by dushyants19** [comment]
Cannot Import. Please fix @NickArt1342 

![image](https://user-images.githubusercontent.com/13567007/27262837-85b7554a-547c-11e7-9e69-89e48d5ed3c8.png)
