### ISSUE TITLE
LSZV

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#862]

**Comment by TristinWoolf** [comment]
@NickArt1342 No more! These should be added when you start working on them!! We don't want all of Switzerland on the tracker!

**Comment by bavAVIA** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23106999/702930dc-f6bb-11e6-8d6f-542f1ff63ddd.png)
