### ISSUE TITLE
LSZX-Schanis Airport-SANKT GALLEN-SWITZERLAND

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#864]

**Comment by kilt46** [comment]
No file in Repo.

**Comment by NickArt1342** [comment]
synced again, should be there now

**Comment by NickArt1342** [comment]
Okay this is really weird
The file is online and it shows it to me via the github app when comparing it to my local version (I changed a location of a line by milimeters to make sure) I commited and synced it again, but idk why it doesn't get into the repo

**Comment by NickArt1342** [comment]
Nvm, it's there now

**Comment by dushyants19** [comment]
Might be because you didn't hit sync when you closed this. That's why 2 commits

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25561944/504ad690-2d3d-11e7-975d-120e8492ed86.png)
