### ISSUE TITLE
 ZJHK-Haikou Meilan International Airport-HAINAN-CHINA

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Airports#865]

**Comment by NickArt1342** [comment]
airport permanently closed.

**Comment by brunocr98** [comment]
Recycled. Up for grabs!

**Comment by brunocr98** [comment]
Expected to be done by this evening.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25299725/a35b5fc0-26c7-11e7-8688-433ba885ea3a.png)
