### ISSUE TITLE
LRBS-Baneasa-Aurel Vlaicu Airport-BUCHAREST-ROMANIA

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#866]
Aurel Vlaicu International Airport
Being re-done

**Comment by IFAEpat** [comment]
What airport is this @TheGamingGuy ?

**Comment by TheGamingGuy** [comment]
It is Baneasa Airport-BBU (Romania)

**Comment by IFAEpat** [comment]
@TheGamingGuy next time, please insert the _real_ ICAO :)

**Comment by IFAEpat** [comment]
This is the real name by the way: Aurel Vlaicu International Airport

**Comment by TheGamingGuy** [comment]
Sorry got it wrong

**Comment by TheGamingGuy** [comment]
We call it baneasa airport in romania

**Comment by IFAEpat** [comment]
We have to have the official name :)

**Comment by TheGamingGuy** [comment]
Ok 😉🖒

**Comment by dushyants19** [comment]
grabs

**Comment by dushyants19** [comment]
i'll do it, looks like a piece of crème caramel

**Comment by dushyants19** [comment]
Done, finally. Was too lazy

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/26954390-4cd78c40-4c75-11e7-81e5-8e9345de73af.png)

**Comment by Czechoslovaki** [comment]
Updating this airport. 


- Commercial apron configuration has completely changed
- Stand numbers changed, currently incorrect
- Some runway holds missing
- Buildings to be removed, hangars have incorrect pavement

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111398239-18d62780-8691-11eb-9486-9041fd5f56fa.png)
