### ISSUE TITLE
VVCT-Can Tho Airport-MEKONG DELTA-VIETNAM

### ISSUE THREAD

**Issue by ColonelJeff** [InfiniteFlightAirportEditing/Airports#867]
Can Tho Airport
Being Redone.

**Comment by IFAEpat** [comment]
![screen shot 2016-07-06 at 3 18 19 pm](https://cloud.githubusercontent.com/assets/18223248/16631388/e94db506-438c-11e6-8104-c8365cf2029a.png)

**Comment by dushyants19** [comment]
up for grabs

**Comment by ReflexRSM** [comment]
I'll do this one :)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19539539/82712c06-961f-11e6-843c-875ee8c4566c.png)

**Comment by MajorTomMueller** [comment]
Latest AIP document:
https://vnaic.vn/images/stories/vnaic.vn/SanPhamDichVu/AIP-SUP/esup-20-a09-approvedbycaav.pdf

**Comment by IFUA2003** [comment]
![ảnh](https://user-images.githubusercontent.com/43931356/78680239-73112900-7915-11ea-8439-2e33e362fec8.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/111558589-09241500-875d-11eb-9a21-21607c5762d6.png)
