### ISSUE TITLE
WSSS-Singapore Changi Airport-CHANGI-SINGAPORE

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#87]

**Comment by carmichaelalonso** [comment]
This was improved by @NickArt1342

**Comment by Swang007** [comment]
Is this issue still "being redone"? Someone on IFFG was saying that the whole airport was shifted, maybe some objects were not in the right position. Not really sure. Does anyone want to look into this?

**Comment by carmichaelalonso** [comment]
Nick Art handles WSSS, best to speak to him about it on the forum :)

**Comment by Swang007** [comment]
![wsss](https://cloud.githubusercontent.com/assets/11000109/7785127/67866a32-0147-11e5-8126-138f8af96403.jpg)

**Comment by NickArt1342** [comment]
Hey guys, so what's the prob?

**Comment by samuelandersson** [comment]
https://community.infinite-flight.com/t/missing-taxiway-s-wsss/54943/2

**Comment by kilt46** [comment]
Reworking outlines

**Comment by IceBlue02** [comment]
@kilt46 done?

**Comment by dushyants19** [comment]
@NickArt1342 you are making changes

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23343088/735e691e-fc2b-11e6-9e22-3b441f39c73f.png)

**Comment by ryu12332** [comment]
ISSUE: Elevation incorrect. 
IF ELEVATION: -12
TRUE ELEVATION: 22

**Comment by ewanfleming** [comment]
I’ll fix this one.

**Comment by ewanfleming** [comment]
Turns out that the current version in the repo is at 22 feet. I imagine someone has recently fixed it.

**Comment by brunocr98** [comment]
Fixed

**Comment by MajorTomMueller** [comment]
will get interlinked by taxiway in near future to WSAC #517

**Comment by jakey20** [comment]
Thanks!

**Comment by jakey20** [comment]
What?

**Comment by MajorTomMueller** [comment]
This is interlinked to WSAC, it couldn't been redone individualy.

**Comment by jakey20** [comment]
It's not connected now. It needs a rework.

**Comment by MajorTomMueller** [comment]
DON'T you READING?

**Comment by jakey20** [comment]
Actually, I can read. I can also see. I can see that the airport needs a rework, and based on current imagery, it can be reworked. What's the point in waiting to connect it to WSAC when they aren't even connected now? Why not bring it up to current standards now, and then connect it to WSAC once imagery is available?

**Comment by RyanEpps** [comment]
Will discuss internally.

**Comment by MajorTomMueller** [comment]
![WSSS-git](https://user-images.githubusercontent.com/26853210/94259674-61046080-ff1e-11ea-90c6-14a82d391890.png)

**Comment by MajorTomMueller** [comment]
will revise as soon as new imagery is available
