### ISSUE TITLE
UIII

### ISSUE THREAD

**Issue by sentikum** [InfiniteFlightAirportEditing/Airports#870]
Being redone

**Comment by dushyants19** [comment]
88ee4f0

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17267350/37f2eda6-55cc-11e6-89a0-ed653a7a0307.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18028954/27d3f740-6c50-11e6-8712-5b670a3b5717.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18028958/32dffb20-6c50-11e6-833e-90fd1438f06b.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18028960/3969c26e-6c50-11e6-87f0-6ebb94cc1550.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44002782-09eb182a-9e0e-11e8-990b-f442df08a19f.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44003121-6992abc6-9e13-11e8-9527-9d8a14d0c73a.png)
