### ISSUE TITLE
KMSP-Minneapolis-St Paul International Airport-MINNESOTA-USA

### ISSUE THREAD

**Issue by david-garden** [InfiniteFlightAirportEditing/Airports#872]
This one is mine <3

**Comment by dushyants19** [comment]
@david-garden 🌴 hows this goin

**Comment by david-garden** [comment]
Bad Dush. Computer has failed me. Got most of the taxiways down before it junked out on me. Sounds like someone else has to do this.

**Comment by dushyants19** [comment]
Grabs

**Comment by lolo31r** [comment]
Priority 2

**Comment by Aviationluver** [comment]
I will take this.

**Comment by brunocr98** [comment]
Assigned :)

**Comment by Aviationluver** [comment]
Thanks ;) @brunocr98

**Comment by Aviationluver** [comment]
Sent in for review.

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/23755046/c40ded36-04a4-11e7-8ab7-b5681f5e1392.png)

**Comment by kilt46** [comment]
RUNWAY NUMBERS WRITTEN ON RUNWAYS!!!!
![image](https://user-images.githubusercontent.com/14023167/28650989-c8a4abc4-7244-11e7-9685-0415123c12de.png)

**Comment by brunocr98** [comment]
They're not "written", that's actually a new feature of WED, you can now see the runway numbers.

**Comment by kilt46** [comment]
OK THX

**Comment by danisrils39** [comment]
Upon further review, MSP is going to go under the laser cutter for a complete rework, some of the issues I noticed were:
-Lack of lighting
-Many locations with incorrect pavements
-Incorrect markings
-Incorrect spawn names
-Missing spawns
-New redesigned gates at Terminal 2
-Many unmergable taxiways

**Comment by danisrils39** [comment]
Sent to OR, any questions please forward to me before rejection if possible. ( ͡° ͜ʖ ͡°) @RyanEpps

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/64998344-281cbf00-d8ba-11e9-9778-b8a3d0221aa4.jpg)

**Comment by brunocr98** [comment]
"I'm currently in the process of adding the new taxiway Z" - Daniel Rilschi.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/75724882-0ffcf880-5cbe-11ea-8060-eb822aada735.jpg)
