### ISSUE TITLE
UUMU-Chkalovsky Airport-MOSCOW OBLAST-RUSSIA

### ISSUE THREAD

**Issue by sentikum** [InfiniteFlightAirportEditing/Airports#873]
Being redone.

By my assistant

**Comment by dushyants19** [comment]
how is this going @sentikum

**Comment by ErshovlaD** [comment]
Can I take this port? I'm going to make it

**Comment by sentikum** [comment]
Sure, @ershovlad

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19581913/4f9d0f0c-96f6-11e6-95dc-cde938e95e4d.png)
