### ISSUE TITLE
UHPP-Petropavlovsk-Kamchatsky Airport-KAMCHATKA-RUSSIA

### ISSUE THREAD

**Issue by sentikum** [InfiniteFlightAirportEditing/Airports#875]
Being redone

**Comment by kilt46** [comment]
Missing runway
![image](https://cloud.githubusercontent.com/assets/14023167/16887456/d7ea2636-4a9f-11e6-94c0-bfa57cf75546.png)

**Comment by TristinWoolf** [comment]
@sentikum Did you/are you going to fix this?

**Comment by sentikum** [comment]
I has already fixed

**Comment by TristinWoolf** [comment]
Has it been approved @sentikum?

**Comment by sentikum** [comment]
it is checked by Kilt

**Comment by kilt46** [comment]
2nd runway added as per Navigraph JUN-2016

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17267342/08de46be-55cc-11e6-85a7-abd6a727eabb.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18030385/b0cff4da-6c79-11e6-895c-de4f6385aa16.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18030386/ba083ea4-6c79-11e6-8bd9-815fe9f0ee94.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18030389/c5087a76-6c79-11e6-991e-683db2190d7b.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/43991899-8d019532-9d3b-11e8-844f-2d986f2e44a9.png)
