### ISSUE TITLE
LTAJ-Gaziantep Airport-GAZIANTEP-TURKEY

### ISSUE THREAD

**Issue by turkish1941** [InfiniteFlightAirportEditing/Airports#876]
I will make it

**Comment by turkish1941** [comment]
just send the email

**Comment by dushyants19** [comment]
211ae1d

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19409338/7b448f30-9297-11e6-9f7d-14f1bf2b9426.png)

**Comment by ECoops-123** [comment]
@SuhasIF will be redoing this airport for the following reasons:

* Removal of runway 10R/28L, converting to taxiway
* Adding multiple new hangars and taxiways 
* Adding many new markings in terminal area.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115118227-ca55ca80-9f67-11eb-8c31-9e7344c6d8e5.png)
