### ISSUE TITLE
LTCO

### ISSUE THREAD

**Issue by turkish1941** [InfiniteFlightAirportEditing/Airports#878]
I will make it

**Comment by turkish1941** [comment]
I cant make it bc wedbing decided to add a cloud over the whole airport

**Comment by TristinWoolf** [comment]
@turkish1941 Did you try Google Earth imagery?

**Comment by turkish1941** [comment]
I wanted to do that but I cant overlay an image on this, or at least I dont know how
![20160715_013230 1](https://cloud.githubusercontent.com/assets/13819750/16859150/cd2da95c-4a2c-11e6-8025-c79d505335c0.jpg)

**Comment by Oguz8011** [comment]
@turkish1941
Trabzon,Diyarbakır,Ordu Giresun havalimanlarını da yapabilir misin? Bu zamana kadar yaptıkların için tekrar teşekkürler.

Translate: 
@turkish1941
Can you make Trabzon(LTCG),Diyarbakır(LTCC) Ordu-Giresun (LTCB) Airports? Thank you again for all you had done of Airports.

**Comment by turkish1941** [comment]
tabi abi ama kulandimiz harita ordu daha yok, onu malesef daha yapamiyorum
translation: sure, but I cant make ordu yet bc of bing

![123456](https://cloud.githubusercontent.com/assets/13819750/17115618/7b7a352c-52b4-11e6-869d-c1803b47ed96.png)

**Comment by turkish1941** [comment]
Can I get unassigned? This airport can not be made with the curent bing map.

**Comment by dushyants19** [comment]
Hit Earth on the GMaps tab, you'll get the sat image. Use Google Earth to import them. If you still cant do it, we'll unassign you

**Comment by turkish1941** [comment]
![cd2da95c-4a2c-11e6-8025-c79d505335c0](https://cloud.githubusercontent.com/assets/13819750/17836569/9b411842-6797-11e6-8a76-fdf769905b9a.jpg)
Dush this is the image bing gives me it doesnt matter how I zoom in or out the cloud keeps being there above the whole airport

**Comment by turkish1941** [comment]
I give this one up, NOT doing this one.

**Comment by dushyants19** [comment]
Up for grabs

**Comment by ReflexRSM** [comment]
I'll take up this one, I'll be using Google Maps.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19332292/28a9f0a0-90b0-11e6-87e2-e5ea6c7cbc73.png)
