### ISSUE TITLE
PHTO-Hilo International Airport-HAWAII-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#88]
Scott's doing this one.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20582521/747bf092-b1a7-11e6-99ad-d516e84690ad.png)

**Comment by dushyants19** [comment]
New cargo apron  added

![image](https://cloud.githubusercontent.com/assets/13567007/20959513/5487ecde-bc81-11e6-833d-9a112a70540c.png)


@kilt46 should I remove the label?

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/61162402-c49f9b00-a4de-11e9-8ff9-2b5efd16f27f.jpg)
