### ISSUE TITLE
EGBJ-Gloucestershire Airport-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by ColonelJeff** [InfiniteFlightAirportEditing/Airports#880]
Being redone

**Comment by kilt46** [comment]
No file in REPO yet

**Comment by dushyants19** [comment]
Not received, send to correct email please :)

**Comment by dushyants19** [comment]
Up for grabs

**Comment by Will171** [comment]
when doing this airport, be weary that that runway 09-27 has been changed from existing bing imagery. Check google imagery for more info :)

**Comment by SWNelson** [comment]
I'm not part of IFAE, but can someone please do this?  This is my training and home airport and I would love to see this done.  If anyone would do this it would be highly appreciated.

**Comment by Will171** [comment]
ill do this one

**Comment by dushyants19** [comment]
@Ralphy444 is doing this

**Comment by dushyants19** [comment]
Any progress? @Ralphy444

**Comment by dushyants19** [comment]
Up for Grabs; Let us know if you want to do the airport.

**Comment by benjwri** [comment]
I can do this if it's still needed

**Comment by brunocr98** [comment]
Please accept the invite (should have been sent to your email) to collaborate in the repo, so then we will be able to assing you :)

**Comment by benjwri** [comment]
Went into spam, accepted now

**Comment by ryu12332** [comment]
Progress?

**Comment by moritzbabl** [comment]
member inactive, up for grabs

**Comment by ItsW1ll** [comment]
Assign me. Will do it April time.

**Comment by ItsW1ll** [comment]
I saw kilt mentioned that the airport has no file. Is this still correct?

**Comment by MajorTomMueller** [comment]
Ho, @ItsW1ll which years april?? ;-)

**Comment by ItsW1ll** [comment]
Idk mate should have been September

**Comment by kilt46** [comment]
Will is this done yet?

**Comment by ItsW1ll** [comment]
9e78493

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46924385-be30d100-cfe9-11e8-8be8-bdaa22a6f2fb.png)
