### ISSUE TITLE
LTCS

### ISSUE THREAD

**Issue by turkish1941** [InfiniteFlightAirportEditing/Airports#882]
I will make it

**Comment by TristinWoolf** [comment]
@turkish1941 You can only have three issues assigned to you at a time. You already have more than that..

**Comment by turkish1941** [comment]
oops forgot to send the others in, will do that right now

**Comment by turkish1941** [comment]
email is gone

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18618873/397234e6-7db5-11e6-9753-03dc65203022.png)
