### ISSUE TITLE
LTDA

### ISSUE THREAD

**Issue by turkish1941** [InfiniteFlightAirportEditing/Airports#883]
I will make it

**Comment by turkish1941** [comment]
email is gone

**Comment by samuelandersson** [comment]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/ff7e019cf1495188e8625f63de8db78283b64ebc)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18618475/2829506e-7dad-11e6-8caf-29a50c279fdc.png)
