### ISSUE TITLE
LHKD

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#884]
Kecskéd Airport

**Comment by IFAEpat** [comment]
Done.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17209333/2bdd899a-5482-11e6-8017-05851c3f4756.png)

**Comment by IFAEpat** [comment]
Gated

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17684893/ddf055c6-6324-11e6-8793-241e9dc8df62.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17684898/e42fd646-6324-11e6-8395-600d02efc123.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17684926/152f5d84-6325-11e6-8d67-c74858286482.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17684930/1b6434a4-6325-11e6-86d0-b37e60ac56ef.png)
