### ISSUE TITLE
LHZA

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#885]
Zalaegerszeg-Andráshida Airport

**Comment by IFAEpat** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17209536/10c659d8-5483-11e6-94d9-ff9f700dffca.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17350295/015e4598-58eb-11e6-8236-618671784c89.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17350393/f489d246-58eb-11e6-9a44-31473191ee10.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17384884/a43ae60e-59a4-11e6-8bdb-d0ba0869eb49.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34082749-c35517c0-e329-11e7-95f9-7120a92b32da.png)
