### ISSUE TITLE
UHSS

### ISSUE THREAD

**Issue by sentikum** [InfiniteFlightAirportEditing/Airports#886]
Being redone.

**Comment by dushyants19** [comment]
d68e1dc

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17267344/1b0e78cc-55cc-11e6-8972-9819c0aed1db.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18029047/f0bd7120-6c52-11e6-8e2a-dde8e26d2e0a.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18029052/fcee2818-6c52-11e6-98d9-bacfb2e87698.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/43992405-96d27a6a-9d43-11e8-8419-3489ffa4fc80.png)
