### ISSUE TITLE
LHBS

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#887]
Budaors Glider Airport

**Comment by IFAEpat** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17209198/7413ba1e-5481-11e6-9a7d-2fe0a4f1cd75.png)

**Comment by IFAEpat** [comment]
Gated

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17684782/c87c2d9c-6323-11e6-8064-ea441e359879.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17684807/fe459544-6323-11e6-929a-6c4920c9c081.png)
