### ISSUE TITLE
UNNT-Novosibirsk/Tolmachevo Airport-NOVOSIBIRSK-RUSSIA

### ISSUE THREAD

**Issue by sentikum** [InfiniteFlightAirportEditing/Airports#888]
Being redone

**Comment by kilt46** [comment]
Redone

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17194911/5f604864-5420-11e6-8b5c-5bade4731995.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17194948/98f1812e-5420-11e6-8df0-cac2b9759993.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32685962-bf4d58fc-c661-11e7-9faa-456409c4c205.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44308916-ea322c00-a383-11e8-9e05-53f5f7c09a16.png)
