### ISSUE TITLE
TJBQ

### ISSUE THREAD

**Issue by mjgonzalez45** [InfiniteFlightAirportEditing/Airports#889]
I am doing this!

**Comment by dushyants19** [comment]
Invited you to join our Github team, check it out! :)

**Comment by mjgonzalez45** [comment]
Alright! dushyants19 :)

**Comment by bylrret** [comment]
I think it's Priority 2, the runway is 11,752ft long

**Comment by IFAEpat** [comment]
@mjgonzalez45 status? If you're not doing this, I'm willing to take over. An Airport of this size shouldn't take more than 3 months...

**Comment by carmichaelalonso** [comment]
@mjgonzalez45 If you don't have time to do this soon, please let us know as we have other people waiting to do it. Thanks!

**Comment by IFAEpat** [comment]
That's it @mjgonzalez45, it's been too long.

**Comment by dushyants19** [comment]
Its on @IFAEpat now, @mjgonzalez45

**Comment by IFAEpat** [comment]
Up for grabs

**Comment by brunocr98** [comment]
Decided not to do this one, up for grabs.

**Comment by stryderIFC** [comment]
will be attempting this

**Comment by dushyants19** [comment]
Any progress? @stryderIFC

**Comment by dushyants19** [comment]
Up for Grabs; Let us know if you want to do the airport.

**Comment by bylrret** [comment]
I can do this one

**Comment by bylrret** [comment]
Sent for review

**Comment by moritzbabl** [comment]
Added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/28147815-a1ae5508-6748-11e7-827c-c8fa9f1c4fbf.png)
