### ISSUE TITLE
WMKM-Malacca Airport-MELAKA-MALAYSIA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#89]

**Comment by jpperks** [comment]
Missed out the north west apron. This will be fixed soon...

**Comment by jpperks** [comment]
Added missing aprons. Closing.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20043568/1380bbf6-a455-11e6-9714-cbcf68e63217.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/117542375-023bb500-afde-11eb-9256-d4c0c4a80e63.png)

**Comment by kilt46** [comment]
Request by Adibya Putra to rework airport. Significant change in runway length. Rework permission granted!

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/118897954-0b2b6100-b8d1-11eb-9521-3e46f9a3b52f.png)
