### ISSUE TITLE
LHER

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#890]
Eger Airport

**Comment by IFAEpat** [comment]
Done.

**Comment by kilt46** [comment]
This is just an airstrip

**Comment by IFAEpat** [comment]
Removed unneeded details

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19294888/308fce58-8ff6-11e6-85fc-2b94e787cef7.png)
