### ISSUE TITLE
LHKA

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#891]
Kalocsa Airport

**Comment by IFAEpat** [comment]
Done 8281d41

**Comment by kilt46** [comment]
TOO MANY SPAWN POINTS

**Comment by IFAEpat** [comment]
Fixed 639fedf

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17209312/0b6b2276-5482-11e6-8189-b4f4b34c502e.png)

**Comment by IFAEpat** [comment]
Gated

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17685039/2f71edd2-6326-11e6-849f-cb21abd28e70.png)
