### ISSUE TITLE
SPQT-Iquitos Airport-LORETO-PERU

### ISSUE THREAD

**Issue by woleby** [InfiniteFlightAirportEditing/Airports#892]
RECYCLED.

**Comment by TristinWoolf** [comment]
@woleby it appears that you haven't accepted the email to the GitHub team yet. @dushyants19 or somebody can you please invite him?

**Comment by dushyants19** [comment]
Invited :)

**Comment by dushyants19** [comment]
Please accept the invite :pray:

**Comment by dushyants19** [comment]
Please accept the invite 🙏 @woleby

**Comment by dushyants19** [comment]
Up for grabs

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/25304004/ea53bc4a-2723-11e7-8786-cce3df08b415.png)
