### ISSUE TITLE
KRND-Randolph AFB Airport-TEXAS-USA

### ISSUE THREAD

**Issue by CaptainDawud** [InfiniteFlightAirportEditing/Airports#894]
Self inflicted

♻️

**Comment by dushyants19** [comment]
Dove already I guess. #256

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21593156/c047bdac-d0d9-11e6-837b-7419c73b78aa.png)

**Comment by ItsW1ll** [comment]
Runway numbers need correcting in order to push this. InfiniteFlightAirportEditing/Navigation#1571

**Comment by MajorTomMueller** [comment]
Oh, the one with the baseball pitch ...

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/90325553-b2dec180-df42-11ea-9a69-0932287177ab.png)
