### ISSUE TITLE
YPAD-Adelaide Airport-SOUTH AUSTRALIA-AUSTRALIA

### ISSUE THREAD

**Issue by lachieee** [InfiniteFlightAirportEditing/Airports#895]
Adelaide International Airport.

**Comment by lachieee** [comment]
I will work on this.

**Comment by dushyants19** [comment]
Why did you close this? lol

**Comment by lachieee** [comment]
pm

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/22004122/ceab4e4a-dc1e-11e6-9166-052a19c0bee1.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/49686908-156e9180-fac1-11e8-824c-cee0226c7d66.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102554769-08f77900-408b-11eb-989b-0771cb3b70cb.png)
