### ISSUE TITLE
UWKD

### ISSUE THREAD

**Issue by sentikum** [InfiniteFlightAirportEditing/Airports#897]
Being redone

**Comment by dushyants19** [comment]
7d00dc4

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17267583/6fdaecfe-55d2-11e6-82ee-b64646da49a4.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18027011/741192f8-6c1d-11e6-94a9-162a133291ea.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18027014/7c585dca-6c1d-11e6-8ac1-3921eb61fb86.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18027016/83db9a44-6c1d-11e6-8b32-46767a0bc49e.png)
