### ISSUE TITLE
LGPA-Paros Airport-NOTIO AIGAIO-GREECE

### ISSUE THREAD

**Issue by CaptainDawud** [InfiniteFlightAirportEditing/Airports#898]
~~Moorabbin Airport~~

New Paros National, old removed but in repo.

https://en.wikipedia.org/wiki/New_Paros_Airport

**Comment by CaptainDawud** [comment]
I will work on this.

**Comment by CaptainDawud** [comment]
Sorry, can't do it.

**Comment by dushyants19** [comment]
Up  for grabs

**Comment by dushyants19** [comment]
Recycled to LGPA - New Paros National

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/37570303-322e2a0e-2abc-11e8-8106-b9bbfa0074d6.png)
