### ISSUE TITLE
KORH

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Airports#899]
Whole airport needs a redo.

**Comment by IFAEpat** [comment]
Nathan is doing this but he needs an invite to the team

**Comment by dushyants19** [comment]
a63f2c4

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19009801/1b28f344-873d-11e6-9725-e59e87311268.png)
