### ISSUE TITLE
KMCF

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#9]
Florida

**Comment by JohnPreston21** [comment]
I would like to do begin this one.

**Comment by AxelBeder** [comment]
I have already done this one @JohnPreston21. For some reasons my label didn't go through the system.

**Comment by AxelBeder** [comment]
Finished.

**Comment by kilt46** [comment]
3 Gates with same name
New Ramp 2 (x3)

**Comment by kilt46** [comment]
Will fix spawn points

**Comment by kilt46** [comment]
3 duplicate spawn points renamed

**Comment by samuelandersson** [comment]
Typo in gate name;

https://community.infinite-flight.com/t/kmcf-run-up-4-runway-04-parking-typo/20176

**Comment by IceBlue02** [comment]
Fixed.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17277005/1f7ecef6-56fe-11e6-9c02-a85f30b8ee2a.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17831762/af363ed0-66b7-11e6-9eea-ddb8e21df8e5.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17831763/b6419774-66b7-11e6-8874-737d74d5f52e.png)
