### ISSUE TITLE
URSS-Sochi Airport-KRASNODAR-RUSSIA

### ISSUE THREAD

**Issue by tsarkov90** [InfiniteFlightAirportEditing/Airports#900]
Being redone

**Comment by dushyants19** [comment]
d83b7d7

**Comment by kilt46** [comment]
outlines required for south apron

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17267364/6c2344ae-55cc-11e6-89e6-0a8d0a89fd49.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18027940/7652e6de-6c36-11e6-9ee2-b5e75f65b42a.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18027944/7e9cfaaa-6c36-11e6-890d-95d7dc3e4bc2.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44372403-5bb7ca80-a4a9-11e8-9b62-413f4e152a15.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/119571186-a95a7380-bd76-11eb-9bc9-e59448e3fd77.png)
