### ISSUE TITLE
RPVE-Godofredo P.Ramos Principal Airport-AKLAN-PHILIPPINES

### ISSUE THREAD

**Issue by sumith11** [InfiniteFlightAirportEditing/Airports#901]

**Comment by dushyants19** [comment]
So you want to do it?

**Comment by ReflexRSM** [comment]
Just sent for approval.

**Comment by dushyants19** [comment]
Only max 3 issues please :)

**Comment by dushyants19** [comment]
Not received. Correct email please!

**Comment by ReflexRSM** [comment]
Sent again

**Comment by samuelandersson** [comment]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/663a6546d519651bb75012753bcff5374f7e4f8b)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18975263/7fe60fd0-866e-11e6-886a-1bc1659178f7.png)

**Comment by RyanEpps** [comment]
Updated 3/20; needs gated

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/81459798-f2de1d80-9177-11ea-8ac2-845aa865f9f6.jpg)

**Comment by jaypzs** [comment]
Hi Tom, 
This is the update I wish to do for this airport. 
![image](https://user-images.githubusercontent.com/65849473/90490282-06ceed80-e171-11ea-82dd-4c51af7bd846.png)

**Comment by brunocr1050** [comment]
I'm reassigning @jaypzs to this airport again as he was still working on it.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/116813256-94444900-ab18-11eb-845c-4c534731297c.png)
