### ISSUE TITLE
LTAG

### ISSUE THREAD

**Issue by turkish1941** [InfiniteFlightAirportEditing/Airports#903]
will make it

**Comment by turkish1941** [comment]
email is gone

**Comment by samuelandersson** [comment]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/d7e1a652e8d43e2f05d0bb318730a83b04d7f4f9)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18618594/aca68b20-7daf-11e6-8021-6253c6088638.png)
