### ISSUE TITLE
ESOK 

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#904]
Being redone

**Comment by PaulNielsen** [comment]
Annndddd... Done. Awaiting approval now.

**Comment by dushyants19** [comment]
507746b

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17233001/ff31852a-54f1-11e6-9465-cecbc98cdbc4.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17264448/918c2c6c-55ac-11e6-8081-ac7a86048749.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18231196/7ae3d4c8-7277-11e6-997c-d1fb66ef82c2.png)
