### ISSUE TITLE
LHMP

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#906]
Matkópuszta Airport

**Comment by IFAEpat** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17209381/66fbe9c2-5482-11e6-9fd8-deca9be88e76.png)

**Comment by IFAEpat** [comment]
Gated

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17685254/f92ab414-6327-11e6-94a5-e376538a1634.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17685258/001b657a-6328-11e6-8b2b-3652a41a2ce2.png)
