### ISSUE TITLE
LHOY

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#907]
Õcsény Airport

**Comment by IFAEpat** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17209408/81c3f826-5482-11e6-9277-44a5eb8314be.png)

**Comment by IFAEpat** [comment]
Gated

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17684677/f862150e-6322-11e6-9546-b5baeb6dfd13.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17684679/00ccbe24-6323-11e6-815d-cc2ebded97a1.png)
