### ISSUE TITLE
LHJK

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#908]
Jakabszállás Airport

**Comment by IFAEpat** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17209268/d9acdaf4-5481-11e6-8aac-cc3e408cfa22.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17831776/479a8208-66b8-11e6-9b08-08a043cbc788.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17831777/5076271a-66b8-11e6-874b-37bc70c0b558.png)
