### ISSUE TITLE
EDHL

### ISSUE THREAD

**Issue by KarlLuebs** [InfiniteFlightAirportEditing/Airports#909]
Redoing EDHL.

**Comment by IFAEpat** [comment]
Can someone please invite Karl to the team?

**Comment by dushyants19** [comment]
Karl, check your email and accept the invite to out Github Team.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17350615/da98055e-58ed-11e6-9563-2be51969a658.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17386959/dac310a6-59b4-11e6-973b-cf3a6ff27918.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17386963/e318428a-59b4-11e6-9e1f-e730116ce97f.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33801199-e39537b6-dd18-11e7-9e1c-e9a0e7cc32af.png)
