### ISSUE TITLE
LHBD

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#910]
Börgönd Airport

**Comment by IFAEpat** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17209160/3e319132-5481-11e6-99c0-2bb9e95fd28a.png)

**Comment by IFAEpat** [comment]
Gated

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17684279/de8ea35c-631f-11e6-948b-3ca5169b13ef.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17684286/e795101c-631f-11e6-9531-c3dc9a73d5f7.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17684381/cf38dd4a-6320-11e6-983e-0c580e54c277.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17684390/daca9932-6320-11e6-941a-7ce1c1a34269.png)
