### ISSUE TITLE
LHSA

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#911]
Veszprém-Szentkirályszabadja Airport

**Comment by IFAEpat** [comment]
done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17209432/9e6b9fce-5482-11e6-8995-8dcb4cfc17c9.png)

**Comment by IFAEpat** [comment]
Gated

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17719853/3d61fb72-63e3-11e6-9b6e-998fbf6f8bb4.png)
