### ISSUE TITLE
USSS

### ISSUE THREAD

**Issue by sentikum** [InfiniteFlightAirportEditing/Airports#912]
Being redone.

**Comment by dushyants19** [comment]
4966c26

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17267370/88779b32-55cc-11e6-90e2-1ae3ba77adab.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18027515/8094d694-6c2b-11e6-9d31-191f1413ca9e.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44608004-e48b7a80-a7b7-11e8-9c0a-08bb159c8554.png)
