### ISSUE TITLE
YMRY-Moruya Airport-NEW SOUTH WALES-AUSTRALIA

### ISSUE THREAD

**Issue by bylrret** [InfiniteFlightAirportEditing/Airports#913]
RECYCLE IS LOVE. RECYCLE IS LIFE  ♻️

**Comment by IFAEpat** [comment]
He said he can't do this, I'll be taking over

**Comment by IFAEpat** [comment]
Up for grabs

**Comment by brunocr98** [comment]
Not doing it anymore. Up for grabs.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27002483-491d3bce-4da9-11e7-95af-29d46852d7ca.png)
