### ISSUE TITLE
KIWI

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Airports#914]
Needs a redo

**Comment by samuelandersson** [comment]
[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/034508291672668e6814beb37b4026c55e9feeca)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18817487/fb8ed02c-8326-11e6-984c-9036ae1ae934.png)
