### ISSUE TITLE
UWWW

### ISSUE THREAD

**Issue by sentikum** [InfiniteFlightAirportEditing/Airports#915]
Being redone.

**Comment by sentikum** [comment]
close! airport is approved

**Comment by IFAEpat** [comment]
Approved✅

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17400716/15e924cc-5a0f-11e6-9c44-164c1ea01fe8.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17400727/24a732ba-5a0f-11e6-8579-18b307984ed1.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17400735/2fdc4ea4-5a0f-11e6-8d12-d57ea712c8db.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34320350-edc0991a-e7bd-11e7-8861-f0f00f8a3210.png)
