### ISSUE TITLE
EDDS - Stuttgart Int'l Airport

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Airports#917]
I will re-do this one.

**Comment by TristinWoolf** [comment]
This is up for grabs! :)

**Comment by moritzbabl** [comment]
I'll do this, may take a bit since no WEDbing images are available

**Comment by dushyants19** [comment]
@moritzbabl you're doing this

**Comment by moritzbabl** [comment]
Sent for approval

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20029493/7c2311bc-a31b-11e6-9b0d-70faf3e88f42.png)
![image](https://cloud.githubusercontent.com/assets/14023167/20029496/85041538-a31b-11e6-8b56-1cbd5ae4d5e6.png)
