### ISSUE TITLE
LFLL-Lyon Saint Exupery Airport-RHONE-ALPES-FRANCE

### ISSUE THREAD

**Issue by SeanTea** [InfiniteFlightAirportEditing/Airports#918]
Please edit me

**Comment by dushyants19** [comment]
How is the progress on this, @SeanTea?

**Comment by SeanTea** [comment]
Abandoning the project, banned from IF 2 months ago, best of luck with IFAE.

**Comment by dushyants19** [comment]
ok

**Comment by lolo31r** [comment]
redoing this

**Comment by brunocr98** [comment]
Up for grabs.

**Comment by moritzbabl** [comment]
I'll do that - let's see what we can do with that construction site

**Comment by moritzbabl** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24072171/b90c1a9e-0bb0-11e7-831a-b462a204be83.png)

**Comment by moritzbabl** [comment]
Going to add the completed new terminal part
