### ISSUE TITLE
LHBC

### ISSUE THREAD

**Issue by SeanTea** [InfiniteFlightAirportEditing/Airports#919]

**Comment by TristinWoolf** [comment]
Duplicate. Go to #918 for further discussion.

**Comment by IFAEpat** [comment]
Békéscsaba Airport

**Comment by IFAEpat** [comment]
Done

75e16575b0d3ecbadc2d6240e02015e4480bd7f6

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17209128/15156968-5481-11e6-8266-f48b37c60e27.png)

**Comment by IFAEpat** [comment]
Gated

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17719941/c1b560f8-63e3-11e6-84ed-9690b3a93b21.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17719943/c9cf78be-63e3-11e6-8527-a48a0b3a12f6.png)
