### ISSUE TITLE
MYRP

### ISSUE THREAD

**Issue by TristinWoolf** [InfiniteFlightAirportEditing/Airports#920]
New Port Nelson Airport

**Comment by TristinWoolf** [comment]
Done.

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/20e76580587a8821d04b8c9c8b6c99a8429cfeca)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18620335/e1bf2ada-7dd5-11e6-93f0-f8f047448aa8.png)
