### ISSUE TITLE
KBIF-Biggs AAF (Fort Bliss) Airport-TEXAS-USA

### ISSUE THREAD

**Issue by NewZealand1** [InfiniteFlightAirportEditing/Airports#922]
PLEASE REDRAW ME!

**Comment by samuelandersson** [comment]
Have you got an invite from github by mail?

Please accept it if so so that we can assign you.

**Comment by dushyants19** [comment]
Invited, check it out

**Comment by TristinWoolf** [comment]
Duplicate issue. Please check #596 for further discussion.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34991308-c2426d0c-fa8e-11e7-9370-d5cdebddff1e.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/52541268-a7607800-2d58-11e9-8a6e-d0df9da0dee9.png)
