### ISSUE TITLE
ESSK

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Airports#923]
Requires redo

**Comment by samuelandersson** [comment]
Redone.

For future reference I had to use google maps and ortophotos in order to outline the airport.

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/02f379849d07fe070cd6d9f71e436c0777f4d6ec)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17264507/0c7f765e-55ad-11e6-9c37-77fcaaf8a7b9.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18231164/8da5f97a-7276-11e6-9d45-d28d8a37e809.png)
