### ISSUE TITLE
EGFF-Cardiff Airport-WALES-UNITED KINGDOM

### ISSUE THREAD

**Issue by CJ-Sapan** [InfiniteFlightAirportEditing/Airports#924]
EGFF - Cardiff International Airport

**Comment by dushyants19** [comment]
@CJ-Sapan hows this going

**Comment by CJ-Sapan** [comment]
Stilll getting there

**Comment by dushyants19** [comment]
@CJ-Sapan are you still on this

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by brunocr98** [comment]
Doing this airport.

**Comment by brunocr98** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21964435/b3d1bd60-db11-11e6-9da0-5973f0ab36dd.png)

**Comment by ItsW1ll** [comment]
Adding stands 7L,7,8R plus airport changes

**Comment by ItsW1ll** [comment]
d9c659b done

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/47608642-79983300-d9f6-11e8-9b31-10b5192a6551.png)
