### ISSUE TITLE
RJTT-Tokyo Intl-TOKYO-JAPAN

### ISSUE THREAD

**Issue by turkish1941** [InfiniteFlightAirportEditing/Airports#925]
I  will make it

**Comment by turkish1941** [comment]
Email is gone

**Comment by kilt46** [comment]
Taxiway not visible!
![image](https://cloud.githubusercontent.com/assets/14023167/17911351/b60ad8cc-6952-11e6-9da2-619bb297f49b.png)

**Comment by turkish1941** [comment]
thats pretty weird just opened the file 2 sec ago and it worked proof
![rjtt kilt](https://cloud.githubusercontent.com/assets/13819750/17912080/c055396e-6991-11e6-9244-96a9dff1f798.png)

**Comment by dushyants19** [comment]
It was not visible at higher zoom levels, WED bug.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32994626-b39d140a-cd2f-11e7-9367-426e9c665e93.png)

**Comment by MBeringuy** [comment]
Is it to reopen this issue? Or has the airport been reviewed by OR?

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/71047089-35e01b80-2119-11ea-8aa3-4b38b9a66487.jpg)
