### ISSUE TITLE
ESGR

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Airports#926]
Skövde Airport, Vastra Gotland, Sweden (This is for you @kilt46).

Needs redo.

**Comment by samuelandersson** [comment]
Done.

For future reference I had to use an ortophoto due to a cloud above the main apron.

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/8d946599607fc8680ce0a398e538849a2927ce2c)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17232715/a521937e-54ef-11e6-94f3-8e19ad0fecb5.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17262957/093ae478-55a4-11e6-99aa-b091aa08408c.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18231473/140688f0-7280-11e6-9d74-95dc32708ff4.png)
