### ISSUE TITLE
ESKN

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Airports#927]
Making small fixes like adding buildings and other small things.

**Comment by samuelandersson** [comment]
Added buildings and lowered AD elev.

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/dd411d2979f333bdf4f80e8a78f2da524ac5a4db)

**Comment by kilt46** [comment]
APRON 4 GATES MISSING. PLEASE ADD
![image](https://cloud.githubusercontent.com/assets/14023167/16894669/12a2faea-4b23-11e6-9c19-9c585f9d5820.png)

**Comment by samuelandersson** [comment]
Will fix.

**Comment by samuelandersson** [comment]
Missing spots added

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/8059296007cf551c2f176a92a66a8c67dfea6f1a)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17232769/05f222ea-54f0-11e6-9023-52a2a7e8f007.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17263047/6a08b852-55a4-11e6-9c1a-017fd03450e6.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18231383/3d7be90c-727e-11e6-9201-f761495209fb.png)
