### ISSUE TITLE
ESNS

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Airports#928]
Needs redo

**Comment by samuelandersson** [comment]
And redone.

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/ab0573fca0dd94c3c1fbdcbe81e33512bc1a5a85)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17232980/dc5fd236-54f1-11e6-9d1e-ebe25270153b.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18419266/7e80325c-781c-11e6-98f4-0d27c492a98c.png)
