### ISSUE TITLE
NVVV-Port Vila Bauerfield Airport-SHEFA-VANUATU

### ISSUE THREAD

**Issue by KarlLuebs** [InfiniteFlightAirportEditing/Airports#929]
RECYCLED (TWICE)

**Comment by TristinWoolf** [comment]
Duplicate issue. Please search before creating issues. We don't want duplicates. Check #574 for further discussion.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/31864050-ae88e3dc-b71c-11e7-874e-064dc2ca9c53.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/123527927-25fbad00-d6a9-11eb-9a36-2be42dea29d0.png)
