### ISSUE TITLE
LGSA

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#930]
Chania Airport, i will do it
Runway is longer than 10k ft according to airport chart btw

**Comment by moritzbabl** [comment]
Sent for approval

**Comment by dushyants19** [comment]
ok approved

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19175068/58d38022-8bf9-11e6-9345-98394614ffa2.png)
