### ISSUE TITLE
EDGS

### ISSUE THREAD

**Issue by lolo31r** [InfiniteFlightAirportEditing/Airports#931]
I´ll do this airport :)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17463641/d6a6129c-5c8f-11e6-910c-ef631beb32cb.png)
GA APRONS
![image](https://cloud.githubusercontent.com/assets/14023167/17463643/e24b3384-5c8f-11e6-888d-19236a9cefb3.png)
