### ISSUE TITLE
ESMX

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#933]
Being redone

**Comment by PaulNielsen** [comment]
Done, awaiting approval

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17232799/43c89cb6-54f0-11e6-9842-994e60b37622.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18420670/b7dd59fa-783d-11e6-8248-31e4a13b48c7.png)
