### ISSUE TITLE
KBUF-Buffalo Niagara International Airport-NEW YORK-USA

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#936]
Buffalo Niagara Intl

**Comment by IFAEpat** [comment]
Up for grabs! Good for new editors!

**Comment by IFAEpat** [comment]
Up for grabs

**Comment by dushyants19** [comment]
Stop bumpin'

**Comment by lolo31r** [comment]
redoing this

**Comment by moritzbabl** [comment]
added

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/24578734/5812be4e-16ac-11e7-9f49-73284f19e5c7.png)

**Comment by ryu12332** [comment]
ISSUE: Certain Runway markings are missing on all runways and only the threshold markings and the aiming point markings are showing. 
[IF IMAGE](https://drive.google.com/open?id=1M9qJPd2ep2NzvPW-68LhgIn-DwSYlsCB)
[SAT IMAGE](https://drive.google.com/open?id=15flvEka0yANf4vMKy_loaNlxlHXJCI1K)

**Comment by ewanfleming** [comment]
I'll take this one.

**Comment by dushyants19** [comment]
No I'll fix it. It'll be quicker

**Comment by MajorTomMueller** [comment]
@Czechoslovaki ?
• GA area needs additional spawns + currently incorrect sizes
• Many areas with the wrong pavement
• Some taxiways are not accurate
• Gate outlines are outdated (inaccurate)
• RWY 14/32 missing shoulder

**Comment by Czechoslovaki** [comment]
Sent For OR

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/92186825-95a06300-ee1d-11ea-8099-4f3863e3a7cc.png)
