### ISSUE TITLE
ESST

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Airports#937]
Torsby

Will fix.

**Comment by samuelandersson** [comment]
Redone.

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/7b7a9676f337c5f85c131677b68a4c6a78ad5128)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17264545/56a6cdc2-55ad-11e6-8dc6-754a4f3c56e5.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18231099/6aaaf5f8-7274-11e6-9a4b-34d61a367309.png)
