### ISSUE TITLE
ESSP 

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#939]
Being redone

**Comment by PaulNielsen** [comment]
Done, awaiting approval

**Comment by kilt46** [comment]
Please add gates 5-7 as per enclosed chart
![image](https://cloud.githubusercontent.com/assets/14023167/17083572/285d7e2a-516b-11e6-87a3-46dfdc320044.png)

**Comment by PaulNielsen** [comment]
Will look into it now :)

**Comment by PaulNielsen** [comment]
Weird, because this is not how it look on the image, for example look here 
![skarmavbild 2016-07-24 kl 14 55 29](https://cloud.githubusercontent.com/assets/15717537/17083594/b96e4ece-51ae-11e6-9dda-704afe075dc9.png)

**Comment by PaulNielsen** [comment]
Fixed and sent in.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17456295/9ae9032e-5b98-11e6-8f0b-c6f249bfa5d0.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17456300/abd9f350-5b98-11e6-87f0-f6abfedb12d4.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17456302/ba947244-5b98-11e6-9a06-da588082ae5f.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33529155-2471c20e-d832-11e7-9411-3f83a47de15f.png)
