### ISSUE TITLE
UUEE-Moscow-Sheremetyevo Airport-MOSCOW-RUSSIA

### ISSUE THREAD

**Issue by tsarkov90** [InfiniteFlightAirportEditing/Airports#940]
Moscow-Sheremetyevo.
Hub for Aeroflot-Russian Airlines.
Two runways:
06R/24L - 12,139 ft
06L/24R - 11,647 ft

BEING REDONE

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17197291/1b58b6ea-5431-11e6-9757-22ec76cab0fe.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17197297/336ebc52-5431-11e6-82fd-1639c07668e3.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17197573/6e60b764-5433-11e6-9390-ab16d63dc0cc.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17231404/3c573522-54e7-11e6-9e28-e2a76eba365f.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17267490/4595a6de-55d0-11e6-9d79-9462c1932ef9.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17267493/4cd0030e-55d0-11e6-9b28-abc9b36de03b.png)

**Comment by kilt46** [comment]
TERMINAL D
![image](https://cloud.githubusercontent.com/assets/14023167/17456640/810cf22e-5ba4-11e6-893c-bf4c8e1260c7.png)
TERMINAL E
![image](https://cloud.githubusercontent.com/assets/14023167/17456643/8ff02c70-5ba4-11e6-89f8-8d47de4e0c36.png)
CARGO
![image](https://cloud.githubusercontent.com/assets/14023167/17456647/ab61711c-5ba4-11e6-8e38-603e45dbd2b0.png)

**Comment by kilt46** [comment]
TERMNAL B
![image](https://cloud.githubusercontent.com/assets/14023167/17456710/24d0b182-5ba7-11e6-8109-153c76e27ccc.png)

**Comment by kilt46** [comment]
TERMINAL C
![image](https://cloud.githubusercontent.com/assets/14023167/17456720/6b6c2d88-5ba7-11e6-9416-2c2551df7280.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17456868/37b2e7da-5bab-11e6-8b2b-6db9ffdb9e83.png)

**Comment by kilt46** [comment]
Missing new runway 06L/24R
![image](https://user-images.githubusercontent.com/14023167/40886892-b9829f1e-6705-11e8-9845-d86ef381965f.png)

**Comment by brunocr98** [comment]
Since the 3rd runway is not available neither in Google and Yandex I think it will be better to leave it as a suggestion in the meantime. Once Google or Yandex update their satellite images I'd reconsider this airport or yield it to someone else. I'll not waste my time on this issue.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/43747039-2132f04e-99ad-11e8-96ac-a2df5c8f852c.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/43805141-4593d306-9a64-11e8-8479-08e004908f22.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/88436947-01c58b00-cdcb-11ea-9868-21e58b37e3f0.png)

**Comment by MajorTomMueller** [comment]
Editor did find some more things to improve

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/94206862-09b5b000-fe8c-11ea-91c4-ca20f1866990.png)

**Comment by brunocr1050** [comment]
@AleksanderIF will be doing the following:

- Terminal C and West Sector of Terminal B are fully completed
- Add new Stands 93B & C - 97B & C
- Align terminals A and B with images
- New Tower, Approach and Departure frequencies

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/115964263-39dc3480-a4e9-11eb-9beb-6677bb5524e6.png)
