### ISSUE TITLE
ESMK

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#941]
Being redone

**Comment by PaulNielsen** [comment]
Done, awaiting approval

**Comment by kilt46** [comment]
Transparent runway
![image](https://cloud.githubusercontent.com/assets/14023167/17083606/ed2a6ace-516b-11e6-9152-ad1b835ced57.png)

**Comment by PaulNielsen** [comment]
I have sent in ESMK again with and fixed the runway. :)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17262756/f87302ac-55a2-11e6-93cd-30612547574a.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17456204/543570dc-5b95-11e6-8c27-1d9f37d50c71.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17456205/5e0aad84-5b95-11e6-9f9f-00f3897e4e22.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33529114-969a87a4-d831-11e7-884f-33a0c2487209.png)
