### ISSUE TITLE
LHHH

### ISSUE THREAD

**Issue by hairlineAirlines** [InfiniteFlightAirportEditing/Airports#942]

**Comment by IFAEpat** [comment]
@hairlineAirlines needs to be invited guys1 :)

**Comment by TristinWoolf** [comment]
Duplicate issue. Please search before creating issues! Check #646 for further discussion.

**Comment by IFAEpat** [comment]
Will reuse this and #919 to clean up the Duplicates

**Comment by IFAEpat** [comment]
Hármashatárhegy Airport

**Comment by IFAEpat** [comment]
done

fbfcae8

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17209234/ada16fec-5481-11e6-8684-8c8c90940235.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17456394/e79a1638-5b9b-11e6-875a-fee4c9e5a78c.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17456395/ef60af6c-5b9b-11e6-97cd-8ee3a0539877.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34082678-4ba3e608-e328-11e7-9742-963acbce7246.png)
