### ISSUE TITLE
SULS-Capitan Curbelo Intl-MALDONADO-URUGUAY

### ISSUE THREAD

**Issue by hairlineAirlines** [InfiniteFlightAirportEditing/Airports#943]
RECYCLED.

**Comment by IFAEpat** [comment]
@hairlineAirlines is doing this, needs to be invited

**Comment by dushyants19** [comment]
Invited.

**Comment by dushyants19** [comment]
Please accept the invite :pray: :)

**Comment by dushyants19** [comment]
Up for Grabs

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/27499153-17427a04-5828-11e7-8de4-222f843094ee.png)

**Comment by brennanhackard** [comment]
@GBKarp will be editing this airport for the following reasons:

- new apron and taxiway to the north of the airport
- material changes on apron needed
- buildings need to be removed

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/102944249-e2b54d00-447f-11eb-943f-359360a1a3be.png)
