### ISSUE TITLE
EDBC

### ISSUE THREAD

**Issue by lolo31r** [InfiniteFlightAirportEditing/Airports#944]
I am doing now this airport

**Comment by TristinWoolf** [comment]
@lolo31r You haven't accepted the invite to the GitHub team via email yet. Please accept. :)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17387250/81e34408-59b7-11e6-8851-bf3d113f34a2.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17387262/927d69e2-59b7-11e6-9a4b-5d98fb8dc325.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20507212/e4ef6582-b01e-11e6-9862-983429ebd678.png)
