### ISSUE TITLE
ESSD

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Airports#945]
Redoing

**Comment by samuelandersson** [comment]
Done.

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/2737a17ef513a21bbc3fe181e635edb5334afbb7)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17233019/2180a20a-54f2-11e6-9b79-25c8d615f77c.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17264473/c8f19f3e-55ac-11e6-99fe-ea5ecf1c58fa.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17456168/c42a768c-5b93-11e6-9aee-fdc33784f2c7.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17456169/cba5c128-5b93-11e6-82cf-e2de786f2882.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33527544-61082dbc-d818-11e7-8483-9f7fcd136763.png)
