### ISSUE TITLE
ESND

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Airports#946]
Redoing.

**Comment by samuelandersson** [comment]
Done.

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/121ef813cb380c9de1168e9144774606386b0c27)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17232809/55eef05c-54f0-11e6-824f-52a0ca04e0f5.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17264315/c0ef1394-55ab-11e6-88ce-f1f78e5d82db.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17456112/c62c4aca-5b91-11e6-86b0-ece62c6f4a97.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17456114/cd317926-5b91-11e6-890b-faa10d58f64a.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33529675-b8b58b10-d839-11e7-964e-90eb9d1e9eca.png)
