### ISSUE TITLE
ESNN

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#947]
Being redone :)

**Comment by PaulNielsen** [comment]
Done, awaiting approval.

**Comment by kilt46** [comment]
Only 6 gates on main apron
![image](https://cloud.githubusercontent.com/assets/14023167/17083651/088381b0-516d-11e6-8aea-b9543363844f.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17083659/1427717a-516d-11e6-9b1e-0b843cbe9f5a.png)

**Comment by PaulNielsen** [comment]
Again these old images where wrong.. Will fix this.

**Comment by PaulNielsen** [comment]
Fixed, and sent in for approval

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17232951/9846ee86-54f1-11e6-9621-295f91277408.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17264377/21ec5918-55ac-11e6-8553-a50aebefa74c.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17456063/d10c3bcc-5b90-11e6-95e2-18fcd8bbb51a.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17456066/da4243da-5b90-11e6-9cb5-d7b9cd664545.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33529662-8532c00a-d839-11e7-95c2-44e50eb7f96d.png)
