### ISSUE TITLE
YWLM-Williamtown Airport-NEW SOUTH WALES-AUSTRALIA

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Airports#948]
Newcaslte airport in aus. Needs a complete re-do. I will do it.

**Comment by dushyants19** [comment]
hows this going @RileyDunshea

**Comment by RileyDunshea** [comment]
It's taking me a while because I have another airport I'm doing too. Should be done quite quickly as soon as I finish EPWA.

**Comment by moritzbabl** [comment]
any progress now? @RileyDunshea

**Comment by dushyants19** [comment]
@RileyDunshea its been ages....

**Comment by RileyDunshea** [comment]
Its nearly done. Sorry I've been busy with school.

**Comment by dushyants19** [comment]
Any progress? @RileyDunshea

**Comment by RileyDunshea** [comment]
That computer doesn't work with editing, I'm not going to lie to you I haven't opened IF in 3 months, and I've been busy with school.

**Comment by brunocr98** [comment]
Up for grabs.

**Comment by MajorTomMueller** [comment]
Take this one.

**Comment by MajorTomMueller** [comment]
![ywlm-overview](https://user-images.githubusercontent.com/26853210/30982545-0406adbe-a488-11e7-8bd9-eb937a9f4a7d.jpeg)

**Comment by MajorTomMueller** [comment]
roofed fighter spawns adjusted to accommodate most IF fighters

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/40260828-6c52ad14-5ac2-11e8-8954-2e3b5cb98d00.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44947565-4198b900-add4-11e8-912c-2b73ec805788.png)

**Comment by kilt46** [comment]
Boundary Fix - Error Channel

**Comment by MajorTomMueller** [comment]
Hey @kilt46 if you remove buildings why don't you remove all?
Why do you change outline of Hangars instead of fit it to the moving area floorspace?
And why don't you add obvious Lines to the Hangar spaces?
If you say Boundary fixes why changed you other things without notice? and why haven't you removed the storage Buildings at the Apron?

You would have better changed nothing then doing such an incomplete and incorrect work...
It is annoying!!

**Comment by MajorTomMueller** [comment]
Airport fits neither old nor new guidelines.
Will be reworked by time.

**Comment by RyanEpps** [comment]
Boundary fix indicates that this airport is being brought up to spec, which it is. Fixing the boundary, switching existing hangars, and removing unnecessary ones is sufficient for a fix of this magnitude. 

In the future, if you wish to rework an airport, it is best to avoid criticizing members and their work to this extent. Rather, "Performing a complete rework" is sufficient.

Thanks.

**Comment by MajorTomMueller** [comment]
- corrected Hangarfloors 
- corrected Markings
- added RWY extensions with related TWYs and EOR
- removed old EOR
- added JSF Apron

PLEASE note: The Airport is under construction, further updates will be added as soon as new imagery or AIP is available. I keep track of this.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46589864-350f1c80-ca74-11e8-8069-cba042be288e.png)
