### ISSUE TITLE
ESNH

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#949]
Being redone

**Comment by PaulNielsen** [comment]
Done, awaiting approval

**Comment by kilt46** [comment]
This is a base file. No modification has taken place
![image](https://cloud.githubusercontent.com/assets/14023167/17262829/5ae625cc-55a3-11e6-9021-482c128c27c5.png)

**Comment by PaulNielsen** [comment]
I guess maybe @dushyants19 forgot to add it.

**Comment by dushyants19** [comment]
Ill look into it.

**Comment by dushyants19** [comment]
Newest version is in the repo. 
Nothing wrong on my side

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17456002/0b550072-5b8f-11e6-813f-eb07f0f3b8a1.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17456003/138f3d8e-5b8f-11e6-8c62-6b78b783b5a0.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33529745-cddb62f2-d83a-11e7-92fb-72db7553e12d.png)
