### ISSUE TITLE
ESMT-Halmstad Airport-HALLAND-SWEDEN

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Airports#951]

**Comment by samuelandersson** [comment]
Redone.

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/5e4780f18802d65c860eb15a3b14f577913a4ba7)

**Comment by kilt46** [comment]
Error with taxiway. Transparent
![Uploading image.png…]()

**Comment by TristinWoolf** [comment]
@kilt46 Could you please reupload the picture? It did not manage to upload..

**Comment by samuelandersson** [comment]
@kilt46 I have also doublechecked wi th @henrikbg. This is currently a bug in WED and it is actually there.

**Comment by kilt46** [comment]
That is because...
![image](https://cloud.githubusercontent.com/assets/14023167/17004904/ef4b8b98-4e9c-11e6-982c-729af103fa3e.png)

**Comment by kilt46** [comment]
Its a LINE not a taxiway
![image](https://cloud.githubusercontent.com/assets/14023167/17004914/019a7b74-4e9d-11e6-8918-d30de035f9a6.png)

**Comment by samuelandersson** [comment]
That explains it all, I'll check it out tomorrow.

**Comment by samuelandersson** [comment]
Fixed problem, the previous line is now a taxiway.

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/2d222301a08b417990765dc0adcffe402b00c038)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17232790/3339a110-54f0-11e6-9e51-0ef0a01ce43d.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17264243/54059866-55ab-11e6-9cc2-74313eadb631.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17455987/46178942-5b8e-11e6-9758-df2c61afebd6.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17455990/50b9f484-5b8e-11e6-8739-85a6bdd1464b.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33527587-fcb791ee-d818-11e7-80bd-486c1a9775a8.png)
