### ISSUE TITLE
RJFT

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#953]
Kumamoto

Previous issue may have been recycled, created a new one so Kilt can process :)

**Comment by dushyants19** [comment]
Pat, do you want to do this?

**Comment by IFAEpat** [comment]
@dushyanys19 I already did, I said the issue may have been recycled already. I opened a new one so Kilt can process it for his website.

**Comment by dushyants19** [comment]
If its done, close it :)

**Comment by IFAEpat** [comment]
@dushyants19, ok sorry, I didn't have much service earlier. Anyway, thanks :)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17244549/11ad8ed2-5548-11e6-8a1c-3f647b858a59.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17454270/f1ce7aa0-5b54-11e6-8a2f-b7b7b5867cac.png)
TERMINAL
![image](https://cloud.githubusercontent.com/assets/14023167/17454272/fdc74da0-5b54-11e6-9d58-bbb5e6880f84.png)
MILITARY APRON
![image](https://cloud.githubusercontent.com/assets/14023167/17454274/0b2fb48c-5b55-11e6-8dd1-92160e413382.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32994474-64a1cb68-cd2d-11e7-9ba7-26c1e0b20545.png)
