### ISSUE TITLE
EDNB

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#954]
Editing EDNB (Arnbruck, Germany) as my first airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17837652/f80a6764-677d-11e6-9f23-ce61ba6f8c8b.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17837653/ffa70df6-677d-11e6-9ce5-72040b9bab70.png)
