### ISSUE TITLE
VQTY

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#956]
Quickly redoing VQTY (Yongphulla Airport), Bhutan.

**Comment by dushyants19** [comment]
New airport eh? Nice!

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17451907/0e6eca04-5b30-11e6-9bf6-5b948de1a840.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17451955/92fdbb2c-5b30-11e6-96b7-fb6eefb5798a.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33918006-d2ce2798-df76-11e7-8612-0bf41d09ae36.png)
