### ISSUE TITLE
EDNR

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Airports#957]
Regensburg Oberhub Airfield, will do it

**Comment by moritzbabl** [comment]
Sent for approval

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17451770/07f6e16c-5b2f-11e6-95e1-b1bb4084f0b4.png)

![image](https://cloud.githubusercontent.com/assets/14023167/17451766/fea4138c-5b2e-11e6-89fc-0d2d68c26972.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33692429-e1e4f9e6-dab2-11e7-9fb4-ed7b17d574f0.png)
