### ISSUE TITLE
ESNQ

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#958]
Being redone

**Comment by PaulNielsen** [comment]
Sent in for approval

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17232970/ccf1073e-54f1-11e6-9f47-f95c8056f998.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17451436/7992a23c-5b2c-11e6-9738-1b0987f7e364.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17451445/83a552ce-5b2c-11e6-8159-abbf791d63cb.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33529104-5229ea4c-d831-11e7-8795-147ce9d5833f.png)
