### ISSUE TITLE
LDLO

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#959]
Overhauling Losinj Airport, Croatia.

**Comment by TristinWoolf** [comment]
@bavAVIA You have to accept the email invite to the GitHub team. :)

**Comment by dushyants19** [comment]
Please accept the invite 🙏

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17837320/1aeb98b4-6776-11e6-8226-8d2f846681f4.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17837323/23e2e1e8-6776-11e6-8fb2-0c8e1fc9ea85.png)
