### ISSUE TITLE
MYNN-Lynden Pindling International Airport-NASSAU-BAHAMAS

### ISSUE THREAD

**Issue by TristinWoolf** [InfiniteFlightAirportEditing/Airports#964]
Lynden Pindling International Airport

Being redone.

**Comment by TristinWoolf** [comment]
Done... Finally!

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/bbc7268637d79ca85a3d4fafe8a3a65701c9aa25)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17684150/ddbefec8-631e-11e6-8a11-071ec5937c82.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17684154/eb55008c-631e-11e6-9933-0b78b4902801.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17684161/f4e7d0ca-631e-11e6-9c05-5c3741f69241.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17684169/0062fd08-631f-11e6-9a5b-90b72f14ca0b.png)

**Comment by kilt46** [comment]
Lots of inaccuracies
![image](https://user-images.githubusercontent.com/14023167/34237779-1b09896e-e5c4-11e7-8ab7-42444300ff53.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34641411-63e54238-f2c9-11e7-8ce9-3b91e2916df6.png)

**Comment by kilt46** [comment]
Taxisway line up
![image](https://user-images.githubusercontent.com/14023167/34641546-8978ae7a-f2cb-11e7-9331-c4ec8c402082.png)
