### ISSUE TITLE
ESOH

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#965]
Redone and sent in for approval

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17195202/21908218-5422-11e6-9612-495069915281.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17264421/6cb3a898-55ac-11e6-8171-5237dc3db650.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17450991/1fa0eb42-5b29-11e6-9bf6-92197e76dde2.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17450996/27e5f6c6-5b29-11e6-9770-d83ab7d00ed8.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33527574-bdec63e0-d818-11e7-86d7-d4b5a2cb0c96.png)
