### ISSUE TITLE
ENVA-Trondheim Vaernes Airport-NORD-TRONDELAG-NORWAY

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Airports#966]
Thought it was time to pick up on something bigger.
Redoing Trondheim - Vaernes Airport.

**Comment by bavAVIA** [comment]
Can someone please unassign me. Can't do the airport, no satellite imagery available.
The original X-Plane file also looks quite finished already

**Comment by chrislunde** [comment]
I can continue on ENVA.

**Comment by TristinWoolf** [comment]
@chrislunde I will adding you to the airport on this issue. :)

**Comment by MajorTomMueller** [comment]
Hi there, please assign me.

**Comment by MajorTomMueller** [comment]
apt.dat send to ape@ for aceptance

**Comment by moritzbabl** [comment]
added

**Comment by MajorTomMueller** [comment]
![enva-overview](https://user-images.githubusercontent.com/26853210/28629226-247d7a7a-7227-11e7-9836-ce6b209ac254.jpeg)

**Comment by MajorTomMueller** [comment]
- Boundary fix
- Buildings removed
- Hangar Floor added

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/46383059-fd6b3380-c673-11e8-8a00-27af2d4a3ebd.png)
