### ISSUE TITLE
ESKK

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#967]
Redoing this one

**Comment by PaulNielsen** [comment]
Sent for approval

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17195438/5585d676-5423-11e6-9975-c6fedd971fb7.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17450831/2ffb85fc-5b28-11e6-8898-c0a217728137.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17450841/3c182732-5b28-11e6-9707-340c2d117316.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33529785-f5226040-d83a-11e7-9ef3-3d0e6b3e46d1.png)
