### ISSUE TITLE
EGKB-Biggin Hill Airport-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#968]
Will redo this one

**Comment by PaulNielsen** [comment]
Sorry, when I searched for it. Nothing showed up, but I noticed 5 seconds after my internet went out, so that's probably why. Sorry.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17251917/2e2f309c-5570-11e6-85a2-e7fa51189d04.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17424759/b23171fe-5a8c-11e6-8b9a-971d9c3787a5.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17424781/d72849c4-5a8c-11e6-863b-b4e194e245ee.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17424792/e551bbd4-5a8c-11e6-8292-e34bb94ddde7.png)

**Comment by ItsW1ll** [comment]
Runway 11/19 has been permanently withdrawn from use see http://www.nats-uk.ead-it.com/aip/current/amend28/EG_Amdt_A_2017_08_en.pdf page 287

**Comment by ItsW1ll** [comment]
File has bee committed, can we close this?

**Comment by moritzbabl** [comment]
Well, the issue is already closed

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/32755111-5e88ed3a-c899-11e7-92e3-72cbbbe48573.png)

**Comment by ItsW1ll** [comment]
Google earth released new imagery, so will be adding necessary changes to the airport layout

**Comment by ItsW1ll** [comment]
Removed in a9782f5

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/51801298-78e38880-2201-11e9-928b-c19437b93a01.png)
