### ISSUE TITLE
ESNO

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#969]
Will redo this one

**Comment by PaulNielsen** [comment]
Sent in for approval! :)

**Comment by henrikbg** [comment]
Approved.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17232632/104c0220-54ef-11e6-8fe9-c1228a76d1b2.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17424587/1911a0ee-5a8b-11e6-8f55-e5d8f3b12ece.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17424590/26611a36-5a8b-11e6-902b-c4b021e7f3e7.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33529338-42e1e108-d835-11e7-8c89-30e4a5c32ea1.png)
