### ISSUE TITLE
ESNU

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#970]
Re-doing this one

**Comment by PaulNielsen** [comment]
Sent in for approval

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17262438/ef14ba04-55a0-11e6-96cf-253c0a98c427.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17262610/015e3748-55a2-11e6-8506-001543e4efac.png)

**Comment by samuelandersson** [comment]
Made two small changes. See attached pics.

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/24d0e4f7dc89e52e34b08525b1c597c9a33ec7b9)

![skarmavbild 2016-07-30 kl 11 14 29](https://cloud.githubusercontent.com/assets/15381853/17269386/030db082-5647-11e6-9eb3-cd49307965a6.png) 

The other change was literally just another taxiway that I removed the edge lighting from.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17424462/b3b10682-5a89-11e6-8819-85fabbf633b6.png)
CARGO
![image](https://cloud.githubusercontent.com/assets/14023167/17424468/c02d308e-5a89-11e6-8e31-9c174bac8bb7.png)

TERMINAL
![image](https://cloud.githubusercontent.com/assets/14023167/17424476/ca77b03c-5a89-11e6-959d-77dfb10200d3.png)
GA
![image](https://cloud.githubusercontent.com/assets/14023167/17424483/d50c5da4-5a89-11e6-9682-630e9ef3f1c9.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/33529697-1a83e5c6-d83a-11e7-88e2-91c00b23c0be.png)
