### ISSUE TITLE
LD57

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Airports#971]
Has been redone.

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/55cc184d1ab5916ab6768c9cd14870810da261fe)

**Comment by kilt46** [comment]
NO CHART

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17424199/358e9e1a-5a87-11e6-8b60-2358f439b494.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34628788-496ab616-f22b-11e7-88c5-c57792dcc9c5.png)
