### ISSUE TITLE
LDDP

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Airports#972]
Changed state to closed.

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/690f075b75538d7ad246ad7a86cf4c2f2268999b)

**Comment by kilt46** [comment]
THIS HAS NOT BEEN REDONE!
![image](https://cloud.githubusercontent.com/assets/14023167/17232301/a8dd4f06-54ec-11e6-9e7f-7cfcf1e0b5c2.png)

**Comment by PaulNielsen** [comment]
Croatia has many closed airports. That dosen't even exist anymore. And this is one of them.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17245278/5b325c24-554b-11e6-921c-3f6e70e48ebb.png)
