### ISSUE TITLE
LDRI

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Airports#973]
Rijeka, Croatia.

Redoing.

**Comment by samuelandersson** [comment]
Done.

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/25c1afd8982fae59afbe5d72a80fd16a43c95831)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17232231/35fee4fe-54ec-11e6-8fd2-2f37e21782fb.png)
PLEASE ADD GATES AS PER CHART

**Comment by samuelandersson** [comment]
Gate name change done.

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/d5d96aa6f791a9877ceb5b47c35c44ddd2568617)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17245836/0bf5f6ae-554e-11e6-8aeb-f18a64dd6474.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17422352/bb9760c0-5a76-11e6-863c-1ec81e182420.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17422356/c4c22e0a-5a76-11e6-9c7c-894a9afa8695.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34323289-667201fc-e807-11e7-8fe4-05219faeb5a0.png)
