### ISSUE TITLE
LDOC

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Airports#974]
Osijek Cepin Zracna Luka.

Redoing.

**Comment by samuelandersson** [comment]
Done.

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/299fd7094eee0486ba73f780f2e48f8969cb1da5)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17232036/e8f18e56-54ea-11e6-809c-8a5b55fc4c57.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17421797/53fb32e2-5a72-11e6-8bbe-35173453b812.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17421798/5aed4702-5a72-11e6-9236-e9762197ef40.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17421804/6597df96-5a72-11e6-890d-3888e8cdd79e.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34323300-037e6e5e-e808-11e7-8b94-a75490678d6f.png)
