### ISSUE TITLE
LDOS

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Airports#975]
Osijek Klisa Zracna Luka, Croatia.

Redoing.

**Comment by samuelandersson** [comment]
Done.

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/ac9e2ffdbae433f02df1cc03aec402c660c8c11b)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17231808/b3436afa-54e9-11e6-8708-c7e48078c882.png)
PLEASE NUMBER GATES AS PER ATTACHED CHART

**Comment by samuelandersson** [comment]
Thanks Kilt, could not find chart. Will fix by tomorrow.

**Comment by samuelandersson** [comment]
Gate name change done.

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/11ad92e5f59ff3be5ee09180c578317e582bc9ae)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17246072/6714593a-554f-11e6-949f-596382bb399d.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17421645/20a91be4-5a71-11e6-97af-662e71c2f2ee.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17421649/2895a214-5a71-11e6-8ae8-ed2be42589f2.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34323281-1cc9da98-e807-11e7-97df-bea91c03cac0.png)
