### ISSUE TITLE
LDRG

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Airports#976]
Redoing

**Comment by samuelandersson** [comment]
Done.

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/3dee52b802dc62bf089fc409532bc66f16cbbef1)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17231570/631a3424-54e8-11e6-9558-d9f29d27e299.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17421537/1c85c7c0-5a70-11e6-9646-259d3413c7c4.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17421541/235f8284-5a70-11e6-8f2e-2a69be1a8e3e.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34323297-ce291c7c-e807-11e7-9bea-ab4e542ed587.png)
