### ISSUE TITLE
LDVA

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Airports#977]
Redoing

**Comment by samuelandersson** [comment]
Done.

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/21d36b4d9ab665e51f6e15e0cc99fb3cef95f911)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17245599/ceec8a3a-554c-11e6-8703-17f420b7a6bf.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17421454/767d33d6-5a6f-11e6-8e9c-03d9b8a8371d.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17421457/7e82ce38-5a6f-11e6-9cd7-602a38073a04.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34323308-2bb43548-e808-11e7-9ede-6e7ba52f4519.png)
