### ISSUE TITLE
LDZA-Zagreb Airport-GRAD ZAGREB-CROATIA

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#978]
Will redo

**Comment by PaulNielsen** [comment]
Sent in for approval. Sorry Kilt if the parking stands are a bit off. The charts where very weird with some positions having a A after them.

**Comment by PaulNielsen** [comment]
Still no one to check this one out?

**Comment by dushyants19** [comment]
As you know, the airport has an issue with alignment. We are looking into it. Please be patient

**Comment by PaulNielsen** [comment]
What still? That's really weird, as both time I have sent it in. It has been perfectly aligned. I promise.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17642879/4c91f48a-611d-11e6-88da-9cf87451389a.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17642880/583276e8-611d-11e6-88f4-1d63d2a60a9a.png)

**Comment by moritzbabl** [comment]
146th airport done

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/40876140-b3bdff3c-663e-11e8-864e-32dcee62d210.png)
