### ISSUE TITLE
EDCG

### ISSUE THREAD

**Issue by KarlLuebs** [InfiniteFlightAirportEditing/Airports#979]
Redoing this small airport.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17642723/e2a3421e-6116-11e6-9357-4ccbde786c41.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17642725/f587622a-6116-11e6-98b3-768b2b38d8b4.png)
