### ISSUE TITLE
LGML

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Airports#981]
Working on this one.

**Comment by samuelandersson** [comment]
Done.

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/2b6272b591ce68bf88ddcb9fb002558f2893c303)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17276901/7cb63576-56fb-11e6-8c57-2170d00c7bd1.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17421332/a48e215a-5a6e-11e6-8618-a2834e65b1f6.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34396063-08251f58-eb2c-11e7-8315-4fa4c5a10dae.png)
