### ISSUE TITLE
LGKO

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#982]
Being redone

**Comment by PaulNielsen** [comment]
Sent in for review!

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17352167/0464d1bc-58fa-11e6-8e13-c9bae7a619dc.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17384855/705b4b9e-59a4-11e6-8148-4111286ad4a2.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34390524-e30dec66-eb05-11e7-8591-7ea282ae1301.png)
