### ISSUE TITLE
EGCN-Doncaster Sheffield Airport-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Airports#983]

**Comment by TristinWoolf** [comment]
I'm going to assume that @liamkirky is doing this airport and remove the Suggestion label.

**Comment by Will171** [comment]
Claimed :)

**Comment by Will171** [comment]
Sent for review

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20778767/9e70b53e-b735-11e6-91f1-30f308591b8a.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/45270868-87eeb780-b467-11e8-8d39-07142df7ad7c.png)
