### ISSUE TITLE
LGMT

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#984]
Being redone

**Comment by PaulNielsen** [comment]
Sent in for review

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17350242/8501a4ea-58ea-11e6-8503-69f50a68f573.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17383932/56d3f988-599e-11e6-9e55-3b651b254677.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17383939/5eca165e-599e-11e6-959c-7dcd40a99b3c.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17384706/942d97d0-59a3-11e6-90a1-8809bcfa0378.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34396074-353906d0-eb2c-11e7-9fd3-d7e3e5379c05.png)
