### ISSUE TITLE
LGNX

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Airports#985]
Redid this one.

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/6c8f8b6252b8d518af13127d2193dc765b853dbb)

**Comment by kilt46** [comment]
A FEW LINES MISSING
![image](https://cloud.githubusercontent.com/assets/14023167/17276848/13f4041a-56fa-11e6-9c98-06032ca87259.png)

**Comment by PaulNielsen** [comment]
Fixing!

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18494760/fd619c88-79dd-11e6-9f77-67b76eebcbf3.png)
