### ISSUE TITLE
LTCG-Trabzon Airport-TRABZON-TURKEY

### ISSUE THREAD

**Issue by turkish1941** [InfiniteFlightAirportEditing/Airports#986]
will make it

**Comment by turkish1941** [comment]
email is gone

**Comment by kilt46** [comment]
FILE NOT LOADED TO REPO

**Comment by dushyants19** [comment]
my bad, fixed

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17420978/dee4647a-5a6b-11e6-88cf-b9f4bb5f3271.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17420983/e7956524-5a6b-11e6-9c26-38a05499d939.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34326559-84d57dae-e875-11e7-9271-c4ea57901306.png)

**Comment by MajorTomMueller** [comment]
spawn size needs to be reworked
buildings need to be removed

**Comment by jackyboy2578** [comment]
I'll do this

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/85909317-de64eb80-b7de-11ea-97ff-c019a84a440b.png)
