### ISSUE TITLE
LGMK-Mikonos Airport-NOTIO AIGAIO-GREECE

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Airports#987]
Has been redone.

[Commit](https://github.com/InfiniteFlightAirportEditing/Airports/commit/53b5b14c1a8e0a327a239c917a6acd024aea5d98)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17276834/a487c0d0-56f9-11e6-890e-c9faf4007bce.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17386897/624f7e16-59b4-11e6-9ca4-9f76f85b134b.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17386899/69578fb4-59b4-11e6-8bb4-3b9864c86abf.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34396050-d61762aa-eb2b-11e7-8c22-72486fcbbf7e.png)

**Comment by moritzbabl** [comment]
Missing basically all markings, could use a rework

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/75640110-92c87980-5c12-11ea-9bc3-01f1d802f2da.jpg)
