### ISSUE TITLE
RKPK-Busan/Gimhae International Airport-BUSAN-SOUTH KOREA

### ISSUE THREAD

**Issue by RiKowalSkipper** [InfiniteFlightAirportEditing/Airports#988]
Gimhae Intl Airport-South Korea
Finishing

**Comment by dushyants19** [comment]
Hi @RiKowalSkipper, are you in our slack? Send an email to airports@liveflightapp.com! :)

I have also invited you to the team, do accept it.

**Comment by RiKowalSkipper** [comment]
Thank you Dush!

**Comment by RiKowalSkipper** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17685722/4df40f8c-632c-11e6-9faf-fa935a81ea35.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17685727/5afbe77c-632c-11e6-9675-7167ce15f0ca.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17685730/6283c712-632c-11e6-92aa-6621fb76ab9e.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17685733/6aa1c778-632c-11e6-9e87-a69d21b52837.png)

**Comment by adrinerDP** [comment]
I think ATC callsigns are needed to be fixed

**Comment by brunocr98** [comment]
Ok, you can go ahead.

**Comment by Czechoslovaki** [comment]
Reworking this.
