### ISSUE TITLE
LTCC-Diyarbakir Airport-DIYARBAKIR-TURKEY

### ISSUE THREAD

**Issue by turkish1941** [InfiniteFlightAirportEditing/Airports#989]
will make it

**Comment by dushyants19** [comment]
hows this going @turkish1941

**Comment by turkish1941** [comment]
@dushyants19 I have been really busy with school so I kinda forgot about it. If you want to make it, feel free to do so....  otherwise I'll finish it within one month.

**Comment by dushyants19** [comment]
Take your time :)

**Comment by dushyants19** [comment]
@turkish1941 are you done with this?

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/36936438-309ebdea-1ecb-11e8-8ab6-5096b4ad8873.png)
