### ISSUE TITLE
LSMD-Dubendorf Airport-ZURICH-SWITZERLAND

### ISSUE THREAD

**Issue by RiKowalSkipper** [InfiniteFlightAirportEditing/Airports#990]
Recycled

**Comment by RiKowalSkipper** [comment]
Done

**Comment by TristinWoolf** [comment]
Has this one been approved, @dushyants19? I don't see it in the repo.

**Comment by dushyants19** [comment]
Wasn't approved

**Comment by dushyants19** [comment]
Don't add waiting approval labels 11 days after he said it. I would've rejected it :) @TristinWoolf

**Comment by dushyants19** [comment]
@RiKowalSkipper any progress?

**Comment by moritzbabl** [comment]
done

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/35472030-4df3a018-032d-11e8-800b-c8e32d59c994.png)
