### ISSUE TITLE
RKJY

### ISSUE THREAD

**Issue by RiKowalSkipper** [InfiniteFlightAirportEditing/Airports#991]
Yeosu Airport-South Korea
Finishing

**Comment by RiKowalSkipper** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17642805/0a74320a-611a-11e6-8f98-0dd9bd3195cd.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17642806/10e8a724-611a-11e6-9ad8-3724f16b6c25.png)
