### ISSUE TITLE
ULLI-Sankt-Peterburg Pulkovo Airport-SANKT PETERBURG-RUSSIA

### ISSUE THREAD

**Issue by tsarkov90** [InfiniteFlightAirportEditing/Airports#992]
St. Petersburg / Pulkovo Intl Airport. Hub for airlines of Aeroflot group . Two runways - 12401 and 11000 ft.

**Comment by dushyants19** [comment]
b44faa03fa1dbae0188b191419701277e78e99e1

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18855196/93376dea-8416-11e6-9fbe-65af2638452e.png)

**Comment by kilt46** [comment]
TERMINAL 1
![image](https://cloud.githubusercontent.com/assets/14023167/18855208/aaa807b4-8416-11e6-8dc8-ab65014444ab.png)

**Comment by kilt46** [comment]
TERMINAL 2
![image](https://cloud.githubusercontent.com/assets/14023167/18855216/b7aeb20a-8416-11e6-83c6-9f3ee4182e92.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/44005636-0fe65d06-9e3c-11e8-981e-8756e86810ec.png)

**Comment by brennanhackard** [comment]
@tsarkov90 will be updating the north apron and aligning the airport with new imagery.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/108595727-165d0800-7347-11eb-8865-c0fc16086e73.png)
