### ISSUE TITLE
LHFM -  Fertőszentmiklós Airport - Fertőszentmiklós - Fertőd - Hungary

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#993]
Fertőszentmiklós Airport

**Comment by IFAEpat** [comment]
Done

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17401646/5a2b87f6-5a14-11e6-8f6e-99ea15b8ff9d.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17401649/623b3c2a-5a14-11e6-8a70-030bdfa7cbcc.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34082663-f5d74620-e327-11e7-8f23-37946be2a22b.png)
