### ISSUE TITLE
LHFH - Farkashegy Airport - Budakeszi - Hungary

### ISSUE THREAD

**Issue by IFAEpat** [InfiniteFlightAirportEditing/Airports#994]
Farkashegy Airport

**Comment by IFAEpat** [comment]
Done

**Comment by IFAEpat** [comment]
and gated

**Comment by kilt46** [comment]
file missing

**Comment by IFAEpat** [comment]
fixed

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17454322/86f7ed86-5b56-11e6-95bd-3525e201f287.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/34081695-da3a6be2-e316-11e7-86f2-29aaabbb2c6c.png)
