### ISSUE TITLE
MPTO-Tocumen International Airport-PANAMA-PANAMA

### ISSUE THREAD

**Issue by KarlLuebs** [InfiniteFlightAirportEditing/Airports#996]
:tada::panama:Proudly done by @brunocr1050:panama::tada:

**Comment by KarlLuebs** [comment]
I can't do this airport anymore. I've tried to import and align the google earth scenery instead of the blurred wedbing image but I just can't do it. Someone else, more experienced can have this one instead.

**Comment by dushyants19** [comment]
Up for grabs :) 

Karl is unable to do these 2

**Comment by brunocr98** [comment]
I'll do this airport soon and I'm elaborating a project that will include all the airports in Panama.

**Comment by brunocr98** [comment]
I'll do this airport soon and I'm elaborating a project that will include all the airports in Panama. I'll keep you updated.

**Comment by brunocr98** [comment]
Finished and submited to airport@liveflightapp.com

**Comment by brunocr98** [comment]
Sent to airports@liveflightapp.com for approval.

**Comment by dushyants19** [comment]
Done in ec585287fdba4ba67dbbd7b99b0cea1d621a36b3

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19213054/074cc43c-8d27-11e6-9f90-f757e41edc4c.png)
![image](https://cloud.githubusercontent.com/assets/14023167/19213056/16f81a30-8d27-11e6-9417-03e9310c5acd.png)

**Comment by brunocr98** [comment]
Terminal 2 was added. Used the airport's master plan diagrams and charts.

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/62651873-58268900-b930-11e9-80c2-bd8521304c6b.jpg)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/112719618-c504e300-8ec7-11eb-879e-25412f448c83.png)
