### ISSUE TITLE
EGNS

### ISSUE THREAD

**Issue by Adam167** [InfiniteFlightAirportEditing/Airports#997]
I'm redoing this airport

**Comment by Adam167** [comment]
Sent for review

**Comment by lolo31r** [comment]
I´ve done it already
It was accepted

**Comment by Adam167** [comment]
Well I drew the taxi lines moved some of the hold lines as they weren't right added parking stands that should of been there. Moved the tower as it was in the wrong place and added the terminal buildings.
![screen shot 2016-08-09 at 12 03 59](https://cloud.githubusercontent.com/assets/20886638/17516823/96449bec-5e38-11e6-8dec-a604d4373a70.png)

**Comment by Adam167** [comment]
Sent for approval again

**Comment by Adam167** [comment]
Approved

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18308261/6b92f7ee-74b9-11e6-9b88-2b42c40749d5.png)
