### ISSUE TITLE
EYVI-Vilnius Airport-VILNIAUS-LITHUANIA

### ISSUE THREAD

**Issue by Ignas04** [InfiniteFlightAirportEditing/Airports#999]
Vilnius International airport

**Comment by Ignas04** [comment]
Sorry, I need an easier airport. Any recomendations on a small airport that needs to be done?

**Comment by Padi3-14** [comment]
I will take this!

**Comment by Padi3-14** [comment]
Wait, what needs to be done to it? It looks good

**Comment by dushyants19** [comment]
Everything probably.

**Comment by Padi3-14** [comment]
A complete redo? Ok, got it

**Comment by Padi3-14** [comment]
Can I be unassigned? I don't have the time to import scenery from google earth (on WEDbing, the airport is covered with clouds).

**Comment by TristinWoolf** [comment]
Up for grabs!

**Comment by moritzbabl** [comment]
Should be no problem now using SAS, I will redo Vilnius

**Comment by moritzbabl** [comment]
Sent for approval, an assignment would be nice after three days btw ^^

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21482158/ef6f5490-cb35-11e6-95a5-d7c176d37e32.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/72275548-e2c09200-360c-11ea-8698-42777643128f.jpg)
